Time series forecasting improved
nccr-itmo/FEDOT pull request #138
Opened 2020-08-12 14:52 UTC by nicl-nno

TBD

2020-08-12 14:52 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

















* In the file [`core/models/evaluation/stats_models_eval.py`](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/core/models/evaluation/stats_models_eval.py):

> [Line 35:30](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/core/models/evaluation/stats_models_eval.py#L35): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

















































* In the file [`test/models/test_transform.py`](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/test/models/test_transform.py):

> [Line 110:72](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/test/models/test_transform.py#L110): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace

* In the file [`test/models/test_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/test/models/test_tuning.py):

> [Line 66:1](https://github.com/nccr-itmo/FEDOT/blob/d9ffedea4298c3a745f589371955bb369bc917f7/test/models/test_tuning.py#L66): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2020-08-31 16:14 UTC, J3FALL requested changes

2020-08-31 16:14 UTC, J3FALL commented on core/models/model.py
> +        data_for_fit = _drop_data_with_nan(data)
Не хотелось бы поддерживать тенденцию добавлять предобработку на слое моделей.
Чем больше мы добавляем таких функций здесь, тем больше шансов, что их станет еще больше в дальнейшем.

Почему эта функция здесь появилась?

2020-08-31 16:14 UTC, J3FALL commented on core/models/model.py
> +            (data_type == DataTypesEnum.ts_lagged_3d or data_type == DataTypesEnum.ts_lagged_table):
data type in [DataTypesEnum.ts_lagged_3d, DataTypesEnum.ts_lagged_table]

2020-08-31 16:14 UTC, J3FALL commented on core/models/model.py
> +def _post_process_ts_prediction(prediction, task: Task, expected_length: int, data_type: DataTypesEnum):
Здесь, кстати, аннотация должна быть TsForecastingParams, а не Task.

2020-08-31 16:19 UTC, J3FALL commented
Изменений оказалось много, и я упустил один момент.
По схеме, которую ты нарисовал, мне показалось, что вроде как достаточно в самом начале "нарезать" входной временной ряд в табличный вид (в соответствии с размерами окон), потом многократно сделать fit/predict (сохраняя результаты), а потом грамотно объединить множество прогнозов в один.
Но в коде я немного потерялся и не увидел однозначно кода, который это делает. Сориентируй меня, пожалуйста, либо я неправильно понял логику, либо в какую функцию мне надо смотреть.

2020-08-31 16:32 UTC, nicl-nno commented
> Изменений оказалось много, и я упустил один момент.
> По схеме, которую ты нарисовал, мне показалось, что вроде как достаточно в самом начале "нарезать" входной временной ряд в табличный вид (в соответствии с размерами окон), потом многократно сделать fit/predict (сохраняя результаты), а потом грамотно объединить множество прогнозов в один.
> Но в коде я немного потерялся и не увидел однозначно кода, который это делает. Сориентируй меня, пожалуйста, либо я неправильно понял логику, либо в какую функцию мне надо смотреть.

Нарезка формируется с помощью table_to_lagged в tranform.py и дальше это используется в обычном методе fit. В predict для каждого временного шага создается прогнозов с заблаговременностью до 0 до n.

А вот метод forecast реализует логику прогнозирования со скользящим окном - т.е. мы прогнозируем на n шагов вперед, потом используем эти n шагов как признаки и снова делаем прогноз на n шагов вперед.

Ну это если я верно понял вопрос.

2020-08-31 17:14 UTC, nicl-nno commented on core/composer/ts_chain.py
> +        if supplementary_data.task.task_type is not TaskTypesEnum.ts_forecasting:
Да, композирование тут применить можно, но тогда надо оборачивать все многочисленные методы Chain (чтобы композер мог работать с Chain, не зная её тип, например) - а это как-то громоздко. Или можно в питоне это как-то более аккуратно сделать?

Т.е. действительно теряется универсальность всех методов Chain, но с другой стороны - она нигде и не заявлялась. Существущие методы Chain же не переопределяются.

2020-11-02 18:37 UTC, nicl-nno commented on core/models/data.py
> +    def subset(self, start: int, end: int):
Добавил [проверку](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-1cec7586536104051430e71f3e576be250af4fe880eb0308b9db152ceedc8740R102-R103)

2020-11-02 18:37 UTC, nicl-nno commented on core/models/data.py
> +
Извелёк и перенес в algorithms/time_series

2020-11-02 18:37 UTC, nicl-nno commented on core/composer/ts_chain.py
> +
[Указал в docstring](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-71f96438f7cd714be2ebb1a0e19bf2fbb5756af4ac4ce4cfee25ee5378cecaeaR28-R32).

2020-11-02 18:37 UTC, nicl-nno commented on core/composer/ts_chain.py
> +        supplementary_data.task.task_params.make_future_prediction = True
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-71f96438f7cd714be2ebb1a0e19bf2fbb5756af4ac4ce4cfee25ee5378cecaeaR28-R32).

2020-11-02 18:37 UTC, nicl-nno commented on core/composer/ts_chain.py
> +        supplementary_data = copy(supplementary_data)
[Описал](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-71f96438f7cd714be2ebb1a0e19bf2fbb5756af4ac4ce4cfee25ee5378cecaeaR12-R20)

2020-11-02 18:37 UTC, nicl-nno commented on core/models/evaluation/data_evaluation.py
> +    if predict_data.features.shape[-1] % number_of_sources_to_sum != 0:
Выпилил пока вообще - пусть суммирование делается через линейную регрессию.

2020-11-02 18:37 UTC, nicl-nno commented on core/models/model.py
> +            (data_type == DataTypesEnum.ts_lagged_3d or data_type == DataTypesEnum.ts_lagged_table):
Убрал DataTypesEnum.ts_lagged_3d вообще

2020-11-02 18:37 UTC, nicl-nno commented on core/models/model.py
> +def _post_process_ts_prediction(prediction, task: Task, expected_length: int, data_type: DataTypesEnum):
Поменял интерфейс.

2020-11-02 18:38 UTC, nicl-nno commented on core/models/data.py
> +        raise NotImplementedError('Dimensionality not supported')
1. Убрал 3D-вариант.
2. [Изменил](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-94009b28b013ee0ed27fb58518b3f86a238ab504c997166ebe6e9eac6ae7f30bR26-R31)
3. Добавил [тест](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-2403ef0343280bf0f47652a7ed4c23be03116788968ce66ecc0e0e60e086d64eR8-R24)

2020-11-02 18:39 UTC, nicl-nno commented on core/models/data.py
> +def clean_nans_in_data(data: InputData, array_with_nans: np.ndarray):
Изменил и [перенес](https://github.com/nccr-itmo/FEDOT/pull/138/files#diff-94009b28b013ee0ed27fb58518b3f86a238ab504c997166ebe6e9eac6ae7f30bR26-R31).

2020-11-03 15:16 UTC, J3FALL commented on core/models/data.py
> +    def subset(self, start: int, end: int):
Добавь, плз, тест на эту функцию: корректный и с исключением.

2020-11-03 16:19 UTC, J3FALL requested changes

2020-11-03 16:19 UTC, J3FALL commented on core/models/data.py
> +        features = ImputationStrategy().fit(features).apply(features)
Хм, а из-за этого падал какой-то код?
Просто по умолчанию, ImputationStrategy заполняет nan-ы средними значениями, и это может привести к неожиданным багам.

2020-11-03 16:19 UTC, J3FALL commented on core/models/data.py
> +    def subset(self, start: int, end: int):
Добавь тест на эту функцию, плз: корректный и с эксепшеном.
Кажется, у нас его нет.

2020-11-03 16:19 UTC, J3FALL commented on core/models/model.py
> +        if np.array([np.isnan(_) for _ in prediction]).any():
А обычный оператор any не работает здесь?

2020-11-03 16:19 UTC, J3FALL commented on core/repository/model_types_repository.py
> +def _set_repo_to_default_sate():
Думаю, здесь предполагалось "state"

2020-11-03 16:54 UTC, nicl-nno commented on core/algorithms/time_series/lagged_features.py
> +        }
data_to_clean в цикле меняется, поэтому тут как нужно, чтобы каждую итерацию словарь пересоздавался с новым data_to_clean  - т.к. критерии очистки применяются последовательно.

2020-11-03 17:01 UTC, nicl-nno commented on core/algorithms/time_series/lagged_features.py
> +                raise NotImplementedError('Dimensionality not supported')
Пока единственное что придумал - везде работать только с 2D-массивами, где вторая размерность минимум 1. Ну а вектора приводить к такому же виду.

Но пока давай действительно вынесем на след. итерацию.

2020-11-03 19:17 UTC, nicl-nno commented on core/models/data.py
> +        features = ImputationStrategy().fit(features).apply(features)
Сейчас у нас не предусмотрено, чтобы в модели попадали данные с пропусками. 
Раньше делалось так же, но заполнение было встроено в Scaling.

Явно нужен более умный подход, но это выглядит отдельной задачей.

2020-11-03 20:00 UTC, nicl-nno commented on core/algorithms/time_series/scale.py
> +    if predict_data.features is not None and not np.array_equal(predict_data.target, predict_data.features):
[Done](https://github.com/nccr-itmo/FEDOT/pull/138/commits/5d6bf1da1569d307b321d86926b181529b9c3e57#diff-4941f9c2b4ab99830977edbc557328753f294aa31c04e51977cf3ca00f647672R34-R39)

2020-11-03 20:00 UTC, nicl-nno commented on core/models/model.py
> +        if np.array([np.isnan(_) for _ in prediction]).any():
Тесты [добавил](https://github.com/nccr-itmo/FEDOT/pull/138/commits/5d6bf1da1569d307b321d86926b181529b9c3e57#diff-08fdb2271d6423cad0834d6db03b135b4995971ebcb743ac6ebae355c5fb26eeR24-R41).

Обычный any здесь выкидывает ошибку вида "ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()"

2020-11-03 20:00 UTC, nicl-nno commented on core/repository/model_types_repository.py
> +def _set_repo_to_default_sate():
Это вообще дубликат, удалил.

2020-11-03 20:01 UTC, nicl-nno commented on core/algorithms/time_series/scale.py
> +        period = round(len(target) / 2)
[Done](https://github.com/nccr-itmo/FEDOT/pull/138/commits/5d6bf1da1569d307b321d86926b181529b9c3e57#diff-4941f9c2b4ab99830977edbc557328753f294aa31c04e51977cf3ca00f647672R27-R31).

Тут возможно специфика используемой функции - мне кажется, что это требование с 2-мя периодами какое-то изобыточное, если период уже заранее известен. Но вообще да, надо будет поискать лучший способ.

2020-11-03 20:01 UTC, nicl-nno commented on core/algorithms/time_series/lagged_features.py
> +        }
См. выше.

2020-11-03 20:01 UTC, nicl-nno commented on core/algorithms/time_series/lagged_features.py
> +                data.features = data.features[0:len(data.target), :]
[Упростил](https://github.com/nccr-itmo/FEDOT/pull/138/commits/5d6bf1da1569d307b321d86926b181529b9c3e57#diff-94009b28b013ee0ed27fb58518b3f86a238ab504c997166ebe6e9eac6ae7f30bR13-R14).

2020-11-03 20:03 UTC, nicl-nno commented on core/models/data.py
> +    def subset(self, start: int, end: int):
[Done](https://github.com/nccr-itmo/FEDOT/pull/138/commits/5d6bf1da1569d307b321d86926b181529b9c3e57#diff-08fdb2271d6423cad0834d6db03b135b4995971ebcb743ac6ebae355c5fb26eeR24-R41)

2020-11-11 09:44 UTC, J3FALL commented on core/algorithms/time_series/lagged_features.py
> +        }
Сорян, не вник сразу.

2020-11-11 09:50 UTC, J3FALL commented on core/models/data.py
> +        features = ImputationStrategy().fit(features).apply(features)
Хорошо, заведу под это отдельную задачу.

2020-11-11 09:53 UTC, J3FALL commented on core/algorithms/time_series/lagged_features.py
> +                raise NotImplementedError('Dimensionality not supported')
Окай

2020-11-11 12:42 UTC, J3FALL approved these changes

2020-11-11 12:58 UTC, merged