first logging version
nccr-itmo/FEDOT pull request #142
Opened 2020-08-19 14:10 UTC by BarabanovaIrina

- Восстановлен класс обертка Logger для стандартной библиотеки logging в core/log.py
- Возможность конфигурации из json-файла.
- Все записи производятся в один log.log файл, который создается в core.

На данный момент в каждом модуле создается отдельный module_logger = Logger(__name__)
Примеры обработки ошибок см в tuners.py через конструкции try/except.

2020-08-20 13:33 UTC, J3FALL requested changes

2020-08-20 13:33 UTC, J3FALL commented on core/log.py
> +        self.logger.addHandler(console_handler)
А есть возможность эти параметры тоже вынести в конфиг?
Выглядит так, что, как минимум, параметры formatter-а дублируются.

2020-08-20 13:33 UTC, J3FALL commented on core/log.py
> +            self._config()
Я правильно понимаю логику этой проверки? "Если указан некорректный путь до файла c конфигом/файла не существует, то используем дефолтный конфиг?

2020-08-20 13:33 UTC, J3FALL commented on core/models/evaluation/evaluation.py
> +            module_logger.error(f'Impossible to obtain SKlearn strategy for {model_type}')
А это почему так?
Base class для KeyError ведь Exception.

2020-08-20 13:33 UTC, J3FALL commented on core/models/tuning/tuners.py
> +            return None, None
Тот же вопрос.

2020-08-20 13:36 UTC, BarabanovaIrina commented on test/test_logger.py
> +    assert logger.logger.level == 20
Проверяется базовая настройка логгера при отсуствии config файла, конкретно метода _config класса Logger. 
Константа: это числовое представление уровня логгирования INFO.

2020-08-20 13:38 UTC, BarabanovaIrina commented on core/log.py
> +            self._config()
Да

2020-08-20 14:03 UTC, BarabanovaIrina commented on core/models/evaluation/evaluation.py
> +            module_logger.error(f'Impossible to obtain SKlearn strategy for {model_type}')
Ну тут можно либо ловить конкретную ошибку (типа KeyError, ValueError) и записывать в лог вот так через двойной except. Или оставлять только один except Exception и записывать в лог. 
В целом разницы нет, просто как я поняла logging работает только с Exception.

2020-08-20 14:04 UTC, BarabanovaIrina commented on core/models/tuning/tuners.py
> +            return None, None
см. выше

2020-08-20 14:11 UTC, BarabanovaIrina commented on core/log.py
> +        self.logger.addHandler(console_handler)
Все можно вынести в конфиг файл, этот метод просто был сделан изначально (ну или на случай, если конфиг файла нет)
Можно упростить этот кусок при помощи logging.basicConfig() и указать минимальные параметры (filename, level), но там нельзя сделать чтобы одновременно и в файл и в консоль.

2020-08-20 14:13 UTC, J3FALL commented on core/models/evaluation/evaluation.py
> +            module_logger.error(f'Impossible to obtain SKlearn strategy for {model_type}')
Я предлагаю сделать второй вариант: записывать сообщение в лог и вызывать эксепшен, как было раньше.
Иначе получается, будто сработает исключение, оно обработается в блоке except, запишется в лог, но при этом код не упадет (хотя должен).

2020-08-24 13:54 UTC, pep8speaks commented
Hello @BarabanovaIrina! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`core/models/model.py`](https://github.com/nccr-itmo/FEDOT/blob/e90625cf738f23df35fa8ef8b12e89966b8a245e/core/models/model.py):

> [Line 70:121](https://github.com/nccr-itmo/FEDOT/blob/e90625cf738f23df35fa8ef8b12e89966b8a245e/core/models/model.py#L70): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)

2020-08-24 13:58 UTC, BarabanovaIrina commented on test/test_logger.py
> +
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-59e3f189a1c7ab50b93fe8619ce10f93R41-R63)

2020-08-24 13:58 UTC, BarabanovaIrina commented on test/test_logger.py
> +def test_logger_setup_from_file(data_fixture, request):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-59e3f189a1c7ab50b93fe8619ce10f93R32)

2020-08-24 13:59 UTC, BarabanovaIrina commented on test/test_logger.py
> +def test_default_logger():
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-59e3f189a1c7ab50b93fe8619ce10f93R24-R25)

2020-08-24 14:00 UTC, BarabanovaIrina commented on core/models/tuning/tuners.py
> +            return None, None
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-c73e5c618382254fc5671a4d5e856c59L61-L65)

2020-08-24 14:00 UTC, BarabanovaIrina commented on core/models/evaluation/evaluation.py
> +            raise Exception
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-fbba522e2d8716cf74280ef8a01d3ddaL130-R134)

2020-08-24 14:01 UTC, BarabanovaIrina commented on core/log.py
> +    def _setup_logger_from_default(self):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/e90625cf738f23df35fa8ef8b12e89966b8a245e#diff-bc20f3f00206b15ad39dd72e87920d24L40-R40)

2020-08-24 14:02 UTC, BarabanovaIrina commented on core/log.py
> +        :param log_file:
Подумала, что когда вмержим ветку с документацией, тогда там и займусь этим, если я правильно поняла. Но описание ввела с прицелом на будущее.

2020-08-25 15:58 UTC, J3FALL commented on test/test_logger.py
> +def tear_down(logger, log_file):
Замени tear_down на release_log или что-то такое

2020-08-25 15:58 UTC, J3FALL commented on core/log.py
> +        self.logger = logging.getLogger(self.name)
Это ведь нужно, чтобы deepcopy работало?
Если да, то оставь какой-то поясняющий комментарий, ибо довольно не очевидная вещь.

2020-08-25 15:58 UTC, J3FALL commented on core/log.py
> +class Log:
Ты переименовала Logger на Log - это норм.
Но теперь тогда надо и в остальных местах поменять переменные logger на log.

2020-08-25 19:55 UTC, BarabanovaIrina commented on test/test_logger.py
> +def tear_down(logger, log_file):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/eff57e7762e010bd8f9c2fe12ac406ac64dcd145#diff-59e3f189a1c7ab50b93fe8619ce10f93L18-R18)

2020-08-25 19:55 UTC, BarabanovaIrina commented on core/log.py
> +        self.logger = logging.getLogger(self.name)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/142/commits/eff57e7762e010bd8f9c2fe12ac406ac64dcd145#diff-bc20f3f00206b15ad39dd72e87920d24R82-R97)

2020-08-25 19:59 UTC, BarabanovaIrina commented on core/log.py
> +class Log:
Исправлено везде. Оставлено только объект logger в Log классе, потому что от logging там получаем logger.

2020-08-26 11:21 UTC, BarabanovaIrina commented
Добавлен [пример](https://github.com/nccr-itmo/FEDOT/pull/142/commits/7bd1e2dded201f1c7e826e2e536775dcdb502cd8#diff-f764c27d947286d77f1c4c45781bb6e5) логирования цепочки

2020-08-27 10:26 UTC, J3FALL approved these changes

2020-08-27 11:08 UTC, merged