Implement export of the composite model structure to json #129
nccr-itmo/FEDOT pull request #144
Opened 2020-09-09 13:36 UTC by MAGLeb

Посмотреть в ту ли сторону двигаюсь. 
Полный ли объект JSON или его можно дополнить как-то? 
Чистота и качество кода?
Также я проходил рекурсивно, так как, насколько я понял, количество моделей небольшое. Если все же в теории их будет много, то думаю лучше переписать.

В планах:
- добавить обученную модель для тестирования парсинга JSON с полем model_id (название файла обученной модели)
- дописать участок кода для парсинга с полем model_id
- добавить еще тестов

Нужна помощь с ChainTemplate, не совсем понял как её тут задействовать.

2020-09-10 06:56 UTC, BarabanovaIrina requested changes

2020-09-10 06:56 UTC, BarabanovaIrina commented on utilities/synthetic/model_json_vice_versa.py
> +    return chain
Теперь в целом по идее. Сейчас сделано так что, что есть две функции, взаимодействующие с объектом класса. Нужно сделать из этого функционала класс типа JsonConvert(), но он должен работать не с объектом класс Chain напрямую, а с его шаблоном (тот самый ChainTemplate). 

Этот объект так же необходимо создать, и он должен иметь такие поля, по которым мы могли бы воссоздать Chain. Можно проследить логику работы этого [теста](https://github.com/nccr-itmo/FEDOT/blob/master/test/test_synthetic_chain.py#L30), чтобы понять каким образом и из чего может собраться цепочка (еще в [real_chain](https://github.com/nccr-itmo/FEDOT/blob/master/utilities/synthetic/chain_template.py#L198) наглядный пример сборки). Логика имеющегося скрипта [chain_template](https://github.com/nccr-itmo/FEDOT/blob/master/utilities/synthetic/chain_template.py#L198) в том, чтобы собирать цепочку по уровням. 

Таким образом Chain не должен взаимодействовать напрямую с JsonConvert, эти два объекта работать должны через ChainTemplate. JsonConvert не должен заниматься сборкой цепочки (это не его ответственность), он должен только сериализовать объект и десериализовать.

По сути задача сводится к формированию удобного объекта ChainTemplate, чтобы можно было удобно собрать цепочку из имеющихся полей и удобно (де)сериализовать его. 
Нынешний имеющийся функционал может пригодится для изъятия структуры цепочки, только при этом будет формироваться не словарь, а объект. 

Кроме того можно подумать, как использовать идею [ModelTemplate](https://github.com/nccr-itmo/FEDOT/blob/master/utilities/synthetic/chain_template.py#L22) внутри ChainTemplate, но это уже по ходу дела.

2020-09-17 21:17 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`utilities/synthetic/chain_template_new.py`](https://github.com/nccr-itmo/FEDOT/blob/a3dd1d4a2b6d286968d5f45ea2c28206908f7f01/utilities/synthetic/chain_template_new.py):

> [Line 71:121](https://github.com/nccr-itmo/FEDOT/blob/a3dd1d4a2b6d286968d5f45ea2c28206908f7f01/utilities/synthetic/chain_template_new.py#L71): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)
> [Line 110:1](https://github.com/nccr-itmo/FEDOT/blob/a3dd1d4a2b6d286968d5f45ea2c28206908f7f01/utilities/synthetic/chain_template_new.py#L110): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-09-18 11:35 UTC, BarabanovaIrina requested changes

2020-09-18 11:35 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +test_chain_convert_to_chain_template()
Тест не нужно явно вызывать, если это было написано с этой целью

2020-09-18 11:35 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +    def to_json(self):
Хорошо, только добавь еще экспорт в файл, чтобы соответственно и импорт можно было из файла сделать. И я бы назвала функцию export_to_json (и соответственно import_from_json)

2020-09-18 11:35 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +                        secondary_node.custom_params = DEFAULT_PARAMS_STUB
Тут ведь тоже можно избавиться от проверки и просто присваивать node_object['params']

2020-09-18 11:35 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +def transform_uniq_id_to_uuid4(expected, chain_template: ChainTemplate):
Понимаю, что делает эта функция, но не совсем понимаю, зачем она нужна?

2020-09-18 11:35 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +        self.total_model_types = {}
Это поле просто для информации о том, какие модели лежат?

2020-09-18 11:35 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +    def prepare_object(self):
Кажется, что название to_json вот тут подойдет.

2020-09-18 13:22 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +test_chain_convert_to_chain_template()
Оставил вызов, когда тестировал.

2020-09-18 13:24 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +                        secondary_node.custom_params = DEFAULT_PARAMS_STUB
Здесь был вопрос, если будут обязательно передавать в json string "default_params", думал возможны случаи если будут передавать None.

2020-09-18 13:26 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def transform_uniq_id_to_uuid4(expected, chain_template: ChainTemplate):
При создании model_templateв поле model_id записывается уникальное значение id. В JSON я указываю просто связи между моделями, так как те же самые id сгенерированные uuid4  не могу, потому что они зависят от времени и всегда уникальны. Поэтому я перевожу простые id из json в uuid4 id.

2020-09-18 13:27 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        self.total_model_types = {}
Подумал может быть интересным. Да, просто для информации какие типы моделей в цепочке.

2020-09-18 13:38 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +                        secondary_node.custom_params = DEFAULT_PARAMS_STUB
Хорошее замечание. Но его лучше обработать на этапе передачи параметров в модель. У Node в setter для custom_params можно добавить условие if params: self.model.params = params (в противном случае, он их не передаст и тогда там будут DEFAULT_PARAMS_STUB по умолчанию). Это в принципе там будет полезной проверкой.

2020-09-21 10:09 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +                        secondary_node.custom_params = DEFAULT_PARAMS_STUB
@BarabanovaIrina в setter ты имеешь в виду при инициализации объекта Model? 

Если да, то ниже привел кусок кода, который мог бы быть релевантным.

`
class Model:
    def __init__(self, model_type: str, log: Log = default_log(__name__), params: dict = None):
        self.model_type = model_type
        self._eval_strategy, self._data_preprocessing = None, None
        if params:
            self.params = params
        else:
            self.params = DEFAULT_PARAMS_STUB
        self.log = log
`

2020-09-21 10:22 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +                        secondary_node.custom_params = DEFAULT_PARAMS_STUB
Нет, я имела ввиду в объекте Node:
```
@custom_params.setter
    def custom_params(self, params):
        self.model.params = params
```

2020-09-21 10:24 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +def transform_uniq_id_to_uuid4(expected, chain_template: ChainTemplate):
Как мы уже обсудили в пятницу, вроде как uuid нам не нужны по факту, поэтому можно просто оставить простые id.

2020-09-23 17:32 UTC, BarabanovaIrina requested changes

2020-09-23 17:32 UTC, BarabanovaIrina commented on utilities/synthetic/chain_template_new.py
> +    def __init__(self, instance):
Название не совсем удачное, но оно тут с точки зрения архитектурного вопроса. И надо подумать. Потому что на проверке isinstance(Chain) - он отработает верно, а на проверке с object - не уверена, потому что все в питоне object (практически)) и тут может быть непредсказуемое поведение. Подумаем.

2020-09-23 17:32 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +    with open('test/data/fitted_chain_to_json_test_2.json', 'r') as json_file:
соответственно так же как описано выше

2020-09-23 17:32 UTC, BarabanovaIrina commented on core/composer/node.py
> +        else:
А можно тут оставить просто if без else? Возможно это незавершенный if statement это моветон, но ведь в противном случае параметры назначены не будут, а на уровне Model и так будет присвоен DEFAULT_PARAMS_STUB.

2020-09-26 05:48 UTC, MAGLeb commented on core/composer/node.py
> +        else:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/d76d113653e0211d626f26496e1ed725ac9708b5)

2020-09-26 05:49 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +    with open('test/data/fitted_chain_to_json_test_2.json', 'r') as json_file:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7552dada5111093608776aca2967923ac4386400)

2020-09-26 05:49 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def __init__(self, instance):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7552dada5111093608776aca2967923ac4386400

2020-09-26 05:49 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def create_static_chain_1() -> Chain:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7552dada5111093608776aca2967923ac4386400)

2020-09-26 05:49 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +    with open('test/data/chain_to_json_test_1.json', 'r') as json_file:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7552dada5111093608776aca2967923ac4386400)

2020-09-28 09:45 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +    with open('test/data/chain_to_json_test_1.json', 'r') as json_file:
Основной путь вынесли, но все таки лучше использовать os.path.join вместо конкатенации. Есть несколько обсуждений на этот счет(пр. [тут](https://stackoverflow.com/questions/13944387/why-use-os-path-join-over-string-concatenation) или [тут](https://stackoverflow.com/questions/16789714/differences-between-use-of-os-path-join-and-os-sep-concatenation/16789790)). На моей памяти были конфликты хотя бы с различным наклоном слеш ('\' или '/'). os.path.join помогает в таких тонкостях

2020-09-28 09:46 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +    with open('test/data/fitted_chain_to_json_test_2.json', 'r') as json_file:
см. выше

2020-10-14 15:59 UTC, J3FALL requested changes

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +from core.composer.node import PrimaryNode, SecondaryNode, Node
тут тоже импорты надо отформатировать.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/get_application_settings_path.py
> +DEFAULT_PATH = get_data_direction() / "FEDOT"
Вот эту константу я бы лучше обернул в функцию.
Импорт констант as-is, мне кажется, не очень хорошая практика.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +    def _chain_to_chain_template(self, chain):
Думаю, можно сократить название до "_chain_to_template" - по контексту, вроде, понятно, что там ChainTemplate.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def extract_chain_structure(node: Node, model_id: int):
Мне кажется, nested-функции некоторым образом усложняют навигацию по коду.
Мб просто эту функцию перенести на уровень скрипта?

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            nonlocal counter
Честно говоря, первый раз вижу такую штуку)
Мб просто переменные по-разному назвать, вроде мы тут не боремся за каждый 4 байта памяти?

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def extract_chain_structure(node: Node, model_id: int):
А, ну и можно в описании/названии функции упомянуть, что тут происходит DFS.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def extract_chain_structure(node: Node, model_id: int):
И тогда тест на эту функцию тоже будет не лишним, ибо внутри происходит не самая очевидная логика.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +    def __init__(self, node: Node = None, model_id: str = None, nodes_from: list = None, chain_id: str = None):
Добавь здесь перенос строки, а то слишком длинная запись получается.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +    def _model_to_model_template(self, node: Node, model_id: str, nodes_from: list, chain_id: str):
Здесь тоже можно сократить до "_model_to_template"

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        if node.cache.actual_cached_state:
Вот для этой проверки я бы выделил отдельную функцию с более говорящим названием, например: "node_is_fitted" или что-то такое. Иначе прост по контексту не очень понятно, при чем здесь актуальное состояние кэша узла.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            self.model_name = node.cache.actual_cached_state.model.__class__.__name__
Вот эту сложную конструкцию я бы тоже вынес в отдельную функцию, например: "extracted_model_name".
Потенциально, думаю, это место нужно будет рефакторить, поэтому отдельная функция напомнит о том, что эта проблема существует.
В общем, чтобы не забыть потом.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            self.fitted_model_path = os.path.join(DEFAULT_FITTED_MODELS_PATH, chain_id, 'model_'
Извлеки здесь переменную, и вместо 'model_' + str(self.model_id) + '.pkl' примени f-string.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def create_unique_chain_id(path_to_save: str):
Эту функцию тоже можно вынести на уровень скрипта.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            if len(last_file) >= 2:
Если я не ошибаюсь, то чтобы вытащить имя файла из всего file_path, достаточно сделать так:
`head, tail = os.path.split(path_to_save)`
и в tail будет имя файла.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            print(f"The chain saved in the path: {os.path.join(absolute_path, f'{self.unique_chain_id}.json')}")
Для этой сложной конструкции: "os.path.join(absolute_path, f'{self.unique_chain_id}.json')" можно извлечь отдельную переменную и использовать ее.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +                            key=lambda model: model['model_id'])
Вот тут тоже вполне можно извлечь переменные, чтобы упростить код.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +    def import_from_json(self, path: str):
В этой функции все nested-функции тоже стоит вытащить на уровень скрипта, для того, чтобы упростить понимание сути функции. 
В общем, по аналогии с тем, что выше.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            raise JsonFileInvalid(f"Required field 'model_id, model_type, params, nodes_from'")
Предлагаю добавить отдельную функцию типа "validate_json_model_template", в которой проверяется:
- Что присутствуют обязательные поля model_id, model_type и т.д.
- Нет каких-то левых полей (хотя это и опционально, на самом деле, можно не проверять)
- Выбрасывать исключение, что f"Required field: {field} is expected, but not found"

И сделать эту проверку вначале функции json_to_model_template.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        root_node = find_model_jsons_from_json_chain(json_object_chain['nodes'], [0])[0]
Вот эти магические константы [0] меня смущают. 
Лучше ввести под них объясняющую переменную.

2020-10-14 15:59 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def find_model_jsons_from_json_chain(json_chain, list_of_model_ids):
Думаю, название функции не очень удачное.
Судя по контексту, в ней извлекаются model_templat-ы из json-а, для которых указаны соответствующие id-шники (list_of_model_ids).
Если я не ошибся, то, думаю, можно упростить название функции на "extract_nodes_from_json_by_model_ids".
Ну и переменную list_of_model_ids можно сократить до "model_ids" - по аннотации типов можно будет и так понять, что это список.

2020-10-15 11:00 UTC, MAGLeb commented on core/log.log
> +2020-09-08 19:58:22,469 - core.models.model - ERROR - Can not find evaluation strategy because of No module named 'hyperopt'
Исправлено

2020-10-15 11:02 UTC, BarabanovaIrina commented on save_chain_to_json.md
> +#### How to save fitted models and interpreting the chain in JSON format
Только переконвертируй в .rst файл, и помести его в docs/source/fedot/utilities/name_of_your_file. При этом в docs/source/fedot/utilities.rst допиши строку utilities/name_of_your_file под utilities/synthetic.

Кроме того, в rst файлах заголовки подчеркиваются (знаками =, -,  ~). Сделай так, чтобы подчеркнутым остался только верхний заголовок. Остальные подзаголовки сделай bold (помести название в двойные звездочки)

2020-10-15 11:09 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +from cases.data.data_utils import get_scoring_case_data_paths
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/144/commits/13da122ed9f2ce6cffc7ec1a6602c1450a62696f#diff-d42e702d69e914394a4aa8b0080dc633083c13ac69405443e5833160d7dfea8eR6-R10)

2020-10-15 11:10 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +import json
Agree
Fixed

2020-10-15 11:11 UTC, BarabanovaIrina commented on test/test_json_vice_versa.py
> +def test_absolute_relative_paths():
а что проверятся этим тестом? Кажется, что ни впиши в этот тест, он всегда выполнится.

2020-10-15 11:17 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +    node_xgboost_second = SecondaryNode('xgboost')
@J3FALL 
Можно уменьшить, но не намного. Проверял как работают с глубиной рекурсивные функции. Важно было сделать сложную цепочку, в которой ноды являются родителями для нескольких нод, чтобы проверить обхожу ли всю цепочку и правильно ли обрабатываю повторяющие ноды. 
Мне кажется в тесте использовать сложный тест нормально.

2020-10-15 11:26 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def delete_models(chain):
Да, все верно, при тестировании, чтобы не засорялся локально диск удаляю обученные модели. Согласен.

[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/4ce76e03645df3a6cffc43f38b0a26ce15d35594#diff-7f68f47b346a0a1d8f530210eed62a0a1056a8791546406a6c06e24115f74b13L43-R54)

2020-10-15 11:38 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +                            key=lambda model: model['model_id'])
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/13b83b3a12f9e47729601b421534985f1b183fbf#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL91-R100)

2020-10-15 11:48 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def import_from_json(self, path: str):
@J3FALL понял что нужно сделать, но не совсем понимаю правильно ли. Меня смушает то, что вложенные функции не универсальны, они уместны только в контексте родительской функции. 

Также не совсем понял фразу "по алогии с тем что выше", что ты имеешь ввиду?

2020-10-15 11:57 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            raise JsonFileInvalid(f"Required field 'model_id, model_type, params, nodes_from'")
Нравится, только появится static метод.

[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/abdd593d805e6a0e709c6c1b1f2792a5e30cc92b#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL213-R247)

2020-10-15 12:17 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        root_node = find_model_jsons_from_json_chain(json_object_chain['nodes'], [0])[0]
Исправлено

2020-10-15 12:17 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        def find_model_jsons_from_json_chain(json_chain, list_of_model_ids):
Решил вообще удалить эту функцию, код сократился и стал более читабельным.

[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/144/commits/310474eff0ed04e93a3fda379dbcb72c00a8fb71)

2020-10-15 16:24 UTC, J3FALL commented on test/test_json_vice_versa.py
> +    node_xgboost_second = SecondaryNode('xgboost')
Окай, в целом, норм, оставляем так.

2020-10-16 10:42 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        root_node = find_model_jsons_from_json_chain(json_object_chain['nodes'], [0])[0]
Только теперь тесты падают, кажется, из-за этого изменения.
Проверь, плз.

2020-10-16 10:44 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        def find_model_jsons_from_json_chain(json_chain, list_of_model_ids):
Тут что-то сломалось)

2020-10-16 10:44 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +        root_node = find_model_jsons_from_json_chain(json_object_chain['nodes'], [0])[0]
UPD: кажется, проблема в коде, которые ниже: https://github.com/nccr-itmo/FEDOT/pull/144#discussion_r506281918

2020-10-16 10:56 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            raise JsonFileInvalid(f"Required field 'model_id, model_type, params, nodes_from'")
Слушай, мне кажется, не нужно делать этот метод статическим.
Не вижу ничего плохого в том, что эта функция: "_validate_json_model_template" будет на уровне скрипта "chain_template_new.py" и не будет принадлежать классу ModelTemplate.
Благо, python это позволяет - создавать методы без обязательной привязки к конкретному классу.
И у нас в проекте достаточно [подобных ](https://github.com/nccr-itmo/FEDOT/blob/831062bc6d4109de67fe286c151b57c534e05ef6/core/composer/node.py#L354) примеров.

К слову, персонально я противник статических методов и в большинстве случаев, когда я их вижу - это признаки плохого ооп-дизайна. И это не я первый придумал - у этой идеи есть сторонники ([например](https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html))  :)

2020-10-16 10:58 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +    def import_from_json(self, path: str):
Я имею в виду что-то [такое](https://github.com/nccr-itmo/FEDOT/blob/831062bc6d4109de67fe286c151b57c534e05ef6/core/composer/node.py#L354). Метод находится на уровне скрипта, где реализован этот класс, при этом, по умолчанию, он не будет виден при импорте этого скрипта.

2020-10-16 12:41 UTC, J3FALL commented on utilities/synthetic/get_application_settings_path.py
> +def get_data_direction() -> pathlib.Path:
UPD: Ира в этом PR https://github.com/nccr-itmo/FEDOT/pull/162 реализовала аналогичную штуку, думаю, надо совместить решения. 
Мне кажется, можно ограничиться функцией get_data_direction, заменить ее, например, на: "default_fedot_data_dir" и изменить ее так, чтобы она возвращала директорию:
```
home_dir = pathlib.Path.home()
fedot_dir = os.path.join(home_dir, 'fedot')

return fedot_dir
```

2020-10-19 16:38 UTC, J3FALL commented on utilities/synthetic/get_application_settings_path.py
> +def get_data_direction() -> pathlib.Path:
UPD: эта функция уже реализована и смержена в мастер, см. [тут](https://github.com/nccr-itmo/FEDOT/blob/d43d9db6c1fbf83f67d28c66e3f8df8c3e1c7cba/core/utils.py#L15).
Так что думаю, этот скрипт get_application_settings_path.py можно удалить и воспользоваться функцией default_fedot_data_dir.

2020-10-20 06:14 UTC, MAGLeb commented on test/data/test_custom_json_template.json
> +        },
Да, делал сортировку по model_id для того, чтого тесты сходились. Но теперь такая проверка не нужна, а сортировка осталась. 
[Вернул](https://github.com/nccr-itmo/FEDOT/pull/144/commits/4f823f7daedeb4603b138fae91971688ba2d0586#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL91-R99) в логичный порядок ноды, теперь JSON генерируется от PrimaryNodes к родителям.

2020-10-20 06:20 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def test_custom_json_object_to_chain():
Почему то у тебя не было тестового JSON. Он должен был быть уже в ветке. Тестирование на пользовательское конвертирование из JSON в цепочку. Проверь сейчас, не должно упасть.

2020-10-20 06:34 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def test_chain_to_json_correctly():
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/195ecc9580e1c595cc3be7f8259d6bbb00b53417#)

2020-10-20 06:38 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def test_one_chain_object_save_load_vice_versa():
Немного его [переписал](https://github.com/nccr-itmo/FEDOT/pull/144/commits/195ecc9580e1c595cc3be7f8259d6bbb00b53417#diff-7f68f47b346a0a1d8f530210eed62a0a1056a8791546406a6c06e24115f74b13L193-R207), проверяю можно ли в один и тот же объект загружать новую модель. То есть применить последовательность комманд к объекту chain:
- load_chain(path_first)
- load_chain(path_second)
- load_chain(path_third)
и при этом последняя команда перепишет объект chain правильно.

2020-10-20 06:45 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +    assert True
Да, проверка методов загрузки или сохранения цепочек для абсолютных и относительных путей, если что-то пойдет не так, вылетит исключение.

Не уверен что это правильно, как ты уже подметил, в конце просто assert == True, по контексту непонятно, что проверяет тест. Но по другому мне не очень нравится решение, по крайней мере то, которое я вижу. По путям проходить и проверять создался или удалился ли там файл.

2020-10-20 06:59 UTC, MAGLeb commented on utilities/synthetic/custom_errors.py
> +    pass
Хорошо, буду придерживаться этой практики.

[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/1260ab58554c8803314073be7aa6f2429747be43)

2020-10-20 07:43 UTC, MAGLeb commented on utilities/synthetic/get_application_settings_path.py
> +def get_data_direction() -> pathlib.Path:
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/c33eb3cd841f8ac76f26886243e4f6697f23d37c)

2020-10-20 07:49 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +from core.composer.node import PrimaryNode, SecondaryNode, Node
FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/5b06a71ea49d68fb8235968f2e3a315f02d97c13)

2020-10-20 07:52 UTC, MAGLeb commented on utilities/synthetic/get_application_settings_path.py
> +DEFAULT_PATH = get_data_direction() / "FEDOT"
Файл [удалил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/c33eb3cd841f8ac76f26886243e4f6697f23d37c)

2020-10-20 08:19 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def _chain_to_chain_template(self, chain):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/07b2deb7e8f07f9194dd72ee17c7766b8813ead1)

2020-10-20 08:19 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def _model_to_model_template(self, node: Node, model_id: str, nodes_from: list, chain_id: str):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/07b2deb7e8f07f9194dd72ee17c7766b8813ead1)

2020-10-20 08:24 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def __init__(self, node: Node = None, model_id: str = None, nodes_from: list = None, chain_id: str = None):
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/afc879d79afdc39fa67c3d887117d4bdde1b0766)

2020-10-20 08:48 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            nonlocal counter
Очень долго думал как бы избавиться от этого внешнего счетчика, когда писал функцию и сейчас.

[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/1fbe09e0e48f7d2af86e6a1146c7240060dfb63c)

2020-10-20 10:20 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def import_from_json(self, path: str):
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7466471a70ca6cda507d1a7e9376ab8f99b06d9f)

2020-10-20 10:47 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        def extract_chain_structure(node: Node, model_id: int):
Внутри функции, которую вынес, я использую self, это нормально что придется передавать self-object внутрь функции?

[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/7466471a70ca6cda507d1a7e9376ab8f99b06d9f)

2020-10-20 11:37 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        if node.cache.actual_cached_state:
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/cc03d33a931707173c74eaae2675940f2697b119)

2020-10-20 11:38 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            self.model_name = node.cache.actual_cached_state.model.__class__.__name__
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/16cdebde9ba175512df3156fb59a1379b456817f#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL193-R197)

2020-10-20 11:38 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            self.fitted_model_path = os.path.join(DEFAULT_FITTED_MODELS_PATH, chain_id, 'model_'
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/16cdebde9ba175512df3156fb59a1379b456817f#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL193-R197)

2020-10-20 11:39 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        def create_unique_chain_id(path_to_save: str):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/981b41e79c5833ba8a080fb2c62572d0a03f478c#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL36-R89)

2020-10-20 11:40 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +    def import_from_json(self, path: str):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/144/commits/981b41e79c5833ba8a080fb2c62572d0a03f478c#diff-ab09dae179545fee30d6f4d0e45d191b77b0da1cbc75b57760d7d326f8db6c6aL77-L240)

2020-10-20 11:49 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            if len(last_file) >= 2:
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/6a889f942d74769f2279a56b46e7b7bd684b2e01)

2020-10-20 11:53 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            print(f"The chain saved in the path: {os.path.join(absolute_path, f'{self.unique_chain_id}.json')}")
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/817a8730c23c9270a82554a8eb0ab10a952fc505)

2020-10-20 11:54 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            raise JsonFileInvalid(f"Required field 'model_id, model_type, params, nodes_from'")
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/80e029682b30552a96a942ce01fe9641a8fed468)

2020-10-20 11:55 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        root_node = find_model_jsons_from_json_chain(json_object_chain['nodes'], [0])[0]
Исправлено

2020-10-20 11:55 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +        def find_model_jsons_from_json_chain(json_chain, list_of_model_ids):
Все починено

2020-10-20 12:51 UTC, J3FALL commented on test/test_json_vice_versa.py
> +def test_custom_json_object_to_chain():
Угу, теперь норм отрабатывает.

2020-10-20 12:58 UTC, J3FALL commented on test/data/test_custom_json_template.json
> +        },
Смотри, что я имел в виду: 
![image](https://user-images.githubusercontent.com/7864250/96588900-dc262000-12ec-11eb-83a2-7b7d8cadc67a.png)
Если перенести эти узлы в json-е на самый верх, то тесты все равно работают.
Интуитивно должно быть так, что если в цепочки узлы идут сверху вниз от primary узлов до secondary, то и в этом файле резонно соблюдать порядок следования моделей.

2020-10-20 13:57 UTC, J3FALL commented on test/test_json_vice_versa.py
> +def test_one_chain_object_save_load_vice_versa():
Хм, окей, тогда добавь, плз, в этот тест docstring с коротким описанием того, что ты здесь описал.
И тогда норм.

2020-10-20 13:59 UTC, MAGLeb commented on test/data/test_custom_json_template.json
> +        },
А я наоборот сделал, снизу вверх. [Переделал](https://github.com/nccr-itmo/FEDOT/pull/144/commits/90396d63af0a79dd9b095ad7b83716464c1a8249)

2020-10-20 14:16 UTC, J3FALL commented on test/test_json_vice_versa.py
> +    assert True
Хм, ну смотри тогда: в тесте проверяется, что при выполнении этих операций не вылетит исключение, т.е:
- ожидаемое поведение: исключение не вылетело
- иначе: что-то упало
Есть такая удобная штука - pytest.raises, мы ее тоже использовали в тестах:
![image](https://user-images.githubusercontent.com/7864250/96598581-af2b3a80-12f7-11eb-982e-eeb8a35b68c4.png)
Здесь делается ассерт, что сработало исключение.
Но в твоем случае, можно и не делать так и ограничиться просто постфиксом в названии теста: "_no_exceptions_"
Ну и убрать assert True, чтобы не путало.

2020-10-20 14:43 UTC, MAGLeb commented on save_chain_to_json.md
> +#### How to save fitted models and interpreting the chain in JSON format
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/abc5db15f3d3cef812ce81aeab79fc28276be0c8)
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/6d3973b443d1a70ec8dee52ea3b79f542ed9384e)

2020-10-20 14:44 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +def test_one_chain_object_save_load_vice_versa():
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/3bf45c07361ad190384570b1c3aac6264a05a5f0)

2020-10-20 14:54 UTC, J3FALL commented on utilities/synthetic/chain_template_new.py
> +            self.model_name = node.cache.actual_cached_state.model.__class__.__name__
![image](https://user-images.githubusercontent.com/7864250/96603965-3a5aff00-12fd-11eb-80a9-84e761adc32d.png)
Вот под эту строчку извлеки отдельную функцию, плз.
Чтобы не потерялось потом.

2020-10-20 16:39 UTC, MAGLeb commented on test/test_json_vice_versa.py
> +    assert True
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/a29678e4b91b52637aa5c062eccab6d1505a9ed4)

2020-10-20 16:50 UTC, MAGLeb commented on utilities/synthetic/chain_template_new.py
> +            self.model_name = node.cache.actual_cached_state.model.__class__.__name__
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/144/commits/d60bd964259c6a8b1c5134f2fd327425dedb7f8b)

2020-10-21 08:51 UTC, J3FALL approved these changes

2020-10-21 09:38 UTC, nicl-nno approved these changes

2020-10-21 09:55 UTC, BarabanovaIrina approved these changes

2020-10-21 09:58 UTC, merged