Parameter free evo approach
nccr-itmo/FEDOT pull request #146
Opened 2020-09-09 23:35 UTC by YanaPolonskaya

Была добавлена схема схема эволюции называемая "parameter free" при которой такие параметры как размер популяции, размер потомства и кол-во поколений изменяются в ходе эволюции в зависимости от качества популяции, полученного на предыдущем шаге. Данная схема была вынесена в отдельный оптимайзер поскольку из-за этого код основного gp_optimiser стал загруженным.
Подробнее про схему эволюции можно почитать в этой статье: https://www.researchgate.net/publication/338883598_An_Adaptive_and_Near_Parameter-free_Evolutionary_Computation_Approach_Towards_True_Automation_in_AutoML.

Добавлена так же автоматическая настройка глубины дерева в ходе эволюции.

Помимо этого в  ходе стажировки стажером было обнаружена следующая ошибка: Если мы берем ранее обученную цепочку в моделях которой уже имеется какой-то кеш, и пытаемся заново ее обучить с использованием метода fit, подавая в него совершенно другие данные, отличные от тех на которых она ранее была обучена - используется старый кеш и цепочка заново не обучается. Данная ошибка была так же исправлена в этом PR.

Буду рада любой критике и советам по поводу того, как сделать так, чтобы код в оптимизаторах выглядел более читаемо, потому что мои раздумия пока не привели к какому-то однозначному и хорошему ответу.

2020-09-09 23:35 UTC, pep8speaks commented
Hello @YanaPolonskaya! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cases/credit_scoring_problem.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/cases/credit_scoring_problem.py):

> [Line 57:5](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/cases/credit_scoring_problem.py#L57): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`core/composer/chain.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/chain.py):

> [Line 31:12](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/chain.py#L31): [E714](https://duckduckgo.com/?q=pep8%20E714) test for object identity should be 'is not'





* In the file [`core/composer/optimisers/gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py):

> [Line 68:121](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (123 > 120 characters)
> [Line 76:58](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L76): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 76:64](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L76): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 76:65](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L76): [E252](https://duckduckgo.com/?q=pep8%20E252) missing whitespace around parameter equals
> [Line 169:46](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L169): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 239:1](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/gp_optimiser.py#L239): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`core/composer/optimisers/inheritance.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/inheritance.py):

> [Line 23:71](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/inheritance.py#L23): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 39:1](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/inheritance.py#L39): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`core/composer/optimisers/mutation.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/mutation.py):

> [Line 120:46](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/optimisers/mutation.py#L120): [E714](https://duckduckgo.com/?q=pep8%20E714) test for object identity should be 'is not'





* In the file [`core/composer/timer.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/timer.py):

> [Line 40:12](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/timer.py#L40): [E714](https://duckduckgo.com/?q=pep8%20E714) test for object identity should be 'is not'

* In the file [`core/composer/visualisation.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/visualisation.py):

> [Line 196:53](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/core/composer/visualisation.py#L196): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

* In the file [`test/test_chain.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/test/test_chain.py):

> [Line 244:1](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/test/test_chain.py#L244): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`test/test_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/test/test_tuning.py):

> [Line 41:1](https://github.com/nccr-itmo/FEDOT/blob/e34915f3595c4972d0142bca22f7e59e6cc78bf3/test/test_tuning.py#L41): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2020-09-10 20:40 UTC, nicl-nno requested changes

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +        self.archive_fibonacci_values = {}
Хорошо бы иметь возможность заменять все fibonacci-related штуки на произвольный итератор.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/selection.py
> +            unselected_individuals = [individuals[i] for i in unselected_indexes]
Cлишком уж много тут операций с индексами и индивидами.
Мб можно сделать просто unselected_individuals.remove(individual)?

unselected_individuals я бы переименовал в remaining_ или как-то так.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/visualisation.py
> +    size = int(7000.0 / max(ceil(log2(nodes_amount)),1))
Тут и везде надо оформление подправить, см https://github.com/nccr-itmo/FEDOT/pull/146//#issuecomment-689879311

2020-09-10 20:40 UTC, nicl-nno commented on test/test_chain.py
> +from sklearn.datasets import load_iris, load_boston
А зачем тут load_boston? Вроде не используется.

2020-09-10 20:40 UTC, nicl-nno commented on test/test_chain.py
> +def test_chain_cache_changed_data(data_setup, other_data_setup):
И из названия, и из кода сложно понять, что именно тут проверяется.

Тест видимо на то, что кэш после повторного обучения модели с use_cache = Falseдолжен сбрасываться. Но вроде исход теста должен не зависеть от манипуляций с данными? Мб тогда нужно тестировать с use_cache = True? 

Был связанный с этим баг, но он был связан с применением SharedCache, насколько я помню.

Ну и в любом случаее лучше в test_node_cache.py это переместить.

2020-09-10 20:40 UTC, nicl-nno commented on test/test_chain.py
> +    new_first_child_cache_id = id(chain.root_node.nodes_from[0].cache)
А тут действительно нужны все эти id? Не получится объекты между собой сравнивать напрумую?

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                    for parent_num in range(0, len(selected_individuals), 2):
А это норм что элементы reproduce-ятся по порядку их следования? Не нужно случайные 2 брать?

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                    new_population = [self.reproduce(self.population[0])[0]]
Лучше записать в две строки, first_ind, _ = self.reproduce() и потом new_population = [first_ind].

А то [...[0]] - какая-то странная операция.

Тогда и в след. строке можно будет new_population[0] не использовать.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                            self.max_std = self.current_std
Лучше все операции с std вынести в отдельный метод.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                    self.current_std = np.std(all_fitness)
Выглядит как будто можно и в одну строку записать, зачем лишняя переменная. 

А то и вообще превратить current_std  в property (тогда оно ещё и всегда актуально будет).

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                        self.max_std = self.current_std
Кажется эти строки не нужны.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/mutation.py
> +    max_depth: int = None
Тут вроде всё дублируется из ComposerParams? Это точно нужно?

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/mutation.py
> +    if mut_id == MutationStrengthEnum.weak.value:
Зачем сравнивать  по value, если можно сравнивать напрямую Enum.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/mutation.py
>          return mutation_strength / (node_depth(root_node) + 1)
Строчку можно не дублировать, а один раз в конце использовать.

Также, не знаю, насколько это принято, но mutation_strength  можно хранить в MutationStrengthEnum в виде value. Тогда и if не нужен.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/mutation.py
> +    none = 'none'
Надо будет добавить docstring с описанием всех этих типов мутации, а то уже сложно разобраться.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/inheritance.py
> +                                                                      max_size)
Я бы тут сделал так, а то цикл сбивает с толку:

state_state_scheme = steady_state_inheritance
genetic_scheme_by_type  = {
GeneticSchemeTypesEnum.generational: direct_inheritance(new_population, max_size),
GeneticSchemeTypesEnum.steady_state: state_state_scheme 
GeneticSchemeTypesEnum.parameter_free: state_state_scheme 
}
(мб скопировать надо, не знаю)

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/inheritance.py
> +    genetic_scheme_by_type = dict()
Это скорее inheritance_type_by_genetic_scheme кмк

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/gp_optimiser.py
> +        if self.prev_best.fitness == self.best_individual.fitness:
Лучше для проверки равенства фитнесов сделать отдельный метод. float-ы вообще так сравнивать ненадёжно.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/gp_optimiser.py
> +        if self.num_of_gens_non_improving_fitness == self.parameters.depth_configuration_step and \
Какая-то неочевидная проверка. Возможно понятие depth_configuration_step сбивает с толку.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/gp_optimiser.py
> +        self.start_depth = start_depth
А это нельзя в dataclass превратить?

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                                         list(self.archive_fibonacci_values.keys())[0]] - self.requirements.pop_size
Тоже как-то запутанно. А режим когда pop_size_from_fibonacci_sequence==False точно вообще нужен? Выглядит как какая-то параллельная основной логика.

2020-09-10 20:40 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +                print("pop size:", self.requirements.pop_size, "num of new inds", num_of_new_individuals)
Тот же коммент про кавычки + логгер.

2020-10-13 14:42 UTC, YanaPolonskaya commented on core/composer/optimisers/gp_optimiser.py
> +    def parents_num_calculation(self, num_of_new_inds):
Здесь наоборот, если остатка от деления на 2 нет (число четное) - то не прибавлять ничего, т к каждое скрещивание 2х индивидов дает 2 индивида. Если нечетное кол-во новых индивидов нужно получить, то для получения числа родителей прибавляем 1 к их количеству. 
вообще вынести в другой файл (н-р "gp_operators")?

2020-11-03 21:18 UTC, nicl-nno commented on core/composer/optimisers/gp_optimiser.py
> +    def parents_num_calculation(self, num_of_new_inds):
Может как-то так тогда назвать, если это метод чисто под кроссовер?
num_of_inds_for_crossover(num_of_final_inds)

А то без описания выше неочевидно, что всё-таки делается.

2020-11-03 21:19 UTC, nicl-nno commented on core/composer/iterator.py
>      def hasprev(self) -> bool:
Тут и далее в названиях has-методов подчеркивания не помешают.

2020-11-03 21:42 UTC, nicl-nno commented on core/composer/optimisers/param_free_gp_optimiser.py
> +        self.archive_fibonacci_values = {}
К итератору стоит добавить докстирнг, объясняющий зачем он нужен. 
А то без контекста непонятно, почему он именно в optimisers лежит.

2020-11-04 10:22 UTC, nicl-nno commented on core/composer/optimisers/gp_optimiser.py
> +                print("max_depth", self.max_depth, "no improvements", self.num_of_gens_non_improving_fitness)
А логгер применишь? Или в нем не хватает какой-то функциональности?

2020-11-04 21:24 UTC, YanaPolonskaya commented on core/composer/optimisers/gp_optimiser.py
> +                print("max_depth", self.max_depth, "no improvements", self.num_of_gens_non_improving_fitness)
[Здесь](https://github.com/nccr-itmo/FEDOT/pull/146/commits/766579fccac0dccb9385f05e0b426a7faa1eca8c#diff-4fbbe17f61b047d16e70aca55c87133be5e436881af249d4050c491acf071d17R122-R123) и в других местах применила логгер.

2020-11-04 21:26 UTC, YanaPolonskaya commented on core/composer/optimisers/gp_optimiser.py
> +    def parents_num_calculation(self, num_of_new_inds):
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/766579fccac0dccb9385f05e0b426a7faa1eca8c#diff-4f5c26ec048a948176c07810654eb922c94d33158ce716135f49e3bc2c5a83adR110).

2020-11-04 21:27 UTC, YanaPolonskaya commented on core/composer/optimisers/param_free_gp_optimiser.py
> +        self.archive_fibonacci_values = {}
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/766579fccac0dccb9385f05e0b426a7faa1eca8c#diff-9cfdfb68b445c0749132fb7f00a5d7e1b0016abdeb96a9b2e7afb76462df4047R5-R13).

2020-11-04 21:28 UTC, YanaPolonskaya commented on core/composer/iterator.py
>      def hasprev(self) -> bool:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/766579fccac0dccb9385f05e0b426a7faa1eca8c#diff-9cfdfb68b445c0749132fb7f00a5d7e1b0016abdeb96a9b2e7afb76462df4047R24).

2020-11-10 13:44 UTC, nicl-nno approved these changes
От себя аппрувлю, но перед вливанием в мастер ещё Паша хотел посмотреть.

2020-11-10 16:32 UTC, J3FALL requested changes

2020-11-10 16:32 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
Вот тут не очень понял проверку.
- Вроде если выше создается объект (optimiser) класса GPChainOptimiser, то логичнее делать проверку объекта, а не этого класса? Т.е. следовало ожидать `if type(optimiser) is GPChainOptimiser`.
- По коду выше мне показалось, что optimiser_type может быть либо объектом класса GPChainOptimiser, либо GPChainParameterFreeOptimiser. Но при этом второй класс является наследником GPChainOptimiser.
Тогда получается, что вот эта проверка `if optimiser_type is GPChainOptimiser` всегда должна быть true? Если это не так, то тут происходит нарушение абстракций.

2020-11-10 16:32 UTC, J3FALL commented on cases/credit_scoring_problem.py
> +    optimiser_parameters = GPChainOptimiserParameters(genetic_scheme_type=GeneticSchemeTypesEnum.steady_state)
Извлеки здесь переменную, плз.
scheme_type = GeneticSchemeTypesEnum.steady_state.
Хочется постепенно уменьшать число громоздких конструкций в ядре)

2020-11-10 16:32 UTC, J3FALL commented on core/composer/chain.py
> +    :param fitted_on_data: data used in last chain fitting (equals None if chain hasn't been fitted yet)
По идее, это fitted_on_data - это не param, т.к. в конструкторе ведь его нет.
Я не очень в курсе, как в docstring грамотнее отображать около-приватные поля (можешь это посмотреть заодно).
Но, наверное, можно это просто описание оставить как дополнительный текст, но без префикса :param.

2020-11-10 16:32 UTC, J3FALL commented on core/composer/chain.py
> +                    use_cache = False
1. Думаю, можно выделить отдельную функцию типа cache_status_if_new_data(cache_status=use_cache), которая вернет значение True/False в зависимости от этих условий.
2. Это нужно через логер (а не print, как сейчас) делать warning какой-то, ибо ранее мы предполагали, что если запускаешь цепочку на новых данных, забыв ее обучить - то сам дурак ))

2020-11-10 16:32 UTC, J3FALL commented on core/composer/iterator.py
> +from typing import (Callable)
Скобочки, наверное, не нужны.

2020-11-10 16:32 UTC, J3FALL commented on core/composer/iterator.py
> +            raise StopIteration
А здесь разве не объект надо возвращать?
Ну, т.е. StopIteration()

2020-11-10 16:32 UTC, J3FALL commented on core/composer/iterator.py
> +    return n if n < 2 else fibonacci_sequence(n - 1) + fibonacci_sequence(n - 2)
Не, ну, рекурсивно вычислять числа фибоначчи, конечно, не самая лучшая идея)
Стоит это изменить, используя методы динамического программирования

2020-11-10 16:36 UTC, nicl-nno commented on core/composer/iterator.py
> +    return n if n < 2 else fibonacci_sequence(n - 1) + fibonacci_sequence(n - 2)
Вроде можно просто по формуле вычислять: return ((1+sqrt(5))**n-(1-sqrt(5))**n)/(2**n*sqrt(5))

2020-11-11 08:50 UTC, J3FALL commented on core/composer/iterator.py
> +    return n if n < 2 else fibonacci_sequence(n - 1) + fibonacci_sequence(n - 2)
Ну, это для МАТЕМАТИКОВ + тут округлять еще надо.
Но можно и так.

2020-11-12 23:46 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-5d6bb8b9115e4c6188ea33f84a9e261ddffc039d197bcb1f65582a4101b9930dR54-R56).

Подскажите, сильно ли критично, если переменные в Composer выделенные жирным из compose_chain будут перенесены в конструктор?

`
class Composer(ABC):
    """
    Base class used for receiving composite models via optimization

    :param log: optional parameter for log oject
    """

    def __init__(self, log: Log = default_log(__name__)):
        self.history = None
        self.log = log

    @abstractmethod
    def compose_chain(self, data: InputData,
                      initial_chain: Optional[Chain],
                      **composer_requirements**: ComposerRequirements,
                      metrics: Callable,
                      **optimiser_parameters: Any = None**,
                      is_visualise: bool = False) -> Chain:`

В таком случае GPComposerBuilder выглядел бы примерно так (в нем уже сразу создавался бы и оптимайзер, который передавался бы в конструктор GPComposer- а. Так же параметер initial_chain не нужно было бы передавать в composer т к оптимайзер уже создан): 

`class GPComposerBuilder:
    @staticmethod
    def gp_compoer_build(initial_chain: Optional[Chain],
                         composer_requirements: Optional[GPComposerRequirements],
                         optimiser_parameters: GPChainOptimiserParameters = None):

        optimiser_type = GPChainOptimiser
        if optimiser_parameters is not None:
            if optimiser_parameters.genetic_scheme_type == GeneticSchemeTypesEnum.parameter_free:
                optimiser_type = GPChainParameterFreeOptimiser

        chain_generation_params = ChainGenerationParams()

        optimiser = optimiser_type(initial_chain=initial_chain,
                                   requirements=composer_requirements,
                                   chain_generation_params=chain_generation_params,
                                   parameters=optimiser_parameters)

        composer = GPComposer(optimiser_type, composer_requirements, optimiser_parameters)

        return composer`

Так же это позволило бы не дублировать параметр во внешнем файле с экспериментом:
![image](https://user-images.githubusercontent.com/33351964/99009148-91e53700-2558-11eb-8952-487e47307888.png), ну и немного вообще код бы преобразился. Или то же дублирование не так страшно?

2020-11-13 00:02 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-5d6bb8b9115e4c6188ea33f84a9e261ddffc039d197bcb1f65582a4101b9930dR92).

2020-11-13 00:04 UTC, YanaPolonskaya commented on cases/credit_scoring_problem.py
> +    optimiser_parameters = GPChainOptimiserParameters(genetic_scheme_type=GeneticSchemeTypesEnum.steady_state)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-cb43b2176f481d021b0855ea6e309b6a0efbfe80b2fe0fd5172ee7fa604d1e57R55).

2020-11-13 00:04 UTC, YanaPolonskaya commented on core/composer/chain.py
> +    :param fitted_on_data: data used in last chain fitting (equals None if chain hasn't been fitted yet)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-243017476dedcaf19e112f5821a0494aa1ce3d363e6ff527e8451101de4a36edR23-R25).

2020-11-13 00:05 UTC, YanaPolonskaya commented on core/composer/chain.py
> +                    use_cache = False
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-243017476dedcaf19e112f5821a0494aa1ce3d363e6ff527e8451101de4a36edR52-R59).

2020-11-13 00:05 UTC, YanaPolonskaya commented on core/composer/iterator.py
> +from typing import (Callable)
Fixed.

2020-11-13 00:05 UTC, YanaPolonskaya commented on core/composer/iterator.py
> +            raise StopIteration
Fixed.

2020-11-13 00:10 UTC, YanaPolonskaya commented on core/composer/iterator.py
> +    return n if n < 2 else fibonacci_sequence(n - 1) + fibonacci_sequence(n - 2)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/9699eba5fa7d9019af2964a2649ec0518c07d89d#diff-9cfdfb68b445c0749132fb7f00a5d7e1b0016abdeb96a9b2e7afb76462df4047L79-R84).

2020-11-13 13:50 UTC, nicl-nno commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
А может тогда вообще оставить в compose_chain только параметры data и is_visualise? Остальные по контексту вполне ложатся в параметры билдера (например, если передано 2 метрики, а не одна - то композер строится на основе многокритериального алгоритма).

2020-11-13 14:08 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
Тогда доработаю таким образом. И когда будет многокритериальный алгоритм добавлен, будет удобно просто вписать эту логику в билдер (связанную с кол-вом метрик).

2020-11-13 15:53 UTC, J3FALL commented on core/composer/iterator.py
> +            raise StopIteration
Там еще в соседней функции prev тоже можно исправить.

2020-11-13 16:26 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
А так ли критично для ParamFree оптимизатора возвращать self.pop_sizes? Этого поля нет в базовом классе, и вроде оно не особо используется извне, или я ошибаюсь? Можешь кинуть ссылку на пример с кодом, если это где-то используется все-таки.
Просто если оно не очень важное, то и эту проверку не придется делать, и интерфейсы оптимизатора будут одинаковые.

2020-11-13 16:36 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
Поддерживаю идею - большинство параметров резонно вынести в конструктор.
Я пытаюсь в голове придумать кейс, где нужно проводить запуск композера на разных параметрах, и кажется, что чаще всех могут меняться только данные. 
Но а если захочется запустить композер на других requirements и т.д., то не критично создать новый инстанс композера.

+ Еще могу предложить классный (на мой взгляд) концепт билдера с логикой with/set, см [тут](https://habr.com/ru/post/244521/). Мне кажется, в нашем случае это хорошо применяется, и можно реализовать штуку типа:
```
builder = GPComposerBuilder().gp_composer().with_scheme_type(scheme).with_requirements(requirements)....
gp_composer = builder.build()
```

2020-11-13 16:48 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
В ядре нигде это не используется, используется только в эксперименте https://github.com/ITMO-NSS-team/AutoML-benchmark/blob/evo-schemes-experiment/experiments/gp_schemes_experiment.py#L111. Это можно убрать, если изменить вид в котором в композере сохраняется история (self.history). 
Это было нужно поскольку в parameter-free на каждом поколении изменяется размер популяции, а при записи истории мы это не учитывали (там просто сохраняются все индивиды в кучу и считается что размер популяции всегда один). 
Гораздо лучше и правда наверное будет выглядеть если поменять вид в котором формируется история (правда не знаю, мб кто-то еще ее использует активно кроме меня в своих экспериментах, надо будет и там поменять)

2020-11-16 10:08 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
Думаю, если ты поменяешь формат сохранения истории, это не повлияет критично на другие эксперименты.

2020-11-19 10:22 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
Выглядит прикольно, и экономит код в случае который в статье описан, но немного странно, что билдер внутри класса находится (и там много критики в комментариях по поводу него).

Схему именно которую ты предложил я плохо поняла

Типо что-то должно быть в таком роде?
Хотя возможно я не так поняла, потому что выглядит странно

```
class GPComposerBuilder():

    @staticmethod
    def gp_composer():
        return GPComposerBuilder().GPComposer()

    class GPComposer(Composer):
        def __init__(self, metrics =None,
                     composer_requirements=None,
                     initial_chain = None, optimiser_parameters = None): #здесь вместо None можно какие-то значения по умолчанию наверное
            super().__init__(metrics=metrics, composer_requirements=composer_requirements, initial_chain=initial_chain)
            self.shared_cache = {}

        def with_requirements(self, requirements: Optional[GPComposerRequirements]):
            self.composer_requirements = requirements

        def with_initial_chain(self, initial_chain: Optional[Chain]):
            self.initial_chain = initial_chain
            
        def with_optimiser_parameters(self, optimiser_parameters):
            ..........
            
        и т д 

    def build(self):
        # здесь код для создания оптимайзера и прочих вещей которые в текущем коммите прописаны в 
       функции get_composer (GPCpmposerBuilder - а)?

        optimiser_type = GPChainOptimiser
        if optimiser_parameters is not None:
            if optimiser_parameters.genetic_scheme_type == GeneticSchemeTypesEnum.parameter_free:
                optimiser_type = GPChainParameterFreeOptimiser
        ....................
      Но после того как создан оптимайзер, он должен назначиться в качестве параметра gp_composer-у, 
      чтобы в теле gp-composera (в функции compose_chain потом он вызвался)
```

Если по схеме которая предложена у них:

```
class GPComposer(Composer):
     #здесь от класса Composer уже не наследуешься, т к параметры конструктора не соответствуют тем
     которые в Composer-е (либо нужно их объявлять по умолчанию - но тогда место этот билдер никак не 
     сэкономит а только увеличит кол-во кода, т к потом еще для каждого параметра в classe builder своя 
     функция будет!)
    def __init__(self): 
        self.shared_cache = {}

    @staticmethod
    def new_builder():
        return GPComposer().GPComposerBuilder()

    class GPComposerBuilder:

        def with_requirements(self, requirements: Optional[GPComposerRequirements]):
            Something = requirements?? #на месте Something не знаю что написано должно быть, до меня пока
                                                            не доходит как здесь параметры именно текущего композера назначать 
                                                            с учетом того что в него билдер вложен 

        def build(self):
              
             

```
И вообще в целом кажется что эта штука возможно заграмаждает код в нашем случае. Либо я что-то недопонимаю (что вообще не исключено)

2020-11-19 10:32 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
Изменила. Изменения затронули [код в compose_chain](https://github.com/nccr-itmo/FEDOT/pull/146/commits/0fc38ef66e78bbdcbf973b3de8a5bf700c27f0d2#diff-5d6bb8b9115e4c6188ea33f84a9e261ddffc039d197bcb1f65582a4101b9930dR80-R82) и [код в оптимизаторах] (https://github.com/nccr-itmo/FEDOT/pull/146/commits/0fc38ef66e78bbdcbf973b3de8a5bf700c27f0d2#diff-4fbbe17f61b047d16e70aca55c87133be5e436881af249d4050c491acf071d17R243).
История теперь записывается в формате [[ind, ind, ind....][...][...].......] - где каждый вложенный массив - это одно поколение ( поэтому не приходится в эксперимертах в которых участвует parameter-pree-optimiser записывать какого размера была каждая популяция).

2020-11-19 10:33 UTC, YanaPolonskaya commented on core/composer/iterator.py
> +            raise StopIteration
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/0fc38ef66e78bbdcbf973b3de8a5bf700c27f0d2#diff-9cfdfb68b445c0749132fb7f00a5d7e1b0016abdeb96a9b2e7afb76462df4047R72).

2020-11-19 11:13 UTC, YanaPolonskaya commented
В ходе тестирования, при запусках [экспериментов](https://github.com/ITMO-NSS-team/AutoML-benchmark/tree/evo-schemes-experiment/experiments) столкнулась с ошибками, одна из которых:
![image](https://user-images.githubusercontent.com/33351964/99658765-fdefff80-2a70-11eb-9bb2-2b43db2a0bdf.png)
Не вылазит если в функции вычисления метрики весь код заменить на генерацию случайного числа:
```
    def metric_for_nodes(self, metric_function, train_data: InputData,
                         test_data: InputData, is_chain_shared: bool,
                         chain: Chain) -> float:

        from random import random
        return -random()
```
что наводит на мысль о том, что ошибка действительно возникает при вызове fit для цепочки.

2020-11-19 12:13 UTC, nicl-nno commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
Кмк в варианте №1 все with-методы должны быть методами билдера, а не композера - и тогда становится проще, т.к. нет проблем с наследованием.  Т.е. как вот тут в примере это сделано: https://stackoverflow.com/a/22205639 

Там ещё есть ниже вариант с  @buildermethod, но не уверен что в нашем случае он оправдан.

2020-11-19 15:18 UTC, J3FALL commented
> что наводит на мысль о том, что ошибка действительно возникает при вызове fit для цепочки( 
Хм, по тексту ошибки выглядит, что дело в чем-то вообще другом и это не из-за твоих изменений, а могло возникнуть и раньше.
Думаю, после релиза fedot в pypi нужно будет провести ревизию кода в бенчмарках и отдебажить, что там пошло не так.

2020-11-19 15:41 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
Еще немного подробнее:
- GPComposer и GPComposerBuilder - 2 отдельных класса, они не вложены друг в друга.
- GPComposer какой был, такой и остался
- Все методы with, как и сказал Коля выше, относятся к билдеру
Пример того, как могут быть реализованы эти классы, чтобы это все могло работать:
```
class GPComposerBuilder:
def __init__(self):
    self._composer = GPComposer()
    # Просто инициировали приватный экземпляр композера, который будем конфигурировать
def with_requirements(requirements):
    self._composer.requirements = requirements
    # Обращаем внимание, что мы возвращаем self, т.е. не композер, а ссылку на билдер
    return self

def with_scheme_type(...):
     ...
     return self
...

def build():
    # А уже здесь возвращаем готовый к использованию экземпляр композера
    return self._composer
``` 

Таким образом, это позволяет запустить конструкцию, про которую я писал выше:
```
builder = GPComposerBuilder().with_scheme_type(scheme).with_requirements(requirements)
gp_composer = builder.build()
```

Возможна и альтернативная реализация, где мы не создаем в конструкторе билдера заранее объект класса GPComposer, а просто инициализируем его будущие параметры как None (или дефолтными значениями); в методах with_ мы присваиваем им переданные внешние значения; а уже в методе build создаем итоговый объект класса GPComposer с указанными параметрами и возвращаем его.
Но тогда получается, что вроде поля дублируем, хотя это и не обязательно.

2020-11-19 15:56 UTC, J3FALL commented on core/composer/gp_composer/gp_composer.py
> +            best_chain, self.history, self.pop_sizes = optimiser.optimise(metric_function_for_nodes)
Хорошо, что удалось избавиться от лишних проверок.
Как сохраняется история в любом случае я планировал порефакторить, как минимум, для того, чтобы удобнее было потом визуализировать.
Но это уже совсем другая история)

2020-11-22 11:50 UTC, YanaPolonskaya commented on core/composer/gp_composer/gp_composer.py
> +                                   parameters=optimiser_parameters)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/146/commits/17910b3aad99aa37b54c7975abe42744f5958c94#diff-5d6bb8b9115e4c6188ea33f84a9e261ddffc039d197bcb1f65582a4101b9930dR122).

2020-11-23 20:05 UTC, nicl-nno approved these changes

2020-11-24 10:08 UTC, J3FALL approved these changes

2020-11-24 11:02 UTC, merged