Implement gap filling functionality
nccr-itmo/FEDOT pull request #160
Opened 2020-10-12 15:13 UTC by Dreamlone

Added a file utilities/ts_gapfilling.py. It contains two classes SimpleGapfiller and AdvancedGapfiller, which allow to restore values in one-dimensional time series. some info about the main principles in this classes: for example the "inverse_ridge" function from  AdvancedGapfiller works as follows
![Inverse gapfilling](https://user-images.githubusercontent.com/52418437/95762185-07d65400-0cb6-11eb-90e8-8eeb79f0888f.png)

Added an example to examples/time_series_gapfilling_example.py, where you can try to restore omissions on simulated data. I also added a dataframe to the /data and file with gapfilling case in time_series_gapfilling.py which contains an example of restoring a 1000-element gap in the time series of air temperature from a weather station in Saint Petersburg.

2020-10-12 15:13 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`utilities/ts_gapfilling.py`](https://github.com/nccr-itmo/FEDOT/blob/2186d0821f26469eb966d084deed56f2c4a3e6be/utilities/ts_gapfilling.py):

> [Line 14:121](https://github.com/nccr-itmo/FEDOT/blob/2186d0821f26469eb966d084deed56f2c4a3e6be/utilities/ts_gapfilling.py#L14): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)
> [Line 77:121](https://github.com/nccr-itmo/FEDOT/blob/2186d0821f26469eb966d084deed56f2c4a3e6be/utilities/ts_gapfilling.py#L77): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)
> [Line 121:121](https://github.com/nccr-itmo/FEDOT/blob/2186d0821f26469eb966d084deed56f2c4a3e6be/utilities/ts_gapfilling.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2020-10-12 16:54 UTC, J3FALL commented
Сделай, пожалуйста, ребейз на мастер-ветку: там поменялись некоторые зависимости, из-за которых код из этой ветки не удается запустить сразу и без проблем.

2020-10-12 16:57 UTC, nicl-nno commented
> Сделай, пожалуйста, ребейз на мастер-ветку: там поменялись некоторые зависимости, из-за которых код из этой ветки не удается запустить сразу и без проблем.

Этот код основан на ветку ts-gapfilling-new, которая тоже отстала от мастера. Т.ч. напрямую ребейзать в рамках этого PR смысла нет кмк (он же не в мастер).

2020-10-12 17:07 UTC, nicl-nno requested changes
Накидал базовые комментарии по коду, архитектурные аспекты пока не затрагивал.

Также стоит сделать тесты на эту функциональность.

2020-10-12 17:07 UTC, nicl-nno commented on cases/time_series_gapfilling.py
> +            print('Composite chain of 5 models')
Лучше вместо 5 действиительно посчитать модели.

2020-10-12 17:07 UTC, nicl-nno commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Лучше использовать f-строки.

2020-10-12 17:07 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Слишком общая обработка экспешена - зачем преобразоваывать Exception в ValueError?

2020-10-12 17:07 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
Хорошо бы пару simple/advanced назвать более понятно.

Тот что на fedot-е основан - можно ModelGapFiller

2020-10-12 17:40 UTC, J3FALL requested changes

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +    Gapfiller_ridge = AdvancedGapfiller(gap_value=-100.0)
Имя для объекта явно не удачное: это же инстанс класса AdvancedGapfiller, почему он с большой буквы? Согласно PEP, все имена для объектов и функций должны начинаться с маленьких букв.
Также, довольно непонятно, почему инстанциируется объект класса AdvancedGapfiller, а объект называется "gapfiller_ridge"? 
По логике, либо в названии класса должно фигурировать слово "Ridge", либо имя объекта должно отличаться.

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +    Gapfiller_composite = AdvancedGapfiller(gap_value=-100.0)
Аналогичный комментарий, что и выше.

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Что за data? Ни по названию, ни по аннотации нельзя понять, что за dat-у принимает эта функция.

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +            print('Composite chain of 5 models')
Это выглядит не очень ))
Здесь можно отказаться от if-else конструкции, если сделать следующее:
1. Объявить до цикла переменную с alias-ами/label-ами моделей, типо: "model_labels = ['Inverted Ridge Regression', 'Composite model...']"
2. Заменить enumerate на zip
3. Внутри цикла добавить f-string: "print(f'Model: {model_label}'.

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Лучше пользоваться f-string-ами.

2020-10-12 17:40 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Название функции тоже неудачное - check_metrics можно интерпретировать по-разному, однако, в данном случае, функция "печатает метрики ошибки".
Это должно натолкнуть на мысли, как поменять название функции.

2020-10-12 17:40 UTC, J3FALL commented on examples/time_series_gapfilling_example.py
> +def simulated_data(length: int = 2000, gap_size: int = 100, gap_value: float = -100.0):
Название функции, имхо, неудачное. Тут ведь не симулируется/моделируется ничего, просто генерируется синусоида с шумом + добавляются дырки. Я бы предложил поменять название по аналогии с содержанием docstring-а.

2020-10-12 17:40 UTC, J3FALL commented on examples/time_series_gapfilling_example.py
> +    withoutgap_arr_poly = SimpleGapfill.local_poly_approximation(tmp_data, 4, 150)
Снова проблемы с именами объектов

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
Честно говоря, я так и не понял, а для чего здесь нужно наследование SimpleGapfiller -> AdvancedGapfiller?
Класс-потомок, кажется, не переопределяет никакую логику базового класса, а просто добавляет 2 новых функции.
При этом, вроде как, получается, что можно сделать так:
```
filler = AdvancedGapfiller()
filled_values = filler.linear_interpolation(input_data=source)
```
И ничего не сломается. Но для чего тогда нужен базовый класс?

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
Да и в целом тут классы, вроде как и не нужны особо, т.к. получается, что объекты не хранят какого-то состояния.
Кроме поля self.gap_value, но его можно передавать в качестве входного параметра для функций восстановления пропусков.

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +    def _parse_gap_ids(self, gap_list: list) -> list:
Приватный метод нужно вынести ниже публичных методов (linear_interpolation и т.д.) т.к. это некоторым образом вносит путаницу.

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Хм, мне кажется, что если я передам в качестве input_data numpy-массив с размерностью [100,2], исключение не сработает?
Либо тут описание эксепшена не корректное, либо в логике какой-то косяк.
Либо я чего-то не понимаю.

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Тот же вопрос.

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +class AdvancedGapfiller(SimpleGapfiller):
Я уже писал выше про классы, но, в любом случае, AdvancedGapfiller - явно неудачное название для класса, т.к. оно ни о чем не говорит, для чего он нужен. Наверное, он нужен для использования "advanced-методов заполнения пропусков"? Но что такое тогда "advanced-методы"?

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +                    timeseries_train_part = np.flip(timeseries_train_part)
Разделить этот кусок кода на 2 отдельных функции - это возможно?

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +    def composite_fill_gaps(self, input_data, max_window_size: int = 50):
Название функции неудачное, т.к. тоже не понятно, что функция делает.

2020-10-12 17:40 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +            return (chain)
Лучше вытащить это в отдельную функцию в скрипте, а не оставлять ее как nested.

2020-10-12 17:45 UTC, J3FALL commented
> > Сделай, пожалуйста, ребейз на мастер-ветку: там поменялись некоторые зависимости, из-за которых код из этой ветки не удается запустить сразу и без проблем.
> 
> Этот код основан на ветку ts-gapfilling-new, которая тоже отстала от мастера. Т.ч. напрямую ребейзать в рамках этого PR смысла нет кмк (он же не в мастер).

Без проблем, просто не удается запустить код с восстановлением пропусков без установки h2o (который у меня, почему-то, без конфликтов не ставится), хотя в мастере мы эту проблему уже починили.

Энивей, оставил комментарии по коду, которые и без запуска бросаются в глаза.

2020-10-30 08:46 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +    Gapfiller_ridge = AdvancedGapfiller(gap_value=-100.0)
Исправил нотацию в файлах [cases/time_series_gapfilling.py](https://github.com/nccr-itmo/FEDOT/pull/160/commits/42f0955d8fc0aef5f3e2a1c1a7ab74c0aa5700e3#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dL60-R66) и [examples/time_series_gapfilling_example.py](https://github.com/nccr-itmo/FEDOT/pull/160/commits/42f0955d8fc0aef5f3e2a1c1a7ab74c0aa5700e3#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R36-R41).

2020-10-30 08:48 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +    withoutgap_arr_ridge = Gapfiller_ridge.inverse_ridge(np.array(dataframe['With_gap']), max_window_size=250)
Подчеркивание добавил [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/27830c50f9b0e8fa341d9c72e35084b8c0b0c5b6#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R37-R44) и название в файле поменял, чтобы начиналось с маленькой буквы - стало "with_gap"

2020-10-30 08:52 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +            print('Composite chain of 5 models')
Немного не понял, что имеется в виду. То есть написать не "цепочка из 5 моделей", а перечислить их, или стоит попробовать сделать примеры отдельно для каждой из моделей по одиночке без объединения их в одну цепочку?

2020-10-30 08:54 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Исправил, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/54f2960db7ae5bdc760cb0348781e171a89c3fca#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dR26-R34)

2020-10-30 08:58 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Согласен, пока убрал эксепшны (см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/e3d611dfb6dd76c8ac592f4be5716322a23f4f75)), так как никакой полезной функции они не выполняли - поторопился.

2020-10-30 09:03 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
Изменил названия. Насколько я понимаю, еще архитектурно это все сильно изменится, но пока классы остались с названиями "SimpleGapFiller" и "ModelGapFiller", см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/85264fd522b227579be6a0b7c5f44ed174cdab57#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R171-R173).

2020-10-30 09:15 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +    Gapfiller_ridge = AdvancedGapfiller(gap_value=-100.0)
Исправил нотацию и изменил "gapfiller_ridge" на "fedot_gapfiller", см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/160/commits/8de075f47dd5cda29b6b2c1e701191984b761b21)

2020-10-30 09:19 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +    Gapfiller_composite = AdvancedGapfiller(gap_value=-100.0)
Решил не дважды инициализировать объект, а один раз и его использовать для двух моделей (код пропуска в массиве не меняется, а значит нет необходимости), исправления [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/8de075f47dd5cda29b6b2c1e701191984b761b21).

2020-10-30 09:22 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Поменял название функции на "print_metrics", см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/85264fd522b227579be6a0b7c5f44ed174cdab57#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dR12-R19). "data" заменил на "dataframe" и добавил описание в docstring.

2020-10-30 09:27 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +            print('Composite chain of 5 models')
Спасибо за совет! Поменял [конструкцию](https://github.com/nccr-itmo/FEDOT/pull/160/commits/85264fd522b227579be6a0b7c5f44ed174cdab57#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dR26-R28).

2020-10-30 09:29 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Исправлено, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/54f2960db7ae5bdc760cb0348781e171a89c3fca#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dR26-R34)

2020-10-30 09:31 UTC, Dreamlone commented on examples/time_series_gapfilling_example.py
> +def simulated_data(length: int = 2000, gap_size: int = 100, gap_value: float = -100.0):
Согласен, название заменил на "generate_synthetic_data", посмотреть можно [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/85264fd522b227579be6a0b7c5f44ed174cdab57#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R8-R9).

2020-10-30 09:38 UTC, Dreamlone commented on examples/time_series_gapfilling_example.py
> +    withoutgap_arr_poly = SimpleGapfill.local_poly_approximation(tmp_data, 4, 150)
Исправил нотацию, см. в файлах [cases/time_series_gapfilling.py](https://github.com/nccr-itmo/FEDOT/pull/160/commits/42f0955d8fc0aef5f3e2a1c1a7ab74c0aa5700e3#diff-8f666bc864859e35570d413af570c45daab364f4a2efc6d928392c306319026dL60-R66) и [examples/time_series_gapfilling_example.py](https://github.com/nccr-itmo/FEDOT/pull/160/commits/42f0955d8fc0aef5f3e2a1c1a7ab74c0aa5700e3#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R36-R41).

2020-10-30 09:41 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +    def _parse_gap_ids(self, gap_list: list) -> list:
Сделано, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/53090a0073b63ffa6b24a78b15b41d366f63fcc6)

2020-10-30 09:44 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Согласен, никаких функций этт блок кода не выполнял, убрал эксепшны (см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/e3d611dfb6dd76c8ac592f4be5716322a23f4f75)), выше отписался Коле по этому же замечанию.

2020-10-30 09:44 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            raise ValueError('input data should be one-dimensional array')
Исправлено.

2020-11-03 09:00 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Хорошо, только сделай перенос строки:
![image](https://user-images.githubusercontent.com/7864250/97965953-32569100-1dcc-11eb-9dfe-96c598bda960.png)

2020-11-03 09:02 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
И в остальных скриптах проверь тоже, плз.
У меня в IDE стоит ограничение на 80 символов в одной строке:
![image](https://user-images.githubusercontent.com/7864250/97966113-7053b500-1dcc-11eb-991e-edcc9590c507.png)

2020-11-03 09:10 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Можно еще упростить:
`print(f'Root mean squared error -, {rmse_metric:.2f}')`
Подробнее можно посмотреть [тут](https://www.python.org/dev/peps/pep-0498/#id30).

2020-11-05 16:08 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/160/commits/ffdb0b7b869b9e4d49902c79901facba9f0588aa), но есть вопрос. Насколько строгое это правило? В комментариях и docsrtring я все подчистил, но в некоторых моментах есть вот такие заскоки, тоже убрать?
![image](https://user-images.githubusercontent.com/52418437/98265505-3801d180-1f9a-11eb-8200-0d89a13b0f04.png)

2020-11-05 16:09 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +        print('Median absolute error -', round(median_ae_metric, 2), '\n')
Спасибо за совет! Все сделал, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/d5514a5bbb632469a78a9302f2377ac207aa50a8)

2020-11-05 16:12 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +                    timeseries_train_part = np.flip(timeseries_train_part)
Конечно :) Все сделал, функционал реализован в двух вложенных функциях: [forward](https://github.com/nccr-itmo/FEDOT/pull/160/commits/4fbff0e12fa035cde5024ec170891a9bcf8842b4#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R192-R219) и [inverse](https://github.com/nccr-itmo/FEDOT/pull/160/commits/7a8c6b96a4a3e214c814b159d0c9b77c0522a9f6#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R221-R236) .

2020-11-05 16:18 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +    def composite_fill_gaps(self, input_data, max_window_size: int = 50):
Заменил на "composite_model" и добавил описание в docstring, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/4fbff0e12fa035cde5024ec170891a9bcf8842b4#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R272-L245). Тут идея сейчас такая, что для заполнения пропусков можно вызвать либо модель ridge (метод inverse_ridge), которая прогнозирует "слева направо", потом "справа налево" и результат склеивается, либо можно использовать цепочку из моделей (composite_model), которая прогнозирует только "слева направо".

2020-11-05 16:21 UTC, Dreamlone commented
Коллеги, посмотрите пожалуйста добавленный [тест](https://github.com/nccr-itmo/FEDOT/pull/160/commits/7595d2b912e857a32b5e91a3c1d2b9ef09a470c4) для гэпфиллинга. Если этот выполнен сносно, то в таком же стиле буду расширять обкладку тестами для незатронутых в данном тесте функциональностей  заполнения пропусков.

2020-11-05 16:22 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            return (chain)
Вынес в отдельный приватный метод, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/87e8f2c54fc56e8dc01053f50007f7048d414756#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R271-R286).

2020-11-05 16:24 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/98267382-61bbf800-1f9c-11eb-9c6b-345b607358f6.png)

Поправь заодно все эти pep8-дефекты.

2020-11-05 16:25 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +class AdvancedGapfiller(SimpleGapfiller):
По предложению Коли, назвал данный класс "ModelGapFiller", см. [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/85264fd522b227579be6a0b7c5f44ed174cdab57#diff-5d1cec9d1e564243eec7cdc3f7fd22a967735dd551c8c426b7a7c4bc375d1ec2R171-R173). Класс "ModelGapFiller" отвечает в данном случае за применение методов заполнения пропусков на основе обвязок над цепочками из моделей FEDOT'а.

2020-11-05 16:25 UTC, nicl-nno commented on test/tasks/test_gapfilling.py
> +    assert rmse_test < standard_deviation
А как это визуально выглядит? Если заполняется хорошо - нельзя ли в тесте задать более строгое условие, чем rmse < std?

2020-11-05 16:33 UTC, Dreamlone commented on test/tasks/test_gapfilling.py
> +    assert rmse_test < standard_deviation
Ага, выглядит довольно неплохо, примерно вот так:
![image](https://user-images.githubusercontent.com/52418437/98268603-c75cb400-1f9d-11eb-8de9-e207af7a1975.png). Просто я это сравнение у тебя в тестах подглядел.

2020-11-05 16:36 UTC, nicl-nno commented on test/tasks/test_gapfilling.py
> +    assert rmse_test < standard_deviation
Ну выглядит как будто можно потребовать чтобы ошибка была не сильно больше размках random_noise, который ты накладываешь.

2020-11-05 16:46 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
Update: названия классов сейчас "SimpleGapFiller" и "ModelGapFiller"

Согласен. Над архитектурой (из двух классов...) стоит мне еще подумать. Хотел попросить совета (и помощи) в этом вопросе. Вообще, я бы хотел сохранить наследование так, что в SimpleGapFiller предоставлял бы доступ к относительно простым и дешевым методам гэпфиллинга без привязки к функционалу FEDOT'a и был способен действовать автономно, а в ModelGapFiller я бы добавил в качестве дополнительного аргумента при инициализации chain, думаю, это сделает модуль по заполнению пропусков более удобным в использовании, например, что если я как пользователь не хочу "inverse_ridge" использовать с ridge регрессией, а хочу то же самое, только со случайным лесом - пожалуйста. Можно тогда передавать на вход не только одиночные модели, а еще и цепочки. 

А по поводу состояний в объектах, я бы хотел добавить возможность хранения в рамках класса некоторой информации по временному ряду. Например вот тут 
![image](https://user-images.githubusercontent.com/52418437/98269569-ef98e280-1f9e-11eb-91f6-9b6fee43594c.png)
 люди рассчитывают показатели "выраженности сезонности и тренда" для того, чтобы в дальнейшем выбирать наиболее эффективную стратегию прогнозирования временного ряда. Может и нам стоит включить нечто подобное, правда я немного сомневаюсь в целесообразности, потому что конкретно в данной реализации я близко ничего подобного не учитываю.

@nicl-nno, тоже прошу дать фидбек на мои мысли.

2020-11-05 16:54 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +class SimpleGapfiller:
>люди рассчитывают показатели "выраженности сезонности и тренда" для того, чтобы в дальнейшем выбирать наиболее эффективную стратегию прогнозирования временного ряда

В нашем случае эту часть берут на себя модели в цепочки, по идее. Вроде сейчас нет способа, как эти показатели можно было бы применить при прогнозировании.

2020-11-05 19:43 UTC, nicl-nno commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Ну вроде тут не проблема добавить перенос после знака =

2020-11-06 12:09 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Сделано, см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/160/commits/ffdb0b7b869b9e4d49902c79901facba9f0588aa).

2020-11-06 14:36 UTC, J3FALL commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Вообще есть распространенная практика рефакторинга - вводить поясняющие/вспомогательные переменные, чтобы упрощать длинные конструкции в коде, как здесь, например.
Здесь можно ввести переменную с каким-то лаконичным названием:
![image](https://user-images.githubusercontent.com/7864250/98378027-8f657780-2056-11eb-953f-d52fe2bead47.png)

2020-11-10 09:04 UTC, Dreamlone commented on test/tasks/test_gapfilling.py
> +    assert rmse_test < standard_deviation
Задал порог вручную как 1.5*СКО, которое я задаю, когда определяю параметры накладываемого шума (СКО = 0.1). См. [коммит](https://github.com/nccr-itmo/FEDOT/pull/160/commits/bfeb03476b4e91583acddf3e84fdcce49ff19da7).

2020-11-10 09:05 UTC, Dreamlone commented on cases/time_series_gapfilling.py
> +def check_metrics(data):
Спасибо! [Исправил](https://github.com/nccr-itmo/FEDOT/pull/160/commits/a85064c46b8a46f1d434ea95ce0f250b9203b7d9).

2020-11-10 11:48 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +    def inverse_ridge(self, input_data, max_window_size: int = 50):
А есть ли вообще необходимость тут делать упор в том, что это ridge? Может добавить в аргументы название модели со значением ridge по умолчанию? Это несколько упростит эксперименты с тестированием разных моделей.

2020-11-10 11:51 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +    def composite_model(self, input_data, max_window_size: int = 50):
Тут опять же суть-то не в composite_model, а в однопроходном gap filling-е с использованием заданной цепочки. Мб её и вынести в аргументы? Можно сделать метод-обертку для удобства применения конкретной модели.

2020-11-11 17:04 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +    def composite_model(self, input_data, max_window_size: int = 50):
Поддерживаю, звучит логично.

2020-11-11 17:04 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +    def inverse_ridge(self, input_data, max_window_size: int = 50):
+

2020-11-13 11:22 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +    def composite_model(self, input_data, max_window_size: int = 50):
[Все сделано.](https://github.com/nccr-itmo/FEDOT/pull/160/commits/4b209b48f9474f30fcaf003f378fce92c55f37a1). Из ключевых изменений: теперь в классе ModelGapFiller при наследовании переопределяется init, куда помимо флага пропуска можно включить цепочку TsForecastingChain, которая даёт прогноз. Класс имеет два публичных метода: forward_inverse_filling для прогноза "слева направо", "справа налево" и потом склеивает предсказания, а также метод forward_filling, который заполняет пропуски посредством прогноза по временному ряду на основе тех данных, которые расположены "левее" пропуска (такой подход подойдет для тяжелых цепочек из нескольких моделей). 

Пример прогноза (оранжевый - ridge регрессия с forward_inverse_filling, красный - цепочка из 5 моделей с forward_filling):  
![image](https://user-images.githubusercontent.com/52418437/99067349-9db61500-25bb-11eb-8674-a43a2b70cdec.png)

2020-11-13 11:23 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +    def inverse_ridge(self, input_data, max_window_size: int = 50):
Реализовано, см ответ к комментарию ниже.

2020-11-16 10:46 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
Сходу не оч. понятно - а почему вот тут break? Ведь из-за этого только 1-й пропуск заполняется вроде как.

2020-11-16 12:35 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
Согласен, он тут не нужен, остался еще с того времени, когда я запускал "тяжелые" модели, и чтобы не заполнять все пропуски, заполнял только первый из них. Сорри, что пропустил его аж до этого момента. Все исправил - [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/52aeed45771b06186795035c7230202025daeeba).

2020-11-16 12:49 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
А во всех тестах сейчас только примеры с одним пропуском?

2020-11-16 16:29 UTC, J3FALL requested changes

2020-11-16 16:29 UTC, J3FALL commented on test/real_applications/test_real_cases.py
> +    assert rmse_composite < 6.0
Немного смущает, что есть 2 очень похожих теста в test_gapfiilling_problem и test_gapfilling_example.
Это больше тоже на будущее подумать - что у нас кейсы, а что - примеры)

2020-11-16 16:29 UTC, J3FALL commented on test/tasks/test_gapfilling.py
> +import pytest
Эти импорты не используются

2020-11-16 16:29 UTC, J3FALL commented on test/tasks/test_gapfilling.py
> +    arr_with_gaps, real_values = generate_synthetic_data(length=1000,
А можно еще добавить тест на эту функцию "generate_synthetic_data"?
Хотя бы базовый, что эта функция действительно генерит gap_size ожидаемым значением gap_value.

2020-11-16 16:29 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +            """
Вытащи эти функции на один уровень с forward_inverse_filling - на мой взгляд, так будет проще и удобнее изучать логику этих функций.

2020-11-16 16:29 UTC, J3FALL commented on utilities/ts_gapfilling.py
> +from core.repository.tasks import Task, TaskTypesEnum, TsForecastingParams
Тут есть неиспользуемые импорты.

2020-11-16 16:36 UTC, nicl-nno commented on core/composer/chain.py
> +
Да, фитить с включенным make_future_prediction нельзя - модель обучается некорректно.

2020-11-16 16:54 UTC, J3FALL commented on core/composer/chain.py
> +
Немного смущает, конечно, что "как будто" нарушаются абстракции, но конкретного предложения, что с этим сделать у меня нет. 
Так что оставим, мб появятся мысли в будущем.

2020-11-16 17:32 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
Ага, так мне проще контролировать результат и точность восстановления. Просто для метода "forward_inverse_filling" с тяжеловесной цепочкой на борту иногда может не хватать места для разгона справа от пропуска, и все падает с ошибкой. Но согласен, пример в таком случае выходит слишком синтетический, я добавлю генератор временного ряда с несколькими интервалами пропусков. Как вариант могу заполнять такие ряды простыми методами или с помощью "forward_filling".

2020-11-16 17:35 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
Ну пока можно так, а в след. PR-е стоит для вариантов где "может не хватать места для разгона справа от пропуска" добавить какую-то автоматизированную проверку.

2020-12-07 07:17 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
Согласен, однако, это больше проблема не гэпфиллинга, а предсказания по временному ряду в целом и добавлять проверки кмк стоит на уровень ниже высокоуровнего гэпфиллинга. Проблема тут в том, что размер окна max_wondow_size может быть недостаточно большим просто. Думаю, это можно сделать уже сейчас -> предлагаю добавить эту проверку на этапе predict в TsChain.

Также заменил функцию генерации пропусков, там теперь можно генерировать пропуски различной длины и сколько угодно штук, см [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/3263dcc43df98e91c34ede348aa58d3b1caebd76#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R59-R81).

2020-12-07 07:21 UTC, Dreamlone commented on examples/time_series_gapfilling_example.py
> +    plt.show()
Сделано, посмотри-позапускай пожалуйста, устроит ли такая [отрисовка](https://github.com/nccr-itmo/FEDOT/pull/160/commits/3263dcc43df98e91c34ede348aa58d3b1caebd76#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R140-L95). Вполне может быть, что не очень элегантно я это реализовал. 

Update: теперь генерируется пример не с одним пропуском, а с двумя (количество и продолжительность пропусков при желании можно задать каким угодно)

2020-12-07 07:24 UTC, Dreamlone commented on test/real_applications/test_real_cases.py
> +    assert rmse_composite < 6.0
Я думал, что в example идут синтетические примеры, на которых вроде как проще показать более достойный результат. А в cases - примеры применения на реальных данных, которые перебороть сложнее. Подскажи тогда пожалуйста что сейчас с этим сделать?) Или просто в будущем я тогда не буду распыляться на сразу два примера, а сконцентрируюсь только на одном

2020-12-07 07:26 UTC, Dreamlone commented on test/tasks/test_gapfilling.py
> +import pytest
Исправлено, импорты подчистил

2020-12-07 07:32 UTC, Dreamlone commented on test/tasks/test_gapfilling.py
> +    arr_with_gaps, real_values = generate_synthetic_data(length=1000,
Update: заменил функцию, теперь она называется "get_array_with_gaps", см [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/3263dcc43df98e91c34ede348aa58d3b1caebd76#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R26-R82). Теперь есть возможность генерировать пропуски в одномерных массивах путем передачи словаря вида {850: 100, 1400: 150}, где 850 и 1400 - это индексы, с которых пропуски начинаются, а 100 и 150 - это размер (в элементах временного ряда) генерируемых пропусков.

Тест на для этого [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/3263dcc43df98e91c34ede348aa58d3b1caebd76#diff-5680d0c06667a10a762402c4038944a2d0f71f7cdb56dce258858d8680094f11R10-R19).

2020-12-07 07:33 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            """
Сделано, посмотреть можно [тут](https://github.com/nccr-itmo/FEDOT/pull/160/commits/3263dcc43df98e91c34ede348aa58d3b1caebd76#diff-41e5c94c2ed69abe1c42c62ab105d8192715c760ee5a60307cde8ce941d5e546R258-R316)

2020-12-07 07:34 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +from core.repository.tasks import Task, TaskTypesEnum, TsForecastingParams
Импорты убрал

2020-12-07 15:54 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
Но для заполнения пропусков ты же можешь автоматически выбирать размер окна для обучения в зависимости от длина ряда между пропусков?
 
Тут же задача не сообщить от ошибке, а построить модель для заполненая пропусков так, чтобы она работала на доступных данных.

2020-12-07 16:14 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
Да, это можно сделать, правда придется вносить какую-то эвристику в алгоритм - это норм? Но все равно это не решит проблему для тех случаев, когда алгоритму может понадобиться окно в 500 значений, а все что я смогу ему предложить - это размер окна в 200 (проблема с недостатком значений все равно же не уходит, я именно это имел в виду, когда писал про max_window_size).

Вообще, можно посмотреть как именно размер окна совместно со сложностью применяемой цепочки влияет на качество восстановления по хорошему с кучей примеров -> на основе этого определить эвристический алгоритм, который определяет оптимальный размер окна для данного конкретного прогноза и если для данного окна данных получается недостаточно, то каким-либо образом искусственно расширяет часть временного ряда для train'а (например заделывает все пропуски линейной интерполяцией и даёт цепочке на низ обучиться)

Но я все равно считаю, что хорошо бы, перед тем как бросаться в эту мясорубку просто выдавать предупреждение "Ваш временной ряд слишком короткий для такой сложной модели". Ну я так думаю

2020-12-07 16:18 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
>Но все равно это не решит проблему для тех случаев, когда алгоритму может понадобиться окно в 500 значений, а все что я смогу ему предложить - это размер окна в 200

Так ты же всегда можешь по данным точно сказать, какой именно максимальный размер окна вообще возможен. 

Если на нем не получить нормального прогноза - это уже другой вопрос. Предупреждать о том, что окно слишком мало, действительно можно.

2020-12-07 16:22 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
`Так ты же всегда можешь по данным точно сказать, какой именно максимальный размер окна вообще возможен.` - да, могу, но как верно подмечено (и я это замечал, когда применял алгоритм), максимально возможная длина окна не всегда давала лучший результат

2020-12-07 16:25 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
Можно на такой случай ограничить размер окна сверху каким-то эмпирически подобранным значением.

2020-12-07 17:04 UTC, Dreamlone commented on utilities/ts_gapfilling.py
> +            break
Здесь дело в том, что для каждой модели оптимальный размер окна будет своим, чем сложнее, тем больше окно должно быть, на некоторых рядах окно в 1000 элементов давало самый лучший (на мой взгляд) результат. Но я что-нибудь придумаю, спасибо за советы

2020-12-07 17:06 UTC, nicl-nno commented on utilities/ts_gapfilling.py
> +            break
Ну тут главное чтобы модель не падала с технической ошибкой, когда есть возможность её прогнать с меньшим окном.

Остальное уже потом будем изучать.

2020-12-08 14:59 UTC, J3FALL commented on examples/time_series_gapfilling_example.py
> +    plt.show()
Да, теперь хорошо выглядит.

2020-12-08 15:02 UTC, J3FALL commented on test/real_applications/test_real_cases.py
> +    assert rmse_composite < 6.0
Думаю, на данный момент, эта проблема решается:
- либо добавлением небольшого описания в скрипты (как ты написал, в одном случае данные сгенерированы синтетические, а в другом - вот такой кейс реальных данных)
- либо отразить это в названии самих скриптов

2020-12-08 15:11 UTC, J3FALL commented on examples/time_series_gapfilling_example.py
> +    plt.show()
Думаю, можно упрятать построение графика в отдельную функцию.
Не принципиально, чтобы она была какой-то универсальной, просто чтобы она принимала на вход arrays_dict, masked_array, gap_ids переменные и отрисовывала графики (как сейчас).

2020-12-09 14:46 UTC, Dreamlone commented on examples/time_series_gapfilling_example.py
> +    plt.show()
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/160/commits/9aebc3772e9b0d04f8f39f0d8248d77d890f224c#diff-f729a9df7750e3ebde2861a27f18717555242a727ba94e65ec55bae44589d807R123-R133)

2020-12-09 14:47 UTC, Dreamlone commented on test/real_applications/test_real_cases.py
> +    assert rmse_composite < 6.0
Добавил небольшое описание (буквально два слова) [здесь](https://github.com/nccr-itmo/FEDOT/pull/160/commits/9aebc3772e9b0d04f8f39f0d8248d77d890f224c#diff-1037c5a09c54beb60876ad857d602e648a99aa92230f7d3e6a36e77937b2612cL89-R89), сам файл со скриптом теперь называется как "time_series_gapfilling_case.py"

2020-12-09 15:29 UTC, J3FALL approved these changes

2020-12-09 15:43 UTC, nicl-nno approved these changes

2020-12-09 15:50 UTC, merged