upgraded tree visualization, upgraded gif creation, changed pillow ve…
nccr-itmo/FEDOT pull request #167
Opened 2020-10-28 19:03 UTC by Sash0check

Обновлена статическая визуализация структуры композитных моделей:
- не требуется установки Graphviz
- выводятся гиперпараметры
- визуальные улучшения
Обновлена визуализация истории, а именно - теперь все кадры для гифки хранятся в памяти, а не на жестком диске.
Изменена версия PIllow, так как на предыдущей возникала ошибка при создании гиф анимации

2020-10-29 19:18 UTC, nicl-nno requested changes

2020-10-29 19:18 UTC, nicl-nno commented on core/composer/visualisation.py
> +    def _add_table_params(chain, ax):
Похоже что рисуется криво, когда параметров много:

![image](https://user-images.githubusercontent.com/5711814/97620696-f66da580-1a32-11eb-975f-410a3a91bce3.png)

Ну и колонки таблицы стоит делать разной ширины

2020-10-29 19:18 UTC, nicl-nno commented on core/composer/visualisation.py
> +    def _visualise(chain: Chain, ax=None, title=None):
Не стоит private и public метод иметь с одинаковыми именами, различающимися только _.

2020-10-29 19:18 UTC, nicl-nno commented on core/composer/visualisation.py
> +            ComposerVisualiser._visualise(chain, axs[0], 'Current chain')
Большие цепочки сбиваются в нечитаемую кучу:

![image](https://user-images.githubusercontent.com/5711814/97621795-75171280-1a34-11eb-8aff-f9062b86bcdd.png)

Воспроизводится для credit_scoring_problem с

composer_requirements = GPComposerRequirements(
        primary=available_model_types,
        secondary=available_model_types, max_arity=4,
        max_depth=4, pop_size=2, num_of_generations=1,
        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, add_single_model_chains=False)

2020-11-12 15:54 UTC, J3FALL requested changes

2020-11-12 15:54 UTC, J3FALL commented on examples/forecasting_model_composing.py
> +    # plt.clf()
Угу, закомментированный код - это плохо, т.к.:
- Они со временем устаревают (закомментил, потом внес 10 изменений, а комментарий-то старый)
- Они путают других разработчиков
- У нас для этого есть git
Вот [ссылка](https://gist.github.com/wojteklu/73c6914cc446146b8b533c0988cf8d29#comments-rules) на короткий обзор принципов чистого кода от Роберта Мартина, там и про комментирование кода есть.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
>  import os
Импорты отсортированы не по PEP.
Если пользуешься Pycharm, то есть удобный hotkey для этого: ctr + alt + L
Советую пользоваться этим регулярно, чтобы код автоматически исправлялся под стандарт.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +    merged_imgs = []
У меня глобальное предложение: теперь выглядит так, что ComposerVisualiser явно может иметь состояние - у него есть поля (которые сейчас, правда, являются полями класса) chains_imgs и т.д.
Так, может, вместо статических методов перейти на полноценное ООП?
Т.е. вместо такого вызова:
`ComposerVisualiser.visualise(chain)`
Делать так:
```
visualizer = ComposerVisualiser()
visualizer.visualise(chain)
```

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +    def _visualise(chain: Chain, ax=None, title=None):
Угу, при этом по контексту кода не особо-то понятно с ходу, в чем логика такого решения.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +            ax.text(x, y, text, ha='center', va='center')
Эта функция выглядит так, что из нее можно извлечь несколько отдельных функций и упорядочить их вызов.
А сейчас тут все намешано сразу и подряд.
Сначала готовится структура узлов, потом граф отрисовывается.
Далее добавляются лейблы, а в конце - все отображается на экране.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
>              plt.close('all')
Можешь пояснить, почему тут 3 вызова?

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +                                     ComposerVisualiser.convergence_imgs[i]), axis=1)
Слишком громоздкая конструкция, тут можно извлечь отдельно переменные, а уже потом делать конкатенацию.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +                                               optimize=False, duration=0.5, loop=0)
Тут тоже резонно извлечь несколько переменных.

2020-11-12 15:54 UTC, J3FALL commented on core/composer/visualisation.py
> +    def _hierarchy_pos(graph, root, width=1., vert_gap=0.2, vert_loc=0, xcenter=0.5, pos=None, parent=None):
Тут нужен перенос строки, т.к. она слишком длинная.

2020-11-12 16:13 UTC, nicl-nno commented on core/composer/visualisation.py
>  import os
FYI также в окне с коммитом можно включить автоматическое применение форматирование:

![image](https://user-images.githubusercontent.com/5711814/98965512-321c6b00-251b-11eb-85fc-3bf9b2052757.png)

2020-11-15 14:21 UTC, Sash0check commented on core/composer/visualisation.py
>              plt.close('all')
Это осталось от оригинальной функции

2020-12-24 12:30 UTC, closed without merging

2020-12-24 12:31 UTC, J3FALL commented
See #194 for details