Tuning refactor
nccr-itmo/FEDOT pull request #168
Opened 2020-10-30 15:14 UTC by BarabanovaIrina

2020-11-02 17:31 UTC, J3FALL requested changes

2020-11-02 17:31 UTC, J3FALL commented on core/composer/chain_tune.py
> +    def fine_tune_certain_node(self, model_id, input_data: InputData, iterations: int = 30,
Меня немного смущает тема с model_id: по описанию это скорее _порядковый номер модели в цепочке_, при этом порядок определяется внутренними особенностями класса Chain.
Т.е. как будто это model_index, а не model_id.

Еще смущает, что без создания json-а для конкретной цепочки пользователь не может узнать порядковый номер конкретной модели в цепочке, хотя и может получить ссылку на объект этой модели.
В качестве решения, например, можно добавить property в цепочке, которое возвращает этот model_index для объекта Model, или бросает исключение, если этой модели нет в цепочке.

Но возможно, у тебя есть другие идеи, как это можно реализовать, главное - хотелось бы, чтобы пользователь не ломал мозг, изучая исходники и документацию для того, чтобы понять, как мы назначаем порядковые номера моделям в цепочках, чтобы затюнить нужную модель.

2020-11-02 17:31 UTC, J3FALL commented on core/composer/chain_tune.py
> +        return updated_chain
Погоди, мне кажется, тут немного неправильная логика. Я попробую описать, что здесь происходит, поправь меня, если я не прав:
1. Извлекаем поддерево в цепочке, где модель с заданным model_id является корнем.
2. Фитим это поддерево на тех же входных данных, которые являются input_data для исходной цепочки, т.е. то, что передается через primary узлы.
3. Делаем fine_tune для данного узла, воспринимая его как корень.
4. Обновляем шаблон цепочки с новыми параметрами модели (после тюна).
5. Собираем цепочку.

Кажется, здесь упущен один момент: по идее, тюнить secondary-узлы на исходных входных данных не совсем корректно, т.к. в исходной оцепочке они принимают уже "вторичные", пропущенные через предыдущие узлы данные. Т.е. по логике, нужно делать некоторый mock потока данных через цепочку.

2020-11-02 17:31 UTC, J3FALL commented on core/composer/chain_tune.py
> +        return updated_chain
@nicl-nno Коля, можешь тоже проконсультировать?
Мб у тебя есть идеи, как тут грамотнее делать?

2020-11-02 17:31 UTC, J3FALL commented on core/composer/node.py
> +        :param verbose: flag used for status printing to console, default True
Порядок описания переменных в docstring не соответствует порядку этих переменных в самой номенклатуре функции.

2020-11-02 17:31 UTC, J3FALL commented on core/composer/node.py
> +                                                       max_tune_time=max_lead_time, verbose=verbose)
Поясни, плз, как это тут работает?
Кажется, тут есть ответ на мой вопрос выше (про fine_tune_certain_node), но я не уверен.

2020-11-02 17:31 UTC, J3FALL commented on test/test_chain_import_export.py
> +    assert np.array(assertion_list).all()
Кажется, такую проверку можно упростить при помощи оператора `all()`, посмотри.

2020-11-02 17:31 UTC, J3FALL commented on test/test_chain_tuning.py
`roc_auc_score as roc` не используется, его можно убрать.

2020-11-02 17:31 UTC, J3FALL commented on test/test_chain_tuning.py
> +def test_tune_primary_with_new_logic_correctly(data_fixture, request):
Смущает тема с "new_logic" - просто потому, что после мержа эта логика уже не будет new, по идее )
Я предположу, что т.к. у нас теперь есть 2 механизма тюнинга цепочек, то появилось это "new".
Вообще, я думаю, что от старой версии тюнинга нужно будет избавиться, но прежде - убедиться, что новая действительно работает.

2020-11-02 17:31 UTC, J3FALL commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
Погоди, но это ж не roc_auc, а просто mean_squared_error, округленной до 2 знака после запятой?

2020-11-02 17:31 UTC, J3FALL commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
Да, увидел, что в старых тестах эта ошибка тоже есть, кажется.
Нужно исправить.

2020-11-04 12:43 UTC, BarabanovaIrina commented on core/composer/node.py
> +                                                       max_tune_time=max_lead_time, verbose=verbose)
Ну вот этой функцией _input_from_parents мы получаем для ноды входные параметры для родителей. Если мы хотим затюнить текущую ноду просто, то мы должны по идее иметь просто за-fit-ченную цепочку. Поэтому для того, чтобы получить данные от родителей мы их просто fit-тим. А если нам нужно от текущей ноды протюнить все ноды, то мы родителей тюним. 
Причем это работает пока только для root. Пока что нельзя протюнить кусок цепочки: выбрать ноду и от нее рекурсивно протюнить родителей.

2020-11-04 12:49 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +        Optimize hyperparameters in primary nodes models
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-6f5446535b5cb869f61a505a292f0d9a5248d675a81c0f443c0ff46634f8f261R56)

2020-11-04 12:50 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +        Optimize hyperparameters in the root node
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-6f5446535b5cb869f61a505a292f0d9a5248d675a81c0f443c0ff46634f8f261R105)

2020-11-04 12:50 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +        node.fine_tune(input_data, max_lead_time=max_lead_time, iterations=iterations, recursive=False)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-6f5446535b5cb869f61a505a292f0d9a5248d675a81c0f443c0ff46634f8f261L56-R94)

2020-11-04 13:08 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
Вот тут я вообще споткнулась, потому что приведенный тобой пример с полями класса норм не работает.
Я попыталась воссоздать этот пример, чтобы использовать поля класса и можно было бы использовать хоть как-то для всех подобных случаев, но выглядит это не очень. [Реализация](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-6f5446535b5cb869f61a505a292f0d9a5248d675a81c0f443c0ff46634f8f261R12-R38).
Все потому что condition (как в примере) у нас не глобальная штука, как и логгер. По сравнению с тем, что было, выглядит очень сложно. 
Ну либо я не все поняла. 
Можно, по идее, избавиться от log_decorator и оставить только tune_log_decorator, но тогда выйдет, что if просто переехал. 

На подобные проблемы еще предлагают писать декоратор внутри класса, но я так и не поняла, как работают их примеры (например, [тут](https://www.geeksforgeeks.org/creating-decorator-inside-a-class-in-python/)), потому что первый аргумент автоматически self, а не то, что бы ты хотел передать в декоратор.

2020-11-04 13:08 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +        :return: updated chain object
Исправлено везде

2020-11-04 13:10 UTC, BarabanovaIrina commented on test/test_chain_import_export.py
> +    assert np.array(assertion_list).all()
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-7f68f47b346a0a1d8f530210eed62a0a1056a8791546406a6c06e24115f74b13R281)

2020-11-04 13:10 UTC, BarabanovaIrina commented on test/test_chain_tuning.py
Снова используется

2020-11-04 13:11 UTC, BarabanovaIrina commented on test/test_chain_tuning.py
> +def test_tune_primary_with_new_logic_correctly(data_fixture, request):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-884f19ee7b579f4bf5968f629b7e2ae50b6ecb32d8c6f4bd49cf52c85798d837L131-R131) везде на with_tune_class

2020-11-04 13:11 UTC, BarabanovaIrina commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/b711ae6cf400f52f82be89ba52117a8bab617be8#diff-884f19ee7b579f4bf5968f629b7e2ae50b6ecb32d8c6f4bd49cf52c85798d837L146-R153) везде, где используется классификация.

2020-11-05 14:56 UTC, J3FALL commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
Хм, а мне, в целом, нравится такая штука с декораторами и я набросал пример, как можно изменить текущее решение.
Смотри [тут](https://gist.github.com/J3FALL/220989fccbeda0cc0aa2e067d19fbbee).

2020-11-05 15:01 UTC, J3FALL commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
В данном скрипте, думаю, можно реализовать подобную штуку.
Но вот глобально, я подумал что можно вообще переделать логику "if verbose" во всем фреймворке - если в коде мы хотим что-то залогировать через "self.log.info", то не проверяем, что ключ verbose = True, а тупо логируем.
Однако, в самом начале метода мы проверяем состояние verbose и в зависимости от него выбираем тип логгера: либо тот, который только пишет в лог-файл в папке home, либо тот, который одновременно логирует в консоль + файл. А если log != None, то тут без разницы.

2020-11-05 15:03 UTC, J3FALL commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
В сухом остатке: я заведу под эту задачу, в которой надо будет посмотреть, как verbose реализован в tensorflow (как пример), реализовать еще один дефолтный логер и переписать в ядре логику if verbose.

2020-11-05 15:07 UTC, J3FALL commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
Хм, я подумал, что в целом нет смысла округлять значения здесь, т.к. это не влияет значимо на assert.
Следовательно, можно убрать round, но во всех print-ах делать форматированный вывод (типо `f'{bfr_tun_roc_auc:.2f}'`)

2020-11-06 10:45 UTC, J3FALL commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
Создал [задачу](https://github.com/nccr-itmo/FEDOT/issues/170).

2020-11-06 11:07 UTC, BarabanovaIrina commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
Влияет, потому что даже если в test_tune_certain_node_with_tune_class_correctly поставить округление до 2, тест падает 0.6 > 0.61 (assert False), а если без округления то 0.599... > 0.607... Или надо подбирать такую цепочку, чтобы она давала 100% улучшение во всех тестах.

2020-11-06 12:04 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
[Upd](https://github.com/nccr-itmo/FEDOT/pull/168/commits/6bb5a9f139f09fdf309eeff17a6c27ea75097beb#diff-6f5446535b5cb869f61a505a292f0d9a5248d675a81c0f443c0ff46634f8f261R12-R18).

2020-11-06 12:25 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
К слову посмотрела в tf, там verbose связан с отрисовкой progress bar, проверяется просто через if (но он там единичный)
![Screenshot 2020-11-06 at 15 01 04](https://user-images.githubusercontent.com/29018907/98365920-342a8980-2044-11eb-90d2-aae04e364a89.png)

2020-11-06 14:26 UTC, J3FALL commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
Перенеси тогда start_end_log_decorator из chain_tuning в core/log.
И норм.

2020-11-06 14:32 UTC, J3FALL commented on test/test_chain_tuning.py
> +    aft_tun_roc_auc = round(mse(y_true=test_data.target, y_pred=after_tun_root_node_predicted.predict), 2)
Хм, понял.
Кажется, я однажды уже озвучивал идею про тестирование тюнеров - делать заведомо плохие цепочки для конкретного датасета. Например, можно для тестовой цепочки установить некоторые совсем нереалистичные значения.
Однако, все равно не гарантируется, что точно найдется за заданное время работы теста решение > исходного.
Над этим можно подумать на досуге - как грамотнее тестировать тюнеры.
Заведу под это отдельную таску либо впишу в тех.долг.
Пока тесты оставляем, как они есть.

2020-11-06 17:42 UTC, pep8speaks commented
Hello @BarabanovaIrina! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`core/log.py`](https://github.com/nccr-itmo/FEDOT/blob/eac16ef1dd07b6c956549d4fa90af639c9ea2dcc/core/log.py):

> [Line 129:21](https://github.com/nccr-itmo/FEDOT/blob/eac16ef1dd07b6c956549d4fa90af639c9ea2dcc/core/log.py#L129): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-11-06 17:43 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +            self.log.info('End tuning')
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/168/commits/eac16ef1dd07b6c956549d4fa90af639c9ea2dcc#diff-49dfb86cf6ac6cc7420f7085dc600519245de57bdd34490e2e028c7cde865ff9)

2020-11-10 10:32 UTC, BarabanovaIrina commented on core/composer/chain_tune.py
> +    def fine_tune_certain_node(self, model_id, input_data: InputData, iterations: int = 30,
В целом, я согласна, что не самый красивый способ. Исходила из того, что имеется. 
Предполагалось, что пользователь собирает цепочку не вручную, а при помощи композера. И вроде как пока это процесс не завершится он и знать не будет, что ему в эту цепочку положили, пока не посмотрит ну либо в json, либо на картинку.
Просто для того, что ты предлагаешь, есть проблема. Допустим у меня в цепочке 2 knn. И какой из них какой. 
Но если будем на визуализацию model_index выводить, то вроде как и норм.

2020-11-10 12:27 UTC, J3FALL approved these changes

2020-11-10 16:08 UTC, merged