166 implement atomization of thecomposite model
nccr-itmo/FEDOT pull request #173
Opened 2020-11-10 17:48 UTC by MAGLeb

2020-11-12 16:03 UTC, BarabanovaIrina requested changes

2020-11-12 16:03 UTC, BarabanovaIrina commented on core/models/chain_model.py
> +            raise ValueError(f'Model {model_info.id} not found')
В идеале не хватает двух тестов с положительным и отрицательным исходом (как раз на проверку if условия). Но вот как раз для второго случая я не смогла придумать кейса.

2020-11-12 16:05 UTC, BarabanovaIrina commented
А почему в этом PR оказались коммиты с прошлой задачи?

2020-11-12 16:21 UTC, BarabanovaIrina requested changes

2020-11-12 16:21 UTC, BarabanovaIrina commented on core/composer/node.py
>      :param manual_preprocessing_func: optional function for data preprocessing. \
Тут нужно убрать слеш в конце строки.

2020-11-19 11:11 UTC, MAGLeb commented
> А почему в этом PR оказались коммиты с прошлой задачи?

В личке разобрались, не совсем верно ответвился веткой, но это не при

2020-11-19 14:33 UTC, closed without merging