Api operator
nccr-itmo/FEDOT pull request #179
Opened 2020-11-19 10:43 UTC by v1docq

#115 Impement 'fedot' operator

2020-11-19 10:59 UTC, nicl-nno requested changes

2020-11-19 10:59 UTC, nicl-nno commented on api/api_dataset/regression_test.csv
> +5,1.33,62.57,20.66,8.16,897.9,49.87,0.67,0.047
Выглядит как будто это нужно в cases отправить как отдельный прикладной пример (или в examples, если на полноценный пример оно не тянет). Вроде API тут не при чем.

2020-11-19 10:59 UTC, nicl-nno commented on api/api_pipeline.py
> +                       test_file_path=test_file,
Наверное, не во всех случаях удобно подавать путь на файлы - часто датасет может существовать в виде np-массива в памяти.

Но тут надо подумать, какие есть кейсы для API - и нужно ли сохранять обе альтернативы.

2020-11-19 10:59 UTC, nicl-nno commented on api/run_api.py
> +    case: str = 'Fedot_model'
А что такое case в этом случае?

2020-11-19 10:59 UTC, nicl-nno commented on api/run_api.py
> +class FedotModel:
Как определимся с интерфейсом - надо будет docstring с описанием всех полей добавить.

2020-11-19 10:59 UTC, nicl-nno commented on api/run_api.py
> +        current_model = self.fit()
Наверное нет смысла включать fit в predict - для пользователя более ожидаемо будет, что fit необходимо будет вызвать вручную.

2020-11-19 10:59 UTC, nicl-nno commented on api/api_pipeline.py
> +                       test_file_path=test_file,
Плюс не оч. понятно, как в таком API несколько раз сделать predict на разных данных (в examples как был такой  кейс для iris)

2020-11-19 10:59 UTC, nicl-nno commented on api/run_api.py
> +        #current_model.save_chain("./fitted_chain_convert_to_json.json")
Видимо убрать.

2020-11-19 10:59 UTC, nicl-nno commented on api/utils.py
> +def run_ml_problem(train_file_path,
Это что-то вроде compose_fedot_model скорее.

2020-11-19 10:59 UTC, nicl-nno commented on api/utils.py
> +                   task,
Не везде есть аннотации типов.

2020-11-19 10:59 UTC, nicl-nno commented on api/utils.py
> +    # dataset_to_validate = InputData.from_csv(test_file_path, task=task)
Видимо надо убрать (здесь и далее).

2020-11-19 10:59 UTC, nicl-nno commented on api/api_dataset/predictions.csv
> +,Index,Predicted_value
А это файл нужен? Он вроде генерируется в коде.

2020-11-19 10:59 UTC, nicl-nno commented on api/run_api.py
> +                     'Classification': Task(TaskTypesEnum.classification),
Кмк более привычно такие строковые константы с маленькой буквы начинать. Алсо, можно их как-то сократить, чтобы проще было печатать (reg/class например)

2020-11-19 11:13 UTC, v1docq commented on api/api_dataset/regression_test.csv
> +5,1.33,62.57,20.66,8.16,897.9,49.87,0.67,0.047
отправлю в cases как прикладной пример по химии

2020-11-19 11:15 UTC, v1docq commented on api/run_api.py
> +    case: str = 'Fedot_model'
это будущий функционал для загрузки модели которую сохранил пользователь.Нейминг поменяю

2020-11-19 11:15 UTC, v1docq commented on api/run_api.py
> +        current_model = self.fit()
Окей, вынесу отдельно.

2020-11-19 11:15 UTC, v1docq commented on api/utils.py
> +def run_ml_problem(train_file_path,
Поменял

2020-11-19 11:17 UTC, v1docq commented on api/utils.py
> +                   task,
добавил

2020-11-19 11:17 UTC, v1docq commented on api/utils.py
> +    # dataset_to_validate = InputData.from_csv(test_file_path, task=task)
убрал

2020-11-19 11:17 UTC, v1docq commented on api/api_dataset/predictions.csv
> +,Index,Predicted_value
убрал

2020-11-19 11:17 UTC, v1docq commented on api/run_api.py
> +                     'Classification': Task(TaskTypesEnum.classification),
сделал reg/clf

2020-11-19 11:20 UTC, v1docq commented on api/run_api.py
> +        #current_model.save_chain("./fitted_chain_convert_to_json.json")
убрал

2020-11-19 11:32 UTC, v1docq commented on api/api_pipeline.py
> +                       test_file_path=test_file,
Я подумал что в первой итерации у нас будет вариант с csv файлами как базовый. Для вызова предикта для нескольких данных сделал функционал

2020-11-19 14:59 UTC, J3FALL requested changes

2020-11-19 14:59 UTC, J3FALL commented on api/api_pipeline.py
> +from api.run_api import FedotModel
Ну, сразу бросилось в глаза, что новых тестов на эти функции нет.
Хотя частично эти примеры можно удачно покрыть.

2020-11-19 14:59 UTC, J3FALL commented on api/api_pipeline.py
> +    train_file = r'C:\Users\user\Desktop\FEDOT\cases\data\oil_chemistry\train.csv'
Абсолютные пути - это не очень хорошо.
Нужно исправить их на относительные.

2020-11-19 14:59 UTC, J3FALL commented on api/api_pipeline.py
> +    train_file = r'C:\Users\user\Desktop\FEDOT\cases\data\oil_chemistry\train.csv'
Банально хотя бы потому, что я этот пример у себя локально запустить не могу, т.к. пути отличаются.

2020-11-19 14:59 UTC, J3FALL commented on api/api_pipeline.py
> +    case_name = 'reg'
Почему это case_name, а не task_type, например?

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +class FedotModel:
Здесь, походу, dataclass не особо подходит, т.к. явно нужно добавлять некоторую логику в конструктор.
Например, преобразование ml_task из строкового описания в Task-enum.

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +                      }
Мне кажется, что это должно происходить в конструкторе, а не каждый раз, когда вызывается функция fit/predict.

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +            self.current_model = load_model(self.fedot_model_path)
Мне кажется, идея с флагом не самая удачная - лучше сделать отдельную функцию, которая инициирует объект FedotModel и подгрузит в нее цепочку из указанного файла.
И да, кажется, load_model - это не та функция, которая тебе нужна.

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +class FedotModel:
И мне кажется, что логичнее назвать класс просто Fedot

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +    fedot_model_path: str = './fedot_model.json'
Не хватает поля для метрики качества.

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +    def fit(self):
Метод fit должен принимать features и target в виде numpy-массивов, а внутри должно происходить преобразование их в InputData.

2020-11-19 14:59 UTC, J3FALL commented on api/run_api.py
> +        return metric_value
Пока не уверен, что такая функция будет полезна, но оставляем пока как есть.
После первых изменений еще раз взгляну на эту функцию.

2020-11-19 14:59 UTC, J3FALL commented on api/utils.py
> +        metric_function = MetricsRepository().metric_by_id(RegressionMetricsEnum.RMSE_penalty)
1. У нас еще есть вариант с forecasting-ом временных рядов, про них тоже не стоит забывать.
(Хотя мб для рядов отдельный класс вообще резонно запилить).
2. Но ведь классификация не всегда бинарная?

2020-11-19 14:59 UTC, J3FALL commented on api/utils.py
> +    available_model_types, _ = ModelTypesRepository().suitable_model(task_type=task.task_type)
Кстати, еще один потенциальный внешний параметр, хотя для текущего варианта можем не вытаскивать.
Но, вот suitable_model чаще всего возвращает сразу много моделей, причем некоторые из них могут быть довольно тяжеловесные. И из за них пример с Федотом может долго работать.
Может быть, сделать дополнительную функцию, которая "выбросит" некоторые модели из available_model_types?
Исходя из практики, та же нейронка сильно все замедляет.

2020-11-19 14:59 UTC, J3FALL commented on api/utils.py
> +        ComposerVisualiser.visualise(chain_evo_composed)
Вот это здесь, думаю, не нужно.

2020-11-19 15:01 UTC, nicl-nno commented on api/utils.py
> +        metric_function = MetricsRepository().metric_by_id(RegressionMetricsEnum.RMSE_penalty)
2. ROC AUC умеет и для небинарной классификации выдавать значение.

2020-11-19 15:05 UTC, v1docq commented on api/utils.py
> +        ComposerVisualiser.visualise(chain_evo_composed)
убрал

2020-11-19 15:33 UTC, v1docq commented on api/api_pipeline.py
> +    train_file = r'C:\Users\user\Desktop\FEDOT\cases\data\oil_chemistry\train.csv'
исправил

2020-11-19 15:33 UTC, v1docq commented on api/api_pipeline.py
> +    case_name = 'reg'
исправил

2020-11-19 15:33 UTC, v1docq commented on api/run_api.py
> +                      }
перенес в __init__

2020-11-19 15:33 UTC, v1docq commented on api/run_api.py
> +    fedot_model_path: str = './fedot_model.json'
metric_name добавил параметр

2020-11-19 15:35 UTC, v1docq commented on api/run_api.py
> +    def fit(self):
Не совсем тогда понятно, зачем у нас в data.py сделано все что угодно для того чтобы работать с csv файлом. Типо даже split имеется. Если хотим вытащить наружу сплит данных и подачу array предлагаю новый метод класса data .from_array

2020-11-19 15:36 UTC, v1docq commented on api/run_api.py
> +        return metric_value
Решил убрать это ветвление

2020-11-23 10:59 UTC, v1docq commented on api/utils.py
> +    available_model_types, _ = ModelTypesRepository().suitable_model(task_type=task.task_type)
На данном этапе вытащил настройки композера в задаваемые параметры

2020-11-23 11:00 UTC, v1docq commented on api/run_api.py
> +            self.current_model = load_model(self.fedot_model_path)
переделал функцию

2020-11-23 11:45 UTC, pep8speaks commented
Hello @v1docq! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`test/tasks/test_api.py`](https://github.com/nccr-itmo/FEDOT/blob/f9278734eac9f96ec45b681bb9c831083664f296/test/tasks/test_api.py):

> [Line 52:1](https://github.com/nccr-itmo/FEDOT/blob/f9278734eac9f96ec45b681bb9c831083664f296/test/tasks/test_api.py#L52): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2020-11-23 13:10 UTC, v1docq commented on api/api_pipeline.py
> +from api.run_api import FedotModel
добавил файл test_api

2020-11-23 13:25 UTC, nicl-nno requested changes

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +    return fedot_model
А зачем нужен этот метод, почему эту же логику не спрятать внутри Fedot?

Тем более что экземпляр Fedot - это совсем не fedot model, упомянутая в названии переменной.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +                     'cluster': Task(TaskTypesEnum.clustering)
Обсуждали про временные ряды ещё. 
Если с ними какие-то сложности - можно хотя бы выводить сообщение, что они not supported в API пока.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +                             }
Если добавлять cluster - то и метрика для него нужна.

2020-11-23 13:25 UTC, nicl-nno commented on api/utils.py
> +    available_model_types, _ = ModelTypesRepository().suitable_model(task_type=task.task_type)
Да, но возможность управлять именно available_model_types от этого вроде как не появилась.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +            'learning_time': 5}
Я лично не вижу особого смысла выносить столько внутренних параметров - для этого можно и вручную композер создать. 

Но при этом learning_time - параметр довольно часто используемый и достойный выноса в API.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +                save_model: bool = False):
Зачем save model нужен в predict? Я бы вообще его отдельным методом Fedot вынес.

2020-11-23 13:25 UTC, nicl-nno commented on api/api_pipeline.py
> +if __name__ == '__main__':
А весь этот пример вообще нужен? Он не дублирует тест?  

Если нужен - то в examples его надо отправить.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +                 current_model: Chain = None):
А это нужно? Вряд ли пользователь вручную откуда-то получит Chain за пределами API.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +            csv_path: str = None):
Может вместо явного csv_path сделать возможность в features прописывать str-путь к csv а target - название столбца? И далее разделять по типам.

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +                target: np.array = None,
А зачем для предикта таргет?

2020-11-23 13:25 UTC, nicl-nno commented on api/run_api.py
> +        self.metric_name = metric_name
Вроде такой аргумент есть и у метода quality_metric - зачем он ещё и в конструкторе класса?

2020-11-23 13:25 UTC, nicl-nno commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
В тестах уже есть какие-то датасеты для регресии - лучше их используй, чтобы не усложнять взаимодействие между модулями.

2020-11-23 13:39 UTC, v1docq commented on api/run_api.py
> +                save_model: bool = False):
вынес отдельным методом

2020-11-23 13:39 UTC, v1docq commented on api/api_pipeline.py
> +if __name__ == '__main__':
оставил только test_api

2020-11-23 13:40 UTC, v1docq commented on api/run_api.py
> +                 current_model: Chain = None):
убрал

2020-11-23 13:40 UTC, v1docq commented on api/run_api.py
> +            csv_path: str = None):
поменял логику

2020-11-23 13:41 UTC, v1docq commented on api/run_api.py
> +        self.metric_name = metric_name
убрал

2020-11-23 13:43 UTC, v1docq commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
исправил

2020-11-23 13:49 UTC, nicl-nno commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
Ставь плз в ответах ссылки на код в коммитах - а то кода много, уже сложно разбираться.

2020-11-23 13:50 UTC, nicl-nno commented on test/tasks/test_api.py
> +    model_baseline.predict(features=X_test,
Тут все X-переменные нарушают pep8-нотацию своим названием.

2020-11-23 14:05 UTC, v1docq commented on api/run_api.py
> +    return fedot_model
спрятал логику в федоте

2020-11-23 14:56 UTC, v1docq commented on api/run_api.py
> +    return fedot_model
https://github.com/nccr-itmo/FEDOT/pull/179/commits/f4b2e61c0aa818c5bd481fe1d9b937c82eb512ff

2020-11-23 15:01 UTC, v1docq commented on api/run_api.py
> +                     'cluster': Task(TaskTypesEnum.clustering)
` task_dict = {'reg': Task(TaskTypesEnum.regression),
                     'clf': Task(TaskTypesEnum.classification),
                     'cluster': Task(TaskTypesEnum.clustering),
                     'time_series': Task(TaskTypesEnum.ts_forecasting)
                     }
        basic_metric_dict = {'reg': 'RMSE',
                             'clf': 'ROCAUC',
                             'cluster': 'Silhouette',
                             'time_series': 'RMSE'
                             }`

2020-11-23 15:03 UTC, v1docq commented on api/run_api.py
> +                             }
```
        basic_metric_dict = {'reg': 'RMSE',
                             'clf': 'ROCAUC',
                             'cluster': 'Silhouette',
                             'time_series': 'RMSE'
                             }
```

2020-11-23 15:05 UTC, v1docq commented on api/run_api.py
> +            'learning_time': 5}
предлагаю пока оставить такой пак конфигурируемых настроек, т.к. глубина и ширина итоговой композитной модели выглядят как параметры которыми хочется управлять, плюс это косвенное управление сложностью итоговой модели.

2020-11-23 15:06 UTC, v1docq commented on api/run_api.py
> +            csv_path: str = None):
```
        if type(features) == np.ndarray:
            self.test_data = array_to_input_data(features_array=features,
                                                 target_array=target,
                                                 task_type=self.ml_task)
        elif type(features) == str:
            self.test_data = InputData.from_csv(features, task=self.ml_task, target_column=target)
```

2020-11-23 15:08 UTC, v1docq commented on api/run_api.py
> +    return fedot_model
https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R29-R33

2020-11-23 15:10 UTC, v1docq commented on api/run_api.py
> +                             }
https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R34-R38

2020-11-23 15:14 UTC, v1docq commented on api/run_api.py
> +            csv_path: str = None):
[text](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R76-R83)

2020-11-23 15:17 UTC, v1docq commented on api/run_api.py
> +                target: np.array = None,
Пока мне кажется логичней формировать тестовый датасет во время вызова предикта, а в quality_metrics просто перебирать итоговые метрики качества.Если у нас есть готовый тестовый датасет на этапе предикта, я могу сделать сверху кучи функциональности-от визуала до процессинга, еще до вызова метрики качества. Но если нужно, можно перенести этап создания тестового датасета в quality metrics.

2020-11-23 15:19 UTC, v1docq commented on test/tasks/test_api.py
> +    model_baseline.predict(features=X_test,
[исправил](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-dbd9bbb24dfc1e5a4c76059e9d06359995437c388110144c74bdbc18f7ab2b6aR29-R30)

2020-11-23 15:30 UTC, nicl-nno commented on api/run_api.py
> +            'learning_time': 5}
Ну вот как раз выглядит, как будто обычному пользователю в большинстве случаев без разницы, какая ширина и глубина будет у модели.

Пак настроек оставить можно, но нужно возможность подавать вручную только часть их них, а не требовать все разом.

2020-11-23 15:34 UTC, nicl-nno commented on api/run_api.py
> +            print('Please specify a features as path to csv file or as Numpy array')
Выглядит как будто в fit и predict это код дублируется.

2020-11-23 15:34 UTC, nicl-nno commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
>тк для регрессии у нас только 1 датасет и не очень удобный

А в чем это неудобство проявляется с т.з. теста на API?

2020-11-23 15:37 UTC, nicl-nno commented on api/run_api.py
> +                target: np.array = None,
Мне кажется это несколько неинтуитивно для пользователя. 
Логичнее в quality_metrics делать predict на размеченных данных и сравнивать.
А визуалльный анализ качества предсказания и т.д. разрешать делать только после вызова quality_metrics.

2020-11-23 15:38 UTC, nicl-nno commented on api/run_api.py
> +            csv_path: str = None):
Кмк тобы было понятнее, стоит в аннотациях прописать оба возможных типов данных - и str, и nd.array (через Union)

2020-11-24 10:43 UTC, v1docq commented on api/run_api.py
> +            print('Please specify a features as path to csv file or as Numpy array')
[исправил](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R21-R38)

2020-11-24 10:44 UTC, v1docq commented on api/run_api.py
> +                target: np.array = None,
[исправил](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R92-R102)

2020-11-24 10:44 UTC, v1docq commented on api/run_api.py
> +            csv_path: str = None):
[исправил](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R84-R86)

2020-11-24 10:45 UTC, v1docq commented on api/run_api.py
> +            'learning_time': 5}
[исправил](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R9-R18) и [вот тут](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-dbd9bbb24dfc1e5a4c76059e9d06359995437c388110144c74bdbc18f7ab2b6aR9-R11)

2020-11-24 10:47 UTC, v1docq commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
для API есть уже поделенный на 2 csv файла датасет, который я делил и точно знаю какие там должны быть ответы и метрики.

2020-11-27 18:02 UTC, nicl-nno commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
Тогда ввкинь копии этих файлов (сокращенные, если нужны) в тесты - чтобы они были автономны и не зависили от кейсов.

2020-11-30 09:09 UTC, nicl-nno commented on api/run_api.py
> +                             }
Но эти метрики же должны использоваться только внутри def quality_metric?

А там Silhouette никак не обрабатывается - хотя бы как NonImplemented.

2020-11-30 10:50 UTC, v1docq commented on api/utils.py
> +    available_model_types, _ = ModelTypesRepository().suitable_model(task_type=task.task_type)
[добавил пока в таком формате](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-1927a2a7260bf138319644bceb09095e47b82f13b79db71504801f8705c00394R56-R61)

2020-11-30 10:51 UTC, v1docq commented on api/run_api.py
> +                             }
[такой вариант](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-885b4ca1e537ef03126394aa821e40d71bc31c63b4681628db722dd3f7c8f308R116-R129)

2020-11-30 10:51 UTC, v1docq commented on test/tasks/test_api.py
> +    file_path_test = 'cases/data/oil_chemistry/test_1.csv'
закинул в папку тест

2020-12-18 09:41 UTC, J3FALL requested changes

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +            'learning_time': learning_time}
Мне кажется это не логичным, когда функция называется default_evo_params, но, по-факту она принимает на вход значения параметров, которые потом окажутся в словаре. Т.е. пользователь может поменять дефолтные параметры композера, что как-то странно.
Вижу тут 2 возможных решения:
1. Реализовать костанту-словарь DEFAULT_EVO_PARAMS и уже функция default_evo_params будет его возвращать.
2. Реализовать функцию, которая составляет словарь параметров по их переданным значениям (как сейчас в default_evo_params), а уже в default_evo_params будет так:
```
def default_evo_params():
   return params_dict(max_depth=3, max_arity=3, ....)
```

2020-12-18 09:41 UTC, J3FALL commented on test/tasks/test_api.py
> +test_api_advanced()
Этого здесь точно быть не должно, иначе pytest запустит тесты в этом скрипте несколько раз.

2020-12-18 09:41 UTC, J3FALL commented on test/tasks/test_api.py
> +def test_api_baseline():
Что означает test_api_baseline?
По названию функции не очевидно, что там проверяется.

2020-12-18 09:41 UTC, J3FALL commented on test/tasks/test_api.py
> +    model_advanced.predict(features=test)
Функции fit/predict возвращают либо модель, либо предсказанные значения.
Неплохо было бы это в тестах отразить.

2020-12-18 09:41 UTC, J3FALL commented on test/tasks/test_api.py
> +from sklearn.model_selection import train_test_split
Ну, мне кажется, тестов маловато:
1. Как минимум, не покрыты функции save_model и quality_metric.
2. Не по всем задачам есть тесты (даже если clustering и ts-forecasting не поддерживается сейчас).
3. Отсутствуют тесты на check_data_type.
4. Можно проверить логику работы с разными типами данных, неправильных путей до файлов и т.д.

2020-12-18 09:41 UTC, J3FALL commented on api/utils.py
> +    return fitted_model
Эту функцию можно удалить.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +            self.composer_params = {**default_evo_params(), **self.composer_params}
Вот эту строчку не понял, как это работает?
Если composer_params явно заданы и передаются в конструкторе, то надо же просто сделать:
`self.composer_params = composer_params`
Или я ошибаюсь?

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +            self.composer_params = {**default_evo_params(), **self.composer_params}
Кстати, когда мы имеем дело со словарем, его нужно еще и валидировать, чтобы, как минимум, все его ключи соответствовали ожидаемому поведению.
Грубо говоря, нужна функция:
```
def __validate_given_composer_params(params):
  for param in expected_params:
      if param not in params.keys():
          raise Exception(f'Expected param {param} was not found in a given composer params')
```

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +                             }
1. clf - имхо, плохое сокращение. Лучше уж classification полностью.
2. time_series - тут не понятно, что имеется в виду. Time series - это тип данных, а не задачи. Тут явно имелось в виду ts_forecasting, значит это и нужно указать.
3. Может быть, добавим доп. эвристику-функцию, которая для бин. классификации использует  метрику ROC_AUC, а для > 2 классов - confusion matrix/f1?
Для, для многоклассовой можно и ROC_AUC считать, но не кажется ли вам, что пользователь этого явно не ожидает? Вроде для нас не сложно добавить функцию, которая посчитает число классов в датасете и выберет метрику в зависимости от его значения.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +            print('This type of task is not not supported in API now')
В проекте есть logging, рекомендую им пользоваться.
Пример можно посмотреть в композере, моделях или нодах.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +class Fedot(object):
Зачем наследоваться от object?

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +    def _get_model(self):
Предлагаю тогда поменять название функции на _obtain_model.
Вроде мелочь, но мне почему-то кажется, что get - это процедура быстрая, почти мгновенная. Как запрос в БД.
А у нас тут цепочка подбирается, что звучит тяжелее.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +        if self.current_model is None:
Логичнее все поля класса инициализировать в конструкторе.
Т.е. в конструкторе не хватает: `self.current_model = None`

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +            print('This quality metric is not available now')
Логирование.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +                                                            predicted=self.predicted), 3)
Округлять точно здесь нужно?
Мб пусть уже снаружи округление происходит?

2020-12-18 09:41 UTC, J3FALL commented on api/utils.py
> +import datetime
На функции в этом скрипте также не увидел тестов.

2020-12-18 09:41 UTC, J3FALL commented on api/run_api.py
> +    return data
1. Тут получается not consistent output - либо в любом из вариантов нужно возвращать экземпляр data, либо в одном из случаев выбрасывать исключение.
2. Нужно использовать логирование.

2020-12-18 09:41 UTC, J3FALL commented on api/utils.py
> +        available_model_types = [model for model in available_model_types if model not in heavy_models]
Извлеки это в отдельную функцию, плз.
Назвать его можно, например: only_light_model_types.

2020-12-18 09:41 UTC, J3FALL commented on api/utils.py
> +        metric_function = MetricsRepository().metric_by_id(RegressionMetricsEnum.RMSE_penalty)
Отписался комментами в другом месте, но продублирую:
"Может быть, добавим доп. эвристику-функцию, которая для бин. классификации использует метрику ROC_AUC, а для > 2 классов - confusion matrix/f1?
Для, для многоклассовой можно и ROC_AUC считать, но не кажется ли вам, что пользователь этого явно не ожидает? Вроде для нас не сложно добавить функцию, которая посчитает число классов в датасете и выберет метрику в зависимости от его значения."

2020-12-18 09:41 UTC, J3FALL commented on api/utils.py
> +        metric_function = MetricsRepository().metric_by_id(RegressionMetricsEnum.RMSE_penalty)
Еще есть одна потенциальная проблема - metric_function не всегда может быть инициализирована, из-за чего может сломаться GPComposerBuilder.
Кажется, воспроизводится это легко - если передать task = TaskTypesEnum.ts_forecasting.

2020-12-18 09:43 UTC, J3FALL commented
@v1docq Илья, не забудь еще перенести скрипты из api в fedot/api, предварительно создав там новый модуль api.

2020-12-18 10:24 UTC, nicl-nno commented on api/run_api.py
> +                             }
>доп. эвристику-функцию, которая для бин. классификации использует метрику ROC_AUC, а для > 2 классов - confusion matrix/f1?

А есть примеры каких-то решений, где это используется? В TPOT есть вот такие варианты:

![image](https://user-images.githubusercontent.com/5711814/102603803-58de4a80-4134-11eb-81a3-7cd0345ea5ee.png)

2020-12-18 10:28 UTC, nicl-nno commented on api/utils.py
> +                        model_complexity: str = None,
Кстати, может назвать это поле не model complexity, а configuration?

Вот тут в разделе Built-in TPOT configurations описано, какие конфигурации есть у TPOT: https://epistasislab.github.io/tpot/using/
Выглядит, как будто имеется в виду тоже, что и у нас, но есть возможность более гибкого выбора - и поэтому название логичнее.

2020-12-24 18:44 UTC, v1docq commented on api/run_api.py
> +                                                            predicted=self.predicted), 3)
убрал

2020-12-24 18:44 UTC, v1docq commented on api/utils.py
> +    return fitted_model
удалил

2020-12-24 18:44 UTC, v1docq commented on test/tasks/test_api.py
> +test_api_advanced()
убрал

2020-12-24 19:37 UTC, v1docq commented on api/run_api.py
> +            'learning_time': learning_time}
[исправил таким образом](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR10-R28)

2020-12-24 19:38 UTC, v1docq commented on api/run_api.py
> +    return data
[исправил таким образом. Добавил возможность передавать данные в формате федота и поставил вывод исключения в случае некорректного формата.](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR30-R50)

2020-12-24 19:38 UTC, v1docq commented on api/run_api.py
> +class Fedot(object):
убрал

2020-12-24 19:39 UTC, v1docq commented on api/run_api.py
> +            self.composer_params = {**default_evo_params(), **self.composer_params}
[идея в том что пользователь может не передать весь пак параметров для оптимизации и я просто обновляю словарь и те которые он не предела оставляю по дефолту](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR70-R75)

2020-12-24 19:41 UTC, v1docq commented on api/utils.py
> +        metric_function = MetricsRepository().metric_by_id(RegressionMetricsEnum.RMSE_penalty)
[сделал такую функцию для случая бинарной классификации](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR105-R109) и здесь [сделал словарь для иницилизации метрики](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-4468edce3bc1000654a1d60aef819bd6aa0d7dcf2bf77cafdc7a162e2bfc8bfbR15-R24)

2020-12-24 19:44 UTC, v1docq commented on api/run_api.py
> +    def _get_model(self):
[исправил здесь](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR100-R103)

2020-12-24 19:45 UTC, v1docq commented on api/run_api.py
> +            print('This type of task is not not supported in API now')
[здесь](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-bcf53e7adc1235e40fcba1bb649acea62c8fd2cfd732281ca2b3cea89c5e295bR66-R70)

2020-12-24 19:53 UTC, J3FALL commented on fedot/api/run_api.py
> +            self.metric_name = 'F1'
Так наоборот же, если >2 классов - то нужно F1?

2020-12-24 19:53 UTC, J3FALL commented on fedot/core/models/evaluation/ensembling.py
> +    }
Коммент на некст задачи - нужно будет это протестить.

2020-12-24 19:53 UTC, J3FALL commented on test/tasks/test_api.py
> +    return train_data, test_data, threshold
Да разбил бы на разные функции, ничего такого вроде)

2020-12-24 19:55 UTC, J3FALL commented on api/run_api.py
> +                             }
да можно и всегда считать accuracy/precision/f1.
Просто странно, что для не-бинарной классификации используется roc_auc.
Это меня и смущает.

2020-12-24 19:57 UTC, nicl-nno commented on api/run_api.py
> +                             }
В automlbenchmnark по умолчанию в многоклассовых случаах используется logloss к слову (для iris)

![image](https://user-images.githubusercontent.com/5711814/103104927-74b58500-463b-11eb-8105-3a404f5730a3.png)

2020-12-24 19:58 UTC, J3FALL commented
Кстати, обратите внимание, что чет не все тесты как-будто отрабатывают.

2020-12-24 20:14 UTC, v1docq commented on api/utils.py
> +        available_model_types = [model for model in available_model_types if model not in heavy_models]
[исправил здесь](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-4468edce3bc1000654a1d60aef819bd6aa0d7dcf2bf77cafdc7a162e2bfc8bfbR45-R55)

2020-12-24 20:14 UTC, v1docq commented on test/tasks/test_api.py
> +from sklearn.model_selection import train_test_split
полностью переписал тесты

2020-12-24 20:14 UTC, v1docq commented on test/tasks/test_api.py
> +    model_advanced.predict(features=test)
[исправил здесь](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-dbd9bbb24dfc1e5a4c76059e9d06359995437c388110144c74bdbc18f7ab2b6aR59-R70)

2020-12-24 20:14 UTC, v1docq commented on test/tasks/test_api.py
> +def test_api_baseline():
убрал

2020-12-24 20:15 UTC, v1docq commented on fedot/core/models/evaluation/ensembling.py
> +    }
Ок. Я случайно как то убрал твой коммент, насчет словаря.

2020-12-24 20:15 UTC, v1docq commented on api/utils.py
> +                        model_complexity: str = None,
[пока так предлагаю](https://github.com/nccr-itmo/FEDOT/pull/179/files#diff-4468edce3bc1000654a1d60aef819bd6aa0d7dcf2bf77cafdc7a162e2bfc8bfbR45-R54)

2020-12-24 20:19 UTC, nicl-nno commented on fedot/core/models/evaluation/ensembling.py
> +    }
Эм, это из коммитов из PR про кластеризацию - а зачем они тут?

2020-12-24 20:24 UTC, v1docq commented on test/tasks/test_api.py
> +    return train_data, test_data, threshold
я хотел сделать на будущее задел  для генерации данных под задачи

2020-12-24 21:31 UTC, v1docq commented on fedot/core/models/evaluation/ensembling.py
> +    }
честно не заметил как они сюда просочились, видимо ребейз некорректно сделался

2020-12-24 21:31 UTC, v1docq commented on fedot/api/run_api.py
> +            self.metric_name = 'F1'
исправил

2021-01-12 09:46 UTC, nicl-nno commented on fedot/api/utils.py
> +    custom_models_dict = {'Light': ['mlp', 'svc'],
Лучше с маленькой буквы ключи, чтобы было как везде.

Ну и стоит назвать в стиле excluded_models_dict.

2021-01-12 09:47 UTC, nicl-nno commented on fedot/core/composer/metrics.py
> +        return chain.length / norm_constant
Поправь тут и ниже проблемы с нехваткой пустых строк, про которые PEP8-бот написал.

2021-01-12 10:04 UTC, nicl-nno commented
Раз более-менее сошлись по поводу структуры API - нужно добавить страницу с документацией по нему (хотя бы краткую для начала) и вставить пример в README.

2021-01-12 11:35 UTC, v1docq commented on fedot/core/composer/metrics.py
> +        return chain.length / norm_constant
Поправил

2021-01-12 11:35 UTC, v1docq commented on fedot/api/utils.py
> +    custom_models_dict = {'Light': ['mlp', 'svc'],
Исправил

2021-01-13 15:39 UTC, J3FALL requested changes

2021-01-13 15:39 UTC, J3FALL commented on README.rst
> +The fit method returns a composite model, the predict method returns a Numpy array with predicted values, and the quality_metric method returns the quality metric value obtained for this task and the
Initialize Fedot object with parameters. It provides a ML-popular _fit/predict_ interface:
- _fedot.fit_ runs optimization and returns the resulted composite model
- _fedot.predict_ returns the predictied values for a given features
- _fedot.quality_metric_ calculates the quality metrics of predictions

2021-01-13 15:39 UTC, J3FALL commented on fedot/api/run_api.py
> +from typing import Union
Не забудь поменять fedot/api - вместо директории нужно создать python-модуль (чтобы в нем был скрипт __init__.py)

2021-01-14 09:22 UTC, v1docq commented on fedot/api/run_api.py
> +from typing import Union
Сделал

2021-01-14 09:23 UTC, v1docq commented on README.rst
> +The fit method returns a composite model, the predict method returns a Numpy array with predicted values, and the quality_metric method returns the quality metric value obtained for this task and the
Исправил

2021-01-14 09:23 UTC, v1docq commented on README.rst
> +1. Import the Fedot class
Исправил

2021-01-14 11:22 UTC, J3FALL commented on README.rst
> +1. Import the Fedot class
Почему **the** Fedot?)

2021-01-14 11:25 UTC, J3FALL requested changes

2021-01-14 11:25 UTC, J3FALL commented on fedot/api.py
> +from typing import Union
Кажется, ты меня неправильно понял)

Нужно просто создать в  пакете fedot отдельный python-package "api" и в него засунуть скрипты api.py и api_utils.py.

2021-01-14 13:29 UTC, J3FALL approved these changes

2021-01-14 13:35 UTC, nicl-nno approved these changes

2021-01-15 09:28 UTC, merged