PyPi release
nccr-itmo/FEDOT pull request #180
Opened 2020-11-19 13:57 UTC by BarabanovaIrina

New structure of the framework is provided for PyPi release.

FEDOT
├── LICENSE
├── README.md
├── fedot
│   └── __init__.py
│   └── core
│   └── utilities
├── setup.py
└── tests
└── docs
Test version of the fedot is located in the test.pypi.org: 
https://test.pypi.org/project/fedot/0.1.1/ (do not pay attention to version)

Use command to check the installation:
pip install -i https://test.pypi.org/simple/ --no-deps fedot==0.1.1

--no-deps used because test.pypi might not have the proper packages to install

![Screenshot 2020-11-19 at 16 45 04](https://user-images.githubusercontent.com/29018907/99675277-13bcef00-2a88-11eb-81c6-b9fa62d2ceae.png)
Main file for release: setup.py

README.rst installation section was changed to: pip install fedot

2020-11-19 14:17 UTC, nicl-nno commented
А нет смысла utilities внести внутрь core, чтобы не было необходимости создавать доп. папку fedot и менять все import-ы? 
Или все равно нужна папка с тем же именем, что и pypi_пакет?

2020-11-19 14:19 UTC, BarabanovaIrina commented
> А нет смысла utilities внести внутрь core, чтобы не было необходимости создавать доп. папку fedot и менять все import-ы?
> Или все равно нужна папка с тем же именем, что и pypi_пакет?

Да, нужна именно папка с таким именем. Потому что название в setup.py мы можем дать какое захотим, чтобы скачивать. А вот во время import fedot цепляется именно директория.

2020-11-19 15:08 UTC, J3FALL requested changes

2020-11-19 15:08 UTC, J3FALL commented on README.rst
Смотри: я предлагал добавить в installation дополнительный раздел - for developers/contributors.
В него перенести текущий вариант installation.
А в начале - упрощенный вариант с "pip install fedot"

2020-11-19 15:08 UTC, J3FALL commented on setup.py
> +SHORT_DESCRIPTION = "Knowledge-enriched AutoML framework FEDOT"
@nicl-nno Коля, что думаешь насчет "Knowledge-enriched" - это еще актуально или мб что-то другое придумаем?
Что-нибудь связанное со structure learning, evolutionary algorithms, gp, etc.?

2020-11-19 15:14 UTC, nicl-nno commented on setup.py
> +SHORT_DESCRIPTION = "Knowledge-enriched AutoML framework FEDOT"
Мб "Automated modelling framework FEDOT"?

Ну или действительно что-то вроде "Evolutionary stuctural learning framework FEDOT"

2020-11-19 15:58 UTC, J3FALL commented on setup.py
> +SHORT_DESCRIPTION = "Knowledge-enriched AutoML framework FEDOT"
Ок, мне в целом нравится эта версия.

2020-11-19 21:58 UTC, BarabanovaIrina commented on README.rst
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/180/commits/cbf86b072b6d88c4b09881bcf2b8efbfb0d3eb48#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR33-R41)

2020-11-19 21:58 UTC, BarabanovaIrina commented on setup.py
> +SHORT_DESCRIPTION = "Knowledge-enriched AutoML framework FEDOT"
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/180/commits/cbf86b072b6d88c4b09881bcf2b8efbfb0d3eb48#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R17)

2020-11-20 11:13 UTC, J3FALL commented on README.rst
Немного исправил

2020-11-20 11:19 UTC, J3FALL approved these changes

2020-11-20 16:46 UTC, merged