Sensitivity
nccr-itmo/FEDOT pull request #192
Opened 2020-12-02 13:48 UTC by BarabanovaIrina

На данный момент ноду в цепочке можно:
- Просто удалить с сохранением ее поддерева
- Затюнить
- Заменить на ноды:
    - кастомные (передать список напрямую)
    - рандомные (передать количество нод, которые хотелось бы сгенерить)

2020-12-02 13:48 UTC, pep8speaks commented
Hello @BarabanovaIrina! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/composer/chain.py`](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/fedot/core/composer/chain.py):

> [Line 182:13](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/fedot/core/composer/chain.py#L182): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 190:13](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/fedot/core/composer/chain.py#L190): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '













* In the file [`test/test_sensitivity.py`](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/test/test_sensitivity.py):

> [Line 89:13](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/test/test_sensitivity.py#L89): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 105:13](https://github.com/nccr-itmo/FEDOT/blob/c1574396879f53c637bb6569874c8470692ef755/test/test_sensitivity.py#L105): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2021-01-28 15:49 UTC, BarabanovaIrina commented
Добавила (пока что) вшитую функцию визуализации: boxplot параметра + loss (отсылка к осенним обсуждениям)
Проблема в том, что например n_estimators в xgb целые числа [10, 100], а например learning_rate [0., 1.]. Попыталась сделать нормализацию, чтобы на одном графике разместить все параметры, но пока дела не очень.
@J3FALL нужна консультация
![xgboost_sa](https://user-images.githubusercontent.com/29018907/106162623-5e01d100-6199-11eb-893a-fffa63d8810f.jpg)

Запуск на 10 самплах для каждого параметра по-отдельности.

2021-01-28 16:09 UTC, nicl-nno commented
А что тут по оси Y - разброс параметров или разброс loss?

Если первое - можно вертикальную шкалу в % размечать. Например,  Y_relative = (Y-Ymean)/(Ymax-Ymin) или что-то такое.

2021-01-28 16:14 UTC, BarabanovaIrina commented
> А что тут по оси Y - разброс параметров или разброс loss?
и то и то, возможно это неправильно. То есть: сначала boxplot с разбросом значений параметров, а за ним следом boxplot с разбросом loss (mse)

2021-01-28 16:19 UTC, nicl-nno commented
Тогда есть смысл оба выражать в % от дефолтного значения и должно быть норм.

Как тут: IN - параметры, OUT - качество модели

![image](https://user-images.githubusercontent.com/5711814/106166859-a6bb8900-619d-11eb-857f-40f088022c30.png)

2021-02-01 08:39 UTC, BarabanovaIrina commented
delta_a = (a_new - a_default) / a_default - 100% (не поняла правда, почему минус 100)
![xgboost_sa](https://user-images.githubusercontent.com/29018907/106433883-d5797e00-6481-11eb-8fb2-650de24e9633.jpg)
(10 запусков)

2021-02-25 15:58 UTC, J3FALL requested changes

2021-02-25 15:58 UTC, J3FALL commented on fedot/core/chains/chain.py
> +                isinstance(old_node, PrimaryNode) and isinstance(new_node, SecondaryNode):
Я ведь корректно понимаю, что, заменяя старую ноду на новую, у них должен совпадать класс?
Т.е. primary заменяем на primary, или secondary заменяем на secondary.
Если нет, то выкидываем эксепшен.

Т.е. можно заменить эту конструкцию на:
`if type(old_node) is not type(new_node)`

Проверил - работает: 
![image](https://user-images.githubusercontent.com/7864250/109172869-46b40480-7794-11eb-8e1b-3eab1535d3c5.png)

2021-02-25 15:58 UTC, J3FALL commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Немного запутано получилось, но пока у меня нет предложений, как это можно упростить.
Оставлю коммент, чтобы не забыть внести операции с узлами как потенциальное место для рефакторинга.

2021-02-25 15:58 UTC, J3FALL commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Еще, кстати, возникла возможная идея - выделить операции, связанные со структурой цепочки в отдельный интерфейс.

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    degrees = [degree[1] for degree in graph.degree]
А почему degree[1] ?

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +                 all_nodes: bool = False, path_to_save=None):
А можешь еще docstring для документации добавить?
Модуль выглядит достаточно зрело уже с точки зрения реализации.

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +            raise ValueError("Choose only one parameter between all_nodes and nodes_ids_to_analyze")
Хм, а вроде же в методе analyze подобная проверка тоже есть?
Мб тогда либо параметр all_nodes вытащить в analyze, либо сделать его опциональным тут.

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
Как предложение: добавить возможность интерактивно выводить на экране все графики в виде subplot-ов.
При условии, если юзер задал такой параметр.
По умолчанию - сохранять на диск и писать в лог об этом.

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +                             f'{self.approaches[index].__name__}.jpg'))
Тут можно извлечь переменную.

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +                             f'{self.approaches[index].__name__}_cor.jpg'))
Тут тоже можно упростить

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +                                                       path_to_save=self.result_dir).analyze(node_id=node_id)
Я думаю, можно в реализации класса NodeAnalysis добавить поле analysis_name/label и его переопределять.
Так надежнее, имхо, чем брать системное название через __name__

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +    def __init__(self, chain: Chain, train_data, test_data: InputData, path_to_save=None):
Здесь тоже можно docstring добавить, думаю

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +                                                       path_to_save=self.result_dir).analyze(node_id=node_id)
А, погоди, там ведь __str__ и так переопределен вроде.
А зачем тогда через __name__ вытаскивать название?

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +        super(NodeTuneAnalyze, self).__init__(chain, train_data, test_data, path_to_save)
А для чего в super передавать класс?

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +        del samples
Это нужно, или оно появилось в ходе дебага?

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +                node_type = SecondaryNode
Кажется, можно сократить до:
`if type(self._chain_nodes[node_id]) is in [Primary, Secondary]`

2021-02-25 15:58 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +                node_type = SecondaryNode
Ну или сразу присвоить node_type и проверить после

2021-02-25 15:58 UTC, J3FALL commented on fedot/utilities/define_metric_by_task.py
> +        except ValueError:
А в каких случаях возможен ValueError?

2021-02-25 15:58 UTC, J3FALL commented on test/unit/chains/test_chain.py
> +def test_cahin_repr():
кажется, тут опечатка

2021-02-25 15:58 UTC, J3FALL commented on test/unit/test_sensitivity.py
> +# @patch('fedot.sensitivity.chain_sensitivity.ChainStructureAnalyze.analyze', return_value={'key': 'value'})
Патч не сработал или в чем была идея?

2021-02-26 14:51 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +    degrees = [degree[1] for degree in graph.degree]
Потому что graph.degree - это [(node_index, degree),(),...]

2021-02-26 17:20 UTC, BarabanovaIrina commented on test/unit/test_sensitivity.py
> +# @patch('fedot.sensitivity.chain_sensitivity.ChainStructureAnalyze.analyze', return_value={'key': 'value'})
Патч сработал, но с патчем codecov не засчитывает за покрытие.

2021-03-01 12:24 UTC, BarabanovaIrina commented on examples/chain_sensitivity.py
> +            chain = get_three_depth_manual_regr_chain()
[Добавлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-f6705f8cc2086a36b5564f9c58bd22a2236441fa8b26ee88c1cca28e851eca64R112-R128)

2021-03-01 12:26 UTC, BarabanovaIrina commented on examples/chain_sensitivity.py
> +        makedirs(result_path)
[Добавлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-f6705f8cc2086a36b5564f9c58bd22a2236441fa8b26ee88c1cca28e851eca64R126)

2021-03-01 12:26 UTC, BarabanovaIrina commented on examples/chain_sensitivity.py
> +def run_analysis_case(train_data: InputData, test_data: InputData, case_name: str, task, metric, is_composed=False):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-f6705f8cc2086a36b5564f9c58bd22a2236441fa8b26ee88c1cca28e851eca64R125-R126)

2021-03-01 12:27 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +                isinstance(old_node, PrimaryNode) and isinstance(new_node, SecondaryNode):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR183-R186)

2021-03-01 12:53 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Да, тут у меня были такие варианты: либо одну из родительских нод(например, первую в списке родителей) ставить на место старой, либо вот так как есть - все ноды детей ко всем родителям для сохранения всех путей, которые раньше были через посредника (удаленную ноду). 

Однако, я поискала, как вообще решают такие ситуации и сходу нашла [данный](https://stackoverflow.com/questions/8780593/how-to-delete-all-related-nodes-in-a-directed-graph-using-networkx/8790886) пример, в котором говорится, что "сироты на удаление": если у детей больше нет родителей, кроме удаляемой йоды, то они тоже должны быть удалены.

2021-03-01 12:55 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +                 all_nodes: bool = False, path_to_save=None):
[Добавлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R22-R38)
Но еще не добавлена в документацию

2021-03-01 13:07 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +            raise ValueError("Choose only one parameter between all_nodes and nodes_ids_to_analyze")
Они немного разные: в init проверяла, чтобы оба параметра не передали, в analyze, если ни одного не передали. Все проверки [вынесены](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R52-R60) в init и сразу определяются ноды для аналаза.

2021-03-01 13:10 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R43) интерактивный режим на каждый слой (ChainSA, NodeSA), но если честно, не вижу в нем смысла, потому что из "мелькающей" информации сложно сделать какой-либо вывод. 
Также добавлены логгеры.

2021-03-01 13:10 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +                             f'{self.approaches[index].__name__}.jpg'))
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R121-R122)

2021-03-01 13:11 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +                             f'{self.approaches[index].__name__}_cor.jpg'))
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R136-R137)

2021-03-01 13:14 UTC, BarabanovaIrina commented on fedot/sensitivity/node_sensitivity.py
> +                                                       path_to_save=self.result_dir).analyze(node_id=node_id)
Потому что тут передается не экземпляр класса, а сам класс. Если только сделать метод класса как обертка к \_\_name\_\_, но мне казалось, что это не криминально обращаться к этим переменным. 
Когда пишем конструкцию if \_\_name\_\_ == '\_\_main\_\_' - это по сути то же самое.

2021-03-01 13:19 UTC, BarabanovaIrina commented on fedot/sensitivity/node_sensitivity.py
> +        super(NodeTuneAnalyze, self).__init__(chain, train_data, test_data, path_to_save)
PyCharm автоматически сгенерировал при вызове super(). Прочитала, что это отголосок python2.x, [исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-e044cf6ea23f2f211c6fb4b48d7904837c33cb6d21af23dfd725e0b0109eefaaR178-R179) во всех классах.

2021-03-01 13:21 UTC, BarabanovaIrina commented on fedot/sensitivity/node_sensitivity.py
> +        del samples
Попытка убрать ненужный мусор. Не до конца понимаю, что происходит с объектами, при выходе из класса. [Убрано](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-e044cf6ea23f2f211c6fb4b48d7904837c33cb6d21af23dfd725e0b0109eefaaR224-R228)

2021-03-01 13:23 UTC, BarabanovaIrina commented on fedot/sensitivity/node_sensitivity.py
> +                node_type = SecondaryNode
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-e044cf6ea23f2f211c6fb4b48d7904837c33cb6d21af23dfd725e0b0109eefaaR234-R237) на присвоение типа через type

2021-03-01 13:24 UTC, BarabanovaIrina commented on fedot/utilities/define_metric_by_task.py
> +        except ValueError:
В случаях, когда _metric падает. Был какой-то случай (свалилось на несовместимости размерности данных, не разбирала тот момент).

2021-03-01 13:25 UTC, BarabanovaIrina commented on test/unit/chains/test_chain.py
> +def test_cahin_repr():
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8dR259)

2021-03-01 13:26 UTC, BarabanovaIrina commented
Так же убрала сборку покрытия из manual_build, который мы запускаем для интеграционных тестов.

2021-03-02 07:58 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    degrees = [degree[1] for degree in graph.degree]
тогда введи объясняющую переменную под эти индексы.

2021-03-02 08:12 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
Хм, да, действительно, не очень полезно получается.
Мб тогда уберем его, а вместо него добавим функцию, которая визуализирует результаты SA, которые можно передать в качестве параметра?

2021-03-02 08:13 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +                                                       path_to_save=self.result_dir).analyze(node_id=node_id)
точно, не сразу заметил, что это класс.
ну тогда норм, оставляем.

2021-03-02 08:15 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +        del samples
магия черного ящика в виде gc )

2021-03-02 08:16 UTC, J3FALL commented on fedot/sensitivity/node_sensitivity.py
> +        del samples
Мне прост казалось, что даже явное указание del <object reference> не гарантирует, что память, которая была под него выделена, будет освобождена сейчас.
Даже если принудительно запустить gc.

2021-03-02 08:23 UTC, J3FALL requested changes

2021-03-02 08:23 UTC, J3FALL commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Да, тут решение зависит от того, где мы применяем это удаление.
Например, на UI можно не запариваться и удалять просто узел, а все "сломанные" связи помечать определенным образом.
Ну и уведомить юзера, что "надо сначала починить цепочку"
В нашем случае нет определенного требования, что делать с узлами при удалении.
Можно оставить текущую логику.

2021-03-02 08:23 UTC, J3FALL commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Да, кстати, можешь завести issue под рефакторинг операций над "структурой" цепочки?

2021-03-02 09:53 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
[Issue](https://github.com/nccr-itmo/FEDOT/issues/241) открыта.

2021-03-02 10:03 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
А для какой ситуации это вообще полезно?
Если я правильно поняла, то ты предлагаешь передавать объекты plot-ов в качестве аргументов в эту функцию. Но например plot-ы, которые рисуются в результате NodeReplace, существуют только на тот момент, когда мы работаем с конкретной нодой. При переходе на другую ноду - все по новой. Выходит, что нужно:
- при работе с нодой сохранять plot
- выводить его на уровень ChainSA и там хранить(вместе со всеми нодами). (если работаем через ChainSA, а можно и напрямую через NodeAn.)
Получается, что NodeAnalyze будет возвращать не только ratio, но и plot. Получается запутанно, кмк.

2021-03-02 10:30 UTC, J3FALL commented on fedot/core/chains/chain.py
>      def delete_node(self, node: Node):
Кул

2021-03-02 10:32 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
Но у нас же есть сохранение результатов в json?
Кажется, это они:
![image](https://user-images.githubusercontent.com/7864250/109635648-ad9e3880-7b5b-11eb-8675-947299fae00b.png)
Можно же сделать функцию, которая из этого файла достанет нужные результаты и нарисует графики?
Я это имел в виду.

2021-03-02 10:38 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
А, да.
Тогда логика такая:
if interactive_mode:
    plot subplots altogether after whole analyse
else:
    save&log (как сейчас)

2021-03-02 10:41 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity.py
> +    def _visualize(self, results: dict, types: list):
Угу, тогда это не interactive_mode а просто show_results=False или plot_results.

2021-03-04 10:20 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity.py
> +    degrees = [degree[1] for degree in graph.degree]
[Переименовано](https://github.com/nccr-itmo/FEDOT/pull/192/files#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R19-R20)

2021-03-04 11:45 UTC, BarabanovaIrina commented
Добавлена документация https://fedot.readthedocs.io/en/sensitivity/fedot/features/sensitivity_analysis.html

2021-03-04 12:28 UTC, J3FALL approved these changes

2021-03-04 12:29 UTC, J3FALL commented
Вот тут, кажется, пробелы пропали.
![image](https://user-images.githubusercontent.com/7864250/109964128-51274e80-7cfe-11eb-913e-a5ca11b38d6b.png)

2021-03-04 12:55 UTC, merged