upgraded tree visualization, upgraded gif creation, removed graphviz
nccr-itmo/FEDOT pull request #194
Opened 2020-12-02 16:44 UTC by Sash0check

Обновлена статическая визуализация структуры композитных моделей:
- не требуется установки Graphviz
- выводятся гиперпараметры
- визуальные улучшения
Обновлена визуализация истории, а именно - теперь все кадры для гифки хранятся в памяти, а не на жестком диске.
Изменена версия PIllow, так как на предыдущей возникала ошибка при создании гиф анимации

02.12 UPDATE
Учтены комментарии к коду из #167 
Гиперпараметры модели теперь в виде сводной таблицы сохраняются в csv файл (опционально)
Класс для визуализации теперь не static.

Пример использования обновленного класса:
```python
visualiser = ChainVisualiser()
visualiser.visualise(chain, params_save_path=r'C:\Users\user\Downloads\params.csv')
```

2020-12-02 16:44 UTC, pep8speaks commented
Hello @Sash0check! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/composer/visualisation.py`](https://github.com/nccr-itmo/FEDOT/blob/769cc6987787dddf4e9957a66618e4d9f8ae9214/fedot/core/composer/visualisation.py):

> [Line 229:12](https://github.com/nccr-itmo/FEDOT/blob/769cc6987787dddf4e9957a66618e4d9f8ae9214/fedot/core/composer/visualisation.py#L229): [E713](https://duckduckgo.com/?q=pep8%20E713) test for membership should be 'not in'
> [Line 252:53](https://github.com/nccr-itmo/FEDOT/blob/769cc6987787dddf4e9957a66618e4d9f8ae9214/fedot/core/composer/visualisation.py#L252): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'
> [Line 253:37](https://github.com/nccr-itmo/FEDOT/blob/769cc6987787dddf4e9957a66618e4d9f8ae9214/fedot/core/composer/visualisation.py#L253): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'

2020-12-08 18:35 UTC, nicl-nno commented
Предложение - может добавим к chain метод vizualize? 
Кмк будет удобнее, т.к. не придется импортировать ChainVisualiser каждый раз, когда я  хочу посмотреть на структуру цепочки.

2020-12-24 10:24 UTC, J3FALL requested changes

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                on_next_iteration_callback(self.population)
Смотри, мне кажется, чтобы не дублировать эту проверку с if лучше реализовать дефолную версию GPOptHistory.
Т.е. `on_next_iteration_callback(self.population)` вызывать в любом случае, но в начале метода compose_chain реализовать что-то такое:
```
if on_next_iteration_callback is None:
   on_next_iteration_callback = default_callback()
```

Функция default_callback() возвращает инстанс подкласса GPHistory, который ничего внутри не делает.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +                   in_graph_convertet_function=as_nx_graph):
А для чего нужна функция in_graph_convertet_function?
+ Тут в названии опечатка есть.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +    def visualise(self, chain: Chain, save_path: Optional[str] = None, params_save_path: Optional[str] = None):
Добавь здесь перенос строки, плз.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +    return make_pos({})
По-хорошему, на эти функции бы тестов добавить, хоть парочку.

2020-12-24 10:24 UTC, J3FALL commented on fedot/utilities/synthetic/chain_template_new.py
> +def chain_template_as_nx_graph(chain: ChainTemplate):
Добавь на эту функцию тест.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/gp_opt_history.py
> +        self.historical_chains = list(itertools.chain(*self.history))
Если это переменные класса, то нужно их инициализировать в кострукторе.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/gp_opt_history.py
> +
На класс нет тестов, что не очень круто.

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/gp_opt_history.py
> +        file = f'{history_dir}/{file}'
лучше использовать платформо-независимый метод os.path.join()

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/gp_opt_history.py
> +                           generation: int = None):
Названия переменных немного смущают - не понятно, например, что такое num?

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/gp_opt_history.py
> +        i = 0
Крайне не рекомендую называть переменные как i,j и т.д.
Если это не математика какая-то, конечно.
Думаю, что даже idx - более говорящее название.
Кстати, а для чего эта переменная вообще нужна?

2020-12-24 10:24 UTC, J3FALL commented on fedot/core/composer/visualisation.py
>  import os
Кстати, я думаю, что нужно сделать некоторый тест визуализации цепочек, но без привязки к реальным вычислениям.
Грубо говоря, создаем "фейковую" историю оптимизации, которую создаем заранее.
Запускаем визуализацию, проверяем, что в истории достаточное число записей.
Как вариант.
Причем, не обязательно прямо визуализировать в ходе тестов все цепочки

2020-12-24 13:38 UTC, Sash0check commented on fedot/core/composer/visualisation.py
> +                   in_graph_convertet_function=as_nx_graph):
Для конвертирования Chain и ChainTemplate используются разные функции

2020-12-24 14:05 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +                           generation: int = None):
Я эти функции перенес из write_history, но я полагаю, что это индекс, переименую)

2020-12-24 14:07 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +        i = 0
Для индексации в файле
![image](https://user-images.githubusercontent.com/16399597/103093119-7adf3d80-460a-11eb-9d60-4cf76fdb57fa.png)

2021-01-11 08:47 UTC, J3FALL requested changes

2021-01-11 08:47 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +def generate_history(generations_quantity, pop_size):
generations_quantity - думаю, можно проще: generations_amount, или просто generations

2021-01-11 08:47 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    generations_quantity = 2
Здесь тоже можно исправить по аналогии, как выше.

2021-01-11 08:47 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    visualiser.visualise(chain, params_save_path=r'C:\Users\user\Downloads\params.csv')
Нужно использовать относительные пути, иначе не у всех эта функция корректна отработает

2021-01-11 08:47 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_optimiser.py
> +            on_next_iteration_callback = lambda pop: None
Выдели это в отдельную функцию:
```
def default_on_next_iteration_callback():
   return lambda pop: None
```

2021-01-11 08:47 UTC, J3FALL commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
> +            on_next_iteration_callback = lambda pop: None
Здесь тоже не забудь исправить.

2021-01-11 08:47 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    visualiser.visualise(chain, params_save_path=r'C:\Users\user\Downloads\params.csv')
И еще, мне кажется, что при сохранении датафрейма с историей итоговый csv-файл не очень наглядный:
![image](https://user-images.githubusercontent.com/7864250/104160690-974ce980-5402-11eb-875a-a654d9abd540.png)
Тут либо какой-то баг, либо не хватает header-а (описания колонок) + переносов.
Не очень понятно, как этот файл интерпретировать, нужно его доработать.

2021-01-11 08:54 UTC, Sash0check commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                on_next_iteration_callback(self.population)
сделал в виде lambda функции > [Line 109](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/fedot/core/composer/optimisers/gp_optimiser.py#L109)

2021-01-11 08:57 UTC, Sash0check commented on fedot/core/composer/visualisation.py
> +                   in_graph_convertet_function=as_nx_graph):
исправил опечатку > [Line 49](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/fedot/core/composer/visualisation.py#L49)

2021-01-11 08:59 UTC, Sash0check commented on fedot/core/composer/visualisation.py
> +    return make_pos({})
https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/test/test_visualisation_utils.py

2021-01-11 09:01 UTC, Sash0check commented on fedot/utilities/synthetic/chain_template_new.py
> +def chain_template_as_nx_graph(chain: ChainTemplate):
добавил тесты > [Line 32](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/test/test_visualisation_utils.py#L32)

2021-01-11 09:02 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +
добавил тесты > [file](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/test/test_gp_opt_history.py)

2021-01-11 09:04 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +        file = f'{history_dir}/{file}'
исправил > [Line 31](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/fedot/core/composer/gp_opt_history.py#L31)

2021-01-11 09:07 UTC, Sash0check commented on fedot/core/composer/visualisation.py
>  import os
Сделал [Line 46](https://github.com/nccr-itmo/FEDOT/blob/71f3c4e780d1d7d83284ec699814f3c1e29873de/test/test_gp_opt_history.py#L46)

2021-01-11 10:04 UTC, nicl-nno commented on fedot/core/composer/gp_opt_history.py
> +    def prepare_for_visualisation(self):
А нужно это отдельно выносить в метод? Мб проще иметь property historical_fitness и historical_chains, в которых будет делать эта операция при каждом обращении?

2021-01-11 10:06 UTC, nicl-nno commented on fedot/core/composer/gp_opt_history.py
> +class GPOptHistory:
Можно назвать ComposingHistory кмк - тут же нет именно GP-специфики.

2021-01-11 10:12 UTC, nicl-nno commented on test/test_gp_opt_history.py
> +import pytest
Под это и utils ниже стоит создать каталог test/visualization/...

2021-01-11 10:27 UTC, nicl-nno commented on test/test_gp_opt_history.py
> +        chain.fitness = 1
А эта строка должна быть в цикле?

2021-01-11 10:27 UTC, nicl-nno commented on test/test_gp_opt_history.py
> +        chain.add_node(node)
Вместо цикла можно делать просто chain = Chain(final)

2021-01-11 10:45 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +            on_next_iteration_callback = lambda pop: None
А нет смысла в такую функцию колбека по умолчанию добавить сохранении истории в какое-то поле composer, содержащее экземпляр GPOptHistory?
 
Сохранение истории - функция востребованная, и кмк не оч. удобно каждый раз снаружи инициализировать без особой необходимости.

2021-01-13 14:38 UTC, Sash0check commented on examples/chain_and_history_visualisation.py
> +def generate_history(generations_quantity, pop_size):
Исправил https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/examples/chain_and_history_visualisation.py#L30

2021-01-13 14:39 UTC, Sash0check commented on examples/chain_and_history_visualisation.py
> +    generations_quantity = 2
Исправил https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/examples/chain_and_history_visualisation.py#L43

2021-01-13 14:39 UTC, Sash0check commented on examples/chain_and_history_visualisation.py
> +    visualiser.visualise(chain, params_save_path=r'C:\Users\user\Downloads\params.csv')
Убрал сохранение в csv
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/examples/chain_and_history_visualisation.py#L52

2021-01-13 14:42 UTC, Sash0check commented on fedot/core/composer/optimisers/gp_optimiser.py
> +            on_next_iteration_callback = lambda pop: None
Сделал
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/fedot/core/composer/optimisers/gp_optimiser.py#L111-L112
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/fedot/core/composer/optimisers/gp_optimiser.py#L278-L279

2021-01-13 14:42 UTC, Sash0check commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
> +            on_next_iteration_callback = lambda pop: None
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/fedot/core/composer/optimisers/param_free_gp_optimiser.py#L48

2021-01-13 14:43 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +    def prepare_for_visualisation(self):
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/fedot/core/composer/composing_history.py#L52-L59

2021-01-13 14:44 UTC, Sash0check commented on fedot/core/composer/gp_opt_history.py
> +class GPOptHistory:
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/fedot/core/composer/composing_history.py#L10

2021-01-13 14:45 UTC, Sash0check commented on test/test_gp_opt_history.py
> +import pytest
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/test/visualization/test_composing_history.py#L1
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/test/visualization/test_visualisation_utils.py#L1

2021-01-13 14:46 UTC, Sash0check commented on test/test_gp_opt_history.py
> +        chain.fitness = 1
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/test/visualization/test_composing_history.py#L14-L15

2021-01-13 14:46 UTC, Sash0check commented on test/test_gp_opt_history.py
> +        chain.add_node(node)
https://github.com/nccr-itmo/FEDOT/blob/1d708ab5b95a780314a00a6ab9c720e0ace2916f/test/visualization/test_composing_history.py#L14-L15

2021-01-13 14:59 UTC, nicl-nno commented on fedot/core/composer/composing_history.py
> +        self.history = []
Может назвать это поле chains или как-то так? А то нелогично, что в экземпляре ComposingHistory опять есть history.

2021-01-13 14:59 UTC, nicl-nno commented on fedot/core/composer/composing_history.py
> +    def write_header_to_csv(self, f):
Этот метод можно сделать private или вообще вынести из класса, равно как add_history_to_csv и convert_chain_to_template.

2021-01-13 17:32 UTC, Sash0check commented on fedot/core/composer/composing_history.py
> +        self.history = []
https://github.com/nccr-itmo/FEDOT/blob/a79cd3797f49e9e2e72a69e827b60486fa88cbc8/fedot/core/composer/composing_history.py#L16

2021-01-13 17:33 UTC, Sash0check commented on fedot/core/composer/composing_history.py
> +    def write_header_to_csv(self, f):
https://github.com/nccr-itmo/FEDOT/blob/a79cd3797f49e9e2e72a69e827b60486fa88cbc8/fedot/core/composer/composing_history.py#L18
https://github.com/nccr-itmo/FEDOT/blob/a79cd3797f49e9e2e72a69e827b60486fa88cbc8/fedot/core/composer/composing_history.py#L41
https://github.com/nccr-itmo/FEDOT/blob/a79cd3797f49e9e2e72a69e827b60486fa88cbc8/fedot/core/composer/composing_history.py#L46

2021-01-13 17:40 UTC, nicl-nno approved these changes

2021-01-15 08:37 UTC, J3FALL approved these changes

2021-01-15 16:00 UTC, merged