Image pipeline
nccr-itmo/FEDOT pull request #200
Opened 2020-12-08 11:41 UTC by v1docq

[InputData] Support images as InputData

2021-01-03 14:25 UTC, nicl-nno requested changes

2021-01-03 14:25 UTC, nicl-nno commented on requirements.txt
> +scikit-learn~=0.22.1
Выглядит как будто scikit-learn и scikit_learn - дубликаты.

2021-01-03 14:25 UTC, nicl-nno commented on cases/image_recognitation_problem.py
> +    print(f'ROCAUC simple: {roc_auc_on_valid_simple}')
Запустил этот скрипт - получил ROCAUC simple: 0.99995488997993
Это нормально для MNIST? А то выглядит уж очень точно.

2021-01-03 14:25 UTC, nicl-nno commented on cases/image_recognitation_problem.py
> +def run_image_recognitation_problem(train_dataset: Union[str, tuple],
Опечатка.

2021-01-03 14:25 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +    x_test = x_test.astype("float32") / 255
А не нужно ли это как метод preprocessing-а реализовать? Или тут специфика именно для cnn?

2021-01-12 11:19 UTC, v1docq commented on cases/image_recognitation_problem.py
> +    print(f'ROCAUC simple: {roc_auc_on_valid_simple}')
У мнист, насколько я видел, ниже 0.98 вообще не опускается.

2021-01-12 11:21 UTC, v1docq commented on cases/image_recognitation_problem.py
> +    task = Task(TaskTypesEnum.image_classification)
Согласен что можно и обойтись и без него, но это скорее задел на будущее, для задач связанных с работой с изображением. Сегментация, категоризация и прочее.

2021-01-12 11:24 UTC, v1docq commented on requirements.txt
> +scikit-learn~=0.22.1
Исправил

2021-01-12 11:25 UTC, v1docq commented on cases/image_recognitation_problem.py
> +def run_image_recognitation_problem(train_dataset: Union[str, tuple],
Исправил

2021-03-30 14:03 UTC, v1docq commented on fedot/core/models/data.py
> +                   data_type: DataTypesEnum = DataTypesEnum.table,
Добавил datatype image

2021-03-31 13:12 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +    if complexity_flag:
Как-то совсем заглушечно. Может, передавать строковый параметр architecture со значениями 'deep' и 'shallow'?

2021-03-31 13:14 UTC, nicl-nno commented on requirements.txt
> +scikit-learn~=0.22.1
Вроде нет?

2021-03-31 13:15 UTC, nicl-nno commented on requirements.txt
> +scikit-learn~=0.22.1
И нужен ли opencv-python теперь?

2021-03-31 13:16 UTC, nicl-nno commented on test/unit/tasks/test_classification.py
> +    return training_path_1, training_path_2, test_path_1, test_path_2
Лучше в названиях переменных указать, что это не _1, _2, а features и labels

2021-03-31 13:17 UTC, nicl-nno requested changes

2021-03-31 13:17 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +        verbose = 0
Лучше что-то вроде verbose = 0 if verbosity_level_logger<4 else 2

2021-03-31 14:05 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    return training_path_1, training_path_2, test_path_1, test_path_2
Исправил

2021-03-31 14:05 UTC, v1docq commented on requirements.txt
> +scikit-learn~=0.22.1
Убрал

2021-03-31 14:45 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +        verbose = 0
Исправил

2021-03-31 14:45 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +            verbosity_level_logger: int = 5,
Пробросил

2021-04-01 13:55 UTC, nicl-nno requested changes

2021-04-01 13:55 UTC, nicl-nno commented on fedot/core/data/data.py
> +        :param aug_flag: function that provides opportunity to create augmented data
aug_flag уже нет

2021-04-01 13:55 UTC, nicl-nno commented on fedot/core/data/data.py
> +    def from_image(images: Union[str, np.ndarray] = None,
А параметр data_type тут нужен? Вроде он всегда image.
Ну и выходной тип данных стоит указать.

2021-04-01 13:55 UTC, nicl-nno commented on fedot/core/data/data.py
> +        :param labels: name of target column (last column if empty and no target if None)
Вроде по коду это не name, а такой же путь, как и у images?

2021-04-01 13:55 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +        print(f'{architecture_type} is incorrect type of NN architecture')
Лучше использовать логгер, а не print.
В данном случае с log.error

2021-04-01 13:55 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +        verbose = 0
?

2021-04-01 13:55 UTC, nicl-nno commented on cases/image_classification_problem.py
> +    node_first = PrimaryNode('cnn')
Для наглядности лучше здесь явно указать архитектуру 'shallow'

2021-04-01 13:55 UTC, nicl-nno commented on test/unit/tasks/test_classification.py
> +    roc_auc_on_valid_simple = run_image_classification_problem(train_dataset=(training_path_features, training_path_labels),
![image](https://user-images.githubusercontent.com/5711814/113304825-11f31a00-930b-11eb-8243-fac1c17a3bd1.png)

2021-04-01 14:03 UTC, nicl-nno requested changes
Ещё пара комментов

2021-04-01 14:03 UTC, nicl-nno commented on test/unit/tasks/test_classification.py
> +    assert roc_auc_on_valid_simple > 0.1
Странная проверка на 0.1. Пусть будет хотя бы abs(...) > 0.5.

Ну и лучше тест не завязывать на код и данные их примера, а сделать самостоятельным.

2021-04-01 14:03 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +    pred = trained_model.predict(x_test)
Тут не хватает поддержки self.output_mode по аналогии SkLearnClassificationStrategy.

2021-04-02 12:33 UTC, v1docq commented on fedot/core/data/data.py
> +        :param aug_flag: function that provides opportunity to create augmented data
исправил

2021-04-02 12:35 UTC, v1docq commented on fedot/core/data/data.py
> +    def from_image(images: Union[str, np.ndarray] = None,
Исправил

2021-04-02 12:36 UTC, v1docq commented on fedot/core/data/data.py
> +        :param labels: name of target column (last column if empty and no target if None)
Исправил

2021-04-02 12:41 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +        print(f'{architecture_type} is incorrect type of NN architecture')
исправил

2021-04-02 12:42 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +        verbose = 0
исправил

2021-04-02 12:44 UTC, v1docq commented on cases/image_classification_problem.py
> +    node_first = PrimaryNode('cnn')
Исправил

2021-04-02 12:45 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    roc_auc_on_valid_simple = run_image_classification_problem(train_dataset=(training_path_features, training_path_labels),
Исправил

2021-04-05 13:06 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +    pred = trained_model.predict(x_test)
Добавил

2021-04-05 16:35 UTC, v1docq commented on cases/image_classification_problem.py
> +        X_test, y_test = test_dataset[0], test_dataset[1]
Убрал tuple и сделал с строчной буквы

2021-04-05 16:35 UTC, v1docq commented on cases/image_classification_problem.py
> +                                     composite_model_flag: bool = False):
Убрал флаг

2021-04-05 16:36 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    assert roc_auc_on_valid_simple > 0.1
Сделал от 0.4 до 0.6. Данные в папке /test/data

2021-04-05 17:03 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    assert roc_auc_on_valid_simple > 0.1
Переделал как обсуждали на отклонение от 0.5.

2021-04-16 11:21 UTC, nicl-nno commented on fedot/core/models/evaluation/keras_eval.py
> +    # train_data_3d.task.task_params.
?

2021-04-16 11:21 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    # y_train = tf.keras.utils.to_categorical(y_train)
?

2021-04-16 11:30 UTC, v1docq commented on fedot/core/models/evaluation/keras_eval.py
> +    # train_data_3d.task.task_params.
удалил файл он не нужен

2021-04-16 11:30 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    # y_train = tf.keras.utils.to_categorical(y_train)
убрал

2021-04-16 11:30 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    # y_train = tf.keras.utils.to_categorical(y_train)
убрал

2021-04-16 11:33 UTC, nicl-nno approved these changes

2021-04-20 12:22 UTC, J3FALL requested changes

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def _create_cnn(input_shape: tuple,
Я бы сделал этот метод публичным + реализовал парочку тестов на него.

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            ]
Мне кажется, можно извлечь 2 функции под каждую из архитектур.
+ Там можно отразить в docsting, что представляет собой архитектура.
Например, немного confusing описание shallow для архитектуры.

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        logger.error(f'{architecture_type} is incorrect type of NN architecture')
Обрати внимание, что в аннотации поля logger есть опция None.
Если вдруг будет None, то на этой строчке код упадет.

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
не настаиваю, но мб параметры оптимизатора стоит вытащить наружу в эту функцию, хотя бы?

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    x_train = x_train.astype("float32") / 255
Тут немного тонкая грань - вот это деление на 255 вещь достаточно известная, почти всегда при картинках это необходимо делать. Т.е. вполне возможен вариант, когда юзер уже заранее эту операцию проделал. И тогда получится двойное деление.
Что можно сделать:

- Отразить этот момент в docsting методе
- Не делить на 255 внутри, но указать в docsting, что деление на 255 is expected
- Сделать проверку внутри, нужно ли делить, если да - то поделить внутри и вписать в лог об этом

Вроде последний вариант - самый норм, имхо.

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        epochs = 10
В лог стоит написать про это, что выбрано дефолтное значение.

2021-04-20 12:22 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            raise NotImplementedError()
Добавь описание в эксепшен, чтобы не просто был NotImplemented

2021-04-20 12:22 UTC, J3FALL commented on test/unit/tasks/test_classification.py
> +    train_labels_path = '../../data/training_labels.npy'
Я не большой эксперт, но предвещаю тут возможную проблему несовместимости версий npy-формата.
Т.е. ранее файлы были упакованы и сохранены в npy с версией numpy=x, а запуск теста происходит на другой версии. И может так получиться, что файлы не получится открыть.
Мне кажется, я когда-то такое ловил, мб уже такого не встречается, но не уверен.
Мб для теста сделать какой-то усеченный датасет и запаковать его в zip?
Кстати, еще проблема - эти npy файлы никак не посмотреть глазами.

2021-04-20 12:22 UTC, J3FALL commented on test/unit/tasks/test_classification.py
>  import os
Мне кажется, для полноты не хватает еще ряда тестов на новые функции:
- fit/predict базовой цепочки, где встроена cnn
- тесты на CustomCNNImplementation
- тесты на методы create_cnn, fit_cnn и predict_cnn
- InputData для картинок

2021-04-20 14:57 UTC, v1docq commented on examples/image_classification_problem.py
> +from typing import Union
убрал импорт

2021-04-20 14:57 UTC, v1docq commented on examples/image_classification_problem.py
> +                                 'architecture_type': 'shallow'}
Привел к единому формату.

2021-04-20 14:58 UTC, v1docq commented on fedot/core/data/data.py
> +            target = np.load(labels)
Изменил аннотацию

2021-04-20 15:08 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        epochs = 10
Добавил сообщение в warning

2021-04-20 15:20 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    x_train = x_train.astype("float32") / 255
Сделал проверку и логирование

2021-04-20 15:21 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            raise NotImplementedError()
Добавил описание в логгер

2021-04-21 11:18 UTC, v1docq commented on fedot/core/data/data.py
> +    def from_image(images: Union[str, np.ndarray] = None,
Реализовал метод в data/test_data.py

2021-04-21 11:18 UTC, v1docq commented on test/unit/tasks/test_classification.py
>  import os
Первые 3 пункта реализовал в test_classification.py. Тест InputData реализоваk в data/test_data.py

2021-04-21 12:14 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def _create_cnn(input_shape: tuple,
Реализовал в test_classification.py

2021-04-21 12:15 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    train_labels_path = '../../data/training_labels.npy'
Проблемы с несовместимостью честно не встречал. Данная версия это урезанная версия MNIST датасета для того что бы не висли тесты в онлайне. Запаковывать в зип конечно можно, но не вижу смысла для тестовых целей.

2021-04-21 13:50 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        logger.error(f'{architecture_type} is incorrect type of NN architecture')
Добавил создание логгера если они не определен

2021-04-21 13:55 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.compile(loss="categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
Добавил возможность передать словарь с параметрами для оптимизатора

2021-04-22 09:38 UTC, J3FALL requested changes

2021-04-22 09:38 UTC, J3FALL commented on fedot/core/data/data.py
> +        :return:
Кажется, вместо слова "massive" предполагалось "array" :)

2021-04-22 09:38 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            ]
Тут все еще напрашивается извлечение двух методов.

2021-04-22 09:38 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        self.log: Log = default_log(__name__)
Мне кажется, что эта конструкция здесь некорректно - такие аннотации можно делать для dataclass-ов, либо внутри "шапки" метода.
Либо нужно убрать эту аннотацию :Log, либо добавить в конструктор этот параметр, и аннотацию отобразить сюда.
Ибо сейчас не очень понятно, что вообще имеется в виду.

2021-04-22 09:38 UTC, J3FALL commented on test/unit/tasks/test_classification.py
> +    train_labels_path = '../../data/training_labels.npy'
Ну, как минимум, в этом есть смысл - помочь другим будущим разработчикам, кто решит отрефакторить этот тест по каким то причинам.
Ему чтобы разобраться, что там за npy лежат, нужно будет их открыть в коде, в дебаге глянуть и т.д.
Я не настаиваю на том, чтобы так запариваться, но хотя бы намек будущим потомкам этого кода оставить все-таки стоит )
В docstring-е этого теста указать, что это за npy файлы (по аналогии с тем, что ты мне ответил в этом комменте)

2021-04-22 09:38 UTC, J3FALL commented on test/unit/tasks/test_classification.py
> +    assert abs(deviation_simple) < 0.35
Мне кажется, что вместо большого числа assert-тов можно разбить этот тест на 3 маленьких.

2021-04-22 09:38 UTC, J3FALL commented on test/unit/tasks/test_classification.py
> +    assert abs(deviation_simple) < 0.35
Иначе получается, что если тест упал, не совсем ясно, где у нас ошибка появилась - в create_cnn, fit_cnn, predict_cnn или же CustomCNNImplementation ?

2021-04-22 09:47 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    x_train = x_train.astype("float32") / 255
В идеале бы проверить этот момент тестом, но чтобы не гонять целый fit_cnn метод, вижу логичным вытащить эту логику в отдельный метод/проверку, который возвращает true если переданные данные не были нормализованы, и false - в противном случае.
![image](https://user-images.githubusercontent.com/7864250/115693782-e9d66400-a368-11eb-9f1e-24043b321381.png)

2021-04-22 10:14 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            ]
окей, не заметил твой коммент

2021-04-22 10:32 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    x_train = x_train.astype("float32") / 255
Вытащил в отдельную функцию и сделал проверку в тесте.

2021-04-22 10:32 UTC, v1docq commented on fedot/core/data/data.py
> +        :return:
Исправил

2021-04-22 10:33 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    assert abs(deviation_simple) < 0.35
Разбил на 3 теста

2021-04-22 11:13 UTC, v1docq commented on test/unit/tasks/test_classification.py
> +    train_labels_path = '../../data/training_labels.npy'
Добавил docstring для этого теста

2021-04-22 11:13 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            ]
Сформировал словарь функций и сделал 2 отдельные функции.

2021-04-22 11:15 UTC, v1docq commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        self.log: Log = default_log(__name__)
Убрал из шапки класса и передвинул в словарь с параметрами модели.

2021-04-22 11:57 UTC, J3FALL approved these changes

2021-04-22 12:13 UTC, merged