196 issues || export/import zip-project
nccr-itmo/FEDOT pull request #208
Opened 2020-12-11 04:45 UTC by MAGLeb

Closed #196 

Интерфейс для импорта \ экспорта проекта:
def export_project_to_zip(chain: Chain, data: InputData, zip_name: str, log_file_name: str = None, verbose: bool = False):
def import_project_from_zip(zip_path: str, verbose: bool = False) -> [Chain, InputData]:

2020-12-11 10:52 UTC, J3FALL requested changes

2020-12-11 10:52 UTC, J3FALL commented on docs/source/fedot/utilities/project_import_export.rst
> +    from fedot.utilities.project_import_export import export_project_to_zip
Тут ошибка, должен быть импорт import_project_from_zip

2020-12-11 10:52 UTC, J3FALL commented on docs/source/fedot/utilities/project_import_export.rst
> +    import_project_from_zip('/home/user/downloads/project_name.zip', verbose=True)
Для наглядности покажи еще, что именно эта функция возвращает, и что с этими объектами можно делать.
Например, можно добавить еще один небольшой этап в документации, где на импортированной цепочке и данных происходит fit/predict.

2020-12-11 10:52 UTC, J3FALL commented on fedot/core/models/data.py
> +            data_type = get_data_type(data_type_)
А разве нет возможности у pandas-а прочитать csv-файл один раз и извлечь header?
Смущает, что тут 2 раза файл открывается.

2020-12-11 10:52 UTC, J3FALL commented on fedot/core/models/data.py
> +            template = """{} {} \n{}""".format(task_type, data_type, dataframe.to_csv())
А через f-string можно по аналогии отфарматировать?

2020-12-11 10:52 UTC, J3FALL commented on fedot/core/models/data.py
> +    if columns is not None:
Хм, а если будет None?
Получается, что никакого исключения не будет.

2020-12-11 10:52 UTC, J3FALL commented on fedot/core/models/data.py
> +        if all([column for column in columns if isinstance(column, str)]):
Извлеки эту проверку в отдельную функцию ниже.

2020-12-11 12:11 UTC, MAGLeb commented on fedot/core/models/data.py
> +            data_type = get_data_type(data_type_)
Нельзя. Могу запихать все в менеджер контекста with open()...

2020-12-11 12:22 UTC, MAGLeb commented on fedot/core/models/data.py
> +    if columns is not None:
Верно, после проверки я создаю pd.dataframe(columns=columns) и если перевадавать None, то ничего не упадет и default значения будут присвоины колонкам.

2020-12-11 13:14 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/project_import_export.py`](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/examples/project_import_export.py):

> [Line 50:1](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/examples/project_import_export.py#L50): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`fedot/core/models/data.py`](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/fedot/core/models/data.py):

> [Line 265:70](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/fedot/core/models/data.py#L265): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file





* In the file [`fedot/utilities/project_import_export.py`](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/fedot/utilities/project_import_export.py):

> [Line 96:1](https://github.com/nccr-itmo/FEDOT/blob/561bbb73d476f981ef30b339165f65f6c883cedc/fedot/utilities/project_import_export.py#L96): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2020-12-11 13:18 UTC, MAGLeb commented on fedot/core/models/data.py
> +        if all([column for column in columns if isinstance(column, str)]):
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/208/commits/561bbb73d476f981ef30b339165f65f6c883cedc#diff-f22384c715163b95d5823a704836477fea732879bca9d918cf2551af4e5ef2f7L75-R63)

2020-12-11 13:19 UTC, MAGLeb commented on fedot/core/models/data.py
> +            template = """{} {} \n{}""".format(task_type, data_type, dataframe.to_csv())
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/208/commits/561bbb73d476f981ef30b339165f65f6c883cedc#diff-7f4842972609c1f77bd1d4513b2cdb81dbd78fdb4c2bd30ab882d07f2f80e7bbR143-R145)

2020-12-11 13:20 UTC, MAGLeb commented on docs/source/fedot/utilities/project_import_export.rst
> +    from fedot.utilities.project_import_export import export_project_to_zip
[FIXED](https://github.com/nccr-itmo/FEDOT/pull/208/commits/561bbb73d476f981ef30b339165f65f6c883cedc#diff-82aa544fe19aab6c4acfda4382ea6015b8a3b024b8eae1a5e688b97c3d29f9e5L51-L52)

2020-12-11 13:21 UTC, MAGLeb commented on docs/source/fedot/utilities/project_import_export.rst
> +    import_project_from_zip('/home/user/downloads/project_name.zip', verbose=True)
[EXAMPLE](https://github.com/nccr-itmo/FEDOT/pull/208/commits/561bbb73d476f981ef30b339165f65f6c883cedc#diff-99afbc6bec9413ec9a032ec94aa53ddd0d2a4ccb91ae99755a4880289535d942R2-R49)
[FIXED DOC](https://github.com/nccr-itmo/FEDOT/pull/208/commits/561bbb73d476f981ef30b339165f65f6c883cedc#diff-82aa544fe19aab6c4acfda4382ea6015b8a3b024b8eae1a5e688b97c3d29f9e5L39-L55)

2020-12-15 15:46 UTC, J3FALL commented on fedot/core/models/data.py
> +    if columns is not None:
Окей, понял.

2021-01-15 17:44 UTC, nicl-nno commented on docs/source/fedot/utilities/project_import_export.rst
> +    #                       zip_name: str, log_file_name: str = None, verbose: bool = False):
Закомменченный кусок видимо уже не нужен

2022-04-25 15:43 UTC, maypink commented on fedot/utilities/project_import_export.py
> +        zip_name = zip_name + '.zip'
я бы folder_name=zip_name перенесла сюда после else

2022-04-25 15:44 UTC, maypink commented on fedot/utilities/project_import_export.py
> +    :param zip_name: name of the zip file with exported project
хотелось бы упоминания того, что можно указать как имя, так и путь (как в примере)

2022-04-25 15:54 UTC, maypink commented on test/unit/utilities/test_project_import_export.py
> +    folder_path = os.path.join(fedot_project_root(), 'test', 'data', 'project', 'iris_classification')
светится из-за типов

2022-04-25 15:55 UTC, maypink commented on test/unit/utilities/test_project_import_export.py
> +    zip_path = os.path.join(folder_path + '.zip')
а зачем так, если можно `zip_path = folder_path + '.zip'`

2022-04-26 09:38 UTC, IIaKyJIuH requested changes

2022-04-26 09:38 UTC, IIaKyJIuH commented on fedot/utilities/project_import_export.py
> +    if zip_path_split[-1].split('.')[-1] != 'zip':
`Path(zip_path).suffix` != `'.zip'`:
...

2022-04-26 09:38 UTC, IIaKyJIuH commented on test/unit/utilities/test_project_import_export.py
> +DEFAULT_PROJECTS_PATH = os.path.join(default_fedot_data_dir(), 'projects')
Эту глобальную переменную можно импортнуть из `fedot/utilities/project_import_export` же

2022-04-26 09:38 UTC, IIaKyJIuH commented on test/unit/utilities/test_project_import_export.py
> +    zip_path = os.path.join(folder_path + '.zip')
на `pathlib`, кстати, это делается простым `.with_suffix(...)`

2022-04-26 14:37 UTC, MorrisNein commented on docs/source/api/project_import_export.rst
> +pipeline will be converted to JSON format, InputData objects to CSV format. And all folder
Тут понятнее будет, если сказать "the whole folder"

2022-04-26 14:41 UTC, MorrisNein commented on docs/source/api/project_import_export.rst
> +. **'Project'** on that context means: pipeline, data, and logs.
Тут всё-таки "in this context" приятнее заморскому глазу

2022-04-26 14:45 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +    Unzipping zip file. Zip file should contains:
Поправь плиз на `should contain`

2022-04-26 14:51 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +        raise FileExistsError(message)
Тут больше подойдёт `FileNotFoundError`

2022-04-26 15:08 UTC, MorrisNein commented on docs/source/api/project_import_export.rst
> +default path: ``/home/user/Fedot/projects/project_name`` with unarchived files.
На Windows нет директории `home`. Можно писать `%userprofile%/Fedot/...` или лаконичнее `~/Fedot/...`

2022-04-26 15:30 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +    return zip_name[0]
Не только лаконичнее, но это также устранило бы потенциальную ошибку, когда имя файла включает `.`, что вполне обычная ситуация.

2022-04-26 16:07 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +    pipeline, train_data, test_data, opt_history = None, None, None, None
Здесь есть хорошая альтернатива
`pipeline = train_data = test_data = opt_history = None`
либо
`pipeline, train_data, test_data, opt_history = [None] * 4`

2022-04-27 13:11 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        zip_name = zip_name + '.zip'
Done

2022-04-27 13:11 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    :param zip_name: name of the zip file with exported project
Сформулировал как "absolute or relative path". Указал типы Union[str, Path].

2022-04-27 13:12 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +    folder_path = os.path.join(fedot_project_root(), 'test', 'data', 'project', 'iris_classification')
Добавил приведение к str

2022-04-27 13:12 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +    zip_path = os.path.join(folder_path + '.zip')
Сделал через pathlib

2022-04-27 13:12 UTC, nicl-nno commented on docs/source/api/project_import_export.rst
> +will be compressed to zipfile: ``home/user/Fedot/projects/zip_name.zip``.
Поменял.

2022-04-27 13:12 UTC, nicl-nno commented on fedot/api/api_utils/api_data.py
> +            raise ValueError(f'Please specify a features as path to csv file, as Numpy array, '
Fixed

2022-04-27 13:12 UTC, nicl-nno commented on fedot/core/data/data.py
> +    if columns is not None:
Fixed, заодно упростил структуру.

2022-04-27 13:12 UTC, nicl-nno commented on fedot/core/data/data.py
> +        if _array_contains_only_one_type(columns, 'str'):
Done

2022-04-27 13:12 UTC, nicl-nno commented on fedot/core/data/data.py
> +                raise IndexError(f"Length of input columns must be: '{valid_number_columns}'.")
Поправил везде где заметил.

2022-04-27 13:12 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    return zip_name[0]
Так и сделал, функцию вообще убрал.

_prepare_paths тоже поправил

2022-04-27 13:12 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    :param opt_history: history of model optimisation
Приписал.

2022-04-27 13:13 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        opt_history.save(Path(os.path.join(absolute_folder_path, 'opt_history.json')))
Поменял

2022-04-27 13:13 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +DEFAULT_PROJECTS_PATH = os.path.join(default_fedot_data_dir(), 'projects')
Done

2022-04-27 13:13 UTC, nicl-nno commented on docs/source/api/project_import_export.rst
> +pipeline will be converted to JSON format, InputData objects to CSV format. And all folder
Done

2022-04-27 13:13 UTC, nicl-nno commented on docs/source/api/project_import_export.rst
> +. **'Project'** on that context means: pipeline, data, and logs.
Поменял

2022-04-27 13:13 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    Unzipping zip file. Zip file should contains:
Done

2022-04-27 13:13 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    :return [Pipeline, InputData, InputData]: return array of Pipeline and InputData objects.
Убрал вообще перечисле

2022-04-27 13:14 UTC, nicl-nno commented on docs/source/api/project_import_export.rst
> +default path: ``/home/user/Fedot/projects/project_name`` with unarchived files.
Ага, заменил

2022-04-27 13:14 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    if len(name_split) == 2:
Убрал этот код

2022-04-27 13:14 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    shutil.unpack_archive(zip_path, folder_path)
Добавил удаление, т.к. это временная папка по сути.

2022-04-27 13:15 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    pipeline, train_data, test_data, opt_history = None, None, None, None
Поменял.

2022-04-28 07:37 UTC, IIaKyJIuH commented on fedot/core/data/data.py
> +    return all([column for column in array if isinstance(column, t)])
Для all разница во входном аргументе есть:
![image](https://user-images.githubusercontent.com/38308131/165701367-4515673b-b037-4aec-b83d-cf70ec2b3dd0.png)
То есть если в генераторе встречается False значение, то all завершается с False сразу.

2022-04-28 09:07 UTC, IIaKyJIuH requested changes

2022-04-28 09:07 UTC, IIaKyJIuH commented on fedot/utilities/project_import_export.py
> +        zip_path = Path(folder_name).with_suffix('.zip')
Не уверен, как тут должно быть, но для примера:
Если к нам с `zip_path` приходит путь `foo/bar/zoo`, то мы точно его должны разделить на `foo/bar/zoo` и `foo/bar/zoo.zip`, а не на `foo/bar/` и `zoo.zip`?

2022-04-28 09:07 UTC, IIaKyJIuH commented on test/unit/utilities/test_project_import_export.py
> +            shutil.rmtree(absolute_path)
Опять же, это всё тоже переписывается на `pathlib` (в данном случае проку немного, но для консистентности с другими блоками уже).
А ещё второе условие лучше записать, как `elif ...`

2022-04-28 16:22 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +    path_to_folder = os.path.join(DEFAULT_PROJECTS_PATH, folder_name)
Так и сделал.

2022-04-28 16:22 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +            shutil.rmtree(absolute_path)
Переписал

2022-04-28 16:22 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        zip_path = Path(folder_name).with_suffix('.zip')
Вроде первое, т.к. сначла создается папка foo/bar/zoo, а потом она упаковывается в zip.

2022-04-28 16:22 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    absolute_zip_path = os.path.join(absolute_folder_path, zip_path)
Переписал во всех основных местах.

2022-04-28 16:22 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    return [absolute_folder_path, absolute_zip_path, folder_name, zip_path]
Заменил на tuple

2022-04-28 22:01 UTC, nicl-nno commented on fedot/core/data/data.py
> +    return all([column for column in array if isinstance(column, t)])
Ок, согласен. Но пока вообще убрал эту функцию.

2022-04-28 22:01 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    if zip_path_split[-1].split('.')[-1] != 'zip':
Переработал, чуть изменив реализацию (чтобы можно было не указывать '.zip')

2022-05-04 08:56 UTC, MorrisNein commented on docs/source/fedot/features/pipeline_json.rst
> +- ~/project/model/my_pipeline,
Протестировал, в итоге используется директория `~\AppData\Local\Temp\FEDOT\projects\`, а не `~\Fedot\projects`. 

Сохранение проектов в `Temp` не кажется подходящим решением. В общем, нужно поправить либо описание, либо папку сохранения.

2022-05-04 17:07 UTC, nicl-nno commented on test/unit/utilities/test_project_import_export.py
> +    folder_path = os.path.join(str(fedot_project_root()), 'test', 'data', 'project', 'iris_classification')
Переписал

2022-05-04 17:07 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        os.makedirs(absolute_folder_path)
Переписал

2022-05-04 17:07 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        shutil.copy2(log_file_name, os.path.join(absolute_folder_path, os.path.split(log_file_name)[-1]))
Переписал

2022-05-04 17:07 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        os.rmdir(folder_path)
Поменял

2022-05-05 07:52 UTC, IIaKyJIuH commented on fedot/utilities/project_import_export.py
> +        shutil.copy2(log_file_name, os.path.join(absolute_folder_path, os.path.split(log_file_name)[-1]))
Всё круто, только ещё само условие перепиши: `if log_file_name.exists(): ...`

2022-05-05 07:57 UTC, IIaKyJIuH approved these changes

2022-05-05 10:42 UTC, nicl-nno commented on docs/source/fedot/features/pipeline_json.rst
> +- ~/project/model/my_pipeline,
Cделал чтобы если путь не абсолютный - то сохранялось в workdir.

2022-05-05 10:42 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        shutil.copy2(log_file_name, os.path.join(absolute_folder_path, os.path.split(log_file_name)[-1]))
Done

2022-05-05 11:18 UTC, IIaKyJIuH approved these changes

2022-05-05 12:10 UTC, maypink approved these changes

2022-05-05 13:29 UTC, MorrisNein requested changes

2022-05-05 13:45 UTC, MorrisNein requested changes

2022-05-05 13:45 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +    log.info(f'The exported project was saved on the path: {absolute_folder_path}')
Здесь, полагаю, подразумевался `absolute_zip_path`.
Когда проект экспортируется в workdir, в текущем варианте 
`absolute_folder_path` хранит путь к папке внутри дефолтного пути Федота, и она будет показана юзеру.

2022-05-05 14:00 UTC, MorrisNein requested changes

2022-05-05 14:27 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +    log.info(f'The exported project was saved on the path: {absolute_folder_path}')
Сообщение пофиксил.

2022-05-05 14:46 UTC, MorrisNein requested changes

2022-05-05 15:56 UTC, MorrisNein commented on fedot/utilities/project_import_export.py
> +        zip_path = folder_name.with_suffix('.zip')
И последний момент проглядели.
Тут теперь нужно 
```zip_path = zip_path.with_suffix('.zip')```

2022-05-05 15:58 UTC, MorrisNein approved these changes

2022-05-05 17:37 UTC, nicl-nno commented on fedot/utilities/project_import_export.py
> +        zip_path = folder_name.with_suffix('.zip')
Ага, поправил.

2022-05-05 17:51 UTC, merged