207 minor flaws
nccr-itmo/FEDOT pull request #210
Opened 2020-12-14 12:59 UTC by MAGLeb

Closed #207 

Исправил баги, кроме 4, не смог его воспроизвести.
Добавил пару тестов на случаи, которые исправил.

2020-12-14 12:59 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/models/preprocessing.py`](https://github.com/nccr-itmo/FEDOT/blob/e9b7993c32bb5d245944bd1bebb634d9b04dc131/fedot/core/models/preprocessing.py):

> [Line 112:1](https://github.com/nccr-itmo/FEDOT/blob/e9b7993c32bb5d245944bd1bebb634d9b04dc131/fedot/core/models/preprocessing.py#L112): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2020-12-15 13:49 UTC, BarabanovaIrina requested changes

2020-12-15 13:49 UTC, BarabanovaIrina commented on fedot/core/models/preprocessing.py
> +        ['Normalization', 'Scaling', 'ScalingWithoutImputation', 'EmptyStrategy']) -> str:
Мне кажется или без этой функции можно обойтись? Кмк можно либо обратный словарь сделать и доставать по ключу либо накатать функцию(не нашла с ходу родной функции python) - доставать ключ **по значению** из того же словаря.

2020-12-15 13:49 UTC, BarabanovaIrina commented on fedot/core/models/preprocessing.py
> +        return None
эту конструкцию можно заменить, если получать значение по ключу через get: dict_name.get(desired_key). Он как раз сам обработает случай, если не найдет ключ и вернет None сам.

Эту же функцию можно использовать для конвертации обратно, определив на вход либо str либо 'Normalization' и тд.

2020-12-15 13:49 UTC, BarabanovaIrina commented on fedot/core/models/preprocessing.py
> +def overwise_fit_the_model(model, data):
А это для чего? не нашла применение

2020-12-15 13:49 UTC, BarabanovaIrina commented on fedot/utilities/synthetic/chain_template_new.py
> +    def _get_folder_and_unique_chain_id(self, path_to_save: str):
Вот тут, если существует проблема переписывания файлов(папок), или надо уникальное что-то, может есть смысл добавлять в название текущее дату/время? во-первых, так будет проще искать, что последнее запускал то в последней папке и лежит. Не нужны лишние счетчики. А пользователю как надо, так он пусть и переименовывает.

2020-12-15 13:53 UTC, BarabanovaIrina commented on fedot/core/models/preprocessing.py
> +        return None
И еще return _string_for_preprocessing_strategy[string]() - кажется круглые скобки тут не нужны. Мы просто же возвращаем имя. А создание экземпляра происходит в процессе Node.fit().

2020-12-16 14:43 UTC, J3FALL requested changes

2020-12-16 14:43 UTC, J3FALL commented on fedot/core/models/preprocessing.py
> +class ScalingWithoutImputation(PreprocessingStrategy):
Ну да, логичнее видеть, что наследование расширяет интерфейсы, а не ограничивают их.

2020-12-16 14:43 UTC, J3FALL commented on fedot/core/models/preprocessing.py
> +        ['Normalization', 'Scaling', 'ScalingWithoutImputation', 'EmptyStrategy']) -> str:
Угу, можно сделать так:
```
def preproc_strategy_label_by_class(target_strategy: PreprocessingStrategy):
    for label, strategy in _string_for_preprocessing_strategy.values():
        if isinstance(target_strategy, strategy):
            return label
    return None
```

2020-12-16 14:43 UTC, J3FALL commented on fedot/core/models/preprocessing.py
> +        return None
И в целом, вместо string лучше использовать label.

2020-12-16 14:43 UTC, J3FALL commented on fedot/utilities/synthetic/chain_template_new.py
> +    def _get_folder_and_unique_chain_id(self, path_to_save: str):
В целом, поддерживаю идею с добавлением суффикса для новой папки, куда будет экспортироваться все.
Если файл существует, то (а) выбрасывать warning, (б) добавлять к названию нового файла еще суффикс=текущее время и (в) сохранять туда все.

А, и, кстати, мне что-то подсказывает, что механизм проверки того, что файл/директория уже существует и создания "папка_копия(2)" работает на уровне операционной системы.
Мб модули os/shutils это из коробки поддерживают?

2020-12-18 10:34 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
> +class ScalingWithoutImputation(PreprocessingStrategy):
Думал так как переписывать все равно будем оставил такую иерархию, хотя почему бы даже временный код не сделать правильно организованным. 
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/072a8c57fe0ef0dd09f0010a4dff17ec27426d47#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336L61-R94)

2020-12-18 10:35 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
>      DataTypesEnum.table: Scaling,
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/072a8c57fe0ef0dd09f0010a4dff17ec27426d47#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336L96-R109)

2020-12-18 10:35 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
> +        ['Normalization', 'Scaling', 'ScalingWithoutImputation', 'EmptyStrategy']) -> str:
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/072a8c57fe0ef0dd09f0010a4dff17ec27426d47#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336L111-R117)

2020-12-18 10:36 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
> +        return None
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/072a8c57fe0ef0dd09f0010a4dff17ec27426d47#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336L123-L136)

2020-12-18 10:36 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
> +def overwise_fit_the_model(model, data):
Забыл удалить.
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/072a8c57fe0ef0dd09f0010a4dff17ec27426d47#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336L123-L136)

2020-12-18 11:22 UTC, J3FALL requested changes

2020-12-18 11:22 UTC, J3FALL commented on fedot/core/models/preprocessing.py
> +    'scaling': Scaling
Тут ошибка, кажется.

2020-12-18 11:22 UTC, J3FALL commented on fedot/core/models/preprocessing.py
>          self.default = ImputationStrategy()
Слушай, можешь проверить заодно тесты на эти классы?
Там вроде не должно быть сложно, просто данные подобрать подходящие.
Нужно убедиться, что действительно данные с nan-ами нормально скалируются.

2020-12-18 11:23 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
>          self.default = ImputationStrategy()
Хорошо

2020-12-18 12:00 UTC, MAGLeb commented
Проверка нод с типом "direct_data_model" на идентичность, используя property descriptive_id, заканчивается неудачей. В данном случае ноды имеют одинаковый escriptive_id ('/n_direct_data_model_default_params') и не отличаются.

Также эта нода имеет cache.actual_cached_state, но в поле model где должна быть обученная модель записывается None.

2020-12-18 12:03 UTC, MAGLeb commented on fedot/utilities/synthetic/chain_template_new.py
> +    def _get_folder_and_unique_chain_id(self, path_to_save: str):
Удаление всех тестовых файлов в самом конце.
Добавить логгер.

Выбрасывать warning, json с таким названием существует.
Сохранение json and fitted model в одной папке, в названии префикс время
- 05/29/2015 5:50:17 AM name_of_chain
    - name_of_chain.json
    - fitted_model
        - model_1.pkl
        - model_2.pkl
        - model_3.pkl

2020-12-18 12:04 UTC, nicl-nno commented
> Проверка нод с типом "direct_data_model" на идентичность, используя property descriptive_id, заканчивается неудачей. В данном случае ноды имеют одинаковый escriptive_id ('/n_direct_data_model_default_params') и не отличаются.
> 
> Также эта нода имеет cache.actual_cached_state, но в поле model где должна быть обученная модель записывается None.

Для этой "модели" нет необходимости в кэшировании (т.к. это просто источник входных данных, который всегда является Primary-нодой), поэтому это нормальное поведение. Можно подумать, как более аккуратно для таких моделей указывать на факт остутствия кэша.

2020-12-22 12:18 UTC, BarabanovaIrina commented
А может есть смысл вынести chain_template_new.py куда-то повыше (и убрать new суффикс)? Хотя бы просто в utilities, они вроде как к synthetic уже не имеют отношения, а напрямую к цепочке, кмк.

2020-12-22 12:30 UTC, BarabanovaIrina commented on fedot/utilities/synthetic/chain_template_new.py
> +    def _get_folder_and_unique_chain_id(self, path_to_save: str):
Заметила, что тут используется warning библиотека. Есть смысл менять на наш логер? или это в принципе не тот случай, чтобы записывать данное сообщение куда-то?

2020-12-22 14:40 UTC, BarabanovaIrina requested changes

2020-12-22 14:40 UTC, BarabanovaIrina commented on fedot/utilities/synthetic/chain_template_new.py
> +        file_name = '.'.join(file_name_split[0:-1])
Вот тут кмк можно сделать проще. Судя по всему надо отделить папку от имени файла и имя файла от расширения. Предлагаю сделать более читабельным. (Вот это *path_split[0:-1] оч сложно кмк)

folder_name = os.path.dirname(path) - равносильно os.path.split(path)[0]
file_name = os.path.basename(path) - равносильно os.path.split(path)[1]
file_name_without_ext = file_name.split('.')[0]
file_extension = file_name.split('.')[1]

ну или хотя бы через чистый split.

2020-12-22 14:40 UTC, BarabanovaIrina commented on fedot/utilities/synthetic/chain_template_new.py
> +            if file_name_split[-1] == 'json':
Может это уже задротство, но строки с 85 по 87 дублируются в _check_for_json_existence(), которая используется в import_from_json. По факту это проверка файла на существование + некоторая валидация. Кмк, можно вынести в отдельную функцию типа path_validation, ну или хотя бы вложенность поменять на несколько if с обратными условиями. 

Но это субъективно, просто как предложение.

2021-01-11 09:37 UTC, MAGLeb commented on fedot/utilities/synthetic/chain_template_new.py
> +    def _get_folder_and_unique_chain_id(self, path_to_save: str):
Убрал использование warning, переписал все print на использование логгера.
Переписал тестовый файл, и классы ModelTemplate and ChainTemplate. Теперь стало немного понятнее логика, удалил не нужный код и постарался его оптимизировать.
Теперь сохраняется модель в одну папку с иерархией файлов как выше.
Изменил документацию сохранения цепочек.

2021-01-11 11:52 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
>          self.default = ImputationStrategy()
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/841dc42187671cacc877f207187e038642afc26a#diff-237a957c5e78ad597fc92fc1cfcf9b9d72f087176f8f433ba979750ccd38797aR27-R59) тест

2021-01-11 11:54 UTC, MAGLeb commented on fedot/utilities/synthetic/chain_template_new.py
> +            if file_name_split[-1] == 'json':
[Теперь](https://github.com/nccr-itmo/FEDOT/pull/210/commits/841dc42187671cacc877f207187e038642afc26a#diff-d37bafe3665bfddcc19c920ed4900379d7fee8196f6dbea4f05c3ef93b6e267eR126-R135) нужно указать директорию куда выгрузить модель и пробема с JSON форматом отпала. Также отрефакторил код и попытался следовать принципу KISS.

2021-01-11 11:59 UTC, MAGLeb commented on fedot/core/models/preprocessing.py
> +    'scaling': Scaling
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/210/commits/841dc42187671cacc877f207187e038642afc26a#diff-9186fa38f252fd01248620f72f94bcc5c668b6dae4a528aa779dacca6268039fL152-R166)

2021-01-11 14:12 UTC, J3FALL approved these changes

2021-01-11 15:50 UTC, BarabanovaIrina approved these changes

2021-01-12 09:55 UTC, merged