NLP init
nccr-itmo/FEDOT pull request #212
Opened 2020-12-15 08:59 UTC by BarabanovaIrina

+ New method InputData.from_text(), where you can pass meta_file.csv with text in it or path to directories with text files
+ New TextData class, where all the nlp utils are located. Not expected to use directly.

- [ ] Finish BatchLoader for creation of meta_file.csv for collections of data (images, text)

- [ ] Finish the text files -> meta_file.csv

2020-12-15 10:17 UTC, nicl-nno commented on fedot/core/models/data.py
> +class TextData:
Кмк TextData выглядит как смесь препроцессора и модели. 

Нет смысла TfidfVectorizer вынести как одну из моделей, а стемминг и лемматизацию - как этап препроцессинга для DataType = 'text' ?

2020-12-15 10:51 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +class TextData:
А разве TfidfVectorizer не будет тоже как препроцессинг, преобразующий текст в features? 

Если я правильно поняла, то тогда для текста всегда в цепочку придется включать ноду с TfidfVectorizer (или аналогом) перед моделями, решающими конкретную задачу (пр., классификации). Хотя с другой стороны, если по планам выносить препроцессинг в ноды, то может в этом есть смысл.

2020-12-15 10:59 UTC, nicl-nno commented on fedot/core/models/data.py
> +class TextData:
Выглядит как будто иметь ноду с TfidfVectorizer будет универсальнее, т.к. так будет проще подбирать структуру цепочки с помощью композера. Можно будет задать, что для primary-нод используются только модели-векторизаторы текст, а для secondary - уже классификаторы.

2020-12-15 11:20 UTC, nicl-nno requested changes

2020-12-15 11:20 UTC, nicl-nno commented on cases/spam_detection.py
> +    chain.add_node(node)
Вот это кстати можно в одну строчку записать
Chain(PrimaryNode('multinb'), manual_preprocessing_func=EmptyStrategy)

Кмк так удобнее.

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +        elif files_path:
Это опция для папки с файлами? Мб тогда достаточно проверять, что лежит по этому пути? Тогда можно одним параметров обойтись.

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +        frame = pd.read_csv(self.path)
Вопрос привычки, но я бы назвал df_texts или как-то так. Ниже по коду долго соображал, что такое frame.

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +        self.target = target
Может назвать это target_name или как-то так? А то где-то target - это массив, а где-то название столбца.

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +        features = tfidf_vectorizer.fit_transform(clean_messages)
А тут не нужно fit-ить tfidf_vectorizer на обучающей выборке, а transform делать уже на тестовой?

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +        new_text = " ".join(words)
Одинарные кавычки наверное нужны тут и ниже.

2020-12-15 11:20 UTC, nicl-nno commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
Пока не уверен, так ли нам нужен DataTypesEnum.text, но стоит над этим подумать. Все равно мы по факту какое-то единообразное представление текстовых входных данных имеем.

2020-12-15 14:55 UTC, J3FALL requested changes

2020-12-15 14:55 UTC, J3FALL commented on cases/spam_detection.py
> +    run_text_problem(data_path=data_file_abspath)
Тут ошибка - spamham.csv находится в data/spam.
Надо путь до файла исправить.

2020-12-15 14:55 UTC, J3FALL commented on cases/spam_detection.py
> +    nltk.download('wordnet')
Думаю, можно для этого извлечь отдельную функцию.

2020-12-15 14:55 UTC, J3FALL commented on cases/spam_detection.py
> +    chain.add_node(node)
Согласен.

2020-12-15 14:55 UTC, J3FALL commented on fedot/core/models/data.py
> +import os
Думаю, назрела задача разбиения скрипта data на несколько отдельных, с выделением нового модуля data.
Пока оставлю комментарий, чтобы не забыть.

2020-12-15 14:55 UTC, J3FALL commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
Можно вообще реализовать 2 метода для текстов:
один с мета-файлом, другой - с только с директорией, в которой лежат файлы.
Тогда проверки не нужны.

2020-12-15 14:55 UTC, J3FALL commented on fedot/core/models/data.py
> +class TextData:
Угу, выглядит так, что при текущей архитектуре логично перенести вот эти 2 итерации в препроцессинг:
self.stemmer = PorterStemmer
self.lemmanizer = WordNetLemmatizer

Можно пока прямо сделать такой комбинированный PreprocessingStrategy подкласс.
А вот TFIdf напрашивается как отдельная модель.

Да, в будущем хочется поддержать эти операции в виде отдельных нод, чтобы композер способен был за нас проделать эту простую, казалось бы, но необходимую операцию стэмминга и лемматизации.
Возможно, это будет работать не очень эффективно и тогда мы встроим эти операции в internal_preprocessing для модели TFIdf.

2020-12-15 14:55 UTC, J3FALL commented on fedot/core/models/data.py
> +        self.lemmanizer = WordNetLemmatizer
Разве здесь не должно быть: `self.stemmer = PorterStemmer()` ?
Ну, чтобы инстанс класса создать.

2020-12-17 19:36 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        self.lemmanizer = WordNetLemmatizer
А есть существенная разница создается он тут или в момент работы с ним и его методами? кроме того как сам объект нам не нужен, там отрабатывает его метод и все.

2020-12-17 19:37 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/102534848-77066500-40b8-11eb-8832-c6104051b622.png)

Так и задумано?)

2020-12-17 19:40 UTC, BarabanovaIrina commented
> ![image](https://user-images.githubusercontent.com/5711814/102534848-77066500-40b8-11eb-8832-c6104051b622.png)
> 
> Так и задумано?)
Сори, я подумала, что так делать не стоит, но все равно сделала. Может вынесем cases в отдельный репо?) Я просто не придумала, как эти файлы скачивать откуда-то или куда их положить.

2020-12-17 19:43 UTC, nicl-nno commented
> > ![image](https://user-images.githubusercontent.com/5711814/102534848-77066500-40b8-11eb-8832-c6104051b622.png)
> > Так и задумано?)
> 
> Сори, я подумала, что так делать не стоит, но все равно сделала. Может вынесем cases в отдельный репо?) Я просто не придумала, как эти файлы скачивать откуда-то или куда их положить.

Кмк простейший вариант - можно их запаковать в архив (tar, например) и при первом запуске распаковывать (вызывая для этого отдельный скрипт за пределами цепочки).

2020-12-17 19:45 UTC, BarabanovaIrina commented
> > > ![image](https://user-images.githubusercontent.com/5711814/102534848-77066500-40b8-11eb-8832-c6104051b622.png)
> > > Так и задумано?)
> > 
> > 
> > Сори, я подумала, что так делать не стоит, но все равно сделала. Может вынесем cases в отдельный репо?) Я просто не придумала, как эти файлы скачивать откуда-то или куда их положить.
> 
> Кмк простейший вариант - можно их запаковать в архив (tar, например) и при первом запуске распаковывать (вызывая для этого отдельный скрипт за пределами цепочки).

Ок, пока просто уберу их, а то даже ревью не сделать

2020-12-17 19:58 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        elif files_path:
[Разделено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-7f4842972609c1f77bd1d4513b2cdb81dbd78fdb4c2bd30ab882d07f2f80e7bbR68-R101) на 2 метода

2020-12-17 19:58 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        frame = pd.read_csv(self.path)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-7f4842972609c1f77bd1d4513b2cdb81dbd78fdb4c2bd30ab882d07f2f80e7bbR76-R77)

2020-12-17 20:00 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        self.target = target
Класса больше нет, в методах исправлено на [label](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-7f4842972609c1f77bd1d4513b2cdb81dbd78fdb4c2bd30ab882d07f2f80e7bbR69)

2020-12-17 20:09 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        features = tfidf_vectorizer.fit_transform(clean_messages)
Во всех примерах, которые я видела этот метод применяют просто на куске текста. По факту и fit и fit_transfrom делают одно и то же, только из fit возвращается self класса, а из fit_transform результат транфосформации ([source code](https://github.com/scikit-learn/scikit-learn/blob/0fb307bf3/sklearn/feature_extraction/text.py#L1801-L1845))

Но так как TfidfVectorizer теперь отдельная стратегия [VectorizeStrategy](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-bcf8154eca0b01d82e5c3ee8225a5bcec9e652964de85fe12b733e75a1db7577R7-R25), то разделено на fit и transform.

2020-12-17 20:10 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        new_text = " ".join(words)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336R107), [исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336R135)

2020-12-17 20:12 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
Кмк, только если будут еще какие-то виды InputData

2020-12-17 20:13 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    run_text_problem(data_path=data_file_abspath)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334R66)

2020-12-17 20:13 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    nltk.download('wordnet')
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334R12-R17)

2020-12-17 20:14 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
[Разделено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-7f4842972609c1f77bd1d4513b2cdb81dbd78fdb4c2bd30ab882d07f2f80e7bbR68-R101) на 2 метода

2020-12-17 20:33 UTC, BarabanovaIrina commented
в test теперь есть папка utilities, там тесты для файлов из fedot.utilities (но пока без synthetic)

2020-12-17 20:38 UTC, nicl-nno commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
Ну точно ещё будут изображения - и вроде странно хранить значение, означающее, что там table, когда там другой тип данных. Но Илья в своём [PR](https://github.com/nccr-itmo/FEDOT/pull/200) тоже пока не выносил в отдельный тип.

2020-12-17 20:41 UTC, BarabanovaIrina commented
Еще предлагаю убрать тесты на real_cases - потому что они не unit, или замокать, если в них все таки есть необходимость. Если дело в покрытии, то codecov можно настроить только на feodt директорию, а не весь репо. 

Сейчас видимо та самая ситуация, когда завис композер (если я правильно поняла) и билд был отменен по истечение 40 минут.

2020-12-17 21:11 UTC, nicl-nno commented
> Еще предлагаю убрать тесты на real_cases - потому что они не unit, или замокать, если в них все таки есть необходимость. Если дело в покрытии, то codecov можно настроить только на feodt директорию, а не весь репо.
> 
> Сейчас видимо та самая ситуация, когда завис композер (если я правильно поняла) и билд был отменен по истечение 40 минут.

Обсудили в тг, что пока можно и отключить проблемный тест, но в перспективе хорошо бы вынести полноценный прогон cases и тяжеловесных examples в интеграционные nightly-тесты (раз гитхаб экшензы это умеют https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events)

2020-12-18 11:08 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    chain.add_node(node)
Теперь [так](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334R21-R25)

2020-12-18 14:44 UTC, BarabanovaIrina commented
@nicl-nno Добавила архив и функцию разархивирования в spam-detection.py

2020-12-18 16:04 UTC, J3FALL commented on cases/spam_detection.py
> +    run_text_problem(data_path=data_file_abspath)
Теперь у меня выскакивает такая проблема при запуске этого скрипта:
![image](https://user-images.githubusercontent.com/7864250/102634930-9dcda580-4163-11eb-8b07-d97b01556a08.png)
Кажется, ошибка в json-репозитории, если поправить путь до скрипта, то все работает:
![image](https://user-images.githubusercontent.com/7864250/102635074-d5d4e880-4163-11eb-9845-d12be7ea147f.png)

2020-12-18 16:11 UTC, J3FALL commented on fedot/core/models/data.py
> +        self.lemmanizer = WordNetLemmatizer
Существенной разницы нет)
Просто в ООП обычно все вокруг объектов крутится. Нужно что-то сделать - создается объект, и происходит вызов функции этого объекта.
А когда есть ссылка на класс - то уже странно.

2020-12-18 17:16 UTC, J3FALL requested changes

2020-12-18 17:16 UTC, J3FALL commented on fedot/utilities/load_data.py
> +import os
Мне кажется, этот скрипт должен быть где-то в fedot/core.
Думаю, стоит уже сейчас задать новый package data и поместить туда скрипты, связанные с InputData + этот скрипт.

2020-12-19 11:27 UTC, BarabanovaIrina commented on fedot/utilities/load_data.py
> +import os
[Добавлен] package(https://github.com/nccr-itmo/FEDOT/pull/212/commits/2f205be810d5fcc688ea0118263bf34743d0f026#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052e)
load_data.py [переехал](https://github.com/nccr-itmo/FEDOT/pull/212/commits/2f205be810d5fcc688ea0118263bf34743d0f026#diff-3af98de107d9887540bb794f677eed030add8f578803e0f48e0434a26ce10f2b)

2020-12-19 11:28 UTC, BarabanovaIrina commented on fedot/utilities/load_data.py
> +    def __init__(self, path: str, read_mode: str = 'r'):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/commits/2f205be810d5fcc688ea0118263bf34743d0f026#diff-3af98de107d9887540bb794f677eed030add8f578803e0f48e0434a26ce10f2bL8-R8)

2020-12-19 11:29 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +def execute_cahin_for_text_problem(train_data, test_data):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/commits/2f205be810d5fcc688ea0118263bf34743d0f026#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334L82-R83)

Путь тоже [исправлен](https://github.com/nccr-itmo/FEDOT/pull/212/commits/2f205be810d5fcc688ea0118263bf34743d0f026#diff-a5c1624bd36467920ea4aedc11707222e45cce478c7c6728bbdc08424c455621L78-R78)

2020-12-21 09:46 UTC, J3FALL commented on cases/spam_detection.py
> +    # run_text_problem_from_saved_meta_file()
Вот тут закомменчены другие функции - это опечатка или так задумано?

2020-12-21 10:29 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +        self.lemmanizer = WordNetLemmatizer
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336R93-R94)

2020-12-21 10:35 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +class TextData:
[Перенесен](https://github.com/nccr-itmo/FEDOT/pull/212/files#diff-c60bc130b0503a779c985bdcf94c4ac67fae943e051512e2639864fdaba0c336R91-R149) под PreprocessingStrategy

2020-12-21 11:12 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    # run_text_problem_from_saved_meta_file()
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/commits/c4afcea945859eafcd336ff85ce859db7327c167#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334L76-R78)

2020-12-21 11:12 UTC, BarabanovaIrina commented on fedot/core/models/data.py
> +                             target=target, task=task, data_type=DataTypesEnum.table)
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/212/commits/c4afcea945859eafcd336ff85ce859db7327c167#diff-a5c1624bd36467920ea4aedc11707222e45cce478c7c6728bbdc08424c455621L75-R75) тип text

2020-12-23 11:25 UTC, nicl-nno commented on cases/spam_detection.py
> +from fedot.core.composer.node import PrimaryNode, SecondaryNode
Кажется эти пути нужно обновить, т.к. chain теперь не в composer и пример не запускается.

2020-12-24 14:34 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +from fedot.core.composer.node import PrimaryNode, SecondaryNode
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/212/commits/569a24280ee75b2313a6bd3c5de5aa7b5afae39e#diff-831ea99136a41dcfa3d18052e301127988caae2fcfc30dd6a50fb3e6545e8334L6-R9)

2020-12-24 16:04 UTC, nicl-nno approved these changes

2020-12-24 16:19 UTC, J3FALL commented
@BarabanovaIrina Ира, а можешь еще в readme добавить ссылку на твой скрипт cases/spam_detection.py?
Вот сюда:
![image](https://user-images.githubusercontent.com/7864250/103098674-b125b880-461c-11eb-9389-35501637f3d6.png)

2020-12-24 16:25 UTC, J3FALL commented
Еще резонно добавить описание примера с текстами в readthedocs, но можно это сделать в рамках другой задачи:
see #219.

2020-12-26 18:32 UTC, nicl-nno approved these changes

2020-12-26 18:48 UTC, merged