Error with tuning the non-tunable models (e.g. PCA) fixed
nccr-itmo/FEDOT pull request #213
Opened 2020-12-17 19:23 UTC by nicl-nno

Now, if the fine_tune method of the model in node returns None (e.g PCA, it means that the model can not be tuned), the whole chain tuning fails.

Example:

Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\pydevd.py", line 1434, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2019.3.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PycharmProjects\new fed\FEDOT\cases\credit_scoring_problem_multiobj.py", line 102, in <module>
    run_credit_scoring_problem(full_path_train, full_path_test, is_visualise=True)
  File "D:\PycharmProjects\new fed\FEDOT\cases\credit_scoring_problem_multiobj.py", line 74, in run_credit_scoring_problem
    iterations=50)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\composer\chain.py", line 122, in fine_tune_primary_nodes
    node.fine_tune(input_data, max_lead_time=max_lead_time, iterations=iterations)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\composer\node.py", line 157, in fine_tune
    iterations=iterations)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\models\model.py", line 135, in fine_tune
    predict_train = self.predict(fitted_model, data)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\models\model.py", line 104, in predict
    predict_data=prepared_data)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\models\evaluation\data_evaluation.py", line 97, in predict
    return self._model_specific_predict(trained_model, predict_data)
  File "D:\PycharmProjects\new fed\FEDOT\fedot\core\models\evaluation\data_evaluation.py", line 74, in predict_pca
    return pca_model.transform(predict_data.features)[:, :(pca_model.last_component_ind + 1)]
AttributeError: 'NoneType' object has no attribute 'transform'

Fixed by raising of intermediate exception. Also, the stability of the tuning test is improved.

2020-12-18 11:58 UTC, BarabanovaIrina requested changes

2020-12-18 11:58 UTC, BarabanovaIrina commented on test/chain/test_chain_tuning.py
> +    for _ in range(5):
Может создать задачу, что этот тест требует мок?

2020-12-18 11:58 UTC, BarabanovaIrina commented on fedot/core/models/model.py
> +                raise ValueError(f'{self.model_type} can not be fitted')
А можно тогда еще на fine_tune в EvaluationStrategy навесить декоратор abstractmethod? а то при создании новых стратегий идея не ругается, что он обязательный.

2020-12-18 15:47 UTC, nicl-nno commented on test/chain/test_chain_tuning.py
> +    for _ in range(5):
Покопался и нашел баг:
1) Score для задачи регресии нужно сравнивать через >, а не < - т.к. для него стоит greater_is_better = False, которые добавляет к RMSE знак минус.
2) Судя по всему, после прогона fine_tune нужно делать fit_from_scratch - иначе там какие-то странные параметры используются. После этого стало работать стабильнее и чаще давать прирост для цепочки с одной нодой. 

Попробовал его исправить.

2020-12-18 15:47 UTC, nicl-nno commented on fedot/core/models/model.py
> +                raise ValueError(f'{self.model_type} can not be fitted')
Навесил.

2020-12-19 11:39 UTC, BarabanovaIrina approved these changes

2020-12-19 11:50 UTC, merged