Output modes for classification added
nccr-itmo/FEDOT pull request #214
Opened 2020-12-18 15:13 UTC by nicl-nno

In the current version only probabilities can be returned for the classification problems #187 .

Now the 3 mode is implemented:
'probs'/'default' - probability of positive class (all probabilities if >2 classes)
'full_probs' - probabilities for each class
'labels' - labels of the classes (0,1,2...)

2020-12-18 15:13 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`test/chain/test_chain.py`](https://github.com/nccr-itmo/FEDOT/blob/483fb9ef821f4e69702ee83de7c3a8ffb5bfe05f/test/chain/test_chain.py):

> [Line 222:83](https://github.com/nccr-itmo/FEDOT/blob/483fb9ef821f4e69702ee83de7c3a8ffb5bfe05f/test/chain/test_chain.py#L222): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2020-12-18 15:46 UTC, J3FALL requested changes

2020-12-18 15:46 UTC, J3FALL commented on fedot/core/composer/chain.py
> +        :param output_mode: desired output for models (e.g. labels, probs, full_probs)
1. Там еще есть опция default, думаю, стоит про нее указать, что является по умолчанию.
2. Чем отличается probs от full_probs? 
full_probs - это когда выдаются вероятности каждого класса, а probs - только лучшего, или как?

2020-12-18 15:46 UTC, J3FALL commented on fedot/core/composer/node.py
> +    def predict(self, input_data: InputData, output_mode: str = 'default', verbose=False) -> OutputData:
Добавь здесь перенос строки.

2020-12-18 15:46 UTC, J3FALL commented on fedot/core/models/evaluation/evaluation.py
> +                raise NotImplementedError()
Вот этот кейс не очень понял.

2020-12-18 15:46 UTC, J3FALL commented on fedot/core/models/evaluation/evaluation.py
>  from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
Смотри, а если в цепочке будет не sklearn-модель?
По логике получается, что и для моделей из других фреймворков нужна эта штука.
Как отработает скрипт, если в цепочке будет, например, нейронка из keras-а, а ей задать недефолтный output_mode?

2020-12-18 15:46 UTC, J3FALL commented on test/tasks/test_classification.py
> +    assert results.predict.shape == (len(test_data.target), 2)
Уже спрашивал выше про output_mode=probs.
Тут нет теста на этот пример, почему?

2020-12-18 15:50 UTC, nicl-nno commented on fedot/core/models/evaluation/evaluation.py
> +                raise NotImplementedError()
Если нет хотя бы двух классов в данных, то что-то пошло не так и классификация не имеет смысла.

2020-12-18 15:52 UTC, nicl-nno commented on fedot/core/models/evaluation/evaluation.py
>  from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
Да, придется делать так, но сейчас у нас все модели-классификаторы вроде используетю sklearn-стратегию. Keras сейчас только для рядов.

2020-12-18 15:57 UTC, J3FALL commented on fedot/core/models/evaluation/evaluation.py
> +                raise NotImplementedError()
А, ну да, логично )
Я чето тупанул, извиняюсь :)

2020-12-18 15:57 UTC, J3FALL commented on fedot/core/models/evaluation/evaluation.py
>  from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
В ветке с классификацией картинок, видимо, нужно будет это учесть.

2020-12-18 16:10 UTC, nicl-nno commented on fedot/core/models/evaluation/evaluation.py
>  from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
Ага. @v1docq учти, когда будешь дорабатывать.

2020-12-18 19:13 UTC, nicl-nno commented on fedot/core/composer/chain.py
> +        :param output_mode: desired output for models (e.g. labels, probs, full_probs)
1. [Указал](https://github.com/nccr-itmo/FEDOT/pull/214/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR94-R98).
2. Сейчас для бинарной классификации выдается только вероятность позитивного класса (т.к. 2-я вероятность просто дополняет её до единицы и не является полезным признаком). С full_probs в любом случае для N классов возвращается N вероятностей.

2020-12-18 19:14 UTC, nicl-nno commented on fedot/core/composer/node.py
> +    def predict(self, input_data: InputData, output_mode: str = 'default', verbose=False) -> OutputData:
Done

2020-12-18 19:14 UTC, nicl-nno commented on test/tasks/test_classification.py
> +    assert results.predict.shape == (len(test_data.target), 2)
Это вариант по умолчанию, он и так везде тестируется.
Добавил в этот же тест [проверку](https://github.com/nccr-itmo/FEDOT/pull/214/files#diff-cf130fc9a19e73c2b80c06f4bad94fd7fc72c80998e572a314506b6cf40b171fR117-R121), что с ним всё ок.

2020-12-18 19:15 UTC, nicl-nno commented
+ Переструктурировал проект, добавив папка chains и data.
+ Удалил dummy-composer #120

2020-12-21 09:31 UTC, J3FALL approved these changes

2020-12-21 09:32 UTC, J3FALL commented
Думаю, package в тестах тоже стоит переименовать, чтобы он соответствовал fedot/core/chains.
![image](https://user-images.githubusercontent.com/7864250/102761789-6d1a8580-4388-11eb-859f-8e399303101e.png)

2020-12-21 11:39 UTC, merged