multi-obj optimization and fit time control were added
nccr-itmo/FEDOT pull request #215
Opened 2020-12-21 11:40 UTC by YanaPolonskaya

1. Была добавлена возможность использования алгоритмов многокритериальной оптимизации. Практически все инструменты для этого я взяла из deap, пришлось немного переделать класс fitness из deap под multi-objective fitness (это вынесено в отдельный файл). В selection можно добавить любой тип многокритериальной селекции из deap(сейчас я добавила SPEA2 и NSGA2 селекции, интересно бы попробовать например selNSGA3WithMemory, но т к тут немного по-другому надо добавлять поскольку это класс с памятью которая должна обновляться подумаю как лучше встроить его чтобы выглядело норм). Пришлось значительно изменить вычисление метрики в gp-composer-е.

parameter-free-optimiser для многокритериальной оптимизации пока не адаптировала, и не знаю нужно или нет. Там вроде все то же самое (основано на том есть улучшения или нет улучшений - в многокритериальном можно просто по архиву смотреть), но еще считается std дополнительно для фитнеса в популяции, можно наверное средний std рассчитвать по всем objectiv-ам.

2. Добавила так же прерывание fit-а модели при помощи библиотеки multiprocessing (создается процесс, и он прерывается в том случае если модель фитится более заданного ограничения по времени). По умолчанию эта опция отключена, но если передать в  GPComposerRequirements параметр model_fit_time_constraint (например сейчас в credit_scoring экспериментах я задала model_fit_time_constraint=900 (15 мин)) то ограничение будет работать, и в случае если не модель не входит в рамки заданного кол-ва времени, цепоче в которую она входит назначаются плохие фитнесы.

2020-12-21 11:40 UTC, pep8speaks commented
Hello @YanaPolonskaya! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

























* In the file [`fedot/core/models/evaluation/keras_eval.py`](https://github.com/nccr-itmo/FEDOT/blob/efae83b3025caddc371ffeb97a0164eff9e0fbd6/fedot/core/models/evaluation/keras_eval.py):

> [Line 5:1](https://github.com/nccr-itmo/FEDOT/blob/efae83b3025caddc371ffeb97a0164eff9e0fbd6/fedot/core/models/evaluation/keras_eval.py#L5): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file



* In the file [`test/composer/test_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/efae83b3025caddc371ffeb97a0164eff9e0fbd6/test/composer/test_composer.py):

> [Line 224:121](https://github.com/nccr-itmo/FEDOT/blob/efae83b3025caddc371ffeb97a0164eff9e0fbd6/test/composer/test_composer.py#L224): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)

2020-12-21 11:44 UTC, YanaPolonskaya commented
Добавлю так же:
1. Сохранение времени fit в свойствах цепочки, чтобы можно было на графике нарисовать.
2. Визуализацию сходимости objectiv-ов при помощи boxplot-ов.

2020-12-22 17:42 UTC, nicl-nno requested changes

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    bad_metrics.append(0.999)
А в чем тут суть?

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/node.py
> +    def fit_with_time_limit(self, data: InputData, time: int = 900) -> Manager:
Это видимо нужно private-методом сделать

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                 start_depth: int = 3, multi_objective: bool = False, the_most_importent_obj_num=0):
"the_most_importent_obj_num"

Опечатка, плюс не описан в docstring. А в чем вообще суть этого параметра?

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    self.prev_archive = deepcopy(self.archive)
А есть ли смысл разделять переменные? Вроде внутри self.best_individual и так возвращается архив в многокритериальном случае.

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    if self.with_elitism:
Тут if-ы можно объединить.

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                found_inds.append(True if eq_inds else False)
Вроде eq_inds  и так логический тип?

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
> +                         objectives_names: Tuple[str] = ("ROC-AUC", "Complexity"),
Одинарные кавычки лучше.

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/selection.py
> +from deap import tools
deap в requirements нужен

2020-12-22 17:42 UTC, nicl-nno commented on fedot/core/composer/optimisers/selection.py
> +    SPEA2 = 'SPEA2'
Лучше в нижней раскладке названия элементов enum-а.

2020-12-22 17:42 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +                                                is_visualise=True)
Но ведь в многокритериальном случае тут должно возвращаться несколько chain, а не одна?

2020-12-24 16:31 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    evaluated_metrics.append(metric_func(chain))
А точно есть необходимости в таком разделении? 
Что плохого в том, чтоб в структурные метрики передаются лишние параметры.

2020-12-25 11:10 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    bad_metrics.append(0.999)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R137).

2020-12-25 11:11 UTC, YanaPolonskaya commented on fedot/core/composer/node.py
> +    def fit_with_time_limit(self, data: InputData, time: int = 900) -> Manager:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-d3ca12ad2d1f6aa348a795c29d2370bc544af899c14a80e7ab44a578612afdebR97).

2020-12-25 11:31 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                 start_depth: int = 3, multi_objective: bool = False, the_most_importent_obj_num=0):
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-e9091ad680475e338d53ff0e6e47645a3f1b77e9c367b18de21835946b0222abR50). Я добавляла его чтобы самого лучшего индивида выбирать, по самой важной метрике (ROC-AUC), но сейчас мне тоже кажется что это незачем.

2020-12-25 11:32 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    self.prev_archive = deepcopy(self.archive)
Fixed.

2020-12-25 11:34 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    if self.with_elitism:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-e9091ad680475e338d53ff0e6e47645a3f1b77e9c367b18de21835946b0222abR184).

2020-12-25 11:35 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                found_inds.append(True if eq_inds else False)
Нет, он содержит список индивидов срвпадающих с тем, которого мы ищем в архиве!

2020-12-25 11:36 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
> +                         objectives_names: Tuple[str] = ("ROC-AUC", "Complexity"),
Fixed.

2020-12-25 11:36 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/selection.py
> +from deap import tools
Fixed.

2020-12-25 11:47 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/selection.py
> +    SPEA2 = 'SPEA2'
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-079dc27340a954eb1dd989a8d2d3d4b42a485b78bba6d8756123f6327683b8ebR11-R12).

2020-12-25 11:48 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +                                                is_visualise=True)
[Fixed](Возвращаю несколько).

2020-12-25 11:49 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    evaluated_metrics.append(metric_func(chain))
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/ba05551b11be7ef2a0fbfec0f7f4d9880e1cd38a#diff-e9091ad680475e338d53ff0e6e47645a3f1b77e9c367b18de21835946b0222abR184-R185).

2020-12-25 13:03 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    bad_metrics.append(0.999)
Не будет удобнее всё-таки None или np.nan использовать? Ведь если такой фитнес попадет всё-таки в историб (например, из-за лимита времени), то его будет достаточно сложно отсеять.

2020-12-25 13:04 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                found_inds.append(True if eq_inds else False)
Т.е. это проверка на то, пустой список eq_inds или нет?

Тогда это можно записать как:
found_inds.append(len(eq_inds)>0)

ну и found_inds лучше как-то иначе тогда назвать (раз там не найденные индексы, а какие-то флаги)

2020-12-25 13:07 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +                                                is_visualise=True)
Тогда надо ещё и описание выходного типа для compose_chain поменять на Union[Chain, List[Chain]]

2020-12-25 13:09 UTC, nicl-nno commented on fedot/core/composer/chain.py
> +        self.computation_time = None
В перспективе можно будет разделить на fit_time и predict_time, но пока пусть будет так.

2020-12-25 13:23 UTC, nicl-nno commented on fedot/core/composer/timer.py
> +        return self.process_terminated
А не получится этим методы отправить в базовый класс?

Сейчас в потомках Timer дублируется куча методов, маскимум меняется текст сообщений.

Ну и print на логгер надо заменить.

2020-12-28 13:30 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                    bad_metrics.append(0.999)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/31d7a40464b9a71eeff50094806bfb71dcd090a5#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R142-R143).

2020-12-28 13:39 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +                                                is_visualise=True)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/31d7a40464b9a71eeff50094806bfb71dcd090a5#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R84).

2020-12-28 14:42 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                found_inds.append(True if eq_inds else False)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/d91d4370a50bb5cf53bad85f2ad6aa397ded8303#diff-e9091ad680475e338d53ff0e6e47645a3f1b77e9c367b18de21835946b0222abL332-R324).

2020-12-28 14:43 UTC, YanaPolonskaya commented on fedot/core/composer/timer.py
> +        return self.process_terminated
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/d91d4370a50bb5cf53bad85f2ad6aa397ded8303#diff-b006009ccc452e1bcae70923bb78bdfd08c1b22c19d8c62f453cae4dd47ea5f1).

2020-12-28 14:45 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                        is_chain_shared: bool, chain: Chain) -> Union[Tuple[Any], None]:
А тут нельзя Optional[Tuple[Any]] написать?

2020-12-28 15:04 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +                                                      selection_types=[SelectionTypesEnum.nsga2], start_depth=2)
А почему start_depth указывается именно тут, а не в GPComposerRequirements, как всё остальное?

2020-12-29 00:06 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_operators.py
> +        fitness = calculated_fitness
Тут бы лучше читалось return None кмк

2021-01-14 14:35 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_operators.py
> +        fitness = calculated_fitness
Fixed.

2021-01-14 14:35 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +                                                      selection_types=[SelectionTypesEnum.nsga2], start_depth=2)
Fixed.

2021-01-14 14:35 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                        is_chain_shared: bool, chain: Chain) -> Union[Tuple[Any], None]:
Fixed.

2021-03-15 14:02 UTC, nicl-nno requested changes

2021-03-15 14:02 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_optimiser.py
> +            num_of_new_individuals = self.requirements.pop_size - 1  # !
Видимо лишний коммент. А почему кстати -1?

2021-03-15 15:03 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            -> Union[Chain, List[Chain]]:
Не оч. читаемый перенос, лучше под другому отформатировать

2021-03-15 15:13 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, model_fit_time_constraint=900,
Может это корректнее назвать max_chain_fit_time? Это же не про отдельную модель.

2021-03-15 15:20 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, model_fit_time_constraint=900,
Алсо, 900 секунд - это все равно оч. долго на практике. Может, что-то вроде 20 задать для cases?

2021-03-15 15:21 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +    scheme_type = GeneticSchemeTypesEnum.steady_state
Может parameter_free тут включить? Раз по экспериментам он лучше.

2021-03-15 15:24 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_metrics = metrics
Кажется для МК-случая вывод неправильный:

![image](https://user-images.githubusercontent.com/5711814/111177877-b101dd00-85bb-11eb-9bb8-84c9cf30496e.png)

2021-03-15 15:33 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_operators.py
> +def is_equal_archive(old_archive: Any, new_archive: Any) -> bool:
Кажется это не особо gp_operators - лучше в отдельный скрипт вынести.

2021-03-15 15:34 UTC, nicl-nno commented on fedot/core/composer/optimisers/selection.py
> +    """
Описание не сходится с реальными параметрами

2021-03-15 15:43 UTC, nicl-nno commented on fedot/core/composer/optimisers/multi_objective_fitness.py
> +#    This code is modified part of DEAP library (Library URL: https://github.com/DEAP/deap).
![image](https://user-images.githubusercontent.com/5711814/111180715-5b7aff80-85be-11eb-8f7c-37fe1828dab7.png)


Можно вот так все раскидать кмк

2021-03-15 17:18 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +             global_cache_dict: Manager = None):
Потому что для сбора инфы внутри процесса нужно использовать dict Manager из multiprocessing-a (там есть и другие различные типы объектов). Обычный dict для этого не подходит

2021-03-15 17:19 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +            self.global_cache_update_outside_the_process(dict(global_cache_dict))
Да, другого варианта мне не пришло на ум с условием того как устроен сейчас кеш.

2021-03-15 17:27 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +             global_cache_dict: Manager = None):
А нельзя тогда оба dict объединить в process_state? Пусть кэш возвращается тем же способом, что и chain и train_predicted.

2021-03-15 17:30 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +             global_cache_dict: Manager = None):
Да можно, но тогда мы будем обращаться к privated-полю класса. Объединю

2021-03-15 17:31 UTC, nicl-nno commented on fedot/core/chains/node.py
> +    def append(self, fitted_model, return_dict: Manager = None):
Или даже не так: почему в конце fit не собирать кэш из всех нод (fitted_node.cache)? И потом уже вне процесса делать node.cache.import_from_other_cache?

Или конечно это упирается в проблемы с расшариванием, то черт с ним.

2021-03-15 22:00 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +        for model in reversed(requirements.secondary):
reversed потому что мы удаляем элементы из списка при помощи remove в цикле, если не перевернуть его будет работать неправильно https://stackoverflow.com/questions/10665591/how-to-remove-list-elements-in-a-for-loop-in-python.
Ок, помечу как TODO, но если такая реализация не нравится я могу поменять это на проверки через if-ы в кроссовере, мутации и в функции генерации цепочки

2021-03-15 22:06 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +        for model in reversed(requirements.secondary):
>reversed потому что мы удаляем элементы из списка при помощи remove в цикле, если не перевернуть его будет работать неправильно

Проще тогда через list comprehension сделать фильтрацюи списка, вынеся проверку допустимости модели в отдельную функцию вроде can_be_secondary_requirement

2021-03-15 22:13 UTC, nicl-nno commented on test/unit/chains/test_chain.py
> +        set_start_method("spawn", force=True)
Кстати, а почему это делается только в одном тесте? Лучше наверное это в fit вынести, чтобы на линуксе не только один этот пример работал.

2021-03-16 22:02 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +                                              self.computation_time is None else False
Fixed.

2021-03-16 22:06 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +             global_cache_dict: Manager = None):
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR78).

2021-03-16 22:07 UTC, YanaPolonskaya commented on fedot/core/chains/node.py
> +    def append(self, fitted_model, return_dict: Manager = None):
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR78).

2021-03-16 22:07 UTC, YanaPolonskaya commented on fedot/core/composer/composing_history.py
>      def _add_history_to_csv(self, f, fitness: float, models_quantity: int, depth: int, idx: int = None,
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-c2581b323e0ca711f209735be927b074c66a0211fdca41d7542c7f94bbae498eR66).

2021-03-16 22:09 UTC, YanaPolonskaya commented on fedot/core/composer/composing_history.py
> +            historical_fitness = [[chain.fitness.values[0] for chain in pop] for pop in self.chains]
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-c2581b323e0ca711f209735be927b074c66a0211fdca41d7542c7f94bbae498eR83).

2021-03-16 22:09 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +            evaluated_metrics = tuple(evaluated_metrics)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R146).

2021-03-16 22:10 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +        for model in reversed(requirements.secondary):
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R193).

2021-03-16 22:11 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +            self.optimiser_parameters.regularization_type = RegularizationTypesEnum.none
Добавила [TODO](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R231) пока, там вроде быстро переделать, отредактирую и вкину.

2021-03-16 22:11 UTC, YanaPolonskaya commented on test/unit/chains/test_chain.py
> +    assert predicted_second is not None
computation_time_first is None

2021-03-16 22:12 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
> +            if type(history.all_historical_fitness[0]) is not list:
Это место [изменила](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-7db9dda60b06a09eb58a8bf574485ff53a3f0678a531348070a4a64024540028R139-R141).

2021-03-16 22:17 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
>      def next_population_size(self, offspring: List[Any]) -> int:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f03dfa11e198d83284da900d60675a30bad448aff5cced26c05daa2814a4938dR220).

2021-03-16 22:17 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
> +            self.log.info("Result:")
Fixed.

2021-03-16 22:17 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
> +                    filtered_archive_items = duplicates_filtration(archive=self.archive,
а зачем он там ? архива же нет

2021-03-16 22:17 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/mutation.py
> +            if number_of_attempts == 10:
Fixed.

2021-03-16 22:18 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/mutation.py
>                                                     chain_generation_params=chain_generation_params)
Fixed.

2021-03-16 22:21 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/multi_objective_fitness.py
> +#    This code is modified part of DEAP library (Library URL: https://github.com/DEAP/deap).
Fixed.

2021-03-16 23:07 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_optimiser.py
> +            num_of_new_individuals = self.requirements.pop_size - 1  # !
Fixed.

2021-03-16 23:07 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +            -> Union[Chain, List[Chain]]:
Fixed.

2021-03-16 23:10 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, model_fit_time_constraint=900,
Fixed.
20 мне кажется это может быть слишком мало, или для конкретных случаев которые в cases сейчас?

2021-03-16 23:10 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +    scheme_type = GeneticSchemeTypesEnum.steady_state
Fixed.

2021-03-16 23:10 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_metrics = metrics
Fixed.

2021-03-16 23:12 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_operators.py
> +def is_equal_archive(old_archive: Any, new_archive: Any) -> bool:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-2a78b9c46828b1233d2f6f7d96211dd3f73271c3ff422365b615f090b323f4a3). Правда назвала пока неочень, может есть идея как это назвать ? 
Я думала individuals_operations, но тоже как-то стремно звучит

2021-03-16 23:13 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/selection.py
> +    """
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-cd9cde74e82e72c73dd6501a69d201c32348a6983731a5a6ef027b4851bb2a8bR17-R20).

2021-03-16 23:15 UTC, YanaPolonskaya commented on test/unit/chains/test_chain.py
> +        set_start_method("spawn", force=True)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R101-R104).

2021-03-17 10:41 UTC, nicl-nno commented on fedot/core/composer/optimisers/multi_objective_fitness.py
> +#    This code is modified part of DEAP library (Library URL: https://github.com/DEAP/deap).
![image](https://user-images.githubusercontent.com/5711814/111455185-85e7cc80-8726-11eb-810d-f91576abf8aa.png)

Опечатка в названии

2021-03-17 10:49 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/multi_objective_fitness.py
> +#    This code is modified part of DEAP library (Library URL: https://github.com/DEAP/deap).
Fixed.

2021-03-17 11:30 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_operators.py
> +def is_equal_archive(old_archive: Any, new_archive: Any) -> bool:
population_utils мб

2021-03-17 23:00 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_operators.py
> +def is_equal_archive(old_archive: Any, new_archive: Any) -> bool:
Fixed.

2021-03-18 15:59 UTC, nicl-nno commented on cases/credit_scoring_problem_multiobj.py
> +        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, model_fit_time_constraint=900,
Надо смотреть - вообще 20 достаточно, но с учетом падения производительности при запуски в потоке - мб и нет.
Но тогда проще в примерах model_fit_time_constraint вообще отключить.

2021-03-18 16:10 UTC, nicl-nno commented on test/unit/chains/test_chain.py
> +    assert predicted_second is not None
Ну можно его дополнительно вне fit определить. Иначе не проверяется напрямую, что досрочное прерывание задачи работает.

2021-03-18 16:12 UTC, nicl-nno commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
>      def next_population_size(self, offspring: List[Any]) -> int:
Стоит ещё это функции сделать приватными, чтобы было очевиднее, что вызывать нужно не их, а next_population_size.

2021-03-22 23:14 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +        crossover_prob=0.8, mutation_prob=0.8, max_lead_time=max_lead_time, model_fit_time_constraint=900,
Отключила

2021-03-22 23:24 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/112070501-d627ba00-8b7e-11eb-81d3-53c57a6790fa.png)

Может в рамках борьбы с зависаниями вот тут поставить в цикле тоже учитывать а) число итерации б) лимит времени на композирование?

2021-03-22 23:33 UTC, YanaPolonskaya commented on test/unit/chains/test_chain.py
> +    assert predicted_second is not None
к сожалению оно дольше работает, поэтому такой assert не пройдет(

2021-03-22 23:34 UTC, nicl-nno commented on test/unit/chains/test_chain.py
> +    assert predicted_second is not None
А если вравнгить два варианта ограничений на computation_time?
1 и 5 секунд, например.

2021-03-24 14:46 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +            self.optimiser_parameters.regularization_type = RegularizationTypesEnum.none
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8dR390).

2021-03-24 14:46 UTC, YanaPolonskaya commented on test/unit/chains/test_chain.py
> +    assert predicted_second is not None
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/215/files#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8dR390).

2021-03-24 14:46 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/param_free_gp_optimiser.py
>      def next_population_size(self, offspring: List[Any]) -> int:
Fixed.

2021-03-24 14:50 UTC, YanaPolonskaya commented
> ![изображение](https://user-images.githubusercontent.com/5711814/112070501-d627ba00-8b7e-11eb-81d3-53c57a6790fa.png)
> 
> Может в рамках борьбы с зависанием вот тут в цикле тоже учитывать а) число итерации б) лимит времени на композирование?

Добавила [проверку](https://github.com/nccr-itmo/FEDOT/pull/215/commits/8b7ad4a7b95c1082b75a7d3865abaea366d58670#diff-1a882e2388c5f8bb89d7a212f1e39fbf0babb2e18285d9ec5cdd70a2cb6dd9d6R303-R306) на всякий случай на кол-во сгенерированных индивидов.

2021-03-24 20:40 UTC, nicl-nno requested changes

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/chains/chain_template.py
> +            #                              model=fitted_model))
Вот тут забыл убрать.

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                set_start_method("spawn", force=True)
А нет смысла этот код перенести прямо в fit_with_time_limit? Или от этого производительность страдает?

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
Аналогично.

2021-03-24 20:40 UTC, nicl-nno commented on test/integration/real_applications/test_examples.py
> +@pytest.mark.skip('all chains fitness are not calculated')
Но вроде сейчас тест нормально проходит?

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/gp_operators.py
> +            individuals_set.remove(ind)
А вот в этом цикле же не учитывается max_lead_time? Если нет, но надо бы добавить проверку на каждой итерации.
Иначе сложно запускать бенчмарки, где есть фиксированное ограничение по времени..

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +            self.compl_position = get_metric_position(metrics, ComplexityMetricsEnum)
Может сделать функции get_main_metric и get_suppl_metric, которая будет принимать список metrics и возвращать нужное значение objectiv-а? Вроде position только для этого и используются ниже.

2021-03-24 20:40 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Лучше 10 вынести в константу в шапке начале всего скрипта. И для 10000 в создании популяции тоже можно так сделать.

2021-03-24 21:48 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                set_start_method("spawn", force=True)
Нет, просто насколько я понимаю это start method назначается всего 1 раз в начале выполнения скрипта, и нет смысла переназначать каждый раз заново.
Если убрать force вылазит ошибка что start_method уже был выбран
можно конечно поместить туда, чтобы не только в gp composer эта логика была, но наверное не совсем правильно каждый раз переназначать его заново.

2021-03-24 21:51 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                set_start_method("spawn", force=True)
Ну тогда хотя в какую-то отдельную, опциально вызываемую, функцию это стоит вынести, т.к. потенциально fit_with_time_limit можно использовать не только из композера.

2021-03-25 15:21 UTC, J3FALL requested changes

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
>              return [chain_first_copy, chain_second_copy]
Мб этой проверке дать говорящее название - функцию?

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Попробую объяснить логику этого фрагмента - поправьте, если я не прав:
- Применяем кроссовер для 2х цепочек до того момента, пока полученные потомки не стали "валидными" = соответствуют заданным ограничениям
- Если после number_of_attempts попыток не удалось такие найти - возвращаем исходные цепочки и пишем в лог об этом

Думаю, можно чуть упростить эту логику, заменив while + проверку в конце обычным циклом.
Причем, в нем после каждого кроссовера делать проверку на "валидность" и если она сработала - делать return.
А уже вне цикла просто возвращать исходные цепочки + писать в лог.
Думаю, будет выглядеть проще.

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
Ну здесь тоже можно логику упростить, как и в кроссовере.

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/selection.py
> +    return chosen
Наверное, лучше все-таки названия функций делать по PEP, т.е. spea2_selction.

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                 parameters: Optional[GPChainOptimiserParameters] = None, max_population_size: int = 55,
> max_population_size: int = 55
Я догадываюсь, что это одно из чисел Фибоначчи, но не всем это так очевидно)
Возможно, мелочь, но мб говорящую константу внести сюда?
И да, а если задать max_population_size > 55 и не число Фибоначчи - что-то может сломаться?

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +            return self.requirements.pop_size >= 7
Магическая константа 7 что может означать?)

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                std = np.std([ind.fitness for ind in self.population])
Так, а разве np.std не вернет 0 для массива с одним значением?
Возможно, проверка в начале не нужна.

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                       offspring_archive.items))
Тяжеловато смотрится.

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/optimisers/utils/population_utils.py
> +        fronts_coincidence = all(are_inds_found)
Тоже тяжеловато воспринимать этот фрагмент

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +        return all_objectives
К сожалению, эта функция выглядит совсем нечитаемой (

2021-03-25 15:21 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +                       folder: str = f'../../tmp/boxplots', y_limits: Tuple[float] = None):
Возможно, folder стоит связать с default_fedot_dir?
Ибо такие относительные пути могут у всех по-разному находиться.

2021-03-25 15:21 UTC, J3FALL commented on test/unit/chains/test_node_cache.py
>  def test_multi_chain_caching_with_shared_cache(data_setup):
Функцию тогда тоже надо переименовать.

2021-03-25 16:24 UTC, nicl-nno commented on cases/credit_scoring_problem.py
> +                               max_lead_time: datetime.timedelta = datetime.timedelta(minutes=150),
Да, это я тестил, надо откатить.

2021-03-25 16:25 UTC, nicl-nno commented on cases/credit_scoring_problem.py
> +        builder = builder.with_cache(cache_path)
У файла с кэшем будет уникальное GUID-based имя, и при след. запусках он не будет переиспользоваться.

2021-03-25 16:26 UTC, nicl-nno commented on fedot/api/main.py
> +                'preset': 'light_tun'
Ну да, сейчас можно или писать префикс, или с composer_params передавать 'with_tuning'.

2021-03-25 16:28 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        self.unfit()
по п. 2: А как бы ты назвал? Я исходил из логики, что есть fit, есть unfit.
clear_state/undo_fit/etc - вроде не сильно лучше.

2021-03-25 16:29 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +    def _fit_with_time_limit(self, input_data: InputData, use_cache=False, time: int = 900) -> Manager:
Да, думаю стоит везде перейти на минуты, чтобы не путаться.

2021-03-25 16:30 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +                                      self.computation_time is None
Когда модель уже "закэширована" - не нужно обновлять computation_time, т.к. оно стремится к 0.
Нужно это делать только в самый первый раз - когда модель ещё незафичена.

2021-03-25 16:33 UTC, nicl-nno commented on fedot/core/composer/cache.py
> +            self.db_path = db_path
Если ты не указал путь - то кэш падает в default_fedot_data_dir.
То что на скрине - это результат явно указания пути вот тут:

![image](https://user-images.githubusercontent.com/5711814/112508732-def7d600-8da0-11eb-8dbc-af70b70c2e1b.png)

Можно в скрипте с примером скоринга написать ./cache/credict_scoring_problem для красивости.

2021-03-25 16:34 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +        self.shared_cache = ModelsCache()
Это общий кэш для композера. Можно переименовать просто в self.cache разве что.

2021-03-25 16:36 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +        if self.composer_requirements.max_chain_fit_time:
Может отправить поле в базовый класс? У него нет GP-специфики.

2021-03-25 16:37 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                evaluated_metrics = evaluated_metrics + (metric_func(chain, reference_data=test_data),)
Так и раньше так было: композер обучает модели на train и проверяет на test. Сейчас только несколько критериев возвращаетсявместо одного.

2021-03-25 16:39 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_info = 'metric'
Ну так если одно значение (single-obj) - только оно и выводится, если много (multi-obj) - выводится список метрик.

2021-03-25 16:40 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            metrics = [metrics]
Мб лучше через Union разрешить оба варианта?

2021-03-25 16:43 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +from fedot.core.composer.optimisers.GPComp.gp_operators import \
Кстати наверно pep8-ней будет переименовать в gp_comp

2021-03-25 22:10 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +from fedot.core.composer.optimisers.GPComp.gp_operators import \
FIxed.

2021-03-25 22:11 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +                               max_lead_time: datetime.timedelta = datetime.timedelta(minutes=120),
Fixed.

2021-03-25 22:11 UTC, YanaPolonskaya commented on cases/credit_scoring_problem.py
> +                               max_lead_time: datetime.timedelta = datetime.timedelta(minutes=150),
Fixed.

2021-03-25 22:11 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Fixed.

2021-03-25 22:19 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/gp_operators.py
> +            individuals_set.remove(ind)
Добавила [контроль времени](https://github.com/nccr-itmo/FEDOT/pull/215/commits/231abae792e29c86a945bd3f109057edeb8033fe#diff-2a7c7d571d1b235872d40782354427e76c8884808a6923f7099510e60ed3fa2aR115-R125) в функции evaluate_individuals.
В для оценивания single models тоже есть [ограничение](https://github.com/nccr-itmo/FEDOT/pull/215/commits/231abae792e29c86a945bd3f109057edeb8033fe#diff-87cbdb4ae613e3e710ac963ddb8c04e88bf566b76f4609eaa666336cdf7b1a08R320-R323).
Для регуляризации тоже добавила внутри.

В случае если на оценивание single models в начале цикла эволюции затрачено все имеющееся время, в качестве решения возвращается просто лучшая из них. 
В таймере тоже [отделила](https://github.com/nccr-itmo/FEDOT/pull/215/commits/231abae792e29c86a945bd3f109057edeb8033fe#diff-b006009ccc452e1bcae70923bb78bdfd08c1b22c19d8c62f453cae4dd47ea5f1R53-R56) время затраченное на оценку single models и время затраченное на сам эволюционный процесс, чтобы возможность прохода еще одной итерации которая оценивается [тут](https://github.com/nccr-itmo/FEDOT/pull/215/commits/231abae792e29c86a945bd3f109057edeb8033fe#diff-b006009ccc452e1bcae70923bb78bdfd08c1b22c19d8c62f453cae4dd47ea5f1R56) рассчитывалась более достоверно.

2021-03-25 22:21 UTC, YanaPolonskaya commented on test/integration/real_applications/test_examples.py
> +@pytest.mark.skip('all chains fitness are not calculated')
Сейчас да, убрала skip.

2021-03-25 22:21 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
Fixed.

2021-03-25 22:21 UTC, YanaPolonskaya commented on fedot/core/chains/chain_template.py
> +            #                              model=fitted_model))
Fixed.

2021-03-25 22:22 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                set_start_method("spawn", force=True)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/231abae792e29c86a945bd3f109057edeb8033fe#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R34-R37).

2021-03-25 22:47 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +'''
Вот тут комментарий остался

2021-03-25 22:50 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/gp_operators.py
> +            individuals_set.remove(ind)
А нет смысла в конструктор CompositionTimer передавать max_lead_time? 
Кажется они вместе вместе используются. А так не надо будет max_lead_time везде передавать.

Логика с additional_proc_time какая-то оч. громоздкая. Может сделать отдельный метод таймера вроде set_init_time, куда передавать время, потраченное не на ЕА, а на ту или иную подготовку? Это сократит число параметров у is_time_limit_reached.

2021-03-26 11:31 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +    full_path_train, full_path_test = get_scoring_data()
Нужен pillow 7.1.1

2021-03-26 11:38 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +        self.fitted_on_data = dict()
Чтобы точно знать что dict будет, а не set. Со скобками по мне лучше когда ты внутри генерируешь сразу наполнение, но в гугле  говорят лучше {} использовать

2021-03-26 12:31 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +    full_path_train, full_path_test = get_scoring_data()
c 8.1.1 у меня тоже работает

2021-03-26 12:31 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        self.fitted_on_data = dict()
Вроде это всегда dict в такой нотации

![image](https://user-images.githubusercontent.com/5711814/112631732-4cab0d00-8e48-11eb-878c-f20c47a0209d.png)

2021-03-26 16:27 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
>              print(ex)
Надо бы ещё везде где print - заменить на соответсвующий вызов логера. И тут, и в композере, например:

![image](https://user-images.githubusercontent.com/5711814/112662892-437e6800-8e69-11eb-8ace-e1a9391ce2ea.png)

2021-03-28 21:03 UTC, YanaPolonskaya commented on fedot/core/chains/chain_template.py
> +        self.computation_time = chain.computation_time
Потому что все записывающиеся в историю цепочки переводятся в ChainTemplate, а comp time может пригодится уже после того как композер отработал н-р если мы использовали однокритериальный  алгоритм для какого-то анализа/построения графиков, ну и все таки это поле chain, почему бы эту информацию не сохранять?

2021-03-30 10:47 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/gp_operators.py
> +            individuals_set.remove(ind)
Добавила [max_lead_time](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-b006009ccc452e1bcae70923bb78bdfd08c1b22c19d8c62f453cae4dd47ea5f1R7) в конструктор таймера, [пример](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-87cbdb4ae613e3e710ac963ddb8c04e88bf566b76f4609eaa666336cdf7b1a08R133) использования из оптимайзера.

Добавила метод [set_init_time](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-b006009ccc452e1bcae70923bb78bdfd08c1b22c19d8c62f453cae4dd47ea5f1R75-R76) для того чтобы там фиксировать время затраченное на инициализацию включающую single_models evaluaton и др. операции в будущем.

2021-03-30 10:49 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +            self.compl_position = get_metric_position(metrics, ComplexityMetricsEnum)
Добавила [здесь](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-33c5ad7f353dbd901b426b49eb02159425db2aaa2a103d8eb722d92d96f1df0cR242-R250).

2021-03-30 10:50 UTC, YanaPolonskaya commented on cases/credit_scoring_problem_multiobj.py
> +            visualiser.visualise(chain_evo_composed)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-a5ad45ad3d4c61161434fbd8c4652d5cf632336900eeb7a080dc78ca2425dbc4R22-R28).

2021-03-30 10:50 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +        self.fitted_on_data = dict()
Fixed.

2021-03-30 10:53 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +
Переместила [метод](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-5091335cf95d4445c726021ca36f321a3568fdf0c1c7d6e778c90e2efa4d684bR36-R41) и вытащила из однострочника.

2021-03-30 10:58 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +        return data_type, features_hash, target_hash
[Переместила](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-5091335cf95d4445c726021ca36f321a3568fdf0c1c7d6e778c90e2efa4d684bR44). Может создать лучше отдельный файл chain_utils н-р чтобы туда подобные методы которые не напрямую связаны с chain складывать ?
Сейчас я переместила в gp_operators, но все же это думаю совсем туда не относится.

2021-03-30 10:58 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +            'target_hash'] = self.input_data_characteristics(data)
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR61-R64).

2021-03-30 10:59 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +                    'Parameter use_cache value changed to False')
Ты [это](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR74) имел ввиду ?

2021-03-30 11:00 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +                    or self.fitted_on_data['target_hash'] != new_target_hash:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR66-R78). Если правильно поняла.

2021-03-30 11:01 UTC, YanaPolonskaya commented on fedot/core/chains/chain.py
> +    def _fit_with_time_limit(self, input_data: InputData, use_cache=False, time: int = 900) -> Manager:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR80-R81).

2021-03-30 11:01 UTC, YanaPolonskaya commented on fedot/core/chains/node.py
> +    See the `preprocessors <https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/data/preprocessing.py>`__
Fixed.

2021-03-30 11:02 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +        self.shared_cache = ModelsCache()
Изменила на self.cache.

2021-03-30 11:03 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +        if self.composer_requirements.max_chain_fit_time:
[Fixeed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebR29). Теперь вроде ничего желтым не выделяяет.

2021-03-30 11:04 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +            metrics = [metrics]
Добавила [union](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebR54).

2021-03-30 11:05 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/gp_operators.py
> +    return list(filter(lambda x: not any([x.fitness == pop_ind.fitness for pop_ind in population]), archive.items))
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-2a7c7d571d1b235872d40782354427e76c8884808a6923f7099510e60ed3fa2aR147).

2021-03-30 11:07 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
>              return [chain_first_copy, chain_second_copy]
Добавила такую функцию для проверки в [кросовере](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-ec026612dbfdfb98f285a4ad907d699aa07d4053eb88452290524747eddcaa97R21-R22) и [мутации](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-817c9bfcb98debd82ead59e1080d790eeea13d0c61d80ace11a3c8c2aba2819bR39-R40).

2021-03-30 11:07 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
[Поправила](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-ec026612dbfdfb98f285a4ad907d699aa07d4053eb88452290524747eddcaa97R31-R49) таким образом.

2021-03-30 11:08 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-817c9bfcb98debd82ead59e1080d790eeea13d0c61d80ace11a3c8c2aba2819bR48-R62).

2021-03-30 11:09 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/selection.py
> +    return chosen
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-eaff45879d2338199ec10639bbe4da36c7b0e5b0758a035dca7f20486e6058d1R66-R71).

2021-03-30 11:20 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                 parameters: Optional[GPChainOptimiserParameters] = None, max_population_size: int = 55,
Но это ведь не обязательно число Фибоначчи, тут ведь может быть любое ограничивающее число, и оно передается в оптимайзер.
 Если задать "не число Фибоначчи" ничего не сломается, просто найдется ближайщее к нему число Фибоначии в последовательности. 
 Если задать число больше чем max_pop_size то тоже не сломается, просто у популяции будет на протяжении какого-то кол-ва вычислений возможность только уменьшаться, а если уменьшилась уже менее чем max_pop_size у нее появится  возможность увеличиваться - но теперь уже до заданного max_pop_size(ведь может алгоритм двигать и в одну и в другую сторону ее размер). Здесь уже больше несоответствие возникает между ограничением и заданным размеров, но сломаться ничего не должно. 
 Или лучше жестко ограничить размер популяции если в оптимайзере max_pop_size определенное задано (н-р если человек задал 100 у него все равно будет 55 размер сгенерированного потомства на 1 поколении) ?
 
55 занести под константу? но это наверное больше как значение по умолчанию, типо как у нас в GP composer requrements max_depth например.

2021-03-30 11:22 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +            return self.requirements.pop_size >= 7
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-87cbdb4ae613e3e710ac963ddb8c04e88bf566b76f4609eaa666336cdf7b1a08R24).

2021-03-30 11:23 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                std = np.std([ind.fitness for ind in self.population])
Ага. [Убрала](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-33c5ad7f353dbd901b426b49eb02159425db2aaa2a103d8eb722d92d96f1df0cR157) лишнюю проверку.

2021-03-30 11:25 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                       offspring_archive.items))
Эту функцию [отредактировала](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-33c5ad7f353dbd901b426b49eb02159425db2aaa2a103d8eb722d92d96f1df0cR187-R194) с учетом добавленных get_main_metric и get_suppl_metric.

2021-03-30 11:26 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/utils/population_utils.py
> +        fronts_coincidence = all(are_inds_found)
[Отредактировала](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-5091335cf95d4445c726021ca36f321a3568fdf0c1c7d6e778c90e2efa4d684bR15-R23).

2021-03-30 11:27 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
> +        return all_objectives
Поменяла название функции и [отредактировала](https://github.com/nccr-itmo/FEDOT/pull/215/commits/aa48d32d1e0dc544c53cbee4ce54403a723fb194#diff-7db9dda60b06a09eb58a8bf574485ff53a3f0678a531348070a4a64024540028R189-R206) код.

2021-03-30 11:46 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
> +                       folder: str = f'../../tmp/boxplots', y_limits: Tuple[float] = None):
Fixed.

2021-03-30 11:46 UTC, YanaPolonskaya commented on test/unit/chains/test_node_cache.py
>  def test_multi_chain_caching_with_shared_cache(data_setup):
Fixed.

2021-03-30 11:47 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +'''
Fixed.

2021-03-30 11:50 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
>              print(ex)
Глянула по коду, вроде print-ы остались только в примерах и визуализации. В визуализации специально лог не заводится или просто забыли?

2021-03-30 13:45 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
>              print(ex)
Да просто не проброшен туда, видимо. В целом можешь добавить его, раз все равно визуализацию меняешь.

2021-03-30 14:18 UTC, nicl-nno commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                 parameters: Optional[GPChainOptimiserParameters] = None, max_population_size: int = 55,
Мне тоже кажется лучше что лучше вынести 55 в шапки скрипта - для просто значения по умолчанию оно слишком конкретное.

>Или лучше жестко ограничить размер популяции если в оптимайзере max_pop_size определенное
Наверное если max_pop_size не None - лучше его учитывать.

2021-03-30 14:21 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        return data_type, features_hash, target_hash
Ну да, gp_operators вроде не особо подходит - это больше к data относится.
Я бы в data/data_utils.py положил, чтобы data.py не загромоджать. Мб у @J3FALL будут предложения по названию в контексте дискуссий про utils-ы.

2021-03-30 14:49 UTC, YanaPolonskaya commented on fedot/core/composer/visualisation.py
>              print(ex)
Добавила.

2021-03-30 14:50 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/param_free_gp_optimiser.py
> +                 parameters: Optional[GPChainOptimiserParameters] = None, max_population_size: int = 55,
Fixed.

2021-03-31 16:22 UTC, nicl-nno approved these changes

2021-04-01 14:00 UTC, J3FALL commented on cases/credit_scoring_problem_multiobj.py
> +    full_path_train, full_path_test = get_scoring_data()
угу, теперь норм.
my bad, не та версия была

2021-04-01 14:04 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        self.unfit()
в целом, да
подумал еще раз - unfit сойдет.

2021-04-01 14:08 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        return data_type, features_hash, target_hash
Ну, если не получается выделить какой-то скрипт, куда можно поместить > 1 метода, то есть альтернатива созданию utility-классов или скриптов - просто создайте новый скрипт, который частично дублирует суть вашего метода, который планируется туда поместить.
А уже в будущем если появляется возможность что-то обобщить, то и название более подходящее для этого можно подобрать.
Если интересно, могу попробовать мини-лекцию провести, почему utility-классы - это плохо.

2021-04-01 14:09 UTC, J3FALL commented on fedot/core/chains/chain.py
> +                    'Parameter use_cache value changed to False')
да, все так.

2021-04-01 14:10 UTC, J3FALL commented on fedot/core/chains/chain.py
> +                    or self.fitted_on_data['target_hash'] != new_target_hash:
в целом, да, это я имел в виду.

2021-04-01 14:16 UTC, J3FALL commented on fedot/core/chains/chain_template.py
> +        self.computation_time = chain.computation_time
Ну, шаблон по логике - это сущность довольно абстрактная сама по себе.
А время вычисления - вполне себе конкретная штука, которая варьируется еще не только от железа к железу, но и от запуска к запуску.
Основное использование шаблона - экспорт и импорт цепочек, чтобы обеспечить воспроизводимость, в т.ч. и на других фреймворках, если кто-то захочет его реализовать не через FEDOT.
И вот поле computation_time больше тянет на информацию в "логе" обучения цепочки, а не в шаблоне.
В моем представлении если хочется экспортировать инфу/логи о ходе оптимизации, лучше под это выделить отдельный объект, а шаблон оставить шаблоном.

2021-04-01 14:18 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_info = 'metric'
Но можно же просто тогда список из одного значения вывести?

2021-04-01 14:18 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_info = 'metric'
Если это сильно ломает код еще где-то - окей, оставляйте костыль

2021-04-01 14:22 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Можно же еще упросить, убрать эту проверку из цикла и делать ее в любом случае после цикла.
Если проверка сработала где-то в процессе - будет return.
А если цикл завершился, то значит проверка не прошла, и эта операция в любом случае сработает.
Или я ошибаюсь?
![image](https://user-images.githubusercontent.com/7864250/113308161-93987700-930e-11eb-8cde-6de7d3ad0106.png)

2021-04-01 14:22 UTC, J3FALL commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
Тот же коммент, что и выше.

2021-04-01 14:28 UTC, J3FALL approved these changes

2021-04-01 16:36 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Ну да проверка не прошла, но не пройти она еще для двух случаев:
- Если выбран пустой кроссовер CrossoverTypesEnum.none
- Если кроссовер просто не выполняется потому что вероятность не выпала
И в этих 2х других случаях это информационное сообщение с предупреждением неактуально

2021-04-01 16:54 UTC, YanaPolonskaya commented on fedot/core/chains/chain_template.py
> +        self.computation_time = chain.computation_time
[Fixed](https://github.com/nccr-itmo/FEDOT/pull/215/commits/c46ecee26a0ec935ab61913cf7729005a8da8df5#diff-c2581b323e0ca711f209735be927b074c66a0211fdca41d7542c7f94bbae498eR22-R23).

2021-04-01 16:55 UTC, YanaPolonskaya commented on fedot/core/composer/gp_composer/gp_composer.py
> +                log_info = 'metric'
[Упростила](https://github.com/nccr-itmo/FEDOT/pull/215/commits/c46ecee26a0ec935ab61913cf7729005a8da8df5#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R154).

2021-04-01 17:38 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/crossover.py
> +                if number_of_attempts == 10:
Недопоняла, теперь Fixed

2021-04-01 17:38 UTC, YanaPolonskaya commented on fedot/core/composer/optimisers/GPComp/operators/mutation.py
> +            if number_of_attempts == 10:
Fixed.

2021-04-01 20:22 UTC, merged