193-bug_convertion-to-template
nccr-itmo/FEDOT pull request #217
Opened 2020-12-22 10:35 UTC by MAGLeb

Closed #193

Устранил ошибку при работе с Node with model_type: "direct_data_model". Теперь не падает исключение.
При конвертации Chain -> ChainTemplate, количество нод и шаблонов моделей различалось, из-за модели с типом "direct_data_model". Так как я проверял равенство нод по свойству descriptive_id, а для моделей этого типа, свойство одинаковое.

2020-12-22 12:51 UTC, J3FALL approved these changes

2020-12-24 11:18 UTC, nicl-nno requested changes
1. Мне кажется, что тут ещё нужен тест который:

а) проверяет, что для цепочки с direct_data_model поведение корректное
б) В идеале проверяет что оно корректное для всех вариантов моделей. У нас же есть trend_data_model, residual_data_model - мне кажется, что для них тоже эта ошибка возникнет, но я не нашел теста, где это можно проверить.

2. Если ошибка действительно возникает не только для direct_ - то надо будет скорректировать названия методов.

3. Также есть предложение перенести test_chain_import_export.py в папку test

2021-01-04 11:17 UTC, MAGLeb commented
>     1. Мне кажется, что тут ещё нужен тест который:
> 
> 
> а) проверяет, что для цепочки с direct_data_model поведение корректное
> б) В идеале проверяет что оно корректное для всех вариантов моделей. У нас же есть trend_data_model, residual_data_model - мне кажется, что для них тоже эта ошибка возникнет, но я не нашел теста, где это можно проверить.
> 
>     1. Если ошибка действительно возникает не только для direct_ - то надо будет скорректировать названия методов.
> 
>     2. Также есть предложение перенести test_chain_import_export.py в папку test

Добавил тесты на проверку цепочек для типов моделей (trend_data_model, residual_data_model, direct_data_model, pca_data_model) и сделал небольшой рефакторинг ModelTemplate.

2021-01-11 13:20 UTC, nicl-nno requested changes

2021-01-11 13:20 UTC, nicl-nno commented on test/utilities/test_chain_import_export.py
> +        model_path = node['trained_model_path']
Мне кажется логичнее поменять местами проверку и присвоение - иначе проверка на первой итерации бесполезна, а в конце делается одна лишняя итерация.

Но мб стоит вообще заменить весь цикл и дальшейшую проверку на:


try
   model_path = next(node['trained_model_path'] for node in chain['nodes'] if node is not None)
except StopIteration:
   raise ValueError("Nothing to delete")

(https://stackoverflow.com/questions/18533620/getting-the-first-non-none-value-from-list/18533669)

2021-01-11 13:20 UTC, nicl-nno commented on test/utilities/test_chain_import_export.py
> +        raise ValueError("Nothing to delete")
Лучше одинарные кавычки.

2021-01-11 13:20 UTC, nicl-nno commented on test/utilities/test_chain_import_export.py
> +    chain.add_node(knn_root)
Здесь и ниже можно сразу chain = Chain(knn_root)

2021-01-11 15:24 UTC, MAGLeb commented on test/utilities/test_chain_import_export.py
> +        model_path = node['trained_model_path']
Понравилась конструкция с try, next, except. Исправил на неё.

В другой ветке сделал рефакторинг этого файла и эту функцию удалил.

2021-01-11 15:24 UTC, MAGLeb commented on test/utilities/test_chain_import_export.py
> +    chain.add_node(knn_root)
Исправил.

2021-01-11 15:24 UTC, MAGLeb commented on test/utilities/test_chain_import_export.py
> +        raise ValueError("Nothing to delete")
Принял.

2021-01-11 15:35 UTC, nicl-nno commented on test/utilities/test_chain_import_export.py
> +        model_path = next(node['trained_model_path'] for node in chain['nodes'] if model_path is not None)
Ну тут проверка неправильная, должно быть node is not None - поэтому тест падает.

2021-01-11 15:51 UTC, nicl-nno approved these changes

2021-01-12 09:19 UTC, merged