Bug with regression models for the multivariate targets fixed
nccr-itmo/FEDOT pull request #222
Opened 2020-12-27 15:14 UTC by nicl-nno

Current problem: when placing some models for time series forecasting in PrimaryNode, an error occurs in the model's fit stage (for forecast_length > 1).

List of models that fails: xgbreg, adareg, gbr, svr, sgdr
List of models that work correctly: linear, lasso, ridge, knnreg, dtreg, treg, rfr

The bug fixed by with involvement  of MultiOutputRegressor that wraps the models that can not produce multivariate prediction directly (see https://stackoverflow.com/questions/39540123/muti-output-regression-in-xgboost).

2020-12-27 15:15 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`test/chains/test_chain.py`](https://github.com/nccr-itmo/FEDOT/blob/dd845149d1718ad9f715bc6ef8e3f3a093f1bfc5/test/chains/test_chain.py):

> [Line 222:83](https://github.com/nccr-itmo/FEDOT/blob/dd845149d1718ad9f715bc6ef8e3f3a093f1bfc5/test/chains/test_chain.py#L222): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-01-12 11:21 UTC, BarabanovaIrina requested changes

2021-01-12 11:21 UTC, BarabanovaIrina commented on fedot/core/models/evaluation/evaluation.py
> +                sklearn_model.fit(train_data.features, train_data.target)
Может вынести в вспомогательную функцию с говорящим названием?

2021-01-12 11:21 UTC, BarabanovaIrina commented on test/tasks/test_forecasting.py
> +    rmse_threshold = np.std(test_data.target) * 1.3
магическое число

2021-01-12 11:21 UTC, BarabanovaIrina commented on fedot/core/chains/ts_chain.py
> +        # if forecast_length > 1:
Не совсем понятный комментарий, потому что по факту проверки не происходит, код выполнится в любом случае. Возникает вопрос, что будет, если forecast_length <1?(если логически это вообще возможно)

2021-01-12 11:23 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +    TaskTypesEnum.ts_forecasting: 0.5
А для clustering вообще не нужно разделять train и test в ходе подбора модели, поэтому его и нет.

2021-01-12 12:08 UTC, nicl-nno commented on fedot/core/data/preprocessing.py
> +    def __init__(self, with_imputation=True):
Сделал проще - [унаследовал](https://github.com/nccr-itmo/FEDOT/pull/222/files#diff-9186fa38f252fd01248620f72f94bcc5c668b6dae4a528aa779dacca6268039fR88-R100) Normalization и NormalizationWithImputation от соответсвующих Scaling и ScalingWithImputation , чтобы избежать дублирования. 

В идеале конечно они должно от единого класса наследоваться вообще (что-то вроде SklearnPreprocessingStrategy) или же иметь название scaler-а как гиперпараметр.

2021-01-12 12:08 UTC, nicl-nno commented on fedot/core/models/evaluation/evaluation.py
> +                sklearn_model.fit(train_data.features, train_data.target)
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/222/files#diff-9b69b7629ae678324e9459f501e8b8d1d478e427cade16c1f3403b285b92cc57R291-R302).

2021-01-12 12:08 UTC, nicl-nno commented on test/tasks/test_forecasting.py
> +    rmse_threshold = np.std(test_data.target) * 1.3
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/222/files#diff-468bb001a0e75e989084579f4e04ba5ac7e27a43ec5c2ce9260e48724b63fddcR21-R23) в функцию

2021-01-12 12:09 UTC, nicl-nno commented on fedot/core/chains/ts_chain.py
> +        # if forecast_length > 1:
Убрал вообще этот комментарий как устаревшей.

На минимальный forecast_length добавил [проверку](https://github.com/nccr-itmo/FEDOT/pull/222/files#diff-99771fd9ad61e2e454012b0e0904b1c22a8f6c90bb22b6649f7123f0c4dbb784R19-R21) и [тест](https://github.com/nccr-itmo/FEDOT/pull/222/files#diff-468bb001a0e75e989084579f4e04ba5ac7e27a43ec5c2ce9260e48724b63fddcR289-R292).

2021-01-13 16:22 UTC, BarabanovaIrina commented on fedot/core/data/preprocessing.py
> +    def __init__(self, with_imputation=True):
1. А поправь, пожалуйста еще вот [тут](https://github.com/nccr-itmo/FEDOT/blob/0006347a7d2575c1997a666fa6b1678ec2755db5/fedot/core/data/preprocessing.py#L172). Там должно быть ScalingWithImputation. И можно сразу добавить новые.

2. А так и задумано, что теперь нет preprocessing.normalize(), а вместо этого scaler = MinMaxScaler()? они одинаково работают? Просто если логика действий не нарушается, то ок, что такое наследование. А если да, то со стороны выглядит странно, что Normalizaiton наследуется от Scaling. (Хотя может я не сильно в понятиях шарю).

2021-01-13 16:56 UTC, nicl-nno commented on fedot/core/data/preprocessing.py
> +    def __init__(self, with_imputation=True):
1. [Добавил](https://github.com/nccr-itmo/FEDOT/pull/222/commits/c0fa0372637b90d5651ad21e7d96367e22096086#diff-9186fa38f252fd01248620f72f94bcc5c668b6dae4a528aa779dacca6268039fR168-R172).

2. Это @Dreamlone вроде менял - там проблема в том, что normalize на практике как-то оч криво работает, хоть его суть сводится как раз к MinMaxScaler.

Но в любом случае можно и scaler = preprocessing.normalize() при необходимости написать. С порядком наследования наверное нет особого смысла сейчас разбираться, все равно это вроде планировали рефактировать.

2021-01-13 16:58 UTC, BarabanovaIrina commented on fedot/core/data/preprocessing.py
> +    def __init__(self, with_imputation=True):
ок

2021-01-13 17:22 UTC, BarabanovaIrina approved these changes

2021-01-13 17:26 UTC, merged