README actualized
nccr-itmo/FEDOT pull request #235
Opened 2021-01-29 16:33 UTC by nicl-nno

The readme is actualized according to the https://actcognitive.org/platformy/freymvork-generativnogo-avtomaticheskogo-mashinnogo-obucheniya-fedot content: 

- text updated;
- obsolete links corrected
- several sections are moved
- new badges added

2021-01-30 11:51 UTC, J3FALL requested changes

2021-01-30 11:51 UTC, J3FALL commented on README.rst
> +
Прогони, плз, весь текст через grammarly, есть пара ошибок/опечаток.
![image](https://user-images.githubusercontent.com/7864250/106355577-f3bc6e00-6309-11eb-869a-5f7ae7942167.png)

2021-01-30 11:51 UTC, J3FALL commented on README.rst
> +
В других фрагментах тоже где-то не хватает артиклей, имхо.

2021-01-30 11:51 UTC, J3FALL commented on README.rst
> +How to use (advanced approach)
Я бы не назвал это именно advanced - это больше похоже на extended version

2021-01-30 11:52 UTC, nicl-nno commented on README.rst
> +
Хм, вроде прогонял граммарли. Ок, пройдусь ещё раз.

2021-01-30 11:54 UTC, nicl-nno commented on README.rst
> +How to use (advanced approach)
Ну тут я имел в виду "Вариант для продвинутных пользователей". Вроде есть термин advanced mode.

2021-01-30 12:05 UTC, J3FALL commented on README.rst
> +How to use (advanced approach)
Окей, это не принципиально особо.

2021-02-04 21:51 UTC, nicl-nno commented on README.rst
> +
Текст вычитан вручную, вроде стало получше.

2021-02-05 07:41 UTC, J3FALL approved these changes

2021-02-05 08:51 UTC, merged