Preprocessing refactor
nccr-itmo/FEDOT pull request #237
Opened 2021-02-17 08:31 UTC by Dreamlone

Changed the core architecture. Preprocessing operations now can be placed in separate nodes. The following architecture is supported: Operations (Models and DataOperations).

Added methods for preprocessing tabular data. Added specific preprocessing methods for time series. 

The files to run (for check new functionality) will be added to examples and cases.  For now, [cases/operations_regression_case_manual.py](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/cases/operations_regression_case_manual.py) file can be considered as appropriate example of new functionality.

2021-02-17 08:31 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cases/operations_regression_case_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py):

> [Line 11:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 15:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L15): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 16:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L16): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 18:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L18): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 19:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L19): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 20:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L20): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 21:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L21): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 22:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L22): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 24:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L24): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 26:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L26): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 30:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L30): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 31:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L31): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 33:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L33): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 35:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L35): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 36:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L36): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 37:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L37): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 38:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L38): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 39:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L39): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 40:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L40): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 115:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L115): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 130:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_composer.py#L130): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`cases/operations_regression_case_manual.py`](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_manual.py):

> [Line 80:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_manual.py#L80): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`cases/operations_regression_case_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_tuning.py):

> [Line 87:15](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_tuning.py#L87): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator
> [Line 117:1](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/cases/operations_regression_case_tuning.py#L117): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file



* In the file [`examples/preprocessing_classification_example.py`](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py):

> [Line 47:44](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py#L47): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 47:48](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py#L47): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 69:33](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py#L69): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 69:48](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py#L69): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 69:62](https://github.com/nccr-itmo/FEDOT/blob/4b3565c735bb76012707a7c6d214c4a59554a570/examples/preprocessing_classification_example.py#L69): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace [...]

2021-03-02 16:56 UTC, J3FALL requested changes

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/chains/chain_template.py
>  from fedot.core.chains.node import CachedState, Node, PrimaryNode, SecondaryNode
Хм, кстати, а ты пробовал уже экспортировать цепочки с новой логикой?
Кажется, там надо будет какое-то доп. поле добавлять, которое указывает тип узла - модель или операция.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/chains/chain_validation.py
> +    return True
Хм, погоди, а точно нужно подключать ModelTypesRepository и проверять на соответствие каждой из всех моделей?
Можно же просто проверить: `if type(model) is Model` и все?
Или я тут ошибаюсь?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/chains/chain_validation.py
> +    root_node = chain.root_node
Здесь, получается, тоже достаточно проверить тип последней ноды?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/composer/composer.py
> +    add_single_operation_chains: bool = True
Мб тогда просто переименуем поле в allow_single_operations = True ?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +            data_operations, _ = DataOperationTypesRepository().suitable_operation(task_type=self.task.task_type)
Текущая версия уже не крашится при дефолтных настройках?
Интересно, все ли допустимые наборы models + data_operations работают корректно друг с другом.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +            data_operations, _ = DataOperationTypesRepository().suitable_operation(task_type=self.task.task_type)
Бтв, кажется, на эту функцию нет тестов у нас.
Самое время их добавить.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    self._best_single_operations(objective_function)
Здесь, получается, по аналогии можно переименовать параметры.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/data/data.py
> +    target: Optional[np.array] = None
Это у нас, получается, глобальный таргет, или как?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/data/data.py
> +def merge_non_equal_outputs(outputs: List[OutputData], idx_list: List):
Вообще, очень не помешали бы тесты на эти функции, связанные с мержом нескольких потоков данных.
Так будет более понятно, какая там логика реализована + это неплохая точка входа для "починки" тестов у нас )

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/strategy.py
> +class StrategyOperator:
Как то не очень понял по контексту кода - в чем его предназначение?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        output_types = self.metadata.output_types
да, но как будто поля self.metadata нет в конструкторе, либо еще где-то.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/operation.py
> +class Model(Operation):
Можешь растащить Model и DataOperation на отдельные скрипты?
Кажется, там есть дублирование, которое можно устранить, но пока немного трудно понимать код.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/operation.py
> +    strategy = operations_repo.operation_info_by_id(operation_type).current_strategy(task_type_for_operation)
А вот тут что происходит?
Довольно сложная конструкция, возможный кандидат на рефакторинг.
Но сначала хочу понять логику этого куска кода.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
забавная пасхалка ))
представь ситуацию: я был плотно погружен в код, вникал в суть, навигировался по коду.
потом кликнул на эту функцию, а тут - "PRIVET KAK DELA?" ))

а если по делу, то кажется, что эта была когда-то проблема из-за forecasting-а рядов с пропущенными значениями, из-за которых ломались индексы Input и Output данных.
Но могу ошибаться.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
Призываю Колю @nicl-nno на помощь.
Не помнишь, из-за чего возникла такая проблема?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/strategy.py
> +class StrategyOperator:
UPD: Надо было глянуть лучше код Node.
Видимо, идея была в том, чтобы выделить специальный класс, который создает Model или DataOperation в зависимости от переданного operation_type?
Если так, то, видимо, название не очень удачное, т.к. тут и Strategy и Operator.
Мб OperationFactory назвать, или как-то иначе?

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/operations/strategy.py
> +class StrategyOperator:
ну и тестики на него, очевидно, не помешали бы.

2021-03-02 16:56 UTC, J3FALL commented on fedot/core/repository/operation_types_repository.py
> +        return operations_list
Слушай, а тут и до твоих правок было так сложно?)
Функция выглядит тяжеловато, надо бы хоть на пару функций разбить.

2021-03-02 16:56 UTC, J3FALL commented on fedot/utilities/synthetic/chain_template.py
Думаю, chain_template - это тоже ближайший кандидат на "починку" и проверку тестов.

2021-03-02 16:56 UTC, J3FALL commented on fedot/utilities/synthetic/chain_template.py
А, стоп, это synthetic.
Я в любом случае планировал выпилить эти классы, ибо устарели.

2021-03-02 17:45 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
Некоторый модели-классификаторы могут иногда выдавать NaN вместо вероятностей, если они не сходятся. LDA/QDA, например.

2021-03-02 17:46 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +    strategy = operations_repo.operation_info_by_id(operation_type).current_strategy(task_type_for_operation)
Это было сделано, что можно было в пайплайны включать "совместимые" модели для других задач. Например, модель кластеризации в пайплайн классификации.

2021-03-03 09:10 UTC, J3FALL commented
Не нашел других вариантов, где об этом написать, но
В chains/chain нарушается полиморфизм:
![image](https://user-images.githubusercontent.com/7864250/109781585-1ac3d380-7c19-11eb-91cf-2b2db32da55b.png)

Вероятно, в Data нужно добавить абстрактный метод is_appropriate_for_task
И в подтипах его реализовать по аналогии с тем, что в этой функции происходит.

2021-03-03 10:08 UTC, J3FALL commented
В evaluation.py в конструкторе что-то странное:
![image](https://user-images.githubusercontent.com/7864250/109788988-ec49f680-7c20-11eb-87fa-e675a68269e9.png)

Видимо, идея была в объявлении переменной класса у аннотацией, какой тип у него должен быть - None или SkLearnTuner.
Но фактически, здесь ссылка _tune_strategy присваивается Класс/объект типа Optional.

2021-03-03 10:10 UTC, nicl-nno commented
> В evaluation.py в конструкторе что-то странное:
> ![image](https://user-images.githubusercontent.com/7864250/109788988-ec49f680-7c20-11eb-87fa-e675a68269e9.png)
> 
> Видимо, идея была в объявлении переменной класса у аннотацией, какой тип у него должен быть - None или SkLearnTuner.
> Но фактически, здесь ссылка _tune_strategy присваивается Класс/объект типа Optional.

Да, тут явно д.б двоеточие вместо =

2021-03-03 10:41 UTC, J3FALL requested changes

2021-03-03 10:41 UTC, J3FALL commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
Мб в виде костыля на слое SkLearnEvaluationStrategy тогда эту проверку сделать?
Ну и в лог об этом сообщить.
Вообще кстати, LDA/QDA сейчас актуальны? Их кто-то активно юзает?

2021-03-03 10:41 UTC, J3FALL commented on fedot/core/operations/evaluation/keras_eval.py
>  import tensorflow as tf
KerasForecastingStrategy - надо проверить, но кажется, там интерфейс не соответствует EvaluationStrategy.

2021-03-03 10:41 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/sklearn_transformations.py
> +        global DEFAULT_MIN_EXPLAINED_VARIANCE
😰😰😰
А зачем здесь global?

2021-03-03 10:41 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/sklearn_transformations.py
> +         /operations/evaluation/data_evaluation.py
Напиши тест для себя, где ты сравнишь DataModellingStrategy из data_evaluation.py с соответствующими методами из этого скрипта.
На одних и тех же данных.
Если работают идентично (а судя по коду - все должно одинаково работать), то надо выпиливать DataModellingStrategy.

2021-03-03 10:41 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/abs_interfaces.py
> +class ModelRealisation(ABC):
Тут я не очень понимаю:
- В SkLearnEvaluationStrategy есть словарь `__operations_by_types`, в котором FEDOT-alias-ы моделей присваиваются конкретным реализациям = конкретным классам из sklearn
- При этом в TsForecastingStrategy эта логика нарушается, там `__operations_by_types ` для arima передается объект ARIMAModel, который в свою очередь является реализацией класса ModelRealisation

Почему нужно вводить такую отдельную абстракцию ModelRealisation и DataRealisation?
Нет ли там дублирования в них, ибо они являются terminated-классами и у них нет общего предка?
Тогда, может, нужен OperationImplementation / OperationExecutor как базовый класс?

Если такая большая потребность возникла в обобщении некоторых методов в Model/DataRealisation, тогда для соответствия архитектуры sklearn-модели нужно оборачивать в них?

2021-03-05 11:36 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +from fedot.utilities.synthetic.data import regression_dataset
Исправил, кейсы и examples отрефакторил и привел в запускаемый вид. Представлены 5ю файлами: 
* папка cases: 1) operations_regression_case_composer - пример решения задачи регрессии (предсказание уровня воды) с композером и последующей, если потребуется, оптимизацией гиперпараметров, 2) operations_regression_case_manual - тот же самый пример, но без композера, можно вручную позадавать разные цепочки.
* папка examples: 1) operations_classification_example - пример применения вручную заданной цепочки для задачи классификации + тюнер, 2) operations_regression_example - пример применения вручную заданной цепочки для задачи классификации + тюнер, 3) operations_ts_forecasting - пример решения задачи прогноза временного ряда, цепочка задается вручную + тюнер.

Коммент убрал, импорты отформатировал по тем предложениям, которые мне PyCharm предлагал делать, так что должно стать получше. См., если что, [сюда](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0b469e02b7a1610303960ead520fe2aac37450c2c38897f014be101e57f5272a).

2021-03-05 11:39 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +    node_rans = SecondaryNode('rfe_lin_reg', nodes_from=[node_encoder])
Осталось артефактом, потому что раньше в узле был алгоритм RANSAC. Исправил, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ce). Цепочка выглядит теперь [следующим образом](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ceR101-R107).

2021-03-05 11:41 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +    run_experiment('../cases/data/river_levels/station_levels.csv', chain)
Да, там проблемы были с параметрами у RFE операции. Скрипт подправил. Файл с [кейсом](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ce) должен нормально запускаться.

2021-03-05 11:43 UTC, Dreamlone commented on cases/operations_regression_case_manual_with_tuner.py
> +np.random.seed(10)
Совместил файл примеров с тюнером и без него в один. См. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ce).

2021-03-05 11:45 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +        np.array(df['level_station_2']),
Прости, немного не понял :)
Имеешь в виду сделать что-то такое:

```
features = np.array(df[['level_station_1', 'month', 'mean_temp', 'precip']])
target = np.array(df['level_station_2'])
```

И потом уже их использовать, так?

2021-03-05 11:46 UTC, Dreamlone commented on cases/operations_regression_case_manual_with_tuner.py
> +
Во всех кейсах убрал лишние отступы. См. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ce) например, или [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0b469e02b7a1610303960ead520fe2aac37450c2c38897f014be101e57f5272a).

2021-03-05 11:48 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +from fedot.core.repository.tasks import Task, TaskTypesEnum
Сделал, ссылки в сообщении выше. Но мне кажется, что перед мержом стоит сократить количество таких кейсов и примеров до 2х: 1 в cases, 1 в examples. Импорты поправил.

2021-03-05 11:51 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +        print(f'Iteration {i}')
Да, все верно, так как процесс эволюции - стохастический моментами, решил, что надо усреднять. 

P.S. - Имеет смысл посмотреть даже как вручную заданная цепочка себя ведет, видно, что всегда есть +- отклонения от запуска к запуску. Использовать можно вот этот [файл](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-0f43315c145da623677e99e2e147b12ddeed9484ac1c398ff249adf0086683ce), нужно поставить только "tuner=None"

2021-03-05 11:52 UTC, Dreamlone commented on examples/preprocessing_classification_example.py
> +from fedot.utilities.synthetic.data import classification_dataset
Согласен, обновил [файл с примером](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-bb906af2a2fadcaf99f52157d101d0a46a3123b7362a40f5f7374422fea685e2).

2021-03-05 11:54 UTC, Dreamlone commented on examples/refactor_preprocessing_ts_forecasting.py
> +    #time_series = generate_synthetic_data()
Нет, тут проблема была при оптимизации K-nn, там в гипарпаметрах загадочным образом затесалось [True, False] вместо [1, 2]) Все [исправлено](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-1adbba1b9e24043843da507ef8c1470e0cce42f3517e7388eb1131d509fd950cR65-R66).

2021-03-09 13:40 UTC, J3FALL commented on cases/operations_regression_case_manual.py
> +        np.array(df['level_station_2']),
Да, именно так.

2021-03-09 13:41 UTC, J3FALL commented on cases/operations_regression_case_composer.py
> +from fedot.core.repository.tasks import Task, TaskTypesEnum
Угу, это довольно логично - сравнение manual vs composer edition

2021-03-09 13:42 UTC, J3FALL commented on cases/operations_regression_case_composer.py
> +        print(f'Iteration {i}')
Выглядит, что эти операции тоже можно выполнять вне цикла один раз:
![image](https://user-images.githubusercontent.com/7864250/110479444-70efb580-80f6-11eb-968a-0e994210a4ad.png)

2021-03-09 13:45 UTC, J3FALL commented on examples/refactor_preprocessing_ts_forecasting.py
> +    #time_series = generate_synthetic_data()
Новая версия ругается из-за косячных импортов:
![image](https://user-images.githubusercontent.com/7864250/110479761-ccba3e80-80f6-11eb-8c91-bcd27c4f73b8.png)

Вроде я последние изменения подтянул.

2021-03-09 13:58 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
>Вообще кстати, LDA/QDA сейчас актуальны? Их кто-то активно юзает?

Вроде не особо часто выходят в том, но в любом случае обрабатывать такое поведение sklearn-а стоит.

>Мб в виде костыля на слое SkLearnEvaluationStrategy тогда эту проверку сделать?

Можно и так, если это упрощает дело.

2021-03-09 14:29 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +        np.array(df['level_station_2']),
Все сделано, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-0b469e02b7a1610303960ead520fe2aac37450c2c38897f014be101e57f5272aR77-R80).

2021-03-09 14:31 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +        print(f'Iteration {i}')
Вынес этот кусок повыше, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-0b469e02b7a1610303960ead520fe2aac37450c2c38897f014be101e57f5272aR86-R109).

2021-03-09 14:32 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +        composer = builder.build()
Согласен, вынес из цикла, плюс разбил их на несколько функций, см. [файл](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-0b469e02b7a1610303960ead520fe2aac37450c2c38897f014be101e57f5272a).

2021-03-09 14:40 UTC, Dreamlone commented on examples/refactor_preprocessing_ts_forecasting.py
> +    #time_series = generate_synthetic_data()
Мой косяк - [исправил](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-2047080980cd8c1963263984021a87c39167c01c5b9012ec8d7e421a77673ebf). Теперь должно все нормально запускаться, поставил небольшое количество итераций у тюнера, так что если хочется поэкспериментировать, то лучше побольше выбрать (хотя бы 20).

Также добавил [пример](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-e0fafc78bc8e7358d3cb90c9bf33dd03ae1072c1c31699fdc36246cac9dcfb1b) с экзогенным временным рядом. Как можно заметить, качество прогноза (по сравнению с моим примером с экзогенным рядом из туториала, который делал в декабре) возросло. Как и договаривались раньше, реализовал функционал подключения разных источников данных к primary узлам напрямую, если это необходимо, для этого дела.

FYI, обнаружил, что в readme у FEDOT'а ссылка ну туториал с readme недействительна, поменялось название ipnb файла, для сравнения, вот [он](https://github.com/nccr-itmo/FEDOT/blob/master/notebooks/time_series_forecasting_with_fedot.ipynb).

2021-03-09 14:46 UTC, Dreamlone commented on examples/refactor_preprocessing_ts_forecasting.py
> +
Решил избавиться от такой дихотомии, оставил просто "run_experiment". Подчистил код, теперь выглядит более приглядно (я надеюсь), см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-2047080980cd8c1963263984021a87c39167c01c5b9012ec8d7e421a77673ebf).

2021-03-09 14:48 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +    return True
Абсолютно верно :) Спасибо, [исправил](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-218db4373eb9ac8418056e00df5a0c079969ec0abb02a94d8a40a50865d60c5fR102-R104).

2021-03-09 14:50 UTC, Dreamlone commented on fedot/core/composer/composer.py
> +    add_single_operation_chains: bool = True
Согласен, изменил [название](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebR21-R32).

2021-03-09 15:02 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +    return True
Кстати, замени логику, теперь функционал ModelTypesRepository, ровно как и моего "нововведения", выполняет OperationTypesRepository, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/4963749028e3d8e9348721748014f3c47ec4a995#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0).

2021-03-09 15:05 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_optimiser.py
> +                    self._best_single_operations(objective_function)
Ага, всё [сделано](https://github.com/nccr-itmo/FEDOT/pull/237/commits/8de76407161a22eba6a524f3ad5a50a0a75c69aa#diff-e9091ad680475e338d53ff0e6e47645a3f1b77e9c367b18de21835946b0222abL177-R182).

2021-03-09 15:19 UTC, Dreamlone commented on fedot/core/data/data.py
> +    target: Optional[np.array] = None
Да, всё верно. Я ввел это, потому что при некоторых операциях могут меняться не только признаки (которые потом переходят в поле predict), а еще и сам глобальный target. Особенно это актуально для работы с временными рядами, но, потенциально, это может пригодиться в будущем и для других задач (например, при аугментации данных (когда добавляешь новые объекты новым признакам нужно ведь предоставить соответствующий target) и т.д.).

2021-03-09 21:34 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +    root_node = chain.root_node
Да, все верно, чего-то меня повело на неоптимальное решение, - [исправился](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b327b07aa8b1ba82daf8874ae8ef34e6223149da#diff-218db4373eb9ac8418056e00df5a0c079969ec0abb02a94d8a40a50865d60c5fL116-R119).

2021-03-10 14:11 UTC, J3FALL commented on fedot/core/chains/chain_validation.py
> +    return True
Проверь скрипт, там есть теперь неиспользуемые импорты.
И, кажется, можно еще упростить при помощи оператора any:
![image](https://user-images.githubusercontent.com/7864250/110641842-7ff06980-81c3-11eb-83f7-495ef33b2740.png)

2021-03-15 19:55 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +    node_encoder = PrimaryNode('one_hot_encoding')
Немного изменил код и вынес в [fedot/api/help.py](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-4989cae938907bb17252b54ff46d3d00944a392de3474039222802eebdab03ec). Сделал две функции: print_models_info и print_data_operations_info. В самом скрипте пока что оставил пример с запуском. Если предложенное размещение этих функций устроит, то уберу часть кода с вызовом и напишу тесты на эти функции.

2021-03-15 19:58 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +    return True
Решил вообще избавиться от этой функции, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-218db4373eb9ac8418056e00df5a0c079969ec0abb02a94d8a40a50865d60c5f). Решил, что такая проверка будет лишней, ведь есть has_final_operation_as_model. которая как раз проверяет, является ли root узел, узлом с моделью. Тут логика такая - раз в цепочке последний узел с моделью, то в цепочке есть модель, а если в root узле - data operation, то такая цепочка и так невалидна.

2021-03-15 20:01 UTC, Dreamlone commented on fedot/core/operations/strategy.py
> +class StrategyOperator:
Да, идея как раз была именно в этом, изменил название на [OperationFactory](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-035cc844345d24f1c48c89fa825935700cfffadb45843e106dc360eb70a8ac64R6-R7). Тесты на него пока не готовы -> напишу.

2021-03-15 20:24 UTC, Dreamlone commented on fedot/core/operations/operation.py
> +        output_types = self.metadata.output_types
Да, с этим полем изначально какая-то путаница вышла, сейчас свежим взглядом на все посмотрел, оно нигде и не используется теперь (раньше нужно было в методе output_datatype в классе Model, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932R176-R177), а сам этот метод нигде не использовался). 

История тут такая, переменная output_datatype нужна была для метода output_datatype в классе Model (см. как это выглядит в [мастере](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/models/model.py)), потому что метод вызывался в Node при формировании OutputData после предсказания модели (см. как это выглядит в [мастере](https://github.com/nccr-itmo/FEDOT/blob/e132c89c68590a37a6aff2b63a9f7ddf2606e9e0/fedot/core/chains/node.py#L76)). Теперь же OutputData  формируется на уровне реализаций операций, или на уровне EvaluationStrategy, так что необходимости в этом всем нет. - Убрал.

2021-03-15 20:26 UTC, Dreamlone commented on fedot/core/operations/operation.py
> +class Model(Operation):
На счет дублирования согласен, буду рефакторить дальше. Пока разделил на 2 скрипта [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-c573c713bb9e37ab2f427abf5bc72a9884bb4416bf06432cf4e9f36852ff30d2) и [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-564fbcafec5e02ae3cb446874f622d700cdb5e1f9958455e69d8c520ed4b5990).

2021-03-15 20:28 UTC, Dreamlone commented on fedot/core/operations/operation.py
> +    # дублирует Imputation стратегию -> надо разобраться
Подумал, что обработку таких случаев можно вынести на уровень реализации операций, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-111d019611816f220f2040ca67dacd14ea179dea2a2612006b4538936ed12710).

2021-03-15 20:41 UTC, Dreamlone commented
> Не нашел других вариантов, где об этом написать, но
> В chains/chain нарушается полиморфизм:
> ![image](https://user-images.githubusercontent.com/7864250/109781585-1ac3d380-7c19-11eb-91cf-2b2db32da55b.png)
> 
> Вероятно, в Data нужно добавить абстрактный метод is_appropriate_for_task
> И в подтипах его реализовать по аналогии с тем, что в этой функции происходит.

На самом деле в этой функции теперь нет необходимости, убрал её, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/e029dcd9c7fab266c2597297c86f02f99e5d48f3).

Эта штука теперь относится скорее к проверке корректности заданных гиперпараметров в узлах (помню, мы с Пашей об этом говорили). Так как размер скользящего окна теперь как раз гиперпараметр у lagged преобразования. 
Пока думаю как лучше реализовать эту проверку, можно конечно прописывать исключения на уровне реализаций операций, которые. [тут](https://github.com/nccr-itmo/FEDOT/tree/preprocessing-refactor/fedot/core/operations/evaluation/operation_realisations)?

2021-03-15 20:49 UTC, Dreamlone commented
> > В evaluation.py в конструкторе что-то странное:
> > ![image](https://user-images.githubusercontent.com/7864250/109788988-ec49f680-7c20-11eb-87fa-e675a68269e9.png)
> > Видимо, идея была в объявлении переменной класса у аннотацией, какой тип у него должен быть - None или SkLearnTuner.
> > Но фактически, здесь ссылка _tune_strategy присваивается Класс/объект типа Optional.
> 
> Да, тут явно д.б двоеточие вместо =

Ну двоеточие тут не проходит, PyCharm подсвечивает как некорректный синтаксис. Я посмотрел через git blame, это вроде Ира писала, ну я, так сказать, её реализации верю, что это корректная запись. Призываю @BarabanovaIrina помочь разобраться как лучше будет исправить) - Я бы, честно сказать, просто сделал как "self._tune_strategy = SklearnTuner"...

2021-03-16 07:04 UTC, Dreamlone commented on fedot/core/chains/node.py
> +            self.cache.append(CachedState(operation=cached_operation))
Исправил, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-2739bda85c4dab8cb5fb7dbda40088c8617212b3542690798f101f140f09df00L80-R77)

2021-03-16 07:45 UTC, Dreamlone commented on fedot/core/chains/node.py
> +                                                       is_fit_chain_stage=True)
Тут идея в том, что это поле нужно для решения задачи классификации. И передавать его начинает chain в методе predict, затем оно идет в node/predict, оттуда - в Model или в DataOperation. То есть в методе fit оно не используется. Тот кусок кода, комментарий к которому как раз приведен, является частью метода fit - в него не передается output_mode от chain.

Но, и fit, и predict в node вызывают Model / DataOperation predict. которому это поле нужно. Дело в том, что оно по умолчанию уже задано (output_mode: str = 'default', см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/380eb50593f4c1e61e1eaa2f1061f73eb6ae0efd#diff-c573c713bb9e37ab2f427abf5bc72a9884bb4416bf06432cf4e9f36852ff30d2R70-R88)), поэтому, когда мы в fit'е ничего не передаем, то мы устанавливаем дефолтное значение. Тут возможно предложить просто прописывать в этом месте output_mode='default', а значение по умолчанию убрать. но тогда придется передавать output_mode и в метод fit, в котором он не используется.

2021-03-16 08:04 UTC, Dreamlone commented on fedot/core/chains/node.py
> +        return self.operation.metadata.tags
Убрал этот метод, так как он нигде не использовался. Посмотрел как в мастере сейчас с этим дело обстоит, там тоже это свойство не используется нигде, см. [здесь](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/chains/node.py#L68).

2021-03-16 08:06 UTC, Dreamlone commented on fedot/core/data/data.py
> +    idx_list = list()
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR198-R201).

2021-03-16 08:35 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_realisations/sklearn_transformations.py
> +        global DEFAULT_MIN_EXPLAINED_VARIANCE
Переработал PCA, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-6e18010bde6e5db9afb602ca1222259820dff5ce6719e04196cd84bd833df4ee). Теперь там нет никаких глобальных переменных + количество отобранных главных компонент не определяется автоматически, а вынесено в гиперпарметры преобразования. Также добавил [ядерный PCA](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-6e18010bde6e5db9afb602ca1222259820dff5ce6719e04196cd84bd833df4eeR92-R100).

2021-03-16 08:36 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_realisations/sklearn_transformations.py
> +         /operations/evaluation/data_evaluation.py
Сделал, [PCA](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b51487cbef9b42e05652c0d05dcc4d3697159b81#diff-6e18010bde6e5db9afb602ca1222259820dff5ce6719e04196cd84bd833df4ee) готов.

2021-03-16 09:55 UTC, BarabanovaIrina commented
> > > В evaluation.py в конструкторе что-то странное:
> > > ![image](https://user-images.githubusercontent.com/7864250/109788988-ec49f680-7c20-11eb-87fa-e675a68269e9.png)
> > > Видимо, идея была в объявлении переменной класса у аннотацией, какой тип у него должен быть - None или SkLearnTuner.
> > > Но фактически, здесь ссылка _tune_strategy присваивается Класс/объект типа Optional.
> > 
> > 
> > Да, тут явно д.б двоеточие вместо =
> 
> Ну двоеточие тут не проходит, PyCharm подсвечивает как некорректный синтаксис. Я посмотрел через git blame, это вроде Ира писала, ну я, так сказать, её реализации верю, что это корректная запись. Призываю @BarabanovaIrina помочь разобраться как лучше будет исправить) - Я бы, честно сказать, просто сделал как "self._tune_strategy = SklearnTuner"...

Интерестинг, потому что у меня PyCharm не подсвечивает. Но синтаксис, действительно неверный, и как я такое написала, уже сложно сказать) я имела ввиду вот такое: self._tune_strategy: Type[Tuner] = SklearnCustomRandomTuner. Не знаю, насколько верно будет указывать просто SklearnTuner как дефолтное значение, если у него нет реализации [tune](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/models/tuning/tuners.py#L112-L113), потому как он просто объединяет под собой разные стратегии, импортированные из sklearn.

Но я помню, что идея SklearnCustomRandomTuner была в том, что он предполагался как RandomTuner для разных моделей, не только из sklearn (потому как в Random, Grid и Bayes внутри идет проверка на то, что модель действительно из sklearn, а с потенциально другими тюнинг не сработал бы). Название он видимо приобрел, потому что эксперименты проводились все равно только на sklearn моделях, да и к тому же именно этот тюнинг (по каким-то причинам) выдавал более лучшие результаты. 

Наверняка возникает мысль, что в SkLearnEvaluationStrategy все таки должен быть self._tune_strategy: Type[SklearnTuner] (а не просто Tuner), но это ограничивает, поэтому все таки Tuner. Если я где-то неправа с точки зрения реализации, поправьте меня. 

Кроме того, там все еще открытая проблема, как указать тип тюнинга (Random, Bayes, TPE и т.д.), потому что извне в рамках данной реализации это сделать невозможно, для проведения экспериментов я просто меняла название класса руками. Но возможно эта проблема уже как-то решена в рамках данного PR.

2021-03-16 10:05 UTC, BarabanovaIrina commented
Также отмечу, что идея создания класса [Tune](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/chains/chain_tune.py), в которую мы передаем цепочку, была не в том, чтобы изменить способ тюнинга, а в том чтобы добавить гибкость: чтобы можно было(помимо primary и all) отдельно тюнить абсолютно любую выбранную ноду. Хотелось просто предоставить инструмент для полета экспериментальных мыслей.

2021-03-16 10:11 UTC, Dreamlone commented
> > > > В evaluation.py в конструкторе что-то странное:
> > > > ![image](https://user-images.githubusercontent.com/7864250/109788988-ec49f680-7c20-11eb-87fa-e675a68269e9.png)
> > > > Видимо, идея была в объявлении переменной класса у аннотацией, какой тип у него должен быть - None или SkLearnTuner.
> > > > Но фактически, здесь ссылка _tune_strategy присваивается Класс/объект типа Optional.
> > > 
> > > 
> > > Да, тут явно д.б двоеточие вместо =
> > 
> > 
> > Ну двоеточие тут не проходит, PyCharm подсвечивает как некорректный синтаксис. Я посмотрел через git blame, это вроде Ира писала, ну я, так сказать, её реализации верю, что это корректная запись. Призываю @BarabanovaIrina помочь разобраться как лучше будет исправить) - Я бы, честно сказать, просто сделал как "self._tune_strategy = SklearnTuner"...
> 
> Интерестинг, потому что у меня PyCharm не подсвечивает. Но синтаксис, действительно неверный, и как я такое написала, уже сложно сказать) я имела ввиду вот такое: self._tune_strategy: Type[Tuner] = SklearnCustomRandomTuner. Не знаю, насколько верно будет указывать просто SklearnTuner как дефолтное значение, если у него нет реализации [tune](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/models/tuning/tuners.py#L112-L113), потому как он просто объединяет под собой разные стратегии, импортированные из sklearn.
> 
> Но я помню, что идея SklearnCustomRandomTuner была в том, что он предполагался как RandomTuner для разных моделей, не только из sklearn (потому как в Random, Grid и Bayes внутри идет проверка на то, что модель действительно из sklearn, а с потенциально другими тюнинг не сработал бы). Название он видимо приобрел, потому что эксперименты проводились все равно только на sklearn моделях, да и к тому же именно этот тюнинг (по каким-то причинам) выдавал более лучшие результаты.
> 
> Наверняка возникает мысль, что в SkLearnEvaluationStrategy все таки должен быть self._tune_strategy: Type[SklearnTuner] (а не просто Tuner), но это ограничивает, поэтому все таки Tuner. Если я где-то неправа с точки зрения реализации, поправьте меня.
> 
> Кроме того, там все еще открытая проблема, как указать тип тюнинга (Random, Bayes, TPE и т.д.), потому что извне в рамках данной реализации это сделать невозможно, для проведения экспериментов я просто меняла название класса руками. Но возможно эта проблема уже как-то решена в рамках данного PR.

Спасибо большое за объяснения! Остановился на [этом](https://github.com/nccr-itmo/FEDOT/pull/237/commits/2922ad03878f70f412edb3ad71abed9367f88aab#diff-6db1c51fabdfd8f98a92f49da381e724d9940f2b72d418dc3119a3f3853fbb16L142-R143) варианте. 

Вообще, насколько я понимаю, с тюнингом мы определились, что оставляем только новореализованные в рамках данного PR - [ChainTuner и SequentalTuner](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/operations/tuning/hyperopt_tune/tuners.py) тюнеры. Но в любом случае с SklearnTuner'ом нужно было разобраться, так как я буду его использовать/использую при тестировании различных методов тюнинга для статьи.

2021-03-16 10:16 UTC, Dreamlone commented
> Также отмечу, что идея создания класса [Tune](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/chains/chain_tune.py), в которую мы передаем цепочку, была не в том, чтобы изменить способ тюнинга, а в том чтобы добавить гибкость: чтобы можно было(помимо primary и all) отдельно тюнить абсолютно любую выбранную ноду. Хотелось просто предоставить инструмент для полета экспериментальных мыслей.

Понял, принял. Я схожую логику перенес в метод [tune_node](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/operations/tuning/hyperopt_tune/tuners.py#L380) у SequentialTuner'а , чтобы можно было тюнить отдельные узлы, в том числе с операциями предобработки,. Так что, думаю, в плане функционала для настройки гиперпараметров мы ничего не потеряем после мержа данного PR'а :)

2021-03-16 10:23 UTC, BarabanovaIrina commented
Если мы придем к тому (а скорее всего это так), что новые тюнеры ChainTuner и SequentalTuner решают проблемы:
1. обновляют параметры на основе метрики всей цепочки, а не отдельной модели,
2. позволяют тюнить абсолютно любые ноды
то я могу отрефакторить старые тюнеры по аналогии с новыми и подчистить лишние, чтобы в итоге у них у всех была одна и та же логика работы с цепочкой и отличались они только своим подходом(т.е. заложенным алгоритмом). Если это необходимо. Ну или вообще выпилить старый треш.

2021-03-16 10:33 UTC, Dreamlone commented
> Если мы придем к тому (а скорее всего это так), что новые тюнеры ChainTuner и SequentalTuner решают проблемы:
> 
> 1. обновляют параметры на основе метрики всей цепочки, а не отдельной модели,
> 2. позволяют тюнить абсолютно любые ноды
> 

Да, все именно так и сделано. 

> то я могу отрефакторить старые тюнеры по аналогии с новыми и подчистить лишние, чтобы в итоге у них у всех была одна и та же логика работы с цепочкой и отличались они только своим подходом(т.е. заложенным алгоритмом). Если это необходимо. Ну или вообще выпилить старый треш.

А там они вроде как раз и сопоставимы. Только я возьму для сравнения наверно не SklearnCustomRandomTuner, а TPETuner. В основе у тюнеров как раз будут лежать одинаковые алгоритмы оптимизации hyperopt'а. А с остальным, мне кажется, Паша точно лучше меня подскажет что планируем делать.

2021-03-16 10:46 UTC, J3FALL commented on cases/operations_regression_case_manual.py
> +    node_encoder = PrimaryNode('one_hot_encoding')
Именно функция, которая печатает всю инфу в консоль, не особо полезна и не особо гибкая.
Вот я получил портянку в консоле, а что мне с этим теперь делать?
![image](https://user-images.githubusercontent.com/7864250/111296351-6df84600-865d-11eb-9abb-b6ef906bd729.png)
Нужно все равно руками ходить по коду и вытаскивать нужные классы, типы и т.д.

Т.е. функции, которые ты реализовал, не бесполезны, их можно оставить ради общей инфы.
Но точно нужны именно функции, которые будут возвращать списки alias-ов моделей, дата_операций и т.д.
Чтобы можно было потом их в коде использовать.

2021-03-16 11:31 UTC, J3FALL requested changes

2021-03-16 11:31 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/models/discriminant_analysis.py
> +class DiscriminantAnalysisModel:
Смотри, меня сильно смущает ситуация, что нарушается иерархия классов, которая в нашем фреймворке установлена.
Operations -> Model/DataOperation -> EvaluationStrategy -> SomeFrameworkAndSpecificModelImplementationStrategy

Это то, как я себе представляю в идеальном случае. Сделано это для того, чтобы в слоях Operation и выше не было сильной привязки к конкретным фреймворкам, моделям и их интерфейсам.

Конкретно в этой ситуации:
- DiscriminantAnalysisModel - вижу суффикс Model, но это явно не Model в Fedot архитектуре, а скорее EvaluationStrategy
- Этот класс не является наследником других интерфейсов. У этого может быть какие-то причины, но я пока не могу понять

Нужен еще один созвон по этим вопросам)

2021-03-16 11:31 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/data_operations/sklearn_transformations.py
> +        self.params = current_parameters
Здесь название функции не соответствует тому, что происходит: параметры не только проверяется, но и "фиксятся". Соответственно, функцию следует переименовать.

2021-03-16 11:31 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/data_operations/sklearn_transformations.py
> +        self.params = current_parameters
Либо разделить на 2 - одна только валидирует, вторая - исправляет.

2021-03-16 11:31 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_realisations/data_operations/sklearn_transformations.py
> +    :param params: optional, dictionary with the arguments
А где здесь Adapter? В моем представлении, адаптер - это паттерн, который "мапит" 2 класса с разными интерфейсами.

2021-03-16 12:37 UTC, nicl-nno commented on fedot/core/chains/chain_validation.py
Необходимость task была в том, что корректность структуры модели зависела от типа задачи (для forecasting-а, например, были свои требования). Т.е. по хорошему это д.б обязательный параметр. Но сейчас при вызове validate туда не передается task.

2021-03-17 17:01 UTC, BarabanovaIrina requested changes

2021-03-29 12:41 UTC, Dreamlone commented on cases/operations_regression_case_manual.py
> +    node_encoder = PrimaryNode('one_hot_encoding')
Реализовал функцию operations_for_task в fedot/api/help.py. Она более высокоуровневая, чем её аналог из OperationTypesRepository, так что, думаю, она может быть полезна именно в api. Возвращает словарь с подходящими дата операциями и моделями. Добавил на неё [тест](https://github.com/nccr-itmo/FEDOT/pull/237/commits/ccef1c9ef6ebe5aec00d0a7089862b1f5df14ad8#diff-7ba54da653b134f3daa40cedb94272c95bfbdf73c9c00aa7efce6badca1b7715R91-R99), чтобы не получилось так как с её устаревшем предком.

2021-03-29 12:47 UTC, Dreamlone commented on fedot/core/chains/chain_template.py
>  from fedot.core.chains.node import CachedState, Node, PrimaryNode, SecondaryNode
Импорт экспорт пришлось модифицировать, так как корректно не могли сериализоваться модели в моделях, например случаи, когда RANSAC - это модель, но в своём ядре она использует линейную регрессию. Чтобы перебороть этот момент, сделал вот [так](https://github.com/nccr-itmo/FEDOT/pull/237/commits/514ae2898931aa930f3dec57aaa125f4dd33c986#diff-d37bafe3665bfddcc19c920ed4900379d7fee8196f6dbea4f05c3ef93b6e267eR234-R245). Подготовил пример для проверки корректности этого функционала, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/514ae2898931aa930f3dec57aaa125f4dd33c986#diff-ef13f4bfe2dc6032dcef8eb564b5d210fad1018c80facc3671152ac4ff723de5). 

Но на мастере сейчас с импортом вроде как проблема, так что после ребейза придется скорее всего над этим посидеть мне ещё...

2021-03-29 12:53 UTC, Dreamlone commented on fedot/core/data/data.py
> +def merge_non_equal_outputs(outputs: List[OutputData], idx_list: List):
Добавил новый класс [DataMerger](https://github.com/nccr-itmo/FEDOT/pull/237/commits/820774be9a44780365ef2f5432689ea25ad1ecbe#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR151-R184), теперь его при расширении функционала можно будет наполнять соответствующими методами. Также в [data.py](https://github.com/nccr-itmo/FEDOT/pull/237/commits/820774be9a44780365ef2f5432689ea25ad1ecbe#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052e) изменил реализацию разделения на обучения и тест. Логика осталась та же самая для табличных данных, но для временных рядов данные подготавливаются отдельно по своему.

2021-03-29 14:20 UTC, Dreamlone commented on fedot/core/operations/operation.py
> +    strategy = operations_repo.operation_info_by_id(operation_type).current_strategy(task_type_for_operation)
Добавил комментарии и описание docstring, плюс немного изменил названия переменных, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/9e66a49bb98a48cba9f8f0ae33ced8bb53d9d976#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932). Может быть этого будет достаточно для упрощения?

2021-03-29 14:50 UTC, Dreamlone commented on fedot/utilities/synthetic/chain_template.py
А вот тут поподробней :)
Хотел вынести этот вопрос на обсуждение, так как не совсем понимаю некоторое количество функций, классов и методов в synthetic. В этой же директории есть почему то свой собственный скрипт examples, у этого есть какой-то скрытый смысл, чтобы не выносить его во все examples?
Плюс заметил, что он периодически падает с ошибкой из-за разных проблем у synthetic_benchmark_dataset, как и [тесты](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/test/integration/synthetic_generation/test_synthetic_data.py#L53), использующие эту функцию. Вроде же есть отдельные функции [здесь](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/utilities/synthetic/data.py), которые как раз генерируют синтетические датасеты. И я как раз использую в примерах именно эти функции, а вот  synthetic_benchmark_dataset запускается только в своем локальном examples и тестах, причем и тесты и пример с ним периодически (иногда нет почему то) падают... 

И еще я хотел уточнить в чем отличия между chain_template.py и chain_template_new.py в той же synthetic - может какой-то из них нужно убрать и оставить только новый?

2021-03-29 14:57 UTC, Dreamlone commented on fedot/core/data/data.py
> +        idx, features, target = dataset_merging_funcs[data_type](outputs)
Да, действительно не убрал рудименты от прошлой реализации. Теперь выглядит вот [так](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/data/data.py#L119). Да, target теперь напрямую между узлами направлять не требуется, так как он и так передается в списке с OutputData'ми в DataMerg'er.

2021-03-29 15:01 UTC, Dreamlone commented on fedot/core/operations/evaluation/keras_eval.py
>  import tensorflow as tf
В общем, если что - жду от тебя команды что делать со стратегиями по auto ml, сейчас они находятся в отдельном файле. См. [здесь](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/operations/evaluation/old_strategies.py).

2021-03-29 15:08 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_realisations/abs_interfaces.py
> +class ModelRealisation(ABC):
Обсудили этот пункт на прошлой неделе. В итоге выдержал следующий подход:
Появилась новая абстракция - Implementation. По уровню она соответствует sklearn'ским моделям. То есть, Implementation своими руками стоит писать тогда, когда ни одна библиотека не предоставляет возможности делать с данными то, что хочется именно тебе. Для кастомных Implementation реализованы кастомные же стратегии (EvaluationStrategy). .py файлы со стратегиями поделены на решаемые проблемы (регрессия, классификация, прогнозирование временных рядов, кластеризация, обработка текста, общие операции), см. [здесь](https://github.com/nccr-itmo/FEDOT/tree/preprocessing-refactor/fedot/core/operations/evaluation).

Также поменял названия в соответствии с введенной абстракцией: ARIMAModel теперь является ARIMAImplementation и т.д.

2021-03-29 15:40 UTC, J3FALL commented on fedot/core/chains/chain_template.py
>  from fedot.core.chains.node import CachedState, Node, PrimaryNode, SecondaryNode
Окей, вроде понял по коду, что ты имел в виду.
Еще можно проверить - цепочку из examples/chain_import_export.py запаковать в AtomizedModel и проверить ее на экспорт/импорт.

2021-03-29 15:43 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +            data_operations, _ = DataOperationTypesRepository().suitable_operation(task_type=self.task.task_type)
Ты немного неправильно используешь билдер - к приватному экземпляру composer-а вообще не нужно обращаться напрямую, а использовать его уже после операции build:
![image](https://user-images.githubusercontent.com/7864250/112862694-b2a0ca00-90be-11eb-93cf-746bc4d75095.png)

2021-03-29 15:49 UTC, J3FALL commented on fedot/core/data/data.py
> +def merge_non_equal_outputs(outputs: List[OutputData], idx_list: List):
Вынеси еще DataMerger-related функции в отдельный python-скрипт на одном уровне с data.

2021-03-29 16:01 UTC, J3FALL commented on fedot/utilities/synthetic/chain_template.py
Исторически сложилось так: в прошлом году мы проводили исследования по поводу генерации "синтетических" бенчмарков для композера. Для этого понадобился функционал для генерации около-случайных цепочек, который я реализовал через шаблоны цепочек  a.k.a ChainTemplate.
Они использовались только в utilities/synthetic/examples (ну и в некоторых экспериментах).
В дальнейшем штука с бенчмарками заглохла, и этот код просто остался здесь.

Через некоторое время мы решили запилить импорт/экспорт цепочек, которую начал реализовывать Глеб.
Я предложил ему схожий концепт с шаблонами цепочек, но там так сильно отличался контент, что по-итогу остался отдельный скрипт chain_template_new. 
Далее функционал темплейтов, экспорта и импорта начал расширяться, и мы решили перенести его в core/chains.

По-итогу получается, что весь модуль utilities/synthetic устарел, и я думаю его просто выпилить.
Если он тебя не смущает - можно его игнорировать до последнего, а перед мержом я сам уберу устаревшие скрипты.
Либо можем сделать это сейчас.

2021-03-29 16:08 UTC, J3FALL commented on fedot/core/operations/strategy.py
> +from fedot.core.repository.operation_types_repository import OperationTypesRepository
Увидел, норм.
Обрати внимание еще на опечатку тут:
![image](https://user-images.githubusercontent.com/7864250/112866151-2395b100-90c2-11eb-92d3-e37a9676d29a.png)

2021-03-30 09:23 UTC, Dreamlone commented on fedot/core/repository/operation_types_repository.py
> +        return operations_list
Я разбил этот участок (добавил одну функцию), упростил некоторые конструкции, плюс добавил комментариев. Теперь должно быть понятней. См. [коммит](https://github.com/nccr-itmo/FEDOT/pull/237/commits/c9d9ca6364396ca596c6ba82619f23afc1b3c3b2#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0). 

Тем не менее, в некоторых моментах я сомневаюсь. Поэтому прошу @nicl-nno, Колю, посмотреть не нарушил ли я где-то логику ненароком. Например, правильно ли я  понимаю, что конструкция 

```operation_properties = [operation_properties for operation_key, operation_properties in list(operations_json.items()) if operation_key == current_operation_key][0]```

может быть заменена на ```properties = operations_json.get(current_operation_key)```?

И в целом правильно ли я прокомментировал что в коде происходит - думаю, создателю будет проще увидеть если что-то не так.

2021-03-30 09:26 UTC, Dreamlone commented on fedot/utilities/synthetic/chain_template.py
Понял, спасибо! Не, не смущает, есть пить не просит, тесты на эту функциональность прикрыл skip'ом. Хорошо, тогда в пока буду игнорировать эту часть репозитория.

2021-03-30 10:09 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +        raise ValueError(f'{ERROR_PREFIX} Root operation is not a model')
Спасибо, так и сделал, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/be35c6db05b8505860f32ff08a75afe026f20758#diff-218db4373eb9ac8418056e00df5a0c079969ec0abb02a94d8a40a50865d60c5fR92-R94).

2021-03-30 10:10 UTC, Dreamlone commented on fedot/core/operations/strategy.py
> +from fedot.core.repository.operation_types_repository import OperationTypesRepository
Ага, забралась, [исправил](https://github.com/nccr-itmo/FEDOT/pull/237/commits/be35c6db05b8505860f32ff08a75afe026f20758#diff-a0d1769c8d973d3ea998d0cfeacbc4f9c5c6a0c6b3b32a5ecbe99c28957d5ebfR53-L55).

2021-03-30 10:12 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_realisations/data_operations/sklearn_transformations.py
> +        self.params = current_parameters
Изменил название у функции на [check_and_correct_params](https://github.com/nccr-itmo/FEDOT/pull/237/commits/be35c6db05b8505860f32ff08a75afe026f20758#diff-5e39a9f9030a5ede5afe0312e144050dc38e5fdb5b9c773251d98c40fdbc807fR57-R62). Подправил описание в docstring.

2021-03-30 10:15 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_realisations/data_operations/sklearn_transformations.py
> +    :param params: optional, dictionary with the arguments
Ага, извиняюсь, описание осталось с моих самых первых экспериментов, тогда я и правда пытался использовать паттерн адаптер. Сейчас убрал это слово из описания. См. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/be35c6db05b8505860f32ff08a75afe026f20758#diff-5e39a9f9030a5ede5afe0312e144050dc38e5fdb5b9c773251d98c40fdbc807fR75-R76).

2021-03-30 10:17 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +            data_operations, _ = DataOperationTypesRepository().suitable_operation(task_type=self.task.task_type)
Спасибо, теперь я сообразил, исправил как у тебя, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/b71976a783a0ee9561a81bdd4ad5fa2375b95da9#diff-8576c86049d8efe372732362c9a3d35919785e3795da4155e52f8733fbebffe1R219).

2021-03-30 11:00 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +        return operations_list
Обсудили с Мишей: вот эта штука нуждается в переработке, но лучше отдельным PR-ом - так как надо и в композере это учесть.

![image](https://user-images.githubusercontent.com/5711814/112978671-4d9db080-9160-11eb-8705-77440105abf9.png)

2021-03-30 13:34 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +import datetime
Вот я наконец то добрался :) 
По поводу кейсов - спасибо за комментарии, я полностью с ними согласен. Просто у меня были данные, на которых можно сравнить качество экспертного подхода и того решения, которое может предложить FEDOT с новыми операциями предобработки. Я пробовал несколько разных подходов к одной задаче, чтобы выяснить какой будет более показательным, либо композер, либо просто построенная вручную цепочка и т.д. - пока не выяснил точно (но подозреваю, что останется вариант с композером). Пока я вижу план работы с этими кейсами такой: я прогоню два этих скрипта сегодня/завтра и выберу один хороший пример, напишу для него тесты, и, думаю, можно оставлять. 

Пока предлагаю оставить эту ветку с комментариями открытой, перед мержом все вместе с Пашей @J3FALL, думаю, решим как будет лучше сделать.

2021-03-30 13:35 UTC, Dreamlone commented on cases/operations_regression_case_composer.py
> +                              data_type=DataTypesEnum.table)
Написал выше, что скорее всего все таки нужно будет оставить один файл, так что по части дублирования кода, думаю, переживать не стоит. - Все равно останется только один .py файл.

2021-03-30 13:51 UTC, Dreamlone commented on examples/operations_ts_forecasting_with_exog.py
> +neighboring_level = np.array(df['Neighboring level'])
Внес эту часть кода в основную функцию, см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/237/commits/472ad6071dc88ae6b87054056426b6100e34d011).

2021-03-30 14:02 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +            min_function = ChainTuner.get_metric_value(train_input=train_input,
Согласен, исправил на [metric_value](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-1d228b8f5d2ff70d1afad73c863fa72223d29b070145b0689724e8eb625cae46R207-R222). Тюнеры вынес из расположения в проекте "fedot/core/operations/evaluation/tuning" в "fedot/core/chains/tuning", так как сейчас тюнеры не заходят так "низко" в FEDOT, они на уровне цепочек работают, - поэтому решил, что им там самое место, но, это конечно, обсуждаемо. 

Также растащил классы на отдельные файлы, их общий предок теперь расположился в [tuner_interface.py](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-39800b32adf0f861d9405e367895b3e9c61bd7ce6a1865aca406b78c1bd119bd).

2021-03-30 14:03 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/hp_hyperparams.py
> +    for operation_parameter in operation_parameters:
Спасибо за совет, [исправил](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-210a80a7dac0fa43e2637d72a6aed98c9400e080ddbf88fca57e69adc3028027R216).

2021-03-30 14:08 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +        self.is_need_to_maximize = is_need_to_maximize
Конструкцию сохранил для удобочитаемости. Но согласен, так и сделал, теперь везде используется self.is_need_to_maximize, где это требуется (см., например, [здесь](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-628f32bcbcb56e7cd95ef905ed4003354a8b8f5f107fae5f72585b702b73c79aR128-R143)). Некоторые из функций вынес из staticmethod, чтобы это можно было использовать. 

Нет, с partial никаких проблем из-за этого не возникло.

2021-03-30 14:27 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +            x_train, x_test, y_train, y_test = train_test_split(input_features,
Увидел, спасибо! Тут два важных изменения:

1) Теперь это функция используется в тюнерах, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-1d228b8f5d2ff70d1afad73c863fa72223d29b070145b0689724e8eb625cae46R24-R26). Старый метод [_validation_split](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-a15853548a8f67391142136650f7b6ff60898a1a3166b828cb9b8bdf5a0c9d8bL126-L174) из тюнеров я выпилил. 

2) Как ты и советовала в комментарии ниже, реализовал метод разделения на обучение и тест для временных рядов. На данный момент существуют функции разделения на обучение и тест для временных рядов (split_time_series) и для табличных данных (split_table). Посмотреть можно [здесь](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/data/data.py).

2021-03-30 14:33 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +                                  target=None,
Да нет, все верно, это был костыль, от которого стоило избавится. Так и сделал. Target там теперь присваивается. Но я всегда старюсь в кейсах и примерах ставить target=None для тех данных, которые участвуют в predict'е, потому что мало ли: утечка данных и target используется для улучшения прогноза, что может привести к улучшению точности. Поэтому в моем коде такие вещи проскальзывают - лучше перестраховаться, чем не перестраховаться.

2021-03-30 14:34 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +            # Time series forecasting task - TODO not optimal split -> vital!
Так и сделал, см. [ответ](https://github.com/nccr-itmo/FEDOT/pull/237#discussion_r604149413) на комментарий выше.

2021-03-30 14:40 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +
Ага, так сделал, теперь print'ы не используются, но зато используется логер, как [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-39800b32adf0f861d9405e367895b3e9c61bd7ce6a1865aca406b78c1bd119bdR78) или [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/5b9337c887c6dd7d5bb1b4435fa95ca77f454670#diff-39800b32adf0f861d9405e367895b3e9c61bd7ce6a1865aca406b78c1bd119bdR109-R138).

2021-03-30 15:05 UTC, BarabanovaIrina commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +            x_train, x_test, y_train, y_test = train_test_split(input_features,
Есть мнение, что в production code лучше не использовать assert (как [тут](https://github.com/nccr-itmo/FEDOT/blob/preprocessing-refactor/fedot/core/data/data.py#L353)) Не рекомендуют использовать в случае user input validation, как минимум потому что это не дает понятного описания ошибки(будет просто AssertionError).

2021-03-30 15:41 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/hp_hyperparams.py
> +        'rf | n_estimators': hp.choice(label, [100]),
Это хороший вопрос. Начну с того, что есть мной эмпирически выведенное правило: hyperopt воспринимает названия гиперпараметров (label который) в словаре как ключи, то есть, если есть цепочка из двух моделей ridge -> ridge, и нам требуется оптимизировать параметр alpha как в первом узле, так и во втором, то нам нужно задать разные названия этим параметрам. Если название параметров в словаре никак не отличаются друг от друга, то для hyperopt'а это будет восприниматься как один единственный параметр, то есть если присвоить переменной label в конструкции hp.choice(label, range(1, 11)) значение 'alpha', поместить в словарь, и повторить такое же действие для другого параметра alpha, то нас ждет сюрприз, значения, выбираемые гипероптом при оптимизации будут присваиваться одновременно этим двум alpha в двух разных узлах.

Поэтому я решил, что label должен быть уникальным, а уникальным он может быть, например, если его название будет вроде "номер узла | название модели | название параметра", а чтобы удобнее склеивать их было, подготовил вот такую структуру. Мне так проще было начинать с этим работать, но согласен, хранить можно в структуре и поудобней (да и сам ключ свести до "номер узла | параметр"), я это исправлю завтра с утра. Плюс добавлю возможность выбирать не только количество итераций, но и время, выделяемое для оптимизации.

2021-03-31 09:08 UTC, Dreamlone commented on fedot/core/data/data.py
> +def merge_non_equal_outputs(outputs: List[OutputData], idx_list: List):
Сделано, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/84da94c7bf27c39230b7cda1350d1aa2a768c993#diff-92426a61e63324be67ca2359f0ea4ef0aea15ab0c6d2e10ef74d937982ecafb2).

2021-03-31 13:23 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/hp_hyperparams.py
> +        'rf | n_estimators': hp.choice(label, [100]),
Изменил структуру словаря, теперь он занимает меньше места и при этом добавлять новые модели с параметрами в него будет попроще, чем в изначальный вариант. Изменения см. [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/64e009ea9bbf184ebaedde62d1fa77165b769b91#diff-210a80a7dac0fa43e2637d72a6aed98c9400e080ddbf88fca57e69adc3028027).

Логику кодирования значений менять не стал (вспомнил про это почему именно так задавать решил). Все параметры из словаря кодируются в виде "номер узла || название модели | название параметра", а не "номер узла | параметр" для того, чтобы избежать ситуации, когда есть две одинаковые модели в разных узлах. id узла как раз помогает решать такие ситуации. В общем, из словаря параметрам присваиваются лейблы "номер узла || название модели | название параметра".

2021-03-31 13:24 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +            x_train, x_test, y_train, y_test = train_test_split(input_features,
Решил использовать [вот такую](https://github.com/nccr-itmo/FEDOT/pull/237/commits/64e009ea9bbf184ebaedde62d1fa77165b769b91#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR202-R203) конструкцию.

2021-03-31 13:30 UTC, Dreamlone commented on fedot/core/operations/tuning/hyperopt_tune/tuners.py
> +
Понял твой point - сделал так, чтобы свой логгер был у тюнера, см. изменения [тут](https://github.com/nccr-itmo/FEDOT/pull/237/commits/64e009ea9bbf184ebaedde62d1fa77165b769b91#diff-39800b32adf0f861d9405e367895b3e9c61bd7ce6a1865aca406b78c1bd119bdR30-R34).
Также добавил возможность задавать время для оптимизации, а не только количество итераций.

2021-04-12 16:05 UTC, J3FALL approved these changes

2021-04-12 16:09 UTC, BarabanovaIrina approved these changes

2021-04-12 16:11 UTC, nicl-nno approved these changes

2021-04-12 16:17 UTC, merged