API updated, intro notebook added
nccr-itmo/FEDOT pull request #240
Opened 2021-02-27 15:23 UTC by nicl-nno

1. notebooks/intro_to_automl.py added
2. API simplified to be more clear

2021-03-02 08:46 UTC, J3FALL requested changes

2021-03-02 08:46 UTC, J3FALL commented on fedot/api/api_utils.py
> +def _filter_models_by_preset(available_model_types: list,
Мб добавить тесты на эту функцию?
Тут есть несколько вариантов для параметра model_configuration, который влияет на набор моделей.
Эти наборы могут меняться в дальнейшем.

2021-03-02 08:46 UTC, J3FALL commented on fedot/api/api_utils.py
> +                        with_tuning=True
Я бы по умолчанию отключил тюнинг, ибо это сильно замедляет вычисления.

2021-03-02 08:46 UTC, J3FALL commented on fedot/api/main.py
> +    def clean_model(self):
prediction тоже очищается, а в названии функции есть только model )

2021-03-02 08:46 UTC, J3FALL commented on fedot/api/main.py
> +    def validate(self,
А почему функция validate?
Вроде не видно какой-то особенной валидации.

2021-03-02 08:46 UTC, J3FALL commented on fedot/core/chains/utils.py
> +from uuid import uuid4
В общем, я не фанат утилитарных классов, функций и скриптов, поскольку в долгосроке это порождает плохую практику в стиле "Ну, я не знаю, как назвать новый класс/функцию, ну, значит, просто в utills засуну пока"
В перспективе эти скрипты/классы начинают нарушать целый ряд ooп-практик.

Почему это плохо, можно почитать [тут](https://medium.com/@sahoosunilkumar/utils-class-good-and-or-bad-3f0d867ffc39) или [тут](https://www.yegor256.com/2014/05/05/oop-alternative-to-utility-classes.html).

Сейчас по логике в этом скрипте одна функция, которая преобразует цепочку из FEDOT формата в NetworkX.
Мб тогда и скрипт лучше назвать convert? Ну или в стиле.
Тогда будущие разработчики, изучая код ядра, задумаются лишний раз - а надо ли ему свою функцию помещать в этот скрипт, или нет.

2021-03-02 08:46 UTC, J3FALL commented on fedot/core/data/data.py
> +        if features.shape[1] == 0 and task.task_type == TaskTypesEnum.ts_forecasting:
Думаю, стоит добавить функцию с говорящим названием, которая проверяет этот исключительный кейс.

2021-03-02 08:46 UTC, J3FALL commented on fedot/core/data/visualisation.py
> +def plot_forecast(pre_history: 'InputData', forecast: 'OutputData'):
Это здесь должно быть?
Выглядит, как какой-то временный скрипт.

2021-03-02 08:46 UTC, J3FALL commented on plt_mod.py
> +from fedot.core.chains.chain import Chain
Этот скрипт, кажется, тоже лишний.

2021-03-02 08:46 UTC, J3FALL commented on test/unit/tasks/test_api.py
> +    # TODO correct asserts
Ето что значит?)

2021-03-02 09:58 UTC, nicl-nno commented on fedot/core/data/visualisation.py
> +def plot_forecast(pre_history: 'InputData', forecast: 'OutputData'):
Идея была в том, что было бы хорошо иметь в рамках фреймворка какие-то функции для визуализации не только структуры моделей, но и результатов моделирования (в текстовом или графическом виде). Поэтому для data cоздал отдельный скрипт для визуализации.

2021-03-02 19:24 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/chains/chain_template.py`](https://github.com/nccr-itmo/FEDOT/blob/fa39af7188e1b39c93179c0a5e4604a1835a7a5d/fedot/core/chains/chain_template.py):

> [Line 235:21](https://github.com/nccr-itmo/FEDOT/blob/fa39af7188e1b39c93179c0a5e4604a1835a7a5d/fedot/core/chains/chain_template.py#L235): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file





















* In the file [`test/unit/api/test_main_api.py`](https://github.com/nccr-itmo/FEDOT/blob/fa39af7188e1b39c93179c0a5e4604a1835a7a5d/test/unit/api/test_main_api.py):

> [Line 90:1](https://github.com/nccr-itmo/FEDOT/blob/fa39af7188e1b39c93179c0a5e4604a1835a7a5d/test/unit/api/test_main_api.py#L90): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-03-02 23:17 UTC, nicl-nno commented on test/unit/tasks/test_api.py
> +    # TODO correct asserts
Уже пофиксил, проверки были неправильные.

2021-03-02 23:17 UTC, nicl-nno commented on plt_mod.py
> +from fedot.core.chains.chain import Chain
Удалил

2021-03-02 23:17 UTC, nicl-nno commented on fedot/core/data/data.py
> +        if features.shape[1] == 0 and task.task_type == TaskTypesEnum.ts_forecasting:
Добавил [_process_empty_features_for_task](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR275-R278)

2021-03-02 23:18 UTC, nicl-nno commented on fedot/core/chains/utils.py
> +from uuid import uuid4
Переименовал в [chain_convert](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-57c75bd0d6572dfa303c31a969ee07ddaf1881ab75839ae83c5f29f4abf9f391R8), перенес сюда ещё одно однотипную функцию из ChainTemplate

2021-03-02 23:18 UTC, nicl-nno commented on fedot/api/main.py
> +    def validate(self,
Переименовал в [get_metrics](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR241-R243)

2021-03-02 23:18 UTC, nicl-nno commented on fedot/api/main.py
> +    def clean_model(self):
Назвал просто [clean](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR128). Хз, как это компактно поименовать.

2021-03-02 23:19 UTC, nicl-nno commented on fedot/api/api_utils.py
> +                        with_tuning=True
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR77) управление тюнингом в preset.

Но вообще в варианте по умолчанию боюсь придется включить, т.к. всё-таки это дает и выигрыш в эффективности.

2021-03-02 23:20 UTC, nicl-nno commented on fedot/api/api_utils.py
> +def _filter_models_by_preset(available_model_types: list,
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/240/files#diff-bba9273ae2580c3bdd660ae5018de809859a87a7221f6ce158ee08c90f44b77cR6-R25)

2021-03-03 07:58 UTC, J3FALL approved these changes

2021-03-03 07:58 UTC, J3FALL commented on fedot/core/data/visualisation.py
> +def plot_forecast(pre_history: 'InputData', forecast: 'OutputData'):
Ок, понял.

2021-03-03 08:04 UTC, J3FALL commented on fedot/api/api_utils.py
> +                        with_tuning=True
норм.
мб логгер вынести чуть ниже в плане параметров?
![image](https://user-images.githubusercontent.com/7864250/109773365-2bbc1700-7c10-11eb-88f6-ae6526fec6db.png)

2021-03-03 10:27 UTC, merged