Version updated to 0.2.1, README actualized
nccr-itmo/FEDOT pull request #243
Opened 2021-03-11 15:42 UTC by nicl-nno

1. Version updated to 0.2.1
2. API code in README actualized

2021-03-11 16:17 UTC, J3FALL requested changes

2021-03-11 16:17 UTC, J3FALL commented on README.rst
Проверь, у меня как-то косячно отображается, пропустил что-то в коде, кажется.
![image](https://user-images.githubusercontent.com/7864250/110818391-43457080-829e-11eb-8026-eb92676cbe9a.png)

2021-03-11 17:11 UTC, nicl-nno commented on README.rst
Пофиксил.

2021-03-11 17:18 UTC, J3FALL commented on README.rst
Мб оставить все-таки первые 2-3 строчки, откуда взялись train_data и test_data?

2021-03-11 17:18 UTC, J3FALL commented on README.rst
Ибо выглядит, что передаются только признаки, а таргет - нет.

2021-03-11 17:21 UTC, nicl-nno commented on README.rst
Ну они в любом случае "извне" берутся - не вносить же в ридми их считывание с диска

>Ибо выглядит, что передаются только признаки, а таргет - нет.

Мб тогда так:
 model.fit(features=train_data.features, target=train_data.target)
 prediction = model.predict(features=test_data.features)
?

2021-03-12 08:58 UTC, J3FALL commented on README.rst
угу, норм

2021-03-12 09:34 UTC, nicl-nno commented on README.rst
обновил

2021-03-12 09:40 UTC, J3FALL approved these changes

2021-03-12 09:51 UTC, merged