Minor improvement for api
nccr-itmo/FEDOT pull request #251
Opened 2021-03-15 17:12 UTC by nicl-nno

Fixed bug in TS forecasting with API (data type was applied incorrectly)

Also, ts version for old python is updated.

2021-03-15 19:05 UTC, J3FALL commented on test/unit/api/test_main_api.py
> +def test_api_forecast_other_data_format_correct(task_type: str = 'ts_forecasting'):
other_data_format - название неконкретное, что значит "другой" формат?

2021-03-16 12:38 UTC, nicl-nno commented on test/unit/api/test_main_api.py
> +def test_api_forecast_other_data_format_correct(task_type: str = 'ts_forecasting'):
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/251/files#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fbR91) на test_api_forecast_numpy_input_with_static_model_correct

2021-03-16 15:41 UTC, J3FALL approved these changes

2021-03-18 13:18 UTC, nicl-nno commented
Сделал ещё несколько обновлений для совместимости с automlbenchmark

2021-03-19 10:19 UTC, J3FALL requested changes

2021-03-19 10:19 UTC, J3FALL commented on fedot/api/api_utils.py
> +)
Я так и не понимаю, в чем польза инициализации словаря через dict, а не {} ?

2021-03-19 10:19 UTC, J3FALL commented on fedot/api/api_utils.py
>      is_tuning = '_tun' in preset or preset == 'full'
Получилось слишком компактно, что даже и не понятно, что имеется в виду.
Вообще, как я понял по тестам, preset - это набор используемых моделей + ты добавил еще постфикс _tun для проверки, нужен ли еще тюнинг или нет?
Мне кажется, экономия одного внешнего параметра того не стоит, ну будет with_tuning=False в функции compose_fedot_model - ничего такого вроде.
А так с этими префиксами выглядит не очень, ибо всегда можно забыть, какой там префикс должен быть.
Т.е. тут либо:
- Выделять спец. класс preset с двумя полями
- Делать 2 параметра - preset + with_tuning
- Делать "словарь" со всеми возможными комбинациями: ultra_light, light, light_tun, ultra_light_tun, и т.д.

2021-03-19 10:19 UTC, J3FALL commented on fedot/api/main.py
> +                         'silhouette': Silhouette
Немного смущает, что в скрипте выше есть словарь _metrics_mapping, в котором контент дублируется частично.
Так и задумывалось?

2021-03-19 10:19 UTC, J3FALL commented on fedot/utilities/define_metric_by_task.py
>                          }
Еще немного словарей с метриками ))

2021-03-19 10:19 UTC, J3FALL commented on test/integration/quality/test_quality_improvement.py
> +    assert auto_metrics['roc_auc'] > baseline_metrics['roc_auc'] >= 0.827
Почему именно 0.827 ?)

2021-03-19 17:14 UTC, nicl-nno commented on test/integration/quality/test_quality_improvement.py
> +    assert auto_metrics['roc_auc'] > baseline_metrics['roc_auc'] >= 0.827
Ну вот именно такое у бейзлайна качество на этих данных. Если оно снизилось - значит что-то сломано. [Вынес](https://github.com/nccr-itmo/FEDOT/pull/251/files#diff-c6b4340997ef324bb8c9df3307fd583cabefe52d225b0ee10c045df4eaa1d2f4R18) в переменную.

2021-03-19 17:15 UTC, nicl-nno commented on fedot/api/main.py
> +                         'silhouette': Silhouette
В идеале это разные метрики - одни для композирования, другие для оценки результата. Но в текущей реализации действительно разумно [убрать](https://github.com/nccr-itmo/FEDOT/pull/251/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR338) дублирование.

2021-03-19 17:15 UTC, nicl-nno commented on fedot/api/api_utils.py
> +)
Ну, например меньше кавычек можно писать. Ок, поменял на {}

2021-03-19 17:18 UTC, nicl-nno commented on fedot/utilities/define_metric_by_task.py
>                          }
Ну этот и в SA используется, как раз и сослался на него, чтобы убрать дублирование.

2021-03-19 17:19 UTC, nicl-nno commented on fedot/api/api_utils.py
>      is_tuning = '_tun' in preset or preset == 'full'
В функции compose_fedot_model-то не проблема это сделать, но пока не придумал, как это удобно вывести наружу API. Вроде пользователю вообще не особо важно, происходит внутри тюнинг или нет. Мб тут что-то в стиле билдера нужно?

Пока вынес [сюда](https://github.com/nccr-itmo/FEDOT/pull/251/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR118-R126).

2021-03-23 09:50 UTC, J3FALL commented on fedot/api/api_utils.py
>      is_tuning = '_tun' in preset or preset == 'full'
Я не вижу ничего страшного, если в конструкторе Fedot будет опциональное поле - with_tuning.
Ну или если ты его сейчас в composer_params упрятал, но неплохо было бы в docstring или где-то еще раскрыть - что может быть передано в словаре composer_params

2021-03-23 11:09 UTC, nicl-nno commented on fedot/api/api_utils.py
>      is_tuning = '_tun' in preset or preset == 'full'
[Done](https://github.com/nccr-itmo/FEDOT/pull/251/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR57-R64)

Пример тоже добавил.

2021-03-23 14:21 UTC, J3FALL approved these changes

2021-03-23 14:29 UTC, merged