Multi-objective and regression API improvement
nccr-itmo/FEDOT pull request #261
Opened 2021-04-13 21:23 UTC by nicl-nno

- Multi-objective API added
- Regression API corrected
- Inital chains for classificastion/regression added to improve the quality
- Minor fixes
- Version updated to 0.3.0

2021-04-14 11:23 UTC, J3FALL requested changes

2021-04-14 11:23 UTC, J3FALL commented on fedot/api/main.py
>                  }
хм, вроде 2 словаря отличаются только одним значением?
можно, по идее, сократить дублирование.
И еще - 200 поколений - не многовато для дефолта?

2021-04-14 11:23 UTC, J3FALL commented on fedot/api/main.py
> +                 learning_time: Optional[float] = None,
Если learning_time float - ничего не ломается, если задать условно 2.5 минуты?

2021-04-14 11:23 UTC, J3FALL commented on fedot/api/main.py
> +            raise ValueError('Forecasting can be used only for the time series')
Вообще у нас немного получается, что ломается ООП в этом случае )
Типо, в зависимости от значения поля класса можно или нельзя использовать определенные интерфейсы.
Я пока не знаю, как лучше это решить, если мы хотим оставить Fedot класс как условный фасад всего фреймворка.

2021-04-14 11:23 UTC, J3FALL commented on fedot/core/composer/metrics.py
> +                                              y_pred=predicted.predict)
Кажется, на этот класс не хватает тестов

2021-04-14 11:23 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/operators/crossover.py
> +                                                                   deepcopy(chain_second), max_depth)
Думаю, может, грамотнее было бы делать deepcopy внутри этого метода, а не наоборот?
Иначе просто получается, что юзер может забыть передать копии своих объектов, и они будут модифицированы.
Хотя интерфейс метода показывает, что будет return новых объектов.

2021-04-14 11:23 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +                new_chain = mutation_by_type[mutation_type](chain=deepcopy(chain), requirements=requirements,
Тот же вопрос, что и выше с кроссовером.

2021-04-14 11:23 UTC, J3FALL commented on fedot/core/composer/optimisers/utils/pareto.py
> +class ParetoFront(DeapParetoFront):
Тоже, думаю, стоит добавить базовый тест на новый класс

2021-04-14 11:28 UTC, nicl-nno commented on fedot/api/main.py
> +            raise ValueError('Forecasting can be used only for the time series')
Думаю можно это пофиксить, добавив FedotTS/FedotClassifier/FedotRegressor, унаследов их от Fedot.

2021-04-14 12:06 UTC, Dreamlone requested changes

2021-04-14 18:43 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        best_candidates = gp_composer.optimiser.archive
>Вот тут не очень понял - почему для каждой итоговой цепочки нужно прописывать ссылку на логгер?

Ну тут вопрос в том, должно ли композер назначать цепочкам тот логгер, который используем сам. Вроде это не всегда логично. А тут им присваивается логгер, используемой в рамках функции, где композер вызван.

>гарантируется многокритериальным композером

Да, в начале списка - лучший по значению первой метрики (обычно это quality).

2021-04-14 18:44 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        best_candidates = [chain_gp_composed]
Для однокритериального случая chain_gp_composed - это не список, а Chain. 
Но best_candidates для единообразия оставляем списком. Или ты про другое?

2021-04-14 20:47 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





















































* In the file [`test/integration/quality/test_quality_improvement.py`](https://github.com/nccr-itmo/FEDOT/blob/0e5cf57a8e03c906a46ddfc2d9285496b823ba09/test/integration/quality/test_quality_improvement.py):

> [Line 36:94](https://github.com/nccr-itmo/FEDOT/blob/0e5cf57a8e03c906a46ddfc2d9285496b823ba09/test/integration/quality/test_quality_improvement.py#L36): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-04-14 20:47 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        metric_function.append(specific_metric_function)
[Извлек](https://github.com/nccr-itmo/FEDOT/pull/261/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR285-R303)

2021-04-14 20:47 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        init_chain = Chain(node_final)
[Done](https://github.com/nccr-itmo/FEDOT/pull/261/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR230-R244). В будущем тут можно впилить какую-то интеллектуальную логику подбора шаблона под датасет.

2021-04-14 20:48 UTC, nicl-nno commented on fedot/api/main.py
>                  }
>И еще - 200 поколений - не многовато для дефолта?

Это для варианта, когда число поколений де-факт ограничено временем. [Указал](https://github.com/nccr-itmo/FEDOT/pull/261/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR114-R116) это более явно.

Словари объединил, т.к. теперь можно тюнить и ts-модели.

2021-04-14 20:48 UTC, nicl-nno commented on fedot/api/main.py
> +                 learning_time: Optional[float] = None,
Ну да. В тестах оно дробное.

2021-04-14 20:48 UTC, nicl-nno commented on fedot/core/composer/metrics.py
> +                                              y_pred=predicted.predict)
Вот [тут](https://github.com/nccr-itmo/FEDOT/blob/a6ac77e40bd3d7da74cda38c2320ccd0ea0ca4b0/test/unit/composer/test_quality_metrics.py#L67) тестируются все метрики разом (но только на техническую корректность, по сути).

2021-04-14 20:48 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/crossover.py
> +                                                                   deepcopy(chain_second), max_depth)
Смысл такой реализации в том, что crossover - фасад для множества вариантов конкретных реализацией кроссовера. Поэтому кажется логичнее все общие технические операции вынести в него, оставив внутри конкретных функций только алгоритмическую логику.

2021-04-14 20:48 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +                new_chain = mutation_by_type[mutation_type](chain=deepcopy(chain), requirements=requirements,
См. выше, логика та же.

2021-04-14 20:49 UTC, nicl-nno commented on fedot/core/composer/optimisers/utils/pareto.py
> +class ParetoFront(DeapParetoFront):
[Done](https://github.com/nccr-itmo/FEDOT/pull/261/files#diff-9e9bf6707fb39c4941785d8708dde486333c95c66ecfc6cf97ca90d6e0ddee09R38-R55)

2021-04-14 20:49 UTC, nicl-nno commented on fedot/core/chains/chain_template.py
> +
Ок, раз починено на уровне операций - удалил.

2021-04-15 09:20 UTC, J3FALL commented on fedot/api/api_utils.py
> +        best_candidates = gp_composer.optimiser.archive
Ок, тогда надо обновить docstring в методе у GPComposer-е:
![image](https://user-images.githubusercontent.com/7864250/114846013-f09f2d00-9de4-11eb-885b-1c6127afdb35.png)

2021-04-15 09:24 UTC, J3FALL commented on fedot/api/api_utils.py
> +        best_candidates = [chain_gp_composed]
Пардон, вроде тут все норм, я просто перепутал начальное условие

2021-04-15 09:55 UTC, J3FALL commented on fedot/core/composer/metrics.py
> +                                              y_pred=predicted.predict)
ок, разумно, тогда оставим

2021-04-15 11:29 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/operators/crossover.py
> +                                                                   deepcopy(chain_second), max_depth)
ок, понял

2021-04-15 13:14 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        best_candidates = gp_composer.optimiser.archive
![image](https://user-images.githubusercontent.com/5711814/114874885-6ca96d00-9e05-11eb-8c8a-4e2a4c276369.png)

Добавил.

2021-04-15 15:27 UTC, J3FALL commented
Предлагаю подождать изменений от Миши отсюда #263, а потом смержить это в мастер.

2021-04-15 15:28 UTC, J3FALL approved these changes

2021-04-15 15:28 UTC, nicl-nno commented
Ок

2021-04-16 10:55 UTC, Dreamlone approved these changes

2021-04-16 11:11 UTC, merged