Chain multistep forecast realisation
nccr-itmo/FEDOT pull request #263
Opened 2021-04-15 10:32 UTC by Dreamlone

Implemented the multistep time series forecast method (as chain.forecast()), added an example to examples folder and prepare test for this example.

2021-04-15 12:45 UTC, nicl-nno commented
Наверно, стоит сюда же добавить и функцию для predict внутри выборки. Т.е. test 100 значений, каждые 10 используеются под независимый прогноз. Это пригодится для более точного вычисления метрик.

2021-04-15 12:54 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +    def forecast(self, input_data: InputData = None, horizon: int = None,
Я бы вынес это как  отдельную функцию, принимающую chain. Чтобы не делать новых классов, но и иметь возможность делать forecast. А в API будет ее вызывать.

2021-04-15 15:25 UTC, J3FALL requested changes

2021-04-15 15:25 UTC, J3FALL commented on fedot/core/chains/chain_wrappers.py
> +def out_of_sample_forecast(chain: Chain, input_data: InputData, horizon: int = None):
я бы в нейминге явно отразил, что речь идет про временные ряды

2021-04-15 15:25 UTC, J3FALL commented on fedot/core/chains/chain_wrappers.py
> +def in_sample_forecast(chain: Chain, supplementary_data: InputData,
ну и тут тоже

2021-04-16 09:25 UTC, Dreamlone commented on fedot/core/chains/chain.py
> +    def forecast(self, input_data: InputData = None, horizon: int = None,
Так и сделал, появились функции out_of_sample_ts_forecast и in_sample_ts_forecast. Обе эти функции размещены в [chain_ts_wrappers.py](https://github.com/nccr-itmo/FEDOT/pull/263/commits/e50da6469f71ddb2d91aaf2ee3059fb6ec20a333#diff-2be4a7fd12d9052d0c143d2e216c689aac03d22833d7b2c225d4069646274ac2)

2021-04-16 09:26 UTC, Dreamlone commented on fedot/core/chains/chain_wrappers.py
> +def out_of_sample_forecast(chain: Chain, input_data: InputData, horizon: int = None):
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/263/commits/64f393f399c2fbd8cc9c0248917f4a5b9e7c13b2#diff-6db2245e9816823455c31ff1f919428e07ce4dc060f9437f333d12c58ab881c8L58-R55), теперь названия: out_of_sample_ts_forecast и in_sample_ts_forecast, название с chain_wrappers поменял на  chain_ts_wrappers.

2021-04-16 09:27 UTC, Dreamlone commented on fedot/core/chains/chain_wrappers.py
> +def in_sample_forecast(chain: Chain, supplementary_data: InputData,
См. комментарий выше, названия изменил.

2021-04-16 09:54 UTC, J3FALL approved these changes

2021-04-16 10:49 UTC, nicl-nno approved these changes

2021-04-16 10:53 UTC, merged