Lagged hyperparameters check and correct
nccr-itmo/FEDOT pull request #267
Opened 2021-04-16 12:37 UTC by Dreamlone

The function of changing the lagged transformation hyperparameter depending on the length of the time series was implemented.

2021-04-16 12:38 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/ts_forecasting_problem_small_ts.py`](https://github.com/nccr-itmo/FEDOT/blob/6d9e00aa5751c28980edff13f1775010d21dabb0/examples/ts_forecasting_problem_small_ts.py):

> [Line 152:1](https://github.com/nccr-itmo/FEDOT/blob/6d9e00aa5751c28980edff13f1775010d21dabb0/examples/ts_forecasting_problem_small_ts.py#L152): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-04-19 15:18 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +        self.check_and_correct_neighbors(train_data)
check_and_correct_k_value будет более понятно кмк

2021-04-19 15:21 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Кажется это все равно слишком много для варианта по умолчанию. 
Мб что-то вроде round(len(input_data.features) / 2)

2021-04-19 15:22 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/knnreg.py
> +class CustomKnnRegImplementation(ModelImplementation):
Может унаследывать knn и knn_reg их от общей реализации, чтобы избежать дублирования?
Вроде вся разница - в функции для создания model.
Ну и можно всё это в одном скрипте сделать.

2021-04-19 15:50 UTC, J3FALL requested changes

2021-04-19 15:50 UTC, J3FALL commented on examples/bad_knn_classification_example.py
> +    run_experiment()
Миша, напомни, плз - этот пример должен был упасть из-за того, что `'n_neighbors': 150` был задан слишком большим?

2021-04-19 15:50 UTC, J3FALL commented on examples/bad_knn_regression_example.py
> +    run_experiment()
Тот же вопрос, что и с примером про классификацию.

2021-04-19 15:50 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/param_free_gp_optimiser.py
> +        self.compl_position = 1
get_metric_position больше не используется, надо поправить импорты в скрипте

2021-04-19 15:50 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def check_and_correct_window_size(self, input_data, forecast_length) -> None:
Вероятно, здесь не нужна аннотация -> None

2021-04-19 15:50 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
По-хорошему бы это в лог писать, а не просто ворнинг выкидывать

2021-04-19 15:50 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/knnreg.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Выглядит вроде так, что для классификации и регрессии методы одинаковые

2021-04-20 09:25 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +        self.check_and_correct_neighbors(train_data)
Изменил название на [check_and_correct_k_value](https://github.com/nccr-itmo/FEDOT/pull/267/commits/5e9ce260912c60c242d5bd72a7f85bfebee483f2#diff-5012cb03648ba08a546abef9e4bfa82fc96760d69724c05f5a7f653f8f698295R35-R36)

2021-04-20 09:25 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Так и сделал, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/267/commits/5e9ce260912c60c242d5bd72a7f85bfebee483f2#diff-5012cb03648ba08a546abef9e4bfa82fc96760d69724c05f5a7f653f8f698295R46-R47)

2021-04-20 09:27 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knnreg.py
> +class CustomKnnRegImplementation(ModelImplementation):
Согласен, теперь все расположено в [knn.py](https://github.com/nccr-itmo/FEDOT/pull/267/commits/5e9ce260912c60c242d5bd72a7f85bfebee483f2#diff-5012cb03648ba08a546abef9e4bfa82fc96760d69724c05f5a7f653f8f698295). Есть класс-предок "KNeighborsImplementation" и два его потомка "CustomKnnClassImplementation" и "CustomKnnRegImplementation"

2021-04-20 09:30 UTC, Dreamlone commented on examples/bad_knn_classification_example.py
> +    run_experiment()
Да, абсолютно верно, он выводил бы ошибку "ValueError: Expected n_neighbors <= n_samples, but n_samples = 100, n_neighbors = 150". Этот скрипт тут лежит просто для того, чтобы можно было вам с Колей запустить его и убедиться, что все действительно работает - по идее, могу это модифицировать в unit-тесты, или же просто удалить их перед мержом в мастер - только дай отмашку.

2021-04-20 09:31 UTC, Dreamlone commented on examples/bad_knn_regression_example.py
> +    run_experiment()
Ага, все верно, тут просто пример с регрессией - используется другая модель, 'knnreg' вместо 'knn'

2021-04-20 09:32 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_comp/param_free_gp_optimiser.py
> +        self.compl_position = 1
Сделано, [импорты исправил](https://github.com/nccr-itmo/FEDOT/pull/267/commits/14bfa0d372e878aba777a52fc6badcab7cba070e#diff-33c5ad7f353dbd901b426b49eb02159425db2aaa2a103d8eb722d92d96f1df0c).

2021-04-20 09:32 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def check_and_correct_window_size(self, input_data, forecast_length) -> None:
[Убрал](https://github.com/nccr-itmo/FEDOT/pull/267/commits/5e9ce260912c60c242d5bd72a7f85bfebee483f2#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412L74)

2021-04-20 09:36 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knnreg.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Ага, так и есть, избавился от [дублирования](https://github.com/nccr-itmo/FEDOT/pull/267/commits/5e9ce260912c60c242d5bd72a7f85bfebee483f2#diff-5012cb03648ba08a546abef9e4bfa82fc96760d69724c05f5a7f653f8f698295). Сейчас все лежит в файле "knn.py". Классы "CustomKnnClassImplementation" и "CustomKnnRegImplementation" унаследованы от "KNeighborsImplementation".

2021-04-20 09:40 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Согласен с тобой, но как тут лучше будет сделать? - Инициализировать свой собственный логер для конкретной операции, или пробросить логер цепочки до имплементаций? 

Просто я бы инициализировал свой логер для "KNeighborsImplementation" и оставил бы так, но тогда есть вопрос, стоит ли повторить такую модификацию для всех Implementation?

2021-04-20 11:09 UTC, J3FALL approved these changes

2021-04-20 11:10 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Смотри, можно в рамках конкретно этой модели сделать в конструкторе по аналогии, как у нас в других местах:
![image](https://user-images.githubusercontent.com/7864250/115386470-190e9900-a1e2-11eb-9a45-a47ded3a6be4.png)
И добавить задачу на пересмотр логирования на уровне Implementation/Evaluation.
Нужно будет проверить, не возникнет ли просадок по производительности, если прокидывать логгер сверху вниз

2021-04-20 11:11 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/knnreg.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
добро

2021-04-20 13:11 UTC, Dreamlone commented on examples/bad_knn_classification_example.py
> +    run_experiment()
Так и сделал, теперь есть тесты "data_operations/test_data_operation_params.py" и "test_models_params.py" в unit тестах, все примеры подчистил, данные из cases удалил. См. коммиты [тут](https://github.com/nccr-itmo/FEDOT/pull/267/commits/ad15468b1bdd6dd4c05d450cf2128a9132252745#diff-0e20b4707f45383f030883e4fc699bf3e6135926c86b0ddb26bba6900318586d) и [тут](https://github.com/nccr-itmo/FEDOT/pull/267/commits/92c887721fba0b580d9cedccb72aa52dd210ec9c#diff-1921d538c9d8a97f9b0a018985fc9e8867d24de622a1b767b69411cc8d96d2e9).

2021-04-20 13:14 UTC, Dreamlone commented on examples/bad_knn_regression_example.py
> +    run_experiment()
Все примеры, как для временных рядов, так и для регрессии и классификации, перенесены в тесты. Разве что от примера с композером отказался, так как работает он относительно долго, но при этом ничего особенно не проверяет, так как есть уже его тест аналог [test_lagged_transformation_parameters_improving](https://github.com/nccr-itmo/FEDOT/pull/267/commits/92c887721fba0b580d9cedccb72aa52dd210ec9c#diff-1921d538c9d8a97f9b0a018985fc9e8867d24de622a1b767b69411cc8d96d2e9R23-R50), который контролирует, чтобы операция исправляла гиперпараметр корректно и позволяла цепочке обучаться

2021-04-20 13:15 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/knn.py
> +            warnings.warn(f"{prefix} from {n_neighbors} to {len(input_data.features)}")
Сделано, добавил такой логер как в [knn модели](https://github.com/nccr-itmo/FEDOT/pull/267/commits/92c887721fba0b580d9cedccb72aa52dd210ec9c#diff-5012cb03648ba08a546abef9e4bfa82fc96760d69724c05f5a7f653f8f698295), так и в [lagged implementation](https://github.com/nccr-itmo/FEDOT/pull/267/commits/92c887721fba0b580d9cedccb72aa52dd210ec9c#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412).

2021-04-20 13:16 UTC, Dreamlone commented on examples/ts_forecasting_composing_small_ts.py
> +                               with_visualisation=True)
Окс, все сделано, см. комментарии выше. Файлы из examples удалил

2021-04-20 15:34 UTC, nicl-nno approved these changes

2021-04-20 15:40 UTC, merged