deleted synthetic module, deleted test/integration/synthetic_generati…
nccr-itmo/FEDOT pull request #268
Opened 2021-04-16 14:50 UTC by Sash0check

- Deleted synthetic module
- Deleted test/integration/synthetic_generation/
- Moved synthetic/data.py one level up

2021-04-19 09:20 UTC, J3FALL requested changes

2021-04-19 09:20 UTC, J3FALL commented on docs/source/fedot/features.rst
>     features/sensitivity_analysis
Не уверен, что скрипт data.py в корневой папке utilities нормально попадет в документацию read_the_docs?
@BarabanovaIrina Ира, проконсультируй тут, плз.

2021-04-19 14:57 UTC, BarabanovaIrina commented on docs/source/fedot/features.rst
>     features/sensitivity_analysis
Если я правильно поняла, то ты хочешь, чтобы докстринги из data.py попали в документацию. 
(спойлер, их там и не было)

1. все, что касается докстрингов (т.е. то, что мы называем API к коду) описывается файлами в docs/source/api
Модуль synthetic мы не добавляли, потому что собирались его выпиливать. 
2. файлы, которые лежат в docs/source/fedot - описывают больше примеры/идеи/всякого рода пояснения к нашим модулям. Удалив features/synthetic - удаляешь вот этот [раздел](https://fedot.readthedocs.io/en/latest/fedot/features/synthetic.html). Т.е. данная строка(которую ты удалил) является ссылкой на документ synthetic.rst(docs/source/fedot/features/synthetic.rst), который лежит в папке features, которая лежит на одном уровне с редактируемым файлом(docs/source/fedot/features.rst). Это просто для понимания, как это работает. 

<img width="824" alt="Screenshot 2021-04-19 at 17 37 46" src="https://user-images.githubusercontent.com/29018907/115254785-5c133280-a136-11eb-90f5-d8b89f1cac60.png">

Я не знаю, какие планы насчет файла utilities/data.py, но я бы его как минимум переименовала, потому что из названия немного непонятно(в fedot.core есть data и тут data). А так [тут](https://fedot.readthedocs.io/en/latest/contribution.html#contribute-to-the-documentation) есть инструкция, как добавлять новые файлы с докстрингами кода.

2021-04-19 14:57 UTC, BarabanovaIrina commented on docs/source/fedot/features.rst
>     features/sensitivity_analysis
Кстати, нашла недочет в этой инструкции, поправь, пожалуйста, два момента(сама инструкция в docs/contribution.rst):
1. Добавь пункт 4 к списку шагов: Add your_name_for_file to the toctree at docs/source/api/index.rst
2. Замени core.your.first.script.path на fedot.core.your.first.script.path в описаниях автомодулей.

2021-04-20 11:36 UTC, J3FALL commented on docs/source/fedot/features.rst
>     features/sensitivity_analysis
Саша переименовал скрипт в более говорящее название.

2021-04-20 11:36 UTC, J3FALL approved these changes

2021-04-20 12:13 UTC, BarabanovaIrina commented
RTD плохо справился со вставкой между param полями

<img width="753" alt="Screenshot 2021-04-20 at 15 11 11" src="https://user-images.githubusercontent.com/29018907/115393720-a7871880-a1ea-11eb-9567-a8cb5bef5a02.png">

Нужно относящееся к одному полю описание разделять слешами
<img width="805" alt="Screenshot 2021-04-20 at 15 12 22" src="https://user-images.githubusercontent.com/29018907/115393852-d1403f80-a1ea-11eb-9da4-a004c6a58379.png">

2021-04-20 14:40 UTC, merged