Custom graph model optimization
nccr-itmo/FEDOT pull request #269
Opened 2021-04-16 20:41 UTC by nicl-nno

To achieve to applicability of the gp_optimizer to structural learning of bayesian networks, the following changes are implemented:

* added GraphObject - base class for Chain, as well as GraphNode/PrimaryGraphNode/SecondaryGraphNode
* structural DAG-related methods moved to GraphNode
* simplified example of custom model learning
* constraints customization implemented

Now gp_optimizer can be used for any graph-based optimization problems.

2021-04-16 20:41 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/chains/graph.py`](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py):

> [Line 90:13](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py#L90): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 90:42](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py#L90): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 91:43](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py#L91): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\/'
> [Line 92:15](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py#L92): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '
> [Line 92:44](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/chains/graph.py#L92): [W605](https://duckduckgo.com/?q=pep8%20W605) invalid escape sequence '\ '









* In the file [`fedot/core/composer/gp_composer/gp_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/composer/gp_composer/gp_composer.py):

> [Line 22:121](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/composer/gp_composer/gp_composer.py#L22): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)





* In the file [`fedot/core/composer/optimisers/gp_comp/operators/crossover.py`](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/composer/optimisers/gp_comp/operators/crossover.py):

> [Line 28:1](https://github.com/nccr-itmo/FEDOT/blob/8fd4c5a394008f7ab6ab651940bbd2b47fed9c38/fedot/core/composer/optimisers/gp_comp/operators/crossover.py#L28): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)

2021-04-29 12:07 UTC, BarabanovaIrina requested changes

2021-04-29 12:07 UTC, BarabanovaIrina commented on fedot/core/composer/composing_history.py
> +        try:
Если правильно поняла, то эта обертка как раз связана с той проблемой, что ты обозначил, что GraphObject не может быть добавлен в history. Это архитектурная какая-то проблема?

2021-04-29 12:28 UTC, nicl-nno commented on test/additional/test_profiler.py
> +import datetime
Сейчас unit-тесты прекращают выполняться, если не установлены зависимости к обоим профайлерам - что довольно неубодно. Поэтому как будто бы логичнее вынести такие тесты для доп. утилит отдельно..

2021-04-29 12:30 UTC, nicl-nno commented on fedot/core/chains/graph_operator.py
> +                    make_secondary_node_as_primary(node_child, type(node))
Потому что в ситуации, когда ты работаешь именно с Chain, у тебя тут должен создаться экземпляр PrimaryNode, а не PrimaryGraphNode.

2021-04-29 12:31 UTC, nicl-nno commented on fedot/core/composer/composing_history.py
> +        try:
Сейчас сохранение истории работает через ChainTemplate, а он реализуется часть полей, специфичных именно для Chain, а не для Graph (например, сохранение обученной модели)

2021-04-29 13:19 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +    node_types = {'Tectonic regime': 'disc',
В качестве примера тут взята задача структурного обучения баесовской сети:

![image](https://user-images.githubusercontent.com/5711814/116551522-b19eca80-a900-11eb-8524-3a4dbbb15dcf.png)

В её рамках в каждом узле не модель, а название переменной из датасета. Т.е. методов fit и predict у узлов нет, метрика вычисляется иным способом. Также несколько иные требования к валидации.

Поэтому чтобы это (и другие схожие задачи, тот же NAS) могли нативно решаться, нужно:
а) обеспечить возможность работать с графом из произвольных узлов (не только ML-моделей)
б) обеспечить передачу кастомной метрики для оценки качества графа
в) обеспечить возможность передачи набора кастомных правил для валидации структуры.

2021-04-29 14:02 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +            node.unfit()
Да, это ошибка. Перенес все fit-related методы в Chain.

2021-04-29 14:02 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +    data = pd.read_csv(f'{project_root()}\\examples\\data\\geo_encoded.csv')
Fixed

2021-04-29 14:02 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +    def fit_from_cache(self, cache):
Переместил.

2021-04-29 14:03 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +            cached_state = cache.get(node)
Сейчас класс с кэшем называется OperationsCache. [Уточнил](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR169) в аннотации, плюс убрал терминологический конфликт с fitted_operation.

2021-04-29 14:03 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +        if (node_types[str(labels[pair[1]])] == 'disc') & (node_types[str(labels[pair[0]])] == 'cont'):
В целом можно, но т.к. суть не в этой проверке, то заменил эту функцию на более простую - [_has_no_duplicates](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR169).

2021-04-29 14:03 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +    rules = [has_no_self_cycled_nodes, _has_no_cycle, _has_disc_parents]
Изменил в части функций в chain_validation тип данных с Chain на GraphObject. Убрал кастомный _has_no_cycle из примера.

2021-04-29 15:21 UTC, BarabanovaIrina commented on examples/bayesian_network_as_custom_task.py
> +    data = pd.read_csv(f'{project_root()}\\examples\\data\\geo_encoded.csv')
Еще немного занудства. Можно вот так os.path.join(project_root(), 'examples', 'data', 'geo_encoded.csv'))

2021-04-29 16:32 UTC, BarabanovaIrina requested changes

2021-04-29 16:32 UTC, BarabanovaIrina commented on fedot/core/chains/graph_node.py
> +    def __init__(self, nodes_from: Optional[List['GraphNode']],
Добавь, пожалуйста, docstring и наверное нужно в RTD это добавить.

2021-04-29 16:32 UTC, BarabanovaIrina commented on fedot/core/chains/graph.py
> +        ChainVisualiser().visualise(self, path)
Может это тогда тоже станет GraphVisualiser? он вроде полностью основан на nx.

2021-04-29 16:32 UTC, BarabanovaIrina commented on fedot/core/chains/graph.py
> +class GraphObject:
Наверное можно вынести скрипты с GraphObject и NodeObject из chains модуля.

2021-04-29 16:41 UTC, BarabanovaIrina commented on test/additional/test_profiler.py
> +import datetime
Просто профайлеры находятся в fedot, по которому собирается покрытие. Сейчас в пайплайне добавлены строки с установкой нужных пактов. Нужно либо в [CI-pipeline](https://github.com/nccr-itmo/FEDOT/blob/master/.github/workflows/unit-build.yml#L38) тогда прописать pytest --cov=fedot -s test/unit test/additional, либо выносить их из fedot. 
Но если идея в том, что мы все таки предоставляем этот функционал конечному пользователю - то тогда нужно поправить CI.

2021-04-29 16:55 UTC, BarabanovaIrina commented on examples/bayesian_network_as_custom_task.py
> +    rules = [has_no_self_cycled_nodes, _has_no_cycle, _has_disc_parents]
Нужно будет подумать, как валидацию объединить, а то там нарастает. При условии, что в большинство передается chain объект или graph, возможно будет смысл сделать, например, Validator.validate()- запустит базовые проверки структуры и Validator.custom_validate([list of necessary validation functions]) - запустит только необходимые. Но это просто на будущее.

2021-04-29 20:25 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +    rules = [has_no_self_cycled_nodes, _has_no_cycle, _has_disc_parents]
Указал в #37

2021-04-29 20:54 UTC, nicl-nno commented on test/additional/test_profiler.py
> +import datetime
Чтобы не плодить виды тестов - пока перенес additional в integration, там как раз есть тесты с кастомными req.txt

2021-04-29 20:54 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +    data = pd.read_csv(f'{project_root()}\\examples\\data\\geo_encoded.csv')
Done

2021-04-29 20:54 UTC, nicl-nno commented on examples/bayesian_network_as_custom_task.py
> +        list_of_nodes.append(str(node))
Done

2021-04-29 20:54 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +        fitted yet)
Убрал

2021-04-29 20:55 UTC, nicl-nno commented on fedot/core/chains/graph_node.py
> +    def __init__(self, nodes_from: Optional[List['GraphNode']],
Добавил здесь и в соседних классах.

>наверное нужно в RTD это добавить

Ты про [это](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-0b10a4ca82e92505c5628ba226dd6ac339a75f4b7fa52bedbe2e6eaa94f2634aR1-R10)?

2021-04-29 20:56 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +        ChainVisualiser().visualise(self, path)
Разделил [GraphVisualiser](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-7db9dda60b06a09eb58a8bf574485ff53a3f0678a531348070a4a64024540028R24) и ChainVisualiser (хотя второй тоже нуждается в рефакторинге, конечно).

2021-04-29 20:56 UTC, nicl-nno commented on fedot/core/chains/graph.py
> +class GraphObject:
Вынес в core.graphs

2021-04-30 08:15 UTC, BarabanovaIrina commented on fedot/core/chains/graph_node.py
> +    def __init__(self, nodes_from: Optional[List['GraphNode']],
Да, не увидела. 
Только нужно немного поправить. B Node.rst и GraphNode.rst ссылка на chains.node
<img width="856" alt="Screenshot 2021-04-30 at 11 10 33" src="https://user-images.githubusercontent.com/29018907/116667281-b0bf7480-a9a4-11eb-8dca-5d1c6f069044.png">

<img width="970" alt="Screenshot 2021-04-30 at 11 13 48" src="https://user-images.githubusercontent.com/29018907/116667756-36432480-a9a5-11eb-907f-6b838828936d.png">


И в index добавить новые файлы
<img width="778" alt="Screenshot 2021-04-30 at 11 12 48" src="https://user-images.githubusercontent.com/29018907/116667565-03009580-a9a5-11eb-8426-23a46b03eba7.png">

2021-04-30 08:43 UTC, BarabanovaIrina commented
А еще можно, пожалуйста, для кеша(если это он) выделить отдельную папку внутри дефолтной, а то неудобно потом среди множества свои файлы искать. 
<img width="259" alt="Screenshot 2021-04-15 at 11 03 27" src="https://user-images.githubusercontent.com/29018907/116671154-478e3000-a9a9-11eb-9535-9bcdb04ddc8b.png">

2021-04-30 17:34 UTC, BarabanovaIrina requested changes

2021-04-30 17:34 UTC, BarabanovaIrina commented on docs/source/api/graph_node.rst
> +.. automodule:: fedot.core.graphs.graph_node
Только еще заголовки местами поменять

2021-05-11 09:54 UTC, nicl-nno commented on docs/source/api/graph_node.rst
> +.. automodule:: fedot.core.graphs.graph_node
Done

2021-05-13 09:00 UTC, BarabanovaIrina approved these changes

2021-06-03 11:25 UTC, nicl-nno commented
Moved to #324

2021-06-03 11:25 UTC, closed without merging