Evolutionary operators saving to composing history
nccr-itmo/FEDOT pull request #271
Opened 2021-04-19 15:43 UTC by nicl-nno

ParentOperator class is added in order to preserve the full history of each individual. 
Now each individual has the parent_operators field that is exporting to the history.

It is required for the compability with future evolutionary vizualization in FEDOT.Web.

2021-04-29 11:59 UTC, J3FALL requested changes

2021-04-29 11:59 UTC, J3FALL commented on fedot/core/composer/composing_history.py
> +    parent_chains: List[ChainTemplate]
Тоже не помешали бы иллюстративные тесты на эту штуку.

2021-04-29 11:59 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +                chain.parent_operators = []
Хм, а есть какие-нибудь идеи, как можно избежать такого присваивания дополнительных полей в объект Chain?
Мне не очень нравится, что здесь смешиваются немного разные абстракции.

2021-04-29 11:59 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +                chain.parent_operators = []
Ну и по-факту в конструкторе Chain такого поля нет.

2021-04-29 11:59 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/operators/selection.py
> +        return selected
В общем, не хватает какого-то примера, как в конечном виде будет выглядеть история композирования с этой новой штукой.
Можно, например, за-mock-ать работу композера и вручную прописать, какие операции в нем будут совершены. Он вернет нужную историю, а в тесте уже сопроводить ее необходимыми assert-ами.

2021-04-29 11:59 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +                chain.parent_operators = []
Может, как-то через callback-и это можно провернуть?
Создавать историю gp-операций во внешнем объекте History, главное - вызывать этот callback параметрами, по аналогии с ParentOperator

2021-04-29 15:55 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +                chain.parent_operators = []
>Хм, а есть какие-нибудь идеи, как можно избежать такого присваивания дополнительных полей в объект Chain?

Cходу приходят в голову варианты с 
1) Создание класса Individual, в рамках которых будут содержаться parent_operators, fitness
2) Реализацией в рамках Chain словаря metadata с аналогичным назначение.

Посмотрю, можно ли адекватно реализовать первый.

>Может, как-то через callback-и это можно провернуть?

Можно, но это надо будет во всех ген. операторы проборасывать функцию callback-а - не оч. удобно. Ну и с атрибутом fitness такая же проблема, на самом деле.

2021-04-29 15:55 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        return result
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/271/files#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8dR421-R430)

2021-04-29 15:56 UTC, nicl-nno commented on fedot/core/composer/composing_history.py
> +    parent_chains: List[ChainTemplate]
Добавил [такой](https://github.com/nccr-itmo/FEDOT/pull/271/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R12-R21)

2021-04-29 15:56 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/selection.py
> +        return selected
Не придумал сходу, как удобно замокать, поэтому сделал [такой](https://github.com/nccr-itmo/FEDOT/pull/271/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R24-R45) тест, проверяющий основные аспекты.

2021-05-17 11:29 UTC, J3FALL approved these changes

2021-05-17 12:09 UTC, merged