Added exception for lack of openpyxl library
nccr-itmo/FEDOT pull request #272
Opened 2021-04-20 16:53 UTC by Sash0check

2021-04-21 09:28 UTC, Dreamlone approved these changes
Все в точности как описывал Коля в issue, это действительно позволит избежать излишнего усложнения в requirements.txt - approve 

Только добавь пожалуйста хотя бы коротенькое описание в PR, можно одним предложением зачем это было сделано.

2021-04-21 09:32 UTC, J3FALL requested changes

2021-04-21 09:32 UTC, J3FALL commented on examples/multiclass_prediction.py
> +    raise (ImportError, "<openpyxl> is not installed on your system. It is required to run this example.")
Можно еще упростить:
![image](https://user-images.githubusercontent.com/7864250/115531623-acf16b00-a29d-11eb-8ad1-2742ed34cfb7.png)

2021-04-22 11:36 UTC, J3FALL approved these changes

2021-04-22 11:37 UTC, merged