Graph operations extraction
nccr-itmo/FEDOT pull request #278
Opened 2021-04-22 13:49 UTC by BarabanovaIrina

New GraphOperations class, which contains all the operations with graph structure. 
- Chain still has base methods for add, delete, update nodes available, but implementation is moved.
- Methods from gp_operators.py is in GraphOperations also.(except nodes_from_height())

2021-04-22 13:49 UTC, pep8speaks commented
Hello @BarabanovaIrina! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`fedot/core/composer/optimisers/gp_comp/operators/crossover.py`](https://github.com/nccr-itmo/FEDOT/blob/50481cd3908b599565084b489a55d9ae5fb2e154/fedot/core/composer/optimisers/gp_comp/operators/crossover.py):

> [Line 76:32](https://github.com/nccr-itmo/FEDOT/blob/50481cd3908b599565084b489a55d9ae5fb2e154/fedot/core/composer/optimisers/gp_comp/operators/crossover.py#L76): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 79:33](https://github.com/nccr-itmo/FEDOT/blob/50481cd3908b599565084b489a55d9ae5fb2e154/fedot/core/composer/optimisers/gp_comp/operators/crossover.py#L79): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

* In the file [`fedot/core/composer/optimisers/gp_comp/operators/mutation.py`](https://github.com/nccr-itmo/FEDOT/blob/50481cd3908b599565084b489a55d9ae5fb2e154/fedot/core/composer/optimisers/gp_comp/operators/mutation.py):

> [Line 117:121](https://github.com/nccr-itmo/FEDOT/blob/50481cd3908b599565084b489a55d9ae5fb2e154/fedot/core/composer/optimisers/gp_comp/operators/mutation.py#L117): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)

2021-04-22 13:54 UTC, BarabanovaIrina commented
Возникли следующие вопросы: 
- некоторые методы вроде node_depth могут вычисляться независимо от цепочек. И иногда получается вот такой громоздкий код. Насколько резонно так поступать?
<img width="857" alt="Screenshot 2021-04-22 at 16 51 53" src="https://user-images.githubusercontent.com/29018907/115726061-0e433800-a38b-11eb-82d8-ee0e3d1f57e7.png">

2021-04-22 14:08 UTC, nicl-nno requested changes

2021-04-22 14:08 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/gp_operators.py
>  def nodes_from_height(chain: Any, selected_height: int) -> List[Any]:
Может этот метод тоже вынести?

2021-04-22 14:08 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
>некоторые методы вроде node_depth могут вычисляться независимо от цепочек. И иногда получается вот такой громоздкий код. Насколько резонно так поступать?

А нет смысла реализовать NodeOperations для таких методов? В контруктор принимая соответственно node.

2021-04-22 14:08 UTC, nicl-nno commented on fedot/core/chains/chain_validation.py
> +    has_no_multiple_children(chain)
Как обсуждали - не вижу в multiple children ничего плохого. 
Это некорректно для деревьев, но у нас цепочки не обязательно древовидны.

2021-04-22 14:08 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +    def update_node(self, old_node: Node, new_node: Node, include_parents=False):
А есть ли необходимость в такой обертке? 
Явный вызов update_subtree/update_node выглядит более понятно, чем флаг include_parents.

Аналогично для delete_node.

2021-04-22 14:08 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        self.operations = GraphOperations(self)
Тут пересечение по терминологии с operations в узлах. 
Можно, назвать actions или как-то так?

2021-04-25 08:38 UTC, BarabanovaIrina commented on fedot/core/composer/optimisers/gp_comp/gp_operators.py
>  def nodes_from_height(chain: Any, selected_height: int) -> List[Any]:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/278/files#diff-4766c617a51f344e8c8323c85c4b34fc462400876d95e9eea82369d3cec7365aR116-R128)

2021-04-25 08:55 UTC, BarabanovaIrina commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
Возможно, но хотелось бы наверное иметь единое место, которое содержит операции над графом. 
 
Вообще, т.к. в задаче стоит проверка базовых алгоритмов над графами, то у меня была идея сначала действительно реализовать такой "интерфейс" на уровне Node, потому как по идее нужно использовать только те связи, которые даны (в нашем случае это связи от детей к родителям в одном направлении). Тогда бы всякие поиски дистанций и нод осуществлялись от корневой ноды до необходимой(говоря о задачах node_height, nodes_from_height) Выходит, что Chain мы используем тогда, когда нам нужно вычислить т.н. обратные связи от родителей к детям, потому что у нас есть список всех нод в chain.nodes. Так мы упрощаем себе какие-то запросы, и, надо признать, такой способ работает быстрее чем те попытки вычисления от корня, которые я описала(говорю о тех реализациях, что я пробовала). 

Проблема в том, что основные алгоритмы поиска расстояния (или определения уровня в нашем случае) рассмотрены либо для взвешенных графов либо для бинарных, которые имеют свою особенность реализации и прохода по дереву(ну либо я не все прочитала). Я бы хотела реализовать это все на уровне Node, т.к. это кажется более логичным, но это потеря производительности. 

А в идее с разделением основная мысль в том, что операции которые идут от ноды к primary узлам - будут в NodeOperations, а от ноды к корню - ChainOperations.

2021-04-25 09:15 UTC, BarabanovaIrina commented on fedot/core/chains/chain_validation.py
> +    has_no_multiple_children(chain)
SA сломается на таком моменте, если передать цепочку у которой более 2 родителей и более 2 детей, потому как там не итеративное удаление, а удаление одной ноды за раз. Получается, тогда нужно будет ограничить SA: нельзя удалять корневые ноды(это уже есть) и нельзя удалять вот такие ноды. Насколько тогда будет объективным оценка вклада данной ноды?

2021-04-25 11:35 UTC, nicl-nno commented on fedot/core/chains/chain_validation.py
> +    has_no_multiple_children(chain)
В целом, думаю вполне норм иметь "неудаляемые" ноды в рамках SA.
Можно даже без явных ограничений обойтись, а просто проверять валидность Chain после удаления. Если она невалидна, то пропускать ноду для оценки.

2021-04-25 11:54 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
>потеря производительности.

А она действительно значимая для графов более-менее реалистичного размера?

Алгоритмически хорошо бы конечно поддерживать произвольный DAG, но пока вроде достаточно разложить операции над графами по классам, не вдавясь именно в эффективность внутреннюю реализацию. 

>А в идее с разделением основная мысль в том, что операции которые идут от ноды к primary узлам - будут в NodeOperations, а от ноды к корню - ChainOperations.

Да, при этом выглядит логичным в ChainOperations максимально ссылаться на NodeOperations, чтобы избежать дублирования.

2021-04-25 13:03 UTC, BarabanovaIrina commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
> А она действительно значимая для графов более-менее реалистичного размера?

На порядок. Для цепочки из 8 нод - 4 уровня(корень-2 ноды-4-ноды-1нода) найти например ноду с 3 уровня: старым способом - 0.00003, через корень - 0.00038.

>логичным в ChainOperations максимально ссылаться на NodeOperations, чтобы избежать дублирования

ок

2021-04-25 13:11 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
>старым способом - 0.00003, через корень - 0.00038

Ну если это в секундах, то выглядит норм и так, и так. Если конечно нет какого-то драматичного роста сложности для больших графов.

2021-04-26 10:11 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +    def update_node(self, old_node: Node, new_node: Node, include_parents=False):
Исправлено для [update](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR228-R235) и для [delete](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR246-R252)

2021-04-26 10:12 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +        self.operations = GraphOperations(self)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbL37-R37)

2021-04-26 10:13 UTC, BarabanovaIrina commented on fedot/core/chains/chain_validation.py
> +    has_no_multiple_children(chain)
Валидация [убрана](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-218db4373eb9ac8418056e00df5a0c079969ec0abb02a94d8a40a50865d60c5fL188-L198)

2021-04-26 10:44 UTC, BarabanovaIrina commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
Выделены [ChainActionInterface](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-4766c617a51f344e8c8323c85c4b34fc462400876d95e9eea82369d3cec7365aL7-R7) и [NodeActionInterface](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-99da22e4af4bdee208d4b2a7baf6752c305ec9cbce2d4fdab2e79fce002767fbR4-R23)

Для Node сделала сокрытие делегирования, чтобы в том случае, когда нет цепочки (например, как в [данной функции](https://github.com/nccr-itmo/FEDOT/pull/278/commits/a5a3c1efd98859a9a30173ec0989a180f1e0a472#diff-817c9bfcb98debd82ead59e1080d790eeea13d0c61d80ace11a3c8c2aba2819bL44-R42)) можно было вызывать необходимые методы от объекта Node, а не стат метод от ChainActionsInterface. Алсо, исправила нейминг, потому что судя по описанию метода он может использоваться не только с корневыми нодами. 

Просто теперь нужно помнить, какие методы можно вызывать напрямую от Node, какие от Chain.actions.

2021-04-26 10:50 UTC, BarabanovaIrina commented
Но я все еще думала насчет твоей идеи с [GraphObject](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-cf196b8cdf9ebfd9018ce966a4a002963d3584e49ad2933826954c57acec4827), почитала про замену делегирования наследованием и наоборот, и вот какие аргументы для себя выяснила: 
Если делать через наследование, то в случае, если мы создаем не древовидны граф, а другой, то возможно у нас уже не получится использовать те же методы удаления, замены поддеревьев из предка, потому что они могут иметь свою специфику. В таком случае, вероятно, все общие методы объявятся абстрактными, а реализация спустится до конкретного объекта. 
Если делать через композицию, в случае недревовидного графа мы сможем подставить другой класс делегат, который будет реализовывать методы по-своему, но при этом в Chain можно ничего не менять кроме определения поля класса делегата (Chain.actions) в данном случае. 
Но это мои рассуждения вслух.

2021-04-26 10:54 UTC, nicl-nno commented
> Но я все еще думала насчет твоей идеи с [GraphObject](https://github.com/nccr-itmo/FEDOT/pull/269/files#diff-cf196b8cdf9ebfd9018ce966a4a002963d3584e49ad2933826954c57acec4827), почитала про замену делегирования наследованием и наоборот, и вот какие аргументы для себя выяснила:
> Если делать через наследование, то в случае, если мы создаем не древовидны граф, а другой, то возможно у нас уже не получится использовать те же методы удаления, замены поддеревьев из предка, потому что они могут иметь свою специфику. В таком случае, вероятно, все общие методы объявятся абстрактными, а реализация спустится до конкретного объекта.
> Если делать через композицию, в случае недревовидного графа мы сможем подставить другой класс делегат, который будет реализовывать методы по-своему, но при этом в Chain можно ничего не менять кроме определения поля класса делегата (Chain.actions в данном случае).
> Но это мои рассуждения вслух.

Ну да, это можно пропробовать реализовать как последовательность классов Chain - ChainGraph (у которого есть обязательная root_node) - GraphObject, у каждого из которых можно переопределить actions.

2021-04-26 10:55 UTC, nicl-nno commented on fedot/core/chains/node.py
> +    def distance_to_primary_level(self):
А нет смысла это как propery реализовать?

2021-04-26 11:18 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        mutation_prob = mutation_strength / (GraphOperations().distance_to_leaf_level(root_node) + 1)
Мне кажется пока норм, дальше при реализации примеров с не-Chain в качестве объекта оптимизации можно будет вернуться и проверить, что всё норм ложится в идею.

2021-04-26 11:18 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/116074341-4489fb80-a69a-11eb-8a05-883981283d9e.png)

Ну и вот это ещё.

2021-04-26 11:19 UTC, BarabanovaIrina commented on fedot/core/chains/node.py
> +    def distance_to_primary_level(self):
Ну при условии, что property ведут себя под капотом как функции, а какая-либо валидация значения тут не производится (и setter не нужен), то лично я не вижу смысла.

2021-04-26 11:26 UTC, nicl-nno commented on fedot/core/chains/node.py
> +    def distance_to_primary_level(self):
"next_node.distance_to_primary_level()"
Мне кажется без скобочек такая нотация выглядит изящней, и при этом понятней в том плане, что за ней не стоит какое-то действие, изменяющее состояние.

Вроде best practives примерно из такой логики и исходят:
"Prefer properties/getters when you are conceptually accessing a property of the object, and not telling the object to do some work"

https://softwareengineering.stackexchange.com/questions/367161/when-is-it-not-pythonic-to-use-properties-instead-of-a-method-that-doesnt-take

2021-04-26 11:36 UTC, BarabanovaIrina commented on fedot/core/chains/node.py
> +    def distance_to_primary_level(self):
Ок, согласна. [Исправлено](https://github.com/nccr-itmo/FEDOT/pull/278/commits/2dd4a08294f41df2d7e67e706fdd969a77a175d7#diff-2739bda85c4dab8cb5fb7dbda40088c8617212b3542690798f101f140f09df00R115)

2021-04-26 11:44 UTC, BarabanovaIrina commented
> ![image](https://user-images.githubusercontent.com/5711814/116074341-4489fb80-a69a-11eb-8a05-883981283d9e.png)
> 
> Ну и вот это ещё.

Исправлено
<img width="840" alt="Screenshot 2021-04-26 at 14 43 25" src="https://user-images.githubusercontent.com/29018907/116077150-d2b3b100-a69d-11eb-9d40-4cfb4c3b84a2.png">

2021-04-26 12:05 UTC, nicl-nno approved these changes

2021-04-26 12:12 UTC, J3FALL requested changes

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
1. Не совсем понятно, почему именно actions, хотя это не совокупность объектов, а один объект.
2. ChainAction, на мой взгляд, не очень понятный нейминг. К экшенам я могу отнести практически любую операцию )
Мне кажется, чуть лучше и понятнее, например, взять название ChainModifyInterface/ChainModifier.

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/chains/chain_operation.py
> +class ChainActionInterface:
Имхо, стоит частично либо продублировать тесты на операции для этого класса, либо что-то перенести из Chain-related тестов.
Это пригодится не только для банального повышения покрытия, но и повысить шансы в ситуации, когда сломался либо Chain, либо ChainActionInterface, и при помощи тестов мы сможем это определить.

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/chains/node.py
> +        return NodeActionInterface(self).ordered_subnodes_hierarchy(visited)
хм, а есть смысл ввести поле в Node, по аналогии с Chain?
ну, чтобы не создавать каждый раз новый объект NodeActionInterface при вызове функции.
Или я тут поверхностно понимаю логику кода

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/chains/node_operation.py
> +class NodeActionInterface:
Ну, для этого класса те же предложения по правкам, что и для ChainActionInterface - тесты, нейминг.

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/gp_operators.py
> -        return 1 + max([node_depth(next_node) for next_node in node.nodes_from])
Эта функция дублировала какую-то другую?
Или она не использовалась?

2021-04-26 12:12 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/gp_operators.py
> -        return 1 + max([node_depth(next_node) for next_node in node.nodes_from])
Видимо, distance_to_primary_level из Node.

2021-04-26 12:16 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
Может тогда StucturalModifier? Тут вроде привязки именно к Chain нет, только к лежащему в основе графу.

2021-04-26 12:17 UTC, BarabanovaIrina commented on fedot/core/composer/optimisers/gp_comp/gp_operators.py
> -        return 1 + max([node_depth(next_node) for next_node in node.nodes_from])
Она не дублировала, она была отдельно и Коля [предложил](https://github.com/nccr-itmo/FEDOT/issues/241#issuecomment-799526838) добавить их к подобным операциям. distance_to_primary_level это уже производная от нее.

2021-04-26 12:17 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
Ну или просто StructureModifier

2021-04-26 13:46 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
А почему мы не храним обратные связи, которые сейчас достаем при помощи node_children() также как храним nodes_from?

2021-04-26 13:50 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
А зачем их хранить, если можно каждый раз высчитывать заново? Так придется вручную следить за актуальностью обоих полей.

2021-04-26 14:09 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
Я все думаю, что node.distance_to_primary_level и node.distance_to_root_level это одна и та же операция только в разные стороны. Мне не нравится, что одна вызывается от объекта Node, а другая от Chain. 
Но сейчас поняла, что может тогда сделать что-то типа node.distance_to_root_level(within_chain=chain)(то есть в рамках какой цепочки искать) и использовать все тот же интерфейс, который уже есть. И так же с nodes_from_height. То есть поменять точку входа.

2021-04-27 14:41 UTC, BarabanovaIrina commented on fedot/core/chains/chain.py
> +        self.actions = ChainActionInterface(self)
Предыдущую идею не удалось реализовать в силу особенностей архитектуры. 
Переименован в [GraphOperator](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664dbR37) c поле chain.operator, потому как там не только операции по модификации цепочки, но и прочие вспомогательные, которые не модифицируют цепочку, а получают какую-то информацию из нее.

2021-04-27 14:44 UTC, BarabanovaIrina commented on fedot/core/chains/chain_operation.py
> +class ChainActionInterface:
Добавлены [тесты](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-8f8632a520caa36f4aec29d6ab723074c6fb33c2e683c37469bda5d289c1d934) на методы GraphOperator, которые не связаны с модификацией. 
Тесты на модифицирующие методы остались в [test_chain](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8d).

2021-04-27 14:45 UTC, BarabanovaIrina commented on fedot/core/chains/node.py
> +        return NodeActionInterface(self).ordered_subnodes_hierarchy(visited)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-2739bda85c4dab8cb5fb7dbda40088c8617212b3542690798f101f140f09df00R27)

2021-04-27 14:47 UTC, BarabanovaIrina commented on fedot/core/chains/node_operation.py
> +class NodeActionInterface:
[Переименован](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-9e470f06b0095a5b74a7d4703c482d814098c34a11f3c46a2bb1ddfc021d58e5)
Добавлены [тесты](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-3c8067d82f4f82e015947e88deda95b8d191d3baa2ec42942c38e11cd26c2426) на методы Node и [тесты](https://github.com/nccr-itmo/FEDOT/pull/278/commits/b1f8043d2f35288d2b69ca0ac8e88cce79e328a0#diff-f96d11325af34e8b523075b96e438b234095e8afda11f2dfd5696a37e920c868) на методы NodeOperator.

2021-04-28 11:15 UTC, J3FALL approved these changes

2021-04-28 12:46 UTC, merged