230 profiler time memory
nccr-itmo/FEDOT pull request #286
Opened 2021-04-26 08:50 UTC by MAGLeb

Создан класс для профилирования кода по памяти и по времени. 
Легкий интерфейс дает возможность в пару строчек получить ценные результаты:
1. профайлер по времени:
- граф вызовов с кумулятивным временем вызовы функции (сохраняется в формате png)
- веб интерфейс для детального рассмотрения стека вызовов
2. профайлер по памяти:
- граф вызовов с выделением цветом объектов FEDOT'a (сохраняется в формате png)
- график зависимости памяти от времени (сохраняется в формате png)

Создан пример с использованием класса для профилирования.
Обращаю внимание, классы для памяти и времени имеют разный интерфейс.

Дополнительные библиотеки для разработки:
snakeviz==2.1.0
gprof2dot==2021.2.21
objgraph==3.5.0

2021-04-26 09:32 UTC, nicl-nno commented on fedot/utilities/profiler/profiler.py
> +from memory_profiler import memory_usage
А откуда memory_profiler должен браться?

Мб это оно - https://pypi.org/project/memory-profiler/ ?

2021-04-26 09:32 UTC, nicl-nno commented on requirements.txt
> +snakeviz==2.1.0
Можно их положить в отдельные profiler_requirements в каталог profiler? 
И добавить проверку на установленность (по аналогии с той, что для экселя делали).

2021-04-26 09:54 UTC, MAGLeb commented on requirements.txt
> +snakeviz==2.1.0
Где можно посмотреть подобную работу по экселю?

2021-04-26 10:09 UTC, MAGLeb commented on fedot/utilities/profiler/profiler.py
> +from memory_profiler import memory_usage
Добавил пакет.

2021-04-26 10:14 UTC, nicl-nno commented on requirements.txt
> +snakeviz==2.1.0
https://github.com/nccr-itmo/FEDOT/pull/272

2021-04-26 10:21 UTC, nicl-nno commented on examples/fedot_profiler_example.py
> +    # profiler = MemoryProfiler(run_credit_scoring_problem, path=path, roots=run_credit_scoring_problem, max_depth=8)
Если раскомментировать эти строки, то падает ошибка

Traceback (most recent call last):
  File "D:\THEODOR\venv37\lib\site-packages\seaborn\palettes.py", line 232, in color_palette
    palette = mpl_palette(palette, n_colors)
  File "D:\THEODOR\venv37\lib\site-packages\seaborn\palettes.py", line 456, in mpl_palette
    cmap = mpl.cm.get_cmap(name)
  File "D:\THEODOR\venv37\lib\site-packages\matplotlib\cm.py", line 182, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
ValueError: Colormap flare is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r, Dark2, Dark2_r, GnBu, GnBu_r, Greens, Greens_r, Greys, Greys_r, OrRd, OrRd_r, Oranges, Oranges_r, PRGn, PRGn_r, Paired, Paired_r, Pastel1, Pastel1_r, Pastel2, Pastel2_r, PiYG, PiYG_r, PuBu, PuBuGn, PuBuGn_r, PuBu_r, PuOr, PuOr_r, PuRd, PuRd_r, Purples, Purples_r, RdBu, RdBu_r, RdGy, RdGy_r, RdPu, RdPu_r, RdYlBu, RdYlBu_r, RdYlGn, RdYlGn_r, Reds, Reds_r, Set1, Set1_r, Set2, Set2_r, Set3, Set3_r, Spectral, Spectral_r, Wistia, Wistia_r, YlGn, YlGnBu, YlGnBu_r, YlGn_r, YlOrBr, YlOrBr_r, YlOrRd, YlOrRd_r, afmhot, afmhot_r, autumn, autumn_r, binary, binary_r, bone, bone_r, brg, brg_r, bwr, bwr_r, cividis, cividis_r, cool, cool_r, coolwarm, coolwarm_r, copper, copper_r, cubehelix, cubehelix_r, flag, flag_r, gist_earth, gist_earth_r, gist_gray, gist_gray_r, gist_heat, gist_heat_r, gist_ncar, gist_ncar_r, gist_rainbow, gist_rainbow_r, gist_stern, gist_stern_r, gist_yarg, gist_yarg_r, gnuplot, gnuplot2, gnuplot2_r, gnuplot_r, gray, gray_r, hot, hot_r, hsv, hsv_r, icefire, icefire_r, inferno, inferno_r, jet, jet_r, magma, magma_r, mako, mako_r, nipy_spectral, nipy_spectral_r, ocean, ocean_r, pink, pink_r, plasma, plasma_r, prism, prism_r, rainbow, rainbow_r, rocket, rocket_r, seismic, seismic_r, spring, spring_r, summer, summer_r, tab10, tab10_r, tab20, tab20_r, tab20b, tab20b_r, tab20c, tab20c_r, terrain, terrain_r, twilight, twilight_r, twilight_shifted, twilight_shifted_r, viridis, viridis_r, vlag, vlag_r, winter, winter_r

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/THEODOR/examples/fedot_profiler_example.py", line 68, in <module>
    profiler = MemoryProfiler(run_credit_scoring_problem, path=path, roots=run_credit_scoring_problem, max_depth=8)
  File "D:\THEODOR\fedot\utilities\profiler\profiler.py", line 89, in __init__
    self._create_memory_plot(function, args, kwargs)
  File "D:\THEODOR\fedot\utilities\profiler\profiler.py", line 108, in _create_memory_plot
    sns.set_palette("flare", color_codes=True)
  File "D:\THEODOR\venv37\lib\site-packages\seaborn\rcmod.py", line 539, in set_palette
    colors = palettes.color_palette(palette, n_colors, desat)
  File "D:\THEODOR\venv37\lib\site-packages\seaborn\palettes.py", line 234, in color_palette
    raise ValueError("%s is not a valid palette name" % palette)
ValueError: flare is not a valid palette name

2021-04-26 10:42 UTC, nicl-nno commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
А нужно ли дублировать эту функцию, если тут нет никакой профайлерной специфики? Мб проще импортировать откуда-то.

2021-04-26 11:26 UTC, MAGLeb commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Сделал новую упрощенную функцию, чтобы обучался композер не 20 поколейний и долго не пришлось ждать результатов. Могу сделать иморт. Жду ответа.

2021-04-26 11:36 UTC, nicl-nno commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Так у функции же есть параметр max_lead_time.

2021-04-26 11:36 UTC, MAGLeb commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Могу вынести функцию в utils, и сделать её более гибкой.

2021-04-26 11:41 UTC, J3FALL requested changes

2021-04-26 11:41 UTC, J3FALL commented on fedot/utilities/profiler/profiler.py
> +import cProfile
Я бы разбил MemoryProfiler и TimeProfiler на два отдельных скрипта.
Если есть общие функции, то можно сделать третий скрипт - common.py

2021-04-26 11:41 UTC, J3FALL commented on fedot/utilities/profiler/profiler.py
> +class TimeProfiler:
Для двух новых классов не хватает тестов, хотя бы базовых на проверку того, что результаты профилирования генерируются и сохраняются

2021-04-26 11:41 UTC, J3FALL commented on fedot/utilities/profiler/profiler.py
> +class MemoryProfiler:
Еще, кстати, нужно проверить, что новый модуль profiler попадет в автодокументацию в read_the_docs.
Если есть вопросы, как это можно пофиксить/проверить, спроси Иру Б. или Сашу А. @BarabanovaIrina @Sash0check

2021-04-26 11:47 UTC, BarabanovaIrina commented on fedot/utilities/profiler/profiler.py
> +class MemoryProfiler:
Активировала [ветку](https://readthedocs.org/projects/fedot/) для сборки в rtd.

2021-04-26 12:05 UTC, nicl-nno commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Да вроде исходной функции из cases вполне хватает гибкости.

Как альтернативу, можно из fedot_api_examples взять какой-то из примеров, они тоже быстро выполняются и при этом без лишних параметров.

2021-04-26 14:27 UTC, BarabanovaIrina requested changes

2021-04-26 14:27 UTC, BarabanovaIrina commented on .github/workflows/unit-build.yml
> +	pip isntall -r fedot/utilities/profiler/requirements_memory_profiler.txt
Судя по всему из-за неправильного отступа не запускаются тесты

2021-04-26 14:28 UTC, nicl-nno commented on .github/workflows/unit-build.yml
> +	pip isntall -r fedot/utilities/profiler/requirements_memory_profiler.txt
Ну тут и в isntall опечатка.

2021-04-27 08:49 UTC, BarabanovaIrina requested changes

2021-04-27 08:49 UTC, BarabanovaIrina commented on fedot/utilities/profiler/memory_profiler.py
> +                      " Install 'utilities/profiler/requirements_memory_profiler.txt'")
Тут к пути стоит добавить fedot впереди, потому что обычно терминал установлен на корень проекта. 
А этот функционал рассчитан на то, что им будут пользоваться те, кто установит fedot через pip?

2021-04-27 09:09 UTC, BarabanovaIrina requested changes

2021-04-27 09:09 UTC, BarabanovaIrina commented on test/unit/utilities/test_profiler.py
> +                   path=path, roots=run_credit_scoring_problem, max_depth=8)
Здесь несоответствие типов. Тип list из доктринга MemotyProfiler подцепился. 
<img width="981" alt="Screenshot 2021-04-27 at 11 55 33" src="https://user-images.githubusercontent.com/29018907/116216008-d6544000-a750-11eb-8fa5-5984ba4ae9e7.png">

2021-04-27 12:48 UTC, MAGLeb commented on test/unit/utilities/test_profiler.py
> +                   path=path, roots=run_credit_scoring_problem, max_depth=8)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e0fdedc473ae0ed7a43a65b49168a931a56b6354b7de305e4459b24d18ab8d7aR47-R50)

2021-04-27 12:48 UTC, MAGLeb commented on fedot/utilities/profiler/memory_profiler.py
> +                      " Install 'utilities/profiler/requirements_memory_profiler.txt'")
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e9ecfffb8b789d3d9abdd6945ca43b00734b41b9b13c59d7236606f884d79f5dR8-R13)

2021-04-27 12:49 UTC, MAGLeb commented on .github/workflows/unit-build.yml
> +	pip isntall -r fedot/utilities/profiler/requirements_memory_profiler.txt
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-1cfdfb9f67146a6f31ac9a496e9da2c2f6b28af4bae7ba7fc3ef061e7fe12001R32-R37)

2021-04-27 12:49 UTC, MAGLeb commented on fedot/utilities/profiler/profiler.py
> +class MemoryProfiler:
Добавил

2021-04-27 12:51 UTC, MAGLeb commented on fedot/utilities/profiler/profiler.py
> +class TimeProfiler:
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e0fdedc473ae0ed7a43a65b49168a931a56b6354b7de305e4459b24d18ab8d7aR20-R51). 

Было еще по две проверки на каждом тесте, сохраняются ли картинки.
`assert(os.path.exist(os.path.join(os.path.abspath('memory_path'), graph.png)))`
Локально тесты отрабатывали, на сервере что-то не хотели собираться.

2021-04-27 12:51 UTC, MAGLeb commented on fedot/utilities/profiler/profiler.py
> +import cProfile
[Разделил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e9ecfffb8b789d3d9abdd6945ca43b00734b41b9b13c59d7236606f884d79f5dR1-R23)

2021-04-27 12:53 UTC, MAGLeb commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e0fdedc473ae0ed7a43a65b49168a931a56b6354b7de305e4459b24d18ab8d7aR35-R37). Добавил аргументы для оставновки композера по времени.

2021-04-27 12:53 UTC, MAGLeb commented on examples/fedot_profiler_example.py
> +    # profiler = MemoryProfiler(run_credit_scoring_problem, path=path, roots=run_credit_scoring_problem, max_depth=8)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-f84ed45f918c284b32294fb060c4426125686604d043b0358cc07fa3ad8fdd59R66-R67). Убрал палитру, которая недоступна в seaborn в этой версии. Локально установлена была другая версия, поэтому не падало.

2021-04-27 12:54 UTC, MAGLeb commented on requirements.txt
> +snakeviz==2.1.0
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/286/commits/8934f6c46582465960c1e7248b4c9cf0b19badc8#diff-e9ecfffb8b789d3d9abdd6945ca43b00734b41b9b13c59d7236606f884d79f5dR7-R13)

2021-04-27 14:52 UTC, nicl-nno commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Норм.

Но лучше в примере использовать оба профайлера сразу (раскомментировав первый) - т.к. иначе висит неиспользуемый import, который pycharm сразу захочет оптимизировать.

2021-04-27 14:54 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/116262858-8e99dc80-a781-11eb-939e-86a056fa0a2c.png)

А как вообще интерпретировать этот граф? Где тут видно, сколько памяти занято?

2021-04-27 14:54 UTC, nicl-nno approved these changes

2021-04-27 15:09 UTC, BarabanovaIrina approved these changes

2021-04-27 15:11 UTC, BarabanovaIrina commented on fedot/utilities/profiler/profiler.py
> +class MemoryProfiler:
Работает

2021-04-28 10:49 UTC, J3FALL approved these changes

2021-04-28 12:36 UTC, MAGLeb commented
> ![image](https://user-images.githubusercontent.com/5711814/116262858-8e99dc80-a781-11eb-939e-86a056fa0a2c.png)
> 
> А как вообще интерпретировать этот граф? Где тут видно, сколько памяти занято?

Граф показывает созданные объекты. Конкретного ничего на нем не увидишь, но общее впечатление об отработанном коде можно увидеть.

2021-04-28 12:37 UTC, MAGLeb commented on examples/fedot_profiler_example.py
> +def run_credit_scoring_problem(max_lead_time: datetime.timedelta = datetime.timedelta(minutes=5)):
Хорошо.

2021-04-28 12:39 UTC, nicl-nno commented
Ну конечно хотелось бы хотя бы в табличном виде иметь какую-то сводку вида "класс - суммарный объем памяти".
Но не в этом PR уже.

2021-04-28 12:51 UTC, MAGLeb commented
> Ну конечно хотелось бы хотя бы в табличном виде иметь какую-то сводку вида "класс - суммарный объем памяти". Иначе утечку не отследить.
> Но не в этом PR уже.

Пробовал сделать подобную вещь (библиотека pympler), но он собирает очень мало fedot объектов, вроде как только "примитивные" объекты. Используя [mumpy](https://pythonhosted.org/Pympler/muppy.html), объект из pympler, видит только один класс из fedot, остальная статистика о примитивных типах данных: list, tuple, str, int...

Есть возможность сделать такую статистику используя декораторы, но от них пока отказались. Другого способа я не смог найти.

2021-04-28 12:52 UTC, merged