Simple multi-modal example implemented
nccr-itmo/FEDOT pull request #291
Opened 2021-05-12 22:24 UTC by nicl-nno

New case multi_modal_rating_prediction.py is added. It implements the static multi-modal chain for text, image, and table data.
Mm-imdb dataset is used as an example (#290).

2021-05-19 13:51 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/chains/chain.py`](https://github.com/nccr-itmo/FEDOT/blob/364b8f807d4dd1c3140ce02f319939e606cf4959/fedot/core/chains/chain.py):

> [Line 374:1](https://github.com/nccr-itmo/FEDOT/blob/364b8f807d4dd1c3140ce02f319939e606cf4959/fedot/core/chains/chain.py#L374): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-05-20 13:51 UTC, Dreamlone requested changes

2021-05-20 13:51 UTC, Dreamlone commented on fedot/core/chains/chain_validation.py
> +                    raise ValueError(f'{ERROR_PREFIX} Chain has incorrect data connections')
Выглядит тяжеловато - может стоит сделать переменные покороче, например:

```
node_dtypes = set(current_nodes_supported_data_types.input_types)
parent_dtypes = set(parent_node_supported_data_types.output_types)
if len(set.intersection(node_dtypes, parent_dtypes)) == 0:
    raise ValueError(f'{ERROR_PREFIX} Chain has incorrect data connections')
```

2021-05-20 13:51 UTC, Dreamlone commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table):
А можешь пожалуйста добавить описание docsrting для этого метода.

2021-05-20 13:51 UTC, Dreamlone commented on fedot/core/data/load_data.py
> +        self.meta_df = self.meta_df.drop(['file_path'], axis=1)
Сюда ты бы комментариев чуть чуть, чтобы лучше понимать что происходит (я люблю комментарии).

2021-05-20 13:51 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            return idx, features, target
А зачем тут еще и проверка на типы данных? Вроде, если в списке всего один OutputData, то и мержить ничего не надо - бери его одного и передавай дальше, независимо от того, какой тип данных в нем циркулирует.

2021-05-20 13:51 UTC, Dreamlone commented on fedot/core/operations/evaluation/data_source.py
> +                          data_type=predict_data.data_type, target=predict_data.target, predict=predict_data.features)
Описание надо поправить - или вообще сократить до одной строчки (мб даже убрать) - тут же ничего в этом методе не происходит

2021-05-20 13:51 UTC, Dreamlone commented on test/unit/chains/test_multi_modal.py
> +    img_path = os.path.join(str(fedot_project_root()), img_files_path)
Может в этом тесте стоит использовать функции из cases и examples (когда/если мы их выделим в отдельные функции), чтобы код не дублировать.

2021-05-20 13:51 UTC, Dreamlone commented on test/unit/data_operations/test_time_series_operations.py
> +                                                        'lagged': predict_source_ts}))
Дисклеймер: мне понравился реализованный подход к подключению разных данных в цепочку. Но есть вопрос: а будет ли эта же конструкция нормально работать, если например, у нас 3 primary узла, и 2 из них "exog"? Или это реализовано через "<название_операции>/<индекс>" (подсмотрел в multi_modal_rating_prediction.py)?

2021-05-20 14:04 UTC, nicl-nno commented on fedot/core/data/merge.py
> +            return idx, features, target
Тогда возникают ошибки с размерностью массивов для временных рядов.

2021-05-20 14:05 UTC, nicl-nno commented on test/unit/data_operations/test_time_series_operations.py
> +                                                        'lagged': predict_source_ts}))
> Или это реализовано через "<название_операции>/<индекс>" (подсмотрел в multi_modal_rating_prediction.py)?

Ну да, для этого оно и добавлено. Если будет пример с несколькими экзогенными рядами, можно будет добавить тест на это.

2021-05-20 15:51 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            return idx, features, target
А есть какой-нибудь пример. где это вызывало ошибку?
Просто я сейчас в examples запустил ts_forecasting_tuning.py (вполне себе временной ряд), и убрал из проверки часть "self.outputs[0].data_type in [DataTypesEnum.image, DataTypesEnum.text]" и ничего не сломалось.

2021-05-20 17:24 UTC, nicl-nno commented on cases/multi_modal_rating_prediction.py
> +    print(err)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-d9f0e1d6a55a5de297432c4697e964b4061169c2571fde8df76b5723b12d1348R64-R65).

2021-05-20 17:25 UTC, nicl-nno commented on cases/multi_modal_rating_prediction.py
> +    unpack_archived_data('mm_imdb')
[Разбил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-d9f0e1d6a55a5de297432c4697e964b4061169c2571fde8df76b5723b12d1348R3-R5)

2021-05-20 17:25 UTC, nicl-nno commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
Вроде дело не в этом, но в чем именно - непонятно. Пока просто убрал вызов run_text_problem_from_saved_meta_file.

Мб потом @BarabanovaIrina глянет, где именно этот saved_meta_file должен создавать - сходу непонятно.

2021-05-20 17:25 UTC, nicl-nno commented on examples/multi_modal_rating_prediction.py
> +    run_multi_modal_case()
Переделал

2021-05-20 17:25 UTC, nicl-nno commented on fedot/core/data/load_data.py
> +        self.meta_df = self.meta_df.drop(['file_path'], axis=1)
Добавил пару комментов. Возможно потом надо будет переделать работу с json-ами, тут явно несколько переусложнено.

2021-05-20 17:26 UTC, nicl-nno commented on fedot/core/operations/evaluation/data_source.py
> +                          data_type=predict_data.data_type, target=predict_data.target, predict=predict_data.features)
Убрал

2021-05-20 17:26 UTC, nicl-nno commented on test/unit/chains/test_multi_modal.py
> +    img_path = os.path.join(str(fedot_project_root()), img_files_path)
Использовал

2021-05-20 17:41 UTC, nicl-nno commented on fedot/core/data/merge.py
> +            return idx, features, target
![image](https://user-images.githubusercontent.com/5711814/119024420-b6a8e400-b9ab-11eb-99d4-ab95ec9303ee.png)

2021-05-20 19:45 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
А что за ошибка? 
Просто у меня только такая падает, где-то потеряли файлик. 
<img width="1238" alt="Screenshot 2021-05-20 at 22 43 55" src="https://user-images.githubusercontent.com/29018907/119039377-de547800-b9bc-11eb-8d72-dd28d14e3b00.png">

2021-05-20 19:47 UTC, nicl-nno commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
Ошибка эта, но ведь файла и в мастере нет.

2021-05-20 19:58 UTC, Dreamlone commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
Запустил этот же кейс из мастера - там та же самая ошибка. Видимо он действительно генерируется как такой промежуточный csv файл. - Мб стоит и другие примеры проверить, которые не покрыты unit-тестами (или хотя бы запустить интеграционные - там есть большинство из них).  

Как я понимаю, это проблема пришла в этот PR из мастера - может заведём issue под исправление этого? (либо можно в рамках этого PR это перебороть)

2021-05-20 19:58 UTC, BarabanovaIrina commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
Есть подозрение, что название файла вынесли из функции, но почему-то переименовали. 
Потому что образование файла с таким именем нигде нет.

<img width="1076" alt="Screenshot 2021-05-20 at 22 56 30" src="https://user-images.githubusercontent.com/29018907/119040889-9fbfbd00-b9be-11eb-87bc-ee9a72aa2b13.png">

2021-05-20 20:02 UTC, nicl-nno commented on cases/spam_detection.py
> +    unpack_archived_data('spamham')
https://github.com/nccr-itmo/FEDOT/issues/298

Можно все наведение порядка с examples свести сюда.

Все тесты на примеры сейчас проходят.

2021-05-21 08:22 UTC, Dreamlone commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table):
Есть очепяточка в названии переменной "fiedls_to_use"

2021-05-21 08:39 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            return idx, features, target
Убедил) 
Я вник еще раз в код, проблема тут в следующем: я реализовывал DataMerger как класс с одной-единственной точкой входа (доступа) к его функционалу - метод "merge". Сам класс уже внутри определяет как именно стоит мержить данные: если таблицы, - то один способ, если временные ряд - то по другому и так далее (см. merge_function_by_type). И дело в том, что даже если мержить надо всего один OutputData, то в мержере все равно производятся определенные манипуляции над данными (меняется размерность например). 

Отсюда я предлагаю следующее. Раз у нас появились новые типы данных (картинки), и мы начинаем их активно использовать - нужна соответствующая функция их обработки при объединении. Можно реализовать её по аналогии с "combine_datasets_ts" - и назвать метод как "combine_images". Дальше, если в проверке "DataTypesEnum.image, DataTypesEnum.text" есть тип данных текстовый, значит тебя не устраивает как он обрабатывается в мержере, я правильно понял? Как говорится, feel free его тоже реализовать под свои задачи - сейчас то там просто используется объединение таблиц, я считаю, что это не совсем корректно, просто раньше проблем не доставляло. 

Сделать эти штуки важно и еще потому, что хотя в нынешнем примере мы не используем объединение "датасет с картинками - датасет с картинками" - потенциально, обрабатывать такие случаи стоит. И вот когда это будет реализовано, можно будет убрать эту проверку.

2021-05-21 08:56 UTC, Dreamlone requested changes

2021-05-21 08:56 UTC, Dreamlone commented on examples/ts_forecasting_with_exogenous.py
> +                                                       'ts_sea_level.csv'),
Лучше для удобочитаемости вынести конструкцию с "os.path.join" в отдельную переменную. А потом её уже передавать в функцию. Но это конечно так - косметический момент.

2021-05-21 08:56 UTC, Dreamlone commented on fedot/core/data/data.py
> +                target = np.load(labels)
Всё таки мне кажется, что здесь слишком большая вложенность. Эту часть кода возможно разбить на несколько частей и вызывать в виде функций?

2021-05-21 10:33 UTC, nicl-nno commented on fedot/core/data/merge.py
> +            return idx, features, target
Предлагаю это в отдельный issue вынести (#301), т.к. тут нужны ещё и примеры, где картинки/тексты мержатся.

2021-05-21 10:41 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            return idx, features, target
Пожалуй соглашусь, что сейчас просто не на чём проверить. Плюс заметно может поменяться логика мерджинга, когда мы вольем в мастер PR #296 - может тогда появятся новые мысли как это можно сделать элегантно (для мультимодальных данных в том числе).

2021-05-21 11:13 UTC, nicl-nno commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table):
Поменял везде

2021-05-21 11:13 UTC, nicl-nno commented on examples/ts_forecasting_with_exogenous.py
> +                                                       'ts_sea_level.csv'),
Вынес.

2021-05-21 11:13 UTC, nicl-nno commented on fedot/core/data/data.py
> +                target = np.load(labels)
Пока разбил [так](https://github.com/nccr-itmo/FEDOT/pull/291/commits/c1cf2363496db6befbdd9883355b8e8a97f99d4a#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR466-R475). Надо отдельно продумать, в каком виде могут подаваться картинки.

2021-05-21 12:15 UTC, Dreamlone approved these changes

2021-05-21 13:55 UTC, J3FALL requested changes

2021-05-21 13:55 UTC, J3FALL commented on examples/multi_modal_chain.py
> +    ds_image = PrimaryNode('data_source_img/1')
Еще не добрался до слоя Operations, но "data_source_img/1" как-то не состыкуется с alias-ами в остальном фреймворке

2021-05-21 13:55 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        return input_data
Хоть метод и приватный, я бы, все-таки, попробовал его протестировать через метод fit.
Ну, т.е. чтобы можно было убедиться, что node_data действительно расставлены по своим местам.

2021-05-21 13:55 UTC, J3FALL commented on fedot/core/chains/chain.py
> +        return input_data
Еще, кстати, не очень понял, зачем return, если при его вызове он не используется.

2021-05-21 13:55 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +            test_data[node] = test_data_part
Я бы, честно говоря, выделил отдельный метод.

2021-05-21 14:04 UTC, nicl-nno commented on cases/multi_modal_rating_prediction.py
> +    # TODO change to uploadable full dataset
Полный весит 8Гб, я урезал до помещающегося на гитхаб размера.

2021-05-21 14:05 UTC, nicl-nno commented on examples/multi_modal_chain.py
> +    ds_image = PrimaryNode('data_source_img/1')
> "data_source_img/1" как-то не состыкуется с alias-ами

А то ты имеешь в виду? Сейчас постфиксы после / обрезаются при переходе к операциям и далее нигде не фигурируют.

2021-05-21 14:05 UTC, nicl-nno commented on fedot/core/data/data.py
>          else:
Ну идея в том, что в будущем могут понадобится какие-то ещё модификации split для специфических типов данных. 
А так эти детали гарантировано спрятаны внутри спец. функций для типов данных.

2021-05-21 14:40 UTC, J3FALL commented on cases/multi_modal_rating_prediction.py
> +    # TODO change to uploadable full dataset
понял

2021-05-21 14:41 UTC, J3FALL commented on cases/multi_modal_rating_prediction.py
> +    # TODO change to uploadable full dataset
Тогда я бы предложил этот комментарий заменить функцией-заглушкой, которая будет называться, например:
"download_mmdb_dataset". Она будет вызываться, но внутри ничего не будет делать.
Так более надежнее оставить такую штуку на будущее

2021-05-21 14:45 UTC, J3FALL commented on fedot/core/data/data.py
>          else:
Да, но сейчас это выглядит как будто лишний слой вызовов.
Окей, можно оставить, но выглядит, что if-else блоки можно заменить просто словарем, где ключ - это data_type, а значение - соответствующая функция.
Будет компактнее

2021-05-21 14:47 UTC, J3FALL commented on examples/multi_modal_chain.py
> +    ds_image = PrimaryNode('data_source_img/1')
Я, видимо, не добрался еще до изменений с постфиксами )
Либо просто был не в курсе про них )
Посмотрю дальше код и отвечу здесь, но пока кажется, что лучше передавать опциональный параметр, а не кодировать что-то в одном названии

2021-05-21 14:54 UTC, nicl-nno commented on examples/multi_modal_chain.py
> +    ds_image = PrimaryNode('data_source_img/1')
>лучше передавать опциональный параметр

Не придумал, как это сделать универсально и не-громоздко.

2021-05-21 16:06 UTC, nicl-nno commented on examples/multi_modal_chain.py
> +    run_multi_modal_chain(files_path='cases/data/mm_imdb', is_visualise=True)
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-ad713c94d0a9d233ec7bdfa6da5c493d64e50a41b020f6c782c69f63659fdec9R128) для examples упрощенный датасет из пару десятков семпплов.

2021-05-21 16:06 UTC, nicl-nno commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table) -> 'InputData':
1. Пофиксил
2. [Добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-ad713c94d0a9d233ec7bdfa6da5c493d64e50a41b020f6c782c69f63659fdec9R128)

2021-05-21 16:07 UTC, nicl-nno commented on fedot/core/data/data.py
> +            features = np.array(val)
Она отрабатывает когда 1 признак извлекается - [добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-4602cf94a48a1a4368f5381c313e669ac313880a68d3769ce97a7235021f6bdcR151-R154) такой вариант в тест. Отдельно её сложно проверить.

2021-05-21 16:07 UTC, nicl-nno commented on fedot/core/data/data.py
> +        :param data_type: data type in fields
Суть в том, что если в полях json текст, то нужно ставить data_type текст. Если в полях числа - то tables, и т. д.

[Добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR183) уточнение.

2021-05-21 16:07 UTC, nicl-nno commented on fedot/core/data/data.py
> +    return _split_any(data, task, DataTypesEnum.table, split_ratio, with_shuffle)
См. ниже

2021-05-21 16:08 UTC, nicl-nno commented on fedot/core/data/data.py
>          else:
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-27d80afd30b9f4adfece46d6daf0671cfa72846190db2e2b710401febaac53ccR145-R150) в словарь, заодно вынес в отдельный скрипт, а то data.py слишком загроможден.

2021-05-21 16:08 UTC, nicl-nno commented on cases/multi_modal_rating_prediction.py
> +    # TODO change to uploadable full dataset
Done

2021-05-21 16:09 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            test_data[node] = test_data_part
[Выделил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-27d80afd30b9f4adfece46d6daf0671cfa72846190db2e2b710401febaac53ccR162-R172).

2021-05-24 12:22 UTC, J3FALL commented on examples/multi_modal_chain.py
> +    run_multi_modal_chain(files_path='cases/data/mm_imdb', is_visualise=True)
У меня упал этот пример при запуске
![image](https://user-images.githubusercontent.com/7864250/119347180-d4c05e00-bca3-11eb-99cd-b285da55ba2e.png)

2021-05-24 12:27 UTC, nicl-nno commented on examples/multi_modal_chain.py
> +    run_multi_modal_chain(files_path='cases/data/mm_imdb', is_visualise=True)
Кажется я забыл закоммитить архив, исправил.

2021-05-24 12:31 UTC, J3FALL commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table) -> 'InputData':
Норм, стало понятнее
Правда я нашел по коду где создается meta-файл в ходе тестов, подскажи, плз?
![image](https://user-images.githubusercontent.com/7864250/119348073-0e459900-bca5-11eb-88fc-15fd2c13b20a.png)

2021-05-24 12:34 UTC, J3FALL commented on fedot/core/data/data.py
> +        :param data_type: data type in fields
Ок, теперь понял, сойдет

2021-05-24 12:39 UTC, J3FALL commented on examples/multi_modal_chain.py
> +    run_multi_modal_chain(files_path='cases/data/mm_imdb', is_visualise=True)
угу, теперь запускается, норм

2021-05-24 12:42 UTC, nicl-nno commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table) -> 'InputData':
Это взято из реализации @BarabanovaIrina для текстов, там эти тексты перегонялись в csv и сохранялись в meta. 
Посмотрю, можно ли это легко убрать.

2021-05-24 13:33 UTC, J3FALL requested changes

2021-05-24 13:33 UTC, J3FALL commented on cases/multi_modal_rating_prediction.py
> +        with_initial_chain(chain).with_cache('multi_modal_opt.cache')
Тут добавить коммент про начальное приближение, а потом перегнать это в полноценный notebook

2021-05-24 13:33 UTC, J3FALL commented on fedot/core/data/multi_modal.py
> +class MultiModalData(dict):
Добавить простые тесты на этот класс

2021-05-24 13:33 UTC, J3FALL commented on fedot/core/repository/operation_types_repository.py
> +        operation_type = operation_id.split('/')[0]
Тут добавить поясняющую функцию + где-то коротко описать эту штуку с постфиксами.
Мб в виде примера какого-нибудь

2021-05-24 14:31 UTC, nicl-nno commented on fedot/core/data/data.py
> +                        data_type: DataTypesEnum = DataTypesEnum.table) -> 'InputData':
[Выключил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-3af98de107d9887540bb794f677eed030add8f578803e0f48e0434a26ce10f2bR95) по умолчанию.

2021-05-24 14:31 UTC, nicl-nno commented on cases/multi_modal_rating_prediction.py
> +        with_initial_chain(chain).with_cache('multi_modal_opt.cache')
Добавил. Про ноутбук создал issue #304

2021-05-24 14:31 UTC, nicl-nno commented on fedot/core/data/multi_modal.py
> +class MultiModalData(dict):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-4602cf94a48a1a4368f5381c313e669ac313880a68d3769ce97a7235021f6bdcR158-R180).

2021-05-24 14:33 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +        operation_type = operation_id.split('/')[0]
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0R288-R300), описал. Сделал [тест](https://github.com/nccr-itmo/FEDOT/pull/291/files#diff-615c61fe076791f73bd56528d5e0185709557c2fb4a106139b28d8e75a7377a8R86-R89).

2021-05-28 10:10 UTC, J3FALL approved these changes

2021-05-28 15:27 UTC, merged