Cross validation
nccr-itmo/FEDOT pull request #292
Opened 2021-05-14 10:13 UTC by MAGLeb

2021-05-14 10:33 UTC, nicl-nno requested changes

2021-05-14 10:33 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +        :param folds: integer folds to cross validate
Раз допускается None, то стоит это в описании указать

2021-05-14 10:33 UTC, nicl-nno commented on fedot/core/data/data.py
> +def train_test_data_generator(data: InputData, folds: int):
Мб стоит указать в названии, что это для cv?

2021-05-14 10:33 UTC, nicl-nno commented on fedot/core/data/data.py
> +            _features_and_target_by_index(train_idxs, data)
Тут не должно быть test_idxs вместо train?

2021-05-14 10:33 UTC, nicl-nno commented on fedot/core/repository/quality_metrics_repository.py
> +    pass
А это актуально ещё?

2021-05-14 10:33 UTC, nicl-nno commented on test/unit/utilities/test_cross_validation.py
> +        print(train_idxs)
Вроде тут ничего не проверяется.

2021-05-14 10:33 UTC, nicl-nno commented on test/unit/utilities/test_cross_validation.py
> +    chain = Chain(final)
Коммент общего характера - нет ли смысла для компактности такие операции записывать как 

Chain(SecondaryNode(operation_type='logit', nodes_from=[PrimaryNode(operation_type='xgboost'), PrimaryNode(operation_type='scaling')]))

?

2021-05-14 10:33 UTC, nicl-nno commented on test/unit/utilities/test_cross_validation.py
> +def test_composer_optimisation_correct():
тоже стоит упомянуть про cv, чтобы было понятнее в случае сбоя.

2021-05-14 10:33 UTC, nicl-nno commented on test/unit/utilities/test_cross_validation.py
> +                                                   max_lead_time=timedelta(minutes=20),
20 минут - пербор для теста в любом случае

2021-05-14 14:50 UTC, MAGLeb commented on fedot/core/composer/gp_composer/gp_composer.py
> +        :param folds: integer folds to cross validate
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2L104-L111)

2021-05-14 14:50 UTC, MAGLeb commented on fedot/core/data/data.py
> +def train_test_data_generator(data: InputData, folds: int):
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL312-R312)

2021-05-14 14:51 UTC, MAGLeb commented on fedot/core/repository/quality_metrics_repository.py
> +    pass
Верно, лишний класс.
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-aec0d1a8e3b5435466b9bf29c78f5b10ac67f7e382bf59dad6c25f9702cb41bcL13-L16)

2021-05-14 14:51 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +        print(train_idxs)
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-49775d029f454d3c7c665166f48671c835c234ab3231094374bf9aea0f5c1cbbL39-L50)

2021-05-14 14:51 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +    chain = Chain(final)
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-49775d029f454d3c7c665166f48671c835c234ab3231094374bf9aea0f5c1cbbL31-R33)

2021-05-14 14:52 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +def test_composer_optimisation_correct():
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-49775d029f454d3c7c665166f48671c835c234ab3231094374bf9aea0f5c1cbbL63-R69)

2021-05-14 14:52 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +                                                   max_lead_time=timedelta(minutes=20),
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-49775d029f454d3c7c665166f48671c835c234ab3231094374bf9aea0f5c1cbbL63-R69)

2021-05-14 14:52 UTC, MAGLeb commented on fedot/core/data/data.py
> +            _features_and_target_by_index(train_idxs, data)
[Fix](https://github.com/nccr-itmo/FEDOT/pull/292/commits/955cf3b9e0a5562cc32b78889fa519fc1aa5cae9#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL318-L320)

2021-05-14 14:59 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +        :param folds: integer folds to cross validate
>with out CV

Пробел лишний

2021-05-14 15:03 UTC, nicl-nno commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
А почему решили добавлять именно сюда?

Выглядит логичнее в GPChainOptimiserParameters, рядов в is_multi_objective

2021-05-15 10:45 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fedot/core/composer/gp_composer/gp_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/c42a0dfbd4ede7fceed0b47239bd72fd63286fc9/fedot/core/composer/gp_composer/gp_composer.py):

> [Line 121:121](https://github.com/nccr-itmo/FEDOT/blob/c42a0dfbd4ede7fceed0b47239bd72fd63286fc9/fedot/core/composer/gp_composer/gp_composer.py#L121): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2021-05-15 11:16 UTC, MAGLeb commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
Согласен, теперь передача аргумента для кросс валидации в классе [GPChainOptimiserParameters](https://github.com/nccr-itmo/FEDOT/pull/292/commits/c42a0dfbd4ede7fceed0b47239bd72fd63286fc9#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2L102-R122)

2021-05-15 11:16 UTC, MAGLeb commented on fedot/core/composer/gp_composer/gp_composer.py
> +        :param folds: integer folds to cross validate
[Исправил.](https://github.com/nccr-itmo/FEDOT/pull/292/commits/c42a0dfbd4ede7fceed0b47239bd72fd63286fc9#diff-87cbdb4ae613e3e710ac963ddb8c04e88bf566b76f4609eaa666336cdf7b1a08L38-L41)

2021-05-15 11:18 UTC, MAGLeb commented
Также @nicl-nno писал в личку, что cases/credit_scoring_problem.py с folds = 3, падает с ошибкой. Данный случай разобран и [исправлен](https://github.com/nccr-itmo/FEDOT/pull/292/files#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR338-R342).

2021-05-15 13:55 UTC, J3FALL requested changes

2021-05-15 13:55 UTC, J3FALL commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
Но тогда и параметр folds нужно убрать из метода compose_chain, если оно не используется.
Кстати, а не кажется ли более логичным folds передавать в composer_requirements, а не через gp_optimizer?
По идее, cv может использоваться не только в gp-оптимизации.

2021-05-15 13:55 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +
Добавь, плз, здесь запись в лог, что "cv был задан/не задан -> данные были разбиты на train/test

2021-05-15 13:55 UTC, J3FALL commented on fedot/core/data/data.py
> +def train_test_data_generator_cv(data: InputData, folds: int):
Думаю, резонно добавить docstring, чтобы было понятно, что это такое

2021-05-15 13:55 UTC, J3FALL commented on fedot/core/data/data.py
> +def train_test_data_generator_cv(data: InputData, folds: int):
И название мб подсократить? Например, просто на cross_validation_generator?

2021-05-15 13:55 UTC, J3FALL commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
А, тут типо возможность делать CV для многокритериального случая?

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +from datetime import timedelta
хм, оригинальный скрипт находится в operations, тогда тесты на него тоже должны быть где-то там.

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +    assert all(list(map(lambda x: x >= -1, actual_value)))
Можно здесь ввести поясняющую переменную?

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +def test_cv_metric_correct(classification_dataset):
мб название теста "test_cv_multiple_metrics_evaluated_correct" чуть лучше ?

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +def test_cv_with_composer_optimisation_correct():
наоборот, наверное, если метод будет называться: test_composer_with_cv_optimization_correct?

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +
О, кстати, а как насчет добавить cv еще и в FEDOT API? 
Думаю, это вполне себе востребованная фича.

2021-05-15 13:55 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +    assert roc_on_valid_evo_composed > 0
И еще момент: есть подозрение, что для ts_forecasting задачи cross_validation упадет. А если нет, то это энивей некорректно будет работать. Нужно (1) воспроизвести композер с кросс-валидацией для ts_forecasting-а и (б) добавить соответствующую проверку в композере для этого (например) и выкинуть NonImplemented исключение.

2021-05-17 07:56 UTC, MAGLeb commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
Сначала не заострил на этом внимание, но кажется что правильнее этот аргумент передавать в composer, так как именно там и происходит построение цепочки на основе метрики, в данном случае на основе кросс-валидации. Жду ответа от @nicl-nno, чтобы принять дальше действия.

2021-05-17 08:40 UTC, nicl-nno commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
Ок, согласен, давайте в GPComposerRequirements.

2021-05-17 09:53 UTC, nicl-nno commented on test/unit/utilities/test_cross_validation.py
> +    assert roc_on_valid_evo_composed > 0
Для кластеризации кросс-валидация вообще не имеет смысла.

2021-05-17 10:25 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +
[Добавил](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eL1-R173) + [тест](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-93c928751d2a9c6a20c2a5b6a0a1547b3d8c7a3501a6217efcb6063948f0c280R109-R124) для АПИ.

2021-05-17 10:26 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +def test_cv_with_composer_optimisation_correct():
Думаю да, [исправил](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-93c928751d2a9c6a20c2a5b6a0a1547b3d8c7a3501a6217efcb6063948f0c280R79-R81).

2021-05-17 10:26 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +def test_cv_metric_correct(classification_dataset):
[Изменил.](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-93c928751d2a9c6a20c2a5b6a0a1547b3d8c7a3501a6217efcb6063948f0c280R33-R34)

2021-05-17 10:26 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +    assert all(list(map(lambda x: x >= -1, actual_value)))
[Создал.](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-93c928751d2a9c6a20c2a5b6a0a1547b3d8c7a3501a6217efcb6063948f0c280R39-R42)

2021-05-17 10:27 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +from datetime import timedelta
Согласен, исправил. Если следовать этому принципу, хочу обратить внимание что папка models отсутствует, но юнит-тесты в папке models остались.

2021-05-17 10:27 UTC, MAGLeb commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
Не до конца понял вопрос.

2021-05-17 10:27 UTC, MAGLeb commented on fedot/core/data/data.py
> +def train_test_data_generator_cv(data: InputData, folds: int):
[Назвал](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL312-R320) "train_test_cv_generator". Убрал из названия data, остальное кажется полезным в названии, генератор для кросс валидации который разбивает данные на train/test. Также не хочется менять, чтобы было однообразие с другими названиями аналогичных функций.

2021-05-17 10:28 UTC, MAGLeb commented on fedot/core/composer/gp_composer/gp_composer.py
> +
[Добавил.](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2L120-R126)

2021-05-17 10:30 UTC, MAGLeb commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
[Убрал](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebL67-L71) аргумент из метода compose_chain. [Изменил](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebL23-R46) передачу параметра cv_folds через класс ComposerRequirements.

2021-05-17 10:31 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +    assert roc_on_valid_evo_composed > 0
Об этом же. Вдруг кто-то передаст cv_folds and task_type='cluster'. Чтобы не было непонимая, думаю стоит выкидывать ошибку. [Добавил](https://github.com/nccr-itmo/FEDOT/commit/38c320c0e19cf1943efd3c43aa09261febb222b2#diff-7bab6b840a5d83bac705c68a510ee6b1fb61103208605ffe59667d9eb4e13e6fL10-L11) тест + raise if task_type in ['cluster', 'ts_forcast'].

2021-05-17 10:46 UTC, nicl-nno commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
![image](https://user-images.githubusercontent.com/5711814/118476508-446ba180-b716-11eb-98b4-d5b6032b3485.png)

Ну да, вроде работает для МК-случая тоже.

2021-05-17 10:46 UTC, J3FALL commented on fedot/core/composer/gp_composer/gp_composer.py
> +
![image](https://user-images.githubusercontent.com/7864250/118476513-47669200-b716-11eb-8945-c6e4965230ff.png)
А почему именно was implemented? Слово вроде по контексту не оч подходит

2021-05-17 10:48 UTC, J3FALL commented on fedot/core/data/data.py
> +def train_test_data_generator_cv(data: InputData, folds: int):
Укажи явно, что это k-fold cross-validation в docstring.
![image](https://user-images.githubusercontent.com/7864250/118476656-74b34000-b716-11eb-9ab0-7a4038eac21f.png)

2021-05-17 10:48 UTC, J3FALL commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
Ну, если у нас задано > одной метрики, мы делаем кросс-валидацию по каждой из ней?

2021-05-17 10:49 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +from datetime import timedelta
Спасибо за замечание, можно отдельной задачей глянуть на струкутуру тестов и мб переделать ее, чтобы она больше соответствовала ядру

2021-05-17 11:03 UTC, J3FALL commented on test/unit/utilities/test_cross_validation.py
> +    assert roc_on_valid_evo_composed > 0
Думаю, можно сделать f-string подобный эксепшен в стиле: "Cross-validation is not supported for {task}"
![image](https://user-images.githubusercontent.com/7864250/118478394-7d0c7a80-b718-11eb-8281-8f1592b882ff.png)

2021-05-17 11:04 UTC, J3FALL commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
Не очень говорящий эксепшен. Я бы явно указал, что для фолдов < 2 кросс-валидация недоступна
![image](https://user-images.githubusercontent.com/7864250/118478558-b6dd8100-b718-11eb-80ca-cfb02a2a48e8.png)

2021-05-17 11:24 UTC, nicl-nno commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
Да

2021-05-17 11:30 UTC, J3FALL commented on fedot/core/operations/cross_validation.py
> +    evaluated_metrics = tuple(map(lambda x: np.mean(x), evaluated_metrics))
вопрос снят

2021-05-17 13:42 UTC, nicl-nno approved these changes

2021-05-17 14:52 UTC, MAGLeb commented on fedot/core/composer/gp_composer/gp_composer.py
> +
Applied?

2021-05-17 15:01 UTC, MAGLeb commented on fedot/core/composer/composer.py
> +                      is_visualise: bool = False, folds: int = None) -> Chain:
[Изменил.](https://github.com/nccr-itmo/FEDOT/commit/0eb25ad29087c1e56114b462061e027e0a0e0f30#diff-31abfc93279b584b5ec0fef8e59b6f6100d76dc6c1af93aae88d0ff0c5dcf5ebL45-L46)

2021-05-17 15:03 UTC, MAGLeb commented on fedot/core/data/data.py
> +def train_test_data_generator_cv(data: InputData, folds: int):
[Описал](https://github.com/nccr-itmo/FEDOT/commit/0eb25ad29087c1e56114b462061e027e0a0e0f30#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL312-L315) точнее docstring для функции.

2021-05-17 15:04 UTC, MAGLeb commented on test/unit/utilities/test_cross_validation.py
> +    assert roc_on_valid_evo_composed > 0
[Заменил](https://github.com/nccr-itmo/FEDOT/commit/0eb25ad29087c1e56114b462061e027e0a0e0f30#diff-7bab6b840a5d83bac705c68a510ee6b1fb61103208605ffe59667d9eb4e13e6fL10-L14) "hard-written" тип задачи, на переменный, в зависимости от конкретного случая.

2021-05-18 10:12 UTC, J3FALL approved these changes

2021-05-18 14:43 UTC, merged