Data counter implementation
nccr-itmo/FEDOT pull request #303
Opened 2021-05-21 15:12 UTC by Dreamlone

The functionality of counting how many nodes a data block has visited has been implemented. This information is used in the decompose operation and when composing the feature mask.

2021-05-21 16:19 UTC, nicl-nno requested changes

2021-05-21 16:19 UTC, nicl-nno commented on fedot/core/data/data.py
> +    nodes_counter: int = 0
Ну, может это сформулировать как data_flow_length? А то нарушается абстракция, данные же не знают о нодах.

2021-05-21 16:19 UTC, nicl-nno commented on fedot/core/data/data.py
> +        idx, features, target, masked_fs, is_main_target, task, d_type, n_counter = DataMerger(outputs).merge()
Здесь тогда что-то вроде data_flow_len

2021-05-21 16:19 UTC, nicl-nno commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Вот тут не очень понял что это.

2021-05-21 16:19 UTC, nicl-nno commented on fedot/core/data/merge.py
> +                                    '.', str(output.nodes_counter)))
А зачем это хранить в виде строки, а не кортежа или списка?

2021-05-21 16:19 UTC, nicl-nno commented on fedot/core/data/data.py
> +        idx, features, target, masked_fs, is_main_target, task, d_type, n_counter = DataMerger(outputs).merge()
Кстати, а нет смысла DataMerger-у выдавать сразу InputData?

2021-05-24 08:27 UTC, Dreamlone commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Представим ситуацию, что надо объединит две таблицы ([OutputData1, OutputData2]), первая из которых имеет два столбца, а вторая 3. Ещё добавим, что первая OutputData1 прошла 2 узла (Model parent, который предоставляет предсказания в операцию декомпозиции), а вторая OutputData2 прошла только 1 узел (Data parent, который предоставляет исходные признаки в операцию декомпозиции). 

Раньше маску я создавал как [0, 0, 1, 1, 1] (заполнена int). current_flag просто увеличивался на 1, если мы переходили к следующему OutputData. 

Сейчас же идея заключается примерно в том же самом, но я готовлю не целочисленные значения, а строковые. Получается ['0.2', '0.2', '1.1', '1.1', '1.1']. Каждое значение в этом списке представляет собой комбинацию базового флага (0 или 1) и числа, сколько узлов данные посетили раньше (2 или 1). Делаю я такое объединение, чтобы у каждого OutputData было свой уникальный код. 

Я предполагаю, что это далеко не самый оптимальный вариант как можно делать такую маску. Я думал, что в принципе можно эти штуки хранить в двух отдельных массивах и вкладывать это в список. Что-то вроде:
```
[[0, 0, 1, 1, 1]
 [2, 2, 1, 1, 1]]
```
И потом просто при необходимости их объединять. Но я не уверен, что такой подход сильно лучше. Если есть идеи как можно это улучшить - буду благодарен.

2021-05-24 08:36 UTC, Dreamlone commented on fedot/core/data/merge.py
> +                                    '.', str(output.nodes_counter)))
Потому что мне все равно надо будет искать индексы элементов в массиве, удовлетворяющие условию. Делать это вроде проще через вызов np.argwhere на одномерном массиве - с кортежами в массиве не прокатит. Ну или по крайней мере вот такой код 
```
test_arr = np.array([(10, 1), (30, 20), (10, 1)])
element_for_search = (10, 1)
print(np.ravel(np.argwhere(test_arr == element_for_search)))
```
выдает не то, что хочется. - Значит все равно придется объединять в одномерный массив каким-либо образом. Но это опять же к вопросу о самом подходе - может сама идея составления сложный кодов для нанесения маски не лучшая идея. За подробностями того, в чем суть этой самой идеи см. комментарий выше.

2021-05-24 08:49 UTC, Dreamlone commented on fedot/core/data/data.py
> +        idx, features, target, masked_fs, is_main_target, task, d_type, n_counter = DataMerger(outputs).merge()
Хороший вопрос :) Так точно было бы удобнее, но в существующей архитектуре сразу так сделать нельзя, так как будет проблема с (не знаю как по русски) [circular dependency](https://stackabuse.com/python-circular-imports/). То есть мы передаем в метод InputData экземпляр класса InputData. 

Это вроде можно решить, если сделать функцию, которая будет принимать InputData из DataMerger'a, и при этом будет располагаться в отдельном месте от дата классов (принимает на вход список с OutputData, вызывает DataMerger и получая от него InputData, отдает этот блок с данными дальше). Но насколько я понимаю, все эти переделки уже довольно существенны для архитектуры проекта. Поэтому предлагаю обсудить этот вопрос с @J3FALL 

Другая сторона вопроса, что это может и не понадобиться, если мы все дополнительные поля для InputData и OutputData планируем упаковывать в отдельное поле метаданных. То есть мы больше не планируем добавлять кучу разных дополнительных output'ов, которые будет выдавать DataMerger. А просто будем расширять поле с метаданными при необходимости. Тогда и ничего переделывать не надо будет, как мне кажется.

2021-05-24 10:30 UTC, Dreamlone commented on fedot/core/data/data.py
> +    nodes_counter: int = 0
Да, думаю вполне так назвать можно, звучит получше - [исправил](https://github.com/nccr-itmo/FEDOT/pull/303/commits/0059e3f1cee520a752e1b641552ea7aaa716b685)

2021-05-24 10:31 UTC, Dreamlone commented on fedot/core/data/data.py
> +        idx, features, target, masked_fs, is_main_target, task, d_type, n_counter = DataMerger(outputs).merge()
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/303/commits/0059e3f1cee520a752e1b641552ea7aaa716b685#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL179-R180)

2021-05-24 10:45 UTC, nicl-nno commented on fedot/core/data/data.py
> +        idx, features, target, masked_fs, is_main_target, task, d_type, n_counter = DataMerger(outputs).merge()
Ок, если это порождает сложности, то на мой взляд не критично.

2021-05-24 10:46 UTC, nicl-nno commented on fedot/core/data/merge.py
> +                                    '.', str(output.nodes_counter)))
Хм, может для маски (учитывая, что это довольно сложная для пониманию сущность) тогда отдельный класс создать? В котором спрятать все эти нетривиальные операции.

2021-05-24 10:47 UTC, nicl-nno commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Так а что показывает флаг 0 или 1? С длиной пути понятно.

2021-05-24 11:21 UTC, Dreamlone commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Он ничего не показывает, он нужен только для того, чтобы такой вот составной флаг "0.1" был уникальным для каждой OutputData. То есть может быть ситуация, когда OutputData1 прошла 2 узла, OutputData2 прошла2 узла, и OutputData3 прошла 1 узел (примем, что размер таблиц с предсказаниями всегда 1). Тогда список с масками будет таким, если использовать только данные о количестве пройденных узлов - [2, 2, 1], что меня не устраивает. 

Можно конечно жестко задать условие, что у decompose операций должно быть строго 2 предка, но не лучше ли будет уметь просто "игнорировать" лишние узлы-предки?

2021-05-24 11:58 UTC, nicl-nno commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Т.е. по сути это не флаг, а что-то вроде input_id?

2021-05-24 12:26 UTC, Dreamlone commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Да, думаю такое название для него вполне подходит - изменю тогда название переменной со следующим коммитом

2021-05-25 09:26 UTC, Dreamlone commented on fedot/core/data/merge.py
> +        current_flag_base = 0
Изменил логику формирования маски, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/303/commits/f5a76c195f0882273796efeb118a8820b991d261). Теперь маска хранится в виде словаря. И все необходимые методы для преобразования маски положены в новый датакласс [DataInfo](https://github.com/nccr-itmo/FEDOT/pull/303/commits/fb53e13d518e4f4058b98087eb97abf782a22029).

2021-05-25 09:28 UTC, Dreamlone commented on fedot/core/data/merge.py
> +                                    '.', str(output.nodes_counter)))
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/303/commits/fb53e13d518e4f4058b98087eb97abf782a22029), сделал класс DataInfo, в котором хранятся в том числе поля "is_main_target", "data_flow_length" и "masked_features"

2021-05-25 12:31 UTC, nicl-nno commented on fedot/core/data/metadata.py
> +    masked_features: Optional[dict] = None
Может это назвать features_mask? Это же не сами признаки, а только маска для них

2021-05-25 12:32 UTC, nicl-nno commented on fedot/core/data/data.py
> +        self.metadata.data_flow_length = new_value
А это методы точно надо пробрасывать на уровень data? Может им внутри metadata и быть (если они вообще нужны и не обойтись прямым доступом к полям).

2021-05-26 10:47 UTC, J3FALL requested changes

2021-05-26 15:38 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +    """
Тут честно я даже не знаю что сделать. Я понял твою точку зрения и согласен, но вот что ты описал, это именно то, что от этого класса и требуется. Его я сделал в первую очередь, чтобы этот датакласс был универсальным контейнером для всяких дополнительных полей для данных (и способов их обработки). "добавил свое новое поле и забыл" - это как раз, то для чего это сделано.

Просто я рассчитываю на то, что этот класс будет пополняться новыми полями либо очень медленно, либо вообще не будет - просто область его применения очень специфична. Могу поменять название например на "FlowInfo", но честное слово, не уверен.

2021-05-26 16:17 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:















* In the file [`test/unit/data/test_data_info.py`](https://github.com/nccr-itmo/FEDOT/blob/26b79d6ecc9dd0b12bba4ebb401042ac9282e3b8/test/unit/data/test_data_info.py):

> [Line 65:1](https://github.com/nccr-itmo/FEDOT/blob/26b79d6ecc9dd0b12bba4ebb401042ac9282e3b8/test/unit/data/test_data_info.py#L65): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-05-26 16:19 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +    masked_features: Optional[dict] = None
Согласен, так звучит лучше, [исправил](https://github.com/nccr-itmo/FEDOT/pull/303/commits/6ebf32429814de8dff7923263cb8f99686569c00)

2021-05-26 16:20 UTC, Dreamlone commented on fedot/core/data/data.py
> +        self.metadata.data_flow_length = new_value
И правда это оно)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/303/commits/51ecbaaba059b7f6cf34380bdb959752e7dee250#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL159-L172). Теперь все делается напрямую через поля безо всяких методов

2021-05-26 16:21 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +import numpy as np
Пока [сделал](https://github.com/nccr-itmo/FEDOT/pull/303/commits/51ecbaaba059b7f6cf34380bdb959752e7dee250#diff-1d639a22115d88875f3bd0b424fe95daaf43004b84c07dc6bf323b585efb789c) как data_info. Но как я понял, по названию и скрипта и класса мы еще решаем (см. комментарий чуть ниже)

2021-05-26 16:23 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +    def calculate_data_flow_len(self, outputs):
Сделал отдельный файл для тестирования этого блока (раз выделили отдельный датакласс). Там есть проверка на то, работает ли этот метод корректно, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/303/commits/26b79d6ecc9dd0b12bba4ebb401042ac9282e3b8#diff-dc00eb0d7046e2541dfbf457efcce021baed14a87ccfb2b1057f2d505c757c8e)

2021-05-26 16:24 UTC, nicl-nno approved these changes

2021-05-26 16:25 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +        comp_list = np.core.defchararray.add(input_ids, flow_lens)
Вроде рабочее решение в одну строчку - сам благодаря гугл узнал про этот метод. Что он делает можно посмотреть в тестах, добавил тест на него, см. [здесь](https://github.com/nccr-itmo/FEDOT/pull/303/commits/26b79d6ecc9dd0b12bba4ebb401042ac9282e3b8#diff-dc00eb0d7046e2541dfbf457efcce021baed14a87ccfb2b1057f2d505c757c8e).

2021-05-27 10:19 UTC, J3FALL commented on fedot/core/data/metadata.py
> +    def calculate_data_flow_len(self, outputs):
норм

2021-05-27 10:44 UTC, J3FALL commented on fedot/core/data/metadata.py
> +    """
Ок, предлагаю что-то в стиле SupplementaryData и в описании к классу добавить: "A class that stores variables for for internal purposes in core during fit and predict. For instance, to manage dataflow properties"

2021-05-27 10:47 UTC, J3FALL approved these changes

2021-05-27 11:12 UTC, Dreamlone commented on fedot/core/data/metadata.py
> +    """
[Done](https://github.com/nccr-itmo/FEDOT/pull/303/commits/30328ef493dba6b059bc3edb6fcf3c56f0c91fd8)

2021-05-27 12:08 UTC, merged