Extend sensitivity analysis
nccr-itmo/FEDOT pull request #321
Opened 2021-05-31 17:28 UTC by BarabanovaIrina

What's new:
- Add ChainSensitivityAnalysis facade to allow application of structural and non-structural analysis approaches together.
- Add ChainNonStructureAnalyze to apply MultiOperationsAnalysis: apply Sobol method to all the hyperparameters of all chain operations. [TODO: Unite all the possible non-structural operations under one type]
- Add Multi-Times-Analysis(still looking for a better name) to decrease the chain size, using ChainStructureAnalysis.

2021-05-31 19:11 UTC, nicl-nno requested changes
Потом ещё детальнее позапускаю

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        print('finish MTA')
Здесь и далее логгер стоит вызывать

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        return total_nodes_deleted / original_chain_len
Если это какая-то метрика - лучше её отдельно считать.

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        self._visualize(name=self.case_name, path=result_path)
Наверное стоит сделать опцию отключения визуализации

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        visualiser.visualise(self.chain, save_path=image_path)
Можно просто self.chain.show(image_path)

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def sample(self, *args) -> Union[Union[List[Chain], Chain], np.array]:
А зачем вложенный Union?

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +class OneOperationAnalyze(NodeAnalyzeApproach):
Тоже не очень понятно, про что это. Про гиперпараметры?

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.manager_dict = {}
А почему так называется?

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.problem: Problem = OneOperationProblem(operation_types=[self.operation_type])
Странная нотация с двоеточием прямо в коде.

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def get_operation_response_matrix(self, samples: List[dict], node_id: int):
Если это внутренние методы, то стоит их пометить как private.

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/problem.py
> +class OneOperationProblem(Problem):
Не очень понятно, чем именно problem-классы отличаются от analyze-классов. 
Ожидал бы тут увидеть описание задачи, но вроде это не вполне оно.

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/problem.py
> +            'min_child_weight': [1, 21]
Вроде у нас такой список уже есть в другом месте кода?

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/structure_sensitivity.py
>  def get_nodes_degrees(chain: Chain):
А что тут имеется в виду под degrees?

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +
Потерялось описание

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +        return np.array(operation_response_matrix)
Кажется это не заявленный List[List[dict]]

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +                                            y_pred=prediction.predict)
Это бы куда-то вынести (ну или использовать существующие метрики от композера)
Вроде для этого выше есть get_metric.

2021-05-31 19:11 UTC, nicl-nno commented on fedot/sensitivity/non_structure_sensitivity.py
> +                 approaches: Optional[List[Type[MultiOperationsAnalyze]]] = None,
А что тут значит Type?

2021-06-01 10:42 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +        self._non_structure_analyze = ChainNonStructureAnalyze(chain=chain,
Да, тоже нужно более понятное название, с учетом, что могут найтись еще другие методы

2021-06-01 10:57 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        self._visualize(name=self.case_name, path=result_path)
А зачем, если это также наглядно дает понять сразу, какая модель в цепочке отвалилась нежели сравнивать два файла с метриками (предыдущий и текущий)?

2021-06-01 11:01 UTC, nicl-nno commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        self._visualize(name=self.case_name, path=result_path)
Не всегда же нужно, чтобы какие-то доп. файлы генерировались.
Например, если мы это интегрируем в композер (как этап пост-обработки модели) - то SA по сути в автоматическом режиме будет использоваться, где картинки не особо важны.

2021-06-01 11:04 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def sample(self, *args) -> Union[Union[List[Chain], Chain], np.array]:
Ну Union вроде как принимает два значения, а у меня их суммарно 3 List[Chain], Chain, np.array. 

Сама по себе задумка стременная, понимаю. Это связано, что для sample для Deletion возвращает одну цепочку с удаленным выбранным узлом, Replace с кучей замененных, а в Operation вообще семплы гиперпараметров. Как вариант, вызывать конвертацию (присвоение новых гиперпараметров к цепочкам) внутрь метода sample. 

Я тогда оставляла чистые значения, чтобы потом боксплоты рисовать, сейчас это вроде как больше не нужно.

2021-06-01 11:10 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/problem.py
> +class OneOperationProblem(Problem):
Добавлю докстринг. Но вообще это Problem это такой перевод интерфейса SALib на более удобный для использования, чтобы не хранить все в словарях, как в [самой библиотеке](https://salib.readthedocs.io/en/latest/getting-started.html#testing-installation)

2021-06-01 11:12 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def sample(self, *args) -> Union[Union[List[Chain], Chain], np.array]:
Хм, в документации вроде есть примеры с тремя.

![image](https://user-images.githubusercontent.com/5711814/120313921-52f3b480-c2e3-11eb-8b4f-08978d13ca2b.png)

2021-06-01 11:13 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def sample(self, *args) -> Union[Union[List[Chain], Chain], np.array]:
>Как вариант, вызывать конвертацию (присвоение новых гиперпараметров к цепочкам) внутрь метода sample

Ну да, выглядит что так будет понятнее. Боксплоты если что можно и обратным преобразование chain-ов получить.

2021-06-01 11:14 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/problem.py
> +            'min_child_weight': [1, 21]
Да, но он там привязан к объектам hyperopt (типа hp.choice, hp.uniform). Кроме того для некоторых параметров даны не граничные значения, а просто все значения, из которых можно выбирать + добавлен какой-то label. 

В целом, тут просто можно еще раз подумать, какую библиотеку для SA гиперпараметров стоит использовать, потому что SALib я выбрала по причине того, что нужно было поскорее и попроще.

2021-06-01 11:15 UTC, BarabanovaIrina commented on fedot/sensitivity/structure_sensitivity.py
>  def get_nodes_degrees(chain: Chain):
Степень(валентность) узла в графе, т.е. количество его связей.

2021-06-01 11:21 UTC, BarabanovaIrina commented on fedot/sensitivity/non_structure_sensitivity.py
> +                 approaches: Optional[List[Type[MultiOperationsAnalyze]]] = None,
что должен быть List с экземплярами класса MultiOperationsAnalyze. Если использовать без Type, то будет подразумеваться список классов, а не их экземпляров. Тут я просто по аналогии со структурными подходами сделала List[Type[NodeAnalyzeApproach]], потому что там несколько подходов объединены под одним классом(NodeAnalyzeApproach). 
Поэтому я и подумала, что для дальнейшего развития, нужно что-то типа NodeAnalyzeApproach только для подходов неструктурного анализа, от которых будет наследоваться MultiOperationsAnalyze.

2021-06-01 15:39 UTC, BarabanovaIrina commented on fedot/sensitivity/non_structure_sensitivity.py
> +                 approaches: Optional[List[Type[MultiOperationsAnalyze]]] = None,
Хотя не, бред какой-то. Просто где-то видимо мне попался случай, где без Type, почему-то не обошлось. А тут скорее всего действительно не нужен.

2021-06-01 17:17 UTC, J3FALL requested changes

2021-06-01 17:17 UTC, J3FALL commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +    def __init__(self, chain: Chain, train_data: InputData, test_data: InputData,
Здесь тоже не помешал бы docstring

2021-06-01 17:17 UTC, J3FALL commented on fedot/sensitivity/operations_sensitivity/problem.py
> +    operation_params_with_bounds_by_operation_name = {
Этот словарь для границ SA я бы упрятал в json + мб стоит подумать о передаче своих границ параметров.
Но мб я пока не весь код посмотрел, и это уже реализовано

2021-06-01 17:17 UTC, J3FALL commented on test/unit/test_sensitivity.py
> +    assert analyze_method.called
В общем, мне немного не хватило примера SA для гиперпараметров.
По пунктам, как это работает и т.д.

2021-06-02 19:27 UTC, nicl-nno commented on fedot/sensitivity/structure_sensitivity.py
>  def get_nodes_degrees(chain: Chain):
Может это вынести в GraphOperator тогда?

2021-06-03 15:58 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.problem: Problem = OneOperationProblem(operation_types=[self.operation_type])
Странно тем, что это не по-питоновски?
Если делать в конструкторе, то получается, что нужно сделать так:
<img width="572" alt="Screenshot 2021-06-03 at 18 51 32" src="https://user-images.githubusercontent.com/29018907/120674434-c1c83d80-c49c-11eb-9693-7c154393d063.png">

Или дефолтное значение не None. Инициализировать сразу не получится, так как нужен operation type, который можно достать из только из node, а она передается в метод.

2021-06-03 16:01 UTC, nicl-nno commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.problem: Problem = OneOperationProblem(operation_types=[self.operation_type])
Ну я скорее к тому, что есть ли необходимость явно определять типы для переменных класса? 
Вроде во всех остальных местах так не делали.

2021-06-03 17:08 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +        return np.array(operation_response_matrix)
List[List[dict]]  это для входного параметра, а не для выходного. Или про что-то другое?

2021-06-03 17:31 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +        self._non_structure_analyze = ChainNonStructureAnalyze(chain=chain,
Вообще получается, что это даже не разделение на структурные и неструктурные, тут скорее разделение на анализ, в котором изменение происходит внутри узла или во всей цепочке. Потому что те же самые гиперпараметры можно анализировать как в рамках одной модели, так и в рамках всей цепочки.

Но в данном случае пока выходит так, что это действительно больше ChainHyperparamsAnalyze, но это какая-то жесткая привязка. Идея то в том, чтобы потом можно было тут же использовать и другие подходы, помимо анализа гиперпараметров всей цепочки, даже если потенциально таких подходов на данный момент нет.

2021-06-03 17:51 UTC, nicl-nno commented on fedot/sensitivity/chain_sensitivity_facade.py
> +        self._non_structure_analyze = ChainNonStructureAnalyze(chain=chain,
Мб тогда ChainAnalyzis и NodesAnalyzis?

2021-06-08 08:08 UTC, pep8speaks commented
Hello @BarabanovaIrina! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:























* In the file [`fedot/sensitivity/nodes_sensitivity.py`](https://github.com/nccr-itmo/FEDOT/blob/ed6407ced6cf6f534a329f9fc9bda4697b7196da/fedot/sensitivity/nodes_sensitivity.py):

> [Line 76:68](https://github.com/nccr-itmo/FEDOT/blob/ed6407ced6cf6f534a329f9fc9bda4697b7196da/fedot/sensitivity/nodes_sensitivity.py#L76): [E502](https://duckduckgo.com/?q=pep8%20E502) the backslash is redundant between brackets

2021-06-08 08:13 UTC, BarabanovaIrina commented on test/unit/test_sensitivity.py
> +    assert analyze_method.called
[Дополнены](examples/sensitivity_analysis/run_cases.py) имеющиеся кейсы по SA возможностью запускать их с ChainSensitivityAnalisis, NodesAnalysis, ChainAnalysis
Отдельный [пример](examples/sensitivity_analysis/complex_analysis_with_requirements.py) с ChainSensitivityAnalisis и SensitivityAnalysisRequirements
Отдельный [пример](examples/sensitivity_analysis/mta_example.py) с MTA

2021-06-08 08:15 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/problem.py
> +    operation_params_with_bounds_by_operation_name = {
[Убран](fedot/sensitivity/operations_hp_sensitivity/params_bounds.json) в json
Передача параметров пока не сделана, но в целом, сейчас это можно сделать, потому как появился класс SensitivityAnalysisRequirements, в который как раз можно всякие детали к анализу передавать.

2021-06-08 08:16 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +    def __init__(self, chain: Chain, train_data: InputData, test_data: InputData,
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-f964bb5327684663daa093ffd72ec95b10d9abd12f665aea0bfda892fd07d402R19-R32) + переименован класс

2021-06-08 08:17 UTC, BarabanovaIrina commented on fedot/sensitivity/non_structure_sensitivity.py
> +class ChainNonStructureAnalyze:
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R13-R29) + переименован

2021-06-08 08:18 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        while worst_node_score > 1.0 + delta and len(self.chain.nodes) > 2:
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-4ad70f2323662354c9531d24aef93fe56c442c3a492eb7886b4220af9820a7a5R14-R33) namedtuple

2021-06-08 08:19 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +class ChainSensitivityAnalysis:
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-2b0d56afa9738a4e09df0bbc39d81e406da357d0be92791bcc1ed14846651e93R15-R29)

2021-06-08 08:23 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +                                            y_pred=prediction.predict)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-f964bb5327684663daa093ffd72ec95b10d9abd12f665aea0bfda892fd07d402R112-R113) на метрику для композера

get_metric() есть только у NodeAnalysisApproach

2021-06-08 08:25 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/multi_operations_sensitivity.py
> +        return np.array(operation_response_matrix)
Входной параметр теперь типа List[Chain], на выход все так же np.array. Метода [_get_response_matrix](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-f964bb5327684663daa093ffd72ec95b10d9abd12f665aea0bfda892fd07d402R107-R116)

2021-06-08 08:27 UTC, BarabanovaIrina commented on fedot/sensitivity/structure_sensitivity.py
>  def get_nodes_degrees(chain: Chain):
[Функция](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-8ef0acf4aa77ee601ecdaf984b991b8b623c763ed831f712d3f0d5bb83bbc384R117-R123) перенесена в GraphOperator.
Соответсвующий [вызов](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-e196b2900b8abaeb3ebc41d7f5d3ca46abac0dcb7c5a9d89e391bb514a43341cL128-R117)

2021-06-08 08:28 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/problem.py
> +            'min_child_weight': [1, 21]
Пока [перенесен](fedot/sensitivity/operations_hp_sensitivity/params_bounds.json) в json

2021-06-08 08:31 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def get_operation_response_matrix(self, samples: List[dict], node_id: int):
Исправлено и в [multi](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-f964bb5327684663daa093ffd72ec95b10d9abd12f665aea0bfda892fd07d402R107) и в [one](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-eaf4264b3032eef56e376c6f503f9339e60ea66c0518f6aec8a825c338b1ac78R95)

2021-06-08 08:32 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.problem: Problem = OneOperationProblem(operation_types=[self.operation_type])
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-eaf4264b3032eef56e376c6f503f9339e60ea66c0518f6aec8a825c338b1ac78R53)

2021-06-08 08:35 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +        self.manager_dict = {}
Обычно встречала, что в названиях всякого рода объектов, которые необходимо лочить для использования многопоточности, встречается manage, или это с LoggerManager запомнила. [Переименовано](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-eaf4264b3032eef56e376c6f503f9339e60ea66c0518f6aec8a825c338b1ac78R38).

2021-06-08 08:36 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +class OneOperationAnalyze(NodeAnalyzeApproach):
Да, [попыталась](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-eaf4264b3032eef56e376c6f503f9339e60ea66c0518f6aec8a825c338b1ac78R23) внести немного ясности

2021-06-08 08:38 UTC, BarabanovaIrina commented on fedot/sensitivity/operations_sensitivity/one_operation_sensitivity.py
> +    def sample(self, *args) -> Union[Union[List[Chain], Chain], np.array]:
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-eaf4264b3032eef56e376c6f503f9339e60ea66c0518f6aec8a825c338b1ac78R70). Теперь конвертация из чистых значений в цепочки с новыми параметрами происходит внутри метода sample. Также и в [multi](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-f964bb5327684663daa093ffd72ec95b10d9abd12f665aea0bfda892fd07d402R83)

2021-06-08 08:41 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        visualiser.visualise(self.chain, save_path=image_path)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-4ad70f2323662354c9531d24aef93fe56c442c3a492eb7886b4220af9820a7a5L88-R115)
В [примерах](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-e9502fcd57ee11e59ba05999f36c72fc41fd56f13431595aab2cfc4981e72d9dR38) тоже исправлено

2021-06-08 08:44 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        self._visualize(name=self.case_name, path=result_path)
[Добавлен](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-4ad70f2323662354c9531d24aef93fe56c442c3a492eb7886b4220af9820a7a5L66-R99) флаг.

В SensitivityAnalysisRequirements тоже есть флаг is_visualize, но пока не добавлено использование requirements к MTA. MTA пока отдельно существует.

2021-06-08 08:45 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        return total_nodes_deleted / original_chain_len
Вынесена в отдельный [метод](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-4ad70f2323662354c9531d24aef93fe56c442c3a492eb7886b4220af9820a7a5R89-R92)

2021-06-08 08:45 UTC, BarabanovaIrina commented on fedot/sensitivity/deletion_methods/multi_times_analysis.py
> +        print('finish MTA')
Исправлено [здесь](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-4ad70f2323662354c9531d24aef93fe56c442c3a492eb7886b4220af9820a7a5L63-R88) и в других местах.

2021-06-08 08:48 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +        self._non_structure_analyze = ChainNonStructureAnalyze(chain=chain,
Да, пока оставила так. [ChainAnalysis](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-7eb8478649194b8b6310607a9e2feafe096caea98d0b2c8ab5c39d80c7b6ff38R13-R44) - это класс, который анализирует подходами, в которых Chain подразумевается как black-box (если можно так сказать). 
Бывший ChainStructureAnalysis теперь [NodesAnalysis](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-e196b2900b8abaeb3ebc41d7f5d3ca46abac0dcb7c5a9d89e391bb514a43341cL24-R17)

2021-06-08 08:51 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +                 nodes_ids_to_analyze: List[int] = None, path_to_save=None,
Исправлено [тут](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-2b0d56afa9738a4e09df0bbc39d81e406da357d0be92791bcc1ed14846651e93R34) и везде. Раньше видимо была привязка к старому тюнингу, в котором ноды по индексу выбирались. Теперь TuningApproach был удален. 

Также в NodesAnalysis был убран флаг all_nodes, показался излишним. Теперь нужно либо передать ноды, в противном случае будет произведен анализ всех узлов.

2021-06-08 08:52 UTC, BarabanovaIrina commented on fedot/sensitivity/chain_sensitivity_facade.py
> +                 approaches=None,
[Добавлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/ed6407ced6cf6f534a329f9fc9bda4697b7196da#diff-2b0d56afa9738a4e09df0bbc39d81e406da357d0be92791bcc1ed14846651e93R32-R33)

2021-06-08 17:28 UTC, nicl-nno approved these changes

2021-06-12 21:12 UTC, nicl-nno commented on test/unit/test_sensitivity.py
>  # @pytest.mark.skip('Works for more than 10 minutes - TODO improve it')
А этот комментарий ещё актуален?

2021-06-14 09:18 UTC, BarabanovaIrina commented on test/unit/test_sensitivity.py
>  # @pytest.mark.skip('Works for more than 10 minutes - TODO improve it')
Нет, [убран](https://github.com/nccr-itmo/FEDOT/pull/321/commits/8b04d7978a1528dc9bf54a8d4fd0d6eb210ac2ef#diff-c8dbf1c141ebfd274d78f7bd731baabd5827eb8698be71ad70b4e3588671596aL212)

2021-06-14 09:35 UTC, BarabanovaIrina commented on test/unit/test_sensitivity.py
>  # @pytest.mark.skip('Works for more than 10 minutes - TODO improve it')
К слову про вынесение дополнительной [функциональности](https://github.com/nccr-itmo/FEDOT/blob/sa-for-hp/fedot/sensitivity/operations_hp_sensitivity/one_operation_sensitivity.py#L64-L66)визуализации дисперсии для параметров: пока придется оставить как есть, потому что использует методы OneOperationHPAnalyze (_get_response_matrix, _apply_params_to_node), которые невыгодно делать статическими или дублировать.

2021-06-15 08:19 UTC, nicl-nno commented
В рамках совместимости с FEDOT.Web предложил ещё добавить сохрание метрик АЧ в JSON-файле с экспортированным Chain (если для него был выполнен анализ ч-ти)

2021-06-16 13:13 UTC, BarabanovaIrina commented
> В рамках совместимости с FEDOT.Web предложил ещё добавить сохрание метрик АЧ в JSON-файле с экспортированным Chain (если для него был выполнен анализ ч-ти)

[ Добавлено назначение рейтинга](examples/sensitivity_analysis/chain_export_with_sa.py) узлу в значении от 1 до 4, где 1 - неустойчивый узел и 4 - самый устойчивый на основе методов удаления и замены. 
<img width="394" alt="Screenshot 2021-06-16 at 16 10 02" src="https://user-images.githubusercontent.com/29018907/122225304-9d695980-cebd-11eb-8734-5923e47faaa0.png">

2021-06-18 10:18 UTC, BarabanovaIrina commented
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/321/commits/7d1b0c1bb08b91b6fceaba7864ff49909a77fb16#diff-357b2e99686383fc07a1a3113f1cf66bbc45a098a7991dcca72890e5d437752dL73-R73) условие для подсчета рейтинга.

2021-06-18 11:09 UTC, J3FALL commented on fedot/sensitivity/chain_sensitivity_facade.py
> +            non_structural_approaches = None
норм

2021-06-18 11:47 UTC, J3FALL approved these changes

2021-06-21 15:23 UTC, merged