Multitarget fix
nccr-itmo/FEDOT pull request #322
Opened 2021-06-02 13:10 UTC by Dreamlone

There was implemented new case with river levels forecasting. Add new case with multi-target regression task with chain composing. The innability of composer to process multitarget regression task was fixed. 

Also, there were investigated several papers aboul multi-tartget metric estimation. Good one can be accesed via [link](https://lirias.kuleuven.be/retrieve/584987/).

2021-06-02 14:40 UTC, nicl-nno commented on cases/multi_target_levels_forecasting.py
> +        plot_predictions(predicted_output, test_data)
Тут нужен более лаконичный пример с использованием API.
Если текущее не справляется - можно сделать это отдельно в рамках https://github.com/nccr-itmo/FEDOT/issues/306

2021-06-02 14:41 UTC, nicl-nno commented on cases/river_levels_prediction/river_level_case_composer.py
> +        print(f'{node.operation.operation_type} - {node.custom_params}')
А нужны ли вообще эти принты в рамках кейса? Если это удобный способ печатать структуру chain- можно создать соответствующий метод (или изменить _str__).

2021-06-02 14:50 UTC, nicl-nno commented on fedot/core/composer/metrics.py
> +                metric = cls.metric(reference_data, results)
Кажется лучше это в отдельную функцию вынести (да и часть с с ts_forecasting тоже).
Возвращать из этой функции можно reference_data и results

2021-06-02 14:51 UTC, nicl-nno requested changes
.

2021-06-04 11:06 UTC, Dreamlone commented on cases/multi_target_levels_forecasting.py
> +        plot_predictions(predicted_output, test_data)
Сделано, пример теперь оформлен через [api](https://github.com/nccr-itmo/FEDOT/pull/322/commits/6da304f3fbb5264f87cfa97cf0c9be9cdd95c8b2#diff-5f080f05d96aab5cdc73156adfcc2ca7d6cd35dbadb005a3d71e14614b02731b)

2021-06-04 12:20 UTC, Dreamlone commented on cases/river_levels_prediction/river_level_case_composer.py
> +        print(f'{node.operation.operation_type} - {node.custom_params}')
Вообще да, хотелось бы выводить то, какие параметры в узлах у операций получаются. Сделал метод "[display_structure](https://github.com/nccr-itmo/FEDOT/pull/322/commits/632f59b7832b998458b20d72e5e6e71bd99d9cd0#diff-f531f6aebd864a320d78a7369d86b8d8fd330665fced6295419574ff168664db)" у Chain

2021-06-04 12:21 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +                metric = cls.metric(reference_data, results)
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/322/commits/632f59b7832b998458b20d72e5e6e71bd99d9cd0#diff-7488db041ee4881f6441fe845b119323cb27e897f1694965bb978e1059228e66R51-R84)

2021-06-04 13:29 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +    def display_structure(self):
Просто print? Чтобы было понятно, что выведется текст в консоль

2021-06-04 13:30 UTC, nicl-nno commented on fedot/core/composer/metrics.py
> +    def ravel_convert(results, reference_data):
flatten_covert? Или у ravel есть какой-то смысл b за пределами numpy?

2021-06-04 13:32 UTC, nicl-nno approved these changes
Внес пару предложений по неймингу, но в целом норм.

2021-06-04 14:07 UTC, Dreamlone commented on fedot/core/chains/chain.py
> +    def display_structure(self):
[Заменил](https://github.com/nccr-itmo/FEDOT/pull/322/commits/5fe4594d68a0ec44c6e5c32304fe0ef62828ee25)

2021-06-04 14:08 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +    def ravel_convert(results, reference_data):
Да, вроде бы "ravel" термин довольно специфический, и не в numpy стоит избежать его использования - [исправил](https://github.com/nccr-itmo/FEDOT/pull/322/commits/5fe4594d68a0ec44c6e5c32304fe0ef62828ee25)

2021-06-05 07:50 UTC, J3FALL requested changes

2021-06-05 07:50 UTC, J3FALL commented on cases/multi_target_levels_forecasting.py
> +    plt.show()
Я бы для удобства извлек тут 2 функции

2021-06-05 07:50 UTC, J3FALL commented on cases/multi_target_levels_forecasting.py
> +    run_multi_output_case(path_file, vis=True)
А можно еще подобный пример, но в качестве теста?
Кажется, multi-target-регрессии у нас как раз нет в тестах

2021-06-05 07:50 UTC, J3FALL commented on fedot/core/chains/chain.py
> +            print(f'{node.operation.operation_type} - {node.custom_params}')
Это сложно протестировать, но банальный вызов этой функции также можно покрыть

2021-06-05 07:50 UTC, J3FALL commented on fedot/core/composer/cache.py
> +            os.remove(file)
Вытащи в отдельную функцию тогда, чтобы не писать комментарий

2021-06-05 07:50 UTC, J3FALL commented on fedot/core/composer/metrics.py
> +        """ Method prepare data for metric evaluation """
кажется, тут грамматическая ошибка в описании

2021-06-05 07:50 UTC, J3FALL commented on fedot/core/composer/metrics.py
> +        """ Method prepare data for metric evaluation """
И добавь, плз, сюда тоже тест.
Мне кажется, этот метод может еще измениться в будущем

2021-06-05 07:50 UTC, J3FALL commented on fedot/core/data/data.py
> +                                                  data_array)
На эти две ветки тоже можно написать соответствующий тест

2021-06-07 08:24 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





























* In the file [`test/unit/composer/test_quality_metrics.py`](https://github.com/nccr-itmo/FEDOT/blob/c6680bcf8c1fdd2919fbee6928549e88aa01791d/test/unit/composer/test_quality_metrics.py):

> [Line 103:1](https://github.com/nccr-itmo/FEDOT/blob/c6680bcf8c1fdd2919fbee6928549e88aa01791d/test/unit/composer/test_quality_metrics.py#L103): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2021-06-07 08:28 UTC, Dreamlone commented on cases/multi_target_levels_forecasting.py
> +    plt.show()
Сделал [две функции](https://github.com/nccr-itmo/FEDOT/pull/322/commits/368797c2a448de9db7670e3c2f234adc9a096960)

2021-06-07 08:31 UTC, Dreamlone commented on cases/multi_target_levels_forecasting.py
> +    run_multi_output_case(path_file, vis=True)
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/322/commits/5806d555259b3f0f7db277b3107e16409eaea392?file-filters%5B%5D=.py#diff-4308e63e89dc1627e05af132ed40cc732c63d4f331bc60fcd806be6e043d2cb4)в качестве теста в tasks/test_regression.py, но по идее его можно разместить и в composer/test_composer.py. Так весь этот фикс был как раз задуман именно потому, что композер не справлялся с задачей многомерной регрессии (вне композера у цепочек не возникало никаких проблем).

P.S. В этом [коммите](https://github.com/nccr-itmo/FEDOT/pull/322/commits/d52720cc1118f7828421ebff9a615ab84fa3f47b#diff-4308e63e89dc1627e05af132ed40cc732c63d4f331bc60fcd806be6e043d2cb4L89-L97) немного уменьшил дублирование кода

2021-06-07 08:31 UTC, Dreamlone commented on fedot/core/chains/chain.py
> +            print(f'{node.operation.operation_type} - {node.custom_params}')
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/322/commits/00120da05eb0dbfe0ab5e055443a962641accc0c#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8d) соответствующий тест.

2021-06-07 08:33 UTC, Dreamlone commented on fedot/core/composer/cache.py
> +            os.remove(file)
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/322/commits/d52720cc1118f7828421ebff9a615ab84fa3f47b#diff-c50019984c360138cba52c016981875b18619ceb5defce4569bb4d33d0326e3d)

2021-06-07 08:35 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +        """ Method prepare data for metric evaluation """
По поводу ошибки не понял (и Grammarly тоже) :) 
На всякий случай добавил "s" в prepare. Тест [добавил](https://github.com/nccr-itmo/FEDOT/pull/322/commits/d52720cc1118f7828421ebff9a615ab84fa3f47b#diff-6c1ae426c475ab8a9da8c1216d56d70a44c88ef0280208942bca070e6ca68cc0R93-R102)

2021-06-07 08:36 UTC, Dreamlone commented on fedot/core/data/data.py
> +                                                  data_array)
[Done](https://github.com/nccr-itmo/FEDOT/pull/322/commits/d52720cc1118f7828421ebff9a615ab84fa3f47b#diff-6c1ae426c475ab8a9da8c1216d56d70a44c88ef0280208942bca070e6ca68cc0R93-R102)

2021-06-07 09:59 UTC, J3FALL commented on test/unit/tasks/test_regression.py
Поправь импорты, есть неиспользуемые

2021-06-07 09:59 UTC, J3FALL commented on fedot/core/composer/cache.py
> +            os.remove(file)
Я бы оформил ее в виде обычной (не static) функции, которая принимает на вход путь до folder-а и отчищает его.
А сам путь формировать в функции выше, где происходит вызов clear_folder
![image](https://user-images.githubusercontent.com/7864250/120997724-1ebf3e80-c790-11eb-9d21-8d0714ba5997.png)

2021-06-07 10:25 UTC, Dreamlone commented on fedot/core/composer/cache.py
> +            os.remove(file)
Надеюсь правильно тебя понял - см. [тут](https://github.com/nccr-itmo/FEDOT/pull/322/commits/02f13e2da02fefb300020da140005989b378c351)

2021-06-07 10:27 UTC, Dreamlone commented on test/unit/tasks/test_regression.py
Если ты про строчку номер 12
![image](https://user-images.githubusercontent.com/52418437/121001463-fcc7bb00-c793-11eb-9178-a35438b069b2.png)

то она используется в test_multi_target_regression_composing_correct. Не знаю, как сделать, чтобы она подсвечивалась (вроде видел подобные штуки и в других тестах у нас). Подскажи плиз, если знаешь как лучше будет сделать.

2021-06-07 10:29 UTC, J3FALL commented on fedot/core/composer/cache.py
> +            os.remove(file)
Угу, только описание поправь
![image](https://user-images.githubusercontent.com/7864250/121001860-634cd900-c794-11eb-9f0a-097c5a6bac0e.png)

2021-06-07 10:31 UTC, J3FALL commented on test/unit/tasks/test_regression.py
Хм, да, действительно, не заметил.
Не знаю, как исправить эту штуку, мб дело в форматировании внутри Pycharm и нужно его обновить.
Но у меня та же проблема.

2021-06-07 10:31 UTC, J3FALL approved these changes

2021-06-07 10:32 UTC, nicl-nno commented on fedot/core/composer/cache.py
> +            os.remove(file)
Ну тогда уж и deletes. Алсо, я бы не начинал описание с Methods - вроде и так понятно, что это он.

2021-06-07 10:37 UTC, Dreamlone commented on fedot/core/composer/cache.py
> +            os.remove(file)
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/322/commits/6ed11c59f3a88efcc7189f722c8f75f34e82f7c7#diff-c50019984c360138cba52c016981875b18619ceb5defce4569bb4d33d0326e3d)

2021-06-07 10:58 UTC, merged