Custom graph model optimization - refactored version
nccr-itmo/FEDOT pull request #324
Opened 2021-06-03 11:24 UTC by nicl-nno

To achieve to applicability of the gp_optimizer to structural learning of custom graph-based models, the following changes are implemented:

-Graph/Vertice as prototypes for Chain/Node
-OptGraph/StructNode as obtimisation object
- adapter to converrt Chain to OptGraph and back
-simplified example of custom model learning
-custon constraints customization for implemented
-custom mutain and crossover can be used

Now gp_optimizer can be used for any graph-based optimization problems.

Proposal: rename Chain to Pipeline

Old version: https://github.com/nccr-itmo/FEDOT/pull/269

2021-06-03 11:24 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`examples/bayesian_network_as_custom_task.py`](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/examples/bayesian_network_as_custom_task.py):

> [Line 35:42](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/examples/bayesian_network_as_custom_task.py#L35): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 35:42](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/examples/bayesian_network_as_custom_task.py#L35): [E262](https://duckduckgo.com/?q=pep8%20E262) inline comment should start with '# '

















* In the file [`fedot/core/chains/chain_template.py`](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/chains/chain_template.py):

> [Line 46:17](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/chains/chain_template.py#L46): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '





































* In the file [`fedot/core/dag/graph_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/dag/graph_operator.py):

> [Line 14:31](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/dag/graph_operator.py#L14): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 15:31](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/dag/graph_operator.py#L15): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

* In the file [`fedot/core/dag/node_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/dag/node_operator.py):

> [Line 6:1](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/fedot/core/dag/node_operator.py#L6): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

















* In the file [`test/unit/composer/test_selection_operators.py`](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/test/unit/composer/test_selection_operators.py):

> [Line 6:56](https://github.com/nccr-itmo/FEDOT/blob/5d319d899a0cf2e4d462935d7443308a6469b910/test/unit/composer/test_selection_operators.py#L6): [E271](https://duckduckgo.com/?q=pep8%20E271) multiple spaces after keyword

2021-06-10 12:05 UTC, nicl-nno commented on fedot/core/composer/composing_history.py
> +            print(f'Cannot add to history: {ex}')
Проблемы при экспорте в chain_to_template (не обязательно из-за графовых задач, см https://github.com/nccr-itmo/FEDOT/issues/300)

2021-06-10 12:06 UTC, nicl-nno commented on fedot/core/dag/vertex.py
> +        return self._operator.distance_to_primary_level()
Ну да, т.к. графы ациклические. Primary - это те ноды, у которых нет предков. Расстояние, соответственно, всегда определено.

2021-06-10 12:09 UTC, nicl-nno commented on fedot/core/chains/chain_template.py
> +            return
>Вопрос - я так понимаю, проблема в том, что, например, у байесовской сети root может быть не определен?

В теории, даже для ML-пайплайна может быть ситуация, когда root несколько - например, когда пайплайн для классификации и регресии одновременно. Но сейчас это действительно не поддерживается.

>доработать экспорт моделей, добавив абстракцию для Graph-объектов

Да, это надо будет доделать в рамках PR-а, chain.root_node[0] поставил как заглушку.

>Либо ограничить экспорт только объектов типа Chain/Pipeline

C этим сложно, т.к. экспорт в Template нужен для сохранения истории оптимизации.

2021-06-12 16:55 UTC, nicl-nno commented on examples/data/geo_encoded.csv
> +Tectonic regime,Period,Lithology,Structural setting,Hydrocarbon type,Gross,Netpay,Porosity,Permeability,Depth
Да. [Заменил](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-aa991f0f169c0c45846985425069d0a7560b1429ce8e3ab23036ad098f010f62R1) на более абстрактные названия (V1-V10), раз сеть все равно не строится.

2021-06-12 16:55 UTC, nicl-nno commented on examples/graph_model_optimization.py
> +                    graph_generation_params: GraphGenerationParams, max_depth: int = None):
Спрятал в kwargs.

2021-06-12 16:55 UTC, nicl-nno commented on examples/graph_model_optimization.py
> +class Network(Graph):
Вынес в fedot-based-cases.

2021-06-12 16:56 UTC, nicl-nno commented on fedot/core/chains/chain_convert.py
> +def chain_as_nx_graph(chain: 'ChainStructure'):
Осталось от прошлого варианта, поменял на Graph

2021-06-12 16:58 UTC, nicl-nno commented on fedot/core/chains/chain_validation.py
> +def custom_validate(graph: Graph, rules: List[Callable]):
Пока [сделал](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-2f2e614865e1064127283142c886afa070dd983bbbcd5b4555e35d55ad17efb2R23-R29) validate изначально кастомизируемым, и создал default_rules с набором правил по умолчанию.

Фабрику с "пресетами" предлагаю отложить до возникновения в ней реальной надобности - т.к. пока не оч. понятно, какие именно варианты в ней должны быть.

2021-06-12 16:58 UTC, nicl-nno commented on fedot/core/chains/node.py
> +        self._operator = NodeOperator(self)
Убрал

2021-06-12 16:58 UTC, nicl-nno commented on fedot/core/chains/node.py
> +                      **kwargs)
Можно, поменял на super

2021-06-12 16:58 UTC, nicl-nno commented on test/unit/graphs/test_graph.py
> +from copy import copy, deepcopy
Переименовал в dag

2021-06-12 16:59 UTC, nicl-nno commented on fedot/core/dag/node_operator.py
> +class NodeOperator:
Подумал и остановился на GraphNode вместо Vertex. Иначе возникает куча неоднозначностей с именованием, если Vertex-ы начинают пролезать на уровень Chain.

2021-06-12 17:00 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
> +    def visualise(self, chain: 'ChainStructure', save_path: Optional[str] = None):
Поменял на Graph

2021-06-12 17:00 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
>  class GraphOperator:
Поменял на Vertex  на GraphNode, чтобы обойти эту проблему (см. выше)

2021-06-12 22:42 UTC, nicl-nno commented on examples/graph_model_optimization.py
> +    run_bayesian()
Обновил пример.

Теперь так:
![image](https://user-images.githubusercontent.com/5711814/121790503-9f46ca80-cbe8-11eb-85db-ba248b733ba2.png)

2021-06-12 22:44 UTC, nicl-nno commented on fedot/core/chains/chain.py
> +        return all([(node.fitted_operation is not None) for node in self.nodes])
Добавил такой вот [тест](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-e7f4408d2f7ac2deacce152f67dc72ae7a81f65d90cc53f0d0311f7b294e6c8dR443-R455).

2021-06-12 22:45 UTC, nicl-nno commented on fedot/core/chains/chain_validation.py
> +def custom_validate(graph: Graph, rules: List[Callable]):
Добавил [тест](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-ec68067bf3a715aa0e161546db680b645b8fcaf283218bf2064ee9208f0f2832R354-R357)

2021-06-12 22:47 UTC, nicl-nno commented on fedot/core/dag/vertex.py
> +        self.operation = operation_type
Заменил на [content](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-e54796b27ec1332765525eb1271516fa0c1aac1f0c728d0394b2b6a6d015b425R14-R18), тоже же самое для OptNode.

В Node пайплайна добавил kwargs-обертку, чтобы не лопать интерфейс предка.

2021-06-12 22:54 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
> +class GraphVisualiser:
Разбил, вынес в visualization.

2021-06-25 14:34 UTC, J3FALL commented on examples/graph_model_optimization.py
> +    run_bayesian()
норм, у меня теперь работает

2021-06-25 14:51 UTC, J3FALL commented on fedot/core/dag/vertex.py
> +        self.operation = operation_type
Погоди, немного не понял, как это работает:
![image](https://user-images.githubusercontent.com/7864250/123442406-84f3f000-d5dd-11eb-948c-6fe0dccf93d1.png)

Я предполагал, что в GraphVertex (теперь GraphNode) есть поле content.
Но в Node остается поле operation, которая дублирует content по-сути.
При этом, не понял, можно ли создать Node с переданным параметром operation и content одновременно.

2021-06-25 14:55 UTC, nicl-nno commented on fedot/core/dag/vertex.py
> +        self.operation = operation_type
>Я предполагал, что в GraphVertex (теперь GraphNode) есть поле content.

Но operation - это обертка над content:
![image](https://user-images.githubusercontent.com/5711814/123443386-883bab80-d5de-11eb-8d4b-e66dc65128f8.png)

т.к. на уровне ноды пайплайна content - это как раз операция.

2021-06-25 15:02 UTC, J3FALL commented on fedot/core/composer/composing_history.py
> +            print(f'Cannot add to history: {ex}')
окей, понял. гляну эту задачу, что там с ней

2021-06-25 15:07 UTC, J3FALL commented on fedot/core/composer/visualisation.py
> +class GraphVisualiser:
ок, там скрипт пустой остался (в core/composer/visualisation.py)
стоит удолить

2021-06-25 15:10 UTC, J3FALL commented on fedot/core/dag/vertex.py
> +        self.operation = operation_type
Пардон, чутка не увидел ниже:
`super().__init__(nodes_from, content=operation)`

2021-06-25 15:21 UTC, J3FALL requested changes

2021-06-25 15:21 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    converter = GraphGenerationParams().adapter
Хм, а можно ли инициализировать адаптер напрямую, а не через GraphGenerationParams?
Глянул в конструктор, там вроде и нет какой-то специфики в инициализации адаптера

2021-06-25 15:21 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    converter = GraphGenerationParams().adapter
Ну и для точности - это адаптер, а не конвертер )
Хотя по логике примерно похоже

2021-06-25 15:21 UTC, J3FALL commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        return self.adapter.restore_as_template(opt_graph)
Вот тут не выглядит ли это как Gypsy паттерн?
https://habr.com/ru/post/217847/
Просто методы повторяют контент, делегируя действие адаптеру.
А сами вроде и ничего полезного не делают.

2021-06-25 20:59 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        return self.adapter.restore_as_template(opt_graph)
Это сделано только для того, чтобы в рамках оптимизатора можно было более коротко вызывать адаптер. 
Могу удалить, если считаешь лишним.

2021-06-25 21:00 UTC, nicl-nno commented on examples/chain_and_history_visualisation.py
> +    converter = GraphGenerationParams().adapter
>Хм, а можно ли инициализировать адаптер напрямую, а не через GraphGenerationParams?

Ну в GraphGenerationParams сохранен именно там адаптер, который мы хотим использовать. Там же может быть не только ChainAdapter. Или ты про другое?

2021-06-26 10:56 UTC, J3FALL commented on examples/chain_and_history_visualisation.py
> +    converter = GraphGenerationParams().adapter
А, понял, да
Может быть разная реализация адаптера внутри параметров

2021-06-26 10:57 UTC, J3FALL commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        return self.adapter.restore_as_template(opt_graph)
Мне кажется, что стоит удалить и заменить вызовы адаптера через _params.adapter.adapt_ и т.д.

2021-06-26 11:23 UTC, J3FALL requested changes

2021-06-26 11:23 UTC, J3FALL commented on fedot/api/main.py
> +            'max_arity' - max arity of the graph
Бтв, переименовать в пайплайн будешь в самом конце?
Или в отдельном pr-е?
Я думаю, что в fedot api работа идет именно с пайплайнами

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/dag/graph.py
> +        :param new_node: new Node object
Видимо, GraphNode должно быть

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/dag/graph.py
> +        :param new_node: 'GraphNode' object to replace
Тут, видимо, ошибка в описании?

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/dag/graph.py
> +        :param new_subroot: 'GraphNode' object to replace
тут тоже

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    while not is_correct_graph:
К вопросу об unexpected зависаниях в фреймворке - у нас вроде есть несколько while-блоков.
Мб логирование хотя бы добавить для этих блоков?
Мб выявим уязвимые места в генетическом алгоритме

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/optimisers/graph.py
> +# TODO implement OptNode->GraphNode conversion
Это TODO актуально?

2021-06-26 11:23 UTC, J3FALL commented on fedot/core/visualisation/opt_viz.py
> +# TODO refastor as opt visualizer
А чем отличаются GraphVisualizer и ChainVisualizer?

2021-06-26 11:26 UTC, nicl-nno commented on fedot/api/main.py
> +            'max_arity' - max arity of the graph
Думаю лучше в отдельном, чтобы как-то можно было понять, что тут менялось.

2021-06-26 12:25 UTC, nicl-nno commented on fedot/core/optimisers/graph.py
> +# TODO implement OptNode->GraphNode conversion
Да, проблема видна вот тут, например:

![image](https://user-images.githubusercontent.com/5711814/123512920-cc888380-d692-11eb-950c-60199c631020.png)

2021-06-26 17:32 UTC, nicl-nno commented on fedot/core/composer/visualisation.py
> +class GraphVisualiser:
Удолил.

2021-06-26 17:32 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        return self.adapter.restore_as_template(opt_graph)
Заменил.

2021-06-26 17:33 UTC, nicl-nno commented on fedot/api/main.py
> +            'max_arity' - max arity of the graph
Но именно тут поменял коммент.

2021-06-26 17:33 UTC, nicl-nno commented on fedot/core/dag/graph.py
> +        :param new_node: new Node object
fixed

2021-06-26 17:33 UTC, nicl-nno commented on fedot/core/dag/graph.py
> +        :param new_node: 'GraphNode' object to replace
fixed

2021-06-26 17:33 UTC, nicl-nno commented on fedot/core/dag/graph.py
> +        :param new_subroot: 'GraphNode' object to replace
fixed

2021-06-26 17:33 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    while not is_correct_graph:
Добавил [так](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R36-R46)

2021-06-26 17:33 UTC, nicl-nno commented on fedot/core/visualisation/opt_viz.py
> +# TODO refastor as opt visualizer
Переименовал 2-е в ChainEvolutionVisualiser. Т.к. там отрисовка не просто chain, а её изменений в ходе эволюции.

2021-06-28 10:52 UTC, nicl-nno commented on fedot/core/optimisers/graph.py
> +# TODO implement OptNode->GraphNode conversion
[Пофиксил](https://github.com/nccr-itmo/FEDOT/pull/324/files#diff-63687a0ad8364bd5e1bdf20da6d700e0ea7b6c38181e088dd67c46414c266971R169-R177) это, убрал TODO

2021-06-28 10:55 UTC, J3FALL commented on fedot/core/visualisation/opt_viz.py
> +# TODO refastor as opt visualizer
окей, увидел
тогда TODO можно убрать?

2021-06-28 10:58 UTC, J3FALL commented
Прогони же потом pep8 после ребейза
Там есть в паре моментов недостающие пробелы

2021-06-28 13:02 UTC, nicl-nno commented on fedot/core/visualisation/opt_viz.py
> +# TODO refastor as opt visualizer
Ага

2021-06-28 13:22 UTC, nicl-nno commented
> Прогони же потом pep8 после ребейза
> Там есть в паре моментов недостающие пробелы

Вроде всё поправил.

2021-06-28 13:27 UTC, J3FALL approved these changes

2021-06-29 14:36 UTC, J3FALL requested changes

2021-06-29 14:36 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        if 'imputation' not in self.operation_type:
Операция называется "simple_imputation" - сработает ли для этого случая?

2021-06-29 14:39 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        if 'imputation' not in self.operation_type:
Так я для того и добавил, чтобы для simple_imputation принудительный imputation не срабатывал. Т.к. это как раз тот тип единственный операции, где подавать данные с пропусками можно.

2021-06-29 14:41 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        if 'imputation' not in self.operation_type:
Не, я понял, я прост не уверен, сработает ли оператор in для подстрок

2021-06-29 14:43 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        if 'imputation' not in self.operation_type:
Вроде да:

https://stackoverflow.com/questions/3437059/does-python-have-a-string-contains-substring-method

2021-06-29 18:09 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        if 'imputation' not in self.operation_type:
Окай

2021-06-29 18:10 UTC, J3FALL approved these changes

2021-06-30 10:35 UTC, merged