README updated
nccr-itmo/FEDOT pull request #325
Opened 2021-06-03 15:20 UTC by nicl-nno

Habr.com posts and link to multi-modal example are added to README

2021-06-03 15:58 UTC, Dreamlone approved these changes
Всё здорово

2021-06-04 10:41 UTC, J3FALL requested changes

2021-06-04 10:41 UTC, J3FALL commented on README.rst
> +We also published several posts devoted to the FEDOT (`1 <https://habr.com/ru/company/spbifmo/blog/558450>`__, `2 <https://habr.com/ru/post/559796/>`__) (in Russian).
Предлагаю отдельный раздел добавить про Publication about FEDOT.
И ссылки на статьи сопроводить заголовками, вроде: "Composite models, variable-shaped pipeline: general concepts"
И "Time series forecasting with FEDOT"

2021-06-04 14:02 UTC, nicl-nno commented on README.rst
> +We also published several posts devoted to the FEDOT (`1 <https://habr.com/ru/company/spbifmo/blog/558450>`__, `2 <https://habr.com/ru/post/559796/>`__) (in Russian).
Вынес в отдельный раздел.

2021-06-05 07:30 UTC, J3FALL requested changes

2021-06-05 07:30 UTC, J3FALL commented on README.rst
> +We also published several posts devoted to the FEDOT (`1 <https://habr.com/ru/company/spbifmo/blog/558450>`__, `2 <https://habr.com/ru/post/559796/>`__) (in Russian).
Тогда эти ссылки можно удалить, они дублируются в разделе ниже

2021-06-05 07:30 UTC, J3FALL commented on README.rst
>  =================
Заодно можно освежить этот раздел.
![image](https://user-images.githubusercontent.com/7864250/120883960-fc3ef100-c5e8-11eb-893b-4ddc55fc6e51.png)

2021-06-05 10:08 UTC, nicl-nno commented on README.rst
> +We also published several posts devoted to the FEDOT (`1 <https://habr.com/ru/company/spbifmo/blog/558450>`__, `2 <https://habr.com/ru/post/559796/>`__) (in Russian).
Удалил.

2021-06-05 10:08 UTC, nicl-nno commented on README.rst
>  =================
Поменял текст на тот, что обсуждали.

2021-06-05 10:16 UTC, J3FALL approved these changes

2021-06-05 10:21 UTC, merged