Prototype of GPU evaluation implemented
nccr-itmo/FEDOT pull request #327
Opened 2021-06-06 19:52 UTC by nicl-nno

Prototype of GPU-based chain implementation:using cuML:
- controlled by selected repository json
- only part of models are supported
- file to run: gpu_example

Issues: 
 - fails if dataset is large
- unclear how to install cuML using requirements

Manuals:
- https://github.com/rapidsai/cuml
- https://medium.com/rapids-ai/running-rapids-on-microsoft-windows-10-using-wsl-2-the-windows-subsystem-for-linux-c5cbb2c56e04

Output of Win10/WSL2:

![image](https://user-images.githubusercontent.com/5711814/120938026-7c647400-c719-11eb-8c8d-8f768f0ceea3.png)

2021-06-29 12:22 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/gpu_example.py`](https://github.com/nccr-itmo/FEDOT/blob/cfcf85fa4373e43f08cb48785394686d9eadb3c2/examples/gpu_example.py):

> [Line 10:1](https://github.com/nccr-itmo/FEDOT/blob/cfcf85fa4373e43f08cb48785394686d9eadb3c2/examples/gpu_example.py#L10): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 11:1](https://github.com/nccr-itmo/FEDOT/blob/cfcf85fa4373e43f08cb48785394686d9eadb3c2/examples/gpu_example.py#L11): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/nccr-itmo/FEDOT/blob/cfcf85fa4373e43f08cb48785394686d9eadb3c2/examples/gpu_example.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 14:1](https://github.com/nccr-itmo/FEDOT/blob/cfcf85fa4373e43f08cb48785394686d9eadb3c2/examples/gpu_example.py#L14): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2021-07-20 16:09 UTC, Dreamlone requested changes
Пока посмотрел "косметические" моменты. Как наконец смогу поднять у себя cudf - пройдусь дебагом по непонятным мне частям и позапускаю примеры - тогда, возможно, еще отпишусь :)

2021-07-20 16:09 UTC, Dreamlone commented on fedot/core/operations/factory.py
> +        correct_repo_by_tag = [file_name for file_name in repositories if repo_tag in file_name][0]
Эти конструкции выглядят очень "тяжелыми". Их можно упростить?

2021-07-21 15:33 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
Нет, нельзя, потому что это нужно для обозначения, что такое fedot и где он лежит, чтобы питон мог к нему обращаться. Иначе no module named 'fedot'.

2021-07-21 16:09 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +    # test_data = get_synthetic_input_data(1000)
Вынесла данные в отдельные [функции](https://github.com/nccr-itmo/FEDOT/pull/327/files#diff-8cf3e538caf90184dc649a19866210a377107856f5f08404508b660e330ce431R131-R156) и теперь их нужно напрямую подавать в функции типа run_...
В итоге, я думаю останется вообще один датасет, просто сейчас нужно было сравнить разные данные и разные конфигурации.

2021-07-21 16:09 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +    # toy moon dataset
см. выше

2021-07-21 16:16 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/classification.py
> +import cudf
Скорее всего это будет отдельный requirements файл, который будет ставиться в случае, если пользователь захочет этим пользоваться (как, например, с профайлерами). Тут нужно просто еще понять, какую среду предоставлять. Если это будет контейнер, то просто .txt, если conda, то  conda_requirements.sh. 
Т.к. мне например удобнее пользоваться докером, а тебе или кому-либо еще conda, то скорее всего будет и то и то.

2021-07-21 16:18 UTC, BarabanovaIrina commented on examples/pure_gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
см. тот же коментарий. 
+ этот файл будет удален, т.к. нужен был чисто для экспериментального сравнения

2021-07-21 16:56 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/common.py
> +                                                             tags=['non_multi'])
Он теперь работает по-другому. 
Теперь задавать "поведение" OperationTypesRepository нужно не файлом репозитория, а типом узла 'model' или 'data_operation'. 
При первом вызове OperationTypesRepository() (в любом месте кода, главное чтобы первый раз) в нем [инициализируются](https://github.com/nccr-itmo/FEDOT/pull/327/files#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0R64-R80) дефолтные репозитории для моделей и data-операций. 
И каждый раз, когда создается новый объект OperationTypesRepository() необходимо передать operation_type='model' или operation_type='data_operation'. 'model' - по умолчанию. 

Если хочешь использовать другой файл-репозитория - то необходимо явно вызвать метод OperationTypesRepository.assign_repo(type, repository) и передать для какого типа ноды переопределять репозиторий, как [тут](https://github.com/nccr-itmo/FEDOT/pull/327/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR136-R137), например.

До тех пор пока, снова не вызвать OperationTypesRepository.assign_repo(type, repository) будет использоваться репозиторий, назначенный последним.

2021-07-21 17:10 UTC, BarabanovaIrina commented on fedot/core/operations/factory.py
>          return operation_type
Мне, если честно, вообще не нравится эта взаимоисключающая конструкция, но я пока лучше идей нет.

На данный момент у нас пока один репозиторий с data_operations и уже как минимум 3 (model, automl, gpu_model) для моделей. Мне показалось, что исключить операцию по данным сейчас проще чем модель хотя бы по этой причине.
Со старой постановкой условия Node('tpot') попадала в data_operation, потому что данная модель не описана в репозитории model_repository.py, что вызывало 'tpot is not implemented in data_operations_repository.py'. Ну и ко всему прочему data_operations по количеству меньше, предположу, что и поиск чуть быстрее. 

По идее, если в скрипте, из которого запускается пример с альтернативным repo явно задавать новый репозиторий, то можно и по старому.

2021-07-21 17:11 UTC, BarabanovaIrina commented on fedot/core/operations/factory.py
> +        correct_repo_by_tag = [file_name for file_name in repositories if repo_tag in file_name][0]
Этого метода больше нет.

2021-07-21 18:08 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +    # baseline_model.fit(features=train_data_path, target='target', predefined_model='logit')
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/327/commits/37396621da8a195792ad03acbd5e2e9daef38476#diff-8cf3e538caf90184dc649a19866210a377107856f5f08404508b660e330ce431L67-L71)

2021-07-21 18:09 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +    preset_pipeline = Pipeline(nodes=[svc_node_with_custom_params], tag='gpu')
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/327/commits/37396621da8a195792ad03acbd5e2e9daef38476#diff-8cf3e538caf90184dc649a19866210a377107856f5f08404508b660e330ce431L86-R84)

2021-07-21 18:10 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/common.py
> +            #                                                         train_data)
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/327/commits/37396621da8a195792ad03acbd5e2e9daef38476#diff-883de6835be7545975efad596298e37ab022abb5ba0e2da9a16fef30badafc81L65-R64)

2021-07-21 18:16 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/common.py
> +    This class defines the certain operation implementation for the GPU-based CuML operations
С точки зрения реализации - согласна, [исправлено](https://github.com/nccr-itmo/FEDOT/pull/327/commits/37396621da8a195792ad03acbd5e2e9daef38476#diff-883de6835be7545975efad596298e37ab022abb5ba0e2da9a16fef30badafc81L18-R17)

2021-07-23 13:35 UTC, nicl-nno commented on Dockerfile
> +FROM nvcr.io/nvidia/rapidsai/rapidsai:21.06-cuda11.2-base-ubuntu18.04
В названии файл мб упоминать, что это именно версия для GPU и linix?

2021-07-23 13:36 UTC, nicl-nno commented on conda_requirements.sh
> +conda create -n rapids-0.19 -c rapidsai -c nvidia -c conda-forge rapids-blazing=0.19 python=3.8 cudatoolkit=11.0
Аналогично - это же именно для GPU файл, а не для установки FEDOT через конду.

2021-07-23 13:59 UTC, nicl-nno commented on examples/gpu_example.py
> +def run_pipeline_gpu_example(train_data: InputData, test_data: InputData,
Мб что-то вроде run_pipeline_with_specific_evaluation_mode?

Тут же не всегда gpu.

2021-07-23 14:03 UTC, nicl-nno commented on fedot/core/operations/evaluation/gpu/classification.py
> +        converted = self._convert_to_output(prediction, predict_data)
Тут конечно соблазн объединить этот код с https://github.com/nccr-itmo/FEDOT/blob/9d5185b9bebb7a1de44cf2c2655daccb2c0ce459/fedot/core/operations/evaluation/classification.py

Может выделенную логику вынести в отдельную функцию вроде sklearn_compatible_prediction (да и n_classes ту да же)?

2021-07-23 16:29 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/126812896-7d8b254b-eda5-41e1-a05d-c63ebcc28c79.png)

Вот тут бы ещё одинаковые названия mode сделать в фунции и в репозитории

2021-07-26 14:20 UTC, BarabanovaIrina commented on Dockerfile
> +FROM nvcr.io/nvidia/rapidsai/rapidsai:21.06-cuda11.2-base-ubuntu18.04
Оставила [комментарий](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R1), потому как название файла должно оставаться таким ([пояснение](https://stackoverflow.com/questions/26077543/how-to-name-dockerfiles))

2021-07-26 14:21 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +def run_pipeline_gpu_example(train_data: InputData, test_data: InputData,
Исправлено для [one_model](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-8cf3e538caf90184dc649a19866210a377107856f5f08404508b660e330ce431L21-R21) и [pipeline](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-8cf3e538caf90184dc649a19866210a377107856f5f08404508b660e330ce431L50-R51)

2021-07-26 14:21 UTC, nicl-nno commented on Dockerfile
> +FROM nvcr.io/nvidia/rapidsai/rapidsai:21.06-cuda11.2-base-ubuntu18.04
А он обязательно должен быть в корне?

2021-07-26 14:22 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/classification.py
> +        converted = self._convert_to_output(prediction, predict_data)
Согласна, [вынесено](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-60a694a93b0cdb51f5f81fc4449dfb07a74d317aa8bd323439c4804353c0584aR204-R218) на уровень SkLearnClassificationStrategy, и, следовательно, обратно изменено [наследование](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-883de6835be7545975efad596298e37ab022abb5ba0e2da9a16fef30badafc81L17-R19).

2021-07-26 14:26 UTC, nicl-nno commented on fedot/core/operations/evaluation/gpu/classification.py
> +        converted = self._convert_to_output(prediction, predict_data)
![image](https://user-images.githubusercontent.com/5711814/127005364-6cc85245-b42b-423c-aa3f-1b9271df1544.png)

Хм, а может тогда вообще тут после строки с cudf.DataFrame вызывать реализацию метода из класса-предка? И self._convert_to_output туда загнать. Тогда возможно и функция не понадобится.

2021-07-26 14:27 UTC, BarabanovaIrina commented
> ![image](https://user-images.githubusercontent.com/5711814/126812896-7d8b254b-eda5-41e1-a05d-c63ebcc28c79.png)
> 
> Вот тут бы ещё одинаковые названия mode сделать в фунции и в репозитории

Унифицировано и [оптимизированы](https://github.com/nccr-itmo/FEDOT/pull/327/commits/26c6bf9c5e1ccf23a6ed83ca08e3985b9aad3a7c#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0L263-R290) функции get_operations_for_task и get_ts_operations. get_ts_operations больше нет.

2021-07-26 14:42 UTC, nicl-nno commented on Dockerfile
> +FROM nvcr.io/nvidia/rapidsai/rapidsai:21.06-cuda11.2-base-ubuntu18.04
>Желательно, но не обязательно

Это я к тому, что может создать отдельную папку для GPU-related артефактов? И туда и докерфайл, и conda_req положить.

>Но вообще, в best practicies 1 проект - 1 Dockerfile

Ну у нас видимо будет 1 для CPU, 1 для GPU

2021-07-26 14:46 UTC, BarabanovaIrina commented on fedot/core/operations/evaluation/gpu/classification.py
> +        converted = self._convert_to_output(prediction, predict_data)
Ну тут тогда придется либо CuMLClassificationStrategy наследовать от SkLearnClassificationStrategy, а не от SkLearnEvaluationStrategy, потому как именно там предопределена функция predict, либо выносить ее на уровень SkLearnEvaluationStrategy, что не очень правильно, потому как для того вроде и разделяли.
а перенаследовать от SkLearnClassificationStrategy - выглядит логически кмк не очень правильно.

2021-07-26 14:50 UTC, nicl-nno commented on fedot/core/operations/evaluation/gpu/classification.py
> +        converted = self._convert_to_output(prediction, predict_data)
Ок, тогда пусть будет как есть.

2021-07-26 16:11 UTC, BarabanovaIrina commented on Dockerfile
> +FROM nvcr.io/nvidia/rapidsai/rapidsai:21.06-cuda11.2-base-ubuntu18.04
Оставила в корне [Dockerfile](https://github.com/nccr-itmo/FEDOT/pull/327/commits/0afec2fd6f95701fafc8e8f1ee49959c0ea0df99) для обычного запуска (CPU) и выделила [дирректорию](gpu/Dockerfile) под gpu.

2021-07-26 16:11 UTC, BarabanovaIrina commented on conda_requirements.sh
> +conda create -n rapids-0.19 -c rapidsai -c nvidia -c conda-forge rapids-blazing=0.19 python=3.8 cudatoolkit=11.0
[Перенесен](gpu/conda_gpu_requirements.sh)

2021-07-26 16:18 UTC, nicl-nno commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
Кстати, а не получится этот фрагмент вынести в функцию? А то сейчас дублируется дважды.

2021-07-26 16:22 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
А где дублируется?

2021-07-26 16:27 UTC, nicl-nno commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
В examples/gpu_example.py  и examples/pure_gpu_example.py

2021-07-26 16:33 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
а может examples/pure_gpu_example.py вообще удалить? он же чисто для сравнения был. кроме того, кажется, что тогда ему придется добавить в path путь до этой функции, если она будет не в текущем скрипте.

2021-07-26 16:37 UTC, nicl-nno commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
Если удалить, то ок.

2021-07-27 16:50 UTC, BarabanovaIrina commented on examples/gpu_example.py
> +sys.path.append(os.path.join(ROOT, "fedot"))
[Удален](examples/pure_gpu_example.py)
Этого куска кода теперь тоже нет, потому как в Dockerfile теперь [добавлен](https://github.com/nccr-itmo/FEDOT/pull/327/commits/691e09626b5af0adb9ca8213cec402f8245d38dd#diff-dd2c0eb6ea5cfc6c4bd4eac30934e2d5746747af48fef6da689e85b752f39557R11) путь до fedot.

2021-07-27 17:59 UTC, BarabanovaIrina commented
Добавлены стратегии для [кластеризации](fedot/core/operations/evaluation/gpu/clustering.py) и [регрессии](fedot/core/operations/evaluation/gpu/regression.py)
Не тестированы.

2021-07-27 19:17 UTC, Dreamlone approved these changes

2021-07-28 09:38 UTC, merged