Composing of multi-variate time series supported
nccr-itmo/FEDOT pull request #328
Opened 2021-06-07 18:06 UTC by nicl-nno

Main changes:
- API wrapper for multivariate time series added (can be taken into account during API refactoring by @v1docq)
- Metocean forcasting case simplified

The multivariate TS are represented as several datasources in multi-modal chain.

2021-06-07 18:06 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

















* In the file [`fedot/core/data/data_split.py`](https://github.com/nccr-itmo/FEDOT/blob/55cb8e241d9c6d836075d17392ef01c68aa0cc40/fedot/core/data/data_split.py):

> [Line 168:9](https://github.com/nccr-itmo/FEDOT/blob/55cb8e241d9c6d836075d17392ef01c68aa0cc40/fedot/core/data/data_split.py#L168): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 170:9](https://github.com/nccr-itmo/FEDOT/blob/55cb8e241d9c6d836075d17392ef01c68aa0cc40/fedot/core/data/data_split.py#L170): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 239:33](https://github.com/nccr-itmo/FEDOT/blob/55cb8e241d9c6d836075d17392ef01c68aa0cc40/fedot/core/data/data_split.py#L239): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-06-08 09:34 UTC, Dreamlone requested changes
У меня еще один вопрос возник: а как у тебя происходит определение, какой target главный в итоге? - По коду я не очень понял как это происходит видимо.
То есть присутствуют 2 lagged узла с разными временными рядами в цепочке. У каждого из них есть свой временной ряд на вход. Преобразование у них внутри устроено так, что из lagged в таком случае у каждого из них выходит свой features и свой target. 
Тогда надо какому-то из них назначать is_main_target = False. Или как оно происходит?

2021-06-08 09:34 UTC, Dreamlone commented on fedot/api/main.py
> +
Просто из любопытства - ты тут имеешь в виду, что потенциально хотелось бы давать прогноз не только на горизонт, на который модель была натренирована? 
Если это так, то это можно довольно просто сделать, можешь попробовать даже в рамках этого PR. 
Подглядывай если что в examples/ts_multistep_example.py. Вот такой код должен сработать:
```
predicted = out_of_sample_ts_forecast(chain=self.current_model,
                                      input_data=pre_history,
                                      horizon=forecast_length)
```
Обрати внимание, что в переменной predicted будет не OutputData, а уже предсказанный numpy массив

2021-06-08 09:34 UTC, Dreamlone commented on fedot/api/main.py
> +                                            task=ml_task)) for (key, value) in features.items())
Выглядит тяжеловато как по мне. Эту конструкцию возможно сделать попроще?

2021-06-08 09:34 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +        return results, results
Извини, но я не понял, зачем тут это было сделано. Вернее, я это понял как то, что раз нам нужно сравнивать predict из модели и фактический target, то почему бы не хранить их в одной InputDat'е, а не в разных. Правильно ли я понял?

Если да, то тогда надо передавать не 2 объекта, а только один "results". Ну и соответственно, переписать немного логику принимающих всё это дело от функции "flatten_convert" вышестоящих методов. В любом случае, оставлять "return results, results" не стоит кмк.

2021-06-08 09:34 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +                      for _ in range(self.requirements.pop_size)])
А можешь плиз объяснить что тут делается (и главное, зачем). Как я понимаю, тут мы начинаем теперь процесс оптимизации не из множества копий начального приближения (назовем это приближение chain1), а его видоизменений. Так ли это?

Мне кажется коммент тут не помешает

2021-06-08 09:34 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +        chain.nodes.append(new_node)
Описание в docstring добавь пожалуйста. Плюс max_depth внутри метода никак не используется.

2021-06-08 09:34 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +                max_depth = node_from_chain.distance_to_primary_level
Тут и раньше было непросто, а сейчас без комментариев совсем тяжко :) Добавь их, если не сложно

2021-06-08 09:34 UTC, Dreamlone commented on fedot/core/data/data_split.py
> +
Описание у функций "train_test_setup_for_dataset" и "train_test_data_setup". Не дублируют ли они функциональность друг друга? Если нет, и они все таки занимаются разными вещами, то надо подправить описания в docsting.

2021-06-09 07:56 UTC, Dreamlone commented on cases/metocean_forecasting_problem.py
> +                                     is_visualise=True)
Да, это вроде и правда не сильно помогло - пример все равно долго крутится, хотя, как по мне, всё таки меньше, чем было. Пусть будет пока так.

2021-06-09 08:09 UTC, Dreamlone commented on fedot/api/api_utils.py
> +            node_final = SecondaryNode('ridge', nodes_from=[PrimaryNode('lagged')])
Я тут всё таки имел в виду то, что 
```
node_model = SecondaryNode('ridge',
                           nodes_from=[SecondaryNode('lagged',
                                       nodes_from=[PrimaryNode(key)])])
```

можно заменить например на
```
parent_nodes = [SecondaryNode('lagged', nodes_from=[PrimaryNode(key)])]
node_model = SecondaryNode('ridge', nodes_from=parent_nodes)
```
Чтобы избежать шибко длинных строк, да и читается вроде получше. Но твой вариант тоже ок - выглядит красuво

2. Я тогда пока этот коммент сворачивать не буду, чтобы Илья не забыл про этот момент

2021-06-09 08:20 UTC, Dreamlone commented on fedot/api/main.py
> +                                            task=ml_task)) for (key, value) in features.items())
Ага, норм
По поводу всего этого блока с "_define_data", может его вообще вынести в отдельное место, и убрать все эти многочисленные "if, elif" и т.д.? Просто выглядит так, как будто уже есть запрос на то, чтобы это был отдельный модуль подготовки данных, эдакий вспомогательный инструмент, который по запросу из api берёт на себя все функции по подготовке данных. 

Думаю, это можно обсудить с @J3FALL и @v1docq (и сделать нечто подобное в рамках PR по рефакторингу API)

2021-06-09 08:39 UTC, Dreamlone approved these changes
В одном месте есть опечатка - а так welcome to master branch

2021-06-09 08:39 UTC, Dreamlone commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +        :return: list of individuals
Вроде тут очепяточка: variants

2021-06-09 09:31 UTC, J3FALL requested changes

2021-06-09 09:31 UTC, J3FALL commented on fedot/api/api_utils.py
> +                node_final.nodes_from.append(node_last_model)
last и final можно интерпретировать одинаково )

2021-06-09 09:31 UTC, J3FALL commented on fedot/api/api_utils.py
> +            for data_source_name in data.keys():
Чтобы убрать множество if-ов, предлагаю такой рефакторинг:
- для отдельных условий "if classification/regression/ts_forecasting" - сделать dict, где ключ - это task_type, а значение - начальное условие=цепочка
- для multi_modal добавить отдельную функцию, вроде "assumtion_if_multi_modal", которая при условии, что data is MultiModalData перепишет начальное приближение

Таким образом, можно представить это так:
```
...
initial = assumption_by_task(task)
initial = _assumption_if_multi_modal(task, data)

return initial
```

2021-06-09 09:31 UTC, J3FALL commented on fedot/api/main.py
> +        data = MultiModalData(sources)
Чтобы лучше понимать этот фрагмент, его вроде можно вытащить в отдельную функцию и протестить

2021-06-09 09:31 UTC, J3FALL commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +    if random() > 0.5:
Думаю, понятно, почему эта штука не очень, но в целом, мотивация мне ясна.

2021-06-09 09:42 UTC, v1docq commented on fedot/api/api_utils.py
> +            node_final = SecondaryNode('ridge', nodes_from=[PrimaryNode('lagged')])
Я в рамках своего рефакторинга, вынес генерацию и композирование в отдельный класс, где есть отдельный метод для начальных приближений. Сделать в виде словаря не проблема, много где по коду используется.

2021-06-09 09:43 UTC, v1docq commented on fedot/api/api_utils.py
> +            for data_source_name in data.keys():
Это уже пойдет в мой рефакторинг, вприципе реализовать как ты предложил реально.

2021-06-09 09:43 UTC, v1docq commented on fedot/api/main.py
> +        data = MultiModalData(sources)
Тоже забираю к себе в рефакторинг.

2021-06-09 11:53 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/gp_optimiser.py
> +        :return: list of individuals
Fixed

2021-06-09 11:53 UTC, nicl-nno commented on fedot/api/api_utils.py
> +                node_final.nodes_from.append(node_last_model)
Попробовал сформулировать как last_node_for_sub_chain

2021-06-09 11:53 UTC, nicl-nno commented on fedot/core/composer/optimisers/gp_comp/operators/mutation.py
> +    if random() > 0.5:
Да, потом надо продумать более интеллектуальное управление вероятностями мутаций.

2021-06-09 12:38 UTC, J3FALL approved these changes

2021-06-09 13:45 UTC, merged