lgbm and catboost
nccr-itmo/FEDOT pull request #329
Opened 2021-06-08 11:51 UTC by MAGLeb

Implement new models - LightGBM, Catboost.
Discovered the default hyperparameters of the models. For LGBM I took the best parameters, based on empirical experiments, for CatBoost, by default good parameters.

2021-06-08 22:11 UTC, nicl-nno requested changes

2021-06-08 22:11 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +            self.log = log
Может вынести эту часть в конструктор ModelImplementation?

2021-06-08 22:11 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
А это где-то используется?

2021-06-08 22:11 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +	},
Общий вопрос - а почему нельзя добавить эти модели как SkLearnСlassificationStrategy? Выглядит ведь как будто по интерфейсу они полностью совместимы и разница только в начальных параметрах.

2021-06-08 22:11 UTC, nicl-nno commented on test/unit/models/test_model.py
> +    assert roc_on_train >= roc_threshold
А есть смысл делать отдельные тесты на каждую модель? Может просто в одном тесте пройтись циклом по всем имеющимся?

2021-06-08 22:11 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/lightgbm.py
> +        }
Ещё наверное надо добавить для новых моделей диапазоны гиперапараметров для тюнера.

2021-06-09 08:16 UTC, MAGLeb commented on fedot/core/repository/data/model_repository.json
> +	},
Из-за начальных параметров и сделал отдельным классом. 
В принципе можно под SKLearnStrategy и как-то передавать начальные параметры, что думаешь @nicl-nno?

2021-06-09 08:17 UTC, MAGLeb commented on test/unit/models/test_model.py
> +    assert roc_on_train >= roc_threshold
Согласен.

2021-06-09 08:18 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/lightgbm.py
> +        }
Имеешь ввиду что-то такое?

`_tuning_range_params = {
"num_leaves": [8, 16, 32, 64, 128, 256],
...
}`

2021-06-09 08:24 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
Вроде как это свойство не присутствует в интерфейсе ModelImplementation, но другие классы наследники реализуют его. Мне кажется стоит оставить, чтобы был одинаковый интерфейс к CustomModels. Что думаешь?

2021-06-09 08:37 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
![image](https://user-images.githubusercontent.com/52084975/121321797-16454000-c917-11eb-9b7e-1e4b05db76c4.png)

2021-06-09 09:09 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/lightgbm.py
> +        }
Если ты об этом, почему-то думаю лучше в тюнере их добавить, так как в зависимости от того как тюнить, диапозон гиперпараметров может быть задан по разному.

2021-06-09 09:14 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +            self.log = log
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/329/commits/38082bb1b3f39322ed484d33bce65e1c912ed320#diff-53579048c8b22a05e52c5f7ee8b4779da341929a2be7ac10d431e85a071c34deL161-R173) для всех моделей.

2021-06-09 09:14 UTC, MAGLeb commented on test/unit/models/test_model.py
> +    assert roc_on_train >= roc_threshold
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/329/commits/38082bb1b3f39322ed484d33bce65e1c912ed320#diff-1cafb1c54b4ad34680bcf45f9926d3f7e34990e57caf865c4968212d6895f069L158-R82).

2021-06-09 10:29 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +	},
Сatbost и lgmb явно специально сделаны sklearn-совместимыми, поэтому на это вполне можно полагаться. 

Поэтому если дело только в начальных параметрах - я бы их сделал просто доп. моделями из sklearn-стратегии и дополнительно сделал возможность задавать кастомный параметры по умолчанию таким моделям.

Это если найдутся какие-то различия в поведении, то можно и вынести в отдельную имплементацию, как сейчас сделано.

2021-06-09 10:30 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
Переход на sklearn-стратегию по идеи устранит необходимость в явной реализации этого поля.

2021-06-09 10:32 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/lightgbm.py
> +        }
Ну я про вот этот словарь:

https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/chains/tuning/hyperparams.py

2021-06-09 14:28 UTC, J3FALL requested changes
Еще вопросы:
- Проверялся ли тюнинг на новых моделях?
- Глеб говорил ранее, что дефолтный catboost и lgbm не особо полезны, можно ли в этом pr-е провести эмпирический тест (например, на скоринге), что дает лучше результат после 5 минут композирования - с lgbm и catboost или без

Более подробнее про последнее: в available models в одном случае передаешь эти модели, в другом - нет.
И смотришь, появляются ли вообще эти модели в итоговых цепочках + сравниваешь среднее качество по N запускам.

- Еще надо проверить пресеты в API, кажется туда резонно вставить новые модели

2021-06-09 14:28 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
В целом, да, если там нет расхождений в интерфейсах fit/predcit, то CatBoost и LightGBM можно унаследовать от SkLearn-овских стратегий.
Только стоит этот момент указать в docstring, что мы это сделали намерено

2021-06-09 14:28 UTC, J3FALL commented on test/unit/models/test_model.py
> +        test_pred = model.predict(fitted_operation=_, data=test_data, is_fit_chain_stage=False)
А можно тогда логирование добавить?
Чтобы можно было отследить, на какой модели может упасть тест

2021-06-09 14:28 UTC, J3FALL commented on test/unit/models/test_model.py
> +        rmse_value_test = mean_squared_error(y_true=test_data.target, y_pred=test_pred.predict)
Предложение тоже, что и выше

2021-06-10 13:25 UTC, MAGLeb commented on fedot/core/repository/data/model_repository.json
> +	},
Правильно понимаю, добавить [сюда](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/operations/evaluation/evaluation_interfaces.py) CatBoost and Lgbm. Также создать JSON файл с дефолтными парамтрами для моделей и при инициализации проверять, есть ли дефолтные параметры для этой модели. 

И разве сейчас нельзя передавать кастомные параметры?
![image](https://user-images.githubusercontent.com/52084975/121532862-6bad4a00-ca08-11eb-9f70-f411072d7767.png)

2021-06-10 13:29 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +	},
Ну да.

Кастомные передавать можно, просто нужен удобный вариант именно для параметров по умолчанию (в случае если кастомные не заданы)

2021-06-11 08:00 UTC, MAGLeb commented
> * Еще надо проверить пресеты в API, кажется туда резонно вставить новые модели

[Добавил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR111-R115) в пресеты.

> * Проверялся ли тюнинг на новых моделях?

Проверил, в тесты не стал добавлять, так как по времени падает.

> * Глеб говорил ранее, что дефолтный catboost и lgbm не особо полезны, можно ли в этом pr-е провести эмпирический тест (например, на скоринге), что дает лучше результат после 5 минут композирования - с lgbm и catboost или без

Позапускал композер с дефолтными-кастомными параметрами LGBM и дефолтными CB, иногда модели попадают в цепочку.

2021-06-11 08:01 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/lightgbm.py
> +        }
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-210a80a7dac0fa43e2637d72a6aed98c9400e080ddbf88fca57e69adc3028027L161-R192).

2021-06-11 08:03 UTC, MAGLeb commented on fedot/core/repository/data/model_repository.json
> +	},
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-60a694a93b0cdb51f5f81fc4449dfb07a74d317aa8bd323439c4804353c0584aL24-R160) наследование моделей от sklearn. И добавил возможность инициализировать модели с кастомно-дефолтными параметрами.

2021-06-11 08:04 UTC, MAGLeb commented on test/unit/models/test_model.py
> +        test_pred = model.predict(fitted_operation=_, data=test_data, is_fit_chain_stage=False)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-1cafb1c54b4ad34680bcf45f9926d3f7e34990e57caf865c4968212d6895f069L155-R98) логгер.

2021-06-11 08:04 UTC, MAGLeb commented on test/unit/models/test_model.py
> +        rmse_value_test = mean_squared_error(y_true=test_data.target, y_pred=test_pred.predict)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-1cafb1c54b4ad34680bcf45f9926d3f7e34990e57caf865c4968212d6895f069L155-R98) логгер.

2021-06-11 12:26 UTC, MAGLeb commented on fedot/core/operations/evaluation/operation_implementations/models/catboost.py
> +        return self.model.classes_
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/329/files#diff-60a694a93b0cdb51f5f81fc4449dfb07a74d317aa8bd323439c4804353c0584aL24-R160).

2021-06-11 20:54 UTC, nicl-nno approved these changes

2021-06-16 10:57 UTC, J3FALL requested changes

2021-06-16 10:57 UTC, J3FALL commented on fedot/api/api_utils.py
> +                                          'catboostreg', 'lgbm', 'lgbmreg']}
Погоди, но ты ведь наоборот исключил из пресетов lgbm и catboost?
Или такая задумка и была?

2021-06-16 11:04 UTC, J3FALL approved these changes

2021-06-16 11:08 UTC, merged