Example with NEMO on multiple models and timeseries
nccr-itmo/FEDOT pull request #338
Opened 2021-06-15 20:37 UTC by ChrisLisbon

Example with NEMO data using in composite models. 
Statsmodels STLForecast implementation for ARIMA as a strategy.

2021-06-15 20:37 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`examples/ts_forecasting_with_nemo_multiple_models.py`](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py):

> [Line 13:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L13): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 58:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L58): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 66:52](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L66): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 84:52](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L84): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 130:52](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L130): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 142:52](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L142): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 148:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L148): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 179:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L179): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 354:40](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L354): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 355:40](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L355): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 356:40](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L356): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 359:67](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L359): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 359:69](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L359): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 368:52](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L368): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 406:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L406): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 407:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L407): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 408:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L408): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 409:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L409): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 410:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L410): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 411:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L411): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent
> [Line 412:51](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L412): [E124](https://duckduckgo.com/?q=pep8%20E124) closing bracket does not match visual indentation
> [Line 414:17](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L414): [E711](https://duckduckgo.com/?q=pep8%20E711) comparison to None should be 'if cond is not None:'
> [Line 442:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/examples/ts_forecasting_with_nemo_multiple_models.py#L442): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file









* In the file [`fedot/core/operations/evaluation/operation_implementations/models/custom_model.py`](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/custom_model.py):

> [Line 9:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/custom_model.py#L9): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 41:9](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/custom_model.py#L41): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (4)
> [Line 53:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/custom_model.py#L53): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file



* In the file [`fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py`](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py):

> [Line 237:1](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py#L237): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 259:9](https://github.com/nccr-itmo/FEDOT/blob/7c9f292a7662c9ef6e23e723c479996bf92573c5/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py#L259): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2021-06-17 10:38 UTC, J3FALL requested changes

2021-06-17 10:38 UTC, J3FALL commented on cases/data/mm_imdb/3889036.json
> +    {
Сразу отмечу - мне кажется, что датасет mm_imbd был первоначально в zip архиве, но в этом коммите все его файлы попали в репозиторий. Думаю, их нужно исключить.
Без этого неудобно делать ревью, т.к. слишком много файлов

2021-06-28 09:51 UTC, nicl-nno requested changes

2021-06-28 09:51 UTC, nicl-nno commented on examples/ts_forecasting_nemo_example.py
> +    # Nemo feature
Кажется отступы лишние.

2021-06-28 09:51 UTC, nicl-nno commented on examples/ts_forecasting_with_exogenous.py
> +    #exog_variable = np.array(df['Neighboring level'])
Комменты видимо устарели.

2021-06-28 09:51 UTC, nicl-nno commented on examples/ts_forecasting_with_exogenous.py
> +    data_path = os.path.join('C:/Users/yulas/OneDrive/Документы/ITMO/NSS_lab/FEDOT_development/FEDOT/cases/data/nemo/test_nemo.csv')
Путь неправильный

2021-06-28 09:51 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +import numpy as np
Может стоит все эти example объединить в 1? Кажется, большая часть кода дублируется.

2021-06-28 09:51 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +class DomainSpecificModelImplementation(ModelImplementation):
А это где-то используется?

2021-06-28 18:59 UTC, ChrisLisbon commented on examples/ts_forecasting_nemo_example.py
> +    # Nemo feature
Исправила

2021-06-28 19:00 UTC, ChrisLisbon commented on examples/ts_forecasting_with_exogenous.py
> +    #exog_variable = np.array(df['Neighboring level'])
Исправила

2021-06-28 19:01 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +import numpy as np
Переписала весь multiple_example в виде функций, чтобы код не дублировался. И убрала тестовые файлы не особо нужные.

2021-06-28 19:03 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +class DomainSpecificModelImplementation(ModelImplementation):
Это заготовка под тот глобальный класс, который будет сам запускать физические модели, сейчас он нигде не используется, наверное можно пока снести

2021-06-28 19:16 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +class DomainSpecificModelImplementation(ModelImplementation):
Ну если он не нужен в твотх примерах, то зачем он.

2021-06-28 19:17 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +        predict_dataset = MultiModalData(chains[name]['pr_nodes_data'])
Может делать deepcopy вот здесь, чтобы не дублировать его столько раз?

2021-06-28 19:18 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    def combine_chain(name):
Название функции не вполне отражает то, что внутри.

2021-06-28 19:18 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +     test_data) = prepare_data(time_series=time_series,
А тут нужны скобит?

2021-06-28 19:19 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    return train_input, predict_input, train_input_exog, predict_input_exog, test_data
test_data как-то выбивается из логики вывода. В чем ее отличие от predict_input?

2021-06-28 19:22 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        """ Method for smoothing time series
Описание кажется не соотвтствует.

2021-06-28 19:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            diff = int(self.actual_ts_len - len(fitted_values))
len и так int, понятнее будет int(self.actual_ts_len)

2021-06-29 10:16 UTC, nicl-nno commented
Также стоит добавить тест на новый пример в test_examples.py

2021-06-29 10:17 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +class STLForecastARIMAImplementation(ModelImplementation):
А эта модель где-то в unit-тестах тестируется? Если нет - то стоит добавить (мб сделав проход по всем ts-моделям в цикле)

2021-06-29 11:55 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +class DomainSpecificModelImplementation(ModelImplementation):
Убрала

2021-06-29 11:56 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +        predict_dataset = MultiModalData(chains[name]['pr_nodes_data'])
Вынесла внутрь функции подготовки данных

2021-06-29 11:56 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    def combine_chain(name):
Заменила на multimodal_data_preparing

2021-06-29 11:57 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +     test_data) = prepare_data(time_series=time_series,
Без скобок не дает перенести строку, без переноса строки она оказывается слишком длинной для стандарта

2021-06-29 12:02 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    return train_input, predict_input, train_input_exog, predict_input_exog, test_data
Отличие в том, что test_data это просто массив, включающий только тестовую выборку, а predict_input это объект класса InputData, у которого в индексах обозначены только необходимые для предсказания, а features содержит весь временной ряд. Если убрать из вывода test_data, то выборку для подсчета метрик нужно будет извлекать из predict_input с обрезанием по индексам. Я руководствовалась логикой как в ts_forecasting_with_exogenous.py и ts_forecasting_tuning.py

2021-06-29 12:03 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        """ Method for smoothing time series
Я поправила для нового класса, только вот для ARIMAImplementation и AutoRegImplementation описание такое же, думаю стоит тоже исправить?

2021-06-29 12:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            diff = int(self.actual_ts_len - len(fitted_values))
Исправила

2021-06-29 12:39 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +        predict_dataset = MultiModalData(chains[name]['pr_nodes_data'])
Ок. 

Ставь только плз ссылки на код для не-тривиальных измений вроде этого, чтобы было проще смотреть. Можешь в других PR-ах посмотреть примеры.

2021-06-29 12:42 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +     test_data) = prepare_data(time_series=time_series,
Не принципиально, но кажется так лучше:

![image](https://user-images.githubusercontent.com/5711814/123799155-97796c80-d8f0-11eb-898c-9b0dbf6bf7b3.png)

Непривычно просто видеть скобки в левой части таких конструкции.

2021-06-29 12:43 UTC, nicl-nno commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    return train_input, predict_input, train_input_exog, predict_input_exog, test_data
>Отличие в том, что test_data это просто массив, включающий только тестовую выборку

Там только целевая переменная? Можно назвать тогда test_target?

2021-06-29 12:43 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        """ Method for smoothing time series
Да, стоит.

2021-06-29 16:04 UTC, ChrisLisbon commented on examples/ts_foresting_with_nemo_multiple_example.py
> +    return train_input, predict_input, train_input_exog, predict_input_exog, test_data
Только целевая, заменила название

2021-06-29 16:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        """ Method for smoothing time series
Исправила

2021-06-29 16:29 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +class STLForecastARIMAImplementation(ModelImplementation):
Тест на nemo example

https://github.com/nccr-itmo/FEDOT/blob/9c664e5e3b7e609862919abb373665a126dcfee9/test/integration/real_applications/test_examples.py#L53-L61

Тест на ts модели

https://github.com/nccr-itmo/FEDOT/blob/3b5de3ac59576bcac81885923f80b5d6a80b0e7f/test/unit/models/test_model.py#L110-L126

2021-06-29 19:08 UTC, nicl-nno approved these changes

2021-06-30 07:55 UTC, J3FALL approved these changes

2021-06-30 07:56 UTC, merged