add models to repository
nccr-itmo/FEDOT pull request #345
Opened 2021-06-30 15:03 UTC by MAGLeb

- Сatboost and lgbm were added in automl_repository.json
- model_repository.json  and automl_repository.json were parsed and same parts were relocated to **model_repository.json**
- to expand some repository can add key: 'base_repository' with path to it

2021-06-30 15:16 UTC, nicl-nno commented
Вообще, раз уж про это вспомнили, хорошо бы сделать функцию расширения json-репозитория, чтобы вручную не поддерживать несколько версий.
Например, добавив корневое поле base_repository.

2021-07-05 16:43 UTC, nicl-nno requested changes

2021-07-05 16:43 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +        base_repository_json_file = create_repository_path('base_repository.json')
Идея верная, но такая реализация слишком под конкретные файлы заточена. 

Лучше сделать, чтобы в любом repository могло быть не-обязательное поле 'base_repository' с адресом файла, из которого берутся все не-переопределенные поля.

2021-07-05 16:43 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +    }
А почему это в отдельном файле, а не в base_repository?

2021-07-05 16:54 UTC, MAGLeb commented on fedot/core/repository/data/model_repository.json
> +    }
Его не было в automl_repo, не придал значение.

2021-07-06 09:28 UTC, nicl-nno requested changes

2021-07-06 09:28 UTC, nicl-nno commented on fedot/core/repository/data/automl_repository.json
> +  "base_repository": "fedot/core/repository/data/base_repository.json",
Может прописать тут model_repository.json, чтобы не дублировать файлы?

2021-07-06 09:28 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +    }
Ну кажется это можно объединить с base_repository

2021-07-06 13:04 UTC, MAGLeb commented on fedot/core/repository/data/automl_repository.json
> +  "base_repository": "fedot/core/repository/data/base_repository.json",
[Согласен.](https://github.com/nccr-itmo/FEDOT/pull/345/commits/3c0a6835521ef31dca0231cd0f02772aa23f9e9f#diff-b86439e69920c9b9d9679874ea5d66648d6756b187252762d3335ab9e23327d1L2-L3)

2021-07-06 13:06 UTC, MAGLeb commented on fedot/core/repository/data/model_repository.json
> +    }
Оказывается что model_repository просто расширяет automl_repository. Поэтому нет необходимости в base_repository.json. Если есть необходимость расширить репозиторий, нужно добавить ключ base_repository с путем к расширяющему репозиторию.

2021-07-06 14:06 UTC, nicl-nno approved these changes

2021-07-06 14:23 UTC, merged