edit requirements
nccr-itmo/FEDOT pull request #346
Opened 2021-06-30 15:05 UTC by MAGLeb

Add requirements for GitHub Actions. Now should be all alright.

2021-06-30 15:14 UTC, nicl-nno requested changes

2021-06-30 15:14 UTC, nicl-nno commented on examples/requirements.txt
> +openpyxl==3.0.7
Может сюда и содержание extra_requirements.txt перенести (а тот файл удалить?) tpot все равно только в примерах используется.

2021-07-01 14:04 UTC, MAGLeb commented on examples/requirements.txt
> +openpyxl==3.0.7
Подумал об этом, что-то сразу не сделал.

2021-07-01 14:08 UTC, J3FALL requested changes

2021-07-01 14:08 UTC, J3FALL commented on .github/workflows/manual-build.yml
>            pip install pytest-cov
Вручную запускал экшен?
Если все собирается - то гуд

2021-07-01 14:08 UTC, nicl-nno commented on examples/requirements.txt
> +openpyxl==3.0.7
Не, я имел в виду удалить extra_req, перенеся его содержание в examples/req.txt

2021-07-05 11:55 UTC, MAGLeb commented on .github/workflows/manual-build.yml
>            pip install pytest-cov
Последний раз manual-build успешно запускался 5 месяцев назад, сейчас тесты падают по времени, выходят за 40 минут. Обсудил с @BarabanovaIrina в manual-build проверять только интеграционные тесты, так как при каждом ПР у нас и так проверяются unit тесты.

2021-07-05 13:29 UTC, nicl-nno commented on .github/workflows/manual-build.yml
>            pip install pytest-cov
Если это поможет уложиться в 40 мин, то почему нет.

2021-07-06 08:20 UTC, MAGLeb commented on .github/workflows/manual-build.yml
>            pip install pytest-cov
Добавил описание к ПР.

2021-07-06 09:45 UTC, nicl-nno commented
>I also think it is worth adding tests for metrics on other datasets in the future, because only one test for the framework's performance metric is used (comparison with baseline and xgboost).

Да, разумно. Можешь отдельный issue создать на эту тему, чтобы не забыть.

2021-07-06 09:45 UTC, nicl-nno approved these changes

2021-07-06 09:46 UTC, J3FALL approved these changes

2021-07-06 12:53 UTC, merged