Iss343
nccr-itmo/FEDOT pull request #349
Opened 2021-07-01 19:31 UTC by gorokhovnik

Fix of issue #343

2021-07-01 21:17 UTC, nicl-nno requested changes

2021-07-01 21:17 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert np.sum(np.isinf(output_data.predict)) == 0
Для компактности можно убрать пустые строки.

2021-07-01 21:17 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +    ii.fit(input_data)
Думаю imputer вместо ii будет понятнее (здесь и выше)

2021-07-01 21:26 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
Сделал по просьбе @J3FALL

2021-07-01 21:31 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
Так а какой смысл в это закладывался?
Если и выводить что-то такое - то в  _fill_remaining_gaps, он же не всегда вызывается (в след строчке как раз if)

2021-07-01 21:34 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
If в следующей строчке проверяет, что сама операция - не imputation, чтобы не повторяться. Но если смущает, могу просто убрать

2021-07-01 21:36 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
То есть фактически заполнение идет всегда. (Проверка асимптотически занимает столько же времени, сколько и заполнение, поэтому как будто нет смысла сначала проверять, а потом заполнять)

2021-07-01 22:52 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +def test_inf_absence_after_pipeline_tuning():
Кстати, в тесте же вроде нет tuning?

2021-07-01 23:25 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +        assert np.sum(np.isinf(predicted)) == 0
Кажется вся разница с test_nan_absence_after_pipeline_fitting_from_scratch - в одном assert. Может объединить эти тесты?

2021-07-02 06:29 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +        assert np.sum(np.isinf(predicted)) == 0
Типа один тест на одну багу (unit тестирование же). Один проверяет отсутствие бесконечных элементов, второй пустых

2021-07-02 08:50 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +        assert np.sum(np.isinf(predicted)) == 0
unit-тест - это в первую очередь свой тест на каждый блок.  Тут вроде оба возможных бага связаны с одним и тем блоком (т.к. все строчки кода теста одинаковы). Конкретная проблема все равно будет известна - pytest сообщит, какой именно assert из двух не прошел.

Ну и вычислительно довольно дорого так делать - fit для кучи пайплайнов занимает некоторое время, и удаивать его из-за одной проверки кажется лишним.

2021-07-02 11:14 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
Да, первоначально идея была в следующем: если в input-е для операции пришли nan-ы или inf-ы, то нужно уведомить в лог, что они заполняются mean/most_frequent значениями.
Технически, проверка, если ли такие значения ~ заполнению таких значений.
Но получается, что в лог тогда часто попадает это уведомление.

2021-07-02 11:15 UTC, J3FALL commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
В целом, наверное, можем оставить это без логирования, а уже когда-нибудь в API добавим такую проверку входных данных и единожды в лог об этом напишем.

2021-07-02 20:25 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self.log.warn('NaN / Inf filling')
Оставил без логирования

2021-07-02 20:25 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +                           'rfe_lin_reg', 'rfe_non_lin_reg', 'simple_imputation']:
сделал

2021-07-02 20:26 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert np.sum(np.isinf(output_data.predict)) == 0
сделал

2021-07-02 20:26 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +    ii.fit(input_data)
сделал

2021-07-02 20:26 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +def test_inf_absence_after_pipeline_tuning():
исправил

2021-07-02 20:27 UTC, gorokhovnik commented on test/unit/data_operations/test_data_operations_implementations.py
> +        assert np.sum(np.isinf(predicted)) == 0
Объеднил

2021-07-02 22:38 UTC, nicl-nno approved these changes

2021-07-03 05:35 UTC, merged