Modified mutation schemes
nccr-itmo/FEDOT pull request #355
Opened 2021-07-07 22:28 UTC by nicl-nno

- Mutation schemes are modified to represent step-by-step approach for the pipeline design.
- Advisor class is implement to make to mutation more directed

2021-07-14 15:17 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







































* In the file [`fedot/core/validation/validation.py`](https://github.com/nccr-itmo/FEDOT/blob/b7b6080d416ba2cd8eaa1eb2966be0c1a2b6bc74/fedot/core/validation/validation.py):

> [Line 10:121](https://github.com/nccr-itmo/FEDOT/blob/b7b6080d416ba2cd8eaa1eb2966be0c1a2b6bc74/fedot/core/validation/validation.py#L10): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2021-07-22 11:10 UTC, Dreamlone requested changes

2021-07-22 11:10 UTC, Dreamlone commented on fedot/core/composer/advisor.py
> +class PipelineAdvisor(DefaultAdvisor):
Нужно добавить описание и ещё может название "MutationAdvisor" лучше бы подошло, но можно оставить и так, не принципиально

2021-07-22 14:12 UTC, Dreamlone commented
Еще пара комментариев:
При запуске credit_scoring_problem_multiobj.py возникает ошибка
AttributeError: 'Pipeline' object has no attribute 'visualise'
Полагаю, проблема в функции results_visualization

По поводу credit_scoring_problem:
Может уменьшить время выполнения у "credit_scoring_problem" до 5 минут?
Просто он у меня пыхтел 20 минут, чтобы выдать одиночную модель catboost, и это не очень обидно когда это делается за минут 5, но тут времени было достаточно чтобы найти разветвленный пайплайн

2021-07-26 16:19 UTC, nicl-nno commented on cases/credit_scoring/credit_scoring_problem.py
> +    metrics = automl.get_metrics()
[Добавил.](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-aeef3d78b8115fb4d0ac61b230d0a886e523239235b0ba178c103a97a83fa7f6L37-R34)

2021-07-26 16:19 UTC, nicl-nno commented on fedot/api/api_utils.py
> +            folds = None
[Записал](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR222-R223)

2021-07-26 16:19 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +        return possible_operations
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-f319fd14dd46608ccc4227f328444f1f0d7825bcdab8ed5d93223cf3ae8aac2eR30-R33).

2021-07-26 16:20 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +        super().__init__(task)
Конкретно тут это не особо важно, т.к. нужно только определить, является ли current_operation_id моделью или операцией. Поменял на [такое](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-f319fd14dd46608ccc4227f328444f1f0d7825bcdab8ed5d93223cf3ae8aac2eR24-R25).

2021-07-26 16:21 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +                                                   secondary=['one_hot_encoding', 'logit'], mutation_prob=1)
Описание [добавил](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R182-R189), графы слегка упростил.

2021-07-26 16:21 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +            candidates.remove(current_operation_id)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-f319fd14dd46608ccc4227f328444f1f0d7825bcdab8ed5d93223cf3ae8aac2eR64).

2021-07-26 16:21 UTC, nicl-nno commented on fedot/core/dag/graph.py
> +        return self.operator.graph_description()
Изменил.

2021-07-26 16:26 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +                    raise ValueError(f'Required mutation type is not found: {mutation_type}')
Разбил [так](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-adb53d31d35223b4209ffceadddd7fd47842a77c22c853a98a0df0de267d4325R126-R130).

2021-07-26 16:26 UTC, nicl-nno commented on fedot/core/composer/gp_composer/specific_operators.py
> +    if primary_nodes[0] != existing_pipeline.root_node:
Поменял.

2021-07-26 16:26 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +from fedot.core.composer.advisor import DefaultAdvisor
1 - это оптимизатор, который называется gp_comp. Так исторически сложилось
2 - удалил, лишний файл
3 - это именно композер - обертка для оптимизатора, которая адаптирует его для работы с pipeline

2021-07-26 16:30 UTC, nicl-nno commented on fedot/core/optimisers/graph.py
> +        self.nodes = [self._node_adapter.adapt(n) if not isinstance(n, OptNode) else n for n in self.nodes]
Упростил [так](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-63687a0ad8364bd5e1bdf20da6d700e0ea7b6c38181e088dd67c46414c266971R12-R23).

2021-07-26 16:30 UTC, nicl-nno commented on fedot/core/pipelines/validation_rules.py
> +def has_correct_data_sources(pipeline: Pipeline):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-8936bad33a31a40bfe9ebc8d0a8b7d9f7e277fbd41e2e3d997ae0b4c5116a6dcR369-R378).

2021-07-26 16:38 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +            self._repo = cls._op_repo
self._repo - это тот что используется в экзампляре, cls-переменные - статичны и хранят глобальное состояние (чтобы не считатывать json при каждом вызове). Сделал это для ускорения тестов пока, потом Ира сделает в своем PR реализацию получше.

2021-07-26 16:38 UTC, nicl-nno commented on test/unit/composer/test_history.py
> +    assert len(auto_model.history.parent_operators) >= 1
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R34-R35) условие (от 1 до 3).

2021-07-26 16:38 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +                                                         pipeline_third(), pipeline_fourth()]]
Вынес.

2021-07-26 16:38 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +                                             nodes_from=[primary]), primary]))
Убрал названия полей для большей лакончиности, но кажется сильно не сократишь.

2021-07-26 16:38 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +class PipelineAdvisor(DefaultAdvisor):
Поменял на PipelineChangeAdvisor.
Не уверен пока, что это только для мутации будет использоваться.

2021-07-26 16:47 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +        if parent_operations_ids:
>Тогда нужно указать это в нотации типов
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/355/files#diff-f319fd14dd46608ccc4227f328444f1f0d7825bcdab8ed5d93223cf3ae8aac2eR48-R49) на Optional[List]

2021-07-27 10:02 UTC, Dreamlone approved these changes
Еще нужно поправить pep8 - а то pep8speaks ругается 
А так - лайк ит

2021-07-29 16:20 UTC, merged