ARIMA using specific parameters ValueError bug fixed
nccr-itmo/FEDOT pull request #362
Opened 2021-07-13 14:51 UTC by ChrisLisbon

For some timeseries there were not relevant values for box-cox transformation inside ARIMA ts_implementations. Values like that now are filling with linear interpolation. The model works with the tuner on different ARIMA parameters.

2021-07-13 15:24 UTC, J3FALL requested changes

2021-07-13 15:24 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
Обрати внимание, что там опять лишние файлы попали в коммит - jpeg-и

2021-07-13 15:24 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +gf = SimpleGapFiller()
Не рекомендую так делать - теперь будет создаваться SimpleGapFiller каждый раз, когда будет импортироваться скрипт ts_implementations.py.
Нужно создавать инстанс в месте, где он используется

2021-07-13 15:24 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        _, self.lmbda = stats.boxcox(source_ts)
Мб переименовать self.lmbda в lambda ?
Не очень понятно, к чему тут экономить одну букву )

2021-07-13 15:24 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
1. Это принципиально держать функцию _inverse_boxcox статической и приватной? 
Если нет, то мб ее сделать либо публичной и статической, либо вообще к классу не привязывать.
2. Резонно добавить тест, который явно воспроизводит этот случай.
3. Чтобы упростить эту ситуацию, можно блок кода в else завернуть в отдельную функцию.
Так и тестировать ее будет легко

2021-07-13 15:28 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
Еще, кстати, один момент - если параметры могут быть float-типа, то сравнивание их на == 0.0 - крайне ненадежная тема. Из-за ошибок округления.
Лучше такие вещи сравнивать в стиле [np.isclose](https://numpy.org/doc/stable/reference/generated/numpy.isclose.html).
Там же недалеко есть подобная история: 
![image](https://user-images.githubusercontent.com/7864250/125480173-0e05130c-f8a6-4b87-9a58-801a32aaea7d.png)
Хоть там и есть преобразование в int, но я бы предложил исправить на сравнение float-типов

2021-07-14 06:29 UTC, Dreamlone requested changes

2021-07-14 06:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            res[nan_ind] = -100.0
Вроде ты тут забыла немного подчистить код после экспериментов
То есть я не вижу смысла оставлять строчку
```res[0] = np.nan```
Надо убрать

Плюс комментарии в этом фрагменте кода не помешали бы

Еще необязательный комментарий. Я бы строчку 
```nan_ind = np.argwhere(np.isnan(res))``` 
обернул в np.ravel(), так как np.argwhere выдает не одномерный массив с индексами, а что-то вроде [[0, 2, 3 ...]]. Не уверен, что это критично, но у меня иногда возникали проблемы при несоответствии размерностей

2021-07-14 06:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                res = gf.linear_interpolation(res)
У этой конструкции проверки есть недостаток. Рассмотрим случай, когда у нас есть ряд [nan, 1, 2, 10, nan, 4, nan]
В таком случае первую проверку он пройдёт (получим значение условия True) и ты восстановишь пропущенное значение средним (предположим, это среднее арифметическое равно 5). Дальше спускаемся ниже - получаем опять True. Заполняем уже последний пропуск 5-ой. Но до процедуры линейной интерполяции мы так и не добрались. 

Получили ряд [5, 1, 2, 10, nan, 4, 5]

Да, этот случай довольно редкий, но обрабатывать его точно стоит.

2021-07-14 06:37 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
> 1. Это принципиально держать функцию _inverse_boxcox статической и приватной?
>    Если нет, то мб ее сделать либо публичной и статической, либо вообще к классу не привязывать.

Тут я, пожалуй, вставлю свои пять копеек. Считаю, что это должен быть именно приватный метод, так как во первых, в классе в методе fit есть прямое преобразование Бокса-Кокса, значит и обратное должно быть где-то в этом месте (реализовано в рамка одного класса). Во вторых, обратное степенное преобразование нигде кроме этой реализации ARIMA и не используется - зачем в таком случае выносить это в отдельную функцию (правда теоретически, его можно применять в реализации STLForecastARIMAImplementation ниже, но так как видимо нет потребности в этом там, то я бы предложил оставить как есть).

2021-07-14 06:41 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
> Еще, кстати, один момент - если параметры могут быть float-типа, то сравнивание их на == 0.0 - крайне ненадежная тема. Из-за ошибок округления.

Ты конечно всё верно говоришь) Но только тут идёт сравнение индексов (если быть точным, проверка на наличие int объекта с конкретным значением в списке с индексами). Индексы не могут быть вещественными. Мб и нет необходимости добавлять np.isclose?

2021-07-14 13:04 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
Да, конкретно с индексами проблемы нет, плохо глядел )

2021-07-14 13:12 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
Окей, про inverse_boxcox - аргументировано. Я просто в целом не самый сторонник комбинации (private + static методы). Статик - вообще вещь спорная, т.к. в парадигме ооп нарушается логика "объектов".

2021-07-15 14:56 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
Поправила

2021-07-15 14:56 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +gf = SimpleGapFiller()
Перенесла в блок вызова

2021-07-15 15:16 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +gf = SimpleGapFiller()
гуд

2021-07-16 14:03 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return res
https://github.com/nccr-itmo/FEDOT/blob/980593ea4873bb4c6a97212dbc6e77c2d6d085cb/test/unit/tasks/test_forecasting.py#L105-L118

Тест добавила, функцию вынесла

2021-07-16 14:03 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        _, self.lmbda = stats.boxcox(source_ts)
self.lambda пытается вызвать метод, переименовала в lambda_params

2021-07-16 14:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            res[nan_ind] = -100.0
Код подчистила, закомментировала

2021-07-16 14:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                res = gf.linear_interpolation(res)
else заменила следующим:

if len(np.ravel(np.argwhere(np.isnan(res)))) != 0:

2021-07-16 14:06 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
а вот тут загвоздка в том, что без этих файлов тесты падают, и если посмотреть в мастере, то они там лежат, я их вернула в папку

2021-07-16 14:50 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        _, self.lmbda = stats.boxcox(source_ts)
мб тогда просто lambda_value?

2021-07-16 14:55 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
Они нужно для тестов, но после каждого запуска они ресайзятся и поэтому при коммите воспринимаются как измененнные. Пока можно просто заменить их на версию из мастера, потом изменю логику ресайза.

2021-07-16 14:59 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        _, self.lmbda = stats.boxcox(source_ts)
Поменяла на lambda_value

2021-07-19 07:42 UTC, Dreamlone approved these changes
В целом, ю хэв гат май апрув
Но стоит проверить что не так с тестами было

2021-07-19 07:42 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    input_ts_len = len(ts)
Сюда бы docstring описание добавить что и зачем тут делается

2021-07-20 10:01 UTC, ChrisLisbon commented on test/unit/tasks/test_forecasting.py
> +    input_ts_len = len(ts)
Добавила

2021-07-21 09:28 UTC, J3FALL approved these changes

2021-07-21 09:43 UTC, merged