Sparse lagged time series transformation operation implementation
nccr-itmo/FEDOT pull request #370
Opened 2021-07-27 13:41 UTC by ChrisLisbon

Sparse lagged ts_transformation was added. It based on sklearn TruncatedSVD operation with extracting significant components. The optimal number of components is determined on the threshold for the increase in the proportion of explained variance depending on the number of components.

2021-07-27 13:41 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`test/unit/pipelines/test_pipeline_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/13fada8dd4f24654d4543aabedfe82dc48e47207/test/unit/pipelines/test_pipeline_tuning.py):

> [Line 231:52](https://github.com/nccr-itmo/FEDOT/blob/13fada8dd4f24654d4543aabedfe82dc48e47207/test/unit/pipelines/test_pipeline_tuning.py#L231): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 235:30](https://github.com/nccr-itmo/FEDOT/blob/13fada8dd4f24654d4543aabedfe82dc48e47207/test/unit/pipelines/test_pipeline_tuning.py#L235): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-07-28 13:59 UTC, Dreamlone requested changes

2021-07-28 13:59 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                self.gain_tolerance = params.get('gain_tolerance')
По поводу передачи гиперпараметров мне понравилась идея Глеба с классом DefaultModelParamsRepository (см. [тут](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/repository/default_model_params_repository.py)). При таком подходе все значения гиперпараметров по умолчанию хранятся в отдельном json файле (см. [default_model_params.json](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/repository/data/default_model_params.json)). Не нужно будет их прямо в классах хардкодить

Я бы предложил сделать то же же самое для этой операции тоже. Если возникнут сложности, я бы предложил призвать на помощь Глеба @MAGLeb

2021-07-28 13:59 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +class SparseLaggedTransformationImplementation(DataOperationImplementation):
Реализация мне нравится, но я бы предложил сократить дублирование с классом "LaggedTransformationImplementation". Возможно стоит выделить общий класс-предок, определить общеупотребимые методы у него, и вызывать их в нужных местах. Что-то типо: 


Предок: LaggedImplementation

Потомки: SparseLaggedTransformationImplementation; LaggedTransformationImplementation

2021-07-28 13:59 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    :param forecast_length: forecast length
Тут можно поправить описание, уже другие параметры на вход функции подаются

2021-07-28 13:59 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components = int(features_columns.shape[1] / 2)
Лучше записать в логер, что таблица с признаками уполовинилась

Заодно нужен тест на эту функцию

2021-07-28 13:59 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +    for pipeline in pipelines:
Ты конечно довольно специфичную часть для внесения тестов выбрала :) 
В этом файле идет тестирование in-sample и out-of-sample прогнозирования (по сути, обёрток над пайплайнами). Хорошо, что ты проверяешь и то, как теперь цепочки со "sparse lagged" работают вместе с такими обёртками, но операция "sparse lagged" по идее так высоко не может принципиально ни на что влиять. То есть для in-sample wrapper'а нет особой разницы, будет ли пайплайн с "lagged" или со "sparse_lagged" операцией. Поэтому в этом месте тестировать новую операцию не релевантно - если просто одиночный пайплайн может нормально работать с новой операцией, то и wrapper'ы смогут.

Я бы предложил написать тесты в месте вроде "test\unit\data_operations\test_time_series_operations.py". Туда можно добавить проверку на то, корректно ли происходит sparse преобразование, и может ли цепочка адекватно обучиться с такой операцией в своей структуре. А эту часть можешь откатить к изначальной версии, или генерировать цепочку по разному от запуска к запуску - то с lagged операцией, то со sparse_lagged (принципиальной разницы быть не должно) - как посчитаешь нужным

2021-08-02 12:36 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                self.gain_tolerance = params.get('gain_tolerance')
Дописала для lagged и sparse_lagged в файл

2021-08-02 12:37 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +class SparseLaggedTransformationImplementation(DataOperationImplementation):
Выделила предка и передала ему основную функцию transform только с флагом, нужен sparse или нет

2021-08-02 12:37 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    :param forecast_length: forecast length
Поменяла

2021-08-02 12:37 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components = int(features_columns.shape[1] / 2)
Добавила тест на эту функцию и лог на этом этапе

2021-08-02 12:40 UTC, ChrisLisbon commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +    for pipeline in pipelines:
Откатила то, что написала в прошлый раз, добавила по предложенному пути тест на fit и predict цепочки (test_forecast_with_sparse_lagged)

2021-08-03 10:14 UTC, Dreamlone commented on fedot/core/repository/data/default_model_params.json
> +    "sparse_transform": false
Я так понял, эти гиперпараметры возникли потому что ты унаследовала две имплементации (lagged и sparse_lagged) от общего класса предка. 
Но lagged такие штуки как "n_components", "gain_tolerance" и "sparse_transform" не использует же, - значит их нужно убрать из гиперпараметров "lagged" операции

2021-08-03 10:14 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    :param input_data: time series for transformation
Первый аргумент не input_data, а time_series. Обнови docstring плиз, заодно можешь нотации типов добавить, но это не принцпиально

2021-08-03 10:14 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components = int(features_columns.shape[1] / 2)
Лучше просто передавай логер в качестве аргумента в эту функцию, и тогда не придётся возвращать log_info вместе с количеством компонент "components" 
А потом просто прямо в этой функции:
```self.log.info(log_info)```

2021-08-03 11:13 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components = int(features_columns.shape[1] / 2)
Done, в тесте тоже поменяла

2021-08-03 11:14 UTC, ChrisLisbon commented on fedot/core/repository/data/default_model_params.json
> +    "sparse_transform": false
Убрала

2021-08-03 11:14 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    :param input_data: time series for transformation
Поменяла в этом случае и добавила типы входных данных, где была в них уверена

2021-08-03 11:47 UTC, Dreamlone approved these changes
Небольшой комментарий оставил, а так апруваю

2021-08-03 11:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>          super().__init__()
Замени плиз во всех местах тут и ниже эту конструкцию
``` **params: Optional[dict] ```
на эту
``` **params ```

2021-08-03 11:48 UTC, merged