Composing history and pipeline export corrections
nccr-itmo/FEDOT pull request #372
Opened 2021-08-01 22:56 UTC by nicl-nno

The modifications of composing history and pipeline export for better compability with Fedot.Web

2021-08-11 06:17 UTC, MAGLeb requested changes

2021-08-13 12:52 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +        :root_node: root node of exported pipeline
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/372/files#diff-f4b05f3f14ea72c656a09e4098af6b9461d58bd93aae50477030a08921d477fbR85-R91).

2021-08-13 12:53 UTC, nicl-nno commented on fedot/api/api_utils.py
> +    if 'steady_state' in 'preset':
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/372/files#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR184-R185).

2021-08-13 12:53 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +            f.write(json.dumps(json.loads(json_data), indent=4))
Переделал [так](https://github.com/nccr-itmo/FEDOT/pull/372/files#diff-f4b05f3f14ea72c656a09e4098af6b9461d58bd93aae50477030a08921d477fbR105-R108)

2021-08-13 12:53 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +class SimpleArchive(list):
Перенес в archive.py

2021-08-13 12:53 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +                self.log.message(f'The chain was imported from the path: {path}.')
Поменял.

2021-08-17 15:49 UTC, MAGLeb approved these changes

2021-08-17 17:27 UTC, merged