Feature categorical error
nccr-itmo/FEDOT pull request #374
Opened 2021-08-03 19:07 UTC by MAGLeb

Closes #369 
Closes #366 

- [ ] #367 
- [ ] add tests

2021-08-03 19:07 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`fedot/core/pipelines/pipeline.py`](https://github.com/nccr-itmo/FEDOT/blob/ba13e03faeea8b8be4c9b1ae769b32b9fece111b/fedot/core/pipelines/pipeline.py):

> [Line 368:39](https://github.com/nccr-itmo/FEDOT/blob/ba13e03faeea8b8be4c9b1ae769b32b9fece111b/fedot/core/pipelines/pipeline.py#L368): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-08-03 19:50 UTC, nicl-nno requested changes
+ не помешало бы пару тестов: для одномодальных и мульти-модальных наборов данных, требующих энкодинга.

2021-08-03 19:50 UTC, nicl-nno commented on examples/features_categorical_error.py
> +    dataset_path = './data/sampled_app_train.csv'
Лучше через fedot_project_root

2021-08-03 19:50 UTC, nicl-nno commented on fedot/api/api_utils.py
> +                raise NotImplementedError(f"Don't have initial chain for task type: {task.task_type}")
Лучше initial pipeline

2021-08-03 19:50 UTC, nicl-nno commented on fedot/api/api_utils.py
> +    if isinstance(data, MultiModalData):
Рефакторинг API - это отдельная задача, но лучше тут хотя бы на 2 функции разбить (для multi-modal и для обычных данных).

А вообще кажется надо будет в будущем эти initial assumptions хранить в виде json-ов.

2021-08-03 19:50 UTC, nicl-nno commented on examples/features_categorical_error.py
> +    print(auto_metrics)
Лучше загнать это в функцию, чтобы можно было протестировать.

2021-08-03 19:50 UTC, nicl-nno commented on fedot/api/main.py
> +                self.current_pipeline = Pipeline(model)
Может сразу и scaling сюда добавить?

2021-08-03 19:50 UTC, nicl-nno commented on fedot/core/data/data.py
> +    # values less then MAX_UNIQ_VAL, then convert this column to string.
Лучше в виде docstring оформить, и указать, что на выходе (bool или data)

2021-08-03 19:50 UTC, nicl-nno commented on fedot/core/data/data.py
> +def _change_to_categorical(data: InputData):
Лучше в названии или описание уточнить , что именно тут делается с принаками - сейчас не очень понятно, что именно change.

2021-08-03 19:50 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +            self.encoders = _preprocess_categorical_features(input_data)
Может метод так и назвать - _encode_data_for_fit (если суть в этом)?

2021-08-03 19:50 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        if input_data.data_type == DataTypesEnum.table and data_has_categorical_features(input_data):
А эта проверка сработает для мультимодальных данных?

2021-08-03 19:50 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        for encoder in encoders:
А в одно-модальном случае может быть несколько энкодеров?

2021-08-04 06:39 UTC, Dreamlone requested changes

2021-08-04 06:39 UTC, Dreamlone commented on examples/features_categorical_error.py
> +    features, target = load_data()
Позапускай этот пример. Я его сделал так, чтобы в features были только категориальные признаки - такая возможность проверить всё ли корректно обрабатывается. Но у меня сейчас этот пример падает с ошибкой

2021-08-04 06:39 UTC, Dreamlone commented on fedot/core/data/data.py
> +            if uniq_val_in_col <= MAX_UNIQ_VAL:
Здесь и ниже добавь комментариев плез. Или же подробное docstring поможет объяснить зачем тут делаются все эти преобразования

2021-08-04 06:39 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +    encoders = []
Сюда нужно docstring и тест на эту функцию

2021-08-04 06:39 UTC, Dreamlone commented on fedot/api/api_utils.py
> +    node_final = _build_initial_assumption(task, data)
Мне кажется тут можно обойтись без обёртки 
"_obtain_initial_assumption - _build_initial_assumption"
Занеси весь код из _build_initial_assumption в функцию, из которой вызывается

2021-08-04 06:39 UTC, Dreamlone commented on fedot/api/api_utils.py
> +        if task.task_type == TaskTypesEnum.ts_forecasting:
Как и обещал, трезвым взглядом посмотрев, у меня появились идеи как это можно разбить. Я бы предложил разбить вот так:
```
if isinstance(data, MultiModalData):
    node_final = prepare_multimodal_nodes(**arg)
elif isinstance(data, InputData):
    node_final = prepare_unimodal_nodes(**arg)
```
Где arg - нужные тебе аргументы

Функции prepare_unimodal_nodes и prepare_multimodal_nodes внутри тоже можно разбивать на 
* multi_table_nodes
* uni_table_nodes
* multi_ts_nodes
* uni_ts_nodes
и так далее при необходимости. Но мне кажется пока действительно стоит остановиться на prepare_unimodal_nodes / prepare_multimodal_nodes и тогда должна будет выглядеть конструкция не так тяжеловесно как мне кажется :)

2021-08-06 12:03 UTC, MAGLeb commented on fedot/api/api_utils.py
> +                raise NotImplementedError(f"Don't have initial chain for task type: {task.task_type}")
[DONE](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eL281-L282)

2021-08-06 12:04 UTC, MAGLeb commented on fedot/api/api_utils.py
> +    if isinstance(data, MultiModalData):
[DONE](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR246-R273)

2021-08-06 12:05 UTC, MAGLeb commented on fedot/api/main.py
> +                self.current_pipeline = Pipeline(model)
Думаю да, [добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeL209-R211).

2021-08-06 12:06 UTC, MAGLeb commented on fedot/core/data/data.py
> +    # values less then MAX_UNIQ_VAL, then convert this column to string.
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL308-R315).

2021-08-06 12:07 UTC, MAGLeb commented on fedot/core/data/data.py
> +def _change_to_categorical(data: InputData):
[Изменил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL323-R359) название, добавил docstring, выделил функции во избежание дублирование кода.

2021-08-06 12:08 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +            self.encoders = _preprocess_categorical_features(input_data)
[Согласен](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL165-R222).

2021-08-06 12:08 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +        if input_data.data_type == DataTypesEnum.table and data_has_categorical_features(input_data):
Благодарю, очень важный момент. [Исправил.](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL165-R222).

2021-08-06 12:10 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +        for encoder in encoders:
На будущее писал, может быть моно будет добавить заполнение пропусков, или несколько операций предобработки данных.
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL336-R345) на один для UniModalData.

2021-08-06 12:11 UTC, MAGLeb commented on fedot/core/data/data.py
> +            if uniq_val_in_col <= MAX_UNIQ_VAL:
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eL308-R334).

2021-08-06 12:12 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +    encoders = []
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL348-R356) docstring.

2021-08-06 12:12 UTC, MAGLeb commented on fedot/api/api_utils.py
> +    node_final = _build_initial_assumption(task, data)
Согласен, [исправил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eL302-R313).

2021-08-06 12:13 UTC, MAGLeb commented on fedot/api/api_utils.py
> +        if task.task_type == TaskTypesEnum.ts_forecasting:
Отлично, [разделил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/e28d61040f6eef183f24621ec3385a6ef9f31bb8#diff-0975751fd631b03bfdbe49d411b336f269e14dec2d1a4a652eaf42698070ae0eR246-R270) на две функции обратки для UniModalData and MultiModalData.

2021-08-06 15:10 UTC, nicl-nno commented on fedot/core/data/data.py
> +    # values less then MAX_UNIQ_VAL, then convert this column to string.
Норм, только пропиши лучше возвращаемый тип через ->, как аннотацию

2021-08-06 15:14 UTC, nicl-nno commented on fedot/core/data/data.py
> +def _change_to_categorical(data: InputData):
_integer_to_categorical - это кодирование 0 в '0'? Может тогда что-то вроде _convert_categorical_int_to_str

2021-08-06 15:59 UTC, MAGLeb commented on fedot/core/data/data.py
> +def _change_to_categorical(data: InputData):
В целом не увидел разницы, исправил на _convert_categorical_int_to_str.

2021-08-06 15:59 UTC, MAGLeb commented on fedot/core/data/data.py
> +    # values less then MAX_UNIQ_VAL, then convert this column to string.
Добавил.

2021-08-06 16:00 UTC, MAGLeb commented on examples/features_categorical_error.py
> +    print(auto_metrics)
Удалил весь файл, перенес его в тест.

2021-08-06 16:00 UTC, MAGLeb commented on examples/features_categorical_error.py
> +    dataset_path = './data/sampled_app_train.csv'
Удалил весь файл, перенес его в тест.

2021-08-06 16:00 UTC, MAGLeb commented on examples/features_categorical_error.py
> +    features, target = load_data()
Удалил весь файл, перенес его в тест.

2021-08-06 16:08 UTC, nicl-nno commented on fedot/api/api_utils.py
> +        if task.task_type == TaskTypesEnum.ts_forecasting:
Ремарка - всё эти многочисленные

if isinstance(data, MultiModalData):
...
elif isinstance(data, InputData):
...

напрашиваются на переработку в стиле паттерна Strategy. Но не в этом PR, конечно.

2021-08-06 17:05 UTC, nicl-nno commented
А есть тест, который вот это:

![image](https://user-images.githubusercontent.com/5711814/128546876-6b7f6613-ae65-44c2-9a56-cecc46202c49.png)

проверяет?

2021-08-09 08:19 UTC, Dreamlone requested changes

2021-08-09 08:19 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +        Union[List[DataOperationImplementation], DataOperationImplementation]:
Всё кул, но считаю, что нужно еще немного внимания уделить операции заполнения пропусков. 
Моё первое предположение: Imputation стоит применять до операции энкодинга, так как не уверен, что OneHotEncoding отработает без ошибок если данные имеют пропуски. Если он их адекватно обрабатывает (мало ли), то можно оставить так, главное, чтобы не получилось что-то вроде такого (или случая, когда OneHotEncoding nan спишет в отдельную категорию):

``` 
Source
[['green'],
 [nan],
 ['red']]

Encoding 
[[1, 0],
 [nan, nan],
 [0, 1]]

Imputation
[[1, 0],
 [0.5, 0.5],
 [0, 1]]
```
Хотя я, конечно, не хочу отдавать отдавать обработку nan'ов на совесть sklearn'а.

Во вторых - Imputation нужно применять по разному на вещественных и на категориальных данных. Мы это учитывали в предыдущей версии обработки пропусков. Возможно, стоит опереться на вот функцию "[_fill_remaining_gaps](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/operations/operation.py#L168)" (её мы же убрали в рамках этого PR).

2021-08-09 08:19 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +
Нужно добавить тест, в котором будет проверяться, сможет ли  цепочка, например, из одного узла linear нормально обучиться на категориальных данных: с пропусками: сработает ли, или нет, наша реализованная "заглушка".

2021-08-10 10:45 UTC, nicl-nno approved these changes

2021-08-10 12:04 UTC, MAGLeb commented
> А есть тест, который вот это:
> 
> ![image](https://user-images.githubusercontent.com/5711814/128546876-6b7f6613-ae65-44c2-9a56-cecc46202c49.png)
> 
> проверяет?

Локально написал тестик, проверил. Решил что не стоит для бага добавлять тест.

2021-08-10 12:19 UTC, nicl-nno commented
> > А есть тест, который вот это:
> > ![image](https://user-images.githubusercontent.com/5711814/128546876-6b7f6613-ae65-44c2-9a56-cecc46202c49.png)
> > проверяет?
> 
> Локально написал тестик, проверил. Решил что не стоит для бага добавлять тест.

Ну раз этот баг вылез - то тест лучше иметь.

2021-08-11 06:58 UTC, MAGLeb commented
> > > А есть тест, который вот это:
> > > ![image](https://user-images.githubusercontent.com/5711814/128546876-6b7f6613-ae65-44c2-9a56-cecc46202c49.png)
> > > проверяет?
> > 
> > 
> > Локально написал тестик, проверил. Решил что не стоит для бага добавлять тест.
> 
> Ну раз этот баг вылез - то тест лучше иметь.

Так в коде прямым текстом

> > > А есть тест, который вот это:
> > > ![image](https://user-images.githubusercontent.com/5711814/128546876-6b7f6613-ae65-44c2-9a56-cecc46202c49.png)
> > > проверяет?
> > 
> > 
> > Локально написал тестик, проверил. Решил что не стоит для бага добавлять тест.
> 
> Ну раз этот баг вылез - то тест лучше иметь.

По сути этот "баг" состоял из одной строки, мы раньше удаляли прямой командой target из data: "del data[target]". И кажется нет необходимости писать тест для такого случая.

2021-08-11 07:00 UTC, nicl-nno commented
ок

2021-08-11 07:45 UTC, nicl-nno commented on fedot/core/data/data.py
> +    MAX_UNIQ_VAL, then convert this column to string.
>Мб стоит просто кодировать в строки все значения признаков, уникальных значений в которых больше двух, но меньше двенадцати

Да, пока норм. Полностью универсального решения все равно не придумать. В будущем можно добавить опциальную разметку типов данных в столбцах.

2021-08-11 10:42 UTC, MAGLeb commented on fedot/core/data/data.py
> +    MAX_UNIQ_VAL, then convert this column to string.
С бинарными признаками можно добавлять параметр в OneHotEncoder drop: 'if_binary' лишних столбцов не будет добавляться.

2021-08-11 12:30 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +        Union[List[DataOperationImplementation], DataOperationImplementation]:
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/516194ce8cf75c6bc816c153c3964807770c82e4#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL370-R364) в pipeline ImputationImplementation до OneHotEncoder, не использовал метод "_fill_remaining_gaps".

2021-08-11 12:30 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/516194ce8cf75c6bc816c153c3964807770c82e4#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fbR265-R273).

2021-08-11 12:52 UTC, MAGLeb commented on fedot/core/data/data.py
> +    MAX_UNIQ_VAL, then convert this column to string.
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/24850e79b6143dc186f4144afc1ab2025d470fa3#diff-5e39a9f9030a5ede5afe0312e144050dc38e5fdb5b9c773251d98c40fdbc807fL112-L120).

2021-08-12 08:12 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +
Сорри, ссылка нерабочая. Можешь обновить плиз? 
А без ссылки я не нашёл этого теста. Вот [это](https://github.com/nccr-itmo/FEDOT/blob/feature_categorical_error/test/unit/api/test_main_api.py#L254) оно? 

Если так, то тесты test_categorical_preprocessing_unidata_predefined и test_categorical_preprocessing_unidata_predefined_linear тогда по сути проверяют одно и то же.

2021-08-13 11:40 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/d78be2aaebe315d87ee7f014010fd554bad3f497#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fbL260-R290) несколько тестов, они покрывают проверку предобработки данных с категориальными и пропущенными данными.

2021-08-13 11:43 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +            _encode_data_for_prediction(input_data, self.encoders)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/374/commits/d78be2aaebe315d87ee7f014010fd554bad3f497#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aL184-L233) проверку на пропуски в данных или наличие категориальных признаков в данных. Также добавил проверку на наличие ImputerImplementation and OneHotEncoder в pipeline.

2021-08-15 10:43 UTC, Dreamlone approved these changes
Как исправишь баг, можно заливать в мастер
I like this pull request

2021-08-15 10:43 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline.py
> +                               linear, xgb, xgb_second, ridge, encoder_second, root])
Немного необычно ты тут объявляешь Pipeline конечно :)
Мне кажется, лучше просто Pipeline(root)

2021-08-15 13:43 UTC, merged