Made incremental parameters change
nccr-itmo/FEDOT pull request #375
Opened 2021-08-05 16:15 UTC by Dreamlone

A new class ParametersChanger has been implemented, which allows to gradually change the hyperparameters of operations when composing a pipeline. 

Slightly changed default hyperparameters values for some operations.

2021-08-05 16:22 UTC, Dreamlone commented
Есть один важный момент, на который я хочу обратить внимание: я никак не смог разобраться с тем, чтобы получать интервалы параметров из hyperopt. 

Например, если есть конструкция ``` hp.uniform(label, 10, 100) ```, и она записана в переменную hp_range, то вот каким образом из hp_range вытащить значения 10 и 100, как min и max, я так и не понял. А мне это бы очень пригодилось, например в методе "_incremental_change", так как не очень хорошо, кмк "вслепую" менять гиперпараметры не привязываясь к каким-то границам. 

В общем, нужна помощь, можем решить в рамках этого PR как можно это перебороть. 
Может Ира @BarabanovaIrina знает как это можно сделать

2021-08-05 16:25 UTC, nicl-nno requested changes

2021-08-05 16:25 UTC, nicl-nno commented on examples/ts_forecasting_composing.py
> +    mutation_types = [parameter_change_mutation]
Это связано с изменениями в PR или прост?

2021-08-05 16:25 UTC, nicl-nno commented on fedot/core/composer/gp_composer/specific_operators.py
> +            node.custom_params = get_new_operation_params(operation_name, current_params)
Может тут сделать выбор - получить random или incremental?

2021-08-05 16:25 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def __init__(self, log: Log = None, **params):
А почему тут убрана аннотация? params же все равно dict

2021-08-05 16:25 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        self.window_size = int(round(params.get('window_size')))
Вообще кстати в python>3.6 round без доп. аргумента и так должен возвращать int https://docs.python.org/3/library/functions.html#round

2021-08-05 16:25 UTC, nicl-nno commented on fedot/core/pipelines/tuning/hyperparams.py
> +        new_value = random.normalvariate(current_value, sigma)
А тут нет необходимости сверяться с макс и мин. значениями переменной?

2021-08-05 16:25 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size = 6
6 лучше в константу.

2021-08-06 08:05 UTC, Dreamlone commented on examples/ts_forecasting_composing.py
> +    mutation_types = [parameter_change_mutation]
Эту пометку я сделал для того, чтобы потом не забыть включить другие мутации в этот пример. После того, как закончу с этим PR, перед мержом в мастер, добавлю. 

Дело в том, что так удобнее проверять мои изменения, а они касаются только мутации параметров: мне нужен был пример, в котором все мутации, которые применяются, затрагивают только изменение гиперпараметров

2021-08-06 08:09 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def __init__(self, log: Log = None, **params):
А это обязательно? Я к тому, что разве может через **kwargs подаваться не словарь, а какая-то другая структура данных? 
Я эти конструкции убрал, потому что PyCharm на меня ругался. Писал что-то вроде 
``` 
Unexpected type(s): (Optional[dict]) Possible types: (SupportsRound) (float)  
Parameter params of fedot.core.operations.evaluation.operation_implementations.data_operations.ts_transformations.SparseLaggedTransformationImplementation.__init__ params: Dict[str, Optional[dict]]
``` 

в строчке 
```
 self.window_size = int(round(params.get('window_size')))
```

Но могу вернуть нотацию, просто PyCharm опять подсвечивать начинает

2021-08-06 08:13 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def __init__(self, log: Log = None, **params):
Ок

2021-08-06 12:34 UTC, ChrisLisbon commented on fedot/core/pipelines/tuning/hyperparams.py
> +    def _random_change(operation_name: str, parameter_name: str, current_value=None):
current_value вроде не используется

2021-08-06 15:20 UTC, BarabanovaIrina commented
> Есть один важный момент, на который я хочу обратить внимание: я никак не смог разобраться с тем, чтобы получать интервалы параметров из hyperopt.
> 
> Например, если есть конструкция `hp.uniform(label, 10, 100)`, и она записана в переменную hp_range, то вот каким образом из hp_range вытащить значения 10 и 100, как min и max, я так и не понял. А мне это бы очень пригодилось, например в методе "_incremental_change", так как не очень хорошо, кмк "вслепую" менять гиперпараметры не привязываясь к каким-то границам.
> 
> В общем, нужна помощь, можем решить в рамках этого PR как можно это перебороть.
> Может Ира @BarabanovaIrina знает как это можно сделать

Поэтому в SA модуле я делала [свой словарь](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/sensitivity/operations_hp_sensitivity/params_bounds.json) с граничными значениями. Как вариант (первое, что в голову пришло) сделать какой-то мапинг со словаря с граничными значениями к словарю для hyperopt. Из коробки (полазила) ничего не нашла. 
Возможно это будет полезно, если придется задавать границы параметров динамически, проверяя, например, разные области поиска. Нужно только придумать правило, по которому в одни гиперпараметры необходимо передавать граничные значения(для hp.uniform, например), а в другие категориальные (для hp.choice).

2021-08-09 09:04 UTC, Dreamlone commented
> Поэтому в SA модуле я делала [свой словарь](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/sensitivity/operations_hp_sensitivity/params_bounds.json) с граничными значениями. Как вариант (первое, что в голову пришло) сделать какой-то мапинг со словаря с граничными значениями к словарю для hyperopt. Из коробки (полазила) ничего не нашла.

А есть какой-нибудь механизм "слежения" за тем, чтобы значения в этом словаре были согласованы с [get_operation_parameter_range](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/hyperparams.py#L5)? 

Просто мне точно такая же мысль пришла (с отдельным словарём с границами интервалов гиперпараметров). 

> Нужно только придумать правило, по которому в одни гиперпараметры необходимо передавать граничные значения(для hp.uniform, например)

Это выглядит, по крайне мере сейчас, как что-то очень "велосипедное". Я попробую реализовать данную функциональность в рамках этого PR. Но, возможно, это повод для нас задуматься о переходе в будущем с hyperopt на их конкурентов, optuna. например.

2021-08-09 13:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        self.window_size = int(round(params.get('window_size')))
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/375/commits/c2048d56d46778751acabccc5fe26d01dd4c7e85)

2021-08-09 13:16 UTC, Dreamlone commented on fedot/core/pipelines/tuning/hyperparams.py
> +        new_value = random.normalvariate(current_value, sigma)
Ага, нужно
Но пока реализовать это довольно затратно (см. нашу переписку с Ирой в этом PR, можно начать с этого [комментария](https://github.com/nccr-itmo/FEDOT/pull/375#issuecomment-893591182) и ниже)

Я попробую реализовать словарь с интервалами (min / max) в рамках этого PR (см. [комментарий](https://github.com/nccr-itmo/FEDOT/pull/375#issuecomment-895061939)) 

Однако, даже сейчас это не сильно мешает, так как невалидные значения гиперпараметров обрабатываются на уровне операций у lagged и sparse_lagged (см. [_check_and_correct_window_size](https://github.com/nccr-itmo/FEDOT/pull/375/commits/48ea3402eac5d3a4ada8bb862b9e41dcc821e429#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R272-R292)). А пока кроме этих операций нигде не используется "incremental change"

2021-08-09 13:17 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size = 6
Немного это дело по другому [обыграл](https://github.com/nccr-itmo/FEDOT/pull/375/commits/48ea3402eac5d3a4ada8bb862b9e41dcc821e429), чтобы было удобнее исправлять значения скользящего окна

2021-08-09 13:28 UTC, BarabanovaIrina commented
> А есть какой-нибудь механизм "слежения" за тем, чтобы значения в этом словаре были согласованы с [get_operation_parameter_range](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/hyperparams.py#L5)?
> 
> Просто мне точно такая же мысль пришла (с отдельным словарём с границами интервалов гиперпараметров).

Нет, никакого механизма нет. Но я старалась брать границы для своего словаря границ из get_operation_parameter_range


> Это выглядит, по крайне мере сейчас, как что-то очень "велосипедное/костыльное". Я попробую реализовать данную функциональность в рамках этого PR. Но, возможно, это повод для нас задуматься о переходе в будущем с hyperopt на их конкурентов, optuna. например.

Ну другим решением может быть небольшая бд или что-то типа адаптера. 
Ну бд - это +1 зависимость и лишние телодвижения при установке фреймворка, поэтому пусть это будет последней идеей.
А вот для типа адаптера:
Пусть, например, у нас будет уже известная нам "схема" с json репозиторием, в котором будет след структура
{
hyperparams {
'model_name' {
    'param_name_1' {
        'range' : [a, b],
        'set': Null
    },
    'param_name_2' {
        'range' : Null,
        'set': ['a', 'b', 'c']
    },
}
}

А уже на уровне класса для репозитория по наличию того или иного поля для параметра определять, какую операцию делать внутри hyperopt. 
И пусть у Tune стратегии тоже будет свой репозиторий. как-то так.

Ну или optuna :D

2021-08-09 13:57 UTC, Dreamlone commented on fedot/core/pipelines/tuning/hyperparams.py
> +    def _random_change(operation_name: str, parameter_name: str, current_value=None):
[Исправлено](https://github.com/nccr-itmo/FEDOT/pull/375/commits/16bcb820ec1cfe2dd55b0c14f0871ad1c6cb7774), теперь опциональные аргументы передаются через **kwargs

2021-08-10 10:44 UTC, nicl-nno approved these changes
В целом, граничные значения можно и в отдельном PR учесть, если там много правок нужно.

2021-08-10 14:29 UTC, Dreamlone commented
> В целом, граничные значения можно и в отдельном PR учесть, если там много правок нужно.

Пожалуй, соглашусь с тем, что это задача не для этого пулл реквеста. Сделал соответствующее [issue](https://github.com/nccr-itmo/FEDOT/issues/384), чтобы не забыть 

В рамках этого PR, еще немного исправлю класс ParametersChanger в соответствии с замечаниями, и, думаю, можно будет мержить

2021-08-11 08:39 UTC, Dreamlone commented on fedot/core/composer/gp_composer/specific_operators.py
> +            node.custom_params = get_new_operation_params(operation_name, current_params)
Может лучше всё таки отдать прерогативу делать этот выбор новому классу ParametersChanger. Я реализовал это [так](https://github.com/nccr-itmo/FEDOT/pull/375/commits/b7e3c6d6174dce6e66373819768fada7c02f9b44). 

Уже внутри он в себе содержит "стратегии изменений" и решает какую из них к какому гиперпараметру применять. Может у нас в будущем возникнет задача применять к некоторым параметрам новый способ мутации, не только incremental или random. В таком случае, кмк, проще будет расширять

2021-08-12 09:03 UTC, ChrisLisbon approved these changes

2021-08-12 10:06 UTC, merged