Example on sparse_lagged implementation
nccr-itmo/FEDOT pull request #379
Opened 2021-08-09 13:05 UTC by ChrisLisbon

Sparse lagged implementation was overwritten with flag of using svd or not. In case of simple sparse, features matrix thinns out with the percent of components to save as a hyperparameter evenly. Simple way was added because of increasing time usage on short time series.

2021-08-09 13:10 UTC, nicl-nno commented
А в плане качества какие результы получаются без sparse и с разными видами sparse?

2021-08-09 13:13 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +def _sparse_matrix(logger, features_columns: np.array, n_components_perc=0.5, use_svd=False):
Добавила здесь флаг на использование разложения, но в гиперпараметры больше нигде не вносила. Пока решила эту реализацию оставить, не смотря на то что она медленнее, чем lagged работает. Пока стоит вопрос, как вынести на более высокие уровни флаг использования svd.

2021-08-09 13:16 UTC, ChrisLisbon commented
> А в плане качества какие результы получаются без sparse и с разными видами sparse?

Брала метрики MAE и MSE - прироста в качестве оба типа sparse не дают. Но зато во времени выигрываем порядка 20% на больших выборках (10тыс значений) с использованием sparse без svd (c svd еще не успела прогнать)

2021-08-09 13:19 UTC, nicl-nno commented on examples/sparse_lagged_tuning.py
> +import timeit
Думаю стоит в этом PR сложить в отдельную папку внутри examples все примеры, связанные с временными рядами.

2021-08-09 13:21 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        self.n_components = params.get('n_components')
А эт не дублирует код из LaggedImplementation?

2021-08-09 21:49 UTC, Dreamlone requested changes

2021-08-09 21:49 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +def _sparse_matrix(logger, features_columns: np.array, n_components_perc=0.5, use_svd=False):
Думаю, можно просто сделать также как с n_components_perc сделать:
```
self.use_svd = False
```

И тюнеру передать возможность выбирать между True и False - всё должно быть кул

2021-08-09 21:49 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components_perc = 0.5
У этой конструкции нет необходимости, раз ты по умолчанию всегда задаёшь n_components_perc=0.5

2021-08-11 07:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +def _sparse_matrix(logger, features_columns: np.array, n_components_perc=0.5, use_svd=False):
Вынесла, протестировала, тюнер и правда иногда меняет этот флаг

2021-08-11 07:05 UTC, ChrisLisbon commented on examples/sparse_lagged_tuning.py
> +import timeit
Сделала

2021-08-11 07:07 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        n_components_perc = 0.5
На самом деле это специально сделано (по крайней мере пока), тк при кастомной перезаписи параметров через словарь ( node_lagged.custom_params = {'window_size': window_size} ) он обращает остальные параметры по умолчанию в None, в связи с чем вся эта конструкция падает. То есть сейчас это просто защита от передачи не всех параметров в словарь.

2021-08-11 17:10 UTC, nicl-nno approved these changes

2021-08-11 18:18 UTC, merged