Hyperparameters adaptation fix
nccr-itmo/FEDOT pull request #380
Opened 2021-08-09 17:01 UTC by Dreamlone

There was fixed an issue with the transformation the Pipeline object into OptGraph and back. During this conversion through Adapter the values of hyperparameters were lost. 

For that fix, a new 'params' field has been added to the "content" structure.

Example of correct work can be seen in the file convert_pipeline.

2021-08-09 17:01 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/fedot_based_solutions/graph_model_optimization.py`](https://github.com/nccr-itmo/FEDOT/blob/4a90697a76b714a2c04e0cc588e7c2467dabffb3/examples/fedot_based_solutions/graph_model_optimization.py):

> [Line 79:121](https://github.com/nccr-itmo/FEDOT/blob/4a90697a76b714a2c04e0cc588e7c2467dabffb3/examples/fedot_based_solutions/graph_model_optimization.py#L79): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)



















* In the file [`test/unit/optimizer/test_gp_operators.py`](https://github.com/nccr-itmo/FEDOT/blob/4a90697a76b714a2c04e0cc588e7c2467dabffb3/test/unit/optimizer/test_gp_operators.py):

> [Line 191:121](https://github.com/nccr-itmo/FEDOT/blob/4a90697a76b714a2c04e0cc588e7c2467dabffb3/test/unit/optimizer/test_gp_operators.py#L191): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (144 > 120 characters)
> [Line 223:76](https://github.com/nccr-itmo/FEDOT/blob/4a90697a76b714a2c04e0cc588e7c2467dabffb3/test/unit/optimizer/test_gp_operators.py#L223): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'

2021-08-09 17:14 UTC, nicl-nno requested changes

2021-08-09 17:14 UTC, nicl-nno commented on examples/convert_pipeline.py
> +from fedot.core.optimisers.adapters import PipelineAdapter
Думаю нет смысла в таком файле и можно на его основе сделать тест, если нужно.

2021-08-09 17:14 UTC, nicl-nno commented on test/unit/dag/test_graph.py
> +    first = GraphNode(content={'name': 'n1'})
Выглядит слишком громоздко. 

Как вариант, можно внутри GraphNode сделать опциальную возможность принимать только str, оборачивая в словарь уже в конструкторе.

2021-08-09 17:14 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +    model_node = OptNode({'name': 'knn', 'params': 'default_params'}, [init_node])
А почему именно тут параметры явно указаны?

2021-08-09 17:14 UTC, nicl-nno commented on fedot/core/optimisers/adapters.py
> +        self._transform_to_pipeline_node(opt_graph.root_node)
Возможно тут и в adapt стоит сделать deepcopy? Неочевидно, что исходный opt_graph будет меняться.

2021-08-09 17:14 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    candidates = params.advisor.propose_parent(str(node_to_mutate.content['name']), None,
А в name может быть не str?

2021-08-09 17:14 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +                operation_type = passed_content['name'].operation_type
Наверное стоит это в функцию вынести.

2021-08-09 17:28 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +            print('------------------')
Это вроде не нужно.

2021-08-10 14:35 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +    model_node = OptNode({'name': 'knn', 'params': 'default_params'}, [init_node])
Это осталось после моих экспериментов с тем, чтобы нормально всё работало как бы поле content я ни задавал, [убрал](https://github.com/nccr-itmo/FEDOT/pull/380/commits/7a763e0455ba824650039e3c8ee16005624e3212)

2021-08-10 14:36 UTC, Dreamlone commented on fedot/core/pipelines/node.py
> +                operation_type = passed_content['name'].operation_type
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/380/commits/400a0cd628c709c6aeeec85ba1ee0da3ba456404). В целом, немного упростил эту конструкцию в инициализации узла

2021-08-10 14:37 UTC, Dreamlone commented on fedot/core/optimisers/adapters.py
> +        self._transform_to_pipeline_node(opt_graph.root_node)
Если правильно понял, то [воть](https://github.com/nccr-itmo/FEDOT/pull/380/commits/ae556a358a10df0f91588f2b0860d560855c8989)

2021-08-10 14:38 UTC, Dreamlone commented on test/unit/dag/test_graph.py
> +    first = GraphNode(content={'name': 'n1'})
Так и сделал, см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/380/commits/77f8d10e89cd11e21ea3fa233526ab05ac3eb6a7#diff-9b57e32e19c9dbcc26efc77d3d0ac3cfcb568482c76ae2ba886cb4a028b569dd)

2021-08-10 14:39 UTC, Dreamlone commented on examples/convert_pipeline.py
> +from fedot.core.optimisers.adapters import PipelineAdapter
[Done](https://github.com/nccr-itmo/FEDOT/pull/380/commits/77f8d10e89cd11e21ea3fa233526ab05ac3eb6a7#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R393-R419)

2021-08-10 14:40 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    candidates = params.advisor.propose_parent(str(node_to_mutate.content['name']), None,
Ага, в name может быть еще и объект Model или DataOperation 
В Node если в content['name'] является строкой - она как раз конвертируется в операцию

2021-08-10 14:41 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +            print('------------------')
Согласен, забыл убрать 
Сейчас [исправил](https://github.com/nccr-itmo/FEDOT/pull/380/commits/7a763e0455ba824650039e3c8ee16005624e3212#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27L368-L370)

2021-08-11 11:07 UTC, BarabanovaIrina commented on fedot/core/pipelines/validation.py
> +        graph = DirectAdapter(base_graph_class=Graph,
Возник вопрос. Чем существенно OptGraph отличается от просто Graph? То же самое с Node, там отличие только в том, что у OptNode есть адаптер, который конвертирует из OptNode в GraphNode и обратно. Каких-то уникальных методов я не заметила. 

Я поняла, что идея видимо в том, чтобы использовать объект в процессе оптимизации, но сейчас выглядят слегка как два очень похожих класса. Есть какие-то дальнейшие идеи для расширения?

2021-08-11 11:28 UTC, BarabanovaIrina commented on test/unit/optimizer/test_gp_operators.py
> +    assert np.array_equal(init_preds.predict, restored_preds.predict)
Это не юнит тест. 
Ты проверяешь то, что у тебя параметры после конвертации туда сюда не теряются. Зачем делать fit/predict? еще и дважды. Юнит тест проверяет одну микрофункциональность. А тут проверяется целая логика. 
Ок, допустим ты возразишь: "Но вдруг окажется, что во время обучения что-то идет не так, поэтому предикты могут оказаться совсем разными?"
Ответ: а это уже проблемы не этого теста, а теста который проверяет, как работает fit, и как работают отдельные методы, участвующие в fit, которые конвертируют данные и прочее. 
Этот тест проверяет, что поле params не теряется при конвертации. все. 

Меня наверное уже скоро побьют, что я постоянно тыкаю на "юнитность", но что поделать)
Твой тест выполняется 33ms. Твой тест без строк 400-405, 413-414 и 419 - выполняется 5ms. 

Пусть это будет общая рекомендация: не нужно пытаться раздувать тесты. Пусть их лучше будет много - но маленькие и конкретные, чем один, но большой.

2021-08-11 11:39 UTC, BarabanovaIrina commented
Кажется, вот [тут](https://github.com/nccr-itmo/FEDOT/pull/380/files#diff-2741db94fbb4d1ebea5aee06a47bbff0103caa7323acd020b61d57cc0bba45cbR46-R47) не обязательно вытаскивать значения путем list comprehension, потому что тут просто длины сравниваются. Можно напрямую вроде сравнивать len(dict.values()) и len(set(dict.values()))

[В описании аргументов функции](https://github.com/nccr-itmo/FEDOT/pull/380/files#diff-2741db94fbb4d1ebea5aee06a47bbff0103caa7323acd020b61d57cc0bba45cbR70) лучше не вызывать никаких методов, других функций, производить создание каких-то объектов. При запуске программы перед выполнением самого скрипта интерпретатор проходится по строкам определения всех классов и функций. И выполняет все то, что определено в скобках методов. Это может некритично в одном случае, но у нас тогда была такая ситуация с логгерами, которые плодились еще до запуска программы впустую, потому что во время работы уже самого скрипта создается новый объект, а все старые - просто забивают память и не используются. Так сказать "лучше в тело, чем без дела"))

2021-08-13 13:57 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +    assert np.array_equal(init_preds.predict, restored_preds.predict)
Согласен
Тест [разбил на два](https://github.com/nccr-itmo/FEDOT/pull/380/commits/4e1f65693eecc9cab64abde76c4c3383a9b27d59#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27), надеюсь, теперь они более юнитовые)

2021-08-13 13:58 UTC, Dreamlone commented on fedot/core/pipelines/validation.py
> +        graph = DirectAdapter(base_graph_class=Graph,
Мне кажется, этот вопрос лучше Коля @nicl-nno прояснит

2021-08-13 14:00 UTC, nicl-nno commented on fedot/core/pipelines/validation.py
> +        graph = DirectAdapter(base_graph_class=Graph,
Суть в том, что это концептуально разные сущности, т.к. оптимизатор может быть использован полностью назависимо от Graph, использованного как базовый класс для пайплайнов. Поэтому для корректности иерархии классов они сделаны раздельными.

2021-08-13 14:16 UTC, Dreamlone commented on fedot/core/pipelines/node.py
> +    def _process_content_init(self, passed_content: dict):
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/380/commits/d5227b52eac435793385dc48afeeeef4f0a1bc6c#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dL43-R58)

2021-08-13 14:16 UTC, Dreamlone commented on fedot/core/dag/graph_node.py
> +    :param content: dict for the content in node
Расширил описание, см. [тут](https://github.com/nccr-itmo/FEDOT/pull/380/commits/d5227b52eac435793385dc48afeeeef4f0a1bc6c#diff-e54796b27ec1332765525eb1271516fa0c1aac1f0c728d0394b2b6a6d015b425R12-R15)

2021-08-13 14:18 UTC, Dreamlone commented
Замечания в комментарии тоже исправлены
См. [тута](https://github.com/nccr-itmo/FEDOT/pull/380/commits/4e1f65693eecc9cab64abde76c4c3383a9b27d59#diff-2741db94fbb4d1ebea5aee06a47bbff0103caa7323acd020b61d57cc0bba45cb)

2021-08-13 14:27 UTC, BarabanovaIrina approved these changes

2021-08-13 14:37 UTC, nicl-nno approved these changes

2021-08-13 14:38 UTC, merged