Change logging when default tuner metric is set
nccr-itmo/FEDOT pull request #382
Opened 2021-08-10 10:31 UTC by J3FALL

Based on this issue: https://github.com/ITMO-NSS-team/fedot_electro_ts_case/issues/1

Previously, if `tuner_metric=None` in compose_fedot_model, a message in log is given: 'Default loss function was set'.
Now it is more user-friendly: 
![image](https://user-images.githubusercontent.com/7864250/128852041-3b6e1227-0f49-4527-9325-7b5e4626247f.png)

2021-08-10 11:00 UTC, Dreamlone requested changes

2021-08-10 11:00 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    generations = 1
Тест хорош, но я бы предложил пару правок:
1) Он очень долгий. Композер ты ограничили количеством поколений, но тюнеру тут раздолье - и он веселится примерно 1000 итераций. Предлагаю добавить ограничением ему по времени через timeout. Например, указать timeout=0.1

2) А можно как нибудь задать логгер до передачи в функцию и после выполнения композирования просто к нему обратиться и проверить, выводит ли он то сообщение, которое мы хотим (с оптимизируемой метрикой по умолчанию)?

2021-08-10 11:14 UTC, J3FALL commented on test/unit/api/test_api_utils.py
> +    generations = 1
1. Хм, ну в целом он у меня отработал за 23 секунды, но да, разумно поставить меньший таймаут. Поставлю.
2. Прямо через логгер, скорее всего, не получится, но можно попробовать перенаправить его на запись в файл и там сделать grep-like поиск нужной строчки. Но придется возиться с файлами.
Но возможен другой вариант - через фикстуры, нашел такую штуку - [testfixtures](https://pypi.org/project/testfixtures/). С ее помощью, кажется, можно за-mock-ать поток вывода и проверять сообщения. 
Проверю, если нормально работает, то мб эта штука пригодится и в других местах проекта.

2021-08-10 12:15 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    generations = 1
23 секунды на один такой тест - это очень много, как мне кажется :) 

2 - звучит очень сложно, а у нас тут уже лейбл "minor". Предлагаю оставить как есть - нужно будет просто тогда подправить время выполнения

2021-08-11 10:28 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    generations = 1
И правда выглядит к р а с u в о
Спасибо

2021-08-11 10:28 UTC, Dreamlone approved these changes

2021-08-11 11:48 UTC, merged