Iss403
nccr-itmo/FEDOT pull request #404
Opened 2021-08-27 10:28 UTC by gorokhovnik

Added ability to use custom search space and optimization algorithm in SequentialTuner and PipelineTuner

2021-08-28 12:34 UTC, J3FALL commented
> _No description provided._

Добавь, плз, небольшое описание к этому PR. Так другие разрабы чуть лучше поймут, что было смержено + понадобится для описания следующего релиза.

2021-08-28 13:22 UTC, J3FALL requested changes

2021-08-28 13:22 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +                        self.parameters_per_operation[operation][key] = value
Вроде был уже вопрос, но хотел уточнить - идея в том, чтобы заменить дефолтные значения теми, которые были переданы в custom_search_space?
Кажется, есть вариант упростить эту штуку

2021-08-28 13:22 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +                node_op_parameter_name = ''.join((str(node_id), ' || ', op_parameter_name))
История с захардкоженным разделителем не очень надежная. Мне кажется, лучше сделать либо паттерн-регулярное выражение в виде параметра SearchSpace, либо хотя бы выделить `separator = '| |'` как параметр.

2021-08-28 13:37 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +    def get_operation_parameter_range(self, operation_name: str, parameter_name: str = None, label: str = 'default'):
Название и описание не менял, могу подправить, как я его вижу, принимаю предложения.
Отдельный тест напишу

2021-08-28 13:38 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +        :param label: label to assign in hyperopt pyll
Нет, pyll
http://hyperopt.github.io/hyperopt/getting-started/search_spaces/
Предложения по улучшению описания также принимаются

2021-08-28 13:43 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +                return hyperopt_tuple[0](label, *hyperopt_tuple[1])
Порядок if тоже не мой - но могу поменять
В последнем блоке параметры из tuple[expression, options] (например, (hp.uniform, [1, 10])) превращаются в заданное пространство с меткой (например, в hp.uniform('0 || logit | C', 1, 10))

2021-08-28 13:45 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +class SearchSpace:
Могу, как назвать? search_space?

2021-08-28 13:47 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +    :attribute custom_search_space: dictionary of dictionaries of tuples (hyperopt expression, *params)
hyperopt.hp.choice, hyperopt.hp.uniform или еще что угодно из hyperopt.hp. Для выхода за формат hyperopta надо будет сильно все переконопатить, и не понятно, зачем

2021-08-28 13:48 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +        self.parameters_per_operation = {
Его можно вынести в отдельную функцию и переместить ниже, но эта функция будет использоваться только в конструкторе

2021-08-28 13:51 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +                        self.parameters_per_operation[operation][key] = value
Идея в том, чтобы заменить дефолтные значения теми, которые были переданы. 2 опции (replace_default_search_space True / False):
True - Заменить полностью набор search_space для модели
False - заменить (или дополнить), search_space только тех параметров, которые указаны в кастомном словаре, а остальные оставить дефолтными

2021-08-28 13:58 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/hyperparams.py
> +                node_op_parameter_name = ''.join((str(node_id), ' || ', op_parameter_name))
Тоже не мое авторство, но проблемы не вижу. Формат "айдишник ноды (всегда число) || модель (не содержит слешей) | название параметра (не содержит слешей)" выглядит вполне адекватным для технической переменной метки в hyperoptе и исключает дубликаты. А создание параметра / паттерна выражения дает возможность юзеру случайно задать что-нибудь не то, при этом не добавляя возможности влиять на алгоритм

2021-08-28 16:41 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +        :param label: label to assign in hyperopt pyll
Забавно, ок, тогда не трогаем

2021-08-28 16:42 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +                return hyperopt_tuple[0](label, *hyperopt_tuple[1])
Ок, как минимум, порядок можно поменять

2021-08-28 16:42 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +class SearchSpace:
Да

2021-08-28 16:44 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +    :attribute custom_search_space: dictionary of dictionaries of tuples (hyperopt expression, *params)
Окей, разве можно в описании метода сослаться на этот формат из hyperopt

2021-08-28 16:44 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +        self.parameters_per_operation = {
Да, норм, переноси

2021-08-28 16:50 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +                node_op_parameter_name = ''.join((str(node_id), ' || ', op_parameter_name))
Я не имел в виду вытаскивать его наружу, а оставить внутри приватным.
Но пока оставь, как есть, я ещё покопаюсь в этом

2021-08-30 19:34 UTC, J3FALL commented on fedot/core/pipelines/tuning/hyperparams.py
> +                        self.parameters_per_operation[operation][key] = value
Мб это тогда full_replace?
К вопросу о неймингу

2021-08-30 19:39 UTC, J3FALL approved these changes

2021-08-30 20:31 UTC, nicl-nno approved these changes

2021-08-31 07:59 UTC, merged