Encoding bug
nccr-itmo/FEDOT pull request #407
Opened 2021-08-30 14:31 UTC by MAGLeb

- add import/export for "one_hot_encoding" operation
- delete functionality: convert integer to categorical (because some tests did not work, some category in the test did not exist in train)
- add check: whether categories in test data contain in train data

2021-08-30 14:31 UTC, pep8speaks commented
Hello @MAGLeb! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cases/credit_scoring/example.py`](https://github.com/nccr-itmo/FEDOT/blob/71ad58106825daa26cff6fa481f2fc8d9def9a9a/cases/credit_scoring/example.py):

> [Line 10:37](https://github.com/nccr-itmo/FEDOT/blob/71ad58106825daa26cff6fa481f2fc8d9def9a9a/cases/credit_scoring/example.py#L10): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals

2021-08-31 10:27 UTC, Dreamlone commented
У меня вопрос. Функция [_fill_remaining_gaps](https://github.com/nccr-itmo/FEDOT/blob/encoding_bug/fedot/core/operations/operation.py#L168) до сих пор нужна? 

Честно говоря, я думал, что она ушла еще после этого [PR по категориальным признакам](https://github.com/nccr-itmo/FEDOT/pull/374). Есть какая-то причина, почему мы все равно применяем операцию заполнения пропусков на уровне операции?

2021-08-31 11:09 UTC, nicl-nno commented on cases/credit_scoring/example.py
> +import os
А этот пример нужен?

2021-08-31 11:16 UTC, nicl-nno requested changes

2021-08-31 11:16 UTC, nicl-nno commented on cases/oil.py
> +import os
Думаю в кейсах этот файл не обязателен, можно его в тестах использовать как пример.

Ну и файл oil2 вроде не используется никак.

2021-08-31 11:16 UTC, nicl-nno commented on fedot/core/data/data.py
>      return False
return isinstance(values[0], str)? 

Плюс, не нужна ли тут проверка на all или any вместо [0]?

2021-08-31 11:16 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +EMPIRICAL_ROWS_TO_DELETE = 0.1
Из названия непонятно, как и зачем эти строки удаляются.
И судя по коду ниже - это не percentage, а просто доля

2021-08-31 11:16 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +def _is_converted_to_float(s) -> bool:
_is_convertable_to_float скорее, раз проверяется возможно преобразования, а не то, что оно уже совершено.

2021-08-31 11:16 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        data.idx = np.delete(data.idx, list(rows_to_remove), 0)
А нужно ли такие строки удалять? Может достаточно помечать их как пропуски и заполнять обычным способом?

2021-08-31 12:44 UTC, MAGLeb commented on cases/credit_scoring/example.py
> +import os
Думаю что нет.

2021-08-31 12:44 UTC, MAGLeb commented on cases/oil.py
> +import os
Кажется что и в примеры он не нужен. Ничего нового в этом примере нет. Данные собственно говоря очень плохие.

2021-08-31 12:44 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +def _is_converted_to_float(s) -> bool:
Согласен.

2021-08-31 12:58 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +        data.idx = np.delete(data.idx, list(rows_to_remove), 0)
Собственно говоря, реализовал этот функционал именно для датасета oil.csv, какое-то наблюдение в середине датасета является названиями колонок, и в этом случае правильно удалять наблюдение. Но может быть случай когда только одна колонка принимает значение строки, тогда можно заполнять средним значением, но как это понять алгоритму, в каком случае заполнять средним, а в каком удалять? 
Если изменять на среднее или повторяющиеся значения, не зная природу пропусков (то есть почему данное значение отличается по типу от остальных в столбце), можно получить сильно выбивающиеся наблюдения. Принял решение удалять в этом случае.

С обработкой данных, очень много различных случаев, которые не перебрать все. Стоит задуматься какие данные мы можем принимать на вход и обрабатывать, а на какие выкидывать exseption.

2021-08-31 12:58 UTC, MAGLeb commented
> У меня вопрос. Функция [_fill_remaining_gaps](https://github.com/nccr-itmo/FEDOT/blob/encoding_bug/fedot/core/operations/operation.py#L168) до сих пор нужна?
> 
> Честно говоря, я думал, что она ушла еще после этого [PR по категориальным признакам](https://github.com/nccr-itmo/FEDOT/pull/374). Есть какая-то причина, почему мы все равно применяем операцию заполнения пропусков на уровне операции?

Не нужна, можно удалять.

2021-08-31 13:04 UTC, MAGLeb commented on fedot/core/data/data.py
>      return False
Думаю лишним не будет.  Исправил и в других случаях.

2021-08-31 16:16 UTC, nicl-nno commented on cases/oil.py
> +import os
Ну вот в тесты его и можно отправить, даже не упоминая что это oil

2021-08-31 16:23 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        data.idx = np.delete(data.idx, list(rows_to_remove), 0)
Мне кажется, удалять стоит то, у чего заведомо некорректный target, а остальное заполнять средним. 
Понятно что случай с дублированием заголовка довольно вырожденный.

2021-09-01 13:00 UTC, nicl-nno commented
https://github.com/nccr-itmo/FEDOT/issues/412

Вот эта ошибка ещё проявляется

2021-09-03 06:52 UTC, MAGLeb commented on cases/credit_scoring/example.py
> +import os
> > У меня вопрос. Функция [_fill_remaining_gaps](https://github.com/nccr-itmo/FEDOT/blob/encoding_bug/fedot/core/operations/operation.py#L168) до сих пор нужна?
> > Честно говоря, я думал, что она ушла еще после этого [PR по категориальным признакам](https://github.com/nccr-itmo/FEDOT/pull/374). Есть какая-то причина, почему мы все равно применяем операцию заполнения пропусков на уровне операции?
> 
> Не нужна, можно удалять.

[Deleted](https://github.com/nccr-itmo/FEDOT/pull/407/commits/e8f42fb31dd76f1e6f507f0aa3e67ec95f1ef78b#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932L168-L184)

2021-09-03 06:52 UTC, MAGLeb commented
> > У меня вопрос. Функция [_fill_remaining_gaps](https://github.com/nccr-itmo/FEDOT/blob/encoding_bug/fedot/core/operations/operation.py#L168) до сих пор нужна?
> > Честно говоря, я думал, что она ушла еще после этого [PR по категориальным признакам](https://github.com/nccr-itmo/FEDOT/pull/374). Есть какая-то причина, почему мы все равно применяем операцию заполнения пропусков на уровне операции?
> 
> Не нужна, можно удалять.

[Deleted](https://github.com/nccr-itmo/FEDOT/pull/407/commits/e8f42fb31dd76f1e6f507f0aa3e67ec95f1ef78b#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932L168-L184)

2021-09-14 07:46 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +EMPIRICAL_ROWS_TO_DELETE = 0.1
Add some descriptions for **EMPIRICAL_ROWS_TO_DELETE**

2021-09-14 07:57 UTC, MAGLeb commented on fedot/core/pipelines/pipeline.py
> +        data.idx = np.delete(data.idx, list(rows_to_remove), 0)
Delete rows with **None** target, other cases fill with mean or frequently.

2021-09-14 09:20 UTC, MAGLeb commented on cases/oil.py
> +import os
Don't handle this case of data. Delete oil example and oils data for this PR.

2021-09-14 09:20 UTC, MAGLeb commented
> #412
> 
> Вот эта ошибка ещё проявляется

Solve this error. Check for each runs.

2021-09-14 09:28 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/133232611-11fc9b5f-61ab-47fa-b09d-afd02fd7f4aa.png)

А датасет специально урезан?

2021-09-14 09:30 UTC, MAGLeb commented
> ![image](https://user-images.githubusercontent.com/5711814/133232611-11fc9b5f-61ab-47fa-b09d-afd02fd7f4aa.png)
> 
> А датасет специально урезан?

Нет, был урезанный в этой ветке. Подумал ты специально сделал.

2021-09-14 09:35 UTC, nicl-nno commented
Нет, можно вернуть как было.

2021-09-14 09:37 UTC, nicl-nno approved these changes
Верни плз scoring_train как было, а так вроде всё норм.

2021-09-14 11:52 UTC, merged