K-fold cross-validation for tabular data in Tuner implemented
nccr-itmo/FEDOT pull request #409
Opened 2021-08-31 14:03 UTC by ChrisLisbon

Before only for time series cross-validation in tuner was implemented, now it was added for tabular data too (classification, regression, clustering task).

2021-08-31 14:31 UTC, Dreamlone requested changes

2021-08-31 14:31 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +            # For tabular data forecasting task in-sample forecasting is provided
Фраза "For tabular data forecasting task in-sample forecasting is provided" тут не к месту. Лучше просто убрать комментарий

2021-08-31 14:31 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if data.task.task_type is TaskTypesEnum.ts_forecasting:
Лучше объединить это всё в одну конструкцию и проверять не по решаемой задаче, а по типу данных: 
```
if data.data_type is DataTypesEnum.table or data.data_type is DataTypesEnum.text:
    Делай кросс-валидацию для табличных данных
elif data.data_type is DataTypesEnum.table: 
    Делай кросс-валидацию для временных рядов
```

2021-08-31 14:31 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +            preds, test_target = cross_validation_predictions(pipeline, data, log=self.log,
Может обновить название, чтобы были сопоставимы. Можно типо такого сделать: cv_time_series_predictions и cv_tabular_predictions

2021-08-31 14:31 UTC, Dreamlone commented on fedot/core/validation/tune/tabular.py
> +    forecasting on each step (fold)
Описание надо попрваить, in-sample тут никакого нет

2021-08-31 14:31 UTC, Dreamlone commented on fedot/core/validation/tune/tabular.py
> +        if validation_blocks is None:
Тут надо переработать. validation_blocks - это штука, которая используется только при кросс-валидации временных рядов. Здесь же у нас только таблички - можешь смело выпиливать этот атавизм отсюдова

2021-08-31 15:04 UTC, Dreamlone commented on test/unit/validation/test_table_cv.py
> +    task = Task(task_type=TaskTypesEnum.classification)
Возможно я начитался постов про тестирование, или может меня слова Иры Барабановой про тесты всё таки настигли, но я предлагаю немного изменить нашу стратегию написания тестов для этого PR (мне кажется, тут это будет уместно).

По факту, этот тест проверяет не то, что производится тюнинг на заданном количестве фолдов, а то что просто "тюнер не падает при решении задачи классификации". А падать он не будет практически всегда, так как там внутри всё обложено обработкой исключений. 

Стоит добавить тест, который будет чуть пониже на уровень (или два): вызывай саму функцию cross_validation_tabular_predictions, и проверяй длину predictions и targets. Она должна меняться в зависимости от параметра cv_folds. Возможно, стоит добавить подобный тест и для кросс-валидации временных рядов для сохранения единообразия. Запуск таких тестов поможет удостовериться всё ли корректно работает и действительно всё ли бьётся на нужное количество фолдов.

2021-09-01 11:42 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/pipelines/tuning/tuner_interface.py`](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/fedot/core/pipelines/tuning/tuner_interface.py):

> [Line 185:121](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/fedot/core/pipelines/tuning/tuner_interface.py#L185): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (130 > 120 characters)







* In the file [`test.py`](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py):

> [Line 12:49](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py#L12): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 13:49](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py#L13): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 14:49](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py#L14): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 15:49](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py#L15): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 15:64](https://github.com/nccr-itmo/FEDOT/blob/068c36d3fd0934a33f53366587a2c1589f1e698d/test.py#L15): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-09-03 09:56 UTC, ChrisLisbon commented on fedot/core/pipelines/tuning/tuner_interface.py
> +            # For tabular data forecasting task in-sample forecasting is provided
Убрала

2021-09-03 09:56 UTC, ChrisLisbon commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if data.task.task_type is TaskTypesEnum.ts_forecasting:
Сделала

2021-09-03 09:56 UTC, ChrisLisbon commented on fedot/core/pipelines/tuning/tuner_interface.py
> +            preds, test_target = cross_validation_predictions(pipeline, data, log=self.log,
Зарефакторила

2021-09-03 09:56 UTC, ChrisLisbon commented on fedot/core/validation/tune/tabular.py
> +    forecasting on each step (fold)
Поправила

2021-09-03 09:57 UTC, ChrisLisbon commented on fedot/core/validation/tune/tabular.py
> +        if validation_blocks is None:
Переписала

2021-09-03 09:57 UTC, ChrisLisbon commented on test/unit/validation/test_table_cv.py
> +    task = Task(task_type=TaskTypesEnum.classification)
Сделала два теста на функции с самим разбиением cv, и один что тюнер не падает на табличных данных

2021-09-03 16:31 UTC, Dreamlone approved these changes

2021-09-03 16:31 UTC, Dreamlone commented on test/unit/validation/test_table_cv.py
> +                                                loss_params={"multi_class": "ovr"},
Поправь пожалуйста в рамках этого PR'а type hint у метода loss_params. Там почему-то 
```
loss_params:Callable = None
```
стоит, а это конечно не так. надо прописать, что это словарь

2021-09-06 09:30 UTC, merged