Fixed single feature selection
nccr-itmo/FEDOT pull request #414
Opened 2021-09-02 09:37 UTC by aPovidlo

Fix to issues #387

2021-09-02 09:37 UTC, pep8speaks commented
Hello @aPovidlo! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/unit/data_operations/test_data_operations_implementations.py`](https://github.com/nccr-itmo/FEDOT/blob/29ee07cef929b5d986078b23598e0eb124c8912d/test/unit/data_operations/test_data_operations_implementations.py):

> [Line 110:1](https://github.com/nccr-itmo/FEDOT/blob/29ee07cef929b5d986078b23598e0eb124c8912d/test/unit/data_operations/test_data_operations_implementations.py#L110): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1
> [Line 250:59](https://github.com/nccr-itmo/FEDOT/blob/29ee07cef929b5d986078b23598e0eb124c8912d/test/unit/data_operations/test_data_operations_implementations.py#L250): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-09-02 09:39 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +            return None
А это не приведет к тому, что для пайплайна, содержащщего такую модель, is_fitted всегда будет False?

2021-09-02 09:43 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +            train_input = get_single_feature_data(Task(TaskTypesEnum.regression))
Наличие подстрок class/reg в целом не гарантированно. Думаю сразу лучше в suitable_operation указывать нужный task_type.

2021-09-02 09:46 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +                            features=np.array([[1],
Для единообразия можно тоже записать в строчку

2021-09-02 09:47 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +            return None
Ну и стоит снабдить комментарием, чтобы было поняно, почему такая проверка понадобилась.

2021-09-02 11:09 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +                            features=np.array([[1],
Исправил

2021-09-02 11:09 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +            train_input = get_single_feature_data(Task(TaskTypesEnum.regression))
Исправил

2021-09-02 11:09 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +            return None
Комментарий добавил

2021-09-02 11:11 UTC, nicl-nno approved these changes

2021-09-02 16:01 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +        # To avoid getting an error from sklearn for 1-feature dataset
Сделал в функции

2021-09-03 07:29 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +                            data_type=DataTypesEnum.table)
Пожалуй, я немного включусь в этот PR :) 
Есть комментарий-обсуждение. Обратим внимание, что FeatureSelectionImplementation у нас унаследовано от класса EncodedInvariantImplementation. Это значит, что данная имплементация работает только с численными столбцами в таблице с признаками, игнорируя при этом те столбцы, значения в которых бинарны (принимают например только 0 и 1). 

Сделано это было затем, что при операции энкодинга (OneHotEncoding'a если быть точно при кодировании категориальных признаков) образуется довольно много таких бинарных столбцов. Например, из таблицы с двумя признаками:
```
[[7, красный],
 [1, синий],
 [5, красный]]
```
получается такая матрица
```
[[7, 1, 0],
 [1, 0, 1],
 [5, 1, 0]]
```
Отбрасывать в таком случае один из закодированных столбцов при применении алгоритма отбора признаков мне показалось нерелевантно в то время, когда я реализовывал эти классы. Поэтому он последние два столбца игнорирует. Отсюда есть два вопроса (Коля @nicl-nno, присоединяйся к обсуждению):

1) Мне кажется теперь, что отбрасывать один из категориальных столбцов вполне себе оправдано. То есть в приведенном выше примере, если алгоритм отбросит столбец номер 3, это будет значить, что-то вроде "Алгоритм считает, что важно знать, красный ли объект, при этом ему не важно знать синий ли он, или какого-либо другого цвета". При этом алгоритм сможет отсеивать и истинно бинарные признаки, которые закодированными в виде категорий >2 никогда и не были. Тогда, может стоит отказаться от описанной выше логики? 

2) Если мы решаем отставить всё как есть, то нужно модифицировать обработку, реализованную в данном PR. Так как если заменить функцию выше на вот такую:
```
train_input = InputData(idx=[0, 1, 2, 3, 4, 5],
                            features=np.array([[1, 0, 1],
                                               [2, 1, 0],
                                               [3, 1, 0],
                                               [7, 1, 0],
                                               [8, 1, 1],
                                               [9, 0, 0]]),
                            target=np.array([[0], [0], [0], [1], [1], [1]]),
                            task=task,
                            data_type=DataTypesEnum.table)
```

то реализованный тест упадёт с ошибкой.

2021-09-03 07:48 UTC, nicl-nno commented on test/unit/data_operations/test_data_operations_implementations.py
> +                            data_type=DataTypesEnum.table)
>отбрасывать один из категориальных столбцов вполне себе оправдано

Тут весь тест/PR вроде про ситуации, когда признак только один и отбрасывать нечего.

2021-09-03 07:52 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +                            data_type=DataTypesEnum.table)
Да, но я веду разговор о том, что FeatureSelectionImplementation в текущей реализации что таблица признаков
```
[[7],
 [1],
 [5]]
```
что таблица 
```
[[7, 1, 0],
 [1, 0, 1],
 [5, 1, 0]]
```
есть одна и та же таблица. Он все равно в обоих случаях пойдёт обрабатывать всего один крайний левый столбец. 
Но в этом PR это не учтено, и при обработке номер два вывалится ошибка, потому что до sklern'ского RFE дойдёт этот один столбец.

2021-09-03 15:51 UTC, Dreamlone requested changes

2021-09-03 15:51 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +        self._1d_feature_flag = None
Меня немного смущают числа в названиях переменных и методов)
Может лучше вроде self.is_fitted = False и потом менять на True только тогда, когда операция применялась на данных

2021-09-03 15:51 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +        """
Тут можно обойтись одной строчкой docstring, или вообще не делать описание, метод вроде сам за себя говорит что он делает

2021-09-03 15:51 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +    for task_type in [TaskTypesEnum.classification, TaskTypesEnum.regression]:
Стоит ещё добавить тест на случай обработки таблички вида
```
[[7, 1, 0],
 [1, 0, 1],
 [5, 1, 0]]
```

2021-09-03 16:27 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +        """
А есть ли смысл в этой функции с учетом изменений, когда можно обойтись уже только одной строчкой?

2021-09-03 16:29 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +        """
Пусть будет, с функцией несколько понятнее. К тому же она может где-то ещё пригодиться.
Только стоит её вынести из класса.

2021-09-04 09:23 UTC, J3FALL requested changes

2021-09-04 09:23 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                return None
Погодите, а можете объяснить этот момент - почему для случая, где всего один признак, self.is_fitted = True?
И нет ли тут side-эффекта, если возвращать None?

2021-09-04 09:23 UTC, J3FALL commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                return None
Мб я плохо вник в проблему PR-а, но тогда расскажите )

2021-09-07 07:54 UTC, Dreamlone requested changes

2021-09-07 07:54 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +            assert predicted.shape == train_input.features.shape
Тут много дублирования кода, по сравнению с тестом выше
Лучше используй product из itertools как вот [тут](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/pipelines/test_decompose_pipelines.py) в рамках одной функции

2021-09-07 08:26 UTC, Dreamlone approved these changes

2021-09-07 08:27 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                return None
Исправил [логическую ошибку с именем переменной](https://github.com/nccr-itmo/FEDOT/pull/414/commits/641aa00474ffcb1abb22a08f00e6152280f23bb1#diff-aade0320a1a02e0199dc3aac09c6b2981c6bed58a7e6b0913a2d8eedb39cc6ebR21) и [возвращением self.operation](https://github.com/nccr-itmo/FEDOT/pull/414/commits/641aa00474ffcb1abb22a08f00e6152280f23bb1#diff-aade0320a1a02e0199dc3aac09c6b2981c6bed58a7e6b0913a2d8eedb39cc6ebR39-R41).

2021-09-07 08:28 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +            assert predicted.shape == train_input.features.shape
Обернул оба теста в один.

2021-09-07 09:39 UTC, J3FALL approved these changes

2021-09-07 09:55 UTC, nicl-nno approved these changes

2021-09-07 10:00 UTC, merged