Api refactoring
nccr-itmo/FEDOT pull request #416
Opened 2021-09-06 12:42 UTC by v1docq

2021-09-06 12:42 UTC, pep8speaks commented
Hello @v1docq! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`fedot/api/api_utils/params.py`](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/fedot/api/api_utils/params.py):

> [Line 26:5](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/fedot/api/api_utils/params.py#L26): [E301](https://duckduckgo.com/?q=pep8%20E301) expected 1 blank line, found 0







* In the file [`fedot/api/main.py`](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/fedot/api/main.py):

> [Line 67:9](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/fedot/api/main.py#L67): [E122](https://duckduckgo.com/?q=pep8%20E122) continuation line missing indentation or outdented









* In the file [`test/unit/api/test_main_api.py`](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/test/unit/api/test_main_api.py):

> [Line 306:32](https://github.com/nccr-itmo/FEDOT/blob/8d8c5bf8feb52ea79bd055abbf14ff024c1bb058/test/unit/api/test_main_api.py#L306): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-09-06 16:33 UTC, nicl-nno commented on fedot/api/api_utils/api_utils.py
> +class Api_facade(API_data_helper, API_composer_helper, API_metrics_helper, API_initial_assumptions_helper):
По названиям ещё момент - у нас вроде везде CamelCase используется в названих классов.

2021-09-06 16:33 UTC, nicl-nno commented on fedot/api/api_utils/api_utils.py
> +                             'Prediction': prediction}).to_csv(r'./predictions.csv', index=False)
Неочевидно, что возвращается. Путь к файлу?

2021-09-06 16:34 UTC, nicl-nno commented on fedot/api/api_utils/composer.py
> +        return init_chain
Отсылки к chain лучше заменить на pipeline (здесь и далее)

2021-09-06 16:34 UTC, nicl-nno commented on fedot/api/api_utils/composer.py
> +                            ):
Может всё вот это в виде словаря и передавать?

2021-09-06 16:35 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +            self.task_params = TsForecastingParams(forecast_length=30)
Тут можно выводить варнинг, что глубина прогнозирования задана = 30.

2021-09-06 16:36 UTC, nicl-nno commented on fedot/api/api_utils/presets_types.py
> +light_models = ['dt', 'dtreg', 'logit', 'linear', 'lasso', 'ridge', 'knn', 'ar']
Это место в мастере чуть изменилось.

2021-09-06 16:37 UTC, nicl-nno commented on fedot/api/api_utils/composer.py
> +        optimizer_parameters = GPGraphOptimiserParameters(genetic_scheme_type=GeneticSchemeTypesEnum.parameter_free)
Не потеряй [правки ](https://github.com/nccr-itmo/FEDOT/blob/acda0b9881d26739f8964874233236a499e0199e/fedot/api/api_utils.py#L188)из мастера в этом месте.

2021-09-06 16:38 UTC, nicl-nno commented on test/unit/api/test_api_utils.py
> +composer_checker = API_composer_helper()
Непонятна разница между checker и helper.

2021-09-07 09:28 UTC, v1docq commented on test/unit/api/test_api_utils.py
> +composer_checker = API_composer_helper()
Привел в соотвествие

2021-09-07 09:43 UTC, v1docq commented on fedot/api/api_utils/composer.py
> +        optimizer_parameters = GPGraphOptimiserParameters(genetic_scheme_type=GeneticSchemeTypesEnum.parameter_free)
Забрал изменения по оператором мутаций и начальным приближениям

2021-09-07 09:44 UTC, v1docq commented on fedot/api/api_utils/composer.py
> +                            ):
Сделал в виде словаря

2021-09-07 09:44 UTC, v1docq commented on fedot/api/api_utils/params.py
> +            self.task_params = TsForecastingParams(forecast_length=30)
Поставил варнинг

2021-09-07 09:44 UTC, v1docq commented on fedot/api/api_utils/composer.py
> +        return init_chain
Привел в соответствие

2021-09-07 09:52 UTC, v1docq commented on fedot/api/api_utils/api_utils.py
> +class Api_facade(API_data_helper, API_composer_helper, API_metrics_helper, API_initial_assumptions_helper):
исправил

2021-09-07 09:59 UTC, v1docq commented on fedot/api/api_utils/presets_types.py
> +light_models = ['dt', 'dtreg', 'logit', 'linear', 'lasso', 'ridge', 'knn', 'ar']
Добавил пресеты связанные с steadu state

2021-09-07 16:48 UTC, nicl-nno commented on fedot/api/api_utils/composer.py
> +        return init_chain
![image](https://user-images.githubusercontent.com/5711814/132381868-92df1fe9-1efd-4f8f-8373-b17cfd76c8f6.png)

Ну кое-где осталось

2021-09-07 16:48 UTC, nicl-nno commented on fedot/api/api_utils/composer.py
> +                            ):
![image](https://user-images.githubusercontent.com/5711814/132381928-af06ad3f-1f7b-43a7-a311-b4fe5540abc4.png)


Кажется нет.

2021-09-07 16:49 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +            self.task_params = TsForecastingParams(forecast_length=30)
30 лучше вынести в константу, а то может рассинхронизировать.

2021-09-07 16:49 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +
строка выглядит лишней

2021-09-08 07:20 UTC, Dreamlone commented
У меня есть вопрос. Такая история коммитов после каких-то изменений намеренно такой стала?
![image](https://user-images.githubusercontent.com/52418437/132463716-2a657722-2fe9-483f-98ca-f48f6d9770d4.png)

Название коммитов же должно сообщать о том, какие изменения были сделаны, а тут совсем ничего не понятно. Я понимаю, что и сам пишу коммиты не по всем правилам, но ver 1, ver 2, ver 3, кмк, уже перебор 

С одной стороны, раз у нас все коммиты после мержа PR в мастер и так сквошатся, понятно, что при разработке FEDOT'а со временем начинаешь скорее мыслить категориями пулл реквестов, нежели чем коммитов, но всё же 

Понятное дело, что это комментарий на будущее

2021-09-08 08:13 UTC, Dreamlone requested changes

2021-09-08 08:13 UTC, Dreamlone commented on fedot/api/api_utils/presets.py
> +                                'light_steady_state': extended_excluded}
Тоже дублирование с fedot\api\api_utils\presets_types.py

2021-09-08 08:13 UTC, Dreamlone commented on fedot/core/pipelines/tuning/hyperparams.py
> +                current_value = None
Объясни плез почему возникла потребность в этой конструкции? Выглядит как борьба с симптомами, а не с причиной. До этого метода не должны по идее доходить никакие ни пустые словари, ни строки, ни что-то подобное, только "каждой операции по своему гиперпараметру, некоторым - по два...")

В общем, мне нужно понять, в чем была проблема

2021-09-08 08:18 UTC, Dreamlone commented
Ещё стоит прогнать примеры в cases и examples. У меня например упал пример examples\fedot_api_example.py вот с такой ошибкой: 
![image](https://user-images.githubusercontent.com/52418437/132472842-223dec15-bfd6-4a95-8266-afd770afdb72.png)

2021-09-08 09:45 UTC, v1docq commented on fedot/api/api_utils/presets.py
> +                                'light_steady_state': extended_excluded}
Убрал дублирование.

2021-09-08 09:47 UTC, v1docq commented on fedot/api/api_utils.py
>      'acc': ClassificationMetricsEnum.accuracy,
Убрал дубликат

2021-09-08 10:54 UTC, v1docq commented on fedot/api/api_utils/params.py
> +            self.task_params = TsForecastingParams(forecast_length=30)
Вынес в конструктор класса.

2021-09-08 12:48 UTC, v1docq commented on fedot/api/api_utils/composer.py
> +        return init_chain
Убрал

2021-09-08 13:42 UTC, v1docq commented on fedot/api/api_utils/api_utils.py
> +                             'Prediction': prediction}).to_csv(r'./predictions.csv', index=False)
Убрал return, вместо этого просто оставил сообщение от логгера

2021-09-08 14:18 UTC, Dreamlone commented on fedot/core/pipelines/tuning/hyperparams.py
> +                current_value = None
Не смог воспроизвести тот случай, который вы описывали. В общем, не страшно, пусть лучше except будет, чем не будет
Но возможно стоит добавить TODO, что надо выяснить нужна ли обработка или нет

2021-09-08 14:30 UTC, nicl-nno commented on fedot/core/pipelines/tuning/hyperparams.py
> +                current_value = None
Как вариант - можно добавить ворнинг, чтобы было видно, что что-то не так.

2021-09-08 14:50 UTC, v1docq commented on fedot/api/api_utils/params.py
> +
убрал

2021-09-08 15:29 UTC, nicl-nno commented on fedot/api/api_utils/api_utils.py
> +                             'Prediction': prediction}).to_csv(r'./predictions.csv', index=False)
Лучше совсем убрать

2021-09-08 15:31 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +            self.task_params = TsForecastingParams(forecast_length=30)
Всё ещё в строки явно написано

2021-09-08 15:31 UTC, nicl-nno approved these changes

2021-09-08 15:40 UTC, Dreamlone approved these changes
Только описание добавь в PR, хоть пару фраз, что изменилось по сравнению с прошлой версией

2021-09-08 16:08 UTC, merged