CLSTM torch implementation
nccr-itmo/FEDOT pull request #420
Opened 2021-09-09 08:52 UTC by valer1435

- implemented CLSTM model in pytorch

2021-09-09 08:52 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`test/unit/tasks/test_forecasting.py`](https://github.com/nccr-itmo/FEDOT/blob/12691c1f0253a2c00a867c6f6d144fb93dcf298f/test/unit/tasks/test_forecasting.py):

> [Line 51:1](https://github.com/nccr-itmo/FEDOT/blob/12691c1f0253a2c00a867c6f6d144fb93dcf298f/test/unit/tasks/test_forecasting.py#L51): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

2021-09-09 09:13 UTC, Dreamlone requested changes

2021-09-09 09:13 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.linear = nn.Linear(self.hidden_size, output_size)
Предлагаю привести в порядок слои. Предлагаю разбить всё именно по слоям, то есть занесём функции активации под объекты слоёв. Я имею в виду что-то вроде такого:
```
self.layer1 = nn.Sequential(nn.Conv2d(1, 16, kernel_size=2, stride=1, padding=1),
                            nn.ReLU(),
                            nn.MaxPool2d(kernel_size=2, stride=2))
self.layer2 = nn.Sequential(nn.Conv2d(16, 32, kernel_size=2, stride=1, padding=1),
                            nn.ReLU(),
                            nn.MaxPool2d(kernel_size=2, stride=1))
self.layer3 = nn.Sequential(nn.Conv2d(32, 16, kernel_size=2, stride=1, padding=1),
                            nn.ReLU(),
                            nn.Upsample(scale_factor=0.99, mode='nearest'))
self.layer4 = nn.Sequential(nn.Conv2d(16, 1, kernel_size=2, stride=1, padding=1),
                            nn.ReLU(),
                            nn.Upsample(scale_factor=1.97, mode='bilinear'))
```
Будет выглядеть более "чисто"
Ещё стоит выяснить, не пропущена ли функция активации перед вторым слоем свёртки?

2021-09-09 09:13 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        predictions = self.linear(self.hidden_cell[0])
Точно уверен, что всё правильно передаёшь? 
Возможно, в туториалах PyTorch'а есть более прозрачные примеры реализации forward метода для LSTM сетей. Если разобраться с этим, возможно получится перебороть константный output при прогнозировании последовательностей. 

Я например, пробовал менять 
```
predictions = self.linear(self.hidden_cell[0])
```
на 
```
predictions = self.linear(self.hidden_cell[1])
```
и прогноз получался получше

2021-09-09 09:13 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return torch.Tensor(self.data.features[idx])
Может есть опция избежать создания таких классов? 
Я раньше использовал такую конструкцию для подготовки тензоров:
```
import torch.utils.data as data_utils
train = data_utils.TensorDataset(x_train, y_train)
```
где x_train и y_train - это обычные numpy массивы
Тут можно сделать что-то подобное?

2021-09-09 09:13 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        data_loader = DataLoader(dataset, batch_size=64)
batch_size стоит вынести в гиперпараметры операции

2021-09-09 09:13 UTC, Dreamlone commented on fedot/core/repository/data/model_repository.json
> +        "ts_specific"
Тег не подходящий, нужно убрать. 
Тег "ts_specific" означает, что данная модель/операция не требует предобработки временного ряда в lagged / sparse_lagged операциях. А LSTM в текущей реализации требует перед собой применения lagged. 

Так что убирай этот тег отсюдова)

2021-09-09 09:13 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +def get_ts_data_long(n_steps=80, forecast_length=5):
Лучше будет убрать этот большой временной ряд из тестов в примеры (examples).
И test/data/ts_long.csv файл соответственно надо перенести из тестов. Для тестирования лучше оставить что-то более легковесное, чтобы тест проходил за секнуд 5-6 максимум. 

В общем, предлагаю сделать пример запуска пайплайна с LSTM в examples/time_series и там показать на длинном временном ряду какие прогнозы получаются

2021-09-09 09:29 UTC, nicl-nno commented on test/unit/tasks/test_forecasting.py
> +    node_lagged.custom_params = {'window_size': window_size}
А для LSTM не маловат window size? Я бы ожидал, что для эффекта памяти окно мб побольше.

2021-09-09 09:29 UTC, Dreamlone commented
Ещё есть два момента, которые нужно не забыть:
1) Сериализация PyTorch сетей - это дело безумно интересное) Поэтому предполагаю, что у нас возникнут проблемы с импортом/экспортом цепочек. Как сеть будет готова - с этим нужно будет разобраться. 
2) Хотелось бы обучать нейросети на видеокарте. Для этого в своих проектах я раньше использовал простенькую функцию
```
def get_device():
    """
    Method for getting available devices.
    """

    if torch.cuda.is_available():
        device = 'cuda:0'
    else:
        device = 'cpu'
    return device
```
Ну не будем забывать, что на GPU нужно будет переносить ещё и данные, чтобы модель могла обучаться

2021-09-10 13:38 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.linear = nn.Linear(self.hidden_size, output_size)
Переделал

2021-09-10 13:40 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        predictions = self.linear(self.hidden_cell[0])
Очень странно, кстати, потому что в этой ячейке лежит "ненужная" информация (труба), в которую скидывается устаревшая информация (но могу ошибаться)

2021-09-10 13:41 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return torch.Tensor(self.data.features[idx])
Переделал с использованием TensorDataset

2021-09-10 13:41 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        data_loader = DataLoader(dataset, batch_size=64)
Вынес batch_size в гиперпараметры

2021-09-10 13:41 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +        "ts_specific"
Переделал пайплайн и теперь "ts_specific" актуальна

2021-09-10 13:42 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +def get_ts_data_long(n_steps=80, forecast_length=5):
Переместил все в example

2021-09-10 13:43 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    node_lagged.custom_params = {'window_size': window_size}
Теперь с таким окном теперь получается вполне неплохой результат при небольшом горизонте прогнозирования (48 для traffic_volume)

2021-09-10 13:51 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
А где это поле используется?

2021-09-10 13:58 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
В методе init_hidden

2021-09-10 14:04 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
![image](https://user-images.githubusercontent.com/5711814/132865983-55114b03-1af7-4cea-b05f-6666c99f34ce.png)

Вроде нет?

2021-09-16 20:53 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
> +        "ts_specific"
>"ts_specific" означает, что данная модель/операция не требует предобработки временного ряда в lagged / sparse_lagged операциях.

Может тэг переименовать как-то тогда? А то действительно неочевидно.

2021-09-17 05:38 UTC, Dreamlone commented on fedot/core/repository/data/model_repository.json
> +        "ts_specific"
Да, согласен, можно придумать какое-нибудь более подходящее, могу предложить например "non_lagged"

2021-09-17 13:19 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
self.device

2021-09-17 13:24 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
Исходный вопрос был про self.cnn2_output_size

2021-09-17 13:37 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
![image](https://user-images.githubusercontent.com/32017472/133791614-70d7ed0c-6a12-4de0-b23d-4a516fd2e95d.png)

Здесь

2021-09-17 14:18 UTC, nicl-nno commented on examples/time_series/ts_clstm_forecasting.py
> +    # print(f'Prediction from pipeline loaded from dict {predicted_output_from_dict[:4]}')
Надо всё это не забыть убрать.

2021-09-17 15:12 UTC, Dreamlone requested changes

2021-09-17 15:12 UTC, Dreamlone commented on fedot/core/repository/data/model_repository.json
> +        "non_lagged"
Тут то ты заменил, а что на счет других мест в репозитории, где осталось старое название тега?) - Надо поправить

2021-09-17 15:12 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    }
А можно сделать количество эпох ещё поменьше? 1-2 например. Хотелось бы, чтобы тест быстро работал

2021-09-17 15:12 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    predicted = out_of_sample_ts_forecast(pipeline=pipeline,
out_of_sample_ts_forecast тут ещё нужно использовать? Вроде пайплайн может и так прогнозировать на нужный горизонт

2021-09-17 15:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
Но здесь используется сама переменная cnn2_output_size, а не self-поле.

2021-09-19 08:51 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
Да, действительно, что-то проглядел

2021-09-19 09:38 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        y = torch.from_numpy(input_data_new.target.copy()).float()
Идея как раз была вынести это в отдельную функцию в прошлом ревью

2021-09-19 09:44 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        y = torch.from_numpy(input_data_new.target.copy()).float()
Проясни пожалуйста, я не понял, что ты имеешь в виду

2021-09-19 09:46 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    predicted = out_of_sample_ts_forecast(pipeline=pipeline,
Проверка, не свалится ли он с ошибкой при таком варианте прогнозирования

2021-09-19 09:55 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    predicted = out_of_sample_ts_forecast(pipeline=pipeline,
Хорошо, но для этого (для тестирования out_of_sample_ts_forecast) есть специальные unit тесты в других местах, например [test_pipeline_ts_wrappers.py](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/pipelines/test_pipeline_ts_wrappers.py)
Тут это не требуется проверять, кмк
Тем более, если тест вдруг завалится при таком подходе тяжело будет сразу понять, проблема в out_of_sample_ts_forecast функции, или в том, что просто сам пайплайн не может обучиться / дать прогноз.

2021-09-19 09:58 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        y = torch.from_numpy(input_data_new.target.copy()).float()
Точно, помню, что было предложение разбить fit на функции, так как было много кода в одном месте, но что-то не могу найти.( Это один из методов разбиения разбиения  - преобразование inputData в DataLoader

2021-09-19 10:06 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        y = torch.from_numpy(input_data_new.target.copy()).float()
Ну да, к этому то вопросов как раз нет. То что вынесено в отдельные метод - это гуд)
Я веду разговор про то, что ты тут почему то пытаешься результаты функций _ts_to_table и _prepare_target запихивать в input_data_new, хотя в этом нет никакой необходимости. Можно же просто сделать преобразования и сделать типо такого:
```
_, features_columns, final_target = _prepare_target(idx=new_idx,
                                                        features_columns=lagged_table,
                                                        target=input_data_new.target,
                                                        forecast_length=forecast_length)
x = torch.from_numpy(features_columns).float()
y = torch.from_numpy(final_target).float()
```

вместо такого
```
final_idx, features_columns, final_target = _prepare_target(idx=new_idx,
                                                            features_columns=lagged_table,
                                                            target=input_data_new.target,
                                                            forecast_length=forecast_length)
input_data_new.idx = final_idx
input_data_new.features = features_columns
input_data_new.target = final_target
x = torch.from_numpy(input_data_new.features.copy()).float()
y = torch.from_numpy(input_data_new.target.copy()).float()
```
получается input_data_new можно и не использовать в этой функции выше. Просто принимай на вход в метод InputData, а потом бери только нужные поля из этого датакласса и конвертируй их после преобразований в торч тензоры

2021-09-20 07:56 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.cnn2_output_size = cnn2_output_size
Убрал ненужные поля

2021-09-20 07:56 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    predicted = out_of_sample_ts_forecast(pipeline=pipeline,
Переделал под predict

2021-09-20 07:56 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +        "non_lagged"
Заменил во всем проекте

2021-09-20 07:57 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    predicted = out_of_sample_ts_forecast(pipeline=pipeline,
Уменьшил кол-во эпох

2021-09-20 07:57 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                        final_output = output
Разбил на функции

2021-09-20 07:57 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        forecast_length = input_data.task.task_params.forecast_length
Добавил описание docstring

2021-09-20 07:58 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.criterion = nn.MSELoss()
Сделал словарь для оптимизатора и лосса

2021-09-20 07:58 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        y = torch.from_numpy(input_data_new.target.copy()).float()
Исправил без копирования

2021-09-20 07:58 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        input_data_new = copy(input_data)
Добавил docstring

2021-09-20 07:59 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        for epoch in range(self.epochs):
Объяснил идею teacher forcing'а

2021-09-20 07:59 UTC, valer1435 commented on examples/time_series/ts_clstm_forecasting.py
> +                               cv_folds=None) -> None:
Убрал композирование

2021-09-20 08:00 UTC, valer1435 commented on examples/time_series/ts_clstm_forecasting.py
> +                              is_visualise: bool) -> None:
Убрал дублирование

2021-09-20 08:00 UTC, valer1435 commented on examples/time_series/ts_clstm_forecasting.py
> +    # print(f'Prediction from pipeline loaded from dict {predicted_output_from_dict[:4]}')
Убрал ненужные комментарии

2021-09-20 08:00 UTC, valer1435 commented on examples/time_series/ts_clstm_forecasting.py
> +    #                                         validation_blocks=2)
Убрал ненужные комментарии

2021-09-21 18:30 UTC, Dreamlone requested changes

2021-09-21 18:30 UTC, Dreamlone commented on README.rst
> +* `Gap-filling in time series and out-of-sample forecasting <https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/latest/5_non_lagged_cases.ipynb>`__
Это всё таки надо вернуть как было)

2021-09-21 18:30 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>                                                            time_series=features,
Поправь плиз отступы тут и ниже, чтобы было 
```
ts_to_table(idx=old_idx,
            time_series=features ...
```

2021-09-21 18:30 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            'SGD': torch.optim.SGD(self.model.parameters(), lr=self.learning_rate)
Сделай плиз все с маленьких букв, чтобы было: 'adam', 'sgd', 'mae', 'mse'

2021-09-21 18:30 UTC, Dreamlone commented on fedot/core/pipelines/ts_wrappers.py
>                                       time_series=indices_range,
Тут тоже отступы

2021-09-21 18:30 UTC, Dreamlone commented on test/unit/test_log.log
> +2021-09-21 20:52:55,068 - test_log - INFO - Pipeline composition started
Этот файл лишним затесался в коммит. Удоли

2021-09-21 18:49 UTC, Dreamlone commented on examples/time_series/ts_clstm_forecasting.py
> +    GPComposerBuilder, GPComposerRequirements
Неиспользуемые импорты нужно убрать 
Плюс параметр cv_folds не используется в примере теперь

2021-09-21 18:50 UTC, nicl-nno commented on test/unit/tasks/test_forecasting.py
> +        'hidden_size': 100.66211398383396,
Вроде

"hidden_size – The number of features in the hidden state"

Есть смысл задать не-целое значение?

2021-09-21 18:54 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +        'hidden_size': 100.66211398383396,
Тут моё предложение было, чтобы hyperopt тюнеру было проще искать оптимальное значение гиперпараметра. Также сделал для window_size у lagged в своё время. На уровне имплементации всё равно этот гиперпараметр приводится к int

2021-09-21 18:54 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +        'hidden_size': 100.66211398383396,
Это параметры, которая дал тюнинг модели. Нецелое значение-потому что параметр выбирается из равномерного распределения. На входе в модель все равно обрезается int'ом. Но в примере, действительно, стоит убрать нецелую часть

2021-09-22 07:08 UTC, valer1435 commented on fedot/core/pipelines/ts_wrappers.py
>                                       time_series=indices_range,
убрал отступы

2021-09-22 07:39 UTC, valer1435 commented on README.rst
> +* `Gap-filling in time series and out-of-sample forecasting <https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/latest/5_non_lagged_cases.ipynb>`__
Вернул как было

2021-09-22 07:39 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +        'hidden_size': 100.66211398383396,
Убрал нецелые значения

2021-09-22 07:40 UTC, valer1435 commented on examples/time_series/ts_clstm_forecasting.py
> +    GPComposerBuilder, GPComposerRequirements
Убрал ненужные импорты и параметры

2021-09-22 07:40 UTC, valer1435 commented on test/unit/test_log.log
> +2021-09-21 20:52:55,068 - test_log - INFO - Pipeline composition started
Убрал файл из коммита

2021-09-22 07:40 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            'SGD': torch.optim.SGD(self.model.parameters(), lr=self.learning_rate)
Сделал маленькие буквы

2021-09-22 07:41 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>                                                            time_series=features,
Поправил отступы

2021-09-22 08:29 UTC, Dreamlone approved these changes

2021-09-22 08:29 UTC, Dreamlone commented on examples/time_series/ts_clstm_forecasting.py
> +    of folds to use
cv_folds тут уже нет

2021-09-22 08:31 UTC, nicl-nno approved these changes

2021-09-22 10:33 UTC, merged

2021-09-23 22:56 UTC, nicl-nno commented on test/unit/test_log.log
> +2021-09-21 20:52:55,068 - test_log - INFO - Pipeline composition started
Кажется в итоге не убрал:

https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/test_log.log

2021-09-24 06:28 UTC, valer1435 commented on test/unit/test_log.log
> +2021-09-21 20:52:55,068 - test_log - INFO - Pipeline composition started
Я затупил, подумал убрать изменения в этом файле, а не удалить полностью. Пофиксить через pr?

2021-09-24 07:03 UTC, nicl-nno commented on test/unit/test_log.log
> +2021-09-21 20:52:55,068 - test_log - INFO - Pipeline composition started
Не надо, уберём в следующем.