Pipeline typing check in GPComposerBuilder
nccr-itmo/FEDOT pull request #423
Opened 2021-09-13 15:01 UTC by aPovidlo

Corrections after processing issue #342. Added a typing check in GPComposerBuilder.with_initial_pipeline()

2021-09-13 15:04 UTC, Dreamlone approved these changes

2021-09-13 15:08 UTC, nicl-nno requested changes

2021-09-13 15:08 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Я думал ты хотел это в API добавить. На уровне композера в целом можно ожидать, что пользователь понимает что делает и передает правильные типы.

Но, в любом случае, выглядит излишне громозко - дублируется информация из type hint-ов. Если надо, можно использовать вот такую штуку: https://pydantic-docs.helpmanual.io/usage/validation_decorator/


Алсо, а это проверка не будет падать, если в неё передать None (вроде аннотация это разрешает)?

2021-09-13 15:13 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
> На уровне композера в целом можно ожидать, что пользователь понимает что делает и передает правильные типы

Ну не сказал бы. Вполне себе рабочая схема не обернуть PrimaryNode в Pipeline, а подать его так как есть

2021-09-13 15:15 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Может тогда для большей дружелюбности разрешить такое поведение и оборачивать такой узел в Pipeline вместо генерации ошибки?

2021-09-13 15:19 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Я за вывод ошибки на самом деле, а то так можно всякого в пайплайн назаворачивать) 
Поговорил с Андреем, - всё таки решили вынести в api эту проверку

2021-09-13 15:21 UTC, Dreamlone commented
А у нас как-то reduce_mutation функция может примениться к пайплайну из одного узла? Или до туда в принципе такие однопалубные пайплайны не доходят?

2021-09-13 15:23 UTC, aPovidlo commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Переместил проверку в api

2021-09-13 15:31 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Ок.

https://github.com/nccr-itmo/FEDOT/blob/fb86c277947d42a062e19617d09bef9b77219910/fedot/api/api_utils/composer.py#L116

Вот это условие ещё стоит упросить.

2021-09-13 15:33 UTC, nicl-nno commented
> А у нас как-то [reduce_mutation](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/optimisers/gp_comp/operators/mutation.py#L346) функция может примениться к пайплайну из одного узла? Или до туда в принципе такие однопалубные пайплайны не доходят?

Вроде явной проверки нет, так что может.

В идеале можно сделать тест чтобы проверить, что все мутации и кроссоверы работает с 1node.

2021-09-14 11:15 UTC, aPovidlo commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
@nicl-nno добавление тестов для проверки мутации и кроссовера сделать в данной ветке? Если да, то подскажи, пожалуйста, необходимый файл.

2021-09-14 11:20 UTC, aPovidlo commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Упростил условие.

2021-09-14 11:26 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            raise ValueError(f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
>добавление тестов для проверки мутации и кроссовера сделать в данной ветке? 
Можно и в этой, вроде тест не должен быть громоздким.

>Если да, то подскажи, пожалуйста, необходимый файл.
https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/optimizer/test_gp_operators.py

2021-09-15 13:15 UTC, Dreamlone requested changes

2021-09-15 13:15 UTC, Dreamlone commented on fedot/api/api_utils/composer.py
> +                    f'Incorrect type of initial_pipeline: Pipeline needed, but has {type(initial_pipeline)}')
Как вариант, можно разбить вот так, чтобы не была слишком длинной строчка:
```
prefix = 'Incorrect type of initial_pipeline'
raise ValueError(f'{prefix}: Pipeline needed, but has {type(initial_pipeline)}')
```

2021-09-15 13:15 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +def reduce_mutation(graph: OptGraph, requirements, **kwargs) -> OptGraph:
Коля @nicl-nno, проверь пожалуйста, правильно хинты расставлены

2021-09-15 13:15 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
А можно это дело в цикле вызывать?

2021-09-15 13:15 UTC, Dreamlone commented on test/unit/pipelines/test_node_cache.py
> +    # Only one single node KNN
А почему именно в test_node_cache.py? Полагаю, лучше перенести функцию туда же, где она и используется, то есть в test_gp_operators.py

2021-09-15 13:18 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
Можно. Я это брал из тестов выше, могу и их переделать тогда.

2021-09-15 13:19 UTC, aPovidlo commented on test/unit/pipelines/test_node_cache.py
> +    # Only one single node KNN
В прочих тестах в этом файле были вызовы других функций с генерацией из test_node_cache.py. Поэтому подумал, что логично туда добавить.

2021-09-15 13:22 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
Я смотрю, там много в каких тестах есть подобное дублирование. 
Давай пока оставим задачу рефакторинга старых тестов. Пока лучше исправить только вот этот

2021-09-15 13:26 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
Вроде @MAGLeb начинал рефакторить, думаю это туда же пойдет (как и коммент ниже)

2021-09-15 13:27 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +def reduce_mutation(graph: OptGraph, requirements, **kwargs) -> OptGraph:
Вроде.

2021-09-15 13:30 UTC, Dreamlone commented on test/unit/pipelines/test_node_cache.py
> +    # Only one single node KNN
Но ведь pipeline_sixth не используется в этом же файле

2021-09-15 13:32 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
Как бы да (я об этом и подумал). Но то что Глеб будет рефакторить тесты не значит, что сейчас можно их писать как попало) 
В общем мой тезис такой: новый тест стоит поправить, старые - не трогаем

2021-09-15 13:34 UTC, Dreamlone commented on test/unit/pipelines/test_node_cache.py
> +    # Only one single node KNN
И название функции наверное стоит поменять на что-то более говорящее

2021-09-15 14:04 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +    assert new_graphs[1].graph == graph_example_second
@nicl-nno @Dreamlone мне исправлять этот комментарий или оставить для рефакторинга?

2021-09-15 14:55 UTC, Dreamlone requested changes

2021-09-15 14:55 UTC, Dreamlone commented on fedot/api/api_utils/composer.py
> +                    f'{prefix}: Pipeline needed, but has {type(initial_pipeline)}')
Идея с префиксом была для того, чтобы не было вот такого отступа после "("

2021-09-15 14:55 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +        {'crossover_prob': 0, 'crossover_types': [CrossoverTypesEnum.subtree]}
А почему нолик у вероятности кроссовера стоит? 
Это же вроде значит, что кроссовер не будет применяться

2021-09-15 14:56 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +    for temp in params:
логичнее param или param_set

2021-09-15 14:59 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +        {'crossover_prob': 0, 'crossover_types': [CrossoverTypesEnum.subtree]}
Inspired by `test_crossover()`, в котором была такая проверка)

2021-09-15 15:01 UTC, aPovidlo commented on fedot/api/api_utils/composer.py
> +                    f'{prefix}: Pipeline needed, but has {type(initial_pipeline)}')
Понял, учел

2021-09-15 15:01 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +    for temp in params:
Исправил

2021-09-15 15:02 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +        {'crossover_prob': 0, 'crossover_types': [CrossoverTypesEnum.subtree]}
Неплохо)
Ну тогда перед тем, как использовать такую комбинацию, надо выяснить, не озанчает ли crossover_prob = 0 то, что кроссовер применяться не будет

2021-09-15 15:03 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +        {'crossover_prob': 0, 'crossover_types': [CrossoverTypesEnum.subtree]}
А разве это не полезно тоже проверять?

2021-09-15 15:21 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +        {'crossover_prob': 0, 'crossover_types': [CrossoverTypesEnum.subtree]}
![image](https://user-images.githubusercontent.com/5711814/133461864-1f31d481-7cce-4e29-b39d-4e70b2bf99f9.png)

В test_crossover как раз проверяется, что кроссовер НЕ меняет графы, если стоит none или вероянтость 0. Можно скорректировать название того теста.

2021-09-15 16:28 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +def test_mutation_with_single_node():
Если проверяется только одна мутация - то стоит это вынести в название теста.
Но кажется стоит проверить ещё и single_drop_mutation.

Или же проверять все мутации, но с разными условиями.

2021-09-15 16:30 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +    ]
Вроде можно итерироваться прямо по значениями Enum-а, не дублируя их.

2021-09-15 16:43 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +def test_mutation_with_single_node():
@Dreamlone предложил проверять только `reduce_mutation()`. В принципе можно же вызвать функцию `mutation()` и проверить все? Или они не все подойдут для работы с одним узлом?

2021-09-15 16:44 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +def test_mutation_with_single_node():
Подойти должно все, но не везде результат будет равен исходному.

2021-09-15 16:50 UTC, aPovidlo commented on test/unit/optimizer/test_gp_operators.py
> +    ]
У меня возникала такая ошибка:

![image](https://user-images.githubusercontent.com/22475542/133475613-3c4486bc-29dd-481e-9120-dea08c750ae3.png)

И сам класс такой:
```Python
class CrossoverTypesEnum(Enum):
    subtree = 'subtree'
    one_point = "one_point"
    none = 'none'
```

2021-09-16 10:35 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +    ]
Вот такой сниппет работает. 

`
from fedot.core.optimisers.gp_comp.operators.crossover import CrossoverTypesEnum

for val in CrossoverTypesEnum:
    print(val)
`

Возможно, надо в первый аргумент передавать [crossover_type]

2021-09-16 11:15 UTC, Dreamlone commented on test/unit/optimizer/test_gp_operators.py
> +def test_mutation_with_single_node():
Мне кажется особого смысла проверять такое специфичное условие как одноузловой пайплайн для всех мутаций нет. Предлагаю ограничиться только reduce_mutation и single_drop_mutation в рамках одного теста например

2021-09-16 12:38 UTC, nicl-nno commented on test/unit/optimizer/test_gp_operators.py
> +def test_mutation_with_single_node():
Ну ошибки могут быть в любой. Но в целом не принципиально.

2021-09-16 13:56 UTC, Dreamlone approved these changes
Не забудь сделать ребейз

2021-09-16 15:22 UTC, nicl-nno approved these changes

2021-09-16 17:46 UTC, merged