Remote evaluation feature implemente for pipelines in composer
nccr-itmo/FEDOT pull request #433
Opened 2021-09-24 15:13 UTC by nicl-nno

What's new:

'Remote' module:
1) run_pipeline.py script is added. It receives the pipeline and data description as input and returns the fitted pipeline. This script is aimed to be called at the remote node
2) ComputationalSetup class added to implement the remote fit of pipelines
3) Batch evaluation of the pipelines added to the composer if ComputationalSetup is initialized.
4) Logic for REST requests to a remote server with computational resources.

Other:
1) Indices corrected for Data. Now, the indices are preserved during transformations and not creating from scratch.
2) New notebook added for industrial case
3) Minor fixes in forecasting

Known disadvantages:

Now, the ComputationalSetup is DataMall-specific. The refactoring to support different strategies is expected.

2021-09-24 15:13 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`examples/remote_execution/ts_composer_with_integration.py`](https://github.com/nccr-itmo/FEDOT/blob/26f22a852e9a8c98e0b5e4c67deae2f9e2a7bfd2/examples/remote_execution/ts_composer_with_integration.py):

> [Line 12:1](https://github.com/nccr-itmo/FEDOT/blob/26f22a852e9a8c98e0b5e4c67deae2f9e2a7bfd2/examples/remote_execution/ts_composer_with_integration.py#L12): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 13:1](https://github.com/nccr-itmo/FEDOT/blob/26f22a852e9a8c98e0b5e4c67deae2f9e2a7bfd2/examples/remote_execution/ts_composer_with_integration.py#L13): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file
> [Line 17:1](https://github.com/nccr-itmo/FEDOT/blob/26f22a852e9a8c98e0b5e4c67deae2f9e2a7bfd2/examples/remote_execution/ts_composer_with_integration.py#L17): [E402](https://duckduckgo.com/?q=pep8%20E402) module level import not at top of file

2021-09-26 20:55 UTC, Dreamlone requested changes

2021-09-26 20:55 UTC, Dreamlone commented on cases/industrial/processing.py
> +            idx = list(dataframe['datetime'])
Подскажи плиз, что значит, если длина прогноза меньше либо равна нулю? Насколько я понимаю, в таком случае, нет смысла давать прогноз, раз горизонт прогнозирования <= 0, то и прогнозировать нечего

2021-09-26 20:55 UTC, Dreamlone commented on fedot/core/data/data.py
> +        new_features = None
Методу неплохо было бы добавить описание

Плюс место, где в одной строчке цикл, if-конструкция, обращение к ".index" и конвертации в строки выглядит неочевидно. Возможно, станет понятней, когда добавится описание

2021-09-26 20:55 UTC, Dreamlone commented on fedot/core/data/data_split.py
> +    idx_test = data.idx[-forecast_length:]
Это точно равнозначная замена? 

Например, всего во временно ряду 7 элементов, прогноз даётся на 3 элемента вперёд
Было что-то вроде (см. удаленные строки):
Индексы для тренировки - 0, 1, 2, 3, 4, 5, 6
Индексы для предсказания - 7, 8, 9

Стало (см. новые строки): 
Индексы для тренировки - 0, 1, 2, 3
Индексы для предсказания - 4, 5, 6

2021-09-26 20:55 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    ts_target = target[[list(all_idx).index(i) for i in idx]]
Разве эта конструкция делает не то же самое, что было? 

Например при запуске такого простенького эксперимента результат будет такой же:
```
all_idx = [0, 1, 2, 3, 4, 5]
idx = [2, 3]
target = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

print(list(all_idx).index(0))
print([list(all_idx).index(i) for i in idx])

ts_target = target[[list(all_idx).index(i) for i in idx]]
print(ts_target)

ts_target = target[idx]
print(ts_target)

```

2021-09-26 20:55 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        non_empty_group = [g for g in group if g.fitness is not None]
Вроде для этого уже есть подготовленная функция - correct_if_population_has_nans в fedot\core\optimisers\gp_comp\gp_optimiser.py (она ведь подходит для этого?). 
Предлагаю здесь, и в других местах использовать именно её, - так в будущем будет проще убирать заглушки.

2021-11-10 13:39 UTC, nicl-nno commented on fedot/remote/run_pipeline.py
> +                return f'data_source_ts/{data_part_key}'
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/433/files#diff-339e08cb17987c53518828193339812fde35ba18634ce1269acb67982a2fe465R22-R25) наружу

2021-11-10 13:39 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        print('Remote fit used')
Создал лог в этой функции.

2021-11-11 12:40 UTC, Dreamlone requested changes

2021-11-11 12:40 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    calculated_fitness = objective_function(converted_object)
Сначала по поводу хинтов `Union[OptGraph, Any]`. Какой ещё тут граф предполагается, можно будет какой-нибудь просто Graph передать? - Мб тогда стоит перечислить эти классы, вместо Any

Просто если перейдём ниже, то до objective_function дойдёт Graph никак не преобразованный, это не вызовет ошибку? 
Плюс не до конца понимаю, converted_object - это в итоге всегда должен быть Pipeline, или не обязательно?

2021-11-12 19:41 UTC, nicl-nno commented on fedot/remote/run_pipeline.py
> +                     parse_dates=['datetime'])
Cделал вот [так](https://github.com/nccr-itmo/FEDOT/pull/433/files#diff-339e08cb17987c53518828193339812fde35ba18634ce1269acb67982a2fe465R22-R33) чтобы минимизировать дублирование.

2021-11-12 19:43 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    calculated_fitness = objective_function(converted_object)
Смысл в том, что если пайплайны обучены заранее, то вместо OptGraph будет Pipeline. Но оптимизатор не знает реальный тип объектов с которыми он работает - поэтому для него это Any.

>objective_function дойдёт Graph никак не преобразованный
Вроде до objective_function  как раз доходит преобразованный результат - или заранее, или через restore.

2021-11-14 11:03 UTC, Dreamlone requested changes
Пример "ts_fitted_values.py" в examples падает теперь с ошибкой

2021-11-14 11:32 UTC, Dreamlone commented
Также запустил тесты `sensitivity` проходят нормально. Но среди интеграционных `integration` вот такой список упавших:
* test_multiclass_example
* test_api_example
* test_metocean_forecasting_problem
* test_multi_modal_case

2021-11-15 15:11 UTC, nicl-nno commented on cases/industrial/processing.py
> -
Пока удалил этот ноутбук.

2021-11-15 15:11 UTC, nicl-nno commented
Примеры и кейсы починил вот [так](https://github.com/nccr-itmo/FEDOT/pull/433/commits/043ab20960d10555162670526f74f4731a01a5c1).

2021-11-15 16:34 UTC, Dreamlone commented on fedot/core/data/multi_modal.py
> +                'Multivariate predict not supported in this function yet.')
Вроде бы не соотносятся условия и выводимая ошибка. Или я что-то не уловил?

2021-11-15 16:50 UTC, nicl-nno commented on fedot/core/data/multi_modal.py
> +                'Multivariate predict not supported in this function yet.')
Если ты запустил MultiModalData.from_csv_time_series в predict-режиме - то получаешь ошибку, что это ещё не реализовано. Или ты про другое?

2021-11-15 17:10 UTC, Dreamlone commented on fedot/core/data/multi_modal.py
> +                'Multivariate predict not supported in this function yet.')
Да, пардон, всё хорошо. Я перепутал с методом from_csv_time_series в обычном InputData

2021-11-15 19:43 UTC, nicl-nno commented
>С отрисовкой в ts_fitted_values.py что-то не то

Пока починил это так. Проблема в том, что индексы до и после предсказания становятся разными (см https://github.com/nccr-itmo/FEDOT/pull/433/commits/7f4c9f37b95e408532db866398b42197f0c9c2b9).

Не знаю, можно ли это как-то изящно обработать.

2021-11-16 08:57 UTC, Dreamlone commented
Мне уже неловко писать по поводу такого относительно неважного блока, так как выделение обученных значений модели по временному ряду не является важнейшей частью FEDOT'а, но с `ts_fitted_values.py` точно что-то не так. 
Если сравнить как выглядит output скрипта в мастере и в твоей ветке, то будет следующая картина (обрати внимание на пики желтой линии)
![ts_fitted](https://user-images.githubusercontent.com/52418437/141953198-ae1fdda6-a101-43e7-bbee-f0f8623551fa.png)

Теоретически, это может являться симптомом того, что обработка индексов не совсем корректно сейчас происходит. Вопрос в том, является ли это проблема частной только для `fitted_values`, или что-то не так с более критически важными вещами

2021-11-16 12:14 UTC, nicl-nno commented
>сейчас присмотрелся, там и другие кривые отличаются друг от друга, просто не так явно

Тут наверное тебе будет проще посмотреть, сходу сложно понять, насколько сами индексы важны для предсказания fitted_values.

2021-11-17 10:34 UTC, Dreamlone approved these changes

2021-11-23 13:48 UTC, merged