Fix decompose operation processing
nccr-itmo/FEDOT pull request #434
Opened 2021-09-24 17:40 UTC by Dreamlone

The way to determine the ancestor of data ("Data parent") and the ancestor of predictions ("Model parent") in the decompose operation has been fixed

Now, if the number of visited nodes in the data is equal, preference (for being "Data parent") is given to the lagged operation for example

2021-09-24 17:46 UTC, nicl-nno requested changes

2021-09-24 17:46 UTC, nicl-nno commented on fedot/core/data/supplementary_data.py
> +        if 'lagged' in self.last_visited_operations:
Может это лучше по тегу проверять?

2021-09-24 17:46 UTC, nicl-nno commented on fedot/core/data/supplementary_data.py
> +    last_visited_operations: Optional[list] = None
А не лучше назвать это previous_operations? last подразумевает ограничение по числу, а его тут вроде нет.

2021-09-27 10:15 UTC, Dreamlone commented on fedot/core/data/supplementary_data.py
> +    last_visited_operations: Optional[list] = None
[Заменил название](https://github.com/nccr-itmo/FEDOT/pull/434/commits/c21e8b4efb3b6bca7e4347551b5788df21ee6c7a#diff-6ccd62dc0288800c6867ef58fb3a0569cfb9817d3fd568d5b1928d172740e4c0R22-R23)

2021-09-27 10:16 UTC, Dreamlone commented on fedot/core/data/supplementary_data.py
> +        if 'lagged' in self.last_visited_operations:
Лучше даже не по тегу, а по принципу "дата операция" или "модель" 
Сделал вот [так](https://github.com/nccr-itmo/FEDOT/pull/434/commits/c21e8b4efb3b6bca7e4347551b5788df21ee6c7a#diff-6ccd62dc0288800c6867ef58fb3a0569cfb9817d3fd568d5b1928d172740e4c0R103-R121)

2021-09-27 10:26 UTC, nicl-nno commented
Всё ок, осталось только тесты починить)

2021-09-27 10:44 UTC, nicl-nno approved these changes

2021-09-27 11:48 UTC, merged