Individuals evaluation modified
nccr-itmo/FEDOT pull request #443
Opened 2021-09-28 16:17 UTC by nicl-nno

Now only individuals with correct fitness are preserved in population.

The only case for failure is the case when all individuals in population has None in fitnesss.

2021-09-28 22:13 UTC, Dreamlone requested changes

2021-09-28 22:13 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +        if nodes_not_cycling and (target_node.nodes_from is None or source_node not in target_node.nodes_from):
Проблема с None в фитнесах была из-за вот этой мутации? (из любопытства)

2021-09-29 15:11 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +        if nodes_not_cycling and (target_node.nodes_from is None or source_node not in target_node.nodes_from):
Не только. Мутация порождала вот такие некорректные пайплайны

![image](https://user-images.githubusercontent.com/5711814/135297354-7d3f72bc-f929-4a47-aa52-1b014e1c40ff.png)

но есть и другие случае, когда фитнес не может быть вычислен.

Пример - формально валидный, но нерабочий пайплайн:

![image](https://user-images.githubusercontent.com/5711814/135297508-4af64649-d173-4c6a-89da-b8c063fa1a97.png)

2021-09-29 15:17 UTC, nicl-nno commented on examples/gapfill.py
> +output = gapfiller.forward_inverse_filling(array_with_gaps)
Удалил

2021-09-29 15:24 UTC, Dreamlone approved these changes

2021-09-30 07:26 UTC, merged