+ classes/interfaces for 'OptHistory' serialization (FEDOT.Web)
nccr-itmo/FEDOT pull request #478
Opened 2021-10-22 10:43 UTC by IIaKyJIuH

Also code fixes (marginal cases) and imports sorting

2021-11-11 14:10 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        self.save_folder: str = save_folder if save_folder \
Кольцевые зависимости исправлены полем 'TYPE_CHECKING' и строковыми литералами типов

2021-11-11 14:19 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        self.individuals: List[List[Individual_m.Individual]] = []
Теперь в каждом индивиде FEDOT-а в поле 'graph' хранится 'OptGraph' вместо 'PipelineTemplate'

На [клиентской стороне](https://github.com/nccr-itmo/FEDOT.Web/pull/82/files#diff-ef902eb810a86acff83843efd3577d9e8d18df2963a342a13649d913762fd2ccR68) идёт преобразование в 'PipelineTemplate', и в таком виде история сериализуется и десериализуется на клиенте.

2021-11-11 14:21 UTC, IIaKyJIuH commented on fedot/core/repository/operation_types_repository.py
> +class OperationTypesRepository(BasicSerializer):
Сделал замену 'PipelineTemplate' на 'OptGraph' в индивидах FEDOT-а

2021-11-11 22:43 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        self.metrics: List[Callable[..., float]] = metrics
Лучше тип указать для аргумента конструктора (metrics), а не для поля класса.

2021-11-11 22:52 UTC, nicl-nno requested changes

2021-11-11 22:52 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                cur_ind_graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Вроде в этот момент это уже скорее ind_pipeline_template

2021-11-11 22:52 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        ]
В перспективе надо будет создать что-то вроде ComposerHistory, который унаследовать от OptHistory и перенести туда pipeline-специфичную логику. Но пока пусть будет так.

2021-11-11 22:52 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +            self.depth = 0  # TODO: should be None or 0?
Пусть будет 0.

2021-11-11 22:52 UTC, nicl-nno commented on fedot/core/repository/operation_types_repository.py
> +class OperationTypesRepository(BasicSerializer):
А после этого изменения для чего-то нужно наследование от BasicSerializer для OperationTypesRepository/OperationMetaInfo/PipelineTemplate/etc?

2021-11-12 07:50 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        self.metrics: List[Callable[..., float]] = metrics
Правда хорошая идея

А типизацию для полей, которые не в аргументах конструктора, оставить?

2021-11-12 09:44 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +                cur_ind_graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Как проверить точно? Потому что никакие тесты нигде не падают

2021-11-12 09:51 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        ]
Кстати, если на клиентской части вызвать в [этом месте](https://github.com/nccr-itmo/FEDOT.Web/blob/7335346e6585eebb3b48f9a209f79a06465dc1ee/init/init_history.py#L91) данное свойство напрямую (как и было раньше), то всё поломается, потому что на клиенте в `individuals[i][j].graph` лежит уже не `OptGraph`, а `PipelineTemplate`

Это пофиксить, или оставить так, как я эту проблему обошёл? Смущает просто то, что если кто-то захочет вызвать на клиенте свойство `historical_pipelines`, будет поднята ошибка

2021-11-12 09:51 UTC, IIaKyJIuH commented on fedot/core/pipelines/template.py
> +            self.depth = 0  # TODO: should be None or 0?
Ок, теперь там 0

2021-11-12 10:19 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                cur_ind_graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Я здесь про нейминг cur_ind_graph .

2021-11-12 10:24 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        ]
Можно в качестве воркэраунда в def historical_pipelines добавить проверку на тип ind.graph - и если там уже PipelineTemplate, то не преобразовывать.

2021-11-12 10:24 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        self.metrics: List[Callable[..., float]] = metrics
Пусть будет, раз уже добавил.

2021-11-12 10:43 UTC, IIaKyJIuH commented
Сериализаторы на OperationTypesRepository/OperationMetaInfo больше, действительно, не нужны, они убраны

А вообще сейчас на клиенте индивиды из истории, возвращённой `FEDOT`-ом, сразу [конвертируется](https://github.com/nccr-itmo/FEDOT.Web/blob/7335346e6585eebb3b48f9a209f79a06465dc1ee/app/api/composer/service.py#L100) в `PipelineTemplate`, из-за чего с этим же классом и сериализуется, поэтому `BasicSerializer` для `PipelineTemplate` всё ещё нужен.

2021-11-12 10:47 UTC, nicl-nno commented
>поэтому BasicSerializer для PipelineTemplate всё ещё нужен

Ок, пусть остается тогда.

2021-11-12 10:47 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +                cur_ind_graph = adapter.restore_as_template(ind.graph, ind.computation_time)
Понял, изменил, теперь семантичное название

2021-11-12 10:50 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        ]
Боялся, что так код будет выглядеть костыльнее, и вообще думал, что можно элегантнее это решить, но не придумал, как

2021-11-16 07:58 UTC, IIaKyJIuH commented on fedot/shared/interfaces/serializable.py
> +
Сделал тесты

2021-11-16 08:00 UTC, IIaKyJIuH commented on fedot/core/repository/operation_types_repository.py
> +class OperationTypesRepository(BasicSerializer):
Уже нет и я это пофиксил

2021-11-17 14:40 UTC, nicl-nno commented on fedot/core/operations/evaluation/evaluation_interfaces.py
>  from xgboost import XGBClassifier, XGBRegressor
Если уж менять эти строки - то стоит к единообразному виду привести (как в строках 13-18, например - выглядит более компактно)

![image](https://user-images.githubusercontent.com/5711814/142221448-4738acfa-6971-40bc-8931-48a24587bc12.png)

2021-11-17 14:45 UTC, nicl-nno commented on test/unit/serialization/test_object_path_dumping.py
> +from .test_input import *
Лучше всё таки конкретные функции/классы импортировать.

2021-11-17 14:46 UTC, nicl-nno commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
А если использовать os.path.join - не получится избавиться от DELIMITER?

2021-11-18 06:41 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/evaluation_interfaces.py
>  from xgboost import XGBClassifier, XGBRegressor
Унифицировал формат

2021-11-18 06:45 UTC, IIaKyJIuH commented on test/unit/serialization/test_object_path_dumping.py
> +from .test_input import *
Понимаю, так будет понятнее, откуда они возникают => читаемость

Исправил

2021-11-18 07:16 UTC, IIaKyJIuH commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
`DELIMITER` нужен для того, чтобы отделять имя модуля от полного имени объекта

Имя модуля нужно выделять для того, чтобы корректно работала функция [`importlib.import_module`](https://github.com/nccr-itmo/FEDOT/pull/478/files/8677cb02501511011405799f837e051c0acd95b5#diff-7559994aa0eed2eda58abf463a7dedcfa162e9369ff932c8ed32eef9bc6e0fbcR46)

Суть в том, что нужный тип объекта импортируется не сразу, а постепенно: сначала от самого модуля, потом от "модуля + подобъект внутри него" и так далее.

Допустим у нас такой путь: "my.simple.module/A.Bar.foo"
Сначала мы загрузим "my.simple.module.A", затем "my.simple.module.A.Bar", и только потом "my.simple.module.A.Bar.foo"

2021-11-18 07:30 UTC, nicl-nno commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
Ок, я подумал что input_data это путь к данным.

2021-11-18 07:32 UTC, IIaKyJIuH commented on test/unit/serialization/test_decoder.py
> +DECODER_CASES = [
Вообще они очень условно моки, я не делал замен оригинальных классов в тестах, это было просто для наглядности всё в одном файле [`test_input.py`](https://github.com/nccr-itmo/FEDOT/pull/478/files/8677cb02501511011405799f837e051c0acd95b5#diff-ef9a6dcccc02772d2aaba07db8c8b6511e0d0a736a5c0e32a8366ba0433244a2), просто кроме них есть ещё классы и функции, которые не моки, а просто образцы, как может выглядеть сериализуемый класс.

В любом случае, не страшно поместить классы с соответствующим префиксом в `.../mocks/...`

2021-11-18 07:43 UTC, IIaKyJIuH commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
Может лучше тогда переименовать `input_data`, чтобы было прозрачнее, что там лежит?

2021-11-18 08:03 UTC, nicl-nno commented
Давай так.

чт, 18 нояб. 2021 г., 10:44 IIaKyJIuH ***@***.***>:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In test/unit/serialization/test_get_class.py
> <https://github.com/nccr-itmo/FEDOT/pull/478#discussion_r751975439>:
>
> > @@ -0,0 +1,48 @@
>
> +from uuid import UUID
>
> +
>
> +import pytest
>
> +from fedot.serializers.json_helpers import DELIMITER, _get_class
>
> +
>
> +from .dataclasses.serialization_dataclasses import GetClassCase
>
> +from .test_input import *
>
> +
>
> +GET_CLASS_CASES = [
>
> +    GetClassCase(
>
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
>
>
> Может лучше тогда переименовать input_data, чтобы было прозрачнее, что
> там лежит?
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/nccr-itmo/FEDOT/pull/478#discussion_r751975439>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLSPRV2IYROIWPKBYFQN2TUMSVERANCNFSM5GQH6ITA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-11-18 09:43 UTC, nicl-nno commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
Давай так

2021-11-18 09:46 UTC, nicl-nno commented on test/unit/serialization/shared_data.py
> +    def foo(self):
Может для единообразния test_func и TestClass назвать?

А ниже - TestSerializableClass или как-то так.

2021-11-18 09:47 UTC, nicl-nno commented on test/unit/serialization/test_decoder.py
> +DECODER_CASES = [
Ок, не принципиально, смотри сам.

2021-11-18 10:57 UTC, IIaKyJIuH commented on test/unit/serialization/shared_data.py
> +    def foo(self):
Хорошая идея, сделал именно так

2021-11-18 12:16 UTC, IIaKyJIuH commented on test/unit/serialization/test_get_class.py
> +        input_data=f'{UUID.__module__}{DELIMITER}{UUID.__qualname__}',
Сделал

2021-11-18 12:25 UTC, nicl-nno approved these changes

2021-11-18 12:26 UTC, nicl-nno commented
Вроде всё норм.
@J3FALL ещё посмотрит и можно мержить.

2021-11-18 16:02 UTC, J3FALL commented on fedot/shared/serializers/json_helpers.py
> +    return json_obj
Да, например, я бы подумал над тем, какую говорящую функцию/переменную подобрать для проверки: `OBJECT_ENCODING_KEY in json_obj`.
Просто не очень понятно по контексту, что эта штука значит.
А, ну и + можно еще в docstring encoder/decoder добавить эту стратегию сериализации/десериализации.

2021-11-18 16:13 UTC, J3FALL approved these changes

2021-11-18 16:13 UTC, J3FALL commented on fedot/core/serializers/graph_serializer.py
> +                            break
Мб какую-нибудь inner-функцию здесь извлечь?
Чтоб не так громоздко смотрелось, т.к. тут 3 слоя for-вложенности

2021-11-18 16:13 UTC, J3FALL commented on fedot/core/serializers/graph_serializer.py
> +
Писал в одном из комментов про docstring, мб для основных объектов тоже это повторить.
Т.е. коротко описать стратегию сериализации/десериализации конкретных сущностей.

2021-11-18 16:13 UTC, J3FALL commented on test/unit/serialization/shared_data.py
> +    pass
Вот эта функция вроде не нужна?

2021-11-18 16:13 UTC, J3FALL commented on test/unit/serialization/dataclasses/serialization_dataclasses.py
> +
Интересно выглядит, а можешь рассказать идею с TestCas-ами?
Ожидал увидеть просто n разных функций с говорящими названиями под разные кейсы.
Что-то в стиле:
```
test_node_serialized_correctly()
test_pipeline_sriealized_correctly()
```
Ну и в таком духе.

2021-11-19 09:17 UTC, IIaKyJIuH commented on fedot/shared/serializers/json_helpers.py
> +    return json_obj
В общем, семантизировал переменные, чтобы было понятнее, что тут происходит
И добавил docstring-и для функций в `json_helpers.py`

2021-11-19 09:55 UTC, IIaKyJIuH commented on fedot/core/serializers/graph_serializer.py
> +                            break
Использовал itertools.product(...), чтобы компактнее смотрелось

2021-11-19 09:56 UTC, IIaKyJIuH commented on test/unit/serialization/shared_data.py
> +    pass
Нужна, просто в тестах не важно, что она делает, проверяется просто, как она сериализуется/десериализуется

2021-11-19 10:26 UTC, IIaKyJIuH commented on test/unit/serialization/dataclasses/serialization_dataclasses.py
> +
В каждом `serialization/test_*.py` сделал шаблонную функцию проверки, которая зависит от входных датаклассов, названия которых говорят о том, что тестируется.

Входные датаклассы же содержат поля, значения которых как раз с говорящими названиями под разные кейсы. Вообще тестируемые сущности из [`shared_data.py`](https://github.com/nccr-itmo/FEDOT/pull/478/files/3a79967ad2c6a314f1916bc5ea5627bf1a376f99#diff-514e5b8d255ad467286617f7e5570a1892e98c06775146356305793c16a9c73f) и [`serialization_mocks.py`](https://github.com/nccr-itmo/FEDOT/pull/478/files/3a79967ad2c6a314f1916bc5ea5627bf1a376f99#diff-0f5a2d1ae097d09ea258fea30c9cadf0a9586bf6e77a8748190f0c5961da471d) являются 
- либо обыденными функциями/методами/классами
- либо сериализуемыми по функциональности, добавленной в этом PR, чтобы продемонстрировать, как бы это выглядело на произвольном классе
- либо "моками", которые напоминают классы из FEDOT-а и при этом являются сериализуемыми по добавленной в PR функциональности, чтобы показать, какие поля сериализация затронет, а какие нет

2021-11-19 11:47 UTC, IIaKyJIuH commented on fedot/core/serializers/graph_serializer.py
> +
Добавил докстринги для всех добавленных сериализаторов

2021-11-19 12:30 UTC, J3FALL commented on test/unit/serialization/shared_data.py
> +    pass
Я, окей, упустил это

2021-11-19 14:00 UTC, merged