Feature/pipeline explanations
nccr-itmo/FEDOT pull request #482
Opened 2021-11-01 09:10 UTC by MorrisNein

What's new:

1. An inner repo `fedot/explainability` for the corresponding experiments.
2. `Explainer` abstract class, implementing an interface.
3. `SurrogateExplainer `class for building surrogate explanation models. __The only supported surrogate at the moment is the decision tree__.
4. `explain` method and `explanation` attribute in the `Pipeline` class for creating and storing the `Explainer` successors.

2021-11-01 09:10 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/pipelines/pipeline.py`](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/core/pipelines/pipeline.py):

> [Line 347:121](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/core/pipelines/pipeline.py#L347): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)



* In the file [`fedot/explainability/surrogate_explainer.py`](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py):

> [Line 17:75](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L17): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 18:5](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L18): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line
> [Line 19:1](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L19): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 53:1](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L53): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 55:1](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L55): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 69:1](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L69): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 78:87](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L78): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 95:46](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L95): [W291](https://duckduckgo.com/?q=pep8%20W291) trailing whitespace
> [Line 98:1](https://github.com/nccr-itmo/FEDOT/blob/d8a4fd39efc3e66b1e38a103342dc336b002a033/fedot/explainability/surrogate_explainer.py#L98): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2021-11-01 10:06 UTC, nicl-nno requested changes

2021-11-01 10:06 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +            self.explainer = SurrogateExplainer(self, surrogate='dtreg')
А надо давать такой выбор пользователю? Пусть указывает surrogate_dt, а выбор class/regr осуществляется автоматически.

2021-11-01 10:06 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        self.explainer(data, instant_output=instant_output, **kwargs)
А что тут делается? Вроде экземпляр уже создан выше.

2021-11-01 10:06 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        :rtype: Explainer
Типы можно не указывать в docstring-е, т.к. они уже есть в type hint-ах выше.

2021-11-01 10:06 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        from fedot.explainability.surrogate_explainer import SurrogateExplainer
Лучше всё-таки передалать логику, чтобы круговой зависимости не было.
Нпример, вынести создание пайплайна для объяснения в отдельный скрипт или как-то ещё..

2021-11-01 17:58 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +        self.explainer = None
Как раз используется в строчке 185.

Атрибут действительно избыточный, так как метод `pipeline.explain()` возвращает этот самый объект эксплейнера. Сделал исключительно ради удобства и возможности написать pipeline.explainer.output() в удобный момент.

2021-11-01 18:01 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +            self.explainer = SurrogateExplainer(self, surrogate='dtreg')
Согласен, исправлю

2021-11-01 18:06 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +        self.explainer(data, instant_output=instant_output, **kwargs)
Я намеренно отделил инициализацию эксплейнера `__init__` от генерации объяснения `__call__` для возможности переиспользования (при инициализации задали метод и взяли нужную информацию о чёрном ящике, а затем хотим каждым вызовом делать локальные объяснения для разных сэмплов). Думаю, что мне стоило использовать именованную функцию для лучшей читаемости.

2021-11-03 15:56 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        self.explainer(data, instant_output=instant_output, **kwargs)
С именованной функций действительно будет понятнее и более ООП-шно.

2021-11-03 16:00 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +            raise ValueError(f'Explanation method {method} is not supported')
Вот это лучше тоже куда-то explainer вынести. Туда task_type поступает вместе с data.

2021-11-03 16:01 UTC, nicl-nno commented on fedot/core/explainability/utils.py
> +        if metric is None:
1) Пустая строка лишняя 
2) Условия можно объединить

2021-11-04 11:22 UTC, nicl-nno commented
Ну и явно нужны тесты в test и хоть один пример в examples

2021-11-11 11:02 UTC, Dreamlone requested changes

2021-11-11 11:02 UTC, Dreamlone commented on fedot/core/explainability/utils.py
> +    return score
У меня есть вопрос-предложение. Может explainability из core вынести повыше в иерархии в то же самое место, где лежит sensitivity у нас? 

Второе: utils здесь точно нужны? Почему бы не держать эти функции в том же месте, где и сам Explainer? Вроде не сильно много кода получается. - Но допустим мы все таки решаем их держать отдельно, ок. Тогда вспоминая слова Паши @J3FALL, хочется сказать про важность "не-называть" модули по типу "utils". Во первых, такое название ничего не говорит о функциональности модуля, непонятно, что именно методы в этом .py файле делают. А во вторых со временем возникает соблазн не продумывать архитектуру библиотеки или расширяемого модуля, а сваливать все новореализованные методы в utils.

В этом случае можно назвать вроде `surrogate_fit`, `surrogate`, или любой другой вариант

2021-11-11 11:07 UTC, nicl-nno commented on fedot/core/explainability/utils.py
> +    return score
>explainability из core вынести повыше в иерархии на тот же самый уровень где лежит sensitivity у нас (модули вроде равнозначны)?

Мы это обсуждали - пока сделали оставили внутри core, т.к. в Pipeline есть вызовы Explainability (и наоборот). 
А sensitivity сейчас полностью отдельно функционирует.

Но если считаешь что так понятнее со стороны, то можно и вынести, не суть.

2021-11-11 11:23 UTC, Dreamlone commented on fedot/core/explainability/utils.py
> +    return score
Согласен, убедил)
Давайте тогда пока оставим этот модуль в core

2021-11-15 19:49 UTC, nicl-nno commented on fedot/core/explainability/explainers.py
> +def pick_pipeline_explainer(pipeline: 'Pipeline', method: str, task_type: TaskTypesEnum):
Может эту функцию перенести в explainer.py?

А то explainer и explainers как-то не очень отличаются по смыслу.

2021-11-15 19:51 UTC, nicl-nno commented on fedot/core/explainability/surrogate_explainer.py
> +        self.surrogate = single_node_pipeline(self.surrogate_str, self.surrogates_default_params[surrogate])
Кажется с т.з. SurrogateExplainer вообще не важно, что там именно single_node. Поэтому нет смысла выносить в название функции.

2021-11-15 19:51 UTC, nicl-nno commented on fedot/core/explainability/surrogate_explainer.py
> +    surrogate_node = PrimaryNode(model)
А если добавить Scaling - результат не становится лучше?

2021-11-15 19:53 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        :param instant_output: print and plot the explanation simultaneously, defaults to True.
Может понятнее будет назвать visualize?

2021-11-15 19:55 UTC, nicl-nno commented on fedot/core/explainability/surrogate_explainer.py
> +    def output(self, dpi: int = 300, **kwargs):
Если уж есть dpi - то и опциальный путь для сохранение на диск стоит предусмотреть.

2021-11-18 19:24 UTC, nicl-nno commented on fedot/core/explainability/surrogate_explainer.py
> +
Пуста строка явно лишняя.

2021-11-20 10:22 UTC, nicl-nno approved these changes
Осталось вынести примеры в отдельный каталог внутри examples и норм.

2021-11-20 10:29 UTC, MorrisNein commented on fedot/core/explainability/utils.py
> +    return score
> У меня есть вопрос-предложение. Может explainability из core вынести повыше в иерархии на тот же самый уровень где лежит sensitivity у нас (модули вроде равнозначны)?

Была и такая идея, чтобы подключить .explain в API, а не в core. В итоге, неумение Python 3.6 работать с циклическими импортами сыграло решающую роль, чтобы так сделать.

> Второе: utils здесь точно нужны?> 

Избавился от них :)

2021-11-20 10:41 UTC, MorrisNein commented
> Осталось вынести примеры в отдельный каталог внутри examples и норм.

Перенёс туда пример с пайплайном. Пример с API сейчас содержится в `fedot_api_example.py`. Можно там и оставить?

2021-11-20 10:44 UTC, MorrisNein commented
Кроме того, вывод рисунков в примерах сделал в корневой каталог FEDOT. Возможно, стоило использовать current working directory? На случай, если запустят примеры в FEDOT как site-package.

2021-11-20 10:55 UTC, nicl-nno commented
>Возможно, стоило использовать current working directory? 

Можно использовать default_fedot_data_dir(), если указан относительный путь. Если абсолютный - то его и использовать.

2021-11-20 11:00 UTC, nicl-nno commented
>Можно там и оставить?

Кмк лучше всё-же вынести для простоты поиска.

2021-11-20 11:04 UTC, Dreamlone commented
> Я пересмотрел идею и предлагаю пойти классическим путём: добавлять по классу (то есть по методу объяснения) в отдельный модуль. Добавил коммит.
Преимущество простое: мало связанные служебные функции и импорты не будут лежать в куче, сколько бы методов объяснимости мы не решили добавить в итоге. А их придумали много и продолжают стараться.
Импорт отдельного класса/-ов, всё ещё удобно делать из агрегирующего модуля explainers, где хранится функция pick_pipeline_explainer.

Было бы неплохо, если бы в фразе `Добавил коммит` была бы ссылка на сам коммит. Просто так я не очень понял что было сделано. Тогда разносить классы Explainer'ы в отдельные модули по какому принципу предполагается?

2021-11-20 11:11 UTC, Dreamlone requested changes

2021-11-20 11:11 UTC, Dreamlone commented on fedot/explainability/surrogate_explainer.py
> +    surrogate_model.fit(data)
А так и задумано, что суррогатная модель обучается без настройки гиперпараметров? 
Возможно, если использовать тут тюнинг, то модель сможет лучше аппроксимировать вывод "black-box модели"

2021-11-20 11:22 UTC, Dreamlone commented
Замечу ещё, что сегодня ночью меня просто засыпало уведомлениями о том, что в этот PR прилетел новый коммит) 

В целях экономии ресурсов (хотя вроде у нас сейчас нет таковых по запуску тестов но да ладно), можно push делать нескольких коммитов сразу, работаю в основном у себя локально. Например, предлагаю вместо схемы `коммит в 13:20, push в 13:21, коммит в 14:00, push в 14:01` использовать `коммит в 13:20, коммит в 14:00, push в 14:01`

2021-11-20 12:08 UTC, MorrisNein commented
> Было бы неплохо, если бы в фразе Добавил коммит была ссылка на сам коммит. 

Спасибо, учту на будущее.

Я предполагал, что отправляю комментарии сразу, и будет возможность посмотреть изменения. А сегодня выяснил, что комменты провисели в статусе Pending, и отправил всё скопом.

> Тогда разносить классы Explainer'ы в отдельные модули по какому принципу предполагается?

По принципу схожести методов, а значит, и используемого контекста. Например, есть пары методов, основное различие между которыми: один "глобальный", а другой "локальный". А принцип объяснения схожий. Их можно вынести в отдельный модуль.

Чтобы далеко не ходить, есть ещё т.н. "локальный суррогат", который логичнее всего добавить в `surrogate_explainer.py`

> Замечу ещё, что сегодня ночью меня просто засыпало уведомлениями о том, что в этот PR прилетел новый коммит)

Только что благодаря тебе узнал, что ревьюверам приходит уведомление по каждому залитому коммиту. Ну а про ресурсы тестирования совсем не думал. Впредь постараюсь разбивать коммиты на блоки и не заливать ночью. Извини за беспокойство!

2021-11-20 12:12 UTC, MorrisNein commented on examples/fedot_api_example.py
> +                            precision=6)
Ты предлагаешь изменить дефолтный путь сохранения или только пример сохранять в той же папке?

2021-11-20 12:16 UTC, MorrisNein commented on examples/fedot_api_example.py
> +                            precision=6)
Почитал ещё раз твой комментарий, ответ понятен. А почему так лучше, поделись мыслями

2021-11-20 12:20 UTC, MorrisNein commented on fedot/explainability/surrogate_explainer.py
> +    surrogate_model.fit(data)
Пока реализованы только деревья, тюнинг в целом ни к чему. Глубину нет смысла тюнить, так как с увеличением глубины уменьшается их интерпретируемость.

Вообще тоже об этом думал, но пока договорились отложить до востребованности.

2021-11-20 12:25 UTC, Dreamlone commented on examples/fedot_api_example.py
> +                            precision=6)
Потому что, когда запускаешь example например с анализом чувствительности, то результаты сохраняются в то же место, где и расположен сам пример с запуском. Хорошо бы, конечно, чтобы можно было самому задать этот путь при необходимости (сейчас такая возможность есть?), но по умолчанию ожидается (по крайне мере я), что если появится какой-нибудь файл, то появится он в том же месте, откуда я запускаю .py файл, а не на уровень выше, или не на уровень ниже. Но это конечно мелочи

2021-11-20 12:26 UTC, MorrisNein commented on examples/fedot_api_example.py
> +                            precision=6)
Просто если этот скрипт запустят из FEDOT как site-package, сейчас рисунок сохранится в корне основного проекта. Если захардкодить папку скрипта, то рисунок попадёт в venv, и кажется, что это не круто.

Поэтому интересно мнение, как следует выбрать путь сохранения.

2021-11-20 12:28 UTC, MorrisNein commented on examples/fedot_api_example.py
> +                            precision=6)
Спасибо за помощь)

2021-11-20 13:04 UTC, Dreamlone commented
> Спасибо, учту на будущее.

Так и какой в итоге коммит то был?) Прямо заинтриговал

> Извини за беспокойство! 

Да не стоит извиняться. В конце концов мне всегда можно отключить уведомления (что я потом и сделал), так что никакого беспокойства не было. В конце концов надо же мне как-то следить за тем что происходит в PR'х. Я этот разговор завёл к тому, что каждый отправленный в remote ветку коммит при открытом пулл реквесте запускает тесты, и если изменения были очень маленькими, например, исправлена опечатка в названии класса (а следующим коммитом хочешь например добавить новый класс), то мы по сути просто лишний раз прогнали тесты для проверки того, что и так работает нормально в первом случае. В общем мой тезис был про то, что коммиты вполне можно группировать

2021-11-20 13:38 UTC, Dreamlone reviewed
А есть какая-то причина почему тесты были вынесены в отдельное место "test/explainability", а не в unit. Вроде они довольно быстро отрабатывают

2021-11-22 17:07 UTC, Dreamlone approved these changes

2021-11-23 07:06 UTC, MorrisNein commented
>Так и какой в итоге коммит то был?) Прямо заинтриговал

Вот [этот](https://github.com/nccr-itmo/FEDOT/pull/482/commits/78273a675ff4729e34900aa4ac1da048e495a2a4) и [этот](https://github.com/nccr-itmo/FEDOT/pull/482/commits/78273a675ff4729e34900aa4ac1da048e495a2a4)
До них всё было в explainers.py и в utils.py
Вынес оба класса (интерфейс и наследника) в отдельные модули и избавился от utils.py, всё его содержимое отнёс к surrogate_explainer.

> А есть какая-то причина почему тесты были вынесены в отдельное место "test/explainability", а не в unit. Вроде они довольно быстро отрабатывают

Нет, я был не в курсе, для чего другие вынесли из `unit`-а, и сделал по аналогии. Перенёс всю папку в `unit`

> В общем мой тезис был про то, что коммиты вполне можно группировать.

Договорились)
Не правая, а левая.
![image](https://user-images.githubusercontent.com/57573631/142982919-eb9bfbc2-2c68-42d8-bf18-639ed8d63e30.png)

2021-11-23 07:29 UTC, merged