Editing preprocessing
nccr-itmo/FEDOT pull request #483
Opened 2021-11-02 15:16 UTC by aPovidlo

Solving errors in `_preprocessing_input_data()` and `ImputationImplementation - fit`. Was added method `preprocessing_features_full_of_nans()` in preprocessing.py, which dropping features with more than 30% of nan's. Fix problem in `sklearn_transformation.py`.

2021-11-02 15:34 UTC, Dreamlone requested changes

2021-11-02 15:34 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +
Давай может сделаем более говорящее название, например `drop_features_full_of_nans`? 
Плюс я так понял, мы договорились, чтобы не вызывать этот метод на predict стадии

2021-11-02 15:35 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +
А так в целом готов вливать в penn-check. Потом её до ума доведу и вольем в мастер на днях

2021-11-03 11:51 UTC, aPovidlo commented on fedot/core/pipelines/pipeline.py
> +
Название поменяю. Если не вызывать метод, то так не работает. Думаю, пока оставить так.

2021-11-03 12:10 UTC, Dreamlone approved these changes

2021-11-03 12:12 UTC, merged