Modifying table preprocessing
nccr-itmo/FEDOT pull request #484
Opened 2021-11-03 20:28 UTC by Dreamlone

Improved processing of some tabular data. For now it is possible to fit pipelines on tables:

1) When the cateogories in the categorical features from the test did not occur in the train
2) When a dataset contains only categorical features 
3) When a dataset contains features with a large number of gaps  (more than 30%)

Also, pipeline preprocessing refactor was done. 

> Attention: Processing datasets with gaps is still complicated, because the current implementation does not allow to adequately process the gaps in the datasets during predict stage. The preprocessing logic of pipelines is being revised for this purpose, Andrey @aPovidlo is working on it

2021-11-06 10:23 UTC, nicl-nno requested changes

2021-11-06 10:23 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        logger.info(f'Initial pipeline fit were failed due to: {ex}')
Тут лучше возвращать error и добавлять пару слов пояснения, что это значит ("проверьте данные, тип задачи и т.п.). Т.к. это одна из основных ошибок, с которой может столкнуть пользователь.

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +            self.remove_binary_features_from_ids(input_data)
Комментарий и название функции не слишком согласуются.

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +    def remove_binary_features_from_ids(self, input_data: InputData):
Опять же, в названии remove, а дальше всё про convert

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
А зачем конвертировать именно во float, а не int, если значение бинарное?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    self.imputer_num.fit(numerical.features)
Тут бы как-то упростить, т.к. почти весь код дублируется..

Например, вынести в функцию, принемающую на вход features

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    numerical_features = self.imputer_num.transform(numerical.features)
Аналогично тому что выше.

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/preprocessing.py
> +            return True
А np.isnan(array) тут не сработает?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/preprocessing.py
> +EMPIRICAL_PARTITION = 0.5
А EMPIRICAL_PARTITION где-то используется сейчас?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/preprocessing.py
> +    has_encoder = len([_ for _ in has_encoders if not _]) == 0
Может через Any это проверять?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/preprocessing.py
> +            # Column not a string and cannot be converted into str
А такое возможно на практике?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/preprocessing.py
> +            features_df[column] = features_df[column].str.strip()
А что-то вроде df.applymap(lambda x: x.strip() if isinstance(x, str) else x) не будет быстрее?

2021-11-06 10:23 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +            copied_input_data = self._preprocessing_fit_data(copied_input_data)
Немного смущает то, что обработка данных будет выполняться каждый раз, когда обучается пайплайн в композере. Выглядит как потенциальное место для просадки производительности.

Было бы здорово добавить проверку, не сделана ли уже эта операция для API. Мб через флаг в InputData. Ну и в API соответственно продублировать эту операцию.

2021-11-09 13:02 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
Бинарное же может быть например и так:
```
[['1.5'],
 ['1.7'],
 ['1.5']]
```
Тогда при попытке конвертировать этот столбец в int, получим и вовсе константный признак: [1, 1, 1]

2021-11-09 13:19 UTC, Dreamlone commented on fedot/core/pipelines/preprocessing.py
> +            return True
Эту функцию не я писал. Глеб @MAGLeb, есть какая-то причина, почему ты её именно так записал, или Колин вариант тоже подходит? Моё мнение, что np.isnan(array) лучше подойдёт, дай отмашку - перепишу

Бай вэ вей, текущая функция вроде не улавливает пропуски. Например output кода 
```
arr = np.array([10, 20, np.nan, 20, 10, 5])
print(is_np_array_has_nan(arr))
print(np.isnan(arr))
```
был вот такой:
```
False
[False False  True False False False]
```

2021-11-09 13:19 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
Но можно же сразу конвертировать в 0 и 1? Раз заведомо len(column_uniques) < 2

2021-11-09 13:21 UTC, Dreamlone commented on fedot/core/pipelines/preprocessing.py
> +            # Column not a string and cannot be converted into str
Конечно, иначе бы я и не написал такое исключение) 
Вроде у меня проблема была с какими-то видами nan'в, сейчас проверю ещё раз в чем конкретно было дело

2021-11-09 13:28 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
Можно так сделать. В таком случае придётся хранить label_encoder в каком-то виде в состояниях класса OneHot Encoder'а. Ну или хотя бы какой-нибудь словарик вида {old_value: new_value} и так для каждого бинарного признака, который мы конвертируем
Сделать так?

2021-11-10 08:44 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        logger.info(f'Initial pipeline fit were failed due to: {ex}')
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR297-R301)

2021-11-10 08:45 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +            self.remove_binary_features_from_ids(input_data)
Изменил название, обновил описание и комментарии в коде
См. [коммит](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-5e39a9f9030a5ede5afe0312e144050dc38e5fdb5b9c773251d98c40fdbc807fR206-R209)

2021-11-10 08:45 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +    def remove_binary_features_from_ids(self, input_data: InputData):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-5e39a9f9030a5ede5afe0312e144050dc38e5fdb5b9c773251d98c40fdbc807fR206-R209)

2021-11-10 08:46 UTC, Dreamlone commented on fedot/core/pipelines/preprocessing.py
> +EMPIRICAL_PARTITION = 0.5
Нет, [удалил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-b7d035e49f07b172c460ba50b4d631033e2a8c3a96811959aee1c82a031fb18bL15-L20)

2021-11-10 08:48 UTC, Dreamlone commented on fedot/core/pipelines/preprocessing.py
> +    has_encoder = len([_ for _ in has_encoders if not _]) == 0
[Сделал через all](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-b7d035e49f07b172c460ba50b4d631033e2a8c3a96811959aee1c82a031fb18bR138-R139) 

Нужно же проверить, что во всех ветках в пайплайне присутствует требуемая операция

2021-11-10 08:49 UTC, Dreamlone commented on fedot/core/pipelines/preprocessing.py
> +            features_df[column] = features_df[column].str.strip()
[Заменил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/3eb546a4fed64afbdcc087381eb9f54daff07ebc#diff-b7d035e49f07b172c460ba50b4d631033e2a8c3a96811959aee1c82a031fb18bR153-R154)

2021-11-12 09:47 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

































* In the file [`test/unit/test_data_preprocessing.py`](https://github.com/nccr-itmo/FEDOT/blob/28996303c6758b83cfa07677b560e83f953a597e/test/unit/test_data_preprocessing.py):

> [Line 133:32](https://github.com/nccr-itmo/FEDOT/blob/28996303c6758b83cfa07677b560e83f953a597e/test/unit/test_data_preprocessing.py#L133): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-11-25 10:57 UTC, Dreamlone commented
Коллеги (@nicl-nno, @MAGLeb, @J3FALL), прошу присоединиться к обсуждению этого PR. Поскольку было сделано довольно много и планы тоже по совершенствованию добавились, то подумал, что неплохо было бы подвести некоторую черту. 

**Сделано:**
- Существенно переработан препроцессинг. Ранее все функции (после PR Глеба) по препроцессингу лежали в pipeline.py. Сейчас они перекочевали в полноценный модуль [preprocessing](https://github.com/nccr-itmo/FEDOT/tree/penn-check/fedot/preprocessing). Самый главный класс там DataPreprocessor. Он занимается "обязательной предобработкой" и "опциональной". В "обязательную предобработку" входят такие штуки как трансформация ячеек из "x ", " x" в "x", "x", преобразование одномерных target'в в столбцы при решении задачи классификации и регрессии, исключение признаков с количеством пропусков более 90% и т.д. То есть всякая "грязная работа". Есть еще и элитарная "опциональная предобработка". Она заключается в применении операций "заполнения пропусков" и "кодирования категориальных признаков" если таковых операций в структуре пайплайна для которого осуществляется предобработка, нет. Если такие операции есть, то эта самая "опциональная предобработка" не проводится. Как понять, что в пайплайне есть подходящие операции? - Для этого в препроцессинге реализован класс [PipelineStructureExplorer](https://github.com/nccr-itmo/FEDOT/blob/penn-check/fedot/preprocessing/structure.py#L8). Он исследует структуру пайплайна, и если обнраживает, что если пропуски не заделать сейчас хоть как-то, по пайплайн вывалится с ошибкой, то "даёт сигнал" DataPreprocessor'у - действуй, и тот применяет заполнение пропусков перед тем как подать данные в пайплайн. Зачем это сделано? - чтобы композер если что всегда мог подобрать более оптимальный способ кодирования или заполнения пропусков (например, не OneHotEncoding, а LabelEncoding или любой другой). Но при этом, пайплайн не упадёт с ошибкой даже если операций обработки в его структуре не будет. 
- Изменилась предобработка на разных уровнях (API и пайплайн). Теперь обязательная предобработка происходит на уровне API всегда. Как только она сделана, предобработанный блок InputData через SupplementaryData флаг was_preprocessed помечается как "прошедший обязательную предобработку". Затем в методах Pipeline fit и predict если блок данных не был предобработан, то запускается обязательная уже на уровне пайплайна. После уже идет - опциональная. 
- Произвёл небольшой рефакторинг API. Убрал лишний (на мой взгляд) ApiFacade. который просто дублировал функциональность Fedot класса. Поменял названия классов на более говорящие (опять же, на мой взгляд). Также вынес несколько повторяющихся переменных в переменные состояния (раньше классы были просто набором функций, никаких преимуществ class конструкции не использовалось, сейчас немного исправлено). Также избавился от множественного наследования и в целом следовал советам из этого [issue](https://github.com/nccr-itmo/FEDOT/issues/422). Перешёл к композиции, а не наследованию, полагаю, теперь "diamond problem" можно считать решенной (?)
- Добавил довольно много (я надеюсь) тестов с игрушечными датасетами, которые должны обрабатываться корректно. См. функции-генераторы в [test_data_preprocessing](https://github.com/nccr-itmo/FEDOT/blob/penn-check/test/unit/test_data_preprocessing.py) и методы [get_mixed_data](https://github.com/nccr-itmo/FEDOT/blob/penn-check/test/unit/data_operations/test_data_operations_implementations.py#L131) и [get_nan_binary_data](https://github.com/nccr-itmo/FEDOT/blob/penn-check/test/unit/data_operations/test_data_operations_implementations.py#L162). Все они тестируются на то, чтобы а) корректно обрабатывались через API или на уровне pileline и б) обрабатывались как задумано (кодировались в нужное количество признаков, удалялись в нужных размерах и так далее). 
- Есть нововведения в обработке таблиц. Думаю, там будет понятно из кода и тестов, но если коротко, то "строки с nan в target'е удаляются", "столбцы-признаки с более чем 90% пропусков удаляются", "если в категориальном признаке в test'e появляется категория, которой не было в train'e, то всё будет работать корректно не упадёт", "если признак бинарный категориальный, то он конвертируется в бинарный целочисленный, например `['a', 'b']` -> `[1, 0]`. Если в признаке будут пропуски, то они будут проигнорированы и вставлены на свои места после обработки, вроде `['a', 'b', np.nan]` -> `[1, 0, np.nan]`. Если в test'e встретится новая категория в этом признаке (не 'a'и не 'b'), то она будет сконвертирована в следующий по порядку int номер, то есть в 2, затем в 3 и так далее. Признак в дальнейшем не рассматривается как категориальный.

**Что планируется сделать в этом PR:**
- С сериализацией пайплайнов с предобработкой сейчас не всё так гладко. Помимо обученных моделей нужно будет хранить encoder, imputer, все labelencoder'ы для бинарных категориальных признаков и так далее. Не думаю, что возникнут серьезные проблемы, просто пока не сделал ещё. Для проверки нормального экспорта импорта даже сделан тест, но пока прикрыт skip. Уберу fixture после того как реализую
- Провести эксперименты на таблицах для хуавея (это ведь в первую очередь для них затевалось). Если где-то что-то будет падать, то итеративно буду улучшать 
- Надо бы сделать конвертатор для target-столбца при решении задачи классификации. То есть во время предобработки конвертировать метки в духе `['болен', 'здоров']` в `[1, 0]`.

**Что планируется сделать в дальнейшем:**
- Функциональность для предобработки мультимодальных данных пока отвалилась. За один PR такое не проглотить (он и так большой вышел). Тем более что, написать обработчик это одно дело, а вот адекватно его проверить и обложить тестами - совсем другое, в общем, займёт время. Сделаю соответствующее issue как закончу с этим PR'м. 
- Обработка бинарных признаков при заполнении пропусков. Сейчас если в бинарном признаке есть пропуск `[1, 1, np.nan, 0]`, то он заполнится 0.66. А корректно скорее всего было бы подставить 1. Мелочь, но неприятно. Также сделаю на это issue 

Сейчас поставлю лейбл `in progress` для этого PR и к середине/концу следующей недели постараюсь завершить. Буду рад вашим дельным комментариям! (на таких больших изменениях взгляд может замыливаться)

2021-11-30 22:38 UTC, nicl-nno requested changes

2021-11-30 22:38 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +    def get_composer_dict(composer_dict):
А предполагается использование этого метода снаружи? Может сделать приватным и вынести из класса?
Ну и пояснений, что ожидается на выходе, не помешает.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        raise ValueError(advice_info)
Тут стоит стэктрейс дублировать для удобства отладки.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +            raise SystemExit(message_success)
Вот тут не очень понял.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/api/api_utils/api_data.py
> +        self.mark_as_preprocessed(data)
Может это делать внутри obligatory_prepare_for_*?

2021-11-30 22:38 UTC, nicl-nno commented on fedot/api/api_utils/api_data.py
> +    @staticmethod
Точно стоит вынести как private-функцию.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/core/data/data.py
> +def divide_data_categorical_numerical(input_data: InputData, categorical_ids: list,
Мб функции, вязанные именно с препроцессингом, вынести в отдельный скрипт в рамках модуля data? А то слишком раздут data.py

2021-11-30 22:38 UTC, nicl-nno commented on fedot/core/data/data.py
> +def _return_subsample_features(input_data: InputData, ids: list):
Кажется лучше subset и features_ids, чтобы не было путаницы со строками.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +        automl_repo = OperationTypesRepository(operation_type='automl')
Тут бы конечно конечно была полезна operation_type='all'.
Но это вроде @aPovidlo в [PR](https://github.com/nccr-itmo/FEDOT/pull/491/files) уже реализовал.

2021-11-30 22:38 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +            if self.data_preprocessor is not None:
А если данные обработаны на уровне API - выгрузка все равно работает?

2021-11-30 22:38 UTC, nicl-nno commented on fedot/preprocessing/preprocessing.py
> +            if data_has_categorical_features(data) and not data_has_missing_values(data):
Выглядит вычислительно неэффективным каждый раз заново проверять data_has_categorical_features/data_has_missing_values

2021-11-30 22:38 UTC, nicl-nno commented on fedot/preprocessing/preprocessing.py
> +                    self.apply_imputation(data)
Ну тут конечно сложная логика. Схожу кажется что можно сначала обработать пропуски (если нужно), а потом энкодить (если нужно) - но может упускаю какой-то нюанс.

2021-12-01 07:32 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                                check_mode: bool,
Описание есть в [docstring класса Fedot](https://github.com/nccr-itmo/FEDOT/blob/penn-check/fedot/api/main.py#L55)

2021-12-01 07:37 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            raise SystemExit(message_success)
Когда выставляется флаг `check_mode`, делается следующая последовательность действий: формируется начальное приближение, обучается, даётся прогноз, программа завершает работу. 
Сделано для того, чтобы когда хочется просто проверить корректность данных / установки библиотеки, не ждать пока композер начнет крутить свои поколения, можно было запустить api вот в таком режиме.

Теоретически можно возвращать полученное начальное приближение после завершения обучения - могу сделать и так

2021-12-01 08:09 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +            raise SystemExit(message_success)
Может в таких случаях задавать pre_defened_model вместо нового параметра? Можно для удобства сделать pre_defined_model = 'auto', чтобы удобнее было/

2021-12-01 13:12 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +    def get_composer_dict(composer_dict):
Сделал метод приватным и вынес его из под класса в отдельную функцию. Поменял название для неё и аргумента, теперь функция называется `_divide_parameters,` см. [тут](https://github.com/nccr-itmo/FEDOT/pull/484/commits/8f554a7a059d9f3f43f83a1a02a830aa8af4bb9d#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR305-R328). 

Также модифицировал способ объединения операций из preset'а и исходных (для временных рядов)

2021-12-01 13:40 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        raise ValueError(advice_info)
Сделал вывод [вот так](https://github.com/nccr-itmo/FEDOT/pull/484/commits/8f554a7a059d9f3f43f83a1a02a830aa8af4bb9d#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR301-R302), но возможно есть более элегантный способ это делать

2021-12-01 13:41 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +        self.mark_as_preprocessed(data)
[Перенёс метод в preprocessing](https://github.com/nccr-itmo/FEDOT/pull/484/commits/8f554a7a059d9f3f43f83a1a02a830aa8af4bb9d#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR69-R81)

2021-12-01 13:41 UTC, ChrisLisbon commented on test/unit/pipelines/test_pipeline_preprocessing.py
> +    pipeline.fit(categorical_data)
Тут assert не должен быть?

2021-12-01 13:41 UTC, ChrisLisbon commented on test/unit/test_data_preprocessing.py
> +    assert predicted[0] == 'ba'
В комменте тоже должно быть 'ba' или я не поняла?

2021-12-01 13:46 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +    def get_composer_dict(composer_dict):
Поменял название этой функции на _divide_parameters, плюс добавил описание 
См. [тут](https://github.com/nccr-itmo/FEDOT/pull/484/commits/8f554a7a059d9f3f43f83a1a02a830aa8af4bb9d#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR305-R328)

2021-12-01 13:51 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +    @staticmethod
[Перевёл](https://github.com/nccr-itmo/FEDOT/pull/484/commits/8f554a7a059d9f3f43f83a1a02a830aa8af4bb9d#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bL105-R105) методы в функции, сделал их приватными

2021-12-01 13:52 UTC, Dreamlone commented on fedot/core/data/data.py
> +def divide_data_categorical_numerical(input_data: InputData, categorical_ids: list,
Вынес в [data_preprocessing.py](https://github.com/nccr-itmo/FEDOT/pull/484/commits/bfba60ac545e86c859c1d9c9d9c591dcf3d8d386#diff-c1c9919b19ad3855f98b1a40f465c33911178a991571f93127655f2ff03e64a5R1-R2)

2021-12-01 13:53 UTC, Dreamlone commented on fedot/core/data/data.py
> +def _return_subsample_features(input_data: InputData, ids: list):
Изменил название, добавил описание, поменял название аргумента с ids на features_ids
См. [тут](https://github.com/nccr-itmo/FEDOT/pull/484/commits/bfba60ac545e86c859c1d9c9d9c591dcf3d8d386#diff-c1c9919b19ad3855f98b1a40f465c33911178a991571f93127655f2ff03e64a5R45-R54)

2021-12-01 13:54 UTC, Dreamlone commented on fedot/core/pipelines/node.py
> +        automl_repo = OperationTypesRepository(operation_type='automl')
Добавил [todo](https://github.com/nccr-itmo/FEDOT/pull/484/commits/bfba60ac545e86c859c1d9c9d9c591dcf3d8d386#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR214), чтобы не забыть обновить это место после того, как изменения Андрея вольются в мастер

2021-12-01 13:58 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +            if data_has_categorical_features(data) and not data_has_missing_values(data):
Вынес вычисление этих флагов [чуть повыше](https://github.com/nccr-itmo/FEDOT/pull/484/commits/bfba60ac545e86c859c1d9c9d9c591dcf3d8d386#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR97-R100). Теперь вычисляются всего один раз

2021-12-01 13:58 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +                    self.apply_imputation(data)
Ты абсолютно прав, лишнего кода написал. 
[Упростил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/bfba60ac545e86c859c1d9c9d9c591dcf3d8d386#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aL112-L123)

2021-12-01 14:05 UTC, Dreamlone commented on fedot/core/pipelines/template.py
> +            if self.data_preprocessor is not None:
Да, конечно, ведь у Pipeline при инициализации существует свой дефолтный DataPreprocessor. После окончания обучения через API, обученные энкодеры передаются в DataPreprocessor пайплайна 
Так что полученный через API пайплайн сериализуем и имеет все требуемые экнодеры/обработчики для успешного запуска

2021-12-01 14:19 UTC, Dreamlone commented on fedot/api/api_utils/metrics.py
> +        return task_dict[self.problem]
Насколько я понимаю, идея в следующем. Композеру (и тюнеру) нужна метрика для оптимизации. Также нужна метрика / метрики для вывода значений при вызове get_metrics через API. В первом случае. если нам нужно определить метрику для оптимизации, а приходит список, выбирается одна (по умолчанию решается задача однокритериальной оптимизации). Во втором же берутся обе, и посчитанные значения метрик выводятся для каждой из них

Общим хранилищем выступает всегда этот словарь

2021-12-01 14:36 UTC, nicl-nno commented on fedot/core/pipelines/template.py
> +            if self.data_preprocessor is not None:
Норм

2021-12-01 14:39 UTC, ChrisLisbon commented on fedot/api/api_utils/metrics.py
> +        return task_dict[self.problem]
Поняла, спасибо

2021-12-01 16:06 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            raise SystemExit(message_success)
[Переработал](https://github.com/nccr-itmo/FEDOT/pull/484/commits/ca4a81479567047d928e34b5da95cbc796e7cb05)
Теперь check_mode нет, но если задать predefined_model = 'auto', то провернётся ровно то же самое, что и выше, но без exit'а, то есть просто вернётся обученный пайплайн

2021-12-01 16:07 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +                    self.apply_imputation(data)
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/484/commits/594aa5ba41fcbb037a14b3cd4e2b0ec29ade70af#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aL96-R103) ещё проще

2021-12-01 16:10 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +        """
В словарь оборачиваются мультимодальные данные. [Добавил](https://github.com/nccr-itmo/FEDOT/pull/484/commits/594aa5ba41fcbb037a14b3cd4e2b0ec29ade70af#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bL38-R39) фразу про это

2021-12-01 16:13 UTC, Dreamlone commented on test/unit/test_data_preprocessing.py
> +    assert predicted[0] == 'ba'
[Добавил пояснение](https://github.com/nccr-itmo/FEDOT/pull/484/commits/594aa5ba41fcbb037a14b3cd4e2b0ec29ade70af#diff-522ee6a5b9129f76a01487a5b0e8e4598f342aaffac76457a9f94f1fa27519f5R162). В пространстве признаков метка 'ba' самая близкая к 'di'. Её после энкодинга и должен был предсказать пайплайн.

2021-12-01 16:41 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
В итоге сделал с label_encoder?

2021-12-01 16:41 UTC, nicl-nno approved these changes

2021-12-01 18:33 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +                    np.array(categorical_features[:, column_id], dtype=float)
Ага, в итоге этим занимается отдельный класс в препроцессинге - [BinaryCategoricalPreprocessor](https://github.com/nccr-itmo/FEDOT/blob/668fab0e4a7072c2f969f073d93306b4fb459fd2/fedot/preprocessing/categorical.py#L13)

2021-12-01 20:05 UTC, merged