Stopping criteria for composer
nccr-itmo/FEDOT pull request #491
Opened 2021-11-12 13:35 UTC by aPovidlo

Resolve the issue [#445](https://github.com/nccr-itmo/FEDOT/issues/445). 
The stopping criteria should be implemented for a composer to avoid unnecessary long runs. The proposed criteria is 'stopping_after_n_generation` generations without improvement for all objective functions. Default `stopping_after_n_generation = 7`, but the external configuration option should be provided.

2021-11-12 14:01 UTC, nicl-nno requested changes
Концептуально норм, осталось добавить тест на мини-датасете: задать очень большое время оптимизации и убедиться, что останавливается за пару секунд.

Можно ещё пул моделей сделать минимальным, чтобы лучше сходилось.

2021-11-12 14:01 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +    def _is_stopping_criteria_triggered(self):
А зачему этот метод дублировать дважды?

2021-11-12 14:01 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                self.log.info(f'GP_Optimiser: Early stopping criteria was triggered and generation finished')
Может это сообщение выводить внутри _is_stopping_criteria_triggered?

Вместо "generation" лучше "composing", чтобы избежать путаницы.

2021-11-12 14:12 UTC, aPovidlo commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +    def _is_stopping_criteria_triggered(self):
Из-за использования переменных внутри классов. Если в итоге оба будут объединены в один метод, то создавать сейчас общую функцию смысла не вижу.

2021-11-12 14:12 UTC, aPovidlo commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                self.log.info(f'GP_Optimiser: Early stopping criteria was triggered and generation finished')
Исправил оба замечания

2021-11-19 09:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        if self.use_stopping_criteria:
Тут можно и без проверки обойтись.

2021-11-19 12:56 UTC, aPovidlo commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        if self.use_stopping_criteria:
Убрал проверку

2021-11-22 12:30 UTC, nicl-nno commented
Проведи ещё эксперимент - как качество получившегося индивида зависит от значения числа поколений early_stopping. Вдруг 7 - слишком мало.
Можно использовать обязку для экспериментов, которую Илья делал.

2021-12-03 12:48 UTC, nicl-nno approved these changes
Пока установим значение критерия 10, а там посмотрим.

Ну и ребейзнуть надо.

2021-12-04 16:37 UTC, Dreamlone commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
Я обычно стараюсь такие параметры объединять в один, чтобы избежать неожиданного поведения. Например, вот я пользователь, задаю use_stopping_criteria=False и stopping_after_n_generation=20, - критерий остановки будет применён? Вопрос на самом деле риторический, ведь "я" сам возможно не знаю, что именно хочу сделать, то ли отключить критерий, то ли назначить ему 10 операций. Может объединить? 
Например, сделать `stopping_after_n_generation` по умолчанию None? И всегда, когда stopping_after_n_generation None запускать композер без критерия

2021-12-04 16:55 UTC, Dreamlone reviewed
Вроде бы всё норм. Ворнингов по репозиторию не появляется, за исключением совсем уж странных `UserWarning: Operation w not found in the repository warnings.warn(f'Operation {operation_id} not found in the repository'`

Главное, что теперь их не выводится так много

2021-12-06 12:06 UTC, aPovidlo commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
@Dreamlone если указать `use_stopping_criteria = False`, то ранней остановки не будет. По постановке задачи критерий ранней остановки должен быть включен по умолчанию.

2021-12-06 12:10 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
Речь тут о другом - 2 два параметра можно заменить на один.

2021-12-06 12:17 UTC, aPovidlo commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
@nicl-nno то есть оставить `stopping_after_n_generation', который может принимать булевы значения и целочисленные?

2021-12-06 12:39 UTC, nicl-nno commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
Думаю если критерий отключён - то None или меньше 1.

2021-12-06 14:29 UTC, aPovidlo commented on fedot/api/api_utils/params.py
> +                  'stopping_after_n_generation': 10}
@nicl-nno изменил на None

2021-12-06 16:35 UTC, Dreamlone approved these changes

2021-12-06 16:45 UTC, merged