add cut operation
nccr-itmo/FEDOT pull request #492
Opened 2021-11-12 15:06 UTC by valer1435

Implementation of cutting a time series to avoid unnecessary  information

2021-11-12 15:06 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`test/unit/tasks/test_forecasting.py`](https://github.com/nccr-itmo/FEDOT/blob/dbad3519b9c137c3c5eb5709619e6fd1c01eb6fc/test/unit/tasks/test_forecasting.py):

> [Line 177:14](https://github.com/nccr-itmo/FEDOT/blob/dbad3519b9c137c3c5eb5709619e6fd1c01eb6fc/test/unit/tasks/test_forecasting.py#L177): [E225](https://duckduckgo.com/?q=pep8%20E225) missing whitespace around operator

2021-11-12 19:29 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.cut_part = 0
Может задать какой-то значение по умолчанию > 0? 
Иначе этот блок вообще никакой функции не выполняет когда cut_part не задано.

2021-11-13 09:50 UTC, Dreamlone requested changes
Файл `test/data/simple_regression_train.csv — ярлык.lnk` затесался, выгоняй его оттудова 

Дефолтное значение гиперпараметра для cut операции также нужно добавить в соответствующий json файл (см. `fedot\core\repository\data\default_operation_params.json`)

2021-11-13 09:50 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def transform(self, input_data, is_fit_pipeline_stage: Optional[bool]):
Для fit'а в docstring дейтсвительно думаю можно обойтись только фразой `Class doesn't support fit operation`, а вот для метода transform стоит добавить описание.

И сам класс стоит поднять повыше функций, к другим классам. Например начиная со строки номер 278

2021-11-13 09:50 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                self.cut_part = 0
Изменение гиперпараметра стоит вынести в отдельный метод и писать об этом в лог

2021-11-13 09:50 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        input_copy.idx = np.arange(output_values.shape[0])
Может стоит передавать действительно те индексы объектов, которые были оставлены, а не задавать их заново?
Потому что если сейчас например исходный временной ряд с индексами `[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]` мы обрежем с cut_part=0.5, то останутся индексы ведь `[6, 7, 8, 9, 10]`, а задаёшь ты их как `[1, 2, 3, 4, 5,]`, что не правда

2021-11-13 09:50 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        return {"cut_part": self.cut_part}
Если cut_part скорректирован (а ты его корректируешь в конструкторе класса), то и передавать его в этом методе стоит по другому, посмотри как это реализовано в методе get_params класса LaggedTransformationImplementation

2021-11-13 09:50 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    assert test_data.features.shape[0] == 2 * test_pred.idx.shape[0] - horizon
Мне кажется в этом тесте не стоит проверять вывалился пайплайн за threshold или нет. Просто ограничиться проверкой того, что ряд действительно обрезается как надо. И делать это кмк стоит не на уровне пайплайна, а пониже. Например, создать узел с cut операцией, подать ему на вход данные и проверить действительно ли он их корректно обрезает по индексам и по длине ряда. 

Тест можно будет в таком случае перенести в `test\unit\data_operations\test_data_operations_implementations.py`

2021-11-13 11:00 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    assert test_data.features.shape[0] == 2 * test_pred.idx.shape[0] - horizon
Перенес тест https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:01 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        return {"cut_part": self.cut_part}
Переделал https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:01 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        input_copy.idx = np.arange(output_values.shape[0])
Теперь индексы не с 0 https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:02 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                self.cut_part = 0
Не уверен, стоит ли (2 строки там) https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

Но если надо, то сделаю

2021-11-13 11:02 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    def transform(self, input_data, is_fit_pipeline_stage: Optional[bool]):
Убрал повыше и добавил docstring к transform https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:03 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    horizon =5
Метод убран https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:03 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.cut_part = 0
Переделал постановку значения по умолчанию https://github.com/nccr-itmo/FEDOT/pull/492/commits/e24e766ca532f28dd8e0886d94ddd4d2243b4354

2021-11-13 11:34 UTC, nicl-nno approved these changes

2021-11-13 12:04 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                self.cut_part = 0
Пойдет

2021-11-13 12:09 UTC, Dreamlone approved these changes

2021-11-13 13:18 UTC, merged