Polyfit operation implementation
nccr-itmo/FEDOT pull request #493
Opened 2021-11-15 16:24 UTC by valer1435

implementation for polyfit operation to find a trend

2021-11-15 16:24 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py`](https://github.com/nccr-itmo/FEDOT/blob/6662ff096422edc52e8bd64cfc419fb4c7f5bb4e/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py):

> [Line 652:49](https://github.com/nccr-itmo/FEDOT/blob/6662ff096422edc52e8bd64cfc419fb4c7f5bb4e/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py#L652): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 653:49](https://github.com/nccr-itmo/FEDOT/blob/6662ff096422edc52e8bd64cfc419fb4c7f5bb4e/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py#L653): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2021-11-15 16:26 UTC, nicl-nno commented on test/unit/models/test_repository.py
> +        assert len(model_names) == 11
Может переработать этот тест, чтобы не надо было его каждый раз после добавления моделей изменять? А то не очень удобно.

2021-11-15 16:28 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            input_data.target = target_columns
Вот это не дублируется в разных имплементациях? Мб вынести в отдельную функцию?

2021-11-15 16:28 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return tuple([params_dict, ['cut_part']])
А тут точно должно быть именно cut_part? Вроде это из другой модели.

2021-11-15 17:03 UTC, Dreamlone requested changes

2021-11-15 17:06 UTC, Dreamlone commented
Может кстати файл `monthly-beer-production-in-austr.csv` переименовать покороче? Но это всё конечно косметические моменты

2021-11-16 16:44 UTC, valer1435 commented on test/unit/models/test_repository.py
> +        assert len(model_names) == 11
Не очень понимаю, как это можно пока исправить(

2021-11-16 16:54 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            input_data.target = target_columns
К сожалению, у ARIMA похожая, но все-таки другая имплементация

2021-11-16 17:03 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            input_data.target = target_columns
Ок.

2021-11-16 17:04 UTC, nicl-nno commented on test/unit/models/test_repository.py
> +        assert len(model_names) == 11
Я бы предложил проверять что  len(model_names) после запроса больше изначального.
И то что все модели из ['linear', 'logit', 'knn', 'lda', 'lasso', 'ridge', 'polyfit'] в него входят.

2021-11-16 17:26 UTC, valer1435 commented on examples/time_series/polyfit_example.py
> +    :param len_forecast: forecast length
Добавил описание https://github.com/nccr-itmo/FEDOT/pull/493/commits/ca0a0600973e64ce1659fd293a4cf5c0707fff51

2021-11-16 17:26 UTC, valer1435 commented on examples/time_series/polyfit_example.py
> +                                cv_folds=None):
Заменил на degree https://github.com/nccr-itmo/FEDOT/pull/493/commits/ca0a0600973e64ce1659fd293a4cf5c0707fff51

2021-11-16 17:26 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            return tuple([params_dict, ['cut_part']])
Заменил на degree https://github.com/nccr-itmo/FEDOT/pull/493/commits/ca0a0600973e64ce1659fd293a4cf5c0707fff51

2021-11-17 08:34 UTC, Dreamlone requested changes
В целом осталось только исправить небольшие комментарии. Только нужно понять перед мержом в мастер почему тесты не проходят. У меня локально вроде всё отработало нормально

2021-11-17 08:34 UTC, Dreamlone commented on examples/time_series/polyfit_example.py
> +                                                          test_data_features=train_data)
Предлагаю переписать эту часть при помощи внутренних функций FEDOT'а. 
Можно сделать так (сначала импорт)
```
from fedot.core.data.data_split import train_test_data_setup
```
Потом можно сделать вот так
```
train_input = InputData(idx=np.arange(0, len(time_series)),
                        features=time_series,
                        target=time_series,
                        task=task, 
                        data_type=DataTypesEnum.ts)
train_data, test_data = train_test_data_setup(data)
```

2021-11-17 08:34 UTC, Dreamlone commented on examples/time_series/polyfit_example.py
> +    mse_before = mean_squared_error(test_data, predict, squared=False)
Исходя из[ этой страницы](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html), если squared = False, то возвращается RMSE метрика, а не MSE. Следовательно метрику лучше записывать в переменную `rmse_before ` и так далее (замечу правда, что ниже в print название выводится правильно). Исправь плиз и в том примере, на который ты полагался при составлении этого

2021-11-17 08:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.degree = params.get('degree')
Может округлять будем на всякий случай этот гиперпараметр до целых значений?

2021-11-17 08:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +from matplotlib import pyplot as plt
Неиспользуемый импорт

2021-11-17 10:39 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +from matplotlib import pyplot as plt
Убрал https://github.com/nccr-itmo/FEDOT/pull/493/commits/ed6119d2c31f5ef19b80427167535b23cdfcde17

2021-11-17 10:40 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.degree = params.get('degree')
Переделал логику слегка https://github.com/nccr-itmo/FEDOT/pull/493/commits/ed6119d2c31f5ef19b80427167535b23cdfcde17

2021-11-17 10:40 UTC, valer1435 commented on examples/time_series/polyfit_example.py
> +                                                          test_data_features=train_data)
https://github.com/nccr-itmo/FEDOT/pull/493/commits/ed6119d2c31f5ef19b80427167535b23cdfcde17 переделал через data_setup

2021-11-17 10:41 UTC, valer1435 commented on test/unit/models/test_repository.py
> +        assert len(model_names) == 11
https://github.com/nccr-itmo/FEDOT/pull/493/commits/ed6119d2c31f5ef19b80427167535b23cdfcde17 поменял условия проверки

2021-11-17 11:04 UTC, Dreamlone approved these changes

2021-11-17 11:12 UTC, valer1435 commented on examples/decompose/refinement_forecast_example.py
> +
Оставил как аналогию к исходному decompose. Чтобы можно было в случае чего показать пример с polyfit_decompose

2021-11-17 13:04 UTC, nicl-nno commented on test/unit/models/test_repository.py
> +        assert len(model_names) == 11
Тут бы сравнивать не только 0, но и с полным числом операций (чтобы проверить что фильтр работает).

![image](https://user-images.githubusercontent.com/5711814/142205807-f34c029b-e6b8-4bb0-9481-f6ae026578de.png)

2021-11-17 13:04 UTC, nicl-nno approved these changes

2021-11-17 13:34 UTC, merged