Exp smoothing implementation
nccr-itmo/FEDOT pull request #501
Opened 2021-11-19 10:12 UTC by valer1435

Implementation of exponential smoothing model from statsmodels.

2021-11-19 10:56 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'error': (hp.choice, ['add', 'mul']),
Вроде при hp.choice нужно аргументы ещё раз завернуть в список `[['add', 'mul']]`

2021-11-19 15:10 UTC, Dreamlone requested changes

2021-11-19 15:10 UTC, Dreamlone commented on examples/time_series/statsmodels_example.py
> +    return Pipeline(node_ridge1)
Первое предложение - назвать файл немного по другому. Например `exponential_smoothing_example` или что-то того. 

Также, стоит обкатать новую операцию отдельно не вместе с ridge. Например, если сделать пайплайн `Pipeline(PrimaryNode('ets'))`, то прогноз получается вот таким: 
![image](https://user-images.githubusercontent.com/52418437/142644031-4bc23cdc-8512-4a9a-9a29-b6088bcb46ea.png)

2021-11-19 15:10 UTC, Dreamlone commented on examples/time_series/statsmodels_example.py
> +    :param len_forecast: forecast length
Описание не для этого примера. Также может вынести весь этот код ниже в отдельную функцию вне этого примера и использовать не только тут, но и в других примерах с временными рядами. 
А то мне кажется в time series examples очень много кода так дублируется. Хотя по сути меняется только функция-генератор пайплайна

2021-11-19 15:10 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return
Лучше просто pass

2021-11-19 15:10 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        input_data = copy(input_data)
Так вот же тут fit метод у модели. Может его и вынести в метод fit у имплементации?

2021-11-21 18:57 UTC, nicl-nno commented
Заметил в мастере лишний файл, удали плз в этом же PR
https://github.com/nccr-itmo/FEDOT/blob/master/fedot/api/api_utils/presets.py~

2021-12-03 12:39 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        input_data = copy(input_data)
Да, разобрался по-подробнее. Метод фит оптимизирует параметры сглаживания. [Вынес в fit](https://github.com/nccr-itmo/FEDOT/pull/501/commits/5ebde6e4fdddd3470cb779f0b4864e08f697b0d0#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R252-R261)

2021-12-03 12:39 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return
См Ниже

2021-12-03 12:41 UTC, valer1435 commented on examples/time_series/statsmodels_example.py
> +    :param len_forecast: forecast length
[Изменил описание](https://github.com/nccr-itmo/FEDOT/pull/501/commits/7bd3dca35c3c9b6150d7593dc58b45c5cf0412cb#diff-946d2dcf7a3741081dd2cc9bfc12e5ac43539942bb45c333e47df5a27da12aa8R41-R46)

2021-12-03 12:42 UTC, valer1435 commented on examples/time_series/statsmodels_example.py
> +    return Pipeline(node_ridge1)
[Добавил тюнер](https://github.com/nccr-itmo/FEDOT/pull/501/commits/7bd3dca35c3c9b6150d7593dc58b45c5cf0412cb#diff-946d2dcf7a3741081dd2cc9bfc12e5ac43539942bb45c333e47df5a27da12aa8R79-R85). Теперь такого плохого результата быть не должно)

2021-12-03 12:43 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +                'error': (hp.choice, ['add', 'mul']),
[Завернул](https://github.com/nccr-itmo/FEDOT/pull/501/commits/7bd3dca35c3c9b6150d7593dc58b45c5cf0412cb#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7R131-R134)

2021-12-03 13:24 UTC, Dreamlone requested changes

2021-12-03 13:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            input_copy.idx = np.arange(cut_len, input_values.shape[0])
Может это не в этом PR сделать. Но просто мысль есть такая: может сделать 'cut'-операцию способную обрабатывать как одномерные массивы (временные ряды), так и таблицы. Чтобы корректными были бы и пайплайн `cut -> lagged -> ridge`, и пайплайн `lagged -> cut -> ridge`
Так композеру будет проще такую операцию вставлять в ходе эволюции

2021-12-03 13:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +
Криво ребейзнулось, ts_implementations.py в мастере нет

2021-12-03 13:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    def __init__(self, log: Log = None, **params):
Перенеси в statsmodels имплементации

2021-12-03 13:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def __init__(self, log: Log = None, **params):
А какой из двух вариантов итоговый?

2021-12-03 13:24 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +            },
Значение может быть вещественным, или всегда должно быть int?

2021-12-03 17:32 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +            },
Перевожу насильно в int

2021-12-03 17:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    def __init__(self, log: Log = None, **params):
Странно, должна быть

2021-12-03 17:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def __init__(self, log: Log = None, **params):
[Тот, который не удален](https://github.com/nccr-itmo/FEDOT/pull/501/commits/302b80f46ecbe91ddff1a0cca2b1b3142d60fa3a)

2021-12-03 17:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +
[Удалил](https://github.com/nccr-itmo/FEDOT/pull/501/commits/302b80f46ecbe91ddff1a0cca2b1b3142d60fa3a)

2021-12-03 17:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            input_copy.idx = np.arange(cut_len, input_values.shape[0])
В другом PR тогда лучше

2021-12-04 17:00 UTC, Dreamlone requested changes

2021-12-04 18:38 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            end_id = old_idx[-1]
Все ок, так как индексы на уровне InputData конвертируются в числа
![image](https://user-images.githubusercontent.com/32017472/144720832-20b51d0e-2627-4872-b6ea-2bc9d1e8d23d.png)

2021-12-04 18:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def __init__(self, log: Log = None, **params):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/501/commits/bfcf14653c950d072e3ada5f17492a1b39537f5a#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R242-R243)

2021-12-04 18:48 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        self.model = self.model.fit(disp=False)
[Возвращаю](https://github.com/nccr-itmo/FEDOT/pull/501/commits/bfcf14653c950d072e3ada5f17492a1b39537f5a#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R263)

2021-12-04 20:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def __init__(self, log: Log = None, **params):
Я имел в виду несколько более развернутое описание, но ок, пойдёт)

2021-12-04 20:50 UTC, Dreamlone commented
В пресет ts стоит добавить все новореализованные операции, а именно сглаживание, polyfit, а также glm
Вот [сюда](https://github.com/nccr-itmo/FEDOT/blob/exp_smoothing_implementation/fedot/api/api_utils/presets.py#L65)

2021-12-06 19:13 UTC, Dreamlone approved these changes

2021-12-07 19:10 UTC, merged