GLM implementation for time series
nccr-itmo/FEDOT pull request #503
Opened 2021-11-21 13:53 UTC by valer1435

GLM model from statsmodels was implemented. It could be useful in pipeline composition for detrending.

2021-11-21 13:53 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`test/unit/data_operations/test_data_operations_implementations.py`](https://github.com/nccr-itmo/FEDOT/blob/629dd6c127120e92b49625de6560e98c5f9590a9/test/unit/data_operations/test_data_operations_implementations.py):

> [Line 356:1](https://github.com/nccr-itmo/FEDOT/blob/629dd6c127120e92b49625de6560e98c5f9590a9/test/unit/data_operations/test_data_operations_implementations.py#L356): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`test/unit/data_operations/test_time_series_operations.py`](https://github.com/nccr-itmo/FEDOT/blob/629dd6c127120e92b49625de6560e98c5f9590a9/test/unit/data_operations/test_time_series_operations.py):

> [Line 83:41](https://github.com/nccr-itmo/FEDOT/blob/629dd6c127120e92b49625de6560e98c5f9590a9/test/unit/data_operations/test_time_series_operations.py#L83): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 84:41](https://github.com/nccr-itmo/FEDOT/blob/629dd6c127120e92b49625de6560e98c5f9590a9/test/unit/data_operations/test_time_series_operations.py#L84): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2021-11-21 14:29 UTC, Dreamlone requested changes

2021-11-21 14:29 UTC, Dreamlone commented on examples/time_series/statsmodels_example.py
> +                            target=time_series,
Про дублирование кода уже писал в другом [PR](https://github.com/nccr-itmo/FEDOT/pull/501), здесь можно пока эту задачу не решать, а заняться этим уже в том PR. Просто чтобы не забылось 

Заодно стоит фалу другое название дать

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +def ts_to_lag(idx, time_series: np.array, window_size: int):
Поскольку метод практически полностью повторяет код из ts_to_table функции за исключением последней строки, то стоит поступить так. В ts_to_table добавить аргумент (True или False), нужно ли обрезать последние n элементов или нет. А ts_to_lag просто убрать

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        "tweedie": Tweedie()
А внутри всех этих Binomial, Gaussian и так далее есть какие-нибудь гиперпараметры, которые имеет смысл настраивать?

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            exog=sm.add_constant(input_data.idx.astype("float64")).reshape(-1, 2),
У Коли @nicl-nno в [этом PR](https://github.com/nccr-itmo/FEDOT/pull/433) индексы могут задаваться как строки (например '2020-01-01', такой аналог datetime), просто на всякий случай - с этим местом в будущем могут возникнуть проблемы. Добавь тогда сюда TODO плез. Пока менять ничего не нжно

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return self.params
А у GLM точно нормально переваривается вызов свойства params?

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'family': (hp.choice, ["binomial",
Надо обернуть ещё в лист вроде бы, см. как выше в hp.choice сделано

2021-11-21 14:29 UTC, Dreamlone commented on fedot/core/repository/data/model_repository.json
> +        "lagged"
Lagged - значит, требуется lagged преобразование?

2021-11-21 14:29 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +    input_data = generate_simple_series()
Стоит добавить описание что и как тут проверяется

2021-11-21 16:15 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        "tweedie": Tweedie()
Да, что-то я проглядел, поподробнее поизучаю тогда

2021-11-21 16:16 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return self.params
Пока было все ок. Почему возникли подозрения?

2021-11-21 21:17 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return self.params
Ну просто метод get_params это скорее интерфейс к sklearnэским моделям. Для других бтблиотек он может заметно отличаться, вот например PyCharm мне подсказывает, что у Binomial нет такого метода/свойства как get_params или просто params (с GLM так же)
![image](https://user-images.githubusercontent.com/52418437/142779198-465ef077-0a55-4605-8264-22250a2d09d6.png)

2021-11-23 18:05 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return self.params
Здесь, насколько я понимаю - берутся параметры федотовской обертки, так что все должно быть ок. Так же работает  метод и у Аримы

2021-11-23 19:48 UTC, valer1435 commented on test/unit/data_operations/test_data_operations_implementations.py
> +    input_data = generate_simple_series()
Добавил описание https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:49 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +        "lagged"
Наоборот) Поправил https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:49 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +                'family': (hp.choice, ["binomial",
Обернул в лист https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:49 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            exog=sm.add_constant(input_data.idx.astype("float64")).reshape(-1, 2),
Добавил TODO https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:50 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +def ts_to_lag(idx, time_series: np.array, window_size: int):
Оставил только ts_to_table https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:50 UTC, valer1435 commented on examples/time_series/statsmodels_example.py
> +                            target=time_series,
Переименовал https://github.com/nccr-itmo/FEDOT/pull/503/commits/2f90787b86da2e1e498f67dbe050d426e6bfc114

2021-11-23 19:51 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        "tweedie": Tweedie()
Добавил параметр функции-связки для семейств распределений https://github.com/nccr-itmo/FEDOT/pull/503/commits/c4920a583e12628104fd9f01e9421e4fa22e8f77

2021-11-24 07:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +>>>>>>> 2f90787 (fixes)
Осталось после ребейза

2021-11-24 07:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +            exog=sm.add_constant(input_data.idx.astype("float64")).reshape(-1, 2),
Поскольку изменения влились в мастер, то теперь можно начинать править историю с индексами

2021-11-24 07:48 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        return self.params
А ну да, логично, сорян

2021-11-24 08:11 UTC, Dreamlone requested changes

2021-11-24 08:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                f"link {GLMImplementation.default_links.get(self.family)}")
Давай лучше одинарные кавычки

2021-11-24 08:11 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                                      "log"]]
Правильно я понимаю, что есть невалидные сочетания например `binomial - identity` и `gamma - inverse_squared`? (Просто судя по документации
[`The link functions currently implemented are the following. Not all link functions are available for each distribution family. The list of available link functions can be obtained by`](statsmodels.org/stable/glm.html#link-functions) это так)

Просто в таком случае можно попытаться реализовать древовидную структуру параметров в hyperopt. См. пример [тут](https://github.com/hyperopt/hyperopt/wiki/FMin#22-a-search-space-example-scikit-learn). Не исключаю, что в нашем случае это будет очень муторно, поэтому если не пойдёт, то можно будет отказаться от такой "модификации"

2021-11-24 08:11 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +    # and indexes like [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Вот эту штуку можно в docstring

2021-11-24 17:52 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +                                      "log"]]
Да, есть невалидные. Борюсь через try-except и выставлением дефолтных параметров

2021-11-24 18:22 UTC, valer1435 commented on test/unit/data_operations/test_data_operations_implementations.py
> +    # and indexes like [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
Убрал в docstring https://github.com/nccr-itmo/FEDOT/pull/503/commits/ce27233ca8dfe50c64453c9cb29779b40ec2cbfe

2021-11-24 18:22 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                f"link {GLMImplementation.default_links.get(self.family)}")
Поставил одинарные кавычки https://github.com/nccr-itmo/FEDOT/pull/503/commits/ce27233ca8dfe50c64453c9cb29779b40ec2cbfe

2021-11-24 18:23 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        self.link = self.params.get('link')
Переделал в конструкторе https://github.com/nccr-itmo/FEDOT/pull/503/commits/ce27233ca8dfe50c64453c9cb29779b40ec2cbfe

2021-11-24 18:24 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    family_dict = {
Первый словарь - словарь для семейств распределений
Второй словарь - отображение текст->класс
Третий словарь - дефолтная связка для каждого семейства

2021-11-24 18:25 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +>>>>>>> 2f90787 (fixes)
Убрал https://github.com/nccr-itmo/FEDOT/pull/503/commits/ce27233ca8dfe50c64453c9cb29779b40ec2cbfe

2021-11-25 07:58 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +>>>>>>> 2f90787 (fixes)
FYI, можно ссылки давать не на конкретные коммиты (в котором у тебя довольно много изменений), а на измененные строки. Нужно их выделить пробежавшись курсором вот так
![image](https://user-images.githubusercontent.com/52418437/143401744-7f19a419-b7da-41a1-8702-e7620d1ca9ed.png)
Ссылка тогда будет выглядеть вот [так](https://github.com/nccr-itmo/FEDOT/commit/ce27233ca8dfe50c64453c9cb29779b40ec2cbfe#diff-1a84e56753fbb3eac797a9881c826baf94064215f64b50c76237fa8d845f7d07R709-R710)

2021-11-25 08:02 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                                      "log"]]
Так я и предлагаю сразу сделать адекватное пространство поиска, а не ломать процесс тюнинга исправлением на дефолтные значения

2021-11-25 08:53 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    family_dict = {
Мой вариант: 
```
family_distribution = {
        "gaussian": {'distribution': Gaussian,
                     'default_link': identity(),
                     'available_links': {}},
        "gamma": {'distribution': Gamma,
                  'default_link': inverse_power(),
                  'available_links': {}},
        "inverse_gaussian": {'distribution': InverseGaussian,
                             'default_link': inverse_squared(),
                             'available_links': {}},
        "poisson": {'distribution': Poisson,
                    'default_link': lg(),
                    'available_links': {}},
        "tweedie": {'distribution': Tweedie,
                    'default_link': lg(),
                    'available_links': {}}
    }

```

Вместо 
```
family_distribution = {
        "gaussian": Gaussian,
        "gamma": Gamma,
        "inverse_gaussian": InverseGaussian,
        "poisson": Poisson,
        "tweedie": Tweedie
    }

  links_function = {"log": lg(),
                    "identity": identity(),
                    "sqrt": sqrt(),
                    "inverse_power": inverse_power(),
                    "inverse_squared": inverse_squared(),
                    "power": Power()
                    }

  default_link_function = {
      "gaussian": "identity",
      "gamma": "inverse_power",
      "inverse_gaussian": "inverse_squared",
      "poisson": "log",
      "tweedie": "log"
  }
```

Всё умещается в одной переменной-словаре. Также в поле `available_links` тогда можешь хранить перечень подходящих функций для данного распределения в виде списка, или также в виде словаря.  Не плодишь сущности таким образом. Сможешь так сделать? Или есть какие-то принципиальные проблемы с такой реализацией?

Для удобочитаемости можно разбить на два словаря

2021-11-26 09:09 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    family_dict = {
[Исправил](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py)

2021-11-26 09:12 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +    family_dict = {
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/503/commits/f4e961e3945f8d6c2fdc5cb4c0b810226b2f97e4#diff-1a84e56753fbb3eac797a9881c826baf94064215f64b50c76237fa8d845f7d07R673-R708)

2021-11-26 09:15 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +                                      "log"]]
Пришлось доставать костыли, но удалось реализовать [ts_implementation](https://github.com/nccr-itmo/FEDOT/pull/503/commits/f4e961e3945f8d6c2fdc5cb4c0b810226b2f97e4#diff-1a84e56753fbb3eac797a9881c826baf94064215f64b50c76237fa8d845f7d07R715-R752)

[search_space](https://github.com/nccr-itmo/FEDOT/pull/503/commits/f4e961e3945f8d6c2fdc5cb4c0b810226b2f97e4#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7R130-R161)

2021-11-26 10:11 UTC, Dreamlone requested changes
Файлы вида "test/data/remote/fitted_pipeline/fitted_operations/operation_0.pkl" затесались в PR, нужно удалить

2021-11-26 10:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                f"Invalid family. Changed to gefault value")
Тяжелая конструкция. Стоит вынести в отдельный метод и подумать над тем, как упростить. Начать можно с того, чтобы писать не `GLMImplementation.family_distribution[family]['available_links']`, а `self.family_distribution[family]['available_links']`. Плюс обрати внимание что тебе это срока возвращает (а возвращает она словарь)

Плюс заодно объявлять о том, что входные параметры были изменены. Как ты это делал для polyfit недавно

2021-11-26 10:11 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +
Этот импорт надо вынести повыше

2021-11-26 10:11 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +        if is_fit_pipeline_stage:
Стоит добавить docstring. Плюс мб поменять название. Тут же вроде не абстрактный "ts preprocessing" происходит, а именно манипуляции с индексами

2021-11-26 10:11 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +        if isinstance(data, InputData):
Поскольку ты тут забираешься в препроцессинг (ну конкретно в этом месте ты просто функцию в метод превратил, но не суть), то возможно стоит перебазироваться на ветку [penn-check](https://github.com/nccr-itmo/FEDOT/tree/penn-check).  Там довольно заметно поменялся препроцессинг. Несмотря на то, что PR с этой веткой "in progress". Основные изменения там уже внесены, и скорее всего ничего кардинально я там менять не буду. По крайне мере в интерфейсе препроцессинга 

Призываю Колю @nicl-nno проконсультировать стоит ли так делать

2021-11-26 10:25 UTC, Dreamlone requested changes

2021-11-26 10:25 UTC, Dreamlone commented on test/data/remote/fitted_pipeline/fitted_pipeline.json
> +	"descriptive_id": "((/n_simple_imputation_default_params;)/n_lagged_{'window_size': 10};)/n_ridge_default_params"
Лишний файл, удоли

2021-11-26 10:25 UTC, Dreamlone commented on test/unit/data_operations/test_data_operations_implementations.py
> +                    features=y,
Мне кажется лучше тестировать либо только вариант когда idx тут строковые, либо оба варианта (когда строковые и когда заданы целыми числами)

2021-11-26 10:25 UTC, Dreamlone commented on test/unit/models/test_model.py
> +    train_data, test_data = get_ts_data_with_dt_idx(forecast_length=5)
Добавь сюда описание плиз. Я например не сразу въехал чем этот тест отличается от того, что чуть повыше

2021-11-26 11:52 UTC, valer1435 commented on examples/time_series/glm_example.py
> +    return Pipeline(node_ridge1)
Хочу это сделать в отдельно pr по переработке примеров

2021-11-26 11:59 UTC, Dreamlone commented on examples/time_series/glm_example.py
> +    return Pipeline(node_ridge1)
Оке, но тут точно стоит сделать такой пример, чтобы 1) самому убедиться, что новореализованный способ задачи гиперпараметров работает корректно и 2) я сам тоже всё проверю

2021-11-27 18:03 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +        if isinstance(data, InputData):
Переделал под новую логику https://github.com/nccr-itmo/FEDOT/pull/503/commits/9df00382de6e9af9de49b966a9c676f4f40aad5b Тут в общем-то сложно выделить отдельные строки

2021-11-27 18:12 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +                f"Invalid family. Changed to gefault value")
Выделил в отдельную функцию https://github.com/nccr-itmo/FEDOT/pull/503/commits/57a297b836ac0ac5d29b19031dec1ae5f0ea52fb#diff-1a84e56753fbb3eac797a9881c826baf94064215f64b50c76237fa8d845f7d07R786-R813

2021-11-27 18:19 UTC, valer1435 commented on examples/time_series/glm_example.py
> +    print(f'MAE before tuning - {mae_before:.4f}\n')
[Тюнинг](https://github.com/nccr-itmo/FEDOT/pull/503/commits/50537860a42c2f618a66c81f5473e7de1236ff72#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R67-R85)

2021-11-27 18:20 UTC, valer1435 commented on examples/time_series/glm_example.py
> +    :param degree: degree of polynomial function
[Без degree](https://github.com/nccr-itmo/FEDOT/pull/503/commits/50537860a42c2f618a66c81f5473e7de1236ff72#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R35-R36)

2021-11-27 18:20 UTC, valer1435 commented on examples/time_series/glm_example.py
> +    return Pipeline(node_ridge1)
[Добавил такую возможность](https://github.com/nccr-itmo/FEDOT/pull/503/commits/50537860a42c2f618a66c81f5473e7de1236ff72#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R35-R36)

2021-11-27 18:21 UTC, valer1435 commented on examples/time_series/polyfit_example.py
> +    idx = pd.to_datetime(time_series.iloc[:, -2].values)
[Переработал индексы](https://github.com/nccr-itmo/FEDOT/pull/503/commits/50537860a42c2f618a66c81f5473e7de1236ff72#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R35-R36)

2021-11-27 18:21 UTC, valer1435 commented on examples/time_series/polyfit_example.py
> +    time_series = time_series.iloc[:, -1].values
[Переработал индексы](https://github.com/nccr-itmo/FEDOT/pull/503/commits/50537860a42c2f618a66c81f5473e7de1236ff72#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R35-R36)

2021-11-27 18:24 UTC, valer1435 commented on fedot/core/data/supplementary_data.py
> +    non_int_idx = None
[Поставил](https://github.com/nccr-itmo/FEDOT/pull/503/commits/af7c4c8ddc130ae56289bde9317b1931734e6252#diff-6ccd62dc0288800c6867ef58fb3a0569cfb9817d3fd568d5b1928d172740e4c0R27)

2021-11-27 18:26 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +
[Импорт](https://github.com/nccr-itmo/FEDOT/pull/503/commits/af7c4c8ddc130ae56289bde9317b1931734e6252#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR26-R27) оказался ненужным)

2021-11-27 18:27 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +        if is_fit_pipeline_stage:
[Теперь это разнесено по функциям](https://github.com/nccr-itmo/FEDOT/pull/503/commits/af7c4c8ddc130ae56289bde9317b1931734e6252#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR349)

2021-11-27 18:29 UTC, valer1435 commented on test/unit/data_operations/test_data_operations_implementations.py
> +                    features=y,
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/503/commits/af7c4c8ddc130ae56289bde9317b1931734e6252#diff-d3983733e21871bc68767e85d23eb2788296d1855b89644063933f32035dc400R413-R420) новый тест

2021-11-27 18:32 UTC, valer1435 commented on test/unit/models/test_model.py
> +    train_data, test_data = get_ts_data_with_dt_idx(forecast_length=5)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/503/commits/af7c4c8ddc130ae56289bde9317b1931734e6252#diff-d3983733e21871bc68767e85d23eb2788296d1855b89644063933f32035dc400R413-R420) описание

2021-11-27 18:36 UTC, valer1435 commented on test/data/remote/fitted_pipeline/fitted_pipeline.json
> +	"descriptive_id": "((/n_simple_imputation_default_params;)/n_lagged_{'window_size': 10};)/n_ridge_default_params"
https://github.com/nccr-itmo/FEDOT/pull/503/commits/acda4708c622c382ac8a8f3732dca5b7d51ea934

2021-11-27 18:57 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations.py
> +        "gaussian": {'distribution': Gaussian,
[Разнес](https://github.com/nccr-itmo/FEDOT/pull/503/commits/825ab67ca22a2fdda27e402676b6c304101b653f)

2021-11-29 08:56 UTC, Dreamlone commented on examples/time_series/glm_example.py
> +                                            validation_blocks=1)
Сейчас не так важно, но на будущее: 
1) Лучше не использовать PipelineTuner, а вызывать метод fine_tune_all_nodes у Pipeline, это полностью эквивалентно тому, что вызывается здесь, но требует меньше кода
2) cv_folds и validation_blocks равные одному - это какое-то очень странное значение для этих параметров. Уж лучше тогда cv_folds = None поставить, ровно как и не задавать ничего в validation_blocks

2021-11-29 09:34 UTC, Dreamlone requested changes

2021-11-29 09:34 UTC, Dreamlone commented on fedot/core/data/data.py
> +        )
Лучше упростить

2021-11-29 09:34 UTC, Dreamlone commented on fedot/core/data/data.py
> +                    or isinstance(copied_data.idx[0], np.datetime64):
Лучше эти два условия записать в переменные повыше, так не придётся использовать перенос строки

2021-11-29 09:34 UTC, Dreamlone commented on fedot/core/data/data.py
> +                                  copied_data.supplementary_data.non_int_idx[-2]
Тяжеловато смотрится. Стоит вынести штуки вроде copied_data.supplementary_data.non_int_idx[-1] в отдельные переменные с говорящими названиями, тогда должно стать понятней. Стоит добавить на эту функцию тесты и ещё docstring не помешает.

2021-11-29 09:34 UTC, Dreamlone commented on fedot/core/data/supplementary_data.py
> +    non_int_idx: bool = None
А, сорри, я видимо на прошлой итерации не совсем вник в то, что должно сюда помещаться. Лучше спрошу, что планируется в этом месте хранить: флаг того, какие индексы, или сами нецелочисленные индексы? Просто судя по коду, сюда записываются именно что список с индексами.

2021-11-29 09:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +from typing import Optional
По поводу нейминга модулей. Предлагаю немного переиграть. 
Сейчас `math_operations` - сделать `poly`. Там же ведь только poyfit и есть
Сейчас `statsmodels` - сделать `glm`. Ведь там же нет ничего кроме GLMImplementation. Если будем расширять этот модуль, то переименуем.

2021-11-29 09:34 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_tuning.py
> +                                                        loss_function=mse)
Тут лучше вызывать метод `fine_tune_all_nodes`. Ну и тест на самом деле ничего особо то не проверяет, кроме того факта, что "тюнер не падает с ошибками".
Предлагаю переработать тест следующим образом: 
1) Этот модифицировать этот тест так, чтобы действия в нем производимые соответствовали названию, а именно, проверялось бы, что при обращению к методу например get_operation_parameter_range в SearchSpace возвращался адекватный Output
2) Написать новый, в котором будет тестироваться что после тюнинга при обращении к узлу пайплайна будут возвращены корректные значения словаря custom_params. 

Также обратил внимание., что что-то идёт не так при тюнинге, смотри какие custom_params получаются: 
![image](https://user-images.githubusercontent.com/52418437/143841793-d51f5d01-50dc-42e1-9f14-561e3004bfdf.png)
![image](https://user-images.githubusercontent.com/52418437/143841872-e3bc6cd4-eb98-4790-90de-d60d7ab51fe1.png)
![image](https://user-images.githubusercontent.com/52418437/143842004-67023ada-52c4-42d4-8c89-e115af2d6bfe.png)
![image](https://user-images.githubusercontent.com/52418437/143842107-e75b5dca-2bd2-4366-b709-7e1b190ea7ba.png)
Странности тут такие: поле `hp_opt` появилось в словаре, хотя быть его там не должно по идее. Все равно при инициализации имплементации оно игнорируется, берутся только значения по заранее известным имплементации ключам. Вторая странность, похоже поля `family` и `link` все таки меняются по сравнению с начальной конфигурацией, зато вот в дальнейшем они никак не модифицируются - похоже выставляются дефолтными

2021-11-29 09:34 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    elements
Тут ведь вроде самое главное в описании должно быть, что индексы тут какие-то особенные, а не то, что это временной ряд)

2021-11-29 09:34 UTC, Dreamlone commented on test/unit/tasks/test_forecasting.py
> +    elements
Тут тоже про индексы добавить стоит

2021-11-29 12:23 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +from typing import Optional
Туда уже в следующих pr пойдут exp_smoothing и фильтр Саши-Хватова

2021-11-29 13:05 UTC, valer1435 commented on examples/time_series/glm_example.py
> +                                            validation_blocks=1)
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-38fd582ccef725e05d3f2cabb12cad4ba0c070b4d5a737d0a684c9d39ccb4fd7R69) на fine_tune_all_nodes

2021-11-29 13:06 UTC, valer1435 commented on fedot/core/data/data.py
> +        )
[Разнес по методам](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR320-R323)

2021-11-29 13:06 UTC, valer1435 commented on fedot/core/data/data.py
> +                    or isinstance(copied_data.idx[0], np.datetime64):
[Записал](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR290-R291)

2021-11-29 13:08 UTC, valer1435 commented on fedot/core/data/data.py
> +                                  copied_data.supplementary_data.non_int_idx[-2]
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-b291766c2a3592f30a1fc3200e87a98ac8dc24283eca5a5cb00c0feedb40052eR297-R302). + разнес по методам fit и predict

2021-11-29 13:13 UTC, valer1435 commented on fedot/core/data/supplementary_data.py
> +    non_int_idx: bool = None
[Поменял на list](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-6ccd62dc0288800c6867ef58fb3a0569cfb9817d3fd568d5b1928d172740e4c0R27)

2021-11-29 13:16 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    elements
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/503/commits/354e373b04feda797e2ae1137e38ade4723b91fe#diff-6d41b63f94e61d0658f76ccecf8d4c053f40c46a52e168b51bc112381926e0bdR57)

2021-11-29 13:16 UTC, valer1435 commented on test/unit/tasks/test_forecasting.py
> +    elements
Оказалось 2 одинаковых функции. Эту удалил

2021-11-29 14:35 UTC, Dreamlone commented on fedot/core/data/supplementary_data.py
> +    non_int_idx: bool = None
Погоди менять) 
Ответь сначала, что ты планируешь в этом поле хранить?

2021-11-29 14:36 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +from typing import Optional
Окс, убедил

2021-11-29 14:45 UTC, valer1435 commented on fedot/core/data/supplementary_data.py
> +    non_int_idx: bool = None
List с datetime индексами, если они есть

2021-11-29 14:48 UTC, Dreamlone commented on fedot/core/data/supplementary_data.py
> +    non_int_idx: bool = None
Хорошо, давай теперь по порядку. Это всегда list, или не всегда. Именно ли список ты там хранишь, а не numpy array? 
И раз это все таки массив, то описание стоит обновить в комментарии над ним (меня коммент кстати в первую очередь с толку сбил). На вопрос `Is time series has datetime index` ответ будет же True или False, но не массив со значениями

2021-12-01 07:52 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +from typing import Optional
Отпишись тогда сюда как  "math_operations" переименуешь. Заодно в "ts_implementations" стоит добавить файл `__init__.py`. По идее он автоматически должен генерироваться, если ты добавляешь папку в PyCharm как "Python Package"

2021-12-01 12:18 UTC, Dreamlone commented on fedot/core/data/data.py
> +                                  copied_data.supplementary_data.non_int_idx[-2]
Docstring по прежнему нет и тестов нет

2021-12-01 13:13 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +from typing import Optional
Переименовал 
https://github.com/nccr-itmo/FEDOT/pull/503/commits/7cc4bd2d1422759048fe7c55d0f904ec621bf431

2021-12-01 15:20 UTC, valer1435 commented on fedot/core/data/data.py
> +                                  copied_data.supplementary_data.non_int_idx[-2]
[Добавил тесты и docstring](https://github.com/nccr-itmo/FEDOT/pull/503/commits/426681b8b55c909839458fe73e59edf87f3150ec#diff-4602cf94a48a1a4368f5381c313e669ac313880a68d3769ce97a7235021f6bdcR215-R243)

2021-12-02 08:21 UTC, Dreamlone requested changes

2021-12-02 08:21 UTC, Dreamlone commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Все идёт сплошной стеной - смотрится тяжеловато. Мб стоит добавить комментариев. И docstring не сообщает о том, почему в тесте, который "должен тестировать, что индексы конвертируются корректно" появляется в какой-то момент пайплайн с glm. Стоит добавить, что в glm используются целочисленные индексы, и чтобы она обучилась корректно, требуется, чтобы хорошо проходила конвертация индексов

2021-12-02 08:26 UTC, valer1435 commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Здесь пайплайн нужен для того, чтобы он хранил свой последний train индекс

2021-12-02 08:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            self.params_changed = True
Есть идея эту штуку вставить на пару уровней повыше, а именно в Node. Чтобы сразу можно было применять `nested space` для всех операций без внесения модификаций на уровне имплементаций. 
Вставить эту замену можно в setter custom_params.

2021-12-02 08:30 UTC, Dreamlone commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Да, я это понимаю) 
И ты понимаешь. Но может не сообразить, наш коллега который увидит этот тест, который опять же "должен тестировать, что индексы конвертируются корректно" зачем то использует Pipeline для тестирования функции конвертации. Поэтому и нужно добавить описание

2021-12-02 08:35 UTC, Dreamlone commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Кстати этот тест не совсем unit. То есть его можно (и стоит, я считаю) оставить, но перенести в \test\unit\models\test_model.py. И тестировать там, чтобы "GLM корректно обучалась на int и не-int индексах" .И название с описанием поменять соответственно.

А в test/unit/data/test_data.py всё таки нужен другой тест. Проверяй именно `convert_non_int_indexes_for_predict` и `convert_non_int_indexes_for_fit` методы. То есть тестировать их нужно не опосредованно через вызов pipeline.fit(), а прямо в unit тесте. Подал на вход последовательность индексов - получил output, проверил его на корректность и так далее

2021-12-02 17:07 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            self.params_changed = True
[Перенес](https://github.com/nccr-itmo/FEDOT/pull/503/commits/b95b4de35fd3f98d3119e5cf11b42f4fdb0a2ca7?authenticity_token=VGMtF%2B3OWDxXetQu1WHbwFIxHuCXTAy7ixsxIZyDC4Sew43bS8ysWSt%2B4cOF%2Fr4Qakx6jLOrRsWHNLJdNArWQA%3D%3D&file-filters%5B%5D=.json&file-filters%5B%5D=.py&hide-deleted-files=true#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR196-R198)

2021-12-02 17:11 UTC, valer1435 commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Glm тестируется отдельно со всеми. Не знал как сделать по-другому, но [сделал](https://github.com/nccr-itmo/FEDOT/pull/503/commits/b95b4de35fd3f98d3119e5cf11b42f4fdb0a2ca7?authenticity_token=VGMtF%2B3OWDxXetQu1WHbwFIxHuCXTAy7ixsxIZyDC4Sew43bS8ysWSt%2B4cOF%2Fr4Qakx6jLOrRsWHNLJdNArWQA%3D%3D&file-filters%5B%5D=.py&hide-deleted-files=true#diff-4602cf94a48a1a4368f5381c313e669ac313880a68d3769ce97a7235021f6bdcR215-R261)

2021-12-02 17:19 UTC, Dreamlone commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
Вот типо такого, только стоит разнести тесты по разным местам. В одних будет только тестироваться конвертация. В других, только пайплайн с glm

2021-12-02 17:42 UTC, valer1435 commented on test/unit/data/test_data.py
> +    assert np.all(predicted_test.supplementary_data.non_int_idx[0] == len(train_data.idx))
[Не знаю, это ли ты имел в виду](https://github.com/nccr-itmo/FEDOT/pull/503/commits/6060fb253723bd9567e41fd83941ca7a875ea231#diff-1cafb1c54b4ad34680bcf45f9926d3f7e34990e57caf865c4968212d6895f069R214-R252) Перенес тесты на glm, которые уже были в test_model

2021-12-03 08:08 UTC, Dreamlone requested changes
Нужно в preset 'ts_tun' / 'ts' добавить операции 'polyfit' и 'glm'

2021-12-03 08:08 UTC, Dreamlone commented on test/unit/data/test_data.py
> +    assert np.all(test_data.supplementary_data.non_int_idx == old_test_data_idx)
По тестам: 

1) Вот эти (`test_data_convert_string_indexes_correct`, `test_data_convert_dt_indexes_correct`) разнести в разные места. Не надо все тестировать в одном тесте. Вроде ты с GLM сделал тесты. Так что надо просто эти подчистить

2) Не уверен, что это важно. Просто docstring у нас обычно с пробелами """ Test to check """, а не """Test to check""". Но это мелочи

3) Раз есть test_ts_models_dt_idx_fit_correct в котором и так есть GLM, то мне кажется test_glm_fit_correct_with_dt_indexes не очень нужен. 

4) В тесте не совсем то тестируется. Проверяется наличие поля 'family' в словаре GLM, а он там есть всегда. Надо бы проверять, что для выбранного family_distribution'а HP оптимизатор предлагает правильный link (список из таковых)

2021-12-03 09:26 UTC, Dreamlone approved these changes

2021-12-03 10:04 UTC, nicl-nno approved these changes
Вроде норм.

Можно перезапустить тесты на наборе бенчмарков, чтобы оценить, стали ли новые модели отбираться в лучших пайплайнах.

2021-12-03 10:37 UTC, merged