Hotfix for FEDOT.Web integration
nccr-itmo/FEDOT pull request #505
Opened 2021-11-23 20:23 UTC by nicl-nno

- idx list->numpy
- 'resample' temporary disabled

2021-11-27 09:47 UTC, Dreamlone requested changes

2021-11-27 09:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        old_idx = np.asarray(modified_input_data.idx)
Если такое преобразование потенциально может потребоваться не только тут, то мб стоит такое преобразование делать на уровне например пайплайна в препрцессинге. Но это так, просто мысль, возможно так и сделаю в PR по препроцессингу

2021-11-27 09:47 UTC, Dreamlone commented on fedot/core/serializers/opt_history_serializer.py
> +                ]
Строки 18-21 и 23-27 вроде дублируют друг друга. Может вынести их в отдельный метод или функцию?

2021-11-27 14:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        old_idx = np.asarray(modified_input_data.idx)
Да, в идеале стоит в самом начале преобразовывать в nparray, чтобы дальше не заморачиваться.
Давай лучше в твоем PR это поправим - т.к. надо будет ещё убирать проверки на isinstance(list) в паре мест.

2021-12-02 06:38 UTC, IIaKyJIuH commented on fedot/core/serializers/opt_history_serializer.py
> +                ]
[Сделал отдельную функцию](https://github.com/nccr-itmo/FEDOT/pull/505/commits/bff3602010c5ebbd0b54c394889787d0c629d2dd#diff-6cf664e47acce3d03b5f4af97209b4d1c24d6295464a7400ae9236b8e87c9981R30)

2021-12-02 07:58 UTC, Dreamlone approved these changes
Ветка отстала от мастера, надо не забыть сделать ребейз

2021-12-02 07:58 UTC, Dreamlone commented on fedot/core/serializers/opt_history_serializer.py
> +        return super().to_json()
Это наверно не к этому PR уже, но просто чтобы не забылось выскажу парочку своих мыслей. 

Мне кажется, что это нагромождение классов для сериализации "подставь_что_то_своё" излишнее. Все преимущества от наследования здесь проявляются от использования  метода to_json() от суперкласса, а все полезные методы оборачиваются в статические. Это плодит большое количество классов на все случае жизни. Мой вопрос: действительно ли нужны они все? (это не риторический вопрос, правда интересно). Тем более что в type hint периодически всплывает Any. То есть методы у разных сериализаторов по идее могут процессить любые объекты, а зачем тогда их специализировать?

Кмк можно было обойтись одним классом-сериализатором а уже внутри него сделать композицию из функций: каждая - для своего объекта, что-то вроде
```
class Serializable:

      _processors_by_type = {Operation: {'to_json': operation_to_json,
                                       'from_json': operation_from_json},
                             Graph: {'to_json': graph_to_json,
                                     'from_json': graph_from_json}
                             }
    ...
```

Но это конечно так, рассуждения на тему. Этот PR норм )

2021-12-02 08:05 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        old_idx = np.asarray(modified_input_data.idx)
Было реализовано в #484

2021-12-02 10:19 UTC, IIaKyJIuH commented on fedot/core/serializers/opt_history_serializer.py
> +        return super().to_json()
**"...а все полезные методы оборачиваются в статические..."**
В классах сериализации же нет статических методов, что ты имел в виду?

**"...Это плодит большое количество классов на все случаи жизни..."**
Есть [базовый класс сериализации](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/serializers/basic_serializer.py), который использует просто-напросто функционал абстрактного класса. Такой базовый сериализатор нужен для простых классов без особенных полей, но иногда в классах бывают поля, которые вызывают кольцевые зависимости, и для них как раз нужен особенный сериализатор.

**"действительно ли нужны они все?"**
Вообще можно действительно сделать проще, хотя бы отказавшись от наследования частными сериализаторами в сериализуемых классах.
Можно сделать и как ты предлагаешь, тогда не придётся применять наследование вообще, и не будет потенциальных проблем со множественным наследованием. Идея хорошая, её можно реализовать в текущей версии, но пока смущает то, что в одном месте может быть слишком много сущностей.
В общем, от сериализаторов на классах можно попробовать отказаться для упрощения в другом PR.

**"Тем более что в type hint периодически всплывает Any"**
Это была скорее недоработка, которая легко исправляется конкретной типизацией в каждом из сериализаторов.

2021-12-02 12:50 UTC, Dreamlone commented on fedot/core/serializers/opt_history_serializer.py
> +        return super().to_json()
> В классах сериализации же нет статических методов, что ты имел в виду?

Да, пардон, не тот декоратор, там classmethod в основном. Разве что в [OptHistorySerializer](https://github.com/nccr-itmo/FEDOT/blob/hotfix-idx/fedot/core/serializers/opt_history_serializer.py#L10) присутствует статический, но это мелочи конечно 

> В общем, от сериализаторов на классах можно попробовать отказаться для упрощения в другом PR.
"Тем более что в type hint периодически всплывает Any"
Это была скорее недоработка, которая легко исправляется конкретной типизацией в каждом из сериализаторов.

Да, конечно. Можно будет ещё раз обсудить потом как можно будет расширять функциональность сериализации различных объектов в FEDOT'е. Этот PR можно вливать в мастер кмк

2021-12-02 15:56 UTC, merged