Custom model upgrading
nccr-itmo/FEDOT pull request #507
Opened 2021-11-30 16:11 UTC by ChrisLisbon

Fitting for custom models are available. Tests and examples added.

2021-11-30 16:24 UTC, Dreamlone requested changes

2021-11-30 16:24 UTC, Dreamlone commented on test/unit/models/test_custom_model_introduction.py
> +    return reg
Вот эту штуку можно переиспользовать из examples, там эта функция называется `custom_ml_model_imitation_fit`

2021-11-30 16:24 UTC, Dreamlone commented on test/unit/models/test_custom_model_introduction.py
> +        lagged -> custom -> ridge
Вроде тоже можно из examples дернуть

2021-11-30 16:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +                raise ValueError('There is no key word "model_predict" for model definition in input dictionary.')
Вроде можно проще: вместо проверки `if 'model_predict' in self.params.keys():` и выбрасывания можно обращаться к словарю `self.params['model_predict']`. Ошибка сама выкинется о том, что нет такого аргумента в словаре. Или тут вся идея в том, чтобы кастомное сообщение об ошибке выводить?

2021-11-30 16:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +                                        Callable[[any, np.array, dict], np.array, str]')
Проясни плиз эту фразу и почему именно TypeError)

2021-11-30 21:34 UTC, nicl-nno commented on examples/time_series/ts_custom_model_tuning.py
> +def domain_model_imitation_predict(fitted_model, train_data, params):
Если это predict - то лучше и predict_data

2021-11-30 21:34 UTC, nicl-nno commented on examples/time_series/ts_custom_model_tuning.py
> +def custom_ml_model_imitation_fit(features, target, params):
Для большей наглядности примеров стоит типы данных указать.

2021-12-01 09:24 UTC, ChrisLisbon commented on test/unit/models/test_custom_model_introduction.py
> +    return reg
Сделала, удалила функции из теста

2021-12-01 09:24 UTC, ChrisLisbon commented on test/unit/models/test_custom_model_introduction.py
> +        lagged -> custom -> ridge
Импортировала

2021-12-01 09:24 UTC, ChrisLisbon commented on examples/time_series/ts_custom_model_tuning.py
> +def domain_model_imitation_predict(fitted_model, train_data, params):
Поправила

2021-12-01 09:24 UTC, ChrisLisbon commented on examples/time_series/ts_custom_model_tuning.py
> +def custom_ml_model_imitation_fit(features, target, params):
Добавила во всех кастомных функциях

2021-12-01 09:47 UTC, Dreamlone approved these changes
Было ещё неплохо добавить описание PR

2021-12-01 09:47 UTC, Dreamlone commented on examples/time_series/ts_custom_model_tuning.py
> +    if pipeline_type == 'without_fit':
Можно сделать как `if-elif` или как `if-else`

2021-12-01 09:47 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +from fedot.core.data.data import InputData
Импорт не используется

2021-12-01 15:56 UTC, ChrisLisbon commented on examples/time_series/ts_custom_model_tuning.py
> +    if pipeline_type == 'without_fit':
сделала elif

2021-12-01 15:56 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +from fedot.core.data.data import InputData
Убрала

2021-12-01 15:59 UTC, nicl-nno approved these changes

2021-12-01 16:00 UTC, merged