Improving binary feature processing
nccr-itmo/FEDOT pull request #508
Opened 2021-12-02 13:30 UTC by Dreamlone

Modified the Imputer so that it can correctly handle integer features with unique values of 2 or less. 
For example, now `[1, 1, nan, 0]` will not be transformed into `[1, 1, 0.75, 0]`, but into `[1, 1, 1, 0]`. 
Another case: `[1, nan, nan, 0]` (the number of known categories is equal to each other). Then it will be converted inro `[1, 0.5, 0.5, 0]` 

Minor issues with preprocessing and processing of multi-output cases have also been corrected

2021-12-02 14:35 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +
Шанс что попадет в равенство мал, но может лучше подстраховаться?

2021-12-02 14:38 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +
В этом и идея, что если количество массив такой [1, 1, nan, 0] то он сначала после заполнения пропусков преобразуется в такой [1, 1, 0.75, 0] а потом благодаря строкам выше в такой [1, 1, 1, 0].
Если же ситуация такая например: [1, nan, nan, 0] (the number of known categories is equal to each other)

То мы равные среднему значения не трогаем и остаётся вот так - [1, 0.5, 0.5, 0]

2021-12-02 14:39 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +
Поняла, оригинально)

2021-12-03 12:53 UTC, nicl-nno requested changes

2021-12-03 12:53 UTC, nicl-nno commented on fedot/core/data/data_preprocessing.py
> +    is_int_dtype = data.features.dtype is np.array([1.5]).dtype
А тут не зафиксировать тип в правой части?

2021-12-03 12:53 UTC, nicl-nno commented on fedot/core/data/data_preprocessing.py
> +    if is_float_dtype or is_int_dtype:
Кмк лучше

is_categorical = not (is_float_dtype or is_int_dtype)
return is_categorical

2021-12-03 12:53 UTC, nicl-nno commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        is_multi_target = False
Аналогично: is_multi_target = ... выглядит проще

2021-12-03 12:59 UTC, Dreamlone commented on fedot/core/data/data_preprocessing.py
> +    is_int_dtype = data.features.dtype is np.array([1.5]).dtype
С сопоставлением типов numpy массивов периодически возникают проблемы. Например, никакая из проверок `data.features.dtype is np.int32` или любые другие аналоги не помогали. Загвоздка в том, что иногда массивы предложенными мной вариантами проверок успешно обрабатывались, а иногда нет, хотя вроде и там int, и там int, но не так всё просто. 

Не помогла проверка через isinstance тоже. В общем на данный момент я в поиске. предполагаю исправить все эти штуки с типами в пулл реквесте с "фиксом типов" - уже в процессе. Пока этот вариант несколько более стабилен, чем предыдущий

2021-12-03 13:18 UTC, nicl-nno commented on fedot/core/data/data_preprocessing.py
> +    is_int_dtype = data.features.dtype is np.array([1.5]).dtype
Ок, кажется проблема [известная](https://stackoverflow.com/questions/26921836/correct-way-to-test-for-numpy-dtype)

Можно тогда хотя бы вынести правую часть в шапку как константы

2021-12-03 14:20 UTC, Dreamlone commented on fedot/core/data/data_preprocessing.py
> +    is_int_dtype = data.features.dtype is np.array([1.5]).dtype
[Done](https://github.com/nccr-itmo/FEDOT/pull/508/commits/a6e3ceea638b878699d6127223fe7781a0ca2b89#diff-c1c9919b19ad3855f98b1a40f465c33911178a991571f93127655f2ff03e64a5R9-R22)

2021-12-03 14:24 UTC, Dreamlone commented on fedot/core/data/data_preprocessing.py
> +    if is_float_dtype or is_int_dtype:
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/508/commits/a6e3ceea638b878699d6127223fe7781a0ca2b89#diff-c1c9919b19ad3855f98b1a40f465c33911178a991571f93127655f2ff03e64a5R21-R22), разве что там проверка не на то, что весь массив категориальный, а то что в нем содержатся категориальные колонки. Поэтому и название немного отличается от предложенного варианта

2021-12-03 14:25 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        is_multi_target = False
[Обновил](https://github.com/nccr-itmo/FEDOT/pull/508/commits/a6e3ceea638b878699d6127223fe7781a0ca2b89#diff-60a694a93b0cdb51f5f81fc4449dfb07a74d317aa8bd323439c4804353c0584aL256-R257)

2021-12-03 14:31 UTC, nicl-nno approved these changes

2021-12-06 09:19 UTC, merged