NumericalDerivativeImplementation implementation
nccr-itmo/FEDOT pull request #510
Opened 2021-12-03 15:11 UTC by valer1435

Implementation of method to finding a numerical derivative of time series

2021-12-03 15:49 UTC, nicl-nno requested changes

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +class HvatovFilterImplementation(DataOperationImplementation):
Лучше назвать NumericalDerivativeImplementation или как-то так.

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        """ Hvatov filter """
Аналогично - это не совсем фильтр в такой реализации, и изобрел его не Хватов.

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        supp1 = ts[0:self.window_size]
Нотацию лучше использовать supp_1 для единообразия

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.order = 1
Лучше корректировать не order, а poly_degree.
Должно выполняться правило poly_degree - order >=1

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.poly_degree = 2
Логичнее ставить 5 вроде, чтобы не было резких скачков.

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.log.info(f'HvatovFilter: invalid parameter poly_degree ({self.poly_degree}) changed to 2')
Лучше вместо 2 ссылаться на переменную.

2021-12-03 15:49 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        if self.parameters_changed is True:
А тут нужно явное is True?

2021-12-03 17:18 UTC, nicl-nno commented on examples/time_series/derivative_example.py
> +    :param raw_model: if only raw model used
Вот этого параметра кажется не существует.

2021-12-03 18:26 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +class HvatovFilterImplementation(DataOperationImplementation):
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/510/commits/a6bd74f7acc99ba3b49e4da054c51170aa7400a3#diff-09c6cc40fb21ffe71f2ef4e204936b283d885519c78b24d5ef17907d6422f462R21)

2021-12-03 18:26 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        """ Hvatov filter """
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/510/commits/a6bd74f7acc99ba3b49e4da054c51170aa7400a3#diff-09c6cc40fb21ffe71f2ef4e204936b283d885519c78b24d5ef17907d6422f462R21)

2021-12-03 18:27 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        supp1 = ts[0:self.window_size]
[Поменял названия](https://github.com/nccr-itmo/FEDOT/pull/510/commits/e5352bc45b66cda742b4b60a506c4c1897240605#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R343-R352)

2021-12-03 18:34 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        if self.parameters_changed is True:
[Справедливо](https://github.com/nccr-itmo/FEDOT/pull/510/commits/a6bd74f7acc99ba3b49e4da054c51170aa7400a3#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R437)

2021-12-03 18:35 UTC, valer1435 commented on examples/time_series/derivative_example.py
> +    :param raw_model: if only raw model used
[Удалил](https://github.com/nccr-itmo/FEDOT/pull/510/commits/a6bd74f7acc99ba3b49e4da054c51170aa7400a3#diff-09c6cc40fb21ffe71f2ef4e204936b283d885519c78b24d5ef17907d6422f462R31)

2021-12-03 18:40 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.order = 1
Оно должно выполняться всегда? В теории poly_degree может быть больше чем на 1 чем order. (как сейчас). Или подразумевается функциональная зависимость (так даже было бы проще - задавать только order)

2021-12-03 20:00 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.order = 1
@SuperSashka прокомментируй лучше ты, чтобы я не исказил истину.

2021-12-03 20:15 UTC, SuperSashka commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.order = 1
Действительно 
>Лучше корректировать не order, а poly_degree
Это 
>Должно выполняться правило poly_degree - order >=1
тоже верно, должно выполняться всегда. Приведу пример, если poly_degree=3, первая производная - poly_degree=2, вторая poly_degree=1 - это уже линия. Чем больше poly_degree, тем точнее линия подстраивается под данные, то есть в теории для "чистых" данных, лучше брать порядок полинома=ширине окна. Чем меньше poly_degee - тем больше данные фильтруются. И вот минимальное значение poly_degree должно быть на один больше, чем порядок производной order, иначе будет константа или нуль, что плохо.

По этому вопросу у меня всё.

2021-12-07 08:54 UTC, Dreamlone requested changes

2021-12-07 08:54 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        x = np.arange(ts.shape[0])
Я понимаю, что это не твои переменные здесь (вроде бы), но все таки давай попробуем код немного сделать более понятным. Переменные длиной в одну букву - первое место, которое можно улучшить. 
Например, не `x`, а `x_axis`, не `n`, а `len_features`, `j` можно заменить на `central_window_index`. Дальше можно оставить как есть

2021-12-07 08:54 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'window_size': (hp.choice, [[3, 4, 5, 7, 10, 15, 20]])
Может лучше не `hp.choice` использовать, а hp.uniform? Просто округлять до корректных значений на уровне самой имплементации

2021-12-07 08:54 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +				"non_lagged"
Забыл тег про то, что параметры у операции корректируются

2021-12-10 11:15 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.poly_degree = 2
[Поменял на 5](https://github.com/nccr-itmo/FEDOT/pull/510/commits/8828c740211c0dc8523e499e92a9277516c800dd#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R289-R290)

2021-12-10 11:15 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.log.info(f'HvatovFilter: invalid parameter poly_degree ({self.poly_degree}) changed to 2')
[Ссылаюсь](https://github.com/nccr-itmo/FEDOT/pull/510/commits/8828c740211c0dc8523e499e92a9277516c800dd#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R368)

2021-12-10 11:16 UTC, valer1435 commented on fedot/core/pipelines/tuning/search_space.py
> +                'window_size': (hp.choice, [[3, 4, 5, 7, 10, 15, 20]])
[Поменял на uniform](https://github.com/nccr-itmo/FEDOT/pull/510/commits/8828c740211c0dc8523e499e92a9277516c800dd#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7R225-R227)

2021-12-10 11:16 UTC, valer1435 commented on fedot/core/repository/data/data_operation_repository.json
> +				"non_lagged"
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/510/commits/8828c740211c0dc8523e499e92a9277516c800dd#diff-df7dac615bd3b8aa10c0a9d37c85378e1a91d41ab4ae144573109cc2c9efe115R220)

2021-12-10 11:17 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        x = np.arange(ts.shape[0])
[Поменял названия](https://github.com/nccr-itmo/FEDOT/pull/510/commits/8828c740211c0dc8523e499e92a9277516c800dd#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R339-R360)

2021-12-10 11:35 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.poly_degree = 2
![image](https://user-images.githubusercontent.com/5711814/145567973-92688ef1-3e73-4700-b7ad-fb4b7c74bdfe.png)

Я про другое - если self.poly_degree > B, то логично его значение устанавливать равным B.
Соответсвенно, если < 0 - то 0 (к слову, для степени полинома минимальное значение 1 выглядит более применимо)

2021-12-17 08:08 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.poly_degree = 2
[Исправил этот момент](https://github.com/nccr-itmo/FEDOT/pull/510/commits/1087f816f81101a78063bac2ab1733f32a287741#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R370-R377)

Также, теперь, если order <= 0, то ставим значение 1. Если степень полинома <= 1, то условие poly_degree = order + 1 исправит степень полинома на правильное значение

2021-12-17 08:19 UTC, Dreamlone approved these changes
Не забудь сделать ребейз, ветка довольно сильно от мастера отстала

2021-12-17 10:03 UTC, nicl-nno approved these changes

2021-12-17 14:27 UTC, merged