Safe mode implementation
nccr-itmo/FEDOT pull request #514
Opened 2021-12-08 19:19 UTC by valer1435

Sometimes we faced with large table datasets (when MxN is too large). This pull request is devoted to solving such problem by cutting train data. 
Also a problem with encoding categorical features with big cardinality should be resolved in this PR. To do this we use label encoding when summary cardinality become bigger than a  constant threshold.

2021-12-08 19:19 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/api_utils/api_safety.py`](https://github.com/nccr-itmo/FEDOT/blob/44fce4d8a2b43b1dc84b8663cc74815f222b5e3e/fedot/api/api_utils/api_safety.py):

> [Line 47:1](https://github.com/nccr-itmo/FEDOT/blob/44fce4d8a2b43b1dc84b8663cc74815f222b5e3e/fedot/api/api_utils/api_safety.py#L47): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file





* In the file [`fedot/preprocessing/preprocessing.py`](https://github.com/nccr-itmo/FEDOT/blob/44fce4d8a2b43b1dc84b8663cc74815f222b5e3e/fedot/preprocessing/preprocessing.py):

> [Line 393:5](https://github.com/nccr-itmo/FEDOT/blob/44fce4d8a2b43b1dc84b8663cc74815f222b5e3e/fedot/preprocessing/preprocessing.py#L393): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 398:36](https://github.com/nccr-itmo/FEDOT/blob/44fce4d8a2b43b1dc84b8663cc74815f222b5e3e/fedot/preprocessing/preprocessing.py#L398): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-12-08 19:21 UTC, nicl-nno commented on fedot/api/main.py
> +    :param save_mode: if set True it will cut large datasets to prevent memory overflow.
Видимо sa**f**e

2021-12-08 19:46 UTC, valer1435 commented on fedot/api/main.py
> +    :param save_mode: if set True it will cut large datasets to prevent memory overflow.
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/514/commits/d37253748f6c0a6b91b0aa7e165da05e655cb826#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR56)

2021-12-08 21:31 UTC, Dreamlone requested changes

2021-12-08 21:31 UTC, Dreamlone commented on fedot/api/api_utils/api_safety.py
> +    def __init__(self, safe_mode):
Точно есть потребность в таком классе? Я бы предложил всё таки использовать изначальную концепцию с DataAnalyser'м. Плюс docstring

Пусть лучше у DataAnalyser'а будет режим вроде "Проанализируй датасет с расчетом на то, чтобы он точно позволил запуститься композеру"

2021-12-08 21:31 UTC, Dreamlone commented on fedot/api/api_utils/api_safety.py
> +        if isinstance(input_data, InputData):
Опять же, docsting 
Заодно стоит добавить TODO для мультимодальных данных. Или мб сейчас получится реализовать обработку, вроде можно просто итерироваться по датасетам с точно такой же обработкой

2021-12-08 21:31 UTC, Dreamlone commented on fedot/api/api_utils/api_safety.py
> +            input_data, self.label_encoder = DataPreprocessor.label_encoding(input_data)
Важно не забыть. Если LabelEncoder используется при обучении, его тоже  нужно будет использовать на стадии predict. Хорошо, что ты его в состояние сохраняешь, - осталось его на predict'е в api тоже вызывать 

Важное уточнение: представим ситуацию. Мы запускаем на здоровенном датасете через API FEDOT. Он пыхтит три часа на урезанном и перекодированном датасете и возвращает нам пайплайн. Мы его с радостью сохраняем (сериализуем). И вот нам теперь необходимо этот сериализованный пайплайн запустить в прод. Внимание вопрос: подав ему на вход тот же самый датасет, не свалится ли он с ошибкой. Ответ такой: нет, если мы предусмотрим механизм переноса предобработки от API к пайплайну. 

Я так реализовывал для простого препроцессинга. Возможно, стоит сделать так же - DataAnalyser - анализирует, и даёт реккомендации препроцессору в API. Тот успешно выполняет все требования и по окончании композирования просто "подменяет" pipeline'ский препроцессор апишным препроцессором (извиняюсь за жаргонизм)

2021-12-08 21:31 UTC, Dreamlone commented on fedot/api/api_utils/api_safety.py
> +            all_cardinality += np.unique(input_data.features[:, idx].astype(str)).shape[0]
А если в датасете пропуски, не упадёт с ошибкой?

2021-12-09 07:52 UTC, valer1435 commented on fedot/api/api_utils/api_safety.py
> +    def __init__(self, safe_mode):
Ты говорил, что это будет огромный модуль, который будет больше DataAnalyser. Возможно я неправильно понял

2021-12-09 08:07 UTC, Dreamlone commented on fedot/api/api_utils/api_safety.py
> +    def __init__(self, safe_mode):
Да, предполагается его расширять со временем. Но так реализовать то его нужно уже сейчас и "поручить" какие-то задачи для выполнения. Например, в рамках данного PR - это будет функциональность по анализу размера табличных датасетов и его предобработка до "адекватного вида" путем урезания строк, конвертации столбцов и так далее

Как мы вчера обсуждали, все операции обрезки и конвертации действительно можно делать на уровне дата препрцессора

2021-12-09 13:38 UTC, valer1435 commented on fedot/api/api_utils/api_safety.py
> +            all_cardinality += np.unique(input_data.features[:, idx].astype(str)).shape[0]
При переходе к строке наны переводятся в 'nan'

2021-12-09 13:39 UTC, valer1435 commented on fedot/api/api_utils/api_safety.py
> +    def __init__(self, safe_mode):
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/244b3269ad5532f01ed515f53bb9b73ecec910f4#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR9-R59)

2021-12-09 13:40 UTC, valer1435 commented on fedot/api/api_utils/api_safety.py
> +        if isinstance(input_data, InputData):
[Добавил docstring](https://github.com/nccr-itmo/FEDOT/pull/514/commits/244b3269ad5532f01ed515f53bb9b73ecec910f4#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR10-R15)

Работу с мультимодальными данными добавлю попозже

2021-12-09 13:52 UTC, Dreamlone commented on fedot/api/api_utils/api_data_analyser.py
> +        self.data_preprocessor.preprocessor.encode_data_for_fit(input_data, need_label)
Комментарии на русском надо убрать или перевести на английский

2021-12-09 14:01 UTC, Dreamlone requested changes

2021-12-09 14:05 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +        self.data_preprocessor.preprocessor.encode_data_for_fit(input_data, need_label)
Это больше вопрос тебе, чтобы ты обратил внимание - так нормально?

2021-12-09 14:12 UTC, Dreamlone commented on fedot/api/api_utils/api_data_analyser.py
> +        self.data_preprocessor.preprocessor.encode_data_for_fit(input_data, need_label)
Ага, да, давай так оставим, думаю тут самое место

2021-12-09 14:24 UTC, nicl-nno commented
Вопрос: а итоговый [fit](https://github.com/nccr-itmo/FEDOT/blob/244b3269ad5532f01ed515f53bb9b73ecec910f4/fedot/api/api_utils/api_composer.py#L77) после работы композера делается на полных данных или на сокращенных? Должен на полных.

2021-12-09 14:34 UTC, Dreamlone commented
> Вопрос: а итоговый [fit](https://github.com/nccr-itmo/FEDOT/blob/244b3269ad5532f01ed515f53bb9b73ecec910f4/fedot/api/api_utils/api_composer.py#L77) после работы композера делается на полных данных или на сокращенных? Должен на полных.

А, да, сейчас конечно будет производится на урезанных, так как все операции по преобразованию делаются inplace

2021-12-09 20:45 UTC, valer1435 commented on fedot/api/main.py
> +        self.data_analyser.safe_preprocess(self.train_data)  # inplace
[Реализовал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/38102785db50a3f984f8b9a2d2faa3e3d02b5a8d#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR24-R35), но более подробно надо во всем коммите смотреть

2021-12-09 20:45 UTC, valer1435 commented on fedot/api/main.py
> +    :param safe_mode: if set True it will cut large datasets to prevent memory overflow.
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/514/commits/38102785db50a3f984f8b9a2d2faa3e3d02b5a8d#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR56-R57)

2021-12-09 21:24 UTC, nicl-nno commented on fedot/preprocessing/preprocessing.py
> +    def cut_dataset(self, data: InputData, border):
Может тут же shuffle делать?

2021-12-10 09:30 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +    def cut_dataset(self, data: InputData, border):
[Сделал shuffle](https://github.com/nccr-itmo/FEDOT/pull/514/commits/a271579e9c9dd007ea7403015bf55b9a2e159ae3#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR271)

2021-12-10 10:40 UTC, Dreamlone requested changes

2021-12-10 10:40 UTC, Dreamlone commented on fedot/api/main.py
> +        full_train_not_preprocessed = deepcopy(self.train_data)
Тут точно два раза deepcopy нужно?

2021-12-10 10:40 UTC, Dreamlone commented on fedot/core/repository/data/model_repository.json
> +      "tags": ["tree"]
Стоит и одиночным решающим деревьям поставить соответствующий тег

2021-12-10 10:40 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +    def encode_label_for_fit(self, data: Union[InputData]):
Пусть лучше в названии будет отражено, что это label_encoding

2021-12-10 10:40 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +        :param is_label: is we use a specific label encoder
Параметр в docstring устарел

2021-12-10 10:40 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +        :param is_label: is we use a specific label encoder
Параметр устарел

2021-12-10 10:40 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +        Fills in the gaps, converts categorical features using OneHotEncoder and create encoder.
Описание не под тот метод

2021-12-10 10:40 UTC, Dreamlone commented on test/unit/api/test_api_safety.py
> +def test_api_fit_predict_with_pseudo_large_dataset_with_onehot_correct():
Нужно описание ко всем тестам, а то мне честно сказать тяжело через них пробираться. В качестве примеров можешь использовать [эти](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/test_data_preprocessing.py) и [эти](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/pipelines/test_pipeline_preprocessing.py)

2021-12-10 10:40 UTC, Dreamlone commented on test/unit/api/test_api_safety.py
> +    model.fit(features=data)
лучше для сохранения времени на тестах во всех методах fit ставить predefined_model='auto'

2021-12-10 10:49 UTC, valer1435 commented on fedot/api/main.py
> +        full_train_not_preprocessed = deepcopy(self.train_data)
В теории можно обойтись без него - тут он нужен, чтобы сохранить копию исходного датасета для финального fit (оригинал может быть обрезан)

То есть у нас есть:
1) Исходные данные принятые из вне (их менять нельзя)
2) Данные для композирования (копия исходных). Они могут быть обрезаны
3) На финальный fit нужна копия оригинального не обрезанного датасета
Отсюда и 2 deepcopy(

2021-12-10 13:59 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +                    recommendations['label'] = {}
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR34)

2021-12-10 13:59 UTC, valer1435 commented on fedot/api/api_utils/params.py
> +        preset_name = 'tree_reg' if task.task_type == 'regression' else 'tree_class'
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R89)

2021-12-10 14:01 UTC, valer1435 commented on fedot/api/main.py
> +        full_train_not_preprocessed = deepcopy(self.train_data)
Как и договорились, [перенес](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR49-R57) deepcopy в define_data

2021-12-10 14:01 UTC, valer1435 commented on fedot/core/repository/data/model_repository.json
> +      "tags": ["tree"]
[Проставил теги](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-a5c1624bd36467920ea4aedc11707222e45cce478c7c6728bbdc08424c455621R244-R245)

2021-12-10 14:02 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +    def encode_label_for_fit(self, data: Union[InputData]):
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR252)

2021-12-10 14:02 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +        :param is_label: is we use a specific label encoder
[Убрал параметр](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR339-R340)

2021-12-10 14:03 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +        :param is_label: is we use a specific label encoder
[Убрал параметр](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR253-R255)

2021-12-10 14:03 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +        Fills in the gaps, converts categorical features using OneHotEncoder and create encoder.
[Поменял описание](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52aR356)

2021-12-10 14:04 UTC, valer1435 commented on test/unit/api/test_api_safety.py
> +def test_api_fit_predict_with_pseudo_large_dataset_with_onehot_correct():
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-a1dbd9bd27a41e0008c93d2193e8368752e1a83acf1bc0e4f9dc7d608e084e44R13-R15) описание к тестам

2021-12-10 14:04 UTC, valer1435 commented on test/unit/api/test_api_safety.py
> +    model.fit(features=data)
[Добавил параметр](https://github.com/nccr-itmo/FEDOT/pull/514/commits/851cb07aae5645c1973c52516b4b306552384393#diff-a1dbd9bd27a41e0008c93d2193e8368752e1a83acf1bc0e4f9dc7d608e084e44R13-R15)

2021-12-10 14:41 UTC, Dreamlone requested changes

2021-12-10 14:41 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +                idx = deepcopy(features['idx'])
Делаешь deepcopy индексов? Давай хотя бы просто copy

2021-12-10 14:41 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
features и target могут быть и строками, зачем тогда их так копировать? 
Вообще я другое имел в виду, когда говорил, что надо делать deepcopy в define_data методе. Предлагаю просто перед return data делать копию

2021-12-10 14:41 UTC, Dreamlone commented on fedot/api/api_utils/api_data_analyser.py
> +            :return list with str recommendations
list все таки или словарь?

2021-12-10 14:41 UTC, Dreamlone commented on fedot/api/api_utils/api_data_analyser.py
> +                self.give_recommendation(input_data[data_source_name])
Мне кажется, что рекурсивно вызывать тут не самое лучшее решение. Вот например смотри, give_recommendation всегда выдаёт словарь (вроде как я понял) recommendations. Но словарь тоже вложенный вернётся, или я что-то не понимаю?

2021-12-10 18:58 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +                self.give_recommendation(input_data[data_source_name])
Ой, тут чет я намудрил, изначально тут была логика, что все изменения проходят здесь же и проблем не возникало. Интересно, как сделать, чтобы и для мультимодальных данных работало

2021-12-10 22:10 UTC, Dreamlone commented on fedot/api/api_utils/api_data_analyser.py
> +                self.give_recommendation(input_data[data_source_name])
Да давай тогда пока просто как TODO оформим обработку мультимодальных данных. Думаю, потом отдельным PR это все пропишем. Просто сейчас это все выглядит как игра вслепую, ни подходящих тестов, ни используемых примеров для именно предобработки мультимодальных табличных данных пока не имеется

2021-12-11 08:11 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
Тогда технически не будет разницы где deepcopy - снаружи или внутри. А так deepcopy будет создавать копию не всей InputData, где у нас могут быть дополнительные поля класса, методы, а только исходных индексов, фич и таргета. В теории это должно быть оптимальнее (хоть и не на много)

2021-12-11 08:56 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR49-R52)

2021-12-11 08:59 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +            :return list with str recommendations
[Словарь](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR28)

2021-12-11 09:07 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +                self.give_recommendation(input_data[data_source_name])
[Переделал 1](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR34-R35)

[Переделал 2](https://github.com/nccr-itmo/FEDOT/](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R78-R80)

[Переделал 3](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR108-R121)

2021-12-11 11:42 UTC, valer1435 commented on fedot/api/api_utils/api_safety.py
> +        if isinstance(input_data, InputData):
[Добавил TODO](https://github.com/nccr-itmo/FEDOT/pull/514/commits/e4ed0e556841e786b25ecc22f70429404342d494#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR24)

2021-12-11 11:42 UTC, valer1435 commented on fedot/api/api_utils/api_data_analyser.py
> +                self.give_recommendation(input_data[data_source_name])
Последний комментарий не прогрузился вовремя)

[Добавил TODO](https://github.com/nccr-itmo/FEDOT/pull/514/commits/e4ed0e556841e786b25ecc22f70429404342d494#diff-609676ec6aee24c98abc25f3af08021deda98fcb8cee78e4adc575ced1200dbfR24)

2021-12-11 11:44 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
[Сделал deepcopy таргета](https://github.com/nccr-itmo/FEDOT/pull/514/commits/e4ed0e556841e786b25ecc22f70429404342d494#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR117)

У нас как минимум временные ряды на горизонты прогнозирования >1

2021-12-11 11:44 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                idx = deepcopy(features['idx'])
[Сменил на copy](https://github.com/nccr-itmo/FEDOT/pull/514/commits/4dc406a41b7161a90f8c46610794cceca763cac1#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR49)

2021-12-11 12:08 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
> А так deepcopy будет создавать копию не всей InputData, где у нас могут быть дополнительные поля класса, методы, а только исходных индексов, фич и таргета. В теории это должно быть оптимальнее (хоть и не на много)

Сначала - преждевременная оптимизация - это анти-паттерн. Второе, я не совсем уверен, что вызов три раза deepcopy на небольших частях - это более эффективная стратегия, чем один раз скопировать один цельный объект. Не мог бы ты проверить это плиз? (например позамерять время "делания копий" по частям среднее по 10 запускам и время делания копии целиком). Просто меня вот [эта штука](https://stackoverflow.com/questions/24756712/deepcopy-is-extremely-slow) немного смущает. Deepcopy очень медленный, и моё предположение, что это не линейно зависит от размера копируемого объекта.
 
Ну и плюс вроде начальная InputData никаких полей кроме индексов и features с target не имеет. Всё остальное по умолчанию либо None, либо весит очень мало кмк

2021-12-11 12:16 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
> У нас как минимум временные ряды на горизонты прогнозирования >1

Просто FYI. Изначальный target для временных рядов не многомерный - представляет собой просто одномерный временной ряд. Он становится многомерным только после применения lagged-трансформации. А вот случай многомерной регрессии/классификации и правда никто не отменял - они изначально в InputData могут подаваться в многомерном виде

2021-12-11 14:19 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                                          target=deepcopy(target),
[Перенес deepcopy в конец define_data](https://github.com/nccr-itmo/FEDOT/pull/514/commits/ee6318db4e561b9388ce7f68f18bee2a6401f226#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR67)

2021-12-11 14:34 UTC, nicl-nno approved these changes

2021-12-11 14:48 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +                self. accept_recommendations(input_data[data_source_name], recommendations[data_source_name])
Пробел не лишний?

2021-12-11 15:05 UTC, Dreamlone approved these changes

2021-12-11 15:05 UTC, Dreamlone commented on test/unit/api/test_api_safety.py
> +    api_safety.max_cat_cardinality = 100
мб стоит вынести вот эти гиперпараметры max_size и max_cat_cardinality в аргументы функции get_data_analyser_with_specific_params для удобства

2021-12-11 17:53 UTC, valer1435 commented on fedot/api/api_utils/api_data.py
> +                self. accept_recommendations(input_data[data_source_name], recommendations[data_source_name])
[Лишний](https://github.com/nccr-itmo/FEDOT/pull/514/commits/80741f457d1c314fc3e4b38d34f83b2a12780596#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bR117)

2021-12-11 17:53 UTC, valer1435 commented on test/unit/api/test_api_safety.py
> +    api_safety.max_cat_cardinality = 100
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/514/commits/80741f457d1c314fc3e4b38d34f83b2a12780596#diff-a1dbd9bd27a41e0008c93d2193e8368752e1a83acf1bc0e4f9dc7d608e084e44R12)

2021-12-11 18:07 UTC, merged