Fixes for hybrid pipelines
nccr-itmo/FEDOT pull request #516
Opened 2021-12-16 15:01 UTC by nicl-nno

Several corrections were made to improve the AutoML applicability for hybrid pipelines with custom models.

CRM case will be moved to external repository.

2021-12-19 14:57 UTC, Dreamlone requested changes

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/crm.py
> +@author: deepthisen, dear-anastasia
Я не знаю до конца всей задумки с CRM: понимаю, что код не в ядре будет, а скорее как прикладной пример. Но буду предлагать здесь и ниже правки так, чтобы можно было в дальнейшем код без особых проблем сопровождать. Если комментарии по CRM-части сочтёшь излишними, то можешь проигнорировать. 

Сначала по поводу @author и описания. Из верхней части стоит убрать, либо совсем, либо перенести в docstring описание класса

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/crm.py
> +    def __init__(self, inputs_list, include_press=False):
Стоит добавить описание в docstring, хотя бы общее, что за CRM класс такой и что он прогнозирует и сделать то же самое для методов класса (хотя бы что помнишь, насколько понимаю, код здесь писала Настя)

Названия переменных тут тоже было бы полезно описать плюс расставить type hints

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/crm.py
> +        self.N_prd = self.gain_mat.shape[1]
Большие буквы стоит убрать

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3.py
> +from cases.oil.crm import CRMP as crm
Может просто CRMP?

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3.py
> +    filepath = join(project_root(), 'cases', 'data', 'oil')
Описание было бы здорово добавить как именно данные готовятся

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3.py
> +                                                        target=q_obs_train,  # [:, 0],
Комментарий можно убрать мне кажется

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3_with_opt.py
> +def prepare_data(target_well=0, is_full=True, modify_target=True):
Этот метод чем-то отличается от того `prepare_data`, который в cases/oil/oil3.py лежит? Если нет, то мне кажется, стоит его оттуда импортировать, или перенести в cases/oil/crm.py и подтягивать оттуда

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3_with_opt.py
> +def run_exp(with_automl=True):
Может название более говорящим сделать, вроде `automl_with_custom_model_run`?

2021-12-19 14:57 UTC, Dreamlone commented on cases/oil/oil3_with_opt.py
> +                             , np.ravel(predicted_test.predict), squared=False)
Запятая съехала)
Плюс если squared=False, то опираясь на вот [эту страничку](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_squared_error.html), возвращается RMSE метрика, а не MSE

2021-12-19 15:26 UTC, nicl-nno commented on cases/oil/crm.py
> +@author: deepthisen, dear-anastasia
Пример про CRM уйдет в отдельный репозиторий.

2021-12-20 07:40 UTC, J3FALL requested changes

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/crm.py
> +    def __init__(self, inputs_list, include_press=False):
Мне кажется, inputs_list лучше "раскрыть" в отдельные переменные - tau, gain_mat, n_inj, n_prod, и т.д.
Не вижу причин экономить на числе переменных в конструкторе

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/crm.py
> +    def prod_pred(self, input_series, train=False):
На подумоть: в методе есть 3 проверки `if train`, может, резонно выделить train-specific логику отдельно?

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/crm.py
> +        Grad_Q0 = self.Grad_Q0
not pep

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/crm.py
> +        #        dmse_dq0 = 2*np.sum(((q_obs - q_pred)/(q_obs+0.001))*-Grad_Q0,axis=0)/np.max(q_obs,axis=0)**2
Коммент не нужен?

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/crm.py
> +                                                                 axis=0) ** 2  # /np.sum((q_obs - q_pred)**2,axis=0)
Коммент?

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/oil3.py
> +    parse_date = True  # This dataset has dates instead of elapsed time. Hence convert to timedelta
Лучше тогда вынести его как внешний параметр у функции.

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/oil3.py
> +    percent_train = 0.7
Этот параметр, наверное, тоже.

2021-12-20 07:40 UTC, J3FALL commented on cases/oil/oil3.py
> +def crm_fit(idx: np.array, features: np.array, target: np.array, params: dict):
Тогда и для return-а стоит аннотации добавить

2021-12-20 09:02 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
>                                                            self.params)
То же

2021-12-20 09:06 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
>          initial_pipeline.fit(data)
Обсуждали этот момент с Колей. Тут вся идея в том, чтобы проверить, что пайплайн способен нормально обучиться и дать прогноз. Но такой формат (то что было раньше) подходит только для табличных данных, а не для временных рядов, так как ts пайплайн не может дать прогноз на тех же самых данных на которых обучался из-за индексирования по моему

2021-12-20 13:05 UTC, Dreamlone requested changes

2021-12-20 13:05 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
Может я где-то прошляпил, но тега ts_transformer вроде нигде нет

2021-12-20 13:05 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> -                data.target = np.ravel(data.target)
Поясни зачем убрал?) 
Вроде в DataMerger'е делается как раз обратное преобразование в этом PR

2021-12-20 13:05 UTC, Dreamlone commented on test/unit/models/test_custom_model_introduction.py
> +def prepare_data():
А можно как-нибудь эту функцию совместить с prepare_data, которая в cases используется?

2021-12-20 16:53 UTC, nicl-nno commented on cases/oil/crm.py
> +    def __init__(self, inputs_list, include_press=False):
Раскрыл.

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +    def __init__(self, inputs_list, include_press=False):
Кратко описал, хотя CRM и уйдет перед мержем в другой репо.

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +class CRMP:
Кратко добавил

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +        self.N_prd = self.gain_mat.shape[1]
Убрал

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +    def prod_pred(self, input_series, train=False):
Пока не будут так глубоко зарываться в CRM, но вообще да.

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +        Grad_Q0 = self.Grad_Q0
Cделал чтобы было pep.

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +        #        dmse_dq0 = 2*np.sum(((q_obs - q_pred)/(q_obs+0.001))*-Grad_Q0,axis=0)/np.max(q_obs,axis=0)**2
Убрал

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/crm.py
> +                                                                 axis=0) ** 2  # /np.sum((q_obs - q_pred)**2,axis=0)
Убрал

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/oil3.py
> +from cases.oil.crm import CRMP as crm
Поменял

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/oil3.py
> +    filepath = join(project_root(), 'cases', 'data', 'oil')
Кратко описал

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/oil3.py
> +    parse_date = True  # This dataset has dates instead of elapsed time. Hence convert to timedelta
Вынес

2021-12-20 16:54 UTC, nicl-nno commented on cases/oil/oil3.py
> +    percent_train = 0.7
Вынес

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3.py
> +    # Separation into training and test set
Упростил с использованием train_test_data_setup. Но не до конца уверен, что она полностью корректно работает с экзогенными переменными.

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3.py
> +                                                        target=q_obs_train,  # [:, 0],
Убрал

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3.py
> +def crm_fit(idx: np.array, features: np.array, target: np.array, params: dict):
Добавил

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3_with_opt.py
> +def prepare_data(target_well=0, is_full=True, modify_target=True):
Перенес и подтянул.

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3_with_opt.py
> +                             , np.ravel(predicted_test.predict), squared=False)
Вернул запятную на место, добавил r.

2021-12-20 16:55 UTC, nicl-nno commented on cases/oil/oil3_with_opt.py
> +def run_exp(with_automl=True):
Переименовал.

2021-12-20 16:55 UTC, nicl-nno commented on fedot/core/composer/advisor.py
> +        self.lag_transformers = get_operations_for_task(task, mode='data_operation')
Удалил пока совсем.

2021-12-20 17:04 UTC, nicl-nno commented
@Dreamlone @valer1435 при запуске оптимизации в oil_pipeline_opt.py у меня часто выпадает ошибка 'Pipeline' object has no attribute 'last_idx_int'.

![image](https://user-images.githubusercontent.com/5711814/146804815-2b8f1287-0b4f-4d08-8b31-a7701bb5d9b5.png)


Вроде это завязано на ваши недавние изменения - есть идеи, что может быть не так с данными или моделями?

2021-12-20 17:16 UTC, nicl-nno commented on fedot/core/composer/advisor.py
>              candidates = set.intersection(set(self.data_operations), set(possible_operations))
Упростил

2021-12-20 17:16 UTC, nicl-nno commented on fedot/core/data/merge.py
> +        if len(features.shape) and features.shape[1] == 1:
Добавил условие >1

2021-12-20 17:18 UTC, nicl-nno commented on fedot/preprocessing/preprocessing.py
> -                data.target = np.ravel(data.target)
Потому что в новой реализации target для custom-модели может быть и многомерным.
А если он одномерный - то и ravel вроде не нужен.

2021-12-20 20:12 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/custom_model.py
> +            self.fitted_model = self.model_fit(input_data.idx, input_data.features, input_data.target, self.params)
Чтобы сделать custom_fit/custom_predit полностью независимыми от классов FEDOT-а.

2021-12-20 20:15 UTC, nicl-nno commented on fedot/core/data/multi_modal.py
> +    def task(self, value):
В текущей реализации не могут, поэтому сделал так.

2021-12-20 20:19 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
Без этого тега невозможно выделить трансформирующие операции. Но пока я действительно их просто захардкодил в advisor-е.

>Заодно мне кажется, нам стоит сделать расшифровку в json файле с текстом того какой тег где и за что отвечает

Да, можно в документации этому посвятить страницу.

2021-12-20 20:54 UTC, nicl-nno commented on test/unit/models/test_custom_model_introduction.py
> +def prepare_data():
Лучше тестам быть независимыми от примеров. Но упростил немного код.

2021-12-21 07:41 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            target = np.ravel(np.array(target))
Многомерный target для временного ряда?

2021-12-21 08:41 UTC, valer1435 commented
> @Dreamlone @valer1435 при запуске оптимизации в oil_pipeline_opt.py у меня часто выпадает ошибка 'Pipeline' object has no attribute 'last_idx_int'.
> 
> ![image](https://user-images.githubusercontent.com/5711814/146804815-2b8f1287-0b4f-4d08-8b31-a7701bb5d9b5.png)
> 
> Вроде это завязано на ваши недавние изменения - есть идеи, что может быть не так с данными или моделями?

Интересно. Я встречал эту ошибку и даже фиксил. Посмотр, что там

2021-12-21 21:15 UTC, nicl-nno commented
Добавил fit после fit_from_cache - вроде решило проблему.

2021-12-22 08:15 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            target = np.ravel(np.array(target))
Покопался в коде, как я понял что происходит: CRM нужен многомерный target, поэтому все модели, которые подают данные в неё тоже должны иметь таковой. Понимаю зачем это было сделано, но тогда возникает вопрос: Чем отличается задача прогнозирования временного ряда от задачи регрессии? 

Я думал, что ключевая разница была как раз в том, что target у них разный - из этого предположения строились все предобработки (будь то lagged-like предобработки или встроенные обёртки в имплементации time-series моделей, например AR или ARIMA). Если такого ограничения в данном случае не требуется, то есть ли смысл стирать границу между задачами. Мне кажется, что лучше изначально для Primary-узлов перед CRM моделью подготавливать данные с пометкой - Task.regression, а на уровне CRM уже менять на ts_forecasting. Вижу, что сейчас не предусмотрена замена task'а в кастомной операции, так что видимо, это предложение на обсуждение на будущее 

Просто я не могу пока придумать никакого другого случая, когда при прогнозировании временного ряда target будет многомерным изначально

2021-12-22 08:18 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
> захардкодил в advisor-е

Ссылку дай пожалуйста на это место плиз, потому что видимо у меня PyCharm сломался, потому что не могу нигде найти использование этих тегов (кроме json файла)
![image](https://user-images.githubusercontent.com/52418437/147059402-41cd488b-6cdc-4a1c-8f51-3acfd12992d6.png)

2021-12-22 09:51 UTC, nicl-nno commented on fedot/core/data/merge.py
> +            target = np.ravel(np.array(target))
Многомерный target соответствует случаю, когда прогнозируется несколько рядов за раз (как в VAR). В остальном это та же задача forecasting-а. CRM - не точечная модель, поэтому ей для обучения нужна и предыстория, и истинные значения во всех точках.

В целом, можно было бы все предсказанные ряды дальше и использовать, но сейчас нельзя такой массив передавать в exog_ts, поэтому я на выходе оставляю только один целевой ряд.

2021-12-22 10:10 UTC, Dreamlone commented on fedot/core/data/merge.py
> +            target = np.ravel(np.array(target))
> Многомерный target соответствует случаю, когда прогнозируется несколько рядов за раз (как в VAR)
Но у нас сейчас нет ни одной модели прогнозирования временного ряда в FEDOT, которая могла бы прогнозировать несколько рядов сразу. А совмещать предысторию вместе со значениями в точках в те же моменты времени можно и в рамках задачи регрессии (по сути, это же и есть регрессия) добавив, например, подходящую операцию предобработки 

В остальном ок, убедил, оставляем как есть реализацию с многомерным target'м

2021-12-22 20:02 UTC, Dreamlone approved these changes
Я бы предложил тег "ts_transformer" пока убрать из репозитория (раз он пока не используется), потом подумаем как его лучше будет встроить

2021-12-22 20:05 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
Тег должен позволять отбирать именно те операции, которые служат для преобразования ряда в траекторную матрику. Т.е. это частный случай для ts -> table.

2021-12-22 20:09 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
Да, это понял, вот только дело в том, что все модели и регрессионные, и для временных рядов делают именно вот это преобразование `ts -> table`. 
То есть нет никакой разницы с точки зрения преобразования между lagged -> ridge и arima -> ridge, или exog_ts -> ridge. Модели не делают именно "траекторную матрицу" как это бывает при классическом "lagged", но таблицы из одномерного массива размера m x n, где n - это горизонт прогнозирования они все делают

2021-12-22 20:12 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
Вот поэтому и напрашивается теэг, который позволяет различить разные варианты преобразований. Иначе надо будет везде явно пересчислять операции.

2021-12-22 20:18 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +				"ts_transformer"
А, теперь понял) Тогда, думаю, можно этот тег проставить для всех регрессионных моделей, и для всех моделей на временных рядах (ARIMA, GLM и т.д.), плюс exog_ts, sparse_lagged, lagged 
Просто меня смутило, что тег на данный момент стоит только на последних двух

2021-12-23 08:13 UTC, valer1435 approved these changes

2021-12-23 16:53 UTC, nicl-nno commented
Тэг убрал, все скрипты crm удалил. Комментарии @J3FALL относятся только к ним, т.ч. аппрувлю.

2021-12-23 16:53 UTC, merged