Timeseries examples refactor
nccr-itmo/FEDOT pull request #517
Opened 2021-12-17 14:33 UTC by valer1435

* create template for tuning and composing pipelines
* rename examples

2021-12-17 14:33 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`examples/time_series/custom_model_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/d6bc95ada45e83ec1ecf4ca30888daa147ec1c54/examples/time_series/custom_model_tuning.py):

> [Line 141:119](https://github.com/nccr-itmo/FEDOT/blob/d6bc95ada45e83ec1ecf4ca30888daa147ec1c54/examples/time_series/custom_model_tuning.py#L141): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file











* In the file [`examples/time_series/pipelines.py`](https://github.com/nccr-itmo/FEDOT/blob/d6bc95ada45e83ec1ecf4ca30888daa147ec1c54/examples/time_series/pipelines.py):

> [Line 203:20](https://github.com/nccr-itmo/FEDOT/blob/d6bc95ada45e83ec1ecf4ca30888daa147ec1c54/examples/time_series/pipelines.py#L203): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-12-17 14:41 UTC, nicl-nno commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
А через API то же самое не сделать? Есть необходимость в advanced-режиме?

2021-12-17 15:11 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
Основная идея - разделить уровень API и уровень Composer'а. Чтобы при проблемах в API можно было работать напрямую с композером

2021-12-18 11:17 UTC, nicl-nno commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
Тогда стоит это перенести в отдельную папку advanced и описать в скрипте, что это для продвинутых пользователей.

Чтобы дюди, которым надо решить простую задачу, не шли столь сложным путём.

2021-12-18 11:21 UTC, nicl-nno commented on examples/time_series/pipelines.py
> +                              'seasonal': "add",
Для единообразия можно везде одинаковые таблички сделать. Ну и к каждому пайплайну дать короткий комментарий, хотя бы расшифровав сокращенные названия основных моделей.

2021-12-18 11:21 UTC, nicl-nno commented on examples/time_series/multistep.py
> +    # Let's divide our data on train and test samples
Вроде комментарий не в тему.

2021-12-18 11:22 UTC, nicl-nno commented on examples/time_series/composing_ts_pipelines.py
> +    for m in metrics_info:
Может хранить метрики как словарь, чтобы можно было просто сделать print()?

2021-12-18 21:41 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
> Чтобы дюди, которым надо решить простую задачу, не шли столь сложным путём.

Хочется прояснить ситуацию с примерами, вернее с examples в репозитории. Ниже опишу свои мысли по поводу как что можно сделать. Присоединяйтесь к обсуждению. 

Как вижу: у нас есть отдельный репозиторий с примерами, оформленный в виде jupyter notebooks (1), и есть примеры использования из examples и cases в репозитории фреймворка (2). Все примеры, которые есть в (1) мы делаем (или в процессе делания) максимально показательными и простыми. Они выполняют роль примеров для обычных пользователей фреймворка. Там есть картинки и примеры запуска в парадигме "low-code" естественно через api.

Если пользователь в состоянии сделать git clone и он точно уверен, что ему нужна именно текущая версия мастера, значит он знает, что делает. И вот для него уже будут примеры в папке cases и examples. Cases в данном PR, как я понимаю, мы не трогаем - остановимся на examples. Второе применения examples - это примеры для нас самих, то есть для разработчиков FEDOT'а, чтобы всегда можно было быстро запустить FEDOT'а на подходящей задаче относительно быстро как и при помощи API, так и при помощи низкоуровневых обвязок. Это к тому, что я за то, чтобы поддерживать жизнь таких участков кода как "как запустить FEDOT при помощи только композера всего в 100 строк кода" (в разумных пределах естественно). 

Тогда структура будет выглядеть примерно так:

* examples
    * simple (примеры через api, простые примеры со статичными генерируемыми вручную пайплайнами)
       * classification
       * regression
       * time_series_forecasting
       * import_export
       * interpretation
       * visualisation
    * advanced (композирование не через api, тюнинг пайплайнов, decompose примеры, дополнительные)
       * fedot_based_solutions 
       * remote_execution
       * sensitivity_analysis
       * time_series_forecasting
 
При этом хотелось бы избавиться от ситуации, когда есть папка (например remote_execution) и при этом в самих же examples лежит файл integration_example.py, который вроде бы и отвечает за remote execution (@nicl-nno или я что-то путаю и для такого расположения файлов есть задумка специальная?). То есть как-нибудь раскидать файлы по папкам так, чтобы как можно меньше было отдельно лежащих .py файлов. 

Да, тут придётся затронуть и не только ts-forecasting файлы, но, думаю, это не страшно, переписывать ничего не требуется, просто разложить примеры. Основная загвоздка в этом PR в том, что именно для примеров с временными рядами есть очень много дублирующего кода (но это вроде уже исправлено).

2021-12-18 21:53 UTC, nicl-nno commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
Ок, давай так раскидаем.

integration_example.py можно удалять.

2021-12-19 11:57 UTC, Dreamlone requested changes

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +from examples.time_series.pipelines import *
Там прямо все методы нужно импортировать? Лучше явно указать какие функции таскает этот пример

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +    obtained_pipeline.print_structure()
Лучше показывать как пайплайн выглядит в этом месте через pipeline.show()

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +                      })
Это конечно не критически важный момент, но предлагаю придерживаться такого стиля со скобками:
```
plot_info.append({'idx': idx,
                  'series': time_series,
                  'label': 'Actual time series'})
```

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +    plt.figure()
Поскольку это примеры, не скупись на комментарии и особенно на docstring для вспомогательных функций

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +                      'color': 'black'
А при чем здесь тюнинг? Вроде бы он тут не применяется, просто проверяется как может прогнозировать начальное приближение. Стоит поменять название лейбла на графике

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/multistep.py
> +    horizon = step_forecast * 5
Может во всех подобных функциях всегда в первую очередь показывать структуру пайплайна, а потом уже запускать примеры? Чтобы было понятно что за композитная модель используется

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/ts_clstm.py
> +
Лишняя строка

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/ts_clstm.py
> +                                 np.ravel(prediction_before_export)]))
Эти расчеты кмк стоит вынести в отдельные переменные

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/tuning_ts_pipelines.py
> +    if tuning:
Раз пример посвящен тюнингу, то стоит его всегда делать, можно убрать этот флаг из аргументов. 
Из названия файла можно убрать фразу "ts_pipelines" все равно же в папке "time_series" все лежит, я бы предложил просто "tuning"

2021-12-19 11:57 UTC, Dreamlone commented on examples/time_series/tuning_ts_pipelines.py
> +    run_experiment('salaries', clstm_pipeline(), len_forecast=30, tuning=False)
В качестве пайплайна по умолчанию можно выбрать более легковесный пример, чем CLSTM

2021-12-19 12:03 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +from examples.time_series.pipelines import *
Специально так сделал, чтобы условный pycharm мог подсказать, какие пайплайны можно туда вставить. Но если не очень вариант - уберу

2021-12-19 12:04 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +from examples.time_series.pipelines import *
А, тогда да, давай лучше оставим `*` - окей

2021-12-19 14:34 UTC, valer1435 commented on examples/time_series/tuning_ts_pipelines.py
> +    if tuning:
Хотелось бы оставить возможность прогнать просто пайплайн без тюнинга (при встраивании новой модели, например). Может переименовать пример?

2021-12-19 15:09 UTC, Dreamlone commented on examples/time_series/tuning_ts_pipelines.py
> +    if tuning:
> Хотелось бы оставить возможность прогнать просто пайплайн без тюнинга

Пусть такая возможность и останется. Только можно делать вот так: получаем пайплайн, делаем fit - predict, тюним его - делаем fit predict. На финальном графике отображаем оба варианта предсказаний.
Но вообще ладно, действительно пусть лучше такая возможность будет, оставляй как есть.

> Может переименовать пример?

Не, не стоит, тут все таки главная идея в демонстрации тюнинга)

2021-12-19 17:22 UTC, valer1435 commented on examples/time_series/multistep.py
> +    horizon = step_forecast * 5
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-33305ff1e0619318a6a9c887ac7d0929d832b19c574a021b0b1c46cfcd4050a6R32-R34)

2021-12-19 17:23 UTC, valer1435 commented on examples/time_series/pipelines.py
> +                              'seasonal': "add",
[Поменял кавычки и добавил описания](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-cc2be53914793b8cdb42d2b834e0b4f6eb875432c7947fe43459397cb9ff329aR6-R125)

2021-12-19 17:24 UTC, valer1435 commented on examples/time_series/multistep.py
> +    # Let's divide our data on train and test samples
[Удалил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-cfb97a803301593946e46e160bbdf0ac6275b67e9a1e7eebddb346db7e016f96R30)

2021-12-19 17:24 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    for m in metrics_info:
[Сделал словарь](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-cfb97a803301593946e46e160bbdf0ac6275b67e9a1e7eebddb346db7e016f96R61-R62)

2021-12-19 17:25 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    obtained_pipeline.print_structure()
[Показываю](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-b39946519949bc37f45edb9404ba3c7446982e7183841b81c44bab5dd3a5e890R126)

2021-12-19 17:27 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +                      })
[Привел скобки к нормальному виду](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-b39946519949bc37f45edb9404ba3c7446982e7183841b81c44bab5dd3a5e890R120)

2021-12-19 17:28 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    plt.figure()
[Добавил описание](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-b39946519949bc37f45edb9404ba3c7446982e7183841b81c44bab5dd3a5e890R130-R137). У остального вроде есть описания

2021-12-19 17:28 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +                      'color': 'black'
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-b39946519949bc37f45edb9404ba3c7446982e7183841b81c44bab5dd3a5e890R77-R78)

2021-12-19 17:29 UTC, valer1435 commented on examples/time_series/ts_clstm.py
> +
[Удалил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-e147c8f3c65d5f2aa99d7f0fbf0d0816db1b66c83625bc885f2b4265ca61c8f1R18-R19)

2021-12-19 17:30 UTC, valer1435 commented on examples/time_series/multistep.py
> +    horizon = step_forecast * 5
[Добавил print_structure](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#)

2021-12-19 17:30 UTC, valer1435 commented on examples/time_series/tuning_ts_pipelines.py
> +    run_experiment('salaries', clstm_pipeline(), len_forecast=30, tuning=False)
[Убрал clstm](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-cfb97a803301593946e46e160bbdf0ac6275b67e9a1e7eebddb346db7e016f96R93)

2021-12-19 17:31 UTC, valer1435 commented on examples/time_series/ts_clstm.py
> +                                 np.ravel(prediction_before_export)]))
[Вынес в функцию](https://github.com/nccr-itmo/FEDOT/pull/517/commits/2567e89e9c58ad87371045d8b6079fbf8d6af81d#diff-b39946519949bc37f45edb9404ba3c7446982e7183841b81c44bab5dd3a5e890R147-R160)

2021-12-19 17:34 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +                      })
Ещё такие же скобки есть в clstm.py, exogenous.py, tuning_pipelines.py, - тоже поправь плиз

2021-12-19 17:38 UTC, Dreamlone commented on examples/time_series/composing_ts_pipelines.py
> +    plt.figure()
Предлагаю выдерживать везде следующую структуру оформления параметров в docstring: 
```
Небольшое описание

:param новый параметр: описание параметра за что отвечает
```
Про оформление возможных полей в словаре возьми как пример то, как в api оформлено - см. class Fedot
Type hint ещё стоит проставить

2021-12-19 19:56 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    plt.figure()
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/517/commits/817061ae75466bbf2d1406f49048cec9fb710807#diff-3384f5c514371fc624fb0a9ff9b4e4511497098d5adadaa5b928c71b8a03e897R134-R140)

2021-12-19 19:59 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +                      })
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/817061ae75466bbf2d1406f49048cec9fb710807#diff-e8478c8f86ded0b09eac298d6faf95f1a63818635f829a41a8de02184c3683a9R58)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/817061ae75466bbf2d1406f49048cec9fb710807#diff-784cab98c5cce14dac8e43c643c9442c8a21fadc75d5af8f9789a3a1221c182fR43-R47)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/517/commits/817061ae75466bbf2d1406f49048cec9fb710807#diff-dc13f6f224b4ab23b2d703ac586e7b8685fd0136442e9bfb5a12f7aa85b469fcR65)

2021-12-20 07:26 UTC, J3FALL commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
Я бы тогда предложил еще добавить README в директориях simple и advanced.
Чтобы другим разработчикам было понятнее, что имел в виду автор под "простыми" и "сложными" примерами.

2021-12-20 07:28 UTC, J3FALL commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
А, ну или один README в корневой папке examples.
Так лучше, думаю

2021-12-20 08:05 UTC, Dreamlone reviewed
По предложенным изменениям: `automl` можно в папку advanced перенести. Туда же скрипты additional_learning.py, fedot_profiler_example.py, gpu_example.py, multi_modal_pipeline.py, pipeline_sensitivity.py
Остальные лежащие в корне py файлы спокойно можно в simple

2021-12-20 11:36 UTC, valer1435 commented on examples/time_series/composing_ts_pipelines.py
> +    composer = builder.build()
[Добавил файл](https://github.com/nccr-itmo/FEDOT/pull/517/commits/48bd985bf9cdc062b1fe45d554f588bf4ef375e3#diff-dfb7847397370766fb5e6f09ae9facca2eb878cf4b55bf63d64639e49f228897R1-R20)

2021-12-22 16:44 UTC, nicl-nno approved these changes
Только PEP8-комментарии надо поправить.

2021-12-23 08:42 UTC, Dreamlone requested changes
Думаю, проще будет писать комментарии скопом, а не итерироваться по файлам. Readme - like. В остальном тоже все хорошо, но предлагаю немного переместить некоторые примеры. 

Начну с simple: 
* в examples/simple/classification/api_classification.py есть run_classification_multiobj_example. Его стоит перенести в advanced под названием multiobj_example.py, потому что тут главное, что идёт многокритериальная оптимизация, а не то, что решается задача классификации. Ну и multiobj это всё таки advanced, потому что начинающим юзерам такое вряд ли нужно
* examples/simple/classification/resample_example.py - импорты некорректные, пример не запускается 
* examples/simple/interpretable/pipeline_explain.py - та же проблема 
* examples/simple/regression/api_regression.py - попробуй плиз посмотреть после ребейза как новая система препроцессинга справляется с сырым датасетом без строчки `data.features[data.features == '?'] = np.nan`
* examples/simple/time_series_forecasting/clstm.py - импорты 
* examples/simple/time_series_forecasting/multistep.py - импорты. Плюс лучше стоит перенести в advanced 
* examples/simple/time_series_forecasting/exogenous.py - лучше перенести в advanced 
* examples/simple/time_series_forecasting/pipelines.py - лучше вынести в папку examples и назвать как-нибудь pipelines_generators.py
* examples/simple/time_series_forecasting/tuning_pipelines.py - импорты

2021-12-23 08:48 UTC, Dreamlone commented
Advanced:
* examples/advanced/classification_with_tuning_example.py - лучше перенести в simple в папку с классификацией
* examples/advanced/regression_with_tuning_example.py - так же в папку регрессией в simple
* examples/advanced/automl/h2o_example.py - импорты
* examples/advanced/automl/tpot_example.py - импорты
* examples/advanced/sensitivity_analysis/case_analysis.py - импорты
* examples/advanced/sensitivity_analysis/complex_analysis_with_requirements.py - импорты
* examples/advanced/sensitivity_analysis/mta_example.py - импорты
* examples/advanced/sensitivity_analysis/pipeline_export_with_sa.py - импорты
* examples/advanced/sensitivity_analysis/run_cases.py - импорты
* examples/advanced/time_series_forecasting/composing_pipelines.py - импорты 
* examples/advanced/time_series_forecasting/sparse_lagged_tuning.py - импорты

Раз возникли неполадки с автоматической заменой импортов, то стоит проверить и еще тогда интеграционные тесты и cases

2021-12-23 09:03 UTC, Dreamlone commented
Кстати, мне кажется описание "fedot_based_solution - shows how FEDOT can be used with non-datascience tasks" лучше заменить на `shows how FEDOT can be applied to another graph optimization problems` или что-то в таком духе

2021-12-23 12:43 UTC, Dreamlone approved these changes

2021-12-23 13:10 UTC, merged