Target from InputData in predict mode should be ignored in (almost) all cases
nccr-itmo/FEDOT pull request #518
Opened 2021-12-19 23:58 UTC by MorrisNein

I constructed a wrapper around `predict()` method of `Pipeline`. What it does:

1.  executes `predict()` the second time with `input_data.target = None`.
2.  cheks the equality of `output_data.predict` in both cases.

This small investigation showed a bug with Keras CNN implementation. `input_data.num_classes` was used during predict stage. Fixed it by using `model.num_classes` custom property that is set in fit stage.

Besides that, no cases of `target is None` affecting `predict` results were found during unit tests.
Tests using `custom_model_imitation()` trigger the error, and it is OK since the function returns a random output.

The next task is to find out where the bug was noticed and check its existence.

2021-12-20 07:55 UTC, Dreamlone requested changes

2021-12-20 07:55 UTC, Dreamlone commented on fedot/core/data/data.py
> +                         task=self.task, data_type=self.data_type)
Здорово, что взялся за этот баг :) 

Давай немного заценю изменения. 
Лучше строку с `self.target is not None else None` перенести повыше, где точно такая же проверка сделана для features. И второе, посмотрел usages, а метод subset_range вообще где-то кроме тестов используется? Просто если не используется, то проблема с обращением к target'у там где не нужно, это не про этот метод

2021-12-20 07:55 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.num_classes = train_data.num_classes
А разве задание количество классов для классификации не происходит в методе `fit` класса `FedotCNNImplementation` (или при старом способе передачи параметры как-то затирались)? См. строку 163 и потом 167. Там вроде бы логика точно такая же, классы читаются только при вызове метода `fit`, что по идее не должно приводить к ошибкам

Призываю Илью @v1docq проконсультировать по этой CNN модели

2021-12-20 07:55 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +        #
Комменты стоит убрать

2021-12-20 08:13 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +    def wrapper(*args, **kwargs):
А можно как-нибудь эту проверку адаптировать под тест? Чтобы можно было протестировать что действительно, когда раньше у нас target влиял на предсказания, а с предложенными изменениями всё работает ок

И еще мне кажется, что по нескольку раз запускать метод predict - это не оптимальная стратегия. У нас же за время эволюции довольно много пайплайнов обучается, и для каждого из них мы увеличиваем время "оценки" за счет нескольких вызовов predict'в. Стоит ещё держать в голове, что для некоторых моделей (например K-nn) стадия обучения очень дешёвая (просто запомнил обучающую выборку и всё), а вот predict вызывать - дорогое удовольствие, особенно на больших датасетах. Там же именно на стадии predict'а происходит вся эта "прелесть" с оценкой расстояния между объектами и всё такое

2021-12-20 21:55 UTC, MorrisNein commented on fedot/core/data/data.py
> +                         task=self.task, data_type=self.data_type)
>Здорово, что взялся за этот баг :)

Люблю сложные случаи)

> а метод subset_range вообще где-то кроме тестов используется?

Каюсь, воткнул лишнюю заглушку. Убрал.
Спасибо, что проверил)

А в целом, я не предполагаю прям все изменения в `data.py` и `pipeline.py` из этого PR доводить до merge. Так что тут пока могут быть временные изменения, нужные для "расследования". Главное не забыть потом про финальный ревью.

2021-12-20 21:56 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.num_classes = train_data.num_classes
Смотрю атрибуты `trained_model` в режиме дебага -- и там нет информации о кол-ве классов. Разве что сделать вывод на основании атрибута output_shape, что выглядит даже более костыльно.

2021-12-20 21:57 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +    def wrapper(*args, **kwargs):
> А можно как-нибудь эту проверку адаптировать под тест?

Здесь действительно есть над чем подумать, потому что в идеале проверка должна обладать следующими свойствами:
- Иметь большой охват, чтобы включать как можно больше имплементаций, включая новые добавленные. Сейчас в качестве эдакого мета-теста этот декоратор идеально выполняет свою роль. Другой вопрос, как подключить его исключительно для тестирования -- переопределить класс `Pipeline` или что-то в этом духе.
- Проверка (в текущем виде) должна игнорировать тесты `custom_model_implementation`. Варианты рещения: а) убрать `np.random` из custom_model или б) сделать проверку без множественных вызовов `predict`, но об этом ниже.

> И еще мне кажется, что по нескольку раз запускать метод predict - это не оптимальная стратегия.

Абсолютно согласен. Это первое, что пришло в голову на замену идеи занулять target и смотреть, что сломается, потому что тогда ломается лишнее. 

Мб получится замерять число обращений `n` к `input_data.target` в процессе `predict()` и делать `assert n == 0`. Буду пробовать.

2021-12-20 21:59 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +        #
На самом деле я позабыл про эти комменты, спасибо.
Тут первый вариант проверки -- нигде не закомиченный.

2021-12-20 22:44 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +    def wrapper(*args, **kwargs):
Кажется этот тест вполне можно интегрировать например сюда: https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/models/test_model.py#L112 в явном виде, без декораторов и прочего.

2021-12-23 09:16 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.num_classes = train_data.num_classes
Комментарий в формате FYI:

Сейчас ещё раз посмотрел как происходит расчет в мастере - запускал examples/image_classification_problem.py, только добавил вот такую строчку
```
dataset_to_validate.target = None
```
И всё отработало корректно, - значит Keras модель точно ни при чем. Ну а в целом, не лезу пока что в ревью этого PR, после нашего вчерашнего созвона, думаю, понятно что и как делать и без моих комментариев) (Если появятся вопросы - пиши)

2021-12-23 15:51 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +    def wrapper(*args, **kwargs):
> Кажется этот тест вполне можно интегрировать 

Интегрировал! Туда и не только :)

2021-12-23 15:53 UTC, MorrisNein commented on fedot/core/data/data.py
> +                         task=self.task, data_type=self.data_type)
Убрал ненужные проверки

2021-12-23 15:56 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    model.num_classes = train_data.num_classes
> значит Keras модель точно ни при чем

Охотно верю, интересно, почему мой примёр её сломал, а твой - нет.

2021-12-23 16:13 UTC, nicl-nno approved these changes

2021-12-23 19:14 UTC, Dreamlone approved these changes
Всё ок, но не забудь сделать ребейз, на 3 PR от мастера ветка отстала

2021-12-23 20:19 UTC, MorrisNein commented
> Всё ок, но не забудь сделать ребейз, на 3 PR от мастера ветка отстала

Yep, ty.

2021-12-24 14:49 UTC, MorrisNein commented
Не уверен, почему периодически падают тесты remote. 

Сначала воспроизвёл ошибку локально, а потом при перезапуске конкретного теста она пропала.

Потом перезапустил тесты на сервере, и все успешно выполились.

Вероятно, вопрос для отдельной iasue?

2021-12-24 14:55 UTC, nicl-nno commented
>Не уверен, почему периодически падают тесты remote.

Они требуют правильно установленного working directory, скорее всего дело в этом.

2021-12-24 21:46 UTC, merged