FEDOT Command Line Interface (CLI) prototype
nccr-itmo/FEDOT pull request #519
Opened 2021-12-20 13:26 UTC by ChrisLisbon

FEDOT CLI prototype supports all API parameters, which can be input from the command line.
It provides by running fedot_cli.py with flags described in help. 
Integration tests with imitation of console run was added.

2021-12-20 13:52 UTC, Dreamlone reviewed
А ты специально файлы из cases/industrial удалила? Они вроде для того нужны, чтобы при случае можно было продемонстрировать "нашим индустриальным партнерам" как FEDOT работает на примере вот этих сериализованных моделей

Но в целом, там примеры были для ipnb ноутбуков, а ноутбуки устарели, так что, думаю, в челом industrial надо бы обновить или убрать если никому не нужно
@nicl-nno, присоединяйся к обсуждению

2021-12-20 13:54 UTC, ChrisLisbon commented
> А ты специально файлы из cases/industrial удалила? Они вроде для того нужны, чтобы при случае можно было продемонстрировать "нашим индустриальным партнерам" как FEDOT работает на примере вот этих сериализованных моделей
> 
> Но в целом, там примеры были для ipnb ноутбуков, а ноутбуки устарели, так что, думаю, в челом industrial надо бы обновить или убрать если никому не нужно @nicl-nno, присоединяйся к обсуждению

Я убрала потому что подумала, что это рудимент, тк папка была названа как временные файлы обычно называются у нас. Верну если это ваажная штука.

2021-12-20 13:58 UTC, Dreamlone requested changes

2021-12-20 13:58 UTC, Dreamlone commented on cli_application/fedot_cli.py
> +import argparse
Может cli_application спрятать в fedot, или в fedot/api?

2021-12-20 13:58 UTC, Dreamlone commented on cli_application/fedot_cli.py
> +    :param help: str, help text for parameter
Type hints лучше выше вынести а вот из doctring можно убрать

2021-12-20 13:58 UTC, Dreamlone commented on cli_application/fedot_cli.py
> +        nargs = None
Можно капельку проще
```
if is_list:
    nargs = '*'
else:
    nargs = None
```

2021-12-20 13:58 UTC, Dreamlone commented on fedot/api/main.py
> +            'metric' - metric for quality calculation during composing
Решила все таки не трогать composing_params? Просто они вроде больше api_params, или fedot_params, а не composing. Да и в целом, думаю, можно в рамках этого PR сделать передачу аргументов немного попроще в API - через именованные аргументы 

Плюс еще вопрос: а metric именно для композера здесь, или в том числе и для тюнера?

2021-12-20 14:05 UTC, ChrisLisbon commented on fedot/api/main.py
> +            'metric' - metric for quality calculation during composing
В данном случае именно для композера.
api_params - звучат вроде норм, могу поменять.

эта метрика может быть в виде списка и для нее возвращаются сущности для таска, композера и тюнера
`metric_name = self.api_params['metric_name']`
`self.task_metrics, self.composer_metrics, self.tuner_metrics = self.metrics.get_metrics_for_task(metric_name)`
`self.api_params['tuner_metric'] = self.tuner_metrics`

2021-12-20 14:10 UTC, Dreamlone commented on fedot/api/main.py
> +            'metric' - metric for quality calculation during composing
Окс

2021-12-20 15:21 UTC, ChrisLisbon commented on cli_application/fedot_cli.py
> +import argparse
Перенесла в fedot/api

2021-12-20 15:22 UTC, ChrisLisbon commented on cli_application/fedot_cli.py
> +    :param help: str, help text for parameter
Перенесла

2021-12-20 15:22 UTC, ChrisLisbon commented on cli_application/fedot_cli.py
> +        nargs = None
Поправила

2021-12-20 15:32 UTC, Dreamlone commented on fedot/api/fedot_cli.py
> +print(f"\nPrediction saved at {os.getcwd()}\\predictions.csv")
А это тут пример использования уже идёт? Если так, то его стоит отдельно держать от скрипта, чтобы он запускался при импорте чего-нибудь из этого файла. Ну и пример тогда стоит добавить в examples

2021-12-20 15:34 UTC, ChrisLisbon commented on fedot/api/fedot_cli.py
> +print(f"\nPrediction saved at {os.getcwd()}\\predictions.csv")
Нет, это не пример, это собственно сам запуск федота из выбранных из консоли параметров. Пример есть в интеграционниках.

2021-12-20 15:36 UTC, Dreamlone commented on test/integration/cli_application/cli_call_test.py
> +    """ Test executing regression problem from cli with saving prediction"""
А запуск в unit тестах даже самого коротенького примера с консолью - это слишком дорогое удовольствие? Просто можно было бы просто запустить с параметром predefined_model = 'auto' и api обучил бы всего один пайплайн

2021-12-20 15:38 UTC, ChrisLisbon commented on test/integration/cli_application/cli_call_test.py
> +    """ Test executing regression problem from cli with saving prediction"""
Дело не в дороговизне а в нереализуемости. Тк мы проверяем запуск из консоли, то идет эмуляция этой консоли с созданием отдельного процесса. Git такое не переварит ни при каком варианте.

2021-12-20 15:39 UTC, nicl-nno commented on fedot/api/fedot_cli.py
> +    :param parameters: argparse filtered keys
Если функция ещё и "converts numbers from strings" - то лучше назвать её preprocess_keys или как-то так.

2021-12-20 15:40 UTC, nicl-nno commented on test/integration/cli_application/cli_classification_call.bat
> +set python_path = "DEFAULT"
Может это в expamples? 
Вроде тут никакого тестирования результата нет.

2021-12-20 15:42 UTC, nicl-nno commented on test/integration/cli_application/cli_call_test.py
> +    """ Test executing regression problem from cli with saving prediction"""
Можно обернуть код fedot_cli.py в функцию и протестировать её, подменив консольный ввод, который ты собираешь в parameters.

2021-12-20 15:51 UTC, ChrisLisbon commented on test/integration/cli_application/cli_classification_call.bat
> +set python_path = "DEFAULT"
Ну тут тестирование, что консоль не падает. А example написать довольно сложно потому что сама идея что это просто строка в консоли и задавать ее через файлы сомнительно

2021-12-20 15:54 UTC, ChrisLisbon commented on fedot/api/fedot_cli.py
> +    :param parameters: argparse filtered keys
Поправила

2021-12-20 21:32 UTC, nicl-nno commented
Хорошо бы ещё сделать страничку в документацию с примерами использования. По аналогии с https://fedot.readthedocs.io/en/latest/fedot/features/pipeline_json.html

2021-12-20 21:32 UTC, nicl-nno commented on test/integration/cli_application/cli_classification_call.bat
> +set python_path = "DEFAULT"
В examples могут те  же самые bat-скрипты лежать.

2021-12-23 12:55 UTC, valer1435 commented on cli_application/fedot_cli.py
> +parser.add_argument('--c_tuning',
Может быть сделать это просто необязательным аргументом? 
Кажется проще писать --with_tuning, чем всегда --c_tuning <num>

2021-12-27 16:47 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/cli_application/cli_call_test.py`](https://github.com/nccr-itmo/FEDOT/blob/17a3d2c635710fdf080d437f964760cb34ac06b9/examples/cli_application/cli_call_test.py):

> [Line 57:29](https://github.com/nccr-itmo/FEDOT/blob/17a3d2c635710fdf080d437f964760cb34ac06b9/examples/cli_application/cli_call_test.py#L57): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2021-12-27 16:56 UTC, ChrisLisbon commented on test/integration/cli_application/cli_call_test.py
> +    """ Test executing regression problem from cli with saving prediction"""
Переписала fedot_cli в виде функций и добавила с ними юнит тест (test_api_cli_params.py)

2021-12-27 16:56 UTC, ChrisLisbon commented on test/integration/cli_application/cli_classification_call.bat
> +set python_path = "DEFAULT"
Перенесла в папку examples/cli_application

2021-12-27 17:01 UTC, ChrisLisbon commented on cli_application/fedot_cli.py
> +parser.add_argument('--c_tuning',
Он и так необязательный, если параметр не передается (или передается что либо кроме 1), то по умолчанию становится False

2021-12-27 19:17 UTC, Dreamlone approved these changes
Всё кул, только я бы все таки попросил бы тест немного упростить тест `test_cli_with_parameters`. Я понимаю, что написанные unit тесты хороши потому что позволяют разобраться как запускать FEDOT через консоль, но они работают очень долго - полминуты только на один тест на моем ноуте - долговато. Оставь пример для временного ряда и для классификации. Регрессия во многом дублирует задачу классификации по внешним аргументам (только problem classification нужно поменять на problem regression) 
У меня в таком случае тест отработал за 17 секунд

2021-12-28 10:51 UTC, nicl-nno approved these changes
Добавить страничку документации и норм.

2021-12-28 15:36 UTC, merged