External optimizer support added
nccr-itmo/FEDOT pull request #520
Opened 2021-12-21 13:50 UTC by nicl-nno

Now optimizer can be added as external class derived from Graph optimizer.

Example of random search-based optimizer implemented.

2021-12-23 10:37 UTC, Dreamlone requested changes

2021-12-23 10:37 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +            else self.optimiser.graph_generation_params.adapter.restore(opt_result)
Лучше вынести в отельную функцию кмк

2021-12-23 10:37 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +            self.optimiser_parameters.archive_type = tools.ParetoFront()
archive_type вроде до этого нигде не задаётся, или это так и задумано?
Может тут self.archive_type = None имелось в виду

2021-12-23 10:37 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    Multi-objective evolutionary graph optimiser named GPComp
Docstring описание устарело (archive_type)

2021-12-23 10:37 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +class EvoGraphParameterFreeOptimiser(EvoGraphOptimiser):
Тоже вроде docstring устарели

2021-12-23 11:04 UTC, Dreamlone commented
Есть вопрос про `FixedStructureComposer`, объясни плиз зачем он нужен? Вроде сейчас он нигде не используется, так ещё и  по сути просто взывает метод суперкласса никак его не расширяя

2021-12-24 13:21 UTC, nicl-nno commented on examples/fedot_based_solutions/external_optimizer.py
> +    automl.api_composer.optimiser = RandomSearchOptimizer
Оставил это для будущего рефакторинга API, там много нюансов связанных с тем, что параметры оптимизатора тоже надо типизировать

2021-12-24 14:19 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            self.optimiser_parameters.archive_type = tools.ParetoFront()
archive_type = None убрал

2021-12-24 14:19 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +            else self.optimiser.graph_generation_params.adapter.restore(opt_result)
Вынес.

2021-12-24 14:19 UTC, nicl-nno commented on examples/fedot_based_solutions/external_optimizer.py
> +    def __init__(self, initial_graph: Union[Any, List[Any]],
Немного расширил описание GraphOptimiser и optimize.

2021-12-24 14:19 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +class EvoGraphParameterFreeOptimiser(EvoGraphOptimiser):
Убрал вообще дублирующий базовый класс докстринг.

2021-12-24 14:20 UTC, nicl-nno commented
>Есть вопрос про FixedStructureComposer

Пока убрал, потом перенесу функциональность создания композера, не меняющего структуру, в ComposerBuilder

2021-12-24 14:38 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    Multi-objective evolutionary graph optimiser named GPComp
Удалил описание, дублирующее базовый класс.

2021-12-27 08:04 UTC, Dreamlone requested changes
Я бы предложил добавить тест для внешнего оптимизатора. Что-то вроде, создаётся класс `ConstantOptimizer` (по аналогии с `RandomSearchOptimizer`), который на каждой итерации возвращает одно и то же решение - пайплайн например с операцией linear. И проверить, что после n итераций начальный пайплайн dtreg -> rfr превращается в такой вот простенький или что-то подобное

2021-12-27 08:04 UTC, Dreamlone commented on examples/fedot_based_solutions/external_optimizer.py
> +from typing import Any, Callable, List, Optional, Union
После недавнего PR Валеры структура examples изменилась - нужно перенести этот файл из этой папки в examples/advanced/fedot_based_solutions

2021-12-27 13:06 UTC, nicl-nno commented on examples/fedot_based_solutions/external_optimizer.py
> +from typing import Any, Callable, List, Optional, Union
Перенес

2021-12-27 13:06 UTC, nicl-nno commented
Добавил вот [такой](https://github.com/nccr-itmo/FEDOT/pull/520/commits/014466742a7936c802a2c34c70e1b75e25d0d2c4#diff-d8c13f6fedf419a3219d4c7e63e79d37af2def69c2b57aa8a73ba8280dc2e8bcR1) тест.

2021-12-27 13:27 UTC, Dreamlone approved these changes

2021-12-27 13:28 UTC, Dreamlone commented
Только не забудь ребейз перед мерджем сделать, ветка на один PR отстала

2021-12-27 15:05 UTC, merged