Increasing number of initial assumptions
nccr-itmo/FEDOT pull request #522
Opened 2021-12-26 13:31 UTC by valer1435

Due of increasing number of time series forecasting models number of initial assumptions was increased. 
List of initial assumptions for time series forecasting:
- glm + ridge pipeline
- polyfit + ridge  pipeline
- lagged + ridge pipeline
- ar pipeline

2021-12-26 13:31 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fedot/api/api_utils/api_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/bac7089d240b618275bd2f20711c134e854433c7/fedot/api/api_utils/api_composer.py):

> [Line 306:13](https://github.com/nccr-itmo/FEDOT/blob/bac7089d240b618275bd2f20711c134e854433c7/fedot/api/api_utils/api_composer.py#L306): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2021-12-26 17:06 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        fit_and_check_correctness(initial_pipelines, data, logger=logger)
Мне кажется, тут достаточно проверять только один из пайплайнов - иначе слишком много времени будет уходить на обучение каждого.

2021-12-26 17:25 UTC, nicl-nno commented on fedot/api/main.py
> +            pipelines = [Pipeline(model)]
Тут тоже можно автоматизировать выбор структуры пайплайна по аналогии с тем как сделано для остальных начальных приближений.

2021-12-26 17:26 UTC, nicl-nno commented on fedot/api/main.py
> +        return pipelines[0]
А почему возвращается только один?

2021-12-26 17:45 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
![image](https://user-images.githubusercontent.com/5711814/147416030-c7c6eebd-0cb5-4d2c-8398-ed19bf53db2d.png)

Вот тут тогда должно быть не -1, а -len(initial_pipelines)

2021-12-26 17:46 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _create_randomized_pop_from_inital_graph(self, initial_pipelines: List[Pipeline]) -> List[Individual]:
Сюда вроде уже передается OptGraph, а не Pipeline - поэтому и в названиях дб graph.

2021-12-27 08:34 UTC, Dreamlone requested changes
Доп. вопрос: а как текущая версия отреагирует, если размер популяции будет меньше (например, если пользователь задал количество особей 4), чем количество начальных приближений?

2021-12-27 08:34 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
Раз мы решили, что начальных приближений может быть несколько, то почему бы не предоставить пользователю тоже задавать по несколько штук. Предлагаю добавить здесь ещё проверку на то, является ли initial_pipelines уже списком. Ну и тогда стоит обновить описание в docstring и type hints при необходимости

2021-12-27 08:34 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        builder = builder.with_initial_pipeline(initial_pipelines)
Стоит поменять название метода на `with_initial_pipelines`

2021-12-27 08:34 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            initial_pipeline.fit(data)
Согласен тут с Колей, пока предлагаю проверять только первый пайплайн в списке

2021-12-27 08:34 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +def gaps_imputer(task_type: TaskTypesEnum, has_gaps: bool = False, has_categorical_features: bool = False):
В методе готовятся узлы не только для заполнения пропусков, значит название не совсем соответствует тому, что происходит внутри функции

2021-12-27 08:34 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +    return Pipeline(node_final)
Я бы предложил в пайплайн с авторегрессией ещё добавить узел со сглаживанием

2021-12-27 08:34 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        :param initial_pipelines: Initial assumption for first population
s на конце

2021-12-27 08:34 UTC, Dreamlone commented on fedot/core/pipelines/tuning/hyperparams.py
> +                continue
Лучше 
```
if func is None:
    func = self._random_change
```

2021-12-27 14:00 UTC, valer1435 commented on fedot/api/main.py
> +        return pipelines[0]
Потому что внутри мы оперируем с листом пайплайнов, а в api непосредственно с пайплайном. Издержка коныертирования в list и обратно

2021-12-27 14:03 UTC, valer1435 commented on fedot/api/main.py
> +        return pipelines[0]
А predifined_model по определению единичный объект

2021-12-27 14:24 UTC, valer1435 commented
> Доп. вопрос: а как текущая версия отреагирует, если размер популяции будет меньше (например, если пользователь задал количество особей 4), чем количество начальных приближений?

![image](https://user-images.githubusercontent.com/32017472/147480589-cce3a34e-9932-408b-96b6-18105d7a7d34.png)
pop_size изначально раздувается в 10 раз

2021-12-27 15:09 UTC, nicl-nno commented on fedot/api/main.py
> +        return pipelines[0]
Ок. Тогда надо будет в списках вариантов пайплайнов всегда первым ставить наиболее "универсальный".

2021-12-27 15:12 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
Тогда может стоит сделать задание initial_assumption только списком сразу? Чтобы избежать противоречий и уменьшить кол-во кода

2021-12-27 15:23 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
Выглядит как масштабное изменение, поэтому вызываю @nicl-nno

2021-12-27 15:37 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
BTW, заметил еще, что в некоторых местах в параметрах стоят initial_pipeline, хотя класс может быть использован и для графов. Может быть, чтобы избегать неоднозначностей называть все начальные приближения initial_assumptions, тем самым, не привязываясь к какому-то классу объектов?

2021-12-27 15:54 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
>заметил еще, что в некоторых местах в параметрах стоят initial_pipeline

В оптимизаторе надо использовать терминалогию graph, в композере - пайплайн. В том PR-е, который в мастер влил, это частично уже сделано.

>Тогда может сразу сделать задание initial_assumption только списком

На уровне API лучше давать пользователю свободу действий. Глубже по коду уже можно передавать везде списом.

2021-12-27 20:00 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            initial_pipeline.fit(data)
[Теперь проверяется только первый](https://github.com/nccr-itmo/FEDOT/pull/522/commits/b6a797dee96a5c7965df462bdad5d878c6225e14#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR310-R311)

2021-12-27 20:00 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        fit_and_check_correctness(initial_pipelines, data, logger=logger)
[Теперь проверяется только первый](https://github.com/nccr-itmo/FEDOT/pull/522/commits/b6a797dee96a5c7965df462bdad5d878c6225e14#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR310-R311)

2021-12-27 20:01 UTC, valer1435 commented on fedot/api/api_utils/initial_assumptions.py
> +    return Pipeline(node_final)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/522/commits/17a6a2e77cdb52d33a490b815af0cdf999703e25#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R163-R164)

2021-12-27 20:02 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/522/commits/052381b7112a62a75d29e23e9a865fb3554510d6#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R150)

2021-12-27 20:02 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _create_randomized_pop_from_inital_graph(self, initial_pipelines: List[Pipeline]) -> List[Individual]:
[Поменял](https://github.com/nccr-itmo/FEDOT/pull/522/commits/0dfcbf1ab43b1694e8ec55add745a5aa12e507b2#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R128-R151)

2021-12-27 20:04 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        builder = builder.with_initial_pipeline(initial_pipelines)
[Поменял на with_initial_pipelines](https://github.com/nccr-itmo/FEDOT/pull/522/commits/265977b47903482d23a6f7b1128f4891ea4dd298#diff-f6906db18a4fd897736c04874481a212263670af9322347e1edd0302f87a0bc7R103)

2021-12-27 20:06 UTC, valer1435 commented on fedot/api/main.py
> +            pipelines = [Pipeline(model)]
[Автоматизировал](https://github.com/nccr-itmo/FEDOT/pull/522/commits/265977b47903482d23a6f7b1128f4891ea4dd298#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR384-R393)

2021-12-27 20:07 UTC, valer1435 commented on fedot/api/api_utils/initial_assumptions.py
> +def gaps_imputer(task_type: TaskTypesEnum, has_gaps: bool = False, has_categorical_features: bool = False):
[Поменял название](https://github.com/nccr-itmo/FEDOT/pull/522/commits/265977b47903482d23a6f7b1128f4891ea4dd298#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R101)

2021-12-27 20:09 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        :param initial_pipelines: Initial assumption for first population
[Теперь там graphs](https://github.com/nccr-itmo/FEDOT/pull/522/commits/0dfcbf1ab43b1694e8ec55add745a5aa12e507b2#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R131)

2021-12-27 20:10 UTC, valer1435 commented on fedot/core/pipelines/tuning/hyperparams.py
> +                continue
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/522/commits/15105403d741890dba2dd29bfefb1a4ace8149a5#diff-c5db280c673e554662f25e9cbfbbbae34ecb01db10d9bb3ce93637acc404d61cR59)

2021-12-27 20:12 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = [initial_pipeline]
Решил придерживаться такого разделения: 
Все, что в апи, до попадания в композер - initial_assumption
В композере - initial_pipelines
В оптимизаторе - initial_graphs

2021-12-27 20:36 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +def gaps_imputer(task_type: TaskTypesEnum, has_gaps: bool = False, has_categorical_features: bool = False):
Стоит добавить docstring для понятности

2021-12-28 07:41 UTC, valer1435 commented on fedot/api/api_utils/initial_assumptions.py
> +def gaps_imputer(task_type: TaskTypesEnum, has_gaps: bool = False, has_categorical_features: bool = False):
Поменял еще раз название и [добавил docstring](https://github.com/nccr-itmo/FEDOT/pull/522/commits/8662c490b7430cd05b8178de23c7daaa8cfa3143#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R101-R110)

2021-12-28 09:06 UTC, Dreamlone approved these changes
Оставил небольшое предложение, а так норм

2021-12-28 11:22 UTC, nicl-nno approved these changes
Хорошо бы ещё провести эк-ты на наборе временных рядах чтобы убедиться что нет непредвиденных последствий.

2021-12-28 12:27 UTC, valer1435 commented
> Хорошо бы ещё провести эк-ты на наборе временных рядах чтобы убедиться что нет непредвиденных последствий.

Могу запустить на день-два, а потом, если все ок - влить

2021-12-28 12:28 UTC, valer1435 commented on fedot/api/main.py
> +                                                      )
[Убрал](https://github.com/nccr-itmo/FEDOT/pull/522/commits/b6b319e2d5ee2928d96a906814afb85409e2fe3a#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR382-R383)

2021-12-30 11:54 UTC, Dreamlone commented on examples/simple/time_series_forecasting/ts_pipelines.py
> +    #node_glm.custom_params = {"family": "poisson", "link": "log"}
Стоит удалить комментарий раз задавать гиперпараметры уже не нужно

2021-12-30 11:54 UTC, Dreamlone commented on examples/simple/time_series_forecasting/ts_pipelines.py
> +def ts_fat_ets_pipeline():
Лучше `multiple_ets_pipeline`

2021-12-30 11:54 UTC, Dreamlone commented on fedot/api/main.py
> +        return np.random.choice(pipelines)
Я бы предложил все таки возвращать либо всегда первый пайплайн, потому что обучается и проверяется в  fit_and_check_correctness именно первый в списке. Либо (что не кажется лучшим решением, но это возможно предложение больше на будущее), обучать все пайплайны в списке и возвращать тот, у которого метрика лучше

2021-12-30 19:58 UTC, merged