Improvement of time series processing
nccr-itmo/FEDOT pull request #527
Opened 2021-12-30 16:28 UTC by Dreamlone

In this PR it was added the possibility to supply two time series to the input of the lagged operation. A bug has been fixed that occurred when poly_features was used in a time-series pipeline

2021-12-30 16:32 UTC, Dreamlone commented
@ChrisLisbon Юль, обрати пожалуйста внимание на изменения в sparse_lagged. Мне сейчас показалось, что в текущей версии в мастере, если в пайплайн например sparse_lagged -> ridge подать на вход новые данные, ну например мы используем такой пайплайн в проде где-нибудь и нам нужно давать прогнозы на новых данных каждый день не обучая при этом модель заново
Тогда, насколько я понимаю, возникнут проблемы с тем, что на каждом predict'е, обученная sparse_lagged операция будет обращаться только к последней строке в таблице с предикторами, которую она (модель) видела при обучении пайплайна

2021-12-30 17:35 UTC, nicl-nno approved these changes
Вроде все ок.

2021-12-31 12:33 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`test/unit/data_operations/test_data_operations_implementations.py`](https://github.com/nccr-itmo/FEDOT/blob/805a3992c925bf42a4a259b030169aada2879f4c/test/unit/data_operations/test_data_operations_implementations.py):

> [Line 147:30](https://github.com/nccr-itmo/FEDOT/blob/805a3992c925bf42a4a259b030169aada2879f4c/test/unit/data_operations/test_data_operations_implementations.py#L147): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2021-12-31 13:28 UTC, valer1435 requested changes

2021-12-31 13:28 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                self.operation.fit(features, target[:, 0])
Если у нас не поддерживается прогнозирование нескольких рядов на этом уровне, почему бы не кидать error и заканчивать работу? Мб юзеру будет лучше сразу понять, что так нельзя, чем он получит неочевидный результат и потом начнет разбираться в чем загвоздка

2021-12-31 13:28 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.features_columns = self.features_columns.reshape(1, -1)
Вроде можно заменить на
self.features_columns = self.features_columns[-1].reshape(1, -1)

2021-12-31 13:28 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            last_part_of_ts = last_part_of_ts.reshape(1, -1)
То же

2021-12-31 13:29 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                self.operation.fit(features, target[:, 0])
Или я что-то не так понял?

2021-12-31 13:43 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +                self.operation.fit(features, target[:, 0])
Здесь не про временные ряды, а про алгоритмы рекурсивного отбора признаков. Изменения в этой части подразумевают следующее: теперь из датасетов могут исключаться и бинарные (содержащие 1 и 0 например) признаки, раньше этого не делалось. Тут исключительно обработка таблиц

2021-12-31 13:45 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.features_columns = self.features_columns.reshape(1, -1)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/527/commits/4b36ede2ab4802364d88e3b5b2ca9de59a938e40)

2021-12-31 13:45 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            last_part_of_ts = last_part_of_ts.reshape(1, -1)
Исправил, см. коммит выше

2021-12-31 13:59 UTC, valer1435 approved these changes

2021-12-31 14:03 UTC, merged