Fix initial assumption
nccr-itmo/FEDOT pull request #538
Opened 2022-01-14 13:38 UTC by valer1435

* bug with predefined initial assumption was fixed
* bug with None as default value for cv_folds in api for ts_forecasting  was fixed

2022-01-14 14:00 UTC, Dreamlone requested changes

2022-01-14 14:07 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    timeout = 1
Стоит добавить описание в docstring, потому что тяжело сообразить что тут тестируется

Timeout можно не определять отдельно, вполне себе одна цифра залезет в словарь для composer_params.

2022-01-14 14:07 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    model.composer_params.accept_and_apply_recommendations(model.train_data, recommendations)
А можно как-то избежать вывода одного и того же метода в двух разных местах с одними и теми же аргументами?

2022-01-14 14:19 UTC, valer1435 commented on fedot/api/api_utils/params.py
> +            self.api_params['cv_folds'] = None  # there are no support for muttimodal data now
[Там буквально стоит NotImplememntError](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/composer/gp_composer/gp_composer.py#L153)

2022-01-14 14:19 UTC, nicl-nno requested changes

2022-01-14 14:22 UTC, valer1435 commented on test/unit/api/test_api_utils.py
> +    model.composer_params.accept_and_apply_recommendations(model.train_data, recommendations)
Это разные методы, просто у разных классов

2022-01-14 14:39 UTC, Dreamlone commented on fedot/api/api_utils/params.py
> +            self.api_params['cv_folds'] = None  # there are no support for muttimodal data now
Лол, на будущее (не в рамках этого PR) - я думаю мы вплотную уже подошли к тому, чтобы поддерживать кросс-валидацию с мультимодальными данными

2022-01-14 14:40 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    model.composer_params.accept_and_apply_recommendations(model.train_data, recommendations)
Точно, сорри, вопрос снят

2022-01-15 12:42 UTC, valer1435 commented on fedot/api/api_utils/params.py
> +            params['validation_blocks'] = 1
[Поставил 2](https://github.com/nccr-itmo/FEDOT/pull/538/commits/245551f82920fd148c4d7f639c5e54f282390678#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R128)

2022-01-15 12:42 UTC, valer1435 commented on fedot/api/api_utils/params.py
> -                return self.change_preset_for_label_encoded_data(input_data.task)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/245551f82920fd148c4d7f639c5e54f282390678#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R91)

2022-01-15 12:43 UTC, valer1435 commented on fedot/api/api_utils/params.py
> +            self.api_params['cv_folds'] = None  # there are no support for muttimodal data now
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/245551f82920fd148c4d7f639c5e54f282390678#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R85)

2022-01-15 12:44 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        :param optimiser: otimiser for composor
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/c7676ce33144497b0a811c317cc20b824316625e#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR100)

2022-01-15 12:44 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        :param optimiser: otimiser for composor
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/c7676ce33144497b0a811c317cc20b824316625e#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR100)

2022-01-15 12:45 UTC, valer1435 commented on test/unit/api/test_api_utils.py
> +    timeout = 1
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/245551f82920fd148c4d7f639c5e54f282390678#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R68)

2022-01-15 12:47 UTC, valer1435 commented on fedot/api/main.py
> +        self.api_params = {**self.api_params, **self.composer_params.api_params}
Вообще система с api_params и composer_params была очень непонятной (composer_params класса ApiParams, например) + он нигде не использовался по-существу. Поэтому заменил composer_params на params, а в нем уже лежит api_params

2022-01-16 16:35 UTC, Dreamlone requested changes

2022-01-16 16:35 UTC, Dreamlone commented on fedot/api/api_utils/params.py
> +            params['validation_blocks'] = 2
А зачем тут в двух if-проверках ts_forecasting? Заодно мне кажется всё таки можно во втором случае обойтись просто сравнением `elif problem == 'ts_forecasting'`

2022-01-16 16:35 UTC, Dreamlone commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
А почему всё таки решил убрать initial_assumption из параметров? Вроде довольно важный - его бы на ряду с timeout позволить пользователю задавать как напрямую, так и через composer_params

2022-01-17 08:02 UTC, valer1435 commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
Можно, но тогда будет неопределенность - какой initial_assumption брать за настоящее начальное приближение. Кажется, что это все-таки больше относится к композированию, чем к API

2022-01-17 08:13 UTC, Dreamlone commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
Можно делать как с timeout, тот, который задаётся через аргумент всегда будет приоритетным. По сути, так и было сделано (и на данный момент реализовано в мастере), в общем, я за то, чтобы предоставлять пользователю выбор, задавать через словарь или передавать напрямую. Плюс стоит всегда с большой осторожностью изменять параметры в API - это же фасад для всей библиотеки, чуть немного изменил, и сломал обратную совместимость версий. Моё предложение: откати плиз эту часть как было, потом уже отдельным PR будем рефакторить параметры в API (а это скорее всего придётся сделать)

2022-01-17 09:57 UTC, valer1435 commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
[Вернул](https://github.com/nccr-itmo/FEDOT/pull/538/commits/27df06c068f7807406346379dd25dd5f9cc2fe4a#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR81-R83)

2022-01-17 09:57 UTC, valer1435 commented on fedot/api/api_utils/params.py
> +            params['validation_blocks'] = 2
[Переделал ](https://github.com/nccr-itmo/FEDOT/pull/538/commits/cf1cb08144135882720e03b4b0756e29ad2b4b96#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8R125-R129)

2022-01-17 09:59 UTC, nicl-nno approved these changes

2022-01-17 10:09 UTC, Dreamlone commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
Лучше это делать через метод update_params

2022-01-17 11:15 UTC, valer1435 commented on fedot/api/main.py
> -                 initial_assumption: Union[Pipeline, List[Pipeline]] = None,
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/538/commits/ec7fcc00045c05fec633eb20a42ab07b903279b8#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR334-R338)

2022-01-17 12:30 UTC, Dreamlone approved these changes

2022-01-17 12:31 UTC, merged