add ability to add external parameters for optimizer
nccr-itmo/FEDOT pull request #542
Opened 2022-01-26 10:49 UTC by valer1435

With this pull-request we add ability to add external parameters for a custom optimizer

2022-01-26 10:49 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`test/unit/optimizer/test_external.py`](https://github.com/nccr-itmo/FEDOT/blob/ab09247f4ec0f6f015411f68cd74adce84d86005/test/unit/optimizer/test_external.py):

> [Line 76:1](https://github.com/nccr-itmo/FEDOT/blob/ab09247f4ec0f6f015411f68cd74adce84d86005/test/unit/optimizer/test_external.py#L76): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-01-26 13:04 UTC, Dreamlone requested changes
А планируем в итоге добавлять именованные аргументы в исходный класс оптимизатора? (Если что - я бы предложил всё так сделать)

2022-01-26 13:04 UTC, Dreamlone commented on test/unit/optimizer/test_external.py
> +def test_external_static_optimizer_with_external_parameters(data_fixture, request):
Этот тест практически полностью дублирует `test_external_static_optimizer`, лучше тогда `test_external_static_optimizer` и убрать, оставить только этот

2022-01-26 13:32 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +                                               optimizer_external_parameters=self.optimizer_external_parameters,
Они передаются не в composer_params, а через api_composer. Так же, как мы вставляем кастомный оптимайзер

2022-01-26 13:40 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                                               optimizer_external_parameters=self.optimizer_external_parameters,
Вник в тест, и правда. Давай лучше их будем всё таки через composer_params передавать и также с Optimizer'м

2022-01-27 10:20 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +                                               optimizer_external_parameters=self.optimizer_external_parameters,
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/542/commits/4f9c62ab2c4d15e0ec92373de1d95f00af5ad135#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR209-R213)передается через параметры

2022-01-27 10:21 UTC, valer1435 commented on test/unit/optimizer/test_external.py
> +def test_external_static_optimizer_with_external_parameters(data_fixture, request):
Оставил [один ](https://github.com/nccr-itmo/FEDOT/pull/542/commits/4f9c62ab2c4d15e0ec92373de1d95f00af5ad135#diff-d8c13f6fedf419a3219d4c7e63e79d37af2def69c2b57aa8a73ba8280dc2e8bcR46-R47)тест

2022-01-27 10:24 UTC, nicl-nno commented on test/unit/optimizer/test_external.py
> +        if 'external_parameters' in dir(self):
Может просто задать поле в базовом классе и проверять на None? Ну или через args/kwargs в конструкторе.

А то так не очень ООП-шно выглядит.

2022-01-27 13:32 UTC, Dreamlone reviewed
Поддерживаю [комментарий Коли](https://github.com/nccr-itmo/FEDOT/pull/542/files#r793463194) по поводу именованных аргументов в композере. Пусть лучше словарём передаются

2022-01-27 13:32 UTC, Dreamlone commented on examples/simple/time_series_forecasting/api_foresacting.py
> +    test_target = np.ravel(test_data.target)
test_target не используется

2022-01-27 16:21 UTC, valer1435 commented on test/unit/optimizer/test_external.py
> +        if 'external_parameters' in dir(self):
Вообще можно было бы под каждый оптимизатор предлагать писать  свой GraphGenerationParams. Но с @Dreamlone посчитали, что это выглядит не слишком дружелюбно для пользователя. Такой вариант, наверное, был бы самым правильным с точки зрения ООП, но так неудобно. А разделение параметров на GPGraphOptimiserParameters и какие-то external_params само по себе не очень вяжется с логикой отдельных классов параметров. Понятно, что речь сейчас не про dir, это действительно, не самое удачное решение. Пытаюсь посмотреть более глобально. Может быть найдется более изящное решение

2022-01-27 16:55 UTC, valer1435 commented on test/unit/optimizer/test_external.py
> +        if 'external_parameters' in dir(self):
[Переделал ](https://github.com/nccr-itmo/FEDOT/pull/542/commits/7e86433c3e3548c7d9bc2a4ecd2deb421c9d5433#diff-9680f0ba0da76fbbcfbda0b6a66054b5a23d34d28a4c0b94c694bae35d44abb6R108-R109)с помощью именованных аргументов

2022-01-27 16:56 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_foresacting.py
> +    test_target = np.ravel(test_data.target)
[Убрал](https://github.com/nccr-itmo/FEDOT/pull/542/commits/7e86433c3e3548c7d9bc2a4ecd2deb421c9d5433#diff-0728671d7b586e7827df689575a65071a9fc14b4df62f14cafe8b6fb10520af8R35-R36)

2022-01-27 17:56 UTC, nicl-nno approved these changes

2022-01-28 07:02 UTC, Dreamlone approved these changes
Только поправь PEP8

2022-01-28 08:07 UTC, merged