add isolation_forest preprocessing
nccr-itmo/FEDOT pull request #544
Opened 2022-01-27 09:08 UTC by maypink

2022-01-27 09:15 UTC, nicl-nno requested changes

2022-01-27 09:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(False)
Можно eghjcnbnm до mask.append(pred == 1)

2022-01-27 09:15 UTC, nicl-nno commented on examples/simple/classification/classification_isolation_forest
> +import numpy as np
Файл не .py

Да и отдельный пример для новой модели не особо нужен.

2022-01-27 09:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Filtering Algorithm: didn't fit correctly. Return all objects")
Cтоит указать название модели в сообщении.

2022-01-27 09:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +            modified_input_data = copy(input_data)
А тут действительно нужно дополнительно копировать данные, если они не изменялись?

2022-01-27 09:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                modified_input_data = copy(input_data)
Можно это код вынести в начало метода, чтобы не дублировать дважды.

2022-01-27 09:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _get_inlier_mask(self, input_data):
Лучше прописать type hint-ы для большей понятности.

2022-01-27 09:19 UTC, Dreamlone commented on examples/simple/classification/classification_isolation_forest
> +import numpy as np
Это я попросил пока сделать, перед мержом в мастер удалим. Но для того, чтобы можно было позапускать считаю вполне его полезным

2022-01-27 09:34 UTC, Dreamlone requested changes
Ещё немного пожеланий: 
1) Стоит добавить описание на английском к этому PR
2) Стоит добавить в [search_space](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/search_space.py) границы гиперпараметров для новой операции

P.S. Концептуально пока что ещё не проверял алгоритм, позапускаю и проверю корректность логики чуть позже

2022-01-27 09:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +class IsolationForestImplementation(FilterImplementation):
Можешь тут унаследовать класс от DataOperationImplementation. Всё равно он переопределяет методы FilterImplementation класса. В данном случае не будет никакого профита от наследования

2022-01-27 09:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +            self.operation = IsolationForest()
По поводу дефолтных параметров. Предлагаю позапускать на разных размерах датасета - убедиться, что гиперпараметры по умолчанию не вызывают ошибки.  И в целом это поможет убедиться, что реализация алгоритма удалась. Примерные варианты: 1) таблица с одним столбцом и 100 объектами, 2) таблица с двумя столбцами и 20 объектами (я как-то и на таких данных FEDOT запускал)

Пример: значение ubgthgfhfvtnh

2022-01-27 09:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def predict(self, input_data):
А predict метод где-то используется?

2022-01-27 09:55 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +class IsolationForestImplementation(FilterImplementation):
мы уже исправляли на наследование от DataOperationImplementation, в таком случае надо определять get_params

2022-01-27 10:02 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def predict(self, input_data):
Та же просьба относится и к комментариям остальных ревьюеров. По хорошему стоит соблюдать принцип "кто оставил комментарий - тот его и закрывает при необходимости"

2022-01-27 10:07 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +class IsolationForestImplementation(FilterImplementation):
Да, но как мне кажется, что ничего страшного в этом нет - в конце концов для других имплементаций все равно приходится определять метод get_params. Класс FilterImplementation реализован как предок именно для RANSAC алгоритмов и опирается на интерфейс RANSAC моделей при реализации методов.

2022-01-27 10:19 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py`](https://github.com/nccr-itmo/FEDOT/blob/348cfc22b6f748c6ddff017404f9aadb28c995af/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py):

> [Line 192:17](https://github.com/nccr-itmo/FEDOT/blob/348cfc22b6f748c6ddff017404f9aadb28c995af/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py#L192): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented
> [Line 240:1](https://github.com/nccr-itmo/FEDOT/blob/348cfc22b6f748c6ddff017404f9aadb28c995af/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py#L240): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-01-27 10:28 UTC, Dreamlone requested changes
Можно ещё протестировать как тюнинг работает с новой операцией

2022-01-27 10:28 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        inner_features = features
Вроде тут нет необходимости объявлять inner_features, все равно ниже перезаписывается

2022-01-27 10:28 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(pred == 1)
При работе с numpy массивами старайся использовать векторизованные операции. Здесь например цикл можно заменить одной строчкой `mask = predictions == 1`

2022-01-27 10:47 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(pred == 1)
![image](https://user-images.githubusercontent.com/57305249/151344081-e1a2e4b9-7278-4d4d-b2ce-fc773fe52b47.png)

2022-01-27 10:48 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        inner_features = features
Если маска None, то не перезаписываются

2022-01-27 11:16 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(pred == 1)
Numpy массив, не список

2022-01-27 12:31 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        inner_features = features
Я посмотрел ниже и так производится прореживание данных в методе _update_data. Вроде тогда можно вообще обойтись без строк с `inner_features`

2022-01-27 13:05 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +            self.operation = IsolationForest()
позапускала, там все ок, ничего не падает

2022-01-27 13:57 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def predict(self, input_data):
[теперь используется](https://github.com/nccr-itmo/FEDOT/pull/544/commits/348cfc22b6f748c6ddff017404f9aadb28c995af#:~:text=predictions%20%3D%20self.predict(input_data))

2022-01-27 14:00 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        inner_features = features
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/be4c976863850c76d48ffb4db72d70bb839e8e3b#:~:text=%22%22%22-,features%20%3D%20input_data.features,-modified_input_data%20%3D%20input_data)

2022-01-27 14:01 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(pred == 1)
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/be4c976863850c76d48ffb4db72d70bb839e8e3b#:~:text=mask%20%3D%20predictions%20%3D%3D%201)

2022-01-27 14:12 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                mask.append(False)
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/be4c976863850c76d48ffb4db72d70bb839e8e3b#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R183)

2022-01-27 14:13 UTC, maypink commented on examples/simple/classification/classification_isolation_forest
> +import numpy as np
done

2022-01-27 14:14 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Filtering Algorithm: didn't fit correctly. Return all objects")
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/348cfc22b6f748c6ddff017404f9aadb28c995af#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R216)

2022-01-27 14:15 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +            modified_input_data = copy(input_data)
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/be4c976863850c76d48ffb4db72d70bb839e8e3b#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R186-R208)

2022-01-27 14:15 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                modified_input_data = copy(input_data)
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/be4c976863850c76d48ffb4db72d70bb839e8e3b#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R186-R208)

2022-01-27 14:33 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _get_inlier_mask(self, input_data):
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/72d73eddec37fc81dec2b0e7bc20bb827122a6c9)

2022-01-27 14:34 UTC, Dreamlone requested changes

2022-01-27 14:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
Добавь ещё плиз в конструктор этого класса такую строчку `self.params = params`, а то PyCharm ругается что поле не было ранее объявлено 
![image](https://user-images.githubusercontent.com/52418437/151377467-5801f6e3-47f2-4d82-b293-bf8f00d9d30d.png)

Плюс стоит проверить не меняется ли in-place InputData при такой обработке. Тут два варианта: либо можно обойтись без назначения ссылки на input_data в переменную modified_input_data и работать сразу с input_data, либо может потребоваться deepcopy

2022-01-27 14:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def predict(self, input_data):
Формально - да. Но можно ещё проще: можно же напрямую вызывать метод predict у операции sklaern'а, а не опосредованно. Например в `_get_inlier_mask` методе можно написать `self.operation.predict(input_data.features)` вместо `self.predict(input_data)`

2022-01-27 14:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Isolation Forest: didn't fit correctly. Return all objects")
У класса DataOperationImplementation вроде не определено поле log в __init__ методе. Надо объявить `self.log = default_log(__name__)` в конструкторе

2022-01-27 14:34 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _update_data(input_data, mask):
Этот метод можно трансформировать в функцию. Так уменьшится дублирование кода в классах FilterImplementation и IsolationForestImplementation

2022-01-27 14:34 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'max_features': (hp.uniform, [0.05, 1.01]),
n_estimators можно убрать
А max_features точно может быть больше 1.0? Может быть надёжнее 0.99 сделать. 
Кстати это хорошая возможно позапускать тюнер на пайплайне с новореализованной операцией в своей структуре и проверить

2022-01-27 14:44 UTC, Dreamlone commented
Есть ещё вопрос про применимость данной операции к различным задачам (классификации и регрессии): судя по [документации](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.IsolationForest.html), там base_estimator_ - ExtraTreeRegressor. Нет ли каких-то ограничений из-за того, что алгоритм по сути решает задачу классификации как задачу регрессии

P.S. Небольшое уточнение: в FEDOT есть предобработка, которая трансформирует при решении задачи классификации метки из например `da` и `net` в `0` и `1` поэтому чисто теоретически ошибок применение ExtraTreeRegressor при обучении алгоритма отсева выбросов возникать не должно. Но сможет ли алгоритм работать адекватно, когда есть например дисбаланс классов. Например, бинарная классификация - 0: 950 объектов, 1: 50 объектов и тут IsolationForest решит отбросить все объекты, относящиеся к первому классу. Алгоритм отсева выбросов для классификации по идее должен бы как-то это учитывать, но тут у нас ExtraTreeRegressor

2022-01-27 14:55 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Isolation Forest: didn't fit correctly. Return all objects")
на коммент выше, ответить нельзя, пишу здессс
мне просто кажется, что наоборот хорошо, если у этого класса будет публичный метод predict, удобнее пользоваться, если кто-то будет ковырять

2022-01-27 14:59 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _update_data(input_data, mask):
в этот же файл до классов?

2022-01-27 15:01 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _update_data(input_data, mask):
Ага, только лучше функции все пониже снести после классов как раз

2022-01-27 15:05 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
так если мы заходим в _update_data, то нам все равно, будет ли меняться input_data, тк дальше мы будем юзать ток modified
а если не заходим, то input data и не поменяется, нет?(

2022-01-27 15:15 UTC, maypink commented on fedot/core/pipelines/tuning/search_space.py
> +                'max_features': (hp.uniform, [0.05, 1.01]),
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/e40a456ddd9817d73c4e5032a30bb715eb0985c3#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7L203-R203)

2022-01-27 15:16 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def _update_data(input_data, mask):
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/e40a456ddd9817d73c4e5032a30bb715eb0985c3#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R202-R212)

2022-01-27 15:16 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Isolation Forest: didn't fit correctly. Return all objects")
[этот комм done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/e40a456ddd9817d73c4e5032a30bb715eb0985c3#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R139)

2022-01-27 15:35 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Isolation Forest: didn't fit correctly. Return all objects")
> мне просто кажется, что наоборот хорошо, если у этого класса будет публичный метод predict, удобнее пользоваться, если кто-то будет ковырять

Implementation - очень низкоуровневая обвязка. Настолько низкоуровневая для пользователей, что ниже абстракции Node не зашёл пока ёще никто, а разработчики owner'ы, которые будут работать с кодом думаю, разберутся. В общем против призрачных "удобнее пользоваться кому-то" я предлагаю убрать лишние строки, что сделает код более "линейным" (проще и понятнее, если угодно) здесь и сейчас, заодно сократится количество обвязок до вызова predict (их и так немало)

2022-01-27 15:53 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def fit(self, input_data: InputData) -> 'NonLinearRegRANSACImplementation':
Возвращает метод не NonLinearRegRANSACImplementation

2022-01-27 15:53 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        return self
Лучше return  self.operation

2022-01-27 15:55 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
Чекнул сейчас, ты права. Copy и правда в update_data достаточно. Правда в таком случае нет необходимости в строчке `modified_input_data = input_data` в методе transform, пусть лучше везде будет input_data

2022-01-27 16:44 UTC, nicl-nno approved these changes

2022-01-28 09:32 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        return self
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/1a10cb7234285ae07031a13210ab24279515a18f#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R155)

2022-01-28 09:32 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def fit(self, input_data: InputData) -> 'NonLinearRegRANSACImplementation':
[oops](https://github.com/nccr-itmo/FEDOT/pull/544/commits/1a10cb7234285ae07031a13210ab24279515a18f#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R146)

2022-01-28 09:32 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.log.info("Isolation Forest: didn't fit correctly. Return all objects")
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/1a10cb7234285ae07031a13210ab24279515a18f#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R164)

2022-01-28 09:33 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/1a10cb7234285ae07031a13210ab24279515a18f#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R181)

2022-01-28 09:33 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +    def predict(self, input_data):
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/1a10cb7234285ae07031a13210ab24279515a18f#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R164)

2022-01-28 10:18 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'max_features': (hp.uniform, [0.05, 0.99]),
Ещё внимательно полазил по документации, имеет смысл добавить `max_samples`, диапазон можно задать от 0.05 до 0.99

2022-01-28 11:53 UTC, maypink commented on fedot/core/pipelines/tuning/search_space.py
> +                'max_features': (hp.uniform, [0.05, 0.99]),
[done](https://github.com/nccr-itmo/FEDOT/pull/544/commits/3c03cf81bb21ea47029c5e36e7fdcaeca90fa8e2#diff-2e757189efed106001507ee9fb93df8a34d81ecec4728aaddf402c28b5c44ea7R203)

2022-01-28 12:55 UTC, Dreamlone requested changes

2022-01-28 12:55 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +            if mask is not None:
mask не может быть None в текущей реализации

2022-01-28 12:55 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
Вроде в аналогичном методе отказались от такой комбинации

2022-01-28 13:07 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        modified_input_data = input_data
так здесь же надо сохранять и сами данные, и их модифицированную версию, чтобы сравнивать далее. как без модифайд даты обойтись...

2022-01-28 13:31 UTC, Dreamlone approved these changes
Удаляй `examples/simple/classification/classification_isolation_forest.py` и можешь вливать в мастер
Ну и про PEP8 не надо забывать

2022-01-28 13:41 UTC, merged