545 finding nodes for an intermediate task in pipeline
nccr-itmo/FEDOT pull request #547
Opened 2022-01-31 11:54 UTC by maypink

Implementation of a method that returns the last (root) regression node in pipeline

2022-01-31 11:54 UTC, pep8speaks commented
Hello @maypink! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/simple/classification/classification_pipelines.py`](https://github.com/nccr-itmo/FEDOT/blob/6e6e7e63a9cfa9783f8b810240cb64b2a8906ef2/examples/simple/classification/classification_pipelines.py):

> [Line 234:1](https://github.com/nccr-itmo/FEDOT/blob/6e6e7e63a9cfa9783f8b810240cb64b2a8906ef2/examples/simple/classification/classification_pipelines.py#L234): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-01-31 12:29 UTC, nicl-nno requested changes

2022-01-31 12:29 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
Тут нужно указывать тип задачи для поиска - ведь не обязательно именно регрессия нужна.

Также, я бы не выдавал тут низкоуровневую Node, а формировал новый Pipeline, в котором есть только нужная часть узлов. Это позволит использовать высокоуровневые функции вроде fit/predict более удобно.

Ну и соответственно семантика названия метода должна быть немного другой.

2022-01-31 12:29 UTC, nicl-nno commented on examples/simple/classification/classification_with_regression.py
> +import numpy as np
Вроде в этом примере добавленный метод никак не используется?

2022-01-31 12:29 UTC, nicl-nno commented on examples/simple/classification/classification_pipelines.py
> +def classification_with_regression_pipeline():
Хорошо бы проверить ещё и на примере, где классификация и регрессия объединяются без узла decompose/

2022-01-31 12:30 UTC, Dreamlone requested changes

2022-01-31 12:30 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
Стоит добавить docstring. 

Плюс немного моих соображений: в будущем лучше сделать не поиск последнего регресионного узла, а более общо: поиск root узла побочной ветки. Например при итеративном улучшении ошибки в регрессии посмотреть какие прогнозы выдаёт регресионный узел для моделирования ошибок лично было бы интересно (даже мб для статьи по временным рядам пригодится). Но я не уверен, что это полезно здесь и сейчас (в целом, @nicl-nno, можешь высказать свои соображения).

В любом случае, стоит свойство немного по другому назвать, в духе "side_root_node"

2022-01-31 12:30 UTC, Dreamlone commented on examples/simple/classification/classification_with_regression.py
> +    run_classification_tuning_experiment(pipeline=classification_with_regression_pipeline(),
Пример стоит упростить, здесь много всего лишнего: не нужен тюнинг, не нужно засекать метрики, можно просто показать, что после обучения пайплайн при обращении к свойству "последнего промежуточного root узла" выдаёт корректный номер узла

Даже лучше адаптировать то что я выше написал не в пример, а как unit-тест сделать. Можешь его разместить в test/unit/pipelines/test_decompose_pipelines.py, заодно можешь поглядеть как там тесты организованы как примеры

2022-01-31 12:41 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
'нужная часть узлов' == все узлы до найденного?

2022-01-31 12:43 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
Ну да, все его предки.

2022-01-31 12:43 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
Учитывая Колин комментарий 

> Также, я бы не выдавал тут низкоуровневую Node, а формировал новый Pipeline, в котором есть только нужная часть узлов. Это позволит использовать высокоуровневые функции вроде fit/predict более удобно.

думаю действительно лучше будет возвращать пайплайн, а не идентификатор узла. Стоит не забыть передать препроцессор в формируемый пайплайн

2022-01-31 14:45 UTC, Dreamlone commented on examples/simple/classification/classification_pipelines.py
> +def classification_with_regression_pipeline():
А в этом вообще есть смысл? Пайплайн получается невалидным без decompose операции, следовательно, его нельзя обучить, а значит и применять поиск по нему не требуется

2022-01-31 14:47 UTC, nicl-nno commented on examples/simple/classification/classification_pipelines.py
> +def classification_with_regression_pipeline():
Я имею в виду ситуации, как в молочном примере - когда сначала решается задача А, потом задача Б.

2022-01-31 14:58 UTC, Dreamlone commented on examples/simple/classification/classification_pipelines.py
> +def classification_with_regression_pipeline():
А, всё, понял
@maypink, можешь собрать [подобный мультимодальный](https://github.com/ITMO-NSS-team/milk-project/blob/multitask/fedot_example2.py) пайплайн и подготовить для него тест, это проверяющий. Разместить его можешь в [test/unit/multimodal/test_multimodal.py](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/multimodal/test_multimodal.py)

2022-01-31 16:05 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/7be0095cf707c674c30477d875b781a74bd79ab0#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR315-R322)

2022-01-31 16:05 UTC, maypink commented on examples/simple/classification/classification_with_regression.py
> +import numpy as np
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/7be0095cf707c674c30477d875b781a74bd79ab0#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R104-R119)

2022-01-31 16:06 UTC, maypink commented on examples/simple/classification/classification_pipelines.py
> +def classification_with_regression_pipeline():
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/7be0095cf707c674c30477d875b781a74bd79ab0#diff-0cbb1a85cc6ff8196da97b9f80f2c26101bae5ea6cd0d6c0b1459f70bf9272ecR69-R74)

2022-01-31 16:06 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/7be0095cf707c674c30477d875b781a74bd79ab0#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR315-R332)

2022-01-31 16:08 UTC, maypink commented on examples/simple/classification/classification_with_regression.py
> +    run_classification_tuning_experiment(pipeline=classification_with_regression_pipeline(),
те удалила, новые [here](https://github.com/nccr-itmo/FEDOT/pull/547/commits/7be0095cf707c674c30477d875b781a74bd79ab0#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R104-R132)

2022-01-31 16:22 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
Ок. Можно назвать метод pipeline_for_side_task для простоты.

Ну и как Миша писал надо ещё препроцессор перенести в новый пайплайн.

2022-01-31 16:50 UTC, nicl-nno commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
А разве в этом пайплайне есть регрессионная часть?

2022-01-31 16:56 UTC, nicl-nno commented on test/unit/pipelines/test_decompose_pipelines.py
> +    reg_pipeline.preprocessor = pipeline.preprocessor
Вот это должно внутри метода делаться

2022-01-31 16:57 UTC, nicl-nno commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
Надо бы проверить, что результат отличается от  predict-а основного пайплайна.

2022-02-01 09:09 UTC, maypink commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
может дело в самом алгосе поиска, но он ищет по полю 'tasks' у операции. у scaling стоит custom_preprocessing 
![image](https://user-images.githubusercontent.com/57305249/151940679-e3a3cffc-242f-4d05-9892-db89758836e7.png)

2022-02-01 09:27 UTC, Dreamlone commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
Вроде вся идея как раз в том, чтобы протестировать может ли работать алгоритм поиска side root узла на мультимодальном пайплайне, которые одновременно решает две разные задачи - например классификацию и регрессию. В данном примере такого многозадачности нет, но есть разные источники данных - а это не совсем то, что нам нужно. Надо, чтобы одна часть решала задачу классификации, а другая - задачу регрессии. Приоритетность задачи определяется исходя из флага is_main_task в SupplementaryData

2022-02-01 09:29 UTC, maypink commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
я бы наверно не считала операции, у которых больше одной задачи в поле tasks, тк если длина пайплайна >1, то дальше будет стоять нода, решающая конкретную задачу

2022-02-01 10:01 UTC, nicl-nno commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
Также есть смысл при проверке учитывать только модели, а не операции предобработки.

2022-02-01 10:13 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +    def last_reg_node(self) -> Optional[Node]:
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/860c282af645a25219b52339b4a594c7d5c35be0#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR315-L332)

2022-02-01 10:16 UTC, maypink commented on test/unit/pipelines/test_multi_modal.py
> +    pipeline = generate_multi_modal_pipeline()
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/860c282af645a25219b52339b4a594c7d5c35be0#diff-0cbb1a85cc6ff8196da97b9f80f2c26101bae5ea6cd0d6c0b1459f70bf9272ecR46-R65)

2022-02-01 10:17 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +def test_pipeline_predict():
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/860c282af645a25219b52339b4a594c7d5c35be0#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R122)

2022-02-01 10:17 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +    reg_pipeline.preprocessor = pipeline.preprocessor
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/860c282af645a25219b52339b4a594c7d5c35be0#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR331)

2022-02-01 10:17 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/860c282af645a25219b52339b4a594c7d5c35be0#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R137)

2022-02-01 10:27 UTC, Dreamlone commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert reg_pipeline.nodes[0] is pipeline.nodes[1]
Лучше здесь не индексы использовать, а 1) у reg_pipeline обращаться к root узлу и запрашивать название операции в виде строки (вроде через reg_pipeline.root_node.operation.operation_type) и сравнивать с уже заранее заготовленным в тесте лейблом, записанном в переменную. - так проще в нём разбираться будет

2022-02-01 11:06 UTC, Dreamlone commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert reg_pipeline.nodes[0] is pipeline.nodes[1]
Кстати docstring стоит обновить, здесь не возвращается пайплайн же

2022-02-01 11:15 UTC, Dreamlone commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
А так точно можно сравнивать numpy массивы? 
Например мой вариант 
```
import numpy as np
reg_predicted_labels = np.array([1, 1, 1])
predicted_labels = np.array([1, 1, 1])

print(reg_predicted_labels is not predicted_labels)
```
выдал мне True, хотя, очевидно, массивы полностью идентичны по содержащимся в них значениях. Тут конечно OutputData сравниваются, а не массивы, но всё равно недоверяэ - проверь эту конструкцию пожалуйста

2022-02-01 11:26 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
мне кажется, все ок ![image](https://user-images.githubusercontent.com/57305249/151960377-31bec977-8596-4d33-b559-9ea78b5022cd.png)

2022-02-01 11:52 UTC, Dreamlone commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
Ну вот смотри на ячейку 107: массивы одинаковые, но проверка говорит, что все нормально, что "предсказания отличаются"

2022-02-01 13:35 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert reg_pipeline.nodes[0] is pipeline.nodes[1]
[docstring](https://github.com/nccr-itmo/FEDOT/pull/547/commits/22ca87eccbf4377c10e104fedd893506eaf32f3c#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R106)
[остальное](https://github.com/nccr-itmo/FEDOT/pull/547/commits/22ca87eccbf4377c10e104fedd893506eaf32f3c#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R117-R122)

2022-02-01 13:35 UTC, maypink commented on test/unit/pipelines/test_decompose_pipelines.py
> +    assert predicted_labels is not None
[done](https://github.com/nccr-itmo/FEDOT/pull/547/commits/22ca87eccbf4377c10e104fedd893506eaf32f3c#diff-d76a43642a9da593609484ab135b70fe969192cdae5768d45b24f41b5f752cf7R142)

2022-02-01 14:08 UTC, Dreamlone requested changes

2022-02-01 14:08 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +                    and node.operation.metadata.supported_strategies not in preprocessing_strategies \
Подожди, зачем здесь preprocessing_strategies?) По моему лучше отсекать узлы предобработки по классу, является ли модель объектом класса Model, или объектом класса DataOperation, или в крайнем случае ввести подходящий тег

2022-02-01 14:33 UTC, Dreamlone approved these changes
В целом, вроде всё ок, по крайне мере по моей части комментариев

2022-02-01 15:47 UTC, merged