Updated _is_greater_better logic
nccr-itmo/FEDOT pull request #550
Opened 2022-02-01 12:46 UTC by gorokhovnik

2022-02-01 12:49 UTC, nicl-nno commented
Это к #549 ? 

А можно данное поведение проверить каким-то тестом?

2022-02-01 13:17 UTC, Dreamlone requested changes
Как Коля написал, хорошо бы, чтобы был тест
Плюс стоит добавbть описание к PR

2022-02-04 07:11 UTC, Dreamlone requested changes

2022-02-04 07:11 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        not_optimal_multi_target[:, 0] = 1
Вот эту подготовку таблицы с вероятностями (я так понял здесь про неё речь идёт), стоит вынести в отдельную функцию с подробными описанием в docstring что там внутри творится

Плюс меня смущает вот эта конструкция, она кмк тяжеловата, а во вторых, есть ли возможность её проводить в векторизованной форме? 
```
for i, t in enumerate(target):
            optimal_multi_target[i, t[0] if isinstance(t, Iterable) else t] = 1
```

2022-02-04 07:11 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_tuning.py
> +def test_greater_is_better():
Сюда бы тоже docstring с описанием того, что и зачем проверяется

2022-02-05 20:54 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        not_optimal_multi_target[:, 0] = 1
сделал через csr_matrix

2022-02-06 09:02 UTC, Dreamlone requested changes
Осталось [этот коммент](https://github.com/nccr-itmo/FEDOT/pull/550/files#r799213471) поправить и сделать rebase, ветка отстала от мастера

2022-02-06 09:28 UTC, gorokhovnik commented on test/unit/pipelines/test_pipeline_tuning.py
> +def test_greater_is_better():
А что, кроме "тестирую функцию _greater_is_better" написать?

2022-02-06 09:30 UTC, gorokhovnik commented
А для merge разве актуален rebase? Он же только diff поправит

2022-02-06 10:09 UTC, nicl-nno commented
rebase исправит это, деля финальный merge более очевидным

![image](https://user-images.githubusercontent.com/5711814/152676074-1ef92194-ca1c-4e85-a8b4-977eccc0d1cb.png)

2022-02-06 10:12 UTC, Dreamlone commented
> А для merge разве актуален rebase? Он же только diff поправит

Rebase актуален всегда. По крайней мере, это гарантирует, что ничего не поламается при вливании изменений в мастер. Я сам задавался подобным вопросом  примерно год назад, когда Паша просил меня сделать rebase, а изменения я вносил какие-то довольно ксометические. Каково было моё удивление, что после ребейза на моей ветке перестали проходить несколько тестов из-за того, что изменились какие-то функции, на которые я опирался, но сам в рамках PR не менял. В любом случае, лучше в этом деле перестраховаться - особенно если конфликты разрешать во время ребейза не приходится и он проходит гладко и быстро

2022-02-06 11:13 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_tuning.py
> +def test_greater_is_better():
Ну я бы предложил уточнить как именно происходит проверка, в духе берутся два target и смотрится, как при сопоставлении ведёт себя метрика (хотя сейчас подумал, что подобные объяснения стоило бы вынести в описании самой функции, которая занимается проверкой)

Но в целом, думаю и так пойдёт

2022-02-06 11:13 UTC, Dreamlone approved these changes

2022-02-06 13:27 UTC, merged