add disconnect_neighboring_nodes method
nccr-itmo/FEDOT pull request #551
Opened 2022-02-02 21:45 UTC by maypink

Add disconnect_neighboring_nodes method to GraphOperator class

2022-02-02 22:07 UTC, nicl-nno requested changes

2022-02-02 22:07 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def make_secondary_node_as_primary(self, node_child, new_type):
А этот метод предполагается к использованию снаружи? Если нет, то лучше пометить как приватный через _.

2022-02-02 22:07 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def _clean_up_leftovers(self, node: GraphNode):
Тут стоит в докстринге пояснить, кто такие leftovers.

2022-02-02 22:07 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def disconnect_neighboring_nodes(self, node_parent: GraphNode, node_child: GraphNode):
А нужно уточнение про neighboring?

2022-02-02 22:07 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +        self._clean_up_leftovers(node_parent)
Не особо ожидаемое поведение. Можно добавить в аргументы флаг, включающих при необходимости очистку.

2022-02-02 22:07 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +            self.make_secondary_node_as_primary(node, PrimaryNode)
По-хорошему тут не должно быть явных отсылок к PrimaryNode - т.к. это сущность не из fedot.core.dag
Но сходу не предложу готового решения, надо подумать. Пока можно пометить как workaround.

2022-02-03 09:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +    def disconnect_neighboring_nodes(self, node_parent: GraphNode, node_child: GraphNode):
мне кажется, что да, тк разъединить можно и ноду 'rf' с синей нодой 'svc', но данный метод именно для разъединения **соседних** вершин (имеющих между собой ребро) 
![image](https://user-images.githubusercontent.com/57305249/152314590-9db33118-f8e1-41b9-a5f2-b52057d9ed66.png)

2022-02-03 09:42 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def disconnect_neighboring_nodes(self, node_parent: GraphNode, node_child: GraphNode):
Ну вот способ "разъединения" не-соседних узлов выглядит неоднозначным (т.к. есть несколько способов, как именно это сделать) - значит как раз его лучше выносить в отдельным метод со специфичным названием.

А в теорминах графа если ноды можно disconnect - то я бы ожидал что они до этого были соединены ребром напрямую.

2022-02-03 10:20 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +        self._clean_up_leftovers(node_parent)
так если не очистить 'хвосты', то получится невалидный граф

2022-02-03 10:23 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +        self._clean_up_leftovers(node_parent)
Пользователь может захотеть сначала удалить ребро, а потом вручную сделать граф валидным.

Методы graph_operator не гарантируют валидность результата - это просто действия на графом (не обязательно вообще имеющим отношение к пайплайну МО)

2022-02-03 11:22 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +            self.make_secondary_node_as_primary(node, PrimaryNode)
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/456add85bf75a695a25d9715ded716ccbef4b332#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R149)

2022-02-03 11:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +        self._clean_up_leftovers(node_parent)
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/456add85bf75a695a25d9715ded716ccbef4b332#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R146)

2022-02-03 11:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +    def disconnect_neighboring_nodes(self, node_parent: GraphNode, node_child: GraphNode):
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/456add85bf75a695a25d9715ded716ccbef4b332#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R145)

2022-02-03 11:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +    def _clean_up_leftovers(self, node: GraphNode):
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/456add85bf75a695a25d9715ded716ccbef4b332#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R134-R137)

2022-02-03 11:24 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +    def make_secondary_node_as_primary(self, node_child, new_type):
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/456add85bf75a695a25d9715ded716ccbef4b332#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R37)

2022-02-03 11:48 UTC, maypink commented
и чтобы дальше работать с SA: для ребер завести класс в fedot/core/dag/graph_edge.py или продолжать представлять их просто двумя вершинами?

2022-02-03 13:58 UTC, Dreamlone requested changes

2022-02-03 13:58 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +                         is_clean_up_leftovers: bool = True):
Стоит добавить docstring к методу, плюс хорошо бы unit тест сделать, чтобы лучше понимать как он работает. Можно добавить его в папку test/sensitivity

2022-02-03 14:04 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +    def _clean_up_leftovers(self, node: GraphNode):
То, что leftovers определение есть, это хорошо, но ещё стоит добавить, что, собственно, сам метод делает, глагол `clean_up` можно трактовать довольно широко. Я исходя из названия интерпретировал бы что метод делает как, что он "убирает ребра и узлы, которые остаются после удалений и не влияют на результат работы конвейера", или я напутал?)

2022-02-03 14:07 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +        if len(node_child.nodes_from) == 1:
А так и задумано, что если nodes_from возвращает None, или пустой список, он проваливается в else и обрабатывается наравне с теми узлами, у которых несколько предков?

2022-02-03 19:26 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +            self._make_secondary_node_as_primary(node_child, type(self._graph.nodes[-1]))
А почему берется именно индекс -1? Узлы же могут в произвольном порядке идти.

2022-02-03 19:26 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +from fedot.core.pipelines.node import PrimaryNode
Импорт теперь лишний.

2022-02-03 19:56 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +            self._make_secondary_node_as_primary(node_child, type(self._graph.nodes[-1]))
они не всегда идут в порядке обхода в глубину? //понятно уже, что даже в таком случае последняя нода не всегда primary, но интереса ради

2022-02-03 20:57 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +            self._make_secondary_node_as_primary(node_child, type(self._graph.nodes[-1]))
Есть метод ordered_subnodes_hierarchy, который их упорядочивает.

В nodes они в порядке добавления попадают.

2022-02-04 10:18 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`test/sensitivity/test_sensitivity.py`](https://github.com/nccr-itmo/FEDOT/blob/efdd8dbfeb113c9fa04f404f9e24234728999c5d/test/sensitivity/test_sensitivity.py):

> [Line 500:1](https://github.com/nccr-itmo/FEDOT/blob/efdd8dbfeb113c9fa04f404f9e24234728999c5d/test/sensitivity/test_sensitivity.py#L500): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-02-04 10:20 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +                         is_clean_up_leftovers: bool = True):
[docstring](https://github.com/nccr-itmo/FEDOT/pull/551/commits/efdd8dbfeb113c9fa04f404f9e24234728999c5d#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R149-R156)
[tests](https://github.com/nccr-itmo/FEDOT/pull/551/commits/efdd8dbfeb113c9fa04f404f9e24234728999c5d#diff-53dfaf2321e140572ed788717f02757aae38baee2bc29ef6147aca4d20c95fd8R386)

2022-02-04 10:21 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +        if len(node_child.nodes_from) == 1:
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/efdd8dbfeb113c9fa04f404f9e24234728999c5d#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R159)

2022-02-04 10:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +            self._make_secondary_node_as_primary(node_child, type(self._graph.nodes[-1]))
[вернула обратно](https://github.com/nccr-itmo/FEDOT/pull/551/commits/efdd8dbfeb113c9fa04f404f9e24234728999c5d#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R163)

2022-02-04 10:23 UTC, maypink commented on fedot/core/dag/graph_operator.py
> +from fedot.core.pipelines.node import PrimaryNode
[вернула обратно с TODO](https://github.com/nccr-itmo/FEDOT/pull/551/commits/efdd8dbfeb113c9fa04f404f9e24234728999c5d#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R162)

2022-02-04 10:37 UTC, Dreamlone commented on test/sensitivity/test_sensitivity.py
> +    assert(res_pipeline == pipeline1)
Ещё немного подушню) 

Цифры в названии переменных и в названии методов в данном случае можно избежать. Плюс один большой тест можно разбить либо на несколько маленьких, либо просто в цикле пройтись по парам 
`zip(исходные_пайплайны, пайплайны_которые_должны_получиться_после_преобразований)`
Так будет меньше кода (хотя у тебя тут разные узлы вытаскиваются, так что наверно все таки лучше несколько отдельных тестов просто сделать)

И вопрос опять про сравнение, разница в топологии точно может улавливаться через `==`? 
Может более надежным будет способ проверять идентичность списков узлов-предков в нужных узлах?

2022-02-04 10:38 UTC, nicl-nno commented on test/sensitivity/test_sensitivity.py
> +# Tests fro disconnect_nodes method in GraphOperator
Опечатка в from. Да и лучше эти тесты в отдельный файл с тестами операций над графами поместить - они же напрямую к SA не имеют отношения.

2022-02-04 10:38 UTC, nicl-nno commented on test/sensitivity/test_sensitivity.py
> +def get_res_pipeline_test1():
Для единообразия вместо 1/2/... использовать first/second.

2022-02-04 10:40 UTC, nicl-nno commented on test/sensitivity/test_sensitivity.py
> +    assert(res_pipeline == pipeline1)
>И вопрос опять про сравнение, разница в топологии точно может улавливаться через ==?

У пайплайнов переопределен _eq_, поэтому так можно.

2022-02-04 11:04 UTC, maypink commented on test/sensitivity/test_sensitivity.py
> +    assert(res_pipeline == pipeline1)
там перегружен оператор == для графов

2022-02-04 11:20 UTC, maypink commented on test/sensitivity/test_sensitivity.py
> +def get_res_pipeline_test1():
[и так далее](https://github.com/nccr-itmo/FEDOT/pull/551/commits/1fd2d6b96a7b093f151e328822c8942cbce5568b#diff-e5379a26bc8bcf69b507a29f221a94193e162d3caa2c877380f82ef3b685bbd2R27)

2022-02-04 11:21 UTC, maypink commented on test/sensitivity/test_sensitivity.py
> +# Tests fro disconnect_nodes method in GraphOperator
[очепятка](https://github.com/nccr-itmo/FEDOT/pull/551/commits/1fd2d6b96a7b093f151e328822c8942cbce5568b#diff-e5379a26bc8bcf69b507a29f221a94193e162d3caa2c877380f82ef3b685bbd2R8)
[new file](https://github.com/nccr-itmo/FEDOT/pull/551/commits/1fd2d6b96a7b093f151e328822c8942cbce5568b#diff-e5379a26bc8bcf69b507a29f221a94193e162d3caa2c877380f82ef3b685bbd2R27)

2022-02-04 11:21 UTC, maypink commented on test/sensitivity/test_sensitivity.py
> +    assert(res_pipeline == pipeline1)
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/1fd2d6b96a7b093f151e328822c8942cbce5568b#diff-e5379a26bc8bcf69b507a29f221a94193e162d3caa2c877380f82ef3b685bbd2R1)

2022-02-04 12:16 UTC, Dreamlone approved these changes

2022-02-04 12:48 UTC, nicl-nno commented on test/sensitivity/test_sensitivity.py
> +# Tests fro disconnect_nodes method in GraphOperator
Я про вот этот файл: https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/dag/test_graph_operator.py

Ты же юнит-тестируешь GraphOperator вообще без привязки к SA.

2022-02-04 13:11 UTC, maypink commented on test/sensitivity/test_sensitivity.py
> +# Tests fro disconnect_nodes method in GraphOperator
[done](https://github.com/nccr-itmo/FEDOT/pull/551/commits/1d968b13c4402079dc550595a8a1c196978a3491#diff-8c444e0074cbcbc163b9efb7bd6a6df87721f240f3387d0a2c60345e740b3f45R95)

2022-02-04 13:12 UTC, nicl-nno approved these changes

2022-02-04 13:26 UTC, merged