Implemented parallelization
nccr-itmo/FEDOT pull request #553
Opened 2022-02-05 21:20 UTC by valer1435

Parallelization using multiprocessing.Pool for individuals was implemented

2022-02-05 21:24 UTC, valer1435 commented
К сожалению, на создание пула требуется некоторое (лишнее) время. Оно особенно мешает, когда прогоняются тесты. Может стоит сделать условие, если timeout < 0.5 то не проводить никакого композирования? Думаю, спасет порядка минуты на тестах, а может и больше.

2022-02-05 21:35 UTC, nicl-nno requested changes

2022-02-05 21:35 UTC, nicl-nno commented on examples/simple/time_series_forecasting/api_foresacting.py
> +                  workers=-1)
Может назвать n_jobs по-аналогии с другими фреймворками?

2022-02-05 21:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    graph = ind.graph
Мб для компактости использовать запись с namespace (как [тут](https://stackoverflow.com/a/36059129))?

2022-02-05 21:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def individual_evaluation(args):
Хорошо бы пояснить, что тут возвращается именно экземпляр Individual.

2022-02-05 21:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        return None
А не лучше возвращать просто индивид в любом случае? А потом при необходимости отфильтровывать по ind.fitness=none.

2022-02-05 21:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _evaluate_individuals(self, individuals_set, objective_function, timer=None, workers=4):
Если и задавать дефолтное значение - то лучше что-то вроде 1.

2022-02-05 21:35 UTC, nicl-nno commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
А приложи плз картинку к PR.

2022-02-05 21:35 UTC, nicl-nno commented on examples/advanced/parallelization_comparison.py
> +    for n_worker in [1, n_workers]:
Хорошо бы тут измерять реально время, потраченное на каждую итерацию. 
Если таймер плохо работает в многопоточном режиме - оно может быть неодинаковым.

2022-02-05 21:36 UTC, nicl-nno commented on fedot/api/main.py
> +            workers = multiprocessing.cpu_count()
Где-то тут можно печатать в лог число используемых CPU.

2022-02-05 21:53 UTC, nicl-nno commented
>К сожалению, на создание пула требуется некоторое (лишнее) время. Оно особенно мешает, когда прогоняются тесты.

Так может просто не создавать пул, если workers=1 (как по умолчанию)?

2022-02-06 09:17 UTC, Dreamlone commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
А почему решил убрать эту функцию? Проблемы с fitness равным None, если что появляются не при каждом запуске и то что их не было некоторых запусках, не значит, что они исчезли)

2022-02-06 14:06 UTC, valer1435 commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
Потому что это фактически обрабатывается в процессе вычисления фитнесса
![image](https://user-images.githubusercontent.com/32017472/152684684-24b3f328-47cb-45a1-ae28-7a50fd918791.png)

2022-02-06 14:27 UTC, Dreamlone commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
Да, это так, но почему-то иногда все равно None в фитнессе появлялся 
В общем предлагаю оставить функцию на всякий случай - будет такое защитное программирование

2022-02-06 15:36 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_foresacting.py
> +                  workers=-1)
[Заменил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/12297730577126a600b4cfaf3b84d5dd7fefff03)

2022-02-06 15:37 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_foresacting.py
> +                  workers=-1)
PS n_n_jobs исправлены далее

2022-02-06 15:39 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    graph = ind.graph
[Переделал ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/ab8556ff41bec450e31a28ef6acce4b7195bb4aa#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R150-R161)под NameSpace

2022-02-06 15:39 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _evaluate_individuals(self, individuals_set, objective_function, timer=None, workers=4):
[Заменил ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/f05df5f0297babbf0428f5fddc209f0e2be5ffa1#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R402)на 1

2022-02-06 15:40 UTC, valer1435 commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
[Возвратил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/f05df5f0297babbf0428f5fddc209f0e2be5ffa1#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R402), но убрал проверку на None в evaluate_individuals

2022-02-06 15:42 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def individual_evaluation(args):
> > К сожалению, на создание пула требуется некоторое (лишнее) время. Оно особенно мешает, когда прогоняются тесты.
> 
> Так может просто не создавать пул, если workers=1 (как по умолчанию)?

[Сделал ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/eb17abf9e798fe39a129b928c7b1053ff733bb12#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R141-R145)ветвление

2022-02-06 15:42 UTC, valer1435 commented
> > К сожалению, на создание пула требуется некоторое (лишнее) время. Оно особенно мешает, когда прогоняются тесты.
> 
> Так может просто не создавать пул, если workers=1 (как по умолчанию)?

[Сделал ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/eb17abf9e798fe39a129b928c7b1053ff733bb12#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R141-R145)ветвление

2022-02-06 15:43 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def individual_evaluation(args):
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/eb17abf9e798fe39a129b928c7b1053ff733bb12#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R141-R145)TypeHint

2022-02-06 15:44 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        return None
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/ab8556ff41bec450e31a28ef6acce4b7195bb4aa#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R158-R161)в таком случае не возвращаются None

2022-02-06 15:49 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    for n_worker in [1, n_workers]:
Пока серьезных тестов производительности не проводил, но, как мне кажется, многопоточность не должна сильно влиять на таймер, так как важные для нас параметры таймера (подсчет минут) не меняются в дочерних процессах.
Плюс сама идея сравнения - определить, сколько пайплайнов успеет обучиться с одним ядром и с несколькими ядрами. При одинаковых таймаутах время будет колебаться незначительно, за счет того, что отдельные пайплайны могут обучаться слишком долго. Поэтому сравнивается кол-во пайплайнов

2022-02-06 15:50 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
Пока не проводил серьезных замеров производительности

2022-02-06 16:53 UTC, valer1435 commented on fedot/api/main.py
> +            workers = multiprocessing.cpu_count()
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/715fa9df5b93b36a6fe56325dde750b3eb62f279#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R132) Плюс перепес эту проверку непосредственно в evaluate_individuals, потому что если этого не сделать, можно по ошибке подвергнуть компьютер страданию (два раза зависало все намертво)

2022-02-07 12:18 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
![image](https://user-images.githubusercontent.com/32017472/152786717-9d89e1bb-46d9-4482-a957-c2f9070c1bbd.png)
Таймаут 10 минут, считал количество успешно обученных пайплайнов

2022-02-11 14:56 UTC, nicl-nno commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
Неплохо. А что тут по оси X?

2022-02-11 14:57 UTC, nicl-nno commented on examples/advanced/parallelization_comparison.py
> +    for n_worker in [1, n_workers]:
Я к тому, что стоит дополнительно проконтролировать, что время более-менее идентично - нет разныцы в N раз. А то всякое бывает с параллелизацией.

2022-02-11 14:58 UTC, nicl-nno approved these changes

2022-02-11 16:38 UTC, Dreamlone commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
Там вся идея была в двухуровневой проверке на наличие пайплайнов с None
Всё таки стоит вернуть как было, мне кажется. Во всяком случае именно проверка на None в evaluate_individuals была основной, а всё остальное было реализовано как заглушка для того, если что-то в функции шло не так

2022-02-11 16:44 UTC, Dreamlone commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
Пожалуй я могу тут ответить, так как сам задавал вопрос Валере, ответ был такой
"По оси х - кол-во строк в датасете, по y-кол-во пайплайнов, которые успели обучиться"

P.S. Надеюсь в текущей версии оси всё таки подписываются)

2022-02-21 19:53 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
![image](https://user-images.githubusercontent.com/32017472/155018506-4416fa75-db98-4455-95f5-b66f6c0089cf.png)
Обновил эксперимент

2022-02-22 09:31 UTC, Dreamlone commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
Картинка красивая, но мне не особо понятно что на colorbar показывается - время обучения пайплайна, или общее время обучения, затраченное на весь процесс оптимизации? 
Стоит расшифровать подпись. Плюс название графика и название оси слева дублируют друг друга

2022-02-23 09:32 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/advanced/parallelization_comparison.py`](https://github.com/nccr-itmo/FEDOT/blob/83352ea65aae179d2d7e9ae63513fc1127e7a9ef/examples/advanced/parallelization_comparison.py):

> [Line 57:54](https://github.com/nccr-itmo/FEDOT/blob/83352ea65aae179d2d7e9ae63513fc1127e7a9ef/examples/advanced/parallelization_comparison.py#L57): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2022-02-23 09:36 UTC, valer1435 commented on fedot/core/optimisers/optimizer.py
> -def correct_if_has_nans(individuals, log):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/b942dff3547f693734049bc17069a7cd48b51ebf#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R148-L148)

2022-02-23 09:37 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    plt.title('Num of pipelines that were evaluated correctly')
[Изменил подписи](https://github.com/nccr-itmo/FEDOT/pull/553/commits/83352ea65aae179d2d7e9ae63513fc1127e7a9ef#diff-8f2d6ebb1ec4c68c06715f7304cda0490e2580d584f25fdf808fc02f969e7d6cR51-R66)

2022-02-23 09:38 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    for n_worker in [1, n_workers]:
Добавлена возможность смотреть на время оптимизации для каждого запуска (см выше)

2022-02-24 11:37 UTC, Dreamlone requested changes

2022-02-24 11:37 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    logger.info(f"Number of used CPU's: {n_jobs}")
Предлагаю всё мубльтипроцссинговые штуки держать в отдельном py файле, или в отдельном классе даже, если это будет необходимо. В данном случае эти три строки можно завернуть в отдельную функцию

2022-02-24 11:37 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +                                   'timer': timer if i != 0 or n_jobs == 1 else None}  # one individual must fit
`timer if i != 0 or n_jobs == 1 else None` вычисления лучше сделать выше и записать в переменную

2022-02-24 11:37 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        evaluated_individuals = single_evaluating(reversed_individuals)
По хорошему бы, я предложил бы архитектурно переработать подход к запуску в однопоточном и многопоточном режимах. Насколько могу предположить из своих познаний в паттернах, тут может подойти поведенческий паттерн "Состояние". Но, @nicl-nno, если считаешь, что сейчас не хочется сильно тратить на это время и хочется побыстрее включить функциональность параллелизации в мастер, то рефакторинг ядра для распараллеливания можно будет решить потом отдельным PR.

2022-02-27 11:34 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    logger.info(f"Number of used CPU's: {n_jobs}")
Попробовал, получаются циклические импорты( Может быть вместе получится найти подходящий вариант

2022-02-27 13:25 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        evaluated_individuals = single_evaluating(reversed_individuals)
Действительно кажется что можно это выделить в тех. долг - после того как поймем, что всё работает как надо.

2022-02-27 13:27 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    logger.info(f"Number of used CPU's: {n_jobs}")
Ну хотя бы базовые функции вроде validate_n_jobs должны без проблем выноситься.

2022-02-27 14:49 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    train_data_path = f'{fedot_project_root()}/cases/data/scoring/scoring_train.csv'
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/4c9c921eb6d4a38a260afd19fbb425c8b6771802#diff-8f2d6ebb1ec4c68c06715f7304cda0490e2580d584f25fdf808fc02f969e7d6cR20-R28)

2022-02-27 14:50 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    logger.info(f"Number of used CPU's: {n_jobs}")
[Вынес ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8884ab46a1b3ad2daa061f16f240b0c5cce57ff9#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R1)функции для оценивания отдельно

2022-02-27 14:50 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +                                   'timer': timer if i != 0 or n_jobs == 1 else None}  # one individual must fit
[Перенес ](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8884ab46a1b3ad2daa061f16f240b0c5cce57ff9#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R136)выше

2022-03-03 10:30 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    if n_jobs > multiprocessing.cpu_count() or n_jobs == -1:
Лишние строки
Кстати тут не correct, а лучше бы подошло determine или что-то подобное

2022-03-03 10:30 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +            del node.content['params']['n_jobs']
Может лучше явно задавать 1? Просто мы вполне можем подтянуть в какой-то момент модельку, в которой значение n_jobs по умолчанию будет -1
Это конечно не решает проблему с тем, что node.content['params'] может быть строкой "default_params", но все равно кажется несколько надёжней

2022-03-03 10:45 UTC, Dreamlone requested changes

2022-03-03 10:45 UTC, Dreamlone commented on examples/advanced/parallelization_comparison.py
> +    times_ = {1: [], n_jobs: []}
А есть какая-то причина, почему в названии переменной решил оставить "_" в конце?

2022-03-03 10:45 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
>          """
Метод поднабрал аргументов - стоит расшифровать их в docstring

2022-03-03 10:45 UTC, Dreamlone commented on examples/advanced/parallelization_comparison.py
> +    cb = plt.colorbar(cm.ScalarMappable(norm=c_norm, cmap=cm.get_cmap('cool')))
С отрисовкой чёт опять не пошло, вывалилось на этой строчке с ошибкой
`TypeError: You must first set_array for mappable`

Это же та самая ошибка, которая связана с версией matplotlib (вроде в той же env запускал, в которой всегда юзаю)?

2022-03-03 10:45 UTC, Dreamlone commented on fedot/core/validation/compose/tabular.py
> -        evaluated_metrics = [[] for _ in range(len(metrics))]
А объясни плиз почему try - except убрал?

2022-03-04 08:42 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    cb = plt.colorbar(cm.ScalarMappable(norm=c_norm, cmap=cm.get_cmap('cool')))
Пример взят [отсюда](https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.colorbar.html). Думаю проблема в версии

2022-03-04 09:32 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    if n_jobs > multiprocessing.cpu_count() or n_jobs == -1:
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8ebbdbd6d43771cac5e09f57204583e3c7946f21#diff-720efcdc31ff628319f49b0faf6cb943c3761252c6117174be7f24d954cd6172R133)

2022-03-04 09:33 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
>          """
[Расшифровал](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8ebbdbd6d43771cac5e09f57204583e3c7946f21#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR179-R183)

2022-03-04 09:34 UTC, valer1435 commented on fedot/core/validation/compose/tabular.py
> -        evaluated_metrics = [[] for _ in range(len(metrics))]
Спасибо, что заметил. Убрал, чтобы ловить нормально ошибки. [Добавил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8ebbdbd6d43771cac5e09f57204583e3c7946f21#diff-be18b6ca8e798ef8db958502103a22f5ed791f5417fac4e4d8e6f4ec3fb7b7adR29-R43) обратно

2022-03-04 09:35 UTC, valer1435 commented on examples/advanced/parallelization_comparison.py
> +    times_ = {1: [], n_jobs: []}
[Нет](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8ebbdbd6d43771cac5e09f57204583e3c7946f21#diff-8f2d6ebb1ec4c68c06715f7304cda0490e2580d584f25fdf808fc02f969e7d6cR43)

2022-03-04 09:35 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +            del node.content['params']['n_jobs']
[Справедливо](https://github.com/nccr-itmo/FEDOT/pull/553/commits/8ebbdbd6d43771cac5e09f57204583e3c7946f21#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R86)

2022-03-04 09:55 UTC, Dreamlone commented on examples/advanced/parallelization_comparison.py
> +    cb = plt.colorbar(cm.ScalarMappable(norm=c_norm, cmap=cm.get_cmap('cool')))
Такс, у меня ничего не изменилось - та же самая ошибка, хот версия matplotlib у меня строго по requirements.txt. Но да ладно, в конце концов, главное, что работает распараллеливание, а рисование графиков дело тут не первостепенное

2022-03-04 10:14 UTC, Dreamlone requested changes

2022-03-04 10:14 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        evaluated_individuals = list(filter(lambda x: x, evaluated_individuals))
Может я немного запутался, но скажи пожалуйста, что делает эта конструкция? evaluated_individuals вроде же уже список

2022-03-04 10:14 UTC, Dreamlone commented on fedot/core/validation/compose/tabular.py
> +        cache = None
Мб стоит добавить TODO, если кэширование для многопоточного режима планируем переработать в дальнейшем

2022-03-06 18:51 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        evaluated_individuals = list(filter(lambda x: x, evaluated_individuals))
Конструкция фильтрует None. List для обертки итератора

2022-03-10 07:16 UTC, Dreamlone approved these changes
Вроде всё ок, не забудь только сделать ребейз

2022-03-10 11:25 UTC, valer1435 commented on fedot/core/validation/compose/tabular.py
> +        cache = None
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/553/commits/00b3ebb2b96d8aece35e1458c127fd3ede850536)

2022-03-10 11:44 UTC, Dreamlone commented on fedot/core/validation/compose/tabular.py
> +        cache = None
Найс

2022-03-10 11:45 UTC, merged