Cross-validation support for cache
nccr-itmo/FEDOT pull request #555
Opened 2022-02-09 16:56 UTC by nicl-nno

Cache for fitted models is not working for CV-based metrics now.
This PR tries to fix it by the adding of fold-based supplementary ids for cache.

2022-02-15 19:40 UTC, Dreamlone requested changes

2022-02-15 19:40 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +                                                validation_blocks=self.composer_requirements.validation_blocks,
Вроде тут PR, который оптимизирует вычисления, но при этом я правильно понимаю суть нововведений, что решаешь хранить фолды по кросс-валидации в памяти? Есть ли возможность этого избежать, потому что на крупных датасетах это вполне себе может стать ботлнеком. (Или нет, в общем, я за то, чтобы проверить моё наивное предположение)

2022-02-15 19:40 UTC, Dreamlone commented on fedot/core/validation/compose/tabular.py
> +        raise NotImplementedError(f"Tabular cross validation for clustering is not supported")
Смотрится тяжеловато, я бы предложил разбить на несколько переменных

2022-02-15 19:49 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
> +                                                validation_blocks=self.composer_requirements.validation_blocks,
Ну вроде разбиение CV у sklearn'a и не предполагает перемешивания данных (если речь про это), если явно это не просить делать. Для временных рядов ещё проще - там порядок и так не менялся. 
Про потребление да, мы никуда таблички размером 500 Мб условно конечно прятать не можем, но мы может разбить их по 250 Мб и подавать последовательно (вроде yield как раз это делает, он не держит фолды в памяти) и тогда будем держать 500 + 250 единовременно. А в новой версии это будет всегда 500 + 500 (исходный массив мы же тоже дежим вроде как при себе). Но в целом согласен, и так вроде норм, не хотелось бы конечно преждевременной оптимизацией заниматься в этом плане, просто по потреблению памяти FEDOT вроде и так не голодает)

2022-02-15 22:06 UTC, nicl-nno commented on fedot/core/composer/cache.py
> +    def save_node(self, node, partial_id='all'):
(Уточнил)[https://github.com/nccr-itmo/FEDOT/pull/555/files#diff-c50019984c360138cba52c016981875b18619ceb5defce4569bb4d33d0326e3dR27-R29) и сделал дефолтное значение пустым.

2022-02-15 22:06 UTC, nicl-nno commented on fedot/core/composer/gp_composer/gp_composer.py
> +                                                validation_blocks=self.composer_requirements.validation_blocks,
Проверил - разбиение действительно происходит почти мгновенно. 
Поэтому пока вернул как было.

2022-02-15 22:06 UTC, nicl-nno commented on fedot/core/validation/compose/tabular.py
> +        raise NotImplementedError(f"Tabular cross validation for clustering is not supported")
Удалил вообще - кажется актуальность кластеризации очень низка, чтобы загромождать из-за неё код.

2022-02-16 07:50 UTC, Dreamlone approved these changes

2022-02-16 10:39 UTC, merged