tuning time and metric score fixes
nccr-itmo/FEDOT pull request #565
Opened 2022-02-17 12:56 UTC by v1docq

https://github.com/nccr-itmo/FEDOT/issues/559 
https://github.com/nccr-itmo/FEDOT/issues/560

2022-02-17 13:04 UTC, Dreamlone reviewed
А как решена проблема с зависанием? Вернее, за счет чего? Я тут вижу только фиксы по замеру времени и по расчету метрики в тюнере

2022-02-17 13:24 UTC, v1docq commented
> А как решена проблема с зависанием? Вернее, за счет чего? Я тут вижу только фиксы по замеру времени и по расчету метрики в тюнере

Это скорее PR не про зависания, а про некорректное время работы и вычисление метрик. С самими зависаниями пока что я ничего не делал и продолжаю ресерч.

2022-02-17 13:42 UTC, Dreamlone requested changes
> Это скорее PR не про зависания, а про некорректное время работы и вычисление метрик. С самими зависаниями пока что я ничего не делал и продолжаю ресерч.

Принял

2022-02-17 13:42 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            timeout_for_tuning = api_params['timeout'] - spending_time_for_composing
А что будет, если spending_time_for_composing окажется больше api_params['timeout']? Ну например подзавис композер и немного лишнего отработал, чем мы задавали времени для тюнинга и композирования.

2022-02-17 14:08 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +            timeout_for_tuning = api_params['timeout'] - spending_time_for_composing
Ну мы задаем на композирование, половину времени от всего лимита, если у нас требуется тюнинг. Если композирование занимает в 2 раза больше времени чем ему отводится то это вопрос к работе композера скорее, Можно конечно оставить перестраховку но тогда, возможна следующая ситуация. "Мы задали 30 минут на весь поиск пайплайна с композированием, в старой логике время на композирование займет 15, если реальное время композирование допустим 29 минуты, то по старой логике мы берем на тюнинг половину от исходного, т.е. 15 минут, итого получаем 44 минуты вместо 30. А если композирование сошлось быстрее, допустим за 10 минут, то по новой логике остаток мы тратим на тюнинг.

2022-02-17 14:19 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            timeout_for_tuning = api_params['timeout'] - spending_time_for_composing
По поводу твоих выкладок согласен. Новый подход несколько более прозрачен - к этом вопросов нет. Но вот может же случится, особенно на небольших timeout'ах, например в 1-2 минуты, что композер одну модель считал ну немного дольше чем планировал, - и из-за этого у вот этого расчета timeout_for_tuning выйдет отрицательным. Может тогда, если так выходит, то сделать проверку, что если времени в `timeout_for_tuning` например меньше 5 сек, то тюнинг не проводится, и возвращается сразу пайплайн. Ну и в лог об этом написать естессно

2022-02-17 14:23 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +            timeout_for_tuning = api_params['timeout'] - spending_time_for_composing
Согласен с тобой, реализую такое сообщение

2022-02-17 14:52 UTC, pep8speaks commented
Hello @v1docq! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/api_utils/api_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/60ef39d4b282ab001c6e5495b389ddfe4509e1eb/fedot/api/api_utils/api_composer.py):

> [Line 254:1](https://github.com/nccr-itmo/FEDOT/blob/60ef39d4b282ab001c6e5495b389ddfe4509e1eb/fedot/api/api_utils/api_composer.py#L254): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-02-17 15:03 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = api_params['timeout'] - int(spending_time_for_composing.total_seconds() / 60)
Вроде выше уже timeout_for_tuning посчитан, в чем идея его тут ещё раз пересчитывать? Выше он вроде расчитан в секундах, тут нужно просто число из timeout переконвертировать в минуты

2022-02-17 18:13 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                vb_number = composer_requirements.validation_blocks
Стоит тогда сообщение логгера `api_params['logger'].message('Hyperparameters tuning started')` тоже где-нибудь отсюда вызывать, а не выше

2022-02-17 18:15 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                vb_number = composer_requirements.validation_blocks
Ну и добавить описание к PR тоже не помешает

2022-02-18 10:54 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                vb_number = composer_requirements.validation_blocks
Добавил описание и передвинул сообщение.

2022-02-18 11:35 UTC, Dreamlone approved these changes

2022-02-18 13:05 UTC, merged