Api forecast indices fix
nccr-itmo/FEDOT pull request #568
Opened 2022-02-18 11:53 UTC by Dreamlone

Fixed setting indices for time series forecasting through API forecast method

2022-02-18 12:37 UTC, nicl-nno requested changes

2022-02-18 12:37 UTC, nicl-nno commented on fedot/api/main.py
> +    def update_params(self, timeout, initial_assumption):
А почему это всё неактуально? Смысл-то в том, чтобы ограничивать число поколений, если время не ограничено - и наоборот.

2022-02-18 13:24 UTC, Dreamlone commented on fedot/api/main.py
> +                 timeout: Optional[float] = None,
Такс, а эти изменения я не вносил, проверю, может ребейзнулось как-то криво, проверю

2022-02-18 15:21 UTC, Dreamlone commented on fedot/api/api_utils/api_data.py
> +def update_indices_for_time_series(test_data: InputData, forecast_length: int):
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/568/commits/752b4d91305104e12cec1e47af133c02b02945d2#diff-650638a6c6857b24a2475786ce055e9486f5484462307146eba8d3219bb7344bL125-R125)

2022-02-18 15:24 UTC, Dreamlone commented on fedot/api/main.py
> +    def update_params(self, timeout, initial_assumption):
Исправил

2022-02-18 16:02 UTC, Dreamlone commented on fedot/api/main.py
> +        self.test_data = update_indices_for_time_series(self.test_data, forecast_length)
[Перенёс](https://github.com/nccr-itmo/FEDOT/pull/568/commits/46a4d2d8e949c8f8e58b0c0511d14e5bd85487ab)
Метод применяется только на predict'е и исправляет индексирование, если для тестовых данных количество индексов для прогноза больше, чем горизонт прогнозирования модели

2022-02-19 13:37 UTC, valer1435 approved these changes

2022-02-19 13:37 UTC, valer1435 commented on fedot/preprocessing/preprocessing.py
> +            if forecast_len < len(input_data.idx):
Я правильно понимаю, что это нужно, чтобы избавиться от неопределенности в forecast_length (она может задаваться в input_data и еще где-то)

2022-02-19 16:48 UTC, Dreamlone commented on fedot/preprocessing/preprocessing.py
> +            if forecast_len < len(input_data.idx):
Не совсем. Ключевая проблема была в рамках этого PR в том, что для корректной работы алгоритмов прогнозирования временного ряда критически важным было в InputData задать индексы. При этом индексы для обучения и индексы в InputData заметно индексируют разные вещи. То есть, если для обучения в train_input надо передавать idx = [0, 1, 2, 3, ... n], где n - это длина ряда, который является обучающей выборкой. То для test_input нужно idx = [10, 11, ... m], где m - горизонт прогнозирования. 

При формировании InputData через API в методе forecast это не учитывалось. И если в forecast подавался numpy массив, он готовил его с индексами как в train. В большинстве случаев это ни к чему не приводило, так как 1) forecast в API не самый частоиспользуемый метод, 2) обычно для временных рядов (по крайней мере я) формируются именно InputData, а не numpy массивы даже для API, 3) если пайплайн не разветвленный и при этом не содержит специфических (например, как GLM) моделей, то модели машинного обучения вполне могут переваривать и такую индексацию. 

Поскольку проверка теперь вынесена в pipeline решилась проблема некоторой громоздкости в работе с InputData для временных рядов. То есть теперь вариант 
```
pipeline.fit(train_input)
pipeline.predict(train_input)
```
будет корректным - предсказания будут делаться от обучающей выборки

2022-02-19 20:05 UTC, merged