tuning timeout and initial_assumptions fixes
nccr-itmo/FEDOT pull request #572
Opened 2022-02-22 12:50 UTC by v1docq

fixes in timeout for tuning calculation. XGBoost and Catboost was excluded from avaliable model list

2022-02-22 13:00 UTC, nicl-nno commented on fedot/core/repository/data/model_repository.json
>      },
А зачем полность убирать? Можно просто из пресетов выпилить пока.

2022-02-22 13:02 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
>          spending_time_for_composing = datetime.datetime.now() - starting_time_for_composing
Лучше кстати spended.

2022-02-22 13:50 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                                                                                timeout=int(np.ceil(
перенес выше

2022-02-22 14:06 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +                                                                                timeout=int(np.ceil(
Так может поставить перед проверкой "timeout_for_tuning < 15"
?

2022-02-22 14:06 UTC, v1docq commented on fedot/core/repository/data/model_repository.json
>      },
поправил

2022-02-22 14:27 UTC, Dreamlone requested changes

2022-02-22 14:27 UTC, Dreamlone commented on fedot/api/api_utils/presets.py
> +        excluded_tree = ['xgboost', 'catboost']
Может регрессионные тоже исключим тогда?

2022-02-22 14:32 UTC, v1docq commented on fedot/api/api_utils/presets.py
> +        excluded_tree = ['xgboost', 'catboost']
Давай

2022-02-22 14:37 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
предлагаю так timeout_for_tuning = max(1,int(round(abs(timeout_for_tuning) / 60)))

2022-02-22 14:48 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
int можно убрать, round и так в int переводит

2022-02-22 14:48 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
Кстати проверил на float - все работает, можно вообще убрать округление до целых

2022-02-22 15:22 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                                                                                timeout=int(np.ceil(
Я бы предпочел его оставить после else, т.к проще задавать минимальный трешхолд для времени на тюнинг, да и просто логически приятней выглядит

2022-02-22 15:22 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
Поправил

2022-02-22 15:35 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
Так а зачем строка? 
```
timeout_for_tuning = max(1.0, abs(timeout_for_tuning) / 60)
```

2022-02-22 15:57 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +                                                                                timeout=int(np.ceil(
Ок, пусть будет.

2022-02-22 16:23 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
я думал что минимально хотя бы 1 минуту оставить на тюнинг

2022-02-22 16:34 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
Тогда теряется смысл проверки выше, когда определяем порог в 15 секунд как значимый. Да и не всегда кмк это актуально - дали мы например на очень очень мощном компьютере 30 сек на тюнинг, этого может и хватит на 50 итераций, так вроде и лишнего давать тюнеру не надо - и так времени достаточно

2022-02-22 16:59 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +                timeout_for_tuning = int(np.ceil(abs(timeout_for_tuning) / 60))
Ок давай так

2022-02-22 19:39 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
С остальным всё кул, но вопрос выше вы как-то заочно обсудили? Потому что мне тоже кажется, что когда на композирование выделяется неограниченное время неочевидно, почему тюнинг не используется вовсе. Можно тогда просто выделять небольшое количество времени по умолчанию, например 5 минут. А то spending_time_for_composing, когда его ограничивает только критерий остановки может раздуваться до очень больших значений кмк

2022-02-22 19:50 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
Нет, не обсуждали.

>может раздуваться до очень больших значений

Если мы не ограничиваем время - то оно нам и не важно, что для композирования, что для настройки.

2022-02-22 19:56 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
> Если мы не ограничиваем время - то оно нам и не важно, что для композирования, что для настройки.
Но для композирования есть ограничитель, а для тюнера у нас такового пока что не реализовано. И по опыту могу сказать, что пространство поиска для композера конечно намного больше, чем у тюнера, выделять ему сопоставимое время может быть даже лишним. Но пока как решение здесь и сейчас, пожалуй, соглашусь, раз время мы не задаём, значит готовы подождать) 

В общем ок, тогда осталось сделать назначение времени тюнеру, равным тому, которое было затрачено при композировании, если было задано как None изначально, и вливать этот PR в мастер

2022-02-23 19:51 UTC, Dreamlone approved these changes

2022-02-23 19:53 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
Внес [фикс](https://github.com/nccr-itmo/FEDOT/pull/572/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR260).

2022-02-23 20:00 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
Тогда сквашу и в мастер?

2022-02-23 20:00 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
> Внес [фикс](https://github.com/nccr-itmo/FEDOT/pull/572/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR260).

Опередил меня на 2 минуты)

2022-02-23 20:01 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        if tuning_params['with_tuning'] and timeout_for_composing is not None:
> Тогда сквашу и в мастер?

Ага, я ребейзнул как раз.

2022-02-23 20:08 UTC, merged