Delete boosting models and operator
nccr-itmo/FEDOT pull request #577
Opened 2022-02-25 15:24 UTC by v1docq

2022-02-25 15:40 UTC, Dreamlone requested changes
Описание к PR добавь плиз

2022-02-25 15:40 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        target = np.eye(nb_classes)[target_converted]
Лучше в отдельную функцию и добавить описание

2022-02-25 15:40 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        mutations = [parameter_change_mutation,
Раз репозиторий подчистил, то тут можно вернуть как было

2022-03-03 20:57 UTC, nicl-nno commented
Updated version in https://github.com/nccr-itmo/FEDOT/pull/579/commits

2022-03-03 20:57 UTC, closed without merging