Mulltimodal pipeline improvement
nccr-itmo/FEDOT pull request #581
Opened 2022-03-01 19:15 UTC by andreygetmanov

Fixes in composer's work, minor changes and optimization of multimodal tools

2022-03-01 19:16 UTC, pep8speaks commented
Hello @andreygetmanov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cases/multi_modal_genre_prediction.py`](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/cases/multi_modal_genre_prediction.py):

> [Line 18:7](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/cases/multi_modal_genre_prediction.py#L18): [E114](https://duckduckgo.com/?q=pep8%20E114) indentation is not a multiple of four (comment)
> [Line 18:7](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/cases/multi_modal_genre_prediction.py#L18): [E116](https://duckduckgo.com/?q=pep8%20E116) unexpected indentation (comment)
> [Line 56:54](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/cases/multi_modal_genre_prediction.py#L56): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent





* In the file [`examples/advanced/multi_modal_pipeline.py`](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/examples/advanced/multi_modal_pipeline.py):

> [Line 73:32](https://github.com/nccr-itmo/FEDOT/blob/794d2bd68cfc4c9f748f26bb31483fe764e4421a/examples/advanced/multi_modal_pipeline.py#L73): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2022-03-04 14:50 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
Обновил PR. По идее, должно работать.

2022-03-04 14:51 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
>      pipeline.fit(input_data=fit_data)
В датасете много классов + он достаточно дисбалансный, поэтому при разделении на train/test не все классы попадали в обе выборки. Поменял датасет, сократил число классов, теперь должно работать.

2022-03-04 14:53 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    # images_size)
Убрал. Пока чиню merge табличных данных, можно оставить закомменченные строчки, относящиеся к этой проблеме?

2022-03-04 14:57 UTC, nicl-nno commented on examples/advanced/multi_modal_pipeline.py
>      pipeline.fit(input_data=fit_data)
>поэтому при разделении на train/test не все классы попадали в обе выборки

Хорошо бы это починить, конечно. Но можно отдельным PR.

2022-03-04 15:01 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
>      pipeline.fit(input_data=fit_data)
> Хорошо бы это починить, конечно.

В этом примере используется небольшой датасет. Подумал, что поменять датасет и сократить число  классов - норм идея для демонстрации примера. Но можно и что-то другое сделать, наверное.

2022-03-04 15:05 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    # images_size)
Не принципиально.

2022-03-05 07:40 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
Понял в чем проблема: путь надо поменять
`run_multi_modal_case('cases/data/mm_imdb', is_visualise=True)` вместо `run_multi_modal_case('cases/data/mmimdb', is_visualise=True)`

2022-03-05 07:45 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
Всё отработало, но метрика конечно что-то с чем-то) 
`F1 micro for validation sample is 0.2`

А на этом датасете нельзя выше метрику получить? Если например, использовать только один источник данных - например, обучать модель только на картинках или только на тексте. Хотелось бы понять, это значение предел, или именно мультимодальность как-то ухудшает прогностические возможности модели

2022-03-05 07:55 UTC, Dreamlone requested changes

2022-03-05 07:55 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    pipeline_evo_composed.fit(input_data=fit_data)
А можно пример адаптировать через API, а не собирать так низкоуровнево? 
Если это невозможно, то мне кажется, стоит в рамках этого PR модифицировать API

2022-03-05 07:55 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
>      return err
В этом файле довольно много закомментированных строк - от них стоит избавиться, если они не нужны
Ещё есть предложение добавить type hints в тех местах, в которых они ещё не стоят и добавить docstring описания (по поводу описаний могу поделиться, что даже среди команды разработки не у всех есть понимание, что такое "мультимодальные данные", поэтому не стесняйся в примере объяснить что это чуть подробнее)

2022-03-05 07:57 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
>      pipeline.fit(input_data=fit_data)
Думаю пока можно действительно оставить упрощенный вариант, а уже последующими PR организовать возможность нормально работать с сильно несбалансированными датасетами

2022-03-05 09:41 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
> А на этом датасете нельзя выше метрику получить? 

На этом датасете на только текстовых данных получалось 0.23, но это датасет маленький, на побольше 0.46 выдаёт. Мультимодальность тоже пока ухудшает прогноз, но это из-за того, что CNN не отрабатывает на multilabel target и выдаёт не то.

2022-03-05 13:39 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
`из-за того, что CNN не отрабатывает на multilabel target и выдаёт не то`
Предлагаю поправить это в рамках данного PR тоже в таком случае. В идеале мне кажется. было бы здорово получить кейс, когда мы берём только картинки и получаем 0.2. потом только текст и получаем 0.23 например, а когда берём все вместе, - получаем 0.4 например. Вот под что-то такое можно бы оформить case

2022-03-17 15:02 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
> +    :param pred: model's prediction
valid тут не совсем вектор с предсказаниями. Скорее Fedot'ский датакласс, в котором хранятся действительные значения

2022-03-17 15:02 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
> +    :return: pipeline object, 2 multimodal data objects (fit and predict)
В целом названия переменных тут довольно говорящие, можно в docsting не особо расписывать (но вообще пусть будет так). Стоит после `Generates initial pipeline for data from 3 different sources (table, images and text)` написать про то, что для каждого источника данных в пайплайне генерируется своё поддерево, начинающееся с data source узлов

2022-04-01 13:28 UTC, nicl-nno commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +                if isinstance(trained_operation.classes_, list):
Выше уже есть такая проверка - может вынести её результат в переменную? Заодно будет понятно, что именно проверяется.

2022-04-01 15:44 UTC, andreygetmanov commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +                if isinstance(trained_operation.classes_, list):
> Выше уже есть такая проверка - может вынести её результат в переменную? Заодно будет понятно, что именно проверяется.

Вынес

2022-04-01 15:55 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
>      return err
> Ещё есть предложение добавить type hints в тех местах, в которых они ещё не стоят и добавить docstring описания
Добавил

2022-04-01 16:07 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
> `Предлагаю поправить это в рамках данного PR тоже в таком случае. 

Поправил

>В идеале мне кажется. было бы здорово получить кейс, когда мы берём только картинки и получаем 0.2. потом только текст и получаем 0.23 например, а когда берём все вместе, - получаем 0.4 например. Вот под что-то такое можно бы оформить case

Text pipeline отдельно выдаёт f1=0.43, image pipeline f1=0.42, при совмещении получается 0.56. Мне кажется, достаточно показательно

2022-04-01 16:09 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +    :return: pipeline object, 2 multimodal data objects (fit and predict)
> В целом названия переменных тут довольно говорящие, можно в docsting не особо расписывать (но вообще пусть будет так). Стоит после `Generates initial pipeline for data from 3 different sources (table, images and text)` написать про то, что для каждого источника данных в пайплайне генерируется своё поддерево, начинающееся с data source узлов

Да, добавил про это

2022-04-01 16:13 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    # images_size)
> Не принципиально.

Убрал закомменченные части

2022-04-01 16:30 UTC, nicl-nno approved these changes

2022-04-02 08:43 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    pipeline_evo_composed.fit(input_data=fit_data)
Создай тогда issue под это дело

2022-04-02 09:55 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
>          train_img, test_img = data_img, data_img
Немного неочевидное поведение. Лучше кмк разделить подготовку данных с разделением. Учитывая, что судя по строке `train_num, test_num = data_num, data_num` например оно не всегда нужно

2022-04-02 09:55 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
FYI, у меня получилось 
```
F1 micro for validation sample is 0.31
```

2022-04-02 10:16 UTC, Dreamlone requested changes
Ещё стоит написать тест на мультимодальную функциональность, которая уже есть. Вроде таких тестов ещё нет, по крайней мере я не нашёл для случая "картинки + текст + таблицы"

2022-04-02 10:16 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
У меня при запуске структура полученного пайплайна никак не отличается от исходного
![image](https://user-images.githubusercontent.com/52418437/161378044-5dc9c041-d45f-4aa6-9af8-25214108b6b0.png)
Это частая ситуация? 

Ещё есть вопрос про тюнинг - он может нормально работать с мультимодальными пайплайнами такого типа? Может его тогда добавить в этот пример

2022-04-02 10:16 UTC, Dreamlone commented on fedot/core/data/data.py
> +                    df_data[f] = [' '.join(v) for v in df_data[f]]
А что тут означают переменные `f` и `v`? Стоит наверно целиком написать названия

2022-04-02 10:16 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
> +        train_text, test_text = train_test_data_setup(data_text, shuffle_flag=True, split_ratio=ratio)
А тут не возникает проблем, что по отдельности данные дробятся на train и test, если shuffle_flag стоит True? 
Мне тут в голову пришла ситуация, что может быть так, что в train от разных источников могут прийти разные объекты. Можно делать это сначала оборачивая InputData из разных источников в MultiModalData, а только потом вызывая train_test_data_setup?

2022-04-02 10:16 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        if is_multi_output_target:
Стоит добавить комментарий, что тут имеется в виду, не многомерный output в виде вероятностей в случае многоклассовой классификации, а то что одному объекту сопоставляются две (или больше) метки при решении задачи классификации

2022-04-04 19:13 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +        train_text, test_text = train_test_data_setup(data_text, shuffle_flag=True, split_ratio=ratio)
> А тут не возникает проблем, что по отдельности данные дробятся на train и test, если shuffle_flag стоит True? Мне тут в голову пришла ситуация, что может быть так, что в train от разных источников могут прийти разные объекты. Можно делать это сначала оборачивая InputData из разных источников в MultiModalData, а только потом вызывая train_test_data_setup?

Чуть поменял, теперь prepare_multimodal_data выдаёт объект MultiModalData со всеми данными внутри, а разделение может быть произведено уже в generate_initial_pipeline_and_data
Тест test_multi_modal_pipeline написан под предыдущую структуру этих функций, поэтому падает. Что с ним делать?

2022-04-04 19:13 UTC, andreygetmanov commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        if is_multi_output_target:
> Стоит добавить комментарий, что тут имеется в виду, не многомерный output в виде вероятностей в случае многоклассовой классификации, а то что одному объекту сопоставляются две (или больше) метки при решении задачи классификации

Добавил

2022-04-04 19:14 UTC, andreygetmanov commented on fedot/core/data/data.py
> +                    df_data[f] = [' '.join(v) for v in df_data[f]]
> А что тут означают переменные `f` и `v`? Стоит наверно целиком написать названия

F - fields (используемые поля), v - составляющие элемента поля.
Поправил, теперь должно быть понятнее

2022-04-04 19:14 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    train_img, test_img, train_text, test_text = prepare_multi_modal_data(files_path, task, images_size)
> FYI, у меня получилось F1 micro for validation sample is 0.31

Да, всё так, я не на те цифры посмотрел. Те, что я назвал, получаются в multi_modal_pipeline. В этом примере только текст даёт 0.24, всё вместе получается 0.31

Upd: заметил, что в этом примере при использовании только картинок f1 получается 0. Буду разбираться

> И ещё очень много варнингов, так и должно быть?

Сообщения о нормализации теперь пишутся в лог через debug

2022-04-04 19:41 UTC, nicl-nno commented on examples/advanced/multi_modal_pipeline.py
> +        train_text, test_text = train_test_data_setup(data_text, shuffle_flag=True, split_ratio=ratio)
>Тест test_multi_modal_pipeline написан под предыдущую структуру этих функций, поэтому падает. Что с ним делать?

Резонно поправить и тест.

2022-04-05 16:03 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
> У меня при запуске структура полученного пайплайна никак не отличается от исходного ![image](https://user-images.githubusercontent.com/52418437/161378044-5dc9c041-d45f-4aa6-9af8-25214108b6b0.png) Это частая ситуация?

Пока что оптимизатор нормально не работает с этим примером. Эту проблему вынесу в следующий PR

> Ещё есть вопрос про тюнинг - он может нормально работать с мультимодальными пайплайнами такого типа? Может его тогда добавить в этот пример

Это тоже, наверное, лучше вынести в новый PR?

2022-04-05 16:08 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +        train_text, test_text = train_test_data_setup(data_text, shuffle_flag=True, split_ratio=ratio)
> Резонно поправить и тест.

Поправил

2022-04-05 16:16 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    pipeline_evo_composed.fit(input_data=fit_data)
> Создай тогда issue под это дело плез

Создал

2022-04-05 16:59 UTC, nicl-nno approved these changes

2022-04-06 08:42 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
Моё мнение такое: если что-то можно сделать в рамках PR, и если это "что-то" не раздувает его до невообразимых размеров и при этом касается тематики PR - надо это делать. Пробовать, ошибаться, иногда откатываться обратно и делать. Только если попробовал и понял, что это приводит к тому, что придётся ещё пару недель работать, то тогда да, выделать отдельный PR и issue.  

Минутка философствования от меня: перенос всего и вся в отдельные issue приводит к двум вещям: 1) раздел с тикетами раздувается до нескольких сотен так что уже даже не помнишь что там было среди первых, которые висят незакрытыми. И 2) я всегда держу в голове фразу "нет ничего более постоянного, чем временное". Предлагаю делать так же. Некоторые костыли живут в проекте годами только потому что руки до них не доходят. Плюс со временем те особенности реализаций, которые сейчас у тебя в голове, забудутся, и при работе над задачей, на которую сегодня/завтра тратится 2-3 часа тебе придется проводить 8 например через месяц.

Поэтому мои мысли такие: для композера ок - это действительно задача не данного PR. Но вот тюнер попробовать применить явно стоит. Ты уже запускал его на этих данных? Если не получается, то да, пусть будет отдельный PR. Но просто если работает, то почему бы не потюнить

2022-04-06 09:05 UTC, Dreamlone reviewed
В целом все ок, осталось только с random_state = 42 ещё разобраться. Может @nicl-nno подскажет стоит ли вводить тут определение random_state через randint, чтобы разбиение все таки отличалось от запуска к запуску. Или это для чего-то конкретного так задумывалось?

2022-04-06 09:59 UTC, Dreamlone commented
Ну и unit тест ещё нужен - стоит не забыть

2022-04-06 15:14 UTC, andreygetmanov commented
> Ещё стоит написать тест на мультимодальную функциональность, которая уже есть. Вроде таких тестов ещё нет, по крайней мере я не нашёл для случая "картинки + текст + таблицы"

https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/pipelines/test_multi_modal.py

Этот тест генерирует и запускает пайплайн для случая "картинки + текст + таблицы". Нужно как-то дополнить его функционал? Не совсем понимаю, что можно в него добавить

2022-04-06 16:39 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
> Но просто если работает, то почему бы не потюнить

Тюнер запускается и, кажется, тюнит

2022-04-06 17:59 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
> Поэтому мои мысли такие: для композера ок - это действительно задача не данного PR. Но вот тюнер попробовать применить явно стоит. Ты уже запускал его на этих данных? Если не получается, то да, пусть будет отдельный PR. Но просто если работает, то почему бы не потюнить

Тюнер запускается, но не тюнит. Создал issue для композера и тюнера.

2022-04-06 18:23 UTC, nicl-nno commented
>чтобы разбиение все таки отличалось от запуска к запуску

Да вроде в примере это не обязательно.

2022-04-07 12:22 UTC, Dreamlone commented on cases/multi_modal_genre_prediction.py
> +        pipeline_evo_composed.show()
Ага, вижу

2022-04-07 12:26 UTC, Dreamlone commented
> Да вроде в примере это не обязательно.

Для примера - определенно да. Но мой вопрос про то, стоит ли оставлять такой момент во внутренних функциях. То есть если [random seed не меняется в `_split_any`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/data/data_split.py#L88) никогда, алгоритм всегда будет делать одно и то же разбиение на всех запусках

2022-04-07 12:28 UTC, Dreamlone requested changes
Сделай пожалуйста ребейз, и думаю, можно мерджить

2022-04-07 12:30 UTC, nicl-nno commented
> > Да вроде в примере это не обязательно.
> 
> Для примера - определенно необязательно. Но мой вопрос про то, стоит ли оставлять такой хардкод во внутренних функциях. То есть если [random seed не меняется в `_split_any`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/data/data_split.py#L88) никогда, алгоритм всегда будет делать одно и то же разбиение на всех запусках

Ок, это действительно можно убрать. Хотя оно и не в этом PR-е появилось.

2022-04-07 14:03 UTC, andreygetmanov commented
> Ок, это действительно можно убрать. Хотя оно и не в этом PR-е появилось.

Создать issue по этому поводу?

2022-04-07 14:12 UTC, nicl-nno commented
Можешь просто убрать.

2022-04-07 14:35 UTC, merged