fix_available_operations
nccr-itmo/FEDOT pull request #582
Opened 2022-03-03 09:43 UTC by maypink

Now the setting of composer_params['available_operations'] affects the initial assumption and mutations. The initial assumption is built only from the available operations and boosting mutation can no longer add nodes to the pipeline with operations/models that are not specified in the 'available_operations' (if composer_params['available_operations'] is specified)

2022-03-03 09:46 UTC, maypink commented
Сейчас логика в том, что:

2022-03-03 10:22 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        if not composer_params['available_operations']:
Я правильно понимаю, что эта запись сделана как эквивалент предыдущей? 
Просто на всякий случай отмечу, что поведение все таки немного отличается вот в таком случае
```
a = []
print(not a)
print(a is None)
```
Но вроде это нигде сильно ни на что повлиять не должно

2022-03-04 14:27 UTC, maypink commented on fedot/api/api_utils/api_composer.py
> +        if not composer_params['available_operations']:
мы это обсудили после и пришли к выводу, что все норм

2022-03-04 14:34 UTC, maypink commented
Логика обновилась ;) теперь формирование начального приближения происходит только для унимодальных данных. 
*для временных рядов* нода 'lagged' + одна рандомная модель регресси после (выбранная из пересечения множеств доступных операций и рег. моделей из репо)
*для регрессии и классификации* одна рандомная модель так же выбранная из пересечения множеств доступных операций и соотв. задаче моделей из репо
в случае, если заданные начальные операции не соответствуют решаемой задаче, попадаем [сюда](https://github.com/nccr-itmo/FEDOT/pull/582/commits/d1004da56867e0f7256d0b778b703f22393b408f#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R84-R88) и выдаем initial_assumption как если бы операции не были заданы
вот

2022-03-05 08:35 UTC, Dreamlone requested changes

2022-03-05 08:35 UTC, Dreamlone commented on examples/advanced/fedot_based_solutions/external_optimizer.py
> +                   preset='fast_train', composer_params=composer_params)
Я правильно понимаю, что тут было решено совместить тестирование внешнего оптимизатора и 'available_operations'? 

Лучше избежать тестирования двух функциональностей в одном unit тесте, а написать новый, который проверяет, что действительно при задаче available operations через API 1) формируется корректное начальное приближение (это тест номер один) и 2) primary и secondary операции в композере соответствуют начальному перечню моделей, которые определил пользователь (это пусть будет второй тест)

2022-03-05 08:35 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                                               composer_params['available_operations'], api_params['logger'])
Стоит вынести в отдельный метод

2022-03-05 08:35 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +        return operations_to_choose_from
Мб просто использовать intersection у множеств в Python?

2022-03-05 08:35 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +            elif not node.nodes_from and not self.operator.node_children(node) and node != self.root_node:
А объясни плиз зачем добавлено дополнительное условие

2022-03-05 08:35 UTC, Dreamlone commented on fedot/core/composer/gp_composer/specific_operators.py
> +        new_model = choice(boosting_model_candidates)
Кмк стоит вынести в отдельную функцию

2022-03-05 08:35 UTC, Dreamlone commented on fedot/core/composer/gp_composer/specific_operators.py
> +        all_data_operations.append('lagged')
А в проверке выше (см. строки 80-90) не производится схожий учет потребности lagged операции в пайплайне?

2022-03-05 08:35 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +                                       "available operations, default initial assumption will be used")
Сообщение можно объявить повыше и переиспользовать его тут и в логах ниже

2022-03-05 08:35 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +                    node_final = SecondaryNode(choice([operations_to_choose_from]), nodes_from=[node_lagged])
А если operations_to_choose_from будут представлены только моделями временных рядов, например "ar" или "arima"? - вроде пайплайн получится некорректным

2022-03-05 08:40 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +            elif not node.nodes_from and not self.operator.node_children(node) and node != self.root_node:
потому что если граф состоит только из root_node, то без этого условия рут нода удалится под видом изолированной

2022-03-05 08:58 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +            elif not node.nodes_from and not self.operator.node_children(node) and node != self.root_node:
Ок, теперь понял, спасибо

2022-03-05 12:54 UTC, maypink commented on fedot/api/api_utils/initial_assumptions.py
> +                    node_final = SecondaryNode(choice([operations_to_choose_from]), nodes_from=[node_lagged])
это мы решили устно

2022-03-05 12:55 UTC, maypink commented on fedot/api/api_utils/initial_assumptions.py
> +                                       "available operations, default initial assumption will be used")
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/603ecaee60346be313740446e03e23123330f8a1#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R15)

2022-03-05 12:59 UTC, maypink commented on fedot/core/composer/gp_composer/specific_operators.py
> +        all_data_operations.append('lagged')
я все-таки посмотрела еще раз и подумала, что если добавлять 'lagged' в available_operations [где ты предложил](https://github.com/nccr-itmo/FEDOT/blob/fix_available_operations/fedot/core/composer/gp_composer/specific_operators.py#L73), то придется поднимать выше определение самих available_operations и логика будет размазана по всему методу, тебе не кажется, что лучше таки так....

2022-03-05 13:00 UTC, maypink commented on fedot/core/composer/gp_composer/specific_operators.py
> +        new_model = choice(boosting_model_candidates)
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/603ecaee60346be313740446e03e23123330f8a1#diff-059ec354537ba96e9848bd54fe1320f3fefcb434caedb0a5e111a03c9d62428dR102)

2022-03-05 13:00 UTC, maypink commented on fedot/api/api_utils/initial_assumptions.py
> +        return operations_to_choose_from
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/603ecaee60346be313740446e03e23123330f8a1#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R55)

2022-03-05 13:00 UTC, maypink commented on fedot/api/api_utils/api_composer.py
> +                                               composer_params['available_operations'], api_params['logger'])
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/603ecaee60346be313740446e03e23123330f8a1#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR153)

2022-03-05 13:04 UTC, maypink commented on examples/advanced/fedot_based_solutions/external_optimizer.py
> +                   preset='fast_train', composer_params=composer_params)
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/603ecaee60346be313740446e03e23123330f8a1#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R94)
там получается первые два теста проверяют, что available_operation в целости сохранности дошли и повлиялили на формирование initial_assumption, а третий про корректное деление в композере на праймари/секондари. в третьем кажется можно взаимодействовать только с ApiComposer, тк двумя предыдущими тестами уже проверен весь путь, что был до

2022-03-05 13:33 UTC, Dreamlone requested changes

2022-03-05 13:33 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +                    raise NotImplementedError(f"Don't have initial pipeline for task type: {task.task_type}")
Вот эта часть тяжеловата, я бы предложил вынести в отдельную функцию

2022-03-05 13:35 UTC, nicl-nno commented on fedot/core/composer/gp_composer/specific_operators.py
> +        if node.content['name'].__str__() not in available_operations:
А str(node.content['name']) не годится?

2022-03-05 13:36 UTC, Dreamlone commented on fedot/core/composer/gp_composer/specific_operators.py
> +        all_data_operations.append('lagged')
Ок, пусть останется как есть

2022-03-05 15:49 UTC, nicl-nno approved these changes

2022-03-09 07:54 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`fedot/api/api_utils/initial_assumptions.py`](https://github.com/nccr-itmo/FEDOT/blob/fe8ebd15cb7df27cac75dc89895e26ca4a15b2f6/fedot/api/api_utils/initial_assumptions.py):

> [Line 109:121](https://github.com/nccr-itmo/FEDOT/blob/fe8ebd15cb7df27cac75dc89895e26ca4a15b2f6/fedot/api/api_utils/initial_assumptions.py#L109): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)

2022-03-09 08:06 UTC, maypink commented on fedot/api/api_utils/initial_assumptions.py
> +                    raise NotImplementedError(f"Don't have initial pipeline for task type: {task.task_type}")
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/fe8ebd15cb7df27cac75dc89895e26ca4a15b2f6#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R109)

2022-03-09 08:10 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +                    raise NotImplementedError(f"Don't have initial pipeline for task type: {task.task_type}")
Кул, но лучше все таки название изменить у метода - мы ведь вроде редко когда хотим создавать некорректные пайплайны, чтобы выделять случаи, когда мы создаем именно корректные) В названии стоит сделать упор на то, что пайплайны в методе создаются из ограниченного пользователем перечня моделей / операций

2022-03-09 08:11 UTC, maypink commented on fedot/core/composer/gp_composer/specific_operators.py
> +        if node.content['name'].__str__() not in available_operations:
[а годится](https://github.com/nccr-itmo/FEDOT/pull/582/commits/fe8ebd15cb7df27cac75dc89895e26ca4a15b2f6#diff-059ec354537ba96e9848bd54fe1320f3fefcb434caedb0a5e111a03c9d62428dR93)

2022-03-09 08:33 UTC, maypink commented on fedot/api/api_utils/initial_assumptions.py
> +                    raise NotImplementedError(f"Don't have initial pipeline for task type: {task.task_type}")
[done](https://github.com/nccr-itmo/FEDOT/pull/582/commits/c145fe2219be707af60e53dbde90cc59e7c23f68#diff-9c93dd584f4bfae59e00f931b8bce639082f546139f4be2ac776e7da4480c566R67)

2022-03-09 08:42 UTC, Dreamlone approved these changes

2022-03-09 09:56 UTC, merged

2022-03-09 10:00 UTC, maypink commented
fixes #582