Multi ts type
nccr-itmo/FEDOT pull request #583
Opened 2022-03-03 10:07 UTC by ChrisLisbon

2022-03-03 10:07 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`cases/arctic_ssh_custom.py`](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/arctic_ssh_custom.py):

> [Line 54:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/arctic_ssh_custom.py#L54): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 57:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/arctic_ssh_custom.py#L57): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 62:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/arctic_ssh_custom.py#L62): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 152:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/arctic_ssh_custom.py#L152): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

* In the file [`cases/multiple_lagged_arctic.py`](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/multiple_lagged_arctic.py):

> [Line 175:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/multiple_lagged_arctic.py#L175): [E305](https://duckduckgo.com/?q=pep8%20E305) expected 2 blank lines after class or function definition, found 1
> [Line 176:5](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/multiple_lagged_arctic.py#L176): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '
> [Line 178:1](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/cases/multiple_lagged_arctic.py#L178): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`examples/advanced/time_series_forecasting/custom_model_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/examples/advanced/time_series_forecasting/custom_model_tuning.py):

> [Line 141:121](https://github.com/nccr-itmo/FEDOT/blob/f2722dce21cb3b8e950d459d8d52e7157a60ef94/examples/advanced/time_series_forecasting/custom_model_tuning.py#L141): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2022-03-15 14:04 UTC, nicl-nno requested changes
И ещё явно нужен тест на статичный пайплайн с multi-ts данными.

2022-03-15 14:22 UTC, Dreamlone requested changes

2022-03-15 14:22 UTC, Dreamlone commented on fedot/core/composer/gp_composer/gp_composer.py
>              self.log.info(f'Pipeline assessment warning: {ex}. Continue.')
Надо будет потом не забыть снести эту штуку с show

2022-03-15 14:22 UTC, Dreamlone commented on fedot/core/data/merge.py
> +    # if indeces repeats (for multi_ts data type)
очепятка в индексах

2022-03-15 14:22 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                    all_transformed_idx = np.hstack((all_transformed_idx, np.array(new_idx)))
Здесь очень много if-в. И до твоих изменений их было немало, а стало заметно больше) 
Поэтому предлагаю организовать 1) либо отдельную операцию для предобработки multi ts данных, похожую на lagged, 2) либо вынести все вот эти функции в отдельный класс (потомок или просто новый какой-то) - это возможно сделать?

2022-03-17 08:12 UTC, valer1435 requested changes

2022-03-17 08:12 UTC, valer1435 commented on fedot/api/api_utils/initial_assumptions.py
> +        is_milti_ts = data.data_type == DataTypesEnum.multi_ts
is_multi_ts вероятно

2022-03-17 08:12 UTC, valer1435 commented on fedot/api/api_utils/initial_assumptions.py
> +                                                                          logger, is_milti_ts)
Кажется, что флаг лишний, если можно передать специфичный task/data multi_ts

2022-03-21 16:50 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                    all_transformed_features = np.hstack((all_transformed_features, transformed_cols))
[Вынесла](https://github.com/nccr-itmo/FEDOT/pull/583/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R143-R160)

2022-03-21 16:55 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                full_smoothed_ts.append(smoothed_ts)
[Вынесла](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L318-L324)

2022-03-21 17:10 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                                  data_type=DataTypesEnum.ts)
Поправила

2022-03-21 17:10 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                                  data_type=DataTypesEnum.ts)
Поправила

2022-03-21 17:12 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            validate(object_for_validation, rules, params.advisor.task)
Убрала

2022-03-21 17:13 UTC, ChrisLisbon commented on fedot/core/repository/dataset_types.py
> +    # Table with columns as supporting time-series
[Пояснила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/repository/dataset_types.py#L11) чуть подлиннее

2022-03-21 17:21 UTC, ChrisLisbon commented on cases/multi_ts_arctic_forecasting.py
> +    composer_requirements = PipelineComposerRequirements(
[Перенесла](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py) в cases, добавила [пример](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/cases/multi_ts_level_forecasting.py) через API

2022-03-21 17:38 UTC, ChrisLisbon commented on fedot/core/data/merge.py
> +                                  DataTypesEnum.multi_ts: self.combine_datasets_table,
Новый метод пока отложила, потому что там есть необходимость только в небольшой проверке на дублирование в третьей вложенной функции [tables_mapping](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/data/merge.py#L321-L368) к подобному методу. Изменения не стоят целого метода. Думала думала как это можно хоть немного изящно преобразовать, пока все равно кажется, что по хорошему это под отдельный таск рефакторинга записать

2022-03-21 17:41 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                    all_transformed_idx = np.hstack((all_transformed_idx, np.array(new_idx)))
Пока вынесла в [функции](https://github.com/nccr-itmo/FEDOT/pull/583#discussion_r831326964) с ключом по типу данных, вроде читабельно

2022-03-21 17:42 UTC, nicl-nno commented on fedot/core/repository/dataset_types.py
> +    # Table with columns as supporting time-series
Кмк всё ещё непонятно. Мб лучше как-то так:

Table with different variant of time-series for the same variable as ciolumns (used for extending train sample).

2022-03-21 17:51 UTC, ChrisLisbon commented on fedot/api/api_utils/initial_assumptions.py
> +                                                                          logger, is_milti_ts)
Флаг убрала, теперь извлекаю его внутри [функции](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/api/api_utils/initial_assumptions.py#L100-L105)

2022-03-21 17:57 UTC, ChrisLisbon commented on fedot/core/data/merge.py
> +    repeats_num = int(min(obj.shape[0] for obj in object_list)/len(common_idx))
Применимо ко всем дублирующимся индексам, но осознанно это делается только в multi_ts типе данных. Я там по факту изменены только две строчки с повторной записью, если repeats_num > 1, пыталась вынести отдельно, но в рамках [tables_mapping](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/data/merge.py#L321-L368) это не имеет особо смысла, нужно видимо как-то всю структуру пересматривать.
У Миши было похожее [предложение](https://github.com/nccr-itmo/FEDOT/pull/583#discussion_r827028994)

2022-03-21 18:05 UTC, ChrisLisbon commented on fedot/core/repository/dataset_types.py
> +    # Table with columns as supporting time-series
[Done](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/repository/dataset_types.py#L11)

2022-03-21 18:23 UTC, ChrisLisbon commented on cases/multi_ts_arctic_forecasting.py
> +    plt.show()
Подписи [добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/cases/multi_ts_level_forecasting.py#L41-L42) и [добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py#L145-L146)

А прогнозирование и правда бывает получше, просто тебе что-то не повезло)
![image](https://user-images.githubusercontent.com/44952202/159337257-5abf9c63-de90-44e0-a0a5-aab23b99a3c5.png)
Мой запуск не то чтобы сильно лучше, но есть разнообразие.

2022-03-21 18:26 UTC, ChrisLisbon commented on fedot/core/data/merge.py
> +    repeats_num = int(min(obj.shape[0] for obj in object_list)/len(common_idx))
Условие if [добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/data/merge.py#L336-L339)

2022-03-22 10:18 UTC, Dreamlone commented on fedot/core/data/data.py
> +
Добавь сюда плиз docstring описание что за multi_time_series тут вытаскиваются из файла

2022-03-22 10:18 UTC, Dreamlone commented on fedot/core/data/data_split.py
> +    :param data: array with data to split (not InputData)
Стоит type hint проставить), чтобы было понятно что за покемон не InputData

2022-03-22 10:18 UTC, Dreamlone commented on examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py
> +
Стоит кмк округлять значения для удобочитаемости

2022-03-22 10:18 UTC, Dreamlone commented on fedot/core/data/merge.py
> +                                  DataTypesEnum.multi_ts: self.combine_datasets_table,
Оке, логика похоже и правда пересекается с не-multi-ts данными

2022-03-22 10:25 UTC, nicl-nno approved these changes

2022-03-22 10:46 UTC, Dreamlone requested changes

2022-03-22 10:46 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +from fedot.core.pipelines.validation import validate
Лишний импорт

2022-03-22 10:46 UTC, Dreamlone commented on test/data/model_repository.json
> +	  "input_type": "[DataTypesEnum.ts, DataTypesEnum.multi_ts]",
Тогда наверно стоит добавить в custom_time_series_transformation из data_operation_repository.json

2022-03-22 10:46 UTC, Dreamlone commented on test/unit/tasks/test_multi_ts_forecast.py
> +    task = Task(TaskTypesEnum.ts_forecasting,
Давай лучше в названии get_multi_ts_data

2022-03-22 10:46 UTC, Dreamlone commented on test/unit/tasks/test_multi_ts_forecast.py
> +    assert len(prediction) == len(test_data.target)
Может сгенерировать файлы с линейно возрастающими значениями, вроде 1, 2, 3, 4, 5 ... 
И потом тренировать на них пайплайн с линейными моделями. Тогда можно будет проверить корректность формируемого прогноза (а не только соответствие длин предсказанных значений)

2022-03-22 10:46 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                                  data_type=input_data.data_type)
Часть с output_data можно вынести вниз (транспонировать не нужно кстати?)

2022-03-22 10:46 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                              data_type=input_data.data_type)
Есть ещё вопрос про ExogDataTransformationImplementation. А он сможет работать с новым типом данных?

2022-03-22 17:19 UTC, ChrisLisbon commented on examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py
> +
[Добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py#L150-L155) округление

2022-03-22 17:22 UTC, ChrisLisbon commented on fedot/core/data/data.py
> +
[Добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/data/data.py#L110-L118) полный докстринг

2022-03-22 17:22 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +from fedot.core.pipelines.validation import validate
Убрала

2022-03-22 17:24 UTC, ChrisLisbon commented on test/data/model_repository.json
> +	  "input_type": "[DataTypesEnum.ts, DataTypesEnum.multi_ts]",
[Добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/repository/data/data_operation_repository.json#L73)

2022-03-22 17:25 UTC, ChrisLisbon commented on test/unit/tasks/test_multi_ts_forecast.py
> +    task = Task(TaskTypesEnum.ts_forecasting,
[Переименовала](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/test/unit/tasks/test_multi_ts_forecast.py#L13)

2022-03-22 17:27 UTC, ChrisLisbon commented on test/unit/tasks/test_multi_ts_forecast.py
> +    assert len(prediction) == len(test_data.target)
Добавила [файл](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/test/data/synthetic_multi_ts.csv)
Поправила [тест](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/test/unit/tasks/test_multi_ts_forecast.py#L54-L59)

2022-03-22 17:37 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +                                              data_type=input_data.data_type)
В данной реализации нет, но тут идея то в том, что таргет находится в пачке расширенных данных, чтобы лучше переменная сама себя прогнозировала. Мне кажется прогнозировать одну переменную, а расширять обучающую выборку для другой не особо имеет смысл.

2022-03-22 19:25 UTC, Dreamlone approved these changes

2022-03-22 19:25 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        all_features = np.vstack((all_features, features))
Стоит расставить type hints и docsting описать, чтобы было понятно в чем заключается разница между multi ts и multivariate ts

2022-03-23 10:04 UTC, ChrisLisbon commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        all_features = np.vstack((all_features, features))
[Добавила](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_type/fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py#L152-L186)

2022-03-23 10:05 UTC, valer1435 approved these changes

2022-03-23 10:13 UTC, merged