Fast ICA implementation
nccr-itmo/FEDOT pull request #585
Opened 2022-03-03 15:49 UTC by technocreep

[ISSUE](https://github.com/nccr-itmo/FEDOT/issues/429)

@v1docq

2022-03-03 21:39 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +				"applicable_for_ts"
А зачем applicable_for_ts указывать?

>independent_components_extraction
А такой тэг для каких-то операций кроме этой может пригодиться?

2022-03-03 21:40 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
Кажетя такого блока метаданых в json-е нет

2022-03-04 07:43 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
согласен, тут я совсем не подумал. Должно быть classification_preprocessing?

2022-03-04 07:44 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
согласен, тут я совсем не подумал. Должно быть classification_preprocessing?

2022-03-04 07:45 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
просто я работал по аналогии PCA и kPCA, но здесь `dimension_transformation `по идее быть не может, ведь ICA не про понижение размерности

2022-03-04 07:52 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +				"applicable_for_ts"
не могу ответить. Реквестирую пояснительные материалы про тэги и метаданные

2022-03-05 09:56 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
Он про повышение размерности - выглядит как частные случай dimension_transformation. В любом случае, здесь важен не текст названия, а применимость метаданных из вот этого блока для новой операции:

![image](https://user-images.githubusercontent.com/5711814/156878261-a2e86448-9efa-44fc-a6da-6a8221ad1066.png)

2022-03-05 09:57 UTC, nicl-nno commented on fedot/core/repository/data/data_operation_repository.json
> +				"applicable_for_ts"
Новые добавлять не нужно, нужно указывать по аналогии с схожими операциями.

Тег correct_params значит что модель сама может менять гиперпараметры в ходе обучения.

2022-03-05 10:13 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +			"meta": "independent_components_extraction",
спасибо за пояснения! исправления в следующем коммите

2022-03-05 10:29 UTC, technocreep commented on fedot/core/repository/data/data_operation_repository.json
> +				"applicable_for_ts"
учтено, спасибо!

2022-03-09 13:38 UTC, Dreamlone requested changes
Нужно ещё вот [сюда](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/search_space.py) внести границы гиперпараметров и проверить как операция работает при разных значениях - то есть позапускать тюнинг параметров на пайплайне с новой операцией в своей структуре 

Также может имеет смысл добавить значение гиперпараметров по умолчанию в [этот файл](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/repository/data/automl_repository.json)

2022-03-09 13:38 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py
> +
Мб стоит обновить описание, добавить `FastICA` вместо `PCA`

2022-03-10 14:35 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
>              },
Добавь ещё в kernel_pca ядра плиз

2022-03-10 15:07 UTC, nicl-nno commented
Ребейз только не забудь сделать.

2022-03-10 15:07 UTC, nicl-nno commented
Ребейз только не забудь сделать.

2022-03-10 15:41 UTC, merged