Timeouts api refactor
nccr-itmo/FEDOT pull request #587
Opened 2022-03-05 14:55 UTC by Dreamlone

Setting parameters via API has become a bit more clear

Also added a test for path compatibility during serialization. Slightly extended the list of initial assumptions for tabular data with linear models

2022-03-05 15:19 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        if timeout_for_tuning < 15:
Стоит наверное вынести в константы (мб вообще отдельный скрипт для них создать)

2022-03-05 15:27 UTC, nicl-nno commented on fedot/pattern_wrappers.py
> +def singleton(class_):
Может это не в корень, а в https://github.com/nccr-itmo/FEDOT/tree/master/fedot/utilities?

2022-03-09 09:00 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        if timeout_for_tuning < 15:
Так и сделал [тут](https://github.com/nccr-itmo/FEDOT/pull/587/commits/a234dda0e80b6a10b7dede67b0ebc54860006e3e#diff-4ef9b7a2a2edfb22283c66a7a8b1fc6a6e9c9f10387c9d4854aef6a729a00c69R1-R2), потом расширил следующим [коммитом](https://github.com/nccr-itmo/FEDOT/pull/587/commits/dca4f5bf7ecb300e363d76aa0238fe3d0a498ea5#diff-4ef9b7a2a2edfb22283c66a7a8b1fc6a6e9c9f10387c9d4854aef6a729a00c69R3-R5)

2022-03-09 09:00 UTC, Dreamlone commented on fedot/pattern_wrappers.py
> +def singleton(class_):
[Перенёс](https://github.com/nccr-itmo/FEDOT/pull/587/commits/a234dda0e80b6a10b7dede67b0ebc54860006e3e#)

2022-03-10 12:56 UTC, IIaKyJIuH requested changes

2022-03-10 12:56 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_composer.py
> +            timer.start_composing()
Здесь тоже пригодился бы контекстный менеджер на таймере, тогда бы не пришлось в 
[`tune_final_pipeline(...)->determine_resources_for_tuning()`](https://github.com/nccr-itmo/FEDOT/pull/587/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR317) вызывать у него [`end_composing()`](https://github.com/nccr-itmo/FEDOT/pull/587/files#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R46)

2022-03-10 12:56 UTC, IIaKyJIuH commented on fedot/api/time.py
> +        return self.composing_spend_time
Точно ли здесь и в [`end_tuning()`](https://github.com/nccr-itmo/FEDOT/pull/587/files#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R57) понадобится возвращать значения соответствующих полей?

2022-03-10 12:56 UTC, IIaKyJIuH commented on fedot/api/api_utils/params.py
> +    return api_params
Я сам частично писал этот код и только сейчас заметил косяк.

Строки [165, 167, 169, 170] можно убрать, потому что там перезапись того же самого значения.

2022-03-10 13:26 UTC, nicl-nno commented on test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
> +}
Для JSON-ов это вроде не специфицировано.

2022-03-10 13:41 UTC, Dreamlone commented on fedot/api/time.py
> +        spended_time_for_composing = self.end_composing() + self.init_pipeline_fit_time
Пока прикрыл вот [такой проверкой](https://github.com/nccr-itmo/FEDOT/pull/587/commits/805fb2f45a122787102350eadadd5221c025ae92#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R69-R71)
Хотя конечно не люблю самостоятельно выбрасывать ошибки, но здесь это поможет не напортачить при внесении изменений в API

2022-03-10 13:41 UTC, Dreamlone commented on fedot/api/time.py
> +        if self.time_for_automl is None:
Согласен, [сделал](https://github.com/nccr-itmo/FEDOT/pull/587/commits/805fb2f45a122787102350eadadd5221c025ae92#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95L34-L35)

2022-03-10 13:45 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        timeout_were_set = timer.datetime_composing not in [-1, None]
Учел, [исправил](https://github.com/nccr-itmo/FEDOT/pull/587/commits/805fb2f45a122787102350eadadd5221c025ae92#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fL237-L238)

2022-03-10 13:46 UTC, Dreamlone commented on fedot/api/api_utils/constants.py
> +DEFAULT_TIMEOUT_API_MINUTES = 5.0
Ну ты завернул
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/587/commits/805fb2f45a122787102350eadadd5221c025ae92#diff-4ef9b7a2a2edfb22283c66a7a8b1fc6a6e9c9f10387c9d4854aef6a729a00c69L1-R3)

2022-03-10 13:48 UTC, Dreamlone commented on test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
> +}
Не стоит. Как FEDOT сериализует модели, так лучше и оставлять кмк

2022-03-10 13:49 UTC, Dreamlone commented on fedot/api/api_utils/params.py
> +    return api_params
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/587/commits/805fb2f45a122787102350eadadd5221c025ae92#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8L165-L173)

2022-03-10 14:08 UTC, v1docq reviewed
Small review

2022-03-10 14:27 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +from fedot.api.api_utils.constants import MINIMAL_SECONDS_FOR_TUNING, DEFAULT_TUNING_ITERATIONS_NUMBER
По заглавному шрифту, ага, действуем по стандартному [соглашению по неймингу](https://pythonz.net/references/named/constants/)

По поводу всех констант вполне может быть резонно. Можно подготовить этот файл где-то рядом с `core`. Собственно, так и сделал в этом [коммите](https://github.com/nccr-itmo/FEDOT/pull/587/commits/1739a40967df5872ab0a5ade952826ff4ddefafd). Потом можем с течением времени туда сносить подобные константы

2022-03-10 14:27 UTC, Dreamlone commented on fedot/api/api_utils/params.py
> -                  'max_arity': 4,
Согласен, [изменил](https://github.com/nccr-itmo/FEDOT/pull/587/commits/1739a40967df5872ab0a5ade952826ff4ddefafd#diff-35c9039b23102036436d1536f49036a1cdfa7214c697fbd184e84071246dead8L118-R119)

2022-03-10 14:29 UTC, Dreamlone commented on fedot/api/time.py
> +        spended_time_for_composing = self.end_composing() + self.init_pipeline_fit_time
Update, решил просто вынести init_pipeline_fit_time как аргумент в метод determine_resources_for_tuning. Пришлось его протащить через метод в API, зато теперь исключена (я надеюсь), проблема с тем, что init_pipeline_fit_time будет None

2022-03-10 14:30 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            timer.end_tuning()
Решил запускать в with отдельно взятые методы, например, как [здесь](https://github.com/nccr-itmo/FEDOT/pull/587/commits/1739a40967df5872ab0a5ade952826ff4ddefafd#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR339-R352)

2022-03-10 14:31 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            timer.start_composing()
Согласен, [исправил](https://github.com/nccr-itmo/FEDOT/pull/587/commits/1739a40967df5872ab0a5ade952826ff4ddefafd#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fL246-R251)

2022-03-10 14:33 UTC, v1docq commented on fedot/api/api_utils/api_composer.py
> +from fedot.api.api_utils.constants import MINIMAL_SECONDS_FOR_TUNING, DEFAULT_TUNING_ITERATIONS_NUMBER
Тогда держим константы в одном месте

2022-03-10 14:33 UTC, v1docq approved these changes
С изменениями согласен

2022-03-10 14:33 UTC, Dreamlone commented on fedot/api/time.py
> +        return self.composing_spend_time
Нет, [убрал этот момент](https://github.com/nccr-itmo/FEDOT/pull/587/commits/1739a40967df5872ab0a5ade952826ff4ddefafd#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R41-R48)

2022-03-11 09:02 UTC, valer1435 approved these changes

2022-03-11 12:30 UTC, IIaKyJIuH commented on fedot/api/api_utils/constants.py
> +DEFAULT_TIMEOUT_API_MINUTES = 5.0
Соре, само вырвалось)

2022-03-11 13:11 UTC, IIaKyJIuH commented on test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
> +}
Просто заметил, что GitHub ругается на отсутствие пустой строки.

Не принципиально, но может стоит тогда вообще сделать issue по сериализации моделей с добавлением пустой строки?

2022-03-11 13:18 UTC, Dreamlone commented on test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
> +}
Мне кажется, не стоит. Коля верно написал, что для не .py по стандарту PEP8 не предусмотрено подобных стилистических правил. А на gihub лучше в этом плане не смотреть, главное, чтобы PEP8 бот не ругался)

2022-03-11 13:36 UTC, ChrisLisbon approved these changes

2022-03-11 14:59 UTC, IIaKyJIuH commented on fedot/api/time.py
> +            self.log.info('Algorithm was terminated due to processing time limit')
Лишний метод

2022-03-11 14:59 UTC, IIaKyJIuH commented on test/data/pipeline_with_old_paths/pipeline_with_old_paths.json
> +}
Тогда всё отлично)

2022-03-11 15:00 UTC, IIaKyJIuH commented on fedot/api/api_utils/api_composer.py
> +            timer.end_tuning()
Красиво получилось, молодец

2022-03-11 15:47 UTC, IIaKyJIuH requested changes

2022-03-11 15:47 UTC, IIaKyJIuH commented on fedot/api/time.py
> +        self.composing_spend_time = datetime.datetime.now() - self.starting_time_for_composing
Полагаю, теперь часть с "return" не нужна, а на её место можно поставить 50 строку, взяв обратное условие.

Точно так же можно поступить и с [`launch_tuning()`](https://github.com/nccr-itmo/FEDOT/pull/587/files#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R53)

2022-03-11 16:27 UTC, Dreamlone commented on fedot/api/time.py
> +            self.log.info('Algorithm was terminated due to processing time limit')
Да, чего то я тут погорячился, [убрал](https://github.com/nccr-itmo/FEDOT/pull/587/commits/6d085ee2d52f7f2ed1f45d564a37fc74fefea6c9)

2022-03-11 16:29 UTC, Dreamlone commented on fedot/api/time.py
> +        self.composing_spend_time = datetime.datetime.now() - self.starting_time_for_composing
Согласен, даже проще, можно просто убрать блок с проверкой "if", так как self.starting_time_for_composing None точно быть не может, так как запускается прямо в этом же методе
[Коммит](https://github.com/nccr-itmo/FEDOT/pull/587/commits/6d085ee2d52f7f2ed1f45d564a37fc74fefea6c9)

2022-03-14 06:31 UTC, IIaKyJIuH commented on fedot/api/time.py
> +        self.composing_spend_time = datetime.datetime.now() - self.starting_time_for_composing
Ты прав

2022-03-14 06:31 UTC, IIaKyJIuH approved these changes

2022-03-14 06:34 UTC, merged