Serialization logic modified
nccr-itmo/FEDOT pull request #593
Opened 2022-03-11 16:05 UTC by nicl-nno

The main change is that uid assigned to unividuals instead graphs and pipelines. 
It allow simplifying the tracking of ancestors

2022-03-11 16:05 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





































* In the file [`test/unit/composer/test_history.py`](https://github.com/nccr-itmo/FEDOT/blob/5f1525d00f51ff8e98e0fa017b35a294555d6be8/test/unit/composer/test_history.py):

> [Line 95:38](https://github.com/nccr-itmo/FEDOT/blob/5f1525d00f51ff8e98e0fa017b35a294555d6be8/test/unit/composer/test_history.py#L95): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-03-16 18:13 UTC, IIaKyJIuH requested changes

2022-03-16 18:13 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +                    remaining_individuals.remove(individual)
Предлагаю сделать `remaining_individuals` множеством, чтобы асимптотически быстрее производить удаление

2022-03-16 18:13 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +            print("!")
Опять же условие упрощается до `not individuals`, а ещё может быть следует сделать более наглядный принт?

2022-03-16 18:13 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        individual = individuals[randint(0, len(individuals) - 1)]
Нагляднее воспользоваться `random.choice` просто

2022-03-16 18:13 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                            new_population += self.reproduce(selected_individuals[parent_num])
Здесь можно сделать то же самое, что предлагал для [`gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/pull/593/files#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R232-R236)

2022-03-17 10:35 UTC, nicl-nno commented on examples/simple/regression/api_regression.py
> +    print(os.getcwd())
Убрал.

2022-03-17 10:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +    if len(evaluated_individuals) == 0 and len(reversed_individuals) != 0:
Ок, пусть будет так.

2022-03-17 10:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                        new_population += self.reproduce(selected_individuals[parent_num])
Сделал так (в исправленнм виде).

2022-03-17 10:35 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/regularization.py
> +    is_multi_obj = population[0].fitness is MultiObjFitness
Поменял

2022-03-17 10:35 UTC, nicl-nno commented on test/unit/serialization/test_encoder.py
> +from .fixtures.serialization_fixtures import *
Указал конкретные фикстуры.

2022-03-17 10:35 UTC, nicl-nno commented on test/unit/serialization/test_decoder.py
> +from .fixtures.serialization_fixtures import *
Указал конкретные.

2022-03-17 10:35 UTC, nicl-nno commented on fedot/core/serializers/coders/parent_operator_serialization.py
> +        if isinstance(parent_ind, Individual)
Убрал проверку.

2022-03-17 10:35 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        self.archive_history.append(new_inds)
Ну разница во времени выглядит максимально незначительной)
Давай поменяю.

2022-03-17 10:35 UTC, nicl-nno commented on test/unit/serialization/test_encoder.py
> +
Чтобы pycharm не пытался оптимизировать импорты. Он почему-то не видит использование фикстур.

2022-03-17 10:35 UTC, nicl-nno commented on test/unit/composer/test_history.py
> +        assert len(crossover_result.parent_operators[0 - 1].parent_individuals) == 2
Поменял на просто -1, видимо опечатка была.

2022-03-17 10:36 UTC, nicl-nno commented on test/unit/composer/test_history.py
> +    assert operator_for_history.parent_individuals[0] == ind.uid
Поправил, действительно должен быть индивид

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
>      return serialized_obj
Удалил

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
>              for (idx, inner_node_idx), outer_node in product(enumerate(node.nodes_from), nodes):
Поменял

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/serializers/coders/opt_history_serialization.py
> +            for idx, parent_obj_id in enumerate(parent_op.parent_individuals):
Поменял

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        while len(chosen) < pop_size and n_iter < pop_size * 10 and len(remaining_individuals) > 0:
Поменял

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +                    remaining_individuals.remove(individual)
Может привести к непредвиденным последствия в слуаях, если где-то внутри селекции важен порядок.
А размер remaining_individuals все равно на практике вряд ли больше 100 будет.

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +            print("!")
Упросил и убрал print

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        individual = individuals[randint(0, len(individuals) - 1)]
Поменял на choice

2022-03-17 10:36 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                            new_population += self.reproduce(selected_individuals[parent_num])
Сделал

2022-03-17 11:18 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +                    remaining_individuals.remove(individual)
Тогда всё ок

2022-03-17 12:24 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        self.archive_history.append(new_inds)
Разница намного ощутимее (в миллион раз), если не кастовать результат функции `map(...)` к списку:
![image](https://user-images.githubusercontent.com/38308131/158805803-46a148c4-f0bd-434b-a272-86a371ccc2da.png)

Но такой способ будет давать возможность только одноразового обхода.
Это здесь не подходит, полагаю?

2022-03-17 12:26 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        self.archive_history.append(new_inds)
Тут все равно в итоге где-то будет приведение к списку, поэтому действительно не особо важно - учитывая для типовая длина <100

2022-03-17 12:49 UTC, IIaKyJIuH commented on examples/simple/regression/api_regression.py
> +    print(os.getcwd())
Забыл закоммитить изменение, видимо, строчка всё ещё здесь

2022-03-17 12:58 UTC, nicl-nno commented on examples/simple/regression/api_regression.py
> +    print(os.getcwd())
Да, поправил.

2022-03-17 13:16 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +        self.archive_history.append(new_inds)
Окей, тогда лучше, чтобы просто было читаемее)
Мне вариант с `list(map(...` видится более лаконичным, тебе же с list comprehension

Сейчас последнее слово за @gkirgizov

2022-03-17 13:21 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        self.archive_history.append(new_inds)
Максимально лаконичным вариантом тут вообще будет new_inds=deepcopy(individuals)

2022-03-17 13:55 UTC, IIaKyJIuH commented on test/unit/serialization/test_encoder.py
> +
Я понял, как это решить:
1. Нужно перенести содержимое файла с фикстурами в особый файл `conftest.py`, поместив его в папке с тестами
2. Удалить все импорты фикстур, они теперь будут подгружаться в тесты автоматически

2022-03-18 07:20 UTC, gkirgizov commented on fedot/core/serializers/coders/graph_serialization.py
> +                if inner_node_uid == outer_node.uid:
думаю, перед циклом можно создать lookup table {node.uid -> node} и избавиться от product, т.е. лишнего вложенного пробегания по nodes. да и логика очевиднее будет.

2022-03-18 07:20 UTC, gkirgizov commented on fedot/core/serializers/coders/opt_history_serialization.py
> +                    if parent_ind_uid == _ind.uid:
схоже. можно от внутреннего цикла избавиться, если заранее создать dict {ind.uid -> ind}.
тогда, кстати, можно просто по его `individuals_dict.values` пробегаться вместе `itertools.chain`

2022-03-18 15:08 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +            if individual.uid not in [c.uid for c in chosen]:
Ты имеешь в виду просто (c.uid for c in chosen)? Ну можно и так, сделал.

2022-03-18 15:08 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_operators.py
>          raise AttributeError('Too much fitness evaluation errors. Composing stopped.')
Поменял

2022-03-18 15:08 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        if individual.uid not in [c.uid for c in chosen]:
Аналогично, поменял.

2022-03-18 15:08 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        if best.uid not in [c.uid for c in chosen]:
Поменял

2022-03-18 15:08 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
>          raise ValueError('All evaluations of fitness was unsuccessful.')
Fixed

2022-03-18 15:09 UTC, nicl-nno commented on fedot/core/serializers/coders/opt_history_serialization.py
> +                    if parent_ind_uid == _ind.uid:
Сделал [так](https://github.com/nccr-itmo/FEDOT/pull/593/files#diff-42d9e7dc65d1ac470f8befcc39599bace41874eb80e40cf1d6ae0b336a3c60e1R13-R21)

2022-03-18 15:10 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
> +                if inner_node_uid == outer_node.uid:
Сделал [так](https://github.com/nccr-itmo/FEDOT/pull/593/files#diff-84dc3a31b73f8a174d5e4d35997a063a13d67535c56c24f7aa23bd7eb7553f3cR27-R32)

2022-03-18 15:11 UTC, gkirgizov approved these changes

2022-03-21 06:59 UTC, IIaKyJIuH requested changes

2022-03-21 06:59 UTC, IIaKyJIuH commented on fedot/core/serializers/coders/parent_operator_serialization.py
> +        for parent_ind in serialized_op['parent_individuals'] if parent_ind is not None
Не странно ли, что в массиве родителей могут возникать None-ы? Было бы логичнее, если бы оставался только пустой список

2022-03-21 10:47 UTC, nicl-nno commented on fedot/core/serializers/coders/parent_operator_serialization.py
> +        for parent_ind in serialized_op['parent_individuals'] if parent_ind is not None
Тут смысл в том, что при нескольких мутациях подряд не у всех сохраненных операторах есть реально существующие предки. Подумаю, можно ли это реализовать получше.

2022-03-21 16:59 UTC, nicl-nno commented on fedot/core/serializers/coders/parent_operator_serialization.py
> +        for parent_ind in serialized_op['parent_individuals'] if parent_ind is not None
Предлагаю пока оставить как есть - None символизирует что предок есть, но он не в популяции.
Потом возможно реализую прямые ссылки на операторы.

2022-03-21 21:27 UTC, IIaKyJIuH approved these changes

2022-03-22 09:49 UTC, merged