add SMAPE metric
nccr-itmo/FEDOT pull request #596
Opened 2022-03-15 12:59 UTC by maypink

2022-03-15 13:30 UTC, Dreamlone requested changes
Надо бы ещё для тюнера в `get_tuner_metrics_mapping` добавить

Upd: в описание хоть пару слов стоит добавить, что, мол, и в для тюнера, и для композера теперь может использоваться новая регресионная метрика

2022-03-15 13:30 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +                              (np.abs(reference.target) + np.abs(predicted.predict))))
Можно конструкцию упростить - вынести некоторые расчеты в отдельные переменные

2022-03-15 14:12 UTC, maypink commented on fedot/core/composer/metrics.py
> +                              (np.abs(reference.target) + np.abs(predicted.predict))))
[done](https://github.com/nccr-itmo/FEDOT/pull/596/commits/5f73301c5bbbd12d7a46c198411c4e3844632027#diff-7488db041ee4881f6441fe845b119323cb27e897f1694965bb978e1059228e66R174-R176)

2022-03-15 14:26 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +                              (np.abs(reference.target) + np.abs(predicted.predict))))
Тут `denominator = (np.abs(reference.target) + np.abs(predicted.predict))` можно скобочки убрать)

2022-03-15 14:46 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +                              (np.abs(reference.target) + np.abs(predicted.predict))))
Кул - осталось только сделать для тюнера метрику

2022-03-15 15:03 UTC, ChrisLisbon approved these changes

2022-03-16 10:14 UTC, maypink commented on fedot/core/composer/metrics.py
> +                              (np.abs(reference.target) + np.abs(predicted.predict))))
[done](https://github.com/nccr-itmo/FEDOT/pull/596/commits/bdbefca6031a8a4f51819a48a89169a5d98b6722)

2022-03-17 12:43 UTC, maypink commented on fedot/api/api_utils/metrics.py
> +    """ Symmetric mean absolute percentage error """
[done](https://github.com/nccr-itmo/FEDOT/pull/596/commits/4de3c369ab9cb8014e5c63e438a5d3582b2cc25d)

2022-03-17 13:18 UTC, Dreamlone commented on fedot/api/api_utils/metrics.py
> +    """ Symmetric mean absolute percentage error """
Всё ок, только не забудь ребейз сделать

2022-03-17 15:05 UTC, merged