Refactor pipeline generation as builder #509
nccr-itmo/FEDOT pull request #597
Opened 2022-03-15 16:01 UTC by gkirgizov

Refactor Assumptions Pipeline building process

Primary changes:
- Extract TaskAssumptions as a kind of data-class containing actual readable assumptions.
- Extract PreprocessingBuilder which is almost independent of the task. Handles gaps and categorical data.
- PrimaryAssumptionsBuilder handles case of InputData, logger and available operations.
- MultiModalData assumptions case is reduced to InputData case. Can now be easily customized if needed. Handled by MultiModalAssumptionsBuilder. In principle, can be also extended to handle available operations mechanics.
- Actual pipeline building is handled by PipelineBuilder underneath. It's independent, all other logic is built on top. So it can be used elsewhere for somewhat shorter construction of pipelines.

2022-03-15 16:01 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/api_utils/assumptions_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/assumptions_builder.py):

> [Line 165:1](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/assumptions_builder.py#L165): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 176:46](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/assumptions_builder.py#L176): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 265:121](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/assumptions_builder.py#L265): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)
> [Line 304:24](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/assumptions_builder.py#L304): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent



* In the file [`fedot/api/api_utils/legacy_assumptions.py`](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/legacy_assumptions.py):

> [Line 201:1](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/api/api_utils/legacy_assumptions.py#L201): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file



* In the file [`fedot/core/data/data_preprocessing.py`](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/core/data/data_preprocessing.py):

> [Line 143:47](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/fedot/core/data/data_preprocessing.py#L143): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

* In the file [`test/unit/api/test_assumption_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py):

> [Line 35:24](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L35): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 35:26](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L35): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 40:25](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L40): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'
> [Line 40:27](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L40): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 44:1](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L44): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)
> [Line 68:121](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L68): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (127 > 120 characters)
> [Line 69:121](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L69): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (133 > 120 characters)
> [Line 70:121](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L70): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (166 > 120 characters)
> [Line 111:77](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L111): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 176:1](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_assumption_builder.py#L176): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`test/unit/api/test_pipeline_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py):

> [Line 23:60](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L23): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 24:54](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L24): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 33:63](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L33): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 34:62](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L34): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 37:27](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L37): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 37:92](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L37): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 37:94](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L37): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 38:27](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L38): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 38:121](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L38): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (147 > 120 characters)
> [Line 38:132](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L38): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 38:134](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L38): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 41:27](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L41): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after '('
> [Line 41:86](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L41): [E202](https://duckduckgo.com/?q=pep8%20E202) whitespace before ')'
> [Line 41:88](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L41): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment
> [Line 42:27](https://github.com/nccr-itmo/FEDOT/blob/a4c60a8e32102f4caae3398dca963f565798c32f/test/unit/api/test_pipeline_builder.py#L42): [E201](https://duckduckgo.com/?q=pep8%20E201) whitespace after  [...]

2022-03-15 16:22 UTC, nicl-nno requested changes

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
А нужны ли тут именно именованные методы. Можно проще хранить в словаре?
Текущий вариант выглядит сложноватым для расширения.

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/pipeline_builder.py
> +NodeT = Union[PrimaryNode, SecondaryNode]
А почему не указать просто их базовый класс None?

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/pipeline_builder.py
> +    def node(self, operation_type: Optional[OpT], branch_idx: int = 0):
Может выдерживать глагольную терминологию везде? add_node, add_branch и т.п.
А то возникает некоторая путаница при чтении.

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +            raise NotImplementedError(f"Don't have assumptions for task type: {task.task_type}")
Мне кажется лучше словарем это заменить.

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +            self._builder.node('scaling')
Не очень понятно как функционалньость связана с названием метода

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/initial_assumptions.py
> +            .from_operations(available_operations or [])\
Может просто научить его принимать None?

2022-03-15 16:22 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +class PrimaryAssumptionsBuilder(AssumptionsBuilder):
Не очень понятно, почему он Primary. Кмк можно назвать unimodal или как-то так.

2022-03-15 16:22 UTC, nicl-nno commented on test/unit/api/test_pipeline_builder.py
> +    n2b = SecondaryNode('ridge', nodes_from=[n1b])
Какие-то названия не очень понятные. Если так и задумано - то стоит их в докстринге пояснить (схематично нарисовав ожидаемый результат, например).

2022-03-15 16:22 UTC, nicl-nno commented on test/unit/api/test_pipeline_builder.py
> +    assert PipelineBuilder().join(None).to_pipeline() is None # empty join is empty
Может это вынести в отдельную функцию-тест?

2022-03-16 06:58 UTC, Dreamlone requested changes
Я бы предложил все .py файлы отвечающие за построение начальных приближений вынести в отдельный модуль в api, - что-то вроде такого
![image](https://user-images.githubusercontent.com/52418437/158534020-8f6701cf-5af9-41ff-87ed-8643957023f8.png)

2022-03-16 06:58 UTC, Dreamlone commented on fedot/api/api_utils/initial_assumptions.py
> +            .build()
Думаю, что можно обойтись без класса - все равно никаких преимуществ от его использования тут нет

2022-03-16 06:58 UTC, Dreamlone commented on fedot/api/api_utils/assumptions_builder.py
> +        if data_has_missing_values(data):
Предлагаю не называть переменные одной буквой

2022-03-16 06:58 UTC, Dreamlone commented on fedot/api/api_utils/pipeline_builder.py
> +NodeT = Union[PrimaryNode, SecondaryNode]
Думаю, Коля выше имел в виду класс Node) Но вообще согласен, имеет смысл Node указывать

2022-03-16 06:58 UTC, Dreamlone commented on fedot/api/api_utils/pipeline_builder.py
> +        self._heads: List[NodeT] = list(filter(None, initial_nodes))
А есть какой-то смысл в том, что поле задаётся через нижнее подчеркивание "_"?

2022-03-16 06:58 UTC, Dreamlone commented on fedot/api/api_utils/pipeline_builder.py
> +        if not ops:
Я за то, чтобы полностью писать "operation" вместо сокращений. Тот же комментарий и для циклов

2022-03-16 06:58 UTC, Dreamlone commented on fedot/core/data/data_preprocessing.py
>          features_types = data.supplementary_data.column_types.get('features')
А если InpuData и при этом не определены ещё типы, то 1) подскажи плиз в каких случаях такое происходит и 2) как это влияет на дальнейшую обработку? Просто насколько мне известно, у нас в любом случае когда-нибудь точно придётся типы определять для табличных данных - иначе обучение пайплайна запуститься не сможет. Мб имеет смысл, если поле None, то прямо здесь и производить оценку типов столбцов

2022-03-16 06:58 UTC, Dreamlone commented on test/unit/api/test_assumption_builder.py
> +    def is_the_op(node: Node):
Лучше в нотации писать, что ~~op~~ operation_name: str

2022-03-16 06:58 UTC, Dreamlone commented on test/unit/api/test_assumption_builder.py
> +    results = map(cond := partial(pipeline_contains_one, pipeline), op)
Место есть, чтобы не сокращать)

2022-03-16 06:58 UTC, Dreamlone commented on test/unit/api/test_assumption_builder.py
> +    return OperationTypesRepository(repo).suitable_operation(task_type=task_type, data_type=data_type)[0]
Мб тут можно переиспользовать `operations_for_task` из fedot/api/help.py, или `get_operations_for_task` из fedot/core/repository/operation_types_repository.py

2022-03-16 11:24 UTC, gkirgizov commented on fedot/api/api_utils/pipeline_builder.py
> +OpT = Union[str, 'Operation']
Сейчас нет, но для дальнейшего использования я посчитал это более разумным, тем более когда для операции есть собственный тип. Заменить строку на Operation, если это затем понадобится, окажется не очень удобно.

2022-03-16 11:26 UTC, nicl-nno commented on fedot/api/api_utils/pipeline_builder.py
> +OpT = Union[str, 'Operation']
Ну вот вроде на уровне бидера не видно особых причин чтобы передавать не строку, а объект с обученной моделью.

2022-03-16 11:48 UTC, gkirgizov commented on test/unit/api/test_assumption_builder.py
> +    results = map(cond := partial(pipeline_contains_one, pipeline), op)
that's echoes of haskell speaking in me...  ¯\_(ツ)_/¯
fixed

2022-03-16 12:00 UTC, gkirgizov commented on test/unit/api/test_assumption_builder.py
> +    return OperationTypesRepository(repo).suitable_operation(task_type=task_type, data_type=data_type)[0]
В этих методах не указывается data_type параметр, что, вероятно, повлияет на результат. Да и все-таки это прямое использование публичного api репозитория, не вижу чего-то криминального в этом. Но, конечно, могу чего-то не знать.

2022-03-16 12:08 UTC, Dreamlone commented on test/unit/api/test_assumption_builder.py
> +    return OperationTypesRepository(repo).suitable_operation(task_type=task_type, data_type=data_type)[0]
Ок, убедил
Ещё тут опишусь: пожалуйста, не помечай треды как решенные, мне так тяжело сообразить что в итоге было изменено и когда (могу запутаться) - я сам их помечу как resolved, когда буду просматривать код второй раз или когда буду лазить по коммитам, оставленным в комментариях
![image](https://user-images.githubusercontent.com/52418437/158586461-aeb43086-b734-477f-ab59-ced243ad0f8c.png)

2022-03-16 12:14 UTC, gkirgizov commented on fedot/core/data/data_preprocessing.py
>          features_types = data.supplementary_data.column_types.get('features')
1) Кажется, падало в тестах на искуственных тестовых данных. Попробовал, не воспроизводится. Значит, я это поправил в тестах, а про данный "фикс", видимо, забыл.
2) Не влияет.
Откачу.

2022-03-16 12:41 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
Pipeline строится только на основе имеющейся node_preprocessed. Так что заранее их построить нельзя.
Вариант -- строить частичные пайплайны, хранить их и потом все равно в райнтайме к нему добавлять в начало эту ноду. Но тогда нужно менять семантику PipelineBuilder, который растет только вперед, его сейчас нельзя снизу нарастить. Я думал об этом в связи с другим вопросом. Это усложнит код и поддержку, я против такого варианта.

2022-03-16 12:43 UTC, gkirgizov commented on fedot/api/api_utils/pipeline_builder.py
> +OpT = Union[str, 'Operation']
Если возникнет потребность динамически строить эти пайплайны (забирать откуда-то из чего-то вроде AssumptionsRepository, например), то можно вернуться к этому вопросу. А пока это статические, заранее известные структуры, то разницы между словарем и именованными методами нет.

2022-03-16 12:44 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
Если возникнет потребность динамически строить эти пайплайны (забирать откуда-то из чего-то вроде AssumptionsRepository, например), то можно вернуться к этому вопросу. А пока это статические, заранее известные структуры, то разницы между словарем и именованными методами особо нет.

2022-03-16 12:48 UTC, gkirgizov commented on test/unit/api/test_assumption_builder.py
> +    return OperationTypesRepository(repo).suitable_operation(task_type=task_type, data_type=data_type)[0]
А, ок, без проблем. Отмечал, чтобы самому не запутаться, что поправил, а что нет.

2022-03-16 12:51 UTC, gkirgizov commented on fedot/api/api_utils/pipeline_builder.py
> +OpT = Union[str, 'Operation']
Окей, тогда имеет смысл убрать. Не смотрел на Operation, увидел ее использования и абстрагировал на всякий случай.

2022-03-16 13:18 UTC, nicl-nno commented
>Второй по логике не относится к assumptions, а как раз скорее api_utils

Может PIpelineBuilder его отправить вообще в Pipelines? Он же не только в API может быть применен

2022-03-16 13:18 UTC, gkirgizov commented
> > Второй по логике не относится к assumptions, а как раз скорее api_utils
> 
> Может PIpelineBuilder его отправить вообще в Pipelines? Он же не только в API может быть применен

Вот да, мне тоже кажется, что ему где-то еще место. Перенесу в Pipelines.

2022-03-16 13:31 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
Я все-таки за отказ от таких методов - они очень уж загромождают класс.

Как вариант приходит в голову увеличить степень абстрагированности методов.

Т.е. вместо - create_glm_ridge_pipeline - create_one_branch_pipeline, примающий на вход не 1, а 3 названия моделей.

Алсо, может вместо явной передачи node_preprocessed реализовать передачу PreprocessingBuilder-а в конструктор? Кажется так меньше деталей реализации будет торчать наружу

2022-03-16 13:37 UTC, nicl-nno commented on fedot/api/api_utils/assumptions_builder.py
> +        self.task_assumptions = TaskAssumptions.for_task(task)
Вот тут создаете впечатления, что в поле будет перечень пайплайнов-приближений - но по факту там их класс-генератор. Тоже выглядит немного неочевидно.

2022-03-16 14:49 UTC, Dreamlone commented
> Насчет этого -- сейчас остался только assumptions_builder.py & pipeline_builder.py. (Я дропнул легаси и initial_assumptions.) Второй по логике не относится к assumptions, а как раз скорее api_utils. Выносить же один файл, наверное, нет смысла. Согласны?

В данном случае с вашими с Колей комментариями согласен. Просто на будущее - я бы хотел взять курс на растаскивание api_utils на отдельные субмодули в рамках большого и структурированного API в ближайшее время (понятно, что не к этому PR). Потому что API заметно усложнился с того момента, как появился "api_utils". Можно будет его потом как-то более прозрачно структурировать, чем надежный подход "всё в кучу"

2022-03-16 15:21 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
>          else:
Я так понимаю, проверка ниже уже не нужна, ведь build всегда возвращает список из пайплайнов?

2022-03-16 15:40 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +        task2assumptions = {
это ж сокращение в смысле task_to_assumptions
но ок, переименую

2022-03-16 15:47 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
>          else:
Проверка которая под else? `if not isinstance(initial_assumption, list):`

Так там проверка не по initial_pipelines (который да, всегда список), а вообще по параметру метода initial_assumptions, который либо None либо Pipeline либо list[Pipeline]

2022-03-16 15:54 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                .build()
ok

2022-03-16 15:54 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +    def ensemble_op(self) -> str:
ok

2022-03-17 09:59 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
Подумал еще раз обо всем этом. Решил реализовать merge для билдеров, чтобы можно было билдеры с частичными пайплайнами хранить.

Вот TaskAssumptions их и будет хранить, а node_preprocessed не надо будет передавать вообще. Вместо этого AssumptionsBuilder будет сам мержить кого нужно вместо перекидывания зависимостей в качестве аргументов.

2022-03-17 13:32 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +    def create_lagged_ridge_pipeline(node_preprocessed: Optional[NodeT]):
done in [9c9995f](https://github.com/nccr-itmo/FEDOT/pull/597/commits/9c9995fb6df4ed9a421a22ec0665097229ebe9b3)

2022-03-17 13:44 UTC, nicl-nno approved these changes

2022-03-17 17:04 UTC, Dreamlone requested changes

2022-03-17 17:09 UTC, Dreamlone commented on fedot/api/api_utils/assumptions_builder.py
> +        task2assumptions = {
Давай я ещё поиграю в душного деда - вместо `task_to_assumptions` лучше подошло бы `assumption_by_task`, потому что ниже ты получаешь подходящего строителя именно по имеющейся задачи

2022-03-17 17:10 UTC, Dreamlone commented on test/unit/api/test_assumption_builder.py
> +    def is_the_op(node: Node):
Это же относится и к другим сокращениям) Расширь их тоже плиз

2022-03-18 07:23 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +        for data_type, (data_source_name, values) in zip(data.data_type, data.items()):
`_subbuilders` это не часть публичного api класса, а его внутреннее состояние. хотя бы by convention лишнее состояние наружу показывать не надо.

Насчет размещения -- согласен, растащу.

2022-03-18 07:27 UTC, Dreamlone commented on fedot/api/api_utils/assumptions_builder.py
> +        for data_type, (data_source_name, values) in zip(data.data_type, data.items()):
> `_subbuilders` это не часть публичного api класса, а его внутреннее состояние. хотя бы by convention лишнее состояние наружу показывать не надо.

Оке, принял

2022-03-18 07:28 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    return lhs.descriptive_id == rhs.descriptive_id
left-hand-side & right-hand-side, т.е. то что слева и то что справа. Довольно стандартные сокращения, в плюсах по крайней мере.

2022-03-18 07:30 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
Что-то вроде id, чтобы просто различать ноды. То есть почти ничего не значат, потому и просто буквы. Здесь нет содержательной логики их различения, и другие имена сделают код менее читаемым.

2022-03-18 07:44 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    return lhs.descriptive_id == rhs.descriptive_id
Ну я на плюсах писал очень мало и только для лабораторных, поэтому и не понял. В любом случае мой тезис по неймингу такой: лучше писать полностью и названия переменных, и названия методов в тех местах где это возможно - вот тут вроде место есть и код станет более читаемым. Не все, кто пишет на Python, имеют опыт разработки на C++

2022-03-18 07:45 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    )
ok

2022-03-18 07:46 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    return lhs.descriptive_id == rhs.descriptive_id
reasonable

2022-03-18 07:46 UTC, gkirgizov commented on test/unit/api/test_assumption_builder.py
> +        task, train_input, data_type=None, logger=default_log('FEDOT logger', verbose_level=4)):
ok

2022-03-18 07:46 UTC, gkirgizov commented on test/unit/api/test_assumption_builder.py
> +    assert True
ok

2022-03-18 07:46 UTC, gkirgizov commented on fedot/api/api_utils/assumptions_builder.py
> +        #     subbuilder.from_operations(available_ops)
ok

2022-03-18 07:55 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
Лучше использовать названия операций, размещенных в узлах, как индексы. Можно сделать как вот [тут](https://github.com/nccr-itmo/FEDOT/blob/master/examples/simple/regression/regression_pipelines.py). 

И ещё комментарий по пайплайну. Лучше взять какой-нибудь другой, потому что именно вот этот невалидный по своей структуре. Операция glm - это обобщенная линейная модель, которая работает только с временными рядами. Работает так, что принимает на вход ts, а выплевывает из себя table тип данных. Поэтому связка glm -> glm приведёт к ошибке, так как вторая для обучения получит не так любимый ей одномерный временной ряд, а таблицу. 

В целом можешь посмотреть в [model_repository.json](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/repository/data/model_repository.json), там стоит обратить внимание на тег "non_lagged". Он означает, что модель может применяться на временном ряду для задачи прогнозирования временного ряда без lagged преобразования. (если не в курсе что такое lagged преобразование, то можешь посмотреть анимации в [этом примере](https://github.com/ITMO-NSS-team/fedot-examples/blob/main/notebooks/latest/3_intro_ts_forecasting.ipynb)). Обычные регрессионные модели без lagged для прогнозирования рядов использоваться не могут. Исходя из этой логики стоит чекнуть one more time составление пайплайнов для прогнозирования временных рядов - я сам тоже пробегусь более подробно по этому моменту в текущем PR

2022-03-18 09:55 UTC, Dreamlone requested changes

2022-03-18 09:55 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = AssumptionsBuilder.get(task, data).build()
Проверь пожалуйста как новая система построения пайплайнов реагирует на available_operations, переданные в composer_params. Как вариант, можешь использовать `examples/simple/time_series_forecasting/api_foresacting.py` для отладки. 

Мой кейс такой:
```
composer_params = {'available_operations': ['ridge', 'lasso']}
model = Fedot(problem='ts_forecasting',
              task_params=task.task_params,
              timeout=timeout,
              preset='fast_train',
              n_jobs=-1,
              composer_params=composer_params)
```
Такое ощущение, что билдер игнорирует то, что в available_operations и генерирует приближения по умолчанию
![image](https://user-images.githubusercontent.com/52418437/158980262-f6ac4a7d-247f-4e5d-8fdd-a73f73bb548a.png)

2022-03-18 09:55 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/preprocessing_builder.py
> +        self._builder = PipelineBuilder(*initial_nodes)
Предлагаю конструктор класса вынести повыше метода `builder_for_data`

2022-03-18 09:55 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    assert pipelines_same(Pipeline([primary_a, primary_b]), PipelineBuilder().add_branch('glm', 'lagged').to_pipeline())
Для теста это не принципиально, но все таки замечу, что соединение glm и lagged сделает пайплайн невалидным. Можешь пробросить связь между AR и ridge - либо отказаться от демонстрации работы билдера на пайплайнах для временных рядов

2022-03-18 09:55 UTC, Dreamlone commented on test/unit/models/test_custom_model_introduction.py
>                     preset='ts',
Ага, вот про этот момент я и говорил в комментарии выше) Пусть пользователю можно будет все таки подавать одиночный пайплайн без оберток в список

2022-03-18 13:12 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                                initial_assumption: List[Pipeline] = None,
ok

2022-03-18 13:15 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/preprocessing_builder.py
> +        self._builder = PipelineBuilder(*initial_nodes)
ok

2022-03-18 13:19 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    assert pipelines_same(Pipeline([primary_a, primary_b]), PipelineBuilder().add_branch('glm', 'lagged').to_pipeline())
ок, приму к сведению

2022-03-18 13:19 UTC, gkirgizov commented on test/unit/models/test_custom_model_introduction.py
>                     preset='ts',
ok

2022-03-18 13:27 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
Насчет имен: в том и дело, что важны не операции, а просто их порядок. Имена это подчеркивают. Первая нода А, вторая нода А после А и тд.

Переименовать то не сложно, но я не вижу причины в данном случае. Если бы это были тесты именно на валидность данных операций -- тогда точно нужны полные имена.

2022-03-18 13:27 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
На валидные операции посмотрю, спасибо за коммент.

Я бы тогда вообще отказался от конкретных операций и тестировал лишь функциональность билдера, чтобы не вкладывать лишние смыслы. Например, `PipelineBuilder().add_node('operation1').add_node('operation_b')`

Что думаешь?

2022-03-18 13:33 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
> Я бы тогда вообще отказался от конкретных операций и тестировал лишь функциональность билдера, чтобы не вкладывать лишние смыслы. Например, PipelineBuilder().add_node('operation1').add_node('operation_b')

Согласен, звучит логично. Я правда не уверен, что FEDOT такие операции сможет переварить. Ну если что всегда можно перебирать просто все регресионные модели - в них порядок не так важен. Пула должно хватить для должного разнообразия: 'rfr', 'dtreg', 'ridge', 'lasso', 'svr', 'linear'

2022-03-18 13:41 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    secondary_ab = SecondaryNode('glm', nodes_from=[primary_a])
> Насчет имен: в том и дело, что важны не операции, а просто их порядок. Имена это подчеркивают. Первая нода А, вторая нода А после А и тд.

Понимаю твои аргументы. Но всегда намного проще всегда читать не-абстрактные буквенные названия переменных. Это в конце концов может помочь для быстроты дебагинга когда придётся с головой лезть в код. 
Давай приведу пример: 
Представим, что падает первая строка из этих трёх
```
assert pipelines_same(Pipeline(secondary_aa), PipelineBuilder(primary_a).add_node('ridge').to_pipeline())
assert pipelines_same(Pipeline(secondary_aa), PipelineBuilder().add_node('glm').add_node('ridge').to_pipeline())
assert pipelines_same(Pipeline(secondary_aa), PipelineBuilder().add_sequence('glm', 'ridge').to_pipeline())
```
я быстрее соображу, если в названии переменной будет сказано, что за операция в ней содержится. Не абстрактное `secondary_aa`, а `secondary_glm_ridge` (кстати странно, почему первая a - это glm, а вторая a - это ridge). И не нужно искать выше что где задавалось - и так понятно, что что-то не так законнектилось просто

2022-03-18 14:14 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = AssumptionsBuilder.get(task, data).build()
Оказывается, ожидаемое поведение. Пересечение результата вызова `OperationsTypesRepository.suitable_operation()` с данными пользователя `['ridge', 'lasso']` оказывается пустым. (см. скриншот)
![dbg_ass_builder2](https://user-images.githubusercontent.com/10994117/159017935-ea315ebe-0ac4-49b1-b43c-1bb05d1ccaed.png)

В этом случае логгер выводит предупреждение и AssumptionsBuilder выдает результат, игнорируя `available_operations`. Здесь я поддержал поведение, которое было изначально.
![dbg_ass_builder1](https://user-images.githubusercontent.com/10994117/159018208-b553cbc5-e5c5-4246-9d77-8b5b5e4b1cc3.png)

Не скажу, что это кажется лучшим поведением. Но не очень ясно, как себя вести в таком случае. Падать совсем не хочется.
Можно, конечно, игнорировать не user input, а довериться, мол, caller значет что делает, сам дурак если что... и игнорировать нашу внутреннюю проверку на `suitable_operation` от репозитория, выводя предупреждение.
И можно тогда добавить в метод `from_operations(available_operations, strict=True)` флажок `strict`. Если пользователь знает что делает, пусть выключает его.
Что думаешь?

2022-03-18 14:47 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +            initial_pipelines = AssumptionsBuilder.get(task, data).build()
Хмм, спасибо за развернутое исследование. Вообще, мне кажется, тогда стоит и оставить как есть - раз перечень операций не позволяет построить нормальное начальное приближение, то пусть действительно как сейчас - игнорируется. 

Думаю, обойдёмся без флагов - и так API довольно гибкий и лишний раз его перегружать не хочется

2022-03-21 08:28 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_builder.py
> +    assert ppl1
А этот тест что проверяет? - Стоит раскрыть в названии и проверять как-то более надежно, чем то, что ppl1 (давай лучше без цифр в названии переменных и таких жестких сокращений) не None / False

Ещё мб стоит выдержать единый стиль оформления названий операций, например:
не `operation1`, а `operation_a`

2022-03-21 08:28 UTC, Dreamlone commented on fedot/core/pipelines/pipeline_builder.py
> +    merged_builder = PipelineBuilder(root_nodes) if isinstance(root_nodes, Node) else PipelineBuilder(*root_nodes)
А разве может быть ситуация, когда root-узлов несколько (тут root_node**s**)

2022-03-21 08:28 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
Сейчас запустил пример `examples/simple/time_series_forecasting/api_foresacting.py`, в который добавил вот такую последовательность операций в available_operations:
```
composer_params = {'available_operations': ['lagged', 'ridge', 'ar']}
    model = Fedot(problem='ts_forecasting',
                  task_params=task.task_params,
                  timeout=timeout,
                  preset='fast_train',
                  n_jobs=-1,
                  composer_params=composer_params)
```

Стоит модифицировать логику составления начальных приближений - на данный момент появляются невалидные приколюхи вроде такого
![image](https://user-images.githubusercontent.com/52418437/159225793-c617bd3b-004c-45e2-810b-8ca7967f70d4.png)

К слову, их четырех сгенерированных пайплайнов три невалидных и не смогут обучиться - упадут с ошибкой
![image](https://user-images.githubusercontent.com/52418437/159225910-32f88ea8-c28b-4c5e-a317-d775d8a1ab63.png)

2022-03-21 08:28 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> -            initial_pipelines = self.initial_assumptions.get_initial_assumption(data, task)
А может initial_assumption быть когда-нибудь None? 
Вроде если initial_assumption не задан пользователем, то в `_set_initial_assumption` в `fedot/api/api_utils/api_composer.py` используется AssumptionsBuilder, который None эту переменную не оставит

2022-03-21 08:28 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_builder.py
> +    assert ppl1
название намекает, что я забыл удалить эти строки...

2022-03-21 08:31 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_builder.py
> +    merged_builder = PipelineBuilder(root_nodes) if isinstance(root_nodes, Node) else PipelineBuilder(*root_nodes)
Да. Если мы мержим неготовые PipelineBuilder-ы в промежуточном состоянии. На это они и нацелены, чтобы неготовые пайплайны держать, у которых может быть несколько финальных root nodes

2022-03-21 08:37 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
На данный момент я только поддерживал ту логику, которая была.
Логика такая: lagged + случайная нода из available_operations.
```
    def fallback_builder(self, ops_filter: OperationsFilter) -> PipelineBuilder:
        random_choice_node = ops_filter.sample()
        return PipelineBuilder().add_node('lagged').add_node(random_choice_node)
```

Как можно проверять, совместима ли последовательность операций?

2022-03-21 08:40 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
Видимо логика некорректная. 
Лучше так:
lagged + случайная нода из available_operations, у которой нет тега "non_lagged"

2022-03-21 08:44 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
Ещё замечу, что если initial_assumtion не задан и при этом заданы available_operations, из которых не получается собрать исходные четыре пайплайна начальных приближений, то лучше собирать всего один. 

Все равно дальше по коду они будут мутировать, чтобы создать начальную популяцию нужного размера. А там уже более низкоуровневые механизмы не позволят нагенериться невалидным пайплайнам. Лишь бы начальное приближение было корректным

2022-03-21 08:48 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> -            initial_pipelines = self.initial_assumptions.get_initial_assumption(data, task)
Но `_set_initial_assumption` вызывается не всегда. Только если `available_operations` пуст:
```
        if not composer_params['available_operations']:
            ...
        else:
            self._set_initial_assumption(...)
```

В целом, я бы в интерфейсе не зкалкадывался на его существующие использования, даже если оно одно. Интерфейс `get_gp_composer` говорит, что initial_assumption -- опциональный. Это логично. Иначе создается впечатление, что пользовательский initial_assumption обязателен для работы.

2022-03-21 08:56 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> -            initial_pipelines = self.initial_assumptions.get_initial_assumption(data, task)
Согласен
Да и в любом случае, наверно лишним не будет

2022-03-21 09:26 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
> Видимо логика была некорректная. Лучше так: lagged + случайная нода из available_operations, у которой нет тега "non_lagged"

Может, просто одну случайную валидную ноду?
Не хочется ради одного подбора тащить зависимость от репозитория в TaskAssumptions. И кажется, что fallback вариант все-таки должен не подбирать что-то, а возвращать что-то самое простое. Что думаешь?

2022-03-21 09:49 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
> Может, просто одну случайную валидную ноду?
Не хочется ради одного подбора тащить зависимость от репозитория в TaskAssumptions.

А как понять без тегов валидная она или нет? - модель "ar" валидна, а вот "ridge" уже нет. Но по поводу fallback полностью согласен, не нужно тогда подбирать пайплайн - выдавай Pipeline MVP так сказать

2022-03-21 10:22 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/task_assumptions.py
> +        'glm_ridge': PipelineBuilder()
По логике, в TaskAssumptions подбирается случаяная нода среди этих в пересечении с пользовательскими `available_operations`:
```
        operations_for_the_task, _ = \
            OperationTypesRepository(repo).suitable_operation(task_type=task_type, data_type=data_type)
        operations_to_choose_from = list(set(operations_for_the_task).intersection(available_operations))
```
Если `repo.suitable_operation` не возвращает невалидных (кажется, не должен?), то все ок.

2022-03-21 16:08 UTC, Dreamlone requested changes
Всё кул, осталось сделать rebase на мастер ветку и можно мержить

2022-03-22 09:48 UTC, Dreamlone approved these changes

2022-03-22 09:49 UTC, Dreamlone commented
А претензии PEP8 можешь поправить ещё плиз?

2022-03-22 11:22 UTC, merged