Auto preset added
nccr-itmo/FEDOT pull request #599
Opened 2022-03-16 16:40 UTC by Dreamlone

A new 'auto' preset has been implemented. It is also now set by default. If the initial assumption takes a long time to fit, a fast_train preset is selected to speed up the calculation. If this is not the case, then best_quality is used. 
The "non-default" tag for lightgbm operation has been removed

2022-03-16 18:16 UTC, valer1435 requested changes

2022-03-16 18:16 UTC, valer1435 commented on examples/simple/regression/api_regression.py
> +                       preset='auto',
Может тоже вынести в перечисление? Получается, что best_quality и fast_train у нас перечисление, а тут строка

2022-03-16 18:16 UTC, valer1435 commented on fedot/api/api_utils/presets.py
> +    composer_requirements.primary = new_operations['available_operations']
Тут может быть беда, когда для primary и secondary будут разные available operations, так как они ссылаются на один и тот же список

2022-03-16 18:16 UTC, valer1435 commented on examples/simple/regression/api_regression.py
> +                       preset='auto',
PS увидел, что оно есть в перечислении.

2022-03-16 21:01 UTC, nicl-nno commented on fedot/api/api_utils/presets.py
> +    if one_fit_percent > 0.5:
0.5 точно стоит вынести в константы. 

Какое значение задать - спорный вопрос, мб стоит хотя бы до 1 поднять.

2022-03-16 21:03 UTC, nicl-nno commented on test/unit/api/test_presets.py
> +    # API must return initial assumption without starting composing and tuning
>API must return initial assumption without starting composing and tuning

А это как-то проверяентся в тесте?

2022-03-16 21:04 UTC, nicl-nno commented on test/unit/optimizer/test_external.py
> +                   preset=FAST_TRAIN_PRESET_NAME,
Думаю в тестах лучше использовать конкретные названия.

2022-03-17 08:05 UTC, Dreamlone commented on test/unit/optimizer/test_external.py
> +                   preset=FAST_TRAIN_PRESET_NAME,
А можно вопрос: почему? Ну то есть я когда недавно менял названия пресетов, мне пришлось в несколько итераций исправлять в тестах названия пресетов на новые. Естественно, можно и автозаменой пройтись (оставим за скобками, что полностью автоматическая замена может и лишнего попереименовывать), но не проще ли держать названия в константах и подставлять их в тесты. Если решим опять поменять название, просто заменим константу и всё работает как надо. Или я что-то упускаю?

2022-03-17 08:32 UTC, Dreamlone commented on fedot/api/api_utils/presets.py
> +    if one_fit_percent > 0.5:
Ок, сделаю. Но по поводу значения, FIY, я исходил из такой логики: "Если можно обучить 200 пайплайнов, то примерно 80 вычислений уйдёт на оптимизацию гиперпараметров в тюнинге. Остается 120 пайплайнов на композирование. По умолчанию, в популяции 20 пайплайнов. 120 / 20 = 6 поколений. Вроде их довольно мало получается, поэтому можно использовать упрощенный пресет"

2022-03-17 08:46 UTC, pep8speaks commented
Hello @Dreamlone! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



























* In the file [`fedot/api/api_utils/presets.py`](https://github.com/nccr-itmo/FEDOT/blob/eb3405aedae46969a5a1aef6f0c5af8430d67301/fedot/api/api_utils/presets.py):

> [Line 128:1](https://github.com/nccr-itmo/FEDOT/blob/eb3405aedae46969a5a1aef6f0c5af8430d67301/fedot/api/api_utils/presets.py#L128): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace

2022-03-17 08:49 UTC, Dreamlone commented on fedot/api/api_utils/presets.py
> +    composer_requirements.primary = new_operations['available_operations']
[Добавил copy](https://github.com/nccr-itmo/FEDOT/pull/599/commits/eb3405aedae46969a5a1aef6f0c5af8430d67301#diff-bfb55318e87be211b23b7c1dee00a6c42cf34e11bac6302ec29f32def3a4c6bbL109-L110)

2022-03-17 08:50 UTC, Dreamlone commented on fedot/api/api_utils/presets.py
> +    if one_fit_percent > 0.5:
Вынес в константу и немного изменил расчет (см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/599/commits/eb3405aedae46969a5a1aef6f0c5af8430d67301#diff-bfb55318e87be211b23b7c1dee00a6c42cf34e11bac6302ec29f32def3a4c6bbR127-R130))

2022-03-17 08:59 UTC, nicl-nno commented on test/unit/api/test_presets.py
> +    # API must return initial assumption without starting composing and tuning
Может тогда добавить проверку на то, что найденный пайплайн соответсвует ожидаемому, history пустая и т.п.? 
Чтобы понять, что пресет применился корректно.

2022-03-17 09:54 UTC, Dreamlone commented on test/unit/api/test_presets.py
> +    # API must return initial assumption without starting composing and tuning
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/599/commits/0484bfa830a61b57a9c3c63903e740d76c57e4c6#diff-81917fb91136ed0de5bccf36ddc7008979f9ef8c81d5a2f427e6515717d2bd92R73-R74)

2022-03-17 09:54 UTC, Dreamlone commented on test/unit/optimizer/test_external.py
> +                   preset=FAST_TRAIN_PRESET_NAME,
Убрал константы из примеров и тестов (см. [коммит](https://github.com/nccr-itmo/FEDOT/pull/599/commits/0484bfa830a61b57a9c3c63903e740d76c57e4c6))

2022-03-17 09:56 UTC, Dreamlone commented on examples/simple/regression/api_regression.py
> +                       preset='auto',
Поговорили с Колей, решили задавать в примерах и в тестах preset через строки явно. Константы пусть будут больше   для внутреннего пользования

2022-03-18 07:25 UTC, valer1435 approved these changes

2022-03-18 09:25 UTC, nicl-nno approved these changes
Только ворнинги подавить и норм

![image](https://user-images.githubusercontent.com/5711814/158976450-e191915a-dfb3-450a-a357-ca71b6fda19d.png)

2022-03-22 14:45 UTC, Dreamlone commented
Только ворнинги подавить и норм
@nicl-nno, посмотри плиз - вроде всё окей, по крайней мере при запуске на сервере вывод вот такой (запускалось композирование с lgbmreg в начальном приближении и как единственный вариант в available operations)
![image](https://user-images.githubusercontent.com/52418437/159508857-3b131ad0-09bf-4031-9aa4-89e076138657.png)

2022-03-22 14:47 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +            with suppress_stdout():
А может для всех моделей это сделать? Хуже не будет.

2022-03-22 14:48 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +            with suppress_stdout():
RANSAC например тоже иногда флудит:

![image](https://user-images.githubusercontent.com/5711814/159509593-33c6efe6-8968-47ee-beed-5e5dbd48f5c5.png)

2022-03-22 15:00 UTC, Dreamlone commented on fedot/core/operations/operation.py
> +            with suppress_stdout():
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/599/commits/918cae3b0078d6c45659f146084436fe9ba165c7) вот такое ограничение по verbose

2022-03-23 15:22 UTC, nicl-nno commented
ага

2022-03-23 15:31 UTC, merged