repaired automl examples
nccr-itmo/FEDOT pull request #605
Opened 2022-03-21 19:20 UTC by valer1435

Issue https://github.com/nccr-itmo/FEDOT/issues/600 has been resolved in this PR

2022-03-22 09:47 UTC, Dreamlone requested changes

2022-03-22 09:47 UTC, Dreamlone commented on examples/advanced/automl/h2o_example.py
> +    # prediction_after_export = predicted_output_after_export.predict[:, 0]
Стоит убрать комментарии

Заодно pipeline_path = "h2o_class" в 39й строке нигде не используется - мб стоит подчистить

2022-03-22 09:47 UTC, Dreamlone commented on fedot/core/operations/automl.py
> +class AutoML(Model):
А зачем тут это было сделано? Вроде сейчас в get_operation в OperationFactory все три разновидности операций лежат на одном уровне: есть модели, есть методы предобработки, есть AutoML-блоки. А сейчас эта логика нарушается, - возможно, тогда стоит и `get_operation` подправить

2022-03-22 16:31 UTC, valer1435 commented on examples/advanced/automl/h2o_example.py
> +    # prediction_after_export = predicted_output_after_export.predict[:, 0]
Комментарии тут потому, что h2o стал стабильно давать пайплайны, которые он не может сериализовать (помнишь может быть, такую проблему)

2022-03-22 19:15 UTC, Dreamlone commented on examples/advanced/automl/h2o_example.py
> +    # prediction_after_export = predicted_output_after_export.predict[:, 0]
Да, точно
Тогда просто вынеси этот код в отдельную функцию плез с говорящим названием

2022-03-25 09:59 UTC, valer1435 commented on fedot/core/operations/automl.py
> +class AutoML(Model):
Operation не содержит реализации этой функции 
![image](https://user-images.githubusercontent.com/32017472/160098875-3c8ad372-0509-44df-b8a4-38c16280505a.png)

2022-03-25 10:12 UTC, valer1435 commented on examples/advanced/automl/h2o_example.py
> +    # prediction_after_export = predicted_output_after_export.predict[:, 0]
[Перенес](https://github.com/nccr-itmo/FEDOT/pull/605/commits/5f21341a823f3943a99e3b33bcd898dde56b7072#diff-1ba3d6bfdff392fe9f5fe98a45b8b2aa1307130c039d08c4e1eae45304debc3cR38-R51)

2022-03-25 14:04 UTC, Dreamlone commented on fedot/core/operations/automl.py
> +class AutoML(Model):
Её там никогда и не было) Я тут подумал, похоже вариант с наследованием  и правда самый безболезненный
Ок, пусть остается так

2022-03-25 14:05 UTC, Dreamlone approved these changes
Проверь плиз ещё AutoML примеры в интеграционных тестах. Ну и ребейз тоже стоит сделать

2022-03-28 14:44 UTC, merged