Forbid duplicate edges in the Graph
nccr-itmo/FEDOT pull request #606
Opened 2022-03-22 11:28 UTC by gkirgizov

Resolves #604 & #580

I was thinking about 2 ways to resolve this:
1. Maintain the new invariant in the Graph (actually, in GraphOperator) on each operation (add,remove,update etc.)
2. Maintain the new invariant in the GraphNode

I chose the second alternative and substituted  implementation of `nodes_from` from standard `list` to thin subclass `UniqueList` that forbids duplicate elements. Btw: list is used instead of something like ordered set to preserve standard list interface, and for small lists such as `nodes_from` it's no less efficient than a set.

Motivation for the second approach:
 - This *for sure* prevents us from future bugs related to duplicate edges. otherwise on each change to Graph *or its subclasses* we must remember about its invariants. It's difficult to enforce.
- Trying to maintain the new invariant on Graph level requires a lot of scattered changes, that complicates core logic of graph methods. GraphNode is essential part of Graph, so that's natural that it bears responsibility for Graph invariants. Anyway, I see no sense to allow storing duplicate elements in `node.nodes_from`.
- It also somewhat hides implementation details of GraphNode (that we use a list underneath)

2022-03-22 11:28 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fedot/core/dag/graph_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/graph_operator.py):

> [Line 230:26](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/graph_operator.py#L230): [E701](https://duckduckgo.com/?q=pep8%20E701) multiple statements on one line (colon)
> [Line 232:1](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/graph_operator.py#L232): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

* In the file [`fedot/core/dag/unique_list.py`](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/unique_list.py):

> [Line 11:32](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/unique_list.py#L11): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 11:34](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/unique_list.py#L11): [E251](https://duckduckgo.com/?q=pep8%20E251) unexpected spaces around keyword / parameter equals
> [Line 39:1](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/fedot/core/dag/unique_list.py#L39): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file









* In the file [`test/unit/dag/test_unique_list.py`](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py):

> [Line 12:56](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 12:93](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L12): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:50](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 13:87](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L13): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:17](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:19](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:21](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:23](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:25](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:27](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:29](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 33:31](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L33): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:13](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:15](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:17](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:19](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:21](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:23](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:25](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 38:27](https://github.com/nccr-itmo/FEDOT/blob/64a531c78a592f84d9db8599ee4b91d9b5f183fd/test/unit/dag/test_unique_list.py#L38): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2022-03-22 12:54 UTC, nicl-nno requested changes

2022-03-22 12:54 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def remove_all(collection: List, removed_items: List):
Как-то не очень интуитивно названа на мой вкус. 
Я бы вынес вообще из класса и назвал в стиле remove_items.

И, возможно, возвращал бы изменную collection (тоже для большей понятности)

2022-03-22 12:54 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +                    edges.append((parent_node, node))
А почему тут set? Ведь порядок важен, т.к. ребро направленное.

2022-03-22 12:54 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +    res_edges = [(knn, logit), (qda_second, knn), (qda_first, knn), (lda, qda_second)]
Тоже вопрос про направленнность ребер.

2022-03-22 15:52 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +                    edges.append((parent_node, node))
tuple же, поменял в соотвествии с сигнатурой функции

2022-03-22 15:52 UTC, gkirgizov commented on test/unit/dag/test_graph_operator.py
> +    res_edges = [(knn, logit), (qda_second, knn), (qda_first, knn), (lda, qda_second)]
это tuples, все ок

2022-03-22 15:57 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +    res_edges = [(knn, logit), (qda_second, knn), (qda_first, knn), (lda, qda_second)]
Ок, действительно.

2022-03-22 15:58 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +    def remove_all(collection: List, removed_items: List):
Сделал присваивание через `a[:]=...` чтобы сохранить семантику in-place, то есть сохранить object reference на старый лист. Но можно и новый возвращать, вроде, никто внутри и снаружи кода Graph не должен хранить референсы на эти списки (то есть никто не должен закладываться на то, что список нод как объект никогда не подменяется целиком). Это должно быть так? Тогда поменяю, да.

2022-03-22 20:42 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def remove_all(collection: List, removed_items: List):
Не против того чтобы менять in-plcae, просто дополнительный return дает большую читаемость - сразу понятно, что именно внутри функции изменилось.

2022-03-23 08:13 UTC, Dreamlone requested changes

2022-03-23 08:13 UTC, Dreamlone commented on test/unit/dag/test_graph.py
> +    return next(filter(lambda n: n.descriptive_id == target.descriptive_id, nodes), None)
Предлагаю сделать функцию попроще - не фанат использования `next`, `filter`, `lambda` в одной строке. Когда код обрастает такими относительно запутанными конструкциями, повышается порог входа для его разработки и поддержки 
Но вот этот коммент ИМХО

2022-03-23 09:23 UTC, nicl-nno commented on test/unit/dag/test_graph.py
> +    return next(filter(lambda n: n.descriptive_id == target.descriptive_id, nodes), None)
Да вроде выглядит понятно.

2022-03-23 09:27 UTC, Dreamlone commented on test/unit/dag/test_graph.py
> +    return next(filter(lambda n: n.descriptive_id == target.descriptive_id, nodes), None)
Ок

2022-03-23 11:00 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Я это написал как абстрактный метод работы со списком в целом, безотносительно конкретного содержимого, потому так. Смысл метода определяется тем, для какой коллекции его используют. Где-то для нод, где-то для ребер.

2022-03-23 11:03 UTC, gkirgizov commented on fedot/core/dag/unique_list.py
> +
Это как рекомендация, а не жесткое ограничение. Типа, у нас тут линейная сложность. Если бы использовали ordered set, то сложность была бы O(log(n)), тут O(n), при n <= 4 разница никакая, при n <= 10 тоже вряд ли заметная.

Напишу подробнее в доке.

2022-03-23 11:05 UTC, gkirgizov commented on fedot/core/optimisers/graph.py
>          self.content = {**content, **default_dict}
Кортеж чуть полегче весит, чем список. А так без разницы, по чему итерироваться, констурктор любой Iterable принимает.

2022-03-23 11:55 UTC, nicl-nno approved these changes

2022-03-23 11:56 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +        remove_items(self._graph.nodes, subtree_nodes)
Раз добавлен return, то тут и ниже бы я тоже вот так сделал:
self._graph.nodes = remove_items(self._graph.nodes, subtree_nodes)

2022-03-23 11:56 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +def remove_items(collection: List, removed_items: Container):
Мб removed_items -> items_to_revome

2022-03-23 11:56 UTC, nicl-nno approved these changes

2022-03-23 12:32 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
А, ок, тогда вот это "Смысл метода определяется тем, для какой коллекции его используют. Где-то для нод, где-то для ребер." стоит указать в docstring

2022-03-23 12:33 UTC, Dreamlone commented on fedot/core/optimisers/graph.py
>          self.content = {**content, **default_dict}
Ок, пусть будет кортеж

2022-03-23 12:41 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
ага, а еще для потенциально бесконечного количества любых других объектов :) это только confusing. Метод убирает все элементы -- и это все, он принципиально не знает и не хочет знать о его использованиях, даже в докстринге. А вот в месте использования сам код говорящий, смотря что передается в метод.

2022-03-23 12:43 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Это может и кажется мелочью, но я стараюсь очень строго относится к уровням абстракции и разделению ответственности в коде

2022-03-23 12:51 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
>абстрактный метод работы со списком в целом

Тогда может его вынести из graph_operator?

2022-03-23 12:57 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
> Это может и кажется мелочью, но я стараюсь очень строго относится к уровням абстракции и разделению ответственности в коде

Хорошо, что ты упомянул разделение ответственности. Тогда этому методу не место в GraphOperator, ведь как класс работает именно с узлами и ребрами

2022-03-23 13:02 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Да, была мысль во что-то вроде utils его спрятать. Куда лучше это перенести?

2022-03-23 13:29 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Мне кажется вполне можно вынести class UniqueList в файл lists.py или мб fedot_lists.py (можно прямо там же держать, в fedot/core/dag). И к нему же докинуть функцию remove_items

2022-03-23 13:50 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Но он же не только в dag может быть нужен.

Можно создать каталог core/utils и там создать data_structures.py

Как другой кандидат на перенос туда - класс ComparableEnum

2022-03-23 14:04 UTC, gkirgizov commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
> Можно создать каталог core/utils и там создать data_structures.py

Вот на этом и порешим, может?

2022-03-23 14:09 UTC, Dreamlone commented on fedot/core/dag/graph_operator.py
> +        """Remove all elements from the list in one pass."""
Согласен

2022-03-23 14:39 UTC, Dreamlone approved these changes

2022-03-23 14:54 UTC, merged