fix apply encoder method
nccr-itmo/FEDOT pull request #609
Opened 2022-03-22 14:02 UTC by maypink

Earlier in `_apply_encoder` method new labels were recursively added to the `encoder.classes_` if they had not been encountered before. 
Now at the very beginning we go through the current column and add all the labels that have not been seen before

2022-03-22 14:18 UTC, Dreamlone requested changes

2022-03-22 14:36 UTC, maypink commented
> А корректность поведения можно каким-то тестом проверить?

[this](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/preprocessing/test_pipeline_preprocessing.py#L149)

2022-03-22 14:38 UTC, nicl-nno commented on fedot/preprocessing/categorical.py
> +                encoder_classes.append(label)
> > А корректность поведения можно каким-то тестом проверить?
> 
> [this](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/preprocessing/test_pipeline_preprocessing.py#L149)



> > А корректность поведения можно каким-то тестом проверить?
> 
> [this](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/preprocessing/test_pipeline_preprocessing.py#L149)

Но этот тест же и раньше не падал?

2022-03-22 14:38 UTC, nicl-nno commented
> > А корректность поведения можно каким-то тестом проверить?
> 
> [this](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/preprocessing/test_pipeline_preprocessing.py#L149)

Но этот тест же и без фикса не падает.

2022-03-22 14:59 UTC, maypink commented on fedot/preprocessing/categorical.py
> +                encoder_classes.append(label)
[done](https://github.com/nccr-itmo/FEDOT/pull/609/commits/c8384ee5cb4744bdbbb946f01f0e5bd81239aacd#diff-f7952f4ada6d235f933e9102aa3d95c4820508f487c4f74f954e4a4cbcc13053R188)

2022-03-23 10:16 UTC, Dreamlone approved these changes

2022-03-25 15:24 UTC, merged