Extended optimizer history
nccr-itmo/FEDOT pull request #611
Opened 2022-03-22 17:31 UTC by nicl-nno

Initial assamptions and final results are added to the OptHistory.

2022-03-25 14:38 UTC, Dreamlone approved these changes
Кмк всё ок

2022-03-25 16:41 UTC, gkirgizov requested changes

2022-03-25 16:41 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        if selected_individual_second is not None:
двумя строчками ниже повторяется проверка, мб объединить стоит

2022-03-25 16:41 UTC, gkirgizov commented on fedot/core/optimisers/optimizer.py
> +                                           archive: Optional[List[Individual]]):
кажется, везде этот метод используется с None параметром. мб стоит сделать его по дефолту None, чтобы каждый раз не передавать Optional

2022-03-25 20:20 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
> +                                           archive: Optional[List[Individual]]):
Добавил None по умолчанию.

2022-03-25 20:20 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        if selected_individual_second is not None:
Объединил

2022-03-28 11:22 UTC, gkirgizov approved these changes

2022-03-28 13:43 UTC, merged

2022-03-29 11:11 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +                                 len(node_first_childs) == len(node_second_childs))):
Мб уже поздно, да и вообще это скорее grammar, но `child` в множественном числе - `children`