Save additional info about nodes
nccr-itmo/FEDOT pull request #612
Opened 2022-03-25 15:39 UTC by valer1435

Now such information about pipelines and nodes will saved:
1) number of parent nodes
2) number of child nodes
3) distance from primary node
4) distance to root node 
5) number of brothers of node
6) is that pipeline is initial assumption

2022-03-25 21:37 UTC, nicl-nno requested changes

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/dag/node_operator.py
> +        return len(self._node.nodes_from)
Из названия неочевидно,  что возвращается количество предков, а не они сами.

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/dag/node_operator.py
> +            return 1 + max([next_node.calculate_distance_to_root_level(graph) for next_node in child_nodes])
А это не дублирует вот [этот](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/dag/graph_operator.py#L67) метод?

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/optimisers/graph.py
> +        return self._operator.get_children(graph)
"calculate_" в названии выглядит лишним.

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/dag/node_operator.py
> +        return len([n for n in graph.nodes if n.nodes_from and self._node in n.nodes_from])
Аналогично - вроде дублируется [это](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/dag/graph_operator.py#L107)

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.is_initial_assumption = is_initial
Сейчас initial_assumption явно не сохраняется в истории, но после моего PR-е они будут в 0-м поколении. После этого флаг всё ещё будет актуален?

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.distance_to_root_level = node.calculate_distance_to_root_level(obj)
Как-то странно - зачем их сохранять в поля, если можно динамически высчитывать.

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
> +            child_nodes = [n for n in obj.nodes if n.nodes_from and node in n.nodes_from]
Это функцию кажется дублирует.

2022-03-25 21:37 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.num_of_brothers = sum([len(n.nodes_from) for n in child_nodes if n.nodes_from]) - len(child_nodes)
Это вообще вроде нигде не упоминается.

2022-03-26 09:49 UTC, Dreamlone requested changes

2022-03-26 09:49 UTC, Dreamlone commented on fedot/core/serializers/coders/graph_node_serialization.py
>      if encoded['nodes_from']:
Стоит ещё добавить поле с метрикой. Правда всегда высчитывать метрику на каждом узле неоптимально в том случае, если нас не интересует сбор подробной истории композирования, а хочется, чтобы AutoML просто побыстрее выдал результат. Поэтому можно объявлять такие расчеты только если задан флаг через API например  в духе "collect_node_metrics=True". 

Плюс кмк полезно в том числе и для отладки расчетов сохранять информацию 1) о времени обучения всего пайплайна в json и 2) время обучения отдельно взятого узла

2022-03-31 06:48 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.is_initial_assumption = is_initial
Не будет

2022-03-31 06:53 UTC, valer1435 commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.distance_to_root_level = node.calculate_distance_to_root_level(obj)
Все эти ухищрения тут потому, что нам  для получения узлов - потомков требуется ссылка на объект графа. А в сериализации узлов у нас нет этой ссылки. Поэтому приходится на момент сохранения графа сохранять состояния distance_to_root_level и других полей, где нужна ссылка на граф. Если это можно как-то просто исправить - буду рад узнать

2022-03-31 07:34 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.is_initial_assumption = is_initial
Вроде тут Коля имел в виду вот этот [PR](https://github.com/nccr-itmo/FEDOT/pull/611). Он уже в мастере, так что можешь попробовать сделать rebase и обновить подход

2022-03-31 10:25 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.distance_to_root_level = node.calculate_distance_to_root_level(obj)
@IIaKyJIuH мб у тебя будут идеи как упростить.

2022-04-01 13:51 UTC, IIaKyJIuH commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.distance_to_root_level = node.calculate_distance_to_root_level(obj)
Проблему осознал, ничего не придумалось для упрощения в контексте работы внутри сериализаторов.

Я тоже думаю, что эти поля можно высчитывать динамически, когда имеется доступ к соответствующему графу, чтобы это было возможно, а не хранить их в самом `OptNode`.
Если же стоит хранить, то надо хотя бы вписать их в `OptNode`, написав ещё для них методы установки значения по графу. Так при дебаггинге не было бы удивлений, откуда взялись поля, которых в классе как бы и нет.

2022-04-03 14:26 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/dag/graph_node.py`](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/dag/graph_node.py):

> [Line 64:1](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/dag/graph_node.py#L64): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file



* In the file [`fedot/core/optimisers/gp_comp/evaluating.py`](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/optimisers/gp_comp/evaluating.py):

> [Line 113:1](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/optimisers/gp_comp/evaluating.py#L113): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file











* In the file [`fedot/core/pipelines/node.py`](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/pipelines/node.py):

> [Line 445:1](https://github.com/nccr-itmo/FEDOT/blob/1aa04170192a0b4122c029c0c9a69037094894e1/fedot/core/pipelines/node.py#L445): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (4)

2022-04-03 14:27 UTC, valer1435 commented on fedot/core/dag/node_operator.py
> +        return len(self._node.nodes_from)
Существенно изменил подход. Теперь [неактуально](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR236-R243)

2022-04-03 14:28 UTC, valer1435 commented on fedot/core/dag/node_operator.py
> +            return 1 + max([next_node.calculate_distance_to_root_level(graph) for next_node in child_nodes])
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR236-R243)использую оригинальные методы

2022-04-03 14:28 UTC, valer1435 commented on fedot/core/optimisers/graph.py
> +        return self._operator.get_children(graph)
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR236-R243)неактуально

2022-04-03 14:28 UTC, valer1435 commented on fedot/core/dag/node_operator.py
> +        return len([n for n in graph.nodes if n.nodes_from and self._node in n.nodes_from])
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR236-R243)неактуально

2022-04-03 14:29 UTC, valer1435 commented on fedot/core/serializers/coders/graph_serialization.py
> +            child_nodes = [n for n in obj.nodes if n.nodes_from and node in n.nodes_from]
[Удалил ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-84dc3a31b73f8a174d5e4d35997a063a13d67535c56c24f7aa23bd7eb7553f3cR19-R21)ненужное

2022-04-03 14:30 UTC, valer1435 commented on fedot/core/serializers/coders/graph_serialization.py
> +            node.num_of_brothers = sum([len(n.nodes_from) for n in child_nodes if n.nodes_from]) - len(child_nodes)
Теперь [считается ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/1aa04170192a0b4122c029c0c9a69037094894e1#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR241-R243)и сохраняется

2022-04-03 14:32 UTC, valer1435 commented on fedot/core/serializers/coders/graph_node_serialization.py
>      if encoded['nodes_from']:
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/67656b481670bed8baa467a263a2e5c63808a75a#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR201-R209)возможность сохранять метрику на нодах. Думаю, что стоит определиться, что предложенный подход хранить все в dataclass'е нормальный и дальше уже реализовывать computation_time

2022-04-04 09:34 UTC, Dreamlone requested changes
Стоит ещё написать тест на новую функциональность, чтобы он проверял, например, правильно ли генерируется информацию об узлах пайплайна, когда мы вызываем  `calculate_objective`

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/dag/graph_node.py
>          self._nodes_from = None
А чем отличаются поля nodes_from и _nodes_from?

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/optimisers/adapters.py
> +        graph.nodes[i].content['specific_info'] = deepcopy(pipeline.nodes[i].specific_info)
В history.json сериализуется в том числе путь до NodeSpecificInfo, эта информация (см. "_class_path") точно нужна? 
![image](https://user-images.githubusercontent.com/52418437/161514031-7f8d121b-4387-4fda-a0e3-c421fcd87163.png)

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/pipelines/node.py
> +    'ts_forecasting': mean_squared_error
Для регрессии лучше взять какую-нибудь относительную метрику, которую можно экстраполировать в какой-то степени на несколько датасетов, например SMAPE. Или эта проблема решается при нормализации по датасетам при расчете коэффициентов?

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/pipelines/node.py
> +            self.specific_info.metric = metric(input_data.target, operation_predict.predict, **add_params)
Стоит вынести в отдельный метод

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/serializers/coders/graph_node_serialization.py
> +from ...optimisers.graph import OptNode
Какой странный импорт однако

2022-04-04 09:34 UTC, Dreamlone commented on fedot/core/serializers/coders/graph_serialization.py
> +from ...optimisers.graph import OptNode
Это какой-то новый стандарт в PyCharm так пути генерировать?

2022-04-04 09:47 UTC, Dreamlone commented on fedot/core/serializers/coders/graph_node_serialization.py
>      if encoded['nodes_from']:
Вообще моя идея была изначально несколько другой. Не плодить новые "побочные" сущности для побочных же задач, а сводить всё к единым расширяемым абстракциям. Например, вот появилась у нас потребность собирать дополнительную информацию во время оценки фитнес функции, - создаем не новый класс для этих новых генерируемых данных NodeSpecificInfo, а делаем общий dataclass ObjectiveOutput, который снабжаем необходимыми полями. Теперь всегда какие бы параметры мы не задали бы в calculate_objective, она всегда вернет один и тот же объект - экземпляр класса ObjectiveOutput. Разница лишь будет в том, какие поля мы наполняем в этом объекте значениями. По умолчанию например, всегда заполняется поле fitness, а все остальные - None.

Идём дальше, для обработки объектов класса ObjectiveOutput у нас есть специальная функция парсер, которая принимает на вход objective_output переменную и индивид, и сама в нужные места перераспределяет информацию. fitness идет в соответствующее поле индивида, метрики узлов идут в поля узлов. При таком подходе всю логику по назначению информации полям мы разносим относительно пайплайна или узлов. Значит мы можем написать новый модуль назначения информации например уже не для пайплайнов, а для графов из дифф. уравнений не внося никаких изменений пайплайны или узлы. Графы всегда будут "знать", что при необходимости некоторые атрибуты во время расчета фитнеса можно сгрузить в ObjectiveOutput и потом они окажутся на своих местах. То есть я примерно так себе это представлял - не исключаю, что такой подход не самый гибкий и имеет свои недостатки, поэтому открыт к аргументированной критике, да и в целом обсуждаемо.

2022-04-04 11:03 UTC, nicl-nno commented
Вопрос: а specific_info не то же самое, что metadata из вот этого PR-а @MorrisNein 
https://github.com/nccr-itmo/FEDOT/pull/614
?

2022-04-04 11:10 UTC, Dreamlone commented
> Вопрос: а specific_info не то же самое, что metadata из вот этого PR-а @MorrisNein
> #614
> ?

Ага. выглядит и правда похоже, можно ориентироваться на изменения Петра

2022-04-04 11:18 UTC, valer1435 commented
> Вопрос: а specific_info не то же самое, что metadata из вот этого PR-а @MorrisNein #614 ?

<Близко, но не совсем. У меня информация хранится в нодах и связано исключительно с нодой. А в PR, видимо предлагается хранить информацию на уровне индивида. В теории можно хранить информацию о нодах в метадате, но, кажется логичным хранить информацию о нодах в нодах.

2022-04-04 11:21 UTC, valer1435 commented on fedot/core/optimisers/adapters.py
> +        graph.nodes[i].content['specific_info'] = deepcopy(pipeline.nodes[i].specific_info)
Сериализатор работает так, что сериализует объект целиком. Можно, конечно, отдельно распарсить этот объект на поля, но это занимает код + лишняя логика

2022-04-04 11:21 UTC, valer1435 commented on fedot/core/dag/graph_node.py
>          self._nodes_from = None
Вообще вопрос хороший. _nodes_from появилось после ребейза

2022-04-04 12:39 UTC, nicl-nno commented
> > Вопрос: а specific_info не то же самое, что metadata из вот этого PR-а @MorrisNein #614 ?
> 
> <Близко, но не совсем. У меня информация хранится в нодах и связано исключительно с нодой. А в PR, видимо предлагается хранить информацию на уровне индивида. В теории можно хранить информацию о нодах в метадате, но, кажется логичным хранить информацию о нодах в нодах.

Ок, пусть тогда будет так есть, с двумя отдельными сущностями.

2022-04-04 12:46 UTC, Dreamlone commented on fedot/core/optimisers/adapters.py
> +        graph.nodes[i].content['specific_info'] = deepcopy(pipeline.nodes[i].specific_info)
Не, согласен - пусть лучше остается как есть

2022-04-04 12:47 UTC, valer1435 commented on fedot/core/serializers/coders/graph_node_serialization.py
>      if encoded['nodes_from']:
Вижу следующие недостатки
1)Придется objective_output прокидывать во все методы fit-predict и так далее вниз вплоть до нод. Например сейчас приходится так прокидывать флаг collect_node_metric. 
2) У нас датакласс по умолчанию неизменяемый + кол-во полей строго заданы изначально, а кол-во нод в графе, например, может быть произвольным. Если задавать это через список, придется плодить еще массу вложенных сущностей

Не знаю, насколько хороша эта идея

2022-04-04 12:57 UTC, Dreamlone commented on fedot/core/serializers/coders/graph_node_serialization.py
>      if encoded['nodes_from']:
> 1)Придется objective_output прокидывать во все методы fit-predict и так далее вниз вплоть до нод. Например сейчас приходится так прокидывать флаг collect_node_metric.

В этом нет необходимости. objective_output формирует только обвязка над пайплайном, та, что запускается в calculate_objective. 

> 2) У нас датакласс по умолчанию неизменяемый + кол-во полей строго заданы изначально, а кол-во нод в графе, например, может быть произвольным. Если задавать это через список, придется плодить еще массу вложенных сущностей

Датакласс - вроде же изменяемый объект. Количество полей при этом очевидно более расширяемая часть, чем количество возвращаемых объектов. По поводу узлов - в самом датаклассе при необходимости calculate_objective может возвращать и сам граф с записанной атрибутивной информацией в узлах.

2022-04-04 13:04 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +    def save_specific_info_about_location(self, graph):
Вместо save лучше compute или что-то такое.

2022-04-04 13:04 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +    computation_time: int = None
Может разделить на fit_time/inference_time?

2022-04-04 13:05 UTC, nicl-nno commented on fedot/core/serializers/coders/graph_node_serialization.py
> +        encoded['content']['num_of_parents'] = obj.num_of_parents
А это точно надо сериализовывать? Не проще после импорта json-а заново вычислить?

2022-04-04 13:15 UTC, nicl-nno commented on fedot/core/pipelines/node.py
> +    'ts_forecasting': mean_squared_error
Если что-то такое и оставлять - то лучше не в node.py
Кажется такого рода словари уже много раз в коде реализованы - можно попробовать объединить.

2022-04-07 07:39 UTC, valer1435 commented
Пересоздал ветку с нуля. Убрал всю информацию, связанную со структурой графа

2022-04-07 12:35 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +
Нужно будет потом не забыть вернуть обратно закомментированные строки кода

2022-04-07 12:48 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +        cnt = 0
Лучше писать целиком

2022-04-08 07:32 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    input_data = args[0]
Эти аргументы прокидываются через partial + для разных задач подается разное число аргументов и не хочется засорять ими calculate_objective

2022-04-08 07:37 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +        cnt = 0
Уже [неактуально](https://github.com/nccr-itmo/FEDOT/pull/612/commits/9ae37bb030244ecd21987ca6740b3ac05810e2a8#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R121-R123)

2022-04-08 09:11 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    input_data = args[0]
[Заменил ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/c81e827c4dc42e59841a14398489589184975beb#diff-f8695bee5d4c0f3e8ec2d95c40ffbf1bd469568f8d51e9f69453b1124a3df5f2R167-R181)таким обазом

2022-04-08 09:11 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    num_of_folds = args[1]
[Перенес](https://github.com/nccr-itmo/FEDOT/pull/612/commits/c81e827c4dc42e59841a14398489589184975beb#diff-d79b57402c649a963d787b321d87a1f50b279e48bd35b3946af23af9fe80f54dR7-R19)

2022-04-08 09:13 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    if isinstance(converted_object, Pipeline):
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/612/commits/5bfc8840837a991c040f3bdfb2a9a20891e808dc#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R59-R61)

2022-04-08 09:13 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +        individual_context.ind.graph = graph
[Прокидываю ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/5bfc8840837a991c040f3bdfb2a9a20891e808dc#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R24-R25)теперь только контекст

2022-04-08 09:14 UTC, valer1435 commented on examples/simple/time_series_forecasting/api_foresacting.py
> +    model.plot_prediction()z
[Вернул](https://github.com/nccr-itmo/FEDOT/pull/612/commits/5bfc8840837a991c040f3bdfb2a9a20891e808dc#diff-0728671d7b586e7827df689575a65071a9fc14b4df62f14cafe8b6fb10520af8R54)

2022-04-08 09:14 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +
[Вернул](https://github.com/nccr-itmo/FEDOT/pull/612/commits/4465ccf46d5cc29d1b104f0db015dd7802bae92d)

2022-04-08 09:50 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    """
А что будет, если у нас не используется кросс-валидация? 
Я вот попробовал задать cv_folds как None и получил ошибку

2022-04-08 13:55 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    """
[Поправил](https://github.com/nccr-itmo/FEDOT/pull/612/commits/f105f1c9e45fcacc395478da753ba66826428a98)

2022-04-09 19:53 UTC, Dreamlone approved these changes

2022-04-09 19:53 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +    # print(baseline_model.get_metrics())
Опять стоит не забыть расскоментить

2022-04-09 19:53 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    individual_context.ind.metadata['computation_time'] = timeit.default_timer() - start_time
А у нас computation_time для пайплайнов тоже в datetime формате? В общем, надо, чтобы это дело было унифицировано. И если в секундах замеряется, то стоит это слово добавить в ключ, чтобы не перепутать

2022-04-11 09:39 UTC, IIaKyJIuH requested changes

2022-04-11 09:39 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
Енумы в питоне - синглтон, их лучше сравнивать через `is`, однако, это работает без проблем, потому что в FEDOT написали прослойку для енумов.

Обращаясь к @nicl-nno, считаю, что можно запросто избавиться от этой прослойки - [`ComparableEnum`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/utilities/data_structures.py#L66-L76), если просто соблюдать правильный принцип сравнения синглтонов.

2022-04-11 09:39 UTC, IIaKyJIuH commented on fedot/core/validation/compose/tabular.py
> +            if fold_id != cv_folds - 1 and fold_id != 0:
Вообще можно упростить до `0 != fold_id != cv_folds - 1`, но лучше проголосовать за то, как нагляднее

2022-04-11 09:39 UTC, IIaKyJIuH commented on fedot/core/validation/compose/time_series.py
> +            if fold_id != cv_folds - 1 and fold_id != 0:
Аналогично комменту из [`table_metric_calculation`](https://github.com/nccr-itmo/FEDOT/pull/612/files#diff-be18b6ca8e798ef8db958502103a22f5ed791f5417fac4e4d8e6f4ec3fb7b7adR41)

2022-04-11 09:39 UTC, IIaKyJIuH commented on fedot/core/validation/split.py
> +def ts_cv_generator(data, folds: int, validation_blocks: int, log = default_log(__name__)) -> Iterator[Tuple[InputData, InputData]]:
`default_log(...)` возвращает наш класс `Log`, а вообще пользовательские классы в питоне - мутабельные; мутабельные дефолтные параметры могут привести к проблемам.

Лучше, в общем, просигнализировать, что log - опциональный, а ниже его задать так: `log = log or default_log(__name__)`

2022-04-11 09:39 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +        if type(node.operation) == Model:
Может просто `isinstance(node.operation, Model)`?

В остальных тестах те же замечания

2022-04-11 09:39 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +            assert node.metadata.metric is None
Попробуй параметризовать все эти 4 теста через `pytest.mark.parametrize`

2022-04-11 09:39 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
Эти тесты тоже можно параметризовать

2022-04-11 09:41 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
>если просто соблюдать правильный принцип сравнения синглтонов

Проблема в том, что внешние пользователи FEDOT не умеют его соблюдать) Поэтому и добавили прослойку.

2022-04-11 09:50 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
Не знал, всегда видел в FEDOTe обращение через равенство, поэтому сделал так

2022-04-11 09:55 UTC, valer1435 commented on fedot/core/validation/compose/tabular.py
> +            if fold_id != cv_folds - 1 and fold_id != 0:
Проголосую за то, что такая запись может и короткая, но не удобно читаема (лично мне с and or удобнее)

2022-04-11 11:55 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +    # print(baseline_model.get_metrics())
[Раскомментировал](https://github.com/nccr-itmo/FEDOT/pull/612/commits/61a8a67f75856b717a1effd8e5f1e9492570a3e7#diff-b42069019862f2fa94d0428f6eae68669c539a219c75684c54c01c3778af65dcR9-R13)

2022-04-11 11:55 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    individual_context.ind.metadata['computation_time'] = timeit.default_timer() - start_time
[Да](https://github.com/nccr-itmo/FEDOT/pull/612/commits/61a8a67f75856b717a1effd8e5f1e9492570a3e7#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R31), в секундах

2022-04-11 11:56 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
Стоит ли исправлять? Тогда лучше везде и сразу на is исправить

2022-04-11 11:57 UTC, valer1435 commented on fedot/core/validation/split.py
> +def ts_cv_generator(data, folds: int, validation_blocks: int, log = default_log(__name__)) -> Iterator[Tuple[InputData, InputData]]:
[Убрал ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/61a8a67f75856b717a1effd8e5f1e9492570a3e7#diff-bc82fae06f383f0c24d15cfa8864a019d9bce71280fb2231e86875e10860a1b1R112)значение по умолчанию

2022-04-11 11:58 UTC, valer1435 commented on test/unit/composer/test_history.py
> +        if type(node.operation) == Model:
[Да](https://github.com/nccr-itmo/FEDOT/pull/612/commits/61a8a67f75856b717a1effd8e5f1e9492570a3e7#diff-bc82fae06f383f0c24d15cfa8864a019d9bce71280fb2231e86875e10860a1b1R112), так действительно логичнее

2022-04-11 11:58 UTC, valer1435 commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
[Тык](https://github.com/nccr-itmo/FEDOT/pull/612/commits/ebd1fdb42125c17469756676c89ba02584cb7e44)

2022-04-11 13:03 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    individual_context.ind.metadata['computation_time'] = timeit.default_timer() - start_time
`timeit.default_timer() - start_time` выдает результат в секундах? Похоже, как будто это будет datetime объект

2022-04-12 15:15 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
Ну я всё же считаю, что нужно писать корректно, поэтому если у внешних пользователей и будут проблемы, то это их вина, а всем не угодишь)

2022-04-12 17:07 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    if input_data.task.task_type == TaskTypesEnum.ts_forecasting:
[Заменил](https://github.com/nccr-itmo/FEDOT/pull/612/commits/b0987506e47c84b31172939a77d14d343e19b587)

2022-04-12 17:25 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    individual_context.ind.metadata['computation_time'] = timeit.default_timer() - start_time
![image](https://user-images.githubusercontent.com/32017472/163019337-371c1624-1233-42d9-9003-28875c0a8328.png)
Да нет, обычный флоат вроде

2022-04-13 07:22 UTC, IIaKyJIuH commented on fedot/core/validation/split.py
> +def ts_cv_generator(data, folds: int, validation_blocks: int, log = default_log(__name__)) -> Iterator[Tuple[InputData, InputData]]:
Добавь ещё typing, плиз

2022-04-13 07:38 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
Я хотел сказать, что так как эти методы ну очень похожи, то можно не держать их копии, а просто передавать определённые параметры в `pytest.mark.parametrize`, а код внутри сделать типа шаблонным, что у тебя почти получилось.

Тебе придётся ещё передать функцию сбора метрики в первые три функции из предыдущего замечания, часть параметров можно будет задать через `functools.partial`.
В функциях из этого замечания нужно передать ещё генератор, который тоже можно частично забиндить через `functools.partial`.

Попробуй так, суть в том, что кода должно стать меньше.

2022-04-13 08:25 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/evaluating.py
> +    individual_context.ind.metadata['computation_time'] = timeit.default_timer() - start_time
А, тогда ок

2022-04-13 17:28 UTC, valer1435 commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
[Теперь ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/5111e627911df7795db8277f8c11d432a626178e#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R123-R138)понял, о чем ты. Действительно, мощная вещь в связке с partial

2022-04-13 17:30 UTC, valer1435 commented on fedot/core/validation/split.py
> +def ts_cv_generator(data, folds: int, validation_blocks: int, log = default_log(__name__)) -> Iterator[Tuple[InputData, InputData]]:
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/0975e9354e642733c3ee3b29ab0904550a55e803)

2022-04-14 10:40 UTC, valer1435 commented on fedot/core/composer/gp_composer/gp_composer.py
> +            objective_function_for_pipeline = partial(self.composer_metric,
Это вызвано тем, что когда мы хотим посчитать промежуточную метрику на узле, нам приходится использовать аргументы [calculate_objects ](https://github.com/nccr-itmo/FEDOT/pull/612/files#diff-64feac041c3d9d1dc551abd1aaea42632bc64c14c108c558948aa64a5d3f4bf8R67-R75)(в частности инпут дату, метрики и тд.). И чтобы из вытащить из partial приходилось юзать обращение по индексам, что мы с Мишей сочли не очень правильным. Поэтому переделал в kwargs

2022-04-14 10:44 UTC, valer1435 commented on fedot/api/main.py
> +            'collect_intermediate_metric' - save intermediate metric into nodes
Основная идея - считать промежуточные метрики на узлах. Так как пайплайн может состоять из нескольких моделей, выход которых является входом для других моделей, может быть целесообразно высчитывать промежуточные метрики. (Например, потом по этой информации можно будет обрубать лишние части пайплайна).

2022-04-14 11:10 UTC, valer1435 commented on fedot/api/main.py
> +            'collect_intermediate_metric' - save intermediate metric into nodes
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/e74c7b0acaae9b638ffa0f81d96cab75a93ae285#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR64-R65)побольше информации

2022-04-14 11:26 UTC, gkirgizov approved these changes

2022-04-14 11:27 UTC, gkirgizov commented on fedot/core/composer/gp_composer/gp_composer.py
> +            objective_function_for_pipeline = partial(self.composer_metric,
Ага, понял, имеет смысл

2022-04-14 11:33 UTC, valer1435 commented on fedot/core/composer/gp_composer/gp_composer.py
> -                        pipeline: Pipeline) -> Optional[Tuple[Any]]:
К сожалению из-за kwargs partial не работает так, как как хочется( Причины kwargs тут уже описал

2022-04-14 12:12 UTC, valer1435 commented on test/unit/composer/test_composer.py
> +    composer.composer_metric(metrics=[quality_metric], train_data=dataset_to_compose, test_data=test_data,
Тут аналогично

2022-04-14 14:20 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
Уже лучше, но забинди метрику сразу на функцию, и вместо неё передавай лучше датасет, чтобы как раз обучить пайплайн, а потом передать в `method` и пайплайн и датасет, т.е что-то похожее на.:
```
@pytest.mark.parametrize("pipeline, metric_method, data",
[(rf_scaling_pipeline(),
  partial(collect_intermediate_metric_for_nodes_cv,
      cv_generator=partial(tabular_cv_generator, get_classification_data()[0], 3),
      metric=MetricsRepository().metric_by_id(ClassificationMetricsEnum.ROCAUC)
  ),
  get_classification_data()[0]),
  ...
]
def test_collect_intermediate_metric(pipeline, metric_method, data):
    """ Test if intermediate metric collected for nodes """
    pipeline.fit(data)
    metric_method(pipeline=pipeline)

    ...
```
Думаю, можно подумать немного, как не писать дважды вызов одного и того же датасета, чтобы было ещё эргономичнее.

2022-04-14 14:23 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
Уже лучше, но забинди метрику сразу на функцию, и вместо неё передавай лучше датасет, чтобы обучить пайплайн (или здесь и не надо?), а потом передать в method обученный пайплайн, т.е что-то похожее на.:

@pytest.mark.parametrize("pipeline, metric_method, data",
[(rf_scaling_pipeline(),
  partial(collect_intermediate_metric_for_nodes_cv,
      cv_generator=partial(tabular_cv_generator, get_classification_data()[0], 3),
      metric=MetricsRepository().metric_by_id(ClassificationMetricsEnum.ROCAUC)
  ),
  get_classification_data()[0]),
  ...
]
def test_collect_intermediate_metric(pipeline, metric_method, data):
    """ Test if intermediate metric collected for nodes """
    pipeline.fit(data)
    metric_method(pipeline=pipeline)

    ...
Думаю, можно подумать немного, как не писать дважды вызов одного и того же датасета, чтобы было ещё эргономичнее.

2022-04-15 07:26 UTC, valer1435 commented on test/unit/composer/test_history.py
> +                           ts_cv_generator(get_ts_data()[0], 3, 2))])
[Записал](https://github.com/nccr-itmo/FEDOT/pull/612/commits/f324ea457be210ac3884093b6402a2c35256d1e7#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R160-R165)

2022-04-15 07:26 UTC, valer1435 commented on fedot/core/validation/split.py
> +def ts_cv_generator(data, folds: int, validation_blocks: int, log = default_log(__name__)) -> Iterator[Tuple[InputData, InputData]]:
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/612/commits/f324ea457be210ac3884093b6402a2c35256d1e7#diff-bc82fae06f383f0c24d15cfa8864a019d9bce71280fb2231e86875e10860a1b1R115)

2022-04-15 07:27 UTC, valer1435 commented on test/unit/composer/test_history.py
> +        assert np.all(idx_first[i] == idx_second[i])
Фит действительно куда-то потерялся. Вроде [переделал ](https://github.com/nccr-itmo/FEDOT/pull/612/commits/f324ea457be210ac3884093b6402a2c35256d1e7#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R124-R139)как надо

2022-04-15 07:49 UTC, gkirgizov commented on test/unit/composer/test_composer.py
> +    composer.composer_metric(metrics=[quality_metric], train_data=dataset_to_compose, test_data=test_data,
Но тут не `partial`, тут вызов обычной функции

2022-04-15 07:51 UTC, IIaKyJIuH commented on fedot/core/validation/compose/tabular.py
> +            if fold_id != cv_folds - 1 and fold_id != 0:
Ладно, соглашусь

2022-04-15 07:51 UTC, IIaKyJIuH approved these changes

2022-04-15 07:57 UTC, valer1435 commented on test/unit/composer/test_composer.py
> +    composer.composer_metric(metrics=[quality_metric], train_data=dataset_to_compose, test_data=test_data,
И правда, [передал](https://github.com/nccr-itmo/FEDOT/pull/612/commits/17b0b8f46dc50f55d669a45857f093a91c577027#diff-8576c86049d8efe372732362c9a3d35919785e3795da4155e52f8733fbebffe1R291)

2022-04-15 09:23 UTC, nicl-nno approved these changes

2022-04-15 09:48 UTC, merged

2022-04-15 10:57 UTC, gkirgizov reviewed
Не знаю, как я так отревьюил, что все это пропустил. Но как попробовал сам на это отребейзить свой текущий PR #639, увидел это. Откатывать не нужно. После своего ребейза я это быстро перетру.
Но для @valer1435 будет полезно почитать то что я увидел, когда второй раз смотрел

2022-04-15 10:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluating.py
> +        if not individual_context.objective_function.args:
Если помимо функции нам требуется доступ к каким-то данным -- то нам нужно использовать не функцию, а нормальный объект с полями. `objective_function` -- это просто Callable, а тут, очевидно, нужен уже какой-то класс. Либо передавать эти данные, которые мы запрашиваем (metrics, test_data и тд) отдельно от `objective_function`.

Текущее решение через кейворды -- неподдерживаемое. Оно скрывает зависимости и модифицировать его очень тяжело. Оно также полагается на то, что "где-то там, далеко-далеко" кто-то использует именно `partial` и именно с такими кейвордами. А если кто-то один кейворд поменяет? Откуда он узнает, что что-то сломалось здесь? Только если еть актуальные тесты. Но это же еще дебажить и исктаь надо! А если бы был класс с полями -- то все видно сразу в IDE, где и что поправить надо.

Не надо так делать никогда, это очень плохой костыль.
Те же соображения прилагаются к использованию `individual_ontext` который просто скрывается зависимости. Если кто-то уберет одно поле из него -- узнать невозможно. Если кто-то, кто с этим кодом незнаком, будет это читать -- он понятия не будет иметь, какие поля должны быть в `individual_context`.

2022-04-15 10:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluating.py
> +            collect_intermediate_metric_for_nodes_cv(converted_object,
Это также совершенно ненужная дупликация кода, в которой нет никакого одержательного различия. В прошлом своем PR я намеренно от этого избавлялся, не для того, чтобы тут же это множить.
Обе эти функции имеют одинаковую функциональность и их можно было бы обощить до одной функции.

2022-04-15 10:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +                 cv_generator()][-1]
Вся суть использования генератора -- в том, чтобы **не использовать целый список**. А что, если каждый test_data весит по 100 мегабайт? И у нас 10 фолдов? Тогда здесь ты совершенно впустую выделяешь и  гигабайт памяти чтобы тут же выкинуть.

Общий принцип -- видишь генератор вместо списка -- задумайся, почему здесь не используют список. А лучше не думать и просто работать с генераторами, если нет очень веской причины для списка.

2022-04-15 10:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +    collect_intermediate_metric_for_nodes(pipeline, test_data, metric, validation_blocks=validation_blocks)
Помимо этого, как я уже написал, это почти идентичные функции, которые заставляют где-то делать лишние бранчи. Это могла быть одна функция на генераторе.

2022-04-15 10:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +def collect_intermediate_metric_for_nodes(pipeline, input_data, metric, validation_blocks=None):
Раз мы в кодовой базе стараемся побольше писать кодовые сигнатуры -- то надо их стараться писать, не лениться.
Это облгечает читаемость и изменения в код, очень облегчает. Все-таки его будешь читать и менять не только ты. И проверки корректности. И вообще, одни только плюсы кроме одного -- чуть дольше писать.

2022-04-15 12:43 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +                 cv_generator()][-1]
Тут проблема в том, как происходит логика подсчета промежуточных метрик. Изначально я это делал на уровне Node. То есть на predict шаге в ноду записывалась метрика на тестовых данных на текущем этапе. Это позволяло избегать лишних вызовов, но засоряло код в Node. Поэтому решили делать это отдельно и менее оптимально. 
Теперь мы хотим отдельно посчитать метрику на всех нодах на тестовых данных после того, как обучились. Но так как у нас кросс-валидация - мы в итоге имеем пайплайн, обученный только на последнем разбиении. Соответственно, проще по времени не фитить ничего заново, а просто взять 3 фолд и посчитать метрики на нем. Так мы точно будем уверены, что мы не предсказываем то, что уже видели. Поэтому тут такая странная конструкция. Честно, не знаю, как тут по-другому обойтись, кроме как не перелопачивать все заново

2022-04-15 12:45 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluating.py
> +        if not individual_context.objective_function.args:
Понял идею, буду стараться так не делать

2022-04-15 12:57 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +            node.metadata.metric = metric_func(pipeline, reference_data=input_data, validation_blocks=validation_blocks)
А тут я будто что-то не понимаю. Если мы считаем метрики для всего `pipeline`, то почему оно относится именно к ноде? Разве мы тут не одно и то же значение N раз посчитаем и запишем?

2022-04-15 13:03 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +            node.metadata.metric = metric_func(pipeline, reference_data=input_data, validation_blocks=validation_blocks)
Спасибо, что заметил. Похоже я за постоянным переделыванием подхода проглядел этот момент. Хотя фиксится должно не сложно

2022-04-15 13:08 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/intermediate_metric.py
> +            node.metadata.metric = metric_func(pipeline, reference_data=input_data, validation_blocks=validation_blocks)
Я пофикшу в своем PR как отребейжусь