Graph edit distance between pipelines
nccr-itmo/FEDOT pull request #614
Opened 2022-03-28 10:51 UTC by MorrisNein

* Added `Pipeline.distance_to_other(other)` method that allows to evaluate [graph edit distance](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.similarity.optimize_graph_edit_distance.html) with respect to a node operation and parameters.

Minor improvements:
* Ability to store a dictionary of `additional_params` in optimizer history.

2022-03-28 10:51 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/pipelines/pipeline.py`](https://github.com/nccr-itmo/FEDOT/blob/c05e54dbe3cf5411b4bd1437392b6a2b5e9ee1d8/fedot/core/pipelines/pipeline.py):

> [Line 384:20](https://github.com/nccr-itmo/FEDOT/blob/c05e54dbe3cf5411b4bd1437392b6a2b5e9ee1d8/fedot/core/pipelines/pipeline.py#L384): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2022-03-30 21:20 UTC, nicl-nno requested changes

2022-03-30 21:20 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.additional_params = additional_params
Тогда computation_time тоже стоит отправить в additional_params.

2022-03-30 21:20 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +        if additional_params is None:
Можно назвать metadata для большей понятности.

2022-03-30 21:20 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        return distance
Это можно сделать методом GraphOperator - т.к. вроде семантика самого пайплайна тут никак не учитывается.

2022-03-31 10:53 UTC, MorrisNein commented on fedot/core/pipelines/pipeline.py
> +        return distance
Ок, действительно так лучше. Сделал.

2022-04-01 11:05 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.additional_params = additional_params
У `Pipeline` и у `PipelineTemplate` есть `computation_time`. Стоит ли вносить такое различие в семантику?

2022-04-01 11:07 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +        if additional_params is None:
Согласен, переименовал

2022-04-01 12:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +        self.additional_params = additional_params
Готово

2022-04-01 12:58 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +
Тут бы ещё тесты в которых расстояне не равно 0.

2022-04-01 16:24 UTC, MorrisNein commented on test/unit/dag/test_graph_operator.py
> +
Добавил ассерты для основных случаев.

2022-04-01 16:28 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +    assert int(distance6) == 1  # changes: 1 node (operation + params)
Может не создавать переменные, а сразу сделать assert для компактности?

2022-04-01 16:28 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +    pipeline4.nodes[-1].custom_params = {'n_jobs': -1}  # change params of one node
Как-то плохо читается. Возможно, тут лучше использовать новый класс pipelinebuilder.

2022-04-01 16:29 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +def get_pipeline() -> 'Pipeline':
Тут вроде не нужны кавычки (они используются там, где есть риск циклическчих импортов)

2022-04-01 20:34 UTC, IIaKyJIuH requested changes

2022-04-01 20:34 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
> +                    len(ind_pipeline_template.operation_templates), ind_pipeline_template.depth, str(ind.metadata)
Попробуй не делать каст metadata к `str`, должно работать.

2022-04-01 20:34 UTC, IIaKyJIuH commented on test/unit/dag/test_graph_operator.py
> +    assert int(distance6) == 1  # changes: 1 node (operation + params)
Поддерживаю вариант @nicl-nno, но, как другой вариант, можно просто более информативные названия дать:
не `distanceX`, а `pipelineA_to_pipelineB`

2022-04-01 20:36 UTC, IIaKyJIuH commented on test/unit/dag/test_graph_operator.py
> +    pipeline4.nodes[-1].custom_params = {'n_jobs': -1}  # change params of one node
Поддерживаю вариант @nicl-nno, но, как другой вариант, можно просто более информативные названия дать:
не distanceX, а pipelineA_to_pipelineB

2022-04-01 20:37 UTC, IIaKyJIuH commented on test/unit/dag/test_graph_operator.py
> +    assert int(distance6) == 1  # changes: 1 node (operation + params)
Поддерживаю вариант @nicl-nno, но, как другой вариант, можно просто более информативные названия дать:
не distanceX, а pipelineA_to_pipelineB

2022-04-05 15:12 UTC, MorrisNein commented on test/unit/dag/test_graph_operator.py
> +    assert int(distance6) == 1  # changes: 1 node (operation + params)
Дал информативные имена пайплайнам и перенёс сравнения в assert'ы.

2022-04-05 15:13 UTC, MorrisNein commented on test/unit/dag/test_graph_operator.py
> +    pipeline4.nodes[-1].custom_params = {'n_jobs': -1}  # change params of one node
Использовал builder, дал пайплайнам явные имена.

2022-04-05 15:14 UTC, MorrisNein commented on test/unit/dag/test_graph_operator.py
> +def get_pipeline() -> 'Pipeline':
Поправил

2022-04-05 15:26 UTC, MorrisNein commented on fedot/core/dag/graph_operator.py
> +            node2: GraphNode = node_data2.get('node')
Попробовал такую типизацию, но не похоже, чтобы интерпретатор определял типы переменных node1, node2.
```
def node_match(node_data1: Dict[str, GraphNode], node_data2: Dict[str, GraphNode]) -> bool:
    node1, node2 = (node_data.get('node') for node_data in (node_data1, node_data2))
```

Полагаю в таком случае написать явно
```
node1: GraphNode
node2: GraphNode
node1, node2 = (node_data.get('node') for node_data in (node_data1, node_data2))
```

2022-04-05 16:45 UTC, MorrisNein commented on fedot/core/dag/graph_operator.py
> +        set_node_attributes(g2, nodes2, name='node')
Готово

2022-04-05 16:46 UTC, MorrisNein commented on fedot/core/optimisers/adapters.py
> +            metadata = {}
Готово

2022-04-05 16:46 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +            metadata = {}
Готово

2022-04-05 16:46 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +                    len(ind_pipeline_template.operation_templates), ind_pipeline_template.depth, str(ind.metadata)
Да, действительно

2022-04-05 16:51 UTC, MorrisNein commented on fedot/core/dag/graph_operator.py
> +        set_node_attributes(g2, nodes2, name='node')
[Коммит](https://github.com/nccr-itmo/FEDOT/pull/614/commits/3983cee803cf0dc278b49aed3dc2950f2b26786c)

2022-04-05 16:55 UTC, nicl-nno commented on test/unit/dag/test_graph_operator.py
> +    assert int(pipeline_linear.operator.distance_to_other(pipeline_knn_alternate_params)) == 1  # ch: operation + params
А зачем тут везде приведение к int? Ведь distance_to_other его и возвращает.

2022-04-05 16:56 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +    def distance_to_other(self, other_graph: 'Graph') -> float:
Можно для лаконичности назвать distance_to?

2022-04-05 16:57 UTC, nicl-nno commented on fedot/core/dag/graph_operator.py
> +            node2: GraphNode = node_data2.get('node')
Не вижу особой пользы от явной записи как во втором примере. Вроде из названия и типов входных данных и так понятно.

Алсо, лучше использовать нотацию node_1 и т.п. для единообразия.

2022-04-06 12:43 UTC, MorrisNein commented on test/unit/dag/test_graph_operator.py
> +    assert int(pipeline_linear.operator.distance_to_other(pipeline_knn_alternate_params)) == 1  # ch: operation + params
В общем случае -- float. Но в текущей имплементации да, получаются только целые расстояния. Хорошее замечание, сделаю приведение к int в самом методе.

2022-04-06 13:24 UTC, MorrisNein commented on fedot/core/dag/graph_operator.py
> +    def distance_to_other(self, other_graph: 'Graph') -> float:
Так и сделал

2022-04-06 16:23 UTC, nicl-nno approved these changes
Ребейз только не забудь сделать.

2022-04-06 18:14 UTC, IIaKyJIuH commented on fedot/core/dag/graph_operator.py
> +            node2: GraphNode = node_data2.get('node')
Удивительно, но `pycharm` правда не может определить тип переменной из такого выражения.
В том же VS Сode со стандартными плагинами для питона от майкрософта всё максимально прозрачно.

Кажется, эта проблема существует уже [давно](https://youtrack.jetbrains.com/issue/PY-27708).
Вообще говоря не раз уже сталкиваюсь с тем, что пайчарм на "простых" вещах ломается. Например, была у меня ещё проблема с [невозможностью корректного форматирования отступов внутри скобочного выражения](https://youtrack.jetbrains.com/issue/PY-28496) (совпадение ли, но этой проблеме тоже уже 4 года))

2022-04-06 18:17 UTC, IIaKyJIuH commented on fedot/core/dag/graph_operator.py
> +            node2: GraphNode = node_data2.get('node')
В общем, я бы всё же оставил обычный comprehension без явного указания типа +, как предлагает @nicl-nno, сделал бы единообразную нотацию.

2022-04-06 18:25 UTC, IIaKyJIuH commented on fedot/core/dag/graph_operator.py
> +        set_node_attributes(g2, nodes2, name='node')
Го лучше без двойного for, вот так:
```
(gr1, nodes1), (gr2, nodes2) = (graph_structure_as_nx_graph(graph) for graph in (self._graph, other_graph))
```
Можно ещё короче:
```
(gr1, nodes1), (gr2, nodes2) = map(graph_structure_as_nx_graph, (self._graph, other_graph))
```

2022-04-06 18:37 UTC, MorrisNein commented on fedot/core/dag/graph_operator.py
> +        set_node_attributes(g2, nodes2, name='node')
Посмотри плиз вторую ссылку. Я просто отправил этот этап в цикл, раз уж мы всё равно решили сделать `set_node_attributes` в цикле. Так выглядит максимально просто для восприятия, имхо.

2022-04-06 19:43 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +                 metadata: Dict[str, Any] = None):
Спасибо, проглядел.
[Поправил](https://github.com/nccr-itmo/FEDOT/pull/614/commits/84cbee5597ff8c88fe6b12f49b9879f40e6f56f6) это и ещё где увидел. Конечно, по типизациям в идеале бы системно пройтись, но не в рамках этого PR.

2022-04-06 19:52 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/individual.py
> +                 metadata: Dict[str, Any] = None):
Молодец!

2022-04-06 19:52 UTC, IIaKyJIuH approved these changes

2022-04-07 06:49 UTC, merged