fix get_metrics method
nccr-itmo/FEDOT pull request #620
Opened 2022-03-29 15:07 UTC by maypink

Earlier in this method, when calculating ROCAUC metric, predictions were redefined and probabilities were placed in `prediction.predict`. Then the probabilities were converted into labels
Now at the very beginning when calculating the metric for which labels are needed, predictions are given in labels

2022-03-29 15:38 UTC, Dreamlone requested changes

2022-03-29 15:38 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
Лучше стоит как-нибудь более низкоуровнего это делать, а то сейчас для проверки небольшой части функциональности API (расчета метрик), запускается весь AutoML арсенал. Можно как-нибудь протестировать (кстати get_dataset(task_type=task_type) точно подходит для этого теста?) 

Сам тест кстати очень долгий вышел
![image](https://user-images.githubusercontent.com/52418437/160649996-b0ff09b1-ba7d-49a0-b54f-fa882fc0271c.png)

Можно если что вот так задать 
`model.fit(train_data, predefined_model='logit')`
Работает пошустрее, так как обучает всего один пайплайн
![image](https://user-images.githubusercontent.com/52418437/160650088-e43e877d-a9b0-4c0c-a125-8033102b054a.png)

2022-03-30 08:55 UTC, maypink commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
[done](https://github.com/nccr-itmo/FEDOT/pull/620/commits/7f678ad97dd3a3c54c02dca08d99d9e07c126c4a#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R81-R82)

2022-03-30 08:55 UTC, maypink commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
[ну да, в ирисах действительно многовато для бинарности))](https://github.com/nccr-itmo/FEDOT/pull/620/commits/7f678ad97dd3a3c54c02dca08d99d9e07c126c4a#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R54)

2022-03-30 09:11 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
Можно ещё немного упростить

```Python
task = Task(TaskTypesEnum.classification)
data_processor = ApiDataProcessor(task=task)
```

И тогда не нужно целого Fedot инициализировать.

2022-03-30 09:13 UTC, Dreamlone approved these changes

2022-03-30 09:50 UTC, nicl-nno approved these changes

2022-03-30 10:17 UTC, maypink commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
кажется, что до get_metrics я таким способом не доберусь. мне же из оттуда нужен не только метод correct_predictions у data_processor, логику внутри тоже хотелось бы проверить

2022-03-30 10:29 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    assert isinstance(metrics['f1'], float)
Вообще да, согласен. Ну тогда стоит откатиться всё таки к первому варианту и просто добавить строку 
model.fit(train_data, predefined_model='logit')

Конструкции `model.data_processor.define_data` выглядят сильно громоздкими

2022-03-30 11:01 UTC, merged