Refactor existing DataMerge functionality (closes #610)
nccr-itmo/FEDOT pull request #621
Opened 2022-03-31 14:19 UTC by gkirgizov

Collapse most of the code and branches into one direct 'merge' method with stages.
Merge process is almost same for most data types, essentially just concatenating data along last dimension.
Stages can be customized for each datatype, instead of branching to separate merge.

Substitute many manual routines with numpy counterparts.
Move merge-related stuff from SupplementaryData into separate SupplementaryDataMerger.

Drop InputData.from_predictions in favor of DataMerge.merge that now directly returns InputData.

2022-03-31 14:19 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:















* In the file [`fedot/core/utilities/array_utilities.py`](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/fedot/core/utilities/array_utilities.py):

> [Line 40:1](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/fedot/core/utilities/array_utilities.py#L40): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file





* In the file [`test/unit/data/test_data_merge.py`](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge.py):

> [Line 117:29](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge.py#L117): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','
> [Line 144:26](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge.py#L144): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent





* In the file [`test/unit/data/test_data_merge_text.py`](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge_text.py):

> [Line 37:10](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge_text.py#L37): [E111](https://duckduckgo.com/?q=pep8%20E111) indentation is not a multiple of four
> [Line 37:10](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge_text.py#L37): [E117](https://duckduckgo.com/?q=pep8%20E117) over-indented

* In the file [`test/unit/data/test_data_merge_ts.py`](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge_ts.py):

> [Line 42:50](https://github.com/nccr-itmo/FEDOT/blob/a9fd45998eb80d04cf59b0172182cb7cfd7476ce/test/unit/data/test_data_merge_ts.py#L42): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ','

2022-03-31 14:29 UTC, nicl-nno commented on fedot/core/data/data_merger.py
> +        ts_indices = list(map(DataMerger.is_ts_predict_index, outputs))
Кмк стоит пояснить в комментарии, почему возникает необходимость в таком исключении. Вроде если ts_predict_index - то и тип данных ts.

2022-04-01 08:05 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +    def merge_datatype(data_types: Iterable[DataTypesEnum]) -> Optional[DataTypesEnum]:
Я оставил некоторые функции статическими внутри класса, чтобы они не валялись где-то сбоку неприкаянные. А так ясно, к чему они относятся. Все равно их больше никто не будет использовать, они однозначно под DataMerger написаны. А то, что некоторая его логика не требует доступа к `self`, это не делает эту логику не относящейся к классу. У меня такой ход мыслей.

По поводу имени: переименую

2022-04-01 08:09 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +        ts_indices = list(map(DataMerger.is_ts_predict_index, outputs))
Да, поясню

2022-04-01 08:09 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +            cls = DataMerger
ок

2022-04-01 08:11 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +    def find_priority_output(outputs: List['OutputData']) -> 'OutputData':
ок

2022-04-01 09:31 UTC, Dreamlone requested changes
Пока косметические моменты описал. Как начну запускать код, мб появятся ещё предложения
По архитектуре всё кул - примерно так и представлял обновленный Merger в своих снах

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/data/data_merger.py
> +from fedot.core.utilities.array_utilities import *
Я за то, чтобы как можно меньше использовать utilities и подобные модули. Писал почему так считаю например вот в этом [треде](https://github.com/nccr-itmo/FEDOT/pull/482#discussion_r747404235). 

Тут ещё накладывается и то, что array_utilities содержат функции, полезные скорее для данных, чем для ядра в целом, предлагаю в data их и держать

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/pipelines/pipeline_builder.py
> +    OperationT = Union[str, Tuple[str, dict]]
А что тут значит "T"? (если не хочется мне каждый раз разъяснять такие штуки, есть способ - нужно всего лишь...
писать слова полностью)

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/utilities/array_utilities.py
> +    """ Return a view with extra dimensions to the array if necessary,
может название какое-нибудь более говорящее тут придумать?

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/data/data_merger.py
> +        ts_indices = list(map(DataMerger.is_ts_predict_index, outputs))
Вкину пожалуй, что название неговорящее, в `ts_indices` предполагаешь увидеть массив с индексами, а не список с True, False. Хотя как импорты поправишь и запущу код, возможно, мне станет все намного понятней

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/data/data_merger.py
> +
Может куда-нибудь сюда вставить метод, что если output был всего один, то он просто конвертируется в InputData и никаких нижележащих преобразований не потребуется?

2022-04-01 09:31 UTC, Dreamlone commented on fedot/core/data/data_merger.py
> +            cls = TextDataMerger
А мы разве не договаривались, что не будем допускать случая, когда текстовые данные объединяются?

2022-04-01 09:52 UTC, nicl-nno commented on fedot/core/data/data_merger.py
> +    def merge_datatype(data_types: Iterable[DataTypesEnum]) -> Optional[DataTypesEnum]:
>Я оставил некоторые функции статическими внутри класса, чтобы они не валялись где-то сбоку неприкаянные.

Ну они по прежнему будут относиться к модулю data_merger, просто вызываться более компактно. И можно будет поменить их как приватные, чтобы не торчали наружу.

Но в целом на твое усмотрение.

2022-04-01 10:26 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +from fedot.core.log import Log, default_log
yeap, забыл в гите добавить, запушил фиксы и это

2022-04-01 10:27 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_builder.py
> +    OperationT = Union[str, Tuple[str, dict]]
ок

2022-04-01 10:29 UTC, gkirgizov commented on fedot/core/utilities/array_utilities.py
> +    """ Return a view with extra dimensions to the array if necessary,
по аналогии с numpy, где есть `array.ndim` & `np.atleast_3d` etc.
но ок, переименую

2022-04-01 10:30 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +        ts_indices = list(map(DataMerger.is_ts_predict_index, outputs))
переименовал

2022-04-01 10:32 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +
Тоже думал, пробовал -- появляютя лишние ветки на проверку размерностей в завиимоти от типа данных. Получается лишний дублирующий код.

2022-04-01 10:34 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +            cls = TextDataMerger
добавил exception

2022-04-01 10:47 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +from fedot.core.utilities.array_utilities import *
Перенес в data, согласен.

Насчет utilities в целом тоже согласен, что этого нужно избегать по возможности. Но тут возникает такой tradeoff с дублированием кода (вот эта вся маленькая абстрактная функциональность может регулярно быть полезной при работе с данными).
Все-таки использовать такие utilities в разумных пределах удобно. К свалкам кода это ведет только в случае плохой дисциплины, когда "не хочется" продумывать архитектуру. Я же от обратного отталкиваюсь -- очищаю функциональность DataMerger от какиз-то абстрактных routines. Думаю, использование utilities -- это не договор с дьяволом на продажу души системной архитектуры...

2022-04-01 10:49 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +    def merge_datatype(data_types: Iterable[DataTypesEnum]) -> Optional[DataTypesEnum]:
Да, зачастую и module scope подходит. Но тут все-таки оставлю внутри класса. Уровень модуля это уже логически чуть более широкий scope

2022-04-01 13:09 UTC, nicl-nno approved these changes

2022-04-04 08:57 UTC, Dreamlone requested changes
В целом все хорошо, только перенеси плиз Merger-related функции и классы в отдельный модуль, - можно в рамках папки data создать merger например

2022-04-04 08:57 UTC, Dreamlone commented on fedot/core/data/array_utilities.py
> +    common_elements = reduce(np.intersect1d, indices[1:], indices[0])
Просто бесполезное (наверное) наблюдение. В голову пришёл случай, когда индексы OutputData такие
`[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]` и `[11, 5, 2, 13]`, то функция должна по идее выдать `[2, 5, 11, 13]`. - Это не приведёт к каким-нибудь эффектам?

2022-04-04 08:57 UTC, Dreamlone commented on test/unit/data/test_data_merge_text.py
> +print(os.getcwd())
Лишний print

2022-04-04 08:57 UTC, Dreamlone commented on test/unit/data/test_data_merge_ts.py
> +    output_short = get_output_timeseries(len_forecast=5, for_predict=True)
Пусть будет, но на всякий случай - мы пока ни разу не встречались, когда длина прогноза для двух разных моделей при прогнозировании временного ряда отличается

2022-04-04 10:54 UTC, gkirgizov commented on fedot/core/data/data_merger.py
> +        self.common_indices = find_common_elements(*idx_list)
Не сломает, есть тесты на это.

`from_csv` поправлю

2022-04-04 10:56 UTC, gkirgizov commented on fedot/core/data/array_utilities.py
> +    common_elements = reduce(np.intersect1d, indices[1:], indices[0])
Понял, откуда вопрос. Это не общий индекс, это общие элементы индексов. Тут да, будет, возможно сортировка. Но это не имеет значения. Итоговая выборка общего индекса производится в строках

```
    def merge(self) -> 'InputData':
        common_idx = self.select_common(self.main_output.idx)
```

2022-04-05 09:11 UTC, Dreamlone approved these changes
Не забудь ещё плиз ребейз сделать - мастер убежал немного вперёд

2022-04-05 09:11 UTC, Dreamlone commented on fedot/core/data/data.py
> +    if target_column:
Вроде нет необходимости в этой (`features_df = data_frame`) строчке

2022-04-05 09:11 UTC, Dreamlone commented on fedot/core/data/data.py
> +            pass
Кмк стоит возвращать пользователю ошибку о том, что таких столбцов в таблице нет - если речь об этом)

2022-04-05 09:26 UTC, gkirgizov commented on fedot/core/data/data.py
> +            pass
Вот в том и проблема, что код где-то полагается на такое игнорирование ошибки. 

Вот такое место:
```
class CsvStrategy(StrategyDefineData):
    def define_data(self, features: str,
                    ml_task: Task,
                    target: str = None,
                    is_predict: bool = False) -> InputData:
        # CSV files as input data, by default - table data
        if target is None:
            target = 'target'
       ...
```

2022-04-05 09:27 UTC, gkirgizov commented on fedot/core/data/data.py
> +            pass
Я бы это тоже убрал. Логично при загрузке данных знать, что загружается и обойтись без таких assumptions, явно передавая имя столбца.
Просто я не уверен, насколько вы на эту логику полагаетесь. Может, ты помнишь. Что думаешь?

2022-04-05 09:31 UTC, gkirgizov commented on fedot/core/data/data.py
> +            pass
В целом, падает только тест `test_data_from_csv_load_correctly`, если убрать игнорирование ошибки

2022-04-05 09:49 UTC, gkirgizov commented on fedot/core/data/data.py
> +            pass
Пофиксил в последнем коммите. Если нет комментариев на то, что выше, то тогда мержу

2022-04-05 10:15 UTC, Dreamlone commented on fedot/core/data/data.py
> +            pass
Быстро ты) 
Да, в целом со всеми изменениями согласен - мерджи

2022-04-05 10:19 UTC, merged

2022-04-07 20:56 UTC, ARQtty commented on fedot/core/data/array_utilities.py
> +def flatten_extra_dim(data: Optional[np.array]) -> Optional[np.array]:
`np.ndarray` 🙏

2022-04-07 21:29 UTC, Dreamlone commented on fedot/core/data/array_utilities.py
> +def flatten_extra_dim(data: Optional[np.array]) -> Optional[np.array]:
Приветствую! Замечательно, что обратил внимание на наш open-source проект. Этот PR уже закрыт, но если хочется внести изменения, то мы будем только рады - предлагай / вноси изменения, открывай PR, и наслаждайся вкладом в репозиторий :)

2022-04-08 07:34 UTC, gkirgizov commented on fedot/core/data/array_utilities.py
> +def flatten_extra_dim(data: Optional[np.array]) -> Optional[np.array]:
Yeah, поймал потом эту ошибочку с ndarray типами и завел #625