Mixed types columns processing improvement
nccr-itmo/FEDOT pull request #629
Opened 2022-04-06 13:33 UTC by Dreamlone

A modification was made to improve the logic of processing tables with mixed types columns. 

Now if the column contains the string values '?', 'x', '1', '2', '3', '4', the following processing is done. The algorithm tries to convert the column into float type. If the column contains cells that cannot be converted into float and the ratio of such cells exceeds 50% and at the same time there are cells that can be converted, such column is removed from the table.

2022-04-06 13:38 UTC, nicl-nno commented on fedot/preprocessing/data_types.py
> +                deleted_elements_number += 1
Может выдавать тут ворнинги для таких столбцов?

2022-04-07 09:49 UTC, gkirgizov requested changes

2022-04-07 09:49 UTC, gkirgizov commented on fedot/preprocessing/data_types.py
> +                data.supplementary_data.column_types['features'].pop(index_to_delete)
Думаю, этот цикл проще организовать как фильтрацию `column_types['features'] = [col for i, col in enumerate(column_types['features']) if i not in string_columns_transformation_failed]`. И поэффективнее и понятнее без подсчета индексов.

2022-04-07 14:52 UTC, Dreamlone commented on fedot/preprocessing/data_types.py
> +                data.supplementary_data.column_types['features'].pop(index_to_delete)
Ага, конечно, что то тут меня потянуло не туда, спасибо, что заметил
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/629/commits/fffbcbe7e7865446e22e7c1ca5fc6a5d9e265bee), заодно обновил название у метода и описание, чтобы совпадало с тем, что внутри происходит

2022-04-07 14:53 UTC, Dreamlone commented on fedot/preprocessing/data_types.py
> +                deleted_elements_number += 1
Добавил такое предупреждение сразу для всех столбцов скопом (см. [тут](https://github.com/nccr-itmo/FEDOT/pull/629/commits/fffbcbe7e7865446e22e7c1ca5fc6a5d9e265bee#diff-57f1c1458ebb0217744c5492c18bf70f808bfb10c8eec90b4947419ba3c5b2bbR209-R211))

2022-04-07 14:57 UTC, nicl-nno approved these changes

2022-04-08 07:29 UTC, gkirgizov commented on fedot/preprocessing/data_types.py
> +    def _remain_columns_info_without_types_conflicts(self, data: 'InputData'):
Просто грамматика) Корректно будет либо "retain" либо "remaining"

2022-04-08 07:30 UTC, gkirgizov approved these changes

2022-04-08 07:30 UTC, gkirgizov commented on fedot/preprocessing/data_types.py
> +    def _remain_columns_info_without_types_conflicts(self, data: 'InputData'):
Просто грамматика :) Корректно будет либо retain либо remaining

2022-04-08 07:54 UTC, Dreamlone commented on fedot/preprocessing/data_types.py
> +    def _remain_columns_info_without_types_conflicts(self, data: 'InputData'):
Фэнкс, [исправил](https://github.com/nccr-itmo/FEDOT/pull/629/commits/417caf68524e3f1f50632472cfa0f6a68ff687ce)

2022-04-08 08:09 UTC, merged