Refactoring: drop unnecessary branch in evaluating metrics for cv folds
nccr-itmo/FEDOT pull request #637
Opened 2022-04-12 16:54 UTC by gkirgizov

Removing some code duplication in composer. I'm simplifying it for later changes for #608 

P.S. Pushing my refactorings of the Composer & Optimiser by smaller bits to make process easier for reviewers...

2022-04-12 19:59 UTC, nicl-nno approved these changes

2022-04-13 09:03 UTC, Dreamlone requested changes

2022-04-13 09:03 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> +    for train_data, test_data in ts_cv_generator(time_series, folds, validation_blocks, log):
Как говорится, FYI, у Валеры в [этом PR](https://github.com/nccr-itmo/FEDOT/pull/612) идёт переработка системы сбора метрик, чтобы они могли считаться и для каждого узла в том числе. И в этом PR идёт переработка в том числе этих же самых функций с кросс-валидацией. В связи с этим может получится так, что твои изменения будут перетерты Валерой, учитывая, что его PR вольётся в мастер немного позже, а в этом менялось еще и расположение файлов. 

В общем, я бы предложил: 
1) Как этот PR вольется в мастер, заглянуть в Валерин и после ребейза проконтролировать правильно ли подтянулись изменения
2) Написать тесты на кросс-валидацию по временным рядам и по таблицам так, чтобы по метрикам сразу можно было понять хорошо у нас дела идут или плохо. - Нынешние тесты проверяют только корректность разбиений, а я бы предложил сделать проверку в духе "генерируем синтетический датасет с линейной зависимостью, например временной ряд 1, 2, 3, 4, ..., 50 - собираем пайлайн `lagged -> linear` - запускаем кросс-валидацию на 2 фолдах с validation blocks 2 и проверяем, что предсказывает алгоритм  все почти с нулевой ошибкой и при этом нужной длины"

2022-04-13 09:31 UTC, gkirgizov commented on test/unit/validation/test_time_series_cv.py
> +    for train_data, test_data in ts_cv_generator(time_series, folds, validation_blocks, log):
Ага, спасибо за инфу

1) Проконтролирую. Посмотрб на его реквест после 
2) Звучит как отдельный issue, который к этому рефакторингу напрямую не относится. Тут я реорганизовал код, не добавляя никакой логики. Я бы лучше сконцентрировался на #608. Раз считаешь нужным, то заведи его да назначь на меня или на кого-то еще, кто валидацию/временные трогал.

2022-04-13 09:56 UTC, gkirgizov commented on fedot/core/composer/gp_composer/gp_composer.py
> +            cv_generator = ts_cv_generator
думал про kwargs тоже, пожалуй, лучше, да

2022-04-13 09:56 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> +    for train_data, test_data in ts_cv_generator(time_series, folds, validation_blocks, log):
Ага, согласен с твоим комментарием. [Issue тут](https://github.com/nccr-itmo/FEDOT/issues/638). В этом PR можно тогда дополнительные тесты не реализовывать - просто я подумал, что так проще будет проконтролировать изменения в PR Валеры. Но тут как говорится, если получится глазами оценить насколько ничего не ломается от первоначально задуманного, то можно и так

2022-04-13 10:11 UTC, gkirgizov commented on fedot/core/composer/gp_composer/gp_composer.py
> +            cv_generator = ts_cv_generator
ты прав, я что-то переборщил тут. переделал `cv_generator` через partial

2022-04-13 10:13 UTC, Dreamlone approved these changes

2022-04-13 10:56 UTC, gkirgizov commented
@Dreamlone Мержу или жду ревью от Валеры?

2022-04-13 11:00 UTC, Dreamlone commented
> @Dreamlone Мержу или жду ревью от Валеры?

Сейчас я его пну - подожди пока мерджить, пусть посмотрит

2022-04-13 11:42 UTC, merged