Image processing improvement
nccr-itmo/FEDOT pull request #640
Opened 2022-04-13 13:26 UTC by andreygetmanov

- fixed occasional error of test_image_classification_quality
- image resize function now supports RGB images
- changed the format of image size to more сonvenient

2022-04-13 15:09 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
А это целевой размер или фактический? В любом случае - нельзя ли 3-ю размерностью автоаматически определять по данным?

2022-04-13 15:10 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
А не выйдет тут готовую сеть взять вот таким способом? Сам не пробовал.

https://www.tensorflow.org/api_docs/python/tf/keras/applications/vgg16/VGG16

2022-04-13 15:29 UTC, Dreamlone requested changes
Ещё кмк стоит написать легковесный тест, который будет проверять то, корректно ли работает пайплайн, который обрабатывает только картинки

2022-04-13 15:29 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
Не уверен, что это стоит делать в рамках этого PR. но пока просто замечу, что у нас не определено пространство гиперпараметров для CNN модели (см. `fedot/core/pipelines/tuning/search_space.py`). Возможно, мы уже вплотную подошли к тому моменту, когда пора активно включать обработку изображений в наши пайплайны - для этого стоит хотя бы настраивать гиперпараметры у выбранной архитектуры

2022-04-13 15:39 UTC, nicl-nno commented
> Ещё кмк стоит написать легковесный тест, который будет проверять то, корректно ли работает пайплайн, который обрабатывает только картинки

Есть же test_image_classification_quality, он примерно про это.

2022-04-13 15:40 UTC, Dreamlone commented
> Есть же test_image_classification_quality, он примерно про это.

А, тогда ок, вопрос снимается

2022-04-14 07:00 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
> А не выйдет тут готовую сеть взять вот таким способом?

В целом можно, конечно. Но в данный момент выборочно менять архитектуру сетки возможности, кажется, нет (только если руками в скрипте), а мне, вероятно, придётся это делать для решения задач, поэтому такой вариант показался мне удобнее
Как мне кажется, весьма хорошим вариантом в будущем будет реализовать keras.py так, чтобы подгружать разные сети (в т.ч. предобученные) по запросу и выбирать архитектуры на высоком уровне. Есть смысл делать это в ближайших PR?

2022-04-14 07:13 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
> А это целевой размер или фактический?

Целевой

> В любом случае - нельзя ли 3-ю размерностью автоаматически определять по данным?

Третья размерность - это цветовые каналы. Я не встречал там ничего, кроме 1 (чб) или 3 (rgb цветное). К тому же, некоторые нейронки требуют конкретного числа каналов. Если подать vgg16 одноканальное изображение, она не заработает
Если нужно, могу добавить, но не уверен, что понимаю, где это может использоваться

2022-04-14 07:17 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
> Не уверен, что это стоит делать в рамках этого PR. но пока просто замечу, что у нас не определено пространство гиперпараметров для CNN модели (см. `fedot/core/pipelines/tuning/search_space.py`). Возможно, мы уже вплотную подошли к тому моменту, когда пора активно включать обработку изображений в наши пайплайны - для этого стоит хотя бы настраивать гиперпараметры у выбранной архитектуры

Да, согласен! Мб для этого PR это весьма большие изменения, но могу и в нём начать работать в этом русле, если нужно

2022-04-14 07:34 UTC, Dreamlone commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
Да думаю в текущем PR это не стоит трогать - создай пока issue плиз на тему "Добавление гиперпараметров для CNN" и потом уже за него возьмёмся как время будет

2022-04-14 07:40 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
А зачем её может понадобиться менять? Если смысл именно в том, чтобы попробовать стандартную VGG16 как модель-кандидата. Или есть какие-то нюансы?

2022-04-14 07:42 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
>некоторые нейронки требуют конкретного числа каналов

Но пользователь же не знает, сколько каналов ожидает нейронка, которую пробует использовать FEDOT. Потому и выглядит как будто наличие 3-ей размерности напрямую определяется входными данными - в все трансформации должны происходить внутри FEDOT-а.

2022-04-14 07:45 UTC, nicl-nno commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
Можно попробовать architecture_type туда внести - не должно быть сложно. Но если этот PR хотфиксит периодически падающий тест - то можно не в нём.

2022-04-14 10:03 UTC, gkirgizov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
Согласен с Колей -- мало ли мы передаем какие-нибудь особые картинки, где 1й канал -- это карта глубины, а 2й канал -- это температура через ИК камеру. Всякое бывает. А то, сколкьо на хвод может принять нейронка -- правда проблема не пользователя.

2022-04-14 10:10 UTC, gkirgizov requested changes

2022-04-14 10:10 UTC, gkirgizov commented on fedot/core/data/data.py
> +    if img.shape != target_size:
мб тут shape проверять без каналов? `img.shape[:2] != target_size[:2]`

2022-04-14 10:10 UTC, gkirgizov commented on fedot/core/data/data.py
>  def _resize_image(file_path: str, target_size: tuple):
я бы уточнил typehint для target_size, мол, tuple[??]

2022-04-14 10:10 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        transformed_x_test = np.expand_dims(x_test, -1)
Насколько помню, expand_dims только 1 измерение добавляет. А что, если len(x_test.shape) == 2?

2022-04-14 10:48 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
> Можно попробовать architecture_type туда внести - не должно быть сложно. 

Да, добавление achitecture_type и мб даже n_epochs в поле поиска выглядит как достаточно простая задача

> Но если этот PR хотфиксит периодически падающий тест - то можно не в нём.

Хорошо

2022-04-14 10:49 UTC, andreygetmanov commented on examples/advanced/multi_modal_pipeline.py
> +                                'architecture_type': 'vgg16',
> создай пока issue плиз на тему "Добавление гиперпараметров для CNN" и потом уже за него возьмёмся как время будет

[Создал](https://github.com/nccr-itmo/FEDOT/issues/641)

2022-04-14 17:30 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        transformed_x_test = np.expand_dims(x_test, -1)
btw я в одном PR добавил функцию как раз для этого, называется `atleast_n_dimensions`

2022-04-15 13:56 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        transformed_x_test = np.expand_dims(x_test, -1)
> А что, если len(x_test.shape) == 2?

Если так будет, что-то где-то раньше точно поломалось, потому что x_test.shape - это (размер выборки, width, height, channels). Возможен вариант, когда x_test.shape просто (размер выборки, width, height), тогда и добавляем ещё размерность

Как думаешь, в таком случае лучше будет переписать через atleast_n_dimensions? Или норм так оставить?

2022-04-15 14:42 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
> А зачем её может понадобиться менять? Если смысл именно в том, чтобы попробовать стандартную VGG16 как модель-кандидата. Или есть какие-то нюансы?

И правда так. Поменял на готовую. Были нюансы с разными названиями методов (predict_proba в готовой нет, predict выдаёт вероятности), поправил

2022-04-15 14:45 UTC, andreygetmanov commented on fedot/core/data/data.py
> +    if img.shape != target_size:
> мб тут shape проверять без каналов? `img.shape[:2] != target_size[:2]`

Согласен, [поменял](https://github.com/nccr-itmo/FEDOT/blob/0c4c0f1efe3909085744f4f67738b599bb5461c9/fedot/core/data/data.py#L414)

2022-04-15 14:46 UTC, andreygetmanov commented on fedot/core/data/data.py
>  def _resize_image(file_path: str, target_size: tuple):
> я бы уточнил typehint для target_size, мол, tuple[??]

[Добавил](https://github.com/nccr-itmo/FEDOT/blob/0c4c0f1efe3909085744f4f67738b599bb5461c9/fedot/core/data/data.py#L408)

2022-04-15 15:15 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        transformed_x_test = np.expand_dims(x_test, -1)
Проглядел, что это длина shape, а не количество каналов, ошибся, все ок.
Но лучше тогда неточное неравенство заменить точным сравнением. Чтобы было ясно, что shape должен быть 3

2022-04-15 15:29 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
![image](https://user-images.githubusercontent.com/5711814/163589732-b1dab18e-e459-46fc-84fd-e54ed4a7727f.png)

Но для predict-а это же вполне нормальная ситуация?

2022-04-18 08:00 UTC, Dreamlone commented on fedot/core/data/data.py
> +import cv2
Такой вопрос, а opencv у нас в requirements покрывается? У меня просто в venv такая библиотека установлена, но я не уверен, что я её накатил не поверх федотовских requirements

2022-04-18 13:26 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +def create_vgg16(input_shape: tuple,
Если для обученной модели, то пусть будет.

2022-04-18 13:46 UTC, andreygetmanov commented on fedot/core/data/data.py
> +import cv2
> Такой вопрос, а opencv у нас в requirements покрывается?

Да, я [добавил](https://github.com/nccr-itmo/FEDOT/blob/e1972395771017d7f4beb78562c3e1ac13dc9b17/requirements.txt#L34)

2022-04-18 13:52 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
> все трансформации должны происходить внутри FEDOT-а.

Понял, хорошо! Немного [поменял](https://github.com/nccr-itmo/FEDOT/blob/e1972395771017d7f4beb78562c3e1ac13dc9b17/fedot/core/data/data.py#L414), теперь число каналов определяется автоматически при открытии изображения

2022-04-18 13:52 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +        transformed_x_test = np.expand_dims(x_test, -1)
> лучше тогда неточное неравенство заменить точным сравнением.

[Заменил](https://github.com/nccr-itmo/FEDOT/blob/e1972395771017d7f4beb78562c3e1ac13dc9b17/fedot/core/operations/evaluation/operation_implementations/models/keras.py#L131)

2022-04-18 14:32 UTC, gkirgizov approved these changes

2022-04-18 14:35 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
![image](https://user-images.githubusercontent.com/5711814/163823705-3a29bdb0-ade2-493a-8dde-876f701d7baa.png)

Вот тут тогда тоже можно убрать канал?

2022-04-18 14:37 UTC, nicl-nno approved these changes

2022-04-18 14:45 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
> Вот тут тогда тоже можно убрать канал?

Там функция чуть по-другому написана, чем везде (она формирует пайплайн, но без подаваемых данных), поэтому взять внутри неё images_size нельзя. Если нужно, могу унифицировать, но нужно будет чуть переписать этот тест

2022-04-18 14:48 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
Но потом для этого пайплайна выполняется fit - тогда размерность и будет зафиксирована, нет?

2022-04-18 15:06 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
> Но потом для этого пайплайна выполняется fit - тогда размерность и будет зафиксирована, нет?

Если правильно понял вопрос, размерность фиксируется в настройках пайплайна при его сборке

[Увидел](https://github.com/nccr-itmo/FEDOT/blob/267b949ba269a3ea522fe99199a83c0d3cd0742d/test/unit/multimodal/test_multi_modal.py#L11), что там в целом generate_multi_modal_pipeline стоит немного поправить: там дважды задаются image_node. Заодно [поправил](https://github.com/nccr-itmo/FEDOT/blob/267b949ba269a3ea522fe99199a83c0d3cd0742d/test/unit/multimodal/test_multi_modal.py#L14) images_size

2022-04-18 15:10 UTC, nicl-nno commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
>размерность фиксируется в настройках пайплайна при его сборке

Можно понять, зачем это для ширины и высоты - но остальные размерности-то можно не фиксировать, раз ты реализовал их авто-определение.

2022-04-18 15:12 UTC, andreygetmanov commented on cases/multi_modal_genre_prediction.py
> +    images_size = (128, 128, 3)
> Можно понять, зачем это для ширины и высоты - но остальные размерности-то можно не фиксировать, раз ты реализовал их авто-определение.

Да, согласен

2022-04-18 15:16 UTC, Dreamlone approved these changes

2022-04-18 15:17 UTC, Dreamlone commented
Не забудь только плиз ребейз сделать

2022-04-18 17:04 UTC, merged