Iss651
nccr-itmo/FEDOT pull request #652
Opened 2022-04-19 10:43 UTC by gorokhovnik

1. Extending pipeline tuning testing with different models and metrics
2. Fix PipelineTuner.get_metric_value calculation for binary+rf+accuracy-like case (can't calculate metrics with exact labels while returning 1st class probability)

2022-04-19 10:52 UTC, nicl-nno requested changes
А где именно вот это:

Fix PipelineTuner.get_metric_value calculation for binary+rf+accuracy-like case (can't calculate metrics with exact labels while returning 1st class probability)

фиксится?

2022-04-19 10:52 UTC, nicl-nno commented on test/unit/pipelines/test_pipeline_tuning.py
> +    for pipeline in pipelines_simple + [pipeline_complex]:
Лучше всё-таки сделать это заранее.

2022-04-19 10:52 UTC, nicl-nno commented on test/unit/pipelines/test_pipeline_tuning.py
> +    pipelines_simple = [get_simple_regr_pipeline(ot) for ot in get_regr_operation_types()]
ot непонятно.

2022-04-19 10:52 UTC, nicl-nno commented on test/unit/pipelines/test_pipeline_tuning.py
> +            for loss in get_regr_losses():
А сколько по времени такой тест занимает по сравнению с предыдущей реализацией?

2022-04-19 10:54 UTC, gorokhovnik commented
> А где именно вот это:
> 
> Fix PipelineTuner.get_metric_value calculation for binary+rf+accuracy-like case (can't calculate metrics with exact labels while returning 1st class probability)
> 
> фиксится?

Пока не фиксится, я только добавил тестов, чтобы воспроизвести баг. Позову на ревью, когда будет готово

2022-04-19 10:58 UTC, gorokhovnik commented on test/unit/pipelines/test_pipeline_tuning.py
> +            for loss in get_regr_losses():
На локалке 8 секунд против 51. Возможно, на регрессии это имеет меньше смысла, потому что метки всегда возвращаются числом и в метриках всегда используется число. Но на классификации, кажется, essential

2022-04-19 11:01 UTC, nicl-nno commented on test/unit/pipelines/test_pipeline_tuning.py
> +            for loss in get_regr_losses():
Тогда предлагаю оставить только одну регрессионную метрику и сделать поменьше регрессионных моделей - раз там маловероятно возникновение проблем.

2022-04-19 11:06 UTC, gorokhovnik commented on test/unit/pipelines/test_pipeline_tuning.py
> +    pipelines_simple = [get_simple_regr_pipeline(ot) for ot in get_regr_operation_types()]
done

2022-04-19 11:06 UTC, gorokhovnik commented on test/unit/pipelines/test_pipeline_tuning.py
> +    for pipeline in pipelines_simple + [pipeline_complex]:
done

2022-04-19 11:28 UTC, gorokhovnik commented on test/unit/pipelines/test_pipeline_tuning.py
> +            for loss in get_regr_losses():
Done

2022-04-19 21:23 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/164104060-dd54d805-a174-4c6f-9c04-7f1ba78edc69.png)

Кажется эти тесты действительно довольно однообразны. Може заменить на один тест с разными фикстурами?

2022-04-20 22:51 UTC, pep8speaks commented
Hello @gorokhovnik! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`test/unit/pipelines/test_pipeline_tuning.py`](https://github.com/nccr-itmo/FEDOT/blob/54660f0dec41ecf8533b2347164371cf54f93965/test/unit/pipelines/test_pipeline_tuning.py):

> [Line 222:71](https://github.com/nccr-itmo/FEDOT/blob/54660f0dec41ecf8533b2347164371cf54f93965/test/unit/pipelines/test_pipeline_tuning.py#L222): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent
> [Line 223:71](https://github.com/nccr-itmo/FEDOT/blob/54660f0dec41ecf8533b2347164371cf54f93965/test/unit/pipelines/test_pipeline_tuning.py#L223): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2022-04-21 10:11 UTC, nicl-nno commented on fedot/core/pipelines/tuning/tuner_interface.py
> +    not_optimal_target = np.array([[0], [0]])
Не очень понятно, что тут имеется в виду и что происходит с ними дальше.

2022-04-21 10:15 UTC, nicl-nno commented on fedot/core/pipelines/tuning/tuner_interface.py
> +    not_optimal_target = np.array([[0], [0]])
Ок, я догадался. Но все равно стоит пояснить в комментариях и названиях переменных. Само понятие optimal_target не очень логичное.

2022-04-21 11:06 UTC, gorokhovnik commented on fedot/core/pipelines/tuning/tuner_interface.py
> +    not_optimal_target = np.array([[0], [0]])
Done

2022-04-21 15:15 UTC, Dreamlone reviewed
От себя отмечу, что изменения в самом коде ок, но тесты чет очень долго работают кмк
![image](https://user-images.githubusercontent.com/52418437/164489992-be68cb15-8786-4f97-bc59-0a22db977964.png)

Можно их упростить? Можно например уменьшить количество перебираемых вариантов пайплайнов

2022-04-21 15:16 UTC, nicl-nno commented
https://github.com/nccr-itmo/FEDOT/tree/iss-651-reduced-time

Вот сюда вкинул вариант упрощения.

2022-04-21 20:02 UTC, nicl-nno approved these changes
Время снизилось до 7-8 минут, норм.

2022-04-21 20:26 UTC, merged