Abstract notion of Fitness and unify its usages
nccr-itmo/FEDOT pull request #654
Opened 2022-04-20 12:24 UTC by gkirgizov

- Main purpose is to unify usages of Fitness, giving multi- and single- objective fitness common interface.
- Add `PrioritisedFitness` that generalizes single-objective optimization for the case of secondary quality metrics.
  This will allow to simplify usages of the so-called `supplementary_metrics` in optimisers, completely hiding them.
- This PR also introduces base abstract `Comparable` class, and Fitness inherits from it.

2022-04-20 12:24 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





























* In the file [`fedot/core/utilities/data_structures.py`](https://github.com/nccr-itmo/FEDOT/blob/9361c385cdb8b035e62185b6ca452832fa6b4efb/fedot/core/utilities/data_structures.py):

> [Line 99:38](https://github.com/nccr-itmo/FEDOT/blob/9361c385cdb8b035e62185b6ca452832fa6b4efb/fedot/core/utilities/data_structures.py#L99): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-04-20 13:46 UTC, nicl-nno requested changes

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +    def __init__(self, graph: 'OptGraph', fitness: Fitness = None,  # TODO: fitness field is never set in init here
Действительно параметр fitness выглядит лишним.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +def none_fitness() -> PrioritisedFitness:
Может назвать empty_fitness? Хотя напрямую использовать PrioritisedFitness() тоже будет норм.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +    return PrioritisedFitness(primary_value=value)
А точно эта функция нужна? Мне кажется при условии переименования класса прямое использование будет понятно и так.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +    """Implements lexicographic comparison on one or multiple fitness values.
Не очень понятное описание, ведь lexicographic comparison - это только одна из функций класса.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +class PrioritisedFitness(Fitness):
Может для понятности назвать его SingleObjFitness? Ведь функция secondary_values по судя опциональная.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +    def __init__(self, primary_value: Optional[float] = None, *secondary_values: float):
Может переименовать secondary_values -> supplementary_values?

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
> +    def __init__(self, values: Sequence[Number] = (),
А кто такие wvalues? Вроде в докстроинге не сказано.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +class PrioritisedFitness(Fitness):
Более того - нет ли смысл его унаследовать от MultiObjFitness? Ведь по сути вся разница между ними - этот класс учитывает при сравнении только первый критерий. Причем после записи primary_value и secondary_values все равно уже не считать раздельно.

2022-04-20 13:46 UTC, nicl-nno commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
>      otherwise it is empty (or invalid).
Абстрактные "значения" плохо воспринимаются.
Может разделить понятия objective (как критерии, используемые для построения фитнеса) и value (как значение фитнеса, используемое для сравнения - которое может быть числом или списком)?

2022-04-21 09:44 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +def none_fitness() -> PrioritisedFitness:
С таким, так скажем, синонимом, сразу считывается, что хотели создать неинициализированный фитнесс.
Насчет `empty` -- это слово будто больше относится к чему-то вроде контейнеров, а у fitness семантика значения.
мб `null_fitness` ?

2022-04-21 09:49 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class PrioritisedFitness(Fitness):
Для того как раз и сделал не просто SingleObjFitness -- так как я буду это использовать для рефакторинга оптимизаторов. Так именно такая логика требуется. Просто решил PR-ы поменьше делать.

2022-04-21 09:49 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +def none_fitness() -> PrioritisedFitness:
Ну реализованный фитнес - это и есть своего рода контейнер для objectiv-ов. Но не принципиально, пусть будет null.

2022-04-21 09:52 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class PrioritisedFitness(Fitness):
А, я не так понял. Подумал, что под таким переименованием ты подразумевал, что supplementary не нужны вообще. Да, можно переименовать.

2022-04-21 09:58 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class PrioritisedFitness(Fitness):
Насчет наследования -- не вижу смысла. Особого переиспользования логики нет. Они иначе сравнивают свои значения. Кроме того, SingleObjFitness не нужны веса для метрик.

2022-04-21 10:02 UTC, gkirgizov commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
> +    def __init__(self, values: Sequence[Number] = (),
Добавил описание. Это для более простой десериализации.

2022-04-21 10:22 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +    return PrioritisedFitness(primary_value=value)
согласен

2022-04-21 10:25 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +def none_fitness() -> PrioritisedFitness:
Как бы да, но используем мы фитнесс типа вместо значений float, сравнивая и минимизируя по ним. А это редко относится к контейнерам. Тут логика значений первична. Я это имел ввиду под "семантикой значений".

2022-04-21 10:26 UTC, gkirgizov commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
>      otherwise it is empty (or invalid).
Не уверен, что понял, можешь поподробнее идею описать?

2022-04-21 13:18 UTC, nicl-nno commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
> +class MultiObjFitness(Fitness):
По итогам обсуждаения видимо надо вернуть прошлый вариант с PrioritizedMultiObjFitness - т.к. в реализации класса определен конкретный способ МК-сравения.

2022-04-21 13:18 UTC, nicl-nno commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
>      otherwise it is empty (or invalid).
По итогам обсуждения: предлагаю переименоваоть values в objectives (если именно они и если это не ломает совместимость с deap-ом), остальное оставить как есть.

2022-04-21 13:22 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
Как вариант, можно прямо в базовый класс добавить поле value с типом Any: в нем будет значение фитнеса. Для SO это будет значение основного критерия, для PrioritizedMO - в текущей реализации список критериев, скорректированных с учетов весов, для других реализаций MO - число доминируемых и т.п.

2022-04-21 13:58 UTC, gkirgizov commented on fedot/core/optimisers/fitness/multi_objective_fitness.py
>      otherwise it is empty (or invalid).
поломает таки, deap полагается на `values` property

2022-04-21 14:07 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
Я бы пока это оставил, пока не появится реальный юз-кейс другого вида MultiObjectiveFitness. Хотя бы потому, что на данный момент я вижу наследование для переопределения единственного property избыточным, тогда как вся остальная логика остается той же. Тут правильнее бы что-то вроде внешней функции `reduce_to_single_value(fitness.values)`. Но когда появится другой юз-кейс, тогда станет понятнее, как правильнее абстрагировать.

2022-04-21 14:17 UTC, nicl-nno commented
У меня в run_regression_example в ходе оптимизации иногда выпадает

default() takes 2 positional arguments but 3 were given

Не знаю, в этом ли PR-е дело.

2022-04-21 14:21 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
В данном случае я бы лучше логику визуалзации поменял. Она тут просто ad-hoc на -1 домножает, тут дело не в том, что мы обсуждали, как думаю.

2022-04-21 14:23 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
Но я подумаю еще над этим

2022-04-25 13:22 UTC, gkirgizov commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
Я предлагаю тут оставить просто `f.values[0]`, то есть строить график по первичной метрике.
Мой комментарий насчет юзкейса именно в рамках оптимизации (а не визуализации, что побочная задача) все еще в силе. Когда появится -- вернулся бы к этому вопросу в рамках отдельного Issue. Пока что я просто не очень пойму, как лучше задизайнить всю эту тему для абстрактного юзкейса.

2022-04-25 13:25 UTC, nicl-nno commented on fedot/core/optimisers/fitness/fitness.py
> +class Fitness(Comparable):
Может добавить проперти .value хотя бы SO-фитнеса? Довольно громоздко выглядит везде тянуть этот [0] при в реальность одновретериальной постановке.

2022-04-26 14:05 UTC, Dreamlone commented on fedot/core/optimisers/fitness/__init__.py
> +from .multi_objective_fitness import MultiObjFitness
Спасибо, возьму на заметку

2022-04-26 16:01 UTC, Dreamlone approved these changes
lgtm

2022-04-26 18:10 UTC, nicl-nno approved these changes

2022-04-27 10:11 UTC, merged