Visualization of the operations used in pipelines
nccr-itmo/FEDOT pull request #658
Opened 2022-04-25 13:14 UTC by MorrisNein

Featuring visualization of operations used in evolutionary process.
Changes:
* Added `operation_kde` plot to show operations by generations.
* Added `operation_animated_bar` to show operations by generations with (or without) changing fitness.
* Modified `fitness_box` plot. Now it visually fits the mentioned visuals and supports `pct_best` parameter.

Examples of visuals:
**KDE**
![kde_best_20](https://user-images.githubusercontent.com/57573631/167246213-40de1529-ec6b-49d2-813b-711df48493d0.png)

**Animated barplot**
![_new_test_fitness](https://user-images.githubusercontent.com/57573631/169546825-f050c09b-751f-441a-8dc9-6db9eba49b16.gif)
The same with explicitly hidden fitness:
![_new_test](https://user-images.githubusercontent.com/57573631/169548058-1f70f37f-dc9c-456f-8027-965547f7cfee.gif)

**Modified fitness box**
![fitness_box](https://user-images.githubusercontent.com/57573631/168280099-e41ba46d-1616-48d8-8ab6-96c07d75933d.png)

2022-04-26 11:37 UTC, nicl-nno commented on fedot/core/visualisation/opt_viz.py
> +    def _get_node_tag(self, node: Union[OptNode, str], tags_model: Optional[List[str]] = None,
Может это вынести за рамки визуализатора, в функциональность репозитория?

2022-04-26 16:16 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +    def _get_node_tag(self, node: Union[OptNode, str], tags_model: Optional[List[str]] = None,
В данной конкретной функции захардкожены довольно специфические теги для поиска. Но в остальном - вполне заслуживает вынесения в код репозитория, согласен. Только там дефолтного списка тегов для поиска предоставлять не буду.

2022-05-04 11:41 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +    def _get_node_tag(self, node: Union[OptNode, str], tags_model: Optional[List[str]] = None,
На данном этапе всё-таки [добавил](https://github.com/nccr-itmo/FEDOT/pull/658/files#diff-d44610bae9034915a03fcc43ee3661f957341a13dc1dfd8eefe9610d781752f0R56) дефолтные теги для поиска в класс репозитория.

До этого попробовал инициализировать их в `OptViz`, но это привело к циклическим импортам.

2022-05-04 15:33 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +    def show(self, kind: str = 'fitness_box', save_path_to_file: str = None, n_best: Optional[float] = None):
Кмк понятнее будет type вместо kind.

save_path_to_file нужно поменить как Optional, раз он None. Ну и описать в докстринге.

2022-05-04 15:33 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                return
Тут бы хорошо уведомлять пользоватля.

2022-05-05 10:46 UTC, nicl-nno commented
>(in progress) Added animated bar plot to show operations by generations with changing fitness.

Может это сделать отдельным PR? Вроде в этом уже вполне имеется законченная функциональность.

Единственно - я бы её покрыл хоть каким-то тестом. Например, генерировать картинку в файл и проверять, что он создался.

2022-05-07 07:42 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`fedot/core/visualisation/opt_viz.py`](https://github.com/nccr-itmo/FEDOT/blob/53baf5954bd8801d266451c6a9ebce24ed2bc1fa/fedot/core/visualisation/opt_viz.py):

> [Line 494:121](https://github.com/nccr-itmo/FEDOT/blob/53baf5954bd8801d266451c6a9ebce24ed2bc1fa/fedot/core/visualisation/opt_viz.py#L494): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)

2022-05-07 07:48 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +                return
Добавил исключение с указанием причины

2022-05-07 07:52 UTC, MorrisNein commented
> Может это сделать отдельным PR? Вроде в этом уже вполне имеется законченная функциональность.

Уже успел накатить второй вид графика и унифицировать вид более раннего `fitness_box`. Параметр `n_best` теперь поддерживается всеми тремя визуализациями.

Теперь приглашу ещё ревьюверов и добавлю тесты и пример. А новые фичи оставим для новых PR.

2022-05-07 08:06 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +    def show(self, kind: str = 'fitness_box', save_path_to_file: str = None, n_best: Optional[float] = None):
Назвал `kind`, взяв за пример seaborn, где одноимённый параметр определяет конечный вид визуализации. [Пример](https://seaborn.pydata.org/generated/seaborn.catplot.html). Если с учётом этого всё ещё выглядит неявным, скажи, тогда переименую.

 `save_path_to_file` переименовал в `save_path` (более лаконично и достаточно понятно) и исправил типизацию. Докстринги для новых функций отдельно напишу в ближайших коммитах.

2022-05-11 09:46 UTC, valer1435 requested changes

2022-05-11 09:46 UTC, valer1435 commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["linear", "dimensionality_transforming", "correct_params", "non_applicable_for_ts",
Тут одновременно тире и нижние подчеркивания в названиях. Мб выбрать только нижние подчеркивания?

2022-05-11 09:46 UTC, valer1435 commented on fedot/core/repository/data/data_operation_repository.json
> +				"non-default",
Тут тире

2022-05-11 09:46 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +            if n_best <= 0 or n_best > 1:
n_best - это % лучших? Мб тогда percent_best или что-то такое

2022-05-11 11:49 UTC, aPovidlo requested changes

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/optimisers/opt_history.py
> +                print(f'The history has no fitness data. Fitness is not displayed.')
Выше при отсутствии данных в `all_historical_fitness` вызывается ValueError, а тут вызывается `print`. Может быть как-то в один формат привести или в чем разница в этих двух случаях?

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/optimisers/opt_history.py
> +                print(f'The history has no fitness data. Fitness is not displayed.')
Есть смысл попробовать объединить сообщение об ошибки в одну функцию проверки `all_historical_fitness` и вывода, тк по смыслу сообщения они схожи.

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
А зачем потребовалось добавить данный тэг?

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/repository/data/data_operation_repository.json
> +				"non-default", "data_source"
Мб стоит изменить на `data_sources` чтобы было унифицировано? Или у тэга другой смысл?

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/repository/operation_types_repository.py
> +            return None
Странное положение у `else`.
И я не совсем понимаю что делает данная функция, можешь ли объяснить?

2022-05-11 11:49 UTC, aPovidlo commented on fedot/core/visualisation/opt_viz.py
> +        if n_best is not None:
А в случае `n_best = None` что будет?

2022-05-12 11:31 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +    def show(self, kind: Literal['fitness_box', 'operation_kde', 'operation_animated_barplot'] = 'fitness_box',
Принято, не первая просьба, пусть будет `type`.

2022-05-12 11:37 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +            if n_best <= 0 or n_best > 1:
`pct_best` подойдёт? Вроде общеупотребимое сокращение.

2022-05-12 11:40 UTC, MorrisNein commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["linear", "dimensionality_transforming", "correct_params", "non_applicable_for_ts",
Мы с @mik985, когда расставляли теги, решили использовать так, как они уже имеются, для консистентности. 
Там ещё есть, что пофиксить в репозиториях. Так что наведение порядка в тэгах и в репозиториях решили пока оставить для других PR.

2022-05-12 12:23 UTC, aPovidlo commented on fedot/core/repository/operation_types_repository.py
> +            return None
@MorrisNein название функции, кмк, не в полной мере отражает ее смысл

2022-05-13 07:45 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +            if n_best <= 0 or n_best > 1:
Да, пойдет

2022-05-13 07:45 UTC, valer1435 commented
Вопрос: а мы сейчас можем как-то скачать историю (opt_history.json) и ее визулизировать? Если да, то как?

2022-05-13 08:18 UTC, Dreamlone reviewed
Отмечу на всякий случай, что если цвет в графике не несет какой-либо информации (а в данной анимации это так), то лучше покрасить все элементы однотонно. 
А вообще чем эта анимация отличается от точно такой же, но где цветом показано среднее значение фитнесса?
![image](https://user-images.githubusercontent.com/52418437/168241385-9a56eca0-7696-4544-8c58-a7bd48fbfcc7.png)

2022-05-13 09:36 UTC, MorrisNein commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
> Может быть тут стоит выводить не через `print`, а через соответствующие исключение питона?

Укажи на строчку, пожалуйста.

2022-05-13 09:39 UTC, MorrisNein commented
> А вообще чем эта анимация отличается от точно такой же, но где цветом показано среднее значение фитнесса?

Мб где-то понадобится вариант попроще, без фитнеса. Отличается действительно только отсутствием цветовой шкалы.

2022-05-13 09:45 UTC, MorrisNein commented
> Может быть тут стоит выводить не через print, а через соответствующие исключение питона?

Не понял, про какое ты место. Там сейчас принты везде, где не нужно выбрасывать исключение, и код должен продолжить работу. Мб я что-то упустил

2022-05-13 10:32 UTC, Dreamlone commented
> Мб где-то понадобится вариант попроще, без фитнеса. Отличается действительно только отсутствием цветовой шкалы.

Думаю это какой-то очень маргинальный случай) Лучше бы всегда отрисовывать цветом фитнесс, по крайней мере, по умолчанию

2022-05-13 10:35 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
Мы действительно ввели дополнительные теги, чтобы проще было строить визуализацию. У нас с тегами и правда немного запутанно получается, но как и сказал Петр, тут введение тегов было уместно. Хотя бы потому что помогает сгруппировать похожие операции таким образом как мы хотим

2022-05-13 10:45 UTC, MorrisNein commented
> Вопрос: а мы сейчас можем как-то скачать историю (opt_history.json) и ее визулизировать? Если да, то как?

```
history = OptHistory.load(history_path)
history.show(plot_type='...')
```

Вот две готовых истории [поменьше](https://drive.google.com/file/d/1GflG9N8i-IdZ19XCOHmKPCCguGh3bykx/view?usp=sharing) и [побольше](https://drive.google.com/file/d/1I6Fbl-WcHx8ro50ykoCGpnkR4NvxrLef/view?usp=sharing).

Только не забудь запулить последние изменения в ветке.

2022-05-13 10:47 UTC, MorrisNein commented
> Лучше бы всегда отрисовывать цветом фитнесс, по крайней мере, по умолчанию.

Так и делается, если обратное не указано явно.

2022-05-13 10:53 UTC, aPovidlo requested changes

2022-05-13 10:53 UTC, aPovidlo commented on fedot/core/visualisation/opt_viz.py
> +            raise ValueError('`save_path` should be set to save the animation.')
Поменял бы у данного `raise` сообщение на TypeError: visualize_operations_animated_barplot() missing 1 required positional argument: 'save_path'. Может быть @nicl-nno или @Dreamlone меня поправят, потому что немного сомневаюсь с выбором `TypeError`. Аналогично и в других местах функций, где есть `save_path`.

2022-05-13 10:53 UTC, aPovidlo commented on fedot/core/optimisers/opt_history.py
> +                    f'Visualization "{plot_type}" is not supported. Possible values: '
Поменял бы **Possible values** на **Expecting values**

2022-05-13 11:07 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +            print(f'`hide_fitness` parameter is not supported for "{plot_type.name}". It is ignored.')
Тут можно заменить на warning, потому что это ничего не сломает. Или думаешь, что лучше выбрасывать исключение?

2022-05-13 11:11 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +            raise ValueError('`save_path` should be set to save the animation.')
Два нюанса
1. Вызывая history.show(), юзер не видит спрятанные внутри функции. Могу сделать такое сообщение здесь, но добавить ещё одну проверку с понятным сообщением на уровень выше.
2. В других местах это не нужно, так как только для этой визуализации параметр обязательный.

2022-05-13 11:21 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +            raise ValueError('`save_path` should be set to save the animation.')
Проверка оказалась избыточной, убрал её совсем. Это ведь и так обязательный параметр для функции `visualize_operations_animated_barplot`.

2022-05-13 12:17 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +            raise ValueError('`save_path` should be set to save the animation.')
Вернее, отправил [сюда](https://github.com/nccr-itmo/FEDOT/blob/db6f281543528b5ea5c3d25cc512c79a7bc31ee4/fedot/core/optimisers/opt_history.py#L179), и чуть формализовал текст.

2022-05-13 12:23 UTC, aPovidlo commented on fedot/core/optimisers/opt_history.py
> +            print(f'`hide_fitness` parameter is not supported for "{plot_type.name}". It is ignored.')
@MorrisNein warning думаю будет лучше

2022-05-13 12:28 UTC, MorrisNein commented
@Dreamlone, заменил цвета, см. примеры.

2022-05-13 14:48 UTC, MorrisNein commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
@Dreamlone, мой вопрос был скорее о корректных названиях для обеих операций и тегов для них.
Что я вижу в [sklearn_transformations.py](https://github.com/nccr-itmo/FEDOT/blob/e9cba8b7cb51df881442278e03f91e2dacdb4b32/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py):

- Для `ScalingImplementation` используется `sklearn.preprocessing.StandardScaler`.
- Для `NormalizationImplementation` используется `sklearn.preprocessing.MinMaxScaler`.

Наверное, при таком раскладе тег `scaling` вполне корректен, разве что можно сделать его `feature_scaling`, чтобы он не путался с операцией.

2022-05-13 15:00 UTC, Dreamlone commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
Да, вполне согласен с твоими аргументами, пусть будет `feature_scaling`

2022-05-13 15:49 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +            print(f'`hide_fitness` parameter is not supported for "{plot_type.name}". It is ignored.')
Теперь это warnings, указывающие на место вызова `history.show()`.

2022-05-13 16:19 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +                    f'Visualization "{plot_type}" is not supported. Possible values: '
Так и сделал.

2022-05-13 16:20 UTC, MorrisNein commented on fedot/core/repository/data/data_operation_repository.json
> +			"tags": ["simple", "scaling"]
Готово.

2022-05-16 13:46 UTC, nicl-nno approved these changes

2022-05-17 07:42 UTC, Dreamlone reviewed
Сделай плиз пример в examples как можно генерировать все возможные картинки и анимации, которые были сделаны в этом PR. Всё в одном .py файле

2022-05-18 06:01 UTC, valer1435 approved these changes
Вкину небольшое TODO на будущее - было бы неплохо уметь агрегировать данные нескольких историй для визуализации, но уже в другом PR

2022-05-18 21:19 UTC, SuperSashka commented on fedot/core/optimisers/opt_history.py
> +                    f'Visualization "{plot_type}" is not supported. Possible values: '
Поменял бы **Expecting values** на **Expected values**

2022-05-19 10:35 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
> +                    f'Visualization "{plot_type}" is not supported. Possible values: '
@SuperSashka, окей, босс)
Так действительно грамотнее, но что-то заставило в этом усомниться с самого начала. Что-то хтоническое и трансцендентное, не иначе.

2022-05-20 09:28 UTC, aPovidlo approved these changes

2022-05-20 14:41 UTC, merged