generalized `ensure_list` to `ensure_sequence`
nccr-itmo/FEDOT pull request #661
Opened 2022-04-29 09:33 UTC by IIaKyJIuH

+ input sequence type prevention
+ optional sequence convertion type

2022-04-29 09:37 UTC, nicl-nno commented on fedot/core/utilities/data_structures.py
> +        if isinstance(obj, str):
А в каком случае obj - это одновременно и Sequence, и str?

2022-04-29 09:39 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +        if isinstance(obj, str):
Это возможно, когда передаётся `metric_names`.
`Sequence` вообще это и str, и list, и tuple, и может что-то ещё...всё, что по чему можно итерироваться несколько раз, брать конкретные элементы, узнавать длину.
`Iterable` - просто "одноразовый" проход и всё.

2022-04-29 09:59 UTC, nicl-nno commented on fedot/core/utilities/data_structures.py
> +        if isinstance(obj, str):
Ага, понял.

2022-04-29 10:02 UTC, nicl-nno approved these changes
Можно ещё небольшой тест добавить, раз внутри функции появилось несколько условий.

2022-04-29 10:04 UTC, gkirgizov requested changes

2022-04-29 10:04 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +    return sequence_type([obj])
same, не пойму зачем такое создание нужно. Разве что, видимо, sequence_type *обычно* принимает Iterable, и ты его тут искуственно создаешь, но чтобы тут же отбросить.
Вообще, реально ли нам нужно специфицировать тип Sequence хоть где-либо? Может, просто immutable tuple возвращать да и все?
Иногда лучше не пере-абстрагировать без нужды )

2022-04-29 10:04 UTC, gkirgizov commented on fedot/core/validation/metric_estimation.py
> +    for metric in ensure_sequence(metrics):
тут у нас вроде как typehint в функции говорит, что принимает и так sequence. нужен ли тут этот метод? может лучше не внутри функции это делать, а при вызове, где реально возникает нужда?
Мне в целом не нравится, что эта функция раскидана где-то уже глубоко в ядре. Я могу понять, что нам на входе в API полезно обработать случай *один или много*, но к этому моменту уже мы должны быть уверены, что у нас последовательность везде передается.

2022-04-29 14:05 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +def ensure_sequence(obj: Union[T, Iterable[T], Sequence[T]], sequence_type: Type[List[T]] = list) -> Sequence[T]:
Насчёт `sequence_type` ты прав.
1-2. Не соглашусь, потому что эта функция никогда не намеревалась возвращать объект, по которому можно проитерироваться всего лишь один раз, даже сейчас в мастере есть пару мест, где требуется именно список (что было изначальной семантикой). 
Любой `Sequence` вообще говоря и `Iterable`, но лучше указывать явно, что может прийти, потому что внутри функции есть проверки как раз на вид итерируемого объекта

2022-04-29 14:11 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +            return sequence_type([obj])
Эта ветка нужна тогда, когда приходит `str`, а он является `Sequence`
...
Приходит в метод метрика `rmse`, без этого специфичного случая мы получим итерируемый `r`, `m`, `s`, `e`, а нам нужно получить `seq_type(['rmse'])`, без квадратных скобок мы снова получим то, что нас не устраивает, нам нужен именно "массив" c этой метрикой, но определённого типа, который по умолчанию - list

2022-04-29 14:14 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +            return sequence_type([obj])
Вот [тут](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/api/main.py#L308) может возникнуть проблема, не вижу ничего плохого в том, что она теперь решается внутри `ensure_sequence`, потому что в этом и был смысл обобщения функции

2022-04-29 15:02 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +T = TypeVar('T')  # TODO: make more general, not just for `ensure_sequence` method
То есть вот ты, например, создал `T` тип в `operator.py`, который тоже является "общим", возможно, есть смысл разместить один где-нибудь, чтобы потом можно было просто импортить, с другой стороны, когда он перед глазами создаётся, тоже понятнее, что скажете?

2022-04-29 15:12 UTC, nicl-nno commented on fedot/core/utilities/data_structures.py
> +T = TypeVar('T')  # TODO: make more general, not just for `ensure_sequence` method
А в чем практическая разница между TypeVar('T') и Any при использовании в аннотациях? Второе выглядит понятней кмк.

2022-04-29 15:13 UTC, IIaKyJIuH commented on fedot/core/validation/metric_estimation.py
> +    for metric in ensure_sequence(metrics):
Тут согласен, [поправил](https://github.com/nccr-itmo/FEDOT/pull/661/commits/1502271e1aab6c8f4003e042351abc1aeb306612#diff-5f3aacdff9a5c6b78565d3508eb9c4ae5a67b8987147439a22bbf3dba080a67d)

2022-04-29 15:27 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +T = TypeVar('T')  # TODO: make more general, not just for `ensure_sequence` method
Очень хороший вопрос!

Кажется, что без ограничений на TypeVar и в контексте данной функции, разницы вообще нет

2022-04-29 15:32 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +def ensure_sequence(obj: Union[T, Iterable[T], Sequence[T]], sequence_type: Type[List[T]] = list) -> Sequence[T]:
Записал `sequence_type` вообще в [таком виде](https://github.com/nccr-itmo/FEDOT/pull/661/files#diff-e95245fccd16b1163bb9fdcfe645cf62a1f014669c7a83e01742edcd72c9efffR70), потому что иначе pycharm намекает, что-то не так.

2022-05-04 10:28 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +def ensure_sequence(obj: Union[T, Iterable[T], Sequence[T]], sequence_type: Type[List[T]] = list) -> Sequence[T]:
В таком случае `sequence_type` лучше переименовать `sequence_factory` чтобы имя соответствовало типовой сигнатуре

2022-05-04 10:29 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +def ensure_sequence(obj: Union[T, Iterable[T], Sequence[T]], sequence_type: Type[List[T]] = list) -> Sequence[T]:
насчет 1-2 ок, убедил

2022-05-04 10:39 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +            return sequence_type([obj])
Обобщение нужно тогда, когда у нас хотя бы несколько использований. Данная же функциональность неочевидна -- почему абстрактная функция, которая заявляет что просто удостоверяется в том, что sequence -- это sequence, должна обрабатывать строки по-особому? Кроме того, все другие использования получают лишний `if` из-за одного конкретного usage. 

Теперь, после объяснения пониманию конкретное использование. Но если я о нем не знаю, то я бы очень удивился, передав в эту функцию строку и получив что-то такое. Пришлось бы лезть в реализацию. Не самое оправданное обобщение, на мой взгляд. Оно только скрывает логику и вызывает вопросы.

2022-05-04 10:40 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +    return sequence_type([obj])
return (obj,)

2022-05-04 14:53 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +            return sequence_type([obj])
Поменял название на `ensure_wrapped_in_sequence`, подходит семантически под логику?

2022-05-04 14:54 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +def ensure_sequence(obj: Union[T, Iterable[T], Sequence[T]], sequence_type: Type[List[T]] = list) -> Sequence[T]:
Переименовал параметр с типом-конвертером: [коммит](https://github.com/nccr-itmo/FEDOT/pull/661/commits/bcacf2a9fa2f4a01d10ffebada23199c463d65b6#diff-e95245fccd16b1163bb9fdcfe645cf62a1f014669c7a83e01742edcd72c9efffR74)

2022-05-04 15:03 UTC, IIaKyJIuH commented
> Можно ещё небольшой тест добавить, раз внутри функции появилось несколько условий.

Теперь есть: [test_utils.py](https://github.com/nccr-itmo/FEDOT/pull/661/files#diff-f8892f46b18e3f8c42e6ca94750dae62f678c1cdfee66955aa713d2a59b27ba6R56-R69)

2022-05-04 15:42 UTC, nicl-nno approved these changes

2022-05-05 07:58 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +    return sequence_type([obj])
ок, только если у нас not str but Iterable, то мы дважды проверяем одно условие `isinstance(obj, collections.abc.Iterable)`

2022-05-05 07:59 UTC, gkirgizov commented on fedot/core/utilities/data_structures.py
> +    return sequence_type([obj])
Я могу быть придирчив, но всегда по поводу, на самом деле. Просто текстом сложно бывает объяснить свою линию мысли. Я переспал с этим PR, так сказать. и сейчас так могу сформулировать: я в целом считаю эту абстракцию ill-defined, так как она пытается несколько разнородных случаев объединить: (а) создание списка `ensure_mutable_list` (б) удостовериться что можем проитерироваться, т.е. `ensure_iterable` (в) обернуть конкретно строковые объекты в список, т.е. `ensure_string_list`.

Я бы поступил так: оставил просто `ensure_iterable`, а остальные случаи обработал ad-hoc в местах использования. Но не хочу больше ничье время тратить на этот небольшой кусочек кода (и так over-потратили время) — так что оставляй текущее решение, если считаешь нужным и оно помогает тебе в коде.

2022-05-05 08:01 UTC, gkirgizov approved these changes
Я могу быть придирчив, но всегда по поводу, на самом деле. Просто текстом сложно бывает объяснить свою линию мысли. Я переспал с этим PR, так сказать. и сейчас так могу сформулировать: я в целом считаю эту абстракцию ill-defined, так как она пытается несколько разнородных случаев объединить: (а) создание списка ensure_mutable_list (б) удостовериться что можем проитерироваться, т.е. ensure_iterable (в) обернуть конкретно строковые объекты в список, т.е. ensure_string_list.

Я бы поступил так: оставил просто ensure_iterable, а остальные случаи обработал ad-hoc в местах использования. Но не хочу больше ничье время тратить на этот небольшой кусочек кода (и так over-потратили время) — так что оставляй текущее решение, если считаешь нужным и оно помогает тебе в коде.

2022-05-05 09:28 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +    return sequence_type([obj])
[Пофиксил](https://github.com/nccr-itmo/FEDOT/pull/661/commits/243b2fb065757a346dac23f9eab8f6268e203808#diff-e95245fccd16b1163bb9fdcfe645cf62a1f014669c7a83e01742edcd72c9efffR78) + учёл, что иногда мы хотим возвращать последовательность другого типа

2022-05-05 09:33 UTC, IIaKyJIuH commented on fedot/core/utilities/data_structures.py
> +T = TypeVar('T')  # TODO: make more general, not just for `ensure_sequence` method
На самом деле, был не прав тут, в `vs code` без TypeVar некорректно определяются типы в последовательностях, в общем, всё-таки оставил)

2022-05-05 09:35 UTC, merged