Refactor improvement checking and adaptive population size in GP Optimisers
nccr-itmo/FEDOT pull request #662
Opened 2022-04-29 13:38 UTC by gkirgizov

Primary changes:
- Introduce GenerationKeeper:
  It encapsulates watching improvements/stagnation and keeping best individuals through generations 
- Drop usages of supplementary metrics in optimisers:
  In favor of using compound SingleObjFitness with supplementary metrics.
- Encapsulate dynamic parameter of next offspring size in AdaptiveParameter.
  This simplifies main optimiser loop a lot, allowing to drop many variables with duplicate functionality,
  thanks to combination of GenerationKeeper and Fitness. See `AdaptivePopulationSize` class.
- Other minor code refactorings (notably dropping custom ParetoFront subclass as it doesn't really override any functionality)

Important notes on changes in API:
- Now if only 1 metric is provided, additional default complexity metric is appended to `metrics`
  The appended metric is the previously used and scattered in Optimisers supplementary metric,
  which is used for distinguishing individuals with equal fitness.
  See usages of `ComposerBuilder._default_complexity_metrics()`

This PR is a part of big refactoring #608

2022-04-29 13:38 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



















* In the file [`fedot/core/optimisers/gp_comp/gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/blob/ac45c0b3d2b97ca51937b9dbb0659bb3ab330f71/fedot/core/optimisers/gp_comp/gp_optimiser.py):

> [Line 239:121](https://github.com/nccr-itmo/FEDOT/blob/ac45c0b3d2b97ca51937b9dbb0659bb3ab330f71/fedot/core/optimisers/gp_comp/gp_optimiser.py#L239): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)









* In the file [`fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/blob/ac45c0b3d2b97ca51937b9dbb0659bb3ab330f71/fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py):

> [Line 94:121](https://github.com/nccr-itmo/FEDOT/blob/ac45c0b3d2b97ca51937b9dbb0659bb3ab330f71/fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py#L94): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (124 > 120 characters)

2022-04-29 14:52 UTC, nicl-nno requested changes

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/composite_condition.py
> +class CompositeCondition:
Мне кажется лучше не использовать понятие Composite, чтобы не было путаницы с composite pipelines/composer и т.п

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/composite_condition.py
> +from typing import Optional, List, Callable, Tuple, Iterable
Может вынести этот скрипт в другой модуль? Он же ничего специфичного для optimisers.

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        self._generation_num = -1  # -1 means no generations
Может лучше None?

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +    def stagnation_length(self) -> int:
stagnation_duration мб?

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +    def last_improved(self) -> bool:
Тут нужен или комментарий, или другое название (is_any_improvement?) - непонятно почему last_improved это bool.

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        return self._metrics_improvement.get(metric, False)
А это где-то используется?

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +    def quality_improved(self) -> bool:
Может для единнообразция использовать везде нотацию с is?

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/operator.py
> +
Может этот скрипт тогда переименовать в base.py или как-то так? Вроде новый класс не имеет отшноения к операторам.

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                    # TODO: feels unneeded, ParetoFront does it anyway
Можно попробовать проверить, временно добавив экспешен в случае дубликата.

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
>                          new_population += self.reproduce(ind_1, ind_2)
Может это вынести в метод базового класса, чтобы не дублировать?

2022-04-29 14:52 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
> +        pass
В целом можно его реализовать - достаточно полезно иметь возможность узнать, срабатывал ли критерий останова.

2022-05-04 11:30 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        self._generation_num = -1  # -1 means no generations
Нет, это счетчик, он потом просто инкрементится

2022-05-04 11:30 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +    def stagnation_length(self) -> int:
Тоже раздумывал, length не нравилось. Можно и duration

2022-05-04 11:37 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        return self._metrics_improvement.get(metric, False)
Нет, но можно представить случай, где какой-нибудь реализации лагоритма нужно првоерять особую метрику помимо в целом сложности или качества. Логике класса этот метод соответствует, не вижу в нем проблемы

2022-05-04 11:41 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/operator.py
> +
Ты про класс `Operator`? А то я тут с ним ничего в данном PR не менял.
Может, он и абсатрктен, но как раз к оператором и только в ним он и относится. Это в следующих PR, когда сами операторы отрефакторю, станет видно. Пока что это заготовка.

2022-05-04 11:42 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                    # TODO: feels unneeded, ParetoFront does it anyway
Ага, проверю и отрефакторю, когда доберусь до операторов. Я разделяю PR на отдельные, но TODO оставляю, чтобы не забыть.

2022-05-04 11:43 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
>                          new_population += self.reproduce(ind_1, ind_2)
Оставлю это на PR когда уже эво операторы буду менять.

2022-05-04 11:45 UTC, gkirgizov commented on fedot/core/optimisers/optimizer.py
> +        pass
Это нигде не используется, потому как раз и убираю. В грядущем PR я это, кажется, уже совсем дропнул.

2022-05-04 11:46 UTC, gkirgizov commented on fedot/core/optimisers/optimizer.py
> +        pass
То есть не очень понятно, зачем это может быть нужно снаружи, а внутри алгоритм это и так знает. Если будет нужно -- то можно будет отдельно сделать, а так я интерфейс Оптимизатора чищу.

2022-05-04 11:48 UTC, gkirgizov commented on examples/advanced/multiobj_optimisation.py
> +                                                       show=True)
в API чьем?

2022-05-04 12:47 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/operator.py
> +
Нет, я по класс AdaptiveParameter(ABC, Generic[T]), который в скрипте operator.py

2022-05-04 12:50 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        self._generation_num = -1  # -1 means no generations
Тогда хотя бы комментарий скорректировать в стиле # -1 means state before initial generation

2022-05-04 12:53 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/generation_keeper.py
> +        return self._metrics_improvement.get(metric, False)
Ок. 

Но стоит пояснить докстрингами - разницу между metric_improved и _is_metric_kind_improved сходу понять было сложно.

2022-05-04 12:56 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
> +        pass
Сообщение о том что "Early stopping criteria was triggered and composing finished" выводить было бы полезно - чтобы пользователь знал, закончилась ли оптимизация досрочно. Но действительно можно это делать за рамками этого метода.

2022-05-04 12:59 UTC, nicl-nno commented on examples/advanced/multiobj_optimisation.py
> +                                                       show=True)
Тут под API имеется в виду верхнеуровневый пользовательский интерфейс https://github.com/nccr-itmo/FEDOT/tree/master/fedot/api.

Т.е. чтобы было какой-то аналог auto_model.best_models.show(), используя которое не требуется вдаваться в детали реализации.

2022-05-04 13:36 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                    # TODO: feels unneeded, ParetoFront does it anyway
Возник вопрос:
1) а почему эта фильтрация только для multi_objective?
2) фактически, это у нас условие элитизма, то есть мы добавляем всех лучших, причем в любом случае.

Эта ветка кажется ненужной вообще в таком случае. Что думаешь?

2022-05-04 13:44 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/operator.py
> +
Понял. Лучше тогда вынесу этот класс в свой модуль вместе с `popoulation_size.py`

2022-05-05 08:17 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +                    # TODO: feels unneeded, ParetoFront does it anyway
Ок, давай попробуем убрать. В целом действительно, если и удалять дубликаты - то логично это делать по генотипу. 

Мб это какой-то workaround и старая реализация multi_objective падала когда фитнес повторялся.

2022-05-13 08:32 UTC, nicl-nno approved these changes
Только тесты починить.

2022-05-13 08:51 UTC, MorrisNein commented on fedot/api/api_utils/params.py
> +        self.metric_name = self.metric_name or self.get_default_metric(problem)
Возможно, это уже было в дискуссии, но на какой случай эта заглушка? Если правильно понимаю стек вызова:

Fedot.__init__ -> self.params.initialize_params -> get_initial_params -> _parse_input_params. Т.е. в нынешнем варианте они всегда None на этой строке.

2022-05-13 08:53 UTC, MorrisNein commented on fedot/api/main.py
> +        self.best_models: Optional[HallOfFame] = None
Здесь типизация выбивается из общей картины. Можем ли задать типизацию и для других параметров?

2022-05-13 09:16 UTC, MorrisNein requested changes

2022-05-13 09:16 UTC, MorrisNein commented on fedot/core/utilities/aggregate_condition.py
> +class AggregateCondition:
Это группа из условий поменьше, судя по докстрингу?
Название `AggregateCondition` выглядит неявным. Дословно можно перевести как агрегатное состояние. Может, `ComplexCondition` подойдёт лучше? И ещё в докстринге остался старый вариант `CompositeCondition`.

2022-05-13 09:16 UTC, MorrisNein commented on test/unit/optimizer/test_generation_keeper.py
> +    archive.append(population1())
Тут снова по именованиям, в Федоте принято использовать имена переменных по типу `population_1`, `population_2`. Да и читается лучше в целом. Меня уже поправляли по этому поводу, передаю эстафету)

2022-05-13 09:20 UTC, MorrisNein commented on fedot/core/utilities/aggregate_condition.py
> +class AggregateCondition:
Ещё вариант `ConditionsGroup`, как наиболее явный

2022-05-13 09:20 UTC, maypink approved these changes

2022-05-13 09:22 UTC, Dreamlone approved these changes

2022-05-13 09:22 UTC, Dreamlone commented on fedot/core/composer/composer_builder.py
> +        return [ComplexityMetricsEnum.node_num]
Не до конца уверен, но просто выскажу свою мысль. Насколько мне известно, где-то в недрах оптимизации есть механизм регуляризации, который отвечает примерно за то же самое, что и данная метрика - он не позволяет пайплайну разрастаться. Не приведёт ли такое "двойное воздействие" со сторону дополнительной метрики, штрафующей за сложность и нативной регуляризации к тому, что FEDOT перестанет выращивать сколько-нибудь крупные пайплайны?

2022-05-16 10:25 UTC, gkirgizov commented on fedot/core/composer/composer_builder.py
> +        return [ComplexityMetricsEnum.node_num]
Не должно привести к этому.
1. Эта метрика не столько штрафует, сколько позволяет выбирать более простую модель среди одинаково эффективных (по первой метрике) моделей. То есть эта метирка используется в `SingleObjFitness` просто как `supplementary metric`. 
2. Эта логика не нова -- эта вторая метрика как бы "вручную" добавлялась внутри эволюционных оптимизаторов. Тут я просто вынес ее на уровень композера и сделал ее явной.

2022-05-16 10:46 UTC, Dreamlone commented on fedot/core/composer/composer_builder.py
> +        return [ComplexityMetricsEnum.node_num]
Принял, вопрос снят

2022-05-16 10:49 UTC, gkirgizov commented on test/unit/optimizer/test_generation_keeper.py
> +    archive.append(population1())
эстафету принял

2022-05-16 11:20 UTC, gkirgizov commented on fedot/api/api_utils/params.py
> +        self.metric_name = self.metric_name or self.get_default_metric(problem)
Ты прав, а я уже забыл, чем руководствовался, когда добавил это. Откачу эту строчку.

2022-05-17 09:56 UTC, merged