Issue 659 bug fixed, minor fix for visualization
nccr-itmo/FEDOT pull request #669
Opened 2022-05-02 13:54 UTC by ChrisLisbon

**Metric evaluation error: can't set attribute** - setter to target of MultiModalData added.
**plot_prediction** - fedot.plot_prediction target argument for MultiModalData added.

2022-05-02 15:09 UTC, nicl-nno commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
А что тут проверяется для таргета? Для этого нет уже существующнй функции?

2022-05-02 15:09 UTC, nicl-nno commented on fedot/core/data/visualisation.py
> +    if type(data) == MultiModalData:
Лучше isinstanceof

2022-05-02 16:00 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
target это просто строка, которую я прокинула в аргументы plot_prediction, если она не задана, то мы не знаем какой из рядов MultiModalData отрисовывать и все валится. А так он ищет соответствия по имени ряда

2022-05-02 16:35 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +    if type(data) == MultiModalData:
[Поправила](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-85e5ddaa031f25770daaab7a55a176fc2fe31cdeb3e3025496558efd1190c511R18)

2022-05-02 19:38 UTC, nicl-nno commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
Ну вот кмкэтот разбор строки таргета со / лучше куда-то вынести и снабдить. Явно ещё пригодится где-то.

2022-05-03 08:01 UTC, valer1435 requested changes

2022-05-03 08:01 UTC, valer1435 commented on fedot/core/data/visualisation.py
> +    :param target: name of target variable for MultiModalData
Если мы храним таргет в классе MultiModalData, то зачем прокидывать лишний раз таргет?

2022-05-06 09:38 UTC, ChrisLisbon commented on fedot/api/main.py
> +    def plot_prediction(self, target: [Optional] = None):
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR269)

2022-05-06 09:41 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +    :param target: name of target variable for MultiModalData
В качестве таргета в MultiModalData есть просто сам ряд (array), для отрисовки нам нужно обратиться к одному из InputData, который содержит непосредственно нужную переменную, а не вспомогательные. Поэтому target здесь это строка с пользовательским названием, которое дали InputData при оборачивании в MultiModalData

2022-05-06 09:42 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
[Вынесла](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-85e5ddaa031f25770daaab7a55a176fc2fe31cdeb3e3025496558efd1190c511R51-R60) в тот же файл. Оставить тут или может переместить в класс MultiModalData ?

2022-05-06 09:48 UTC, nicl-nno commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
Если метод универсальный, то лучше перенести. И стоит указать, что именно возвращается из get_target_for_multi_modal_data.

Но всё ещё не очень понятно, почему вот этотго свойства недостаточно?
![image](https://user-images.githubusercontent.com/5711814/167108527-035012c5-9ca5-4e69-8653-650cee74b76c.png)

Мб по факту ищется не target, а просто один из фрагментов данных и надо назвать в стиле get_data_part?

2022-05-06 10:00 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
Просто для визуализации нам нужен вот такой [полноценный ряд](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-85e5ddaa031f25770daaab7a55a176fc2fe31cdeb3e3025496558efd1190c511R22), а посчитать его мы не можем, так как data.features отсутствует потому что у нас несколько рядов в виде фич (картинка) и чтобы это полноценный ряд собрать (и не нарушать логику plot_forecast для других типов данных) приходится обращаться к ключу словаря 
![image](https://user-images.githubusercontent.com/44952202/167110699-f1a0566c-f6ca-49da-8e8a-154fa31d541a.png)

2022-05-06 10:04 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
[Вынесла](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-92a862192777de2d5abf87b8f3d3970c5100e86e6d08d816b33c5f983ea0eadbR65-R74) в класс

2022-05-06 10:11 UTC, ChrisLisbon commented on fedot/core/data/visualisation.py
> +        data = data[[key for key, val in data.items() if target == key.split('/')[-1]][0]]
Да, касательно MultiModalData  это и правда data_source, [переименовала](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-92a862192777de2d5abf87b8f3d3970c5100e86e6d08d816b33c5f983ea0eadbR65). Но для визуализации все же ряд помечен как target, об этом и [комментарии](https://github.com/nccr-itmo/FEDOT/pull/669/files#diff-0873e7e185c9d0abc859724221465dac4c95db9648356a7f01bc0b629b99b8e2R41) говорят

2022-05-06 11:22 UTC, valer1435 approved these changes

2022-05-06 12:36 UTC, merged