Added params preprocessing SkLearnEvaluationStrategy.fit
nccr-itmo/FEDOT pull request #672
Opened 2022-05-03 21:11 UTC by gorokhovnik

1. Added integer converting
2. Added share from n_samples converting

2022-05-03 21:15 UTC, nicl-nno commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    share_params = {
А что тут имеется в виду под share?

2022-05-03 22:25 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    share_params = {
Переименовал. Тесты в test_pipeline_tuner_with_custom_search_space в том числе это проверяют. Не совсем юнит, конечно, но ошибки не допустит

2022-05-03 22:50 UTC, gorokhovnik commented
![image](https://user-images.githubusercontent.com/45238581/166585663-34bc5a73-369d-4308-afd3-0e37ac10289b.png)
Однажды Эрнест Хэммингуэй поспорил...

2022-05-04 07:24 UTC, Dreamlone requested changes
Может тогда сразу в рамках этого PR'а исправить [словарь с пространством поиска](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/pipelines/tuning/search_space.py#L21)? Ну то есть заменить где считаешь полезным hp.choice на hp.uniform

2022-05-04 07:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        'min_data_in_leaf', 'min_data_per_leaf', 'min_data', 'min_child_samples', 'min_samples_leaf'
Ещё отмечу, что мне кажется данный способ корректировки не очень надежным хотя бы потому что в `SkLearnEvaluationStrategy` запрятано очень много разных реализаций моделей. Какова гарантия, что `min_samples_leaf` в Random Forest и Extra Trees будет по одинаковому обрабатываться / восприниматься, скажем, в какой-нибудь новой модели от Sklearn'а.

Я бы предложил сделать что-то вроде: Вынести проверку на уровень повыше (например на уровень Operation) и разбить все вышеперечисленные списки на пары "ключ - значение", где ключом будет выступать название операции, а списком названия гиперпараметров. Хранить этот относительно большой словарь можно в json файле.

2022-05-04 07:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +            params[param] = int(params[param])
Может тут лучше `round`?

2022-05-04 07:29 UTC, nicl-nno commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        'min_data_in_leaf', 'min_data_per_leaf', 'min_data', 'min_child_samples', 'min_samples_leaf'
Тут ещё возможный нюанс в том, что в теории название операции может сооветствовать нескольким реализациям (например, CPU/GPU). Поэтому к такому словарю надо будет предосмотреть и механизм переопределения части его значений.

2022-05-04 07:36 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +        'min_data_in_leaf', 'min_data_per_leaf', 'min_data', 'min_child_samples', 'min_samples_leaf'
Тогда можно просто метакласс в таком словаре использовать, то есть держать как в [model_repository.json](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/repository/data/model_repository.json), по нему стратегия должна однозначно определяться

2022-05-04 08:51 UTC, gorokhovnik commented
@Dreamlone про словарь с пространством поиска: я сейчас как раз занимаюсь тем, чтобы подобрать пространства поиска под supervised алгоритмы (ветка hyperparameters_set_optimization). Могу поменять совсем странные чойсы, но там и раньше можно было рандинт вставить

2022-05-04 08:54 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +            params[param] = int(params[param])
round флоаты ретернит, насколько я знаю, вряд ли это где-то выстрелит, но так надежнее имхо

2022-05-04 08:55 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    integer_params = {
Предложения по неймингу принимаются

2022-05-04 08:56 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    integer_params = {
Общее название было выбрано преднамерено, чтобы потом можно было разные обработчики в эту функцию добавлять, типа защиты от дурака с указанием отрицательных значений параметров

2022-05-04 08:59 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    integer_params = {
докстрингу добавил

2022-05-04 09:21 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +            params[param] = int(params[param])
`round` без аргументов начиная с Python 3.6 (вроде) возвращает тип int. Можешь чекнуть

2022-05-04 09:23 UTC, Dreamlone commented
> @Dreamlone про словарь с пространством поиска: я сейчас как раз занимаюсь тем, чтобы подобрать пространства поиска под supervised алгоритмы (ветка hyperparameters_set_optimization). Могу поменять совсем странные чойсы, но там и раньше можно было рандинт вставить

Да, думаю вполне можно изменить некоторые значения гиперпараметров.  Иногда и правда встречаются довольно странные вещи

2022-05-04 09:29 UTC, Dreamlone commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    integer_params = {
Если хочешь придумывать расширяемую конструкцию, то стоит реализовать в виде отдельного класса, в котором в главном методе `correct` вызываются приватные (у нас же тут ООП парадигма). Тогда если хочется добавить доп. проверку, то просто добавляешь метод, а не модифицируешь уже существующую функцию. А если пишешь функцию, то стоит наоборот делать её максимально прозрачной и, пожалуй, специализированной. При этом такую специализацию стоит отразить в названии. 

Ну это моё субъективное мнение, Коля, например, может что-то другое посоветовать. Или можешь сам привести аргументы в пользу текущей реализации. Нынешние меня пока не переубедили

2022-05-04 09:51 UTC, gorokhovnik commented
@Dreamlone заменил choice на более подходящие распределения, там, где он совсем плохо выглядел

2022-05-04 21:00 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +            params[param] = int(params[param])
Done

2022-05-04 21:01 UTC, gorokhovnik commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +    integer_params = {
Класс заделал

2022-05-05 08:29 UTC, Dreamlone commented on fedot/core/operations/hyperparameters_preprocessing.py
> +    def __init__(self,
Стоит добавить докстринг с объяснением что класс делает

2022-05-05 08:29 UTC, Dreamlone commented on fedot/core/operations/hyperparameters_preprocessing.py
> +        : return : param_value after preprocessing
Вроде не перед param у нас не ставятся пробелы

2022-05-05 08:29 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        self._init(data.task, params=params, train_data=data)
Может лучше делать преобразование гиперпараметров в рамках fit? А то специально из-за этого прокидывать train в конструктор выглядит как-то громоздко.

2022-05-05 08:33 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self._init(data.task, params=params, train_data=data)
В целом, можно прокидывать shape таргета сразу

2022-05-05 08:43 UTC, nicl-nno commented on fedot/core/operations/operation.py
> +        self._init(data.task, params=params, train_data=data)
Не заметил, что это не настоящий конструктор. Тогда действительно можно просто data_size пробросить.

2022-05-05 08:44 UTC, gorokhovnik commented on fedot/core/operations/hyperparameters_preprocessing.py
> +    def __init__(self,
done

2022-05-05 08:44 UTC, gorokhovnik commented on fedot/core/operations/hyperparameters_preprocessing.py
> +        : return : param_value after preprocessing
fixed

2022-05-05 08:44 UTC, gorokhovnik commented on fedot/core/operations/operation.py
> +        self._init(data.task, params=params, train_data=data)
Теперь прокидываю n_samples_data

2022-05-05 09:06 UTC, Dreamlone approved these changes
Концептуально мне кажется всё ок, только с тестом разберись плиз. Ну и название PR стоит поменять и обновить описание

2022-05-05 09:23 UTC, nicl-nno approved these changes

2022-05-05 10:17 UTC, merged