Abstract notion of Objective, its evaluation and refactor usages of metrics
nccr-itmo/FEDOT pull request #678
Opened 2022-05-17 13:48 UTC by gkirgizov

Main introduced abstractions:
- **Objective** -- Represents objective functions, encapsulates a set of metrics, the kind of objective (single/multi) and can provide some info about them (metric names).
- **ObjectiveEvaluate** -- Responsible for specific evaluation policy of (a) Objective and (b) Graphs. It hides domain specifics of what are the graphs and what's additionally requried for evaluating objective.
    - For example, Pipelines are evaluated by `DataObjectiveEvaluate`, that encapsulates necessary `pipeline.fit` on the train data and objective evaluation on the test data.
- Evaluate (introduced in a previous PR #639) is renamed to **EvaluateDispatcher** -- Responsible for how computing ObjectiveEvaluation must be distributed over processes.

So, following these abstractions, main changes in API:
- Now Objective must be used instead of just a list of metrics with boolean flag `is_multi_objective`. All useages of `metrics` list are dropped from composers, optimsiers etc.
- `GraphOptimiser.optimise` now accepts `ObjectiveEvaluate` as an argument.
  For tests and ad-hoc usages there is a way to contruct trivial `ObjectiveEvaluate` with trivial `Objective` from a simple Callable: e.g. see `run_custom_example.py`.

Part of the big issue #608

2022-05-17 13:48 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:























































* In the file [`test/unit/composer/test_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/722e19df1c773f50ab267a0b5ef014fbd62f965e/test/unit/composer/test_builder.py):

> [Line 49:121](https://github.com/nccr-itmo/FEDOT/blob/722e19df1c773f50ab267a0b5ef014fbd62f965e/test/unit/composer/test_builder.py#L49): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)
> [Line 59:121](https://github.com/nccr-itmo/FEDOT/blob/722e19df1c773f50ab267a0b5ef014fbd62f965e/test/unit/composer/test_builder.py#L59): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (128 > 120 characters)

2022-05-17 19:53 UTC, nicl-nno requested changes

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/composer/random_composer.py
> +                 iter_num: int = 10,
Уточню - а тут добавление iter_num не нарушает интерфейс класса-предка? Выглядит как будто это аналог числа поколений для эв. оптимизатора и должно передаваться схожим способом.

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/composer/random_composer.py
>              print(f'Iter {i}')
Лучше на логирование заменить.

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
> +class EvaluationDispatcher(Generic[G, GN], Operator[PopulationT]):
Не совсем понял - а зачем именно тут наследование от Generic[G, GN]?

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
>              self.evaluation_cache = {ind.uid: graph for ind, graph in zip(population, computed_pipelines)}
Возможно тут теперь стоит бросать ошибку, если базовый тип - не Pipeline.

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/optimisers/objective/data_objective_eval.py
> +class DataObjectiveEvaluate(ObjectiveEvaluate[Pipeline]):
Может назвать PipelineObjectiveEvaluate? Может быть кейс, когда данные нужны, но целевая структура, не пайплайн.

Пример: https://github.com/ITMO-NSS-team/nas-fedot, который Ярослав делает. Возможно, кстати, для упрощения его кода будет полезно разбить на DataObjectiveEvaluate и PipelineObjectiveEvaluate.

2022-05-17 19:53 UTC, nicl-nno commented on fedot/core/optimisers/objective/data_objective_eval.py
> +        graph.log = self._log  # TODO: remove. why it's needed? members shouldn't be assigned in this way.
Кажется, это воркэрауд для ситуации, когда при преобразовании граф<->пайпалйн теряется нужный логгер.

2022-05-18 08:47 UTC, Dreamlone commented on fedot/core/composer/composer.py
> +         For multi-objective optimization -- the list of the graph is returned.
nit: список наверно с пайплайнами, а не с графами (во множественном числе)

2022-05-18 08:47 UTC, Dreamlone commented on fedot/core/composer/random_composer.py
> -    def __init__(self, iter_num: int, primary_node_func: Callable, secondary_node_func: Callable):
А для единообразия не стоит класс унаследовать от `GraphOptimiser`?

2022-05-18 08:47 UTC, Dreamlone commented on fedot/core/optimisers/objective/data_objective_builder.py
> +                self.validation_blocks = default_validation_blocks
Мне кажется, здесь и не требуется записывать обновленное значение в состояние класса - вполне можно убрать

2022-05-18 11:47 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
>              self.evaluation_cache = {ind.uid: graph for ind, graph in zip(population, computed_pipelines)}
Почему? Evaluator работает с любыми подклассами `Graph`. Это скорее проблема `RemoteFitter`. если он только с Pipeline умеетю

2022-05-18 11:49 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
> +class EvaluationDispatcher(Generic[G, GN], Operator[PopulationT]):
Согласен, нигде в классе `G` особо не используется. Хотел как-то убрать, забыл. Уберу.

2022-05-18 11:57 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
>              self.evaluation_cache = {ind.uid: graph for ind, graph in zip(population, computed_pipelines)}
С одной стороны да, с другой - ну вот есть RemoteFitter, который работает с пайплайнами. Для такого варианта же тоже должно быть местро в архитектуре. А тут явно в более общем методы вызывается compute_pipelines.

2022-05-18 12:12 UTC, gkirgizov commented on fedot/core/composer/random_composer.py
> -    def __init__(self, iter_num: int, primary_node_func: Callable, secondary_node_func: Callable):
Он плохо вписываетя в интерфейс его конструктора. Придется немного извращаться и усложнять пример.

2022-05-18 12:15 UTC, gkirgizov commented on fedot/core/optimisers/objective/data_objective_eval.py
> +        graph.log = self._log  # TODO: remove. why it's needed? members shouldn't be assigned in this way.
Добавлю коммент об этом

2022-05-18 12:19 UTC, gkirgizov commented on fedot/core/optimisers/objective/data_objective_eval.py
> +class DataObjectiveEvaluate(ObjectiveEvaluate[Pipeline]):
Переименую.
Возможные использования потом обсудим с Ярославом.

2022-05-18 12:22 UTC, nicl-nno commented on fedot/core/composer/random_composer.py
> -    def __init__(self, iter_num: int, primary_node_func: Callable, secondary_node_func: Callable):
Мб это повод переработать и базовый класс. В том и смысл, чтобы на его основе можно было строить разные оптимизаторы.

2022-05-18 12:48 UTC, gkirgizov commented on fedot/core/composer/random_composer.py
> -    def __init__(self, iter_num: int, primary_node_func: Callable, secondary_node_func: Callable):
Разумно, да. В следующем PR это сделаю, иначе коммиты перетасовывать придется из-за конфликтов (тк локально у меня с этим работа идет)

2022-05-18 13:59 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/evaluation.py
>              self.evaluation_cache = {ind.uid: graph for ind, graph in zip(population, computed_pipelines)}
Подумал на этот счет -- сделаю отдельный небольшой PR для абстракции этого. Завел #679

2022-05-23 12:37 UTC, Dreamlone commented on fedot/core/optimisers/objective/data_objective_builder.py
> +}
Может вынести значения в константы? - fedot/core/constants.py 
Сходу вопрос, а как split ratio для временных рядов используется? Просто по моим соображениям, оно должно игнорироваться в текущей реализации

2022-05-23 12:37 UTC, Dreamlone commented on fedot/core/serializers/coders/parent_operator_serialization.py
> +from ...optimisers.gp_comp.individual import ParentOperator
А чем такая запись удобнее полной?

2022-05-23 13:25 UTC, nicl-nno commented on fedot/core/optimisers/objective/data_objective_builder.py
> +}
Если и выносить - то весь словарь целиком кмк.

2022-05-23 17:03 UTC, Dreamlone commented on fedot/core/optimisers/objective/data_objective_builder.py
> +}
Да в целом лучше то, чтобы всё, что есть в коде, имело какой-то смысл, а не просто "чтобы было") С другой стороны, раньше стоял этот порог и никому не мешал - в общем, пусть будет
Оформил https://github.com/nccr-itmo/FEDOT/issues/686 под это дело - в данном PR игнорируем етот момент

2022-05-23 17:03 UTC, Dreamlone approved these changes

2022-05-24 09:22 UTC, merged