Divided requirements for setup
nccr-itmo/FEDOT pull request #685
Opened 2022-05-23 14:17 UTC by IIaKyJIuH

Now basic `requirements.txt` contains only those libs that are mandatory for common ML usage whilst extra requirements in `requirements_extra.txt` contains libs for DNN, image and text processing.

2022-05-23 14:30 UTC, MorrisNein commented
Тут не перестанут падать тесты, пока не вынесем `import cv2` из `fedot.core.data.data.py`, т.к. OpenCV отнесена к опциональным зависимостям.

2022-05-23 19:57 UTC, nicl-nno commented on README.rst
> +   :target: https://img.shields.io/badge/python_3.6-passing-success
А тут точно дб python_3.6?

2022-05-23 19:58 UTC, nicl-nno commented on requirements_extra.txt
> +h2o == 3.28.1.2
Я бы эти вынес в отдельный req - т.к. это весьма редкий кейс.

2022-05-23 19:59 UTC, nicl-nno commented
В data.py действительно нужен фикс чтобы сделать cv2 необязательным.

2022-05-24 06:40 UTC, IIaKyJIuH commented on README.rst
> +   :target: https://img.shields.io/badge/python_3.6-passing-success
Нет, это была ошибка

[Поправил](https://github.com/nccr-itmo/FEDOT/pull/685/commits/df67d989f6f5627a2a507d38fa86a59be76a2a9a)

2022-05-24 06:41 UTC, IIaKyJIuH commented on requirements_extra.txt
> +h2o == 3.28.1.2
[Подходит?](https://github.com/nccr-itmo/FEDOT/pull/685/commits/83a17f780609653f91a85ba8bb63ee709e8ec0eb)

2022-05-24 07:28 UTC, MorrisNein requested changes

2022-05-24 07:28 UTC, MorrisNein commented on fedot/core/data/data.py
> +    import cv2
Предлагаю воспользоваться лучшими практиками от pandas и сделать [обёртку над опциональными импортами](https://github.com/pandas-dev/pandas/blob/main/pandas/compat/_optional.py#L87).

2022-05-24 07:28 UTC, MorrisNein commented on requirements_extra.txt
> +Pillow >= 8.2.*
Теперь тесты падают на отсутсвии pillow в opt_viz.py

Скажу сразу, чтобы долго не разбираться, эта либа используется в кривоватой визуализации, которую я недавно убрал из примеров и тестов до рефакторинга. 

Т.е. этот импорт нигде не используется. Просто занеси его в используемую функцию, подобно `cv2`, и, возможно, сделай обёртку, как я предложил ранее.

2022-05-24 08:58 UTC, pep8speaks commented
Hello @IIaKyJIuH! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py`](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py):

> [Line 24:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py#L24): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 227:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py#L227): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 270:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py#L270): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 274:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py#L274): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

* In the file [`fedot/core/operations/evaluation/text.py`](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/text.py):

> [Line 124:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/text.py#L124): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)
> [Line 192:5](https://github.com/nccr-itmo/FEDOT/blob/9a69750fe0c15f33351fd9a9b7770e08a9c57796/fedot/core/operations/evaluation/text.py#L192): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (2)

2022-05-24 10:13 UTC, IIaKyJIuH commented on fedot/core/data/data.py
> +    import cv2
Может быть я чего-то не понял, но мне такая обёртка кажется плохой практикой:
1. Если у человека есть нужные библиотеки, то тогда у него перестанет работать `IntelliSense` на модуле
2. Явное прописывание строкового имени модуля самим разработчиком вызывает опасения

2022-05-24 10:14 UTC, IIaKyJIuH commented on requirements_extra.txt
> +Pillow >= 8.2.*
Там было ещё много всего, помимо `opt_viz.py`.
Оказалось, что это целый квест по фиксу зависимостей)

Починил и вроде бы выглядит даже не так плохо, как могло бы быть

2022-05-24 10:36 UTC, nicl-nno commented on requirements_extra.txt
> +h2o == 3.28.1.2
Ага

2022-05-24 10:38 UTC, MorrisNein commented on fedot/core/data/data.py
> +    import cv2
1. Ты имеешь в виду в процессе разработки FEDOT? 
На время разработки мы можем использовать импорт напрямую, перед деплоем заменять на обёртку.
2. Уточни, опасения какого рода.

В моём понимании это подходящий способ ввести пользовательское сообщение о необходимости установки extra requirements. Это снизит число обращений в поддержку. Альтернативой может быть использование try/except при каждом импорте, но это сложнее поддерживать.

2022-05-24 10:40 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
> +    class LSTMNetwork:
На мой взгляд оборачивание такой большой части кода в try выглядит громоздко. Можно хотя бы try/except/else тут применить?

2022-05-24 12:01 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
> +    class LSTMNetwork:
Тут просто хочется вкинуть идею.

Думается мне, это разрешимо вынесением классов с опциональными зависимостями в модули с `_` и затем их импортом под условием, когда зависимость существует.

Да, получится условный импорт второго рода, но зато смотреться будет лаконично и `IntelliSense` всё поймёт.

2022-05-25 07:34 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
> +    class LSTMNetwork:
Решил вообще не усложнять, а оставить примерно в том стиле, как было раньше

[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/c2aa8d911e5e7319c468a5fce7864ff912aede9d)

2022-05-25 10:09 UTC, MorrisNein commented on fedot/core/data/data.py
> +    import cv2
Хорошо, насчёт обёртки убедил.
Тогда, пожалуйста, унифицируй общим шаблоном ошибку об отсутствующей зависимости и добавь это же сообщение для импортов на уровне функций, наподобие `cv2` и `PIL`.

2022-05-25 10:13 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    print('Tensorflow is not installed, continue')
Выглядит не информативно. Предлагаю:
а) добавить шаблонное сообщение с указанием установить extra requirements
б) возможно, использовать warning

2022-05-25 10:13 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
> +    print('Torch is not installed, continue')
Тут то же самое

2022-05-25 10:13 UTC, MorrisNein commented on fedot/core/operations/evaluation/text.py
>      print('Gensim is not installed, continue')
И тут

2022-05-25 10:13 UTC, MorrisNein commented on examples/simple/classification/image_classification_problem.py
> +    import tensorflow as tf
А здесь предполагаем, что юзер знает, что делает?

2022-05-25 10:33 UTC, IIaKyJIuH commented on examples/simple/classification/image_classification_problem.py
> +    import tensorflow as tf
Вообще да, тут предполагается так.

Но я лучше откачу в этом файле обратно до моих изменений, потому что этот файл завязан на тестах, а для них правда нужна полная установка.

2022-05-25 11:43 UTC, IIaKyJIuH commented on fedot/core/data/data.py
> +    import cv2
Надеюсь, я тебя правильно понял

[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/58dc349f4710b1b02ac7310f86aa185a19bea0a5)

2022-05-25 11:43 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    print('Tensorflow is not installed, continue')
Согласен

[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/58dc349f4710b1b02ac7310f86aa185a19bea0a5)

2022-05-25 11:43 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/clstm.py
> +    print('Torch is not installed, continue')
[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/58dc349f4710b1b02ac7310f86aa185a19bea0a5)

2022-05-25 11:43 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/text.py
>      print('Gensim is not installed, continue')
Всё тот же коммит)

[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/58dc349f4710b1b02ac7310f86aa185a19bea0a5)

2022-05-25 11:57 UTC, MorrisNein commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
А если FEDOT установлен как внешняя либа, сработает `pip install .[extra]`?

2022-05-25 11:59 UTC, MorrisNein approved these changes

2022-05-25 12:00 UTC, IIaKyJIuH commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
Хорошее замечание

Вообще нет)
Но, кажется, это странная ситуация: если даже внешняя библиотека устанавливает фреймворк, зная, что нужны будут опциональные библиотеки, то это её ошибка в том, что она не поставила в зависимостях установку `fedot[extra]`

2022-05-25 12:04 UTC, MorrisNein commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
Но кажется, что это будет подавляющее большинство случаев.
Мы-то, как разработчики, понимаем, что нужно установить extra requirements, и на эту ошибку будет чаще попадаться юзер, который делал `pip install fedot`.

2022-05-25 12:04 UTC, IIaKyJIuH commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
С другой стороны, это бы правда помогло пользователю понять, почему его сторонняя библиотека не работает)

Не понимаю просто пока что, как обработать ситуацию (для внешней либы), когда указывается конкретный путь до библиотек, например, `fedot/examples/requirements.txt`

2022-05-25 12:08 UTC, MorrisNein commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
Может, просто всегда предлагать `pip install fedot[extra]`? Если это не подойдёт, поправь меня

2022-05-25 12:27 UTC, nicl-nno approved these changes

2022-05-25 12:36 UTC, IIaKyJIuH commented on fedot/utilities/requirements_notificator.py
> +    msg = f'"{name}" is not installed, use "pip install {default_install_path}" to fulfil'
Получилось максимально красиво, даже разнесённые по всему проекты библиотеки получилось собрать в одном месте

[Вот](https://github.com/nccr-itmo/FEDOT/pull/685/commits/5e25e6f5756d4045295241564c18953db3af0323)

2022-05-25 13:15 UTC, merged