Unify implementations of GP Optimisers
nccr-itmo/FEDOT pull request #687
Opened 2022-05-24 13:18 UTC by gkirgizov

Now `EvoGraphParameterFreeOptimiser` inherits implementation of main `optimise` loop from `EvoGraphOptimiser` and only adjusts evolutionary process by setting several evolutionary parameters in its `__init__`. Previously it duplicated whole `optimise` method.

2022-05-24 18:12 UTC, Dreamlone commented on fedot/core/optimisers/opt_history.py
> +    :return:
return можно убрать

2022-05-25 10:01 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        pass
Комментарий поясняет. Метод перегружается в param_free_gp_optimiser

2022-05-25 10:10 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        self.generations.append(next_population)
Опиши подробнее, какие случаи имеешь ввиду? Я не очень понял, что именно ты предлагаешь протестировать.
А опосредованно весь процесс существующими тестами проверяется.

Вообще, у меня на очереди сразу же еще несколько PR, которые от многих веток избавляются и далее меняют основной класс. Я бы их все залил, а затем потестировал corner cases алгоритма, которые не тестируются существующими. Да и более модульный код попроще тестировать будет и яснее будет, что важно тестировать.

2022-05-25 10:29 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        self.generations.append(next_population)
По поводу случаев, имею в виду вроде [такого](https://github.com/nccr-itmo/FEDOT/pull/687/files#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R235) или [такого](https://github.com/nccr-itmo/FEDOT/pull/687/files#diff-153adaee81d3d13bc9b52d786bbfce2612b0a88b3316e7076531bb5a85fb5caeR21). Про тестирование разных кейсов после внесения всех изменений - согласен

2022-05-25 10:30 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        pass
Пардон, не заметил, что у наследников данный метод расширяется - вопрос снят

2022-05-25 10:58 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
>          self.initial_graph = initial_graph
А тут не поможет новый метод для преобразования в list, который @IIaKyJIuH реализовывал?

2022-05-25 10:59 UTC, nicl-nno commented on fedot/core/optimisers/optimizer.py
> +        # optimisation: callback function that runs on each iteration for new population
В базовом оптимизаторе лучше избегать "эволюционных" терминов (убрать про for new population)

2022-05-25 11:00 UTC, nicl-nno requested changes
В целом норм, param_free-оптимизатор теперь куда компактнее.

2022-05-25 13:51 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +    history.add_to_archive_history(generations.best_individuals)
В `archive_history` хранятся лучшие представители за все время, а в `history` поколения. Механика одна, но информация в этих списках разная.

2022-05-25 14:19 UTC, Dreamlone approved these changes

2022-05-25 14:19 UTC, Dreamlone commented on fedot/core/optimisers/gp_comp/param_free_gp_optimiser.py
> +        # Define adaptive parameters
Я бы предложил воспользоваться ситуацией и вынести константу `DEFAULT_MAX_POP_SIZE` из этого файла в то место, где у нас все константы хранятся

2022-05-25 14:30 UTC, andreygetmanov approved these changes

2022-05-25 15:58 UTC, merged