Leaderboard added to OptHistory
nccr-itmo/FEDOT pull request #695
Opened 2022-05-29 18:45 UTC by nicl-nno

In this PR, the H2O-like leaderboard is added. How to use:

`history.print_leaderboard()`

It consists of:
1) TOP 10 graphs obtained by optimiser
2) Initial assumptions

The main aim is to demonstrate for user how the optimised solution differs from initial one.

Example:
![image](https://user-images.githubusercontent.com/5711814/170886503-b1e53a54-5ffd-4725-b45f-91fafd3b5f5a.png)

2022-05-29 18:45 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





* In the file [`fedot/core/optimisers/gp_comp/gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/blob/cf4a7d37ee0e467959bc80b296d1210fd31a3db3/fedot/core/optimisers/gp_comp/gp_optimiser.py):

> [Line 132:17](https://github.com/nccr-itmo/FEDOT/blob/cf4a7d37ee0e467959bc80b296d1210fd31a3db3/fedot/core/optimisers/gp_comp/gp_optimiser.py#L132): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2022-05-29 20:16 UTC, valer1435 requested changes

2022-05-29 20:16 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                                       self.initial_graph]
Скорее всего не относится к текущему pr - тут идет итерация по initial_graph, что подразумевает, что он список, тогда мб лучше initial_graphs?

2022-05-29 20:16 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +            print(f'{i} | {individual.graph.descriptive_id} | {round(individual.fitness.value, 4)}')
Тут думаю имеет смысл выводить номер поколения/ номер пайплайна в поколении, чтобы можно было быстро найти более подробное описание

2022-05-29 20:16 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +    def print_leaderboard(self):
Мб ввести top_n как параметр?

2022-05-29 22:24 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +    def print_leaderboard(self):
Ввёл:

![image](https://user-images.githubusercontent.com/5711814/170893646-7dd03ed3-d439-4298-ba6d-d2db13810191.png)

2022-05-29 22:24 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +            print(f'{i} | {individual.graph.descriptive_id} | {round(individual.fitness.value, 4)}')
Добавил вывод "поколение-номер":

2022-05-29 22:24 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                                       self.initial_graph]
Переименовал поле в initial_graphs

2022-05-30 06:41 UTC, aPovidlo reviewed
Не совсем понимаю, но в описании пайплайнов `\n_` несет какую-то смысловую нагрузку?

2022-05-30 07:24 UTC, nicl-nno commented
> Не совсем понимаю, но в описании пайплайнов \n_ несет какую-то смысловую нагрузку?

Обозночает что далее идет название node.

2022-05-30 09:07 UTC, valer1435 approved these changes

2022-05-30 09:15 UTC, aPovidlo requested changes

2022-05-30 09:15 UTC, aPovidlo commented on fedot/core/optimisers/opt_history.py
> +        print(f'Position | Fitness | Pipeline | Generation')
Необходимо поменять местами _Fitness_ и _Pipeline_. Далее в конце функции в выводе через `print` идет сначала описание пайплайна, а потом его значение.

2022-05-30 09:18 UTC, aPovidlo commented
> > Не совсем понимаю, но в описании пайплайнов \n_ несет какую-то смысловую нагрузку?
> 
> Обозночает что далее идет название node. \ - разделитель.

А есть ли смысл это выводить для каждого?

2022-05-30 09:59 UTC, aPovidlo approved these changes

2022-05-30 14:04 UTC, gkirgizov requested changes

2022-05-30 14:04 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                # TODO refactor to new optimiser architecture
Да в целом логика верна, разве что в чем-то красивее это сделать. Не уверен пока, как, пусть так будет.

2022-05-31 12:26 UTC, gkirgizov requested changes
Вообще говоря, сейчас в GenerationsKeeper можно передать параметр `keep_n_best: int`, чтобы он сохранял лучшие модели в `best_models`. Может, так лучше и правильнее, чем по истории пробегать заново?
Просто этот параметр на вытащен наружу в API, вот и все.

2022-05-31 12:26 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +        print(f'Position | Pipeline | Fitness | | Generation')
тут лишний разделитель

2022-05-31 12:26 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
мб descritptive_id графа последним печатать? читаемее будет.
и я бы выровнял столбцы по фиксированной длине (тут есть пример с fstring -- https://stackoverflow.com/questions/8450472/how-to-print-a-string-at-a-fixed-width)

2022-05-31 15:26 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                                 key=lambda ind: ind.fitness)[:top_n]
Переделал на [top_n:]. Также реализовал логику, обеспечивающую отсутствие дубликатов из более поздних поколений.

2022-05-31 15:26 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                  f'{round(individual.fitness.value, 4)} | '
Done

2022-05-31 15:26 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
descritptive_id перенес в конец, со столбцами пока не нашел удачного решения

2022-06-03 09:03 UTC, gkirgizov requested changes

2022-06-03 09:06 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
а как насчет `f`{top_item_id:<8}'` ? на первые 3 столбца вроде можно макс. ширину прикинуть

2022-06-06 16:06 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
![image](https://user-images.githubusercontent.com/5711814/172199662-9c9c4949-25c4-4e64-8c78-4c1b79221327.png)

Cловил вот такую проблему для фитнеса

2022-06-06 17:25 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
Сделал, но все равно не особо аккуратно выглядит:

![image](https://user-images.githubusercontent.com/5711814/172212160-335401b1-1ccd-4042-970f-164b49060de3.png)

2022-06-06 17:25 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +            key=lambda ind: ind.fitness, reverse=True)[:top_n]
Так и сделал.

2022-06-06 17:25 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +            [ind for ind in all_individuals if ind.graph.descriptive_id in unqiue_individuals_ids],
Да, есть такое. Изменил логику.

2022-06-06 17:26 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +    def print_leaderboard(self, top_n: int = 10):
Добавил новое поле индивида positional_id, чтобы по нему можно было сортировать.

2022-06-07 11:54 UTC, gkirgizov requested changes

2022-06-07 11:54 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            ind.positional_id = f'g{self.generations.generation_num}-i{ind_id}'
Предлагаю все-таки отдельно хранить номер поколения и номер индивида. С такой строчкой, таким id сложно сделать что-то еще, тк она заточена только для лидерборда. А вот если можно достать номер поколения -- его можно где-то еще использовать. Хотя бы вот в логе где-то выводить.
И предлагаю хранить номера, а не строки.
Как вариант можно tuple двух значений хранить `(generation_num, ind_num)` -- но тогда в описании поля надо объяснить это. Я пожалуй за вариант с отдельным хранением int-ов. Не вижу смысла объединять разные по смыслу значения в один непрозрачный объект.

2022-06-07 11:54 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            ind.positional_id = f'g{self.generations.generation_num}-i{ind_id}'
Если идея была в том, чтобы абстрагировать ключ сортировки (мол, можем в принципе туда писать и что-то еще, хоть np.random.rand), то, может, расскажешь, в каких случаях может понадобиться это? Мне такие в голову не приходят.

2022-06-07 11:54 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +            fitness = str(individual.fitness)
а зачем это, если f-string и так `__str__` вызывает?

2022-06-07 11:54 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +                                                          key=lambda ind: ind.graph.descriptive_id)][:top_n]
думаю, можно попроще через dict:
`list({ind.graph.descriptive_id:ind for ind in individuals})[:top_n]` (dict сохранит порядок сортировки, это гарантировано начиная с python 3.7)

2022-06-07 11:54 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +        all_individuals = list(itertools.chain(*self.individuals))
можно лишний раз `list` не создавать, тк `sorted` просто `Iterable` принимает

2022-06-07 11:57 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +                          f'g{gen_id}-i{ind_id}')
Наверное так все таки чуть получше. А так, если хочется запариваться для полной красоты, есть маленькие либы на питон для форматирвоания таблиц в консоль.

2022-06-07 12:46 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                                                          key=lambda ind: ind.graph.descriptive_id)][:top_n]
Но там будет строковое представление ind.graph.descriptive_id:ind - а мне нужны сами индивиды.

2022-06-07 12:48 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +            fitness = str(individual.fitness)
Убирание str порождает ошибку typeError: unsupported format string passed to SingleObjFitness.__format__

2022-06-07 13:02 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            ind.positional_id = f'g{self.generations.generation_num}-i{ind_id}'
Вынес positional_id как property, generation_num и ind_num сделал переменными

2022-06-07 13:02 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +        all_individuals = list(itertools.chain(*self.individuals))
Убрал list

2022-06-08 09:32 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +                                                          key=lambda ind: ind.graph.descriptive_id)][:top_n]
а, да, тогда  `{...}.values()` еще вызвать

2022-06-08 09:35 UTC, gkirgizov approved these changes

2022-06-08 11:44 UTC, nicl-nno commented on fedot/core/optimisers/opt_history.py
> +                                                          key=lambda ind: ind.graph.descriptive_id)][:top_n]
Ок, действительно. Сделал.

2022-06-08 13:05 UTC, merged