add max_pipeline_fit_time
nccr-itmo/FEDOT pull request #696
Opened 2022-05-30 13:32 UTC by valer1435

max_pipeline_fit_time param added in composer_params

2022-05-30 13:44 UTC, aPovidlo requested changes

2022-05-30 13:44 UTC, aPovidlo commented on examples/simple/classification/api_classification.py
> +    # print(baseline_model.get_metrics())
А зачем этот кусок кода было нужно заносить в комментарий и оставлять?

2022-05-30 13:44 UTC, aPovidlo commented on examples/simple/classification/api_classification.py
> +                       composer_params={'max_pipeline_fit_time': timedelta(minutes=1)})
Лучше сразу сделать внутри какое-то преобразование к минутам, также как это сделано с `timeout` (там это вроде только к секундам), чтобы каждый раз не приходилось оборачивать в `timedelta()`

2022-05-30 13:49 UTC, ChrisLisbon reviewed
Есть ли необходимость в рамках этого pr добавлять в репозиторий pkl модели и историю к ней? Если да, то добавь это в описание пожалуйста, если нет, то стоит убрать лишние файлы

2022-05-30 13:49 UTC, ChrisLisbon commented on examples/simple/classification/api_classification.py
> +    # baseline_model = Fedot(problem=problem, timeout=timeout)
Забыл комменты убрать

2022-05-30 13:51 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +                       composer_params={'max_pipeline_fit_time': timedelta(minutes=1)})
Сделал https://github.com/nccr-itmo/FEDOT/pull/696/commits/2f72d958bf97690fc6e7dd7a4acde136c69388b2#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR86

2022-05-30 13:52 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +    # print(baseline_model.get_metrics())
Убрал комменты https://github.com/nccr-itmo/FEDOT/pull/696/commits/2f72d958bf97690fc6e7dd7a4acde136c69388b2#diff-b42069019862f2fa94d0428f6eae68669c539a219c75684c54c01c3778af65dcR13-R20

2022-05-30 13:54 UTC, ChrisLisbon requested changes

2022-05-30 13:54 UTC, ChrisLisbon commented on test/unit/models/test_repository.py
> -import json
Специально снес?

2022-05-30 13:57 UTC, aPovidlo commented on test/unit/models/test_repository.py
> -import json
@ChrisLisbon Твой код пройдет все тесты, если тестов не будет)

2022-05-30 14:26 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`test/unit/models/test_repository.py`](https://github.com/nccr-itmo/FEDOT/blob/e688a728447e548b9ae3b7e45afee9924336f799/test/unit/models/test_repository.py):

> [Line 97:89](https://github.com/nccr-itmo/FEDOT/blob/e688a728447e548b9ae3b7e45afee9924336f799/test/unit/models/test_repository.py#L97): [W292](https://duckduckgo.com/?q=pep8%20W292) no newline at end of file

2022-05-30 14:52 UTC, valer1435 commented
> А что имеется ввиду под operation fitting?

Обучение одного пайплайна. Чтобы не было такого, что пайплайн обучается тыщу часов

2022-05-30 14:53 UTC, valer1435 commented on test/unit/models/test_repository.py
> -import json
https://github.com/nccr-itmo/FEDOT/pull/696/commits/e688a728447e548b9ae3b7e45afee9924336f799 добавил

2022-05-30 15:25 UTC, Dreamlone approved these changes
LGTM

2022-05-30 15:40 UTC, nicl-nno commented
А где по факту используется max_pipeline_fit_time? Не нашел в коде, чтобы оно передавалось в пайплайн.

2022-05-31 09:41 UTC, valer1435 commented
> А где по факту используется max_pipeline_fit_time? Не нашел в коде, чтобы оно передавалось в пайплайн.

Добавил атрибут в PipelineComposerRequirements (но и без него вроде прокидывалось) https://github.com/nccr-itmo/FEDOT/pull/696/commits/51f87e0d791d15724afa186a87ba153da50a3052

2022-05-31 12:34 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +    # print(baseline_model.get_metrics())
Это старый код - показывает, что можно юзать predifined_model, поэтому оставил

2022-05-31 12:38 UTC, nicl-nno commented
>Добавил атрибут в PipelineComposerRequirements (но и без него вроде прокидывалось) https://github.com/nccr-itmo/FEDOT/commit/51f87e0d791d15724afa186a87ba153da50a3052

А где именно проброшенное значение используется для задания time_constraint при fit?

2022-05-31 14:50 UTC, valer1435 commented
> > Добавил атрибут в PipelineComposerRequirements (но и без него вроде прокидывалось) [51f87e0](https://github.com/nccr-itmo/FEDOT/commit/51f87e0d791d15724afa186a87ba153da50a3052)
> 
> А где именно проброшенное значение используется для задания time_constraint при fit?

Сначала в композер через api https://github.com/nccr-itmo/FEDOT/blob/max_pipeline_fit_time/fedot/core/composer/gp_composer/gp_composer.py#L80
Потом сюда https://github.com/nccr-itmo/FEDOT/blob/51f87e0d791d15724afa186a87ba153da50a3052/fedot/core/optimisers/objective/data_objective_builder.py#L23
Далее сюда https://github.com/nccr-itmo/FEDOT/blob/51f87e0d791d15724afa186a87ba153da50a3052/fedot/core/optimisers/objective/data_objective_eval.py#L36

И уже этот класс используется в evaluating для fit-predict индивида. И там, соответственно используется time_constaint https://github.com/nccr-itmo/FEDOT/blob/51f87e0d791d15724afa186a87ba153da50a3052/fedot/core/optimisers/objective/data_objective_eval.py#L93

2022-05-31 18:10 UTC, aPovidlo approved these changes

2022-06-01 09:13 UTC, ChrisLisbon approved these changes

2022-06-02 09:15 UTC, merged