Generalize Evaluation subsystem and Objective interface
nccr-itmo/FEDOT pull request #697
Opened 2022-05-31 12:57 UTC by gkirgizov

- Use generic ObjectiveFunction (Callable) instead of ObjectiveEvaluate in .optimise interface.
  This generalises Optimiser interface and allows passing arbitrary Callables as Objective functions.
- Introduce ObjectiveEvaluationDispatcher:
  Dispatcher accepts objective function and returns population evaluator.
  Its role is to define details of how objective must be actually evaluated,
  e.g. using multiprocessing, evaluation cache or remote evaluation.
  Rename EvaluationDispatcher to MultiprocessingDispatcher, which reflects its implementation.
- Introduce `evaluation_callback` functionality in Optimiser.
  This allows extracting the need for computing intermediate metrics.
  Now gp_composer defines this callback.

This is a continuation of PR #678 and part of the issue #608

2022-05-31 14:32 UTC, valer1435 requested changes

2022-05-31 14:32 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluation.py
> +    def set_evaluation_callback(self, callback: Optional[GraphFunction]):
Я так понимаю, что предполагается только один callback?

2022-05-31 14:32 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +def _unfit_pipeline(graph: Any):
Может быть место этой функции где-то в pipeline модуле?

2022-05-31 14:45 UTC, ChrisLisbon approved these changes

2022-06-01 09:58 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +    def set_evaluation_callback(self, callback: Optional[GraphFunction]):
Да, хотя в целом легко расширяемо на произвоьное количество коллбэков, если будет необходимость

2022-06-01 10:00 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +def _unfit_pipeline(graph: Any):
Тоже думал, но нет. Она только локально используется и больше для импорта не предназначена. Сделал именованную вместо лямбды для лучшей читаемости.

2022-06-01 10:03 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +def _unfit_pipeline(graph: Any):
Может тогда её в evaluation?

2022-06-01 17:12 UTC, valer1435 approved these changes

2022-06-02 21:39 UTC, nicl-nno approved these changes

2022-06-03 08:33 UTC, merged