Backward compatibility of OptHistory
nccr-itmo/FEDOT pull request #700
Opened 2022-06-02 13:44 UTC by MorrisNein

Changelist:

1. Individual serialization - `float` fitness is converted to `SingleObjFitness`.
2. `ParentOperator` class is temporary imported at `opt_history` until the [issue](https://github.com/nccr-itmo/FEDOT/issues/699) is closed.

2022-06-02 13:44 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/optimisers/opt_history.py`](https://github.com/nccr-itmo/FEDOT/blob/3787d272997dd3665c5842896a2d4d13cf145f3e/fedot/core/optimisers/opt_history.py):

> [Line 14:80](https://github.com/nccr-itmo/FEDOT/blob/3787d272997dd3665c5842896a2d4d13cf145f3e/fedot/core/optimisers/opt_history.py#L14): [E261](https://duckduckgo.com/?q=pep8%20E261) at least two spaces before inline comment

2022-06-02 21:20 UTC, MorrisNein commented
В рамках этого PR также пройдусь по проекту, где уже натыкал `isinstance(fitness, float)` и уберу вилку.

2022-06-05 18:10 UTC, IIaKyJIuH requested changes

2022-06-07 10:33 UTC, IIaKyJIuH approved these changes

2022-06-09 08:59 UTC, maypink commented on test/unit/composer/test_history.py
>  from fedot.core.optimisers.gp_comp.operators.crossover import crossover, CrossoverTypesEnum
чуть-чуть подушню и скажу, что может импорты из одной директории (в нашем случае fedot.core.optimisers) должны идти подряд? в pep-е это не регламентируется, но глазу поприятнее

2022-06-09 09:02 UTC, MorrisNein commented on test/unit/composer/test_history.py
>  from fedot.core.optimisers.gp_comp.operators.crossover import crossover, CrossoverTypesEnum
Да, действительно, в идеале их сортировать по алфавиту. Поправлю)

2022-06-10 13:30 UTC, gkirgizov requested changes

2022-06-10 13:30 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _initialize_individuals_from_graphs(self):
Может быть, все это сделать один раз в `__init__` базового класса? 
Тогда можно избавиться от поля `initial_graphs`, тк это фактически дублирующие друг друга поля.
Property мб лишнее, тк в `init` это можно вычислить и просто хранить в `initial_individuals`.

2022-06-10 13:30 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/initial_population_builder.py
>      def with_initial_graphs(self, initial_graphs: Sequence[OptGraph]):
Подумал, давай оставим только `with_initial_individuals`, а то дубликация кода фактически

2022-06-10 13:30 UTC, gkirgizov commented on test/unit/composer/test_history.py
> +    assert isinstance(history.individuals[0][0].fitness, SingleObjFitness)
я бы пробежался бы по всей истории, раз уже это тест

2022-06-10 14:23 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    assert isinstance(history.individuals[0][0].fitness, SingleObjFitness)
[Готово](https://github.com/nccr-itmo/FEDOT/pull/700/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R200)

2022-06-10 14:24 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/initial_population_builder.py
>      def with_initial_graphs(self, initial_graphs: Sequence[OptGraph]):
Согласен, [поменял](https://github.com/nccr-itmo/FEDOT/pull/700/files#diff-00aa1644bbe78562474bd8a2fec7a9d3557a8c73784594a7b66821a71f067d5aL35)

2022-06-10 14:25 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _initialize_individuals_from_graphs(self):
Теперь [здесь](https://github.com/nccr-itmo/FEDOT/pull/700/files#diff-8403390fb245520b5527e48932b6e9f2a3842f425924be024e8c26f1bc67b9a0R88)

2022-06-13 08:21 UTC, IIaKyJIuH requested changes

2022-06-13 08:21 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Микро замечание: должно и без каста к `str` работать

2022-06-13 09:17 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Я пробовал, в текущей реализации `OptHistory.load` не работает. Он сначала пробует обработать как JSON и получает:
`TypeError: the JSON object must be str, bytes or bytearray, not WindowsPath`

Хотелось зарефакторить этот метод, пробовал проверку на Path.exists() первым делом, но такая неудачная попытка в среднем в 5 раз медленнее неудачной попытки распарсить JSON. Возможно, выходом будет сделать явное условие на входной тип `Path` в `OptHistory.load`.

2022-06-13 09:19 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Либо добавлю TypeError в уже имеющийся там try-except

2022-06-13 10:31 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Полагаю, нашёл [приемлемое решение](https://github.com/nccr-itmo/FEDOT/pull/700/files#diff-24454c25d44682b1bec4847be8b29568764673aa0312e54294f34b1fa2dcc730R103)

2022-06-13 11:46 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Может быть теперь достаточно одного `else` на загрузку, как `JSON`, вместо `try...except...`?

2022-06-13 11:53 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
Каст, кстати, убрал

2022-06-13 12:27 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +    history = OptHistory.load(str(test_history_path))
> Может быть теперь достаточно одного `else` на загрузку, как `JSON`, вместо `try...except...`?

В таком случае путь, переданный строкой, будет прочитан как JSON. Ты закладываешь такую логику в это предложение?

2022-06-14 08:26 UTC, gkirgizov approved these changes

2022-06-14 17:14 UTC, merged