Update statsmodels models
nccr-itmo/FEDOT pull request #702
Opened 2022-06-04 08:50 UTC by valer1435

Before this pr such statsmodels models as Arima, STLArima, AuroReg had special flag "refit_insample" for refitting on a new data while insample forecasting. Now this logic moved into implementation for being able to use it not only in FEDOT insample forecasting method.

2022-06-04 13:11 UTC, Dreamlone requested changes
Еще хотелось бы тест проверяющий то, что при in-sample модели работаю нормально (хотя бы для AR)

2022-06-04 13:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            end_id = start_id+parameters.forecast_length-1
Можно использовать просто `forecast_length` здесь вместо parameters.forecast_length

2022-06-04 13:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def _update(self, input_data: InputData):
В названии метода можно вполне использовать фразу про усвоение новых данных или вроде того, вместо абстрактного _update

2022-06-04 13:11 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
Ох, раз тут без переобучения заново никак то может введем какой-нибудь тег для таких операций в духе `new_data_refit`?

2022-06-05 19:34 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            _, predict = ts_to_table(idx=idx,
![image](https://user-images.githubusercontent.com/32017472/172067419-6f6ebe27-43fd-435d-b939-5ccf41e0a7b7.png)
У меня отработало. Скинул в лс requirements мои

2022-06-05 19:41 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
Вкину идею - вот у нас есть федот, который в процессе композирования создает много моделей (допустим та же арима закрепилась где-то вначале). Тогда ему придется много раз все равно ее обучить и будет ли refit при новых данных таким значимым при обучении таких моделей на этапе композирования?

2022-06-06 09:05 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
Тут два момента: если используется in-sample валидация (а используется она довольно часто при кросс-валидации временных рядов), то при одном вызове метода `predict` придется аж 3, или 4, или 5 раз заново переобучать ARIMA модель - об этом точно хочется знать хоть как-то 

И второе, если модель в самом начале и гиперпараметры не меняются, то она должна будет подтягиваться из кэша. Следовательно, при вызове метода fit она никах не будет съедать время. Но совсем другое будет на predict'е

2022-06-06 09:08 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Объясни, пожалуйста, на пальцах, на что эта проверка.

2022-06-06 09:10 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Сам долго въезжал: здесь проверяется то, является ли первый индекс, на который формируется прогноз, следующим после последнего последнего известного модели значения из обучения
Ну, если что, Валера получше распишет

2022-06-06 09:12 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Вижу, эта проверка встречается не единожды.
Можем её вынести в отдельную функцию с говорящим названием?
По типу `is_insample_forecasting(start_idx, ts_len)`

Если понадобится изменить это условие, оно будет в одном месте.

2022-06-06 09:16 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            _, predict = ts_to_table(idx=idx,
Ага, все работает. 
Есть предложение: поправь плиз вот этот кусок: линии все равно никак не различаются
![image](https://user-images.githubusercontent.com/52418437/172132425-89faf4a7-aa99-473b-a684-ef6a31443dcb.png)

Предлагаю убрать один из элементов легенды. И кстати ещё по картинке - почему-то не отображаются разграничители для третьего и следующих блоков валидации, - только первый окаймлён

2022-06-06 10:32 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Надеюсь так будет понятнее - если мы прогнозируем чуть дальше, чем мы закончили обучаться - нужно делать рефит
![image](https://user-images.githubusercontent.com/32017472/172144403-5fe3dd76-8c39-47e3-abdb-c717d962b962.png)

2022-06-06 11:17 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            _, predict = ts_to_table(idx=idx,
Тут нет явной кросс-валидации - она скрыта в fit. То- что между линиями - тестовые данные - а дальше то, как экстраполирует моделька (данных на этот промежуток нет)

Я когда перерабатывал тесты это заметил, но оставил

2022-06-06 12:03 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
https://github.com/nccr-itmo/FEDOT/pull/702/commits/bc6b81538bc28ca4912cc138f583821ef70fc3ad#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R116-R120

2022-06-06 12:04 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
[Добавил сообщение в лог](https://github.com/nccr-itmo/FEDOT/pull/702/commits/bc6b81538bc28ca4912cc138f583821ef70fc3ad#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R116-R120)

2022-06-06 12:04 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +    def _update(self, input_data: InputData):
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/bc6b81538bc28ca4912cc138f583821ef70fc3ad#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R230)

2022-06-06 12:05 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            end_id = start_id+parameters.forecast_length-1
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/bc6b81538bc28ca4912cc138f583821ef70fc3ad#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R249)

2022-06-06 14:01 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +        if idx[0] - self.actual_ts_len > 1:
а если разница равна 1, то все ок?

2022-06-06 14:03 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            if idx[0] - self.actual_ts_len > 1:
предлагаю поддерживать все в едином виде, как в других моделях: через вызов метода `def _refit_on_new_data_if_needed(self, idx, input_data):`

2022-06-06 14:17 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Предлагаю эту проверку либо вынести в отдельный метод с говорящим названием, либо пояснить комментарием (а лучше и то и другое), типа `is_insample_forecast`

2022-06-06 14:47 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            if idx[0] - self.actual_ts_len > 1:
Тут не рефит, а просто подмена параметров

2022-06-06 15:24 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Да, вполне.
Я предлагал совсем вынести эту функцию из имплементаций в единое место, но так тоже неплохо.

2022-06-06 15:25 UTC, valer1435 commented on examples/simple/time_series_forecasting/ts_pipelines.py
> +    pipeline = Pipeline(node_arima)
Думаю, что стоит отдельным PR все пайплайны, которые есть, переделать

2022-06-06 15:29 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
@valer1435, @Dreamlone, спасибо за пояснение.

2022-06-06 15:29 UTC, MorrisNein commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
Метод действительно напрашивается куда-нибудь в `TimseriesModelImplementation`.

2022-06-06 15:34 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            if idx[0] - self.actual_ts_len > 1:
[чуть-чуть оптимизировал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/33096f47109237fba8365f11607d6f1299d6e372#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R117)

2022-06-06 15:35 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        self.actual_ts_len = None
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/702/commits/33096f47109237fba8365f11607d6f1299d6e372#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2L161-R162)

2022-06-06 15:41 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +        if idx[0] - self.actual_ts_len > 1:
[Нет](https://github.com/nccr-itmo/FEDOT/pull/702/commits/3651f86dd8827cf4bb6a745ddde1bf58e14feb90#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R118), спасибо, что заметил.

Сейчас actual_ts_len - это длина ряда, а не индексы. Из-за того, что индекс начинается с 0, а длина с 1 - то нужно брать поправку -1, когда сравниваем длину и индексы (те первый индекс должен быть равен длине ряда в случае, когда это не in/out sample)

Но, действительно, стоит это переработать более глобально

2022-06-07 09:57 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            _, predict = ts_to_table(idx=idx,
Ок, но линию `End of test` надо бы сделать все таки не такого же цвета, как `train|test`, например серым

2022-06-07 09:58 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
Надо ещё тег

2022-06-07 10:06 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            self.log.info("STL arima refitted for an insample forecasting")
Такой же комментарий что и выше

2022-06-07 12:00 UTC, gkirgizov commented on examples/simple/time_series_forecasting/ts_pipelines.py
> +    pipeline = Pipeline(node_arima)
Пожалуй, но это не мешает новый код писать с учетом этого :)

2022-06-07 12:05 UTC, gkirgizov requested changes

2022-06-07 12:05 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            if idx[0] - self.actual_ts_len > 1:
тогда предлагаю придумать общее название для метода, не `refit...` и не `_change_train_set`. Что-то вроде `handle_insample_forecast` -- чтобы код в моделях временных рядов был единообразным. Как если бы они перегружали один метод. Это потом упроситт в будущем рефакторинг и выделение общего `TSModelImplementation`

2022-06-07 12:50 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            if idx[0] - self.actual_ts_len > 1:
Влечу с предложением по неймингу: пусть лучше метод будет называться `handle_new_data` или вроде того, так как переобучать модель или обновлять train данные может потребоваться совсем не только в случае in-sample валидации (прогноза). Либо можно назвать такое прогнозирование out-of-sample

2022-06-08 07:30 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/advanced/time_series_forecasting/multistep.py`](https://github.com/nccr-itmo/FEDOT/blob/60e9505007e3294caa9f45e5277d7fa2de2c060d/examples/advanced/time_series_forecasting/multistep.py):

> [Line 67:121](https://github.com/nccr-itmo/FEDOT/blob/60e9505007e3294caa9f45e5277d7fa2de2c060d/examples/advanced/time_series_forecasting/multistep.py#L67): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (121 > 120 characters)

2022-06-08 07:31 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            _, predict = ts_to_table(idx=idx,
[Добавил серый цвет](https://github.com/nccr-itmo/FEDOT/pull/702/commits/a697d4dcb201803385dd2bd0ba530e81435aff12)

2022-06-08 07:31 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +                self.model = self.fit(input_data)
[Добавил тег](https://github.com/nccr-itmo/FEDOT/pull/702/commits/a697d4dcb201803385dd2bd0ba530e81435aff12)

2022-06-08 07:32 UTC, valer1435 commented on examples/simple/time_series_forecasting/ts_pipelines.py
> +    pipeline = Pipeline(node_arima)
[Переделал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/edb75fa82d786f774d85554e1246ca7477143c5f#diff-d3d15b71d0d759c10fb6393596877a60d4713388cb4c0c907652751bdfb9f20fR209)

2022-06-08 07:33 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            self.log.info("Arima refitted for an insample forecasting")
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/60e9505007e3294caa9f45e5277d7fa2de2c060d#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R116-R121)

2022-06-08 07:35 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            self.log.info("Arima refitted for an insample forecasting")
И обновил [сообщение ](https://github.com/nccr-itmo/FEDOT/pull/702/commits/60e9505007e3294caa9f45e5277d7fa2de2c060d#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R124)

2022-06-08 07:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
> +            self.log.info("STL arima refitted for an insample forecasting")
[То же](https://github.com/nccr-itmo/FEDOT/pull/702/commits/60e9505007e3294caa9f45e5277d7fa2de2c060d#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R274)

2022-06-08 07:36 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +            if idx[0] - self.actual_ts_len > 1:
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/702/commits/60e9505007e3294caa9f45e5277d7fa2de2c060d#diff-cab26f87359c001d56fbec6f1650b37f3e20ce8a22adb6ef5aa549ddc6a87a12R116-R121)

2022-06-08 07:48 UTC, valer1435 commented
> Еще хотелось бы тест проверяющий то, что при in-sample модели работаю нормально (хотя бы для AR)

Он [уже ](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/pipelines/test_pipeline_ts_wrappers.py#L109)есть

2022-06-08 09:29 UTC, MorrisNein approved these changes

2022-06-08 09:38 UTC, gkirgizov approved these changes

2022-06-08 09:46 UTC, merged