+ preprocessors cacher
nccr-itmo/FEDOT pull request #707
Opened 2022-06-06 12:11 UTC by IIaKyJIuH

Refactored [`DataPreprocessor`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/preprocessing/preprocessing.py#L35) class and added its cacher using sqlite3 database.

Besides fixed caching via multiprocessing in [`data_objective_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/optimisers/objective/data_objective_builder.py), extended [`pipelines_caching.py`](https://github.com/nccr-itmo/FEDOT/blob/master/examples/advanced/pipelines_caching.py) example

2022-06-06 12:11 UTC, pep8speaks commented
Hello @IIaKyJIuH! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`fedot/core/optimisers/gp_comp/gp_optimiser.py`](https://github.com/nccr-itmo/FEDOT/blob/6c08acd360dbf4f52bd7c1f0f6154e2805dc3f15/fedot/core/optimisers/gp_comp/gp_optimiser.py):

> [Line 113:17](https://github.com/nccr-itmo/FEDOT/blob/6c08acd360dbf4f52bd7c1f0f6154e2805dc3f15/fedot/core/optimisers/gp_comp/gp_optimiser.py#L113): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent















* In the file [`test/unit/test_logger.py`](https://github.com/nccr-itmo/FEDOT/blob/6c08acd360dbf4f52bd7c1f0f6154e2805dc3f15/test/unit/test_logger.py):

> [Line 82:121](https://github.com/nccr-itmo/FEDOT/blob/6c08acd360dbf4f52bd7c1f0f6154e2805dc3f15/test/unit/test_logger.py#L82): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (126 > 120 characters)

2022-06-06 12:18 UTC, IIaKyJIuH commented
В текущей реализации кеша препроцессоров почему-то не появляется преимущества (а есть даже ухудшение) от его использования при оценке среднего количества оценённых пайплайнов в обучении (для тестирования, сколько их будет, есть файл [`pipelines_caching.py`](https://github.com/nccr-itmo/FEDOT/blob/master/examples/advanced/pipelines_caching.py))

Кроме того, если не отключить в [`preprocessing_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/api/api_utils/assumptions/preprocessing_builder.py#L24-L27) строки с обязательным добавлением опциональных предобработчиков, то это влияет в худшую сторону в том числе и на общее время, которое будет тратиться на методы `fit/predict` в пайплайнах.

2022-06-06 14:49 UTC, Dreamlone requested changes

2022-06-06 14:49 UTC, Dreamlone commented on fedot/preprocessing/cache.py
> +    def __init__(self, log: Optional[Log] = None, db_path: Optional[str] = None):
Классу бы дать подробное docstring описание

2022-06-06 14:49 UTC, Dreamlone commented on test/unit/test_logger.py
> +    expected_number_of_loggers = 7  # TODO: changed cause of PreprocessingCache() creation in pipeline.fit is it ok?
Ага, такое случается, тест и правда довольно часто приходится модифицировать

2022-06-06 14:49 UTC, Dreamlone commented on examples/advanced/pipelines_caching.py
> +                cache_effectiveness += auto_model.api_composer.cache.effectiveness_ratio if basic_cache_usage else {}
Как пример, смотрится довольно тяжеловато. Есть возможность разбить на функции поменьше?

2022-06-06 14:49 UTC, Dreamlone commented on fedot/preprocessing/cache.py
> +    return f'{pipeline_id}_{data_id}'
По большому счету могут существовать только следующие 9 случаев: 
1) Данные содержат пропуски и категории - Пайплайн не может заполнить пропуски и выполнить энкодинг
2) Данные содержат пропуски и категории - Пайплайн не может заполнить пропуски но может энкодинг
3) Данные содержат пропуски и категории - Пайплайн может заполнить пропуски но не может энкодинг
4) Данные содержат пропуски и категории - Пайплайн может заполнить пропуски и может сделать энкодинг

-
5) Данные содержат пропуски, категорий нет - Пайплайн не может заполнить пропуски
6) Данные содержат пропуски, категорий нет - Пайплайн может заполнить пропуски

-
7) Данные не содержат пропусков, категории есть - Пайплайн не может выполнить энкодинг
8) Данные не содержат пропусков, категории есть - Пайплайн может выполнить энкодинг

-
9) Данные без пропусков и категорий

Таким образом, нам нужно хранить в БД всего 8 препроцессоров. В целом, даже меньше - ведь заполнение пропусков не имеет метода fit - только fit_transform всегда. Следовательно, париться нам стоит только лишь об энкодинге. 

Отсюда вопрос: это как-то в текущей версии используется эта информация?

2022-06-06 14:49 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +            self.preprocessor = preprocessing_cache.try_find_preprocessor(self, input_data)
Запускал эксперименты с использование кэша - поставил метку в этом месте. И в итоге алгоритм так ни разу и не заглянул сюда

2022-06-07 08:08 UTC, IIaKyJIuH commented on examples/advanced/pipelines_caching.py
> +        ...
[Сделал `pass`](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-eac22fe0d80a91ac207928f9b2d765165a31968718c0afd1333fbb1c67d5ae40R83-R84)

2022-06-07 08:09 UTC, IIaKyJIuH commented on fedot/api/main.py
> +
Точно, [убрал](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR117-R120)

2022-06-07 08:09 UTC, IIaKyJIuH commented on fedot/preprocessing/cache.py
> +    def __init__(self, log: Optional[Log] = None, db_path: Optional[str] = None):
[Согласен](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-f1a6c6229e268a4100175eb18f71492c865e1b5bd7bdfdf504a7ec21e0a49c4cR13-R18)

2022-06-07 08:11 UTC, IIaKyJIuH commented on examples/advanced/pipelines_caching.py
> +                cache_effectiveness += auto_model.api_composer.cache.effectiveness_ratio if basic_cache_usage else {}
[Вынес](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-eac22fe0d80a91ac207928f9b2d765165a31968718c0afd1333fbb1c67d5ae40R87-R119) основное по запуску теста в отдельную функцию

2022-06-07 08:11 UTC, IIaKyJIuH commented on fedot/preprocessing/cache_db.py
> +    def __init__(self, db_path: Optional[str] = None):
[Ага](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-3981be672f0801ce7b8f824bb756855f67a6ae5f593031e322f3485ebe60fc05R14-R19)

2022-06-07 08:14 UTC, nicl-nno commented
>В текущей реализации кеша препроцессоров почему-то не появляется преимущества (а есть даже ухудшение) от его использования

По поводу этого - а оценивал, сколько времени в среднем занимает сохранение/загрузка препроцессора в кэш? И как это соотносится с его обучением с нуля.

2022-06-07 08:15 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +            self.preprocessor = preprocessing_cache.try_find_preprocessor(self, input_data)
Спасибо, что заметил
Мне казалось, что код сюда заходит, но он действительно всегда пропускает эту часть, даже понял, почему.

Но теперь у меня другой вопрос, должны ли быть связаны кеш по пайплайнам и кеш по препроцессору? Пока что связаны

2022-06-07 08:21 UTC, IIaKyJIuH commented
> > В текущей реализации кеша препроцессоров почему-то не появляется преимущества (а есть даже ухудшение) от его использования
> 
> По поводу этого - а оценивал, сколько времени в среднем занимает сохранение/загрузка препроцессора в кэш? И как это соотносится с его обучением с нуля.

Я использовал отдельную [ветку](https://github.com/nccr-itmo/FEDOT/tree/check-preprocessing), созданную @Dreamlone, для проверки, сколько времени теперь в среднем занимает fit/predict в пайплайнах, и вот там прирост ощущался, причём на разных датасетах с разными проблемами.

2022-06-07 09:02 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +            self.preprocessor = preprocessing_cache.try_find_preprocessor(self, input_data)
Вот мне кажется, что необязательно: две разные сущности по сути у нас: "препроцессор" и "пайплайн". Препроцессоры вставляются в пайплайн и конфигурируются на основе особенностей пайплайнов. Но, как я и писал выше, количество вариантов препроцессоров очень маленькое формируется за всю историю композирования (до 10 вариантов, да и то, это с учетом различия энкодеров по факту их обучения на различных фолдах)
Получается такой дисбаланс сотни: и тысячи пайплайнов и  5-10 энкодеров. Может и не связывать тогда кэш - можно даже совсем наивно делать: берем пайплайн - проверяем structure explorer'м требуется ли ему препроцессинг, и если да, достаем из широких штанин обученный энкодер для данного фолда

2022-06-07 09:18 UTC, Dreamlone commented
> Кроме того, если не отключить в [`preprocessing_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/api/api_utils/assumptions/preprocessing_builder.py#L24-L27) строки с обязательным добавлением опциональных предобработчиков, то это влияет в худшую сторону в том числе и на общее время, которое будет тратиться на методы `fit/predict` в пайплайнах.

А вот тут поподробнее: то есть я правильно понимаю, что если не отключать `PreprocessingBuilder`, то будет хуже, чем если отключать? Если это так, то вполне закономерно: есть данные с категориями (PreprocessingBuilder включен), - собирается начальное приближение с узлами для энкодинга, - тогда StructureExplorer посмотрит на граф и сделает вывод, что операции предобработки в его структуре уже есть, и, следовательно, опциональную предобработку включать не требуется. То есть операции предобработки будут кэшироваться как обычные узлы, а если твоя реализация кэширования опционального препроцессинга эффективнее таковой as is, то будет наблюдаться прирост в производительности относительно включенного PreprocessingBuilder.

2022-06-09 10:43 UTC, andreygetmanov requested changes

2022-06-09 10:43 UTC, andreygetmanov commented on fedot/preprocessing/preprocessing.py
> +            # self._apply_categorical_encoding(data, source_name)
В Федоте обработка категориальных признаков относится к опциональной предобработке (Миша писал об этом [тут](https://habr.com/ru/company/ods/blog/657525/) в разделе "Развязка"). Не знаю, почему энкодинг дублируется здесь, но думаю, что его и правда можно убрать
И ещё чуть выше коммент # Process categorical features, имхо, можно изменить на # Process binary categorical features, чтобы было понятнее, что в одном случае мы обязательно кодируем бинарные категориальные признаки, а в другом - опционально мультиклассовые

2022-06-15 14:05 UTC, andreygetmanov approved these changes

2022-06-16 13:03 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +            self.preprocessor = preprocessing_cache.try_find_preprocessor(self, input_data)
То есть, ты предлагаешь просто оставить кэширование на словаре, которое я [сделал в препроцессоре](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-41c3d47730f807de8f4aa2be059052d8658e055ec19855a4331ea13a774ad52a), забыв про базу данных?

2022-06-16 19:56 UTC, IIaKyJIuH commented on fedot/preprocessing/cache.py
> +    return f'{pipeline_id}_{data_id}'
Я думал, что в заполнителе [`ImputationImplementation`](https://github.com/nccr-itmo/FEDOT/blob/caching_preprocessors/fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_transformations.py#L257) всё-таки используется fit, поэтому даже в реализации рассчитываю на него, это раньше в реализации `DataPreprocessor` всегда использовался fit_transform

Ответ на вопрос: в текущей версии это правда не используется

Насчёт твоей идеи всё ещё думаю, но вообще и раньше, и сейчас предполагается, что в препроцессоре есть свои поля с imputer/encoder'ами, в самой базе данных же сохраняется препроцессор в том состоянии, которое получилось после прохода obligatory и optional обработок в `fit` у пайплайна.

2022-06-17 15:32 UTC, Dreamlone commented on fedot/core/pipelines/pipeline.py
> +            self.preprocessor = preprocessing_cache.try_find_preprocessor(self, input_data)
Ага, ну тут посыл в том, чтобы просто разделить две этих задачи: кэширования препроцессинга и кэширование пайплайнов, вторая задача более амбициозная. Но первая, по идее, не должна требовать много ресурсов для реализации

2022-06-17 16:17 UTC, Dreamlone commented on fedot/preprocessing/cache.py
> +    return f'{pipeline_id}_{data_id}'
То есть ты кэшируешь `DataPreprocessor` целиком? Но в целом то вроде это и не требуется, как я и говорил, требуется покрыть всего лишь несколько вариантов составных частей

И по поводу `structural_id`, сорри, я может не помню, но я ничего не предлагал вроде как

2022-06-17 16:35 UTC, Dreamlone commented on fedot/preprocessing/cache.py
> +    return f'{pipeline_id}_{data_id}'
Внимательно всмотрелся в код) Ага, предлагаю производить проверку на основе такой штуки, разве что название лучше заменить, а то у нас есть `structural_id` уже

2022-06-30 11:29 UTC, IIaKyJIuH commented
Так, на текущий момент получается примерно такая картина по кешированию энкодера и импьютера (раньше кешировался весь `DataPreprocessor`):
![image](https://user-images.githubusercontent.com/38308131/176666283-549674e9-09fe-463b-81af-591ebdc5f3eb.png)

Прирост небольшой, но хоть хуже не стало.
Теперь поиграюсь чуток с `id`, который является ключом в БД, и посмотрю, как это повлияет на результаты.

2022-06-30 12:28 UTC, nicl-nno commented
Выглядит как адекватный результат - действительно препроцессор не столь уж тяжел, чтобы прирост был больше.

2022-07-01 15:24 UTC, IIaKyJIuH commented on fedot/preprocessing/cache.py
> +    return f'{pipeline_id}_{data_id}'
Как ни странно, эффективнее получается со старой эвристикой на ключ препроцессора, который сохраняется в БД.

2022-07-01 15:55 UTC, nicl-nno commented on examples/advanced/pipelines_caching.py
> +import collections
Есть предложение такие сложные примеры перед мержом в мастер убрать и вынести в отдельный репозиторий для статьи (что-то вроде automl-peformance-improvement-paper).

2022-07-01 15:57 UTC, nicl-nno commented on fedot/preprocessing/cache.py
> +from contextlib import contextmanager, nullcontext
А может этот модуль тоже отправить в caching, переназав в preprocessing_cache? Или будут проблемы с зависимостями?

2022-07-01 15:57 UTC, nicl-nno commented on fedot/preprocessing/cache.py
> +from contextlib import contextmanager, nullcontext
А может этот модуль тоже отправить в caching, переназав в preprocessing_cache? Или будут проблемы с зависимостями?

Аналогично про cache_db.

2022-07-01 15:58 UTC, nicl-nno commented on fedot/preprocessing/cache.py
> +from contextlib import contextmanager, nullcontext
Аналогично про cache_db ниже.

2022-07-01 16:56 UTC, IIaKyJIuH commented on fedot/preprocessing/cache.py
> +from contextlib import contextmanager, nullcontext
Без проблем можно переназвать и поместить всё в одном месте, так будет прозрачнее, да

2022-07-01 17:00 UTC, IIaKyJIuH commented on examples/advanced/pipelines_caching.py
> +import collections
Зависит от того, как выглядит идеальный пример в проекте.
То есть, на что в примерах делается упор, что нужно, а что лучше не надо показывать.
?
Могу согласиться с тем, что кеширование не про сам фреймворк, конечно, а что-то периферийное

2022-07-01 17:11 UTC, nicl-nno commented on examples/advanced/pipelines_caching.py
> +import collections
Я бы сказал, что примеры - это демонстрация той функциональности, которую может использовать пользователь (пусть и очень продвинутый). А тут вроде скорее эксперимент.

2022-07-04 13:09 UTC, IIaKyJIuH commented on fedot/preprocessing/cache.py
> +from contextlib import contextmanager, nullcontext
[Done](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-cca7098181061dfaa9f40ad21f07edae4e5b35e240e51af77368d8003d4724ff)

2022-07-05 08:28 UTC, IIaKyJIuH commented on examples/advanced/pipelines_caching.py
> +import collections
Создал отдельный репозиторий, норм?

https://github.com/IIaKyJIuH/fedot-performance-improvement-benchmark

2022-07-05 08:40 UTC, nicl-nno commented on examples/advanced/pipelines_caching.py
> +import collections
Ага. Перекинь только сразу в https://github.com/ITMO-NSS-team. Инвайт выслал.

2022-07-05 08:40 UTC, nicl-nno approved these changes

2022-07-05 08:58 UTC, IIaKyJIuH commented on examples/advanced/pipelines_caching.py
> +import collections
[Done](https://github.com/ITMO-NSS-team/fedot-performance-improvement-benchmark)

2022-07-05 11:21 UTC, Dreamlone approved these changes

2022-07-05 11:21 UTC, Dreamlone commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Я бы предложил спустить эти новые параметры в именованные аргументы, в явно задаваемых params все таки стоит держать только ключевые параметры, которые будут использовать пользователи, все более тонкое пусть будет в composer_tuner_params. Хотя в целом обсуждаемо - все таки кэширование напрямую не относится ни к composer, ни к tuner. Но я в любом случае предлагаю туда сгрузить

2022-07-05 11:21 UTC, Dreamlone commented on fedot/core/caching/pipelines_cache_db.py
> +            )
Вроде тут достаточно места, чтобы уместить все в одну строку

2022-07-05 11:21 UTC, Dreamlone commented on fedot/core/caching/preprocessing_cache.py
> +    Stores/loads preprocessors for pipelines to decrease time for fitting preprocessor.
Я бы здесь попросил поподробнее расписать что кэшируется не весь препроцессор, а 1) только импутеры и энкодеры и 2) делается это только для табличных данных

2022-07-05 11:21 UTC, Dreamlone commented on test/unit/test_logger.py
> +from test.unit.utilities.test_pipeline_import_export import create_four_depth_pipeline
Лишний импорт

2022-07-05 13:18 UTC, IIaKyJIuH commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Я считаю, что тогда лучше вообще добавить ещё один словарь, в котором предполагается держать все ключи, которые связаны с "опциональными возможностями".
Туда можно включить ещё, например, `n_jobs` и `safe_mode`

2022-07-05 13:21 UTC, IIaKyJIuH commented on fedot/core/caching/pipelines_cache_db.py
> +            )
[Это правда](https://github.com/nccr-itmo/FEDOT/pull/707/commits/66667f3db3893c05b5890f61cdb1ff569d663cb3#diff-59f1a2c290703dcb41b53e915d8a7b035bf74ae63ef7d631b9e02ca612742e56R35)

2022-07-05 13:22 UTC, IIaKyJIuH commented on fedot/core/caching/preprocessing_cache.py
> +    Stores/loads preprocessors for pipelines to decrease time for fitting preprocessor.
[Done](https://github.com/nccr-itmo/FEDOT/pull/707/commits/66667f3db3893c05b5890f61cdb1ff569d663cb3#diff-f119636507698e1500665ba8fdc41cc99f7f4957d8ba1e6f119dd57aea83c562R21-R22)

2022-07-05 13:39 UTC, Dreamlone commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Вся идея как раз была в том, чтобы не плодить новых аргументов - так проще соблюдать совместимость, а это очень важно для API. Тем более, `n_jobs` впомлне себе важная и часто используемая штука

2022-07-06 10:38 UTC, IIaKyJIuH commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Окей, попробовал реализовать твою идею [в этом коммите](https://github.com/nccr-itmo/FEDOT/pull/707/commits/0cc9be0669af8112398074a9ebc157d06ebd4e35).

Заодно включил кеширование пайплайнов по умолчанию.

2022-07-06 12:44 UTC, Dreamlone commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Кул, можно ещё и use_preprocessing_cache тоже поставить True раз по результатам экспериментов это помогает немного эффективнее производить процесс эволюции

2022-07-06 15:07 UTC, nicl-nno commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Можно в API включать/выключать флаг в зависимости от типа данных. Ну и в перспективе думаю и для не-табличных данных понадобится препроцессинг.

2022-07-07 10:28 UTC, IIaKyJIuH commented on fedot/api/main.py
> +                 use_pipelines_cache: bool = False,
Сделал [такие проверки](https://github.com/nccr-itmo/FEDOT/pull/707/files#diff-f119636507698e1500665ba8fdc41cc99f7f4957d8ba1e6f119dd57aea83c562R52-R55)

2022-07-08 13:01 UTC, merged