622 logger as singleton
nccr-itmo/FEDOT pull request #710
Opened 2022-06-08 09:18 UTC by maypink

Logger was remade as Singleton. Now the logger is initialized on the first call and can always be called like `Log()`. 
Possible problems:
- Logger always writes logs with the same name and to the same directory with which it was first initialized
- default logger now can be removed

2022-06-08 10:00 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        Log().message('AutoML started. Parameters tuning: {}. ''Set of candidate models: {}. '
Выглядит достаточно 
Необходимость везде писать Log() выглядит несколько громоздкой. Может лучше сделать по аналогии с станартным питоновским логгером?

![image](https://user-images.githubusercontent.com/5711814/172589356-3b8fcde3-015e-4792-9ec1-690df704f0be.png)
https://docs.python.org/3/howto/logging.html

2022-06-08 10:03 UTC, Dreamlone commented
Мне кажется, нам тут сейчас нужно решить несколько глобальных вопросов. Например, готовы ли мы использовать один глобальный логгер или стоит дробить их по местам, в которых они вызываются, ну и там у Майи вроде ещё парочка спорных вопросов была. @maypink опиши их в сообщении ниже поподробнее, чем это сейчас сделано в описании PR

2022-06-08 10:32 UTC, maypink commented
меня прежде всего смущает, что логгер пишет все логи под одним именем, с которым он был инициализирован в первый раз. казалось бы, если есть возможность точно указать на место, откуда пришел лог, то не хотелось бы этой возможности лишаться. 
также при текущей реализации нельзя писать логи по разным файлам в рамках одного запуска. мы этим кажется и не пользовались до этого (все логи писались просто в дефолтный log.log), но мало ли кому-то актуально

2022-06-08 11:29 UTC, gkirgizov commented
Я бы такие мысли добавил:
- Несколько файлов, пожалуй, и не нужно (во-первых, непонятно как за ними следить, во-вторых, непонятно, зачем бы это было нужно -- даже крупные системы обычно один глобальный лог файл имеют; главное чтобы по нему было удобно искать и фильтровать его).
- Вместо нескольких файлов лучше просто иметь логгеры с конкретным префиксом, мол, из какой подсистемы пришло сообщение. Например, это может так выглядеть, что в одном месте получаем что-то вроде `self.log = Logger.get_handler(prefix='Optimiser)`, а потом уже используем внутри оптимизатора этот `self.log`.

2022-06-08 11:33 UTC, gkirgizov commented
Еще возникает вопрос многопроцессорной обработки. Например, в `MultiprocessingDispatcher` лог, кажется, может использоваться несколькими процессами. Этот случай надо  обработать и протестировать.

Вообще говоря, самим многопроцессорную синхронизацию (если станет понятно, что она нужна), реализовывать не нужно -- и лучше готовую библиотечку какую-то подтянуть, которая с этим справляется. Я не в курсе, обрабатывает ли это дефолтный `python.logging`

2022-06-15 06:38 UTC, IIaKyJIuH requested changes
Нашёл старое использование логгера ещё тут: [adapters.py](https://github.com/nccr-itmo/FEDOT/blob/622-logger-as-singleton/fedot/core/optimisers/adapters.py)

2022-06-15 06:38 UTC, IIaKyJIuH commented on fedot/core/utilities/grouped_condition.py
> +        self._log = default_log(__name__)
здесь тоже, как я понимаю, должно быть упоминание класса в параметре функции
```
self._log = default_log(self.__class__.__name__)
```

2022-06-15 06:38 UTC, IIaKyJIuH commented on test/unit/test_logger.py
> +    expected_number_of_loggers = 14
Вообще я думал, что получится класс `Log` сделать синглтоном, чтобы этот тест был даже не нужен, потому что инстанс был всегда один, это реально?

2022-06-15 08:40 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/simple/logger_multiproc_example.py`](https://github.com/nccr-itmo/FEDOT/blob/ee0bf33a55acecfce9b2531a9434218926816ac5/examples/simple/logger_multiproc_example.py):

> [Line 57:1](https://github.com/nccr-itmo/FEDOT/blob/ee0bf33a55acecfce9b2531a9434218926816ac5/examples/simple/logger_multiproc_example.py#L57): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-06-15 14:58 UTC, nicl-nno commented on fedot/core/log.py
> +def default_log(prefix: str,
Я бы задал дефолтный префикс тут

2022-06-21 13:03 UTC, maypink commented on fedot/api/api_utils/api_composer.py
> +        Log().message('AutoML started. Parameters tuning: {}. ''Set of candidate models: {}. '
Архитектура стала совсем другой, логгер вызывается почти как раньше `self.log = default_log(self.__class__.__name__)`

2022-06-21 13:04 UTC, maypink commented on fedot/core/utilities/grouped_condition.py
> +        self._log = default_log(__name__)
done

2022-06-21 13:05 UTC, maypink commented on test/unit/test_logger.py
> +    expected_number_of_loggers = 14
все, теперь все именно так

2022-06-21 13:16 UTC, maypink commented
Now Log is a sington. Logs are always written to the same file with which the Log was initialized for the first time. It is possible to write logs on behalf of any class (most cases) 
```
self.log = default_log(self.__class__.__name__)
```
or behalf of any other name using LoggerAdapter. Multiprocessing is not implemented within this pull request.

2022-06-22 08:01 UTC, gkirgizov commented on fedot/core/log.py
> +        file_handler = RotatingFileHandler(self.log_file)
RotatingFileHandler штука полезная, но его особо не имеет смысла с дефолтными параметрами создавать. В `maxBytes` & `backupCount` бы поставить какие-то разумные значения.

2022-06-22 08:04 UTC, gkirgizov commented on fedot/core/log.py
>              handler.close()
Кажется, вот эта функция `release_handlers` нигде не используется в итоге. И нужно ли нам вообще явно закрывать хэндлеры? Я вот не уверен

2022-06-22 08:05 UTC, gkirgizov commented on fedot/core/log.py
>              handler.close()
Проперть `handlers` тоже только здесь вызывается

2022-06-22 08:07 UTC, gkirgizov commented on fedot/core/log.py
> +        return f'LoggerAdapter object for {self.logger.name} module'
Мы же тут в классе `Log`

2022-06-22 08:20 UTC, gkirgizov commented on fedot/core/operations/evaluation/operation_implementations/models/svc.py
> +from fedot.core.log import LoggerAdapter
много таких лишних импортов осталось по файлам

2022-06-22 08:24 UTC, gkirgizov commented on test/unit/test_logger.py
>      assert str(test_default_log) == expected_str_value
мб проверять просто что переданный префикс есть в str(logger)? а то хрупкий тест получается. да и не особо что-то важное он тестирует в целом

2022-06-22 09:21 UTC, Dreamlone commented on fedot/core/log.py
> +    """ Log object to store logger singleton and log adaters
очепятка

2022-06-22 09:21 UTC, Dreamlone commented on fedot/core/operations/operation_template.py
> +        self.log = default_log(self.__class__.__name__)
`nit`: Может для удобства использования передавать в `default_log` не сам префикс, а просто объект, а уже внутри реализовать вытаскивание `.__class__.__name__`?

2022-06-22 10:34 UTC, IIaKyJIuH requested changes

2022-06-22 10:34 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
>              content = file.readlines()
На `pathlib` это может выглядеть так:

```python
if Path(DEFAULT_LOG_PATH).exists():
    content = Path(DEFAULT_LOG_PATH).read_text()
```

2022-06-22 10:34 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
> +    # assert not any('Unexpected: OptNode found in PipelineAdapter instead' in log_message for log_message in content)
Почему закомментировала? И дальше (580 строки) тоже

2022-06-22 10:34 UTC, IIaKyJIuH commented on test/unit/test_logger.py
> +    SingletonMeta._instances = {}
Я бы добавил в каждую функцию, где есть такая инициализация, фикстуру:
```python
@pytest.fixture
def singleton_cleanup():
    SingletonMeta._instances = {}
    yield
```

2022-06-22 10:36 UTC, Dreamlone commented on fedot/core/log.py
> +DEFAULT_LOG_PATH = os.path.join(default_fedot_data_dir(), 'log.log')
А поясни плиз почему pathlib предпочтительнее?

2022-06-24 13:02 UTC, maypink commented on fedot/core/log.py
> +DEFAULT_LOG_PATH = os.path.join(default_fedot_data_dir(), 'log.log')
За pathlib тот момент 
![image](https://user-images.githubusercontent.com/57305249/175540674-316745e5-eefb-413c-85de-3d9fb4018d71.png)
И плюс и правда некрасиво указывать в docstring'ах, что аргумент это путь, в то время как это строка путя (непутю)
[Anyway done](https://github.com/nccr-itmo/FEDOT/pull/710/commits/a40c1f08578ac8fc72606e9cee023470e6ee11a7#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR13)

2022-06-24 13:03 UTC, maypink commented on fedot/core/log.py
> +        file_handler = RotatingFileHandler(self.log_file)
За все тесты капает 20кк байт логов --> поставила 100кк и 1 backup

2022-06-24 13:05 UTC, maypink commented on fedot/core/log.py
>              handler.close()
[теперь используется :)](https://github.com/nccr-itmo/FEDOT/pull/710/commits/0d92b525edf4ce82d89c5d8ff7889b3fa5e264e6#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R562)

2022-06-24 13:06 UTC, maypink commented on fedot/core/operations/automl.py
> +from fedot.core.log import LoggerAdapter
[теперь разгром после вечеринки убран](https://github.com/nccr-itmo/FEDOT/pull/710/commits/7c5e39bb53723ce5283df58a9b024f21c666594b)

2022-06-24 13:08 UTC, maypink commented on fedot/core/log.py
> +        return f'LoggerAdapter object for {self.logger.name} module'
[и правда, поменяла](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR116)

2022-06-24 13:09 UTC, maypink commented on fedot/core/log.py
> +class LoggerAdapter(logging.LoggerAdapter):
Использования почистила
Про передачу логгера: можно либо не писать изнутри функции логи, либо инициализовать внутри отдельный адаптер. Первое отпадает сразу, а во втором случае, кажется, теперяется информация о том, откуда пришел лог

2022-06-24 13:09 UTC, maypink commented on fedot/core/log.py
> +                                                        {'class_name': prefix})
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR135)

2022-06-24 13:10 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/models/svc.py
> +from fedot.core.log import LoggerAdapter
done

2022-06-24 13:10 UTC, maypink commented on test/unit/test_logger.py
>      assert str(test_default_log) == expected_str_value
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R91)

2022-06-24 13:11 UTC, maypink commented on test/unit/test_logger.py
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R105)

2022-06-24 13:11 UTC, maypink commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +        self.logger.info("Available operations are not taken into account when "
обсудиди очно

2022-06-24 13:12 UTC, maypink commented on fedot/core/operations/operation_template.py
> +        self.log = default_log(self.__class__.__name__)
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR154-R155)

2022-06-24 13:13 UTC, maypink commented on fedot/core/composer/random_composer.py
> +    def __init__(self, optimiser: 'RandomSearchOptimiser', composer_requirements: ComposerRequirements = None):
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-102541c50febbcdbe40f44afc4a2b05e9b0c41e683f2290a5c48deabf526c03cR17)

2022-06-24 13:14 UTC, maypink commented on fedot/core/log.py
> +    :param verbose_level: level of detailing
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR146)

2022-06-24 13:14 UTC, maypink commented on fedot/core/log.py
> +    :param output_verbosity_level: verbosity level of logger
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR40)

2022-06-24 13:17 UTC, maypink commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +    if logger.verbosity_level < 40:
кажется, в этом месте смысл не в проверке корректности уровня, а в его изменении в зависимости от исходного значения. энивэй [привела к норм виду ](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-3dec8e358a7f2feec92ac1b3c93ee16cafa408e3f1a56829f01f063d8580a3baR111)

2022-06-24 13:18 UTC, maypink commented on test/unit/optimizer/test_gp_operators.py
>              content = file.readlines()
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R559)

2022-06-24 13:18 UTC, maypink commented on test/unit/optimizer/test_gp_operators.py
> +    # assert not any('Unexpected: OptNode found in PipelineAdapter instead' in log_message for log_message in content)
[вернула](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27L567)

2022-06-24 13:19 UTC, maypink commented on test/unit/test_logger.py
> +    SingletonMeta._instances = {}
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R29)

2022-06-27 07:15 UTC, IIaKyJIuH commented on fedot/core/log.py
> +DEFAULT_LOG_PATH = os.path.join(default_fedot_data_dir(), 'log.log')
Круто!

2022-06-27 10:15 UTC, IIaKyJIuH requested changes

2022-06-27 10:15 UTC, IIaKyJIuH commented on fedot/core/operations/automl.py
> +from fedot.core.log import LoggerAdapter
Молодец, это правда большая уборка)

Правда, есть ещё одно место - [classification_pipelines.py](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-fd42f420f0f8fae7814076628e9559d3dd30277ae7105cca51f8e4345c499eb4)

2022-06-27 11:25 UTC, gkirgizov commented on fedot/core/log.py
> +class LoggerAdapter(logging.LoggerAdapter):
а разве из контекста (предыдущих сообщений в логе) не должно ли стать понятно, откуда это?

2022-06-28 12:56 UTC, maypink commented on fedot/core/log.py
> +class LoggerAdapter(logging.LoggerAdapter):
[deistvitel'no](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-2b5f3f03a740803202f4cd9b4bc5da3b6219f5f062ee654a7bc8812a894b3084R29)

2022-06-28 12:57 UTC, maypink commented on fedot/core/log.py
> +    """ Log object to store logger singleton and log adaters
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR37)

2022-06-28 13:00 UTC, maypink commented on examples/simple/pipeline_log.py
> +    log = Log(logger_name='logger', log_file=log_file).get_adapter('pipeline_log')
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-f9b9329242fd0f09f20c10ff7710dc677b1bd251846e4f8dca37ac0763f4814fR18)

2022-06-28 13:01 UTC, maypink commented on test/unit/api/test_assumption_builder.py
> +    default_log('FEDOT logger', verbose_level=10)
посмотрела еще раз, [он здесь вообще не нужен)](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-be65e1c79fa1d98e6d47a6679632c6bf60ee1eff445c691daebf8c2538eb8df6L105)

2022-06-28 13:02 UTC, maypink commented on test/unit/optimizer/test_gp_operators.py
> +    test_file_path = os.path.join(str(os.path.dirname(__file__)), 'log.log')
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R510)

2022-06-28 13:03 UTC, maypink commented on test/unit/test_logger.py
> +        os.remove(logger.log_file)
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R39)

2022-06-28 13:03 UTC, maypink commented on test/unit/test_logger.py
> +    expected_logger_info_level = 20
угу, [поправила](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R44) везде уровни

2022-06-28 13:04 UTC, maypink commented on test/unit/test_logger.py
[done](https://github.com/nccr-itmo/FEDOT/pull/710/files#diff-0fd1096eb3841ab4bb0bd50137b8718e434611c0afed1f957bc6149fd86ba594R73-R75)

2022-06-29 12:20 UTC, IIaKyJIuH commented on fedot/core/operations/automl.py
> +from fedot.core.log import LoggerAdapter
Умница!

2022-06-29 12:26 UTC, IIaKyJIuH commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +from fedot.core.log import default_log
great)

2022-06-29 12:29 UTC, IIaKyJIuH commented on test/unit/test_logger.py
> +    expected_logger_info_level = 20
Просто супер

2022-06-29 13:13 UTC, IIaKyJIuH requested changes

2022-06-29 13:13 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
> +                                        ind=Individual(linear_two_nodes), requirements=composer_requirements).graph
`max_depth=3` пропал, норм?

2022-06-29 13:44 UTC, maypink commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                              disable=not show_progress or self.log.verbosity_level == logging.NOTSET):
мне наоборот кажется, что сейчас максимально внятно написано. если ты к тому, что прогресс бар нужно отключать, когда у нас низкий уровень детализации (error или critical), то я бы и в таких случаях его оставляла

2022-06-29 22:27 UTC, maypink commented on test/unit/optimizer/test_gp_operators.py
> +                                        ind=Individual(linear_two_nodes), requirements=composer_requirements).graph
[done](https://github.com/nccr-itmo/FEDOT/pull/710/commits/64ca4da0e02d8a7ee4c4a1b28585062e8d518c5c#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R221)

2022-06-30 10:54 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                              disable=not show_progress or self.log.verbosity_level == logging.NOTSET):
Ок.
В конце концов, тема не этого PR уже.

2022-06-30 11:04 UTC, IIaKyJIuH approved these changes

2022-06-30 14:49 UTC, nicl-nno approved these changes

2022-07-01 12:08 UTC, gkirgizov approved these changes

2022-07-01 12:44 UTC, merged