Update statsmodels models
nccr-itmo/FEDOT pull request #712
Opened 2022-06-08 10:09 UTC by valer1435

Hotfix that adds test for checking correctness of working specific operations (ar, arima) in insample case

2022-06-08 10:25 UTC, Dreamlone requested changes

2022-06-08 10:25 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> -    simple_length = 2
Предлагаю переименовать метод, что проверяется как AR-like модели могут справляться с новыми данными

2022-06-08 10:25 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +                            TsForecastingParams(forecast_length=one_step_length))
Сюда бы комментарий, объясняющий что именно тут происходит

2022-06-08 10:25 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +                                              y_pred=predict) < 1
Кстати проверял, проходит ли тест с таким порогом, если убрать из операций ту проверку на соответствие индексов?

2022-06-10 06:53 UTC, valer1435 commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +                            TsForecastingParams(forecast_length=one_step_length))
[.Добавил комментарии](https://github.com/nccr-itmo/FEDOT/pull/712/commits/6fbcd3d5a5d100b80366cfa55675904738df8c22)

2022-06-10 06:53 UTC, valer1435 commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> -    simple_length = 2
[Переименовал](https://github.com/nccr-itmo/FEDOT/pull/712/commits/6fbcd3d5a5d100b80366cfa55675904738df8c22#diff-7123b84bf81103cae71a44e239a4c00680ee128a965a37fd493978f4fb203fbdR94)

2022-06-10 06:53 UTC, valer1435 commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +                                              y_pred=predict) < 1
Да, работает

2022-06-10 13:23 UTC, Dreamlone approved these changes

2022-06-14 12:45 UTC, valer1435 commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +        'value']
[Разбил ](https://github.com/nccr-itmo/FEDOT/pull/712/commits/51f306d9b6c97c344ab1a70571c24fcb8b902478#diff-7123b84bf81103cae71a44e239a4c00680ee128a965a37fd493978f4fb203fbdR102)

2022-06-14 12:49 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +        'value']
Да ты издеваешься
![image](https://user-images.githubusercontent.com/52418437/173580830-1227c02d-4792-4cba-b939-496d87934576.png)

2022-06-14 13:29 UTC, merged

2022-06-14 13:30 UTC, valer1435 commented on test/unit/pipelines/test_pipeline_ts_wrappers.py
> +        'value']
Уберу в своем новом pr