Added simple implementation of ObjectiveEvaluationDispatcher
nccr-itmo/FEDOT pull request #715
Opened 2022-06-08 14:44 UTC by YamLyubov

Added simple implementation of ObjectiveEvaluationDispatcher maps ObjectiveFunction over population.
#711

2022-06-08 14:56 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class Dispatcher(ObjectiveEvaluationDispatcher):
Название сходу выглядит недостаточно конкретным - я бы скорее подумал что Dispatcher - это базовый класс для ObjectiveEvaluationDispatcher, а не наоборот.

2022-06-08 14:59 UTC, nicl-nno commented
Cмущает что новый класс нигде не используется и не тестируется.

2022-06-09 09:46 UTC, gkirgizov commented
> Cмущает что новый класс нигде не используется и не тестируется.

Я планировал, что тесты будут добавлены в https://github.com/nccr-itmo/FEDOT/issues/709, но пожалуй ты прав, этот класс нужно в рамках этого PR протестировать.
@YamLyubov добавишь тесты на него в эту ветку?

Насчет использования -- это задел на мои будущие изменения. Это будет реализация "оценщика целевой функции" по умолчанию. На данный момент, кстати, можно использовать его в `RandomMutationSearchOptimizer` вместо MultiprocessingDispatcher, чтобы этот оптимизатор был эдаким bare minimum example. @YamLyubov, заменишь реализацию?

2022-06-09 09:48 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +class Dispatcher(ObjectiveEvaluationDispatcher):
Хорошо, подумаю над более информативным названием

2022-06-10 07:43 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/unit/optimizer/test_evaluation.py`](https://github.com/nccr-itmo/FEDOT/blob/b2764343f9cdf8156837108764713d992c3e5d05/test/unit/optimizer/test_evaluation.py):

> [Line 21:1](https://github.com/nccr-itmo/FEDOT/blob/b2764343f9cdf8156837108764713d992c3e5d05/test/unit/optimizer/test_evaluation.py#L21): [E303](https://duckduckgo.com/?q=pep8%20E303) too many blank lines (3)

2022-06-10 15:14 UTC, nicl-nno commented on test/unit/optimizer/test_evaluation.py
> +    return input_data
Может все эти функции импортировать из других тестов? Вроде конкретная структура пайплайна не особо важна.

2022-06-10 15:15 UTC, nicl-nno commented on test/unit/optimizer/test_evaluation.py
> +def test_multiprocessingdispatcher_without_timelimit_without_multiprocessing(classification_dataset):
Какое-то громоздкое название - multiprocessing_without_multiprocessing

2022-06-15 14:19 UTC, gkirgizov requested changes
Еще коммент от Pep8 bot пофиксить

2022-06-17 09:16 UTC, gkirgizov approved these changes

2022-06-17 09:20 UTC, gkirgizov commented
Перед мержем перезапусти только тесты на python 3.7, чтобы мастер зеленый был. Там один тест временами падает

2022-06-17 10:01 UTC, merged

2022-06-18 09:53 UTC, nicl-nno commented
Обратите внимание, что в этом PR-е было много "лишних" коммитов перед мержем. 

Поэтому теперь гитхаб думает, что у него 7 авторов)
![image](https://user-images.githubusercontent.com/5711814/174432526-698ac69d-cbfd-4ffa-bc39-82a019cd1044.png)