Refactor ApiComposer for simpler logic
nccr-itmo/FEDOT pull request #716
Opened 2022-06-08 15:36 UTC by gkirgizov

Many small changes in ApiComposer, mostly for readbility and easier parameter passing:
- Simpler passing of initial assumptions
- Better separation between ApiComposer / Composre / ComposerBuilder (ApiComposer & Composer itself previously took some parts that better should be in ComposerBuilder)
- Some simplification of preset logic and code duplication removal

2022-06-08 15:36 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`cases/multi_modal_genre_prediction.py`](https://github.com/nccr-itmo/FEDOT/blob/1b7449d08a29b2a030188b19137dd7a423a67247/cases/multi_modal_genre_prediction.py):

> [Line 46:121](https://github.com/nccr-itmo/FEDOT/blob/1b7449d08a29b2a030188b19137dd7a423a67247/cases/multi_modal_genre_prediction.py#L46): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2022-06-09 07:56 UTC, Dreamlone requested changes
Пока пробежался косметически - позапускать примеры с переработанными модулями не получилось, вываливалась ошибка `TypeError: 'ABCMeta' object is not subscriptable`. Как она уйдёт - более пристально пробегусь по коду

2022-06-09 07:56 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                                      logger=log, cache=self.cache, n_jobs=api_params['n_jobs'])
Может чтобы избавиться от нагромождения кода в Api Composer стоит выделить класс, которые занимается подготовкой и обучением начальных приближений? И тогда этот весь код уйдёт в него

2022-06-09 07:56 UTC, Dreamlone commented on fedot/api/api_utils/assumptions/assumptions_builder.py
> +    if task_type is TaskTypesEnum.ts_forecasting and 'lagged' not in available_operations:
FYI, присутствие lagged операции вовсе не обязательно, чтобы пайплайн был корректным для временных рядов. Например, любая non-lagged (это тег такой) модель может работать с временными рядами нативно без всяких преобразований. И что самое главное, такая модель сама внутри себя перед формированием output'а занимается преобразованием предсказанного одномерного массива в траекторную матрицу. 

Таки образом, какая-нибудь AR будет в каком-то роде заниматься этим самым lagged преобразованием. Что-то вроде "data_type.ts -> `AR` -> data_type.table". Также не стоит и забывать про почти полный аналог lagged - sparse_lagged
Но в целом мне кажется все равно стоит перестраховываться. От lagged в списке операций для композирования точно хуже не станет)

2022-06-09 07:56 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +                                                                 self.timer.datetime_composing, available_operations)
Может это тоже изолировать для красоты? Например в отдельную функцию / метод

2022-06-09 07:56 UTC, Dreamlone commented on fedot/api/main.py
> +        # TODO: remove, unnecessary method
Так можем прямо сейчас его и убрать?)

2022-06-09 07:56 UTC, Dreamlone commented on fedot/api/main.py
> +        best_candidates = self.history.archive_history[-1]
Сорри за глупый вопрос, а где именно происходит упорядочивание по фитнесу? А то я так сходу не смог найти

2022-06-09 09:54 UTC, gkirgizov commented on fedot/api/main.py
> +        best_candidates = self.history.archive_history[-1]
тут я полагаюсь на то, что в `archive_history` пишется история как раз архива -- а он всегда упорядочен. То есть то, что было в `self.best_models` -- это то же самое, что `self.history.archive_history`

2022-06-09 09:54 UTC, gkirgizov commented on fedot/api/main.py
> +        best_candidates = self.history.archive_history[-1]
добавлю коммент описывающий это

2022-06-09 11:06 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                                      logger=log, cache=self.cache, n_jobs=api_params['n_jobs'])
Создам, пожалуй, отдельный issue на это.
Вот: https://github.com/nccr-itmo/FEDOT/issues/717
Либо сам либо Любе отдам

2022-06-09 12:15 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                                                                 self.timer.datetime_composing, available_operations)
Много параметров в метод придется передавать, эти строчки особо не выносятся отдельно.
Но мб вместе с initial assumptions получится во что-то одно абстрагировать в рамках #717

2022-06-09 13:45 UTC, Dreamlone commented on fedot/api/main.py
> +        best_candidates = self.history.archive_history[-1]
Принял, спасибо за разъяснения

2022-06-10 13:24 UTC, ChrisLisbon approved these changes

2022-06-16 11:11 UTC, merged