Individuals inheritance fix
nccr-itmo/FEDOT pull request #724
Opened 2022-06-15 08:31 UTC by MorrisNein

2022-06-15 10:32 UTC, IIaKyJIuH requested changes

2022-06-15 10:32 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                    lambda individual: self._mutate(individual, valid_parents=selected_individuals), new_population
Вроде же можно оставить без лямбды, через "functools.partial", м?

2022-06-15 10:43 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                    lambda individual: self._mutate(individual, valid_parents=selected_individuals), new_population
Действительно, рассматривал такую альтернативу. Просто не был уверен, какой из вариантов сюда лучше подходит.

2022-06-15 10:47 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                    lambda individual: self._mutate(individual, valid_parents=selected_individuals), new_population
Спасибо за подсказку, [поправил](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R223)

2022-06-15 11:18 UTC, IIaKyJIuH requested changes

2022-06-15 11:18 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if all(parent_individual in valid_parents for parent_individual in parent_operator.parent_individuals):
Возможна ли ситуация, что у операторов одинаковые родительские индивиды? Если да, то в таком случае мы бы сделали одно и то же дважды, чего бы не хотелось. Если это актуально, я вижу такое решение:
```python
parent_operators = {id(po.parent_individuals): po for po in individual.parent_operators}.values()
for parent_operator in reversed(parent_operators):
    ...
```

2022-06-15 12:29 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if all(parent_individual in valid_parents for parent_individual in parent_operator.parent_individuals):
В текущей реализации такое невозможно. Более того, если родители будут проверяться на валидность при каждом вызове, то дальше нулевой итерации мы здесь не уйдём.

Сейчас у индивида будет максимум один невалидный родитель как результат предшествующего скрещивания, не попавший ни в одно поколение.

Как считаешь, с учётом этого такая предусмотрительность здесь подойдёт?

2022-06-15 14:34 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if all(parent_individual in valid_parents for parent_individual in parent_operator.parent_individuals):
Вообще кажется, что в таком случае список индивидов можно отфильтровать проще и заранее, но я не придумал ещё, как.
Думаю, старший разработчик скажет точно.

2022-06-15 20:37 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if all(parent_individual in valid_parents for parent_individual in parent_operator.parent_individuals):
Кажется длина individual.parent_operators в любом случае не особо велика, поэтому цикл не должен влиять на производительность.

2022-06-15 20:40 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                new_population = list(map(partial(self._mutate, valid_parents=selected_individuals), new_population))
Мне кажется эта логика должна быть внутри reproduce.
@gkirgizov ты специально её оставил снаружи?

2022-06-16 18:24 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if all(parent_individual in valid_parents for parent_individual in parent_operator.parent_individuals):
Ну тогда лучше правда не усложнять

2022-06-16 18:24 UTC, IIaKyJIuH approved these changes

2022-06-17 11:11 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                new_population = list(map(partial(self._mutate, valid_parents=selected_individuals), new_population))
Особой задумки не было, просто разделял эволюционные операторы, чтобы основные шаги были в цикле видны.
Можно мутацию убрать в `_reproduce`.

2022-06-17 15:55 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                new_population = list(map(partial(self._mutate, valid_parents=selected_individuals), new_population))
Лучше тогда убрать, т.к. вроде и мутация и кроссовер относяятся к reproduce в логике ЭА

2022-06-17 17:25 UTC, IIaKyJIuH requested changes

2022-06-17 17:30 UTC, IIaKyJIuH requested changes

2022-06-17 17:30 UTC, IIaKyJIuH commented on fedot/core/serializers/coders/opt_history_serialization.py
> +    return [uid_to_individual_map.get(uid, Individual(OptGraph())) if isinstance(uid, str) else uid for uid in uid_list]
Пока что не знаю, но может быть всё-таки эту заглушку для старых историй можно полаконичнее разрешить

2022-06-17 19:47 UTC, MorrisNein commented on fedot/core/serializers/coders/opt_history_serialization.py
> +                                                   uid_to_individual_map=uid_to_individual_map)
Там разный уровень вложенности (в истории просто список списков, а у операторов атрибуты). А преисполниться настолько, чтобы передать произвольный список объектов и сериализовать его in-place, у меня пока не удаётся.

2022-06-17 19:58 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +            assert history_1.individuals[gen_num][ind_num] == history_2.individuals[gen_num][ind_num]
Когда в руках молоток, всё вокруг кажется гвоздём [...........](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R216)

2022-06-17 20:02 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                new_population = list(map(partial(self._mutate, valid_parents=selected_individuals), new_population))
[Done](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R253-R270)

2022-06-17 20:04 UTC, MorrisNein commented on test/unit/composer/test_history.py
> +               for parent_individual in op.parent_individuals)
Спасибо, забыл о них. [Так](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-6a8c56ade7e3e48b91b1c8d2907a4066ec37cd37800908f4a1e8e7a6fd7eae02R200-R202) действительно лучше.

2022-06-17 20:26 UTC, nicl-nno approved these changes

2022-06-18 09:04 UTC, MorrisNein commented on fedot/core/serializers/coders/opt_history_serialization.py
> +    return [uid_to_individual_map.get(uid, Individual(OptGraph())) if isinstance(uid, str) else uid for uid in uid_list]
Целиком [переработал](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-42d9e7dc65d1ac470f8befcc39599bace41874eb80e40cf1d6ae0b336a3c60e1R41-R52) функцию

2022-06-20 08:28 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +            assert history_1.individuals[gen_num][ind_num] == history_2.individuals[gen_num][ind_num]
Это точно)

2022-06-21 12:46 UTC, IIaKyJIuH requested changes

2022-07-06 15:53 UTC, MorrisNein commented on fedot/core/serializers/coders/opt_history_serialization.py
> +        individual = Individual(**MISSING_INDIVIDUAL_ARGS)
Так не должно быть, я это [поправил](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-42d9e7dc65d1ac470f8befcc39599bace41874eb80e40cf1d6ae0b336a3c60e1R52)

2022-07-06 16:04 UTC, nicl-nno requested changes

2022-07-06 16:04 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +        raise ValueError
А это не приведет к проблемам в ситуации, когда копируют структуры, содержащую внутри себя экземпляр Individual?

2022-07-06 16:04 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +             individual: Individual, requirements: 'PipelineComposerRequirements', log: Log,
Сюда (в оптимизатор) абстрация пайплайна просачиваться не должна.

2022-07-06 16:44 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +    def set_fitness_and_graph(self, fitness: Fitness, graph: OptGraph):
Я понимаю, но почему бы не сделать это по-очередно. Вроде всего дважды это операция выполняется.

2022-07-06 17:00 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +    def set_fitness_and_graph(self, fitness: Fitness, graph: OptGraph):
В текущей реализации - да, всего дважды. Идея в том, чтобы ограничить замену графа этапом оценки индивида и в других ситуациях это не позволять. 

Если от этой идеи отказаться, то задавать отдельно ничего не мешает

2022-07-06 19:23 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        ind.set_fitness_and_graph(ind_fitness, ind_graph)
А тут вообще нужна необходимость задавать граф? Кажется он тот же, что и в начале функции?

2022-07-07 11:48 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        ind.set_fitness_and_graph(ind_fitness, ind_graph)
post_eval_callback может заполнить промежуточные метрики в метаданных узлов.

2022-07-07 19:14 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        ind.set_fitness_and_graph(ind_fitness, ind_graph)
ок

2022-07-07 19:16 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +        super().__setattr__('fitness', fitness)
Ок, пусть будет.

2022-07-07 19:18 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/individual.py
> +    def set_fitness_and_graph(self, fitness: Fitness, graph: OptGraph):
Ну парная операция все же выглядит как переусложнение. Раздельные set_fitness и update_graph выглядят семантичнее

2022-07-08 10:52 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:















































* In the file [`test/unit/optimizer/test_gp_operators.py`](https://github.com/nccr-itmo/FEDOT/blob/78cef7579b2819cbe245e21ba152eb76ef84ca9f/test/unit/optimizer/test_gp_operators.py):

> [Line 157:121](https://github.com/nccr-itmo/FEDOT/blob/78cef7579b2819cbe245e21ba152eb76ef84ca9f/test/unit/optimizer/test_gp_operators.py#L157): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (125 > 120 characters)

2022-07-08 11:00 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +             individual: Individual, requirements: 'PipelineComposerRequirements', log: Log,
Убрал обратно типизацию

2022-07-08 11:01 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +    def set_fitness_and_graph(self, fitness: Fitness, graph: OptGraph):
А как насчёт одного общего [метода](https://github.com/nccr-itmo/FEDOT/pull/724/commits/78cef7579b2819cbe245e21ba152eb76ef84ca9f#diff-8e161246b55f94bb4d34baaad9b0cc041c7a4d7e0125307239607c7c6228ec9fL33)?

2022-07-08 11:06 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +        super().__setattr__('uid', uid)
Согласен, [сделал](https://github.com/nccr-itmo/FEDOT/pull/724/commits/78cef7579b2819cbe245e21ba152eb76ef84ca9f#diff-8e161246b55f94bb4d34baaad9b0cc041c7a4d7e0125307239607c7c6228ec9fR24) возможность задать uid при инициализации.

2022-07-08 11:08 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        if ind.fitness.valid:
Мне кажется, в таком случае при достижении тайм-лимита уже оцененные индивиды продолжат попадать обратно из результата оценки, и выход по тайм-лимиту не произойдёт.

2022-07-08 11:10 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +        raise ValueError
Вернул возможность копирования, добавил ворнинги с описанием проблемы.
[Тык](https://github.com/nccr-itmo/FEDOT/pull/724/commits/e806543fe00cdf134a8271476a94b677160e4c00#diff-8e161246b55f94bb4d34baaad9b0cc041c7a4d7e0125307239607c7c6228ec9fR47-R61)

2022-07-08 11:12 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/individual.py
> +            raise ValueError
Теперь [ругается](https://github.com/nccr-itmo/FEDOT/pull/724/files#diff-8e161246b55f94bb4d34baaad9b0cc041c7a4d7e0125307239607c7c6228ec9fR33-R38) словами

2022-07-08 12:33 UTC, IIaKyJIuH requested changes

2022-07-11 09:32 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        if ind.fitness.valid:
Смысл этого ограничения в том, чтобы не запускать дорогостоящее вычисление фитнеса, если лимит времени закончился в ходе оценивание поколения. Но если фитнес уже вычислен - то почему бы его и не вернуть.

2022-07-11 09:34 UTC, nicl-nno approved these changes

2022-07-11 15:15 UTC, IIaKyJIuH commented on fedot/core/serializers/coders/opt_history_serialization.py
> +def _get_individuals_pool_from_generations_list(generations_list: List[List[Individual]]) -> List[Individual]:
Круто!

2022-07-11 16:09 UTC, IIaKyJIuH approved these changes

2022-07-11 21:17 UTC, merged