Tests for evaluation subsystem (fixes 709)
nccr-itmo/FEDOT pull request #725
Opened 2022-06-15 11:05 UTC by YamLyubov

Tests for MultiprocessingDispatcher and PipelineObjectiveEvaluate #709

2022-06-15 11:56 UTC, MorrisNein requested changes
Опционально, можно подумать над объединением части однотипных тестов в один параметризуемый (первый попавшийся под руку [пример](https://github.com/nccr-itmo/FEDOT/blob/9843d2b5f410b159a17526dfc63f8c9efb258859/test/unit/api/test_main_api.py#L125))

2022-06-15 11:56 UTC, MorrisNein commented on test/unit/optimizer/test_data_objective_eval.py
> +    x = 1 / 0
А почему бы тут не сделать `raise` в лоб? Всё равно ведь ничего не вернётся.

Аргумент `graph` нужен для дополнительной проверки корректного использования функции? Или можем обойтись `(*args, **kwargs)`?

2022-06-15 11:56 UTC, MorrisNein commented on test/unit/optimizer/test_data_objective_eval.py
> +def test_pipeline_objective_evaluate_with_timelimit(classification_dataset):
Немножко подушню, извиняюсь, но можно назвать `timelimit` как `time_constraint` в имени теста и переменной, чтобы сохранять однозначность.

2022-06-15 11:56 UTC, MorrisNein commented on test/unit/optimizer/test_evaluation.py
> +    x = 1/0
Тут тот же вопрос, что и к соседнему файлу.

2022-06-15 12:29 UTC, YamLyubov commented on test/unit/optimizer/test_data_objective_eval.py
> +    x = 1 / 0
Да, я думала просто сделать ```raise```, но показалось, что так нагляднее. Наверное сделаю просто raise)  

Тут Graph, потому что Objective в качестве метрики принимает ```Callable[[G], Real]```. По идее да, можно использовать ```(*args, **kwargs)``` и тогда останется
```
def throwing_exception_metric(*args, **kwargs):
    raise Exception
```

2022-06-15 12:39 UTC, MorrisNein commented on test/unit/optimizer/test_data_objective_eval.py
> +    x = 1 / 0
По поводу замены аргументов - дело вкуса. Получается, что разница только в предупреждениях в IntelliSense)

2022-06-15 15:12 UTC, gkirgizov requested changes

2022-06-15 15:12 UTC, gkirgizov commented on test/unit/optimizer/test_evaluation.py
> +    population = [Individual(adapter.adapt(pipeline)) for pipeline in pipelines]
А вообще, этот и следующий тест отличаются только тем, какой dispatcher в них передается -- можно параметризовать тест

2022-06-21 09:17 UTC, gkirgizov requested changes

2022-06-21 09:17 UTC, gkirgizov commented on test/unit/optimizer/test_evaluation.py
> +def test_simple_dispatcher_without_timeout(set_up_tests):
полностью аналогичный код с `test_multiprocessing_dispatcher_with_and_without_multiprocessing`, стоит объединить

2022-06-21 09:17 UTC, gkirgizov commented on test/unit/optimizer/test_evaluation.py
> +def test_simple_dispatcher_with_timeout(set_up_tests):
полностью аналогичный код с `test_multiprocessing_dispatcher_with_timeout` -- мб параметризовать диспечтером и переименовать соответствующе

2022-06-21 09:17 UTC, gkirgizov commented on test/unit/optimizer/test_evaluation.py
> +def test_simple_dispatcher_with_timeout(set_up_tests):
два теста ниже -- аналогичный комментарий

2022-06-21 10:06 UTC, YamLyubov commented on test/unit/optimizer/test_evaluation.py
> +def test_simple_dispatcher_without_timeout(set_up_tests):
Да, по идее это уже сделано. Можно просто убрать ```test_simple_dispatcher_without_timelimit```

2022-06-24 09:34 UTC, merged