Multi_ts API example adding, available_operations and initial_assumption from API bug fixed
nccr-itmo/FEDOT pull request #728
Opened 2022-06-15 14:17 UTC by ChrisLisbon

- available_operations for composers which were set by user were ignored and changed on preset, fixed by check operations before using preset;
- initial_assumption was not used from user input, fixed by including into rewriting parameters list;
- single_drop_mutation could delete all nodes from graph and falls with exeption "IndexError: Cannot choose from an empty sequence" in nex call. Fixed by check if graph.nodes list empty;
- multi_ts data type usage via API example fixed and added to repository.

2022-06-15 15:03 UTC, nicl-nno commented on fedot/api/api_utils/presets.py
> +    available_operations = list(set(composer_requirements.primary + composer_requirements.secondary))
Но эти available_operations же никак дальше не используются.

2022-06-15 15:07 UTC, nicl-nno commented
Хорошо бы покрыть основные фиксы в этом PR-е мини-тестами - чтобы впредь это не отваливалось.

2022-06-15 15:08 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    if graph.nodes:
Добавление узлов будет работать, остальные просто видимо игнорируются

2022-06-15 15:15 UTC, nicl-nno commented on fedot/api/api_utils/presets.py
> +    available_operations = list(set(composer_requirements.primary + composer_requirements.secondary))
А в каком месте они именно используются? Я к тому, чтобы было бы здорово всё делать внутри OperationsPreset.

2022-06-15 15:24 UTC, ChrisLisbon commented on fedot/api/api_utils/presets.py
> +    available_operations = list(set(composer_requirements.primary + composer_requirements.secondary))
на строчку ниже, [туть](https://github.com/nccr-itmo/FEDOT/blob/multi_ts_fix/fedot/api/api_utils/presets.py#L105-L106)

2022-06-16 07:38 UTC, valer1435 reviewed
Было бы неплохо сделать какой-нибудь поясняющий текст, что это за multits такой

2022-06-16 07:38 UTC, valer1435 commented on cases/multi_ts_level_forecasting.py
> +def prepare_data(forecast_length, multi_ts):
Предлагаю либо добавить typeHint'ы или (и) поменять multi_ts на is_multi_ts

2022-06-16 07:38 UTC, valer1435 commented on cases/multi_ts_level_forecasting.py
> +def initial_pipeline():
Насколько я понимаю, Гриша переработал процесс создания пайплайнов через builder. И он просил меня все новые пайплайны строить таким образом. Поэтому попрошу и тебя

2022-06-16 07:38 UTC, valer1435 commented on cases/multi_ts_level_forecasting.py
> +        lagged - ridge \
Кажется описание не соответствует итоговому пайплайну

2022-06-16 07:38 UTC, valer1435 commented on cases/multi_ts_level_forecasting.py
> +def run_multi_ts_forecast(forecast_length, multi_ts):
Тут тоже is_multi_ts выглядит более подходящим

2022-06-16 07:39 UTC, valer1435 requested changes
Стоит добавить описание, что делает multits

2022-06-16 16:59 UTC, pep8speaks commented
Hello @ChrisLisbon! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/optimisers/gp_comp/operators/mutation.py`](https://github.com/nccr-itmo/FEDOT/blob/bb00b93d64a3b4426fedbebe93677c1c48de5092/fedot/core/optimisers/gp_comp/operators/mutation.py):

> [Line 297:18](https://github.com/nccr-itmo/FEDOT/blob/bb00b93d64a3b4426fedbebe93677c1c48de5092/fedot/core/optimisers/gp_comp/operators/mutation.py#L297): [E127](https://duckduckgo.com/?q=pep8%20E127) continuation line over-indented for visual indent

2022-06-17 08:17 UTC, Dreamlone commented on cases/multi_ts_level_forecasting.py
> +def initial_pipeline():
А может просто [отсюда](https://github.com/nccr-itmo/FEDOT/blob/master/examples/simple/time_series_forecasting/ts_pipelines.py) взять один более менее подходящий под начальное приближение?

2022-06-17 08:27 UTC, Dreamlone reviewed
Есть концептуальное предложение. Оно наверно, не к этому PR уже, хотя при желании, может и к этому. В общем: ситуация, когда мы можем задавать один и тот же параметр одновременно двумя разными способами (например напрямую через API и через composer_params как у initial_assumption в этом PR - поправьте меня, если я не прав) не хорошая. Отсюда возникают всякие проблемы с перетиранием одного другим. Подобный баг у нас вообще стал практически перманентным, я сам вроде два PR с его исправлением делал, а что уж говорить про совокупное количество этих исправлений по всей команде. Другая издержка при таком подходе - переусложненный код в API модуле. 

Помнится, в одном из PR Гриши @gkirgizov уже были исправлены какие-то такие вещи.
Предлагаю продолжать в том же духе и как можно скорее это исправить: чем дольше мы тянем, тем больше нам придётся поддерживать это "двойное определение параметров" и тем больше подобных багов у нас будет происходить. So, если есть возможность, было бы здорово в этом PR устранить хотя бы часть проблемных аргументов

2022-06-17 08:27 UTC, Dreamlone commented on test/unit/api/test_api_utils.py
> +    """ """
Сюда бы не забыть добавить описание, раз пустой docstring уже инициализирован

2022-06-17 16:11 UTC, ChrisLisbon commented on fedot/api/api_utils/presets.py
> +    available_operations = list(set(composer_requirements.primary + composer_requirements.secondary))
Рефакторинг Григория решил проблему с available_operations, но я добавила [тест ](https://github.com/nccr-itmo/FEDOT/pull/728/files#diff-33b3da5de920cc340bbc6820f766f3d73a87d0545f26ca587bd630cd5cc8a8d3R148-R161)все равно на всякий случай

2022-06-17 16:12 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    if graph.nodes:
Переместила эту [проверку ](https://github.com/nccr-itmo/FEDOT/pull/728/files#diff-adb53d31d35223b4209ffceadddd7fd47842a77c22c853a98a0df0de267d4325R111-R112)на более высокий уровень

2022-06-17 16:12 UTC, ChrisLisbon commented on cases/multi_ts_level_forecasting.py
> +def prepare_data(forecast_length, multi_ts):
изменила

2022-06-17 16:12 UTC, ChrisLisbon commented on cases/multi_ts_level_forecasting.py
> +def initial_pipeline():
[Взяла](https://github.com/nccr-itmo/FEDOT/pull/728/files#diff-56e05b8c50a4b433b9e6f9e1899ab043f08119dc77e183622a0e80462129f1f4R60)

2022-06-17 16:13 UTC, ChrisLisbon commented on cases/multi_ts_level_forecasting.py
> +        lagged - ridge \
Избавилась от этой функции, просто импортировала пайплайн

2022-06-17 16:17 UTC, nicl-nno commented
> Есть концептуальное предложение. Оно наверно, не к этому PR уже, хотя при желании, может и к этому. В общем: ситуация, когда мы можем задавать один и тот же параметр одновременно двумя разными способами (например напрямую через API и через composer_params как у initial_assumption в этом PR - поправьте меня, если я не прав) не хорошая. Отсюда возникают всякие проблемы с перетиранием одного другим. Подобный баг у нас вообще стал практически перманентным, я сам вроде два PR с его исправлением делал, а что уж говорить про совокупное количество этих исправлений по всей команде. Другая издержка при таком подходе - переусложненный код в API модуле.
> 
> Помнится, в одном из PR Гриши @gkirgizov уже были исправлены какие-то такие вещи. Предлагаю продолжать в том же духе и как можно скорее это исправить: чем дольше мы тянем, тем больше нам придётся поддерживать это "двойное определение параметров" и тем больше подобных багов у нас будет происходить. So, если есть возможность, было бы здорово в этом PR устранить хотя бы часть проблемных аргументов

C этим в целом согласен - не обязательно в этом PR, но в целом переработать эту логику стоит.

2022-06-17 16:18 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if not new_graph.nodes:
А это не нужно и до применения mutation_func мутации проверять?

2022-06-17 16:20 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if not new_graph.nodes:
Ну изначально граф пустым не будет, а вот после применения мутации такое случается, поэтому добавила проверку только тут

2022-06-17 16:20 UTC, nicl-nno commented on test/unit/api/test_api_utils.py
> +    assert model.params.api_params['available_operations'] == available_operations
Хорошо бы ещё проверить, что в финальном пайплайне нет моделей, не входящих в available_operations

2022-06-17 16:24 UTC, nicl-nno commented on test/unit/api/test_api_utils.py
> +    assert model.params.api_params['available_operations'] == available_operations
Тогда может из теста вообще убрать этап с fit - чтобы не создавать иллюзий?

2022-06-17 16:25 UTC, nicl-nno approved these changes

2022-06-17 16:27 UTC, Dreamlone approved these changes

2022-06-17 16:43 UTC, ChrisLisbon commented on test/unit/api/test_api_utils.py
> +    assert model.params.api_params['available_operations'] == available_operations
Это как раз важно, потому что параметр терялся именно на процессе фита при входе данных в композер. А так метод вызывается, данные сквозь композер проходят, и важно что в итоге остаются заданные пользователем параметры

2022-06-19 09:40 UTC, valer1435 approved these changes

2022-06-20 09:18 UTC, merged