Embedding stratify k fold
nccr-itmo/FEDOT pull request #733
Opened 2022-06-17 13:52 UTC by valer1435

This pr solve https://github.com/nccr-itmo/FEDOT/issues/732 issue. DataObjectiveAdvisor was created to advise the most suitable strategy to split data on folds.

2022-06-17 14:27 UTC, aPovidlo requested changes

2022-06-17 14:27 UTC, aPovidlo commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +    def __init__(self, threshold: int = 0.5):
Указываешь, что данная переменная должна быть `int`, но по дефолту делаешь `float`

2022-06-20 05:54 UTC, gkirgizov reviewed
All good, но есть вопрос

2022-06-20 05:54 UTC, gkirgizov commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +        return np.any((uniform_probability - probabilities) / uniform_probability > self.threshold)
Для 2х классов при дефолтном threshold=0.5 будет почти всегда выдавать imbalanced. Наверное, так не должно быть?

2022-06-20 08:14 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +        return np.any((uniform_probability - probabilities) / uniform_probability > self.threshold)
Почему? Тут идея, что если отличие от "идеальной" вероятности по отношению к "идеальной" больше половины - то плохо. Вроде и тесты написал

2022-06-20 10:06 UTC, gkirgizov commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +        return np.any((uniform_probability - probabilities) / uniform_probability > self.threshold)
Я не так прочитал код, ты прав, все ок.
Вот разве что буквально то что ты мне ответил надо бы в док-коммент отправить, ты тут хорошо объяснил.

2022-06-20 10:10 UTC, gkirgizov commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +        return np.any((uniform_probability - probabilities) / uniform_probability > self.threshold)
И еще, `abs(...)` не помешает, кажетс )
Есть тест на несколько классов (больше двух), где один из них большую часть займет? Кажется, для такого упадет сейчас.

2022-06-20 10:29 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_advisor.py
> +    def __init__(self, threshold: int = 0.5):
[done
](https://github.com/nccr-itmo/FEDOT/pull/733/commits/65cfbcc8efe8130237e820b3e8bfac89bece046d#diff-d2efedf0ed60665dfc2383305be29f1fec3ef7d8fbba0e7d8655d58bf9f9502cR11)

2022-06-20 12:28 UTC, aPovidlo approved these changes

2022-06-21 08:30 UTC, gkirgizov approved these changes

2022-06-21 12:25 UTC, merged