Extract fit initiall assumption#717
nccr-itmo/FEDOT pull request #736
Opened 2022-06-20 15:07 UTC by valer1435

This PR is devoted to https://github.com/nccr-itmo/FEDOT/issues/717 issue and separate logic for initial assumption from api composer

2022-06-20 15:39 UTC, ChrisLisbon commented on fedot/api/api_utils/assumptions/assumptions_builder.py
>          :param task: task for the pipeline
Докстринг устарел

2022-06-20 15:39 UTC, ChrisLisbon commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +        :param available_operations:
Описание затерялось

2022-06-20 15:39 UTC, ChrisLisbon commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +        :return:
Тоже параметр потерялся

2022-06-20 15:39 UTC, ChrisLisbon commented on fedot/api/main.py
> +def check_final_pipeline(
Эта функция очень похожа на ту, что проверяет начальный пайплайн ([эту](https://github.com/nccr-itmo/FEDOT/pull/736/files#diff-75527b537125cea20faf6fd9173d04b077e5aa8a7146cffdd6fa3effc124e77eR49-R72)), даже логи об ошибках те же. Может сделать общую функцию для проверки корректности пайплайнов на данных и переиспользовать?

2022-06-21 08:02 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +        :param available_operations:
[Нашелся](extract-fit-initiall-assumption%23717)

2022-06-21 08:03 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +        :return:
[убрал ретурн](https://github.com/nccr-itmo/FEDOT/pull/736/commits/b4029c07c2e820201133f8bdbeeb2a57df6f0e5a#diff-75527b537125cea20faf6fd9173d04b077e5aa8a7146cffdd6fa3effc124e77eR87)

2022-06-21 08:05 UTC, valer1435 commented on fedot/api/main.py
> +def check_final_pipeline(
Да, тут была проблема в том, что функция для проверки initial_assumptions использовалась и для predefined model. Думаю тут нужно что-то более глобавльное, чем просто сделать одну функцию - возможно стоит сделать отдельный модуль для обработки predefined model

2022-06-21 08:22 UTC, gkirgizov requested changes

2022-06-21 08:22 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +            preset = change_preset_based_on_initial_fit(assumption_fit_time, timeout)
Есть подозрение, что вот эта функция примерно схожую првоерку проводит, что и `have_time_for_composing`. Может тоже как-то вместо этой функции тут спрашивтаь у ApiTime мол хватает ли нам времени

2022-06-21 08:22 UTC, gkirgizov commented on fedot/api/time.py
> +        self.starting_time_for_assumption_fit = datetime.datetime.now()
кажется что это поле (и аналогичные поля в других функциях `launch_...`) нигде больше не используются и могут быть локальными переменными

2022-06-21 08:22 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +        fitted_assumption, assumption_fit_time = \
Увидел ниже что ты добавил `def launch_assumption_fit(self)` -- так вот тут и можно его использовать и скрыть `assumption_fit_time` вовсе

2022-06-21 08:22 UTC, gkirgizov commented on fedot/api/main.py
> +def check_final_pipeline(
согласен. да и та вынесенная функция мало относится к классу `AssumptionHandler`, тк ничего от `self` кроме логгера не использует.

2022-06-21 12:29 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_builder.py
>          :param task: task for the pipeline
[Обновил](https://github.com/nccr-itmo/FEDOT/pull/736/commits/b4029c07c2e820201133f8bdbeeb2a57df6f0e5a#diff-d9823811fd5afd6c3fb6e32ee7e21071087638c874954b3bae0f4a4979eb181cR60-R61)

2022-06-21 12:30 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        self.timer = ApiTime(time_for_automl=timeout, with_tuning=with_tuning)
Она требует timeout и with_tuning, которые прокидываются только в эту функцию

2022-06-22 08:07 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:







* In the file [`fedot/api/api_utils/predefined_model.py`](https://github.com/nccr-itmo/FEDOT/blob/f2538c83575d7c06bdf5d0eff8d9f929a44e0e86/fedot/api/api_utils/predefined_model.py):

> [Line 18:1](https://github.com/nccr-itmo/FEDOT/blob/f2538c83575d7c06bdf5d0eff8d9f929a44e0e86/fedot/api/api_utils/predefined_model.py#L18): [W293](https://duckduckgo.com/?q=pep8%20W293) blank line contains whitespace
> [Line 43:1](https://github.com/nccr-itmo/FEDOT/blob/f2538c83575d7c06bdf5d0eff8d9f929a44e0e86/fedot/api/api_utils/predefined_model.py#L43): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-06-22 08:12 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +            preset = change_preset_based_on_initial_fit(assumption_fit_time, timeout)
[Перенес ](https://github.com/nccr-itmo/FEDOT/pull/736/commits/6fb06094fc9591c561f38a9adf5dca66a0e724fc#diff-bfb55318e87be211b23b7c1dee00a6c42cf34e11bac6302ec29f32def3a4c6bbR108) проверку в timer, но саму функцию оставил в presets

2022-06-22 08:13 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
>                                                                   self.timer.datetime_composing, preset)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/736/commits/6fb06094fc9591c561f38a9adf5dca66a0e724fc#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR176)

2022-06-22 08:14 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        if self._have_time_for_composing(assumption_fit_time, composer_params['pop_size']):
[Постарался](https://github.com/nccr-itmo/FEDOT/pull/736/commits/cb508c288793bd1fdd0431a24f62afbac280d434#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR171-R172) максимально скрыть

2022-06-22 08:15 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        fitted_assumption, assumption_fit_time = \
[Скрыл](https://github.com/nccr-itmo/FEDOT/pull/736/commits/6fb06094fc9591c561f38a9adf5dca66a0e724fc#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR169-R171)

2022-06-22 13:05 UTC, gkirgizov commented on fedot/api/time.py
> +        return supposed_time <= full_minutes_timeout
а теперь сравни логику этой и предыдущий функции :) мы одну и ту же проверку на основе изначальной оценки первого пайпалайна проводим для какого-то размера популяции.

2022-06-22 13:05 UTC, gkirgizov commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +            preset = change_preset_based_on_initial_fit(assumption_fit_time, timeout)
гуд, но кажется что параметр timeout и так известен таймеру. а если неизвестен -- то должен бы

2022-06-23 07:08 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        fitted_assumption, assumption_fit_time = \
[обернул](https://github.com/nccr-itmo/FEDOT/pull/736/commits/d854196e66da4259ba8e21189e437e989f7a093a#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR169-R173)

2022-06-23 07:09 UTC, valer1435 commented on fedot/api/time.py
> +        return supposed_time <= full_minutes_timeout
[Унифицировал](https://github.com/nccr-itmo/FEDOT/pull/736/commits/d854196e66da4259ba8e21189e437e989f7a093a#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R42-R45)

2022-06-23 07:10 UTC, valer1435 commented on fedot/api/time.py
> +        self.starting_time_for_assumption_fit = datetime.datetime.now()
[Переделал в локальные](https://github.com/nccr-itmo/FEDOT/pull/736/commits/d854196e66da4259ba8e21189e437e989f7a093a#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R39-R41)

2022-06-23 07:11 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> +            preset = change_preset_based_on_initial_fit(assumption_fit_time, timeout)
[Теперь используется внутренний таймаут](https://github.com/nccr-itmo/FEDOT/pull/736/commits/d854196e66da4259ba8e21189e437e989f7a093a#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R44)

2022-06-23 09:17 UTC, gkirgizov approved these changes

2022-06-24 12:25 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        self.timer = ApiTime(time_for_automl=timeout, with_tuning=with_tuning)
[Перенес ](https://github.com/nccr-itmo/FEDOT/pull/736/commits/ca78f5c2faec5c1384f758c8bc4ad68e5a35cd64#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR161)обратно

2022-06-24 15:21 UTC, merged