Editing a ReadMe
nccr-itmo/FEDOT pull request #745
Opened 2022-06-23 10:29 UTC by aPovidlo

Editing text in readme:
- Reducing bukavki in the text to simplify and increase information content;
- Update information according new version;
- Added new publication of @Dreamlone on habr in Publications section;

2022-06-23 12:24 UTC, IIaKyJIuH requested changes

2022-06-23 12:24 UTC, IIaKyJIuH commented on README.rst
> +2. Initialize the Fedot object and define the type of modeling problem. It provides a fit / predict interface:
Я бы оставил слеш без пробелов, чтобы показать, что тут именно связка этих двух понятий (думал, что это обычно так делается всегда)

2022-06-23 12:50 UTC, Dreamlone requested changes

2022-06-23 12:50 UTC, Dreamlone commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
Можно ещё `problems` заменить на `tasks`

2022-06-23 12:50 UTC, Dreamlone commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
Мы вроде кластеризацию не поддерживаем)

2022-06-23 12:50 UTC, Dreamlone commented on README.rst
Про пример кода: предлагаю в рамках данного PR убрать`train_data.features` и подобные части, а заменить их на `features` и выше просто сообщить, что `features` - это обычный numpy массив

2022-06-23 12:50 UTC, Dreamlone commented on README.rst
> +- About hyperparameters tuning of ensembles models - `habr.com <https://habr.com/ru/post/672486/>`__
Может названия в секции "In Russian:" все таки писать на русском?

2022-06-23 13:02 UTC, aPovidlo commented on README.rst
> +FEDOT Features
@IIaKyJIuH заголовок второго уровня. Подглядел в других репах, обычно так оформляют.

П.С.: Заметил, что не все заголовки ему соотвествуют и поэтому следующим коммитом приведу в порядок

2022-06-23 13:09 UTC, aPovidlo commented on README.rst
> +2. Initialize the Fedot object and define the type of modeling problem. It provides a fit / predict interface:
@IIaKyJIuH Подразумевал, что у fit и predict два разных интерфейса. Если имеется ввиду что интерфейс один, то может быть и стоит без пробелов у слеша

2022-06-23 13:21 UTC, aPovidlo commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
@Dreamlone к сущности ML думаю, уместнее будет `problems`

2022-06-23 13:25 UTC, aPovidlo commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
Опирался на комментарий для класса [API](https://github.com/nccr-itmo/FEDOT/blob/c0f2c6a7bc6b57006dff4ed90ada7c18e5c4765b/fedot/api/main.py#L46)

2022-06-23 13:31 UTC, Dreamlone commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
Значит комментарий тоже стоит исправить, или добавить комментарий в скобках вроде (experimental)

2022-06-23 13:33 UTC, aPovidlo commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
@IIaKyJIuH подразумевалось, что это два факта и союз их связывает

2022-06-24 06:08 UTC, IIaKyJIuH commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
Ну хорошо, понятен смысл

2022-06-24 06:10 UTC, IIaKyJIuH commented on README.rst
> +FEDOT Features
Понял, отпишись здесь тогда потом о переделке

2022-06-24 06:15 UTC, IIaKyJIuH commented on README.rst
> +2. Initialize the Fedot object and define the type of modeling problem. It provides a fit / predict interface:
А что если тогда лучше вместо одного слеша написать: `... fit and/or predict ...`?

2022-06-24 09:34 UTC, nicl-nno commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
Да, лучше про кластеризацию везде убрать - пока мы её до ума не довели и в обозримой перспективе это делать не планируем.

2022-06-24 13:28 UTC, aPovidlo commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
@nicl-nno не совсем понял про сочетание

2022-06-24 13:28 UTC, aPovidlo commented on README.rst
@Dreamlone исправил

2022-06-24 13:29 UTC, aPovidlo commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
@nicl-nno @Dreamlone убрал упомниание в доке к классу и поменял описание

2022-06-24 13:29 UTC, aPovidlo commented on README.rst
> +2. Initialize the Fedot object and define the type of modeling problem. It provides a fit / predict interface:
@IIaKyJIuH вернул предыдущий варинат `fit/predict`

2022-06-24 13:30 UTC, aPovidlo commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for all prolbems (classification, regression, time series forecasting and clustering).
@IIaKyJIuH исправил

2022-06-24 13:30 UTC, aPovidlo commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
@IIaKyJIuH исправил

2022-06-24 13:30 UTC, aPovidlo commented on README.rst
> +- FEDOT already supports widely used ML libraries (Scikit-Learn, Catboost, Xgboost, etc.) and it allows to integrate your custom ones;
@IIaKyJIuH исправил

2022-06-24 13:31 UTC, aPovidlo commented on README.rst
> +FEDOT Features
@IIaKyJIuH переделал для всех заголовков

2022-06-24 13:31 UTC, aPovidlo commented on README.rst
> +It provides automatic generative design of machine learning pipelines for various real-world problems. The core of FEDOT based on evolutionary approach and supports classification (binary and multicl
@IIaKyJIuH исправил, как-то проглядел этот момент. Спасибо, что заметил!

2022-06-24 13:32 UTC, aPovidlo commented on README.rst
> +- About hyperparameters tuning of ensembles models - `habr.com <https://habr.com/ru/post/672486/>`__
@nicl-nno @Dreamlone исправил

2022-06-24 13:36 UTC, Dreamlone commented on README.rst
> +NumPy arrays, Pandas DataFrames, and the file's path can be used as sources of input data. In case below, `X_train`, `y_train` and `y_test` are `numpy.ndarray()`:
Предлагаю, раз у нас тут pep8 и все дела, то и названия переменных пуст будут с маленькой буквы: `x_train`

2022-06-24 13:41 UTC, aPovidlo commented on README.rst
> + prediction = model.predict(features=y_test)
@Dreamlone Точно, что-то я тут сглупил)

2022-06-26 08:21 UTC, nicl-nno commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems and distributed under the 3-Clause BSD license.
Это. Можно просто разбить на 2 предложения и будет норм.

**FEDOT** is <an open-source framework for automated modeling and machine learning (AutoML) problems> and <distributed under the 3-Clause BSD license.>

2022-06-27 10:19 UTC, IIaKyJIuH commented on README.rst
> +It provides automatic generative design of machine learning pipelines for various real-world problems. The core of FEDOT based on evolutionary approach and supports classification (binary and multicl
Молодец!

2022-06-27 10:22 UTC, IIaKyJIuH commented on README.rst
> +More detailed about Fedot is available in this video:
Хорошо.

Но раз уж заменил на `next video`, то лучше определённый артикль добавить перед этим словосочетанием

2022-06-27 10:26 UTC, IIaKyJIuH commented on README.rst
> +FEDOT Features
Точно ли правильнее `How to Use` вместо `How To Use`?

2022-06-27 10:27 UTC, IIaKyJIuH commented on README.rst
> +- There are no limits to specific modeling tasks and claims versatility and expandability;
Хорош

2022-06-27 10:30 UTC, IIaKyJIuH commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
может быть в конце первого предложения тогда добавить `... is proposed`? То есть как бы говорим, что установка предлагается либо простая, как было ранее, либо полная, со всеми зависимостями. А в следующем предложении говорится как раз, что это необходимо для картинок, текста, тестов

2022-06-27 10:31 UTC, IIaKyJIuH commented on README.rst
> +2. Initialize the Fedot object and define the type of modeling problem. It provides a fit / predict interface:
Ок)

2022-06-27 10:34 UTC, nicl-nno commented on README.rst
> +FEDOT Features
Предлоги часто не выделяют регистором.

2022-06-27 10:48 UTC, aPovidlo commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
@IIaKyJIuH думаю, что это излишне, т.к. выражается об этом в `In alternative way`

2022-06-28 07:35 UTC, IIaKyJIuH commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
Лично для меня предложение выглядит всё равно неполным.

@nicl-nno, @Dreamlone, что скажете по первому [предложению тут](https://github.com/nccr-itmo/FEDOT/pull/745/files#diff-7b3ed02bc73dc06b7db906cf97aa91dec2b2eb21f2d92bc5caa761df5bbc168fR78) в тексте?

2022-06-28 11:24 UTC, gkirgizov requested changes

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +- Allows building models using widely types of input data (texts, images, tables, etc.) and consisting of various models.
... using different types ... ? widely -- некорректно

building models ... using models -- тавталогично

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +- There are no limits to specific modeling tasks, therefore FEDOT claims versatility and expandability;
несогласовано с заголовком в первом лице "FEDOT: There are no limits"
можно написать "Is versatile and not limited to specific modeling tasks"

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +Alternatively, in order to work with the source code:
Раздел про source лучше последним указывать, мол, сначала все опции для common users

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for next problems: classification, regression and time series forecasting.
The API can be used for problems of classification, regression, and time series forecasting.

так более естественно звучит

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +- 生成式自动机器学习系统. - `youtube.com <https://www.youtube.com/watch?v=PEET0EbCSCY>`__
я бы тут в скобках англ перевод оставил, а то какое-то странное впечатление оставляет. а так большинству читателей будет хоть понятно, что была какая-то конфа на китайском

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
> +Publications About FEDOT
предлог с маленькой?

2022-06-28 11:24 UTC, gkirgizov commented on README.rst
>  In Russian:
пожалуй, лучше вместе с переводом на англ в скобках давать. а то англоязычному читателю будет казаться, будто о нем не позаботились. обычно неприятно на неродной язык без особых пояснений натыкаться

2022-06-28 11:28 UTC, gkirgizov commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
И если так все способы установки описать, то не нужно подбирать вводные предложения\слова для каждой альтернативы.

2022-06-28 11:33 UTC, Dreamlone commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
> а мне кажется, лучше как-то декларативно без особых вводных

Согласен, особенно такой стиль сочетается со всякими инструкциями, которые, по сути, и выдаются в этом месте

2022-06-28 12:41 UTC, aPovidlo commented on README.rst
> +Alternatively, in order to work with the source code:
@gkirgizov не понял комментария

2022-06-28 12:42 UTC, aPovidlo commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for next problems: classification, regression and time series forecasting.
@gkirgizov не соглашусь. Для русского может быть так оно и есть

2022-06-28 12:44 UTC, nicl-nno commented on README.rst
>  In Russian:
С переводом довольно громоздко будет - названия то длинные. Идеалом было бы всплывающий перевод, но маркдаун так кажется не умеет. Предлагаю это пока оставить как есть

2022-06-28 12:45 UTC, aPovidlo commented on README.rst
> +- 生成式自动机器学习系统. - `youtube.com <https://www.youtube.com/watch?v=PEET0EbCSCY>`__
@gkirgizov так вроде из заголовка понятно, что это что-то на китайском

2022-06-28 12:48 UTC, nicl-nno commented on README.rst
> +- 生成式自动机器学习系统. - `youtube.com <https://www.youtube.com/watch?v=PEET0EbCSCY>`__
Вот тут как раз можно оставить англ, т.к. китайское названее не поясняет, где было дело.

В стиле:
生成式自动机器学习系统 (presentation in Open Innovations 2.0 conference)

2022-06-28 12:50 UTC, nicl-nno commented on README.rst
> +FEDOT provides a high-level API that allows you to use its capabilities in a simple way. The API can be used for next problems: classification, regression and time series forecasting.
Мб просто

The API can be used for classification, regression, and time series forecasting tasks.

for next problems действительно кажется слишком формальным и избыточным для перечисления всего трех задач.

2022-06-28 13:08 UTC, aPovidlo commented on README.rst
> +Alternatively, in order to work with the source code:
@gkirgizov мб все таки лучше разделить установку по принципу: легкая и нагруженная?

2022-06-28 13:09 UTC, aPovidlo commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
@nicl-nno @gkirgizov @IIaKyJIuH @Dreamlone в итоге как оставляем?

2022-06-28 13:10 UTC, aPovidlo commented on README.rst
> +**FEDOT** is an open-source framework for automated modeling and machine learning (AutoML) problems. This framework distributed under the 3-Clause BSD license.
@gkirgizov исправил

2022-06-28 13:10 UTC, aPovidlo commented on README.rst
> +The key feature of the framework is the complex management of interactions between the various blocks of pipelines. It is represented as a graph that define the connections between data preprocessing
@gkirgizov исправил оба

2022-06-28 13:10 UTC, aPovidlo commented on README.rst
> +- FEDOT already supports widely used ML libraries (Scikit-Learn, Catboost, Xgboost, etc.) and allows you to integrate your custom ones;
@gkirgizov исправил оба

2022-06-28 13:11 UTC, aPovidlo commented on README.rst
>  - Pipeline optimization algorithms are not tied to specific data types or tasks, but you can use special templates for a specific task class or data type (time series forecasting, NLP, tabular data,
@gkirgizov исправил

2022-06-29 12:15 UTC, IIaKyJIuH commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
Мне нравится предложение @gkirgizov

2022-06-29 14:15 UTC, nicl-nno commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
+

2022-06-29 14:16 UTC, nicl-nno commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
\+

2022-06-29 14:19 UTC, aPovidlo commented on README.rst
> +Setup with full optional dependencies. It requires to work with image/text data and loading tests:
@nicl-nno @gkirgizov @IIaKyJIuH @Dreamlone всех услышал, переделаю как предложил @gkirgizov

2022-06-29 16:40 UTC, gkirgizov commented on README.rst
> +Alternatively, in order to work with the source code:
Да, не заметил сначала, что тут 2 раздела с 2 случаями каждый. Ок, тоже разумно

2022-06-29 16:42 UTC, gkirgizov commented on README.rst
> +Publications About FEDOT
ок

2022-06-30 10:35 UTC, IIaKyJIuH approved these changes

2022-06-30 10:38 UTC, IIaKyJIuH commented on README.rst
> +Accordingly, compared to other frameworks, FEDOT:
+

2022-06-30 10:40 UTC, IIaKyJIuH commented on README.rst
`+`

2022-06-30 10:50 UTC, IIaKyJIuH commented on README.rst
> +- FEDOT is highly flexible: it can be used to automate the construction of mathematical models for various problems, data types, and models;
Предложу свой вариант:
`... the construction of solutions for many problems with various data types using numerous models;`

2022-06-30 10:55 UTC, nicl-nno approved these changes
Ещё планировали обновить картинки - но можно и отдельным PR-ом.

2022-06-30 10:56 UTC, Dreamlone commented on README.rst
> +- Как AutoML помогает создавать модели композитного ИИ — говорим о структурном обучении и фреймворке FEDOT - `habr.com <https://habr.com/ru/company/spbifmo/blog/558450>`__
Думаю, можно добавить ещё одну нашу недавнюю статью на TDS в англоязычный раздел: 
[Hyperparameters Tuning for Machine Learning Model Ensembles](https://towardsdatascience.com/hyperparameters-tuning-for-machine-learning-model-ensembles-8051782b538b)

2022-06-30 14:38 UTC, aPovidlo commented
> Ещё планировали обновить картинки - но можно и отдельным PR-ом.

@nicl-nno осбудили это с @gkirgizov и пришли к тому, что это требует совместного обсуждения попозже "что хотелось бы показать кратко" и видимо да, как отедльный PR.

2022-06-30 14:58 UTC, aPovidlo commented on README.rst
@gkirgizov хороошо, добавлю

2022-06-30 15:00 UTC, aPovidlo commented on README.rst
> +- FEDOT is highly flexible: it can be used to automate the construction of mathematical models for various problems, data types, and models;
@gkirgizov @IIaKyJIuH заменил `mathematical models` на `solutions`

2022-06-30 15:09 UTC, aPovidlo commented on README.rst
> +- Allows building models using widely types of input data (texts, images, tables, etc.) and consisting of various models.
@gkirgizov не понял твоего комментария

2022-07-01 08:41 UTC, Dreamlone approved these changes

2022-07-04 10:07 UTC, gkirgizov approved these changes

2022-07-05 09:41 UTC, gkirgizov commented on README.rst
**No limits** ))

2022-07-05 09:45 UTC, gkirgizov commented on README.rst
> +- Allows building models using widely types of input data (texts, images, tables, etc.) and consisting of various models.
`widely types` -- грамматически некорректное использование widely, и я предложил `using different types`.
Также `models` дважды повторяется и звучит тавталогично. Тут бы тоже solutions или operations или что-то еще во втором случае либо pipelines / composite models в первом.

2022-07-06 10:15 UTC, merged