706 node factory mutation
nccr-itmo/FEDOT pull request #746
Opened 2022-06-24 08:40 UTC by YamLyubov

Mutation operators now are not specific for AutoML (Pipeline). All operations for creating new nodes while mutation are incapsulated in OptNodeFactory abstract class and can be implemented specifically for any other task.
#727

2022-06-24 10:05 UTC, gkirgizov requested changes

2022-06-24 10:05 UTC, gkirgizov commented on fedot/core/optimisers/opt_node_factory.py
> +    def change_node(self,
пропиши возвращаемый тип везде

2022-06-24 10:05 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_node_factory.py
> +    def get_intermediate_parent_node(self,
так, а зачем нам два одинаковых метода?)

2022-06-24 10:22 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +                graph.update_node(node, new_node)
Это я тут ошиблась, хотела наоборот заменять если не None. None возвращается, если нет кандидатов-операций для новой ноды (```PipelineOptNodeFactory._return_node(candidates)```). Возможно лучше этот случай по-другому обрабатывать.

2022-06-24 10:24 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if node.nodes_from:
У primary нод как раз нет предков и мы так из рекурсии выходим

2022-06-24 10:32 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    if not new_node:
В мутациях можно выделить два наиболее общих случая: изменить текущую ноду и добавить новую. В первом случае, если у нас нет подходящих кандидатов для замены, можно было бы возврщать текущую ноду. Во втором случае так не получится, ведь если нет доступных кандидатов, мы не можем просто текущую ноду продублировать (например, если нам нужно было получить как предка primary node для secondary node, а для них разные requirements могут быть).

2022-06-24 10:48 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
>      graph.nodes.append(new_node)
Можно тут последнюю строчку заменить на ```graph.add_node(new_node)```, но две первые придется оставить. Тут не апдейтится нода, а новая добавляется в последовательность.

2022-06-24 12:08 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +                    requirements,
Тут такая ситуация:  мы задаем factory одновременно с advisor для GraphGenerationParams
```
graph_generation_params = GraphGenerationParams(adapter=PipelineAdapter(self.log),
                                                        advisor=PipelineChangeAdvisor(self.task),
                                                        rules_for_constraint=rules_by_task(self.task.task_type),
                                                        node_factory=PipelineOptNodeFactory())
```
а requirements  передаются уже вместе с GraphGenerationParams в optimizer. (это я все взяла из ```ComposerBuilder.build```). То есть advisor и requirements будут два раза передаваться.

2022-06-24 12:15 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +        new_subtree = params.node_factory.get_primary_node(requirements)
Мне казалось, что не очень специфичная, ведь в любом графе могут быть ноды, у которых нет предков (primary) и есть предки (secondary). Ну и тут два метода (```get_primary_nide```, ```get_secondary_node```), которые отличаются тем, какие requirements испоьзовать.

2022-06-24 12:26 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +    def get_intermediate_parent_node(self,
Потому что это два разных случая, в для них с разными параметрами вызывается advisor и по самой ноде нельзя сказать, какой это именно случай. Например, мы можем для secondary node как получить нового отдельного предка (primary node), то есть в список уже существующих предков добавить нового (get_separate_parent_node), так и добавить новую ноду меджу текущей нодой и его предком, в этом случае мы генерим secondary ноду. Можно было бы это объединить в один метод с  bool параметром, но мне показалось, лучше так

2022-06-24 12:38 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +        if advisor:
В данном случае может, зависит от того, передали его при вызове метода или нет) Често говоря, мне кажется, стоит убрать здесь дефолтное значение ```advosor```. Оно здесь есть, потому что в предыдущей версии кода для mutation похожие операции, когда надо было модификацию ноды получить, выполнялись иногда с adviser иногда без. Но я не выявила разницы принципиальной

2022-06-27 10:51 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if node.nodes_from:
там пустой список будет в таком случае и цикл ниже просто не выполнится

2022-06-27 10:55 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
>      graph.nodes.append(new_node)
ага, замени тогда на add_node хотя бы

2022-06-27 10:59 UTC, gkirgizov commented on fedot/core/optimisers/opt_node_factory.py
> +    def change_node(self,
и если у нас может быть None -- то тип будет Optional

2022-06-27 11:15 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_node_factory.py
> +    def get_intermediate_parent_node(self,
ок, согласен. изначально не заметил параметр.
только предлагаю все-таки оставить один метод с доп параметром -- так, может, проще будет потом их объединить. лучше не множить сущности до возникновения необходимости действительно разной логики

2022-06-27 11:19 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_node_factory.py
> +        return self._get_node(requirements, primary=True)
тот же аргумент -- пусть будет один параметризованный метод. 
плюс название метода `get_child_node` немного обманчиво -- в методе никак не используется информация о том , что это child. метод просто возращает ноду, и, мол, делайте с ней что хотите дальше.

2022-06-28 09:08 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if node.nodes_from:
хм, понял
возможно я перепутал, и пофиксил это уже в своей локальной ветке.
пусть тогда будет

2022-06-28 12:10 UTC, gkirgizov requested changes

2022-06-28 12:10 UTC, gkirgizov commented on test/unit/optimizer/test_gp_operators.py
> +                                         node_factory=node_factory)
Вообще, чтобы не дублировать этот код, можно сделать какую-нибудь функцию-конструктор, которая будет возвращать GraphGenerationParams для случая Pipeline

2022-06-28 12:10 UTC, gkirgizov commented on test/unit/optimizer/test_gp_operators.py
> +                                         node_factory=node_factory)
И как раз в Composer.build можно будет использовать ее

2022-06-28 12:22 UTC, gkirgizov commented
Кстати, посмотри еще другие использования OptNode -- может тоже можно этой фабрикой заменить где-то их создание

2022-06-28 14:34 UTC, valer1435 requested changes

2022-06-29 09:59 UTC, YamLyubov commented on fedot/core/optimisers/opt_node_factory.py
> +    def change_node(self,
Я бы тогда предложила что-то вроде ```propose_node_change```, а для других методов соответственно ```propose_parent_node``` и ```propose_node```

2022-07-01 06:53 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/core/composer/composer_builder.py`](https://github.com/nccr-itmo/FEDOT/blob/1fe885e42ca26643a71da654fd2b3ac3466d7601/fedot/core/composer/composer_builder.py):

> [Line 120:121](https://github.com/nccr-itmo/FEDOT/blob/1fe885e42ca26643a71da654fd2b3ac3466d7601/fedot/core/composer/composer_builder.py#L120): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

2022-07-01 09:52 UTC, YamLyubov commented on fedot/core/optimisers/opt_node_factory.py
> +    def change_node(self,
Может быть transform? Другие варианты вроде как тоже предполагают замену в графе, а transform вроде нет. Это, конечно, очень субъективно)

2022-07-04 10:36 UTC, gkirgizov approved these changes
пофиксить pep8, ребейзнуться и можно вливать

2022-07-04 10:36 UTC, gkirgizov commented on fedot/core/pipelines/pipeline_node_factory.py
> +    def __init__(self, requirements: Any,
Это ведь не Any а PipelineComposerRequirements, насколько я понимаю

2022-07-05 09:53 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def random_graph(graph_generation_params: GraphGenerationParams,
Не уверен, что это так и есть. Но max_depth по-идее должно быть вложено в GraphGenerationParams

2022-07-05 09:53 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def random_graph(graph_generation_params: GraphGenerationParams,
Или в requirements

2022-07-05 10:04 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def random_graph(graph_generation_params: GraphGenerationParams,
Да, max_depth вложен в requirements, но похоже есть случаи, когда нужно его отдельно передавать. В общем я поищу примеры использования и, если max_depth не нужен, уберу. Сейчас другой ишью занимаюсь и там тоже на это внимание обратила

2022-07-05 11:45 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def random_graph(graph_generation_params: GraphGenerationParams,
В ```mutation.py``` ```_tree_growth``` max_depth вычисляется относительно max_depth в requirements. По идее, можно в данном случае создавать новые requirements, переопределяя в них max_depth.

2022-07-06 09:37 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +def random_graph(graph_generation_params: GraphGenerationParams,
Вообще выглядит не очень хорошим подходом, что у нас есть max_depth в requirements и max_depth, который как какой-то отдельный параметр. Не думаю, что в рамках pr стоит это фиксить, так как он уже большой, но стоит иметь в виду

2022-07-06 09:37 UTC, valer1435 approved these changes

2022-07-08 14:16 UTC, merged

2022-07-10 14:33 UTC, gkirgizov commented
@YamLyubov удаляй, пожалуйста, рабочие ветки после мержа, если нет причин их сохранить