Remove duplicate params
nccr-itmo/FEDOT pull request #747
Opened 2022-06-27 10:52 UTC by valer1435

Fix for https://github.com/nccr-itmo/FEDOT/issues/744 issue. 
 Duplicates are deleted and divided composer_metric and tuner_metric

2022-06-27 10:52 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

























* In the file [`fedot/api/api_utils/params.py`](https://github.com/nccr-itmo/FEDOT/blob/dce4de11344833b1722ad411499a210bc20c3c18/fedot/api/api_utils/params.py):

> [Line 163:1](https://github.com/nccr-itmo/FEDOT/blob/dce4de11344833b1722ad411499a210bc20c3c18/fedot/api/api_utils/params.py#L163): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

















* In the file [`test/unit/api/test_main_api.py`](https://github.com/nccr-itmo/FEDOT/blob/dce4de11344833b1722ad411499a210bc20c3c18/test/unit/api/test_main_api.py):

> [Line 432:69](https://github.com/nccr-itmo/FEDOT/blob/dce4de11344833b1722ad411499a210bc20c3c18/test/unit/api/test_main_api.py#L432): [E203](https://duckduckgo.com/?q=pep8%20E203) whitespace before ':'

2022-06-27 11:55 UTC, gkirgizov requested changes
красота теперь 
пара мелких комментов только

2022-06-27 11:55 UTC, gkirgizov commented on cases/multivariate_ts_forecasting.py
> +                  cv_fols=2, validation_blocks=2)
опечаятка

2022-06-27 11:55 UTC, gkirgizov commented on examples/advanced/additional_learning.py
> +                                             PrimaryNode('scaling')])))
давай эту "лесенку" строкой выше вынесем в создание пайплайна нормальное -- а то плакать хочется )

2022-06-27 11:55 UTC, gkirgizov commented on fedot/api/main.py
> +    :param max_depth: max depth of the pipeline
тут бы заголовочек категории поставить, мол, keyword params for composer

2022-06-27 11:55 UTC, gkirgizov commented on test/unit/models/test_custom_model_introduction.py
> +                   **{'initial_assumption': initial_assumption, 'preset': 'ts'})
можно попроще)

2022-06-27 11:55 UTC, gkirgizov commented on test/unit/optimizer/test_external.py
> +                   **{'with_tuning': False,
может тоже не паковать-распаковывать тут же

2022-06-27 12:33 UTC, aPovidlo approved these changes

2022-06-27 13:11 UTC, Dreamlone approved these changes

2022-06-27 13:14 UTC, Dreamlone commented
Ещё хотелось бы иметь такой тест для API (если ещё нет), который проверяет правильно ли обработались заданные параметры, в основном конечно хочется проверить самые критичные: timeout, with_tuning, initial_assumption и легендарную связку "preset - available_operations", разные сценарии сочетаний там попробовать - вроде такого более менее общего ещё нет

2022-06-28 06:52 UTC, valer1435 commented on cases/multivariate_ts_forecasting.py
> +                  cv_fols=2, validation_blocks=2)
[Исправил](https://github.com/nccr-itmo/FEDOT/pull/747/commits/82a4cf222e2b6b2c516ab2c10c34fbb6f19c9c5e#diff-a3b610a93d0e23eda790b400d56586e2c01093f428427014153d20a8056bd040R56). Появилась мысль о том, что неплохо было бы где-то на этапе обработки параметров проверять, что все параметры есть в словаре параметров. А то этот пример считай так бы и остался без параметра cv_folds, не тронув бы его сейчас

2022-06-28 06:53 UTC, valer1435 commented on examples/advanced/additional_learning.py
> +                                             PrimaryNode('scaling')])))
[Сделано](https://github.com/nccr-itmo/FEDOT/pull/747/commits/82a4cf222e2b6b2c516ab2c10c34fbb6f19c9c5e#diff-7d328f31ffdba150524eeb0b905ff37a278500ba8bee5f3d16ac42648ea74009R25)

2022-06-28 06:54 UTC, valer1435 commented on test/unit/models/test_custom_model_introduction.py
> +                   **{'initial_assumption': initial_assumption, 'preset': 'ts'})
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/747/commits/82a4cf222e2b6b2c516ab2c10c34fbb6f19c9c5e#diff-aaa6c3ec6eb75a39522547083e206144138fe3c2cafdd71ea60c6d889d6a4e15R225). На самом деле в какой-то момент замучался переделывать словарики на параметры))

2022-06-28 06:55 UTC, valer1435 commented on test/unit/optimizer/test_external.py
> +                   **{'with_tuning': False,
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/747/commits/82a4cf222e2b6b2c516ab2c10c34fbb6f19c9c5e#diff-d8c13f6fedf419a3219d4c7e63e79d37af2def69c2b57aa8a73ba8280dc2e8bcR49)

2022-06-28 06:56 UTC, valer1435 commented on test/unit/api/test_main_api.py
> +    train_input, _, _ = get_dataset(task_type='classification')
[Улучшил ](https://github.com/nccr-itmo/FEDOT/pull/747/commits/3fdea66c54eabecfbc715288bf7531c774dc1b73) тест, теперь там проверяется разделение параметров - как раз available operations и preset там же

2022-06-28 06:56 UTC, valer1435 commented on fedot/api/main.py
> +    :param max_depth: max depth of the pipeline
[Поставил](https://github.com/nccr-itmo/FEDOT/pull/747/commits/82a4cf222e2b6b2c516ab2c10c34fbb6f19c9c5e#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR62)

2022-06-28 09:01 UTC, gkirgizov commented on cases/multivariate_ts_forecasting.py
> +                  cv_fols=2, validation_blocks=2)
Хорошая мысль. Я думаю, это можно в данном PR сделать, где-то в функции где общий словарь параметров разделяется на composer/tuner/api params. На отд issue не тянет

2022-06-28 09:02 UTC, gkirgizov commented on test/unit/models/test_custom_model_introduction.py
> +                   **{'initial_assumption': initial_assumption, 'preset': 'ts'})
Так и подумал )

2022-06-28 15:56 UTC, valer1435 commented on cases/multivariate_ts_forecasting.py
> +                  cv_fols=2, validation_blocks=2)
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/747/commits/911d14fb8a2d209311cdab0eaef821fc6075d804#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR293)проверку

2022-06-29 07:03 UTC, merged