737 initial population factory
nccr-itmo/FEDOT pull request #763
Opened 2022-07-07 11:34 UTC by YamLyubov

Initial population can be generated in three ways: with initial graphs, with initial population generation function and randomly, if nothing from the above were provided. Details of generation of initial graphs are hidden from GraphOptimiser.
#737

2022-07-07 12:25 UTC, gkirgizov commented
запросил ревью от @MorrisNein чтобы проверить, верно ли трекается история мутаций, т.к. в тех же строках было раньше тонкое место с использованием OptHistory

2022-07-07 12:50 UTC, gkirgizov requested changes

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            if new_ind.graph not in [ind.graph for ind in self.initial_individuals] \
может не создавать на каждой итерации один и тот же список?

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _extend_population(self, initial_individuals, pop_size: int, max_depth: int):
предлагаю из этого метода возращать расширенный список, а не тихо модифицирвоать какое-то поле класса -- это более очевидный интерфейс для подобных методов на списках

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            self._next_population(evaluator(self.initial_individuals))
Вот как раз этот метод вызывался _до мутаций_, чтобы изначальные графы добавить в историю оптимизации.
А так мы, кажется, дважды добавим первое поколение -- здесь и в первом цикле.
Также если нам extend_population не требуется -- то вроде тоже дважды одно и то же поколение запишем.

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/initial_graphs_generator.py
> +    def get_initial_graphs(self, **kwargs) -> Sequence[Union[Graph, OptGraph]]:
**kwargs выглядит как-то непрозрачно. 
А теперь представь, что ты пользователь который реализует этот интерфейс. Как ты его реализуешь? :) 
Тем более Optimiser туда передает конкретные аргументы

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/initial_graphs_generator.py
> +    def get_initial_graphs(self, pop_size: int, max_depth: int = None) -> Sequence[Union[Graph, OptGraph]]:
во-первых, если map_depth может быть None -- то это Optional[int]
во-вторых, может мы все-таки можем взять его из requirements? по вызову функции выглядит что да

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        is_max_depth_exceeded = height >= max_depth - 2
есть тест на это изменение? чтобы не гадать, правильно это или неправильно генерируется

2022-07-07 12:50 UTC, gkirgizov commented on fedot/core/optimisers/initial_graphs_generator.py
> +        pass
Еще -- предлагаю все-таки выбрать, что возвращать, Graph или OptGraph.
во-первых, интерфейс так выходит громоздкий.
во-вторых, если рассудить по предполагаемому использованию -- то вероятно пользователю удобнее передавать графы предметной области.

Ты в этом интерфейсе, как я понял, полагаешься на то, что где-то там далеко-далеко будет использоваться адаптер, которому все равно, что адаптировать. Это не очень правильно -- классы и абстракции должны быть как можно более строгими в том, что они возвращают, чтобы снять с тех, кто их использует, ответственность, мол, "сами разберутся, что им нужно"

2022-07-07 12:50 UTC, gkirgizov commented on test/unit/optimizer/test_initial_population_generator.py
> +    unique = reduce(lambda l, x: l.append(x) or l if x not in l else l, generated_population, [])
мб просто `set(...)` будет очевиднее

2022-07-07 12:50 UTC, gkirgizov commented on test/unit/optimizer/test_initial_population_generator.py
> +
а тестируется ли дефолтная генерация с random_graph?

2022-07-07 12:59 UTC, YamLyubov commented on test/unit/optimizer/test_initial_population_generator.py
> +    unique = reduce(lambda l, x: l.append(x) or l if x not in l else l, generated_population, [])
Пробовала set использовать, но Pipeline - это unhashble type.

2022-07-07 13:01 UTC, YamLyubov commented on test/unit/optimizer/test_initial_population_generator.py
> +
Да, самый первый тест ```test_random_initial_population```.

2022-07-07 13:05 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        is_max_depth_exceeded = height >= max_depth - 2
Сейчас теста нет. Просто я тестировала дефолтный случай для генерации начальной популяции и проверяла, что грубина полученных графов не превосходит максимальную, ну и тест не проходит. Я подебажила метод ```graph_growth``` и вот так его исправила. Можно написать тогда еще тесты для ```random_graph```.

2022-07-07 13:13 UTC, YamLyubov commented on fedot/core/optimisers/initial_graphs_generator.py
> +    def get_initial_graphs(self, pop_size: int, max_depth: int = None) -> Sequence[Union[Graph, OptGraph]]:
Мы для вызова используем max_depth не из requirements, а из ```AdaptiveGraphDepth```
```
start_depth = requirements.start_depth or requirements.max_depth
self._graph_depth = AdaptiveGraphDepth(self.generations,
                                             start_depth=start_depth,
                                             max_depth=requirements.max_depth,
                                             max_stagnated_generations=parameters.depth_increase_step,
                                             adaptive=parameters.with_auto_depth_configuration)
 self.max_depth = self._graph_depth.initial

initial_graphs = self.initial_graphs_generator.get_initial_graphs(pop_size=self._pop_size.initial,
                                                                        max_depth=self.max_depth)
```

2022-07-07 13:23 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                 initial_graphs_generator: InitialPopulationGenerator,
Да, я думала так сделать, но для инициализации начальной популяции используются адаптивные параметры (глубина и размер популяции). Я посмотрела, глубину вроде можно напрямую из requirements взять, а вот размер начальной популяции только оптимизатор знает, поэтому в композере не вызвать метод

2022-07-10 21:26 UTC, MorrisNein requested changes

2022-07-10 21:26 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            self._next_population(evaluator(self.initial_individuals))
Действительно получается забавная ситуация: у пайплайнов первого поколения будут предки из этого же поколения. Хочется, как и раньше, добавлять в историю начальные приближения до мутаций.

За исключением этого момента, проблем с целостностью истории не вижу.

2022-07-13 14:32 UTC, MorrisNein requested changes

2022-07-14 08:14 UTC, YamLyubov commented on fedot/core/composer/gp_composer/gp_composer.py
> +from typing import Optional, Sequence, Union, Collection, Tuple
Да это после ребейза похоже у меня так стало)) Поправлю

2022-07-14 10:41 UTC, gkirgizov requested changes

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/composer/gp_composer/gp_composer.py
> +                         composer_requirements=composer_requirements)
Это мелочь относящаяся к code style, но все таки кейворды надо использовать там, где они добавляют смысл (скажем для аргументов чисел) либо незаменимы (keyword-only parameters). Здесь же просто дважды пишешь одно и от же имя

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +MAX_ITER = 1000
Кажется эта константа где-то уже повторяется. Предлагаю ее назвать более говорящим именем и перенести в constants.py

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                         parameters=parameters)
Выше написал уже о таком дублировании

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/optimisers/initial_graphs_generator.py
> +if TYPE_CHECKING:
Может лучше попробовать избавиться от цикла импортов, чем добавлять такие if-ы?

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/optimisers/initial_graphs_generator.py
> +    def get_initial_graphs(self) -> Sequence[Graph]:
Все таки для таких простых интерфейсов которые похожи на Callable предлагаю просто завести type alias.
Пользователям этой абстракции так будут более развязаны руки, они смогут просто лямбду или какой то генератор передать вместо того чтобы реализовывать интерфейс.

Принцип Бритвы Оккама: не множить сущности без необходимости :)

2022-07-14 10:41 UTC, gkirgizov commented on fedot/core/optimisers/optimizer.py
> +    :param initial_graphs: graphs which was initialized outside the optimiser
Грамматика : graphs which _were_

2022-07-15 12:41 UTC, MorrisNein approved these changes

2022-07-15 14:40 UTC, andreygetmanov approved these changes

2022-07-18 09:34 UTC, merged