Fix for 765, remove stdout capture in pytest run
nccr-itmo/FEDOT pull request #766
Opened 2022-07-07 15:01 UTC by gkirgizov

Fixes #765

2022-07-10 14:13 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`test/unit/dag/test_graph_utils.py`](https://github.com/nccr-itmo/FEDOT/blob/c05060667c613f1c6491eabe04ce9b5202762904/test/unit/dag/test_graph_utils.py):

> [Line 23:1](https://github.com/nccr-itmo/FEDOT/blob/c05060667c613f1c6491eabe04ce9b5202762904/test/unit/dag/test_graph_utils.py#L23): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-08-04 13:22 UTC, gkirgizov commented
The main issue was because of this line: https://github.com/nccr-itmo/FEDOT/blob/7eb49b15c0f614493c5c94f5ac0ca5c6405d15b7/fedot/core/operations/operation.py#L80
in `Operation.fit` method. Finally, fixed

2022-08-04 13:37 UTC, MorrisNein commented on test/unit/api/test_api_utils.py
> +#     assert 'Composed pipeline returned without tuning.' in str(logs)
На всякий случай напомню про этот TODO.

2022-08-04 13:44 UTC, MorrisNein requested changes

2022-08-04 13:44 UTC, MorrisNein commented on test/unit/test_logger.py
> +    clear_singleton_class(Log)
Подскажи, а зачем тут 2 вызова?

2022-08-04 13:44 UTC, MorrisNein commented on test/unit/utilities/test_project_import_export.py
> +                logging_level_opt=logging.CRITICAL+1,
А это как, CRITICAL+1?)

2022-08-04 13:44 UTC, MorrisNein commented on examples/simple/pipeline_log.py
> +    # release_log(logger=log)
Тоже на всякий случай напоминаю про комментарий.

2022-08-04 14:03 UTC, gkirgizov commented on test/unit/utilities/test_project_import_export.py
> +                logging_level_opt=logging.CRITICAL+1,
это значит мы закрываем глаза и уши даже на апокалипсис. ничего не будет проходить в лог

2022-08-04 14:04 UTC, gkirgizov commented on test/unit/test_logger.py
> +    clear_singleton_class(Log)
почистить перед тестом и после теста, чтобы следов не оставалось ни до первого теста в файле, ни после последнего

2022-08-04 14:23 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +        return output.getvalue()
Почему тут нельзя все добавить в лист и все сконкатенатить? Или это аналогичный способ без использования неизменяемого str?

2022-08-04 14:23 UTC, valer1435 commented on test/unit/conftest.py
> +    """Workaround for issue #765 (https://github.com/nccr-itmo/FEDOT/issues/765)
Это актуально или уже нет?

2022-08-04 14:23 UTC, valer1435 commented on test/unit/test_logger.py
> +def clear_singleton_class(klass=Log):
По-моему режет глаз. Может быть `_class` или `target_class`?

2022-08-04 14:23 UTC, valer1435 commented on test/unit/test_logger.py
> +    adapter_2 = default_log(prefix='warning_logger', logging_level=logging.WARNING)
Можешь пояснить, как будут работать два лога с разными уровнями, если лог - синглтон?

2022-08-04 14:26 UTC, MorrisNein commented on test/unit/test_logger.py
> +def clear_singleton_class(klass=Log):
Насколько я знаю, общепринятым является андерскор в конце, типа `class_`

2022-08-04 14:39 UTC, gkirgizov commented on test/unit/test_logger.py
> +    adapter_2 = default_log(prefix='warning_logger', logging_level=logging.WARNING)
согласен, у меня такой же вопрос, я планирую issue на это завести. не в рамках данного PR

2022-08-04 14:42 UTC, gkirgizov commented on test/unit/test_logger.py
> +def clear_singleton_class(klass=Log):
да по всякому можно, klass тоже юзают
но переименую

2022-08-04 14:43 UTC, gkirgizov commented on fedot/core/optimisers/opt_history.py
> +        return output.getvalue()
потому что тут separator ненулевой? не уверен что понял, в чем ты видишь проблему

2022-08-04 14:56 UTC, gkirgizov commented on test/unit/test_logger.py
> +    adapter_2 = default_log(prefix='warning_logger', logging_level=logging.WARNING)
https://github.com/nccr-itmo/FEDOT/issues/809

2022-08-04 14:57 UTC, gkirgizov commented on test/unit/conftest.py
> +    """Workaround for issue #765 (https://github.com/nccr-itmo/FEDOT/issues/765)
не особо, убрал

2022-08-05 08:07 UTC, MorrisNein commented on test/unit/test_logger.py
> +    clear_singleton_class(Log)
Не знал, что `pytest` способен так работать с `yield`. Спасибо!

2022-08-05 08:12 UTC, valer1435 commented on fedot/core/optimisers/opt_history.py
> +        return output.getvalue()
В первый раз вижу идею записи в поток, а потом возвращение значения) Стало интересно, в чем фишка, но теперь понял

2022-08-05 08:24 UTC, MorrisNein commented
Не по твоим изменениям, но ты вроде начал перенаправлять выходные сообщения в логер, предлагаю в рамках этого PR рассмотреть включение этих мест в логирование:

https://github.com/nccr-itmo/FEDOT/blob/2470e36de766ba0eb6d8b86711eef786720539d4/fedot/core/repository/operation_types_repository.py#L237

https://github.com/nccr-itmo/FEDOT/blob/50d8406d163c9b7a40a9eb20a5d3fe1c08095b11/fedot/core/operations/evaluation/operation_implementations/models/custom_model.py#L30

https://github.com/nccr-itmo/FEDOT/blob/751bf701a8ed82bf411552059ff39b87b89db25f/fedot/core/optimisers/gp_comp/individual.py#L39-L53

https://github.com/nccr-itmo/FEDOT/blob/2470e36de766ba0eb6d8b86711eef786720539d4/fedot/core/repository/operation_types_repository.py#L237

https://github.com/nccr-itmo/FEDOT/blob/31266613fbe3b8ddc9f661bd03ccb64c99347de0/fedot/core/visualisation/opt_viz.py#L48

https://github.com/nccr-itmo/FEDOT/blob/14d3d5f9e1fa20d932f5df28c8bacbb86235cc28/fedot/utilities/requirements_notificator.py#L13

2022-08-05 08:28 UTC, MorrisNein commented
> рамках этого PR

Конечно, если для этого не понадобится дополнительный рефакторинг

2022-08-05 09:51 UTC, MorrisNein approved these changes

2022-08-05 10:58 UTC, valer1435 approved these changes

2022-08-05 11:14 UTC, merged