GPU preset fix
nccr-itmo/FEDOT pull request #769
Opened 2022-07-09 08:59 UTC by nicl-nno

- [Fixed] List of models for GPU present was not obtaining correctly
- [Added] Test for GPU preset

2022-07-11 11:44 UTC, IIaKyJIuH requested changes

2022-07-11 11:44 UTC, IIaKyJIuH commented on fedot/api/api_utils/presets.py
> +            available_operations, _ = repository.suitable_operation(task_type=self.task.task_type)
Вообще я посмотрел - при вызове этой функции всегда пользуются только самими именами операций (первый аргумент), поэтому вижу смысл переделать её, чтобы не путать людей.

Нужно будет ещё семантизировать название и отразить, что возвращается, в докстринге.

2022-07-11 11:44 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
Я понял, что мы не предупреждаем тут об отсутствии этой библиотеки из-за того, что ниже есть попытка прочитать `KMeans`, хотя я понял это не с первого раза.

Может быть стоит перенести все уведомления для этого файла в этот блок try...except, а `KMeans` просто заменить на что-то, чтобы не было далее `NameError`? Те же мысли по поводу [fedot/core/operations/evaluation/gpu/common.py](https://github.com/nccr-itmo/FEDOT/pull/769/files#diff-883de6835be7545975efad596298e37ab022abb5ba0e2da9a16fef30badafc81)

2022-08-31 09:58 UTC, nicl-nno commented on fedot/api/api_utils/presets.py
> +            available_operations, _ = repository.suitable_operation(task_type=self.task.task_type)
Убрал второй возвращаемый параметр, добавил докстринг.

2022-08-31 09:58 UTC, nicl-nno commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
В этом скрипте обернул всё в один try. А в common вроде и так сделано как ты предложил?

2022-08-31 12:28 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
В этом файле теперь всё ок

А вот с `common.py` напрягает то, что тут может произойти уведомление по `cuml` минимум дважды

2022-08-31 12:44 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
Избавиться от этого можно, например, прописав всем объектам переменной `__operations_by_types` common файла None, но будет выглядеть громоздко.

Ну или как минимум во второй раз уже не уведомлять

2022-08-31 12:47 UTC, nicl-nno commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
Давай тогда может [так](https://github.com/nccr-itmo/FEDOT/pull/769/commits/61182247b82920c8ea59651a71ee8de89ef69b93).

2022-08-31 12:54 UTC, IIaKyJIuH commented on fedot/core/operations/evaluation/gpu/clustering.py
> +    from cuml import KMeans
Топич

2022-08-31 12:54 UTC, IIaKyJIuH approved these changes

2022-08-31 13:02 UTC, merged