Elitism operator
nccr-itmo/FEDOT pull request #772
Opened 2022-07-12 13:26 UTC by YamLyubov

Elitism operator is separated from inheritance and implemented as a class.
#706

2022-07-13 09:45 UTC, MorrisNein requested changes

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return sorted_population[:len(new_population)]
Я правильно понимаю, лучшие индивиды должны вытеснить только тех из нового поколения, которые хуже них?

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return new_population
А здесь точно не нужна сортировка?

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +            raise ValueError(f'Required elitism type not found: {type}')
Здесь не `type`, а `self.elitism_type`

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                if self.elitism and self.with_elitism(pop_size):
Не по твоим изменениям, но предлагаю более корректно назвать `with_elitism`. Имя выглядит как часть паттерна "строитель", будто мы что-то добавляем к объекту.

Хорошо бы подошло что-то вроде `is_elitism_needed`.

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +    def replace_worst_elitism(self, best_individuals: PopulationT, new_population: PopulationT):
Стоит указать тип возвращаемого значения у этого и соседнего методов

2022-07-13 09:45 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                if self.elitism and self.with_elitism(pop_size):
Ещё предлагаю в эту функцию вынести часть условия `if self.elitism`

2022-07-13 09:58 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return new_population
В этом случае идея состоит в том, что мы просто в новом поколении сохраняем лучших предствителей предыдущего. Как бы случайно заменяем индивидов нового поколения лучшими из старого. Это аналогично тому, как если бы мы на каждой итерации создавали pop_size - keep_n_best детей и добавляли к ним лучших из предыдущего поколения. По крайней мере у меня такая идея была)

2022-07-13 10:50 UTC, gkirgizov requested changes

2022-07-13 10:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                 elitism_type: ElitismTypesEnum = ElitismTypesEnum.none,
А для оптимизатора по умолчанию у нас сохраняется поведение как было (элитизм для 1 индивида)?

2022-07-13 10:50 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                if self.elitism and self.with_elitism(pop_size):
Почему бы не спрятать `with_elitism` в сам оператор? И обойтись без лишних проверок. Так сохранится однозначноть и простота -- мы просто вызываем оператор. А так получается что оператор не самодостаточен -- нам нужно еще что-то дополнительное знать, чтобы его правильно вызвать/не вызвать.

2022-07-13 11:35 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                 elitism_type: ElitismTypesEnum = ElitismTypesEnum.none,
Сейчас получается, что по умолчанию оптимизация без элитизма проходит

2022-07-13 16:04 UTC, valer1435 requested changes

2022-07-14 09:22 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                if self.elitism and self.with_elitism(pop_size):
Ну да, сейчас это лишняя проверка получается

2022-07-14 10:28 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                 elitism_type: ElitismTypesEnum = ElitismTypesEnum.none,
Вернула как было: по дуфолту сохраняется один лучший из предыдущего поколения.

2022-07-14 11:11 UTC, gkirgizov approved these changes
Пара небольших комментариев, в остальном все хорошо

2022-07-14 11:11 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +                 objective: Objective):
Я бы передавал напрямую multi_objective в параметры. 
Конструктор сейчас как бы говорит, ято ему нужна вся информация от Objective (метрики и тд), тогда как оператору нужен только один флаг. То есть он заявляет в своем интерфейсе о большем, чем реально использует. В таком случае лучше пусть он запрашивает только то что ему нужно — один булевый флаг.

2022-07-14 11:11 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        self._min_population_size_with_elitism = 5
Можно вынести как параметр инициализации с дефолтным значением

2022-07-14 11:11 UTC, gkirgizov commented on setup.py
> +README = Path(HERE, 'README.rst').read_text(encoding='utf-8')
Откуда эти изменения?

2022-07-14 11:12 UTC, gkirgizov commented
Хотя я не увидел тестов — пара простых модульных тестов на новый оператор нужна

2022-07-15 08:37 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return new_population
Тут есть нюанс, что если мы случайно или намеренно упорядочим поколение перед тем, как подавать сюда, замена будет вовсе не случайной. Как считаешь, может, сделаем рандом явным?

2022-07-15 13:37 UTC, gkirgizov approved these changes
Класс, теперь элитизм у нас на правах полноценного оператора

2022-07-19 07:38 UTC, valer1435 reviewed
Добавь, пожалуйста, в [этот ](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/api/test_main_api.py#L442)тест параметр `keep_n_best`

2022-07-19 07:38 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        else:
`else` тут не нужен, так как все равно выход из функции

2022-07-19 09:38 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        else:
Параметр [добавила](https://github.com/nccr-itmo/FEDOT/pull/772/commits/c92fc7a9bda0349deb4d0245629c2a715d478f4c#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fb), else [убрала](https://github.com/nccr-itmo/FEDOT/pull/772/commits/c92fc7a9bda0349deb4d0245629c2a715d478f4c#diff-8384f2ab5aedcff22b3233bfd2284f97395474a57b85ddb84920eb76caf9debf)

2022-07-19 10:12 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return new_population
Да, возможно это имеет смысл

2022-07-19 11:47 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        else:
Не совсем так - тест проверяет, что все параметры дошли до api_composer и он правильно их разделил. Надо добавить его в correct_composer_params или куда ты его добавила

2022-07-20 07:32 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        else:
Окей, я поняла

2022-07-20 08:57 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        else:
Добавила keep_n_best в correct_composer_params

2022-07-20 14:39 UTC, valer1435 approved these changes

2022-07-21 09:24 UTC, MorrisNein commented on fedot/core/optimisers/gp_comp/operators/elitism.py
> +        return new_population
Супер

2022-07-21 09:27 UTC, MorrisNein approved these changes

2022-07-21 09:28 UTC, merged