Mutation operator
nccr-itmo/FEDOT pull request #776
Opened 2022-07-15 12:08 UTC by YamLyubov

Mutation functions are wraped in a Mutation class. 
#706

2022-07-15 15:15 UTC, ChrisLisbon commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def single_edge_mutation(self, graph: Any, max_depth, *args, **kwargs):
Можно сюда небольшое описание этого типа?

2022-07-18 08:12 UTC, gkirgizov requested changes

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def _tree_growth(self, graph: Any, max_depth: int, local_growth=True):
Эта функция выглядит перегружено условиями, да еще и одинаковыми в разном порядку (local_growth, primary_node). Можно ее логику более очевидной сделать?

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def simple_mutation(self, graph: Any, **kwargs) -> Any:
Какие-то функции мутаций приватные, какие-то -- нет. Выглядит неконсистентно.

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +        for _ in range(MAX_NUM_OF_ATTEMPTS):
В случае рефакторинга из процедурной парадигмы в объектно-ориентированную такие константы стоит заменять на параметры класса

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def _mutation(self, individual: Individual, max_depth: Optional[int] = None) -> Any:
Предлагаю в рамках данного PR избавиться от лишних параметров оператору мутации. max_depth есть в requirements, и стоит отрефакторить использования так, чтобы этот параметр брался оттуда. Короче, должен быть один источник истины. Это поможет нам оператору к одному виду привести и работать с ними однообразно.

Если взять из requirements невозможно -- то можно предусмотреть более общий механизм "перезаписи" параметров из requirements, например через keywords. Но лучше постараться поглубже подумать над ипользованиями и понять, можно ли избежать этого и все-таки работать через общие requirements.

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
>  if TYPE_CHECKING:
Тут этот if правда нужен? Можно ли избежать циклического импорта?

2022-07-18 08:12 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def _mutation(self, individual: Individual, max_depth: Optional[int] = None) -> Any:
и где-то кажется возникает необходимость в подобной механике для mutation_prob

2022-07-18 08:53 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    def single_edge_mutation(self, graph: Any, max_depth, *args, **kwargs):
Хорошо, добавлю

2022-07-25 07:28 UTC, gkirgizov approved these changes
пара небольших комментов, в остальном все хорошо. удобно, что все изменения параметров из requirements теперь находятся в одном месте в оптимизаторе -- логика стала чуть очевиднее

2022-07-25 07:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +                self._update_requirements()
может, вместо того, чтобы вызывать и перед, и в конце цикла, можно вызывать этот метод в начале цикла?

2022-07-25 07:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            new_ind = self.mutation(choice(self.initial_individuals))
я бы тут добавил откат к исходным requirements, чтобы было очевидно, что это временная подмена параметров

2022-07-25 07:52 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
>  if TYPE_CHECKING:
Посмотрел на это тоже. Скорее,стоит передвинуть `ComposerRequirements` -> `optimizer.py` и `PipelineComposerRequirements` -> `gp_opimiser.py`. Они и по использованиям принадлежат этим модулям и логически, тк описывают параметры, используемые именно оптимизатором. Вроде бы это должно разорвать циклы. Также в `pipeline_node_factory` есть такой цикл с `if`. Может еще где есть, я бы просмотрел импорты в usages

2022-07-25 09:58 UTC, ChrisLisbon approved these changes

2022-07-25 10:43 UTC, merged