743 refactor usages of graph
nccr-itmo/FEDOT pull request #781
Opened 2022-07-18 13:22 UTC by maypink

WIP

2022-07-19 13:05 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:















* In the file [`fedot/core/optimisers/graph.py`](https://github.com/nccr-itmo/FEDOT/blob/dfc349cfb0257ebb85ea210bf25c7611f5fc72e2/fedot/core/optimisers/graph.py):

> [Line 181:37](https://github.com/nccr-itmo/FEDOT/blob/dfc349cfb0257ebb85ea210bf25c7611f5fc72e2/fedot/core/optimisers/graph.py#L181): [E128](https://duckduckgo.com/?q=pep8%20E128) continuation line under-indented for visual indent

2022-07-19 13:24 UTC, aPovidlo reviewed
Думаю, что стоит еще интеграционники прогнать, тк изменения фундаментальные и значительные

2022-07-19 13:24 UTC, aPovidlo commented on fedot/core/dag/graph_operator.py
> +    def node_children(self, node: GraphNode) -> List[Optional[GraphNode]]:
А нужно ли для единообразия привести в типизации аргумента либо к `GraphNode`, либо к `'GraphNode'` как уже было сделанно в `graph.py`?

2022-07-19 14:51 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +                                 new_node=PrimaryNode(nodes_from=node.nodes_from,
Кажется лишним передавать PrimaryNode nodes_from

2022-07-19 14:51 UTC, valer1435 commented on test/unit/visualization/test_visualisation_utils.py
> +    assert len(graph.nodes) == pipeline.length  # check node quantity
А тут можно `len(graph.nodes)` заменить на` graph.length`?

2022-07-20 09:02 UTC, maypink commented on fedot/core/dag/graph.py
> +        return self._operator.graph_depth()
вроде метод show() у пайплайнов и так не переопределяется при наследовании от графа

2022-07-20 09:03 UTC, maypink commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
и правда

2022-07-20 09:12 UTC, aPovidlo commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
@maypink @valer1435 Я сначала тоже подумал, что не обязательно. Потом решил проверить возможные варианты значений в выражении и пришёл к тому что лучше оставить.

2022-07-20 14:38 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
Почему?

2022-07-20 15:06 UTC, aPovidlo commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
@valer1435 ![image](https://user-images.githubusercontent.com/22475542/180016646-a4ce0570-93c3-4c62-b2b8-68ef492fe461.png)

2022-07-21 09:35 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
Можешь словами пояснить?

2022-07-21 10:20 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
![image](https://user-images.githubusercontent.com/32017472/180191196-0e2b63a3-9bf3-4667-a085-d96d7ecb14e9.png)
Если я правильно понял, то нет.

2022-07-21 10:21 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +            if new_graph.length == 0:
А, я догнал, все норм

2022-07-25 08:33 UTC, gkirgizov requested changes

2022-07-25 08:33 UTC, gkirgizov commented on fedot/core/dag/graph.py
> +    def get_all_edges(self) -> List[Tuple['GraphNode', 'GraphNode']]:
я бы назвал просто `edges` для единообразия с `nodes`

2022-07-25 08:33 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        height = graph.distance_to_root_level(node_parent)
я бы, пожалуй, избегал таких вызовов изнутри оператора -- ведь этот вызов все равно вернется к `graph.operator.distance_to_root_level` -- где-нибудь можно случайно на рекурсию нарваться

2022-07-25 08:33 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    graph.add_node(node_to_mutate)
эти три вызова выглядят как одна операция.  либо как добавление ноды + добавление ребра. а тут как-то хитро сначала нода добавляется а потом изнутри в ней указывается родитель. неочевидно

2022-07-25 08:33 UTC, gkirgizov commented on fedot/core/optimisers/graph.py
> +    def distance_to(self, other_graph: 'OptGraph') -> int:
Предлагаю это сделать внешней функцией, так как она не требует доступа к каким-то приватным данным/методам графа

2022-07-25 09:25 UTC, maypink commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    graph.add_node(node_to_mutate)
насколько я помню, суть этой мутации в том, что добавляется к ноде1 добавлется, как ребенок нода2 и все ребра из ноды1 становятся ребрами из ноды2

2022-07-25 09:53 UTC, maypink commented on fedot/core/optimisers/gp_comp/gp_operators.py
> +        height = graph.distance_to_root_level(node_parent)
не вижу повода для рекурсии, кажется ето другой оператор

2022-07-25 09:56 UTC, maypink commented on fedot/core/dag/graph.py
> +    def get_all_edges(self) -> List[Tuple['GraphNode', 'GraphNode']]:
[done](https://github.com/nccr-itmo/FEDOT/pull/781/commits/8431d0fe606227633331f82d4e4dbd4b0e9211fa#diff-ceaccb817954ebe86447994d40149207772f0c939d2d3abc31fb801bcc27197fR105)

2022-07-25 09:57 UTC, maypink commented on fedot/core/optimisers/graph.py
> +    def distance_to(self, other_graph: 'OptGraph') -> int:
[done](https://github.com/nccr-itmo/FEDOT/pull/781/commits/8431d0fe606227633331f82d4e4dbd4b0e9211fa#diff-1475cc1c326f6a332bfa373512539cf197ef69f169be81dad1e0098b295ca690R232)

2022-07-25 10:00 UTC, maypink commented on test/unit/visualization/test_visualisation_utils.py
> +    assert len(graph.nodes) == pipeline.length  # check node quantity
[done](https://github.com/nccr-itmo/FEDOT/pull/781/files#diff-b03629827fc8d98464401ca542c8f34af61cdcbf5b5a32e824bcfb00fa74913bR41)

2022-07-25 10:01 UTC, maypink commented on fedot/core/pipelines/pipeline.py
> +                                 new_node=PrimaryNode(nodes_from=node.nodes_from,
[done](https://github.com/nccr-itmo/FEDOT/pull/781/files#diff-234d33139f2520fa65ffcb8d6bb7a6958e97b3aae2cd3def0ac8cfd37f4a8d7aR62)

2022-07-25 10:02 UTC, maypink commented on fedot/core/dag/graph.py
> +    def get_nodes_degrees(self):
[done](https://github.com/nccr-itmo/FEDOT/pull/781/files#diff-ceaccb817954ebe86447994d40149207772f0c939d2d3abc31fb801bcc27197fR101)

2022-07-25 12:29 UTC, maypink commented on fedot/core/optimisers/gp_comp/operators/mutation.py
> +    graph.add_node(node_to_mutate)
[done](https://github.com/nccr-itmo/FEDOT/pull/781/commits/92a0a9a8eef58f83d599eff0a07e18c13343086b)

2022-07-26 09:38 UTC, valer1435 approved these changes
Неплохой PR👍

2022-07-26 10:04 UTC, gkirgizov approved these changes

2022-07-26 10:12 UTC, maypink commented
> Неплохой PR👍

нормально постаралась, сойдет

2022-07-26 12:53 UTC, merged