759 fix tuner metric
nccr-itmo/FEDOT pull request #784
Opened 2022-07-19 08:34 UTC by valer1435

Fix for https://github.com/nccr-itmo/FEDOT/issues/759 issue. Fisrt try to union metric for composer and tuner

2022-07-19 08:34 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:











* In the file [`fedot/api/api_utils/api_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/ffeebf0a32474f9d07f48eb02d89f216ee2f5470/fedot/api/api_utils/api_composer.py):

> [Line 269:84](https://github.com/nccr-itmo/FEDOT/blob/ffeebf0a32474f9d07f48eb02d89f216ee2f5470/fedot/api/api_utils/api_composer.py#L269): [E231](https://duckduckgo.com/?q=pep8%20E231) missing whitespace after ':'

2022-07-20 14:36 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +    def obtain_metric_for_tuning(self, tuner_metric: Union[None, str, Metric], task:Task, log: LoggerAdapter):
Metric- специальный надтип, в котором содержится callable

2022-07-20 14:36 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +            tuner_loss = self.obtain_metric_for_tuning(tuner_metric, task, log)
Пока нет. Хочу отрефакторить тюнинг попозже и привести все метрики к единому виду

2022-07-20 20:24 UTC, Dreamlone reviewed
Люба запросила моё ревью этого PR, а ты бессовестно его отозвал, но гитхаб (и я) всё помнит, и вот я здесь :)

2022-07-20 20:24 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Может лучше оставить одну метрику, чтобы она применялась для композирования и тюнинга. Случай, когда пригодилась бы функциональность с раздельными метриками тяжело придумать

2022-07-20 20:24 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
Тут такой момент: наверно исправлять авторегрессию стоит в отдельном PR, но если уже здесь начал, то пусть будет. Тогда поехали - 1) стоит написать тест, который проверяет, что параметры действительно меняются. И важно - все операции, внутри которых может происходить корректировка параметров следует прикрыть тегом  `correct_params` в `model_repository.json`. Этот тег по сути сообщает всем вышележащим абстракциям (таким как operation и node), что во время fit'а модель может свои гиперпараметры поменять, и надо обязательно их обновить в словаре с гиперпараметрами, который хранится в Node. Да, это функциональность неочевидна, с другой стороны, теперь ты о ней знаешь, и, как говорится, передай следующему

2022-07-20 20:24 UTC, Dreamlone commented on fedot/core/validation/tune/tabular.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
А что `cv_time_series_predictions` делает в tabular.py?

2022-07-20 20:24 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> +        elif isinstance(tuner_metric, Metric):
Возможно имеет смысл ограничиться только передачей строки с названием метрики - так проще будет обрабатывать. Сомневаюсь, что много пользователей FEDOT'а передают в поле метрики что-то своё (может не прав)

2022-07-20 22:31 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        elif isinstance(tuner_metric, Metric):
Ну сохранить возможность кастомизации метрики хочется, раз для композера это поддерживается.

2022-07-20 22:33 UTC, nicl-nno commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Согласен с Мишей. Если сможем одинаковые метрики использовать и для композирования и тюнинга - то одного поля должно хватить.

2022-07-21 09:33 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Пока такой возможности нет, так как метрики для тюнинга и композирования реализованы по-разному

2022-07-21 09:35 UTC, nicl-nno commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Ок, тогда это можно вынести на след. итерацию правок.

2022-07-21 09:35 UTC, nicl-nno approved these changes

2022-07-21 09:45 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Вроде это решается строчкой `tuner_metric = composer_metric` и убиранием tuner_metric из параметров API. composer_metric при этом можно переименовать просто в `metric` 
Унификация расчетов метрик для композера и тюнера это действительно отдельная задача

2022-07-21 09:46 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
Вообще думаю, что надо параметры моделей вынести в отдельную абстракцию, которая бы сама поддерживала изменение параметров при необходимости. Но вливать все в один pr не хочу - так как запутаемся

2022-07-21 09:47 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Ну и кажется Илья просил возможность задавать метрику для тюнинга

2022-07-21 09:55 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Я помню, что Илья хотел, чтобы в принципе метрика для тюнинга могла задаваться, но лучше конечно узнать из первоисточника

2022-07-21 10:10 UTC, nicl-nno commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Уточнил у Ильи:

"я просил чтобы метрика которая идёт через апи для композирования была такая же как и для тюнинга, потому что в ходе экспериментов такого функционала не было"

2022-07-26 08:35 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> +        elif isinstance(tuner_metric, Metric):
Здесь ничего не стала менять

2022-07-26 08:36 UTC, YamLyubov commented on examples/simple/classification/api_classification.py
> +                       max_pipeline_fit_time=1, composer_metric='roc_auc', tuner_metric='roc_auc')
Убрала возможность задавать tuning metric через api. Теперь метрика для тюнинга [выбирается](fedot/api/api_utils/api_composer.py) такая же composer metric.

2022-07-26 08:45 UTC, nicl-nno approved these changes

2022-07-26 08:47 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
В рамках этого pr решила с этим ничего не делать)

2022-07-26 08:54 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
Cоздай тогда плз issue про это, чтобы не забылось.

2022-07-26 10:01 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
Поговорила с Валерой, решили все-таки не откладывать, а сейчас довавить теги и тест.

2022-07-26 13:05 UTC, Dreamlone commented on fedot/core/validation/tune/tabular.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
До сих пор в tabular

2022-07-28 10:23 UTC, YamLyubov approved these changes

2022-07-28 10:30 UTC, YamLyubov commented on fedot/core/validation/tune/tabular.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Сейчас убрала

2022-07-28 10:31 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = _check_and_correct_window_size(source_ts,
Добавила [тест](test/unit/tasks/test_forecasting.py)

2022-07-28 19:10 UTC, Dreamlone requested changes

2022-07-28 19:10 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Есть функция с точно таким же названием `cv_time_series_predictions` в `fedot/core/validation/tune/time_series.py` и с точно таким же описанием

2022-07-28 19:10 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +    train_data, test_data = get_data_from_csv(Path(f'{fedot_project_root()}/examples/data/kc1.csv'),
Такого датасета нет

2022-07-28 19:38 UTC, Dreamlone commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
Не уверен связано ли это с текущими правками, но словил ошибку при запуске примера `examples/simple/time_series_forecasting/api_foresacting.py` трижды 

![image](https://user-images.githubusercontent.com/52418437/181620430-17e5fb02-1430-44f4-80c4-30c5345cc6e6.png)
P.S. Только timeout параметр я установил побольше дефолтного: 3 минуты поставил

2022-07-28 19:38 UTC, Dreamlone commented on fedot/utilities/define_metric_by_task.py
> +from fedot.core.composer.metrics import RMSE, ROCAUC, Silhouette, MSE
Тут есть неиспользуемые импорты

2022-07-28 19:38 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_tuning.py
> +                       target=np.array([1, 0, 1, 0, 1]),
Может разбить это дело на отдельные unit тесты по задачам: классификация метки, классификация вероятности, регрессия и т.д.?

2022-07-28 19:38 UTC, Dreamlone commented on test/unit/pipelines/test_pipeline_tuning.py
> +    assert _calculate_loss_function(Accuracy.metric, target, pred_prob) == -0.8
Лучше использовать `np.isclose` для сравнения float значений - так надежней

2022-07-28 19:38 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> -    folds_len_list = []
А может адаптировать этот тест, чтобы он проверял, что на временных рядах cv метрика считается как ожидается? Если это слишком время/трудо- затратно делать в рамках данного PR, можно создать issue и сделать пост-фактум

2022-07-28 19:43 UTC, Dreamlone reviewed
Еще обнаружил пустой файл `test/unit/utilities/test_define_metric_by_task.py`, снеси его плиз, раз в его названии есть слово metric и это PR тоже посвящен метрикам)

2022-07-30 13:54 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +        horizon = int(data.task.task_params.forecast_length * validation_blocks)
Можешь описать ситуацию, из-за которой пришлось дополнительно в int обернуть?

2022-07-30 13:56 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Можешь это тоже объяснить? Я не особо трогал мультимодальность. Но выглядит странно, что в одном случае берем таргет, в другом фичи

2022-08-01 20:29 UTC, Dreamlone commented
@YamLyubov, отпишись пожалуйста на комментарии, чтобы я понимал где и какие изменения с предыдущей итерации были сделаны

2022-08-02 09:39 UTC, YamLyubov commented
> Еще обнаружил пустой файл `test/unit/utilities/test_define_metric_by_task.py`, снеси его плиз, раз в его названии есть слово metric и этот PR тоже посвящен метрикам)

Этот файл удалила

2022-08-02 09:43 UTC, YamLyubov commented
> @YamLyubov, отпишись пожалуйста на комментарии, чтобы я понимал где и какие изменения с предыдущей итерации были сделаны

Вроде на все ответила уже

2022-08-02 09:54 UTC, YamLyubov commented on fedot/utilities/define_metric_by_task.py
> +from fedot.core.composer.metrics import RMSE, ROCAUC, Silhouette, MSE
Импорты [убрала](fedot/utilities/define_metric_by_task.py)

2022-08-02 10:03 UTC, Dreamlone commented on fedot/api/main.py
> +            if self.metrics.get_metrics_mapping(metric_name) is NotImplemented:
Да мне кажется всё таки стоит, обратную совместимость это все равно не сломает, так как она и так сломана после вынесения `composer_params`. Все таки metric более прозрачное название

2022-08-02 10:05 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Я бы предложил вынести cv_tabular_predictions и cv_time_series_predictions в отдельный py файл, так как в `tuner_interface.py` именно базовый класс для тюнеров лежит. А функции связанные с расчетом метрики на кросс валидации кмк уместнее хранить в отдельном месте

2022-08-02 10:07 UTC, Dreamlone commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
Ок, пусть пока будет так, но потом наверно стоит выяснить почему перестало работать 
@valer1435, как думаешь, тянет на отдельное issue? Или просто что-то не так было всегда именно с этим датасетом? - В таком случае его вообще стоит выпилить или предусмотреть исправление параметров. которые задает пользователь (ряд просто очень короткий - возможно в этом дело)

2022-08-02 10:18 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> -    folds_len_list = []
Направление в целом верное, но проверку можно улучшить. Так`get_simple_ts_pipeline` позволяет генерировать пайплайн, которые всегда будет выдавать одно и то же значение метрики - в ridge модели нет стохастичности. Значит можно проверять точное соответствие метрики через np.isclose (а не просто что она больше нуля и не None).

На разных фолдах будет разная метрика - это повод вынести количество фолдов и ожидаемую метрику в параметры теста. Сделать можно по аналогии с [этим тестом](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/data/test_data_split.py#L74) при помощи `@pytest.mark.parametrize`

2022-08-02 10:23 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Вообще во всех случаях надо тюниться по target временному ряду. Даже в одномодальном режиме могу придумать случай, когда мы по одному временному ряду пытаемся предсказать значение целевого той же длины. Поэтому независимо от типа решаемой задачи стоит всегда как целевой использовать тот ряд, который записан в target - не просто же так его туда запихали

2022-08-02 10:28 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +            actual_values = data.features[-horizon:]
А подскажи плиз какой именно тест падал? Вообще конечно такого быть не должно - если есть несоответствия с длинами рядов, то это говорит о том, что скорее всего что-то не так с разбиением. Исходно разбиения должны работать норм, так как написал довольно много тестов в [своем недавнем PR](https://github.com/nccr-itmo/FEDOT/pull/726) чтобы как раз такие ошибки отсекать - значит возможно какая-то сущность в ядре данные подправляет не так как надо

2022-08-02 11:04 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +        horizon = int(data.task.task_params.forecast_length * validation_blocks)
А как при умножений int на int получается float? Пишу, потому что вдруг есть неточность на уровень ниже

2022-08-02 12:21 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Эти функции используются только тюнером. Если их в отдельный файл вынести, то получится перекрестный импорт. Так как эти функции используются только тюнером, может их в tuner_interface  оставить?

2022-08-02 12:36 UTC, YamLyubov commented on test/unit/validation/test_time_series_cv.py
> -    folds_len_list = []
Мне нужно как-то вручную посчитать правильные значения метрик?

2022-08-02 12:36 UTC, valer1435 commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
В общем, в GLM есть недопустимые связки параметров (их все отследить будет сложно). Думаю следует сделать так, чтобы тюнер не падал при ошибке, а просто проскакивал некорректные значения

2022-08-02 12:39 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> -    folds_len_list = []
Просто поставь те значения, которые сейчас алгоритм выдает - убедись, что они правдоподобные и можно использовать их. Тогда если что-то сломается, то новые значения не будет соответствовать корректным старым значениям метрик

2022-08-02 12:40 UTC, Dreamlone commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
Так тюнер и так не падает при некорректных сочетаниях гиперпараметров - иначе бы мало пользы от него было) Проблема с этим возникает когда уже финальный пайплайн вышел из тюнера

2022-08-02 14:08 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Тут проблема в том, что при тюнинге data.target возвращает недостаточно значений. Я пока что не могу разобраться почему. Я видела, почему-то длина target не соответствует forecast_length * validation_blocks. Пока не отследила все потоки данных при обучении и тьюнинге, но похоже придется это сделать

2022-08-02 14:08 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        horizon = int(data.task.task_params.forecast_length * validation_blocks)
forecast_length по-моему float. Да ест смысл это раньше исправить

2022-08-03 07:48 UTC, valer1435 commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
Проверил в мастере - не падает. Похоже я потер try-except в тюнере

2022-08-03 07:54 UTC, valer1435 commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
@YamLyubov добавь, пожалуйста, [тут ](https://github.com/nccr-itmo/FEDOT/pull/784/files#diff-b026e9a744008b37dcd5ff67275723f10ff5b8c76023486d82830ec1d69f63e9R86) try, который я потер

2022-08-03 08:39 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +            actual_values = data.features[-horizon:]
Этот [тест](https://github.com/nccr-itmo/FEDOT/blob/34c0f3bb876c0595e5e3178e37b8e6e1129312b3/test/unit/api/test_api_cli_params.py#L30) падал по-моему

2022-08-03 09:06 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +            actual_values = data.features[-horizon:]
Падает [```test_cli_with_parameters```](https://github.com/nccr-itmo/FEDOT/blob/34c0f3bb876c0595e5e3178e37b8e6e1129312b3/test/unit/api/test_api_cli_params.py#L30)

2022-08-03 09:10 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +            actual_values = data.features[-horizon:]
Из-за описанного выше происходит ошибка при вычислении метрик для начальных индивидов и оптимизация не проходит

2022-08-03 12:12 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Но ведь они то тюнер не используют. То есть можно вынести в отдельный файл и потом просто импортировать в тюнере.

2022-08-03 12:14 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +        horizon = int(data.task.task_params.forecast_length * validation_blocks)
forecast_length вполне можно к int приводить - все равно горизонт прогнозирования 7.8 например смысла не имеет
Так что проблемы в рассматриваемой в данном треде строчке не вижу

2022-08-04 14:40 UTC, YamLyubov commented on fedot/api/main.py
> +            if self.metrics.get_metrics_mapping(metric_name) is NotImplemented:
[Переименовала ](fedot/api/main.py)

2022-08-04 14:49 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
```HyperoptTuner``` использует ```cv_tabular_predictions``` и ```cv_time_series_predictions```, а ```cv_tabular_predictions``` и ```cv_time_series_predictions``` используют ```_calculate_loss_function```, которая используется как тюнером, так и этими ```cv_..._predictions```.
Поэтому перекрестный импорт

2022-08-04 14:52 UTC, YamLyubov commented on fedot/core/validation/tune/time_series.py
> +    return metric_value / iter
[Вернула](fedot/core/composer/metrics.py).
И еще пофиксила [пример](examples/simple/time_series_forecasting/api_forecasting.py).

2022-08-04 14:53 UTC, YamLyubov commented on test/unit/validation/test_time_series_cv.py
> -    folds_len_list = []
Тест [изменила](test/unit/validation/test_time_series_cv.py).

2022-08-04 14:59 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Тут я нашла в чем загвоздка: если ряд слишком короткий, то он [не делится на фолды](https://github.com/nccr-itmo/FEDOT/blob/418cd0db051727e97856de4ccbaacd98b81bb981/fedot/core/validation/split.py#L137). Однако, это никак не отражается в дальнейшем - число блоков в параметрах не меняется. Когда доходим до _in_sample_prediction горизонт предсказания и длина таргета не совпадают. Пока это так [пофиксила](fedot/core/composer/metrics.py)

2022-08-05 06:56 UTC, valer1435 commented on fedot/core/composer/metrics.py
> +        horizon = len(actual_values)
Почему горизонт прогнозирования тут длина ряда?

2022-08-05 20:33 UTC, Dreamlone requested changes
Стоит ещё раз пройтись по примерам в examples и cases. Например не работает `examples/simple/regression/regression_with_tuning.py` , `examples/simple/classification/classification_with_tuning.py` `examples/simple/time_series_forecasting/tuning_pipelines.py`. Может есть ещё какие-нибудь падающие примеры с ошибками

2022-08-05 20:33 UTC, Dreamlone commented on examples/simple/classification/api_classification.py
> +    run_classification_example(timeout=2)
Вроде раньше пример работал, да и сейчас отработал, но вся консоль теперь в красном: 
![image](https://user-images.githubusercontent.com/52418437/183152705-e40a2e1c-22d9-47cd-b13d-eba73c07ead6.png)
![image](https://user-images.githubusercontent.com/52418437/183152786-ff7be7a1-ea26-4554-a35f-203655807195.png)

Python 3.7, зависимости из req.txt файла FEDOT'а

Ещё стоит взять на заметку, что иногда случается 
```
PipelineObjectiveEvaluate - Continuing after pipeline fit error <all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)>
```
Как я понял, это происходит из-за присутствия resample операции в пайплайне

2022-08-05 20:33 UTC, Dreamlone commented on fedot/api/api_utils/api_composer.py
> -        if composer_metric is None:
Стоит обновить комментарий, а лучше переделать его в docstring

2022-08-05 20:33 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Фолды и блоки при in-sample валидации это разные вещи. Так что вполне могу представить случай, когда фолд один (по сути hold out валидация), а блоков для insample несколько. 

Чтобы лучше понять как in-sample сопрягается с nested кросс-валидацией для временных рядов см. тут
![image](https://user-images.githubusercontent.com/52418437/183157947-892d833d-d391-467e-8d2d-5f02fd89402c.png)

2022-08-05 20:33 UTC, Dreamlone commented on fedot/core/composer/metrics.py
> +            horizon = len(actual_values)
Потенциально опасное место: по сути если временной как-то не так бьется, эта проверка ударит по проблеме кувалдой и скажет "а давай сравнивать хоть что-то с хоть чем-то, лишь бы длина совпадала".  И это не приведет к каким-то большим проблемам со стороны пользователя - ошибки нет, просто качество прогноза не очень, ну видимо фреймворк такой. 

В общем предлагаю либо явно выбрасывать ошибку до выяснения проблем (если такой баг встречается редко). Если же баг встречается часто, то до более подробного его изучения действительно можно поступить как сейчас сделано, только тогда стоит подготовить тест, который будет имитировать текущую ошибку с разной размерностью target и горизонта прогнозирования и убедиться, что предлагаемая правка устраняет проблему как требуется

2022-08-05 20:49 UTC, Dreamlone requested changes

2022-08-05 20:49 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size, self.parameters_changed = _check_and_correct_window_size(new_input_data.features,
Коррекция может ведь потребоваться и перед обучением (особенно при обучении). Вижу случай, когда делаем fit у пайплайна lagged - linear. На этапе fit у пайплайна коррекция параметра не производится и каким-либо чудом пайплайн все таки обучается. А теперь представим, что во время predict lagged выдает таблицу уже другой размерности (так как параметр скользящего окна был изменен) - linear упадёт с ошибкой

2022-08-05 20:49 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    if window_size > len(time_series) // 2 - 1:
Объясни плиз почему решила переделать? 
На всякий случай вот подробная инфографика объясняющая почему важно учитывать не только размер скользящего окна, но ещё и горизонт прогнозирования (мои комментарии в картинке по поводу модификаций системы индексирования временных рядов можешь игнорировать)

![Индексы временных рядов](https://user-images.githubusercontent.com/52418437/183160041-fa2f0a14-6bb5-4f8f-bde4-96ab1be62ff7.png)

2022-08-05 20:49 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag, self.lag_changed = _check_and_correct_window_size(source_ts,
Предлагаю все таки лучше реализовать свой отдельный метод для коррекции гиперпараметров именно у AR, а эту функцию оставить как есть

2022-08-05 20:49 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'lag': (hp.uniform, [2, 800])
Вся прелесть реализации AutoReg модели как мне казалось изначально как раз была в нативном использовании n лагов в модели одновременно. Если её этого лишить, то она по сути ничем не отличается от федотовской lagged реализации

2022-08-06 12:14 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Тогда можно перенести `cv_tabular_predictions`, `cv_time_series_predictions` и `_calculate_loss_function` перенести в отдельный файл
Только стоит `_calculate_loss_function` тогда переименовать в `calculate_loss_function`

2022-08-06 12:32 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_tabular_predictions(pipeline, reference_data: InputData, cv_folds: int, loss_function: Callable):
Меня очень смущает тот факт, что функции для расчета метрик каким-то образом из отдельно отведенного места (`fedot/core/validation`) перекочевали в `fedot/core/pipelines/tuning/tuner_interface.py`. При этом остались старые неиспользуемые артефакты, например функция cv_tabular_predictions есть как в этом месте, так и в `fedot/core/validation/tune/tabular.py`.

Тут есть несколько проблем: 

1) Скажем так, идеологическая. Модуль по валидации - это отдельная часть фреймворка, которая для соблюдения слабосвязности архитектуры располагается отдельно от композера или тюнера. Не знаю, насколько это именно сейчас соблюдается после рефакторинга архитектуры, проведенного Гришей и ко, но в начале года по крайней мере это было так. Тянуть расчет при валидации в тюнер не следует в первую очередь поэтому - у модуля валидации есть своя объемная и очень важная задача. 

2) Архитектура новой версии расчета метрик. Итак, некоторое время назад в `fedot/core/validation` было две папки: compose и tune. Каждый модуль содержал в себе функции для проведения hold out валидации и кросс-валидации на табличных данных и для временных рядов. Функции были очень близки иерархически, просто немного изменялись интерфейсы, так как одни вызывались в композере, а другие в тюнере. Теме не менее под капотом они использовали одинаковые принципы усреднения метрики и разбиения на фолды, блоки валидации, или одноразово train test. После изменений Гриши эта архитектура ушла: композер постепенно стал превращаться в экзогенную остальному фреймворку сущность, а тюнер остался, скажем, вросшимся монолитом в решения исходного FEDOT'а. И потому улетучилась основная идея, которую я пытался заложить во время реализации функций для валидации - "Унификация методов валидации независимо от их применения во время композироания или тюнинга" (даже несмотря на то, что сами метрики в композере и тюнере считаются по разному). Сейчас же валидация осталась в исходном виде только для тюнинга и я понимаю соблазн стянуть эти функции в тюнер, но предлагаю этого не делать. Пока предлагаю наметить план переработки тюнинга (который, очевидно, назрел) и действовать в соответствии с ним а пока в этом PR оставить такие моменты как перенос функций расчета и заметных модификаций самого тюнера на потом

2022-08-06 12:42 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> -        :param loss_params: dictionary with parameters for loss function
Здесь для loss_function описание устарело

2022-08-06 12:42 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if self.cv_folds is None:
А почему тут было решено убрать `try-except` блок?

2022-08-08 07:39 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        horizon = len(actual_values)
[Здесь](https://github.com/nccr-itmo/FEDOT/pull/784#discussion_r937900827) расписала подробнее. Получается, что при попытке разделить танные для кросс валидации мы делим на один фолд из-за того, что ряд слишком короткий, но в дальнейшем, когда делаем предикт это не учитывается. Чтобы правильно посчитать длину предикта берется длина таргета

2022-08-08 08:03 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size, self.parameters_changed = _check_and_correct_window_size(new_input_data.features,
Я этопоменяла, потому что ridge падал с ошибкой, так как во время предикта корректировался lag.

2022-08-08 08:12 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    if window_size > len(time_series) // 2 - 1:
Проблема была в том, что при вызове предикта для авторегрессии возникала ошибка в statsmodels. У [Autoreg](https://www.statsmodels.org/devel/generated/statsmodels.tsa.ar_model.AutoReg.html) есть параметр hold_out, который должен быть больше максимального лага. Во время предикта временной ряд обрезается следующим образом ```new_ts=ts[-hold_out:]``` и для предикта используется уже ```new_ts```. Поэтому, если log больше половины длины  ts, вылетает ошибка по типу index out of range.

2022-08-08 08:17 UTC, YamLyubov commented on fedot/core/pipelines/tuning/search_space.py
> +                'lag': (hp.uniform, [2, 800])
Насколько мы поняли из [документации](https://www.statsmodels.org/devel/generated/statsmodels.tsa.ar_model.AutoReg.html), если указывать два лага, то используются лишь два значения из ряда, а при указании одного лага все значение от 1 до lag. 

> lags{[None], [int], [list][[int]]}
> The number of lags to include in the model if an integer or the list of lag indices to include. For example, [1, 4] will only include lags 1 and 4 while lags=4 will include lags 1, 2, 3, and 4. None excludes all AR lags, and behave identically to 0.
> 

Лучше к двум лагам вернуть?

2022-08-08 08:41 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size, self.parameters_changed = _check_and_correct_window_size(new_input_data.features,
Так ведь он во время predict и будет меняться в новой реализации, а до этого он менялся и при обучении - можешь подготовить тест, который воспроизводит эту ошибку?

2022-08-08 08:42 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    if window_size > len(time_series) // 2 - 1:
Для авторегрессии лучше в отдельной реализации исправлять гиперпараметры

2022-08-08 08:43 UTC, Dreamlone commented on fedot/core/pipelines/tuning/search_space.py
> +                'lag': (hp.uniform, [2, 800])
Ага, лучше откатить к двум лагам, так как иначе AutoReg будет просто дублировать связку lagged - ridge (lagged - linear)

2022-08-08 11:33 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_tabular_predictions(pipeline, reference_data: InputData, cv_folds: int, loss_function: Callable):
Сейчас как раз и намечается [рефакторинг тюнера](https://github.com/nccr-itmo/FEDOT/issues/788).

2022-08-08 11:58 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        if isinstance(data, MultiModalData):
Да, действительно. [Исправила](fedot/core/validation/split.py) это передачей колличества validation_blocks в input_split. Для этого прищлось добавить **kwargs

2022-08-08 12:00 UTC, YamLyubov commented on fedot/core/composer/metrics.py
> +        horizon = len(actual_values)
Теперь actual_values и horizon считаются[ как предже](fedot/core/composer/metrics.py)

2022-08-08 12:02 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> -        if composer_metric is None:
[Переделала](fedot/api/api_utils/api_composer.py)

2022-08-08 12:06 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.window_size, self.parameters_changed = _check_and_correct_window_size(new_input_data.features,
Так как я разделила корректировку лага для lagged и AutoReg, этой проблемы больше нет и я [вернула](fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py) корректировку на ее прежнее место

2022-08-08 12:07 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +    if window_size > len(time_series) // 2 - 1:
Да теперь в отдельном месте [корректируется](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py)

2022-08-08 12:07 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag, self.lag_changed = _check_and_correct_window_size(source_ts,
[Реализован](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py)

2022-08-08 12:09 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if self.cv_folds is None:
Вернули обратно)

2022-08-08 12:12 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> -        :param loss_params: dictionary with parameters for loss function
[Изменила](fedot/core/pipelines/tuning/tuner_interface.py)

2022-08-08 12:59 UTC, YamLyubov commented on fedot/core/pipelines/tuning/search_space.py
> +                'lag': (hp.uniform, [2, 800])
[Вернула](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py) 2 лага

2022-08-09 11:32 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> -        :param loss_params: dictionary with parameters for loss function
Я имел в виду часть про `such function should take vector with true values as first values and predicted array as the second`

2022-08-09 11:45 UTC, Dreamlone commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Функции все ещё в `fedot/core/pipelines/tuning/tuner_interface.py`

2022-08-09 13:37 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        lag_1, self.lag1_changed = AutoRegImplementation._correct_lag(source_ts, lag_1, self.log)
Можно сделать метод не статическим и вызывать через `self._correct_lag` - заодно уйдёт параметр self.log из аргументов

2022-08-09 13:37 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        return lag, was_changed
Тут можно напрямую менять флаг, причем всего один. Нам ведь не так важно знать сколько параметров было изменено - важно только знать факт изменения, так что кмк достаточно lags_changed

2022-08-09 13:37 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        if lag_1 == lag_2:
Может это тоже спрятать в _correct_lag, чтобы модель сообщала о том, что исправила лаги?

2022-08-09 13:37 UTC, Dreamlone commented on test/unit/validation/test_time_series_cv.py
> +    assert metric_value > 0
Эти две проверки лишние - ниже перекрывает их обе

2022-08-10 08:42 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
В [этом коментарии](https://github.com/nccr-itmo/FEDOT/pull/784#discussion_r940134593) как раз писала о том, чтот не вижу смысла из сейчас выносить, так как в последующем pr собираюсь заменить использование этих функций вычислением ObjectiveEvaluate.evaluate()

2022-08-10 09:44 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        return lag, was_changed
То есть при вызове get_params достаточно будет в качестве списка измененных параметров возвращать ['lag_1', lag_2'], даже если только один из них поменялся? Мне кажется, все-таки лучше разделять эти случаи

2022-08-10 12:38 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        return lag, was_changed
> То есть при вызове get_params достаточно будет в качестве списка измененных параметров возвращать ['lag_1', lag_2'], даже если только один из них поменялся?

Ага. Ведь система работает так, что неважно поменялся один параметр или все сразу, в любом случае все параметры вышележащим абстракциям нужно будет предоставить

2022-08-10 12:45 UTC, Dreamlone commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        return lag, was_changed
Хотя сейчас посмотрел другие реализации, твой вариант и правда больше как classic style подходит, тогда согласен - давай оставим как ты предлагаешь

2022-08-10 13:26 UTC, YamLyubov commented on test/unit/validation/test_time_series_cv.py
> +    assert metric_value > 0
[Убрала](test/unit/validation/test_time_series_cv.py)

2022-08-10 13:28 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        if lag_1 == lag_2:
[Реализовала ](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py)метод ```_check_and_correct_lags```, в который эту проверку добавила.

2022-08-10 13:31 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> -        :param loss_params: dictionary with parameters for loss function
Теперь эту строку [поменяла](fedot/core/pipelines/tuning/tuner_interface.py))

2022-08-10 13:32 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_tabular_predictions(pipeline, reference_data: InputData, cv_folds: int, loss_function: Callable):
В общем я все-равно перенесла в отдельный [файл](fedot/core/validation/tune/cv_prediction.py)

2022-08-10 13:33 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +def cv_time_series_predictions(pipeline, reference_data: InputData, log,
Перенесла в отдельный [файл](https://github.com/nccr-itmo/FEDOT/pull/fedot/core/validation/tune/cv_prediction.py)

2022-08-10 13:34 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        return lag, was_changed
[Оставила ](fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py)два флага

2022-08-10 19:51 UTC, Dreamlone approved these changes

2022-08-11 09:34 UTC, merged