Genetic operators refactoring
nccr-itmo/FEDOT pull request #793
Opened 2022-07-25 14:36 UTC by YamLyubov

Refactoring of genetic operators. Regularization, crossover, inheritance and selection are separated as classes.
#706

2022-07-26 11:28 UTC, gkirgizov requested changes
Еще прогони интеграционные тесты. Это довольно большие изменения.
Также посмотри на external_optimizer.py -- там код немного сломан после PR с мутацией.

2022-07-26 11:28 UTC, gkirgizov commented on test/unit/composer/test_history.py
> +    available_operations = ['linear']
мб пустой оставить, чтобы не вводить в заблуждение, что список операций имеет значение

2022-07-26 11:28 UTC, gkirgizov commented on test/unit/composer/test_history.py
> +    available_operations = ['linear']
кстати, можно добавить в requirements значение по умолчанию пустой tuple

2022-07-26 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/inheritance.py
> +        return selected_individuals
может, передавать оператор селекции, а не конструировать свой заново? ведь мы все равно его собираем в том же месте, где и оператор наследования

2022-07-26 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/selection.py
> +        return zip(population[::2], population[1::2])
Получается, если мы захотим поменять логику селекции родителей в кроссовере -- нам придется менять никак не связанный с ним оператор селекции? Не очень удобно.

В целом, логика есть в том, что селекция родителей как-то относится к оператору селекции. Но эта функция никак не зависит от оператора селекции (static). Лучше избегать таких чисто логических зависимостей между модулями и оставить эту функцию в операторе кроссовера.

2022-07-26 14:32 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    def _get_new_individuals_with_proper_parent_operators(self, new_graphs, parent_individuals, crossover_type):
в этой функции скорее создаются новые индивиды и у них задаются верные операторы

2022-07-27 09:52 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    def _subtree_crossover(self, graph_first: Any, graph_second: Any) -> Any:
В каком смыле внешними: вне класса или public static внутри класса?

2022-07-27 10:03 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
>      from fedot.core.optimisers.optimizer import GraphGenerationParams
Да, можно убрать

2022-07-27 10:06 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _add_population_to_optimisation_history(self, next_population: PopulationT):
Может быть тогда назвать ```_move_to_next_population```? По названию ```_next_population``` не совсем понятно, что происходит

2022-07-27 12:54 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _add_population_to_optimisation_history(self, next_population: PopulationT):
update_population может ?

2022-07-27 12:58 UTC, gkirgizov commented on fedot/core/composer/composer.py
> +    secondary: List[str] = tuple()
тогда сигнатуру надо поменять на более общий тип, Sequence, например

2022-07-27 12:58 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _add_population_to_optimisation_history(self, next_population: PopulationT):
а то `move_to_` звучит так, будто мы куда-то перемещаем, а не переменную обновляем с сайд-эффектами

2022-07-27 13:16 UTC, gkirgizov requested changes

2022-07-27 13:16 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def get_operators(self):
может один раз этот список создать? он же не меняется

2022-07-27 13:16 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/operator.py
>  class Operator(ABC, Generic[T]):
Generic тогда нужно убрать, если типовая переменная T нигде не используется

2022-07-27 13:16 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    def _subtree_crossover(self, graph_first: Any, graph_second: Any) -> Any:
Вне класса, совсем независимыми

2022-07-27 13:16 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/operators/crossover.py
> +    def _get_new_individuals_with_proper_parent_operators(self, new_graphs, parent_individuals, crossover_type):
это так, но черезчур многословно, устаешь читать)

2022-07-28 13:37 UTC, maypink approved these changes

2022-07-29 11:24 UTC, gkirgizov reviewed
с интеграционными тестами все в порядке?

2022-07-29 11:24 UTC, gkirgizov commented on fedot/core/composer/composer.py
> +    secondary: List[str] = tuple()
пофикси тип, чтобы соответствовать значению

2022-07-29 11:24 UTC, gkirgizov commented on fedot/core/optimisers/populational_optimizer.py
> +    def update_native_generation_numbers(self, population: PopulationT):
метод стоит приватным сделать

2022-07-29 12:20 UTC, YamLyubov commented
> с интеграционными тестами все в порядке?

В интеграционных тестах операторы не используются напрямую

2022-07-29 12:50 UTC, gkirgizov commented
> > с интеграционными тестами все в порядке?
> 
> В интеграционных тестах операторы не используются напрямую

Так это интеграционные тесты, а не модульные. Они проверяют, что в целом все так же запускается, как ожидалось, и что ничего не сломалось в оптимизаторе

2022-08-01 10:08 UTC, merged