add PopulationalOptimiser
nccr-itmo/FEDOT pull request #795
Opened 2022-07-26 12:49 UTC by maypink

PR for #787

2022-07-26 14:45 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +class PopulationalOptimiser(GraphOptimiser):
PopulationalOptimiser можно вынести из gp_comp - т.к. это конкретная реализация эволюционного оптимизатора.

2022-07-27 11:08 UTC, gkirgizov commented
@maypink @YamLyubov Решите, кому из вас будет проще отребейзиться? Надо понять, этот или сей PR https://github.com/nccr-itmo/FEDOT/pull/793 первым залить

2022-07-27 11:28 UTC, gkirgizov requested changes

2022-07-27 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            self._next_population(new_population)
Может, использование этого метода вынести в PopulationalOptimiser? А то он там определен, но не используется. Кроме того, финальный апдейт поколения с логированием и тд звучит как то, что должно однообразно в любом популяционном методе производится

2022-07-27 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        while not self.stop_optimisation():
Может быть, разделить весь этот метод на что-то вроде `initial_population` и `evolve_population`? И реализовывать их. Думаю, сам цикл  с условием остановки к любому оптимизатору относится.

2022-07-27 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +        self.mutation = Mutation(parameters.mutation_types, graph_generation_params, requirements)
Мутация потребуется в любом популяционном методе?

2022-07-27 11:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +    def _extend_population(self, initial_individuals):
Метод определен здесь, но в классе не используется. Кто и в каких условиях его должен вызывать -- неочевидно, если не знать код и подклассы

2022-07-27 12:33 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +        self._graph_depth = AdaptiveGraphDepth(self.generations,
Адаптивные параметры во всех популяционных алгоритмах используются? Может их стоит вынести в EvoGraphOptimiser?

2022-07-27 12:34 UTC, YamLyubov commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +        self._graph_depth = AdaptiveGraphDepth(self.generations,
В таком случае _update_requirements тоже можно будет вынести

2022-07-27 13:56 UTC, maypink commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +class PopulationalOptimiser(GraphOptimiser):
[done](https://github.com/nccr-itmo/FEDOT/pull/795/commits/1aea12e9442496b695146aebc4dc4a64aee72d71)

2022-07-27 13:56 UTC, maypink commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +    def _extend_population(self, initial_individuals):
[done](https://github.com/nccr-itmo/FEDOT/pull/795/commits/70fe7c1bc17215262a74731a4f131cb525cf981a)

2022-07-27 14:15 UTC, maypink commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +        self._graph_depth = AdaptiveGraphDepth(self.generations,
[все параметры и _update_requirements теперь в evo](mmits/69c557baad88779d37af6f75f1063573cfbbb499#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R95)

2022-07-27 14:16 UTC, maypink commented on fedot/core/optimisers/gp_comp/populational_optimiser.py
> +        self.mutation = Mutation(parameters.mutation_types, graph_generation_params, requirements)
[done](https://github.com/nccr-itmo/FEDOT/pull/795/commits/69c557baad88779d37af6f75f1063573cfbbb499#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R92)

2022-07-27 14:16 UTC, maypink commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +        while not self.stop_optimisation():
[done](https://github.com/nccr-itmo/FEDOT/pull/795/files#diff-54921b8e7684e04131459f7dd7ffcbfe64fa4f5ff3eedfbb52441a301d000c79R149)

2022-07-27 14:18 UTC, maypink commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +            self._next_population(new_population)
[done](https://github.com/nccr-itmo/FEDOT/pull/795/commits/2ad51512273a3b4e3dbb598989daa21f60bfeb37#diff-61d3645c0906bd34a54bf61e60ae8b1cd25904dbfa178233e6dae1d61ac293ecR168)

2022-07-28 08:28 UTC, gkirgizov approved these changes
Все отлично, теперь можно и муравьев запускать в федот, и волчьи стаи..

2022-07-28 08:28 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/gp_optimiser.py
> +    def _evolve_population(self, evaluator: Callable):
Возвращаемый тип только добавить тут и выше

2022-07-28 12:05 UTC, YamLyubov approved these changes

2022-07-28 12:20 UTC, nicl-nno approved these changes

2022-07-28 12:22 UTC, merged