Simplify & rename DataObjectiveBuilder
nccr-itmo/FEDOT pull request #796
Opened 2022-07-27 13:31 UTC by gkirgizov

Minor PR. Now this class only determines how to split the data (holdout, kfold or no split).
Few more minor refactorings.

2022-07-27 14:13 UTC, IIaKyJIuH requested changes

2022-07-27 14:13 UTC, IIaKyJIuH commented on fedot/core/composer/gp_composer/gp_composer.py
> +    :param history: optimisation history
Предлагаю в таких вопросах американских/английских традиций определиться, какому суффиксу отдавать предпочтение, путают разночтения в проекте

2022-07-27 14:13 UTC, IIaKyJIuH commented on test/unit/data/test_data_split.py
> +    objective_builder = DataSourceBuilder(objective=Objective([metric_function]), cv_folds=2, validation_blocks=2)
Лишний аргумент `objective`, его больше нет

2022-07-27 14:13 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
> +    objective_builder = DataSourceBuilder(Objective([metric_function]))
Здесь тоже уже не актуальна передача `objective`

2022-07-27 14:13 UTC, IIaKyJIuH commented on test/unit/composer/test_history.py
> +    objective_builder = DataSourceBuilder(Objective(metrics))
И здесь `objective`

2022-07-28 08:01 UTC, gkirgizov commented on fedot/core/composer/gp_composer/gp_composer.py
> +    :param history: optimisation history
Согласен. Тогда, думаю, лучше остановиться на американском в силу большей распространенности

2022-07-28 08:23 UTC, gkirgizov commented on test/unit/data/test_data_split.py
> +    objective_builder = DataSourceBuilder(objective=Objective([metric_function]), cv_folds=2, validation_blocks=2)
пофиксил это и остальные

2022-07-29 12:54 UTC, IIaKyJIuH requested changes

2022-07-29 12:54 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/operators/operator.py
> +from typing import TypeVar, Generic, Sequence, Callable, Collection
`Collection` тут не используется

2022-08-08 08:31 UTC, IIaKyJIuH approved these changes

2022-08-08 08:39 UTC, merged