`Graph` visualizations improvement
nccr-itmo/FEDOT pull request #798
Opened 2022-07-29 13:13 UTC by MorrisNein

- Refactored default graph representations by Networkx.
- Added 'pyvis' visualization engine for interactive graph views via html.
- Added 'graphviz' visualization engine (requires [Graphviz](https://graphviz.org/) and [pygraphviz](https://pygraphviz.github.io/)).

![image](https://user-images.githubusercontent.com/57573631/181765590-c239195e-8561-488d-bb3f-2afd0f18b532.png)

![image](https://user-images.githubusercontent.com/57573631/181765554-b4638c5a-8175-4bb4-a5d2-7031ea51e95e.png)

![image](https://user-images.githubusercontent.com/57573631/181767119-32f16c15-96df-4695-93c0-1f65d6585c6a.png)

![image](https://user-images.githubusercontent.com/57573631/181765204-88c5f90a-08a6-4d18-8e05-f601ec64e296.png)

![image](https://user-images.githubusercontent.com/57573631/181765360-2ad2c6ed-d800-4c9b-bd6e-71e2f6f7f379.png)

![image](https://user-images.githubusercontent.com/57573631/181766434-1be21c18-eee5-460d-8910-7fec347f5dca.png)

![image](https://user-images.githubusercontent.com/57573631/181765069-d01e2d05-f7da-487e-87f1-d517ed8471b7.png)

2022-07-29 13:13 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:













* In the file [`fedot/core/visualisation/graph_viz.py`](https://github.com/nccr-itmo/FEDOT/blob/8edae3df65ac7a968fd8619ae6a661e88ba61eae/fedot/core/visualisation/graph_viz.py):

> [Line 220:32](https://github.com/nccr-itmo/FEDOT/blob/8edae3df65ac7a968fd8619ae6a661e88ba61eae/fedot/core/visualisation/graph_viz.py#L220): [E741](https://duckduckgo.com/?q=pep8%20E741) ambiguous variable name 'l'

2022-08-03 06:39 UTC, IIaKyJIuH requested changes

2022-08-03 06:39 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +    for path in os.listdir(dir):
Тебе сюда приходит объект pathlib, не пройдёт с `dir.iterdir()`? Тогда итерироваться будешь сразу по объектам с типом Path

2022-08-03 06:39 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +        if datetime.datetime.now() - datetime.datetime.fromtimestamp(os.path.getctime(path)) > time_interval:
Должно подойти: `path.stat().st_ctime`

2022-08-03 06:39 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +            os.remove(path)
Тут должен подойти: `path.unlink()`

2022-08-03 06:39 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_viz.py
> +                save_path = Path(os.getcwd(), save_path)
Как насчёт `Path.cwd().joinpath(save_path)`?

2022-08-03 06:39 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_viz.py
> +                wrapped_text[first_tag_line][second_tag_char:]
Мне кажется, что гораздо читабельнее в таком стиле (тут и далее):
```python
wrapped_text[first_tag_line] = (
    wrapped_text[first_tag_line][:first_tag_char] +
    format_text(wrapped_text[first_tag_line][first_tag_char:second_tag_char], html_format_tag) +
    wrapped_text[first_tag_line][second_tag_char:]
)
```
Считаю, что вообще зря эти обратные слеши в питоне есть)

2022-08-03 06:50 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +        if not nodes_color and type(graph).__name__ in ('Pipeline', 'OptGraph'):
Там так сделано до меня, пробовал, возникает циклический импорт

2022-08-03 07:00 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +        if not nodes_color and type(graph).__name__ in ('Pipeline', 'OptGraph'):
Очень странно, но ладно

2022-08-03 07:11 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +        if not nodes_color and type(graph).__name__ in ('Pipeline', 'OptGraph'):
Думается, что это можно решить, только нужно будет в файлах этих классов добавить обработку модулей, используемых лишь для типизации, по переменной `typing.TYPE_CHECKING` и, возможно, по аналогии внутри честно импортированных модулей

2022-08-03 08:59 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +        if not nodes_color and type(graph).__name__ in ('Pipeline', 'OptGraph'):
Кажется, [это место](https://github.com/nccr-itmo/FEDOT/blob/7a4787ce9316454081c681378033d628164a29dd/fedot/core/optimisers/graph.py#L201-L203) должно помешать.

2022-08-04 09:25 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +        curved_connection_style = 'arc3,rad={}'
Да, [действительно](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7897b3d3800c219ab746f4706beef11d5ecbd0ac#diff-6c717e9b2569e9480813248a3eb82a1e3b584ba17b407a31c44e7a5d9226bde7R145)

2022-08-04 09:25 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +    for path in os.listdir(dir):
[Поправил](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7897b3d3800c219ab746f4706beef11d5ecbd0ac#diff-6c717e9b2569e9480813248a3eb82a1e3b584ba17b407a31c44e7a5d9226bde7R251-R254), спасибо

2022-08-04 09:25 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +        if datetime.datetime.now() - datetime.datetime.fromtimestamp(os.path.getctime(path)) > time_interval:
[Done](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7897b3d3800c219ab746f4706beef11d5ecbd0ac#diff-6c717e9b2569e9480813248a3eb82a1e3b584ba17b407a31c44e7a5d9226bde7R251-R254)

2022-08-04 09:26 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +            os.remove(path)
[Done](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7897b3d3800c219ab746f4706beef11d5ecbd0ac#diff-6c717e9b2569e9480813248a3eb82a1e3b584ba17b407a31c44e7a5d9226bde7R251-R254)

2022-08-04 09:27 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +                save_path = Path(os.getcwd(), save_path)
[Заменил](https://github.com/nccr-itmo/FEDOT/pull/798/commits/c881929983ddcc9d1fda1fd96b062d99384e49cb) по проекту такие вхождения

2022-08-04 09:27 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +                wrapped_text[first_tag_line][second_tag_char:]
Хорошо, пусть будет [так](https://github.com/nccr-itmo/FEDOT/pull/798/commits/9e55150994586f092cdebdc71e6255a7abdd54c4)

2022-08-04 09:55 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_viz.py
> +                save_path = Path(os.getcwd(), save_path)
Хорош

2022-08-04 09:56 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_viz.py
> +                wrapped_text[first_tag_line][second_tag_char:]
Круто, спасибо)

2022-08-04 09:58 UTC, IIaKyJIuH approved these changes

2022-08-04 15:10 UTC, andreygetmanov requested changes

2022-08-05 10:45 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +            size = min_size + int((max_size - min_size) / log2(max(nodes_amount, 2)))
До моих правок там была другая функция того же порядка, но она нигде не использовалась. 
Проверил её на практике, работает неплохо, привёл к виду с явными границами значений и заюзал.

2022-08-05 10:54 UTC, MorrisNein commented on fedot/core/dag/graph.py
> +             nodes_color: Optional[Any] = None, edges_curvature: float = 0.25):
[Готово](https://github.com/nccr-itmo/FEDOT/pull/798/commits/21e018348f11508f1ff7ac1dad416dd7b7f3ba9c)

2022-08-05 10:54 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +from numpy.linalg import norm
Согласен, [сделал](https://github.com/nccr-itmo/FEDOT/pull/798/commits/e4f492588c5e8f9a03bbc73ed259582bb7246265)

2022-08-05 10:55 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +            plt.savefig(save_path, dpi=300)
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7a3afec0689b78aae8852f858399cee0ef76ac55) параметром с верхнего уровня

2022-08-05 10:55 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +            for n in (u, v):
[Done](https://github.com/nccr-itmo/FEDOT/pull/798/commits/42954da869df13f275ddf2820ade4546a2e9c87d)

2022-08-05 12:49 UTC, andreygetmanov commented on fedot/core/visualisation/graph_viz.py
> +            plt.savefig(save_path, dpi=300)
> [Сделал](https://github.com/nccr-itmo/FEDOT/pull/798/commits/7a3afec0689b78aae8852f858399cee0ef76ac55) параметром с верхнего уровня

Да, так даже ещё лучше будет!

2022-08-05 12:56 UTC, andreygetmanov approved these changes

2022-08-08 07:23 UTC, IIaKyJIuH requested changes

2022-08-08 07:23 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +    return {label: palette[unique_labels.index(label)] for label in labels}
Есть смысл пометить их приватными?

2022-08-08 08:30 UTC, IIaKyJIuH requested changes

2022-08-08 08:30 UTC, IIaKyJIuH commented on fedot/core/optimisers/graph.py
> +        GraphVisualiser().visualise(self, save_path, engine, nodes_color, dpi, edges_curvature)
Напомните, плз, почему нельзя задать `Graph` и `OptGraph` общий базовый класс, чтобы не приходилось копировать методы, подобные этому?

2022-08-08 14:30 UTC, nicl-nno commented on fedot/core/optimisers/graph.py
> +        GraphVisualiser().visualise(self, save_path, engine, nodes_color, dpi, edges_curvature)
Это логическое разделение, чтобы минимизировать связность оптимизатора и класса Pipeline. Но в https://github.com/nccr-itmo/FEDOT/pull/750 это как раз переделано.

2022-08-08 16:47 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
>              raise NotImplementedError(f'Oops, plot type {plot_type.name} has no function to show!')
Разве так не удобнее использовать?

2022-08-08 16:48 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
>              raise NotImplementedError(f'Oops, plot type {plot_type.name} has no function to show!')
Я просто не очень представляю выгоды подхода со словарем параметров. На мой взгляд, лучше такого по возможности избегать

2022-08-10 12:56 UTC, IIaKyJIuH commented on fedot/core/optimisers/opt_history.py
>              raise NotImplementedError(f'Oops, plot type {plot_type.name} has no function to show!')
Тут бы вообще использовать pattern-matching, по-хорошему, но как бы не получится

Не знаю, может лично у меня так, но элсыфы плохо читаю

2022-08-10 18:54 UTC, MorrisNein commented on fedot/core/optimisers/opt_history.py
>              raise NotImplementedError(f'Oops, plot type {plot_type.name} has no function to show!')
Я, видимо, сразу не понял, о чём твой коммент. Теперь дошло. 
Уже на другой ветке начал рефачить визуализации, чтобы переиспользуемый код не выносить в функции, а использовать наследование и переопределение.

От этого условия как раз избавит: основная задача визуализатора в новом формате это вернуть визуализацию нужного класса. Этот выбор реализую через словарь. Предлагаю это оставить до другого PR.

2022-08-10 22:25 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +    return {label: palette[unique_labels.index(label)] for label in labels}
Полагаю, да. [Полностью спрятал](https://github.com/nccr-itmo/FEDOT/pull/798/commits/85252c8f05b2698549b1c24f3050af979532d8d1) их в классе GraphVizualiser

2022-08-11 16:23 UTC, nicl-nno approved these changes

2022-08-12 06:52 UTC, IIaKyJIuH requested changes

2022-08-12 06:52 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +    def draw_with_pyvis(graph, save_path, nodes_color=__get_colors_by_tags):
Тут ошибка возникнет, если не написать `...__get_colors_by_tags.__func__):`

https://stackoverflow.com/questions/41921255/staticmethod-object-is-not-callable

2022-08-12 06:52 UTC, IIaKyJIuH commented on fedot/core/visualisation/graph_viz.py
> +        if len(graph.nodes) == 0:
Не принципиально, но не проще ли такое записывать `if not graph.nodes:...`?

2022-08-12 07:01 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +    def draw_with_pyvis(graph, save_path, nodes_color=__get_colors_by_tags):
Странно, почему тесты не упали

2022-08-12 07:05 UTC, MorrisNein commented on fedot/core/visualisation/graph_viz.py
> +    def draw_with_pyvis(graph, save_path, nodes_color=__get_colors_by_tags):
Вижу, потому что передаём значение в вызов функции

2022-08-16 09:36 UTC, IIaKyJIuH approved these changes

2022-08-16 12:19 UTC, MorrisNein commented
**'matplotlib' engine (default view)**
![image](https://user-images.githubusercontent.com/57573631/181770764-83b54479-448b-4c9c-8ab4-72c3e8fe95a5.png)

![image](https://user-images.githubusercontent.com/57573631/181765590-c239195e-8561-488d-bb3f-2afd0f18b532.png)

![image](https://user-images.githubusercontent.com/57573631/181765360-2ad2c6ed-d800-4c9b-bd6e-71e2f6f7f379.png)



**'graphviz' engine**

![image](https://user-images.githubusercontent.com/57573631/181770912-4917beb9-b43e-4073-97c9-db3d3ce55d3e.png)


![image](https://user-images.githubusercontent.com/57573631/181765554-b4638c5a-8175-4bb4-a5d2-7031ea51e95e.png)

![image](https://user-images.githubusercontent.com/57573631/181765204-88c5f90a-08a6-4d18-8e05-f601ec64e296.png)

**'pyvis' engine (all nodes are moveable by drag-and-drop after rendering)**

![image](https://user-images.githubusercontent.com/57573631/181771199-11f2b86f-12d2-46bc-814f-732748ab4dae.png)


![image](https://user-images.githubusercontent.com/57573631/181767119-32f16c15-96df-4695-93c0-1f65d6585c6a.png)

![image](https://user-images.githubusercontent.com/57573631/181766434-1be21c18-eee5-460d-8910-7fec347f5dca.png)

**In synergy with history visualization**
![image](https://user-images.githubusercontent.com/57573631/181765069-d01e2d05-f7da-487e-87f1-d517ed8471b7.png)

**Large chain in pyvis**
![image](https://user-images.githubusercontent.com/57573631/181768800-e4d916fc-e592-41cd-bfd6-09333ae9cb1d.png)

**pyvis shows the selected node's params**
![image](https://user-images.githubusercontent.com/57573631/182029309-1232371d-f39e-4dea-be0e-b99ff653625c.png)

**nodes_color='black'**
![image](https://user-images.githubusercontent.com/57573631/181772054-b69eb9bf-a19e-4f76-a25f-7524fc38b221.png)![image](https://user-images.githubusercontent.com/57573631/181772027-540beeb9-c1ac-439a-8283-1b6f0ace6d49.png)

2022-08-16 12:21 UTC, merged