735-improving-fedot-documentation
nccr-itmo/FEDOT pull request #804
Opened 2022-08-03 11:36 UTC by IIaKyJIuH

Partial improvement.

1. Changed structure of the documentation according to [this document](https://docs.google.com/document/d/1maEzEP2dawy_aoDN2kTUw7A3pLdHvvqEyPt99MXggrs/edit)
2. Added docstrings to classes/functions/props and improved existing ones
3. Created `copy_doc` decorator to copy docstrings for logically the same functions
4. Improved code blocks, typings, variables names

2022-08-03 11:36 UTC, pep8speaks commented
Hello @IIaKyJIuH! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









* In the file [`fedot/core/dag/graph.py`](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/graph.py):

> [Line 28:9](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/graph.py#L28): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line



* In the file [`fedot/core/dag/graph_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/graph_operator.py):

> [Line 51:121](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/graph_operator.py#L51): [E501](https://duckduckgo.com/?q=pep8%20E501) line too long (122 > 120 characters)

* In the file [`fedot/core/dag/node_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/node_operator.py):

> [Line 33:9](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/dag/node_operator.py#L33): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line







* In the file [`fedot/core/pipelines/node.py`](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/pipelines/node.py):

> [Line 450:5](https://github.com/nccr-itmo/FEDOT/blob/903a258462060a417f01856d46a8624e3cfde22f/fedot/core/pipelines/node.py#L450): [E125](https://duckduckgo.com/?q=pep8%20E125) continuation line with same indent as next logical line

2022-08-03 11:43 UTC, IIaKyJIuH commented
В этом PR упор делается на изменение структуры всей документации, чем на текст.

Так что не обращайте особо внимание на те докстринги, которые я изменил или добавил, всё равно @DenisSidoren изменит всю документацию.

2022-08-03 20:36 UTC, nicl-nno commented
А в read-the-docs можно посмотреть на собранную версию с этими правками?

2022-08-03 20:37 UTC, nicl-nno commented on docs/source/basics/ts_forecasting.rst
> +Timer Series Forecasting
Time

2022-08-03 20:39 UTC, nicl-nno commented on docs/source/basics/project_import_export.rst
>  Example of project import and export
Думаю импорт-экспорт проектов можно отправить в advanced. Ну и в файле про импорт паймплайнов упомянуть и дать ссылку

2022-08-04 07:58 UTC, DenisSidoren commented
> А в read-the-docs можно посмотреть на собранную версию с этими правками?

В rtd настроено автоматическое формирование документации для каждого PR - посмогтреть можно в сборках там..

Но и тут, в checks должна появляться ссылка на эту версию документации, возможно, в checks показывается не более 3 записей и это как-то можно поменять в настройках

2022-08-04 08:14 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/182798042-de5dbb72-0744-45f7-921e-65578bbf07c0.png)

Идеи по неймингу разделов. Мб ещё какие-то идеи будут, как сделать понятнее и лаконичнее.

2022-08-04 08:25 UTC, DenisSidoren commented
> ![image](https://user-images.githubusercontent.com/5711814/182798042-de5dbb72-0744-45f7-921e-65578bbf07c0.png)
> 
> Идеи по неймингу разделов. Мб ещё какие-то идеи будут, как сделать понятнее и лаконичнее.

Classes -> Code structure -> Modules (Units/ Components etc) in details

2022-08-04 10:25 UTC, IIaKyJIuH commented on docs/source/basics/project_import_export.rst
>  Example of project import and export
[Done](https://github.com/nccr-itmo/FEDOT/pull/804/commits/899cf0399882f02b2899134912d5e617d0b4cb80#diff-e413647dfeb1e75de8334021d8e13318d33b53230f4b74fef96bb5dc0dcf8676)

2022-08-04 10:25 UTC, IIaKyJIuH commented on docs/source/basics/ts_forecasting.rst
> +Timer Series Forecasting
[Done](https://github.com/nccr-itmo/FEDOT/pull/804/commits/899cf0399882f02b2899134912d5e617d0b4cb80#diff-081c74510a99d7346bfdbc2d3140fefa83d1caa2eddaa09d76bd910d60175c1f)

2022-08-04 11:24 UTC, IIaKyJIuH commented
> А в read-the-docs можно посмотреть на собранную версию с этими правками?

[Ссылка на собранную документацию](https://fedot.readthedocs.io/en/735-improving-fedot-documentation/api/index.html)

2022-08-05 12:56 UTC, gkirgizov requested changes

2022-08-05 12:56 UTC, gkirgizov commented on docs/source/faq/index.rst
> +   others
Оказывается, что первые возникающие, самые общие вопросы оказываются где-то в третьем разделе "Остального". Кроме того, раздел "Conceptual" не очень хорошо сообщает, о чем он. Скорее название раздела выщывает вопросы. Предлагаю объединить Conceptual & Others, переименовать в General и поставить их первым разделом.

2022-08-05 12:56 UTC, gkirgizov commented on docs/source/index.rst
> -   faq
faq как правило ставят в конце, почему решили перенести?

2022-08-05 12:56 UTC, gkirgizov commented on docs/source/index.rst
может быть, tutorials должен быть после basics? а advanced_usage где-то после туториалов? я бы как новый пользователь сначала глядел в туториалы, чем в продвинутые разделы. до них где-то в конце обычно доходят

2022-08-05 12:56 UTC, gkirgizov commented on docs/source/index.rst
Кстати, я в туториалах подумал скорее про какие-то jupyter notebooks, а там внезапно Instalation. Может, установку поставить отдельным разделом в начало, после Introduction? или в сам Introduction?

2022-08-08 08:42 UTC, IIaKyJIuH commented on docs/source/index.rst
> -   faq
Скорее всего, чтобы отразить в коде структуру самой документации
Думаешь, лучше в конце поместить?

2022-08-08 11:05 UTC, IIaKyJIuH commented on docs/source/faq/index.rst
> +   others
Может быть тогда лучше засунуть те вопросы, которые не касаются самого внутреннего устройства (т.е. сейчас все из "Others"), в "Abstract", а "Conceptual" переименовать в "API Usage"?

2022-08-08 11:09 UTC, IIaKyJIuH commented on docs/source/index.rst
> -   faq
Перечитал вопрос, сначала не так понял его

@nicl-nno напомни, почему быть FAQ разделу лучше не в самом конце?

2022-08-08 11:10 UTC, gkirgizov commented on docs/source/index.rst
> -   faq
да. пожалуй. кажется более привычным. faq, кмк, отвечает на те вопросы, которые остаются после прочтения основных разделов. можно опрос в нашем чате провести

2022-08-08 12:52 UTC, nicl-nno commented on docs/source/index.rst
> -   faq
Да давайте в конец, не принципиально.

2022-08-08 14:15 UTC, nicl-nno commented
Как альтернативный вариант - вручную выделать несколько высокоуровневых разделов, на который разбить описание интерфейсов классов. API/Pipeline/Optimiser/etc

2022-08-08 20:48 UTC, nicl-nno approved these changes
В целом в этом PR можно влить базовые структурные правки, а раздел modules уже отдельно менять.

2022-08-11 06:07 UTC, IIaKyJIuH commented on docs/source/index.rst
> -   faq
[Done](https://github.com/nccr-itmo/FEDOT/pull/804/commits/e4173c93e21eeb7fe942025871986e212ed324c7)

2022-08-11 06:25 UTC, IIaKyJIuH commented on docs/source/index.rst
Переместил установку из туториалов в `Introduction` по твоему совету, вполне разумно.

А сами туториалы вообще убрал, чтобы не путало, теперь будут просто `Examples and notebooks`, норм?

[Собранная документация](https://fedot.readthedocs.io/en/735-improving-fedot-documentation/)

2022-08-11 15:02 UTC, gkirgizov commented on docs/source/faq/index.rst
> +   others
Abstract вроде ок и пояснее, как если бы это abstract в научной статье.
Насчет API Usage я тоже не против, достаточно очевидно. Вот только текущий вопрос-ответ насчет why feature_name is not supported будто по смыслу не вписывается. Но, наверное, это уже вопрсо к PR с наполнением и не структурой

2022-08-12 09:42 UTC, merged