Fix boosting mutations
nccr-itmo/FEDOT pull request #806
Opened 2022-08-04 10:17 UTC by valer1435

Fix for issue https://github.com/nccr-itmo/FEDOT/issues/778. Checks on available operations in mutation were deleted.

2022-08-04 10:17 UTC, pep8speaks commented
Hello @valer1435! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`examples/simple/classification/api_classification.py`](https://github.com/nccr-itmo/FEDOT/blob/74b977a924307d802b1f71cf80d18e7e07142c3e/examples/simple/classification/api_classification.py):

> [Line 25:5](https://github.com/nccr-itmo/FEDOT/blob/74b977a924307d802b1f71cf80d18e7e07142c3e/examples/simple/classification/api_classification.py#L25): [E265](https://duckduckgo.com/?q=pep8%20E265) block comment should start with '# '

2022-08-04 11:38 UTC, YamLyubov commented on fedot/core/composer/gp_composer/specific_operators.py
>      node_final = SecondaryNode(choice(requirements.secondary),
Здесь по идее можно использовать PipelineOptNodeFactory из params, по аналогии с тем, как это сделано в мутациях внутри Mutation. Для создания остальных нод вроде как тоже можно ее использовать

2022-08-05 07:57 UTC, valer1435 commented on fedot/core/composer/gp_composer/specific_operators.py
>      node_final = SecondaryNode(choice(requirements.secondary),
+ к тому, что обсуждали вчера - бустинг мутации работают с пайплайнами, то есть сюда приходит ноды пайплайна, а не optNod'ы. Поэтому вариант не прокатит. Но что выглядит не очень - правда

2022-08-05 08:33 UTC, IIaKyJIuH requested changes

2022-08-05 08:33 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
> +                          ])
Попробуй шаблонизировать параметры, кажется, так будет проще читать:
```python
def _get_requirements_and_params_for_task(task: TaskTypesEnum):
    ops = get_operations_for_task(task)
    return PipelineComposerRequirements(primary=ops, secondary=ops, mutation_prob=1, max_depth=2),
           get_pipeline_generation_params(
               rules_for_constraint=DEFAULT_DAG_RULES,
               task=task
           )
```
А в местах использования просто распаковать

2022-08-05 08:33 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
>          _adapt_and_apply_mutations(new_graph=graph, num_mut=1)
Предлагаю здесь и на будущее задуматься о том, чтобы вообще не использовать бэкслеши, как минимум из-за [google-style гайда](https://google.github.io/styleguide/pyguide.html#:~:text=Do%20not%20use%20backslash%20line%20continuation%20except%20for%20with%20statements%20requiring%20three%20or%20more%20context%20managers.)

Мой вариант:
```python
Mutation(
    mutation_types=mutation_types,
    requirements=composer_requirements,
    graph_generation_params=graph_params
)._adapt_and_apply_mutations(new_graph=graph, num_mut=1)
```
Или так (вообще бы хорошо нам в проекте style-guide утвердить):
```python
Mutation(
    mutation_types=mutation_types,
    requirements=composer_requirements,
    graph_generation_params=graph_params)._adapt_and_apply_mutations(new_graph=graph, num_mut=1)
```

2022-08-08 12:58 UTC, valer1435 commented on test/unit/optimizer/test_gp_operators.py
> +                          ])
[Сделал](https://github.com/nccr-itmo/FEDOT/pull/806/commits/1e518a0354bf6fb27175859c67dc6ec8d1ba27c3#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R105)

2022-08-08 12:58 UTC, valer1435 commented on test/unit/optimizer/test_gp_operators.py
>          _adapt_and_apply_mutations(new_graph=graph, num_mut=1)
[Убрал все слеши в этом файле](https://github.com/nccr-itmo/FEDOT/pull/806/commits/1e518a0354bf6fb27175859c67dc6ec8d1ba27c3#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R247-R249)

2022-08-10 12:39 UTC, IIaKyJIuH commented on test/unit/optimizer/test_gp_operators.py
> +                          ])
Думаю, получение параметров смотрится лучше тоже в одной строчке:
```python
return (
    PipelineComposerRequirements(primary=ops, secondary=ops, mutation_prob=1, max_depth=2),
    get_pipeline_generation_params(rules_for_constraint=DEFAULT_DAG_RULES, task=Task(task))
)
```
Для максимальной линейности

2022-08-11 16:19 UTC, valer1435 commented on test/unit/optimizer/test_gp_operators.py
> +                          ])
[done](https://github.com/nccr-itmo/FEDOT/pull/806/commits/101dfcf1d99287ffbfe104c99b9d2925ead575c9#diff-775c48330642929cef79140a5ef51cd5f3da018eaad822b1e9fa1e7a72f59b27R107)

2022-08-12 10:00 UTC, IIaKyJIuH approved these changes

2022-08-12 13:01 UTC, YamLyubov approved these changes

2022-08-12 14:16 UTC, merged