Refactoring preprocessing
nccr-itmo/FEDOT pull request #816
Opened 2022-08-11 15:49 UTC by valer1435

Solving issue https://github.com/nccr-itmo/FEDOT/issues/812

The main changes:
1) Ohe-hot-encoding and simple_imputation are deleted from default model pool
2) Cleaning preprocessor become after fold evaluation
3) Due to (3) we need to fit pipeline to calculate intermediate metric

2022-08-11 15:52 UTC, nicl-nno commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
А str(input_data.features) - это не слишком memory-consuming? Если речь просто о том, чтобы определить закодированы даные или нет - то достаточно брать только N первых строк.

2022-08-11 15:53 UTC, nicl-nno commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            graph.unfit_preprocessor()
А почему unfit_preprocessor() нужно после кажого фолда делать?

2022-08-11 15:57 UTC, nicl-nno commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
Почему это нужно убрать? Ведь смысл в том, что пайплайн уже обучен и может пригодиться в ходе эволюции.

2022-08-11 15:59 UTC, nicl-nno commented
Общий вопрос - а сейчас PreprocessingBuilder ведь по прежнему будет добавить one_hot и прочее в начальные приближения. Или нет?

2022-08-12 08:05 UTC, valer1435 commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
Тут основная идея в том, что мы хотим различать разные наборы данных. В общем тут проблема была в том, что в разных фолдах могло быть разное кол-во категорий и без unfit'а препроцессора получалась каша. Различие данных по индексам - точно не очень вариант, потому что они у нас всегда от 0 до длинны фич. 

Я согласен, что это может быть вычислительно сложно, но пока не знаю, как сделать так, чтобы сто-процентно различать инпут дату из разных фолдов

2022-08-12 08:05 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            graph.unfit_preprocessor()
Объяснил выше

2022-08-12 08:07 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
Он обучен не на фолдах в кросс-валидации, а на разбиении трейна на отдельный трейн и тест. А такое разбиение мы нигде больше не используем и пайплайны будут просто висеть мертвым грузом в кеше. Но может @IIaKyJIuH ответит более подробно

2022-08-12 08:09 UTC, nicl-nno commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
А почему нельзя обучить препроцессор на первом фолде, а потом просто применять обученный для трансформции?

2022-08-12 08:11 UTC, nicl-nno commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
>разных фолдах могло быть разное кол-во категорий и без unfit'а препроцессора получалась каша

Может тогда делать его fit на полных данных?

2022-08-12 08:12 UTC, nicl-nno commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
Ну и даже если нужно так как сейчас - проще добавлять в data_id номер фолда.

2022-08-12 09:43 UTC, nicl-nno commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
Это может быть полезно в режиме без CV. Главное чтобы кэш умел их различать.

2022-08-12 10:07 UTC, IIaKyJIuH commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
> Различие данных по индексам - точно не очень вариант, потому что они у нас всегда от 0 до длинны фич

Я вспомнил, почему сделал `data_id` на индексах: когда дебажил, увидел, что во время разбиения данных по фолдам, индексация сохраняется от исходных данных, отчего она не всегда начиналась с 0

2022-08-12 13:45 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
В таком контексте, действительно, звучит логично, верну

2022-08-12 15:22 UTC, valer1435 commented
> Общий вопрос - а сейчас PreprocessingBuilder ведь по прежнему будет добавить one_hot и прочее в начальные приближения. Или нет?

Добавляеет. Удалю. В остальном - не знаю, имеет ли смысл удалять все упоминания об one-hot и imputation. Все таки скоро будем перерабатывать и вернемся к этому

2022-08-12 15:24 UTC, nicl-nno commented
Все упоминания безусловно нет, достаточно чтобы в эволюции такие операции не фигурировали.

2022-08-16 12:26 UTC, valer1435 commented on fedot/api/api_utils/assumptions/assumptions_handler.py
> -                pipelines_cache.save_pipeline(pipeline)
[Вернул](https://github.com/nccr-itmo/FEDOT/pull/816/commits/64ef5fc0d7d782a99be26c4a4793b4bcad0c14c1#diff-75527b537125cea20faf6fd9173d04b077e5aa8a7146cffdd6fa3effc124e77eR59-R65)

2022-08-16 12:26 UTC, valer1435 commented on fedot/core/caching/preprocessing_cache.py
> +        data_id = f'{hash(str(input_data.features))}'
[Теперь на fold_id](https://github.com/nccr-itmo/FEDOT/pull/816/commits/64ef5fc0d7d782a99be26c4a4793b4bcad0c14c1#diff-f119636507698e1500665ba8fdc41cc99f7f4957d8ba1e6f119dd57aea83c562R78)

2022-08-16 12:27 UTC, valer1435 commented
Переработал немного использование кэша. Удалось полностью его вынести из pipeline.

2022-08-16 12:53 UTC, IIaKyJIuH requested changes

2022-08-16 12:53 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
Может быть назвать лучше с префиксом `try_*`?
Чтобы показать, что это лишь при наличии оных

И по семантике хорошо бы тогда ещё переделать `.try_find_preprocessor`, чтобы он возвращал bool, который показывает, был ли загружен препроцессор или нет. Устанавливать encoder с imputer можно внутри самого метода загрузки, полагаю.

Наконец, можно собрать булы от обоих методов с префиксом `try_*` и вернуть их в этом методе, чтобы тоже семантично получилось. И не забыть отразить это в docstring.

2022-08-16 12:53 UTC, IIaKyJIuH commented on test/unit/preprocessing/test_pipeline_preprocessing.py
> +    print(multi_hyperparams)
1. Почему раньше тут не был нужен `.unfit`?
2. Наверное, принты стоит убрать

2022-08-16 13:08 UTC, nicl-nno approved these changes

2022-08-16 13:18 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
time_constraint? Если задается pipeline_max_fit_time, то обучение каждого пайплайна будет в новом потоке и мы можем оборвать обучение при истечении времени.

2022-08-16 13:22 UTC, valer1435 commented on test/unit/preprocessing/test_pipeline_preprocessing.py
> +    print(multi_hyperparams)
`.unfit` был в `pipeline.fit()` при отсутствии use_fitted. Теперь этот параметр не нужен. Тут получается из-за мутабельности словаря `single_hyperparams ` обнулялся, что не ок в данном тесте. А так все ок

2022-08-16 13:32 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
Не вижу смысла сейчас возвращать bool'ы, так как они нигде не будут использованы по идее

2022-08-16 14:11 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
[Заменил на try](https://github.com/nccr-itmo/FEDOT/pull/816/commits/85f36936dbbbdc59a700134543cfbee2498a4a71#diff-75527b537125cea20faf6fd9173d04b077e5aa8a7146cffdd6fa3effc124e77eR60)

2022-08-16 14:11 UTC, valer1435 commented on fedot/core/caching/preprocessing_cache.py
> +    fold_id = fold_id if fold_id else ""
[Проглядел](https://github.com/nccr-itmo/FEDOT/pull/816/commits/85f36936dbbbdc59a700134543cfbee2498a4a71#diff-f119636507698e1500665ba8fdc41cc99f7f4957d8ba1e6f119dd57aea83c562R65)

2022-08-16 14:11 UTC, valer1435 commented on test/unit/preprocessing/test_pipeline_preprocessing.py
> +    print(multi_hyperparams)
[Убрал ](https://github.com/nccr-itmo/FEDOT/pull/816/commits/85f36936dbbbdc59a700134543cfbee2498a4a71#diff-cf507c5a9b5b97c751f575f45d656219e86e0b79ff80da862b5508028bc9bacbR138-R144)принты

2022-08-17 08:06 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
можешь тогда переделать `.try_load_into_pipeline`, чтобы он НЕ возвращал bool'ы, получается, пока что правда в этом смысла нет

2022-08-17 08:17 UTC, IIaKyJIuH commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
Я про использование метода `.fit` у пайплайна.
В самом докстринге вроде имеется в виду, что считается метрика без фиттинга, или как?

2022-08-17 11:53 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
А, это в `get_intermediate_metric`.  Раньше было так, что после последнего фолда пайплайн не unfit'ился. И его можно было использовать как обученный граф. Но теперь это не так и надо заного фитить. Но в теории, если сюда прикрутить кэш - то все будет браться оттуда (так как операции там уже есть) и будет работать быстро

2022-08-17 13:17 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
Убрал[ bool](https://github.com/nccr-itmo/FEDOT/pull/816/commits/a217c6d2e43bbc0ebdf01b70d75455c5a647647b#diff-55acf5f6ff5192b9bc49d5b950a0e90503113b4cef042dfb6c871df8a9992d5dR73-R76)

2022-08-17 13:20 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
[Добавил ](https://github.com/nccr-itmo/FEDOT/pull/816/commits/a217c6d2e43bbc0ebdf01b70d75455c5a647647b#diff-b74209f31e96829d85a9081c7c984c03dc210033b10faed484b809278e33961bR104-R109)кэш в данный метод

2022-08-17 13:24 UTC, andreygetmanov requested changes

2022-08-17 13:24 UTC, andreygetmanov commented on examples/simple/regression/api_regression.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=5, logging_level=logging.INFO,
Не совсем понимаю. Если убираешь тюнинг, зачем увеличивать время?

2022-08-17 13:24 UTC, andreygetmanov commented on fedot/api/api_utils/assumptions/preprocessing_builder.py
> -            preprocessing_builder = preprocessing_builder.with_categorical()
Правильно понимаю, теперь весь препроцессинг будет происходить не через добавление нод, а через сценарии из preprocessing.py? Если так, не уменьшит ли это гибкость? При обучении через API с predefined model препроцессинг всё равно будет вызываться?

2022-08-17 13:24 UTC, andreygetmanov commented on fedot/core/caching/preprocessing_cache.py
> +        Tries to find preprocessor in DB table and oad it for pipeline
Очепятка. "...and load it..."

2022-08-17 13:24 UTC, andreygetmanov commented on test/unit/api/test_api_safety.py
> +    assert len(model.params.api_params['available_operations']) == 5
Очепятка: "there should be only..."
А в следующем тесте (test_api_fit_predict_with_pseudo_large_dataset_with_onehot_correct) ещё есть смысл, если ты ohe убираешь?

2022-08-17 13:27 UTC, valer1435 commented on examples/simple/regression/api_regression.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=5, logging_level=logging.INFO,
Были беды с композером. Нужно было дать ему больше времени, чтобы беды увидеть

2022-08-17 13:28 UTC, valer1435 commented on fedot/api/api_utils/assumptions/preprocessing_builder.py
> -            preprocessing_builder = preprocessing_builder.with_categorical()
Сейчас это так. Препроцессинг будет вызываться, так как он находится в `pipeline.fit()`

2022-08-17 13:29 UTC, valer1435 commented on test/unit/api/test_api_safety.py
> +    assert len(model.params.api_params['available_operations']) == 5
Имеет. One-hot подразумевается как препроцессинг

2022-08-17 14:09 UTC, valer1435 commented on fedot/core/caching/preprocessing_cache.py
> +        Tries to find preprocessor in DB table and oad it for pipeline
[done](https://github.com/nccr-itmo/FEDOT/pull/816/commits/8ca8237a7e5de39c077f86ac69ea363d53f8171c#diff-f119636507698e1500665ba8fdc41cc99f7f4957d8ba1e6f119dd57aea83c562R32)

2022-08-17 14:09 UTC, valer1435 commented on examples/simple/regression/api_regression.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=5, logging_level=logging.INFO,
[вернул](https://github.com/nccr-itmo/FEDOT/pull/816/commits/8ca8237a7e5de39c077f86ac69ea363d53f8171c#diff-3c412b965db4864b74aec2c776fabf1e32e66b8dd6addd52331a8df797fc0288R18)

2022-08-17 14:09 UTC, valer1435 commented on test/unit/api/test_api_safety.py
> +    assert len(model.params.api_params['available_operations']) == 5
[исправил](https://github.com/nccr-itmo/FEDOT/pull/816/commits/8ca8237a7e5de39c077f86ac69ea363d53f8171c#diff-a1dbd9bd27a41e0008c93d2193e8368752e1a83acf1bc0e4f9dc7d608e084e44R102)

2022-08-18 05:20 UTC, IIaKyJIuH commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
Обнови ещё docstring, пожалуйста)

2022-08-18 11:01 UTC, andreygetmanov commented on test/unit/api/test_api_safety.py
> +    assert len(model.params.api_params['available_operations']) == 5
> Имеет. One-hot подразумевается как препроцессинг

Тогда предлагаю чуть переработать его. Потому что в текущем варианте там добавляется именно ohe-узел
![image](https://user-images.githubusercontent.com/91334765/185379691-377d31d4-1cc1-4b31-9547-91d170805ae6.png)

2022-08-18 14:30 UTC, IIaKyJIuH commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
Понял, но обнови dosctring и комменты

2022-08-19 08:40 UTC, pep8speaks commented
Hello @valer1435! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:





























* In the file [`test/unit/api/test_api_safety.py`](https://github.com/nccr-itmo/FEDOT/blob/db80bae23c555b17671556df9a990afd6c7cc910/test/unit/api/test_api_safety.py):

> [Line 119:1](https://github.com/nccr-itmo/FEDOT/blob/db80bae23c555b17671556df9a990afd6c7cc910/test/unit/api/test_api_safety.py#L119): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-08-19 08:59 UTC, valer1435 commented on fedot/core/optimisers/objective/data_objective_eval.py
> +            )
[Докстринг](https://github.com/nccr-itmo/FEDOT/pull/816/commits/db80bae23c555b17671556df9a990afd6c7cc910#diff-b74209f31e96829d85a9081c7c984c03dc210033b10faed484b809278e33961bR102)

[Комменты](https://github.com/nccr-itmo/FEDOT/pull/816/commits/4c880d977f5f24783342b0256dca91474d992314#diff-b74209f31e96829d85a9081c7c984c03dc210033b10faed484b809278e33961bR103)

2022-08-19 08:59 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +    def fit_from_cache(self, cache: Optional[OperationsCache], preprocessing_cache: Optional[PreprocessingCache],
[Докстринг](https://github.com/nccr-itmo/FEDOT/pull/816/commits/db80bae23c555b17671556df9a990afd6c7cc910#diff-55acf5f6ff5192b9bc49d5b950a0e90503113b4cef042dfb6c871df8a9992d5dR67)

2022-08-19 09:02 UTC, andreygetmanov approved these changes

2022-08-19 11:03 UTC, IIaKyJIuH approved these changes

2022-08-19 12:36 UTC, merged