Refactor metric evaluation for tuner
nccr-itmo/FEDOT pull request #818
Opened 2022-08-12 09:47 UTC by YamLyubov

Tuner now uses PipelineObjectiveEvaluate to evaluate metric while hyperparameters optimization. 

- Tuner uses the same metric function as composer
- ```Pipeline.fine_tune_all_nodes``` is removed. To tune pipeline one can use ```PipelineTuner.tune```
- Functions ```calculate_loss_function```,  ```cv_tabular_predictions```, ```cv_time_series_predictions``` are replaces by PipelineObjectiveEvaluate and removed.
- HyperoptTuner does not use information about whether metric is minimized or maximized. It always minimizes the metric.

2022-08-12 09:47 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:









































* In the file [`fedot/core/pipelines/tuning/unified.py`](https://github.com/nccr-itmo/FEDOT/blob/740d7c1ee57bfce5b621721c4bef169e3a0c5dbe/fedot/core/pipelines/tuning/unified.py):

> [Line 118:1](https://github.com/nccr-itmo/FEDOT/blob/740d7c1ee57bfce5b621721c4bef169e3a0c5dbe/fedot/core/pipelines/tuning/unified.py#L118): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-08-12 10:02 UTC, nicl-nno commented on cases/river_levels_prediction/river_level_case_composer.py
> +            tuned_pipeline = pipeline_tuner.tune(obtained_pipeline, objective_evaluate)
Ручное применение тюнера - конечное не самая частая операция, но всё-таки хочется её делать менее громоздко. Может создать хотя бы спец. функцию для этого?

2022-08-12 10:02 UTC, nicl-nno commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective = Objective(MAE.get_value)
![image](https://user-images.githubusercontent.com/5711814/184332112-c20c93d1-2372-43af-b2ea-a629b925dbaf.png)

Смущает, что по факту целевая функция задается хоть и немного, но по разному. Для пользователя это явно очень неочевидно.

2022-08-12 10:11 UTC, gkirgizov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective = Objective(MAE.get_value)
Да ведь Objective может принимать MetricsTypeEnum

2022-08-12 11:21 UTC, gkirgizov requested changes
Может

2022-08-12 11:21 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                pipeline_gp_composed = tuner.tune(pipeline_gp_composed, objective_evaluate)
Может быть, имеет смысл перенести тюнинг в GPComposer, где уже есть все эти классы? И Objective, и DataSourceSplitter и ObjectiveEvaluate. А здесь, из api_composer просто вызывать композер

2022-08-12 11:21 UTC, gkirgizov commented on fedot/core/pipelines/tuning/tuner_interface.py
> -def _greater_is_better(loss_function) -> bool:
мы точно можем от этого избавиться? как насчет ROCAUC с одной стороны, которую мы максимизируем, и MAE которую минимизируем? можно вместо автоматического определения как-то иначе это решить, например, ввести метрикам булевый флаг

2022-08-12 12:41 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective = Objective(MAE.get_value)
Поменяю здесь, и правда можнотолько MAE передавать

2022-08-12 12:48 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective_evaluate = PipelineObjectiveEvaluate(objective, data_producer)
Думаю в коструктор можно это перенести

2022-08-12 12:50 UTC, valer1435 requested changes

2022-08-12 12:50 UTC, valer1435 commented on fedot/core/pipelines/tuning/unified.py
> +        super().__init__(task=task,
А task где-то используется?

2022-08-12 12:50 UTC, valer1435 commented on fedot/core/pipelines/tuning/unified.py
> +        :param objective_evaluate: PipelineObjectiveEvaluate to evaluate the pipeline
Сейчас получается два одинаковых метода objective у двух тюнеров. Думаю, пока можно перенести этот метод в базовый класс

2022-08-12 12:50 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +    if type(root_node.operation) is not Model and root_node.operation.operation_type != atomized_model_type():
Вставь TODO на всякий. Чтобы не забыть

2022-08-12 12:50 UTC, valer1435 commented on fedot/core/pipelines/verification_rules.py
> +    if type(root_node.operation) is not Model and root_node.operation.operation_type != atomized_model_type():
Что тут можно исправить это

2022-08-12 12:54 UTC, YamLyubov commented on test/unit/pipelines/test_pipeline_tuning.py
> +    return [RMSE.get_value]
Эти функции имеют разные аргументы: ```metric(reference: InputData, predicted: OutputData) -> float``` и ```def get_value(pipeline: 'Pipeline', reference_data: InputData, validation_blocks: int = None) -> float```, а Objective принимает либо MetricsEnum, либо ```Callable[[Graph], Real]```.
Можно просто RMSE оставить

2022-08-12 12:59 UTC, YamLyubov commented on examples/simple/pipeline_tune.py
> +        tuned_pipeline = pipeline_tuner.tune(input_data=train_data,
Это старый код остался, я его пропустила и не исправила

2022-08-12 12:59 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +                pipeline_gp_composed = tuner.tune(pipeline_gp_composed, objective_evaluate)
Не думаю, что это норм идея, так как насколько я понимаю, композер - это все, что связано с операторами изменения графа (мутации, кроссовер). Оптимизатор - тоже как бы отдельная сущность. А тюнер тут не очень сильно вяжется. Возможно стоит перенести Objective, и DataSourceSplitter и ObjectiveEvaluate в отдельный модуль, который будут использовать и эволюционный оптимизатор и тюнер

2022-08-12 13:08 UTC, YamLyubov commented on fedot/core/pipelines/tuning/sequential.py
> +    def tune(self, pipeline: Pipeline, objective_evaluate: PipelineObjectiveEvaluate) -> Pipeline:
Есть [тесты](https://github.com/nccr-itmo/FEDOT/blob/bf3997426ec7c4cc9927fd7bbcb3219cddb7ad8e/test/unit/pipelines/test_pipeline_tuning.py#L292) для него, они проходят

2022-08-12 13:23 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> -def _greater_is_better(loss_function) -> bool:
Это работает и для ROCAUC, потому что, когда мы вызываем get_value для метрик, которые максимизируются, они возвращаются с минусом. Можно сказать, что сейчас все метрики реализованы так, что они минимизируются. Поэтому можно от этого избавиться, так как ObjectiveEvaluate именно get_value и использует.

Может возникнуть проблема с кастомными метриками, если пользователь передаст метрику, которую надо максимизировать. Но тут я так понимаю и у композера в данном случае будт проблемы. Поэтому стоит до пользователя донести, что если он кастомную метрику передает, то она будет минимизироваться)

2022-08-12 13:24 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        self._default_metric_value = -MAX_METRIC_VALUE
Как я [тут ](https://github.com/nccr-itmo/FEDOT/pull/818#discussion_r944458448)написала, все етрики сейчас минимизируются

2022-08-12 13:26 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective_evaluate = PipelineObjectiveEvaluate(objective, data_producer)
Хотя сейчас уже как то многовато значений для инициализации. Надо подумать

2022-08-12 13:42 UTC, YamLyubov commented on fedot/core/pipelines/tuning/unified.py
> +        super().__init__(task=task,
Сейчас не используется.

2022-08-12 13:44 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            data_producer = DataSourceSplitter().build(train_input)
Сейчас практически вся логика и находится в методе api_composer ```tune_final_pipeline```

2022-08-12 14:02 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective = Objective(MAE.get_value)
Да, можно туже метрику передать

2022-08-17 10:13 UTC, YamLyubov commented on fedot/core/pipelines/tuning/unified.py
> +        :param objective_evaluate: PipelineObjectiveEvaluate to evaluate the pipeline
Эти методы у них все же отличаются, потому что в ```PipelineTuner``` оптимизируется pipeline, а в ```SequentialTuner``` node.

2022-08-19 12:24 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            tuned_pipeline = pipeline_tuner.tune(obtained_pipeline, objective_evaluate)
Реализовала [билдер](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-f88729a1a2af257a253338dbe6f29c429c4c0d635b8400b40b8b8a5d7b9890c1R16) для этого, теперь эти строчки выглядят [так](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-f6906db18a4fd897736c04874481a212263670af9322347e1edd0302f87a0bc7R123-R125)

2022-08-19 12:39 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective = Objective(MAE.get_value)
Теперь таже метрика[ передается](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-f6906db18a4fd897736c04874481a212263670af9322347e1edd0302f87a0bc7R123)

2022-08-19 12:39 UTC, YamLyubov commented on cases/river_levels_prediction/river_level_case_composer.py
> +            objective_evaluate = PipelineObjectiveEvaluate(objective, data_producer)
Реализовала [билдер](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-f88729a1a2af257a253338dbe6f29c429c4c0d635b8400b40b8b8a5d7b9890c1R16)

2022-08-19 12:39 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        self._default_metric_value = -MAX_METRIC_VALUE
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-b026e9a744008b37dcd5ff67275723f10ff5b8c76023486d82830ec1d69f63e9R14)

2022-08-19 12:39 UTC, YamLyubov commented on examples/advanced/time_series_forecasting/multi_ts_arctic_forecasting.py
> +    tuner = PipelineTuner(task=task, iterations=50,)
[Убрала](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-56e05b8c50a4b433b9e6f9e1899ab043f08119dc77e183622a0e80462129f1f4R84)

2022-08-19 12:39 UTC, YamLyubov commented on examples/simple/pipeline_tune.py
> +        tuned_pipeline = pipeline_tuner.tune(input_data=train_data,
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-b9ce8e9f2c86c72316c8760bc3c70c76cc4489fd08b9c9abeeefbc1e6001d46dR41-R44)

2022-08-19 12:39 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> +                pipeline_gp_composed = tuner.tune(pipeline_gp_composed, objective_evaluate)
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR266)

2022-08-19 12:39 UTC, YamLyubov commented on fedot/core/pipelines/tuning/unified.py
> +        super().__init__(task=task,
task [убрала](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-b026e9a744008b37dcd5ff67275723f10ff5b8c76023486d82830ec1d69f63e9R26)

2022-08-19 12:39 UTC, YamLyubov commented on fedot/core/pipelines/verification_rules.py
> +    if type(root_node.operation) is not Model and root_node.operation.operation_type != atomized_model_type():
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-626f6b72c51c57024482629cd3ec367c301efd52b2e8883b75c2c6ce394c74eaR41)

2022-08-19 12:55 UTC, nicl-nno approved these changes

2022-08-19 15:08 UTC, valer1435 requested changes

2022-08-19 15:08 UTC, valer1435 commented on test/unit/pipelines/tuning/test_pipeline_tuning.py
> +    file = os.path.join('../../../data', 'simple_regression_train.csv')
Лучше использовать `fedot_project_root()`

2022-08-25 11:53 UTC, gkirgizov commented on fedot/core/pipelines/tuning/tuner_interface.py
> -def _greater_is_better(loss_function) -> bool:
понял, тогда ок

2022-08-25 12:08 UTC, gkirgizov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if not metric_value:
для `metric_value = 0` будет неверно. лучше использовать `Fitness.is_valid`

2022-08-25 12:08 UTC, gkirgizov commented on test/unit/pipelines/test_pipeline_tuning.py
> +    return [RMSE.get_value]
тогда лучше просто RMSE

2022-08-25 12:18 UTC, gkirgizov requested changes

2022-08-25 12:18 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                    .with_timeout(datetime.timedelta(minutes=timeout_for_tuning)).build(train_data)
без переносов тяжеловато читается, лучше каждый метод на новой строке

2022-08-25 12:18 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +                    .with_timeout(datetime.timedelta(minutes=timeout_for_tuning)).build(train_data)
и можно тогда доп. переменных (`vb_number`, `folds`) не создавать. напрямую из reuirements передавая

2022-08-25 12:18 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
>              self.tune_final_pipeline(task, train_data,
предлагаю организовать эти строчки по аналогии со строками 208-213 для композирования. также внести метод `have_time_for_tuning` в `Timer` и тд

2022-09-05 12:49 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>              self.tune_final_pipeline(task, train_data,
Мне кажется, можно ввести  ```have_time_for_tuning``` в ```Timer```, но наоборот строчки с построением композера и вызов ```compose_pipeline``` вынести в отдельный метод, как это сделано для тюнера. Это позволит разбить сократить метод  ```compose_fedot_model```

2022-09-06 08:23 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
>              self.tune_final_pipeline(task, train_data,
можно и так, сделай как считаешь лучше

2022-09-06 09:58 UTC, YamLyubov commented on test/unit/pipelines/tuning/test_pipeline_tuning.py
> +    file = os.path.join('../../../data', 'simple_regression_train.csv')
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-5f8104208a5533d959f18716edd52962f38c0d097547376522b8e6c51605cd88R33)

2022-09-06 09:59 UTC, YamLyubov commented on fedot/core/pipelines/tuning/tuner_interface.py
> +        if not metric_value:
[Исправила](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-b026e9a744008b37dcd5ff67275723f10ff5b8c76023486d82830ec1d69f63e9R68-R70)

2022-09-06 10:03 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> +                    .with_timeout(datetime.timedelta(minutes=timeout_for_tuning)).build(train_data)
Переносы в в[ указанном месте](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR263-R269) и в аналогичных случаях добавила.

2022-09-06 10:04 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
> +                    .with_timeout(datetime.timedelta(minutes=timeout_for_tuning)).build(train_data)
В TunerBuuilder [добавила ](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-f88729a1a2af257a253338dbe6f29c429c4c0d635b8400b40b8b8a5d7b9890c1R34-R39)соответствующий метод

2022-09-06 10:07 UTC, YamLyubov commented on fedot/api/api_utils/api_composer.py
>              self.tune_final_pipeline(task, train_data,
Вынесла композирование в [отдельный метод](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-bb87dc34890bf92350ee4d87a2488b24ce8b9e9e41f43cc36c35d65254135c5fR219). В ApiTime добавила [```have_time_for_tuning```](https://github.com/nccr-itmo/FEDOT/pull/818/files#diff-cc7d8a57ff6077f9ea0a2f35f049483111dbf93c0753043d1c14f50b7b03af95R49)

2022-09-06 10:36 UTC, gkirgizov approved these changes

2022-09-06 10:36 UTC, gkirgizov commented on fedot/core/pipelines/tuning/unified.py
>                           n_jobs=n_jobs)
если ничего нового в конструкторе не добавляется, то можно не перегружать его

2022-09-06 10:36 UTC, gkirgizov commented
Еще пофикси pep8 замечания выше, их много

2022-09-08 10:17 UTC, valer1435 approved these changes

2022-09-08 10:17 UTC, valer1435 commented on examples/advanced/decompose/regression_refinement_example.py
>      run_river_experiment(file_path='../../../cases/data/river_levels/station_levels.csv',
Вроде не твои изменения, но лучше исправить тоже на root_folder

2022-09-08 14:02 UTC, merged