790 fix - Resample's dimensions error
nccr-itmo/FEDOT pull request #820
Opened 2022-08-12 13:42 UTC by aPovidlo

Solving one of problems from Issue #790. The bug was merging features and targets data. I don't know why, but after the updates release, target array became a 1-dim. Solution is to reshape it into 2-dim.

2022-08-12 13:42 UTC, pep8speaks commented
Hello @aPovidlo! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`temp.py`](https://github.com/nccr-itmo/FEDOT/blob/8282b689713d7ab408cf0266a01b90dc3b96c799/temp.py):

> [Line 34:1](https://github.com/nccr-itmo/FEDOT/blob/8282b689713d7ab408cf0266a01b90dc3b96c799/temp.py#L34): [W391](https://duckduckgo.com/?q=pep8%20W391) blank line at end of file

2022-08-12 13:42 UTC, aPovidlo commented
@nicl-nno Временный файл temp в конце удалю

2022-08-12 13:43 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        minority_data = np.hstack((features[min_idx], target[min_idx].reshape(-1, 1)))
А это можно покрыть unit-тестом на resample?

2022-08-12 13:44 UTC, nicl-nno commented on temp.py
> +import os
Не забудь убрать

2022-08-12 14:49 UTC, aPovidlo commented on temp.py
> +import os
Убрал

2022-08-12 18:33 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        minority_data = np.hstack((features[min_idx], target[min_idx].reshape(-1, 1)))
Понял, что reshape универсальное решение одновременно подходящие для представлений одномерных и двумерных масивов. Оно в любом случае переведет все в такое представление `[[1], [1], ... , [1]]`

2022-08-12 18:35 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        minority_data = np.hstack((features[min_idx], target[min_idx].reshape(-1, 1)))
Норм. Но тестов все равно лучше проверить оба варианта.

2022-08-12 18:36 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        minority_data = np.hstack((features[min_idx], target[min_idx].reshape(-1, 1)))
Да, этим сейчас и занят. В процессе)

2022-08-15 10:38 UTC, nicl-nno approved these changes

2022-08-15 13:20 UTC, IIaKyJIuH requested changes

2022-08-15 13:20 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_operations_implementations.py
> +        target = np.array([[0], [0], [0], [0], [1], [1], [1], [1], [1], [1]])
Проще сделать reshape от старого значения

2022-08-15 13:20 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert resample.transform(data_2dim, is_fit_pipeline_stage=True).predict.shape == (10, 2)
Уверен, что можно воспользоваться если не pytest.mark.parametrize, то хотя бы циклами для записи сходных по структуре логических кусков

2022-08-16 11:28 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +    def _return_source_data(self, input_data: Optional[InputData]) -> Optional[OutputData]:
@IIaKyJIuH @nicl-nno А разве такое может быть в операции?

2022-08-16 11:28 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +        target = np.array([[0], [0], [0], [0], [1], [1], [1], [1], [1], [1]])
@IIaKyJIuH Да, но я сделал именно так для наглядности, если будут читать код

2022-08-16 11:29 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert resample.transform(data_2dim, is_fit_pipeline_stage=True).predict.shape == (10, 2)
@IIaKyJIuH полезное замечание, не знал что так можно сделать. А есть уже реализованный пример использования в тестах?

2022-08-16 11:38 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_operations_implementations.py
> +        target = np.array([[0], [0], [0], [0], [1], [1], [1], [1], [1], [1]])
Думаешь, вообще никогда не придётся менять наборы значений в этом таргете?

2022-08-16 11:42 UTC, IIaKyJIuH commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert resample.transform(data_2dim, is_fit_pipeline_stage=True).predict.shape == (10, 2)
[Вот тут, например](https://github.com/nccr-itmo/FEDOT/blob/master/test/unit/optimizer/test_data_objective_eval.py#L67-L70)

2022-08-16 11:44 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +        target = np.array([[0], [0], [0], [0], [1], [1], [1], [1], [1], [1]])
Не знаю даже для каких операций можно еще применить данный датасет, кроме этой

2022-08-16 14:08 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +    def _return_source_data(self, input_data: Optional[InputData]) -> Optional[OutputData]:
Из всех операций только в этом скрипте у input_data стоит аннотация optional - наверное можно её убрать.

2022-08-17 11:58 UTC, YamLyubov approved these changes

2022-08-18 15:17 UTC, aPovidlo commented on test/unit/data_operations/test_data_operations_implementations.py
> +    assert resample.transform(data_2dim, is_fit_pipeline_stage=True).predict.shape == (10, 2)
@IIaKyJIuH поправил через pytest.mark.parametrize

2022-08-19 10:57 UTC, IIaKyJIuH approved these changes

2022-08-19 10:58 UTC, IIaKyJIuH approved these changes

2022-08-19 12:39 UTC, merged