enabled `logging_level` option
nccr-itmo/FEDOT pull request #835
Opened 2022-08-23 09:37 UTC by IIaKyJIuH

1. Fixed wrong `Log` initialization places
2. Changed adapter settings instantiation
3. Made singletons be used in multiprocessing
4. Added `show_progress` option to tuner
5. Minor fixes: caching, sortings, docstrings

2022-08-23 09:56 UTC, IIaKyJIuH commented
Стоит ли разделить `show_progress` для оптимизации и для тюнера?

2022-08-23 10:10 UTC, nicl-nno commented
На уровне API думаю нет.

2022-08-23 10:15 UTC, maypink requested changes

2022-08-23 10:15 UTC, maypink commented on fedot/core/utilities/singleton_meta.py
> +    def using_mp():
подскажи, пожалуйста, как ты тестируешь работоспособность логгера в мультипроцессорном режиме? я пытаюсь затестить таким скриптом в лоб и все равно выходит, что он пишет не все в файл
```
from multiprocessing import Pool

from fedot.core.log import default_log, Log

log = default_log(prefix='new_log')


def write_to_log(message: str):
    log.info(message)


if __name__ == '__main__':
    messages = [f'PRINT {i}' for i in range(100)]

    with Pool(5) as p:
        list(p.imap_unordered(write_to_log, messages))

    # check if every message was written to the log
    log_path = Log('random').log_file
    with open(log_path) as file:
        content = file.read()
        for mes in messages:
            if mes not in content:
                print(f"{mes} NOT IN CONTENT")

```

2022-08-23 10:48 UTC, IIaKyJIuH commented on fedot/core/log.py
> +def default_log(class_object=None, prefix: str = 'default', logging_level: Optional[int] = None,
По факту, устанавливается тот же инт, просто в теле функции и при первом объявлении объекта `Log`.

Я сделал так для того, чтобы обработать извлечение адаптера с нужным уровнем логгирования при условии, что `Log` уже был создан ранее.
Если же уровень не задан (None), то берётся уровень из созданного ранее `Log`.

2022-08-23 10:53 UTC, IIaKyJIuH commented on fedot/core/log.py
> +    return log.get_adapter(prefix=prefix, logging_level=log.logger.level if logging_level is None else logging_level)
Вот тут с этим сложно из-за того, что `Log` - синглтон и он не всегда хавает переменную.
Напиши, плз, как ты видишь решение, может я просто не понял.

2022-08-23 10:57 UTC, IIaKyJIuH commented on fedot/core/utilities/singleton_meta.py
> +    def using_mp():
Слушай, честно говоря, я не фиксил запись в файл в многопотоке.
Я пофиксил только cli выходные данные

Но вообще, можно и в этом PR что-то такое придумать для файлов

2022-08-23 10:58 UTC, IIaKyJIuH commented on fedot/core/utilities/singleton_meta.py
> +    def using_mp():
Как насчёт сделать [это](https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes)?

2022-08-23 11:34 UTC, maypink commented on fedot/core/utilities/singleton_meta.py
> +    def using_mp():
а, соре, подумала так из-за этого в описании к пр `Made singletons be used in multiprocessing`

а насчет решений из кук бука: я пыталась (долго и отчаянно) сделать такое в начале лета, но что-то у меня не вышло. но проблема во мне, а не в решении, так что может выйдет у тебя :)

2022-08-24 12:55 UTC, IIaKyJIuH commented on fedot/core/log.py
> +    return log.get_adapter(prefix=prefix, logging_level=log.logger.level if logging_level is None else logging_level)
[Теперь так](https://github.com/nccr-itmo/FEDOT/pull/835/commits/49580b9f30be4cc4f37dd8f25a6bb299a8d4b0fe)

2022-08-24 12:56 UTC, IIaKyJIuH commented on fedot/core/log.py
> +def default_log(class_object=None, prefix: str = 'default', logging_level: Optional[int] = None,
[Вернул как было](https://github.com/nccr-itmo/FEDOT/pull/835/commits/b9ca0af8b8b8e0a5c174cef9222d8334216a7197)

2022-08-29 07:48 UTC, IIaKyJIuH commented on fedot/core/utilities/singleton_meta.py
> +    def using_mp():
[Решил проблему](https://github.com/nccr-itmo/FEDOT/pull/835/commits/9a9aa20e17b8e8be8c1ab6f9f483353ce350027e)

[Файл для проверки](https://github.com/nccr-itmo/FEDOT/blob/c1ed26947cc13f71aacc8da869a95882e27e7f59/examples/mp_test.py)

2022-08-29 10:33 UTC, maypink approved these changes
супер-дупер-шмупер пулл реквест
![image](https://user-images.githubusercontent.com/57305249/187182243-80691457-0644-49b4-96e1-a1dea159abae.png)

2022-08-29 13:27 UTC, nicl-nno requested changes

2022-08-29 13:28 UTC, nicl-nno commented
По сути всё ок, но хочу уточнить пару вопросов:

1) Для joblib-based реализации многопоточный логгер тоже актуален? Но даже если нет, то функция полезная.
2) Обертывание вычисления фитнеса в контект логгера не влияет на производительность?
3) А существует способ проверить новое поведение логгера в unit-тесте?

2022-08-30 05:18 UTC, IIaKyJIuH commented on examples/mp_test.py
> +import logging
Нет, он просто ознакомительный для проверки работоспособности логгирования в многопотоке

2022-08-30 06:03 UTC, IIaKyJIuH commented
> По сути всё ок, но хочу уточнить пару вопросов:
> 
> 1. Для joblib-based реализации многопоточный логгер тоже актуален? Но даже если нет, то функция полезная.
> 2. Обертывание вычисления фитнеса в контект логгера не влияет на производительность?
> 3. А существует способ проверить новое поведение логгера в unit-тесте?

1 - актуален, причём как теоретически, так и практически (в том же `mp_test.py` если убрать синхронизацию, то всё будет шатко)
2 - Не проверял, но должно влиять, поскольку все логи передаются в очередь, а она синхронизируется между остальными процессами с помощью выделенного
3 - Пока что нет, но даже не знаю, как точно это проверить с учётом создания Listener'а процесса, а если использовать тот же подход из `mp_test.py`, то он даже при сломанной многопоточности может выдавать иногда, что всё ок

2022-08-30 06:49 UTC, nicl-nno commented
Попробуй тогда прикинуть, насколько значимо производительность страдает.
Можно просто в кол-ве пайплайнов измерить.

вт, 30 авг. 2022 г., 09:03 Pakulin Sergei ***@***.***>:

> По сути всё ок, но хочу уточнить пару вопросов:
>
>    1. Для joblib-based реализации многопоточный логгер тоже актуален? Но
>    даже если нет, то функция полезная.
>    2. Обертывание вычисления фитнеса в контект логгера не влияет на
>    производительность?
>    3. А существует способ проверить новое поведение логгера в unit-тесте?
>
> 1 - актуален, причём как теоретически, так и практически (в том же
> mp_test.py если убрать синхронизацию, то всё будет шатко)
> 2 - Не проверял, но должно влиять, поскольку все логи передаются в
> очередь, а она синхронизируется между остальными процессами с помощью
> выделенного
> 3 - Пока что нет, но даже не знаю, как точно это проверить с учётом
> создания Listener'а процесса, а если использовать тот же подход из
> mp_test.py, то он даже при сломанной многопоточности может выдавать
> иногда, что всё ок
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/nccr-itmo/FEDOT/pull/835#issuecomment-1231183768>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABLSPRTP7K465XWYRX277NDV3WP4LANCNFSM57KXWL3A>
> .
> You are receiving this because you commented.Message ID:
> ***@***.***>
>

2022-08-30 08:12 UTC, nicl-nno commented on examples/mp_test.py
> +import logging
кк

2022-08-30 11:38 UTC, IIaKyJIuH commented
Провёл небольшой тест на классификации, [используя этот пример](https://github.com/ITMO-NSS-team/fedot-performance-improvement-benchmark):
![image](https://user-images.githubusercontent.com/38308131/187426856-0bd15c90-9bfb-4060-b4db-0bdf26ec0f69.png)

![image](https://user-images.githubusercontent.com/38308131/187426869-dd9350e4-fb88-45c7-8403-9ffbc3f4a4c6.png)

Получается, без синхронизации логгера результат производительнее (в пайплайнах) до 25%

2022-08-30 13:44 UTC, nicl-nno commented
Тогда предлагаю синхронизацию логов по умолчанию отключить и снабдить комментом, что это очень влияет на перформанс кода внутри контекста.

2022-08-31 05:02 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        with context:
[Done](https://github.com/nccr-itmo/FEDOT/pull/835/commits/a921d9a58b2a110cc7e547ac41bf77a5e7abd02b)

2022-08-31 09:22 UTC, nicl-nno approved these changes

2022-09-01 16:10 UTC, gkirgizov requested changes

2022-09-01 16:10 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                        logs_queue: Optional[multiprocessing.Queue] = None) -> Optional[Individual]:
может можно без ненужной передачи logger_lvl обойтись? ведь он не меняется. думаю, можно как-то скрыть

2022-09-01 16:10 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                                 for ind in individuals)
предлагаю подумать, как скрыть этот одинаковый код за одной веткой. может быть, инкапсулировать этот if внутри какого-нибудь `with Log.get_what_i_need(sync_log)`

2022-09-01 16:10 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        with logger_context:
Подумал еще. С учетом того, что такая синхронизация вызывает замедление кода на болезненно ощутимое значение -- я настаиваю на отказе от такого решения. Как известно, лучшее решение синхронизации данных -- избежать синхронизации данных. Так что взамен предлагаю следующее более простое решение:
- логгеру знать про папку с логами
- каждому процессу создавать собственный лог в этой папке
- общий лог с использованием адаптеров все так же остается основным

Может быть, это и чуть менее удобно, чем читать единый лог, но все-таки сохранить более простое и единообразное (пусть лог будет всегда) решение мне кажется более разумным.

2022-09-02 05:30 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                        logs_queue: Optional[multiprocessing.Queue] = None) -> Optional[Individual]:
Не получится)

Логгер дочернего процесса не унаследует поля из оного в главном процессе, поэтому, собственно говоря, и возник PR.

Но вообще выглядит это действительно не очень.
До добавления параллельности joblib, когда использовался `multiprocessing.Pool`, такая ситуация решалась `initializer` функцией для дочерних процессов, но в жоблибе её нет))

2022-09-02 08:40 UTC, IIaKyJIuH commented
@pep8speaks suggest diff

2022-09-02 08:40 UTC, pep8speaks commented
Here you go with [the gist](https://gist.github.com/62ffd1e59bd65476c50cf5af8946fc78) !

> You can ask me to create a PR against this branch with those fixes. Simply comment `@pep8speaks pep8ify`.

 @IIaKyJIuH

2022-09-02 09:22 UTC, IIaKyJIuH commented
@pep8speaks suggest diff

2022-09-02 09:22 UTC, pep8speaks commented
Here you go with [the gist](https://gist.github.com/e21a883d520192046b4e12795252f368) !

> You can ask me to create a PR against this branch with those fixes. Simply comment `@pep8speaks pep8ify`.

 @IIaKyJIuH

2022-09-02 10:40 UTC, IIaKyJIuH commented
@pep8speaks suggest diff

2022-09-02 10:40 UTC, pep8speaks commented
Here you go with [the gist](https://gist.github.com/6107342bda18da04460f71c0c48455ed) !

> You can ask me to create a PR against this branch with those fixes. Simply comment `@pep8speaks pep8ify`.

 @IIaKyJIuH

2022-09-02 13:02 UTC, gkirgizov approved these changes

2022-09-02 13:02 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        logs_dir = pathlib.Path(Log().log_file).parent
может, скрыть эти два поля и логику с директорией за каким-то непрозрачным маленьким датаклассом? чтобы не светить деталями наружу. что-то вроде `self.logger.get_mp_logs_data`

2022-09-02 13:03 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +                        logs_queue: Optional[multiprocessing.Queue] = None) -> Optional[Individual]:
ага, понял

2022-09-02 13:36 UTC, IIaKyJIuH commented on fedot/core/optimisers/gp_comp/evaluation.py
> +        logs_dir = pathlib.Path(Log().log_file).parent
[Done](https://github.com/nccr-itmo/FEDOT/pull/835/commits/99850a7709ef665f1514384344e87d0ab658d583)

2022-09-07 10:05 UTC, nicl-nno approved these changes

2022-09-07 11:20 UTC, merged