Minor fixes to avoid annoying messages/warnings/etc
nccr-itmo/FEDOT pull request #836
Opened 2022-08-23 11:05 UTC by nicl-nno

- bosting mutation is disabled for classification and regression due to the errors
- Graph verification and images errors supressed
- Models fit messages supressed.
- LGBM parameters modified (not very succesfully)

2022-08-25 11:26 UTC, aPovidlo approved these changes

2022-08-25 13:36 UTC, gkirgizov requested changes

2022-08-25 13:36 UTC, gkirgizov commented on fedot/core/optimisers/objective/objective_eval.py
> +    def __call__(self, graph: G, n_jobs: int = -1) -> Fitness:
Я за то, чтобы сохранять простейший функциональный интерфейс у классов `Objective`, `ObjectiveEvaluate` , а все остальные параметры передавать в `__init__`

2022-08-25 13:36 UTC, gkirgizov commented on fedot/core/optimisers/objective/objective.py
> +    def __call__(self, graph: Graph, *args: Any, **kwargs: Any) -> Fitness:
зачем тут args если он не используется?

2022-08-25 13:36 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            self._post_eval_callback(adapted_graph, n_jobs)
Этот аргумент ломает абстракцию, тк не соотвествует сигнатуре ObjectiveFunction. В этот класс можно передавать любой Callable, который может принимать граф\пайплайн. Хотелось бы сохранить такой обобщенный интерфейс

2022-08-25 13:36 UTC, gkirgizov commented on fedot/utilities/logging.py
> +            sys.stdout = old_stdout
именно из-за этого возникал баг https://github.com/nccr-itmo/FEDOT/issues/765
в целом, это сомнительная штука, которая ломает любые вещи, работающие со стандартным выводом. pytest, tqdm, потенциально проблемы с logging.

может, что-то такое подойдет? https://datascience.stackexchange.com/questions/53954/how-to-make-lightgbm-to-suppress-output

2022-08-25 14:01 UTC, nicl-nno commented on fedot/core/optimisers/objective/objective_eval.py
> +    def __call__(self, graph: G, n_jobs: int = -1) -> Fitness:
Я так и хотел сделать, но проблема в том что передавать нужно вот тут:

![image](https://user-images.githubusercontent.com/5711814/186684931-5118b29a-773d-47fd-94e7-a68c9bd9709e.png)

где _objective_eval - это уже етод, а не экземпляр класса.

2022-08-25 14:28 UTC, valer1435 reviewed
Очень странная штука с прокидыванием n_jobs. пока не знаю, как сделать лучше, но подумаю

2022-08-25 14:28 UTC, valer1435 commented on fedot/api/api_utils/api_composer.py
> +        mutations = [parameter_change_mutation,
Поставить бы сюда TODO чтобы не забыть вернуть ее потом

2022-08-25 14:32 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +        for node in self.nodes:
Я так понимаю, что нужда прокидывания n_jobs в том, чтобы вырубать n_jobs у моделей при многопроцессорном режиме? Если да, то проще проверять, является ли процесс родительским или дочерним. Кажется __name__ == '__main__' как раз оно

2022-08-25 14:35 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        for node in self.nodes:
Основную проблему это решит, но хочется иметь возможность управлять числом jobs-ов на обоих уровнях - и популяции, и конкретного пайплайна.

2022-08-25 21:37 UTC, nicl-nno commented on fedot/core/optimisers/objective/objective_eval.py
> +    def __call__(self, graph: G, n_jobs: int = -1) -> Fitness:
По итогам обсуждения решили перенести в конструктор и инициализировать число "локальных" процессов в композере вручную.

2022-08-25 21:37 UTC, nicl-nno commented on fedot/core/optimisers/objective/objective.py
> +    def __call__(self, graph: Graph, *args: Any, **kwargs: Any) -> Fitness:
Убрал.

2022-08-25 21:37 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            self._post_eval_callback(adapted_graph, n_jobs)
E,hfk

2022-08-25 21:37 UTC, nicl-nno commented on fedot/utilities/logging.py
> +            sys.stdout = old_stdout
Раз вызывает проблемы - то убрал.

2022-08-25 21:37 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        mutations = [parameter_change_mutation,
Поставил.

2022-08-26 06:01 UTC, IIaKyJIuH requested changes

2022-08-26 09:49 UTC, gkirgizov approved these changes

2022-08-26 09:49 UTC, gkirgizov commented on fedot/core/pipelines/pipeline.py
> +        for node in self.nodes:
Соглашусь с Колей, лучше предусматривать возможность настройки, чем хардкодить какие-то решения

2022-08-26 10:00 UTC, nicl-nno commented on examples/simple/classification/image_classification_problem.py
> +    pass
Да, сделал.

2022-08-26 10:00 UTC, nicl-nno commented on examples/simple/classification/api_classification.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=timeout, n_jobs=4,
Нет. Поменял обратно, раз вызывает вопросы.

2022-08-26 10:00 UTC, nicl-nno commented on test/unit/optimizer/test_evaluation.py
> +def prepared_objective(pipeline: Pipeline, *args, **kwargs) -> Fitness:
Тоже убрал.

2022-08-26 10:00 UTC, nicl-nno commented on fedot/core/optimisers/objective/objective_eval.py
> +    def __call__(self, graph: G,) -> Fitness:
Ага, убрал.

2022-08-29 05:19 UTC, IIaKyJIuH approved these changes

2022-08-29 05:19 UTC, IIaKyJIuH commented on examples/advanced/fedot_profiler_example.py
> +    print(path)
Принт остаётся?

2022-08-29 09:12 UTC, valer1435 approved these changes
Я правильно понимаю, что сейчас у нас как бы 2 разных n_jobs? Первый отвечает за распараллеливание на уровне популяции, а второй - на уровне пайплайна? 

Если да, то думаю стоит их назвать по-разному

2022-08-30 14:19 UTC, nicl-nno commented
>Если да, то думаю стоит их назвать по-разному

Поменял на eval_n_jobs

2022-08-30 15:20 UTC, merged