Refactor visualizations
nccr-itmo/FEDOT pull request #841
Opened 2022-08-24 02:07 UTC by MorrisNein

History visualizations are now at the separate classes. Now they are much more convenient to use, as `history.show.` allows context search for available visualizations, and the selected visualization is available with its signature and doc string.

There is a challenge yet, to make the visualizations aware of appropriate values of input arguments.

2022-08-24 02:07 UTC, pep8speaks commented
Hello @MorrisNein! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



























* In the file [`fedot/core/visualisation/opt_history/utils.py`](https://github.com/nccr-itmo/FEDOT/blob/8afbd1dbfecbccea0d80439a15344472261a7f96/fedot/core/visualisation/opt_history/utils.py):

> [Line 121:17](https://github.com/nccr-itmo/FEDOT/blob/8afbd1dbfecbccea0d80439a15344472261a7f96/fedot/core/visualisation/opt_history/utils.py#L121): [E131](https://duckduckgo.com/?q=pep8%20E131) continuation line unaligned for hanging indent

2022-08-24 06:48 UTC, nicl-nno commented
>THIS PR CURRENTLY CONTAINS ALL COMMITS FROM THE PR https://github.com/nccr-itmo/FEDOT/pull/830, DO NOT REVIEW CHANGES NOT INCLUDED IN THE FOLLOWING SCREENSHOT

Можно делать PR не в мастер, а в твою ветку из 830 - тогда и изменения будут только нужные.

2022-08-24 11:45 UTC, IIaKyJIuH requested changes

2022-08-24 11:45 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_history/operations_kde.py
> +            history independently.
Было бы лучше без таких частых переносов строки

2022-08-24 11:45 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_history/utils.py
> +        formatted_text = '$\\' + latex_format_tag + '{' + text_to_wrap + '}$'
f-string?

2022-08-24 11:45 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_viz.py
> +        visualize_function = plot_type.value(self.history).visualize
Может быть не создавать новую функцию, а доставать из полей класса? Что-то типа:
```python
if isinstance(plot_type, str):
    try:
        visualize_function = vars(self)[plot_type]
    except KeyError:
        raise NotImplementedError(
            f'Visualization "{plot_type}" is not supported. Expected values: '
            f'{", ".join(PlotTypesEnum.member_names())}.')
else:
    visualize_function = vars(self)[plot_type.name]
```

2022-08-24 12:09 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/operations_kde.py
> +            history independently.
Недвано обратил внимание на PEP, что допустимая ширина докстрингов и длинных комментариев не 80, а 72 символа. Мб я и переборщил с переносами)

2022-08-24 12:11 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/fitness_line.py
> +            mpl.use(default_mpl_backend)
Из-за того, что мы получили его прямо перед try, мы возвращаем на самом деле не совсем дефолтный бэкенд, а именно тот, что был до. С этой точки зрения да, норм

2022-08-24 12:57 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +        visualize_function = plot_type.value(self.history).visualize
Да, действительно [удобно](https://github.com/nccr-itmo/FEDOT/pull/841/commits/1d2c696c58ea8c517ee5f456667e658253b80fa2). Только вот не уверен насчёт подводных камней у такого решения. Впрочем, всему своё время)

2022-08-24 12:58 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/fitness_box.py
> +        :param dpi: DPI if the output figure.
[Тут поправил](https://github.com/nccr-itmo/FEDOT/pull/841/commits/2499a85170c2132f903f43f664c1a20b6b0a0384)

2022-08-24 12:59 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/utils.py
> +        formatted_text = '$\\' + latex_format_tag + '{' + text_to_wrap + '}$'
[Тут поправил](https://github.com/nccr-itmo/FEDOT/pull/841/commits/2499a85170c2132f903f43f664c1a20b6b0a0384)

Раньше не знал, что нужно двойными скобками экранировать, так бы сразу сделал)

2022-08-24 13:00 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz.py
> +        visualize_function = plot_type.value(self.history).visualize
И получается, что значения перечисления как классы визуализаций больше не используются. Пока у нас есть однозначность "вариант визуализации-класс", предполагаю так и оставить.

2022-08-25 09:44 UTC, IIaKyJIuH commented on fedot/core/visualisation/opt_history/operations_kde.py
> +            history independently.
Ну вот хззз, может текст лучше тогда переделать, выглядит просто крипово

2022-08-25 09:48 UTC, IIaKyJIuH approved these changes

2022-08-25 11:43 UTC, gkirgizov approved these changes
Я сильно не вникал в логику визуализаций. По организации кода все хорошо, чекеры для аргументов полезны и удобны, реализованы тоже хорошо.

Только пару комментариев поправить.

2022-08-25 11:43 UTC, gkirgizov commented on fedot/core/visualisation/opt_history/fitness_line.py
> +            default_log('Requirements').warning(e)
эта строчка упадет, нужно `default_log(prefix=...)`

2022-08-25 11:43 UTC, gkirgizov commented on fedot/core/visualisation/opt_history/history_visualization.py
> +    def visualize(self):
добавить бы тогда `*args, **kwargs`

2022-08-25 11:43 UTC, gkirgizov commented on fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
> +    def wrap_constraints(constraint_checkers: List[Callable[[HistoryVisualization, Dict[str, Any]], Dict[str, Any]]]):
предлагаю ввести type alias для чекеров

2022-08-25 12:14 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/operations_kde.py
> +            history independently.
Я раза с 10 заметил, что действительно натыкал лишних переносов. Действительно поправлю, спасибо

2022-08-25 14:26 UTC, ChrisLisbon approved these changes

2022-08-25 14:26 UTC, ChrisLisbon commented on fedot/core/visualisation/opt_viz_extra.py
> +class OptHistoryExtraVisualizer:
Можно попросить описание класса для очевидности отличия от OptHistoryVisualizer'а

2022-08-25 16:22 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/history_visualization.py
> +    def visualize(self):
Готово, потребовало небольшого [фикса](https://github.com/nccr-itmo/FEDOT/pull/841/commits/1baba8d6f010a7a2fa5aba81606dba659db75a7f)

2022-08-25 16:25 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/arg_constraint_wrapper.py
> +    def wrap_constraints(constraint_checkers: List[Callable[[HistoryVisualization, Dict[str, Any]], Dict[str, Any]]]):
[Согласен](https://github.com/nccr-itmo/FEDOT/pull/841/commits/f2955d3aff4178c192a3683a65210c35a796185f)

2022-08-25 16:28 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/fitness_line.py
> +            default_log('Requirements').warning(e)
[Пофикшено](https://github.com/nccr-itmo/FEDOT/pull/841/commits/f75bb5e42cfd6184c408d05ebe4e336d091d4726)

2022-08-25 16:29 UTC, MorrisNein commented on fedot/core/visualisation/opt_history/operations_kde.py
> +            history independently.
[Так](https://github.com/nccr-itmo/FEDOT/pull/841/commits/4fd64d08c401ac70e4f02f9ca851f054f4ac7617) хорошо?

2022-08-25 16:55 UTC, MorrisNein commented on fedot/core/visualisation/opt_viz_extra.py
> +class OptHistoryExtraVisualizer:
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/841/commits/88fbf00a24b7ca7ed52ff318344c6a8b906fc5a3)  описание к обоим классам

2022-08-25 17:20 UTC, merged