Refactor logging
nccr-itmo/FEDOT pull request #842
Opened 2022-08-24 15:07 UTC by maypink

2022-08-25 11:13 UTC, IIaKyJIuH requested changes

2022-08-25 11:13 UTC, IIaKyJIuH commented on fedot/core/log.py
>      log = Log(logger_name='default',
можно тогда `logger_name` тоже убрать, т.к. теперь всегда по умолчанию `'default'`

2022-08-25 13:40 UTC, gkirgizov approved these changes
Все гуд, небольшое предложение

2022-08-25 13:40 UTC, gkirgizov commented on fedot/core/log.py
>      if class_object:
может быть, автоматически определять, класс это или строка-префикс? удобнее будет инициализировать, а то может забываться, что нужно писать `prefix=...`

2022-08-25 20:35 UTC, maypink commented on fedot/core/log.py
>      if class_object:
[done](https://github.com/nccr-itmo/FEDOT/pull/842/commits/0a98d15277483fb5943840b60334dee4d6c04c7e#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR138)

2022-08-25 20:36 UTC, maypink commented on fedot/core/log.py
>      log = Log(logger_name='default',
[done](https://github.com/nccr-itmo/FEDOT/pull/842/commits/0a98d15277483fb5943840b60334dee4d6c04c7e#diff-702f1068708455144cc2ae7bceb96da8e1de4b0688343b793e3da2b806988ccfR138)

2022-08-26 05:48 UTC, IIaKyJIuH approved these changes

2022-08-26 06:07 UTC, IIaKyJIuH commented on fedot/core/log.py
>      if class_object:
Лучше вообще оставить только один параметр тогда - `prefix`, пусть он и парсится внутри.

2022-08-26 09:29 UTC, merged