Embedding joblib
nccr-itmo/FEDOT pull request #843
Opened 2022-08-25 09:30 UTC by valer1435

Due to some problems with memory and performance https://github.com/nccr-itmo/FEDOT/issues/840. Multiprocessing was refactored using joblib library

2022-08-25 09:39 UTC, gkirgizov requested changes
Запускал ли, сравнивал ли с multiprocessing? Эффективнее ли по памяти?

2022-08-25 09:39 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            if _:
что это и зачем? 
во-первых, можно сделать `if any(graph is None for graph in restored_graphs)`
во-вторых, почему эта обработка появилась здесь, связана ли она с restore или с чем-то другим

2022-08-25 09:39 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            if _:
в-тетьих, так ли нужно кидать исключение? методы этого класса в случае ошибок возращают None, но не падают. есть ли веская причина для исключения?

2022-08-25 09:39 UTC, gkirgizov commented on fedot/core/optimisers/gp_comp/evaluation.py
> +from joblib import Parallel, delayed
может выше убрать вообще импорт и использования multiprocessing

2022-08-25 09:46 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            if _:
Лишнее. Забыл убрать

2022-08-25 10:45 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluation.py
> +from joblib import Parallel, delayed
[done](https://github.com/nccr-itmo/FEDOT/pull/843/commits/ef26e7caf42a41e7c406b9265c1c487ecc749157#diff-572c188f30cc6e7ff1d743abaed320afcf664b681a645764e2e730281b11c0b9R3-R5)

2022-08-25 10:45 UTC, valer1435 commented on fedot/core/optimisers/gp_comp/evaluation.py
> +            if _:
[убрал](https://github.com/nccr-itmo/FEDOT/pull/843/commits/ef26e7caf42a41e7c406b9265c1c487ecc749157#diff-572c188f30cc6e7ff1d743abaed320afcf664b681a645764e2e730281b11c0b9R3-R5)

2022-08-25 10:47 UTC, valer1435 commented
> Запускал ли, сравнивал ли с multiprocessing? Эффективнее ли по памяти?

Тестов не проводил. Хорошо то, что перестал падать у меня пример api_classification. До этого у меня ноут с 16 гб оперативы просто вылетал

2022-08-25 13:52 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/186683275-6a344ac4-e028-4008-ba64-1250a8eb4ce4.png)

А вот этот вывод можно сделать опциальным?

2022-08-25 14:08 UTC, valer1435 commented
> ![image](https://user-images.githubusercontent.com/5711814/186683275-6a344ac4-e028-4008-ba64-1250a8eb4ce4.png)
> 
> А вот этот вывод можно сделать опциальным?

Можно его вообще убрать. Но я так понимаю, скоро будет обновление логгинга и выставление отдельного уровня логирования для композирования(?)

2022-08-25 14:11 UTC, nicl-nno commented on fedot/core/optimisers/gp_comp/evaluation.py
> +from joblib import Parallel, delayed
Но импорт multiprocessing вроде остался. Или он нужен?

2022-08-25 15:32 UTC, nicl-nno approved these changes

2022-08-26 09:37 UTC, gkirgizov approved these changes

2022-08-29 08:48 UTC, merged