Remove lgbm logs
nccr-itmo/FEDOT pull request #847
Opened 2022-08-29 10:02 UTC by valer1435

Resolve https://github.com/nccr-itmo/FEDOT/issues/844 issue (set silent=True by default)

2022-08-29 10:18 UTC, IIaKyJIuH requested changes

2022-08-29 10:18 UTC, IIaKyJIuH commented on fedot/core/repository/data/default_operation_params.json
> +    "silent": true
Это временное решение с добавлением ключей `"silent": True`? Если так, TODO бы оставить

2022-08-29 10:28 UTC, valer1435 commented on fedot/core/repository/data/default_operation_params.json
> +    "silent": true
Насколько я понимаю, в процессе поиска решения федот может подставить параметры, не совместимые друг с другом. И LGBM об этом предупреждает. Исправить это в общем случае не выйдет, так как, поиск параметров идет по сетке и мы не можем покрыть все наборы параметров if'ами

2022-08-29 10:45 UTC, IIaKyJIuH commented on fedot/core/repository/data/default_operation_params.json
> +    "silent": true
Точно ли нельзя решить по-другому?

Переживаю за ситуации, когда что что-то сломалось, но из-за отсутствия логов починить это не удаётся

2022-08-29 10:55 UTC, IIaKyJIuH commented on fedot/core/repository/data/default_operation_params.json
> +    "silent": true
Судя по документации, этот ключ всегда `true`

2022-08-30 09:22 UTC, valer1435 commented on fedot/core/repository/data/default_operation_params.json
> +    "silent": true
[Убрал ](https://github.com/nccr-itmo/FEDOT/pull/847/commits/dd955d70c06569a98e4089016cfa4c567e7efa4e#diff-91ad48086825d5c8033a7eb8326fdb40eba8d096c4b4043d10a02bf5a7070097R25-R37)эти параметры, раз они не работают

2022-08-30 09:37 UTC, valer1435 commented
Теперь логов с lgbm должно стать меньше. num_threads и l1_lambda не должны появляться больше

2022-08-30 11:39 UTC, IIaKyJIuH approved these changes

2022-08-30 11:54 UTC, merged