Incorrect binary preprocessing
nccr-itmo/FEDOT pull request #849
Opened 2022-08-29 12:51 UTC by maypink

in progress

2022-08-30 13:11 UTC, gkirgizov commented
Может быть, эту схему добавить в документацию?

2022-08-30 13:30 UTC, gkirgizov requested changes

2022-08-30 13:30 UTC, gkirgizov commented on fedot/preprocessing/data_types.py
> +                elif failed_ratio >= 0.65 \
предлагаю проименовать и вынести все важные константы в `__init__`

2022-08-30 13:30 UTC, gkirgizov commented on fedot/preprocessing/preprocessing.py
> +        # TODO: fix supplementary data column types after simple imputer
А что за проблема тут подразумевается?

2022-08-30 13:30 UTC, gkirgizov commented on test/unit/preprocessing/test_pipeline_preprocessing.py
> +    assert coefficients.shape[1] == 12
нужно убрать или поправить 17 в комменте

2022-08-31 10:11 UTC, maypink commented on fedot/preprocessing/data_types.py
> +                elif failed_ratio >= 0.65 \
[done](https://github.com/nccr-itmo/FEDOT/pull/849/commits/f27e63a3a1b22229c5ac1565f625fa1ffb9be371#diff-57f1c1458ebb0217744c5492c18bf70f808bfb10c8eec90b4947419ba3c5b2bbR31)

2022-08-31 10:12 UTC, maypink commented on fedot/preprocessing/preprocessing.py
> +        # TODO: fix supplementary data column types after simple imputer
в процессе написала это для себя и забыла убрать, все норм

2022-08-31 10:12 UTC, maypink commented on test/unit/preprocessing/test_pipeline_preprocessing.py
> +    assert coefficients.shape[1] == 12
[done](https://github.com/nccr-itmo/FEDOT/pull/849/commits/f27e63a3a1b22229c5ac1565f625fa1ffb9be371#diff-cf507c5a9b5b97c751f575f45d656219e86e0b79ff80da862b5508028bc9bacbR184)

2022-08-31 10:36 UTC, gkirgizov approved these changes

2022-09-06 19:19 UTC, pep8speaks commented
Hello @maypink! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

* In the file [`fedot/api/main.py`](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/api/main.py):

> [Line 313:30](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/api/main.py#L313): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders



* In the file [`fedot/preprocessing/data_types.py`](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py):

> [Line 58:42](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L58): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 88:46](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L88): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 203:66](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L203): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 235:13](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L235): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable '_' is assigned to but never used
> [Line 299:71](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L299): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 328:75](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L328): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 346:67](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L346): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'
> [Line 387:71](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/fedot/preprocessing/data_types.py#L387): [F821](https://duckduckgo.com/?q=pep8%20F821) undefined name 'InputData'

* In the file [`test/unit/pipelines/test_decompose_pipelines.py`](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/pipelines/test_decompose_pipelines.py):

> [Line 189:5](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/pipelines/test_decompose_pipelines.py#L189): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'predicted_output' is assigned to but never used
> [Line 206:5](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/pipelines/test_decompose_pipelines.py#L206): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'predicted_output' is assigned to but never used
> [Line 223:5](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/pipelines/test_decompose_pipelines.py#L223): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'predicted_output' is assigned to but never used



* In the file [`test/unit/preprocessing/test_preprocessors.py`](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/preprocessing/test_preprocessors.py):

> [Line 254:5](https://github.com/nccr-itmo/FEDOT/blob/07631a2e1a9803283d79910fa0dd49a438a6bcf4/test/unit/preprocessing/test_preprocessors.py#L254): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable '_' is assigned to but never used

2022-09-12 14:13 UTC, andreygetmanov requested changes

2022-09-12 14:13 UTC, andreygetmanov commented on fedot/preprocessing/data_types.py
> +                log.warning(warning)
1. Если у тебя в колонке 1000 чисел с запятой вместо точки, в логе будет 1000 записей об этом. Это будет неудобно, поэтому лучше делать одну запись
2. Если где-то дальше нет автоматического преобразования запятой в точку, лучше его сделать, мы же зе бест автомл ин зе ворлд

2022-09-12 20:25 UTC, andreygetmanov approved these changes

2022-09-13 15:49 UTC, merged