Strict exceptions processing in tests
nccr-itmo/FEDOT pull request #856
Opened 2022-09-01 10:17 UTC by nicl-nno

Now some errors are not supressed in test mode

2022-09-03 12:12 UTC, valer1435 commented
Думаю не стоит так жестко вставлять такие ошибки в тесты. Например проблемы с num_features не зависят от входных данных и модели. Проблема в том, что несовместимые данные отправились в модель. То есть проблема на уровень выше и ее не починить какими-то внутренними исправлениями имплементаций или данных. Но сохранять стоит.

2022-09-03 13:40 UTC, nicl-nno commented
>Думаю не стоит так жестко вставлять такие ошибки в тесты

В идеале после фикса каждой ошибка для нее должне возникать свой конкретный тест и тогда да, существующий будет уже не нужен.

>Проблема в том, что несовместимые данные отправились в модель

Т.е. прямо input_data всего пайплайна проблемные? Странно, брал их напрямую из CV.

2022-09-03 15:31 UTC, valer1435 commented
Не знаю из-за чего сейчас возникает эта ошибка, но раньше проблема была в том, что операция бралась из кеша для данных из другого фолда и соответсвенно может такое быть, что в разных фолдах ohe-hot раздует данные до разной "ширины". Сделав operation.unfit, мы бы запросто заново зафитились бы. И при таком подходе мы никак не можем исправить этот баг, так как нам нужно решать проблемы с на уровне кэша, а не операций, с ними все ок.

Но возможно я не так понял идею

2022-09-03 17:48 UTC, nicl-nno commented
>Сделав operation.unfit, мы бы запросто заново зафитились бы

Ок, в этом случае действительно так. Не заметил что fit больше не обучает с нуля.

Посмотри тогда плз что может быть не так сочетанием кэша и CV (и можно ли это покрыть каким-то тестом).

2022-09-05 17:09 UTC, pep8speaks commented
Hello @nicl-nno! Thanks for updating this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:

















* In the file [`fedot/core/pipelines/pipeline.py`](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/pipeline.py):

> [Line 74:32](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/pipeline.py#L74): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders
> [Line 96:21](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/pipeline.py#L96): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent
> [Line 337:21](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/pipeline.py#L337): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 338:21](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/pipeline.py#L338): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

* In the file [`fedot/core/pipelines/template.py`](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/template.py):

> [Line 220:28](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/template.py#L220): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders
> [Line 316:27](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/template.py#L316): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders
> [Line 368:5](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/template.py#L368): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'e' is assigned to but never used
> [Line 369:19](https://github.com/nccr-itmo/FEDOT/blob/bd00cb0325cc2df3511b7d4a8502fc7887915181/fedot/core/pipelines/template.py#L369): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders

2022-09-06 12:34 UTC, valer1435 requested changes
У нас есть параметр seed в main api. Не стоит ли их как-то объединить или стоит различать?

2022-09-06 12:34 UTC, valer1435 commented on examples/simple/classification/api_classification.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=timeout, n_jobs=-1, preset='best_quality',
Available_operations думаю можно убрать, чтобы не пугать юзеров. max_fit_pipeline_time можно поставить побольше (мб 5 минут), так как датасет жирненький достаточно

2022-09-06 12:34 UTC, valer1435 commented on fedot/core/pipelines/pipeline.py
> +        pass
Комментарии

2022-09-06 12:34 UTC, valer1435 commented on fedot/core/utilities/random.py
> +        np.random.seed(self._seed)
Не знаю, считается ли что-то с помошью питоновского random'a. Но думаю стоит еще указывать и его

2022-09-06 14:28 UTC, nicl-nno commented on examples/simple/classification/api_classification.py
> +    auto_model = Fedot(problem=problem, seed=42, timeout=timeout, n_jobs=-1, preset='best_quality',
Убрал, поставил 5 минут.

2022-09-06 14:28 UTC, nicl-nno commented on fedot/core/pipelines/pipeline.py
> +        pass
Убрал вообще этот метод.

2022-09-06 14:28 UTC, nicl-nno commented on fedot/core/utilities/random.py
> +        np.random.seed(self._seed)
Добавил оба рандома

2022-09-06 14:29 UTC, nicl-nno commented
>У нас есть параметр seed в main api

Да, но не придумал как его изящно пробрасывать. Думал добавлять в гиперпараметры, но там свои нюансы возникают. Поэтому сделал [так](https://github.com/nccr-itmo/FEDOT/blob/77947a35088c3fbb287441a631ebcb5062ec8d2a/fedot/api/api_utils/params.py#L98).

2022-09-08 10:08 UTC, valer1435 approved these changes

2022-09-08 10:18 UTC, merged