790 fix - Resample replace fix and operation refactoring
nccr-itmo/FEDOT pull request #861
Opened 2022-09-03 19:29 UTC by aPovidlo

Solving another problem with resample operation from Issue https://github.com/nccr-itmo/FEDOT/issues/790. 
Bug was in replace parameter. In case of expanding strategy it causes difficulties and needed to change replace param to True. It is required to avoid error in sklearn method, which cannot create data if replace is False. Solution is to check this parameter and dynamically change it in process when it is required.

2022-09-03 21:11 UTC, nicl-nno commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +
Строка лишняя.

2022-09-03 21:12 UTC, nicl-nno approved these changes
Выглядит здорово! Поправь только pep8-проблемы сразу.

2022-09-05 16:04 UTC, nicl-nno approved these changes

2022-09-06 13:48 UTC, andreygetmanov requested changes

2022-09-06 13:48 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        If None numbers of samples will be equal to the shape of opposite selected transformed class.
Имхо, для читаемости лучше описания параметров отделять отступами, чтобы все строчки описания были строго друг под другом

2022-09-06 13:48 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        """
Думаю, кавычки можно переместить на строку выше

2022-09-06 13:48 UTC, andreygetmanov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +    Args:
А чем здесь и далее обусловлен такой стиль докстринга? В целом не вижу разницы между :param и Args:, но в коде в основном первый вариант видел. Не уверен, что новый стиль без проблем поведёт себя при автосборке документации

2022-09-06 13:52 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        """
@andreygetmanov это было сделано в соответствии с новым форматом докстрингов

2022-09-06 13:52 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +    Args:
@andreygetmanov как раз таки замена и нужна для новой автосборки

2022-09-06 13:53 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +    Args:
@andreygetmanov https://github.com/nccr-itmo/FEDOT/pull/807

2022-09-06 13:54 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        If None numbers of samples will be equal to the shape of opposite selected transformed class.
@andreygetmanov не совсем понял про отступ

2022-09-06 15:09 UTC, aPovidlo commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
> +        If None numbers of samples will be equal to the shape of opposite selected transformed class.
Добавил в [b6c7ab0](https://github.com/nccr-itmo/FEDOT/pull/861/commits/b6c7ab0e8721890616f117af960c4eb0e9254de8)

2022-09-06 15:38 UTC, andreygetmanov approved these changes

2022-09-06 16:43 UTC, merged