Refactor forecast method
nccr-itmo/FEDOT pull request #870
Opened 2022-09-09 12:37 UTC by YamLyubov

```Fedot.forecast``` method refactored
#858

2022-09-09 12:37 UTC, pep8speaks commented
Hello @YamLyubov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`fedot/core/composer/metrics.py`](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/fedot/core/composer/metrics.py):

> [Line 144:1](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/fedot/core/composer/metrics.py#L144): [E302](https://duckduckgo.com/?q=pep8%20E302) expected 2 blank lines, found 1

* In the file [`test/unit/api/test_main_api.py`](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/test/unit/api/test_main_api.py):

> [Line 90:5](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/test/unit/api/test_main_api.py#L90): [F841](https://duckduckgo.com/?q=pep8%20F841) local variable 'task' is assigned to but never used
> [Line 196:13](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/test/unit/api/test_main_api.py#L196): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator
> [Line 197:13](https://github.com/nccr-itmo/FEDOT/blob/6acdc7170d3e74471276e5f157656957fc36d04b/test/unit/api/test_main_api.py#L197): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator

2022-09-09 13:31 UTC, gkirgizov requested changes
Все хорошо, небольшие комментарии

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +                 horizon: int = None,
Раз None, то тип Optional

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +        horizon = horizon or self.train_data.task.task_params.forecast_length
Можно не дублировать доступ к `forecast_length`

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +        horizon = horizon or self.train_data.task.task_params.forecast_length
horizon = 0 эквивалентно horizon=None ?

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +        if len(predict.shape) > 1:
можно `predict.ndim > 1`

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +    def _union_predictions(predictions: List[OutputData], horizon: int) -> OutputData:
Может, перенести этот метод в `DataMerger`? Кажется, по логике принадлежит ему.
Еще я бы переименовал в `_concat_predictions`, т.к. "union" менее однозначен.

2022-09-09 13:31 UTC, gkirgizov commented on fedot/api/main.py
> +    def _update_input(previous_input: InputData, predicted_values: OutputData) -> InputData:
Может, лучше что-то вроде `shift_index_for_forecast`

2022-09-09 13:40 UTC, YamLyubov commented on fedot/api/main.py
> +        horizon = horizon or self.train_data.task.task_params.forecast_length
Все-таки не эквивалентен, думаю. Возможно стоит проверять, что horizon > 0 и кидать ошибку?

2022-09-10 14:01 UTC, Dreamlone requested changes
В целом по функциональности всё кул - именно так мне этот метод и представлялся

2022-09-12 07:27 UTC, YamLyubov commented on fedot/api/main.py
> +                input_data = self._update_input(input_data, prediction)
В таком случае возможно стоит переработать существующий метод и использовать его для Fedot.forecast. 

Текущй out_of_sample_ts_forecast некорректно работает на MultimodalData - возвращает одно и тоже значение необходимое кол-во раз. Насколько я понимаю, для случая мультимодальных данных out-of-sample в общем случае нельзя применить.

2022-09-12 10:16 UTC, YamLyubov commented on fedot/api/main.py
> +        horizon = horizon or self.train_data.task.task_params.forecast_length
Не стала делать проверку, просто так [заменила ](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR259)

2022-09-12 10:16 UTC, YamLyubov commented on fedot/api/main.py
> +        if len(predict.shape) > 1:
[Поменяла](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-67c0ef516634676d7459c9742c5be960366ed4b5629bca429676728e4047e351R62)

2022-09-12 10:17 UTC, YamLyubov commented on fedot/api/main.py
> +        self.prediction = self._get_forecast(input_data, horizon, forecast_length)
[Убрала](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-c8c3532da680ee4d8a1c35a5b02009326da1b007a9fa794413345ffc864411eeR264)

2022-09-12 10:18 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +    model.fit(train_data)
[Поставила](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-3024e99987ea3223b4f92729b426eabaf4b75077e6d3c3a550fde20d3a4e23fbR485)

2022-09-12 10:19 UTC, YamLyubov commented on fedot/api/main.py
> +                input_data = self._update_input(input_data, prediction)
Немного поменяла [out_of_sample_ts_forecast](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-67c0ef516634676d7459c9742c5be960366ed4b5629bca429676728e4047e351R15)

2022-09-12 10:26 UTC, YamLyubov commented on fedot/api/main.py
> +    def _union_predictions(predictions: List[OutputData], horizon: int) -> OutputData:
Здесь пока ничего не меняла. Чтобы это исправить, наверное, надо будет изменить [define_data ](https://github.com/nccr-itmo/FEDOT/blob/50e45ea90745fd181c3966822a06d2fd684fa615/fedot/api/api_utils/data_definition.py#L46). 

Насколько это важно исправить?

2022-09-12 10:26 UTC, YamLyubov commented on fedot/api/main.py
> +                prediction = self.current_pipeline.predict(input_data)
Здесь пока ничего не меняла. Чтобы это исправить, наверное, надо будет изменить [define_data ](https://github.com/nccr-itmo/FEDOT/blob/50e45ea90745fd181c3966822a06d2fd684fa615/fedot/api/api_utils/data_definition.py#L46).

Насколько это важно исправить?

2022-09-12 11:14 UTC, gkirgizov approved these changes

2022-09-12 14:43 UTC, andreygetmanov approved these changes

2022-09-13 06:50 UTC, Dreamlone commented on fedot/api/main.py
> +                prediction = self.current_pipeline.predict(input_data)
Да думаю не очень важно, хотя есть сомнения, что glm модель отработает нормально при таком подходе, когда индексы задаются не так как ожидалось - проверь пожалуйста как на таких данных будет работать Pipeline(PrimaryNode('glm')): нужно посмотреть как пайплайн справится с стандартными индексами на тесте, и как они подаются сейчас в main - если output одинаковый, то можно оставлять как есть

2022-09-13 07:02 UTC, Dreamlone approved these changes

2022-09-13 07:02 UTC, Dreamlone commented on test/unit/api/test_main_api.py
> +def test_forecast_with_multimodal_ts():
nit: лучше сохранить исходное название `multivariate` - мультимодальные временные ряды, это не только многомерные, это ещё и 'multi ts' (отдельный DataType в FEDOT). Многомерные ряды более прозрачное название, при этом они всегда мультимодальные в терминах FEDOT'а

2022-09-13 07:44 UTC, YamLyubov commented on fedot/api/main.py
> +                prediction = self.current_pipeline.predict(input_data)
Проверила - предсказания в одинаковые независимо от индексов

2022-09-13 07:53 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +def test_forecast_with_multimodal_ts():
Похоже я просто просто плохо понимаю разницу между многомерным и мультимодальным рядом. Можешь, пожалуйста, объяснить или подсказать, где об этом почитать?

2022-09-13 08:01 UTC, YamLyubov commented on fedot/core/data/multi_modal.py
> +                return input_data.features
Мне была нужна эта функциональность, чтобы создать OutputData из вектора [здесь](https://github.com/nccr-itmo/FEDOT/pull/870/files#diff-67c0ef516634676d7459c9742c5be960366ed4b5629bca429676728e4047e351R323). Показалось, что стоит добавить этот метод сразу в соответствующий класс.

Получается, что для[ target](https://github.com/nccr-itmo/FEDOT/pull/870/files/891efeb2a0da01b40874d3df5541c7fda8d02827#diff-92a862192777de2d5abf87b8f3d3970c5100e86e6d08d816b33c5f983ea0eadbR43) сейчас такая же реализация, поэтому по аналогии решила, что такая реализация имеет смысл

2022-09-14 06:48 UTC, Dreamlone commented on fedot/core/data/multi_modal.py
> +                return input_data.features
Для target она имеет смысл, потому что как правило соблюдается отношение "много предикторов - один target" и даже если целевая переменная в пайплайне не одна, можно однозначно определить по флагу `is_main_target=True` какой из вариантов target'a является самым главным. При этом если есть несколько целевых переменных с флагом `is_main_target=True`, то можно брать любой из них для дальнейших действий, хоть первый попавшийся, потому что есть целевая переменная помечена как `is_main_target=True`, то она ничем не отличается от другой с такой же пометкой. То есть они идентичны. 

С признакми такого нет - они могут отличатся даже в пределах главного поддерева в пайплайне. Лучше тогда просто сделать features поле опциональным в OutputData и не запихивать туда ничего

2022-09-14 07:08 UTC, Dreamlone commented on test/unit/api/test_main_api.py
> +def test_forecast_with_multimodal_ts():
Начать тут стоит с определения мультимодальности в FEDOT. Неформально мультимодальными данными в FEDOT можно назвать такой датасет, объекты которого описываются более чем одним типом данных. Например для каждой метки "болен человек или нет" есть таблица с признаками и ещё дополнительно картинка. Тогда FEDOT построит пайплайн, в котором будет несколько data source узлов. Таким образом, ключевым свойством FEDOT'а на мультимодальных данных будет **наличие data source узлов**. 

Теперь переходим к временным рядам. Иногда требуется прогнозировать один временной ряд не только по его предыстории, но и по предыстории дополнительных (экзогенных) рядов - см. картинку. На этой схеме показано, что мы хотим прогнозироват красный временной ряд. При этом на момент формирования прогноза нам не доступны значения дополнительных временных рядов в те же моменты времени, на которые дается прогноз 
![image](https://user-images.githubusercontent.com/52418437/190083931-00bd9748-9a63-49ae-9d79-cd85b422f766.png)

Вот такие ряды называются многомерными. Поэтому в FEDOT каждый временной ряд подаётся каждый на свой data source узел. 
Таким образом, все многомерные временные ряды в рамках фреймворка мультимодальны. Но не все мультимодальные ряды можно назвать  многомерными в классифеском понимании. На вопрос какие же тогда ещё в библиотеке есть ряды, которые не многомерные, но можно назвать мультимодальными я сначала вспомнил про multi ts, которые готовила Юля (лучше у неё спросить поподробнее что это за зверь такой). Но сейчас обнаружил в `cases/multi_ts_level_forecasting.py` что эти ряды не подаются как мультимодальные.  

Тогда в целом можно привести пример ещё с такими рядами (второй и третий ряд передаются через операцию exog_ts) - устоявшегося названия для такой конструкции в фреймворке пока что нет, но обычно в литературе такую штуку иногда называют динамической регрессией. Они тоже мультимодальны например. 
![image](https://user-images.githubusercontent.com/52418437/190084690-d34f963d-b9e6-4f50-9ca7-8ce9c8da510b.png)

В общем, термин многомерные ряды более специализированный, чем мультимодальные. Поэтому лучше использовать этот термин вместо более общих там, где это возможно

2022-09-14 07:25 UTC, YamLyubov commented on test/unit/api/test_main_api.py
> +def test_forecast_with_multimodal_ts():
Спасибо большое за объяснение

2022-09-14 07:39 UTC, nicl-nno commented on test/unit/api/test_main_api.py
> +def test_forecast_with_multimodal_ts():
Я бы сказал что в случае с "моделью, которая принимает на вход несколько рядов" мультимодальность это скорее наш внутренний сленг. MultiModalData - это механизм, чтобы подавать несколько "независимых" источников данных на вход пайплайна. Он используется и для реально разнотипных данных, и для нескольких рядов с разной природой (температура и давление; или температура в разных частях установки)

А multi-ts - это способ подавать выборку рядов, которые "независимыми" не являются - просто реализациями одного и того же случайного процесса.

2022-09-15 06:45 UTC, merged