608 adapters
nccr-itmo/FEDOT pull request #876
Opened 2022-09-13 11:29 UTC by gkirgizov

Adaptation subsystem is refactored -- now it's more high-level and requires less attention from developers.

Main changes:

Aimed at #742

2022-09-13 11:30 UTC, pep8speaks commented
Hello @gkirgizov! Thanks for opening this PR. We checked the lines you've touched for [PEP 8](https://www.python.org/dev/peps/pep-0008) issues, and found:



* In the file [`examples/advanced/fedot_based_solutions/graph_model_optimization.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/examples/advanced/fedot_based_solutions/graph_model_optimization.py):

> [Line 10:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/examples/advanced/fedot_based_solutions/graph_model_optimization.py#L10): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.adapter.AdaptRegistry' imported but unused

* In the file [`fedot/core/adapter/__init__.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/adapter/__init__.py):

> [Line 1:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/adapter/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) '.adapter.BaseOptimizationAdapter' imported but unused
> [Line 1:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/adapter/__init__.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) '.adapter.DirectAdapter' imported but unused
> [Line 2:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/adapter/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) '.adapt_registry.AdaptRegistry' imported but unused
> [Line 2:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/adapter/__init__.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) '.adapt_registry.register_native' imported but unused





* In the file [`fedot/core/composer/gp_composer/gp_composer.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/composer/gp_composer/gp_composer.py):

> [Line 3:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/composer/gp_composer/gp_composer.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.adapter.AdaptRegistry' imported but unused

* In the file [`fedot/core/composer/gp_composer/specific_operators.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/composer/gp_composer/specific_operators.py):

> [Line 2:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/composer/gp_composer/specific_operators.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Any' imported but unused

* In the file [`fedot/core/dag/graph.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph.py):

> [Line 3:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Any' imported but unused
> [Line 3:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Generic' imported but unused

* In the file [`fedot/core/dag/graph_delegate.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph_delegate.py):

> [Line 2:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph_delegate.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Callable' imported but unused

* In the file [`fedot/core/dag/graph_operator.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph_operator.py):

> [Line 206:16](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/dag/graph_operator.py#L206): [E126](https://duckduckgo.com/?q=pep8%20E126) continuation line over-indented for hanging indent





* In the file [`fedot/core/optimisers/adapters.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/adapters.py):

> [Line 6:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/adapters.py#L6): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.optimisers.gp_comp.individual.Individual' imported but unused
> [Line 8:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/adapters.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.node.Node' imported but unused
> [Line 10:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/adapters.py#L10): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.pipelines.template.PipelineTemplate' imported but unused

* In the file [`fedot/core/optimisers/gp_comp/evaluation.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/evaluation.py):

> [Line 2:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/evaluation.py#L2): [F401](https://duckduckgo.com/?q=pep8%20F401) 'multiprocessing' imported but unused



* In the file [`fedot/core/optimisers/gp_comp/gp_optimizer.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/gp_optimizer.py):

> [Line 8:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/gp_optimizer.py#L8): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.optimisers.gp_comp.individual.Individual' imported but unused



* In the file [`fedot/core/optimisers/gp_comp/operators/mutation.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/mutation.py):

> [Line 4:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/mutation.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Sequence' imported but unused

* In the file [`fedot/core/optimisers/gp_comp/operators/regularization.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/regularization.py):

> [Line 1:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/regularization.py#L1): [F401](https://duckduckgo.com/?q=pep8%20F401) 'copy.deepcopy' imported but unused
> [Line 4:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/regularization.py#L4): [F401](https://duckduckgo.com/?q=pep8%20F401) 'fedot.core.adapter.AdaptRegistry' imported but unused
> [Line 48:29](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/gp_comp/operators/regularization.py#L48): [W503](https://duckduckgo.com/?q=pep8%20W503) line break before binary operator





* In the file [`fedot/core/optimisers/opt_history.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/opt_history.py):

> [Line 200:35](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/opt_history.py#L200): [F541](https://duckduckgo.com/?q=pep8%20F541) f-string is missing placeholders

* In the file [`fedot/core/optimisers/optimizer.py`](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/optimizer.py):

> [Line 3:1](https://github.com/nccr-itmo/FEDOT/blob/9e6fd93188a7710c4ba49c00c1256062cf86fead/fedot/core/optimisers/optimizer.py#L3): [F401](https://duckduckgo.com/?q=pep8%20F401) 'typing.Union' imported but unused











* In the file [`fedot/remote/ru [...]

2022-09-15 11:20 UTC, gkirgizov commented
@pep8speaks pls update youself

2022-09-20 22:05 UTC, nicl-nno requested changes
Предлагаю сразу на основе описания PR-а сделать заметку в документации, посвященную  именно адаптерам. Можно со ссылками на докстринги (т.к. они довольно подробные), которые нужно почитать.

2022-09-20 22:05 UTC, nicl-nno commented on fedot/api/api_utils/api_composer.py
> +        self.was_tuned = False
Может и was_optimised тоже добавить тогда? И не лучше ли будет это реализовать как property, внутри которого будет обращение к композеру?

2022-09-21 13:49 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +        self.was_tuned = False
`was_optimised` скорее тоже будет на уровне ApiComposer, тк логика определения, есть ли время на композирование, находится в нем

2022-10-04 14:35 UTC, gkirgizov commented on fedot/api/api_utils/api_composer.py
> +        self.was_tuned = False
тут чуть поправил https://github.com/nccr-itmo/FEDOT/pull/876/commits/66e4bdfc9f70f70b1ded4a5e6895b213a749540c

2022-10-05 06:19 UTC, gkirgizov commented on fedot/core/adapter/adapter.py
> +        return self._adapt(item) if type(item) is self.domain_graph_class else item
подшлифовал интерфейс

2022-10-05 07:25 UTC, MorrisNein approved these changes

2022-10-05 10:20 UTC, nicl-nno commented on fedot/core/adapter/adapter.py
> +    def _restore(self, opt_graph: OptGraph, metadata: Optional[Dict[str, Any]] = None) -> DomainStructureType:
Может тогда этот метод назвать restore_graph или restore_single?

2022-10-05 10:21 UTC, nicl-nno approved these changes

2022-10-05 13:55 UTC, merged

2022-10-06 07:27 UTC, gkirgizov commented on fedot/core/adapter/adapter.py
> +    def _restore(self, opt_graph: OptGraph, metadata: Optional[Dict[str, Any]] = None) -> DomainStructureType:
oops, не заметил твой коммент перед мерджем. 
вообще, это непубличный метод, и его не предполагается вызывать извне. это скорее ядро реализации метода, для определения в потомках.