Implement Model Repository subsystem for generic graph optimiser
nccr-itmo/FEDOT pull request #894
Opened 2022-09-15 12:47 UTC by maypink

WIP

2022-09-21 11:08 UTC, gkirgizov requested changes

2022-09-21 11:08 UTC, gkirgizov commented on fedot/core/repository/pipeline_operation_repository.py
> +                 models_keys: List[str] = None):
Может, чтобы не делать сложный init с нескольими вариантами, сделать отдельный статический метод вроде `from_available_operations`?

2022-09-21 11:08 UTC, gkirgizov commented on fedot/core/repository/graph_operation_reposiroty.py
> +        self.models_keys = models_keys
зачем нужен `models_keys` в базовом классе?

2022-09-22 09:51 UTC, maypink commented on fedot/core/repository/pipeline_operation_repository.py
> +                 models_keys: List[str] = None):
[done](https://github.com/nccr-itmo/FEDOT/pull/894/commits/322ddba981ae8a52d98a561a680a3cec223d22a0#diff-0e44e75d30da9d74a3a40545377bafdbef27c36daaa9ef74fa314b92b17946c3R22)

2022-09-22 09:52 UTC, maypink commented on fedot/core/repository/pipeline_operation_repository.py
> +        return list(np.array(list((self.operations_by_keys.values()))).flatten())
[done](https://github.com/nccr-itmo/FEDOT/pull/894/commits/322ddba981ae8a52d98a561a680a3cec223d22a0#diff-0e44e75d30da9d74a3a40545377bafdbef27c36daaa9ef74fa314b92b17946c3R39)

2022-09-22 09:52 UTC, maypink commented on fedot/core/repository/graph_operation_reposiroty.py
> +        self.models_keys = models_keys
[а не нужен](https://github.com/nccr-itmo/FEDOT/pull/894/commits/322ddba981ae8a52d98a561a680a3cec223d22a0#diff-145482a3008c324118fcdf91815e24b1d06c072a8d13e77afe533296c8903bc7L8)

2022-09-22 11:38 UTC, gkirgizov approved these changes

2022-09-22 12:40 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +            possible_operations = self.graph_model_repository.get_operations(is_primary=False)
Здесь можно заменить на ```possible_operations = self.graph_model_repository.get_operations(is_primary=is primary)``` без проверки.

2022-09-22 12:40 UTC, YamLyubov commented on fedot/core/pipelines/pipeline_node_factory.py
> +            if is_primary else self.graph_model_repository.get_operations(is_primary=False)
И здесь аналогично

2022-09-22 15:27 UTC, merged