Redesign tunable params
nccr-itmo/FEDOT pull request #902
Opened 2022-09-21 13:28 UTC by YamLyubov

ParametersChangeKeeper is implemented wrapping model parameters and keeping track of parameters updates. 

While tuning Tuner can set incorrect parameters for nodes. These parameters are corrected in DataOperationImplementation and ModelImplementation. ParametersChangeKeeper records what parameters were changed so later node parameters can be updated with correct ones. 

DEFAULT_PARAMS_STUB is removed. If no parameters were passed in the content for node default parameters from default_operation_params.json are used.

2022-09-22 09:53 UTC, valer1435 commented on fedot/core/operations/changing_parameters_keeper.py
> +    If neither parameters nor operation_type were passed, parameters are equal to empty dict.
nor -> or мб?

2022-09-22 10:09 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +    If neither parameters nor operation_type were passed, parameters are equal to empty dict.
Вроде как neither nor верно (https://preply.com/en/blog/using-either-neither-nor-and-or-in-english/)

> “Neither” is used in the same sentence as “nor” to show something is not true or doesn’t happen out of two or more people, actions, things, ideas, or qualities. For example:
>   “Neither Mr Smith nor Mrs Jones came to the meeting.”

2022-09-22 13:13 UTC, gkirgizov requested changes

2022-09-22 13:13 UTC, gkirgizov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def __init__(self, operation_type: Optional[str] = None, parameters: Optional[dict] = None):
может, сделать отдельный staticmethod для `from_operation_type`, и разрешить `parameters` передавать как `**` кейворды?

2022-09-22 13:13 UTC, gkirgizov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def __init__(self, operation_type: Optional[str] = None, parameters: Optional[dict] = None):
тогда использовать обертку будет немного удобнее

2022-09-22 13:13 UTC, gkirgizov commented on fedot/core/operations/changing_parameters_keeper.py
> +class ParametersChangeKeeper:
кажется, имя файла надо обновить в соответствии с именем класса

2022-09-22 13:40 UTC, valer1435 requested changes

2022-09-22 13:40 UTC, valer1435 commented on fedot/core/operations/evaluation/time_series.py
> +            model = self.operation(self.params_for_fit)
Тут тоже можно передавать всегда self.params_for_fit, так как None скушается

2022-09-22 13:40 UTC, valer1435 commented on fedot/core/pipelines/node.py
> +        updated_params = {**self.custom_params, **changed_parameters}
Точно ли приоритет имеют те параметры, которые были указаны вторыми?

2022-09-27 14:41 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +        self.parameters = parameters if parameters is not None else {}
[Сделала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R21-R22) приватными 
copy в данном случае уже не нужно

2022-09-27 14:42 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +        return self.parameters
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R47-R48) на to_dict() и добавила copy

2022-09-27 14:45 UTC, YamLyubov commented on fedot/core/operations/evaluation/clustering.py
>              operation_implementation = self.operation_impl(n_clusters=2)
[Здесь](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-5f80676300c9d56025bb053e95200d04bafeee5c590f90d67e1ef69d8ef63cc9R23) и в аналогичных местах посларалась избавиться от таких проверок. В данном случае осталость проверка на пустой словарь.

2022-09-27 14:47 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +        return self.params
Этот метод [удалила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-9c5efa812bf4dcfec446f6f0ed7a7e619f83367c8111e4587b44929ed49e0a83R182), так как от определен в суперклассе

2022-09-27 14:55 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_imbalanced_class.py
>          self.balance_ratio = params.get('balance_ratio') if params.get('balance_ratio') is not None else 1.0
[Вынесла](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-59569d8434ce7581c1429c03399896e152766e463ac4a53a9f7194b5478e4494R42) эти параметры в проперти и [перенесла ](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-59569d8434ce7581c1429c03399896e152766e463ac4a53a9f7194b5478e4494R163)проверку на None

2022-09-27 14:56 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_selectors.py
> +            rfe_params = {k: params.get_parameters()[k] for k in
Исправила [здесь](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-aade0320a1a02e0199dc3aac09c6b2981c6bed58a7e6b0913a2d8eedb39cc6ebR127) и в аналогичных местах

2022-09-27 14:57 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>          if not params:
Сделала [проперти](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R364-R366)

2022-09-27 14:59 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>              self.sigma = round(params.get('sigma'))
Добавила [get_or_set](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R42) и [использовала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R515)

2022-09-27 15:00 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +        self.window_size = int(self.params.get('window_size'))
Вынесла в [проперти](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R539)

2022-09-27 15:02 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>          else:
[Сделала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R652)

2022-09-27 15:03 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            self.params = ParametersChangeKeeper(parameters={**self.params.parameters, **params.get_parameters()})
Теперь вроде лучше khttps://github.com/nccr-itmo/FEDOT/pull/902/files#diff-3dec8e358a7f2feec92ac1b3c93ee16cafa408e3f1a56829f01f063d8580a3baR170)

2022-09-27 15:08 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +        self.custom_params = updated_params
Здесь update неравнозначен custom_params.setter (теперь [parameters.setter](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR219)
Сеттер обновляет self.content['params']

2022-09-27 15:15 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +            self.content.update({'params': self.parameters.get_parameters()})
Я переименовала custom_params в parameters, так как кажется, что не совсем понятно, почему они кастомные.
Прежние parameters сделала приватными.

2022-09-27 15:22 UTC, YamLyubov commented on test/unit/models/test_model.py
> +        fitted_operation, train_predicted = model.fit(params=ParametersChangeKeeper(parameters=default_params), data=deepcopy(train_data))
[Можно передавать словарь ](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932R69)

2022-09-27 15:23 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def __init__(self, operation_type: Optional[str] = None, parameters: Optional[dict] = None):
добавила[ from_operation_type](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R28)
[пример](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR60)

2022-09-27 15:24 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +class ParametersChangeKeeper:
[Переименовала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14)

2022-09-27 15:27 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +        self.parameters = parameters if parameters is not None else {}
Так как[ изменила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R20) интерфейс конструктора, вынесла эту проверку в Node [тут](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR46) и[ тут](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR228)

2022-09-27 15:32 UTC, YamLyubov commented on fedot/core/operations/evaluation/clustering.py
> +            operation_implementation = self.operation_impl(**self.params_for_fit.get_parameters())
Здесь параметры передаются в реализацию sklearn, поэтому используются kwargs. В других случаям это федотовские реализации, которые принимают OperationParameters

2022-09-27 15:44 UTC, YamLyubov commented on fedot/core/operations/evaluation/evaluation_interfaces.py
> +            operation_implementation = self.operation_impl(**self.params_for_fit.get_parameters())
[убрала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-60a694a93b0cdb51f5f81fc4449dfb07a74d317aa8bd323439c4804353c0584aR217)

2022-09-27 15:45 UTC, YamLyubov commented on fedot/core/operations/evaluation/gpu/common.py
> +            operation_implementation = self.operation_impl(**self.params_for_fit.get_parameters())
[убрала](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-883de6835be7545975efad596298e37ab022abb5ba0e2da9a16fef30badafc81R71)

2022-09-27 15:46 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/sklearn_filters.py
> +                self.operation = RANSACRegressor(base_estimator=self.inner_model, **params.get_parameters())
Заменила на [to_dict](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R47)

2022-09-27 15:47 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.params.update('sigma', 1)
Убрала и [перенесла](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R515)

2022-09-27 15:52 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
> +            self.params.update('poly_degree', self.poly_degree)
Вынесла в [проперти](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R539). Так как эти параметры используются в разных методах несколько раз совсем из убират не удобно

2022-09-27 15:53 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/ts_transformations.py
>              self.cut_part = 0.5
Тоже сделала [проперти](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-c6913fefa5545ed365e8e50fa4a65db05786d33a9c2413df3cec46d441ca8412R653)

2022-09-27 15:54 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/implementation_interfaces.py
> +    def __init__(self, params: ParametersChangeKeeper = ParametersChangeKeeper()):
[исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-53579048c8b22a05e52c5f7ee8b4779da341929a2be7ac10d431e85a071c34deR19)

2022-09-27 15:58 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
>          self.lambda_value = None
Здесь убрать не получится, так как эти параметры достаются не из params и используются в разных методах

2022-09-27 15:58 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/arima.py
>          self.lambda_param = None
Здесь тоже не получится убрать

2022-09-27 16:01 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
>          self.family_link = None
https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R54

2022-09-27 16:01 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/ts_implementations/statsmodels.py
> +        if self._lag_was_changed(previous_lag_1, new_lag_1):
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-73c9b7bf202f067c9c8f3425d56f358d03588b6ab232877aaac7e8d02310d0b2R223) проверкой на равенство

2022-09-27 16:03 UTC, YamLyubov commented on fedot/core/operations/evaluation/time_series.py
> +            model = self.operation(self.params_for_fit)
[Исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-6403a42fbd1b20c9548eea190c48c741efd7899d0c8de6b58aee3e0f82500c2bR58)

2022-09-27 16:04 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +        updated_params = {**self.custom_params, **changed_parameters}
Да, мы берем дефолтные параметры и переопределяем их значения переданными

2022-09-27 16:05 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> -                # take nested composer params if they appeared
[Вернула](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f8b54747977d30964212d81746ebb50494c660385b62e2819bb23b83c156f20dR230)

2022-09-29 12:44 UTC, valer1435 requested changes

2022-09-29 12:44 UTC, valer1435 commented on fedot/core/operations/evaluation/operation_implementations/models/svc.py
> +        if not self.params:
Сейчас подумал, что имеет имеет смысл определить у базового класса метод initialize_default_params() и переопределять у реализаций. Это скроет логику таких вот однообразных действий. Но мб и не надо.

2022-09-29 12:44 UTC, valer1435 commented on fedot/core/operations/operation_parameters.py
> +    def from_operation_type(operation_type: Optional[str], **parameters):
Что будет, если передать сюда None?

2022-09-29 12:44 UTC, valer1435 commented on test/unit/models/test_atomized_model.py
> +    dummy_atomized_model.fit(None, train_data)
Мб стоит указать в определении, что этот параметр необязательный? И переделать на передачу параметров по ключу

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +            if params == 'default_params':
может, контанту таки оставить для обратной совместимости? иначе весьма загадочно, откуда эта строка, и код легко сломать

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +            if params == 'default_params':
тоже лучше константу оставить

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +                params = params['nested_space']
это бы тоже заодно вынести как именованная константу

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +            self.content.update({'params': self._parameters.to_dict()})
один элемент записатьт проще через `=`, чем `update`

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
>          return self.content.get('params')
Как теперь используется `сontent['params']`? Насколько я понимаю, он дублирует информацию из `self._parameters`. Если так, то хотелось бы понимать, для чего. Могу ошибаться.

2022-10-03 07:19 UTC, gkirgizov commented on fedot/core/pipelines/node.py
> +            self.content.update({'params': self.parameters.get_parameters()})
А для чего нужен отдельный `сontent['params']`? Насколько я понимаю, он дублирует информацию из `self._parameters`. Если так, то хотелось бы понимать, для чего.

2022-10-05 12:00 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
[Исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R48)

2022-10-05 12:01 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/data_operations/categorical_encoders.py
> +        self.encoder = OneHotEncoder(**{**self.params.to_dict(), **default_params})
[Исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-f7952f4ada6d235f933e9102aa3d95c4820508f487c4f74f954e4a4cbcc13053R22)

2022-10-05 12:03 UTC, YamLyubov commented on fedot/core/operations/operation_parameters.py
> +    def from_operation_type(operation_type: Optional[str], **parameters):
Здесь все-таки нельзя None передавать - [исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R28)

2022-10-05 12:04 UTC, YamLyubov commented on test/unit/models/test_atomized_model.py
> +    dummy_atomized_model.fit(None, train_data)
[Сделала необязательным](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-5f1e2d47905e5ae35637436e9ee6319f7337430cd28b6dabe69e26e72ac05932R69)

2022-10-05 12:04 UTC, YamLyubov commented on fedot/core/operations/operation_parameters.py
> +        return copy(self._parameters)
[Исправила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R48)

2022-10-05 12:11 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
Этот метод удобно использовать в случае, когда мы хотим получить параметер, а если он не был задан установить некое значение. Если использовать get и set, то нужна будет какая-то такая конструкция каждый раз:
```
param = param.get('name')
if not param:
    param = default_value
    params.update('name', default_value)
```

2022-10-05 12:13 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            self.params = OperationParameters(**{**self.params.to_dict(), **params.to_dict()})
Сейчас у OperationParams update только для одного значения реализован, для словаря не работает

2022-10-05 12:14 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +            if params == 'default_params':
[Добавила ](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-8540e7875d254c2f4c505a82f0a260d6c2567ebc26cfd5a8cd5e0e98f5750b3cR13)

2022-10-05 12:15 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +                params = params['nested_space']
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-8540e7875d254c2f4c505a82f0a260d6c2567ebc26cfd5a8cd5e0e98f5750b3cR14)

2022-10-05 12:16 UTC, YamLyubov commented on fedot/core/pipelines/node.py
> +            self.content.update({'params': self._parameters.to_dict()})
[Поменяла](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-8540e7875d254c2f4c505a82f0a260d6c2567ebc26cfd5a8cd5e0e98f5750b3cR14)

2022-10-05 12:22 UTC, YamLyubov commented
`сontent['params']` нужно чтобы взаимодействовать с Node как с GraphNode, как, например, [тут](https://github.com/nccr-itmo/FEDOT/blob/master/fedot/core/dag/graph_node.py#L118)

2022-10-05 14:08 UTC, valer1435 commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
Не могу пока понять, где это может быть полезно. Выглядит странно. @gkirgizov, что думаешь?

2022-10-05 14:11 UTC, valer1435 reviewed
Замечаний нет. Только с get_or_set разобраться

2022-10-10 09:07 UTC, YamLyubov commented on fedot/core/operations/evaluation/operation_implementations/models/keras.py
> +            self.params = OperationParameters(**{**self.params.to_dict(), **params.to_dict()})
[Изменила](https://github.com/nccr-itmo/FEDOT/pull/902/files#diff-cf9120e9ed264478111aa5f922c4c3a25b40ab9d183a0918ec04e0a3310e8b14R33)

2022-10-10 16:36 UTC, valer1435 approved these changes

2022-10-11 09:34 UTC, gkirgizov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
> Не могу пока понять, где это может быть полезно. Выглядит странно. @gkirgizov, что думаешь?

Я это и предложил :) Была пара ипользований такого рода, и они хорошо укладываютя в этот метод

2022-10-11 09:35 UTC, gkirgizov approved these changes

2022-10-11 09:36 UTC, nicl-nno commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
Может назвать это ensure_value?

2022-10-11 09:46 UTC, YamLyubov commented on fedot/core/operations/changing_parameters_keeper.py
> +    def get_or_set(self, key, value):
Для обычного словаря такой метод называется `setdefault` https://pythonz.net/references/named/dict.setdefault/
Можно по аналогии также назвать

2022-10-11 10:51 UTC, merged