880_quick_start
nccr-itmo/FEDOT pull request #908
Opened 2022-09-26 12:08 UTC by IIaKyJIuH

Finished RTD's `Intro->Quickstart` section.

[Link to the documentation page](https://fedot.readthedocs.io/en/880_doc_quick_start/introduction/tutorial/quickstart.html#how-to-compose-the-pipeline-in-an-automated-way).

2022-09-26 12:15 UTC, nicl-nno commented
Я бы лучше вообще убрал pycharm-related часть и описал бы как создавать venv по аналогии с https://github.com/openml/automlbenchmark, например.

Также, логически лучше начинать quick start с базовых вещей и переходить к более специфичным потом.

В нашем случае это, на мой взгляд: 

- установка из pip
- automl
- ручная сборка пайплайна
- установка с гитхаба.

Ну и пример в How to compose the pipeline in an automated way показан черезчур вырожденный - стоит хотя бы параметр вроде timeout задать.

2022-10-05 09:41 UTC, YamLyubov requested changes

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/quickstart.rst
> +.. include:: automated_creation.rst
Мне кажется было бы удобнее если бы заголовки имели следующую структуру:
# Setup environment
## Easy way
## Using GitHub

# Compose pipeline
## Manual
## Automated

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/manual_creation.rst
> +   model.plot_prediction()
Можно добавить пример аутпута

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/manual_creation.rst
> +-  **Step 4**. Obtain the prediction using *predict* method and show fitting metrics.
>  and show fitting metrics

Может как-нибудь перефразировать, типа 

> and calculate specified metrics

Но возможно и по-лучше вариант есть.

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/manual_creation.rst
> +-  **Step 3**. Fit the chosen pipeline using *fit* method.
Методы лучше выделить как код, а не курсивом *predict* -> ```predict```

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/manual_creation.rst
>  -  **Step 2**. Create *Pipeline* instance, create nodes with desired models
Здесь можно добавить ссылку на раздел с примерами пайплайнов для разных задач. Они есть в Examples and notebooks

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/manual_creation.rst
> +   timeout, preset, metric_names, with_tuning, n_jobs, logging_level = ...
Было бы не плохо указать, где посмотреть доступные параметры запуска. Можно оставить ссылку на раздел Modules -> FEDOT API

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +      following command
Такие штуки можно короче написать: Run in command line или просто Run

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  But, if you want to be able to run NNs examples and all other specific stuff,
Не очень понятно, что за стаф)) Наверное, лучше уточнить.

Что-то типа: To use additional functionality such as  NNs, ... run full installation.

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +      Here you need to type in the following:
Можно короче написать: 
After creating the virtual environment, install the libraries necessary for FEDOT work. Type in:

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +      for excluding libraries incompatibility and confusion.
Confusion здесь синонимично incompatibility, так что confusion можно убрать. 
Я бы еще for excluding заменила на to avoid, но это все дело вкуса)

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  Then open cmd(Windows) or terminal(Unix like OS), type in:
Не хватает пробелов перед открывающими скобками

2022-10-05 09:41 UTC, YamLyubov commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  For more details, take a look at the picture below.
Текст на картинку ссылается, поэтому думаю, что этот пункт можно убрать

2022-10-08 09:17 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  For more details, take a look at the picture below.
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/5355cdd36920156468bb65bff94618ecb5bb21f8)

2022-10-08 09:19 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/manual_creation.rst
> +   model.plot_prediction()
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/4f120a8959c05089ab3c60a0b6fc23b1b4016f0a)

2022-10-08 09:19 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/manual_creation.rst
> +-  **Step 4**. Obtain the prediction using *predict* method and show fitting metrics.
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/4f120a8959c05089ab3c60a0b6fc23b1b4016f0a)

2022-10-08 09:20 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/manual_creation.rst
> +-  **Step 3**. Fit the chosen pipeline using *fit* method.
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/9da5044f4237625fc613167d80fc18fe0cbb3f42)

2022-10-08 09:22 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  But, if you want to be able to run NNs examples and all other specific stuff,
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/f7b4a491586e5c66dbb490942b6e472a52ed0aff)

2022-10-08 09:22 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +      Here you need to type in the following:
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/f7b4a491586e5c66dbb490942b6e472a52ed0aff#diff-34625e89584c76f3ffc1483c712e6fa9dd905c672f117ce89dfc1f864a5ed08eR31-R33)

2022-10-08 09:25 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +      following command
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/f7b4a491586e5c66dbb490942b6e472a52ed0aff#diff-34625e89584c76f3ffc1483c712e6fa9dd905c672f117ce89dfc1f864a5ed08eR42)

2022-10-08 09:26 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +      following command
[Ошибку исправил тут](https://github.com/nccr-itmo/FEDOT/pull/908/commits/c66e3d2fcf6bbbf4b25191f09174a8e4efc5f445)

2022-10-08 09:26 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/manual_creation.rst
>  -  **Step 2**. Create *Pipeline* instance, create nodes with desired models
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/81d9b4bad094d3ae584e335182885f04b37f85e5)

2022-10-08 09:27 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +      for excluding libraries incompatibility and confusion.
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/f7b4a491586e5c66dbb490942b6e472a52ed0aff#diff-34625e89584c76f3ffc1483c712e6fa9dd905c672f117ce89dfc1f864a5ed08eR22)

2022-10-08 09:27 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/github_installation.rst
> +   -  Then open cmd(Windows) or terminal(Unix like OS), type in:
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/f7b4a491586e5c66dbb490942b6e472a52ed0aff#diff-34625e89584c76f3ffc1483c712e6fa9dd905c672f117ce89dfc1f864a5ed08eR12)

2022-10-08 10:26 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/manual_creation.rst
> +   timeout, preset, metric_names, with_tuning, n_jobs, logging_level = ...
[Done](https://github.com/nccr-itmo/FEDOT/pull/908/commits/ceb8a17ead47ab5446e2613b1d0189d3c735fc1b)

2022-10-08 11:04 UTC, nicl-nno commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   )
Тут кажется большая часть параметров не нужна для manual-сборки.

2022-10-08 11:05 UTC, nicl-nno commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   model.fit(features=dataset_to_train, target=target_col, predefined_model=pipeline)
Можно ещё привести пример с predefined_model='auto', где даже структуру пайплайна не нужно указывать - будет использан дефолтный вариант.

2022-10-08 11:05 UTC, nicl-nno commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   >>> metrics: {'roc_auc': 0.617, 'f1': 0.9205}
А это нормально что числа одинаковы с автоматическим примером?

2022-10-08 11:19 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   >>> metrics: {'roc_auc': 0.617, 'f1': 0.9205}
Нет, просто для примера использовалось, надо поменять, наверное

2022-10-08 11:29 UTC, nicl-nno commented
![image](https://user-images.githubusercontent.com/5711814/194705228-5ccc32fe-3eb5-4cc9-a7ef-f4933665e7f4.png)

Ну и вот на такие страницы стоит добавить немного текстовый пояснений, помимо ссылок. Чтобы было понятно, про что это.

2022-10-08 11:36 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   >>> metrics: {'roc_auc': 0.617, 'f1': 0.9205}
[Теперь лучше](https://github.com/nccr-itmo/FEDOT/pull/908/commits/45cd56c83c2dd739542e94e3ab949869d29fb1b2#diff-f2e0f0f2b79451357b3d7e90ca6d3536f28ce71b2cc444b0a35837310efabf10R53)

2022-10-08 11:37 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   )
[Ага](https://github.com/nccr-itmo/FEDOT/pull/908/commits/45cd56c83c2dd739542e94e3ab949869d29fb1b2#diff-c99f4f47f841a3a9d612ba318ec5175f2f594632d08767965fec938f97525296R19)

2022-10-08 11:39 UTC, nicl-nno commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   )
with_tuning тоже вроде можно убрать? В теории он вполне применим для статичного пайплайна, но сейчас, насколько помню, тюнинг все равно не произойдет.

2022-10-08 11:52 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   model.fit(features=dataset_to_train, target=target_col, predefined_model=pipeline)
[Добавил](https://github.com/nccr-itmo/FEDOT/pull/908/commits/89de1d66abc664b05b36ba26b36bb62fcdf6874c)

2022-10-08 11:53 UTC, IIaKyJIuH commented on docs/source/introduction/tutorial/composing_pipelines/manual_creation.rst
> +   )
Понял, [готово](https://github.com/nccr-itmo/FEDOT/pull/908/commits/94574fc8555b75ec21ef8b267e105143ae0d3d19)

2022-10-08 12:05 UTC, IIaKyJIuH commented
> ![image](https://user-images.githubusercontent.com/5711814/194705228-5ccc32fe-3eb5-4cc9-a7ef-f4933665e7f4.png)
> 
> Ну и вот на такие страницы стоит добавить немного текстовый пояснений, помимо ссылок. Чтобы было понятно, про что это.

Вроде добавил, теперь норм?

2022-10-08 12:08 UTC, nicl-nno approved these changes

2022-10-10 10:06 UTC, YamLyubov approved these changes

2022-10-10 10:35 UTC, merged