Doc params tuning
nccr-itmo/FEDOT pull request #916
Opened 2022-09-29 15:10 UTC by YamLyubov

Documentation for hyperparameters tuning

2022-09-29 15:41 UTC, aPovidlo requested changes

2022-09-29 15:41 UTC, aPovidlo commented on docs/source/advanced/hyperparameters_tuning.rst
> +More information about these approaches can be found
мб указать, что ресурс на русском

2022-09-29 15:41 UTC, aPovidlo commented on docs/source/advanced/hyperparameters_tuning.rst
> +* ``examples/simple/regression/regression_with_tuning.py``
Может обернуть это в ссылки?

2022-09-29 15:44 UTC, DenisSidoren commented on docs/source/advanced/hyperparameters_tuning.rst
> +``TunerBuilder`` methods
пропущен отступ перед подзаголовком

2022-09-29 15:44 UTC, DenisSidoren commented on docs/source/advanced/hyperparameters_tuning.rst
> +-----------
отступ

2022-09-29 22:38 UTC, nicl-nno commented on docs/source/advanced/hyperparameters_tuning.rst
> +More information about these approaches can be found
Лучше дать ссылку на английскую версию.

https://towardsdatascience.com/hyperparameters-tuning-for-machine-learning-model-ensembles-8051782b538b

2022-09-29 22:40 UTC, nicl-nno approved these changes
Выглядит здорово.

Я бы добавил ещё пример как выглядит результат тюнинга (гиперпараметры какой-то модели) и как его посмотреть.

2022-09-29 22:40 UTC, nicl-nno commented on docs/source/advanced/hyperparameters_tuning.rst
> +1. Metric can be chosen from ``ClusteringMetricsEnum``, ``ClassificationMetricsEnum``, ``RegressionMetricsEnum``.
Про ClusteringMetricsEnum лучше убрать - смысл их тюнить мало даже для моделей кластеризации.

2022-09-29 22:42 UTC, nicl-nno commented
Ещё можно напомнить читателю, что при стандартном сценарии тюнинг происходит при использование API. И сказать про флаг with_tuning.

2022-09-30 10:51 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +More information about these approaches can be found
[Заменила](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR10)

2022-09-30 10:52 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +* ``examples/simple/regression/regression_with_tuning.py``
[Ссылки добавила](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR460)

2022-09-30 10:52 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +``TunerBuilder`` methods
[Добавила ](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR33)

2022-09-30 10:53 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +-----------
[Добавила](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR52)

2022-09-30 10:53 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +1. Metric can be chosen from ``ClusteringMetricsEnum``, ``ClassificationMetricsEnum``, ``RegressionMetricsEnum``.
[Убрала](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR109)

2022-09-30 12:08 UTC, DenisSidoren requested changes

2022-09-30 12:08 UTC, DenisSidoren commented on docs/source/advanced/hyperparameters_tuning.rst
> +* `examples/simple/regression/regression_with_tuning.py <https://github.com/nccr-itmo/FEDOT/blob/master/examples/simple/regression/regression_with_tuning.py>`_
быть может более читаемо будет, если вмето пути будет просто словами описано то, на что оставленна ссылка - ``Regression with tuning`` намного приятнее глазу

2022-10-02 19:19 UTC, aPovidlo approved these changes

2022-10-03 11:19 UTC, YamLyubov commented on examples/simple/classification/classification_pipelines.py
>      svc -> logit /
По превью в pycharm выглядит не очень. Тогда наверное стоит в примерах пайплайнов вставить картинки вместо этих схем. Вроде как это можно сделать. 
![image](https://user-images.githubusercontent.com/43475193/193564677-d1eef502-20df-4b1b-a978-67bcd445cca5.png)

2022-10-03 11:21 UTC, YamLyubov commented on docs/source/advanced/hyperparameters_tuning.rst
> +* `examples/simple/regression/regression_with_tuning.py <https://github.com/nccr-itmo/FEDOT/blob/master/examples/simple/regression/regression_with_tuning.py>`_
[Поменяла](https://github.com/nccr-itmo/FEDOT/pull/916/files#diff-b2282da5bf5f8c4e20ef4254f460facbc85efc5f4b9966eeb4dd16117b167d5bR453) на названия

2022-10-04 09:44 UTC, YamLyubov commented on examples/simple/classification/classification_pipelines.py
>      svc -> logit /
Добавила картинки
Можно посмотреть в Examples and notebooks

2022-10-04 10:04 UTC, DenisSidoren approved these changes

2022-10-04 10:05 UTC, merged