GraphNode interface abstraction & Graph refactorings
nccr-itmo/FEDOT pull request #919
Opened 2022-10-04 09:53 UTC by gkirgizov

Changes:
- Graph interface is reduced: auxiliary methods are made out-of-class functions
  This is done to simplify other possible implementations of Graph.
  Moved these functions to new module `dag/graph_utils.py`
- Code duplications are removed (e.g. `distance_to_root_level`, `distance_to_primary_level` and others)
- Introduce `GraphNode` interface that provides `nodes_from`. Rename its only implementation as `DirectedNode`.
- Rename `GraphOperator` as `DirectedGraph`

2022-10-11 14:42 UTC, IIaKyJIuH requested changes

2022-10-11 14:42 UTC, IIaKyJIuH commented on fedot/core/optimisers/adapters.py
> +            if type(node) == LinkedGraphNode:
Лучше тут делать проверку, как и в других местах: `isinstance(node, LinkedGraphNode)`

2022-10-11 14:42 UTC, IIaKyJIuH commented on fedot/core/serializers/coders/graph_node_serialization.py
> +from ...dag.linked_graph_node import LinkedGraphNode
Прикольная тема, вроде и знал, но не видел, чтобы использовалось

2022-10-11 14:42 UTC, IIaKyJIuH commented on fedot/core/serializers/serializer.py
> +    _class_compatibility_mapping: Mapping[str, str] = {
чем тут `Dict[str, str]` не подходит? И короче, и точнее на мой взгляд

2022-10-11 14:42 UTC, IIaKyJIuH commented on test/unit/dag/test_graph_operator.py
> +    assert type(pipeline.operator) is LinkedGraph
`isinstance(pipeline.operator, LinkedGraph`) не подойдёт? Или прям точная проверка нужна?

2022-10-11 14:42 UTC, IIaKyJIuH commented on test/unit/pipelines/test_node.py
> +GraphNode = LinkedGraphNode
Может лучше всё-таки по-честному всё заменить?

2022-10-12 13:47 UTC, YamLyubov approved these changes

2022-10-14 11:28 UTC, gkirgizov commented on fedot/core/optimisers/adapters.py
> +            if type(node) == LinkedGraphNode:
нет, тут намеренно cтрогое типовое равенcтво, а не проверка на подтип -- потому что `Node` являетcя подтипом `LinkedGraphNode`

2022-10-14 11:31 UTC, gkirgizov commented on fedot/core/serializers/serializer.py
> +    _class_compatibility_mapping: Mapping[str, str] = {
Mapping не модифицируемый, это над-тип cловаря. Намек на то, что этот мэппинг неизменяемый в ходе работы фреймворка.

2022-10-14 11:33 UTC, gkirgizov commented on test/unit/dag/test_graph_operator.py
> +    assert type(pipeline.operator) is LinkedGraph
Подойдет, но кмк точная проверка тут очевиднее -- прямо говорит, что ожидаетcя конкретный клаcc.

2022-10-14 11:34 UTC, gkirgizov commented on fedot/core/serializers/coders/graph_node_serialization.py
> +from ...dag.linked_graph_node import LinkedGraphNode
Видно, это Pycharm cам cоптимизировал импорт

2022-10-14 12:45 UTC, IIaKyJIuH commented on fedot/core/optimisers/adapters.py
> +            if type(node) == LinkedGraphNode:
Понял

2022-10-14 12:47 UTC, IIaKyJIuH commented on test/unit/pipelines/test_node.py
> +GraphNode = LinkedGraphNode
Красиво

2022-10-14 12:51 UTC, IIaKyJIuH commented on fedot/core/serializers/serializer.py
> +    _class_compatibility_mapping: Mapping[str, str] = {
Понял, тогда всё логично

2022-10-14 12:56 UTC, IIaKyJIuH requested changes

2022-10-14 12:56 UTC, IIaKyJIuH commented on fedot/core/dag/linked_graph_node.py
> +        params = self.content.get('params')
`self.content.get('name')` не надо использовать по аналогии?

2022-10-17 13:03 UTC, gkirgizov commented on fedot/core/dag/linked_graph_node.py
> +        params = self.content.get('params')
`name` должен быть всегда, потому добавил явное исключение https://github.com/nccr-itmo/FEDOT/pull/919/commits/b4d003bf1a58b2f7b0e27e1f61d8da973c3399ba

2022-10-19 10:00 UTC, merged